### ISSUE TITLE
Missing dependency on React prevents Webpack from importing

### ISSUE THREAD

**Issue by jimmed** [i18next/react-i18next#10]
When using react-i18next in an application bundled with Webpack, the following error is thrown by Webpack's `require` function:

    Cannot find module 'react'

I believe this is due to there being no dependency on React being specified in react-i18next's package.json.

Source: [Question on StackOverflow](http://stackoverflow.com/questions/35368799/react-i18n-redux-and-react-router-configuration)

**Comment by jamuhl** [comment]
nope...gave an answer there...not having react as dependency will not cause this.

**Comment by Grmiade** [comment]
I have the same problem :/

`Uncaught Error: Cannot find module 'react'`

```javascript
ReactDOM.render(
  <I18nextProvider i18n={i18n}>
    <Provider store={store}>
      <Router history={browserHistory}>
        <Route path="/" component={App}>
          <IndexRoute component={Login} />
          <Route path="/home" component={Nav}>
            <Route path="/customers" component={CustomersList}>
              <Route path=":customerId" component={CustomersDetail} />
            </Route>
          </Route>
        </Route>
      </Router>
    </Provider>
  </I18nextProvider>,
  document.querySelector('.react-root')
);
```

**Comment by jamuhl** [comment]
http://stackoverflow.com/questions/35368799/react-i18n-redux-and-react-router-configuration

https://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=false&code=%3Cdiv%20%2F%3E

<div /> ---> React.createElement("div", null);

that's why you need to import react on your module...simple as that.

**Comment by Grmiade** [comment]
I did'nt copy paste all my file. I already import the React module. All works, except when I use I18nextProvider.

**Comment by jamuhl** [comment]
hm...then i'm wondering...can't reproduce. we neither have this in our production applications nor in the example inside this repo...

would be glad if you could further investigate...

**Comment by jamuhl** [comment]
are you using this with meteor? if so i just got a interesting hint from @mjmasn here https://github.com/i18next/i18next/issues/570#issuecomment-186683138

**Comment by Grmiade** [comment]
I found the solution ! My fault :/
I used `import { I18nextProvider } from 'react-i18next';` instead of `import { I18nextProvider } from 'react-i18next/lib';` with my webpack config.

**Comment by jamuhl** [comment]
i see...hm. just thought about changing package.json main to point there...makes live more easy for the ones using a modern build chain - which hopefully are more then building some strange stuff using amd.

**Comment by jamuhl** [comment]
starting with v1.0.0 package.json will point to /lib/index.js
