### ISSUE TITLE
t is returning the key passed in enzyme test

### ISSUE THREAD

**Issue by fawad-khalil-lunchon** [i18next/react-i18next#1000]
**Describe the bug**
The code is working fine with next app but while testing the code with enzyme t returns the same key and does not return the translated value. For example, in out component I am doing `t("common|login")` and it works correctly in next app i-e it returns "Login" but it returns "common|login" in enzyme test.

**Occurs in react-i18next version**
npm module version, git tag or even better the explict commit causing the issue

**To Reproduce**

```
**// lib/i18n.js**
const NextI18Next = require("next-i18next/dist/commonjs");
const loginJson = require("../static/locales/en/common.json");

const i18 = new NextI18Next({
  defaultLanguage: "en",
  otherLanguages: ["ar"],
  detection: {
    order: ["querystring", "cookie", "header"],
    lookupQuerystring: "lang"
  },
  fallbackLng: "en",
  nsSeparator: "|",
  returnObjects: true,
  resources: {
    en: { common: loginJson },
    ar: {}
  }
});

module.exports = i18;

**//login.js**
import HtmlHead from "../components/layout/Head";
import LoginContainer from "../components/common/login";
import { getQueryParamFromPath } from "../utils";
import { withTranslation } from "../lib/i18n";
import { connect } from "react-redux";

const Login = props => (
  <>
    <HtmlHead>
      <title>
        {props.t("common|guestPageTitle", {
          proMealPrice: process.env.PRO_MEAL_PRICE
        })}
      </title>
    </HtmlHead>
    <LoginContainer {...props} />
  </>
);

Login.getInitialProps = async ({ asPath, query }) => {
  let queryParam = getQueryParamFromPath(asPath);
  return {
    queryParam,
    query,
    asPath,
    namespacesRequired: ["login"]
  };
};

const mapStateToProps = state => {
  return {
    configuration: state.configurations
  };
};

export default connect(mapStateToProps)(withTranslation("login")(Login));

**// /components/common/login/index.js**
export default const login = ({ queryParam, query, t }) => {

  return (<p>t(common|login)</p>)
}

**// login.test.js**
it("Should test title of login form", async () => {
    const wrap = mount(
      <Provider store={store}>
        <LoginPage />
      </Provider>
    );
    await wrap.instance().componentDidMount();
    const title = wrap
      .find(".auth-board")
      .find("form")
      .find(".form-head")
      .find("h1");

    expect(title.text()).toBe("Login");

    wrap.unmount();
  });
```

**Expected behaviour**
The test should be passed

**Screenshots**
N/A

**OS (please complete the following information):**
 
- Device: HP Probook core i5
 - Browser: N/A

**Additional context**

**Comment by jamuhl** [comment]
You shall not test translations...one day you will change a text in your JSON breaking your tests and do 🤦‍♂️...

read: https://react.i18next.com/misc/testing for proper mocking away i18n

the issue: render happens before init...why...idk...you add resources on init...might be something next-i18next specific...

**Comment by fawad-khalil-lunchon** [comment]
@jamuhl but it won't make sense if test the value as `expect(title.text()).toBe("common|login");`, would it? The mocking tells to do it like so or mock the configurations in i18next's configuration. I have tried that as well, as in the above code. But that does not works. Am I missing something here?

**Comment by jamuhl** [comment]
test your code not the framework. but if you like your tests to rely on actual translations find out how to wait for i18next.init done using the callback or promise. 

Von meinem iPhone gesendet

**Comment by fawad-khalil-lunchon** [comment]
yes I need to test the translations. I have also done `await wrap.instance().componentDidMount()` and then `wrap.update()`. So everything should be updated and ready. But that does not work as well, unfortunately. @jamuhl

**Comment by jamuhl** [comment]
Well still...not much I can do...you will need to figure this out. All I can say...check if i18next.services.resourceStore.data and lng is set correctly at the moment you render...

**Comment by Rynxiao** [comment]
if you want to test the translations, maybe you can wrap your component with `<I18nextProvider />`  as the [https://react.i18next.com/misc/testing#testing-without-stubbing](https://react.i18next.com/misc/testing#testing-without-stubbing) post, it works for me.

example:

```javascript
   const wrapper = render(
      <I18nextProvider i18n={i18n}>
        <Layout>
          <Child />
        </Layout>
      </I18nextProvider>,
    );
    expect(wrapper.find('header').text()).toBe('Header');
```
