### ISSUE TITLE
Crash when using subkeys as part of a new key

### ISSUE THREAD

**Issue by Vadorequest** [i18next/react-i18next#1001]
**Describe the bug**
```jsx
<p className={'inline'}>{t('solutionsPage.groupBy', 'Trier les résultats par :')}</p>
<button className={'btn-selected inline'}>{t('solutionsPage.groupBy.formation', 'Formation')}</button>
```

This generates 
![image](https://user-images.githubusercontent.com/3807458/69332768-a77e9400-0c57-11ea-963e-a7e041a58cd4.png)

The cause is due to reusing `solutionsPage.groupBy` with `solutionsPage.groupBy.formation`

**Occurs in react-i18next version**
11.0.1

**Expected behaviour**
Should certainly not throw an uncaught exception that crashes the whole app. **The `t` function should be safe to use no matter what's provided to it**, in order to avoid app crash due to one bad translation.

**Comment by jamuhl** [comment]
The exception is correct...there is a big issue in your translation key so having that exception is better than silently ignore it leading to questions why the missing key was not added.

**Comment by jamuhl** [comment]
What we might do is a check for an eventual existing key that collides with the new one...and give an extra warning (to easier find out what was wrong).

**Comment by Vadorequest** [comment]
Well, the error message is very misleading and took me some time to figure out the cause exactly. So, definitely better to improve that.

On the other side, I'd rather not have an exception thrown, it's quite hard to catch, I'd rather go for a comprehensive error message rather than an exception.

If you use keys dynamically, you may not hit this issue in dev/staging and have your whole app break appart in production because of that, I'm really not a fan of this. Error messages would be safer.

**Comment by jamuhl** [comment]
In production you have saveMissing turned off - it's a pure development time issue...will check what we can do in future...but this currently has no priority
