### ISSUE TITLE
Using withTranslation in react-native causes `Error: Inavlid Hook call.`

### ISSUE THREAD

**Issue by LaurentGoderre** [i18next/react-i18next#1004]
Using React 16.9, React Native 0.61 and react-i18next 11.2.1 passing a react native class-basec component to `withTranslation` gives a "Hooks can only be called inside the body of a function component.

**Comment by jamuhl** [comment]
Not sure but usually the cause is a mismatch between react and react-native version and/or having multiple react versions bundled...

**Comment by LaurentGoderre** [comment]
I think you might be right. I was trying to copy a local dependency in which had it's own react

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

If you liked my support / work - I would enjoy a coffee sponsored using the “:purple_heart:Sponsor Button”.

There are many ways to help this project :pray:
