### ISSUE TITLE
How to insert value inside a translation

### ISSUE THREAD

**Issue by KVtofan** [i18next/react-i18next#1007]
# Question about react-i18next
How Can I insert the value inside the translation string (without extra JSX, just insert the value).

As I found in the docs, I need to use Trans component, but Trans component requires the JSX as a child. So, I forced to pass the useless JSX to Trans component.

Example: "the message was sent to {{number}}"
``` javascript
<Trans i18nKey="send-number" number={number}>
         the message was sent to {{number}}
</Trans>

JSON: { "send-number" : "the message was sent to {{number}}" }
```

## Main Question

**Is there a ways to do the same without passing the JSX to the Trans component?**
Something like this: 
```javascript
<Trans i18nKey="send-number" number={number} />
```

**Comment by jamuhl** [comment]
`<div>{t(key, { interpolationVar })}</div>` -> https://www.i18next.com/translation-function/interpolation

--> no need to use Trans if not interpolating components!

or: https://react.i18next.com/latest/trans-component#alternative-usage (values is what you search)

**Comment by KVtofan** [comment]
@jamuhl Than you! Simple `t` function helped.
But in my case, I'm also using <br /> tag inside translation.

Is that possible to use `t` function for translation formatting? (Out of Trans documentation - yes).

**Comment by jamuhl** [comment]
As soon react components are used you will have to use `Trans`

-> or create a markdown component so translations can be in markdown
-> or use `t` with dangerouslyInnerHtml thingy: https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml

**Comment by KVtofan** [comment]
Ok. So I think the section at the top of Trans documentation 'As long you have no react nodes you like to be integrated into a translated text' slightly lies.
https://react.i18next.com/latest/trans-component
I think it should be updated.
Or I'm wrong?

**Comment by KVtofan** [comment]
@jamuhl Let's discuss the proposal above and close the this issue.

**Comment by jamuhl** [comment]
does not lie -> not even slightly...`<br />` in your translation is JSX not html ;) and even if it would be html that would be even worse -> you can't add html to react nodes (or only by surpassing react and dangerously add inner html of a virtual dom node)

**Comment by KVtofan** [comment]
Ok, great. Thanks!
