### ISSUE TITLE
Trans does not parse the values and does not render everything

### ISSUE THREAD

**Issue by PaulRBerg** [i18next/react-i18next#1012]
**Describe the bug**
The states in my Trans component are not parsed and not all text nodes are rendered. It's weird, the first part of the string gets duplicated.

**Occurs in react-i18next version**
react-i18next@10.13.2

**To Reproduce**
I tried to reproduce it on [CodeSandbox](https://codesandbox.io/s/reverent-newton-4vpj2), but I couldn't, so I created this issue out of desperation. I'll be as explicit as possible below.

**Expected behaviour**

See the screenshots below.

**Screenshots**
What I want (captured from CodeSandbox):

<img width="627" alt="Capture d’écran 2019-12-01 à 03 15 59" src="https://user-images.githubusercontent.com/8782666/69907988-f0b5ad00-13e8-11ea-8cf3-1407d8d11729.png">

What I get in my app:

<img width="466" alt="Capture d’écran 2019-12-01 à 03 10 57" src="https://user-images.githubusercontent.com/8782666/69907989-f4493400-13e8-11ea-9bb2-a06ed0c3df85.png">

As you can see, "The payment rate will be" is rendered twice.

**OS:**

- Device: MBP 2016 15"
- Browser: Brave 1.0.1 Chromium: 78.0.3904.108 (Build officiel) (64 bits)

**Additional context**
Here's my Trans component:

```jsx
<Trans
  i18nKey="sidebars.createStream.info"
  amount={state.amount}
  ratePerSecond={ratePerSecond.cash}
  remainder={remainder.cash}
  tokenSymbol={state.token.symbol}
>
  <span className="label">
    The payment rate will be {{ ratePerSecond: ratePerSecond.cash }} {{ tokenSymbol: state.token.symbol }} per
    second. The deposit will be {{ remainder: remainder.cash }} {{ tokenSymbol: state.token.symbol }} less than{" "}
    {{ amount: state.amount }} {{ tokenSymbol: state.token.symbol }}.
  </span>
  <StyledLink href={FAQ_LINK}>Read more about streams here.</StyledLink>
</Trans>
```

What I tried to do:

- Place the text on only one line, in case there was any quirky formatting error
- Remove the StyledLink
- Console.log the amount, ratePerSecond, remainder and tokenSymbol, they all have proper values

I also double-checked that the key-value pairs are correct and they are - there is no warning when I set the value of `sidebars.createStream.info` in my translations file.

**Comment by jamuhl** [comment]
Without a codesandbox for reproduction there is not much I can do here - must be some small difference between your sandbox and production code -> but nothing I see right now. Sorry...
