### ISSUE TITLE
Trans component support for react-native

### ISSUE THREAD

**Issue by tankpower1** [i18next/react-i18next#1013]
Hello, my question is if <Trans> component is supported for react-native or not since when i use it it doesn't work.

Examples: 

<Trans
                        defaults="hello <0>{{what}}</0>"
                        values={{ what: 'world'}}
                        components={[
                            <Text>universe</Text>
                        ]}
                    />

<Trans
                        defaults="hello <0>{{what}}</0>"
                        values={{ what: 'world'}}
                        components={[Text]}
                    />

**Comment by jamuhl** [comment]
What error you get? should work with react-native...but you might have to define a parent component for your case -> as a string is not a valid react-native component...https://react.i18next.com/latest/trans-component#trans-props --> `parent`

**Comment by tankpower1** [comment]
Oh yes, my bad, so i guess this is the correct way to do it?

<Trans
                        defaults="hello <0>{{what}}</0>"
                        values={{what: 'world'}}
                        parent={Text}
                        components={[<Text style={{color: 'red', fontSize: 24}}/>]}
                    />

**Comment by Sarvarr** [comment]
<Text>
<Trans
defaults="hello {{what}}"
values={{ what: 'world'}}
/>
</Text>

**Comment by Sarvarr** [comment]
`<Text>
<Trans
defaults="hello {{what}}"
values={{ what: 'world'}}
/>
</Text>`

**Comment by azuken** [comment]
To avoid TS error with component array :

```js
<Trans
  defaults="hello <bold>{{what}}</bold>"
  values={{what: 'world'}}
  parent={Text}
  components={{bold: <Text style={{fontWeight: 'bold'}}/>}}
/>
```

It would be nice to have a react native specific section in documentation, I've searched for multiple hours how to do bold text with trans component with react native...

**Comment by jamuhl** [comment]
@azuken feel free to improve the documentation with a PR -> hard for us to do so as we do not use it

**Comment by Sargnec** [comment]
This one worked for us. Thanks

> Oh yes, my bad, so i guess this is the correct way to do it?
> 
> <Trans defaults="hello <0>{{what}}</0>" values={{what: 'world'}} parent={Text} components={[<Text style={{color: 'red', fontSize: 24}}/>]} />
