### ISSUE TITLE
Trans component does not rerender once data is loaded

### ISSUE THREAD

**Issue by pcorpet** [i18next/react-i18next#1014]
**Describe the bug**
When loading translations from the backend, the Trans component renders the initial text and does not update its content once the resources have arrived except if the component get re-rendered for another reason.

**Occurs in react-i18next version**
11.2.5

**To Reproduce**

1. Go to https://codesandbox.io/s/dark-tree-hhynr
2. Check the text in the first section it says "Initial value" whereas in the second section it says "Late translation" (you might see for a quick second the "Initial value" text but it's replaced by "Late translation")
3. Click on the button to force a re-render of the App component
4. Now both texts says "Late translation"

**Expected behaviour**
In 2. I would expect the text in the first section to be re-rendered once the translation have arrived, exactly like in the second section.

**Comment by jamuhl** [comment]
The Trans component is not itself bound to such events...use either the `withTranslation` HOC or `useTranslation` hook in your component to trigger such behaviour -> Trans "only" enables the Interpolation of react components into a translation - nothing more....

**Comment by pcorpet** [comment]
Would you consider:
 * documenting that caveat in the doc?
 * or add an option so that it actually gets updated if `t` gets updated?

I can send a PR for either or both if you agree.

**Comment by jamuhl** [comment]
sure PR are always welcome 👍

are you sure Trans does not rerender if you pass different t function as props (wondering...it's a functional component not using memo - so it should rerender on receiving new props)...if not I'm not 100% how to fix this

but fully agree - documentation should mention this...

**Comment by pcorpet** [comment]
It does rerender if you give it a different `t` function, but not if you rely on the main `t`. I'll try and send you some PRs for both cases.

**Comment by rtsanev96** [comment]
I had the same problem, I am using <Trans/> and it does not rerender. However, if I use useTranslation hook, it rerenders;

**Comment by jamuhl** [comment]
@rtsanev96 it's not a problem...it's a documented behavior of the Trans component: https://react.i18next.com/latest/trans-component#important-note
