### ISSUE TITLE
TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by GinnieYang** [i18next/react-i18next#1015]
![187704e0a7d7ec2a499e6811d449c69](https://user-images.githubusercontent.com/29425300/70221475-61f7b600-1783-11ea-9e06-7a64ef399f85.png)
 environment:
"react": "16.3.1",
"react-i18next": "^11.2.5",
"i18next": "^19.0.1",
"i18next-browser-languagedetector": "^4.0.1",
 "i18next-xhr-backend": "^3.2.2",
IN Taro project,I copy react-i18next official websiter‘s  Hooks and Hoc examples,this bowser report error

**Comment by jamuhl** [comment]
https://github.com/i18next/react-i18next#requirements
