### ISSUE TITLE
Unable to load string if component is rendered conditionally with SSR using reacti18next

### ISSUE THREAD

**Issue by piyushkmr** [i18next/react-i18next#1016]
I am trying to use reacti18next with SSR, and everything is working fine for pre-loaded content. But for conditionally loaded modules, the resources are not loading.

This is my i18nconfig, which is being used client side using `xhr-backend`
```typescript
import i18next, { InitOptions } from 'i18next';
import { initReactI18next } from 'react-i18next';
import XHR from 'i18next-xhr-backend';

const availableNS = ['common', 'login', 'userPreferences', 'universityCourseListing'];

export const getBaseI18nConfig = (additionalNS: string[] = []): InitOptions => ({
  lng: 'en',
  fallbackLng: 'en',
  ns: availableNS.concat(additionalNS),
  defaultNS: availableNS[0],
  preload: ['en'],
  load: 'languageOnly', // we only provide en, de -> no region specific locals like en-US, de-DE

  interpolation: {
    escapeValue: false, // react already safes from xss
  },
  react: {
    useSuspense: false,
  },
});

const options: InitOptions = {
  ...getBaseI18nConfig(),
  backend: {
    loadPath: '/static/locales/{{lng}}/{{ns}}.json',
    addPath: '/static/locales/add/{{lng}}/{{ns}}',
  },
};

if (process && !process.release) {
  i18next
    .use(XHR)
    .use(initReactI18next);
}

// initialize if not already initialized
export let i18nPromise: Promise<any>;
if (!i18next.isInitialized) {
  i18nPromise = i18next.init(options);
}
export default i18next;
```

SSR side config looks like this:
```typescript
export const initiatei18nSSR = (server?: Express, additionalNS: string[] = []) => {
  return i18n
    .use(Backend)
    .init({
      ...getBaseI18nConfig(additionalNS),
      backend: {
        loadPath: `${__dirname}/public/locales/{{lng}}/{{ns}}.json`,
        addPath: `${__dirname}/public/locales/{{lng}}/{{ns}}.missing.json`,
      },
    },
    ).then(() => {
      if (server) {
        server.use(
          i18nmiddleware.handle(i18n, {
            removeLngFromUrl: false,
          }),
        );
      }
    });
};
```

And then I am initiating server using:
```typescript
initiatei18nSSR(app).then((_res: any) => {
  // initiate express server
});
```

And in my react app, I am using `useSSR(initialI18nStore, initialLanguage)`
```typescript
const BaseApp = () => {
  const { initialI18nStore, initialLanguage } = window as any;
  useSSR(initialI18nStore, initialLanguage);
  removeSSRStyles();
  return (
    <BrowserRouter>
      <App />
    </BrowserRouter>
  );
};

i18nPromise.then(() => {
  hydrate(
    <BaseApp />,
    document.getElementById('app'),
  );
});
```

to get `initiali18nstore` and `initialLanguage`, I am getting them from express i18n middleware by using:
```typescript
export const getInitialProps = (req) => {
  const reqi18n = req.i18n;
  const initialI18nStore: any = {};
  reqi18n.languages.forEach((l: string) => {
    initialI18nStore[l] = reqi18n.services.resourceStore.data[l];
  });
  const initialLanguage = reqi18n.language;

  return { initialI18nStore, initialLanguage };
};
```

Now SSR html is rendering fine, but when I am loading a component on user click, this "NEW"ly loaded component isn't able to load these strings.

Also note that, my `window.initiali18nstore` doesn't contains string that this "NEW" component is using (which makes sense since this part is not being rendered on SSR, so reacti18n will not have idea what strings are being used), but they are being fetched in json file when `xhr-backend` is calling the resource from static url.

**Comment by jamuhl** [comment]
a) find out if the client load that newly needed translations -> set init option debug:true and check console.log if you see backend logs loading that namespace successfully

b) check if you get missings on the new page -> you're rendering the client page before loading is done -> turn on Suspense or use ready flag: https://react.i18next.com/latest/usetranslation-hook#not-using-suspense

JUST turning suspense off does not mean some other magic takes care of suspending rendering ---> means it's now your job by eg. `if (!ready) return 'loading';`

**Comment by piyushkmr** [comment]
Ok, feeling dumb to post this. The error was happening due to a typo. And thanks @jamuhl , debug flag helped. I was using `.` as namespace separator at one single intance, and debug option helped me spot that issue.

Things are working fine. Thanks for your support.

**Comment by jamuhl** [comment]
@piyushkmr glad you found the typo...👍
