### ISSUE TITLE
After languageChanged, plural translation stay in singular

### ISSUE THREAD

**Issue by peacepostman** [i18next/react-i18next#1017]
Hello,

Maybe i've done something wrong but ic cant figure out why this is not working. I am starting my app in 'fr' and it is quickly changed to 'pt-BR', all the translations are in Portuguese but all the plural translations stay in singular.

**Occurs in react-i18next version**
```
"react": "^16.8.6",
"i18next": "^19.0.1",
"i18next-xhr-backend": "^3.2.2",
"react-i18next": "^11.2.5",
```

**To Reproduce**
Boot in a language, then change it after init, new transkations are properly loaded but the plural one, stay in singular

**Comment by peacepostman** [comment]
After basic, test it seems that Brazilian Portuguese is not working with plural :/

Anyone ever faced this situation ?

**Comment by peacepostman** [comment]
Well, problem auto solved, the file i was calling was named *pt-BR*, renaming it to *pt* fix the problem..

**Comment by adrai** [comment]
Can you create an example? i.e. in codesandbox
