### ISSUE TITLE
Many test

### ISSUE THREAD

**Issue by malre** [i18next/react-i18next#1018]
hey.
I would like a solved for this Line 12:16:  'i18n' is assigned a value but never used .
I see doc and open sample but any test is nice .
For exemple. 
Translation :
Title:bienvenue
<h1>{t('title')}</h1
My page give title why ?

**Comment by jamuhl** [comment]
what you like? 

> I would like a solved for this Line 12:16: 'i18n' is assigned a value but never used .

is eslint (or something similar) complaining about something you should easily be able to fix....

this is react-i18next so tests cover what is unique to react! all other tests are here: https://github.com/i18next/i18next/tree/master/test

**Comment by malre** [comment]
Ok thx , i try with this links https://codesandbox.io/s/1zxox032q
->/node_modules/react-i18next/dist/es/Interpolate.js
Attempted import error: 'deprecated' is not exported from './utils'.

**Comment by malre** [comment]
Bien, i have to move my @pp to another folder and i have this message.
Attempted import error: 'initReactI18next' is not exported from 'react-i18next'.

**Comment by malre** [comment]
if this for spoken this very sad,
ok nos i have to delete import and use,
-> Attempted import error: 'useTranslation' is not exported from 'react-i18next'.

**Comment by malre** [comment]
Ok i have a version with any import🦷👌😁🤷‍♀️

**Comment by malre** [comment]
Ok i Don't understand later, before, after ok . Have nice

**Comment by malre** [comment]
Thanks i change folder it's great but i have a problem with array or function map impossible to find how. I est with trans , nothing. Ok for links.....🎅🎅🎅👀✨✨🙌

**Comment by jamuhl** [comment]
can you just add a little...little more information...like some sample code...it's so hard to understand you
