### ISSUE TITLE
how to change color into translation

### ISSUE THREAD

**Issue by kolosovvs** [i18next/react-i18next#1022]
# Question about react-i18next

Questions should be posted on StackOverflow

hello
there is a sample into my react component
```
{t('payout', { amount: this.props.amount})}
```
and  translation
```
{
  "payout": "payment was transferred.<br />{{amount}} rubles.",
}
```
how to make an amount a different color?
I tryed this
```
{
	"payout": "payment was transferred.<br /><span style='color: red'>{{amount}} </span> rubles.",
}
```
Unfortunately, it doesn't work.
thanks in advance

**Comment by jamuhl** [comment]
read: https://react.i18next.com/latest/trans-component

**Comment by kolosovvs** [comment]
> read: https://react.i18next.com/latest/trans-component
I tryed this
<Trans i18nKey="multiline" >
              {t('payout', { amount: this.props.amount})}
</Trans> but it doesn't work too
could you give some  example of code

**Comment by jamuhl** [comment]
```js
<Trans i18nKey="multiline">payment was transferred.<br /><span style='color: red'>{{amount: amountValue}}</span> rubles.</Trans>

// with translation:
// "multiline": "payment was transferred.<1 /><2 style='color: red'>{{amount}}</2> rubles."
```

**Comment by kolosovvs** [comment]
@jamuhl thank you
