### ISSUE TITLE
Question about insterting br equivalent of react-native in trans component

### ISSUE THREAD

**Issue by tankpower1** [i18next/react-i18next#1023]
Hello i need to insert a <br/> equivalent tag in react-native, how can i achieve this?
I've tried doing {'\n'} and Text{'\n'}/Text on a <0/> placeholder but it doesn't seem to work?

**Comment by jamuhl** [comment]
https://react.i18next.com/latest/trans-component and do not forget to set prop parent

**Comment by tankpower1** [comment]
I still can't seem to find a solution for the issue.
Heres an example:

<Trans
defaults="Hello <br/> world?"
parent={Text}
/>

In react-native i can't read a <br/> and i can't seem to see a solution in the documentation?

I've tried this but it also doesn't work:

<Trans
defaults="hello <0/> world."
parent={Text}
components={[<Text>{'\n'}</Text>]}
/>

**Comment by adrai** [comment]
```jsx
<Trans i18nKey="myKey">
  Hello <br/> world.
</Trans>
```

in your resources json:
```json
"myKey": "Hello <1/> world.",
```

Here in the docs: https://react.i18next.com/latest/trans-component#using-for-less-than-br-greater-than-and-other-simple-html-elements-in-translations-v-10-4-0

**Comment by tankpower1** [comment]
Why doesn't this work for react-native. Native can't read a br tag or am i missing something?

`<Trans
                                    i18nKey="key"
                                    defaults="Test <0/> test"
                                    parent={Text}
                                    components={[<Text>{'\n'}</Text>]}
                                />`

**Comment by jamuhl** [comment]
do you see `\n` as text in the Text element?

Try setting escape to false in that case like shown here: https://github.com/i18next/react-i18next/blob/master/example/react/src/i18n.js#L21

**Comment by tankpower1** [comment]
I don't see `\n` in the text and i have escaping set to false.

**Comment by jamuhl** [comment]
Ah sorry, know I see - that's not like it works 

`<Trans i18nKey="key" defaults="Test <0/> test"` -> you try to interpolate content from a component into the translations but it is

interpolating content of the translation into the component
`<Trans i18nKey="key" defaults="Test <0>\n</0> test"` -> <0> will be replaced with the component passed in - and the child of that element will be replaced with the translation given (part inside <0></0>)

Hope that is understandable...?

But you can:

`<Trans i18nKey="key" defaults="Test {{newline}} test" parent={Text} values={{ newline: `\n` }} />`

**Comment by tankpower1** [comment]
Yes i understood perfectly! Thanks for the quick answer.

I understand that i can interpolate it with a parameter but i needed it with a placeholder <0/> etc. Thanks anyway!

**Comment by jamuhl** [comment]
`<0/>` only works with empty (not having a child) component, eg. 

```js
const MyComp = () => { return <Text>{'\n'}</Text>};

<Trans i18nKey="key" defaults="Test <0/> test" parent={Text} components={[<MyComp></MyComp]} />
```

might work

**Comment by tankpower1** [comment]
Yea that worked!
