### ISSUE TITLE
Issue when packing with webpack, says that multiple instance of react is present

### ISSUE THREAD

**Issue by rollinmendez000** [i18next/react-i18next#1025]
**Describe the bug**

**Occurs in react-i18next version**
npm module version, git tag or even better the explict commit causing the issue

**To Reproduce**

**Expected behaviour**

**Screenshots**
If applicable, add screenshots or a GIF to help explain your problem.

**OS (please complete the following information):**

- Device: [e.g. MBP 2018 13"]
- Browser: [e.g. Chrome 70.0.3538.77]

**Additional context**

**Comment by jamuhl** [comment]
https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react

https://github.com/facebook/react/issues/13991
