### ISSUE TITLE
Cannot implement react-i18next with Fetch backend using the useTranslation hook

### ISSUE THREAD

**Issue by mgmodell** [i18next/react-i18next#1026]
**Describe the bug**
I am trying to implement i18next in my react component with the Fetch backend and using the useTranslation hook, but it keeps saying:

> Uncaught Error: Test suspended while rendering, but no fallback UI was specified.
> 
> Add a <Suspense fallback=...> component higher in the tree to provide a loading indicator or placeholder to display.

As you can see in the code below, I have loaded `Suspense` (as high up the chain as I know how) and it still throws an error. How can I add the <Suspense> any higher than what I've got? What am I doing wrong? How do I fix this? It seems to work OK when I use the <Translation> component. Naturally, it also seems to work OK if I turn Suspense off and try to handle it myself, but that sort of defeats the purpose, I think. How can I make this actually work? Do I have the Fetch backend misconfigured?

**Occurs in react-i18next version**

- i18next: 19.0.0
- i18next-browser-languagedetector: 4.0.1
- i18next-fetch-backend: 2.1.0

**To Reproduce**
I am loading the following .js files:
*** Test.js***
```
import React, { Suspense, useState, useEffect, lazy } from "react";
import PropTypes from "prop-types";

import i18n from './i18n';
import { useTranslation } from 'react-i18next';

export default function Test( props ){
  const { t, i18n } = useTranslation( 'bingo_game' );

    return (
    <Suspense fallback={<div>Loading...</div>}>
      <div>
        Pant leg
      </div>
    </Suspense>
    )
}

Test.propTypes = {
  token: PropTypes.string.isRequired,
};
```
and
***i18n.js***
```
import i18n from "i18next";
import LngDetector from "i18next-browser-languagedetector";
import { initReactI18next } from "react-i18next";

import Fetch from "i18next-fetch-backend";

  i18n
    .use(LngDetector) //language detector
    .use(Fetch)
    .use(initReactI18next)
    .init({
      backend: {
        loadPath: "/infra/locales/{{ns}}.json",
        // path to post missing resources
        addPath: "locales/add/{{ns}}",
        // define how to stringify the data when adding missing resources
        stringify: JSON.stringify
      },
      defaultNS: "base",
      fallbackLng: "en",
      debug: true,
      initImmediate: false
    });

export default i18n;
```

**Expected behaviour**
The component should load with no errors and present a `div` with the text

> pant leg

**OS (please complete the following information):**

- Device: [MBP 2018 13"]
- Browser: [Chrome 79.0.3945.79]

**Additional context**
This component is embedded in a rails app using webpacker and it's pulling the translation resources from a URL which seems to work, but when debug is on, I see:

> i18next::backendConnector: loading namespace translation for language en failed failed parsing /infra/locales/translation.json to json

I've posted this on [SO](https://stackoverflow.com/questions/59464880/how-to-fix-no-fallback-ui-was-specified-in-react-i18next-using-hooks) already.

**Comment by jamuhl** [comment]
> I have loaded Suspense (as high up the chain as I know how) and it still throws an error.

That's not high enough...the Suspense Component must be outside of the component triggering a Suspense:

```js
function TestInner( props ){
  const { t, i18n } = useTranslation( 'bingo_game' );

    return (
      <div>
        Pant leg
      </div>
    )
}

export default function Test( props ){
    return (
    <Suspense fallback={<div>Loading...</div>}>
      <TestInner {...props} />
    </Suspense>
    )
}
```

**Comment by mgmodell** [comment]
Thanks for the quick response. So, does this mean that I need to wrap the entire thing in a Suspense? That means that I need to create a wrapper component just to contain this? Is there no way to avoid that?I'll give that a try.

**Comment by mgmodell** [comment]
OK. That seems to have done it. I guess most people are looking more at comprehensive SPAs than adding specialized components on a page of existing content. It makes sense - almost like a try/catch sort of setup, I guess, but I'd expected it to function differently based upon the docs. I wish it could be more self-contained and the error message could be clearer - perhaps explicitly saying that the component should be wrapped in another component that holds the Suspense?

**Comment by jamuhl** [comment]
`Suspense` comes from react...and yes...it's internals is throwing a Promise (throw -> trigger fallback UI, resolve -> back to render). So bubbling up the Suspense enables a rather flexible way of catching such "not yet loaded" cases.

**Comment by mgmodell** [comment]
Thanks. I'm only just starting to play with Suspense. I appreciate that i18next is supporting it, but there's a bunch of learning left to be done, it seems...
