### ISSUE TITLE
Example with Markdown

### ISSUE THREAD

**Issue by steventilator** [i18next/react-i18next#1027]
I have seen a couple of issues with mentions of using Markdown to translate multiline strings with formatting. Sadly, I haven't found an example. Can someone help me how to actually use Markdown with react-i18next?

Specifically, I am struggling with turning my (untranslated) template string into a string that works in a JSON file. So, for example, right now I have this code which renders nicely:

```
<Markdown>
{`
  **Title**
  
  Some text. In my real world case, there is a lot of text.
  
    - List item
    - List item
    - List item
`}
</Markdown>
```

Is there a way I can turn this template string into a JSON string that allows for translating while keeping the formatting?

**Comment by jamuhl** [comment]
Not sure but you pass a translation to markdown - so there won't be any template string...eg.:

`<Markdown source={t('yourKeyWithValueInMarkdown')}  />`

**Comment by steventilator** [comment]
Thank you, but this is not the part I am confused about.

What I don't know is how I can turn the multiline template string with linebreaks and tabs into a one-liner that I can use in a JSON file? How can I keep linebreaks, headings, lists so that it doesn't just render as one long paragraph? 

```
{
   "yourKeyWithValueInMarkdown": "**Title** (linebreak – How do I do this?) Some text. In my real world case, there is a lot of text. (linebreak) - List item (How do I do this?) - List item - List item"
}
```

**Comment by adrai** [comment]
\n in string or maybe this: https://www.i18next.com/translation-function/objects-and-arrays
