### ISSUE TITLE
Add WithRef interface for withTranslation HOC with { withRef: true }

### ISSUE THREAD

**Issue by Ajmdag** [i18next/react-i18next#1029]
**Is your feature request related to a problem? Please describe.**
When I use `withTranslation` HOC with `{ withRef: true }` I can't extend my component props interface in TypeScript with something like `WithRef` exported from `react-i18next`. 

**Describe the solution you'd like**
I'd like to have an interface exported from library to extend my component props with `ref` (just like with `t` function described in `WithTranslation` interface)

**Describe alternatives you've considered**
or should I describe ref myself in my component interface?

**Additional context**
—

**Comment by rosskevin** [comment]
@Ajmdag please PR the change you would like to see and add a usage test to `test/typescript`.

**Comment by denu5** [comment]
Do I see it right that this is still open? could think of looking into it then.

**Comment by jamuhl** [comment]
@denu5 would be awesome
