### ISSUE TITLE
How to get translations before useState?

### ISSUE THREAD

**Issue by antoniogarcez** [i18next/react-i18next#1033]
**Describe the bug**
I can not get the translation for my key. Instead of showing the translation, it is showing the key because .json file was not loaded yet. Is it any way to get translations before call `useState`?

**Occurs in react-i18next version**
"react": "^16.12.0",
"react-i18next": "^11.2.5",
"typescript": "3.7.3"

**Expected behaviour**
It is supposed to get the correct translation. 

**OS (please complete the following information):**

- Device: HP ProBook 450 G4 - Windows 10
- Browser: Chrome 79.0.3945.88

**Additional context**
This is my code:
```ts
import { withTranslation } from 'react-i18next';

function Inventory({ t }) {
    const  [productCode, setProductCode] = useState<InputConfig>({
            className: 'famo-input famo-text-10',
            isDisabled: true,
            isNumber: false,
            label: t('key_87'),
            name: 'productCode',
            value: ''
        }),
}
```

**Comment by jamuhl** [comment]
using `withTranslation` at least if not disabling Suspense asserts translations were loaded (or at least tried to load them)

set `debug: true` on i18next.init to see if something went wrong loading the translations and make sure you either use Suspense or evaluate the ready state: https://react.i18next.com/latest/withtranslation-hoc#not-using-suspense

**Comment by antoniogarcez** [comment]
Ok, I am disabling `useSuspense` so probably it is the reason for my mistake, I need to test tomorrow. Thanks!

**Comment by antoniogarcez** [comment]
Hi,

I disabled `useSuspense` and it worked :)
Thanks a lot!
