### ISSUE TITLE
Character ' becomes &#39; 

### ISSUE THREAD

**Issue by rishabh876** [i18next/react-i18next#1038]
**Describe the bug**
I have a placeholder in my string. When I pass the value for this placeholder with `'` character. The character in output string becomes `&#39;`.

**Occurs in react-i18next version**
v11.2.7

**To Reproduce**
```
const { t } = useTranslation();
t('hello', { name: props.name.split(' ')[0] })} 
```
// this returns `Hello O'Brien`

**en.json** 
{"hello" : "Hello {{name}}"}

**Expected behaviour**
The return value should keep the character as is. 

**OS:**
Android 10

- Device: OnePlus 6

**Comment by jamuhl** [comment]
https://www.i18next.com/translation-function/interpolation#unescape

or do it globally for all like: https://github.com/i18next/react-i18next/blob/master/example/locize/src/i18n.js#L48

**Comment by rishabh876** [comment]
@jamuhl Thanks for the solution. 
One more thing, this says 
> // not needed for react as it escapes by default

So this shouldn't be needed in my case. Isn't it?

**Comment by jamuhl** [comment]
react does escaping string content inside react elements already -> leading to double escaping if i18next escapes it too (i18next is used outside of react too -> therefore, has that safety net). So yes you can turn that off like in the sample.
