### ISSUE TITLE
What's the recommended way to translate static content (stored as a constant)

### ISSUE THREAD

**Issue by Vadorequest** [i18next/react-i18next#1039]
I have the following untranslated file:

```jsx
// constants.js
export const TOTAL_DURATION_IS_TOO_HIGH = `<b>Oops.</b>`;


// somewhereElse.js
() => {
  ...
  const recommendation = TOTAL_DURATION_IS_TOO_HIGH;
  ...
}
```

I don't have access to `t` or `Trans` in `constants.js`, it's kind of "static". 

What's the recommended way to deal with this kind of content? I see several ways (wrapping them into a function that use hooks, mostly), but I wonder what would be your official recommandation on this.

**Comment by jamuhl** [comment]
recommendation...don't do it ;)

set the const to hold a key -> take value based on that key during rendering...

if using it inside some non rendering code -> import `i18n` and use the `t` function on it:  https://www.i18next.com/translation-function/essentials#essentials

**Comment by Vadorequest** [comment]
Yeah, I thought about that as well, thank you for the quick feedback!
