### ISSUE TITLE
How to handle html special chars with the "t" function?

### ISSUE THREAD

**Issue by Vadorequest** [i18next/react-i18next#1041]
The following:

`{t('simulatorResultsFeedback.borrowerSignUpBlock.heading', `Ce prêt vous convient&nbsp;?`)}`

Will render `Ce prêt vous convient&nbsp;?` because html special chars are escaped, even when using 

```
interpolation: {
      escapeValue: false, // not needed for react as it escapes by default
    },
```

So, how are we supposed to have special chars when using the `t` function?

Using the `Trans` component deals with that, but sometimes I need non-breaking spaces with `t`.

**Comment by jamuhl** [comment]
react is doing escaping...not i18next: https://jsfiddle.net/hq7avfud/

**Comment by jamuhl** [comment]
i18next if not setting it to false only escapes interpolated value as those could potentially be user created and contain xss scripts

**Comment by Vadorequest** [comment]
Alright. I guess the way to go is to use `dangerouslySetInnerHTML` then

**Comment by kostia1st** [comment]
>rather `\u00a0` instead of `&nbsp;`

This is the way to go, thank you
