### ISSUE TITLE
Question about using i18n outside of a component.

### ISSUE THREAD

**Issue by tankpower1** [i18next/react-i18next#1042]
Hello i would like to ask how can i use the i18n instance for example in a constants.js file?

Heres my code:

i18n.js

`import i18n from "i18next";
import i18backend from 'i18next-xhr-backend';
import {initReactI18next} from "react-i18next";

i18n
    .use(i18backend)
    .use(initReactI18next)
    .init({
        lng: en,
        fallbackLng: en,
        resources: {},     
        interpolation: {
            escapeValue: false
        }
    });

export default i18n;`

constants.js

`export const TEXT = 'myText';`

When importing the instance of i18n in constants.js it says it's undefined.

**Comment by jamuhl** [comment]
Sure you can import the i18next instance...

```js
import i18n from '.i18n';

export const TEXT = i18n.t('textKey');
```

But those constants never will be updated on languageChange! So either:

- update them to new language value based on event triggered by i18next: https://www.i18next.com/overview/api#onlanguagechanged
- or better have only the keys in the constants and translate as close to the rendering as possible
