### ISSUE TITLE
Missing Key/Namespace

### ISSUE THREAD

**Issue by JamesIves** [i18next/react-i18next#1046]
I'm switching between using `Locize` for my backend when running locally, and then syncing the data back into my local client using `locize-cli` and using the XHR backend to toggle between the `.json` files that were created. This creates a file structure that looks like this:

`/assets/locales/en-US/CurrentAutomobile.json`

This workflow allows my copy editor to make changes locally using Locize, and then check in their work so our other environments can read them exclusively from the file system. The XHR back-end config looks something like this:

```javascript
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';
import XHR from 'i18next-xhr-backend';
import Backend from 'i18next-locize-backend';
import LastUsed from 'locize-lastused';
import Editor from 'locize-editor';
import config from '../../util/config';

i18n
  .use(XHR)
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    fallbackLng: 'en-US',
    debug: true,
    saveMissing: false,
    keySeparator: ':',
    resources: {},
    backend: {
      // for all available options read the backend's repository readme file
      loadPath: '/assets/locales/{{lng}}/{{ns}}.json'
    },
});
```

The problem I'm having is that I keep getting an error saying a key is missing: `i18next::translator: missingKey en-US CurrentAutomobile ownerCardTitle ownerCardTitle`

Inside `CurrentAutomobile.json` I have the `ownerCardTitle` key however. 

```json
{
    "ownerCardTitle": "This car belongs to whom?"
}
```

Where am I going wrong here? I can access `localhost/assets/locales/en-US/CurrentAutomobile.json` just fine and it loads. I'm using the `withTranslation` hoc and setting the namespace correctly, and calling `t('CurrentAutomobile:ownerCardTitle')`.

Any help would be appreciated!

**Comment by jamuhl** [comment]
remove that `resources: {}` from the init options -> passing that in sets i18next to take translations from resources object and omitting the backend for loading...

**Comment by JamesIves** [comment]
Turns out Webpack was throwing an error when it tried to access the .json file, fixing that and removing the resources key solved the issue in the end. Thanks!

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

If you liked my support / work - I would enjoy a coffee sponsored using the “:purple_heart:Sponsor Button”.

There are many ways to help this project :pray:
