### ISSUE TITLE
Missing defaultNS prop in I18nextProviderProps

### ISSUE THREAD

**Issue by jpgarcia** [i18next/react-i18next#1049]
**Describe the bug**
The definition file `src/index.d.ts` seems to be outdated

**Occurs in react-i18next version**
**11.3.1**

**To Reproduce**

1. Create a new dummy `.tsx` file with vscode
2. Include a snippet like this one:
```ts
import { I18nextProvider, withTranslation } from 'react-i18next'

<I18nextProvider i18n={i18n} defaultNS={screenId}>
</I18nextProvider>
```

**Expected behaviour**
`defaultNS` should not show the error

**Screenshots**
If applicable, add screenshots or a GIF to help explain your problem.
![image](https://user-images.githubusercontent.com/95109/74093938-c999ec80-4ab7-11ea-82ad-73a8136b7a58.png)

**OS (please complete the following information):**

- Device: N/A
- Browser: N/A

**Comment by jamuhl** [comment]
Feel free to provide a PR adding this. Also, please add a test case for future regression: https://github.com/i18next/react-i18next/blob/master/test/typescript/I18nextProvider.test.tsx

Afterwards ping @rosskevin for a short review and merging back into master...

Thank you...

**Comment by jpgarcia** [comment]
Thank you for the quick response. I just created a new PR https://github.com/i18next/react-i18next/pull/1050
