### ISSUE TITLE
Keep language preference between page refreshes

### ISSUE THREAD

**Issue by dougsouza** [i18next/react-i18next#1052]
That seems a very basic issue, but I couldn't find the answer anywhere.

After I change the language using:
```javascript
i18n.changeLanguage(lng);
```
Everything updates as expected. But if I refresh the page it goes back to default language. How do I keep language preferences between page refreshes?

Thanks

**Comment by dougsouza** [comment]
Solved by removing `lng` in `init()`.

**Comment by ragheedaloudeh** [comment]
if i remove lng in init() then how can i set a default language

**Comment by dougsouza** [comment]
@ragheedaloudeh, I reopened the issue. Hope someone can help with this.

Cheers!

**Comment by adrai** [comment]
Use https://github.com/i18next/i18next-browser-languageDetector and make sure you define the appropriate cache option.

**Comment by ragheedaloudeh** [comment]
i fix the problem 
before
lng: 'ar'
and thats back to defualt language when reload the page
after
lng: localStorage. getItem(key) || 'ar'
thats will go to default language after first load when there's no localStorage and when reload if there's a localStorage it will remember the choices

**Comment by AhsanNissar** [comment]
Hi, I have removed the lng option too from init but still on page reload the language is not loaded. Before page reload everything works fine and I am also able to switch language via i18.changeLanguage but after page reload the language does not get loaded and I only see the  properties that I set in json file and not their values.

**Comment by claudiahleung** [comment]
> Use https://github.com/i18next/i18next-browser-languageDetector and make sure you define the appropriate cache option. And remove the lng option on init.

does this go in the i18n config file, and how is this used? i'd like to indicate a default language on my site (hence why i need to keep fallbackLng in my init), but in case the other language is chosen, that the page reloads in that language and not the default language.

**Comment by adrai** [comment]
@claudiahleung like here: https://github.com/i18next/react-i18next/blob/master/example/react/src/i18n.js

**Comment by claudiahleung** [comment]
got it, thanks! i was looking [here](https://github.com/i18next/i18next-browser-languageDetector) but have no idea what  `.init(i18nextOptions)` does? where is it defined?

**Comment by adrai** [comment]
@claudiahleung https://www.i18next.com/overview/api

**Comment by NOURELsayed** [comment]
Hello dears,
i have the same issue and I removed lng in init(). but nothing happened!
are there any other ideas?

**Comment by claudiahleung** [comment]
maybe use `fallbackLng` instead? this is my i18n `config.js` for reference

`
import i18next from ‘i18next’
import LanguageDetector from ‘i18next-browser-languagedetector’

i18next.use(LanguageDetector).init({
	fallbackLng: ‘en’, // my default lang is traditional chinese, but it is defined below so the page doesn't default to en
	resources: {
		‘zh-Hant’: { // iso code for trad chinese
			translations: require(‘../translations/zh/common.json’)
		},
		en: {
			translations: require(‘../translations/en/common.json’)
		}
	},
	ns: [‘translations’], // this is a directory
	defaultNS: ‘translations’,
	returnObjects: true,
	debug: process.env.NODE_ENV === ‘development’,
	interpolation: {
		escapeValue: false, 
	},
	react: {
		wait: true,
	},
})

i18next.languages = [‘zh-Hant’, ‘en’]

export default i18next
```

**Comment by NOURELsayed** [comment]
i am already using fallback 
` .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    // we init with resources
    resources: {
      en,
      ar,
    },
    fallbackLng: 'ar',
    // lng: defaultLanguage,

    debug: true,

    // have a common namespace used around the full app
    ns: ["translations"],
    defaultNS: "translations",

    keySeparator: false, // we use content as keys

    interpolation: {
      escapeValue: false,
    },
  });
`

**Comment by adrai** [comment]
@NOURELsayed create a reproducible example and open a new issue

**Comment by rossman-x** [comment]
You have to use LanguageDetector library of i18next-browser-languagedetector, then configure your i18 this way:

```
const resources = {
    en: enTranslation,
    fr: frTranslation,
};

const DETECTION_OPTIONS = {
    order: ['localStorage', 'navigator'],
    caches: ['localStorage']
};

i18next
    .use(LanguageDetector)
    .use(initReactI18next)
    .init({
        resources,
        detection: DETECTION_OPTIONS,
        fallbackLng: 'fr',
        interpolation: {
            escapeValue: false,
        },
    });
export default i18next;
```

**Comment by adasanta29** [comment]
Tried going through this for my react website and nothing seemed to work, does anyone mind helping me out?

`import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

import Backend from 'i18next-http-backend';
import LanguageDetector from 'i18next-browser-languagedetector';

import { TRANSLATIONS_ZH } from "./zh/translations";
import { TRANSLATIONS_EN } from "./en/translations";

i18n
  // load translation using http -> see /public/locales (i.e. https://github.com/i18next/react-i18next/tree/master/example/react/public/locales)
  // learn more: https://github.com/i18next/i18next-http-backend
  // want your translations to be loaded from a professional CDN? => https://github.com/locize/react-tutorial#step-2---use-the-locize-cdn
  .use(Backend)
  // detect user language
  // learn more: https://github.com/i18next/i18next-browser-languageDetector
  .use(LanguageDetector)
  // pass the i18n instance to react-i18next.
  .use(initReactI18next)
  // init i18next
  // for all options read: https://www.i18next.com/overview/configuration-options
  .init({
    fallbackLng: 'en',
    debug: true,
    resources: {
      en: {
        translation: TRANSLATIONS_EN
      },
      zh: {
        translation: TRANSLATIONS_ZH
      }
    }
  });

  i18n.changeLanguage("en");


export default i18n;`

**Comment by adasanta29** [comment]
tried going through this thread but nothing seemed to work for me, does anyone mind helping me out?

`import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

import Backend from 'i18next-http-backend';
import LanguageDetector from 'i18next-browser-languagedetector';

import { TRANSLATIONS_ZH } from "./zh/translations";
import { TRANSLATIONS_EN } from "./en/translations";

i18n
  // load translation using http -> see /public/locales (i.e. https://github.com/i18next/react-i18next/tree/master/example/react/public/locales)
  // learn more: https://github.com/i18next/i18next-http-backend
  // want your translations to be loaded from a professional CDN? => https://github.com/locize/react-tutorial#step-2---use-the-locize-cdn
  .use(Backend)
  // detect user language
  // learn more: https://github.com/i18next/i18next-browser-languageDetector
  .use(LanguageDetector)
  // pass the i18n instance to react-i18next.
  .use(initReactI18next)
  // init i18next
  // for all options read: https://www.i18next.com/overview/configuration-options
  .init({
    fallbackLng: 'en',
    debug: true,
    resources: {
      en: {
        translation: TRANSLATIONS_EN
      },
      zh: {
        translation: TRANSLATIONS_ZH
      }
    }
  });

  i18n.changeLanguage("en");


export default i18n;`

**Comment by jamuhl** [comment]
@adasanta29 you're calling `i18n.changeLanguage("en");` and set language to english -> let https://github.com/i18next/i18next-browser-languageDetector do it's work

**Comment by adasanta29** [comment]
so should I removed `i18n.changeLanguage("en");` thats it?

**Comment by jamuhl** [comment]
@adasanta29 as that always sets the locale used to english....might be worth removing and than check if it works or not....only you can test that ;)

**Comment by adasanta29** [comment]
@jamuhl it worked thank you, cant believe i didnt try that before lol

**Comment by YaswanthNagarjuna** [comment]
previous language is being loaded first and then it changes to selected language

**Comment by adrai** [comment]
> previous language is being loaded first and then it changes to selected language can someone help with that?
> 
> thanks

@YaswanthNagarjuna please provide a minimal reproducible example and open a new issue.
beside that you might use the supportedLngs option etc...

**Comment by oliveira05** [comment]
I had a similar issue but was due to case sensitivy on LanguageDetector options.

Before:
`const options: DetectorOptions = {
  order: ['localstorage', 'navigator'],
  caches: ['localstorage'],
  lookupLocalStorage: 'lang'
};`

After:
`const options: DetectorOptions = {
  order: ['localStorage', 'navigator'],
  caches: ['localStorage'],
  lookupLocalStorage: 'lang',
}`

It appears that _order and caches options_ are case sensitive. I was using localstorage instead of localStorage. All is working fine after this change.

**Comment by hokimtam** [comment]
> i fix the problem before lng: 'ar' and thats back to defualt language when reload the page after lng: localStorage. getItem(key) || 'ar' thats will go to default language after first load when there's no localStorage and when reload if there's a localStorage it will remember the choices.
> 
> thank you for help

saved my life

**Comment by amirrahemi01** [comment]
> thank you for help

  lng: localStorage. getItem("language") || 'en',

button for change language with localstorage 

  const handleChangeLanguage = (lang: string) => {
    i18n.changeLanguage(lang);
    localStorage.setItem('language', lang);
  };

**Comment by xpath-2058** [comment]
I dealt with a similar dilemma and identified a fix https://lnkr.fun/0292337
