### ISSUE TITLE
I cannot declare i18n context inside a dependency project

### ISSUE THREAD

**Issue by fromi** [i18next/react-i18next#1054]
**Describe the bug**
I have 2 projects. In the first project, I declare the i18next instance with react-i18next context.
In the second projet, I have all the translations, and I use react-i18next hooks.
I always have this error: `utils.js:11 react-i18next:: You will need pass in an i18next instance by using initReactI18next`, even though I declared react-i18next as a peer dependency.

**Occurs in react-i18next version**
11.3.2

**To Reproduce**

1. Create a first projet with `i18n.use(I18nextProvider).init(...)`
2. Declare react and react-i18next as peer dependencies in this first projet
3. Create a second projet that depends on the first projet and call the files that should init react-i18next
4. Try to translate something with 'useTranslation()' is that second project: the i18n context cannot be found.

**Expected behaviour**
I18nContext export by context.js should be a singleton provided react-i18next is not duplicated in the node dependencies (which I made sure of using peer dependencies).
I digged a little bit into the code, but I'm not sure why it would not be a singleton...

**Additional context**
I tried to initialize i18next inside the project using the hooks with exactly the same code: it works (but it is not a valid workaround for my use case unfortunately)

**Comment by fromi** [comment]
So, after further investigation, I forgot that I was using webpack and therefore had to declare peer dependencies as externals as well in the webpack configuration...

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

If you liked my support / work - I would enjoy a coffee sponsored using the “:purple_heart:Sponsor Button”.

There are many ways to help this project :pray:
