### ISSUE TITLE
'cp' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by reZach** [i18next/react-i18next#1055]
**Describe the bug**
You cannot run `npm run build` if doing a fresh clone from this repository.

**Occurs in react-i18next version**
11.3.3

**To Reproduce**
Clone repository, run `npm i`, then run `npm build`

**Expected behaviour**
I expect `npm run build` to run successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/4740370/74791690-d4efd380-5280-11ea-9962-08922501ceb4.png)

**OS (please complete the following information):**

- Device: Win 10

**Additional context**
N/A

**Comment by reZach** [comment]
[cp-cli](https://www.npmjs.com/package/cp-cli) is an alternative but the github repo is archived (read-only).

**Comment by reZach** [comment]
[cpy-cli](https://www.npmjs.com/package/cpy-cli) looks to be more maintained.

**Comment by jamuhl** [comment]
On what system are you? Having that globally on mac

**Comment by adrai** [comment]
probably windows, right?

**Comment by reZach** [comment]
@jamuhl / @adrai yes on Windows, Windows 10.

**Comment by adrai** [comment]
No Windows machine here... would you like to create a PR?

**Comment by reZach** [comment]
Would you like the build scripts to use an npm dependency instead of the native **cp**? This was my plan but as long as you are okay with it.

**Comment by jamuhl** [comment]
@reZach sure, I'm ok with that....

**Comment by reZach** [comment]
I am open to other suggestions! (A `build-win` that uses a npm dependency, but I felt a dependency for all systems is the lesser of two evils)

**Comment by jamuhl** [comment]
fully agree...works on both is better...never tested myself on windows...not used windows for so long...

**Comment by reZach** [comment]
https://github.com/i18next/react-i18next/pull/1056
