### ISSUE TITLE
Releasing "Next Right Now" - Integration example of react-i18next + locize in a Next.js application

### ISSUE THREAD

**Issue by Vadorequest** [i18next/react-i18next#1060]
We just released our newest Next.js/Zeit boilerplate at https://github.com/UnlyEd/next-right-now

It features the usage of react-i18next, alongside Locize. It can be a good resource for people trying to implement react-i18next within Next.js framework.

- See https://github.com/UnlyEd/next-right-now/blob/master/src/utils/i18nextLocize.ts for i18next/locize integration
- See https://github.com/UnlyEd/next-right-now/blob/master/src/pages/_app.tsx#L172 for usage within `_app.tsx`
- See https://github.com/UnlyEd/next-right-now/blob/master/src/components/Footer.tsx#L95 for `t` usage

See https://github.com/UnlyEd/next-right-now/blob/master/README_DEPENDENCIES.md#i18n-i18next-and-locize for advanced documentation

Maybe it could be referenced somewhere? Hope it helps!

**Comment by jamuhl** [comment]
There is one place that currently comes to mind: https://react.i18next.com/latest/ssr#using-next-js

https://www.i18next.com/overview/supported-frameworks might be a place to add it?

Just let me know when it's ready to be added and if you see another place where it might fit?

**Comment by Vadorequest** [comment]
NRN is a boilerplate based on Next.js, not a framework by itself. But yes, it could be referenced there!

Should I make a PR? On which repo(s)?

**Comment by jamuhl** [comment]
There should be an "Edit on GitHub" link in the upper right corner (above the TOC)

**Comment by Vadorequest** [comment]
Thanks, done:

https://github.com/i18next/i18next-gitbook/pull/113
https://github.com/i18next/react-i18next-gitbook/pull/75

**Comment by jamuhl** [comment]
Will merge those later...thanks for adding

**Comment by jamuhl** [comment]
merged both
