### ISSUE TITLE
Going down the chain

### ISSUE THREAD

**Issue by JamesIves** [i18next/react-i18next#1061]
**Is your feature request related to a problem? Please describe.**

I have several namespaces loaded into my component using `withTranslate(['namespace1', 'namespace'2])` and I'm trying to figure out how to do some form of priority list. I'm new to using this library and I'm not sure the right way to approach this.

For example I have the following call setup:

`this.props.t('namespace1: helloStr')` 

I'm keying into `namespace1`, but `helloStr` doesn't exist there, but it does in `namespace2`. As both namespaces are loaded is there a way to go down the list of namespaces until it finds a matching key even though a specific namespace was keyed in the `t` function?

**Comment by jamuhl** [comment]
You can try using `nsMode: 'fallback'` https://github.com/i18next/react-i18next/blob/master/src/context.js#L6 in i18next.init options.react

**Comment by JamesIves** [comment]
Exactly what I needed! Thanks

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

If you liked my support / work - I would enjoy a coffee sponsored using the “:purple_heart:Sponsor Button”.

There are many ways to help this project :pray:

**Comment by JamesIves** [comment]
We're in the process of purchasing Locize 👍

**Comment by JamesIves** [comment]
We'll be using Locize soon 👍
