### ISSUE TITLE
Different returning logic when using <Trans/> or t() function added by withTranslation hoc

### ISSUE THREAD

**Issue by WebKieth** [i18next/react-i18next#1062]
**Is your feature request related to a problem? Please describe.**
I wrote a component, which includes some common fields with translation on front-end side and additional fields, which I got from backend - their labels have already translated. 
So, if I use ```<Trans/>``` on pretranslated fields - I set this label on key attribute. Of course this key isnt found inside translation json and tag returns empty string. But when I use ```t()``` function added by withTranslation hoc - this function returns entered key string if key didnt find. 

**Describe the solution you'd like**
I would prefer to use standalone ```<Trans/>``` component instead a hoc (Code is cleaner, performance is better), so just return an entered key string with Trans, as you do it with ```t()```

**Comment by jamuhl** [comment]
can you try adding i18next init options  `transEmptyNodeValue: false` for the react options

```js
const i18nOptions = { react: { transEmptyNodeValue: false } };
i18n.init(i18nOptions);
```

I'm not sure if `Trans` performance is that well compared to using `withTranslation` or `useTranslation`  as it's main purpose is the translation of JSX trees - not simple strings...so there is some html parsing included on rendering that - but might be performance is ok as having simple content might omit that parsing stuff - never tested performance too much (as I never run into issues with that)

**Comment by WebKieth** [comment]
@jamuhl new key didn't work, Trans still returns empty string
My config:
```
import i18n from "i18next";
import { initReactI18next } from "react-i18next";
import locales from '../locales';
// the translations
// (tip move them in a JSON file and import them)
i18n.use(initReactI18next).init({
    resources: {
      en: {translation: locales.en},
      ru: {translation: locales.ru}
    },
    react: {
      transEmptyNodeValue: false
    },
    lng: "ru",
    nsSeparator: ':::',
    keySeparator: '::', // we do not use keys in form messages.welcome
    interpolation: {
      escapeValue: false // react already safes from xss
    }
  })
export default i18n;
```
About performance - I didn't test too, but - just a common sense - one function will work faster than two. Component without hoc will render faster than with. I try to use hocs only if I have no other choice

**Comment by jamuhl** [comment]
Depends on what the called function does (1 function calling 1000 functions might be slower than calling 100 functions calling no other functions 😁)

If you like you might provide a PR fixing the issue -> setting  `transEmptyNodeValue: false` should return the key as is. Else I will try to fix this later this week.

**Comment by WebKieth** [comment]
Ok, I will provide a PR on this week, closer to the weekend

**Comment by jamuhl** [comment]
Awesome...thank you...👍

**Comment by adrai** [comment]
@WebKieth any update on this?
