### ISSUE TITLE
Simplify key name for convenience: (i18nKey) -> (id)

### ISSUE THREAD

**Issue by simoami** [i18next/react-i18next#1063]
**Is your feature request related to a problem? Please describe.**
It is tedious and frustrating to have to type the keys `i`, `1`, `8`, `n`, `shift + K`, `e`, `y` several times per screen.

**Describe the solution you'd like**
Would you be able to accommodate a simpler key? `id` as an alias sounds great and there's no breaking changes. This key name is actually used by several other libs including react-intl and angular i18n

This looks much simpler and easier to type when you're doing it 10 time per screen.
```
<Trans id="my.key" />
```

Additionally, you will be saving some keys from excessive wear and tear :)

![keys](https://user-images.githubusercontent.com/2038264/76233134-1b8c7a00-61fe-11ea-9cc2-5f30bd3abe5a.jpg)

Thank you for considering!

**Comment by jamuhl** [comment]
haha...`id`, `name` and `key` I tried to avoid those because either have special meaning in html elements or react elements -> but nothing against a PR making `id` a fallback for `i18nKey`

**Comment by adrai** [comment]
@simoami can this be closed?

**Comment by simoami** [comment]
Yep, this can be addressed in a separate PR.
