### ISSUE TITLE
How to setup for multiple translations

### ISSUE THREAD

**Issue by inquiztr** [i18next/react-i18next#1065]
# Question about react-i18next

Can we get an example in the documentation on how to setup translations for multiple components but keep the namespaces reside in each component it resides in.

What I want to accomplish is multiple i18n.ts that contain the keys for the specific component it resides in.  The examples available now put them into a locale folder but i would rather have them in the folder where they are used.

ex:  
 /components/product-page/i8n.ts   // a namespace used for general page level translations
/components/product-image-carousel/i18n.ts     //namespace for this specific child widget 
/components/product-detail-modal-widget/i18nts   // namespace for modal

I want the keys precompiled into the components bundle js, not via xhr requests as current examples show.

Where I am getting stuck is i get i18n initially working on the parent component but when i define a second i18n deeper in a child component, the translations don't work. 

The available examples seem to define all the multiple namespaces in the parent component but I am trying to not hard code those dependencies into the parent in case the widgets are used elsewhere on different page.

**Comment by jamuhl** [comment]
You always got a singleton i18n instance around -> so makes no difference...you can try building something that bundles those translations into the i18n instance by using https://www.i18next.com/overview/api#addresourcebundle adding namespaces/component translations into the instance on import...

**Comment by jamuhl** [comment]
What we normally do is having translations as JSON on the server and let eg. the xhr-backend take care of loading needed namespaces based on `useTranslation` or `withTranslation`

**Comment by inquiztr** [comment]
Thank you, that did help. I now setup the parent component as usual with default namespace but for child/widget components i define as below : 
```
//child widget component
import { translation-en, translation-fr } from './nsWidget';

const { i18n, t } = useTranslation('nsWidget');
i18n.addResourceBundle('en', 'nsWidget',translation-en, true, true);
i18n.addResourceBundle('fr', 'nsWidget', translation-fr, true, true);

```

This pattern seems to be working for me. Thank you.

**Comment by jamuhl** [comment]
If it works for you - it works for me 👍
