### ISSUE TITLE
Using public folder for translations

### ISSUE THREAD

**Issue by hreuven** [i18next/react-i18next#1066]
Hello,
Is it mandatory to place the translation files under the public folder?
Can i place it in a react project under app/src and some assets folder?

**Comment by jamuhl** [comment]
Place it where you want -> if using xhr-backend you just have to make sure that path is set correctly in loadPath (having some weird beside component structure you will have to create a own backend implementation figuring that paths out). And make sure those paths are accessible via xhr/fetch -> public path does that per default in react-script (also adds the files there to build output)
