### ISSUE TITLE
images are show 1 sec and disappear when use 'const { i18n } = useTranslation(); '

### ISSUE THREAD

**Issue by ballprogrammer** [i18next/react-i18next#1068]
**Describe the bug**
images are show 1 sec and disappear when use 'const { i18n } = useTranslation(); '

my code
`
import React, { Suspense } from 'react';
import { Route } from 'react-router-dom'
import { useTranslation, withTranslation } from 'react-i18next';

function Page() {
  const { i18n } = useTranslation(); // << when use this line my image when open it show then disappear
    return (
      <div>
          {i18n.t('MENU.HOME')}
          <a href="" onClick={() => i18n.changeLanguage('de')}> de </a>
          <a href="" onClick={() => i18n.changeLanguage('en')} style={{paddingLeft:"8px"}} > en </a>
          <img className="" width="350" alt="" src=image1.png" /> 
      </div>
    );
  }`

**Occurs in react-i18next version**
    "i18next": "^19.3.3",
    "i18next-browser-languagedetector": "^4.0.2",
    "i18next-xhr-backend": "^3.2.2",
    "prettier": "^1.19.1",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-i18next": "^11.3.3",
** note i try too many version

**To Reproduce**

1. when use this line 'const { i18n } = useTranslation();'
2. when open open web browser image to show.
3. after 1 sec image are disappear.
4. no error message.

**Additional context**
i stuck in this error over week, any one can help me?

**Comment by jamuhl** [comment]
Set debug: true on i18next init and check the console...not much I can tell from the few code snippets provided - also consider putting up your complete sample at codesandbox so we get something to work with...thank you

**Comment by ballprogrammer** [comment]
thank you

**Comment by jamuhl** [comment]
were you able to solve it?

**Comment by ballprogrammer** [comment]
yes, thank you so much :)
