### ISSUE TITLE
Group UI Strings into a file

### ISSUE THREAD

**Issue by xihaoxiaohao** [i18next/react-i18next#1069]
Is it possible to group the display string into a file, then export these strings to components?

I tried to place all the ui strings like in a single file, and export each string in that file. For example, `export ABC = t('abc')`, but it fails with the below error because React doesn't allow me to use the `t` hook outside of a function component.

```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component.
```

**Comment by jamuhl** [comment]
https://www.i18next.com/translation-function/essentials#accessing-keys-in-different-namespaces -> you can load different files (per component): https://react.i18next.com/latest/usetranslation-hook#loading-namespaces

**Comment by xihaoxiaohao** [comment]
Thanks @jamuhl , but it still doesn't work. Now it says I access the t function before init.

I think my ui-string file is like a global file, and React call it before my init?

```
18next::translator: key "abc" for namespace "mynamespace" for languages "en" won't get resolved as namespace was not yet loaded This means something IS WRONG in your application setup. You access the t function before i18next.init / i18next.loadNamespace / i18next.changeLanguage was done. Wait for the callback or Promise to resolve before accessing it!!!
```

Here's my ui string file inside the src folder:

```js
import i18n from '../../../i18n';

export const ABC = i18n.t('mynamespace:abc');
```

Here's my i18n.js file inside the root folder:

```js
i18n
  .use(Backend)
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    fallbackLng: 'en',
    whitelist: ['en', 'zh-CN'],
    interpolation: {
      escapeValue: false,
    },
    detection: detectionOptions,
    debug: true,
  });

export default i18n;
```

**Comment by jamuhl** [comment]
You don't need that `export const ABC = i18n.t('mynamespace:abc');` you shoot yourself in the foot with this...making things more complicated than they should be...just follow the best practices in the samples...

Going your file approach, you can't easily:

- access t on the right time
- change the texts on language change
- use the Trans component

just load files / namespaces inside your component using useTranslation, withTranslation -> if needed use https://www.i18next.com/translation-function/objects-and-arrays#objects if you like to do some component based translation thing

What is your reason to do it in that `.js` file with translations beside the component?

**Comment by jamuhl** [comment]
https://github.com/i18next/react-i18next/issues/1058 might help...just personally for me this looks like adding a facade in front of a facade...overengineering, over-complicating...you already have keys that can be grouped into files (namespaces) or by key separated by `.`

**Comment by jamuhl** [comment]
Using a TM like our https://locize.com is for sure a bettter solution to keep translation under control

**Comment by xihaoxiaohao** [comment]
Thanks jamuhl, I think you are right...
