### ISSUE TITLE
Dynamic import for computed module specifiers (looping over an array of locales)

### ISSUE THREAD

**Issue by YassineDM** [i18next/react-i18next#1070]
I am currently configuring internationalization/i18n for a React app using i18next and react-i18next. I basically follow the documentation [here][1] for i18next configuration and [here][2] for formatting with Moment.js.

For Moment.js, it is either possible to import all locales like this:
```javascript
import 'moment/min/locales'
```
or individually for each locale like this:
```javascript
import 'moment/locale/en-gb'
import 'moment/locale/fr'
// Shortened for this example...
````
I have an array of supportedLocales with language varieties:
```javascript
const supportedLocales = ['en', 'en-GB', 'fr', 'fr-CA', 'es'] // Shortened for this example...
```
I was wondering first if there was a way to 'dynamically import' computed module specifiers like this:
```javascript
// Import Moment.js supportedLocales (other than default `en`).
supportedLocales.forEach(locale => {
	if (locale !== 'en') {
		import(`moment/locale/${locale}`)
	}
})
```
But I have an ESLint warning:

> eslint: error no-unused-expressions - Expected an assignment or
> function call and instead saw an expression.

I was also wondering if we could even go further and only import a module specifier when needed (if there is any interest in doing so):
```javascript
// Listen to the change language event to keep Moment.js locale in sync.
i18n.on('languageChanged', newLocale => {
	moment.locale(newLocale)
	import(`moment/locale/${locale}`)
})
```

  [1]: https://react.i18next.com/latest/using-with-hooks
  [2]: https://www.i18next.com/translation-function/formatting

**Comment by jamuhl** [comment]
we do the last one...`i18n.on('languageChanged', ...`. This is not a question / issue with react-i18next -> https://github.com/jmblog/how-to-optimize-momentjs-with-webpack

**Comment by YassineDM** [comment]
Thank you very much for this info which answers my question.

By the way, I did post a [question](https://stackoverflow.com/questions/60682524/dynamic-import-for-computed-module-specifiers-looping-over-an-array-of-locales) in SOF about 10 days ago but it did not get much attention...

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

If you liked my support / work - I would enjoy a coffee sponsored using the “:purple_heart:Sponsor Button”.

There are many ways to help this project :pray:
