### ISSUE TITLE
Using <Trans /> with withTranslations

### ISSUE THREAD

**Issue by JamesIves** [i18next/react-i18next#1071]
I have a component which is wrapped in `withTranslation(['SpendingShared'])` with `ns` fallback configured.

I have a component which imports a string like so (`state.translate` is equal to `props.t` in this case)

```
    <InputCard
      {...props}
      title={state.translate('spendingAmountCard.title', state)}
      description={state.translate('spendingAmountCard.description', state)}
      moreDetails={{
        label: state.translate('spendingAmountCard.moreDetailsLabel', state),
        header: state.translate('spendingAmountCard.moreDetailsHeader', state),
        cabinetContent: whatDoesHealthSpendingInclude(),
      }} />
```

Inside of the function that generates `whatDoesHealthSpendingInclude()` I've wrapped the text in the `<Trans />` component as I need to be able to include paragraph tags:

```
<Trans i18nKey="whatDoesHealthSpendingInclude" />
```

I keep running into an error saying that `whatDoesHealthSpendingInclude` is a missing key in the `common` namespace (which is the default configured namespace in the i18n configuration). Even when placed within `common.json` it still can't find it because it thinks I'm trying to access the translation before i18n is ready. 

What is the correct way to use this component? Do I somehow need to provide context to the component to let it know which namepsace to pull from when `t` is available?

**Comment by jamuhl** [comment]
Importent: `Trans` does not load translations and does not automatically get the t function of the outer Component (uses default namespace)

you can pass t to Trans `<Trans t={t} />` and load common namespace like `withTranslation(['SpendingShared', 'common'])`

**Comment by JamesIves** [comment]
Ah that makes sense. Thanks!

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

If you liked my support / work - I would enjoy a coffee sponsored using the “:purple_heart:Sponsor Button”.

There are many ways to help this project :pray:
