### ISSUE TITLE
Unable to leverage i18n within Translation Component

### ISSUE THREAD

**Issue by jtrelfa** [i18next/react-i18next#1073]
**Describe the bug**
From the docs:
https://react.i18next.com/latest/translation-render-prop
The `Translation` is a render prop and gets the `t` function and `i18n` instance to your component.

```jsx
import React from 'react';
import { Translation } from 'react-i18next';

export function MyComponent() {
  return (
    <Translation>
      {
        (t, { i18n }) => <p>{t('my translated text')}</p>
      }
    </Translation>
  )
}
```

While you most time only need the t function to translate your content you also get the i18n instance to eg. change the language.

```javascript
i18n.changeLanguage('en-US');
```
**Describe the Question**
I'm unable to leverage the i18n.changeLanguage() method within the return() of my component's render{}.  How do I use it as you describe in the documentation?
Side note: I am able to use the i18n object to get the current language (I needed it for a hidden input).  But I am using classes instead of functional components and I'm not seeing a way to leverage .changeLanguage() without a page refresh/changing the route

**Comment by jamuhl** [comment]
I don't see why it should not work: https://github.com/i18next/react-i18next/blob/master/src/Translation.js#L7 calling i18n.changeLanguage will change the language and Translation itself uses useTranslation to get updated...

**Comment by jtrelfa** [comment]
Turns out I had to do it this way:
```jsx
<Translation>
    {(t, i18n) => (
        <button type="button" onClick={() => {i18n.i18n.changeLanguage("en-us")}}>{t("english")}</button>
    )}
</Translation
```
I'll close the issue...

**Comment by jamuhl** [comment]
Does deconstruction not work:

```jsx
// see deconstruction
// assuming: const additional = { i18n, lng };
// const { i18n } = additional;
<Translation>
    {(t, { i18n }) => (
        <button type="button" onClick={() => {i18n.changeLanguage("en-us")}}>{t("english")}</button>
    )}
</Translation>
```

**Comment by jtrelfa** [comment]
It works! I have much to learn...thanks for the help!
