### ISSUE TITLE
react.i18next.com Is working fine inside my main Project but not in my npm package which i used inside my main Project

### ISSUE THREAD

**Issue by ParthCodeDev** [i18next/react-i18next#1074]
# Question about react-i18next

Questions should be posted on StackOverflow
I have two project
 - One is main project 
 - Second one is my react npm package(repository) which i used inside my main project's package.json file as below,
` "dependencies": {
"package-name": "git+https://oauth2:<Access-Token>@gitlab.com/<Project-name>/react-menu.git"
}`

So if i followed all the steps given over here :  https://react.i18next.com/latest/using-with-hooks
Then it is working fine in main project using both way using Hook and using HOC

But when i am trying to add same code inside my another repository as i mentioned above  then it is throwing error like below
https://reactjs.org/docs/error-decoder.html/?invariant=321

So i dont know what was wrong.

Can you guys help me with this.

**Comment by jamuhl** [comment]
Rather sure...main project has a react and second one another

**Comment by ParthCodeDev** [comment]
> Rather sure...main project has a react and second one
Both the project have react but inside my second react project which I used as dependency inside my main project, it is not working into my another project

Did you get it what I am trying to say ??

**Comment by jamuhl** [comment]
I checked your error message -> and you say two repos - so what should I get...you got an error from react -> which says you got a mismatch

**Comment by ParthCodeDev** [comment]
> I checked your error message -> and you say two repos - so what should I get...you got an error from react -> which says you got a mismatch
 

Actually my main project is not fully react project but at some parts like for menu we used react inside HTML
My second project is react-menu which is private npm package and as I mentioned earlier i used my react-menu inside my main project as dependency in my main project package.json file

So the code describe in the i18n react is working fine in my main repo but when I am trying use this in my react-menu repo and after applying all the thing like build creation and etc when I reload the page then it is showing error as I mentioned


If you still not understand than is there any way I can show you the code ??

**Comment by jamuhl** [comment]
I understand...but this problem is not related to i18next or react-i18next -> it's your setup with two projects that don't work. So I'm still at the same thing you should first check:

/node_modules/react
/node_modules/react-menu/node-modules/react

is the cause of your problem

**Comment by ParthCodeDev** [comment]
> I understand...but this problem is not related to i18next or react-i18next -> it's your setup with two projects that don't work. So I'm still at the same thing you should first check:
> 
> /node_modules/react
> /node_modules/react-menu/node-modules/react
> 
> is the cause of your problem

Okay 
Thank you so much 
I will check it and get back to you
😊

**Comment by adrai** [comment]
@ParthCodeDev could you solve the issue?

**Comment by ParthCodeDev** [comment]
@adrai Hello
Yes i solve the issue but it is not working as per it is describe in the react.i18nx but i used i18n.t() then it is working fine.

**Comment by rawbeans** [comment]
Can you please elaborate on your solution? How did you get i18next to work in your package (react-menu)?

Did you do:
```
import i18n from 'i18next';
// then later:
i18n.t("text to translate');
```

instead of:
```
import { useTranslation } from 'react-i18next';
// then later:
const { t } = useTranslation();
t("text to translate');
```

**Comment by ParthCodeDev** [comment]
> Can you please elaborate on your solution? How did you get i18next to work in your package (react-menu)?
> 
> Did you do:
> 
> ```
> import i18n from 'i18next';
> // then later:
> i18n.t("text to translate');
> ```
> 
> instead of:
> 
> ```
> import { useTranslation } from 'react-i18next';
> // then later:
> const { t } = useTranslation();
> t("text to translate');
> ```

Yes I did  import i18n from 'i18next';
> // then later:
> i18n.t("text to translate')
And it is working fine

**Comment by rawbeans** [comment]
When I try:
```
import i18n from 'i18next';
// then later:
i18n.t("text to translate');
```
From within my component library, that i18n instance is different from the one in my main app that is importing my component library. The result is empty strings for all translations in my component library.

Where and how did you initialize your i18next instance?
How are your two projects set up?

**Comment by ParthCodeDev** [comment]
> When I try:
> 
> ```
> import i18n from 'i18next';
> // then later:
> i18n.t("text to translate');
> ```
> 
> From within my component library, that i18n instance is different from the one in my main app that is importing my component library. The result is empty strings for all translations in my component library.
> 
> Where and how did you initialize your i18next instance?
> How are your two projects set up?
> 
> **Update:**
> I got it to work by doing the following:
> 
> ```
> import { useTranslation } from 'react-i18next';
> // then later:
> const { t } = useTranslation();
> t("text to translate');
> ```
> 
> And in my component library package.json, adding the following to peerDependencies:
> 
> ```
> "peerDependencies": {
>     "react-i18next": "^11.4.0",
> },
> ```
> 
> That way, the main projects i18n instance was used instead of bundling a separate version of all i18next packages and creating a second instance.

I have two project 
 one is main project
second one is react menu repositry from which i get menu

Inside my main project i handle everything regarding translation and whatever translation text i need inside my second project i am passing it as props so i can access them inside my second project
