### ISSUE TITLE
t function does not re-render using withTranslation HOC or useTranslation hook

### ISSUE THREAD

**Issue by xihaoxiaohao** [i18next/react-i18next#1075]
I looked at similar issues such as #1014 and #835, both suggesting using withTranslation so that after language is changed, the `t` function will rerender:

> any call to t returns a string so setting `{ text: t('translation_one')`, ... will be a string that has no way to update itself (it is typeof string)...
> a component wrapped `withTranslations` triggers a rerender on languageChanged -> inside render t gets called again -> so it's not the string rendered that updates magically but the HOC with triggers a new render.

But in my code, when the `t` function is inside the title attribute. If I change the language, the text stays the same.

```jsx
// MyComponent.jsx
const MyComponent = ({ t, i18n }) => {
          ...
            <span
              data-toggle="tooltip"
              data-placement="auto"
              title={t('foo', 'text foo')} // does not rerender
            >
            ...
            </span>
}

export default withTranslation(['ns'])(MyComponent);
```

```jsx
// Button.jsx
const { i18n, t } = useTranslation(['ns']);
  
const Button = () => {
  const changeLanguage = (lng) => {
    if (lng === 'en') {
      i18n.changeLanguage('de');
    } else {
      i18n.changeLanguage('en');
    }
  };

  return <Button onClick={evt => changeLanguage(this.state.lng)}>Change Language</Button>
}
```

**Comment by jamuhl** [comment]
check your console output after setting debug: true on i18next.init...sure your content gets not loaded correctly

**Comment by xihaoxiaohao** [comment]
Hi @jamuhl , it seems because I use bootstrap and it doesn't work well with i18n. I also create the [codesandbox](https://codesandbox.io/s/react-i18next-iuhzf) for demoing this problem.

When page loads, it only shows bootstrap an English tooltip.

<img width="529" alt="a" src="https://user-images.githubusercontent.com/9826637/78289613-4903d500-74d7-11ea-94fc-8a902026a1ec.png">

After I change the language, bootstrap tooltip text stays the same, but browser tooltip also shows up and gets translated fine.

<img width="600" alt="b" src="https://user-images.githubusercontent.com/9826637/78289751-81a3ae80-74d7-11ea-829f-a4799be62f39.png">

**Comment by jamuhl** [comment]
you considered not using jquery, bootstrap for react? or at least some react implementation for bootstrap...things won't work like this...the way jquery based bootstrap attaches tooltips is absolutely not what the react way of doing things is.

**Comment by jamuhl** [comment]
https://react-bootstrap.github.io/

**Comment by xihaoxiaohao** [comment]
Thanks jamuhl,

After hours debugging, I found out the solution is I need to manually destroy and recreate the bootstrap tooltip, so under the change language function, add this:

```js
$('[data-toggle="tooltip"]').tooltip("dispose");
```

Things get trickier if not using the bootstrap library...
