### ISSUE TITLE
Nesting reference keys from other namespaces doesn't work

### ISSUE THREAD

**Issue by ivansky** [i18next/react-i18next#1076]
**Describe the bug**
Reference keys from other namespaces doesn't work

**Occurs in react-i18next version**
11.3.0

**To Reproduce**
```js
config = {
  keySeparator: '###',
  defaultLanguage: 'de',
  otherLanguages: ['fr'],
  defaultNS: 'common',
}
```

search.json
```json
{
  "example.key": "Test"
}
```

Component.js
```js
const { t } = useTranslation(['common', 'search']);

const result = t('$t(search:example.key)')
```

Expecting:
```
result === 'Test'
```

Actual:
```
result === 'example.key)'
```

**Comment by jamuhl** [comment]
you can't have a key that is a nesting

**Comment by ivansky** [comment]
@jamuhl Sorry, what am I doing wrong? Is it a way to make it works then? That is a strange behaviour I got here :(

**Comment by jamuhl** [comment]
`const result = t('search:example.key')`

**Comment by adrai** [comment]
@ivansky is this working for you?

```js
const { t } = useTranslation(['common', 'search']);

const result = t('search:example.key')
```
