### ISSUE TITLE
Cannot update a component while rendering a different component

### ISSUE THREAD

**Issue by Vadorequest** [i18next/react-i18next#1077]
**Describe the bug**
I upgraded to the latest version of react and I got warnings. I believe they come from react-i18next but ain't sure.

https://github.com/UnlyEd/next-right-now/pull/27 issue is explained in main description.

Related to https://fb.me/setstate-in-render 

**Occurs in react-i18next version**
"react-i18next": "11.3.4",

https://github.com/UnlyEd/next-right-now/pull/27/commits/7fd91e467ae0adc70396d9f4335e308540403083

May not be related to i18n update but react instead:
https://github.com/UnlyEd/next-right-now/pull/27/commits/d263134cf196b86c9a322e4b77cd32da03d8e3cd
 
**To Reproduce**
Use latest react version and latest i18next version.

Or use our online demo: https://nrn-v1-ssr-mst-aptd-gcms-lcz-sty-c1-axb1uwh7s.now.sh/

Easiest way of local repro is to clone branch https://github.com/UnlyEd/next-right-now/pull/27 and follow the quick start at https://unlyed.github.io/next-right-now/getting-started/quick-start (should be straightforward 3-5mn)

**Expected behaviour**
Shouldn't display this warning

**Comment by jamuhl** [comment]
If possible providing a codesandbox for reproduction would help a lot. Else I will update react in our repo and see if we got the same issue - currently not got the time to hunt maybe warnings.

**Comment by adrai** [comment]
Could not reproduce it with updated dependencies in this example: https://github.com/i18next/react-i18next/commit/2252592541209eecf9a670b4676a59edb26492f4

**Comment by Vadorequest** [comment]
Thank you. Then maybe it's the way my app is configured.

I guess I'll let it slide then.

**Comment by Vadorequest** [comment]
Could be related to https://github.com/apollographql/react-apollo/compare/react-apollo@3.1.3...react-apollo@3.1.4

I'll investigate.

**Comment by Vadorequest** [comment]
Fixed by https://github.com/apollographql/react-apollo/pull/3902 indeed

Released under `react-apollo@3.1.4`.

The difficulty here was to locate which package the error was originating from, which is lost under the react stacktrace tree.
