### ISSUE TITLE
Following example/v9.x.x/reactnative-expo resulting to a TypeError: undefined is not an object (evaluating 'module.type')

### ISSUE THREAD

**Issue by 5ervant** [i18next/react-i18next#1078]
**Description**
I build my Expo app with `@expo/next-adapter`, it means that my `next-expo` project consists of mobile app and Next.js app: https://docs.expo.io/versions/latest/guides/using-nextjs/

I'm trying to implement `react-i18next` on **the mobile version of my `next-expo` project** using this example: https://github.com/i18next/react-i18next/tree/master/example/v9.x.x/reactnative-expo

_(Different issue: Here's my issue implementing `next-i18next` on **the web version of my `next-expo` project**: https://github.com/isaachinman/next-i18next/issues/678)_

**Occurs in react-i18next version**
```
"dependencies": {
  "expo": "~36.0.0",
  "expo-localization": "~8.0.0",
  "i18next": "^19.3.4",
  "react-i18next": "^11.3.4",
  // ...
"devDependencies": {
  "@expo/next-adapter": "^2.0.5",
  // ...
```

**To Reproduce**

1. Create a `next-expo` app with `react-navigation` using this approach: https://docs.expo.io/versions/latest/guides/using-nextjs/#tldr
2. Use `react-redux` and just wrap your _"App.js"_ child component within `Provider` with your created `store`: https://react-redux.js.org/introduction/quick-start#provider
3. Implement `react-i18next` for Expo with the guidelines of this example: https://github.com/i18next/react-i18next/tree/master/example/v9.x.x/reactnative-expo
4. See this error on an Android emulator _(specifically, of Android Studio)_:

```
TypeError: undefined is not an object (evaluating 'module.type')

use
C:\Users\USER\Documents\PROJECTS\PLATFORM\APPNAME\node_modules\i18next\dist\cjs\i18next.js: 2015:11

<unknown>
node_modules%5Cexpo%5CAppEntry.bundle?platform=android&dev=true&minify=false&hot=false: 147266:45

loadModuleImplementation
C:\Users\USER\Documents\PROJECTS\PLATFORM\APPNAME\node_modules\metro\src\lib\polyfills\require.js: 322:6

// ...
```

Here's my _"./App.js"_ structure:

```
function WrappedStack(props) {
  const { initialNavigationState, containerRef } = props;
  return (
    <NavigationContainer
      ref={containerRef}
      initialState={initialNavigationState}
    >
      <Stack.Navigator
        // ...
      >
        <Stack.Screen {...} />
        <Stack.Screen {...} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}

const ReloadAppOnLanguageChange = withNamespaces('common', {
  bindI18n: 'languageChanged',
  bindStore: false
})(WrappedStack);

export default function App(props) {
  const [isLoadingComplete, setLoadingComplete] = React.useState(false);
  const [initialNavigationState, setInitialNavigationState] = React.useState();
  const containerRef = React.useRef();
  const { getInitialState } = useLinking(containerRef);

  // Load any resources or data that we need prior to rendering the app
  React.useEffect(() => {
    async function loadResourcesAndDataAsync() {
      try {
        SplashScreen.preventAutoHide();

        // Load our initial navigation state
        setInitialNavigationState(await getInitialState());

        // Load fonts
        await Font.loadAsync({
          ...Ionicons.font,
          'space-mono': require('./assets/fonts/SpaceMono-Regular.ttf')
        });
      } catch (e) {
        // We might want to provide this error information to an error reporting service
        console.warn(e);
      } finally {
        setLoadingComplete(true);
        SplashScreen.hide();
      }
    }

    loadResourcesAndDataAsync();
  }, []);

  if (!isLoadingComplete && !props.skipLoadingScreen) {
    return null;
  } else {
    return (
      <Provider store={store}>
        <View style={styles.container}>
          {Platform.OS === 'ios' && <StatusBar barStyle="default" />}
          <ReloadAppOnLanguageChange
            initialNavigationState={initialNavigationState}
            containerRef={containerRef}
          />
        </View>
      </Provider>
    );
  }
}
```

**Expected behaviour**
It should not produce a TypeError nor any error, even though I'm not yet using `withNamespaces` on any of my `react-navigation` `Stack.Screen` component, e.g.: https://github.com/i18next/react-i18next/blob/master/example/v9.x.x/reactnative-expo/js/pages/Home.js

**OS:**

- Device: Device: Windows 10
- Browser: Chromium-based browser: 80.0.3987.122 (Official Build) (64-bit)

**Additional context**
Do you think I just stop implementing `i18next` on an experimental platform and just use an easier alternative like `react-localization`, `react-intl` or else? Or they're still in the same level of toughness? 

Any solution or alternative?

**Comment by jamuhl** [comment]
Do you get this issue also in https://github.com/i18next/react-i18next/tree/master/example/react-native with latest react-i18next? Guess it works...or at least I hope...did not test that for long.

I'm not sure what you expect from me now? You mix react-native, react-navigation and some next-expo I not even yet heard of (I really do no mobile development myself) --> all these things, at least in the past were a big pain in the ass (especially the react-navigation) (and not because of react-i18next)

**Comment by adrai** [comment]
@5ervant Is there a possibility to create an easy example that reproduces this? So a non-mobile developer is able to quickly look at it?

**Comment by adrai** [comment]
@5ervant regarding the error you have pasted: "TypeError: undefined is not an object (evaluating 'module.type')" it seems like you pass an undefined module when calling i18next.use(somethingUndefined) => https://github.com/i18next/i18next/blob/master/src/i18next.js#L201

How does your i18next initialization looks like?

**Comment by 5ervant** [comment]
@jamuhl **It works with: https://github.com/i18next/react-i18next/tree/master/example/react-native**
A `next-expo` app is just an Expo app created with `yarn next-expo`, that will use `@expo/next-adapter` having your app a `react-native-web` Next.js version.

@adrai Here's my _"i18n.js"_ initialization for Expo, just like https://github.com/i18next/react-i18next/blob/master/example/v9.x.x/reactnative-expo/js/i18n.js :

```
import i18n from 'i18next';
import { reactI18nextModule } from 'react-i18next';
import { Localization } from 'expo-localization';

// creating a language detection plugin using expo
// http://i18next.com/docs/ownplugin/#languagedetector
const languageDetector = {
  type: 'languageDetector',
  async: true, // flags below detection to be async
  detect: callback => {
    return /*'en'; */ Localization.getLocalizationAsync().then(({ locale }) => {
      callback(locale);
    });
  },
  init: () => {},
  cacheUserLanguage: () => {}
};

i18n
  .use(languageDetector)
  .use(reactI18nextModule)
  .init({
    fallbackLng: 'en',

    resources: {
      en: {
        home: {
          title: 'Welcome',
          introduction:
            'This text comes from i18next and is provided in english.'
        },
        page2: {
          title: 'Page 2',
          introduction: 'This text on page two.'
        },
        common: {
          currentLanguage: 'The current language is "{{lng}}"',
          actions: {
            toggleToGerman: 'Deutsch',
            toggleToEnglish: 'English',
            goToPage2: 'Open page 2'
          },
          infoText:
            '<0><0>Eins </O><1>Zwei </1><2>Drei </2><3>Vier </3><4>Fünf</4></O>'
        }
      },
      de: {
        home: {
          title: 'Willkommen',
          introduction: 'Dieser Text ist von i18next und ist in deutsch.'
        },
        page2: {
          title: 'Seite 2',
          introduction: 'Text auf Seite 2'
        },
        common: {
          currentLanguage: 'Die Sprache ist auf "{{lng}}" gesetzt',
          actions: {
            toggleToGerman: 'Deutsch',
            toggleToEnglish: 'English',
            goToPage2: 'Öffne Seite 2'
          }
        }
      }
    },

    // have a common namespace used around the full app
    ns: ['common'],
    defaultNS: 'common',

    debug: true,

    // cache: {
    //   enabled: true
    // },

    interpolation: {
      escapeValue: false // not needed for react as it does escape per default to prevent xss!
    }
  });

export default i18n;

```

**Comment by adrai** [comment]
This is a v9 example, means: `import { reactI18nextModule } from 'react-i18next';` only works with react-native v9.x.x (which is old)
In your dependencies you have v11.x.x (which is newer and better), but works differently:
you need to import: `import { initReactI18next } from 'react-i18next';` and probably change a lot of other stuff: https://react.i18next.com/latest/migrating-v9-to-v10

**Comment by 5ervant** [comment]
@adrai `react-i18next` don't have up-to-date documentation for the latest version for Expo?
What do you suggest, to use https://github.com/i18next/react-i18next/tree/master/example/react-native ? It's acceptable since React world is in a hook era.

And also please help this issue: https://github.com/isaachinman/next-i18next/issues/678
Just to give a little way to make it work on `next-expo` web application?

**Comment by adrai** [comment]
@5ervant feel free to update the expo example for other expo users
