### ISSUE TITLE
returned an object instead of string

### ISSUE THREAD

**Issue by linxu** [i18next/react-i18next#1079]
# Question about react-i18next
en.js
```
export default {
  message: {
    copyright: '2019 - Designed and developed by Linxu'
  }
}
{t('message')}
{t('message.copyright')}
```
How to get the value of an object?

**Comment by jamuhl** [comment]
please at least read the docs or look at the examples...before guessing how it should work...

**Comment by linxu** [comment]
@jamuhl The documentation does not seem to describe the useage of key as object

**Comment by adrai** [comment]
use returnObjects in the options: https://www.i18next.com/translation-function/essentials#overview-options

**Comment by linxu** [comment]
@adrai thanks

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

If you liked my support / work - I would enjoy a coffee sponsored using the “💜Sponsor Button”.

There are many ways to help this project 🙏

**Comment by tiavina-mika** [comment]
Use the option `returnObjects`

```tsx
t('message', { returnObjects: true })
// { copyright: '2019 - Designed and developed by Linxu' }
```
