### ISSUE TITLE
How to handle if any json files are failed to load in react-i18next

### ISSUE THREAD

**Issue by krishnavamsi39** [i18next/react-i18next#1080]
I am keeping JSON files in the public folder and using xhr-backend to load them. And kept

react: {
            useSuspense: true,
            wait: true
         }
so that page will be displayed after all strings are loaded. However in very rare cases 1 or 2 users facing the problem that they can see keys instead of the actual text. (After reloading actual text appeared)

So

1) How could I know in which cases it is happening
2) Even though in the worst case if JSON files are not loaded is there any standard approach to handle those failure cases?

**Comment by jamuhl** [comment]
beside: v10 -> there is no wait option

having useSuspense useTranslation, withTranslation, Translation will trigger that if not loaded yet

checkout the example in the example folder!!!

**Comment by krishnavamsi39** [comment]
Thanks for the reply @jamuhl  I checked the example

If I understood it correctly When we are using suspense if we wrap the component with `withTranslation`.  Translations will automatically get triggered even though fetching failed for the first time. Am I right?

Currently, I am wrapping my App.tsx(root component) like this. 

`someOtherHOC(withTranslation()(App))`

However in our logs for only two users we got below error

`Error: failed parsing /i18n/translations/en.json to json`

As per the error, it seems there might not be valid JSON but how come only two users won't be having valid JSON

Any leads about this issue?

Thank you

**Comment by jamuhl** [comment]
Can also be your server at some points send something invalid...can't say ... you will have to check those cases and check what the response was...I got no access to that information

**Comment by adrai** [comment]
@krishnavamsi39 could you resolve your issue?

**Comment by krishnavamsi39** [comment]
@jamuhl  We are using 

``` import Backend from 'i18next-xhr-backend' ```

As we are having valid JSONs and assuming that the above backend will work with the same behavior in all environments we couldn't figure out exactly in which case it is failing to parse JSONs.
Can you suggest any specific info which we can send to our error logging service so that it would be helpful to debug the issue.

Thank you

**Comment by adrai** [comment]
@krishnavamsi39 in the meantime i18next-xhr-backend has been deprecated.
It can be replaced with i18next-http-backend.
The error comes from here: https://github.com/i18next/i18next-http-backend/blob/master/lib/index.js#L73
So either the backend serves non-json content or the client has some buggy JSON.parse function.
