### ISSUE TITLE
withTranslation with {wait:true}

### ISSUE THREAD

**Issue by imdadul** [i18next/react-i18next#1081]
I am using withTranslation, i18next-xhr-backend, 
& inside the config.  
```
   react: {
      useSuspense: false,
      wait: true,
    },
```
In my component file.
`withTranslation(['wages.wageTypes'])(MyComponent)`

Now, whenever my component is being rendered I am getting the message.
`i18next::translator: missingKey en ns key name key name`. Either way, my component is rendering with filled translations. It's just the log which I don't like.

Since I am loading the namespaces asynchronously that's why the message is showing as long as the namespace is not loaded.

What I want is that the component should wait until the translation files are loaded or not show me those messages.

Can I achieve this without using Suspense?

**Comment by jamuhl** [comment]
again read the docs: https://react.i18next.com/latest/usetranslation-hook#not-using-suspense

**Comment by imdadul** [comment]
Thanks for your quick reply.
Yes, I already read that part. As I understood it, the only way to avoid that is to either using suspense or conditionally rendering loading component based on the value of `tReady`

In that case, then I would say, it would be nice to have another solution to not have that warning. It somehow forcing components to handle that in order to avoid that log.

**Comment by adrai** [comment]
Do you have any suggestion?

**Comment by jamuhl** [comment]
> forcing components to handle that in order to avoid that log

it's there for a reason - not for fun - your application does an invalid render because it has the translations not ready...depending on your net speed this might be just a noticeable flicker - still it's wrong.

So either use suspense, handle the ready state, use v9 with wait: true do not load translations async.

**Comment by imdadul** [comment]
> not for fun

Oh! I thought it was for fun :) @jamuhl 

I understand the point.
