### ISSUE TITLE
ICU Macro Does Not Interpolate Values That Are Inside  Of HTML Tags

### ISSUE THREAD

**Issue by angelojcruzjr** [i18next/react-i18next#1086]
**Describe the bug**

I am trying to take advantage of the `icu.macro` functionality in my project as stated in the [i18next documentation](https://react.i18next.com/misc/using-with-icu-format) and am unable to properly interpolate values that are wrapped in HTML tags.

**Occurs in react-i18next version**

npm versions:
```json
{
    "i18next": "19.3.2",
    "i18next-browser-languagedetector": "4.0.2",
    "i18next-xhr-backend": "3.2.2",
    "babel-plugin-macros": "2.8.0"
}
```

**To Reproduce**

Using either a production build with similar examples as below or the [gist link in the macro source code file](https://astexplorer.net/#/gist/642aebbb9e449e959f4ad8907b4adf3a/4a65742e2a3e926eb55eaa3d657d1472b9ac7970), do the following:

Attempt to interpolate a value with any HTML tags of your choice and observe that the transpilation does not work as expected. Example:
```javascript
import { Trans } from 'react-i18next/icu.macro';
​
const user = 'John Doe';
​
// Will not work - p tag can be any sort of HTML tag
<Trans i18nKey="icu_and_trans">
  <p>
        Happy Birthday, {user}!
  </p>
</Trans>
```

If you do not use HTML tags, however, the interpolation will work just fine, example:
```javascript
import { Trans } from 'react-i18next/icu.macro';
​
const user = 'John Doe';
​
<Trans i18nKey="icu_and_trans">
  Happy Birthday, {user}!
</Trans>

// Results in
<Trans
     i18nKey="icu_and_trans"
     defaults="Happy Birthday, {user}!"
     components={[]}
     values={{user: 'John Doe'}}
/>;
// Additionally, I can use HTML tags but only if they
// DO NOT have a value to interpolate
```

**Expected behaviour**

I am hoping that when I attempt to interpolate values wrapped in HTML tags that the macro will work correctly. Currently I have to use the non-macro `Trans` syntax to get my use case to work. This is fine for now but I am hoping to utilize the more elegant macro syntax in the future.

**OS (please complete the following information):**

- Device: MBP 2019 15"
- Browser: Chrome 80.0.3987.163

**Additional context**

Please let me know if I am not using the macro correctly or if there is a workaround for this - as far as I was able to gather from the documentation there was not. I'm assuming this has something to do with the `processTrans` function within the `transAsJSX` function. I also have not verified if this works or not for `Select` or `Plural` components.

**Comment by jamuhl** [comment]
There are a few tests: https://github.com/i18next/react-i18next/blob/master/test/icu.macro.spec.js

My guess it only fails when having some element around the translation: `<p>text</p>` as inside seems to work `hello <strong>world</strong>` right?

A pullrequest supporting your case would be welcome....

**Comment by angelojcruzjr** [comment]
> My guess it only fails when having some element around the translation: <p>text</p> as inside seems to work hello <strong>world</strong> right?

That is correct, or at least the behavior I am observing.

> A pullrequest supporting your case would be welcome....

Awesome! I will try to have something together by next week sometime.

Thank you for the prompt response 😇

**Comment by jamuhl** [comment]
closing due inactivity
