### ISSUE TITLE
i18next::translator: missingKey [key key]

### ISSUE THREAD

**Issue by viclafouch** [i18next/react-i18next#1087]
### **Describe the bug**
i18next can't translate the keys, but the debugger `init({ debug: true })` displays the resources well and shows that no keys are missing. 

I have errors like that : 

`i18next::translator: missingKey fr translation home.getStarted home.getStarted`
`i18next::translator: missingKey fr translation about about`

I'm using Typescript and Webpack with Babel.

My i18n init : 

![carbon](https://user-images.githubusercontent.com/23353836/79341962-d65e1500-7f2c-11ea-9e1b-f6c3de8323d0.png)

An example of component : 

![carbon (3)](https://user-images.githubusercontent.com/23353836/79342388-5be1c500-7f2d-11ea-8c61-03b5a87b1d30.png)

### **Occurs in react-i18next version**
**"react-i18next": "11.3.4"**
**"i18next": "19.4.1"**

### **To Reproduce**
I created a branch on my project 

1. Clone the repository: `git clone https://github.com/viclafouch/meme-studio.git`
2. Change branch: `git checkout react-i18next-missing-keys`
3. Install the npm dependencies `npm install`
4. Start server: `npm run dev`

### Screenshots

![image](https://user-images.githubusercontent.com/23353836/79341403-0822ac00-7f2c-11ea-8439-3e73e09ef634.png)

### **Expected behaviour**
A correct translation

### **OS (please complete the following information):**

- Browser:  Chrome 80.0.3987.163

### **Additional context**
What I can't explain, it's working in env Production, but not in env Dev, maybe something related to webpack dev server ? 

My webpack rules : 

![carbon (2)](https://user-images.githubusercontent.com/23353836/79342162-1624fc80-7f2d-11ea-8001-cd80d98420ae.png)

**Comment by adrai** [comment]
Can you log how translationFR looks like after importing?

**Comment by viclafouch** [comment]
Hello @adrai and thank you for your reply, here what you ask : 

### DEV

![image](https://user-images.githubusercontent.com/23353836/79360368-1bda0c80-7f44-11ea-81f8-6f19797e8217.png)

### PROD

![image](https://user-images.githubusercontent.com/23353836/79360600-72dfe180-7f44-11ea-8570-82ad3da42e9f.png)

What's the difference with the `default` key inside the `fr` object ?

**Comment by adrai** [comment]
something in your webpack config...

**Comment by adrai** [comment]
seems during dev something is adding the "default" export to the json files

**Comment by viclafouch** [comment]
Ok just found the solution from https://github.com/webpack/webpack/issues/8504

> import * as config from './config.json' will give you the generate namespace object from the json module.

> require('./config.json') will give you the raw json data <= **That's what I need**

We can close this issue, thanks for the reply btw !

**Comment by KarimElsayad247** [comment]
Currently facing this same problem, it's looking for key key

I'm using create-react-app, so I don't know exactly what webpack configs there are

**Comment by KarimElsayad247** [comment]
Ok, so it turns out my problem was that I didn't pass the context to `useContext` hook, so it was not loaded. It was a quirk of react-i18next Backend configs.
