### ISSUE TITLE
There are four "getting start" guides in the project

### ISSUE THREAD

**Issue by rafalp** [i18next/react-i18next#1091]
**Describe the bug**

I am looking for i18n library for my React.js project, and decided to give `react-i18next` a try. However when I've started reading the docs I've quickly became confused because there are four documents describing initial setup, each subtly different from other:

1. Project's readme
2. Getting started: https://react.i18next.com/getting-started
3. Quick start: https://react.i18next.com/guides/quick-start
4. Step by step guide: https://react.i18next.com/latest/using-with-hooks

In addition, neither readme nor getting started tell me that I have to install `i18next` in addition to `react-i18next`.

**Occurs in react-i18next version**
Latest one.

**To Reproduce**
n/a

**Expected behaviour**
I feel that there's a considerable level of fragmentation within project's docs - its reads more like collection of different articles written in separation of each other than concise guide where each article is logic continuation of previous one.

I feel that instead of multiple guides there should be a single guide split into multiple articles, telling complete story of how one could use the library to add I18n to their project:

1. Initial setup: install lib, create `i18n.js` with most basic configuration
2. Translate strings using `t()`, then `<Trans>`, storing translations on `i18n` instance
3. Extracting translations to separate files, loading translations, namespaces?
4. Pluralization and localization of numbers and dates/datetime, using `Intl.Locale`.
5. Changing language in running application, eg. when user changed language in the UI.

**Screenshots**
n/a

**OS (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by jamuhl** [comment]
Thank you for reaching out. That would be great. Mind creating a PR on the docs branch to improve the documentation?

**Comment by rafalp** [comment]
Thank for an offer, but I'm afraid I am not able to.

Documentation should be written by a person that knows the library, and I'm not such person. :(

**Comment by jamuhl** [comment]
And I thought documentation should be written by technical writers or at least a person talking native English or at least more talented in writing than the author of this lib 😄

Well closing for now...both of us seem to be not able to solve this issue...
