### ISSUE TITLE
is there a way to use locale subpath with next.js v.9.x.x ? 

### ISSUE THREAD

**Issue by toltarisa** [i18next/react-i18next#1093]
Hi i'm using react-i18next with my Next js TypeScript project successfully.Everything is fine but i need to add language to the path as prefix.

like http://localhost:3000/en/blog or http://localhost:3000/nl/blog according to language.
how can i achieve this with this package ?

**Comment by jamuhl** [comment]
better ask this over at https://github.com/isaachinman/next-i18next this request has nothing todo with react-i18next
