### ISSUE TITLE
Invalid module name in augmentation. Module 'i18next' resolves to an untyped  module {...} which cannot be augmented.

### ISSUE THREAD

**Issue by omribitan** [i18next/react-i18next#1094]
**Describe the bug**
During build, I keep getting the following error:

> ../../node_modules/react-i18next/src/index.d.ts(26,16): error TS2665: Invalid module name in augmentation. Module 'i18next' resolves to an untyped
 module at '/Users/omribitan/Workspace/rf-mono/node_modules/i18next/index.js', which cannot be augmented.

**Occurs in react-i18next version**
npm module version, git tag or even better the explict commit causing the issue
"i18next": "^10.6.0"

My tsconfig.js looks like this:

```{
  "include": [
    "src/index.ts",
    "src/commonMiddleware.js",
    "src/generate.*.js",
    "src/generate.*.ts",   
    "src/runFrontend.ts",
    "src/newrelic.js",
    "src/**/*.ts",
    "src/**/*.js",
    "src/**/*.json",
    "tests/**/*.ts"
  ],
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "rootDir": "./",
    "outDir": "./build",
    "allowJs": true,
    "strict": false,
    "types": [      
      "googlemaps", 
      "markerclustererplus"
    ]
  },
  "references": [
    {"path": "../lib"}
  ]
}
```

**Comment by adrai** [comment]
Can you try with the newest version?

**Comment by adrai** [comment]
i18next an react-i18next

**Comment by omribitan** [comment]
That worked! tnx!

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.  If you liked my support / work - I would enjoy a coffee sponsored using the “💜Sponsor Button”.  There are many ways to help this project 🙏
