### ISSUE TITLE
i18next.exists() check returns false for keys that were added with addResourceBundle()

### ISSUE THREAD

**Issue by alekseykarpenko** [i18next/react-i18next#1095]
First of all, thx for all ya doing! 
I have a strange behavior, that seems to be a bug for me. I'm not sure if it's related to `i18next` or `i18next-react`, but im currently working with React, so decided to put it here.

**Describe the bug**
`i18next.exists()` doesn't work for keys that were added after init with `addResourceBundle()`: it always returns `false`, even while `t()` function (called in same place) returns an actual translation for that key.
 
**Occurs in react-i18next version**
```json
"dependencies": {
    "i18next": "19.4.3",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-i18next": "11.3.5",
    "react-scripts": "3.4.1"
  },
```
*Note: also checked some of previous versions (`i18next v17.X` and `react-i18next v10.X`*)

**To Reproduce**

```js
import React, { useState, useEffect } from "react";
import { useTranslation } from "react-i18next";

export default function App() {
  const { t, i18n } = useTranslation("translations");

  const [loaded, setLoaded] = useState(false);

  useEffect(() => {
    i18n.addResourceBundle("en", "translations", { test: "New added value" });
    setLoaded(true);
  }, [i18n]);

  // expecting `true New added value' here after `loaded` becomes true
  console.log(i18n.exists("test"), t("test"));

  return (
    <div className="App">
      <h2>{t("welcomeMsg")}</h2>
      {loaded && i18n.exists("test") && <p>{t("test")}</p>}
    </div>
  );
}
```

Sandbox: https://codesandbox.io/s/react-i18next-example-xc97h?file=/src/app.js
*(see Console Output)*

**Expected behaviour**
I expect `i18next.exists()` should work the same way `t()` function does. When a key is already available and can be accessed with `t(key)` -> `i18n.exists(key)` also should return `true` 

**Screenshots**
Console Output:
![image](https://user-images.githubusercontent.com/4648983/79804387-9653c380-836c-11ea-9f54-33498f15769e.png)

**OS:**
- Device: MBP 2015 13"
- Browser: Chrome 80.0.3987.163

**Comment by jamuhl** [comment]
They work the same...it's just a little tricky to find what is going wrong:

both `t` and `exists` use the same function to find a translation. They look ordered in lng and namespaces given:

`t` -> comes from useTranslation and is a i18n.getFixedT ---> namespace to lookup is set to `translations`

`exists` -> get namespace not set to `translations` and can't detect it via `ns:key` so it takes the defaultNS which is as default set to `translation` not `translations`

solutions:

a) set `defaultNS: 'translations' on init
b) use `i18n.exists("translations:test")`

**Comment by alekseykarpenko** [comment]
Arghhh my fault, I should enable my logic before asking lol :)
@jamuhl thanks for your response! I will now close this ticket. Hope it will be useful for those who will fail in the same way in future

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

If you liked my support / work - I would enjoy a coffee sponsored using the “:purple_heart:Sponsor Button”.

There are many ways to help this project :pray:
