### ISSUE TITLE
Improvement. It seems `raf` dev dependency is useless.

### ISSUE THREAD

**Issue by iamandrewluca** [i18next/react-i18next#1103]
In 82cf0f648c610bf06621012d7b54f612977f485c was added [`raf`](http://npm.im/raf) polyfill when running tests with commit message:

> Fix requestAnimationFrame warning in tests

As I see even when removing this polyfill tests run without any warning.
Also `i18next` and `react-i18next` doesn't have any reference to `requestAnimationFrame`

I'd recommend to remove it.

**Comment by jamuhl** [comment]
agree....will remove that asap
