### ISSUE TITLE
Interpolate all nested descendants with Trans component

### ISSUE THREAD

**Issue by bdrazen** [i18next/react-i18next#1104]
Given some markup like:
```
<Trans i18nKey='some_key'>
  <sup>
    <a href=''
      onClick={openModal}
      aria-label='1 superscript opens modal'>1</a>
  </sup>
</Trans>
```
My translation string would have to be:
```
"some_key": "Some text<0><0><0/></0></0> and more text"
```
Would be nice if there were some way to just specify all descendants to be included without having to explicitly drill into each one.

Not sure if there would be any issue with simply enabling this behavior by default for self-closing tags:
```
"some_key": "Some text<0/> and more text"
```

Otherwise, perhaps something like:
```
"some_key": "Some text<0+/> and more text"
```

**Comment by jamuhl** [comment]
https://github.com/i18next/react-i18next/pull/859 might improve it...

PR welcome...
