### ISSUE TITLE
Interpolation in combination with returnObjects does not work

### ISSUE THREAD

**Issue by danielbayerlein** [i18next/react-i18next#1106]
**Describe the bug**

Interpolation in combination with `returnObjects` does not work, because the placeholder is not replaced.

**Occurs in react-i18next version**

```json
{
  "i18next": "^19.4.4",
  "i18next-xhr-backend": "^3.2.2",
  "react-i18next": "^11.4.0"
}
```

**To Reproduce**

```json
{
  "requirements": [
    "Lorem Ipsum",
    "Lorem Ipsum",
    "Hello {{name}}"
  ]
}
```

```javascript
const Test = ({ t }) => (
  <ul>
    {t('requirements', { returnObjects: true, name: 'Elon' }).map((r) => <li key={r}>{r}</li>)}
  </ui>
)

export default withTranslation()(Test)
```

**Expected behaviour**

```javascript
[
  "Lorem Ipsum",
  "Lorem Ipsum",
  "Hello Elon"
]
```

instead of

```javascript
[
  "Lorem Ipsum",
  "Lorem Ipsum",
  "Hello {{name}}"
]
```

**OS:**

- Device: MacBook Pro 13" (2017) with macOS 10.15.3
- Browser: Chrome 81.0.4044.129

**Additional context**

If I use `joinArrays` instead of `returnObjects` the interpolation works.

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next/blob/master/test/translator/translator.translate.returnObject.spec.js#L75 test does work

not sure why you expect a array to be transformed into an object:

```js
  "requirements": [
    "Lorem Ipsum",
    "Lorem Ipsum",
    "Hello {{name}}"
  ]
```

should be

```js
{
  "Lorem Ipsum",
  "Lorem Ipsum",
  "Hello Elon"
}
```

If you like the result to be an object use an object in translation file:

```js
  "requirements": {
    "Lorem Ipsum",
    "Lorem Ipsum",
    "Hello {{name}}"
  }
```

**Comment by danielbayerlein** [comment]
Sorry my mistake! Of course I expect an array and not an object. (-> updated the description)

**Comment by danielbayerlein** [comment]
```json
{
  "test": [
    "Lorem",
    "Ipsum",
    "Hello {{ name }}"
  ]
}
```

```javascript
t('test', { returnObjects: true, name: 'Elon' })
```

**Current return value:**

```js
["Lorem", "Ipsum", "Hello {{ name }}"]
```

**Expected return value:**

```js
["Lorem", "Ipsum", "Hello Elon"]
```

**Comment by adrai** [comment]
in plain i18next it seems to work:

```js
i18next.init({
  debug: true,
  fallbackLng: 'en',
  lngs: ['en'],
  resources: {
    en: {
      translation: {
        array: [
          "Lorem",
          "Ipsum",
          "Hello {{name}}"
        ]
      }
    }
  }
})

console.log(i18next.t('array', { returnObjects: true, name: 'Elon' })) // [ 'Lorem', 'Ipsum', 'Hello Elon' ]
```

**Comment by jamuhl** [comment]
wondering why it should not work - react-i18next forwards a `t` function created by i18next.getFixedT

A codesandbox for reproduction might help reproducing this

**Comment by danielbayerlein** [comment]
I created a codesandbox → https://codesandbox.io/s/dry-grass-tcg4f

**Comment by adrai** [comment]
try to set keySeparator to true

**Comment by danielbayerlein** [comment]
@adrai Yeah, that works. Thanks a lot! 💚

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.  If you liked my support / work - I would enjoy a coffee sponsored using the “💜Sponsor Button”.  There are many ways to help this project 🙏
