### ISSUE TITLE
useTranlation not working with basic html

### ISSUE THREAD

**Issue by wellyal** [i18next/react-i18next#1107]
I've been looking at the documentation and issues and didn't find anything related to "how can I use `useTranslation` and keep the basic inline html like ***strong***, ***i***, etc." 

I've seen that you have a default setup for `<Trans>` component to escape those values as html. But I couldn't find anything related to this on `useTranslation`. Am I missing something? Is there anything I need to pass to useTranslation so I can make it work? Or this feature is actually not supported yet when using the hook function.

https://github.com/i18next/react-i18next/blob/af220c27b6b56f43b9dc5dc8118ad9664be2d802/src/Trans.js#L30

**Comment by jamuhl** [comment]
react is not html -> you can't just take some HTML from translations and put it inside a react element and hope it magically gets converted from HTML into react elements ---> that's what Trans component does. So use the Trans component for such cases.

**Comment by wellyal** [comment]
Hum, you can actually do that by using [dangerouslySetInnerHTML](https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml). You just need to check withing the strings what is being inserted to avoid other tags than what you want like simple format inline tags.

**Comment by jamuhl** [comment]
so...use dangerouslySetInnerHTML...or Trans...there is no reason it should not work
