### ISSUE TITLE
Trying not to use suspense, getting suspense errors

### ISSUE THREAD

**Issue by Aldrian** [i18next/react-i18next#1109]
Hi!
Due to specific project constraints, I would like to handle the loading state of the translations as far down as I can, with minimum refactoring.

I previously had a `<Suspense>` component wrapping my application, but getting a proper fallback was difficult, and I had loaders when loading a new namespace, breaking my layout.

I chose to override my withTranslation / useTranslation imports for minimal refactoring, replacing them with essentially the same thing, but with their loader inside the `t()` call.

Code is available here: 

- useTranslation.js: https://gist.github.com/Aldrian/33708e49ec2429a0c77129d2855be2ee
- withTranslation.js: https://gist.github.com/Aldrian/027b08ae69e757abbd9a47341fbf5d53

I initially tried to wrap my `CustomT` with a `<Suspense>` component, but since it was called below `useTranslation` it wasn't working. I chose to opt-out of suspense by using `useSuspense: false` in each `useTranslation` usage, and set useSuspense to false in the i18n configuration

- i18n.js: https://gist.github.com/Aldrian/206519cd8c5c2b58f2eb0ffd639e5c5b

With everything set to false, I removed the root <Suspense> component, checked that no useTranslation and withTranslation were imported straight from react-i18n and still got a suspense error:

> Error: A React component suspended while rendering, but no fallback UI was specified. Add a <Suspense fallback=...> component higher in the tree to provide a loading indicator or placeholder to display. in Unknown (at withTracker.js:36) in HOC (created by Context.Consumer) in Route (at Body.js:143) in Switch (at Body.js:142) in main (created by Context.Consumer) in Styled(main) (at Body.js:125) in Query (at Body.js:109) in Body (created by I18nextWithTranslation) in I18nextWithTranslation (created by Context.Consumer) in withRouter(I18nextWithTranslation) (at src/index.js:68) in SentryReporter (created by I18nextWithTranslation) in I18nextWithTranslation (created by Context.Consumer) in withRouter(I18nextWithTranslation) (at src/index.js:67) in Router (at src/index.js:65) in ApolloProvider (at src/index.js:64)

Any pointers?

Thanks!

**Comment by jamuhl** [comment]
-> debugging and find the trigger throwing a Promise - nothing I can do from here

**Comment by Aldrian** [comment]
I'm sorry but could you be more specific? I thought using `useSuspense: false` was bypassing the Suspense promise?

**Comment by jamuhl** [comment]
It does: https://github.com/i18next/react-i18next/blob/master/src/useTranslation.js#L83

That's why you need to debug...either you missed somewhere to replace our `useTranslation` with yours...or something else is triggering

**Comment by Aldrian** [comment]
That's what've seen

The only thing I'm doing, in the two gist provided above is : 

- Calling the original useTranslation, with `useSuspense: false`
- Returning `i18n`, and replacing `t` with a function component that uses `ready` in a ternary

See this gist: https://gist.github.com/Aldrian/33708e49ec2429a0c77129d2855be2ee#file-usetranslation-js-L12

I guess useSuspense is not passing down on useTranslation, but I do not see why

**Comment by jamuhl** [comment]
And what I guess...you missed somewhere an`import { useTranslation } from 'react-i18next'`

**Comment by Aldrian** [comment]
You were right. I checked for all imports, and it ended up being a React.lazy() component defined somewhere in the tree that was needing suspense.

Sorry for the trouble!
