### ISSUE TITLE
JSON.Parse error: parsing "foo" on StorageEvent "i18next.translate.boo"

### ISSUE THREAD

**Issue by najibghadri** [i18next/react-i18next#1111]
Hello! I have been using i18next react for a short time and this started a while ago. I checked all of my translations files, they are all valid, no typos, and it strongly seems unrelated from my code.

What happens:
For the record I have no idea what causes this, but it does not fire when I change the language, it happens on other events related to my code but IMO unrelated to i18next. 

The verbose error context is below. My guess this is a health check for i18n and it puts a bad json, specificall the string "foo" on a storage event keyed "i18next.translate.boo". Again no idea what is up, but it is annoying on deveolpent debugging and it spams the console with error logs. 

![image](https://user-images.githubusercontent.com/11639734/81510148-fb695c00-930f-11ea-97b8-8551ac88d2cd.png)
![image](https://user-images.githubusercontent.com/11639734/81510286-efca6500-9310-11ea-8038-2aac3593f39e.png)

So it is related to localStorage persistence

**Comment by najibghadri** [comment]
I think I managed to find out what is _also_ causing this, roughly. It also happens when a Storage event is fired due to change in languaage another tab. I change language to "en" with changeLanguage, then on the other tab the same error in the same place as above fires but newValue is "en". So as I assumed earlier it might easily be a health check function, but there if there is a loopback with the event it goes into a JSON parse for whatever reason. That is the root of the problme IMO. For now I can not solve this, not with debug true option either

**Comment by adrai** [comment]
It’s probably i18next-browser-languageDetector: https://github.com/i18next/i18next-browser-languageDetector/blob/master/src/browserLookups/localStorage.js#L4

Is your localstorage api broken?
Can you reproduce this ina codesandbox example?

**Comment by najibghadri** [comment]
I will try soon!

**Comment by najibghadri** [comment]
Not exactly closed but ok 😅

**Comment by jamuhl** [comment]
Sorry ... was too actively cleaning up our issues list...

**Comment by najibghadri** [comment]
It's okay, I did not forget it, will try to reproduce soon!

**Comment by jamuhl** [comment]
@najibghadri is this still relevant...keeping this endless open does not help solving it

**Comment by najibghadri** [comment]
Hello @jamuhl @adrai . I did try to reproduce it in a sandbox but I couldn't. As I said it is simple to reproduce on localhost: open two tabs of the same domain (can be localhost) and change the language in one of them. In the other one the following errors will be thrown.
![image](https://user-images.githubusercontent.com/11639734/84790598-ced0f000-aff1-11ea-8440-7cb9a50169b0.png)
I think it happens due to a localStorage listener and obviously erronous code.
There are other triggers for the error, it's in the same part of the code, but I could not find other, this is the most obvious. 

For now I use this library in my website and these errors don't seem to affect the site. So it's your decision from here. Thanks!

**Comment by adrai** [comment]
> As I said it is simple to reproduce on localhost: open two tabs of the same domain (can be localhost) and change the language in one of them. In the other one the following errors will be thrown.

Can you creat a reproducable example? Codesandbox or repository we could try with? Can’t reproduce this.

**Comment by jamuhl** [comment]
Looking at your error this looks not like an issue with i18next but more with some of your state hydration from use-persisted-state

there is technical nothing that is shared between tabs -> language is only detected once on load - not on change in other tab (there is no magic glue)

**Comment by najibghadri** [comment]
Okay, well, unfortunately I don't have time now to reproduce it, perhaps in the next two weeks, but as I said it doesn't break my site. BTW, my site is [https://quarantime.io/](https://quarantime.io/) (not advertising.. 😃 ). The error shows there if you open two tabs with the same room.

Another option is, if you prefer, you close this and if I can reproduce it later I will reopen it.

**Comment by adrai** [comment]
seems this happens already when you just open your site (without doing anything) in 2 different tabs:
![image](https://user-images.githubusercontent.com/1086194/84857154-ae904800-b068-11ea-9956-e870d8630815.png)
Also this guy: https://github.com/donavon/use-dark-mode/issues/38 is having the same problem, without using i18next at all...
This is [use-persisted-state](https://github.com/donavon/use-persisted-state) listening to the localstorage events and always expecting to save a json... (strange behaviour, IMO)
https://github.com/donavon/use-persisted-state/issues/31
https://github.com/donavon/use-persisted-state/issues/16
=> better use: https://github.com/astoilkov/use-local-storage-state

will close as this is not related with i18next.

**Comment by najibghadri** [comment]
Wow, thanks a lot! :) Sorry. :(

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏
