### ISSUE TITLE
Is there a way to trigger rerender after addResourceBundle

### ISSUE THREAD

**Issue by bidiu** [i18next/react-i18next#1112]

**Comment by jamuhl** [comment]
fires added event: https://github.com/i18next/i18next/blob/master/src/ResourceStore.js#L100

you can bind store events to trigger a rerender: https://react.i18next.com/latest/i18next-instance (options)

**Comment by bidiu** [comment]
Oops, I didn't realize I clicked "Submit" after seeing "questions should be posted on StackOverflow". Thanks for your quick reply. I worked around this question by a diferent approach. Will definitely try out your suggestion.

Now that the ticket is here, I will try to add more details. So my use cases are somewhat different. Even though down the line we probably will suport full i18n, for now we are only using i18next doing key substitutions, where keys are regular text in "en", and mapped translations are user-defined substitutions stored in database. There really is no locale other than just "en".

Given the scenario, I don't want to use the backend plugins such as `i18next-http-backend` to fetch the substitution list or do caching, because to my understanding, they are overkill for my cases. And I don't have static locale files stored on server.

So after seeing this method `addResourceBundle`, I thought I can load the resoures my self and add it to the i18n instance, expecting UI will be re-rendered (I am using useTranslation hook). This is the orignal of the question.

I ended up prefetching resources on init by not passing `resources` in `InitOptions`, and a custom backend plugin doing the fetch:
```
class InflowBackendPlugin {
  static type: 'backend' = 'backend'
  constructor(services: Services, backendOptions: object, i18nextOptions: InitOptions) {
    // noop if don't use any serivces shipped with i18next and custom options
  }

  read(language: string, namespace: string, callback: ReadCallback) {
    // setTImeout to mimic async request
    setTimeout(() => {
      if (language === 'fr') {
        callback(null, {
          'Sales order': 'Translated "Sales order" in French',
        })
      } else {
        callback(null, {
          'Welcome to React': 'Welcome to react-i18next (from library examble)',
          'Sales order': 'Renamed "Sales order"',
          'Location': 'Bin (renamed from "Location")',
          'purchase order': 'purchase order',
          'purchase order_plural': 'purchase orders'
        })
      }
    }, 3000)

    // if method fails/returns an error, call this:
    //    callback(truthyValue, null);
  }

  save(language: string, namespace: string, data: ResourceLanguage) {
    // noop
  }

  createfunction(languages: string[], namespace: string, key: string, fallbackValue: string) { 
    // noop
  }
}
```

**Comment by jamuhl** [comment]
I like that...a little more work -> but at the end - simpler to exchange if you eg. switch using a server backend or locize.com

**Comment by n-dragon** [comment]
tks, 
it's working.  
what is the difference between bindStore and bindI18n?  
when to use one rather than another ?

**Comment by jamuhl** [comment]
bindI18nStore -> are events on store (added keys, ... not needed for most cases)
bindI18n -> events on i18next (changeLanguage, initialize, ...)

**Comment by tylergraf** [comment]
Docs aren't super clear on that. Thanks for clarifying.

**Comment by jamuhl** [comment]
@tylergraf it's always hard to write good documentation (sitting in the forest not seeing the trees - hard for me to see were users could struggle) -> PR's to improve the docs are very appreciated
