### ISSUE TITLE
withTranslation not compatible if there is already a custom prop

### ISSUE THREAD

**Issue by jtrelfa** [i18next/react-i18next#1113]
Describe the bug
I tried to use the withTranslation to my class that already has properties. I get an error "Property X is missing in type 'WithTranslation' but required in type"

Steps to reproduce
```
interface StateTypes {
  user: UserCredentials;
  rememberMe: boolean;
}

@inject("store")
class Login extends Component<{ store: Store }, StateTypes> {
  state: StateTypes = {
    user: {
      username: "",
      password: ""
    },
    rememberMe: false
  };
}
export default withTranslation('common')(Login); //<-- here is the error
```
What's the best way to define the class so that it is compatible with "withTranslation"? I added an additional property (t:Function) in the class definition but that didn't seem to work, either..

**Comment by rosskevin** [comment]
Look at the `test/typescript` directory for usage examples.  You have incorrectly defined the props for the given component.
