### ISSUE TITLE
Text is shrunk if translated text is longer than original text

### ISSUE THREAD

**Issue by jahicDario** [i18next/react-i18next#1114]
**Describe the bug**
Text is shrunk if translated text is longer than original text

**Occurs in react-i18next version**
^10.0.0

**To Reproduce**
1. Original string takes two rows
2. Translated string takes three rows 
3. Only 2 rows of translated strings is shown

**Expected behaviour**
Whole string to be shown. 

**OS (please complete the following information):**
Samsung S9+
OS: Android 10

**Comment by adrai** [comment]
Please provide a codesandbox example or similar...

**Comment by jamuhl** [comment]
react-native right? Text component - react-i18next has not influence on setting rows number

**Comment by adrai** [comment]
https://stackoverflow.com/questions/55487695/react-native-text-component-using-number-of-lines

**Comment by jahicDario** [comment]
I forgot to mention that the problems occur in ReactNative inside Text component.

**Comment by adrai** [comment]
@jahicDario please test if the same text without using the t function inside your Text component is also truncated

**Comment by jahicDario** [comment]
> @jahicDario please test if the same text without using the t function inside your Text component is also truncated

If I remove trans component, the text is not truncated.

**Comment by adrai** [comment]
Can you paste here your code snipped?

**Comment by adrai** [comment]
Maybe have also a look at: https://github.com/i18next/react-i18next/issues/271#issuecomment-627125147

**Comment by jahicDario** [comment]
I found out that the problem is when translated string is in format: ""\u0410\u043a\u043e \u0442\u0435\u0437\u0438 ... ". It is a case when you use Serbian Cyrillic for example.

**Comment by adrai** [comment]
so a react-native problem?

**Comment by jahicDario** [comment]
> so a react-native problem?

Yes, it seems so. Thank you for your help.
