### ISSUE TITLE
Expected identifier, string or number in EDGE

### ISSUE THREAD

**Issue by Stepan-Naryshkov** [i18next/react-i18next#1116]
# Question about react-i18next
Hi everyone. I use this example https://github.com/i18next/react-i18next/tree/master/example/razzle-ssr . After running it I see an error in edge ```SCRIPT1028: SCRIPT1028: Expected identifier, string or number```
**Bundle**
![image](https://user-images.githubusercontent.com/49309725/82191370-15e89a00-98fb-11ea-9224-28f29f827316.png)
**Package**
![image](https://user-images.githubusercontent.com/49309725/82191486-44667500-98fb-11ea-9e26-cf2ff80eda4d.png)

It seems that razzle transforms `var` to `const` and `_objectSpread` to `...`.
So the question, how can I prevent it? Because edge browser is broken in this case. As I understood, razzle supports edge by default

**Comment by adrai** [comment]
It’s not react-i18next.... it’s i18next-http-backend... 
see: https://github.com/i18next/i18next-http-backend/issues/11

**Comment by Stepan-Naryshkov** [comment]
I was close...

**Comment by adrai** [comment]
@Stepan-Naryshkov I updated the example to import from i18next-http-backend/cjs
