### ISSUE TITLE
Improved React Component interpolation syntax

### ISSUE THREAD

**Issue by philippefutureboy** [i18next/react-i18next#1118]
**Is your feature request related to a problem? Please describe.**

I find the Trans component convoluted and hard to use.
I don't think that having the base translation directly in the component is good design as it mixes up responsibilities of presentational components with that of the translations. Plus, from one language to another the order of tags can change significantly which makes an order-based tag system weird to use.
I could not find a convenient way of integrating react components as part of a translation.
I would prefer not to have translation directly in my code.
I would like to propose three alternatives, described below.

**Describe the solution you'd like**

Proposition 1: Interpolation of React Components

This is the simplest of all the propositions, client-interface wise. React components can be directly interpolated as values in the translation, and will not be casted to strings.

```yaml
key:
  container: "I like {{apples}} and {{oranges}}"
  interpolations:
    apples: apples
    oranges: oranges
```

```jsx
const Component = (props) => {
  const t = useTranslation("namespace");
  return <div>{
     t("namespace:key.container", {
        apples: <span css={css`color: red;`}>{t("namespace:key.interpolations.apples")}</span>
        oranges: <span css={css`color: orange;`}>{t("namespace:key.interpolations.oranges")}</span>})
  }</div>;
};
```

Advantages:

* No trans component
* No need to have base translation in the markup
* No automated tag naming with numbers that are not necessarily expected

Disadvantages:

* Does not look like normal markup

Proposition 2: Support for extended Trans markup syntax

This proposition opts for a key-value approach where the tags for the React components can be identified via a property "transId" on the component:

```yaml
key:
  container: "I like <apples/> and <oranges/>"
  interpolations:
    apples: apples
    oranges: oranges
```

```jsx
const Component = (props) => {
  const t = useTranslation("namespace");
  return <div>
    <Trans
       i18nKey="namespace:key.container"
       values={{}}
   >
      <span transId="apples" css={css`color: red;`}>{t("namespace:key.interpolations.apples")}</span>
     <span transId="oranges" css={css`color: orange;`}>{t("namespace:key.interpolations.oranges")}</span>
    </Trans>
  </div>;
};
```

Advantages:

* No need to have base translation in the markup
* No automated tag naming with numbers that are not necessarily expected
* Looks like normal markup

Disadvantages:

* May be a breaking change / have to ensure namespacing (not to override normal html tags)

Proposition 3: (breaking) Improved ordering of tags

This solution proposes to keep the implementation as is, but the number by which the tags are identified corresponds to the order of the tags, not order of the children. As such, string children or value children are ignored in the count.

Advantages:

* Same syntax as previously
* Simple to know the ordering of the tags
* Looks like normal markup

Disadvantages:

* Translation is in the markup
* Is a breaking change

What do you think?

Cheers!
Philippe

**Comment by adrai** [comment]
probably related: https://github.com/i18next/react-i18next/pull/859

**Comment by jamuhl** [comment]
You already can: https://react.i18next.com/latest/trans-component#alternative-usage and yes there is already a forever pending PR https://github.com/i18next/react-i18next/pull/859
