### ISSUE TITLE
Inference issue while using withTranslation() with TypeScript 3.9

### ISSUE THREAD

**Issue by clementgarbay** [i18next/react-i18next#1122]
I'm trying to upgrade a big project to TypeScript 3.9 but I encounter some typing error caused by the `withTranslation` HOC. It seems that props inferring from old prop types definition (for JSX files) don't work properly.

- `i18next`: 19.4.4
- `react-i18next`: 11.5.0 (but I also have the issue with versions <10)
- `typescript`: 3.9.3

I created a [very small project](https://github.com/clementgarbay/debug-ts39) to reproduce the problem. If you start it, you will see the error of the wrong assignation from the type returned by the `withTranslation` HOC.

```
Type '{ name: string; }' is not assignable to type 'IntrinsicAttributes & Pick<WithTranslation, never> & WithTranslationProps & { children?: ReactNode; }'.
```

Note that I don't have this issue with version 3.8 of TypeScript or without this HOC.

Maybe I miss something, don't hesitate for more info if needed.

**Comment by rosskevin** [comment]
You are using jsx, not tax, and your types declared I'm Hello.jsx don't include extending `WithTramslation`.

Your example is incorrect as far as I can tell.  Look at the code in `test/typescript` for proper usage.

**Comment by clementgarbay** [comment]
Yes this is in fact my issue. I've deliberately used a jsx file because I have many components that still use this syntax for prop types definition (if you rename the file to tsx the problem stays the same btw). Before TS 3.9 the type on my component was correctly inferred from the `propTypes` but with this new version of TS the type signature of the `withTranslation` HOC seems to break this inference (maybe because of some breaking changes related to the stricter checks on intersections and optional properties).

**Comment by rosskevin** [comment]
It appears to me that pre-3.9 it ignored the file and now it gives you an error that it is not typed properly.

In that case, this doesn't appear to be a problem with our definition, but a problem with your setup or a problem with typescript, so I'm going to leave this closed unless we have some information that points to a defect in our type definitions.

**Comment by svengau** [comment]
Hi @clementgarbay I've got the same issue than you. Could you share how you've solved it ? thx

**Comment by xseman** [comment]
I'm having same problem when trying to handle union `props`.

```tsx
export enum ResourceType {
    LOCAL,
    REMOTE,
}

type Local = {
    type: ResourceType.LOCAL;
   // some props, based on type
}

type Remote = {
    type: ResourceType.REMOTE;
    // some props, based on type
};

export type Props = WithTranslation & (Local | Remote);

class SomeComponent extends React.Component<Props, State> {
...
}

export default withTranslation()(SomeComponent);
```

Works ok without `withTranslation()(...)`. When trying to use "some props" based on `type`:

```plain
Type '{ type: ResourceType.LOCAL;  // some props... }' is not assignable to type 'IntrinsicAttributes & Omit<Subtract<Props, WithTranslationProps>, keyof WithTranslation<N>> & WithTranslationProps & { ...; }'. Property '// some props...' does not exist on type 'IntrinsicAttributes & Omit<Subtract<Props, WithTranslationProps>, keyof WithTranslation<N>> & WithTranslationProps & { ...; }'
```

**Comment by akinnee** [comment]
@xseman I'm having that exact same problem.

**Comment by xingqiwu55555** [comment]
> I'm having same problem

Me too, same problem. @xseman

**Comment by krmao** [comment]
![image](https://github.com/i18next/react-i18next/assets/7344437/90b2d8d5-8979-4907-8087-0c681a97d4c5)
![image](https://github.com/i18next/react-i18next/assets/7344437/d2f50ef6-6367-4ceb-b807-247218952e72)

how to fix now? @rosskevin 


```
    "i18next": "^23.5.0",
    "react": "18.2.0",
    "react-i18next": "^13.2.2",
    "react-native": "0.72.4",
```

**Comment by krmao** [comment]
> ![image](https://private-user-images.githubusercontent.com/7344437/291170563-90b2d8d5-8979-4907-8087-0c681a97d4c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4ODYzNTAsIm5iZiI6MTcwMjg4NjA1MCwicGF0aCI6Ii83MzQ0NDM3LzI5MTE3MDU2My05MGIyZDhkNS04OTc5LTQ5MDctODA4Ny0wYzY4MWE5N2Q0YzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMThUMDc1NDEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTAxZmFkMTQwNGU2OTBlNjE2NzMwYzNkM2M4MjU1YzAzOGRkNmQ4NGU4MWZlMWNkZjg4MGVhYmI4YjNkZWRmZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uiAh5R7fDS_Hcpmy5m0HFCmtaJc3nSwsLdglJNRKTG8) ![image](https://private-user-images.githubusercontent.com/7344437/291170626-d2f50ef6-6367-4ceb-b807-247218952e72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4ODYzNTAsIm5iZiI6MTcwMjg4NjA1MCwicGF0aCI6Ii83MzQ0NDM3LzI5MTE3MDYyNi1kMmY1MGVmNi02MzY3LTRjZWItYjgwNy0yNDcyMTg5NTJlNzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMThUMDc1NDEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDU0MDlhOGMxMWQ0YzczODJkYTRmZWRmZWIyOTM0Mzg2N2NlYzVmYTM3NGNiODRmMjQwNjIxNGExNzAwNjNlYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.oA7wm_4F_rWbE4JMbdS4HqU96wws0gkjbJmMPDFLLvI)
> 
> how to fix now? @rosskevin
> 
> ```
>     "i18next": "^23.5.0",
>     "react": "18.2.0",
>     "react-i18next": "^13.2.2",
>     "react-native": "0.72.4",
> ```

solved by myself [https://stackoverflow.com/a/77677875/4348530](https://stackoverflow.com/a/77677875/4348530)
