### ISSUE TITLE
Translate Suspense Fallback

### ISSUE THREAD

**Issue by sebascomeau** [i18next/react-i18next#1126]
## 🐛 Bug Report

We are trying ton translate the Suspense Fallback when lazy loading the resources but it doesn't work. Our locales are in public folder to make them available for lazy loading. We receiving the following error:

Error: Fallback suspended while rendering, but no fallback UI was specified.

Add a <Suspense fallback=...> component higher in the tree to provide a loading indicator or placeholder to display.

## To Reproduce

```js
import React, { Suspense } from 'react';
import { useTranslation } from 'react-i18next';

const Fallback = () => {
  const { t } = useTranslation();

  return (
    <div className="d-flex justify-content-center align-items-center vh-100">
      <div className="spinner-border" style={{ width: '10rem', height: '10rem' }} role="status">
        <span className="sr-only">{t('loading')}</span>
      </div>
    </div>
  );
};

const App = () => (
  <Suspense fallback={<Fallback />}>
    <div />Hello World!</div>
  </Suspense>
);

export default App;

```

## Expected behavior

It should display for screen reader Loading... in English or Chargement... in French.

## Your Environment

- *runtime version*: v12.16.1
- *i18next version*: ^19.4.4
- *os*: Windows

**Comment by jamuhl** [comment]
The Suspense get triggered by not having translations ready -> you're using useTranslation in the fallback triggering a Suspense cause translations are not loaded...

If you need translated values in the fallback -> you will have to make sure that namespace used in the fallback is loaded before rendering...there is no other way around this chicken-egg problem

What we personally do:

```js
export function Fallback({ i18nKey, i18nOptions = {} }) {
  const { t, ready } = useTranslation('loaders', { useSuspense: false });
  if (!ready) return '...loading';

  return t(i18nKey, i18nOptions);
}
```
