### ISSUE TITLE
Detect untranslated text

### ISSUE THREAD

**Issue by PeterKottas** [i18next/react-i18next#1129]
## 🚀 Feature Proposal

This is somewhere in the middle between a feature request and a question. I think it could be beneficial to be able to detect text inside an app (visually or otherwise) that was not translated yet.

## Motivation

I am working on a huge dashboard app that needs i18n. At the moment, it doesn't have any i-18. To make it easier to locate the text that is not yet translated (which is understandably split between hundreds of components), I was thinking about introducing an app-wide CSS rule to color all text bright red. Then, I could override the "t" function to return a span with text inside instead of a simple string. That span would have CSS rule assigned to it that would color the text e.g. green. Of course, this could have some unforeseen consequences in terms of styling, but since it would be a dev only thing, I am not too worried. 

I am wondering if there is some recommended workflow for achieving something like this. While I totally understand that what I described should/will not be included in the core lib, I would appreciate any pearls of wisdom on this topic. Cheers!

**Comment by adrai** [comment]
I personally use the saveMissing feature (+locize)

showcase: https://youtu.be/9NOzJhgmyQE

**Comment by PeterKottas** [comment]
Ty @adrai however I think you misunderstood (or I didn't explain properly). This is not about missing translations (that are already translated via "t" function) this is about detecting text on the screen that is not translated at all. E.g. plain strings rendered by react instead of translated strings rendered by the "t" function.

**Comment by adrai** [comment]
You could use this: https://github.com/i18next/i18next-emoji-postprocessor
everything that is not an emoji is not translated ;-)

**Comment by PeterKottas** [comment]
That's what I was looking for! Thanks a lot man. Or should I say 🅰️ 👰 🎭 🇫🇷 🇩🇪 ❓ 🍁 🆘 ⭕ 😔 🇮🇹 🆙

**Comment by PeterKottas** [comment]
Quite a nice coincidence seems like you published that lib only 8 days ago. Lucky day :-)

**Comment by jamuhl** [comment]
using `appendNamespaceToCIMode: true` and changing language to `cimode` is another option to detect those strings already translated (less colorful than the emoji-postprocessor but built-in)

**Comment by gamcoh** [comment]
Hey everyone! 👋

I just came across this thread and thought I'd mention my tool, Translations Checker. It helps catch untranslated strings and ensures all your keys are accounted for in your translation files. While it's not specifically focused on detecting React-rendered strings without the t() function, it does help automate finding missing or incomplete translations in your i18n workflow, especially during the commit process.

Feel free to check it out: [Translations Checker](https://github.com/gamcoh/translations-checker/tree/v0.1.8). It could be useful for those handling large translation setups!
