### ISSUE TITLE
Unable to resolve module interopRequireWildcard

### ISSUE THREAD

**Issue by belgamo** [i18next/react-i18next#1131]
## 🐛 Bug Report

When I run the app with `yarn android` I get this error. It's work fine with RN 0.60.0.

![image](https://user-images.githubusercontent.com/19699724/83466718-56ddc400-a44e-11ea-86c5-677cc2b13d6a.png)

## To Reproduce

Create a new react-native app with `npx react-native init AwesomeProject` and install `react-i18next` dependencies with `yarn add i18next react-i18next`.

```js
// i18n.js
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

// the translations
// (tip move them in a JSON file and import them)
const resources = {
  en: {
    translation: {
      welcome: 'Welcome to React and react-i18next',
    },
  },
  pt_BR: {
    translation: {
      welcome: 'Bem-vindo ao React e react-i18next',
    },
  },
};

i18n
  .use(initReactI18next) // passes i18n down to react-i18next
  .init({
    resources,
    lng: 'en',

    keySeparator: false, // we do not use keys in form messages.welcome

    interpolation: {
      escapeValue: false, // react already safes from xss
    },
  });

export default i18n;

// App.js
import React from "react";
import { I18nextProvider, useTranslation } from "react-i18next";
import { Text } from "react-native"

import i18n from "./i18n";

const Home = () => {
  const { t } = useTranslation();
  return <Text>{t("welcome")}</Text>;
};

const App = () => {
  return (
    <I18nextProvider i18n={i18n}>
        <Home />
    </I18nextProvider>
  );
};

export default App;
```

## Expected behavior

It should build without errors.

## Your Environment

- *RN version*: 0.62.2
- *runtime version*: Node v12.16.3
- *i18next version*: >= 11.5.0
- *os*: Ubuntu 20.04 LTS

**Comment by adrai** [comment]
https://github.com/facebook/react-native/issues/28317

**Comment by adrai** [comment]
Can you try if it works with a new react-native project?

**Comment by belgamo** [comment]
Yes, it works with a new project. I don't know why, but I faced other problems with `Unable to resolve ...`. I think it's not related with this library. `yarn start --reset-cache` solved for me. Thank you!

**Comment by belgamo** [comment]
What was really causing my problem was the babel configuration :(

![image](https://user-images.githubusercontent.com/19699724/83518670-1b281600-a4b1-11ea-8a00-d6f001cdbcb2.png)
