### ISSUE TITLE
Trans component uses Number.isNaN which is not supported by IE11

### ISSUE THREAD

**Issue by val3ntin** [i18next/react-i18next#1132]
## 🐛 Bug Report

this line of code adds `Number.isNaN` usage which is not available in IE11 and should be polyfilled.

is there a way of changing this behavior or add an ie11 rollup config to support this?

https://github.com/i18next/react-i18next/blame/5847defd122e237f2372ce96027a7d4f91781c28/src/Trans.js#L168

## react-i18next : 10.13.2

thank you.

**Comment by jamuhl** [comment]
IE11 is dead...

see polyfill to support outdated browser:

https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN

**Comment by val3ntin** [comment]
I thought ie11 support had to be here ^^. np re polyfill

**Comment by val3ntin** [comment]
could you please leave a reference for the browser support here?

**Comment by jamuhl** [comment]
No - as I don't test every browser...but as a rule of thumb - everything that is not stoneage or IE should work ;)
