### ISSUE TITLE
Trans alternative usage with Self-Closing Tags

### ISSUE THREAD

**Issue by abbudao** [i18next/react-i18next#1136]
## 🐛 Bug Report

I'm not sure if intended, but using the alternative usage of `Trans`, as described in [docs](https://react.i18next.com/latest/trans-component#alternative-usage-v-11-6-0), doesn't seem to support interpolating tags with no content. This new feature is really game-changing, so I believe we should support it even without passing content to it!

Also, the type definitions also don't seem to match the new possible `components` structure, as it's accepting only `readonly React.ReactNode[] | undefined`.

## To Reproduce

[Link to CodeSandbox](https://codesandbox.io/s/i18next-u7lez)

## Expected behavior
Trans component interpolation regardless of tags having content inside them or not.

## Your Environment

- *runtime version*: Firefox
- *i18next version*:
  - *i18next*:  **19.4.5**
   - *react-i18next*: **11.6.0**
- *os*: Linux

**Comment by adrai** [comment]
Would you try a PR?

**Comment by jamuhl** [comment]
might be enough to remove the check here: https://github.com/i18next/react-i18next/blob/master/src/Trans.js#L163 (`&& !node.voidElement`)

adding a test case here: https://github.com/i18next/react-i18next/blob/master/test/trans.render.object.spec.js

**Comment by abbudao** [comment]
@jamuhl @adrai Do you still want me to try a PR? 
Or as you just located a possible fix, it doesn't make much sense?

**Comment by jamuhl** [comment]
Depends on your time window...you need it fast -> PR (no need in the next weeks - wait for us to solve it 😁)

**Comment by abbudao** [comment]
Well, I'm very interested in this. I will give it a shot then!
Thanks for the directions!

**Comment by jamuhl** [comment]
Ok...if you do not get it done easily (1hour) ping me again - don't waste too much time (as might be a little more complicated cause the Trans component has baked in a lot - really not the simplest part of react-i18next)
