### ISSUE TITLE
Document how to nest components with new <Trans/> style

### ISSUE THREAD

**Issue by lpoulter** [i18next/react-i18next#1137]
I'm not sure how and if I can use the new <Trans component={}/> style with the following example.

```    
      Click to go <span><Link>Here</Link><span/>
```
To reduce complexity for translators I'd love for the translation string to be
`Click to go <Link>Here</Link>`
Is that possible?

**Comment by jamuhl** [comment]
<Trans
  defaults="Click to go <Link>Here</Link>"
  components={{ Link: ({ children }) => <span><Link>{children}</Link><span/>  }}
/>

Is what I guess should work - but not tested

**Comment by lpoulter** [comment]
Yes that works, thanks. Strangely I'm seeing incorrect renders when using camelcase elements in translations string.
`<link>` works `<Link>` does not.

**Comment by jamuhl** [comment]
Will have to check that...might be the HTML parser does not support non lowercase...

**Comment by jamuhl** [comment]
just added a  test case for:

```js
    <Trans
      defaults="hello <italicCase>beautiful</italicCase> <BoldCase>{{what}}</BoldCase>"
      values={{ what: 'world' }}
      components={{ italicCase: <i>just dummy</i>, BoldCase: <strong>univers</strong> }}
    />
```

https://github.com/i18next/react-i18next/commit/11d01708c1b18477357aed9c787c6f90249dcfc9

seems to work in react-i18next@11.7.0 - can you please revalidate and if it still fails paste the translation string and Trans usage here - so I can reproduce?

**Comment by brotheroftux** [comment]
I 

> Yes that works, thanks. Strangely I'm seeing incorrect renders when using camelcase elements in translations string.
> `<link>` works `<Link>` does not.

I just had the opposite with 11.7.0 -- `<LinkComponent>` did work, `<link>` didn't. The component itself was being rendered, yet it didn't have correct children passed to it. Children were rendered outside of the component itself.

**Comment by jamuhl** [comment]
@brotheroftux please provide a codesandbox for reproduction

**Comment by brotheroftux** [comment]
Sure thing. 

https://codesandbox.io/s/angry-archimedes-5t7uo?file=/src/App.tsx

I'm using 'link' as component placeholder name and `strong` as the component itself, though it doesn't really matter what you use as a component. This originally happened to me when I was trying to use this with a custom `Link` component.

Notice how `<strong>` has no children:
![image](https://user-images.githubusercontent.com/1677844/85861095-75727900-b7c8-11ea-89c9-48861530881b.png)

Changing the component placeholder in the translation string to `LinkComponent` makes all the difference:

![image](https://user-images.githubusercontent.com/1677844/85861253-b5396080-b7c8-11ea-95c8-7b454f205d6a.png)

In fact, if you use `meta` as a placeholder name it also renders without children. However, other HTML tag names such as `script` and `title` still work, so this is a bit strange.

**Comment by jamuhl** [comment]
Hm...link is a valid html element and a void Element -> guess removing the check for void Element here should fix this: https://github.com/i18next/react-i18next/blob/master/src/Trans.js#L171

**Comment by bitttttten** [comment]
I am not sure it's related to this issue, but I am having problems rendering children of View elements in React Native.

For example, with:

```js
<Trans
	i18nKey="some.key"
	components={{ Icon: <IconQuestion /> }}
/>
```

This will work:

```js
const IconQuestion = () => {
	return (
		<View style={{ backgroundColor: `red` }} />
	)
}
```

However this will render the View, with it's background colour as red, but not the text inside.

```js
const IconQuestion = () => {
	return (
		<View style={{ backgroundColor: `red` }}>
			<Text>this text does not render</Text>
		</View>
	)
}
```

I didn't want to open a whole new issue. Although [I was able to make it work on the web](https://codesandbox.io/s/react-i18next-example-o169x?file=/src/app.js) with very similar syntax, so I guess it's related to something about the View component?

**Comment by jamuhl** [comment]
@bitttttten I think it's more related to what you do

If your translations look like: `<Icon>Hello World</Icon>`

you component should take `children` as the text:

```js
const IconQuestion = ({children}) => {
	return (
		<View style={{ backgroundColor: `red` }}>
			<Text>{children}</Text>
		</View>
	)
}
```

At least I guess this is your problem?

**Comment by bitttttten** [comment]
Yeah, that's exactly what my string looks like. I also have it like so: `"some.key": "Press the <Icon /> when you need help"` as it will be the same icon for each language, and it doesn't have children.

The children do work if there is text, but I want to render more things than just text, like:

```js
const IconQuestion = ({children}) => {
	return (
		<View style={{ backgroundColor: `red`, borderRadius: 16, width: 32, height: 32 }}>
			<Feather name="question" size="28" color="blue" >
		</View>
	)
}
```

🤔

**Comment by isaaclem** [comment]
I've successfully nested Link tag by code below

```js
<Trans
   i18nKey="tnc.content"
     components={[
       <Link to={{ pathname: '/termsofuse', state: { from: 'landing' } }} />,
       <Link to={{ pathname: '/dataprotection', state: { from: 'landing' } }} />,
     ]}
/>
```

and in `en.json`

```json
{
  "tnc.content": "By using this website, you agree to its <0>Terms</0> and <1>Data Protection Policy</1>"
}
```
