### ISSUE TITLE
Hash versioning for tranlation.json files

### ISSUE THREAD

**Issue by ajit-hi** [i18next/react-i18next#1141]
HI, Thanks for this awesome library.
I am facing issues with my translation files, as when I update translation.json in locales folder, they are not updated in client browser, as they are cached. 

Can we implement hash versioning to tackle cache issue.

Thanks.

**Comment by jamuhl** [comment]
how is that a problem with this lib? are you using the http-backend?

**Comment by ajit-hi** [comment]
No. I'm not using http backend. Will that be a solution?

**Comment by jamuhl** [comment]
Ah...it's all about hotreloading only...https://github.com/i18next/react-i18next/issues/6#issuecomment-185300536 might help

**Comment by ajit-hi** [comment]
Okay. I will try that first. Closing this issue then. Thanks for your time.
