### ISSUE TITLE
Translation loading heroku problem

### ISSUE THREAD

**Issue by Wozniaxos** [i18next/react-i18next#1143]
## 🐛 Bug Report

Hi, i have problem with translation loading on heroku, i get this error:

`i18next::backendConnector: loading namespace translation for language en-US failed failed parsing /locales/en-US/translation.json to json`

locally it works fine and is loading languages, i triple checked and i have for sure correct JSON file, do you have ane idea what might be the cause? Is it possible that some parser is changing this file during build? I checked locally production build and json file seems to be correct, local production build is also serving correctly with translations loaded.

I used `create-react-app` for app bootstrap

My i18n file:

```js
import i18n from 'i18next';
import Backend from 'i18next-http-backend';
import { initReactI18next } from 'react-i18next';

i18n
  .use(Backend)
  .use(initReactI18next)
  .init({
    fallbackLng: 'en-us',
    debug: true,
    lng: 'en-us',
  });

export default i18n;
```
i18n entry point

```js
import React from 'react';
import ReactDOM from 'react-dom';
import { Provider } from 'react-redux';

import './index.sass';
import './i18n';
import App from './components/App';
import store from './redux/store';
import * as serviceWorker from './serviceWorker';

ReactDOM.render(
  <React.StrictMode>
    <Provider store={store}>
      <App />
    </Provider>
  </React.StrictMode>,
  document.getElementById('root')
);

serviceWorker.unregister();
```

**Comment by adrai** [comment]
How does the http response look like when you inspect it in the developer console in the network tab?
Has your hosted web url a suffix?
Something like my.domain.com/suffix ? you probably need to adapt the loadPath then...

**Comment by Wozniaxos** [comment]
the url is `https://my-app.herokuapp.com/locales/en-US/translation.json`

**Comment by adrai** [comment]
And how does the resonse for https://my-app.herokuapp.com/locales/en-US/translation.json look like?
Is the body a correct json? Are the headers correct?

**Comment by Wozniaxos** [comment]
The response is HTML

`
<!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="icon" href="/favicon.ico"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#000000"/><meta name="description" content="Web site created using create-react-app"/><link rel="apple-touch-icon" href="/logo192.png"/><link rel="manifest" href="/manifest.json"/><title>React App</title><link href="/static/css/main.34c0cda3.chunk.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div><script>!function(e){function r(r){for(var n,l,f=r[0],i=r[1],a=r[2],c=0,s=[];c<f.length;c++)l=f[c],Object.prototype.hasOwnProperty.call(o,l)&&o[l]&&s.push(o[l][0]),o[l]=0;for(n in i)Object.prototype.hasOwnProperty.call(i,n)&&(e[n]=i[n]);for(p&&p(r);s.length;)s.shift()();return u.push.apply(u,a||[]),t()}function t(){for(var e,r=0;r<u.length;r++){for(var t=u[r],n=!0,f=1;f<t.length;f++){var i=t[f];0!==o[i]&&(n=!1)}n&&(u.splice(r--,1),e=l(l.s=t[0]))}return e}var n={},o={1:0},u=[];function l(r){if(n[r])return n[r].exports;var t=n[r]={i:r,l:!1,exports:{}};return e[r].call(t.exports,t,t.exports,l),t.l=!0,t.exports}l.m=e,l.c=n,l.d=function(e,r,t){l.o(e,r)||Object.defineProperty(e,r,{enumerable:!0,get:t})},l.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},l.t=function(e,r){if(1&r&&(e=l(e)),8&r)return e;if(4&r&&"object"==typeof e&&e&&e.__esModule)return e;var t=Object.create(null);if(l.r(t),Object.defineProperty(t,"default",{enumerable:!0,value:e}),2&r&&"string"!=typeof e)for(var n in e)l.d(t,n,function(r){return e[r]}.bind(null,n));return t},l.n=function(e){var r=e&&e.__esModule?function(){return e.default}:function(){return e};return l.d(r,"a",r),r},l.o=function(e,r){return Object.prototype.hasOwnProperty.call(e,r)},l.p="/";var f=this["webpackJsonpdl-frontend"]=this["webpackJsonpdl-frontend"]||[],i=f.push.bind(f);f.push=r,f=f.slice();for(var a=0;a<f.length;a++)r(f[a]);var p=i;t()}([])</script><script src="/static/js/2.6eda0899.chunk.js"></script><script src="/static/js/main.dacbda45.chunk.js"></script></body></html>
`

Headers seems to be fine i think

**Comment by adrai** [comment]
Then the file is not there 🤷‍♂️

**Comment by adrai** [comment]
This seems like your index.html file to me... probably this is the default, when the route is not matching any file...

**Comment by Wozniaxos** [comment]
Ehh.. i was affraid of that, thanks for help, since this is not related to i18-next i am closing issue

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏

**Comment by Wozniaxos** [comment]
Hey,

It's not that file isn't there, cause when i go to `my-app.herokuapp.com/locales/translation.json` the json is showed up on the screen. But the request from connector for some reason has wrong response. The headers are:
![image](https://user-images.githubusercontent.com/26778061/86440411-a98af400-bd0a-11ea-98bd-a14737e000a2.png)

I am not sure why the response header has html content type. Maybe you have yet some ideas?

**Comment by adrai** [comment]
I don’t know heroku...
How are your files served? Do you have a custom http server? Can you influence the content-type somehow?

**Comment by adrai** [comment]
Maybe this helps: https://stackoverflow.com/questions/39999432/heroku-always-send-a-response-as-html-instead-a-json-with-the-data-expected

**Comment by Wozniaxos** [comment]
Ok, thought that it might be the case of additional configuration here at the library. I think I can't influence but I am not sure, anyway i'll try with that proxy thing and if fail i'll move question to heroku than, thanks again, and closing for good. And the repo has star of course!
