### ISSUE TITLE
Handling of ruby signs / language specific tags

### ISSUE THREAD

**Issue by florianbepunkt** [i18next/react-i18next#1144]
## 🚀 Feature Proposal

We have an app that gets translated to Japanese. As other asian languages Japanese uses ruby signs like, for example <ruby>殺人劇の食卓<rt>クリナリオ モルターレ</rt></ruby>.  You would specify this using ruby tags like `<ruby>殺人劇の食卓<rt>クリナリオ モルターレ</rt></ruby>` Reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ruby

In contrast to semantic annotations like `<strong></strong>` this is purely language-specific. So in Japanese the ruby tag would exists, in English it would not. Currently, as far as I know, there is no way in handling this in react i18next as far as I know.

**Comment by florianbepunkt** [comment]
Okay, there is a way. See https://react.i18next.com/latest/trans-component#using-for-less-than-br-greater-than-and-other-simple-html-elements-in-translations-v-10-4-0 in documentation.

Having the following react options in i18n.init allows for ruby annotation in translation files:

```
react: {
      wait: true,
      useSuspense: false,
      transSupportBasicHtmlNodes: true,
      transKeepBasicHtmlNodesFor: ["br", "strong", "i", "ruby", "rt"]
    }
```

**Comment by adrai** [comment]
If you like, you can provide a PR extending the defaults for ruby.

**Comment by jamuhl** [comment]
does that really work...at least in the past those "simple tags" could not have inner elements/tags

**Comment by florianbepunkt** [comment]
@jamuhl Yes, it works.

My translation.json

```
{
"copy": "あなたは「<ruby>殺人劇の食卓<rt>クリナリオ モルターレ</rt></ruby>」のゲ....shortened for brevity
}
```
and then using the t function from the useTranslation hook:

`{t("welcomeGuest.copy")}`
