### ISSUE TITLE
Interpolation not using overloadTranslationOptionsHandler

### ISSUE THREAD

**Issue by abdullah90a** [i18next/react-i18next#1145]
## 🐛 Bug Report

I am trying to add a test locale to my project, without having to lookup key values in a po file/remote source. To do this, I've provided a function to the overloadTranslationOptionsHandler init option to wrap strings to be translated in my JSX files with an 'xx' suffix and prefix when the user locale (persisted in my Redux store) is set to the test locale. The test locale doesn't haven a fallback language, so the keys serve as the originalDefaultValue in the handler.

 This works for regular key strings, but not for interpolated strings. I see the interpolation happening as expected, but the resulting interpolated string is not wrapped in the xx suffix/prefix.

## To Reproduce

fallback languages in i18n init options object:
```js
fallbackLng: {
      [TEST_LOCALE]: [],
      default: [DEFAULT_LOCALE],
    },
```

overloadTranslationOptionsHandler in i18n init options object:
```js
overloadTranslationOptionHandler(args) {
      const [key, originalDefaultValue] = args;
      const defaultValue = isTestLocale(i18n.language) ? testLocaleT(key) : originalDefaultValue;
      return { defaultValue };
    },
```

Wrapping Helper Functions:
```js
export const isTestLocale = language => language === TEST_LOCALE;
export const testLocaleT = key => `xx_${key}_xx`;
```

String to interpolate and wrap
```
{t("{{value}} owned by {{name}}", { value: totalUserOwnedValue, name: userOrgName })}
```

## Expected behavior
Given the following variable values, and user locale set to test locale:
```js
totalUserOwnedValue = 100
userOrgName = myOrg
```

I expect the following string to be produced:
```js
xx_100 owned by myOrg_xx
```

## Actual behavior
```js
100 owned by myOrg
```

## Your Environment

- *runtime version*: node v10.15.0
- *i18next version*: >=11.4.0
- *os*: Mac

**Comment by jamuhl** [comment]
gets called before interpolation: https://github.com/i18next/i18next/blob/master/src/Translator.js#L79

must be something else...

**Comment by adrai** [comment]
overloadTranslationOptionHandler gets only called if no t options are passed

**Comment by adrai** [comment]
Maybe it's better if you create a postProcessor... example: https://github.com/i18next/i18next-emoji-postprocessor

**Comment by abdullah90a** [comment]
@adrai - I'll implement the postProcessor in the link you've posted, will update this bug with results.

**Comment by abdullah90a** [comment]
@adrai - I was able to achieve the wrapping I wanted through the postProcessor. I did have to implement a custom interpolation function to perform value replacement in the wrapped keys.

Post Processor Code:
```js
export const interpolateOptions = (key, options) => {
  let interpolatedKey = key;
  Object.keys(options).forEach(optionKey => {
    interpolatedKey = interpolatedKey.replace(`{{${optionKey}}}`, options[optionKey]);
  });
  return interpolatedKey;
}

export default {
  name: "testLocale",
  type: "postProcessor",

  process (value, key, options) {
    return isTestLocale(i18n.language) ? interpolateOptions(testLocaleT(key), options) : value;
  },
}
```

I18n init code, with the postProcessor provided:
```js
18n
  .use(initReactI18next)
  .use(testLocalePostProcessor)
  .init({
    postProcess: "testLocale",
    ...
```

Since this locale is meant solely for testing purposes, the above implementation satisfies what we were hoping to achieve. Thank you very much for your support on this issue.

**Comment by jamuhl** [comment]
@abdullah90a I'm not a unittest pro...but honestly ... your tests now test nothing ... they test your replacement code ... which only proofs you passed in some options -> which to make the test pass are hardcoded too...it's a assert true = true test.

But...like said...I'm not a unit test pro

**Comment by abdullah90a** [comment]
@jamuhl @adrai  - Turns out we didn't need the overloadTranslationOptionHandler in i18n's init block - performing the wrapping in the postProcessor wraps interpolated strings, as well as regular strings.

TestLocale PostProcessor (process wrapping interpolated value with xx suffix/prefix)
```js
export default {
  name: "testLocale",
  type: "postProcessor",

  process (value) {
    return isTestLocale(i18n.language) ? testLocaleT(value) : value;
  },
}
```

i18n init with just the postProcessor
```js
i18n
  .use(initReactI18next)
  .use(testLocalePostProcessor)
  .init({
    postProcess: "testLocale",
```

This also removes the unit test not actually validating anything.
