### ISSUE TITLE
Compatibility issues with react-redux

### ISSUE THREAD

**Issue by cseas** [i18next/react-i18next#1147]
Does this package have compatibility issues with `react-redux`? Is there a separate guide I should be following to add it to a redux based project so there are no conflicts?

## 🐛 Bug Report

I just followed the [basic tutorial](https://react.i18next.com/getting-started) to add `react-i18next` to a React project that uses `react-redux` and turns out the `i18n.changeLanguage()` function resets my redux store to initial state everytime it is called. There are no errors reported and no application crash.

## To Reproduce

My code is split across multiple files but here's a concise overview of the `i18n` code I'm using:

```jsx
import "translations/i18n";
import { useTranslation } from "react-i18next"; // part of <TranslateButtons /> component

const { i18n } = useTranslation(); // part of <TranslateButtons /> component

function changeLanguage(lng: string) { // part of <TranslateButtons /> component
    i18n.changeLanguage(lng);
}

ReactDOM.render(
  <React.StrictMode>
    <App />
    <button onClick={() => changeLanguage("en")}>EN</button> // part of <TranslateButtons /> component
  </React.StrictMode>,
  document.getElementById("root")
);
```

The redux store's provider and all translation usage using `useTranslation()` hook are added inside the `<App />`  component.

Here's the i18n config:
```js
i18n
  .use(initReactI18next)
  .init({
    resources,
    lng: "da",
    fallbackLng: "da",
    supportedLngs: ["da", "en"],
    keySeparator: ".",
    interpolation: {
      escapeValue: false,
    },
    debug: true,
  });
```

## Expected behavior

I'd assume the redux store should remain unaffected regardless of anything `react-i18next` does since I've just followed the basic tutorial and haven't tried to hook it up with redux in any way.

## Your Environment

- *runtime version*: node v12, Chrome
- *i18next version*: 19.5.4, `react-i18next`: 11.7.0
- *os*: Windows 10

**Comment by adrai** [comment]
react-i18next and i18next has no connection and no influence to react-redux...
https://github.com/i18next/react-i18next/issues/367
https://github.com/i18next/react-i18next/issues/1040
https://github.com/i18next/react-i18next/issues/879

**Comment by jamuhl** [comment]
Wrap the redux provider outside of i18next usage...-> Suspense trigger would...depending on where your Suspense Component is rerender all below...
