### ISSUE TITLE
npm install throws error code EINTEGRITY

### ISSUE THREAD

**Issue by VirgilioGM** [i18next/react-i18next#1150]
## 🐛 Bug Report

I've using this package in a proyect for several months but last friday I cloned my repo in a different machine and run `npm install` getting an error with code EINTEGRITY with this description:
```
npm ERR! sha1-wGavtYK7HLQSjWDqkjkulNXp2+w= integrity checksum failed when using sha1: wanted sha1-wGavtYK7HLQSjWDqkjkulNXp2+w= but got sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg== sha1-2jmj7l5rSw0yVb/vlWAYkK/YBwk=. (0 bytes)
```

I thought that the problem was caused by my project/machine but after several tests (removing package-lock.json, npm cache verify, npm cache clean --force, etc.), installing my dependencies one by one I realized that the problem occurred while installing react-i18next. I tried then to create a node project from scratch and install this package with the same error.

## To Reproduce

```
mkdir test
cd test
npm init
npm install react-i18next
```

## Expected behavior

I expect react-i18next to be installed without errors.

## Your Environment

- Ubuntu 14.04.5
- node v8.16.2
- npm 6.4.1

**Comment by adrai** [comment]
Never seen this...
Can you try a newer lts version of node? >=v10

**Comment by adrai** [comment]
btw: if you have a package-lock.json try to remove it

**Comment by VirgilioGM** [comment]
In fact, the project where I realized the problem is using Meteor framework v1.10.1, which uses node v12.16.1:

- `meteor --version` -> Meteor 1.10.1
- `meteor node --version` -> v12.16.1
- `meteor npm --version` -> 6.14.0

And `meteor npm install react-i18next` results in the same error.

**Comment by VirgilioGM** [comment]
> btw: if you have a package-lock.json try to remove it

Yes, every time I used my existing project, I removed first `package-lock.json`. Also removed this dependency and run `meteor npm install` without errors to isntall then this package with always the same error

**Comment by adrai** [comment]
Sorry, can't reproduce this... just tried on 2 different machines...
You may have some local setup issue 🤷‍♂️

**Comment by VirgilioGM** [comment]
You are right. I tried to install it in a different machine without problem. I'm sorry I wasted your time

**Comment by adrai** [comment]
no problem
