### ISSUE TITLE
keys/strings passed as props 

### ISSUE THREAD

**Issue by gigamesh** [i18next/react-i18next#1156]
I apologize in advance that this is more of a question vs a feature proposal, but the reason I'm posting is that I'm finding the documentation and examples a little lacking. 

The main thing I'm trying to understand is how dynamic keys/strings (ie imported into a component via the parent component, context, `import`, etc) can be extracted from an app to build the translation files. If keys supplied to `t()` or <Trans..>` need to be string literals in order to be parsed, does that mean it's not possible to render child components with translated content without the child component existing in the same file as the parent?

I tried the babel plugin for extracting the keys & strings, but it can only do limited static analysis. Anything beyond a variable within the same file isn't parsed.

Is there a more complex app using `react-i18next` someone can link to as an example for me to follow?

**Comment by jamuhl** [comment]
You will have to ask this over at the babel-plugin -> I do not know every extraction tool out there (so I do not really know what restrictions they come with). Personally we always use the saveMissing feature which sends new translations to a backend (be it a local server or locize.com).

You're welcome to help to improve the docs.

**Comment by gigamesh** [comment]
Ok thanks I'll look more into `saveMissing`. 

Are you aware of any example github repos using that, and/or one with multiple components spread across multiple files?

**Comment by jamuhl** [comment]
where do you struggle...it's the same as with/without react-i18next. Either pass `t` to the child component or wrap it with the HOC or use the hook

**Comment by gigamesh** [comment]
here is an example:
```
grandparent.js
------------------
import content from './content.yaml'

const Grandparent = () => content.map(({cardStrings})=>{
```

**Comment by gigamesh** [comment]
here is a contrived example:
```
CardGrid.js
==============================
import Card from './Card.js'
import cardStrings from './cardStrings.yaml'

const CardGrid = () => (
     <div>
        {cardStrings.map(currentCardStrings => (<Card strings={currentCardStrings}/>))}
     </div>
)

----------------------------------------
Card.js
==============================
import { withNamespaces } from 'react-i18next';

const Card = ({strings, t}) => (
   <div>
      <h1>{t(strings.title)</h1>
       {strings.paragraphs.map((paragraph)=>(
          <p>{t(paragraph)}</p>
       ))}
   </div>
)

export default withNamespaces()(Card)
```

...I haven't been able to figure out how to extract that text content into the translation files. The extraction tools only seem able to interpret string literals instantiated within the same file where `t()` consumes them. The same goes for keys/ids. This seems to make it impossible to import text content from outside of the file where it is translated.

I'm guessing I'm just missing something obvious or not setting things up correctly?

**Comment by jamuhl** [comment]
Ah now I see...it's not about working react-i18next - it's just about not working extraction tool.

Guess that's not possible...extraction tools do not run the actual code -> so they do not know the content of `strings.title` or `strings.paragraph`

But runtime extraction using `saveMissing` will work with this - as it gets called with the correct key.
