### ISSUE TITLE
How to use in Class Component

### ISSUE THREAD

**Issue by uendar** [i18next/react-i18next#1157]
I am trying to use  react-i18next in class component and i cant get right translate at all. 
When i use in functional components it works perfect.

Here is how i use in class components:

```
import { withTranslation } from 'react-i18next';
class LegacyWelcomeClass extends Component {
  render() {
    const { t } = this.props;
    return <h2>{t('title.header')}</h2>;
  }
}
export default withTranslation()(LegacyWelcomeClass)
```

and a file with translation 

```
{
title:{
header:"Hello"
}
}
```

**Comment by jamuhl** [comment]
there are tests asserting it works: https://github.com/i18next/react-i18next/blob/master/test/withTranslation.spec.js

is there something special in your configuration...must be something on your side

**Comment by uendar** [comment]
It is not about the render. it shows the object key when i try to translate. For example:

if i have 

```
title:{
header:"Hello"
}
```

and i use   <p>{t("title.header")}</p> it shows  => title.header in place of a title

**Comment by jamuhl** [comment]
setting debug: true might help...

either key does not exist, not loaded yet or something like that...did you set useSuspense: false?

**Comment by adrai** [comment]
Maybe wrong namespace? withTranslation(‘ns’)

**Comment by Alexggp** [comment]
I'm having this same issue

**Comment by adrai** [comment]
@Alexggp https://react.i18next.com/latest/withtranslation-hoc#when-to-use
example: https://github.com/i18next/react-i18next/blob/master/example/react/src/App.js#L13
Having a reproducible example would help us to help you. Something like this codesandbox example: https://codesandbox.io/s/react-i18next-forked-nwqz8?file=/src/app.js
