### ISSUE TITLE
req.language, Property 'language' does not exist on type 'IncomingMessage'

### ISSUE THREAD

**Issue by gpessa** [i18next/react-i18next#1162]
## 🐛 Bug Report

I have a project with typescript. 
When I try to access the language in the initial properties, I get a TS error because is not defined.
Do you know how to fix it (but keep the typing?)

```js
const Index: NextPage = () => {
...
}

Index.getInitialProps = async ({ store, req }) => {
  const locale = req ? req.language : i18n.language; // req not defined
};
```

## Environment

- *next-i18next*: i.e. 6.0.2

**Comment by adrai** [comment]
Can you post this to the correct repo? https://github.com/isaachinman/next-i18next

**Comment by gpessa** [comment]
sure!
