### ISSUE TITLE
Not all <Trans> components updated with language change

### ISSUE THREAD

**Issue by xobotyi** [i18next/react-i18next#1164]
## 🐛 Bug Report

After changing language dynamically via `i18n.changeLanguage(lang)` only several elements change their language, most of UI persist old language.
But after page reload whole interface uses new language and translated correctly.

I have around 20 `<Trans>` on the page, some of them updated some of them not and i have no ide what the logic.

## To Reproduce

A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

i18n initialization
```js
import i18next from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';
import * as localeEN from './locales/en.json';
import * as localeRU from './locales/ru.json';

export const i18n = i18next
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    debug: false,
    fallbackLng: 'en',
    supportedLngs: ['en', 'ru'],
    interpolation: {
      escapeValue: false,
    },
    resources: {
      en: localeEN,
      ru: localeRU,
    },
  });
```

Then I use `<Trans>` components around the code mixed with `useTranslation` hook. Dont know if it is valid usage hook + `<Trans>` in the same component.

## Expected behavior

All the `<Trans>` component should update on language change.

## Your Environment

- *runtime version*: node 14.8
- *i18next version*: ^19.7.0 (react-i18next: ^11.7.1)
- *os*: Windows 10 x64
- *any other relevant information*: 
    - Browser: chromium based Yandex.Browser
    - react: 16.13.1
    - react-dom: 16.13.1

**Comment by xobotyi** [comment]
Im an idiot, sorry =)

**Comment by jamuhl** [comment]
The Trans component only does what the docs say...please read https://react.i18next.com/latest/trans-component#important-note
