### ISSUE TITLE
ReportNamespaces being dynamically assigned

### ISSUE THREAD

**Issue by ljosberinn** [i18next/react-i18next#1166]
## 🐛 Bug Report

Currently `i18next.reportNamespaces` only gets defined [once `useTranslation` is executed at least once](https://github.com/i18next/react-i18next/blob/dbd54d544ccca654f64a49bc8390d3bf87f02d84/src/useTranslation.js#L10).
I stumbled over this in a test, trying to spy on `reportNamespaces`, but due to that, it's undefined. The typings don't reflect that either.

This is imo a very weird side effect for a hook to have.

Considering both `withTranslation` and `Translation` also use `useTranslation`, wouldn't it make sense to hoist declaration to `init` of `react-i18next` to [here](https://github.com/i18next/react-i18next/blob/dbd54d544c/src/context.js#L55)?

```diff
export const initReactI18next = {
  type: '3rdParty',

  init(instance) {
    setDefaults(instance.options.react);
    setI18n(instance);
+   instance.reportNamespaces = new ReportNamespaces();
  },
};
```

The only case that wouldnt be covered with that is passing an instance via props to `useTranslation`. However, if it's also necessarily an instance initialized via react-i18next, that would work just fine.

**Comment by jamuhl** [comment]
The point is not everyone is using `initReactI18next` (cases where I18nextProvider is used). Honestly not sure why it is an issue if it is undefined as long it's not providing any data - but if you feel like it's important to you...feel free to provide a PR adding it in initReactI18next already (but not remove the check and add in useTranslation - as said it's needed there.)

**Comment by ljosberinn** [comment]
Fair, I wasn't aware people don't use `initReactI18next` when using `react`. I fail to see why you wouldn't though, or rather, why you wouldn't when using `I18nextProvider`?

[This](https://github.com/ljosberinn/personal-react-boilerplate/blob/master/karma/client/Karma.tsx#L47) is my next.js setup which receives its instance through a [custom wrapper here](https://github.com/ljosberinn/personal-react-boilerplate/blob/master/karma/client/i18n.ts#L30). Is this incorrect? Works fine so far.

**Comment by jamuhl** [comment]
Most use it...but some large projects using multiple i18next instances use the provider as it gives more control over which i18next instance is used down the tree...

Regarding next.js you will have to ask over at https://github.com/isaachinman/next-i18next - personally I never used it in production so my knowledge is limited in that area.

**Comment by ljosberinn** [comment]
Yeah, I'm aware of it, sadly very opinionated and not serverless compatible. Thanks anyways!

**Comment by adrai** [comment]
https://github.com/isaachinman/next-i18next/issues/274#issuecomment-664616304

**Comment by ljosberinn** [comment]
Ah, well that may be resolved but its [still recommending using App.getInitialProps](https://github.com/isaachinman/next-i18next/blob/master/examples/simple/pages/_app.js#L6), which is heavily discouraged by the Next team ([1](https://nextjs.org/docs/advanced-features/automatic-static-optimization), [2](https://github.com/vercel/next.js/pull/16277#discussion_r471799586)).
