### ISSUE TITLE
Problem with passing variable values and html tags when using Trans component 

### ISSUE THREAD

**Issue by jurnalanas** [i18next/react-i18next#1169]
## 🐛 Bug Report

I got a problem with passing variable values and HTML tags when using the Trans component.

**this is what I am trying to do:**

Foo.js (snippet for clarity):

```jsx
<p>
  <Trans i18nKey='xpSubAccountTOS' t={t}>
    {`By signing up, you agree to the `}
    <a href={`https://www.foo.co/${currentLanguage.value}/terms-and-conditions`}>
      Terms of Use
    </a>
    {` and the `}
    <a href={`https://www.foo.co/${currentLanguage.value}/foo-for-managed-accounts`}>
      Foo account agreement
    </a>
    .
  </Trans>
</p>
```

en.json (snippet for clarity)

```json
  "xpSubAccountTOS": "By signing up, you agree to the <1>Terms of Use<1/> and the <3>Foo account agreement</3>."
```

**My expectation is that it will be rendered to:**

```html
<p>By signing up, you agree to the <a href=" https://www.foo.co/en/terms-and-conditions">Terms of Use</a> and the  <a href="https://www.foo.co/en/foo-for-managed-accounts">Foo account agreement</a>.</p>
```

**But instead, I get**

```html
<p>By signing up, you agree to the <a href="https://www.foo.co/en/terms-and-conditions">Terms of Use and the Foo account agreement.</a></p>
```

only one `</a>` and in the wrong structure.

this is the node tree:

<img width="382" alt="Screen Shot 2020-09-07 at 10 52 57 AM" src="https://user-images.githubusercontent.com/876900/92348167-6e3ae600-f0fc-11ea-9791-54c69d8782eb.png">

Is this a bug, or do I miss something?

## Your Environment

- *i18next version* :11.7.0
- *os*: Mac

**Comment by jamuhl** [comment]
Could you please provide a reproducible codesandbox? Rather strange issue...

**Comment by adrai** [comment]
Remove the additional ' from your second a element.
instead of:
    
    foo-for-managed-accounts`}'>

It should be:

    foo-for-managed-accounts`}>

**Comment by jurnalanas** [comment]
Oop, this is just a typo apparently. 

`<1>Terms of Use<1/>` should be `<1>Terms of Use</1>`. Works fine. Close this now.
