### ISSUE TITLE
 React concurrent throws a side-effect warning for useTranslation

### ISSUE THREAD

**Issue by AdrienLemaire** [i18next/react-i18next#1170]
Related to #817

## 🐛 Bug Report
When using React concurrent mode (a [16.X release initially planned for Q2 2019](https://reactjs.org/blog/2018/11/27/react-16-roadmap.html#tldr) and not yet stable, but used in prod at facebook), the following error occurs when trying to call useTranslation within a lazy-loaded component with suspense.
![](https://i.imgur.com/hmfwnh6.png)

## To Reproduce
React concurrent mode with console warning: https://codesandbox.io/s/react-i18next-lazy-loading-example-forked-ozkgn

## Expected behavior

No console warning and no side effect.
Expecting the same behavior as @jamuhl's example with React 16.12: https://codesandbox.io/s/react-i18next-lazy-loading-example-forked-kv2cr

**Comment by jamuhl** [comment]
update react-i18next to 11.7.2 should already solve this?

**Comment by AdrienLemaire** [comment]
@jamuhl oh boy... Was running on 11.7.0 and incorrectly assumed that I was on the latest version (having renovate auto-create PRs for package upgrades). bumping to 11.7.2 indeed resolved the issue. 
Sorry for all the messages, and thanks for the quick replies!
