### ISSUE TITLE
Translations not re-rendered on languageChanged in i18next

### ISSUE THREAD

**Issue by ThisIsMissEm** [i18next/react-i18next#1171]
## 🐛 Bug Report

I'm dynamically reloading language bundles (via i18next-hmr), the i18next languageChanged fires, but the rendered components via `t()` and `<Trans>` don't re-render automatically.

## To Reproduce

I'm not particular sure how to give reproduction instructions, as it's not dependent on i18next-hmr. I think the react-i18next Context Provider (`I18nextProvider`) needs to watch on `languageChanged` and `loaded` events and then re-render.

## Expected behavior

The react tree should re-render when the locale changes.

## Your Environment

- *runtime version*: any browser
- *i18next version*: ^19.6.3
- *os*: Mac

## Workaround

Currently, in order to get i18next-hmr working, in my component that renders the `I18nextProvider` component, I'm doing:

```jsx
  // This is to support HMR for i18next, for some reason without this,
  // useTranslation doesn't refresh even though the language has been reloaded
  if (process.env.NODE_ENV === 'development') {
    const [lng, setLng] = useState(locale);
    i18next.on('languageChanged', (lng) => setLng(`${lng}@${Date.now()}`));
    i18next.on('loaded', () => setLng(`${lng.split('@')[0]}@${Date.now()}`));
  }
```

Which forces a re-render due to useState being set, but that seems like a horrible hack for me to be doing. I'd guess that we'd actually need something like this in react-i18next's `i18nextProvider` instead.

For instance, if you have a component that calls `i18next.changeLanguage` then the

**Comment by ThisIsMissEm** [comment]
I looked into this further, I learned that I actually needed this configuration when doing `i18next.init()`:

```
      react: {
        bindI18n: 'loaded languageChanged',
        bindI18nStore: 'added',
        useSuspense: true,
      },
```

I'm not sure why this configuration isn't the default?

**Comment by jamuhl** [comment]
The problem is neither `t()` nor `Trans` listen to any language change (t not even has an option as it's only a function that returns a string. For the Trans component it would be possible - but we decided to not overload that component further - as it already does a lot of things).

So basically there are two things:

- Used for translation: `t`, `Trans`
- Used to load, assert loaded (Suspense or ready param), react to changes like language change (and further bindI18n, bindI18nStore): `useTranslation`, `withTranslation`, `Translation (render prop)`

This is documented partially here: https://react.i18next.com/latest/trans-component#important-note

**Comment by ThisIsMissEm** [comment]
Yeah, we're using `useTranslation` exclusively in our code (as we actually have a wrapper due to having multiple namespaces), but even when using `useTranslation` we weren't seeing UI updates because the events weren't connected how we'd expect.

Is there a reason the default events listened on are just "loaded" and not also "languageChanged" and "languageChanging"?

**Comment by jamuhl** [comment]
defaults are https://github.com/i18next/react-i18next/blob/master/src/context.js#L4 only trigger on languageChanged

trigger on languageChanging is only useful if you like to show a spinner instead of the old language before showing new language...

**Comment by nguyenvantruong17** [comment]
@jamuhl 
I've got the same issue.
On some components, it is using the value of i18n.language to show something.
When I call the changeLanguage API, it does not trigger re-render.
**"react-i18next": "^11.7.1"**

**Comment by jamuhl** [comment]
@nguyenvantruong17 please provide a codesandbox for reproduction...

**Comment by nguyenvantruong17** [comment]
@jamuhl You can check
https://codesandbox.io/s/react-i18next-fsmiu?file=/src/App.js

**Comment by jamuhl** [comment]
your sample does not useTranslation in footer plus setting language in a useEffect might not be the best idea (should be a user interaction) https://codesandbox.io/s/react-i18next-forked-886gw?file=/src/components/footer.js

**Comment by nguyenvantruong17** [comment]
@jamuhl Could you tell me why this work with **setTimeout**. It seems to need to wait for a second before that the component is mounted.

**Comment by jamuhl** [comment]
@nguyenvantruong17 no, I can not tell you why as it seems to be something in react not react-i18next. Might have todo with how react does things internally to optimize rendering. But idk - just know it's not caused by our internals as those are more or less stupid pub/sub bindings.

**Comment by ThisIsMissEm** [comment]
> defaults are https://github.com/i18next/react-i18next/blob/master/src/context.js#L4 only trigger on languageChanged
> 
> trigger on languageChanging is only useful if you like to show a spinner instead of the old language before showing new language...

what about "loaded" as an event to trigger on?

**Comment by jamuhl** [comment]
not needed...loaded happens before when either ready is false or Suspense fallback gets shown -> the load request gets resolved:

Suspense case: https://github.com/i18next/react-i18next/blob/master/src/useTranslation.js#L87
Not using suspense case: https://github.com/i18next/react-i18next/blob/master/src/useTranslation.js#L52

So only case you would have to bind that is if you load/reload namespaces outside of the regular use

**Comment by ThisIsMissEm** [comment]
Which we do, as we use code-splitting.

**Comment by jamuhl** [comment]
Not sure how this relates to code-splitting. When a namespace is loaded also the newly "lazy" import won't reload it...only manually triggering a namespace reload using i18next.reload...

**Comment by ThisIsMissEm** [comment]
We dynamically load different namespaces by using `useTranslation` hook and `i18next-http-backend`, we then reload them using `i18next-hmr` in development, and found that by default i18next does not re-render when we expected it to, we required additional configuration, as given in https://github.com/i18next/react-i18next/issues/1171#issuecomment-689234418

**Comment by jamuhl** [comment]
So all green...works for you...defaults try to be safe to be used in common scenarios not over rerender unnecessary...which could happen with binding additional stuff.
