### ISSUE TITLE
Support passing JSX to <Trans values={{ ... }} />

### ISSUE THREAD

**Issue by jackocnr** [i18next/react-i18next#1173]
Hello, just wanted to say thanks so much for all the great work on react-i18next - love the project!

## 🚀 Feature Proposal

It would be great if we were able to pass JSX in the values prop to the Trans component - see example below.

Cheeky second request: we use `\n` new lines in our translation strings - would it be possible to automatically convert those to `<br />` components?

## Motivation

I saw that recently there was support added for custom tags in translation strings (as per [Alternative usage (v11.6.0)](https://react.i18next.com/latest/trans-component#alternative-usage-v-11-6-0) section of the docs), which is a great step forward from the numeric indexed tags, but it still requires translators to handle HTML, which is not ideal. If we allowed JSX to be passed as values, that would mean us developers could handle all the markup, and the translators could just focus on the text.

## Example

If your translation string is "Hello {{name}}, please {{login}} to continue."

```js
<Trans
    i18nKey="..."
    values={{
        name: <strong>John</strong>,
        login: <a href="/login">Login</a>,
    }}
/>
```

**Comment by jamuhl** [comment]
How do you translate the text "Login" in your login a tag?

For things like <br />, <strong> you can use https://react.i18next.com/latest/trans-component#using-for-less-than-br-greater-than-and-other-simple-html-elements-in-translations-v-10-4-0 guess technical translators can handle those simpler HTML stuff.

There is no build in option to convert /n to <br /> ... sorry

**Comment by jackocnr** [comment]
Thanks for your quick reply @jamuhl!

> How do you translate the text "Login" in your login a tag?

I would use the `t()` function for simple translations like this. So you might end up with something like this:

```js
const loginLink = (
  <a href="/login">
    {t('login_key')}
  </a>
);
<Trans
  i18nKey="..."
  values={{
    name: <strong>John</strong>,
    login: loginLink,
  }}
/>
```

> guess technical translators can handle those simpler HTML stuff.

Sure, but unfortunately some of the translators we work with are not technical, and we end up with a lot of mistakes that waste everyone's time.

**Comment by jackocnr** [comment]
I suppose the other advantage to keeping your markup in your code as opposed to your translation strings is that it's much easier to maintain. Esp if, like us, you need to support several different languages, then whenever you need to update a tag you have to do it in several places.

**Comment by jamuhl** [comment]
Not sure if I like the idea of further bloat the complexity in the Trans component...but feel free to provide a PR including tests and relevant additions.
