### ISSUE TITLE
i18Next Provider doesn't preserve i18next instance

### ISSUE THREAD

**Issue by yuschick** [i18next/react-i18next#1175]
## 🐛 Bug Report

I am working on a central repo that will be a sibling to a few other projects and installed via npm locally ("central-repo": "file:../central-repo"). This central repo exports out an i18NextProvider with a configured i18n instance. However, when I then wrap an app in this provider and try to use `useTranslation()` I receive a warning that an i18n instance must be provided.

`react-i18next:: You will need to pass in an i18next instance by using initReactI18next `

The central repo is being bundled through Rollup via Microbundle.

## To Reproduce

`Central Repo - package.json``
````
"peerDependencies": {
  "react-i18next": "^11.7.2"
},
"devDependencies": {
  "i18next": "^19.7.0",
  "react-i18next": "^11.7.2"
},
`````

`Central Repo - LanguageProvider.tsx`
````js
const LanguageProvider: React.FC = ({ children }) => {
  const resources = {
    en: {
      translation: { ... },
    },
    fi: {
      translation: { ... },
    },
  };
    
  i18n.use(initReactI18next).init({
    lng: 'fi',
    fallbackLng: LANGUAGES.FI,
    resources,
  });

  return <I18nextProvider i18n={i18n}>{children}</I18nextProvider>;
};
````

`Central Repo - CentralProvider.tsx`
````js
const PositiveProvider: React.FC<Props> = ({ target, theme, children }) => {
  const store = createStore(
    { ...storeModel, target, theme },
    { injections: {} }
  );
    
  return (
    <StoreProvider store={store}>
      <LanguageProvider>{children}</LanguageProvider>
    </StoreProvider>
  );
};
````

`React App - package.json``
````
"devDependencies": {
  "react-i18next": "^11.7.2"
},
`````

`React App - Index`
````js
ReactDOM.render(
  <CentralStore>
    <App />
  </CentralStore>,
  document.getElementById('root')
);
````

`React App - App`
````js
const App = () => {
  const { t } = useTranslation();
   
  return (
    <Heading as="h1">
      {t('route.landing.welcome_msg')}
    </Heading>
  )
}
````

## Expected behavior

I would expect that the Provider from the central repo would pass its i18n instance down to whichever app is consuming it.

## Your Environment

System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 938.47 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.6.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 85.0.4183.102
    Firefox: 79.0
    Safari: 13.1.2

**Comment by jamuhl** [comment]
Do you have multiple i18next, react-i18next in your build/node_modules? We got a similar setup in one of our bigger lerna powered monorepo...and works as long we do not have multiple i18next around (like having multiple react - that won't make you happy)

**Comment by yuschick** [comment]
It looks like it. When I run `npm ls react-i18next` in my terminal I get this report:

```shell
web-ui@0.1.0.../react-app
├─┬ central-store@1.0.0 ->.../central-store
│ └── react-i18next@11.7.2  extraneous
└── react-i18next@11.7.2
````

Is there a way I could rework my package files to handle this? Would NPM Link work? This area is very fuzzy to me.

**Comment by jamuhl** [comment]
no npm link just links...you got the module there...it's in the linked to...

building -> excluding by setting module external in your rollup config...

```js
import babel from 'rollup-plugin-babel';

export default {
  external: ['react', 'react-dom', 'i18next', 'react-i18next'],
  input: 'main.js',
  output: {
    file: 'bundle.js',
    format: 'iife'
  },
  plugins: [
    babel({
      presets: ['react']
    })
  ]
};
```

**Comment by yuschick** [comment]
Thanks. This sounds hopeful, just trying to figure out how to do this within microbundle.

If successful, I suspect I can re-install my central package into the react-app and when I run `npm ls react-i18next` I should only see one entry. Correct?

**Comment by jamuhl** [comment]
in outer app it can be a dependency...in all others only peer

**Comment by yuschick** [comment]
In my central store, I have ì18next` and `react-i18next` as dependencies.

Then in my react-app, i have `react-i18next` only as a peerDependency. But then when I start the react app, it errors as if `react-i18next` is not found.

`Module not found: Can't resolve 'react-i18next'`

**Comment by jamuhl** [comment]
such big project configurations are always a little pain...not much I can do from here (beside guessing)....sorry

**Comment by yuschick** [comment]
I totally understand. Thanks for helping though. If I track down a solution, I'll add it here just in case.
