### ISSUE TITLE
Dummy text is needed at start in JSX Trans when first element is <1>

### ISSUE THREAD

**Issue by Noitidart** [i18next/react-i18next#1177]
## To Reproduce

A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

My json file:

```
{
  "homepage": {
    "alerts": {
      "interviewRequired": "<1>Interview Required</1> You cannot view this page until you pass your interview below."
    }
  }
}
```

My JSX:

```
          <Trans i18nKey="homepage.alerts.interviewRequired">
            if i dont put dumy text here, the h4 is left with foo in it
            <h4 className="alert-heading">foo</h4>
            bar
          </Trans>
```

## Expected behavior

I should not need to include that dummy text of `if i dont put dumy text here, the h4 is left with foo in it` in order for "Interview Required" to populate into the h4.

## Your Environment

- *runtime version*: node v12
- *i18next version*: 19.7.0
- *os*: Mac
- *any other relevant information* Firefox v80

**Comment by jamuhl** [comment]
Not sure (tested) but I don't think you need the dummy text if having correct index in your translation:

```jsx
 <Trans i18nKey="homepage.alerts.interviewRequired">
            <h4 className="alert-heading">foo</h4>
            bar
</Trans>
```
-> `h4` is child at index 0 therefore translation should be:

```json
{
  "homepage": {
    "alerts": {
      "interviewRequired": "<0>Interview Required</0> You cannot view this page until you pass your interview below."
    }
  }
}
```

**Comment by Noitidart** [comment]
Oh gosh I'm new I didn't realize that was index! Thank you so much I'll close this out.

**Comment by Noitidart** [comment]
I'm having another similar issue I think.
This is my json:
```
{
"footer": "Think you're seeing this message in error? <0/> Then contact us <1>here.</1>"
}
```

And this is my JSX:
```
          <p>
            <Trans i18nKey="footer">
              Didn't expect this?
              <br className="d-none d-sm-inline" />
              Ok fine then send us an email <a href="/contact">by clicking here.</a>
            </Trans>
          </p>
```

But on load I get the error:

````
br is a void element tag and must neither have `children` nor use `dangerouslySetInnerHTML`.
    in br (created by Status403)
    in Trans (created by Status403)
```

**Comment by jamuhl** [comment]
`br` can not have a className

**Comment by Noitidart** [comment]
> `br` can not have a className

Thank you but that didn't fix it. This fixed it but I don't understand why can you please help me undestand:

```
{
"footer": "Think you're seeing this message in error? <1/> Then contact us <3>here.</3>"
}
```

It seems the docs on Trans can be little better. I'm not sure why this works. They also say there is a non-index way to do this? May you please share that non-index way with me?

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/6372489/94290494-1af3d080-ff0f-11ea-9a02-1ca28e96aa59.png">

**Comment by jamuhl** [comment]
read the docs...it explains in detail how index works: https://react.i18next.com/latest/trans-component#how-to-get-the-correct-translation-string

and with named: https://react.i18next.com/latest/trans-component#alternative-usage-v-11-6-0

If you like you can help improving the docs 🙏

**Comment by Noitidart** [comment]
Oh thank you so much!
