### ISSUE TITLE
Module not found: Can't resolve 'i18next' in

### ISSUE THREAD

**Issue by gnusiva** [i18next/react-i18next#1179]
i just followed your documentation and i am getting this error. 

`Module not found: Can't resolve 'i18next' in
`

**Comment by adrai** [comment]
Have you installed i18next?

npm i i18next

**Comment by gnusiva** [comment]
hi adrai, 

yes it is working after i installed i18next 

please update your below documentation page, it is showing only to install react-i18next
[https://react.i18next.com/getting-started](https://react.i18next.com/getting-started)

but under quick-start page, you have it documented properly. 
[https://react.i18next.com/guides/quick-start](https://react.i18next.com/guides/quick-start)

**Comment by gnusiva** [comment]
for others facing similar issue, please install all the modules mentioned in i18n.js file

`npm i i18next i18next-http-backend i18next-browser-languagedetector react-i18next `

**Comment by adrai** [comment]
just fixed the documentation there... thx

**Comment by gorbatkoff** [comment]
import "i18next";
not 
import './i18n';

Removed relative import according to the documentation.

**Comment by Mazraatek** [comment]
Still not working.
Can we have a WORKING sample: Just 2 button and a text?

**Comment by adrai** [comment]
> Still not working. Can we have a WORKING sample: Just 2 button and a text?

@Mazraatek please provide a minimal reproducible example showing that it's not working.

**Comment by Mazraatek** [comment]
Just as soon as I try:
       npm install react-i18next i18next --save
It gives me:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: next@12.3.2
npm ERR! Found: react@16.14.0
npm ERR! node_modules/react
npm ERR!   peer react@"^16.8.0 || ^17.0.0-rc.1 || ^18.0.0" from @react-aria/ssr@3.3.0
npm ERR!   node_modules/@react-aria/ssr
npm ERR!     @react-aria/ssr@"^3.2.0" from @restart/ui@1.4.0
npm ERR!     node_modules/@restart/ui
npm ERR!       @restart/ui@"^1.3.1" from react-bootstrap@2.5.0
npm ERR!       node_modules/react-bootstrap
npm ERR!         react-bootstrap@"^2.4.0" from the root project
npm ERR!   peer react@">=16.8.0" from @restart/hooks@0.4.7
npm ERR!   node_modules/@restart/hooks
npm ERR!     @restart/hooks@"^0.4.7" from @restart/ui@1.4.0
npm ERR!     node_modules/@restart/ui
npm ERR!       @restart/ui@"^1.3.1" from react-bootstrap@2.5.0
npm ERR!       node_modules/react-bootstrap
npm ERR!         react-bootstrap@"^2.4.0" from the root project
npm ERR!     @restart/hooks@"^0.4.6" from react-bootstrap@2.5.0
npm ERR!     node_modules/react-bootstrap
npm ERR!       react-bootstrap@"^2.4.0" from the root project
npm ERR!   18 more (@restart/ui, formik, prop-types-extra, qrcode.react, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^17.0.2 || ^18.0.0-0" from next@12.3.2
npm ERR! node_modules/next
npm ERR!   next@"^12.2.1" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react@18.2.0
npm ERR! node_modules/react
npm ERR!   peer react@"^17.0.2 || ^18.0.0-0" from next@12.3.2
npm ERR!   node_modules/next
npm ERR!     next@"^12.2.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by adrai** [comment]
https://locize.com/blog/react-i18next/

But then please first learn the basics of react.... And do not pollute this issue but maybe ask at Stackoverflow, sorry.

**Comment by MervelMath** [comment]
@Mazraatek 
Are you in the root folder? I got a similar error when the folder opened was not really the root project folder.
