### ISSUE TITLE
TypeScript error index.d.ts(36,25)

### ISSUE THREAD

**Issue by xumoyan** [i18next/react-i18next#1180]
TypeScript error in /node_modules/react-i18next/src/index.d.ts(36,25):
';' expected.  TS1005

    34 |     Partial<WithT> {
    35 |   children?: React.ReactNode;
  > 36 |   components?: readonly React.ReactNode[] | { [tagName: string]: React.ReactNode };
       |                         ^
    37 |   count?: number;
    38 |   defaults?: string;
    39 |   i18n?: i18n;

- *node*: v12.18.3 chrome
- *react-i18next version*:11.7.3
- *i18next version*:19.7.0
- *os*: Mac

**Comment by rosskevin** [comment]
I think you should try `rm -rf node_modules` and reinstall.  There is some kind of problem local to you environment.  

Certainly I'm not excluding the possibility of something wrong in this library, but our tests would be failing in that case.  If you can PR a failing test then let's reopen this.

**Comment by PeterSR** [comment]
I am seeing the same issue. 

I tried to remove `node_modules` and reinstall with `npm install`, but I am still facing the same issue. 
We are trying to add `react-i18next` to a project that is a bit dated (1-2 years). 

Versions:

```
node: v10.19.0

typescript@3.3.3
react@16.8.2
@types/react@16.8.3
i18next@19.8.2
react-i18next@11.7.3
```

I followed https://react.i18next.com/guides/quick-start and as soon as `import './i18n';` is added, it complains.

**Comment by PeterSR** [comment]
Not entirely sure how to create PR with a test that shows the error, but here is a minimum non-working example with the skeleton we are using as well as all the packages we are using:

[react-i18next-typescript-test.zip](https://github.com/i18next/react-i18next/files/5343160/react-i18next-typescript-test.zip)

When running 

```
npm install
npm start
```

It will give the following error:

```
TypeScript error in /path/to/react-i18next-typescript-test/node_modules/react-i18next/src/index.d.ts(36,25):
';' expected.  TS1005

    34 |     Partial<WithT> {
    35 |   children?: React.ReactNode;
  > 36 |   components?: readonly React.ReactNode[] | { [tagName: string]: React.ReactNode };
       |                         ^
    37 |   count?: number;
    38 |   defaults?: string;
    39 |   i18n?: i18n;
```

If the `i18n.ts` and `import './i18n';` is removed the example compiles.

**Comment by PeterSR** [comment]
Cutting the `package.json` down to the bare minimum and removing the `package-lock.json` solves the problem: 

[package.json.zip](https://github.com/i18next/react-i18next/files/5343387/package.json.zip)

Of course, that is not a solution since we need the packages, but it is a start.

**Comment by void-m4110c** [comment]
Hi, are there any news on this? I have the same problem and deleting `package-lock.json` does not help.

**Comment by Cognisun-quawnee** [comment]
> Hi, I have the same problem, and deleting package-lock.json does not help.

![Screenshot_1](https://user-images.githubusercontent.com/79844423/113412115-14ba4180-93d5-11eb-8894-50b57b74dd60.png)

**Comment by pedrodurek** [comment]
Hey @Cognisun-quawnee, it's hard to say what's happening on your end, but here you can see that this type structure is totally acceptable https://tsplay.dev/Nn6BeN. My suggestion is to set `skipLibCheck` to true (in your tsconfig), which is recommended to reduce compilation time, and your problem will likely be gone.
