### ISSUE TITLE
Add additional simple HTML tags in translations

### ISSUE THREAD

**Issue by jeremy-clearlabs** [i18next/react-i18next#1181]
## 🚀 Feature Proposal

As with de09f8d, can we extend more simple HTML tags for translations?

Proposed list:

* em
* sub
* sup

## Motivation

Some languages use these markup tags differently, and to accommodate for them, they should pass through the HTML.

## Example

```json
{
  "emphasis": "She would like to <em>emphasize</em> her point.",
  "sub": "Reference citation<sub>2</sub> shall be recorded",
  "sup": "As a footnote<sup>*</sup> shows, you shall not pass."
}
```

**Comment by jamuhl** [comment]
PR welcome.
