### ISSUE TITLE
Refreshing the page twice by using i18next with Gatsby plugin.

### ISSUE THREAD

**Issue by StefanSelfTaught** [i18next/react-i18next#1184]
## 🐛 Bug Report

I am using i18next in Gatsby with the help of [this](https://github.com/microapps/gatsby-plugin-react-i18next) Gatsby plugin. When I change the default language and then revisiting the website it refreshes the page to detect the language I selected.

Is this a normal behaviour or it's just from the Gatsby plugin?

## To Reproduce

https://codesandbox.io/s/compassionate-volhard-d3p04

## Expected behavior

I expect not to double refresh the page.

## Your Environment

- *runtime version*: node 12.17.0
- *i18next version*: 19.7.0
- *os*: Windows

**Comment by adrai** [comment]
You may ask @jimmyn never used that plugin myself.

**Comment by ashnamuh** [comment]
I have a same issue

**Comment by jamuhl** [comment]
better ask at https://github.com/microapps/gatsby-plugin-react-i18next#readme -> it's more related to gatsby usage as react-i18next
