### ISSUE TITLE
Improve step by step guide

### ISSUE THREAD

**Issue by gnusiva** [i18next/react-i18next#1185]
hi, in your step by step guide, there no clear information about where to create the translation key-value json file. 
Can u please add one line describing that in better way, probably you can give one sample code block and where to create it.
![image](https://user-images.githubusercontent.com/131292/96178739-708b2e00-0f4d-11eb-849d-cf35e7dcdbed.png)

**Comment by gnusiva** [comment]
you can also provide information on what are the possible language's short-name ( folder names ) that can be created.

**Comment by adrai** [comment]
Feel free to provide a PR if you like.
