### ISSUE TITLE
Can I get full list of resource keys 

### ISSUE THREAD

**Issue by edcurtin** [i18next/react-i18next#1187]
Really liking the flexibility of the react implementation. I would like to generate a tsx component containing labels populated with every resource key, my intention would be to ensure all resources are translated I would like to avoid having to parse JSON. Can I ask do I have the ability to get a full list of resource keys for my i18next resources 

I would use this to iterate over and add a label for each one my unit test would then interrogate the labels collection and expect no empty strings 

And I would iterate through all the supported languages in my app. Firstly I need the full list of resource keys 

Any and all help appreciated :)

**Comment by jamuhl** [comment]
you can https://www.i18next.com/overview/api#getresourcebundle -> flatten the result and Object.keys -> tada...all keys

**Comment by edcurtin** [comment]
Thanks very much appreciate the assist :)

**Comment by elibroftw** [comment]
> you can https://www.i18next.com/overview/api#getresourcebundle -> flatten the result and Object.keys -> tada...all keys

How does this help? getResourceBundletakes a language key and only returns the resource bundle for that specific language.

**Comment by guther** [comment]
I think you're lokking for this: 

```
const resourcesArray: string[] = Object.keys(i18n.options.resources);

console.log(resourcesArray);
```
