### ISSUE TITLE
Library and App using same i18n store

### ISSUE THREAD

**Issue by ButuzGOL** [i18next/react-i18next#1188]
I have lib which initialize i18n and using useTranslation
and App which initialize i18n and using useTranslation

and version of react-i18next and i18next so yarn moves it top lvl so app and lib use same place
in this case i have i am using only one i18n store in app and lib based on { t } = useTranslation

**Comment by adrai** [comment]
I don't understand exactly what your issue is, but probably you just need to define i18next as peerDependency in your lib's package.json

**Comment by ButuzGOL** [comment]
seems like it should be opposite to peerdep
as i understand react-i18next shares same context in app and lib

**Comment by adrai** [comment]
we use i18next as peerDependency in our library orojects and as normal dependency in our app projects
