### ISSUE TITLE
support react-native-windows

### ISSUE THREAD

**Issue by capc0** [i18next/react-i18next#1189]
## 🚀 Feature Proposal

support for react-native-windows

## Motivation

as stated on https://reactnative.directory/ windows is currently not supported

**Comment by adrai** [comment]
Never used react-native-windows myself, but react-i18next is just plain javascript.... so in my opinion it should just work on windows.

**Comment by adrai** [comment]
Here a little example as proof, this works with react-native-windows => https://github.com/i18next/react-i18next/tree/master/example/react_native_windows
