### ISSUE TITLE
Module undefined

### ISSUE THREAD

**Issue by ArthurBrito** [i18next/react-i18next#1190]
## 🐛 Bug Report

It seems to me that this is related to Webpack or something similar. This issue appeared in my production environment when I upgraded to Webpack 5, when I downgraded to 4 it works fine.

The module is undefined and cannot be used in the i18next. If you try to use the removing the uncommented code in the codesandbox example the i18next will return an error saying that:

> Error: You are passing an undefined module! Please check the object you are passing to i18next.use()

If I remove the Backend and LanguageDetector node modules the error still persists.

## To Reproduce

A [codesandbox](https://codesandbox.io/s/laughing-volhard-50hzn?file=/src/App.js)

```js
import initReactI18next from "react-i18next";
console.log(initReactI18next) // undefined
```

## Expected behavior

The module should have work.

## Your Environment
react: 17.0.1
react-dom: 17.0.1
react-i18next: 11.7.3
react-scripts: 3.4.3

**Comment by adrai** [comment]
It's

import { initReactI18next } from "react-i18next"
