### ISSUE TITLE
App broken with Add a <Suspense fallback=...>

### ISSUE THREAD

**Issue by dusanbass** [i18next/react-i18next#1191]
## 🐛 Bug Report

App wont render and there are errors in console because of "Suspense fallback error" as displayed on the image below:
![1](https://user-images.githubusercontent.com/8012306/97541993-537f4200-19c6-11eb-9721-9b6a39057ddc.png)

## To Reproduce

use https://www.npmjs.com/package/cra-template-redux-typescript
npx create-react-app my-app --template redux-typescript
following https://react.i18next.com/latest/using-with-hooks

App.tsx
```
import React, { Suspense } from 'react';
import logo from './logo.svg';
import { Counter } from './features/counter/Counter';
import './App.css';
import { useTranslation } from 'react-i18next';

function App(): JSX.Element {
  const { t, i18n } = useTranslation();

  return (
    <Suspense fallback="loading">
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <Counter />
          <p>
            {t('edit')} <code>src/App.tsx</code> {t('and save to reload')}.
          </p>
          <span>
            <span>Learn </span>
            <a
              className="App-link"
              href="https://reactjs.org/"
              target="_blank"
              rel="noopener noreferrer"
            >
              React
            </a>
            <span>, </span>
            <a
              className="App-link"
              href="https://redux.js.org/"
              target="_blank"
              rel="noopener noreferrer"
            >
              Redux
            </a>
            <span>, </span>
            <a
              className="App-link"
              href="https://redux-toolkit.js.org/"
              target="_blank"
              rel="noopener noreferrer"
            >
              Redux Toolkit
            </a>
            ,<span> and </span>
            <a
              className="App-link"
              href="https://react-redux.js.org/"
              target="_blank"
              rel="noopener noreferrer"
            >
              React Redux
            </a>
          </span>
        </header>
      </div>
    </Suspense>
  );
}

export default App;
```

My only one translation file is in:
```public\locales\en-US\translation.json```

My i18n.js file. And why it won't work if renamed this to i18n.ts?
```
import i18n from 'i18next';
import Backend from 'i18next-http-backend';
import LanguageDetector from 'i18next-browser-languagedetector';
import { initReactI18next } from 'react-i18next';

i18n
  // load translation using http -> see /public/locales
  // learn more: https://github.com/i18next/i18next-http-backend
  .use(Backend)
  // detect user language
  // learn more: https://github.com/i18next/i18next-browser-languageDetector
  .use(LanguageDetector)
  // pass the i18n instance to react-i18next.
  .use(initReactI18next)
  // init i18next
  // for all options read: https://www.i18next.com/overview/configuration-options
  .init({
    fallbackLng: 'en',
    debug: true,
    react: {
      // useSuspense: false,
    },
    interpolation: {
      escapeValue: false, // not needed for react as it escapes by default
    },
  });

export default i18n;
```

## Expected behavior

App would render correctly.

I can jump over this by inserting 
```
react: {
      // useSuspense: false,
    },
```
But I wish to use proper way as it is displayed in your tutorial.

## Your Environment
* "i18next": "^19.8.3",
* "i18next-browser-languagedetector": "^6.0.1",
* "i18next-http-backend": "^1.0.21",
* "react": "^17.0.1",
* "react-dom": "^17.0.1",
* "react-i18next": "^11.7.3",
* node -v v12.19.0
* npm -v 6.14.8

**Comment by adrai** [comment]
You are calling "useTranslation" outside of the Suspense component

**Comment by dusanbass** [comment]
I don't understand that. 
I used <Suspense> and in other place but it worked. Like here:

```
ReactDOM.render(
  <React.StrictMode>
    <Provider store={store}>
      <Suspense fallback="loading...">
        <App />
      </Suspense>
    </Provider>
  </React.StrictMode>,
  document.getElementById('root'),
);
```

Why it won't work inside that component where it is used?

**Comment by adrai** [comment]
The message is: "Add a <Suspense fallback=...> component higher in the tree", but you used `useTranslation` outside of the Suspense component.

More information here: https://github.com/i18next/react-i18next/issues/1026#issuecomment-568770418

**Comment by jamuhl** [comment]
it's rather simple but easy to misunderstand:

```js
function App(): JSX.Element {
  const { t, i18n } = useTranslation();

  return (
    <Suspense fallback="loading">
      <div className="App">
    ...
```

The Suspense here wraps the div (react element) but not your App which uses useTranslation

**Comment by dusanbass** [comment]
@adrai thanks for the https://github.com/i18next/react-i18next/issues/1026#issuecomment-568770418 comment!!! That explains it.

@jamuhl you're the one who described it well so thank to you too! :)
And hey, I've played around, and this won't work too:
```
<p>
  <Suspense fallback="loading...">
    t('edit')} <code>src/App.tsx</code> {t('and save to reload')}.
  Suspense>
</p>
```
or 
```
<Suspense fallback="loading...">
  <p>
    {t('edit')} <code>src/App.tsx</code> {t('and save to reload')}.
  </p>
</Suspense>
```

**Comment by adrai** [comment]
The problem is not the `t` call but the `useTranslation` call

**Comment by dusanbass** [comment]
Summary of the React documentation link: Suspense is for the early adoption.

So to sum it up for this case and close it: are hooks recommended use for this library?
If yes, is Suspense recommended?

Or to just use HOC or yours Translation component?

**Comment by adrai** [comment]
Personally, I use always hooks and Suspense... the react community is using this mostly nowadays...

**Comment by dusanbass** [comment]
Thanks for that insight!

Last one, referring to my previous comment,

do you use like one major Suspense above the whole app, or you wrap each component individually?

**Comment by adrai** [comment]
It depends... but usually per page 1 Suspense or for bigger data loading sections

**Comment by dusanbass** [comment]
Aha, ok. 
Well, I suppose this sums it up. 

I'm closing this due to my inexperience and misuse.

Thank you @adrai and @jamuhl very much.

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏

**Comment by dusanbass** [comment]
I will absolutely!!!  
I've seen https://locize.com too and it appears as an awesome service - tool.

I'm new at this, but this library seems powerful from the beginning.
Thanks again!

**Comment by ashish3010** [comment]
So , I am downloading the json file from server, until the it downloads , the UI shows the json placeholders I am using, So, I wanted to use a loader screen to prevent that, Can anyone help me with this. But I am trying to avoid React Suspense if possible..
