### ISSUE TITLE
Translations not happening after loading resource files using i18next-http-backend

### ISSUE THREAD

**Issue by lekhasharma** [i18next/react-i18next#1192]
Hi, I am using react-i18next and wanted to use lazy loading. I used the i18next-http-backend plugin for the same. Although the required resource file is loading correctly, the translations don't happen and I can see the labels on the UI instead of translated text. I am using withTranslation HOC and this is my configuration :

i18next
  .use(initReactI18next)
  .use(Backend)
  .init({
    interpolation: {
      escapeValue: false
    },
    lng: 'en',
    ns: 'common',
    defaultNS: 'common',
    keySeparator: false,
    fallbackLng: 'en',
    backend: {
      loadPath: '/locales/{{lng}}/{{ns}}.js',
    },
    react: {
      wait: true
    }
});

**Comment by adrai** [comment]
Please provide a reproducable example

**Comment by lekhasharma** [comment]
Hi, so this is a snippet of the code :+1: 
`/* eslint-disable camelcase */
import React from 'react';

import Accordion from './Accordion';
import {withTranslation} from 'react-i18next';

class AppContent extends React.Component {
  render() {

    const {t} = this.props;
    return (
      <React.Fragment>
        <Accordion
          panelHeading={t('LABEL.NewReport')}
        />
      </React.Fragment>
    );
  }
}

export default withTranslation('common')(AppContent);
`
also I set debug : true as you mentioned and this is the error in the console : **i18next::translator: missingKey en common LABEL.NewReport LABEL.NewReport**

In the network tab I can see that the common.js file is loaded for 'en'

**Comment by adrai** [comment]
Please provide a complete reproducable example. codesandbox or similar.
You are probably not waiting for the translations to be loaded: https://react.i18next.com/latest/usetranslation-hook#not-using-suspense
![image](https://user-images.githubusercontent.com/1086194/97559349-9a2c6680-19dd-11eb-9681-18ee542c35ad.png)

**Comment by lekhasharma** [comment]
Hi, turns out my .js file was not getting converted to .json properly. Hence it couldn't find the translation keys. I saw a warning in the console after setting debug to true, thanks for the help, will close this issue.

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏
