### ISSUE TITLE
Cannot read property 'displayName' of undefined

### ISSUE THREAD

**Issue by thoaihuynh97** [i18next/react-i18next#1194]
## To Reproduce

A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

```js
https://github.com/isaachinman/next-i18next/issues/642
```

## Your Environment

- *runtime version*: i.e. node v14, deno, browser xy
- *i18next version*: i.e. 19.5.3
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by jamuhl** [comment]
Please provide a sample for reproduction...never got this error in usage.
