### ISSUE TITLE
i18n re-initialized on its own with partial translations

### ISSUE THREAD

**Issue by Cherviakov** [i18next/react-i18next#1195]
## 🐛 Bug Report

On our website we making transition to react-i18next, on all views it is working normally but on one component
it is suddenly start to report about missing translations. Debug shows that initially i18n loaded normally with all
translations but later on it is initialized again, without any direct call in code to initialize, and resoueces becomes
just first 20-30 items of original translations for given language.

So there three questions:
1. Why i18n can re-initialize on its own?
2. How translations re-loading on such automatic re-initialization?
3. Is there way to hook init event and perform some actions?

## To Reproduce
Sadly I don't know at the moment how to reproduce it, only have this happens on website I working on.
Config is pretty standard

```js
i18n.use(initReactI18next).init({
    resources,
    lng: "en",
    fallbackLng: "en",
});
```

## Expected behavior

i18n should not re-initialize or at least there should be some clear reason to do it, so we can aviod such conditions
or handle loading all translations on new inititalization.

```js
// Paste the expected results here
```

## Your Environment

- *runtime version*: node v14
- *i18next version*: i.e. 19.5.3
- *os*: Mac

**Comment by jamuhl** [comment]
No...there is no auto-reinitializing of i18next or react-i18next...must be something in your code.

**Comment by Cherviakov** [comment]
Thanks, will continue checking.

**Comment by Cherviakov** [comment]
Sorry, thought will have time to check more of this issue but things moved away, not sure when will be able to check it. Will reopen and share details if managed to get to root of it.
