### ISSUE TITLE
Export 'WithTranslation' not found in 'react-i18next'

### ISSUE THREAD

**Issue by rebeccaalpert** [i18next/react-i18next#1196]
## 🐛 Bug Report

We're getting the following TypeScript error when we try to import the type WithTranslation: `"export 'WithTranslation' was not found in 'react-i18next'`

## To Reproduce

The import statement looks like this: `import { WithTranslation, withTranslation } from 'react-i18next';` and we're trying to do something similar to this: https://github.com/i18next/react-i18next/blob/master/test/typescript/withTranslation.test.tsx#L9.

## Expected behavior

We'd expect to be able to import WithTranslation and use it as a type.

## Your Environment

- *runtime version*: node 10.16.2
- *i18next version*: 19.4.3
- *os*: Mac

**Comment by pedrodurek** [comment]
Hello! Did you check your react-i18next version? Because it's being exported here https://github.com/i18next/react-i18next/blob/master/src/index.d.ts#L80.

**Comment by rebeccaalpert** [comment]
Thanks! We upgraded and everything looks good on our end.

**Comment by rebeccaalpert** [comment]
Hey - we noticed that we're still getting some linter errors for "WithTranslation not found in 'react-i18next'" after upgrading. We upgraded to 11.7.3. Any idea what's up?

**Comment by pedrodurek** [comment]
Are you using `@typescript-eslint/parser` as well as `@typescript-eslint/eslint-plugin`?

**Comment by alielkhateeb** [comment]
Hi, I'm facing the same issue with `WithTranslation` and `TFuncKey`
I'm using `@typescript-eslint/parser` with `@typescript-eslint/recommended` in my config

**Comment by pedrodurek** [comment]
Hey @alielkhateeb, I didn't manage to reproduce the error, could you create a minimalistic example on [codesandbox](codesandbox.io)? Thanks!

**Comment by alielkhateeb** [comment]
@pedrodurek I also tried a codesandbox but didn't manage to reproduce it, it's an ESLint error, it goes away if I use `import type { TFuncKey } from 'react-i18next'` have you face it before?

**Comment by pedrodurek** [comment]
Hey @alielkhateeb, that's because the lint rule [consistent-type-imports](https://github.com/typescript-eslint/typescript-eslint/blob/HEAD/packages/eslint-plugin/docs/rules/consistent-type-imports.md) is turned on by default on `@typescript-eslint/eslint-plugin`.
[Type-Only Imports and Export](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export) was introduced in typescript 3.8, which is used to prevent types import from "affecting" runtime (that'll depend on your setup typescript/babel).
> This feature is something most users may never have to think about; however, if you’ve hit issues under --isolatedModules, TypeScript’s transpileModule API, or Babel, this feature might be relevant.

**Comment by alielkhateeb** [comment]
@pedrodurek Awesome, that makes sense! Thank you very much for your help :)
