### ISSUE TITLE
Plural specification when using "Tarns" component with "count" property

### ISSUE THREAD

**Issue by kareemsalah227** [i18next/react-i18next#1199]
## 🚀 Feature Proposal
Currently the way "Trans" component decides whether to use the "_plural" suffixed key, is when passing the property "count" with the other properties that will be used to construct the translated string.

My proposal, is to provide another way, more explicit to code readers, that tells "Trans" which key to use, the singular key or the "_plural" one.

In technical terms, I am suggesting to keep the current "count" usage, and expose another prop "plural" or similar from <Trans> component, that can be used to use the "_plural" version of the translation key.

## Motivation
At first time I saw this in a PR (can't share it, private repo), I thought that "count" will be used in the translation, and I didn't know that it's used to tell "Trans" to use the "_plural" key instead. It was completely ambiguous to me and I thought the PR author was sending a useless "count" property, until I read it on the documentation of i18n.

The motivation behind this proposal is to provide a more readable way to use this features, instead of the current one which I see is a bit ambiguous or not as explicit.

## Example
In this example, it's not clear the importance of `count`, it has 2 effects, the decision of the key to be used, and also it takes part in interpolation.

Component:
```
<Trans values={{count: 5}}>
  TOTAL_ITEMS_IN_CART
</Trans>
```

Locale file:
```
"TOTAL_ITEMS_IN_CART": "You have {{count}} item in cart",
"TOTAL_ITEMS_IN_CART_plural": "You have {{count}} items in cart",
```

In the above example, it's not clear for a new developer that `count` has 2 purposes, now imagine if someone changes count to something else like `numberOfItems`, this change implicitly will affect the overall translation unless the developer is aware that they should also send another property `count` to select the correct key.

Proposed solution example:
```
<Trans values={{count: 5}} plural={count > 1}>
  TOTAL_ITEMS_IN_CART
</Trans>
```

P.S.: I would be happy to contribute it if agree on the proposed feature.

**Comment by jamuhl** [comment]
Your solution is limited...expecting languages work like singular/plural....which is not the case. There are languages having multiple plural forms depending on complexer count rules...

**Comment by kareemsalah227** [comment]
Thank you so much @jamuhl for the insights, I completely didn't know about this.

I would highly appreciate if you point me to where I can read more about "complexer count rules" as I do not understand fully what you are talking about with regards to "complexer count rules".

**Comment by jamuhl** [comment]
https://www.i18next.com/translation-function/plurals#languages-with-multiple-plurals
