### ISSUE TITLE
useTranslation does not return expected t function when the namespace changes across renders.

### ISSUE THREAD

**Issue by nickroth** [i18next/react-i18next#1201]
## 🐛 Bug Report

`useTranslation` does not seem able to handle changing namespaces.

## To Reproduce

https://codesandbox.io/s/react-i18next-switch-namespace-ixhtj?file=/src/app.js

The basic idea is something like 

```
const { t } = useTranslation(somethingThatChangesAcrossRenders);
// Returns only content from the first namespace that was used.
// In this case the key is valid across all namespaces that would be asked for.
const content = t('myKey') 
```

Looking into [useTranslation.js](https://github.com/i18next/react-i18next/blob/master/src/useTranslation.js#L51), it seems that the useEffect lists the namespaces as a dependency of the effect but it is not guaranteed that it will update the `t` state when it does change. If either `ready` or `useSuspense` are true then the effect does not attempt to call `loadNamespaces`.

## Expected behavior

In the example `dynamicT` would able to get the expected content from the changing namespaces.

## Your Environment

- *react-i18next*: 11.4.0
- *i18next*: 19.4.4

**Comment by jamuhl** [comment]
Best would be to prefix your t calls like: `t(\`${somethingThatChangesAcrossRenders}.key\`)`

**Comment by nickroth** [comment]
Thank you very much for the quick reply. I tried your suggestion in the provided sample and in our application and that solved the issue.
