### ISSUE TITLE
Not works as expected

### ISSUE THREAD

**Issue by mtalhagaoglu** [i18next/react-i18next#1202]
## 🐛 Bug Report

Hi I'm new in this library and i can't figure out how its working. I followed instructions in docs step by step but its not working.  Actually working but not how it should do. Devices language is english by default and fallback setting is english also. but this lib thinks im using turkish and showing turkish translations.

## To Reproduce

A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

```js
import i18n from 'i18next';
import {initReactI18next} from 'react-i18next';
import {getLocales} from 'react-native-localize';

import languages from './locales';

i18n.use(initReactI18next).init({
  lng: getLocales()[0].languageCode,
  fallbackLng: 'en',
  supportedLngs: ['tr', 'en'],
  resources: languages,
});

export default i18n;

```
I'm importing this file in App.js

## Expected behavior

It should use english.

## Your Environment

- *i18next version*:17.0.16
- *os*: Windows

**Comment by adrai** [comment]
set debug to true and check the logs....
Smd also check the result of: getLocales()[0].languageCode

**Comment by mtalhagaoglu** [comment]
Hi. Very sorry for late reply.

for being sure to getLocales()[0]languageCode, i removed that writing manually lng: "en". but its still selecting tr language.

i enabled debug mode with debug: true. it says me i18next::translator: missingKey tr

**Comment by adrai** [comment]
Can you paste the logs?

**Comment by adrai** [comment]
Not easy to help without a reproducable example

**Comment by tigerabrodi** [comment]
@mtalhagaoglu There many samples, from which you can create a reproducible example: https://codesandbox.io/examples/package/react-i18next, I'd be down to take a deeper look once the sample has been created, just ping me :tada:
