### ISSUE TITLE
Same 'previous' and 'new' value of language property

### ISSUE THREAD

**Issue by dgnusov** [i18next/react-i18next#1203]
## 🐛 Bug Report

Hi!

Faced an issue when using withTranslation HOC.

Previous value of language property of i18n object is exact same as new one when i'm trying to access it within ComponentDidUpdate method.

Is it a bug or i'm doing something wrong?

I've found a similar old issue: https://github.com/i18next/react-i18next/issues/508
But is seems like that solution is not actual for new versions.

## To Reproduce

https://codesandbox.io/s/great-moore-04ob5

## Expected behavior

Previous value and new value not same.

## Your Environment

i18next 19.7.0
react 16.12.0
react-i18next 11.7.3

**Comment by jamuhl** [comment]
`i18n` is the prop -> that i18n instance did not change -> so accessing something like i18n.language will always show the current value

**Comment by dgnusov** [comment]
@jamuhl so i need to implement some logic to track that at my side.
Ok! I have no problem with that :) Just wanted to check if there any other more natural solution.

Thank you for reply!
