### ISSUE TITLE
Conversion to React Testing Library

### ISSUE THREAD

**Issue by tigerabrodi** [i18next/react-i18next#1207]
## Conversion to React Testing Library

Since I and my friends will be working on this conversion, we thought of creating an issue to track the progress. :clap: 

How do you prefer us to work, in separate small PRs or a few bigger ones? :roll_eyes: 

Our suggestion would be to work in smaller PRs, as they are easier to review. :raised_hands: 

I was thinking personally, not more than one test for each PR? :thinking: 

What do you think @adrai and @jamuhl, any suggestions/questions? :smiley: 

Also thanks for this oppoturnity :two_hearts: :smiling_face_with_three_hearts:

**Comment by adrai** [comment]
Personally I like 1 big PR, with incremental commits, but at the end of the day, do it however you like to do ;-)

**Comment by tigerabrodi** [comment]
Closing this issue, PR has been merged :tada: :metal: :stuck_out_tongue_closed_eyes:
