### ISSUE TITLE
TypeScript 4.1 types and default namespace

### ISSUE THREAD

**Issue by hagmic** [i18next/react-i18next#1216]
## 🐛 Bug Report

The TS 4.1 change does not take the `defaultNS` into consideration.

## To Reproduce

Repo: https://github.com/hagmic/react-i18next-ts-bug

1. Add a `defaultNS: 'ns1'` to the i18next config. [Link](https://github.com/hagmic/react-i18next-ts-bug/blob/master/src/i18n/config.ts#L16)
2. Attempt translation without providing a namespace. [Link](https://github.com/hagmic/react-i18next-ts-bug/blob/master/src/App.tsx#L7)
```js
  const { t } = useTranslation();
  t('title');
```
3. Receive TS error. Run `yarn types:check`
```js
No overload matches this call.
  Overload 1 of 2, '(key: never, options?: string | TOptions<StringMap> | undefined): never', gave the following error.
    Argument of type 'string' is not assignable to parameter of type 'never'.
  Overload 2 of 2, '(key: never, defaultValue?: string | undefined, options?: string | TOptions<StringMap> | undefined): never', gave the following error.
    Argument of type 'string' is not assignable to parameter of type 'never'.
```

## Expected behavior

The TypeScript types should take the `defaultNS` into consideration.

**Comment by adrai** [comment]
//cc: @pedrodurek

**Comment by pedrodurek** [comment]
Hey @hagmic, as typescript cannot infer the defaultNamespace based on the configuration file, you would have to do like this to work: `const { t } = useTranslation<'ns1'>();`.

But I create a way to override the "default" one using type augmentation as you did here, but for the default namespace: 
https://github.com/hagmic/react-i18next-ts-bug/blob/master/%40types/react-i18next/index.d.ts

As soon as I have some time, I'll also add some info about how to use this new ts feature on the react-i18next documentation.

**Comment by nator** [comment]
The @pedrodurek workaround gets me going with a single default namespace, but I can't find a way to use other namespaces on the same page. Any update on this one? I'm fairly new to both typescript and react-i18n, so very possible it's user error...

**Comment by pedrodurek** [comment]
Hey @nator, to access other namespaces you should use the following approach:
```tsx
const { t } = useTranslation(['ns1', 'ns2']);
t('ns1:key');
t('ns2:key');
```
More info here: https://react.i18next.com/latest/usetranslation-hook

**Comment by nator** [comment]
Thanks for the reply! I actually think I found my answer under here: https://github.com/i18next/react-i18next/issues/1277

What I was trying to do is a have a global default namespaces that doesn't require prefixing in calls to t(), AND allow mixing in other namespaces on pages that need it. Something like this with `defaultNS: 'common'` set in i18n.init:
```ts
const { t } = useTranslation(['common', 'ns1');
t('keyFromCommonNS');
t('ns2:keyFromNS2');
```
It sounds like that's intentionally not possible, right?

**Comment by pedrodurek** [comment]
yes! In this case you should use it like this:
```tsx
const { t } = useTranslation(['common', 'ns1');
t('common:keyFromCommonNS');
t('ns2:keyFromNS2');
```
