### ISSUE TITLE
Add the option to load i18n only in certain pages or routes

### ISSUE THREAD

**Issue by PaoloDiBello** [i18next/react-i18next#1219]
I'll give you more context here, in my case I need to be able to stop i18n from loading when the user is logged because all the translations come from the back-end. 

Instead when the user is not logged yet, the translations are all loaded from i18n, so it was unecessary to load it anyway when logged as it's not using them.

**Comment by jamuhl** [comment]
The only option I currently see to achieve this is adding a wrapper component in your app that either loads a component extended withTranslations (not loggedIn case) or not extended (loggedin)
