### ISSUE TITLE
Components interpolation doesn't work

### ISSUE THREAD

**Issue by ferreiro** [i18next/react-i18next#1229]
## 🐛 Bug Report

_t_ function from useTranslation is not able to interpolate a Translate component.

## To Reproduce

1. I have my own <Translate tid="key" /> component that internally uses useTranslate() 
```js
function Translate({ tid, ...props }) {
	const translation = useTranslate(tid, props);
	return <Fragment>{translation}</Fragment>;
}

function useTranslate(tid, { html, context, ...props } = {}) {
	const [namespaces] = useState(extractNamespaces(tid));
	const { t } = useTranslation(namespaces);

	const translationProps = {
		...props,
		...(html && {
			interpolation: {
				escapeValue: false,
			},
		}),
		...(context && {
			context,
		}),
		ns: namespaces,
	};

	return t(tid, translationProps);
}
```

2. In one part of the code I need to be able to translate a function that returns "3 days", "20 hours", so inside that function I use my Translate component. This works fine
```javascript
function formatDate(exp) {
	const now = new Date();
	const days = Math.floor((exp - now) / ONE_DAY);
	const hours = Math.floor((exp - now) / ONE_HOUR);

	if (days >= 1) {
		return <Translate tid="plan.trial.expires.day" count={days} />;
	}

	return <Translate tid="plan.trial.expires.hour" count={hours} />;
}

// Keys
	"plan.trial.expires.day": "1 day",
	"plan.trial.expires.day_plural": "{{count}} days",
	"plan.trial.expires.hour": "1 hour",
	"plan.trial.expires.hour_plural": "{{count}} hours",
```

3. However, when I try to use the result of that function to interpolate that value with another translation, that doesn't work.
```
<Translate tid="plan.remaining" days={formatTrialExp(trialEndDate)} />

// Key
"plan.remaining": "Lifetime discount. It expires in {{days}}. Go and buy it!",
```

4. However, the result of step 3 will produce the following result:
```
Lifetime discount. It expires in [Object Object]. Go and buy it!
```

<img width="554" alt="Screen Shot 2020-12-16 at 9 30 32 AM" src="https://user-images.githubusercontent.com/7242959/102323883-5982af80-3f81-11eb-97c7-a32eb76c4cd6.png">

5. I created a custom formatted to see what's the value that we are getting, and yeah, we got a react component.

It seems to me that Trans component could solve this, but don't know what would it be a good way to integrate it with my current design

## Expected behavior

**t** function should be able to properly interpolate the component and result the text like this:
```Lifetime discount. It expires in 3 days. Go and buy it!```

## Your Environment

- *runtime version*: i.e. node 10
- *i18next version*: latest
- *os*: Mac

**Comment by jamuhl** [comment]
there is a little difference between interpolating a string and react components (functions)...

a PR would be welcome...or (as it won't work)...have a look at https://react.i18next.com/latest/trans-component as interpolating components into a string is more complex than it seems....

**Comment by ferreiro** [comment]
@jamuhl You are amazing, thanks! Reading your comment makes a lot of sense 😅 sorry for my newbie experience in i18n, but learning :P

Your suggestion works:
```js
<Trans>
    <Translate tid="remaining" />{' '}
    <Translate tid="expires.hour" count={hours} />
</Trans>
```

Quick question: Do I still need a key for that? Individually each element is already translating itself, so what would it be the purpose of the translation key? Providing extra context for translators? If so, please let me know how would you define that key, ``

Also, I don't like how the translation file looks like with this, because translators will not have context for `remaining` key (cause they don't know what would it be at the end):
```
"remaining": "Your trial and the lifetime discount deal end in",
"remaining.hour": "1 hour",
"remaining.hour_plural": "{{count}} hours",
```

Do you know any other way to define this that would give more context for translators? (remaining.hour is a shared key used in other parts of the app)

**Comment by ferreiro** [comment]
@jamuhl btw, just checked another i18n library from Transifex, and they have the same feature I was thinking about when developing mine (for interpolating other react components); https://github.com/transifex/transifex-javascript/pull/32/files

How could you accomplish that with i18next?

**Comment by jamuhl** [comment]
Did you read the docs? you don't need your Translate component -> Just either have your JSX inside the Trans component or use it like: https://react.i18next.com/latest/trans-component#alternative-usage-v-11-6-0

**Comment by jamuhl** [comment]
Sidenote -> if you like i18next consider trying https://locize.com too -> directly supports us (our own translation management software like transifex)

**Comment by tonix-tuft** [comment]
> Did you read the docs? you don't need your Translate component -> Just either have your JSX inside the Trans component or use it like: https://react.i18next.com/latest/trans-component#alternative-usage-v-11-6-0

When using the alternative API (which I really like because of the semantic named tags, e.g. ` <bold>` instead of `<1>` is easier for translators to work with), how can we convert this:

```jsx
<Trans i18nKey="userMessagesUnread" count={count}>
    Hello <strong title={t('nameTitle')}>{{name}}</strong>, you have {{count}} unread message. <Link to="/msgs">Go to messages</Link>.
</Trans>
```

To the alternative usage (v11.6.0)?

The following:

```jsx
<Trans
  i18nKey="userMessagesUnread"
  count={count}
  defaults="Hello <bold>{{name}}</bold>, you have {{count}} unread message. <messagesLink>Go to messages</messagesLink>."
  values={{ name }}
  components={{
    bold: <strong title={t("nameTitle")} />,
    messagesLink: <Link to="/msgs" />,
  }}
/>
```

Of course will not work, because the `Link` component expects a child element:

```jsx
const Link = (props: { children: JSX.Element; to: string }) => {
  return <a href={props.to}>{props.children}</a>;
};
```

And when e.g. using TypeScript, we will get an error:

![Screen Shot 2020-12-20 at 10 29 06](https://user-images.githubusercontent.com/10134421/102709834-42f49500-42ae-11eb-8a95-4e8aaf6c0f13.png)

So how can we translate this text with the alternative approach? Is there something like (I don't know if this would work, so it's kinda pseudo-code):

```jsx
<Trans
  i18nKey="userMessagesUnread"
  count={count}
  defaults="Hello <bold>{{name}}</bold>, you have {{count}} unread message. <messagesLink>Go to messages</messagesLink>."
  values={{ name }}
  components={{
    bold: ({ children }) => <strong title={t("nameTitle")}>{children}</strong>, // `children` would be `name` in this case.
    messagesLink: ({ children }) => <Link to="/msgs">{children}</Link>, // This will work now, `children` would be the translated `Got to messages` part.
  }}
/>
```

? That is, accessing the interpolated/translated children within the `components` map so that we can pass it to the components which require a `children` prop. Will this work (the docs don't mention it) or not? If not, how can we achieve the same? 

Thank you!

**Comment by tonix-tuft** [comment]
@jamuhl For now, the only workaround I found and which seems to work pretty well is to pass a **dummy child** to those components which require a children prop (like `<Link>`), e.g.:

```jsx
<Trans
  i18nKey="userMessagesUnread"
  defaults="Hello <bold>{{name}}</bold>, you have {{count}} unread message. <messagesLink><nested1>Go</nested1> <nested2>to</nested2> <italic>messages</italic></messagesLink>."
  values={{ name }}
  count={count}
  components={{
    bold: <strong title={t("nameTitle")} />,
    italic: <i />,
    nested1: <span style={{ color: "red" }} />,
    nested2: <span style={{ color: "green" }} />,
    messagesLink: <Link to="/msgs">_</Link>, // Dummy `_` child FTW so that TypeScript doesn't complain.
  }}
/>
```

This happens to work pretty well for nested components as well. What do you think?

Is this the best/correct way to do it (at least for now)?

The only thing I am concerned is this: Is the `<Link>` component in this example rendered twice? First time with `_` as children, and then again with the proper translated and interpolated content? Could it be a performance issue in some cases, or can we safely ignore this?

Thanks!

**Comment by jamuhl** [comment]
yes...that is the correct usage...Trans needs to know if the component has children or not -> in case of having children it goes down the tree replacing text if possible
