### ISSUE TITLE
React Hook violation

### ISSUE THREAD

**Issue by yordis** [i18next/react-i18next#1231]
## 🐛 Bug Report

React Hook violation due to conditional statement here https://github.com/i18next/react-i18next/blob/8fa7101bc0cb1c39a9ef9b9a47c9f497af08ee21/src/useTranslation.js#L11 since they are some hook usage after such statement.

## To Reproduce

I have a hook where I do initialize my i18next:

```tsx
export function useI18NextSsrState(appProps: AppProps) {
  const router = useRouter();

  React.useEffect(() => {
    if (i18next.isInitialized) {
      return;
    }

    i18next.use(initReactI18next).init({
      defaultNS: 'default',
      lng: router.locale,
      resources: getI18nState(appProps),
      fallbackLng: router.defaultLocale,
      supportedLngs: router.locales,
      debug: process.env.NODE_ENV === 'development',
      interpolation: {
        escapeValue: false,
      },
      react: {
        wait: true,
      },
    });
  }, []);

  React.useEffect(() => {
    if (i18next.language !== router.locale) {
      i18next.changeLanguage(router.locale);
    }
  }, [router.locale]);

  return { i18next };
}
```

That way, the following usage in some component:

```tsx
const { t } = useTranslation(['errors']);
```

Will trigger the following problem:

```text
react-dom.development.js?61bb:67 Warning: React has detected a change in the order of Hooks called by AuthSignInRoute. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: https://reactjs.org/link/rules-of-hooks

   Previous render            Next render
   ------------------------------------------------------
1. useState                   useState
2. useContext                 useContext
3. useRef                     useState
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

## Expected behavior

Shouldn't warn about this issue.

## Your Environment

- "react-i18next": "11.8.4"
- "i18next": "19.8.4"

**Comment by yordis** [comment]
Btw, I kind of understand that this execution pass shouldn't happen unless we misconfigured something, but regardless, I think the source code needs to be refactored or something. Maybe even throw an error, and forcing the users the fix the code or whatever.

**Comment by jamuhl** [comment]
Like you said - the execution path is only triggered on misconfiguration - we see this as the "rule of react-i18next" 😁

**Comment by yordis** [comment]
@jamuhl if that is the case, why don't you throw an exception with some useful message rather than the way it works today? 

The only reason I discovered that is because I had to surf issues, and the internet until I figured out it shouldn't happen, and it was due to a misconfiguration.

**Comment by jamuhl** [comment]
because i18next never throws...all information / issues get piped to the console. And we won't change this...as this would lead to breaking production code...as in most cases it works anyway even when passing i18n later...

**Comment by shestakov-vladyslav** [comment]
Is it possible to make it work as above? If I need first initialization to be in language that comes from back-end ? My current realization assumes first to be in default (English language), and after it change via i18n.changeLanguage
