### ISSUE TITLE
using the t() from react-i18next outside of a component

### ISSUE THREAD

**Issue by callinutter** [i18next/react-i18next#1232]
## 🐛 Bug Report

I am using i18next and react-i18next in a react native application, more specifically with input validation. I am trying to pass the t() as a parameter in a no component and i am receiving the error "TypeError: n is not a function. (In 'n('errorMessages.emailNoMatch')', 'n' is undefined)". any suggestions is highly appreciated since I am relatively new to coding and I have been searching for a couple days with this issue.

here is the i18n.js code:

```js
import i18next from 'i18next';
import common_de from './translations/de/common.json';
import common_en from './translations/en/common.json';
import i18n from 'i18n-js';
import * as Localization from 'expo-localization';
// Set up translations
i18next.init({
  interpolation: { escapeValue: false }, // React already does escaping
  lng: 'en', // language to use
  resources: {
    de: {
      common: common_de, // 'common' is our custom namespace
    },
    en: {
      common: common_en,
    },
  },
  debug: true,
});
export default i18next;
```
RegisterValidator.js code. (is called in RegisterScreen.js inside Input element as a function.) RegisterValidator.js is the no component file where I am trying to use the t() as a parameter.
```
import i18n from '../i18n'
import { useTranslation } from 'react-i18next';
// import { withTranslation } from 'react-i18next';

const RegisterValidator = (type, value, email, t) => {
  let validated = true;
  let warningMsg = [];
  switch (type) {
    case 'username':
      if (!value.includes(' ')) return [true, ''];
      else {
        warningMsg = i18n.t('errorMessages.username');
        return [false, warningMsg];
      }
    default:
      return [validated, ''];
  }
};
export default RegisterValidator;
```

## Expected behavior

I expected the errorMessages.username to be translated, however it is only returning the string and saying that there is a missingKey

**Comment by pedrodurek** [comment]
Hey @callinutter, if the default namespace is different than `translation`, you can either change the default [namespace](https://www.i18next.com/overview/configuration-options#languages-namespaces-resources), or pass the namespace as a prefix to the `t` function, like this:
```ts
import i18next from 'i18next';

const RegisterValidator = () => {
   return i18next.t('common:errorMessages.username')
}
```
If you're calling it from outside a react component, you should call the `t` function from `i18next` instead.

**Comment by callinutter** [comment]
This worked perfectly. Thank you so much for your help!
