### ISSUE TITLE
Translations not loaded by the time i18n.init callback and React component code run

### ISSUE THREAD

**Issue by jspruance** [i18next/react-i18next#1234]
## 🐛 Bug Report

I am attempting to implement translations using react-i18next, but getting 'missingKey' as well as  'This means something IS WRONG in your setup. You access the t function before i18next.init' type errors when invoking 't'.

I have tried several different approaches to importing and awaiting the 'i18n' instance from my 'i18n.js' file into my React component, including using a Promise wrapper function, async / awaiting, using 'then' on the returned promise, and using the 'i18n' init callback.

The error messages would indicate that the translations are not loading in time. In the console output I do see the translations loading and I have verified that I can access the translation json file through the browser just fine.

Even if I exclude the React component from the picture, the translation in the 'i18n' init callback in 'i18n.js' is failing. It's my understanding from the docs that the translations would be loaded by the time this callback is invoked. 

More details, code and info on what I have tried here:
https://stackoverflow.com/questions/65652176/using-react-i18next-with-react-standalone-component-missingkey-error

I very well could be missing something basic. Any help appreciated!

My code:

i18n.js:
```
import i18n from 'i18next'
import i18nhttp from 'i18next-http-backend'
import Backend from 'i18next-chained-backend'
import LanguageDetector from 'i18next-browser-languagedetector'
import { initReactI18next } from 'react-i18next'

const options = {
  backends: [
    i18nhttp
  ],
    
  backendOptions: [
    { loadPath: '/api/constants/{{lng}}/{{ns}}.lang.json' }
  ]
}

i18n.use(Backend).use(LanguageDetector).use(initReactI18next).init({
  backend: options,
  ns: ['fin'],
  defaultNS: 'fin',
  fallbackNS: 'fin',
  fallbackLng: 'en',
  keySeparator: false,
  debug: true,
  detection: {
    order: ['queryString', 'cookie'],
    cache: ['cookie'],
    lookupCookie:'website#lang',
  },
  interpolation: {
    escapeValue: false
  },
  react: {
    useSuspense: true
  }
}, (err, t) => {
  if (err) return console.log('something went wrong loading', err);
  t('pinDescription') 
})

export default i18n
```
React component:
```
import React, { Suspense }  from 'react'
import ReactDOM from 'react-dom'
import '../../../scripts/i18n'
import { useTranslation } from 'react-i18next'

  const Translation = () => {
    const { t, i18n } = useTranslation()
  
    return (
      <div className="translation-sample">
        <h2>Translation Sample - from files</h2>
        <p>{t('accountNumberDescription')}</p>
      </div>
    )
  }

  const domElement = document.getElementById('translation-sample')

  if (domElement) {
    ReactDOM.render(
      <React.StrictMode>
        <Suspense fallback={<div>Loading ... </div>}>
          <Translation />
        </Suspense>
      </React.StrictMode>,
      domElement
    );
  }
```

## Expected behavior

The translations for the corresponding keys are fetched and displayed on the page.

## My Environment

- *runtime version*: Node 15.2.1
- *i18next version*: i.e. 19.8.4
- *os*: Windows
- React v17.0.1

**Comment by jspruance** [comment]
I added a screenshot of the errors in the console to the SO issue:
https://i.stack.imgur.com/Sfpri.jpg

**Comment by adrai** [comment]
Based on the screenshot, I suspect you either have multiple i18next instances or at least calling i18next.init multiple times...
Can you please create a reproducable example?

**Comment by jspruance** [comment]
Yes, you're right I had another i18n instance running from another component that was conflicting. Once I removed that everything started working fine. 

The only thing is, since this is a component library and not an application I don't have a single place where I can import i18n.js - I have to import it in every component individually.  I guess the proper solution would be to import i18n.js once, in the client app, however the client app does not have React. Lots of limitations specific to my project. Thanks for the help.

**Comment by adrai** [comment]
with i18next.createInstance() you can create a separate instance
