### ISSUE TITLE
Typescript 4.1 setup issue

### ISSUE THREAD

**Issue by KestasVenslauskas** [i18next/react-i18next#1239]
Here you have an example which works fine:
https://github.com/i18next/react-i18next/blob/master/example/react-typescript4.1/no-namespaces/src/App.tsx

I have working setup like that. But the problem is when I try to introduce template literals.
Let's say I have type:
`type MyType = 'part1' | 'part2' | 'part3';`

And I want to get the translation like so:

`const part: Part = 'part1';
  const {t} = useTranslation('description.${part}'); //Error
`
This will give me TS error.

Only if single raw string is used TS will understand that this is ok.

**Comment by pedrodurek** [comment]
Hey @KestasVenslauskas, this a typescript limitation which is going to be handled on [typescript 4.2](https://devblogs.microsoft.com/typescript/announcing-typescript-4-2-beta/#smarter-type-alias-preservation).
In the meantime, you can solve this problem by asserting your template string `as const`. Take a look at this comment for more info: https://github.com/i18next/react-i18next/pull/1193#issuecomment-752283441

**Comment by KestasVenslauskas** [comment]
Thaks! That worked!
