### ISSUE TITLE
Cannot type `t` function result 

### ISSUE THREAD

**Issue by hugomartinet** [i18next/react-i18next#1241]
## 💥 Regression Report

Hi,

I cannot type anymore the result of `t` function when using `useTranslation` hook anymore.

My versions are:
- react-i18next > 11.8.5
- i18next > 19.8.4
- typescript > 4.1.3

My code is something like 
```ts
interface Item {
  ...
}

const Component: React.FC = props => {
  const [t] = useTranslation()

  const item = t<Item>('items', {returnObjects: true})

  return <div>...</div>
}
```

and I have an error 
```
Type 'Item' does not satisfy the constraint 'string | TemplateStringsArray'.
  Type 'Item' is missing the following properties from type 'TemplateStringsArray': raw, length, concat, join, and 19 more.
```

## Last working version

Worked up to version: 10.13.1

Stopped working in version: 11.8.5

## To Reproduce

Add a translation for key `item.name` in your translation file. 

```ts
interface Item {
  name: string
}

const Component: React.FC = props => {
  const [t] = useTranslation()

  const item = t<Item>('item', {returnObjects: true})

  return <div>{item.name}</div>
}
```

## Expected behavior

This component should display the translation you added in your translation file.

## Your Environment

- *runtime version*: node v10
- *i18next version*: 19.8.4
- *os*: Mac
- typescript v4.1.3

**Comment by pedrodurek** [comment]
Hey @hugomartinet, now with typescript 4.1, you can automatically infer `keys` and `return` type using type augmentation, take a look at this [example](https://github.com/i18next/react-i18next/blob/master/example/react-typescript4.1/namespaces/%40types/react-i18next/index.d.ts).
If you still want to use the old way, just pass the first generic argument as `string`, and the second as `Item`, like this:
```tsx
const item = t<string, Item>('item', {returnObjects: true})
```
