### ISSUE TITLE
&quot; not rendering within `t()` function

### ISSUE THREAD

**Issue by bmueller-sykes** [i18next/react-i18next#1243]
Apologies for the potential stupidity of this question, but...

Within my `translation.json` file, I have this:

`"Classes Matching": "Classes Matching &quot;{{text}}&quot;",`

Then, within my React application, I'm invoking the `t` function via the `useTranslation` hook. I'm then outputting like:

```t(`Classes Matching`, {text: "test"})```

The output is:

`Classes Matching &quot;test&quot;`

...instead of:

`Classes Matching "test"`

I've trolled the docs and can't figure out how to address this. What stupid thing am I missing? Or is this actually a bug?

**Comment by jamuhl** [comment]
Did you test the string coming back from `t` call? Rather sure it does not change those `"`. Guess it's react doing so to protect from xss. https://jsfiddle.net/0jofrshb/

**Comment by bmueller-sykes** [comment]
Thanks for the reply. My original post had a display mistake. I meant that my JSON file has this:

`"Classes Matching": "Classes Matching &quot;{{text}}&quot;",`

...and the `&quot;` is not getting rendered as HTML, but rather as the text `&quot;`. 

Your solution of putting a backslash before the actual quote character, like this:

`"Classes Matching": "Classes Matching \"{{text}}\"",`

...does indeed work, so I can proceed with that solution. However, I'd like to know whether there is a way to get those entity references to render, or if that's just not possible here.

Thanks!

**Comment by bmueller-sykes** [comment]
huh. Changing your fiddle to replace `\"` with `&quot;` still properly renders the `&quot;` as a `"`. So that must mean that there's something about importing it from a json file (perhaps something about how it's processed through `i18-http-backend`?) that prevents those entity codes from rendering?

**Comment by jamuhl** [comment]
Guess I already told it's react and it's easy to console.log the output you get from the `t` function (which is what is in your JSON).

But let me invest the time to make a proof ;): https://codesandbox.io/s/infallible-grass-yglwh?file=/src/App.js

----
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

If you liked my support / work - I would enjoy a coffee sponsored using the “:purple_heart:Sponsor Button”.
There are many ways to help this project :pray: (

**Comment by bmueller-sykes** [comment]
Okay, you're right. I was confused. `&quot;` is an HTML reference just like `<p>`, and so React will not render that unless you use `dangerouslySetInnerHtml`. Instead, I need to use unicode references, which are considered a string by React, and are therefore rendered. So this:

`"Classes Matching": "Classes Matching &quot;{{text}}&quot;",`

...needs to be this:
`"Classes Matching": "Classes Matching \u0022{{text}}\u0022",`

...or, as you pointed out in your example:
`"Classes Matching": "Classes Matching \"{{text}}\"",`

Anyway, thanks for humoring me.
