### ISSUE TITLE
How to handle a dynamic plural key?

### ISSUE THREAD

**Issue by DoneDeal0** [i18next/react-i18next#1244]
I have asked my question on Reddit & Stackoverflow and also read the doc before writing this issue. 
I would like to implement a simple message counter and display a message such as: `you have x new message(s)`.

The component is:

```js
function Counter() {
  const { t } = useTranslation();
  const [count, setCount] = useState(0);
  return (
    <>
      <h1>{t("message-count", { count })}</h1>
      <button onClick={() => setCount(count + 1)}>+1</button>
    </>
  );
}
```

The json is:

```js
{
  "message-count": {
    "zero": "you don't have new messages",
    "one": "you have 1 message",
    "many": "you have {{count}} messages"
  }
}

```

## To Reproduce
https://codesandbox.io/s/xenodochial-joliot-wtqe3?file=/src/App.tsx:252-257

How to do it?

**Comment by jamuhl** [comment]
plurals are no using zero, one, many conventions: https://www.i18next.com/translation-function/plurals

**Comment by DoneDeal0** [comment]
Thanks for your answer @jamuhl . if I follow the exemple (https://www.i18next.com/translation-function/plurals#languages-with-multiple-plurals)  and write:

```js
  "message-count_0": "you don't have any new messages",
  "message-count_1": "you have 1 message",
  "message-count_2": "you have {{count}} messages"
```
The component displays the text "message-count". I must do something wrong. Could you please provide a working exemple of what I'm trying to achieve on this sandbox (https://codesandbox.io/s/xenodochial-joliot-wtqe3?file=/src/App.tsx) or by a code snippet here?

**Comment by jamuhl** [comment]
if you need to handle some numeral cases different from plain plural handling there is https://github.com/i18next/i18next-intervalPlural-postProcessor

**Comment by DoneDeal0** [comment]
Ok good to know! A last question though: this issue is resolved, but the translated content from tCount() - the custom count function written above - is not updated when I change the language with `i18n.changeLanguage()` .  How to make sure all the app is updated if I change the locale somewhere? Thanks again for your time, I appreciate it.

**Comment by jamuhl** [comment]
The trans component does like the doc stats not rerender on language change: https://react.i18next.com/latest/trans-component#important-note

use `useTranslation` in the containing component and pass `t` as props to Trans component
