### ISSUE TITLE
Trans component not compatible with Flow

### ISSUE THREAD

**Issue by tommoor** [i18next/react-i18next#1245]
## 🐛 Bug Report

When using the `<Trans>` component in a flow typed codebase it results in errors that I cannot find anyway around. It seems that using an object as a child does not conform to the expectations of React or Flow, is there another way to denote these variables?

![image](https://user-images.githubusercontent.com/380914/106365462-a7156a80-62ea-11eb-90b9-11f88b6bd9a7.png)

## To Reproduce

- clone `https://github.com/outline/outline`
- `yarn install && yarn flow`

One note that's weird, although I think this is Flow at fault – running `yarn flow check` results in no errors, so perhaps this is actually an issue with Flow itself? 

## Expected behavior

`Trans` component should be compatible with Flow

## Your Environment

- *runtime version* node 14
- *i18next version*: `11.7.3`
- *os*: Mac

**Comment by pedrodurek** [comment]
I'm not sure, but I don't think we support flow. As I don't know flow either, I cannot help you, sorry 😢.

**Comment by tommoor** [comment]
Okay, well this issue is here for anyone else that comes across it – it seems it can mostly be worked around by using the alternative syntax, here: https://react.i18next.com/latest/trans-component#alternative-usage-v-11-6-0
