### ISSUE TITLE
How to load  namespaces in react i18next?

### ISSUE THREAD

**Issue by DoneDeal0** [i18next/react-i18next#1250]
## To Reproduce

A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

```js
// Paste your code here
```

## Expected behavior

```js
// Paste the expected results here
```

## Your Environment

- *runtime version*: i.e. node v14, deno, browser xy
- *i18next version*: i.e. 19.5.3
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by adrai** [comment]
https://react.i18next.com/latest/usetranslation-hook#loading-namespaces
https://react.i18next.com/latest/withtranslation-hoc#loading-namespaces

**Comment by DoneDeal0** [comment]
Sorry, I accidentally pressed enter before writing the content of the post. I've updated the thread. 

It doesn't work. I have written 
```js
import { useTranslation } from "react-i18next";

export default function Filters() {
  const { t } = useTranslation("filters");

  return (
    <div>
      <h1>{t("title")}</h1>
      <p>{t("settings")}</p>
      <p>{t("chrono")}</p>
    </div>
  );
}
````

But without any success. I  have joined a sandbox, so it's easier  for you to see what  I'm doing wrong here.

**Comment by adrai** [comment]
Take a look at your imports:



instead of:
```js
import commonEN from "./common/en.json";
import filtersEN from "./common/en.json";
import commonFR from "./common/fr.json";
import filtersFR from "./common/fr.json";
import commonSP from "./common/sp.json";
import filtersSP from "./common/sp.json";

```


fix your imports
```js
import commonEN from "./common/en.json";
import filtersEN from "./filters/en.json";
import commonFR from "./common/fr.json";
import filtersFR from "./filters/fr.json";
import commonSP from "./common/sp.json";
import filtersSP from "./filters/sp.json";
```

**Comment by DoneDeal0** [comment]
... Ok, this is definitely a superb facepalm moment. Thanks for your help!

**Comment by dsonet** [comment]
https://react.i18next.com/latest/usetranslation-hook#loading-namespaces
```javascript
// load multiple namespaces
// the t function will be set to first namespace as default
const { t, i18n } = useTranslation(['ns1', 'ns2', 'ns3']);
t('key'); // will be looked up from namespace ns1
t('ns2:key'); // will be looked up from namespace ns2
```
But when I use t without ns1, TypeScript throw error, says No overload matches this call. When I dig into that error, it shows all the keys with namespace., even the ns1. 

versions I use
```
"i18next": "^20.3.5",
"i18next-http-backend": "^1.3.0",
"react-i18next": "^11.11.4",
"typescript": "^4.3.5"
```
I tried on older version, also doesn't work as expected. Any thoughts? Thanks
