### ISSUE TITLE
Update React peer dependency version for use with npm 7

### ISSUE THREAD

**Issue by omonk** [i18next/react-i18next#1251]
## 🚀 Feature Proposal

Update peer dependencies to allow installing alongside react v17. Update to the latest version of npm mean [peer dependencies are installed alongside a simple `npm i`](https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies). This means installing modules without matching peer dependencies requires `--use-legacy-deps` or `--force` which is not ideal.

React 17 is the "No new features" release so there shouldn't be any breaking changes: https://reactjs.org/blog/2020/10/20/react-v17.html

## Motivation

This error message when trying to install and not waiting to force or use legacy deps

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   peer react@"^17.0.1" from the root project
npm ERR!   peer react@">= 16.8.0" from react-i18next@11.8.5
npm ERR!   node_modules/react-i18next
npm ERR!     peer react-i18next@"^11.8.5" from the root project
npm ERR!   2 more (styled-components, react-dom)
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
```

## Example

`npm install` installs harmoniously

**Comment by jamuhl** [comment]
Why does `react@>= 16.8.0` not met the `react@^17.0.1` -> which basically says it is compatible with any react version starting from 16.8

**Comment by omonk** [comment]
My mistake, a case of not reading the error log correctly... it's been a long week managing dependencies. 

Thanks for all your work, big fan of i18next <3
