### ISSUE TITLE
New instance of i18n isn't rerendering the page after switching the language

### ISSUE THREAD

**Issue by SergeyDarmoroz** [i18next/react-i18next#1252]
Here is my 2-nd instance for translating only one component

 const resources = {
    en: {
      translation: translationEN,
    },
    ua: {
      translation: translationUA,
    },
  };

 export const workspaceInstance = i18n.createInstance({ 
    resources,
    fallbackLng: "en",
    debug: true,
    whitelist: avalibleLanguages,
    interpolation: {
      escapeValue: false,
    },
 }, (err, t) => {
  if (err) return console.log('something went wrong loading', err);
  t('key'); 
});

 export const handleLanguageChange = (lang: string) => {
    workspaceInstance.changeLanguage(lang)
  }

And the workspaceInstance.language isn't rerendering in my component

**Comment by jamuhl** [comment]
Do you use the I18nextProvider?!? https://react.i18next.com/latest/i18nextprovider
