### ISSUE TITLE
useTranslation hook breaking Cypress React component tests

### ISSUE THREAD

**Issue by reintroducing** [i18next/react-i18next#1253]
## 🐛 Bug Report

When creating a Cypress test for a component that has the `useTranslation` hook in it, Cypress is showing the following error:
```
The following error originated from your application code, not from Cypress.

  > Cannot read property 'react' of undefined
```

## To Reproduce

I've attached a zip file that has the barebones setup necessary to reproduce the issue. Run the following after unzipping:
* npm i
* npm test

You will now see Cypress open with Foo.spec.js available. Click on it and observe the error. To "fix" the error, open up `/src/Foo.js` and comment out line 5 (the `useTranslation` implementation). The test now runs correctly.

## Expected behavior

There should not be an error when running a Cypress test for a component with the `useTranslation` hook in it.

## Your Environment

- *runtime version*: node v12.13.0, npm v6.12.0
- *i18next version*: 19.8.7
- *os*: Mac 10.15.7
- *any other relevant information*

[cypress-i18n.zip](https://github.com/i18next/react-i18next/files/5977985/cypress-i18n.zip)

**Comment by jamuhl** [comment]
https://react.i18next.com/misc/testing

**Comment by reintroducing** [comment]
@jamuhl Thanks, but thats the exact page I followed. I'm using the section for [Testing without Stubbing](https://react.i18next.com/misc/testing#testing-without-stubbing). As far as I can tell, my configuration is exactly the same as on that page (without the use of Redux, though where I'm actually writing these tests, aka not this small example file that I provided), I am using Redux and that exact setup with the same result.

**Comment by reintroducing** [comment]
Found this and solved my issue: https://github.com/cypress-io/cypress/tree/develop/npm/react/cypress/component/advanced/i18n

**Comment by ma8642** [comment]
> Found this and solved my issue: https://github.com/cypress-io/cypress/tree/develop/npm/react/cypress/component/advanced/i18n

@reintroducing Can you share your code? That link leads to a 404 now.

**Comment by fsheiness** [comment]
For anyone looking for this, the solution is:

```
import { I18nextProvider } from 'react-i18next';
import i18n from 'your/lib/i18n';

cy.mount(
    <I18nextProvider i18n={i18n}>
        <YourComponent />
    </I18nextProvider>
);
```

File was deleted in commit c526b844cac4b797208828762c747baf75608b5a if you want to check it out

**Comment by MauriceArikoglu** [comment]
> > Found this and solved my issue: https://github.com/cypress-io/cypress/tree/develop/npm/react/cypress/component/advanced/i18n
> 
> @reintroducing Can you share your code? That link leads to a 404 now.

https://github.com/cypress-io/cypress/blob/10.0-release-with-debugs/npm/react/cypress/component/advanced/i18n/i18n.ts to look at the example.

Although this example is not working for me. If anyone stumbles upon a solution, I would be grateful.
