### ISSUE TITLE
TransOver Chrome Extension is crashing my page with <Trans/> but not with t()

### ISSUE THREAD

**Issue by codingyourlife** [i18next/react-i18next#1254]
## 🐛 Bug Report

Our registration page was crashing for some users. I found an open Github issue on facebook/react and could reproduce it reliably. I could solve it by changing a `<Trans />` component to a call of the `t()` function. That's why I also report it here. Maybe you guys could add a quickfix until this is solved in react itself (open since november 2019)

![error](https://user-images.githubusercontent.com/10122382/107888660-0dff6a00-6f0e-11eb-9260-5ed50423719c.JPG)

## To Reproduce

There is a **well documented Github issue** https://github.com/facebook/react/issues/17256 **with a codesandbox**. You need to use Chrome with TransOver extension added and enabled. For my issue with react-i18next I've set it to translate into "Italian" when I "point at word". You need to wait for the popup to open and then click on our custom Checkbox. I don't have any empty react elements to solve the issue as mentioned as workaround in the Github issue but I could solve it by changing from a `<Trans />` child component to a `t()` function call.

### JS
My Quickfix which works in this case without any drawback:
![fix](https://user-images.githubusercontent.com/10122382/107888564-55392b00-6f0d-11eb-9b5c-08e85942526f.JPG)

## Expected behavior
Clicking my accept marketing emails checkbox should not lead to an empty page because of react-i18next `<Trans>` component being used.

## Your Environment
browser: Chrome Version 88.0.4324.150 (64-Bit)
node: v14.15.3
os: Windows 10
i18next version: ^11.8.6

**Comment by jamuhl** [comment]
Strange one...you might try setting init option `react: { defaultTransParent: 'div' }` https://github.com/i18next/react-i18next/blob/master/src/Trans.js#L316 -> so instead of a Fragment Trans will render a outer div (or whatever you set it)

**Comment by codingyourlife** [comment]
> Strange one...you might try setting init option `react: { defaultTransParent: 'div' }` https://github.com/i18next/react-i18next/blob/master/src/Trans.js#L316 -> so instead of a Fragment Trans will render a outer div (or whatever you set it)

It DOES work with defaultTransParent div but it also messes up the styling because a div is display block.
![image](https://user-images.githubusercontent.com/10122382/108002111-d87e7d80-6fee-11eb-8bdb-a7642af301c1.png)

It does NOT work with defaultTransParent span interestingly. It DOES work when I use i for italic or b for bold. If there is a way to say defaultTransParent div but display inline without setting it to a span there would be a workaround. I was surprised that span isn't working I thought internally it's an empty element.

**Comment by jamuhl** [comment]
You should be able set it to any custom component:

```js
// ....other options
react: {
  defaultTransParent: function MyDiv ({children}) {
    return <div style={{ display: 'inline' }}>{children}</div>
  };
}
```

**Comment by codingyourlife** [comment]
I can confirm that this workaround works!

**Comment by thiagomorales** [comment]
I get this fixed using:
```
...
react: {
    transEmptyNodeValue: '',
  },
```

Source: https://react.i18next.com/latest/trans-component#trans-props
