### ISSUE TITLE
Using language keys (again) lower in the translation tree causes (key 'setlanguage.fr (en-GB)' returned an object instead of string.) 

### ISSUE THREAD

**Issue by mikkopori** [i18next/react-i18next#1256]
## 🐛 Bug Report

We used language keys again like this:

```
      setlanguage: {
        dialogtitle: 'Set language',
        en: 'English',
        fr: 'French',
        fi: 'Finnish',
      },

```
which caused the following error:

`(key 'setlanguage.fr (en-GB)' returned an object instead of string.) `

Setting the keys like this solved the issue:

```
      setlanguage: {
        dialogtitle: 'Set language',
        _en: 'English',
        _fr: 'French',
        _fi: 'Finnish',
      },

```

## Expected behavior

Either resuing the keys could work, or a more precise error message could be produced preventing the reuse lower in the tree.

Otherwise, thank you for a great library!

Mikko :)

**Comment by jamuhl** [comment]
If I make a minimal sample https://jsfiddle.net/2h5toeba/ it works like expected.

Can you please provide a sample for reproduction?

**Comment by mikkopori** [comment]
Sure, I'll try that later today.

Just came quickly to drop in that the change that broke this for us probably came with "i18next": ">=19.8.5" as "i18next": ">=19.8.4" worked for us

**Comment by mikkopori** [comment]
Sorry for the delay. I tried on the fiddle, but was unable to reproduce. This must have something to do with our env. So I believe closing this issue is the right choice. Maybe later someone will run into the same thing and will be able to provide more details on it.
