### ISSUE TITLE
Translations suddenly stopped working in production

### ISSUE THREAD

**Issue by hugo-licon** [i18next/react-i18next#1259]
## 🐛 Bug Report

Yesterday we deployed some changes to production and notice that the translations stopped working, we've never had an error like this before, and we don't know what's going on and I don't know if you can help us.

The first weird thing is that we did not modify any code related to the configuration of `react-i18next` so we don't know what caused the bug. Besides that, we're not able to replicate this locally, it only happens in production.

We also noticed that we started getting a warning that never before had received. We fixed the warning by changing the configuration but it didn't solve the issue.
```diff
...
react: {
-  wait: true,
+  useSuspense: true
},
...
```
![image](https://user-images.githubusercontent.com/72823833/108260478-9bfe6f00-711f-11eb-9719-f00dd116f73d.png)

We activated the debug mode to see if we could find something and this is what we got:
![image](https://user-images.githubusercontent.com/72823833/108261868-6e1a2a00-7121-11eb-8fab-ddec460a373e.png)
![image](https://user-images.githubusercontent.com/72823833/108261918-796d5580-7121-11eb-9f2d-6419e8758045.png)
[Here](https://gist.github.com/hugo-licon/556e4a3bb62ffe785ad6b5be494eacc1) you can find the params that the init function received the first time it was called and [here the second one](https://gist.github.com/hugo-licon/3aed0a0d4710c966ef7b85bab7b7fcc9).

## To Reproduce
Here is our configuration
```javascript
/*
configure-locales.tsx
*/

import i18n from 'i18next';
import { AppLocaleResources } from 'types/localization';
import { initReactI18next } from 'react-i18next';

const configureLocales = (lng = 'en', resources: AppLocaleResources): void => {
  void i18n.use(initReactI18next).init({
    resources,
    lng: lng || 'en',
    fallbackLng: 'en',
    debug: true,
    keySeparator: false,
    interpolation: {
      escapeValue: false,
    },
    react: {
      wait: true,
    },
  });
};

export default configureLocales;

/*
translations-config.tsx
*/
import { i18n } from 'services/api';
import Languages from 'utils/constants/languages.constants';

const configI18n = (
  selectedLanguage: Languages,
): Promise<{
  selectedLanguage: Languages;
  translations: { [x: string]: { translation: Record<string, unknown> } };
}> =>
  i18n(selectedLanguage).then(({ result: { keys: selectedKeys } }) => ({
    selectedLanguage,
    translations: {
      [selectedLanguage]: {
        translation: selectedKeys as Record<string, unknown>,
      },
    },
  }));
export { configI18n };


/*
AppTranslationHOC.tsx
*/

const AppTranslationsHOC: FC<AppLangRouteComponentProps> = ({
  children,
  match: {
    params: { language: locale },
  },
}: AppLangRouteComponentProps): React.ReactElement => {
  useEffect(() => {
    const selectedLanguage = locale ? locale : Languages.EN;
    const localesConfigImport = import(
      /* webpackChunkName: "locales" */ 'i18n/translations-config'
    );
    const configureLocalesImport = import(
      /* webpackChunkName: "configure-locales" */ 'i18n/configure-locales'
    );

    let configLocalesFn: (lng: string, resources: AppLocaleResources) => void;

    void configureLocalesImport
      .then(({ default: configureLocales }) => {
        configLocalesFn = configureLocales;
        switch (selectedLanguage) {
          case Languages.EN:
            // eslint-disable-next-line @typescript-eslint/no-unsafe-return
            return translationEn;
          case Languages.ES:
            return translationEs;
          default:
            return translationEn;
        }
      })
      .then((translations) => {
        configLocalesFn(selectedLanguage, {
          [selectedLanguage]: {
            translation: translations,
          },
        });
        return localesConfigImport;
      })
      .then(({ configI18n }) => configI18n(selectedLanguage))
      .then(({ selectedLanguage, translations }) =>
        configLocalesFn(selectedLanguage, translations),
      );
  }, [locale]);

  return <>{children}</>;
};

export default AppTranslationsHOC;
```

## Your Environment

**Production Environment:**

- *runtime version*: node v12
- *i18next version*: ^19.8.3
- *react-i18next*: ^11.7.3
- *os*: Ubuntu 18.04

If you need more information please let me know.

**Comment by adrai** [comment]
You should not call the init function multiple times: https://github.com/i18next/i18next/issues/1554#issuecomment-780425514

**Comment by hugo-licon** [comment]
@adrai We're working on it, we'll let you know if that solves the issue but it seems that it will

**Comment by hugo-licon** [comment]
It was that, thank you so much for your help
