### ISSUE TITLE
useTranslation language override

### ISSUE THREAD

**Issue by joekur** [i18next/react-i18next#1260]
## 🚀 Feature Proposal

Allow an optional `lng` language prop to `useTranslation`, to override the language of the provided `t` function.

Currently we call `getFixedT`, but always provide a `null` language argument, deferring to the global language: https://github.com/i18next/react-i18next/blob/ce14f34890927112e1a4e18888651d79970e180f/src/useTranslation.js#L42

## Motivation

When building a component library, I would like to avoid using the same (global) i18n instance in both the component library and the consuming application. I can do this with `createInstance()`. This can be advantageous to ensure no namespace collisions, and to allow for different configuration between library and consuming application.

However we then need a way to communicate to the component library which language to use. There are a few ways to do this, but arguably I think the cleanest ways would involve a top-down flow of the language value from application to component library (via prop, or maybe via context). I would also think if we can avoid calling `changeLanguage()` on the i18n instance in the component library, we can avoid weird edge cases where two components are rendered in different locales, potentially causing an infinite chain of re-renders and flip-flopping of the set language.

## Example

Component library (`language` as prop):
```javascript
const SharedComponent = ({ language }) => {
  const { t } = useTranslation('myNamespace', { lng: language });
  return <>{t('foo')}</>;
}
```

Consuming application:
```javascript
<SharedComponent language={i18n.language} />
```

**Comment by jamuhl** [comment]
Looks like something simple...but -> would not work easily as it would not correctly load namespaces for that language.

You can create a own `t` function -> or call the provided `t` function with `t(key, { lng });` but you will have somehow to assert that language/+namespacs were loaded

**Comment by joekur** [comment]
I see, so there are some gotchas by potentially deviating from the single global language. I think I've found other ways to synchronize the locale between two i18n instances. Thanks!
