### ISSUE TITLE
Storybook 6: <Trans> not workinf without useTranslation on initial load.

### ISSUE THREAD

**Issue by Bielousov** [i18next/react-i18next#1263]
## 🐛 Bug Report

With Storybook 6 the translation is not rendered on the first load after Storybook page refresh if using `<Trans />` component only. However if using both `<Trans />` and `useTranslation` hook in the same component, updating component props, or if navigating between the stories, the are rendered as expected.

## To Reproduce
- **i18n.js**: same as here: https://github.com/i18next/react-i18next/blob/master/example/storybook/src/i18n.js
- **.storybook/decorators.tsx**:
```js
import React, { Suspense } from 'react';
import '../src/i18n';

export const withLocalization = (Story) => (
  <Suspense fallback="Loading localization…">
    <Story />
  </Suspense>
);
```
- **.storybook/preview.tsx**:
```js
import { withLocalization } from './decorators';
export const decorators = [ withLocalization ];
```
- **component.story.tsx**:
```js
import React from 'react';
import { Meta } from '@storybook/react/types-6-0';
import Component from './component';

export default {
  title: 'Component',
  component: Component,
} as Meta;

const PrimaryTemplate = (args) => (
  <Component {...args} />
);

export const Primary = PrimaryTemplate.bind({});
```

- **component.tsx**:
```js
import React from 'react';
import { Trans } from 'react-i18next';

const Component = () => (
  <p>
    <Trans i18nKey="key" />
  </p>
);
export default Component;
```
- Run storybook and navigate to the Component/Primary story page.

## Expected behavior
When story page is loaded, the component should have a translation from translation.json file according to the key used.

## Actual behavior
When story page is loaded, the component renders key value, as if it wasn't waiting for Suspense.
However if updating any component controls or navigating between the stories (without page reload), the expected translation is rendered.

Alternatively if using `useTranslation` hook along with `<Trans />`, the issue is also NOT reproducible (i.e. both translations are rendered on the initial load as expected, e.g.:
- **component.tsx**:
```js
import React from 'react';
import { Trans, useTranslation } from 'react-i18next';

const Component = () => {
  const { t } = useTranslation();
  return (
    <p>
      <Trans i18nKey="key" />
      <span>{t('key')}</span>
    </p>
  );
}
export default Component;
```

It appears as if `Suspense` is not kicking in correctly and the component is not re-rendered when the translations are loaded async.

## Environment
- *runtime version*: node v14.15.1, storybook v6.1.17, Google Chrome 88.0.4324.150
- *i18next version*: 19.8.9
- *react-i18next version*: 11.8.7
- *os*: Mac OS (11.2.1)
- *any other relevant information*: tried both with `I18nextProvider` and without.

**Comment by jamuhl** [comment]
expected as in docs: https://react.i18next.com/latest/trans-component#important-note
