### ISSUE TITLE
Multiple warnings of "It seems you are still using the old wait option" on production server

### ISSUE THREAD

**Issue by felixmosh** [i18next/react-i18next#1266]
## 🐛 Bug Report

Since v11.8.7 there are multiple warnings in production mode server

## Expected behavior
it should not warn on production build at all

## Your Environment

- *runtime version*: node v14
- *i18next version*: 19.5.3
- *os*:  Linux
- *react-i18next*: 11.8.7

**Comment by adrai** [comment]
Can you paste your i18next config?

**Comment by felixmosh** [comment]
I do use it `wait` (given by next-i18next), i just don't want my production logs bombard with this warning (which is relevant only in development)

**Comment by adrai** [comment]
just remove the wait option, it's not respected since the last major version

**Comment by felixmosh** [comment]
I've tried, without it, it throws :|

![image](https://user-images.githubusercontent.com/9304194/109417971-8ebe6b80-79ce-11eb-8f32-56b0606ffe93.png)

**Comment by adrai** [comment]
please provide a reproducible example

**Comment by felixmosh** [comment]
https://codesandbox.io/s/nostalgic-bush-9tqik?file=/i18n.js

**Comment by adrai** [comment]
You may need to update next-i18next first

**Comment by felixmosh** [comment]
I can't the new version doesn't supports custom servers

**Comment by adrai** [comment]
then try to fix react-i18next to v11.8.6

**Comment by felixmosh** [comment]
When does `isReady` flag suppose to change? maybe it is a matter of simple flag change?

**Comment by adrai** [comment]
> When does `isReady` flag suppose to change? maybe it is a matter of simple flag change?

What do you exactly mean?

**Comment by felixmosh** [comment]
This is where it throws a promise since it is not ready...
When `ready` flag suppose to change to `true`?
![image](https://user-images.githubusercontent.com/9304194/109418774-b7486480-79d2-11eb-9247-316ae8d0f01a.png)

**Comment by adrai** [comment]
Can you try with this options?

![image](https://user-images.githubusercontent.com/1086194/109418830-9d0a8880-79ca-11eb-829c-c3a99fdfa552.png)

**Comment by adrai** [comment]
Your example is not using suspense, so you need to set it to false

**Comment by felixmosh** [comment]
Ha, this is working, but the questions is if `wait` flag did something and not it doesn't?

**Comment by adrai** [comment]
the wait option was removed in the last major version of react-i18next

**Comment by felixmosh** [comment]
Ha, so it doesn't do anything for long time 😅, thank you 🙏🏼

**Comment by adrai** [comment]
So can this issue be closed?

**Comment by felixmosh** [comment]
I still thing that debuging / deprecation notices should be only in dev mode... but it is up to you :]
