### ISSUE TITLE
Typesafe translation loophole

### ISSUE THREAD

**Issue by simon-auch** [i18next/react-i18next#1267]
## 🐛 Bug Report

Typesafe translation has a loophole allowing to call `t` with any string.

## To Reproduce

Have any translation with type support set up and call the following function:

```js
function translationBoundTest<T extends (key: "abcde")=>string>(t: T){
  console.log(t("abcde"));
}
```
Notice that you can call it, even if your translation does not contain the key `"abcde"`.

Expectation: the code should only compile iff the translation contains a key "abcde".

## Your Environment

- *runtime version*: i.e. latest node
- *i18next version*: i.e. 19.9.0
- *os*: Linux
- *any other relevant information* None

## My usecase

I have a bunch of enums I would like to translate, each having different "paths" in the translation. So in the end I would like to have a function with a type like `function translateEnum<E,T>(enumeration: E, prefix: string, t: T) => string[]` with bounds on `E` and `T`as necessary.

**Comment by adrai** [comment]
@pedrodurek we need a typescript expert here ;-)

**Comment by simon-auch** [comment]
> @pedrodurek we need a typescript expert here ;-)

Yeah, I looked into the source to understand how that can be possible, but was outside of my typescript knowledge pretty fast..

**Comment by pedrodurek** [comment]
Hey @simon-auch,
This is a typescript limitation when it comes to `function overload`, I've created an [example](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgCoDECuIHIN4BQyyAPKgNIQCeyEAHpCACYDOyA5HO8gD4cBG7AHwAKANbUAXGkpUAlNJZgooAOYBuAgF8CBAPR7kAdQD2UMSwCE+wxKrTO3Pu0EEEJkEuRhpGbLgBeZHFqOWQAoXwiZCgIMEwoEA46OnZNHQJQSFhEFD8cACYo4jJZWgYIZjZHXgFhEPsZUMVlNU0SimpyxlYOLlqXdgAaZAB5AAcwYA82eh62JRUQVVE7X1kRk0npzwB+aQmpmYVkRbbtXQNkABETCDYQEzBkAHczMRtkNeQ4ECo3GbPMAFXxYQrhYJ2MIRYoxOIJJLsFJpC4EIA) to illustrate that. My suggestion is to rely on the `TFunction` type instead, for example:
```tsx
function translationBoundTest<T extends TFunction<'ns1'>>(t: T){
  console.log(t("abcde"));
}
```
Replace `ns1` with the chosen namespace.

**Comment by simon-auch** [comment]
Thank you for the illustration :)

Unfortunately passing a `TFunction<Namespace>` is not enough in my case.
Consider the following enums:
```ts
enum Animal{
  CAT = "cat",
  DOG = "dog",
}
enum Food{
  TOMATO = "tomato"
  POTATO = "potato"
}
```
and assuming my translation has the following valid keys:
```
"animals:cat" | "animals:dog" | "food:tomato" | "food:potato"
```
How would you write a function that translates any such enum given the correct prefix (in this case "animals:" or "food:", depending on the enum passed)? The problem I encountered was always that I would require a bound on the translation function. This however as you illustrated seems to not work as (I) expected in typescript.

**Comment by pedrodurek** [comment]
Hey @simon-auch, do you mean something like [this](https://codesandbox.io/s/wizardly-brahmagupta-z5f2s?file=/src/App.tsx)?
