### ISSUE TITLE
Trans component with count property greater than 1 sends i18nkey instead of templated string as a missing key to the server during development 

### ISSUE THREAD

**Issue by atomic-tang** [i18next/react-i18next#1270]
## 🐛 Bug Report

I am using Razzle and followed the example to setup i18n on my project. I am using the i18next-http-backend, i18next-http-middleware and i18next-fs-backend packages to send missing keys from the client to the server which are then written to file on the server. When using the Trans component with a count prop greater than 1 during development, the Trans component would render the i18nKey instead of the templated string wrapped within the component. I also checked the key sent to the server when the Trans component is rendered which also sends and writes the i18nKey instead of the templated string to file.

**package.json**
```json
{
  "razzle": "3.3.13",
  "i18next": "^19.9.0",
  "i18next-browser-languagedetector": "^6.0.1",
  "i18next-fs-backend": "^1.0.8",
  "i18next-http-backend": "^1.1.1",
  "i18next-http-middleware": "^3.1.0",
  "react-i18next": "11.8.5"
}
```
**Example component**
```js
const TotalCourses = ({ i18n, totalCourses }) => {
   const COURSE_TRANS_KEY = "course:course.totalCourses";

   return (<Trans i18n={i18n} i18nKey={COURSE_TRANS_KEY} count={totalCourses}>{{ totalCourses }} courses</Trans>);
}
```
**course.missing.json** when totalCourses prop is greater than 1
```json
{
   "course": {
      "totalCourses": "course.totalCourses",
      "totalCourses_plural": "course.totalCourses" 
   }
}
```
**course.missing.json** when totalCourses prop is 1
```json
{
   "course": {
      "totalCourses": "{{totalCourses}} courses",
      "totalCourses_plural": "{{totalCourses}} courses"
   }
}
```
## Expected behavior

**course.missing.json** when totalCourses prop is any numerical value
```json
{
   "course": {
      "totalCourses": "{{totalCourses}} courses",
      "totalCourses_plural": "{{totalCourses}} courses"
   }
}
```
However this issue only occurs in development. Building the project and running the build eliminates the issue and the Trans component renders correctly and correctly sends the missing key with the templated string. Also when transferring the missing key to a translation file with the correct templated string, the Trans component will render correctly.

## Your Environment

- *runtime version*: node v12.10.0, browser chrome
- *environment*: development
- *i18next version*: 19.9.0
- *os*: Mac

**Comment by jamuhl** [comment]
rather strange - PR with a fix welcome

**Comment by atomic-tang** [comment]
Nevermind. Reinstalling the dependencies for my project seemed to fix the issue.
