### ISSUE TITLE
Trans component does not wait for i18n Init with HttpBackend to finished

### ISSUE THREAD

**Issue by DoryZi** [i18next/react-i18next#1274]
## 🐛 Bug Report

I'm loading translations dynamically, with the HttpBackend However inside my component I use the Trans component, and it is screaming about missing translation key, I also see the init finished after it tried to access the Trans component. I have a Suspens around my app, why is this happens?

I get in the console: 

`i18next::translator: missingKey en translation myKey This is text that has a`
`i18next::backendConnector: loaded namespace translation for language en {xxxxx}`
`i18next.js:22 i18next: languageChanged en`
`i18next.js:22 i18next: initialized {debug: true, initImmediate: true, ns: Array(1), defaultNS: Array(1), fallbackLng: Array(1), …}`

## To Reproduce

A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

```js
// file: i18n.js
i18n
  // load translation using http -> see /public/locales (i.e. https://github.com/i18next/react-i18next/tree/master/example/react/public/locales)
  // learn more: https://github.com/i18next/i18next-http-backend
  .use(Backend)
  // detect user language
  // learn more: https://github.com/i18next/i18next-browser-languageDetector
  // pass the i18n instance to react-i18next.
  .use(initReactI18next)
  // init i18next
  // for all options read: https://www.i18next.com/overview/configuration-options
  .init({
    fallbackLng: 'en',
    debug: true,
    supportedLngs: [ 'en', 'bg', 'rs'],
    interpolation: {
      escapeValue: false, // not needed for react as it escapes by default
    },
    backend: {
      loadPath: '/static/{{lng}}.translations.json',
    },
    react : {
      wait: true,
      useSuspense: true
    },
    transSupportBasicHtmlNodes: true,
  })


export default i18n;


// app.js
function App() {
  return (
        <Suspense fallback={<Loading />}>
          <ThemeProvider theme={theme}>
              <Header />
              <Routes />
              <Footer />
          </ThemeProvider>
        </Suspense>
  )
}

//home
const I18N_TEXT_KEY_CONSTANT = "text_key"
const Home = () => ({
  <Trans i18nKey={I18N_TEXT_KEY_CONSTANT}>
    This is text that has a <br /> in it
    and also some random spaces.
  </Trans>)
}
```

## Expected behavior

Trans should wait until init is ready before trying to access the translation keys.

## Your Environment

- *runtime version*: React ^17.0.1
- *i18next version*: ^19.9.1 
- *"i18next-http-backend": "^1.1.1",
- "react-i18next": "^11.8.9",
- *os*: Linux - Chrome
- *any other relevant information*

**Comment by adrai** [comment]
https://react.i18next.com/latest/trans-component

![image](https://user-images.githubusercontent.com/1086194/110529048-10be3b00-8119-11eb-9772-6c86cf70e99e.png)
