### ISSUE TITLE
How to use i18next in js files

### ISSUE THREAD

**Issue by diegohdez90** [i18next/react-i18next#1278]
## 🐛 Bug Report

How translate with i18n for js pure files, no component class or function. In my case is using array objects.

## To Reproduce

I tried using i18n package

```js
import i18n from 'i18next';

export const myObject = [{
  foo: i18n.t('foo')
]]
```

also using i18n config file

```js
import i18n from './i18n';

export const myObject = [{
  foo: i18n.t('foo')
]]
```

And none of both works. I search in the community and I can't find a solution.

This object array I use it for another method and apply some code stuff that's not involve i18next.

```js
import i18n from './i18n';

const myObject = [{
  foo: i18n.t('foo')
]]

// ... code

export const myMetehod = () => {
  return myObject.map(() => {
    // ... all stuff code
  })
}
```

## Expected behavior

i18next must translate words in all cases include pure js files.

**Comment by adrai** [comment]
https://www.i18next.com/overview/getting-started#basic-sample
