### ISSUE TITLE
HOC withRef not working properly

### ISSUE THREAD

**Issue by JensDebergh** [i18next/react-i18next#1279]
## 🐛 Bug Report

Using the HOC withTranslation function does not properly forward the ref of the component. Obviously the render function is there but for the purposes for this issue I removed it.

<img width="557" alt="Screenshot 2021-03-14 at 07 34 23" src="https://user-images.githubusercontent.com/6651506/111059793-8834f700-8498-11eb-80a8-ac842c85c963.png">

<img width="792" alt="Screenshot 2021-03-14 at 07 33 30" src="https://user-images.githubusercontent.com/6651506/111059812-98e56d00-8498-11eb-8661-ad82bfcb67fa.png">

## Expected behavior

Providing the `withRef: true` option should properly forward refs towards the component props.

## Your Environment

```
OS: Mac
"i18next": "^19.9.2",
"react-i18next": "^11.8.10",
```

I'm sorry if I posted this issue and I'm doing something wrong, but I'm just following along with the docs and it previously worked but it does not anymore.

If you can point me in the right direction it would be greatly appreciated and if it is a bug I'm more then happily work on a fix.

Kind regards

**Comment by JensDebergh** [comment]
For anyone stumbling on this issue:

The real issue is that the types of this library do not provide a way to tell that the component is being exported as a HOC with the `withRef` option set to `true`.

Forwarding of props does work properly, but the types for the forwarding specifically the `withRef` option is not provided.

Solution (although not perfect):

Manually add the ref to the component props.

```
type IProps = {
	name: string
	onChange: (date: any) => void
	defaultValue?: any
	ref?: React.RefObject<DateInput>  <-- add this
} & WithTranslation & Datetime.DatetimepickerProps
```

Ideally we should have a typed solution that does this:

```
type IProps = {
	name: string
	onChange: (date: any) => void
	defaultValue?: any
} & WithTranslationAndRef & Datetime.DatetimepickerProps
```

Hope this help!

**Comment by adrai** [comment]
//cc @pedrodurek

**Comment by xingqiwu55555** [comment]
Hi, is there any process? I met same question.
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/20753914/228713705-9661be56-e173-4c57-b8e2-c7a454b09e74.png">
**Envrionment**
`
        "i18next": "^22.4.13",
        "i18next-browser-languagedetector": "^7.0.1",
        "i18next-http-backend": "^2.2.0",
        "react": "^18.2.0",
        "react-dom": "^18.2.0",
        "react-i18next": "^12.2.0",
`
