### ISSUE TITLE
Type-definitions for Trans-component do not allow array as i18nKey

### ISSUE THREAD

**Issue by therealtbs** [i18next/react-i18next#1281]
## 🐛 Bug Report

The TypeScript definitions for the `Trans`-component don't allow you to specify an array of `i18nKeys`.

## To Reproduce

[codesandbox](https://codesandbox.io/s/react-i18next-i18nkey-array-c611b)

This (undocumented, for the `Trans`-component at least, for the `t`-function [see here](https://www.i18next.com/translation-function/essentials#multiple-fallback-keys)) feature already works well with the only problem being the type-definitions.

```tsx
t(["key1", "fallbackKey"]) // works and gives no TypeScript errors

  <Trans
    i18nKey={["key1", "fallbackKey"]}
//  ^ Type error: Type 'string[]' is not assignable to type 'string'.
  /> // works otherwise
```

## Expected behavior

The type-definitions for the `t`-function allow this. Since the `Trans`-component uses the `t`-function in order to resolve the message, I would expect to be able to supply fallback keys as if I was using the `t`-function directly.

```tsx
t(["key1", "fallbackKey"]) // works and gives no TypeScript errors

  <Trans
    i18nKey={["key1", "fallbackKey"]}
  /> // works and gives no TypeScript errors
```

## Your Environment

- *runtime version*: Chrome 89, doesn't matter
- *i18next version*: i18next@19.9.2, react-i18next@11.8.10
- *os*: Windows, Linux
- *typescript version*: 4.2.3

**Comment by pedrodurek** [comment]
Hey @therealtbs, it should be fixed now!
