### ISSUE TITLE
Issue access two-level deep inside a a translation

### ISSUE THREAD

**Issue by stephyswe** [i18next/react-i18next#1287]
## 🐛 Bug Report
How to access two-level or more in translation? 
You can write "{t('changeLng')}" to access as below but how to access something like "{t('Cities.newyork')}" ?

I tried to write - <p> {t(`Cities${cityType}`)} </p> - with a param but it only returns a text of everything. 

example of resources
```
const resources = {
  en: {
      translation: {
         changeLng: 'change to swedish',
         Cities: {
            newyork: 'statue of liberty',
            paris: 'eiffel tower',
         }
      }
  },
  sv: {
    translation: {
      changeLng: 'change to english',
      Cities: {
        newyork: 'washington',
        paris: 'louvren',
      },
    },
}
```

## To Reproduce
react18next-issue-two-level-deep - [codesandbox example](https://codesandbox.io/s/react18next-issue-two-level-deep-ymq45) 

```js
function App() {
 return <CityLanguage cityType="newyork" />
}

city-language.js
import React from 'react'
import {useTranslation} from 'react-i18next'

function CityLanguage({cityType}) {
  const {t} = useTranslation()
  return (
    <div>
      <p>How to change this text below as well?</p>
      <h1> {t(`Cities${cityType}`)} </h1>
    </div>
  )
}

export {CityLanguage}

```

## Expected behavior
Using CityLanguage with prop cityType = "newyork" should render 
Language set to sv  (swedish) with component `<CityLanguage cityType="newyork" /> `
expected result: statue of liberty

and Language set to en (english) with component  `<CityLanguage cityType="newyork" />` 
expected result: fifth avenue
```

## Your Environment

- *runtime version*: i.e. node v14, deno, browser xy
- *i18next version*: i.e. 19.5.3
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by adrai** [comment]
You're probably just missing a dot (.)

t(`Cities.${cityType}`)}

**Comment by stephyswe** [comment]
Oh my god! Haha, i have tried with dots and "[ ] " ... that is just to much

**Comment by adrai** [comment]
😉

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏
