### ISSUE TITLE
Format number with toString return characters

### ISSUE THREAD

**Issue by nappalm** [i18next/react-i18next#1288]
## 🐛 Bug Report

When creating a format that returns bold, an error occurs if the value is a number, even if toString is placed, it returns characters.

## To Reproduce

https://codesandbox.io/s/react-i18next-forked-jdd94?file=/src/app.js

```js
interpolation: {
      format(value, format, lng) {
        if (format === 'bold') return value.bold();
        return value;
      },
    },
```

## Expected behavior

Numeric value expected to return in bold format

```js

```

## Your Environment

- *runtime version*: i.e. node v15.6.0
- *i18next version*: i.e. 19.5.2
- *os*: Linux
- *any other relevant information*

**Comment by adrai** [comment]
.bold() generates html...
But react will escape that...

**Comment by adrai** [comment]
Probably the Trans component suits better for your use case: https://react.i18next.com/latest/trans-component#using-with-react-components.
For example: https://codesandbox.io/s/react-i18next-forked-9xn1c?file=/src/app.js:640-778
![image](https://user-images.githubusercontent.com/1086194/112937411-e532dd00-9127-11eb-9854-40099b9bd651.png)
![image](https://user-images.githubusercontent.com/1086194/112937450-f2e86280-9127-11eb-8500-034cd90d018a.png)
