### ISSUE TITLE
TS "excessively deep and possibly infinite" error when creating generic type to specify required namespaces

### ISSUE THREAD

**Issue by stezu** [i18next/react-i18next#1290]
## 🐛 Bug Report

I'm receiving an `excessively deep and possibly infinite` type error in my app even with very few namespaces. In my reproduction I only have two, but locally I have 5 so it doesn't seem like the same issue as what was previously reported. The one thing that I do see as somewhat unique is my attempt to define a generic type which allows me to specify the required namespaces when calling my helper methods.

To be more specific, I have a few helper methods in my app which given a `t` function and a value, will produce the correct translation for a given enum. They're relied on all throughout the app which uses different namespaces depending on the page/bundle (but the helper methods all use a shared bundle). The goal was to ensure I could type check the helper methods properly and ensure that the consumers were loading the required shared translation namespace.

This generic type supports the following:

```ts
const formatDayOfWeek = <T extends TFunction<any>>(
  t: TranslationFunction<'shared', T>,
  day: DayOfWeek
): string => {
  switch (day) {
    case DayOfWeek.Monday:
      return t('shared:monday');
    // ... etc
  }
};

// The dependency exists, so this passes type checking:
const [t] = useTranslation('shared');
formatDayOfWeek(t, DayOfWeek.Monday);

// The dependency exists in a group, so this also passes type checking:
const [t] = useTranslation(['shared', 'accounts']);
formatDayOfWeek(t, DayOfWeek.Monday);

// The dependency doesn't exist, so this fails type checking:
const [t] = useTranslation('accounts');
formatDayOfWeek(t, DayOfWeek.Monday);

// The dependency doesn't exist in a group, so this fails type checking:
const [t] = useTranslation(['users', 'accounts']);
formatDayOfWeek(t, DayOfWeek.Monday);
```

This part all seems to be working as expected, but I still get the excessively deep error.

## To Reproduce

I created a [TS Sandbox minimal reproduction of the issue](https://www.typescriptlang.org/play?noUnusedLocals=true&ts=4.2.3#code/PQKgBAtF07fw+AocY3vQSwIwA4B2ApgB4AuYAJoQA6H5X4DGmhAzhhxyEor3-9BDAkSUgE9aYAMqkATpnwBzALIBDamAC8YAN5gA2gGtCYgFxhWchYoC651fjFgAvgG5REwmAAqAMQCuTKSYAPb4AEps-gA25NqW8kpgAD5gIQBGAFaEjOSpAIKysqpiADwJ1ilpWTmkAHxVgVQAZgqEFFX4MdHuSKCQAoNDKJwcsoSquRA4BCTk4rTso5zcQ2uDQiILXr6q0dHpk4alvgA0PlpgxmIhzWCRrCH+soxsDdr63jZgc3QU7PoiAA3Qiyb4AfjAvjA5m8vW2YAAcqoALZsaiTQgnS67faHRjHCpKOrvKFVXz6Gy9YDAJEhWQovaYABeXlY1miXnwqPRmI8kny1Fo9AA0iZWKURdhziKAEykgAGABIdFKwAAyCxWJTOAB0KrlGq1iUUzgV7gRguFFDFYlYssl0rAcsVBuwRqJpv1OgAosRGNF-FRJbLztdbmAHGJKQ1NZ6zRbPHSGUzWQ7vDLLuG7t5SSKfmQ-uxsz4kGhId59CLvr96OxIox6RRytrFOco3Uy+gK1Wa4W62BxqoKGFok4o5SuxhIVa-rb7ZKwyYI5Xqw0CkK5+KHSLzoj6YzoizCOneySp+hzLPReLF1dlzmz1Vrzbb7vk4fj6e152MOZgaCXb-oQIKyImkj7imR6sqUuZZg+FypJBn5prBdTUrSyGpl4KIxME1CcmA3JoqwGKvKw-JeAAqvgoT4N4IQAJL4KQoKsLUdGlFRpIABRUQWrEDlGYCQjxhjmFRACUWgNECISYB0wGgdJtb-GAYnmAozSgmAjHSZosnyRQXaQoxQFESBoLgV4AAyqiWAA8s0aGXDRdEMcxrGyOxuScd4AlFpGjgiep+kNP5Smgg0qnsDxYVgFpOnhCZ9zmQBYGUWAL6IlIpSIjKro6IiHqts4pgGiVJoJplWHQYQyh4ZgsHnPxMX3jcObnDZlx2Y5zncaS3VtVRKXZblNl7ge2GwfoNk2CSVS1ceDWxE1GZgH6AZBliVFdeeaCRRlNVTXVkSkM8+DNWAABqpLXQFA7KjoiWyM6eoqi99xmil+ZtSW3gXpCS2smdF0zdW5zhL+l4WaB5n3X9CEA+WPj6NdNhpZZGUIsD9WNaDsiXett2XAj-ZqU9n2ImVH34Npr3hN9KPFYjHWltOH7YQTRP6IiNiQ9DB2w4BQvpfCSZ+IEjC2nlD1qciJFkV42gACKEM0qh4QrvKvOc-naA8TwvG8lws+TsX-ZJk7Mydy2NVdiKAv4KLpKC83mWbglqf9KW4zNfPQ+Ynri5IktMNzeV6-OetqxreEPHheuXIbzzkaSnuBWJSNWxjNtQXbq0R+t3jzoHSJy8WSO+7bIOEOdhP+-zPil+ZuIHEcsGx5rsQJ7E6EiAoXka68PgBEEnEZwO2ukZilxd1rPIz68DQ6F2pQXiX4oV6PUsy4i64+IQKIEaorEyCarCFMUThtZ9+Qhffh2nBv8891EsTb2HvlhL3cTGtYz8MDeE8qCagIRoinzomoDQbUMjZFyJcc+1hoFdjqDxC81xYTziqJvO0lJAFgEkrCMejAI75WbuKGO6tu6kF-v3NA68gHYLal-PeB9vBHxPmfVsl8iglG3nfB+MJhayAIWgbwr9aHv3ICwkhwQf7SMuJ6AhaCMEmCwVvVIuDWD4IvC0Gh109j+EIOCIOrYCFEJ3uHOuYNyHaKoXHN+rA8L92cFsJMVF2LeGKPgVgED5ERHRGEdiss2rTyVqST4ciJ51HOOkEI4CJj4G+JqVeaBSDEKlgEvK9DBwTAoGYMA8TEkOHcG4dxkhJHhMxLBS4AByOQDg-GQLCHU0k-k2pt3xISVsDQKzCODiIKgAZVDjDAM0LJdEwD+C8T45p2TJ7y0XkrOe1CF6K0xKotAvjTFImfpYzxhBvFNP8XRB4YDfFYn3r0Po4B1j3IQCMZYnBDneTAI2KgzyvmrAeb82AmxMop2NuwbQ2wIzjEeKnNgvRGy+PIBCo25FLhpLAI03xpywjmB0M4AhvjsBYrUYUlFGBnHpFtOYOpno6kXjcWgHFSBnCRnYLCywMLgnkD0OQRl2gZlHLmRi-APE6l4rqZJdwLL4WKNBUK64upSW2lFWyuFuhUXmFILKFwlxeXHPRS0wV+hhWsGwHUmwYqkASryc42IGrQWyiFXi0wsr5UmEVRUrwPpORohYt4TwLltAdPNvcfJo4xBXxKKUT63EQoeqPnQUgPraBcQaLCDCWUwCKDoKCTAjBUVJlIAAC1Pj8bk6ROTsBmaikIFhaDMGaE4YiOsvBUGtHQZgbA0h3ALV4BUpAFTjMmWEVFhbSCUr6LSDErB2IdEHlW-NhBoi0FemiAtIR-i6h8PmzA7A6DOIhUOotXawBzoXTpZd+bV3sFGV4RgexOQdAAO6YALUOrw4wACO-hMDjGMjSIiyzMSxSLaoMAKIFCYFwiiaSDgOgFqLferwvLUX8r1f-JQ7BYMyOIFu0gupMo6vmXRaJYRGFBo-V+9o1SR6swjEC8iBCA1e3YF-bJHYkDtM-kRy6ka+nqUiGR79lGvBtRjV6+Nvqo39MOtJQ6SrLDjKmn-WpsiB2XQ7Fs1VPhkMBM46UQ1xq9adksZ6GSuguy-p9CCfAYBH3PpDZGCwHIuT-t1tZtkwR9gWEIF4Q9AAiEg5F2QgjHJQLzGhoNgDAZOzA6RMBHnEAlOmYHWI+bM7SbYrBGDyGoDIoo9IuzjHrlZ0g9qjWOpMHK-wZKXVmvKUAA). It uses the latest type definitions for `react-i18next` and `i18next` with most of the unnecessary parts removed so it wouldn't be overly complex.

## Expected behavior

The typescript error about the types being excessively deep and possibly infinite shouldn't be happening. It's certainly possible that the generic type I produced to be able to specify namespace dependencies of a method is incorrect, but I don't think my use case is unique. At the very least, there may be an opportunity to improve documentation or export a type which users of this library can rely on to support the use case.

Thanks for taking a look, I'd appreciate any help!

## Your Environment

- *runtime version*: Node 14, Chrome 88
- *i18next version*: 19.9.2
- *react-i18next version*: 11.8.12
- *os*: Mac

**Comment by pedrodurek** [comment]
Hey @stezu, the `excessively deep and possibly infinite` error is expected, since you're passing `any` to `TFunction`, which will enter in an infinite loop by the moment we call the `t` function. Take a look at this example: https://tsplay.dev/wQAJjw.
We must pass a valid generic to infer the proper keys and return type. 

I'm afraid it's not possible to do what you want...

Anyway, I simplified your types a bit here: https://tsplay.dev/N5EkdN
And this is the best I could get: https://tsplay.dev/ND5gjm

**Comment by pedrodurek** [comment]
I'll close this issue for now, since it's not necessarily a bug, but we can reopen it if needed.

**Comment by kitsunekyo** [comment]
@pedrodurek i just stumbled over this, since we have the same usecase. we have some shared "maps" where we map certain values to translations. i wanted to pass `t` into the function, so that i get the correct translation for the current language.

ie
```ts
export const getAbsenceLabels = (t: (key: string) => string) => ({
  BAD_WEATHER: t('attendence.badWeather'),
  SICKNESS: t('attendence.sickness'),
  ABSENCE: t('attendence.absence'),
  LEAVE: t('attendence.leave'),
  OTHER: t('attendence.other'),
});
```

i could use `i18next.t` directly, but then i lose the reactive language context. and i also dont want to just return the keys as string, as this would break static analysis with `i18next-scanner`.

is there any recommendation you could give on how to handle such shared maps?
