### ISSUE TITLE
Please update examples, because react was updated.

### ISSUE THREAD

**Issue by watscho** [i18next/react-i18next#1294]

**Comment by jamuhl** [comment]
if I remember right v17 contains no breaking changes...so there is nothing different in using react-i18next in v16 vs v17.

Anyway...PR would be welcome

**Comment by watscho** [comment]
I mean ssr examples using react router

**Comment by adrai** [comment]
@watscho do you mean this one? https://github.com/i18next/react-i18next/tree/master/example/razzle-ssr

**Comment by watscho** [comment]
I mean this 
[simpleblack's boilerplate](https://github.com/simpleblack/react-redux-universal-hot-example)
[docs](https://react.i18next.com/legacy-v9/serverside-rendering)

**Comment by adrai** [comment]
That’s the docs vor the old react-i18next...
Have a look at: https://react.i18next.com/latest/ssr

**Comment by watscho** [comment]
okay tnxs
