### ISSUE TITLE
Unable to resolve module html-parse-stringify2 when bumping to react-i18next 11.8.13

### ISSUE THREAD

**Issue by MEsteves22** [i18next/react-i18next#1296]
## 🐛 Bug Report

I bumped react-i18next from 11.8.12 to 11.8.13 and my code stopped compiling. I have this error:

```
Error: Unable to resolve module html-parse-stringify2 from /Users/user/Desktop/project-name/node_modules/react-i18next/dist/commonjs/Trans.js: html-parse-stringify2 could not be found within the project or in these directories:
  node_modules

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
> 1 | "use strict";
  2 |
  3 | var _interopRequireWildcard = require("@babel/runtime/helpers/interopRequireWildcard");
  4 |
    at ModuleResolver.resolveDependency (/Users/user/Desktop/project-name/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:234:15)
    at DependencyGraph.resolveDependency (/Users/user/Desktop/project-name/node_modules/metro/src/node-haste/DependencyGraph.js:413:43)
    at Object.resolve (/Users/user/Desktop/project-name/node_modules/metro/src/lib/transformHelpers.js:317:42)
    at resolve (/Users/user/Desktop/project-name/node_modules/metro/src/DeltaBundler/traverseDependencies.js:629:33)
    at /Users/user/Desktop/project-name/node_modules/metro/src/DeltaBundler/traverseDependencies.js:645:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/user/Desktop/project-name/node_modules/metro/src/DeltaBundler/traverseDependencies.js:644:33)
    at /Users/user/Desktop/project-name/node_modules/metro/src/DeltaBundler/traverseDependencies.js:329:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/user/Desktop/project-name/node_modules/metro/src/DeltaBundler/traverseDependencies.js:137:24)
```

When I was using react-i18next 11.8.12, everything was fine. And if I downgrade to react-i18next 11.8.12, I am able to compile my code.

I tried the steps suggested in the error, but nothing is working.

Am I the only one having this problem when bumping to the new version?

Thank you!

## Your Environment

- *runtime version*: node v14.16.0
- *i18next version*: 11.8.13
- *os*: Mac

**Comment by adrai** [comment]
html-parse-stringify2 is not used anymore....
there must be something strang in your local setup...
try to clean your node_modules... and install again

**Comment by MEsteves22** [comment]
Hello,

I already tried that, but I will try again and clean more stuff on my project.

Thank you!

**Comment by watnFoehn** [comment]
I have the same issue in my react-native project.

Of course I did:
`1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*`
 
 But it didn't solve the issue.

**Comment by watnFoehn** [comment]
npm start -- --reset-cache

Did the trick in the end @MEsteves22

**Comment by MEsteves22** [comment]
@watnFoehn Thank you! I was also able to solve my problem but by deleting my project and cloning it again :sweat_smile:

**Comment by Noitidart** [comment]
For those using Expo you have to do `expo start -c`
