### ISSUE TITLE
Trans component parses values which could lead to translation errors or runtime errors

### ISSUE THREAD

**Issue by kirillku** [i18next/react-i18next#1297]
## 🐛 Bug Report

When using `Trans` component, values are getting html parsed, so extra tags could be inserted or there could be a loop. It could also break the page when some value has invalid html. I faced the issue for the first time when someone from QA tried to paste `</ <> </` to the input field, which was used to render the preview.

Could be related to https://github.com/i18next/react-i18next/issues/1275, but I am experiencing this issue on the latest version also.

## To Reproduce

[codesandbox](https://codesandbox.io/s/trans-component-issue-otkrh)

```js
// translations
{ input: "Hello, your input is {{value}}, <0>congratulations</0>!" }

// code
const value = "Hello, your input is {{value}}, <0>congratulations</0>!";

<Trans
  i18nKey="input"
  values={{ value }}
  components={[<span style={{ background: "orange" }} />]}
/>

```

## Expected behavior

Anything passed to values are treated as a plain text, not parsed as html.

## Your Environment

- *runtime version*: `node@14.15.4`
- *i18next version*: `i18next@19.3.1`, `react-i18next@11.6.0`
- *os*: Mac
- Both with classic and ICU formats

**Comment by adrai** [comment]
This is the purpose of Trans....
if you don't like the Trans behaviour, use the normal t function
