### ISSUE TITLE
Getting @withNamespaces error on running the project

### ISSUE THREAD

**Issue by iphalgun** [i18next/react-i18next#1298]
![Screenshot 2021-04-13 at 6 18 46 PM](https://user-images.githubusercontent.com/54344156/114554773-b1f26100-9c84-11eb-9d3b-944d58e692b4.png)

**Comment by iphalgun** [comment]
> withNamespaces is old: https://react.i18next.com/latest/migrating-v9-to-v10#components-v9-greater-than-v10

But I've used "react-i18next": "^9.0.10", this version in my project, so what could be the issue?

**Comment by adrai** [comment]
the @ before withNamespace

**Comment by iphalgun** [comment]
I've tried with @, but still getting the same issue.

**Comment by adrai** [comment]
Compare your code with this example: https://github.com/i18next/react-i18next/blob/master/example/v9.x.x/react/src/App.js
You are for sure using withNamespaces in the wrong way.
Here are the docs: https://react.i18next.com/legacy-v9/withnamespaces
