### ISSUE TITLE
Usage with TypeScript: Typing useTranslation hook

### ISSUE THREAD

**Issue by velialiev** [i18next/react-i18next#1301]
## 🐛 Bug Report

I've tried to use i18next with TypeScript but I faced an issue in useTranslation hook typing. I type it exactly like in docs: I create d.ts file, import json locale there, merge default Resourse interface with my own one and add namespace: typeof locale there.

But instead of correct types I have this error:
TS2589: Type instantiation is excessively deep and possibly infinite.

<img width="671" alt="изображение" src="https://user-images.githubusercontent.com/55160134/115221851-c4e8b380-a112-11eb-92bc-7fd2334e18e8.png">

Sometimes it works fine and show correct hints, but anyway it requires a very long time to update after I am adding something to locale.

## To Reproduce

Just describe types like described in docs: https://react.i18next.com/latest/typescript#create-a-declaration-file

## Expected behavior

Types should work correctly: They shouldn't throw any errors and should update faster

## Your Environment

- *runtime version*: node v15.14.0
- *i18next version*: v20.2.1
- *react-i18next version*: v11.8.13
- *os*: Mac
- *TypeScript*: v4.2.4

**Comment by velialiev** [comment]
<img width="475" alt="изображение" src="https://user-images.githubusercontent.com/55160134/115224139-30cc1b80-a115-11eb-88d9-9532de97032b.png">
<img width="689" alt="изображение" src="https://user-images.githubusercontent.com/55160134/115224161-3590cf80-a115-11eb-9f94-bd99549bc253.png">
<img width="574" alt="изображение" src="https://user-images.githubusercontent.com/55160134/115224178-39245680-a115-11eb-8292-a94e0104cbdd.png">

**Comment by ImADrafter** [comment]
Hello @velialiev; The default NS for react-i18next is called "translation", not "translations". If you use a different default NS, for the moment, you must specify which one you are using.

TLTR: Rename "translations" to "translation" or call the useTranslations hook with your NS, "translations".

**Comment by velialiev** [comment]
> Hello @velialiev; The default NS for react-i18next is called "translation", not "translations". If you use a different default NS, for the moment, you must specify which one you are using.
> 
> TLTR: Rename "translations" to "translation" or call the useTranslations hook with your NS, "translations".

Hello, thank you for your answer. I've renamed "translations" to "translation" everywhere, but still have the same problem. Also, even if I specify the NS I'm using explicitly by passing it's name in useTranslation hook problem still appears

<img width="827" alt="изображение" src="https://user-images.githubusercontent.com/55160134/115236623-3d0ba500-a124-11eb-8c0d-58991f4ebd7c.png">
<img width="724" alt="изображение" src="https://user-images.githubusercontent.com/55160134/115236639-4268ef80-a124-11eb-9db0-e5652b0ddb21.png">
<img width="711" alt="изображение" src="https://user-images.githubusercontent.com/55160134/115236647-45fc7680-a124-11eb-815b-d044df432c57.png">

**Comment by ImADrafter** [comment]
> Hello, thank you for your answer. I've renamed "translations" to "translation" everywhere, but still have the same problem. Also, even if I specify the NS I'm using explicitly by passing it's name in useTranslation hook problem still appears

Hm so I was wrong then @velialiev  ! Would you mind to fill up a codesandbox so we can check what's wrong ?

**Comment by velialiev** [comment]
> > Hello, thank you for your answer. I've renamed "translations" to "translation" everywhere, but still have the same problem. Also, even if I specify the NS I'm using explicitly by passing it's name in useTranslation hook problem still appears
> 
> Hm so I was wrong then @velialiev ! Would you mind to fill up a codesandbox so we can check what's wrong ?

Hi, sorry for late answer, I'll try it to fill it up tommorow. The problem is that in my current project almost everything works fine. My IDE shows correct hints but only after I press ctrl + s in JSON file on my own, although it never required this. Sometimes I even must press it several times. I'm using Intellij IDEA.

I'm afraid I do something wrong, because it's very strange that in this project everything works and in that one that i described above I have an error. I'm using same config for them...

I'll try my best to reproduce and explain this problem

**Comment by paulmthiebauth** [comment]
@velialiev What ended up being the issue here?
