### ISSUE TITLE
React-i18n showing json property labels before rendering the translation

### ISSUE THREAD

**Issue by r0zator** [i18next/react-i18next#1305]
## 🐛 Bug Report

I am trying to add react-i18n to my React app - with caching in the browser. All is fine, I have added it - it works. Problem is that in the moment I am accessing the website/app, for around 0.2s I can see all the property labels from the translation json (which is on public/locale). I am attaching here the configuration file for i18n and an image with the issue. Bear in mind it's for 0.2s - after that all works fine (until refreshing the page when again 0.2s I can see the labels)

Thanks!

Image to how it looks firstly before being ok: https://imgur.com/WCcCLL4

## To Reproduce

I've just configured react i18n in my React app. All is working fine, besides that rendering.

```js
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import ChainedBackend from "i18next-chained-backend";
import HttpBackend from "i18next-http-backend";
import LocalStorageBackend from "i18next-localstorage-backend";
import LanguageDetector from 'i18next-browser-languagedetector';

i18n
  .use(ChainedBackend)
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    fallbackLng: 'en',
    react: {
      useSuspense: false,
      wait: false,
    },
    backend: {
      backends: [
        LocalStorageBackend,
        HttpBackend
      ],
      backendOptions: [{
        expirationTime: 7 * 24 * 60 * 60 * 1000 // 7 days
      },
      {
        loadPath: '/locales/{{lng}}/translation.json'
      }]
    },
  });

export default i18n;
```

index.tsx
```js
import './i18n';
import 'bootstrap/dist/css/bootstrap.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import * as serviceWorker from './serviceWorker';

ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById('root')
);

serviceWorker.unregister();
```

## Expected behavior

I should see directly the translations - not the property labels and afterwards the translation

## Your Environment

- *runtime version*: node v12.16.1, Chrome
- *i18next version*: ^20.2.1
- *os*:  Windows

**Comment by adrai** [comment]
You're probably not using Suspense, and/or not waiting for the ready flag to be true: https://react.i18next.com/latest/usetranslation-hook#not-using-suspense https://react.i18next.com/latest/withtranslation-hoc#not-using-suspense

**Comment by r0zator** [comment]
Yes, this was it. Sorry, my fault. Glad I got it done. Thanks :D

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏
