### ISSUE TITLE
Introduce a new prop in the Trans component called keyComponents.

### ISSUE THREAD

**Issue by iamrane** [i18next/react-i18next#1308]
## 🚀 Feature Proposal
I would like to introduce a new prop to the Trans component called keyComponents. And what it does is that it wrap a key in a translation string with an element.

## Motivation
1. Unnecessary tags in the translations
Alot of times we end up with `Hello <firstname>{firstname}</firstname>` types of translations. A wrapper around a key with the exact same name. These feels unnecessary in these kind of places.

2. More reusable keys
I can use the same i18nkey on several places. Sometimes with a styling and sometimes without. (see example)

3. The styling ends up in the front end code, and not in the data.
Often the people who do translation they only care for the translations. They don't always know where it should be used or how it should look. With components styling ends up in the translations and I think it's not optimal. With keyComponents the styling will end up in the front end layer where it belongs.

## Example

So instead of writing
```js
<Trans
    t={t}
    i18nKey="myi18nkey"
    defaults="Hello <firstname>{firstname}</firstname>"
    values={{ firstname: 'Christian' }}
    components={{ firstname: <span style={{ color: 'red' }} /> }}
/>
```

I imagine something like this:
```js
<Trans
    t={t}
    i18nKey="myi18nkey"
    defaults="Hello {firstname}"
    values={{ firstname: 'Christian' }}
    keyComponents={{ firstname: <span style={{ color: 'red' }} /> }}
/>
```

Then I can use the same i18nKey in other places where I don't want the highlight styling
```js
{t('myi18nKey', { defaultValue: 'Hello {firstname}', firstname: 'Christian' })}
```

Im not saying we should replace components, because there are places where that makes sense. But for me keyComponents would replace components 9 times of 10.

**Comment by adrai** [comment]
Would you like to try a Pull Request to address this? Remember to add unit tests.

**Comment by iamrane** [comment]
I will have a try. Need to understand how the Trans component works. But will have a look.

**Comment by jamuhl** [comment]
Why not just:

`<span style={{ color: 'red' }}>{t('myi18nkey', { firstname: 'Christian' })}</span>`

or if you got to use Trans (not sure why people use Trans for simple strings)

```js
<span style={{ color: 'red' }}>
<Trans
    t={t}
    i18nKey="myi18nkey"
    defaults="Hello {firstname}"
    values={{ firstname: 'Christian' }}
/>
</span>
```

or using parent props

```js
<Trans
    t={t}
parent='span'
style={ color: 'red' }
    i18nKey="myi18nkey"
    defaults="Hello {firstname}"
    values={{ firstname: 'Christian' }}
/>
```

I really don't see a benefit of adding an additional wrapper prop.

**Comment by iamrane** [comment]
It wraps the values variables and not the entire string. So in this case it would wrap the value  firstname

**Comment by jamuhl** [comment]
not sure if that will work looking at how the implementation of trsns component works. but feel free to provide a PR.

**Comment by iamrane** [comment]
Hi again :)
I made a version now where I implemented wrappers.
Wrote a bunch of tests on it as well.

https://github.com/iamrane/react-i18next/tree/trans-wrappers

Now really sure how to do a PR, but I'll look in to it soon :)

**Comment by iamrane** [comment]
Should i maybe rename wrappers to valueWrappers? Or is wrappers clear enought?

**Comment by jamuhl** [comment]
i think valueWrappers is more speaking for what it does.

**Comment by iamrane** [comment]
Think wrappers are clear enough when its plural. Will go with that.

**Comment by iamrane** [comment]
Hope everything worked out okey now, first time I'm contributing to an open source project.
https://github.com/i18next/react-i18next/pull/1309

How do I deal with documentation?

**Comment by cellog** [comment]
could I suggest an alternative approach: what if you add a `formatter` prop to Trans which accepts the translation string and can modify it to add placeholders?

```tsx
<Trans
    i18nKey="myi18nkey"
    defaults="Hello {firstname}"
    values={{ firstname: 'Christian' }}
    formatter={(translatedString: string) => wrapArgumentWithPlaceholder(translatedString)}
    components={<span style={{ color: 'red' }}>}
/>
```

`wrapArgumentWithPlaceholder` would be a function that finds `{firstname}` and replaces it with `<0>{firstname}</0>`

**Comment by cellog** [comment]
note: implicit in this ^ idea is that the flow would be `translate -> formatter -> interpolate`. Thus `Hello {firstname}` would in `fr` pass `Bonjour {firstname}` to the formatter. The formatter would return `Bonjour <0>{firstname}</0>` and then interpolation of tags and variables would occur.

**Comment by iamrane** [comment]
Not a bad idea… easy to implement

**Comment by cellog** [comment]
I would not prefer the `keyComponents` idea. Incidentally, in our workplace, we are preferring duplication over ease. So for your example, we would have 2 identical translations with different keys. Part of the reasoning is that these are actually different contexts. It is possible that they will intentionally diverge in the future. For example, if you are translating for an email, `Hello {firstName}` might be formatted `Hello {firstName}` and the web page version `Hello <b>{firstName}</b>`, but perhaps later user research shows the email version needs to be formatted larger and with an emoji at the end. If you are using the same translation with a formatter, now you've got a potential UX issue. If the person maintaining the email version doesn't know the web version exists, you get unintended consequences for changing it.

Ultimately, I would not recommend opening this Pandora's box: every variant of text should have a unique key. This is what allows the cross-domain linter we wrote to work. In the example above, if the user were to change the email formatting, the PR build would fail, as the linter would detect that the email version is a different translation from the web version.

**Comment by iamrane** [comment]
I understand what you are saying and I totally agree with you about duplication over ease. But if we are talking about the exact same component but two different views I don't agree that you should duplicate, and this is not about opening pandoras box.

**Comment by iamrane** [comment]
And i really like the idea to separate concerns. If keyComponents is not something people like, but formatter is, i totally can go with that.

**Comment by cellog** [comment]
> I understand what you are saying and I totally agree with you about duplication over ease. But if we are talking about the exact same component but two different views I don't agree that you should duplicate, and this is not about opening pandoras box.

ah I see.  This is how we handle that kind of thing, FWIW:

```tsx
const ConditionalFormattedThing = ({ condition, children }: { condition: boolean; children: React.ReactNode }) => {
  if (!condition) return <>{children}</>;
  return <span style={{ color: 'red' }}>children</span>;
}

const Hello = ({ condition }: { condition: boolean }) => {
  return (
    <Trans>
      Hello <ConditionalFormattedThing condition={condition}>{userName}</ConditionalFormattedThing>
    </Trans>
  );
}
```

This way, you can use `Hello <0>{userName}</0>` for both cases.

**Comment by iamrane** [comment]
I know how to solve this without keyComponents. This was not and issue, but a feature request. I didn’t needed any help, I asked for a feature, and I made a pull request for it. Please read my motivation why I think it’s awesome. If you disagree with that I’m totally fine with that as well. It’s not up to me if this get implemented. I think it’s really nice and should be implemented.

**Comment by jamuhl** [comment]
Would be awesome to get a few more voices/opinions about this. As it is somehow an edge case of quality of life improvement. Not sure how many devs will use this - while introducing additional complexity and size.
