### ISSUE TITLE
Trans does not translate with tags inside without a i18key

### ISSUE THREAD

**Issue by cdaycmc** [i18next/react-i18next#1312]
## 🐛 Bug Report

Using the Trans tag without the i18key attribute and with a tag inside doesn't work, eg. `<Trans>some text with <a>a link</a> here</Trans>` with json `"some text with <1>a link</1> here": "some translated text with <1>a translated link</1> here"`

I have tried a whole bunch of things to make it work, including useEffect for language changes. I've also set a whole bunch or react parameters in the config, none of which worked. I have also made sure there is no whitespace (eg. CRLF) inside the `<Trans>` tag.

It does work if you use `<Trans i18key="some.key">` but I want to be able to auto-extract translations using i18next-parser

## To Reproduce

[translate.zip](https://github.com/i18next/react-i18next/files/6412553/translate.zip)

```js
import "./App.css";
import { useState, useEffect } from "react";
import { useTranslation, initReactI18next, Trans, I18nextProvider } from 'react-i18next';
import i18n from 'i18next';
import translationEN from './locales/en/translation.json';
import translationPT from './locales/pt/translation.json';

i18n
  .use(initReactI18next) // passes i18n down to react-i18next
  .init({
    resources: {
      en: {
        translation: translationEN
      },
      pt: {
        translation: translationPT
      }
    },
    lng: 'en',
    fallbackLng: 'en',

    interpolation: {
      escapeValue: false
    }
  });

function App() {
  const { t, i18n } = useTranslation();
  return (
    <I18nextProvider i18n={i18n}>
      <a
        href="#"
        onClick={() => {
          i18n.changeLanguage("en");
        }}
      >
        en
      </a>
      |
      <a
        href="#"
        onClick={() => {
          i18n.changeLanguage("pt");
        }}
      >
        pt
      </a>
      <br />
      <Trans>Here is a button</Trans>
      <br />
      <MyButton label={<Trans>I Change</Trans>} />
      <MyButton label={t`I Change`} />
      <Trans>I Change</Trans>
      <br />
      <span>
        <Trans t={t}>
          But here is something that has <a href="#">a link</a> in the middle of
          the text.
        </Trans>
        xx
      </span>
    </I18nextProvider>
  );
}

const MyButton = ({ label }) => {
  return (
    <button>
      <span>{label}</span>
    </button>
  );
};

export default App;

```

## Expected behavior

<Trans> should translate with interpolation of tags

## Your Environment

- chrome 90.0.4430.93
- *i18next version*: 20.2.2
- *os*:  Windows
- using i18next-parser 3.11.0 to extract the items to translate

**Comment by adrai** [comment]
You are just missing the dot in your translation json: "... of the text."

`"But here is something that has <1>a link</1> in the middle of the text.": "But here is something that has <1>a link</1> in the middle of the text."`

**Comment by cdaycmc** [comment]
🤦‍♂️
