### ISSUE TITLE
Will not Injecting initialStore in HTML increase the HTML's size?

### ISSUE THREAD

**Issue by bandYellow** [i18next/react-i18next#1318]
## To Reproduce

A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

```js
// Paste your code here
```

## Expected behavior

```js
// Paste the expected results here
```

## Your Environment

- *runtime version*: i.e. node v14, deno, browser xy
- *i18next version*: i.e. 19.5.3
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by jamuhl** [comment]
I don't understand what you try to do - but guess it's an unrelated question. The initialStore is only there for using in combination with serverside rendering
