### ISSUE TITLE
Type error on template literal with expression on Typescript 4.2

### ISSUE THREAD

**Issue by elgorditosalsero** [i18next/react-i18next#1319]
## 🐛 Bug Report

On Typescript 4.2.x the typed `t` function throw  a type error when using template literal with an expression.
The [doc](https://react.i18next.com/latest/typescript#type-errors) says that's handled by TS 4.2.x and the workaround of `as const` is required only in TS 4.1.

![ts](https://user-images.githubusercontent.com/65770455/118475405-8263c800-b70c-11eb-840c-b23d764b85b5.png)

## To Reproduce

1. Follow the guide for TS support on a project with TS 4.2.x.
2. Use an expression inside the `t` function with a template literal

```ts
t(`activities:bottomSheets.assumption.title.${activity._type}`)
```

## Expected behavior

TS should not throw the error :)

## Your Environment

- *runtime version*: Node 15.13.0, React Native 0.64, TS 4.2.4
- *i18next version*: 20.2.2
- *os*: Mac

**Comment by pedrodurek** [comment]
Hey @elgorditosalsero, typescript team ended up reverting the `Template Literal Inference` feature. You can find more info [here](https://devblogs.microsoft.com/typescript/announcing-typescript-4-2/#reverting-template-literal-inference).
You can see the discussion here as well: https://github.com/microsoft/TypeScript/issues/42589, https://github.com/microsoft/TypeScript/pull/41891
So that, `as const` is still needed 😞 . I'll update the document.

**Comment by pedrodurek** [comment]
I will let you know if anything changes

**Comment by elgorditosalsero** [comment]
Hi @pedrodurek, thx for the info, will check the issues!

Btw, I'm still having the error also with `as const` as the attached screenshots.

![Schermata 2021-05-17 alle 17 01 57](https://user-images.githubusercontent.com/65770455/118510959-bf8e8100-b731-11eb-9d33-bfcb00a5eb6f.png)
![Schermata 2021-05-17 alle 17 02 12](https://user-images.githubusercontent.com/65770455/118510963-c0271780-b731-11eb-8363-f9984eacac1d.png)

**Comment by pedrodurek** [comment]
Hey @elgorditosalsero, It seems to be missing some keys, for example:
```json
{
  key: {
   a: 'a',
   b: 'b',
  }
}
```
`c` is missing here.

```tsx
type Foo = 'a' | 'b' | 'c';
const foo: Foo = 'b';
...
t(`key.${foo}`);
```

**Comment by elgorditosalsero** [comment]
@pedrodurek Thx for the tips, my fault on the translation file!
