### ISSUE TITLE
Suggest Add a prop that enable change key into value

### ISSUE THREAD

**Issue by suedar** [i18next/react-i18next#1321]
## 🚀 Feature Proposal

``` en.json
{
   ...
   main_page_example:  'example'
}
```

For example, I have a value that use as `i18n("main_page_example")`, It show `example`. But if there is too much of these, it is hard to find out the world without a translation. So maybe it is possible to have a switch to turn off the translation. And when the switch is on, it show `main_page_example`. It would make the translator easily to find out the word that is leftover.

## Example

``` 
// i18nConfig

i18n.use(initReactI18next).init({
  useKeyAsValue: true, // when it is on, it display main_page_example. And when it is off, it display example
  resources: {
  en: {
    common: {
      main_page_example: "example"
    }
  }
} 
});
```

**Comment by adrai** [comment]
Try to set lng to "cimode"
