### ISSUE TITLE
Keep language preference while page refresh 

### ISSUE THREAD

**Issue by NOURELsayed** [i18next/react-i18next#1325]
`
import i18n from "i18next";
import LanguageDetector from "i18next-browser-languagedetector";
import { initReactI18next } from "react-i18next";
import en from "./i18n/en";
import ar from "./i18n/ar";
import { defaultLanguage } from "./config/index";

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    // we init with resources
    resources: {
      en,
      ar,
    },
    fallbackLng: 'ar',
    // lng: defaultLanguage,

    debug: true,

    // have a common namespace used around the full app
    ns: ["translations"],
    defaultNS: "translations",

    keySeparator: false, // we use content as keys

    interpolation: {
      escapeValue: false,
    },
  });

export default i18n;
`

**Comment by adrai** [comment]
Please provide an reproducible example. A codesandbox example or similar.
