### ISSUE TITLE
@storybook/react ^6.3.0-beta.1

### ISSUE THREAD

**Issue by chrillep** [i18next/react-i18next#1326]
## 🚀 Feature Proposal

make the [storybook example](master/example/storybook) work with newer Storybook 6.3.0 and webpack 5

**Comment by adrai** [comment]
Is there an issue?

**Comment by chrillep** [comment]
yep try checking out the repo.

- `cd react-i18next/example/storybook `
- ` npx sb@next upgrade --prerelease`
- `npm i -D @storybook/builder-webpack5@next @storybook/manager-webpack5@next`
- `npm run storybook`

https://gist.github.com/shilman/8856ea1786dcd247139b47b270912324#upgradenpm 
https://storybook.js.org/blog/storybook-for-webpack-5/

could definitely be me doing something wrong =)

**Comment by adrai** [comment]
Just updated all dependencies: https://github.com/i18next/react-i18next/commit/85889f21141950bf9c52e57326fac12231380f86

Seems to work:
![image](https://user-images.githubusercontent.com/1086194/120784408-56c64780-c52c-11eb-9d76-5d7bee7b1edd.png)

**Comment by chrillep** [comment]
then i'm doing something wrong =)

**Comment by chrillep** [comment]
> Just updated all dependencies: [85889f2](https://github.com/i18next/react-i18next/commit/85889f21141950bf9c52e57326fac12231380f86)
> 
> Seems to work:
> ![image](https://user-images.githubusercontent.com/1086194/120784408-56c64780-c52c-11eb-9d76-5d7bee7b1edd.png)

then i'm doing something wrong =) . ill test the latest update

**Comment by chrillep** [comment]
the error was related to setting [webpack5](https://storybook.js.org/blog/storybook-for-webpack-5/)
```
  core: {
    builder: "webpack5",
  },
```

ill see if i can get around it thanks!

**Comment by chrillep** [comment]
ill close the issue and make a new one if i cant get webpack5 to work =)
