### ISSUE TITLE
Type instantiation is excessively deep and possibly infinite when using type out of json files

### ISSUE THREAD

**Issue by JCQuintas** [i18next/react-i18next#1327]
## 🐛 Bug Report

Trying to type the `Resources` interface as shown on the [react-i18next typescript documentation](https://react.i18next.com/latest/typescript) by using the types of a `json` file results in a `Type instantiation is excessively deep and possibly infinite` typescript error.

## To Reproduce

[CodeSandbox](https://codesandbox.io/s/react-i18next-type-excessively-deep-forked-huwlq?file=/src/App.tsx)

## Expected behavior

I expect `useTranslation` to be typed and not throw a type error

## Your Environment

- *runtime version*: i.e. node v14
- *i18next version*: i.e. 20.3.1
- *os*: Mac

**Comment by pedrodurek** [comment]
That's happening because your `package.json` (your ns1) file has an empty array, which fails to recursively infer the types. We can assume that people won't have empty arrays in their locale files, but I'll try to ignore those (ignore empty arrays when recursively inferring the types).

For now, your problem will be fixed if you add a value to your "keywords" key.

**Comment by JCQuintas** [comment]
My bad, the issue wasn't on this package it seems, but on `next-i18next` that wasn't properly exporting the types. Thanks for the reply :)

**Comment by SeinopSys** [comment]
I ran into this same error message, but for an unrelated reason. I thought I would be smart and import the JSON files as types:

```ts
import 'react-i18next';
import type commonNs from 'public/locales/en/common.json';

declare module 'react-i18next' {
  interface CustomTypeOptions {
    resources: {
      common: commonNs;
    };
  }
}
```

This setup caused the same TypeScript error mentioned in this issue's title. Changing it to the following (which matches the current documentation) made the error disappear:

```ts
import 'react-i18next';
import commonNs from 'public/locales/en/common.json';

declare module 'react-i18next' {
  interface CustomTypeOptions {
    resources: {
      common: typeof commonNs;
    };
  }
}
```

**Comment by topched** [comment]
@JCQuintas We are facing the same issue with next-i18next. What did you do to fix it?

**Comment by JCQuintas** [comment]
Hi @topched, tbh I don't remember exactly what we did. There are design decisions on `next-i18next` that annoy me quite a lot. It is possible the issue you see is due to multiple `react-i18next` or `i18next` in the project, since `next-i18next` uses its own bundled versions.

If that is the real issue, make sure you are only importing every function and component like `useTranslation` from `next-i18next`. 

If that doesn't fix the issue, you might be interested in trying out a lib I built for that. 

https://github.com/JCQuintas/ni18n

It uses a lot of the ideas from `next-i18next`, but I believe it is more flexible, and allows you to import from the libs directly.

**Comment by adrai** [comment]
> If that doesn't fix the issue, you might be interested in trying out a lib I built for that.
> 
> https://github.com/JCQuintas/ni18n
> 
> It uses a lot of the ideas from `next-i18next`, but I believe it is more flexible, and allows you to import from the libs directly.

@JCQuintas do you n18n to be listed here: want https://www.i18next.com/overview/supported-frameworks ?

**Comment by JCQuintas** [comment]
Hi @adrai, that would be nice, thank you :)

**Comment by adrai** [comment]
> Hi @adrai, that would be nice, thank you :)

![image](https://user-images.githubusercontent.com/1086194/134501281-e8174129-154f-4fce-81c7-4c787a2271b8.png)
