### ISSUE TITLE
Feature Proposal: Allow useTranslation hook to accept JSON objects with a namespace

### ISSUE THREAD

**Issue by st1906** [i18next/react-i18next#1330]
## 🚀 Feature Proposal

The useTranslation hook accepts the namespace as its first argument. For namespaces with json object, the useTranslation hook could correctly parse the ns:JSONObject string and return a wrapper t function that accepts desctructured json object key(s) as arguments.   

## Motivation

The motivation is dealing with fallback values. For example, let’s say we get a list of "names" from an API and these names are in English and can be changed and new values can be added, but we want to use them as keys (probably not the best candidates). We also deliver our translation as an JSON file to the UI. In case a name isn’t in our names.json file, we would like the fallback to be that name value. Let's imagine the json has a nested json object inside, so to get a value we would have to do something like `names.coolNames.myNameFromAPI`. To use the actual myNameFromAPI as a fallback value right now, we have to pass the keys in an array like this:

```
const {t: namesT} = useTranslation('names');
const name = namesT([`coolNames.${myNameFromApi}`, myNameFromApi]);
```
To me the way to handle the fallback in this case looks legit, but intuitively I thought we could pass also the json object inside the namespace to the useTranslation hook like `useTranslation('names:coolNames')` and have the t as `coolNamesT(myNameFromApi)`.

I am wondering does it make sense to have such flexibility and how feasible it is? Do the benefits of a bit cleaner fallback syntax outweigh the implementation cost  and has anyone been in a similar situation with fallbacks (maybe my use case is rare with an approach that is not ideally how to handle localization).

## Example
Apologies for the bad content examples
names.json
```
{
  "coolNames": {
    "John": "John"
  },
  "happyNames": {
    "Jane": "Jane"
  }
}
```

```
const {t: coolNames} = useTranslation('names:coolNames');
const {t: happyNames} = useTranslation('names:happyNames');

const myCoolName = getFromApi();
const myHappyName = getFromApi();

<div class="cool-name>{coolNames(myCoolName)}</div>
<div class="happy-name>{happyNames(myHappyName)}</div>
```

My first take on the internal implementation could be having a parser that detects the `:` in the namespace (ns:jsonObject) and returns t as myT = (key) => t(`${jsonObject}.${key}`). I'm not familiar with the details how everything works under the hood, so I am really interested if having this option makes sense and any thoughts around the implementation.
Thanks!

**Comment by jamuhl** [comment]
why not just `<div class="cool-name>{coolNames(`coolNames.${myCoolName}`)}</div>`

**Comment by st1906** [comment]
> why not just:
> 
> ```js
> <div class="cool-name>{t(`coolNames.${myCoolName}`)}</div>
> ```

@jamuhl Hi, so the goal is to display a "human friendly" fallback value in cases the myCoolName isn’t a key in the names namespace. In case myCoolName is not a valid key, the above will resolve to `coolNames.myCoolName` on the UI, while I'm aiming for just myCoolName to be displayed.
It can be done like this:
```
<div class="cool-name>{t([`coolNames.${myCoolName}`, myCoolName])}</div>
```
Maybe passing the fallback in the array is the best option, but wondering if it would make sense to extend the useTranslation hook (hence the open issue)

**Comment by jamuhl** [comment]
in that case using a defaultValue as fallback should be better than adding a key that will be a non-found fallback

**Comment by st1906** [comment]
Yep, somehow I missed that option in the docs and went straight to fallback keys. Thank you very much.
Does this proposal still make sense for any other use case you might think off? For the use case I mentioned not really, so I'll be happy to close it.

**Comment by jamuhl** [comment]
Let's close this for now...we can add this later if really needed.
