### ISSUE TITLE
TfunKey gives string

### ISSUE THREAD

**Issue by rwanito** [i18next/react-i18next#1331]
Hi !
I've just update the last version of r-i18next.
I edit my files to :
```javascript
import * as Localization from 'expo-localization';
import i18next from 'i18next';
import { initReactI18next } from 'react-i18next';
import { resources } from './translations';

export const defaultNS = 'common';

i18next.use(initReactI18next).init({
  lng: Localization.locale,
  fallbackLng: 'fr-FR',
  supportedLngs: ['fr-FR'],
  load: 'currentOnly',
  defaultNS,
  cleanCode: true,
  resources
});

export default i18next;
```

and 
```javascript
import { resources } from '~/libs/locales.lib/translations';

declare module 'react-i18next' {
  interface CustomTypeOptions {
    resources: typeof resources['fr-FR'];
  }
}

```

The t function is correctly typed.
But when I want to use TfuncKey, I get : 
```
No overload matches this call.
  Overload 1 of 2, '(key: "MY NS")[], options?: string | ... 1 more ... | undefined): string | ... 30 more ... | { ...; }', gave the following error.
    Argument of type 'string' is not assignable to parameter of type '"MY NS")[]'.
  Overload 2 of 2, '(key: "MY NS")[], defaultValue?: string | undefined, options?: string | ... 1 more ... | undefined): string | ... 30 more ... | { ...; }', gave the following error.
    Argument of type 'string' is not assignable to parameter of type '"MY NS")[]'.ts(2769)
```

For example, the use case is : 
```javascript

export interface HandledResponse extends SerializedError {
  /**
   * Code permettant de determiner la nature de la réponse.
   */
  code: Flag;
  /**
   * Nom à afficher en titre.
   */
  name: TFuncKey;
  /**
   * Message de la réponse, si besoin.
   */
  message?: TFuncKey;
  /**
   * Messages de la réponse mais en plusieurs exemplaires.
   */
  messages?: TFuncKey[];
}

t(notification.response.message) <- The error

```

Do you have any idea how to bypass this error ?

**Comment by adrai** [comment]
//cc @JCQuintas

**Comment by JCQuintas** [comment]
From what I could test based on your comment, this seems to be an issue regardless of the version. It happens due to having a typed `resources` but not `defaultNS` when you use a custom `defaultNS`

I suppose you can set your default namespace in the `CustomTypeOptions` as well, since you use a custom one. You can try the following on your `.d.ts`

```ts
import { resources } from '~/libs/locales.lib/translations';

declare module 'react-i18next' {
  interface CustomTypeOptions {
    defaultNS: 'common'; // or typeof defaultNS if you import it
    resources: typeof resources['fr-FR'];
  }
}
```
Or you can try setting the namespace of the `TFuncKey` like `TFuncKey<'your-namespace'>` inside the `HandledResponse`

If that doesn't work, do you mind setting up a [codesandbox](https://codesandbox.io) or a repository where we can test your issue?

**Comment by rwanito** [comment]
Hi !
Thanks for your reply !

How can I say all namespaces ?
Maybe a list ?

**Comment by pedrodurek** [comment]
This should work:
```ts
declare module 'react-i18next' {
  interface CustomTypeOptions {
    defaultNS: 'common'; // or typeof defaultNS if you import it
    resources: typeof resources['fr-FR'];
  }
  type TranslationKeys = TFuncKey<CustomTypeOptions['resources'][]>;
}
```

Put `TranslationKeys` inside the module declaration so you can import it from `react-i18next`, like this:
`import type {TranslationKeys} from 'react-i18next'` or `import {TranslationKeys} from 'react-i18next'`

**Comment by rwanito** [comment]
Hi !
Thank !

But, I've triied that and I get  : 
```javascript
Type '{ common: { greetings: { goodMorning: string; goodAfternoon: string; }; actions: { startTracking: string; stopTracking: string; }; }; 'dashboard.page': { pageName: string; subtitle_last_traject: string; ... 6 more ...; modal: { ...; }; }; ... 7 more ...; notifications: { ...; }; }[]' does not satisfy the constraint 'Namespace<"common" | "dashboard.page" | "form.validation" | "sign.page" | "profil.page" | "traject.page" | "welcome.page" | "home.page" | "feedback.page" | "notifications">'.
  Type '{ common: { greetings: { goodMorning: string; goodAfternoon: string; }; actions: { startTracking: string; stopTracking: string; }; }; 'dashboard.page': { pageName: string; subtitle_last_traject: string; ... 6 more ...; modal: { ...; }; }; ... 7 more ...; notifications: { ...; }; }[]' is not assignable to type '("common" | "dashboard.page" | "form.validation" | "sign.page" | "profil.page" | "traject.page" | "welcome.page" | "home.page" | "feedback.page" | "notifications")[]'.
    Type '{ common: { greetings: { goodMorning: string; goodAfternoon: string; }; actions: { startTracking: string; stopTracking: string; }; }; 'dashboard.page': { pageName: string; subtitle_last_traject: string; ... 6 more ...; modal: { ...; }; }; ... 7 more ...; notifications: { ...; }; }' is not assignable to type '"common" | "dashboard.page" | "form.validation" | "sign.page" | "profil.page" | "traject.page" | "welcome.page" | "home.page" | "feedback.page" | "notifications"'.
      Type '{ common: { greetings: { goodMorning: string; goodAfternoon: string; }; actions: { startTracking: string; stopTracking: string; }; }; 'dashboard.page': { pageName: string; subtitle_last_traject: string; ... 6 more ...; modal: { ...; }; }; ... 7 more ...; notifications: { ...; }; }' is not assignable to type '"notifications"'.ts(2344)
(property) CustomTypeOptions.resources: {
    common: {
        greetings: {
            goodMorning: string;
            goodAfternoon: string;
        };
        actions: {
            startTracking: string;
            stopTracking: string;
        };
    };
    'dashboard.page': {
        pageName: string;
        subtitle_last_traject: string;
        ... 6 more ...;
        modal: {
            ...;
        };
    };
    ... 7 more ...;
    notifications: {
        ...;
    };
}
```

Do you have any idea ?

Thanks !

**Comment by adrai** [comment]
> Hi !
> 
> Thank !
> 
> 
> 
> But, I've triied that and I get  : 
> 
> ```javascript
> 
> Type '{ common: { greetings: { goodMorning: string; goodAfternoon: string; }; actions: { startTracking: string; stopTracking: string; }; }; 'dashboard.page': { pageName: string; subtitle_last_traject: string; ... 6 more ...; modal: { ...; }; }; ... 7 more ...; notifications: { ...; }; }[]' does not satisfy the constraint 'Namespace<"common" | "dashboard.page" | "form.validation" | "sign.page" | "profil.page" | "traject.page" | "welcome.page" | "home.page" | "feedback.page" | "notifications">'.
> 
>   Type '{ common: { greetings: { goodMorning: string; goodAfternoon: string; }; actions: { startTracking: string; stopTracking: string; }; }; 'dashboard.page': { pageName: string; subtitle_last_traject: string; ... 6 more ...; modal: { ...; }; }; ... 7 more ...; notifications: { ...; }; }[]' is not assignable to type '("common" | "dashboard.page" | "form.validation" | "sign.page" | "profil.page" | "traject.page" | "welcome.page" | "home.page" | "feedback.page" | "notifications")[]'.
> 
>     Type '{ common: { greetings: { goodMorning: string; goodAfternoon: string; }; actions: { startTracking: string; stopTracking: string; }; }; 'dashboard.page': { pageName: string; subtitle_last_traject: string; ... 6 more ...; modal: { ...; }; }; ... 7 more ...; notifications: { ...; }; }' is not assignable to type '"common" | "dashboard.page" | "form.validation" | "sign.page" | "profil.page" | "traject.page" | "welcome.page" | "home.page" | "feedback.page" | "notifications"'.
> 
>       Type '{ common: { greetings: { goodMorning: string; goodAfternoon: string; }; actions: { startTracking: string; stopTracking: string; }; }; 'dashboard.page': { pageName: string; subtitle_last_traject: string; ... 6 more ...; modal: { ...; }; }; ... 7 more ...; notifications: { ...; }; }' is not assignable to type '"notifications"'.ts(2344)
> 
> (property) CustomTypeOptions.resources: {
> 
>     common: {
> 
>         greetings: {
> 
>             goodMorning: string;
> 
>             goodAfternoon: string;
> 
>         };
> 
>         actions: {
> 
>             startTracking: string;
> 
>             stopTracking: string;
> 
>         };
> 
>     };
> 
>     'dashboard.page': {
> 
>         pageName: string;
> 
>         subtitle_last_traject: string;
> 
>         ... 6 more ...;
> 
>         modal: {
> 
>             ...;
> 
>         };
> 
>     };
> 
>     ... 7 more ...;
> 
>     notifications: {
> 
>         ...;
> 
>     };
> 
> }
> 
> ```
> 
> 
> 
> Do you have any idea ?
> 
> 
> 
> Thanks !

It works in plain javascript, I have no clue about TypeScript

**Comment by rwanito** [comment]
Maybe the cause are my translation files ?

My i18n instance is set here : 
```javascript
import * as Localization from 'expo-localization';
import i18next from 'i18next';
import { initReactI18next } from 'react-i18next';
import { resources } from './translations';

export const defaultNS = 'common';

i18next.use(initReactI18next).init({
  lng: Localization.locale,
  fallbackLng: 'fr-FR',
  supportedLngs: ['fr-FR'],
  load: 'currentOnly',
  defaultNS,
  cleanCode: true,
  resources
});

export default i18next;
```
My resources constante is here : 

```javascript
import { fr } from './fr-FR';

export const resources = {
  'fr-FR': fr
};

```

and my fr constante : 
```javascript
import dashboardPage from './dashboard.page.json';
import formValidation from './form.validation.json';
import profilPage from './profil.page.json';
import trajectPage from './traject.page.json';
import welcomePage from './welcome.page.json';
import signPage from './sign.page.json';
import homePage from './home.page.json';
import notifications from './notifications.json';
import feedbackPage from './feedback.page.json';
import common from './common.json';

export const fr = {
  common,
  'dashboard.page': dashboardPage,
  'form.validation': formValidation,
  'sign.page': signPage,
  'profil.page': profilPage,
  'traject.page': trajectPage,
  'welcome.page': welcomePage,
  'home.page': homePage,
  'feedback.page': feedbackPage,
  notifications
};


```

And as example, common.json : 
```json
{
    "greetings": {
        "goodMorning": "Bonjour,",
        "goodAfternoon": "Bonsoir,"
    },
    "actions": {
        "startTracking": "Démarrer",
        "stopTracking": "Arrêter"
    }
}
```

Is my code is right ?
Maybe the error is here ?
