### ISSUE TITLE
React-native: Module AppRegistry is not a registered callable module (calling runApplication)

### ISSUE THREAD

**Issue by DoneDeal0** [i18next/react-i18next#1332]
## 🐛 Bug Report

When importing i18next in index.js in a React-Native app (no expo, just cli), the following error is thrown: 

```js
 ERROR  TypeError: undefined is not a function, js engine: hermes
 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native., js engine: hermes
```

## To Reproduce

index.js (I also tried to import the config file in App.tsx)
```js
import { AppRegistry } from "react-native";
import App from "./App";
import "./src/i18n"
import { name as appName } from "./app.json";

AppRegistry.registerComponent(appName, () => App);
```

The config file looks like this (I already used the same in a React.js app, it works fine):

```js
import i18n, { LanguageDetectorAsyncModule } from "i18next";
import { initReactI18next } from "react-i18next";
import { Platform, NativeModules } from "react-native";
import { AsyncStorage } from "react-native";
import en from "./en.json";
import fr from "./fr.json";

const languages = {
  EN: "en",
  FR: "fr",
};

const resources = {
  en: { translation: en },
  fr: { translation: fr },
};

const detectLocale = () => {
  const storedLocale = AsyncStorage.getItem("locale");
  if (storedLocale) {
    return storedLocale;
  }
  const mobileLocale =
    Platform.OS === "ios"
      ? NativeModules.SettingsManager.settings.AppleLocale ||
        NativeModules.SettingsManager.settings.AppleLanguages[0]
      : NativeModules.I18nManager.localeIdentifier;
  if (mobileLocale) {
    return mobileLocale;
  }
  return languages.EN;
};

const LanguageDetector = {
  type: "languageDetector" as LanguageDetectorAsyncModule["type"],
  async: false,
  init: () => {},
  detect: detectLocale,
  cacheUserLanguage: () => {},
};

export default i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: languages.EN,
    keySeparator: ".",
    whitelist: [languages.EN, languages.FR],
    interpolation: { escapeValue: false },
  });

```

I use the lib as such:
```js
import { useTranslation } from "react-i18next";

export default function Router() {
  const { t } = useTranslation();
  return (
    <Tab.Navigator
      initialRouteName={screen.home}
    >
      <Tab.Screen
        name={screen.home}
        component={Home}
        options={{ tabBarLabel: t("screen.home") }}
      />
    </Tab.Navigator>
  );
}

```

## Expected behavior

To be able to start the app without any error/crash. 

## Your Environment

- *runtime version*: node v15.11.0, 
- *i18next version*: "^20.3.1",
- *react-i18next version*: "^11.11.0",
- *os*: Mac

**Comment by adrai** [comment]
Currently I have no react-native environment...
It would be the best if you could investigate what is causing this...
Is this only happening with TypeScript? (cc: @pedrodurek)
Is this also happening on this example? https://github.com/i18next/react-i18next/tree/master/example/react-native (it may be it is a bit out of date)

**Comment by pedrodurek** [comment]
That's a little bit odd, that's not a typescript error, and the error is not explicit at all. Have you tried to import `import "./src/i18n"` in the `App.js` rather than the entry point?

**Comment by DoneDeal0** [comment]
Hi, 

@adrai : I don't know what's causing this. I've been asking the question os SO and otehr platform, without any success so far.  I've also tried to init i18next directly in app.tsx instead of importing a config file. It still crashes. 

@pedrodurek I already tried to import ./src/i18n from both idex.js and app.tsx . I have also tried to disable hermes engine. Nothing works.

**Comment by adrai** [comment]
@DoneDeal0 it would be nice if you could try with this example: https://github.com/i18next/react-i18next/tree/master/example/react-native
react-i18next is just plain javascript, so I don't think this gradle stuff is needed (at least it worked like that so far)

**Comment by DoneDeal0** [comment]
So I've been investigating the issue, the error actually came from AsyncStorage. I still can't retrieve a stored locale at the moment. This problem is thus not directly related to react-i18n, all my apologies. We can close this thread, or you can wait a little bit until I find the solution and share the solution here in. case anyone has the same issue. As you prefer. Thanks again for your help!

**Comment by CloudPower97** [comment]
I have the same exact problem.

@DoneDeal0 Have you managed to solve it?

**Comment by DoneDeal0** [comment]
No, I still can't retrieve the locale in asyncStorage. If you find the fix, please let me know.
