### ISSUE TITLE
Translation function fully type-safe not compatible with context

### ISSUE THREAD

**Issue by jer-sen** [i18next/react-i18next#1333]
## 🐛 Bug Report

A resource with context (`type_male`, `type_female`) is not allowed with fully TypeScript-safe use.

## To Reproduce

```js

{
      "type_male": "homme",
      "type_female": "femme"
}

t('type', { context: 'male' }); // TS error
```

## Expected behavior

No error.

## Your Environment

- i18next@20.3.1
- react-i18next@11.11.0

**Comment by adrai** [comment]
//cc @CJQuintas

**Comment by JCQuintas** [comment]
This is a limitation of the current type declaration, I can try something later today to see if it can be fixed.

For now you could work around it by using `t("type" as keyof typeof t, { context: "male" })`

**Comment by pedrodurek** [comment]
yup, that syntax it's not supported. I'd recommend using this approach instead:
```ts
t(`type_${context}` as const);
```

**Comment by adrai** [comment]
try with i18next v22.4.5

**Comment by adrai** [comment]
https://github.com/i18next/react-i18next/issues/1617
https://github.com/i18next/react-i18next/issues/1541

**Comment by adrai** [comment]
i18next v23.0.0 will probably not address that yet

**Comment by adrai** [comment]
handled in i18next v23.4.0 (https://github.com/i18next/i18next/pull/2007/files#diff-97e65d0ee521805ff4ac2d967b61062da8f5543569da4177ceeff689ce4463a3)
