### ISSUE TITLE
Preparing initialI18nStore on server side. (razzle ssr example)

### ISSUE THREAD

**Issue by Ibadichan** [i18next/react-i18next#1335]
https://github.com/i18next/react-i18next/tree/master/example/razzle-ssr

## 🚀 Feature Proposal

Update preparing of initialI18nStore variable in order to reduce final html document size.

## Motivation

For now the razzle ssr example uses this code to populate initialI18nStore variable.

```
const initialI18nStore = {};

req.i18n.languages.forEach(l => {
  initialI18nStore[l] = req.i18n.services.resourceStore.data[l];
});
```
Which will load all the translations into the initialI18nStore variable.
But what if we have a lot of namespace files with a lot of text content?
In this case, the size of the html document will increase as new translations are added.

## Example

Instead of loading all translations i suggest to get all used namespaces and load
the corresponding translations only, using i18next API.

```
const initialI18nStore = {};

const usedNamespaces = request.i18n.reportNamespaces.getUsedNamespaces();

request.i18n.languages.forEach((language) => {
  initialI18nStore[language] = {};

  usedNamespaces.forEach((namespace) => {
    initialI18nStore[language][namespace] = (
      request.i18n.services.resourceStore.data[language][namespace]
    );
  });
});
```

**Comment by adrai** [comment]
If this works for you, feel free to provide a PR to extend the example.

**Comment by Leskd** [comment]
is it work?

> https://github.com/i18next/react-i18next/tree/master/example/razzle-ssr
> 
> ## 🚀 Feature Proposal
> Update preparing of initialI18nStore variable in order to reduce final html document size.
> 
> ## Motivation
> For now the razzle ssr example uses this code to populate initialI18nStore variable.
> 
> ```
> const initialI18nStore = {};
> 
> req.i18n.languages.forEach(l => {
>   initialI18nStore[l] = req.i18n.services.resourceStore.data[l];
> });
> ```
> 
> Which will load all the translations into the initialI18nStore variable. But what if we have a lot of namespace files with a lot of text content? In this case, the size of the html document will increase as new translations are added.
> 
> ## Example
> Instead of loading all translations i suggest to get all used namespaces and load the corresponding translations only, using i18next API.
> 
> ```
> const initialI18nStore = {};
> 
> const usedNamespaces = request.i18n.reportNamespaces.getUsedNamespaces();
> 
> request.i18n.languages.forEach((language) => {
>   initialI18nStore[language] = {};
> 
>   usedNamespaces.forEach((namespace) => {
>     initialI18nStore[language][namespace] = (
>       request.i18n.services.resourceStore.data[language][namespace]
>     );
>   });
> });
> ```


I receive a error: 
`TypeError: Cannot read property 'getUsedNamespaces' of undefined`

**Comment by adrai** [comment]
@Leskd just tried the razzle-ssr example, it still seems to work.
If you have an issue, create a reproducible example and open a new gh issue.

**Comment by Leskd** [comment]
@adrai thank you for your quick response.
I checked, I just set up the config, but don't use the function in components or pages. after I write this
`const [ t ] = useTranslation('translations');` in page, it's works now. thank you again.
