### ISSUE TITLE
Passing in i18n not working

### ISSUE THREAD

**Issue by jamiek-acl** [i18next/react-i18next#1342]
Hello,

I am trying to use `<Trans>` however nothing is rendering as seen in this example: https://codesandbox.io/s/react-i18next-trans-component-example-forked-h8c5m?file=/src/examplethree.js

There is a console warning, but I am not sure if it is related:
```
react-i18next:: You will need pass in an i18next instance by using i18nextReactModule 
```
I won't be using i18nextReactModule as I am using my own instance of i18n.

I am currently passing in `t` to `<Trans>` and when i try to also pass in `i18n` I get an error:
```
Cannot read property 'interpolator' of undefined
```

Any help is appreciated.

**Comment by adrai** [comment]
Somewhere you need to pass initReactI18next to i18next.use()

**Comment by jamiek-acl** [comment]
On line 48 of examplethree.js you can see I wrap my component with a component called `<L10n>`, which [initializes i18next here](https://github.com/acl-services/paprika/blob/master/packages/L10n/src/i18n.js) and [puts it into context](https://github.com/acl-services/paprika/blob/master/packages/L10n/src/L10n.js#L20).  It is then extracted on line 12 of examplethree.js with `useI18n()`.

**Comment by adrai** [comment]
And where do you call `i18next.use()` like: https://github.com/i18next/react-i18next/blob/master/example/react/src/i18n.js#L14 ?

**Comment by jamiek-acl** [comment]
I don't.; I'm not really sure what that part is doing. I thought I could tell `Trans` which I18n instance I am using by passing it in.

**Comment by jamuhl** [comment]
https://github.com/acl-services/paprika/blob/master/packages/L10n/src/L10n.js#L20 -> https://github.com/acl-services/paprika/blob/master/packages/L10n/src/useI18n.js#L24 

```js
  return {
    locale,
    t: _i18n.getFixedT(locale),
  };
  ```
  
  that is not an instance -> why you reinvent every thing i18next already has buildin?!?

**Comment by jamiek-acl** [comment]
> that is not an instance 

Oh yeah you are right, that is not an i18n instance that is returned.  If I can return it and pass it into `<Trans>`, will that work and I won't need to use `i18next.use()`?

> why you reinvent every thing i18next already has buildin?

Can you elaborate, please?

**Comment by jamuhl** [comment]
a) if you do not need SSR and got no need for different sub-instance to translate (eg. shared UI module) there is no need for using context

b) if a does apply i18next already has a context provider built in

c) following the examples provided would reduce your codes complexity - no need to create instances (the one singleton is ok)

**Comment by jamiek-acl** [comment]
Ok we may need to look at how we use i18next, our component is from 3 years ago so may be out-dated.
