### ISSUE TITLE
Trans component „closes“ interpolation values in `<>` when `escapeValue: false` is set

### ISSUE THREAD

**Issue by ckruse** [i18next/react-i18next#1344]
## 🐛 Bug Report

When interpolating a value containing something remotely similar to an HTML tag `Trans` „closes“ that tag. For example:

~~~js
const email = "Foo <bar@example.com>";
return <Trans parent="div"><span>email:</span> {{email}}</Trans>;
~~~

This generates this output:

~~~html
<div><span>email:</span> Foo &lt;bar@example.com&gt;</div>
~~~

It doesn't matter if I enable or disable `transSupportBasicHtmlNodes`.

## To Reproduce

- https://codesandbox.io/s/peaceful-sound-2xmrz
- https://codesandbox.io/s/purple-wood-0cyef

## Expected behavior

The interpolation value w/o any changes should be displayed

## Your Environment

- *runtime version*: Browser
- *i18next version*: i18next@20.3.3, react-i18next@11.11.2
- *os*: Mac, Linux

**Comment by adrai** [comment]
This is probably because of html-parse-stringify...
Open to accept a PR: https://github.com/i18next/react-i18next/blob/master/src/Trans.js#L138

**Comment by ckruse** [comment]
Ok, I understand why interpolation happens before parsing, but to me it seems that the only possible fix to this problem is to do it the other way round. Do you agree or am I wrong?

**Comment by adrai** [comment]
Currently afk, so I did not investigate this issue.
Feel free to suggest a fix.
It will then be reviewed by me or @jamuhl

**Comment by jamuhl** [comment]
just a reminder for the review the reason why we added interpolation upfront: https://github.com/i18next/react-i18next/blame/v9.x.x/src/Trans.js#L61

with a first look at the PR this seems to still work

**Comment by ckruse** [comment]
Fixed by PR

**Comment by adrai** [comment]
releasd in v11.11.3
