### ISSUE TITLE
Something went confused

### ISSUE THREAD

**Issue by wqcstrong** [i18next/react-i18next#1346]
## 🐛 Bug Report

Something went wrong when I toke a try in this [official tuotrial](https://dev.to/adrai/how-to-properly-internationalize-a-react-application-using-i18next-3hdb). 
The only difference is I used chinese in my example and there used deutsch in the tuotrial. And the wrong content is the interpolation invalid if I use `zh` as  key, but everything be ok if I try to change the `zh` to `de`(I leave the comment in the example).

## To Reproduce

A [codepen](https://codepen.io/WQC/pen/eYWRyVm?editors=1010) example, FYI.

## Expected behavior

Fix the problem

## Your Environment

See the above example

**Comment by adrai** [comment]
zh has different plural rules: https://www.i18next.com/translation-function/plurals
So you need a different key for zh.
try to change counter_plural to `"counter_0": "已经调整语言 {{count}} 次"`

**Comment by wqcstrong** [comment]
I spent an afternoon...

OK, Thx!

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏
