### ISSUE TITLE
Passing multiple namespaces to useTranslation() appears to not do anything

### ISSUE THREAD

**Issue by QuaternionMark** [i18next/react-i18next#1347]
## 🐛 Bug Report

Given two namespaces `ns1` and `ns2` that are passed to `useTranslation()`, it appears that any additional namespaces passed after the first one are redundant/ignored.

With the resource:
```
ns1: {
  test1: "translation from ns1"
},
ns2: {
  test2: "translation from ns2"
}
```

Calling `useTranslation(["ns1", "ns2"])` and then `t("test2")` will not resolve any translations from the second namespace without explicitly defining that namespace, `t("ns2:test2")`. This is equivalent to just writing `useTranslation("ns1")`.

## To Reproduce

https://codesandbox.io/s/react-i18next-forked-wkm93?file=/src/app.js

```js
export default function App() {
  const { t } = useTranslation(["ns1", "ns2"]);

  return (
    <div className="App">
      <p>
        Using <code>["ns1", "ns2"]</code>:
      </p>
      {t("test1")} // gets the translation from ns1
      {t("test2")} // does not get the translation from ns1
    </div>
  );
}
```

## Expected behavior

`useTranslation()` checks through all namespaces passed to see if the given translation key is found in any of them.

Either that or if this is an intended feature, `useTranslation()` should just not accept an array of namespaces as the first argument.

## Your Environment

- *runtime version*: node v14.17.3
- *i18next version*: 11.11.3
- *os*: Windows

**Comment by adrai** [comment]
Yes, this is expected.

**Comment by adrai** [comment]
To load the namespaces... i.e. when using i18next-http-backend or similar

**Comment by QuaternionMark** [comment]
So if I'm not using some form of lazy/backend loading, is initializing the hook with multiple namespaces redundant in my example?

**Comment by adrai** [comment]
If not using any i18next backend, yes

**Comment by QuaternionMark** [comment]
Alright makes sense, thanks for the clarification.

**Comment by jamuhl** [comment]
you can try https://github.com/i18next/react-i18next/blob/master/src/context.js#L6 `i18nOptions.nsMode === 'fallback'`

**Comment by dsonet** [comment]
https://react.i18next.com/latest/usetranslation-hook#loading-namespaces
```javascript
// load multiple namespaces
// the t function will be set to first namespace as default
const { t, i18n } = useTranslation(['ns1', 'ns2', 'ns3']);
t('key'); // will be looked up from namespace ns1
t('ns2:key'); // will be looked up from namespace ns2
```
But when I use t without ns1, TypeScript throw error, says No overload matches this call. When I dig into that error, it shows all the keys with namespace., even the ns1. 

versions I use
```
"i18next": "^20.3.5",
"i18next-http-backend": "^1.3.0",
"react-i18next": "^11.11.4",
"typescript": "^4.3.5"
```
I tried on older version, also doesn't work as expected. Any thoughts? Thanks

**Comment by adrai** [comment]
> But when I use t without ns1, TypeScript throw error, says No overload matches this call

If it's only a TypeScript issue, maybe @pedrodurek can help?

**Comment by pedrodurek** [comment]
Hey @dsonet, for a matter of compilation time, the type inference was designed to work by only adding the namespace as prefix, here is some explanation https://github.com/i18next/react-i18next/issues/1277#issuecomment-800455785
```tsx
const { t, i18n } = useTranslation(['ns1', 'ns2', 'ns3']);
t('ns1:key'); // will be looked up from namespace ns1
t('ns2:key'); // will be looked up from namespace ns2
```
