### ISSUE TITLE
withTranslation HOC doesn't pass forward the ref when using the withRef option.

### ISSUE THREAD

**Issue by cricrio** [i18next/react-i18next#1348]
## 🐛 Bug Report

The withTranslation HOC doesn't pass forward the ref to the children when using the withRef option.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/16168447/126305382-8f972a82-6f88-487d-8ed2-d70dd4902917.png">

## To Reproduce

```js
const Input = withTranslation(null, { withRef: true })(({ ref }) => <input ref={ref} />);
const App = () => { 
      const ref = useRef();
      return <Input ref={ref} />
}
```

## Your Environment

- *i18next version*: i.e. 11.11.3

**Comment by cricrio** [comment]
I think the issue is coming from this line. https://github.com/i18next/react-i18next/blob/7cfab9746b3ccc6f833cd9c892e7c3c804944a5e/src/withTranslation.js#L17
`ref` is not a props so it cannot pass down to the children this way.

**Comment by jamuhl** [comment]
not sure what the test https://github.com/i18next/react-i18next/blob/master/test/withTranslation.spec.js#L34 is testing...

**Comment by cricrio** [comment]
The way react handle the ref may have change in 2 years. The ref is not a props so it can't be pass down as the other props.
https://reactjs.org/docs/forwarding-refs.html#forwarding-refs-in-higher-order-components

**Comment by jamuhl** [comment]
You must forward the ref in your own functional component like

```js
const Input = withTranslation(null, { withRef: true })(
  React.forwardRef(function (props, ref) {
    return <input ref={ref} onClick={() => console.warn(ref)} />;
  })
);
```

codesandbox: https://codesandbox.io/s/react-i18next-forked-hzqgh

full code:

```js
import React, { useRef } from "react";

import { withTranslation } from "react-i18next";

const Input = withTranslation(null, { withRef: true })(
  React.forwardRef(function (props, ref) {
    return <input ref={ref} onClick={() => console.warn(ref)} />;
  })
);

const App = () => {
  const ref = useRef();
  return <Input ref={ref} />;
};

export default App;
```

**Comment by cricrio** [comment]
Thanks! It's working like this.
I'm closing this issue.
