### ISSUE TITLE
The I18n instance is initialized twice when using SSR (razzle-ssr for example)

### ISSUE THREAD

**Issue by Ibadichan** [i18next/react-i18next#1350]
## 🐛 Bug Report

After configuring the SSR using the razzle-ssr, the application does not work correctly, the i18n instance is initialized twice.

## To Reproduce
Try to build and start the razzle-ssr application, then open dev console to see the i18next warnings.

## Expected behavior
The console does not contain warnings.

## Your Environment
- *runtime version*: node v12.20.0
- *i18next version*:  20.3.2
- *react-i18next version*:  11.11.0

![Снимок экрана 2021-07-23 в 19 09 58](https://user-images.githubusercontent.com/26125121/126812420-6a7f2127-cafc-4835-bdb3-3d8859ee778c.png)

**Comment by adrai** [comment]
Dis you already had a chance to investigate why this happens? It may be the example is not up-to-date...

**Comment by adrai** [comment]
@jamuhl to prevent the warning, we might add this `!this.initializedStoreOnce` check here: https://github.com/i18next/i18next/blob/master/src/i18next.js#L158

`if (this.isInitialized && !this.initializedStoreOnce) this.logger.warn('init: i18next is already initialized. You should call init just once!');`

?

**Comment by jamuhl** [comment]
It's a false positive. useSSR sets initialized true (to enable render) while i18next is still initialized...guess same happens in next-i18next

adding `!this.initializedStoreOnce` will work

**Comment by jamuhl** [comment]
using i18next@20.3.5 should omit this warning

**Comment by Ibadichan** [comment]
But why is the 'languageChanged' event still triggered twice (react renders page two times.)?

**Comment by jamuhl** [comment]
I'm not a razzle user and did not create the sample -> but my guess is that the language detector is not needed in the browser -> as language gets set from server by passing initialLanguage to useSSR...
