### ISSUE TITLE
Using translation with user input makes it possible to recursively print passed variables

### ISSUE THREAD

**Issue by dlavrenuek** [i18next/react-i18next#1352]
## 🐛 Bug Report

It is possible to use the `{{ variable }}` syntax in variables passed to translation (in both, the `t` function and `Trans` component) to inject other passed variables' data. This can be also used to recursively print (up to a limit) the same variable's content to the screen. Using translation with user input coming from a database or an URL malformed this way can lead to the browser being unresponsible.

## To Reproduce

1. Use translation with a passed variable.
2. Use curly `{{ }}` syntax in this variable to print the same variable's content

```javascript
const test = 'This is a test {{ test }}';
const translatedRecursively = t(test, { test });
```

It looks like only the variables that are passed to this translation context can be used, so it should not be possible to access other data.

### Example:
Visit [codesandbox](https://codesandbox.io/s/mutable-rgb-oh1ez) and enter `Some {{ text }}` in the input field.

## Expected behavior

It should not be possible to inject variables in other variables. Passed data should be printed as plain text

## Your Environment

- *runtime version*: node v14, latest Chrome, Safari, Firefox
- *i18next version*: i.e. 20.3.5
- *react-i18next version*: i.e. 11.11.4
- *os*: Mac

**Comment by adrai** [comment]
Part of this is intended (feature not a bug) 😉
But feel free to provide a PR to optimize this.

**Comment by adrai** [comment]
btw: there's also the `skipOnVariables` option: https://www.i18next.com/translation-function/interpolation#all-interpolation-options

![image](https://user-images.githubusercontent.com/1086194/128017967-71f4f651-33e8-4cf1-b338-aea42c5b9561.png)

**Comment by dlavrenuek** [comment]
Does it make sense to make `skipOnVariables=true` per default to make the usage safe with default configuration? When someone needs this feature, they can turn it on knowing it's drawbacks.

**Comment by adrai** [comment]
This is a major breaking... some time ago we decided to not change the default.

**Comment by igorsantos07** [comment]
Maybe add documentation notes stating this behavior and the drawbacks, at least? Still suboptimal, but BC is BC, so at least there's some warning for those who actually read the docs.
