### ISSUE TITLE
Trans doesn't call parseMissingKeyHandler

### ISSUE THREAD

**Issue by igorsantos07** [i18next/react-i18next#1354]
## 🐛 Bug Report

Common `t()` calls with missing keys go through `parseMissingKeyHandler` if that's defined, but Trans doesn't, what feels like inconsistent/unexpected behavior.

## To Reproduce

I created a single [sandbox](https://codesandbox.io/s/thirsty-dew-f8z8v) for multiple issues I'm reporting, so it's a bit bigger than expected, sorry :)

## Expected behavior

Trans should also go through `parseMissingKeyHandler`? Or should it go somewhere else? I tried the `missingInterpolationHandler`, to no avail as well.

## Your Environment

- *runtime version*: React 17, Chrome 91
- *i18next version*: 20.3.5 (installed last week?)
- *react-i18next version*: 11.11.4
- *os*: Linux

**Comment by adrai** [comment]
I assume this is because <Trans> injests a defaultValue in [here](https://github.com/i18next/i18next/blob/master/src/Translator.js#L187) so `usedKey` is probably `false` [here](https://github.com/i18next/i18next/blob/master/src/Translator.js#L273).

It may be this is intentional @jamuhl?

**Comment by jamuhl** [comment]
Never requested by devs to have that option -> so it's not added. We add features needed not just to be consistent with other calls -> Trans is a completely different beast (so there is no need to compare it to the API call of a simple t call).

So, yes...can be added - if someone needs it...but I won't add lines just to have them...save the bytes

**Comment by adrai** [comment]
fyi: seems it is not directly because of Trans, but because of the defaultValue usage...
i.e. `i18n.t('keyWithDefault', 'some default')`

**Comment by jamuhl** [comment]
@adrai lgtm

**Comment by adrai** [comment]
@igorsantos07 will be fixed in the next i18next version: https://github.com/i18next/i18next/commit/da47faa104ebbb673a34fd298ef979646744c42e

**Comment by kg-currenxie** [comment]
Hope its OK to borrow this thread (if not I can make a new issue)

We have a case like this
```
<Text text={t('.placeholder', { defaultValue: '' })} />
```

We have a generated form, where translation might, or might not be defined. So we'd like to just print nothing.

This commit/release (20.4.0) changes this behavior, and it will now look for the key `''`.

How can i fall back to a string, and not a translation?
(We don't want to define translations with empty string values)

**Comment by adrai** [comment]
@kg-currenxie Please create a reproducible example and open a new issue.
