### ISSUE TITLE
Override language isn't working until language is loaded fully

### ISSUE THREAD

**Issue by mikecousins** [i18next/react-i18next#1358]
## 🐛 Bug Report

If you override a translation it doesn't work until that language is loaded by doing an actual language change to that language.

## To Reproduce

https://codesandbox.io/s/brave-lake-w1is5?file=/src/App.tsx

```js
{language === 'en' ? <>{t('global:French', { lng: 'fr' })}</> : <>{t('global:English', { lng: 'en' })}</>}
```

You'll see on first load the string shows `French` (incorrect), when clicked it switches to `English` (correct), then when clicked again it switches to `Francais` (correct).

## Expected behavior

The string should either be Francais or English.

## Your Environment

- *runtime version*: Latest everything, Chrome, Node 16
- *i18next version*: 20.3.5
- *os*: Windows

**Comment by jamuhl** [comment]
expected...accessing the synchronous function `t` to return a string there is no way to load asynchronous data and to delay the return of the string (you wouldn't be able to use an async `t` function returning your translations in your UI code)

If you access another translation make sure it is loaded by calling `changeLanguage` first or by manually adding the resources (depending on using a backend or not)

**Comment by mikecousins** [comment]
If you call change language then the whole page will flicker in the wrong language. How do you go about manually adding the resources? I'm using http backend.

**Comment by jamuhl** [comment]
using http backend you can call https://www.i18next.com/overview/api#loadlanguages
