### ISSUE TITLE
DX: hook function returning translations with given key prefix

### ISSUE THREAD

**Issue by mdjastrzebski** [i18next/react-i18next#1359]
## 🚀 Feature Proposal

`const { t, tRoot} = useTranslationWithPrefix(keyPrefix: string)`

Usage:
`t('userModule.homeScreen.settingsSection.entry')` -> `t('entry')`

Hook function that provides `t` function scoped to given translation key prefix, so that usage of translation strings with repeating prefix is simplified. Hook additionally returns `tRoot` function which is regular, un-scoped `t` function for cases  when component needs to use some general purpose string.

## Motivation

In React projects I've worked on, we've repeatedly found this kind of function useful, as given component usually uses the same translation key prefix, which occasionally tends to get quite long. This function improves the developer experience by reducing copy-pasting of repeating key prefixes and reduces effect of spelling mistakes in long keys, that may be hard to spot.

Alternatives achieving the same goal:
- key prefix could be passed as an option to regular `useTranslation` hook.
- function that wraps regular `t` function and returns a prefixed version of it.

## Example

```
const { t, tRoot} = useTranslationWithPrefix('user.accountSettings.changePassword')

// Later
<h1>{t('title')}</h1>
<label>{t('label.newPassword')}</label>
<label>{t('label.repeatPassword')}</label>
<button>{tRoot('common.ok')}</button>

```

instead of

```
const { t } = useTranslation()

// Later
<h1>{t('user.acoountSettings.changePasaword.title')}</h1>
<label>{t('user.accountSetinngs.changePassword.label.newPassword')}</label>
<label>{t('user.acconutSettings.changePassword.lable.repeatPassword')}</label>
<button>{t('common.ok')}</button>
```

I'm looking for your feedback, whether you consider this a worthy addition to `react-i18next` API or whether you can already achieve this is some other way.

**Comment by adrai** [comment]
Personally, I never had such a need.

But if this is something the community would like to use, I would suggest to solve it with some extra options for the `i18n.getFixed` function...

**Comment by jamuhl** [comment]
@mdjastrzebski do you like to provide a PR? should be very simple by appending a prefix passed in options to key here: https://github.com/i18next/i18next/blob/master/src/i18next.js#L325

**Comment by mdjastrzebski** [comment]
I am wondering if others find this feature any useful, like I did.

@jamuhl do you think it's worth adding to i18next API? If yes, then I would try submit a PR upcoming week.

**Comment by jamuhl** [comment]
I think yes - and should not add too much complexity as it can be added with a few lines in the mentioned function

**Comment by mdjastrzebski** [comment]
@jamuhl, @adrai  I am looking for some guidance about the API we want to achieve with this PR.

You both mentioned changing `i18n.getFixedT` in `i18next` package. If I understand your suggestion correctly this would result in following API usage:
```
const TRANSLATION_PREFIX = 'user.accountSettings.changePassword'
const { t } = useTranslation();
const title = t('title', { keyPrefix: TRANSLATION_PREFIX });
```
Is that what you are suggesting?

My intention would rather be something along the lines of:
```
const { t } = useTranslation({ keyPrefix: 'user.accountSettings.changePassword' });
const title = t('title');
```

so that provided key prefix is automatically applied to `t` function and developer just passes the relevant suffix.

Wdyt?

**Comment by adrai** [comment]
no... it would look like this:

```js
const { i18n } = useTranslation();
const t = i18n.getFixedT(null, null, 'user.accountSettings.changePassword')
// or
// const t = i18n.getFixedT({ keyPrefix: 'user.accountSettings.changePassword' })
const title = t('title');
```

**Comment by jamuhl** [comment]
or `const { t } = useTranslation(null, { keyPrefix: 'user.accountSettings.changePassword' })`

you will have to pass that option here to getFixedT https://github.com/i18next/react-i18next/blob/master/src/useTranslation.js#L43

**Comment by mdjastrzebski** [comment]
@jamuhl , @adrai thank you for your help.

I've submitted PR with `getFixedT` change to i18next: https://github.com/i18next/i18next/pull/1644

When that get's merged I can work on updating `useTranslation` hook in this repo.

**Comment by mdjastrzebski** [comment]
Thanks for review & merge @adrai . I'll submit PRs for react hook and docs update soon

**Comment by adrai** [comment]
@mdjastrzebski I already tried to document it here: https://www.i18next.com/overview/api#getfixedt
![image](https://user-images.githubusercontent.com/1086194/132502876-905cc984-a984-42ea-a0a0-cfbaf55f20ae.png)

**Comment by mdjastrzebski** [comment]
@adrai the docs looks good 👍🏻

**Comment by mdjastrzebski** [comment]
Added PR for updating `useTranslation` hook in React i18next package #1371

**Comment by minlare** [comment]
So in your original example @mdjastrzebski we can now go:

```
const { t, i18n: { t: tRoot }} = useTranslation('translation', { keyPrefix: 'very.deeply.nested' });
const scopedText = t('key');
const rootText = tRoot('key');
```

**Comment by tibistibi** [comment]
nope. this does not work:

    const { t } = useTranslation('nl', { keyPrefix: 'TrainTripTable' });
    
    will give me the key as translatione: TrainTripTable.column1
    
    this does translate:
    
        const { i18n } = useTranslation();
    const t = i18n.getFixedT(null, null, 'TrainTripTable');

**Comment by adrai** [comment]
> nope. this does not work:
> 
> 
> 
>     const { t } = useTranslation('nl', { keyPrefix: 'TrainTripTable' });
> 
>     
> 
>     will give me the key as translatione: TrainTripTable.column1
> 
>     
> 
>     this does translate:
> 
>     
> 
>         const { i18n } = useTranslation();
> 
>     const t = i18n.getFixedT(null, null, 'TrainTripTable');

seems to work as expected: https://github.com/i18next/react-i18next/blob/e6cb106a134ddc1e21c5cb69fedbab466f4b9223/test/useTranslation.spec.js#L121

@tibistibi if you think there is an issue, please provide a reproducible example codesandbox or similar

**Comment by Gu7z** [comment]
@adrai can you help me spot the error on this sandbox? [Link to sandbox](https://codesandbox.io/s/great-heyrovsky-3g6vzr)
