### ISSUE TITLE
After deploy to EC2, language json file not injecting

### ISSUE THREAD

**Issue by sjb3** [i18next/react-i18next#1360]
After building react app with i18next, it worked perfectly fine in local but after deploying it on AWS EC2, the language file(seems like) not injecting to the placeholder {t('placeholder')}.

I've been googling but not finding any solutions yet.
Is it known issue or solutions?

Please help!

BTW, the locales/country/translation.json files located inside the public folder and fetching those files using i18next-http-backend

## Your Environment

- *runtime version*: node v14
- *i18next version*: 20.3.5
- *os*: Mac
- *react ver*: 17.0.1
- *react-dom*: 17.0.1
- *react-router-dom*: 5.2.1

**Comment by sjb3** [comment]
Forgot, AWS EC2 runtime version: node v12

**Comment by adrai** [comment]
Sorry, can't help that much...
Set the debug flag to true: `i18next.init({ debug: true })` and check the developer console...
I suspect your translation json files are not accessible... So you should also see some failed http requests in the network tab...

some similar issues:
https://github.com/i18next/i18next-http-backend/issues/20
https://github.com/i18next/i18next-http-backend/issues/34
https://github.com/i18next/i18next-http-backend/issues/30
https://github.com/i18next/i18next-http-backend/issues/63

**Comment by sjb3** [comment]
Thanx @adrai 

Right my translation file is not being found when I deployed

![image](https://user-images.githubusercontent.com/14283946/129778680-8e1934c8-86a2-42b9-8671-a1b6a0643a46.png)

and my code in i18n.js is:

  .init({
    supportedLngs: ['AUE', 'GEA', 'CZE'],
    debug: true,
    fallbackLng: 'AUE',
    detection: {
      // order and from where user language should be detected
      order: ['path', 'cookie', 'htmlTag', 'localStorage', 'subdomain'],
      caches: ['cookie']
    },
    backend: {
       loadPath: '/locales/{{lng}}/translation.json',
    }

**Comment by adrai** [comment]
Make sure the json file is correctly served on your configured path...

http://yourIPorDomain/locales/AUE/translation.json

**Comment by adrai** [comment]
This article may help to understand/investigate it: https://www.locize.com/blog/i18next-translations-not-loaded
