### ISSUE TITLE
Cannot find namespace 'i18next'

### ISSUE THREAD

**Issue by JuhG** [i18next/react-i18next#1361]
## 🐛 Bug Report

Using version 9.0.10 typescript is complaining, that the function t is not typed. We're using the type WithNamespaces, but for some reason it didn't contain the types coming from i18next. Checking the type file, it looks like this:

![Screenshot 2021-08-26 at 20 03 06](https://user-images.githubusercontent.com/10765158/131014253-2f3fc363-ee90-437a-8aa4-ae2ccfdcf147.png)

Cannot find namespace 'i18next' - somehow importing the types is not working.

Changing
`import i18next from 'i18next';`
to
`import * as i18next from 'i18next';`
seem to resolve it.

Sorry if this has already come up, but I couldn't find it.

## Your Environment

- *runtime version*: node 12.22.3
- *i18next version*: 20.4.0
- *os*: Mac

**Comment by pedrodurek** [comment]
I was on vacation 😅. @adrai I didn't get your question, could you clarify a little bit more?

**Comment by adrai** [comment]
Welcome back @pedrodurek 😉. Do you remember, some time ago we discussed if there was a possibility to have the types defined each in the appropriate module, so i18next would not need to be updated im case a TypeScript change in the react-i18next interface is done.
I think it was here: https://github.com/i18next/i18next/pull/1626#issuecomment-876532250

**Comment by pedrodurek** [comment]
As answered on the other issue, build-in types are always preferable. I've already faced some issues with external types and type augmentation, where the internal type definitions were being ignored in favour of the external library.

**Comment by pedrodurek** [comment]
Hey @JuhG, let me know if the issue was fixed after updating the libraries
