### ISSUE TITLE
i18next doesn't translate in nested route pages

### ISSUE THREAD

**Issue by RikhsimovSunnatilla** [i18next/react-i18next#1363]
## 🐛 Bug Report

react-i18next doesn't translate in nested route pages, for example when a window location has only one route, it translates normally, but when it has nested route, for example "/myroute/second", translation crashes and only keys are visible

## Your Environment

- *runtime version*: node v12.18.0, browser - Chrome
- *i18next version*: 20.3.5
- *os*: Windows
- useTranslation hook

**Comment by jamuhl** [comment]
do you have a load path that is relative? set debug: true on init and check your console.log output for issues

**Comment by RikhsimovSunnatilla** [comment]
> do you have a load path that is relative? set debug: true on init and check your console.log output for issues

I did as you said and get following message in console

> i18next::backendConnector: loading namespace jobSearch for language en failed failed parsing locales/en/jobSearch.json to json

**Comment by adrai** [comment]
Here you might also find similar cases: https://github.com/i18next/react-i18next/issues/1360#issuecomment-900421616

**Comment by RikhsimovSunnatilla** [comment]
Okay I will try, thank you very much!

**Comment by RikhsimovSunnatilla** [comment]
> Check the http request in the developer console... I suspect the path is wrong or the returned json data is not parsable

I checked the network tab in the devtools and saw that the following message is coming from the json file as a data:

> You need to enable JavaScript to run this app.

**Comment by adrai** [comment]
> > Check the http request in the developer console... I suspect the path is wrong or the returned json data is not parsable
> 
> I checked the network tab in the devtools and saw that the following message is coming from the json file as a data:
> 
> > You need to enable JavaScript to run this app.

Ok, then check your server...
We can't help more than this anyway...
