### ISSUE TITLE
Hi! I have issue about i18next, I have an array list and I want to translate lements to different languages with the help of i18next library of react. Yet when I wrote and run code it works well at first later it does not work. Here my code t("text", { returnObjects: true }).map((item,  country_code ) =>(<li key={country_code}>                              <a href="#">{item}</a>             </li>). And my error is t(...).map is not function. I could not solve this. Can you help me

### ISSUE THREAD

**Issue by baxromxojasultonxojayev** [i18next/react-i18next#1364]
## To Reproduce

A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

```js
// Paste your code here
```

## Expected behavior

```js
// Paste the expected results here
```

## Your Environment

- *runtime version*: i.e. node v14, deno, browser xy
- *i18next version*: i.e. 19.5.3
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by baxromxojasultonxojayev** [comment]
,

**Comment by jamuhl** [comment]
Please provide a reproducible example on codesandbox

**Comment by baxromxojasultonxojayev** [comment]
> Please provide a reproducible example on codesandbox

I have following code in the App.js
const App = () => {
  const currentLangCode = cookie.get("i18next") || "en";
  const currentLang = lang.find((l) => l.code === currentLangCode);
  const [ t ] = useTranslation();

  useEffect(() => {
    document.body.dir = currentLang.dir;
  }, [currentLang]);

  return (
    <>
      <div className="container">
        <ul className="left-side">
          {lang.map(({ code, name, country_code }) => (
            <li key={country_code}>
              <button
                onClick={() => i18next.changeLanguage(code)}
                disabled={code === currentLangCode}
              >
                {name}
              </button>
            </li>
          ))}
        </ul>
        <ul className="right-side">
          {t("text", { returnObjects: true }).map((text, country_code) => (
            <li key={country_code}>
              <a href="#">{text}</a>
            </li>
          ))}
        </ul>
      </div>
      <div>
        <h1>{t("app_titlee")}</h1>
      </div>
    </>
  );
};

And I want to translate following json file :

**Comment by baxromxojasultonxojayev** [comment]
"text": ["Tashkent", "Discounts", "Delivery", "Help", "Contact"]

**Comment by adrai** [comment]
Map works only on arrays: https://www.w3schools.com/jsref/jsref_map.asp

```javascript
// having these resources:
{
  text: ["Tashkent", "Discounts", "Delivery", "Help", "Contact"]
}

// this should work
{t("text", { returnObjects: true }).map((text) => (
  {text}
))} 
```

**Comment by baxromxojasultonxojayev** [comment]
However I got t(..).map is not function then I knew that there is no array but I fetch json file arrays with the help of i 18next library

**Comment by adrai** [comment]
Here a proof this works: https://codesandbox.io/s/react-i18next-forked-iog1t?file=/src/app.js

**Comment by baxromxojasultonxojayev** [comment]
> Map works only on arrays: https://www.w3schools.com/jsref/jsref_map.asp
> 
> ```js
> // having these resources:
> {
>   text: ["Tashkent", "Discounts", "Delivery", "Help", "Contact"]
> }
> 
> // this should work
> {t("text", { returnObjects: true }).map((text) => (
>   {text}
> ))} 
> ```

In that case how can I get each array element and put them into <li><li/> as a list

**Comment by adrai** [comment]
Please check this example: https://codesandbox.io/s/react-i18next-forked-iog1t?file=/src/app.js

**Comment by adrai** [comment]
![image](https://user-images.githubusercontent.com/1086194/131482996-fa567d56-fa29-4c39-8965-ec28016ba1a7.png)

**Comment by baxromxojasultonxojayev** [comment]
> Please check this example: https://codesandbox.io/s/react-i18next-forked-iog1t?file=/src/app.js

seems work well on this link but on the browser :
TypeError: t(...).map is not a function
App
src/App.js:51

  48 |   ))}
  49 | </ul>
  50 | <ul className="right-side">
> 51 |   {t("text", { returnObjects: true }).map((text, country_code) => (
     | ^  52 |     <li key={country_code}>
  53 |       <a href="#">{text}</a>
  54 |     </li>

**Comment by adrai** [comment]
Must be something in your code then...
We can't help more than that if you do not provide a reproducible example, sorry.

**Comment by jamuhl** [comment]
@baxromxojasultonxojayev debug what it returns (is it that hard) - the sample proofs it works if done all correct -> there is something wrong in your code / translations

**Comment by baxromxojasultonxojayev** [comment]
![Screenshot from 2021-08-31 15-11-00](https://user-images.githubusercontent.com/74825957/131492507-3e9b7617-3726-448d-8fc8-2c38edb814ca.png)
![Screenshot from 2021-08-31 14-48-32](https://user-images.githubusercontent.com/74825957/131492517-f61c747c-7ea0-4e45-ba9c-49f83c15737b.png)
![Screenshot from 2021-08-31 14-24-07](https://user-images.githubusercontent.com/74825957/131492556-49651181-64d7-4900-8dea-ee4c3a548ff2.png)


> @baxromxojasultonxojayev debug what it returns (is it that hard) - the sample proofs it works if done all correct -> there is something wrong in your code / translations

**Comment by jamuhl** [comment]
- again it's `{ returnObjects: true }`
- you don't use suspense but load translations from backend -> translations are not loaded on first render -> so t returns undefined
- debug the return value of t and see yourself

**Comment by baxromxojasultonxojayev** [comment]
>     * again it's `{ returnObjects: true }`
> 
>     * you don't use suspense but load translations from backend -> translations are not loaded on first render -> so t returns undefined
> 
>     * debug the return value of t and see yourself

can you clarify your feedback pls

**Comment by baxromxojasultonxojayev** [comment]
because 't' is defined as well as it takes array I think

**Comment by jamuhl** [comment]
https://react.i18next.com/latest/usetranslation-hook#not-using-suspense

`t` is a function returning something, you map on the something returned -> not yet loaded translations (as you disabled suspense and not use the ready flag in any way) the return value is a string (the fallback key) not an array...

**Comment by baxromxojasultonxojayev** [comment]
> @baxromxojasultonxojayev debug what it returns (is it that hard) - the sample proofs it works if done all correct -> there is something wrong in your code / translations

This is codesendbox about issue  ' t(..).map is not function '. Could you check it ?
https://codesandbox.io/s/solitary-flower-oltr3?file=/src/index.js

**Comment by baxromxojasultonxojayev** [comment]
This is codesendbox about issue ' t(..).map is not function '. Could you check it ?
https://codesandbox.io/s/solitary-flower-oltr3?file=/src/index.js

**Comment by baxromxojasultonxojayev** [comment]
This is codesendbox about issue ' t(..).map is not function '. Could you
check it ?
https://codesandbox.io/s/solitary-flower-oltr3?file=/src/index.js

вт, 31 авг. 2021 г. в 16:51, Jan Mühlemann ***@***.***>:

**Comment by jamuhl** [comment]
sandbox has no reproducible code...I would suggest searching for some help on stackoverflow or local friends that have programming skills...

won't further waste my time on this...so do not expect any reply on this issue
