### ISSUE TITLE
strings they are outside of components( in jotai atoms file ) don't translate automatically

### ISSUE THREAD

**Issue by nightwolf-041** [i18next/react-i18next#1369]
hi 
i use [jotai](https://github.com/pmndrs/jotai) as my state manager.
But when I put a string in it files, they does not translate automatically.

They do not translate even when I use `i18n` Instance ( like `i18n.t()`. Even the `languageChanged` event does not fire in this file...

But when a page goes back and forth and I go back, they are translated. :/

here is sample of atom with `t` function :

```
export const mainChartDataReadAtom = atom((get) => {
  const selectedGroupInfo = get(selectedGroupInfoReadAtom);

  const chartData = [
    {
      id: 'Presents',
      label: t('Presents'),
      value: selectedGroupInfo?.attendedParticipantsCount,
    },
    {
      id: 'Absents',
      label: t('Absents'),
      value:
        selectedGroupInfo?.participantsCount! -
        selectedGroupInfo?.attendedParticipantsCount!,
    },
  ];

  return chartData;
});
```

any idea ?

**Comment by jamuhl** [comment]
How should that work? There is no event triggering a translation flow -> on UI components that is done using the hook or HOC...

But there are other issues you might find useful: https://github.com/i18next/react-i18next/issues/1306

**Comment by nightwolf-041** [comment]
> How should that work? There is no event triggering a translation flow -> on UI components that is done using the hook or HOC...
> 
> But there are other issues you might find useful: #1306

but i can't use `useMemo` out side of react component. in this case we should use i18n instance and it's t function directly.
but problem is that in this atoms files it dose not update when language change

**Comment by jamuhl** [comment]
there are more links in that issue, eg.: https://github.com/i18next/react-i18next/issues/1236#issuecomment-762039023

**Comment by nightwolf-041** [comment]
> there are more links in that issue, eg.: [#1236 (comment)](https://github.com/i18next/react-i18next/issues/1236#issuecomment-762039023)

i used this before, in this file it's ok and strings updated. but in that atom file still they did not changed automatically.
even if i add a console log for `data`, if just shown at the first time and how many i change lang it dose not update

**Comment by jamuhl** [comment]
Then you have to look at what atom does -> guess that does run only once and avoid any content change. If the returned object got not freezed you might mutate it's content on language change.

But how to solve this is more a problem with your state management than with react-i18next -> therefore I close this issue.

**Comment by nightwolf-041** [comment]
> Then you have to look at what atom does -> guess that does run only once and avoid any content change. If the returned object got not freezed you might mutate it's content on language change.
> 
> But how to solve this is more a problem with your state management than with react-i18next -> therefore I close this issue.

thank you for your help
