### ISSUE TITLE
Initializing a new instance changes the useTranslation namespace of an existing instance

### ISSUE THREAD

**Issue by dave-db** [i18next/react-i18next#1370]
## 🐛 Bug Report

I have two React apps running in a micro-frontend framework, sharing references to the i18next and react-18next libraries via webpack `externals` (before they shared a reference, everything was fine). Since adding the reference sharing, I've converted both app's i18next initialisation to `createInstance` in order to separate their resource loading and namespacing (they have their own language resources and namespaces).

The apps initialise at different times - there is a parent app, then the child app initialises on user interaction. I can see the first app render correctly (in the selected language), but when I initialise the second app, **despite being a separate instance**, it changes the current namespace of the first app. This triggers an immediate re-render of the default keys and console warnings of missing keys in the first app.

## To Reproduce

We're using react-i18next throughout the apps, almost exclusively with `useTranslation()` without parameters, falling back to the instance's default namespace. I suspect this is what's causing the trouble.

```js
// APP 1 i18n.js
import { initReactI18next } from 'react-i18next'; // shared singleton reference
import i18n from 'i18next'; // shared singleton reference

import de from './locales/de/app1.json';
import en from './locales/en/app1.json';

const instance = i18n.createInstance();
instance
  .use(initReactI18next)
  .init({
    fallbackLng: 'en',
    debug: true,
    defaultNS: 'app1',
    supportedLngs: ['en', 'de'],
    resources: {
      en: {
        app1: en
      },
      de: {
        app1: de
      }
    },
    interpolation: {
      escapeValue: false
    },
    react: {}
  });

export default instance;
```
```js
// APP 2 i18n.js
import { initReactI18next } from 'react-i18next'; // shared singleton reference
import i18n from 'i18next'; // shared singleton reference

import de from './locales/de/app2.json';
import en from './locales/en/app2.json';

const instance = i18n.createInstance();
instance.use(initReactI18next).init({
  fallbackLng: 'en',
  debug: true,
  resources: {
    en: {
      app2: en
    },
    de: {
      app2: de
    }
  },
  defaultNS: 'app2',
  supportedLngs: ['en', 'de'],
  interpolation: {
    escapeValue: false
  },
  react: {}
});

export default instance;
```

```jsx
// example component
import React from 'react';
import { useTranslation } from 'react-i18next';

export const App1Component = () => {
  const { t } = useTranslation();
  return <h1>{t('App1Key')}</h1>;
}
```

Log output [annotations in brackets]:
```
i18next: languageChanged en [default lang]
i18next: initialized {debug: true, initImmediate: true, ns: Array(1), defaultNS: "app1", fallbackLng: Array(1), …}
i18next: languageChanged de [lang preference loaded from backend]
[activate app 2]
i18next: languageChanged en [default lang]
i18next: initialized {debug: true, initImmediate: true, ns: Array(1), defaultNS: "app2", fallbackLng: Array(1), …}
i18next: languageChanged de [language preference passed from app 1]
i18next::translator: missingKey de app2 App1Key App1Key [app1 namespace now "app2"!]
i18next::translator: missingKey de app2 OtherApp1Key OtherApp1Key
```

## Expected behavior

I was expecting this to work as it did before we shared the library references - the instances to be distinct, where calling init() on the second instance would have no effect on the namespace of the first. I'm guessing this relates to how we've used `useTranslation()` without parameters in our components - the shared reference to `initReactI18Next` is only allowing for one default namespace? Either way, not ideal for scaling this approach out to more apps!

Have I missed something done something catastrophically wrong with this setup?

## Your Environment

- node 14.17, Chrome 91
- "i18next": "^20.3.5", "react-i18next": "^11.11.4"
- Mac OS 10.15.7

**Comment by adrai** [comment]
Are you using the I18nextProvider?

https://react.i18next.com/latest/i18nextprovider

**Comment by dave-db** [comment]
...and I've immediately answered my own question - I need to wrap each app in an [I18nextProvider](https://react.i18next.com/latest/i18nextprovider).

Apologies!
