### ISSUE TITLE
i18n.t('') type support

### ISSUE THREAD

**Issue by shubhamdeodia** [i18next/react-i18next#1372]
## 🐛 Bug Report

I followed the steps which is specified [here](https://react.i18next.com/latest/typescript).

within react component, my type support is working fine

```
function App(){
   const { t } = useTranslation()

   return <span>{t('key')}</span>
}
```

But outside React component, I am using `i18n.t` and it is not having the same type support as i had with the `t` from `useTranslation`

I feel both the instance for `t` should have the same type support, as its not  always true that I can use `useTranslation` at all the places in my App.

## Your Environment

- *runtime version*: node 14
- *i18next version*: 20.6.0
- *os*:  Windows

**Comment by pedrodurek** [comment]
We'll add support for the i18next library very soon, https://github.com/i18next/i18next/issues/1504
