### ISSUE TITLE
remove one resource

### ISSUE THREAD

**Issue by El-bana** [i18next/react-i18next#1373]
## 🚀 Feature Proposal

To be able to remove a resource from resources just like adding resource, you pass the lng ns and key and then that resource gets removed

## Motivation

I've been building an app with dynamic text that the user can change so static keys sometimes are an issue of the user added a text field and changed how the content looks like

## Example

currently I'm using unique id's but if one is able to remove a resource it would be better just using the translation and replacing the spaces with hyphens so it's more clear in the JSON file which translation is for which

**Comment by jamuhl** [comment]
Sorry I don't get the use of this request...why would you remove translations during runtime...as soon the session closes the translations are gone anyway...

**Comment by adrai** [comment]
@El-bana maybe related? https://github.com/i18next/i18next-fs-backend/issues/23
