### ISSUE TITLE
Can't use default variables in Translate component without values prop

### ISSUE THREAD

**Issue by andy-potts-nutmeg** [i18next/react-i18next#1375]
## 🐛 Bug Report

Can't use default variables in the Trans component unless the values prop is defined in the Trans component.

## To Reproduce

```
i18n.init({
  ...
  interpolation: { defaultVariables: { testValue: "Lorem ipsum" } },
});

const language = new Translations({
  language: "en-gb,
  resources: {
    common: {
      string: "Test string with default value {{testValue}}"
    }
  }
});
```

This can't access the default variables
```
<Trans
  i18n={language.i18nInstance}
  i18nKey="common.string"
/>
```

This can access the default variables
```
<Trans
  i18n={language.i18nInstance}
  i18nKey="common.string"
  vaules={{}}
/>
```

## Expected behavior
The default variables should always be accessible in the Trans component irrespective of whether the values prop is passed into the Trans component or not

## Your Environment
- *i18next version*: 10.10.0
- *os*: Mac

**Comment by adrai** [comment]
Would you like to send a Pull Request to address this? Remember to add unit tests.

**Comment by andy-potts-nutmeg** [comment]
Will get back to you on this tomorrow

**Comment by andy-potts-nutmeg** [comment]
Bumping the package fixed this issue. Didn't this issue in any of the patch notes when I looked previously, must have missed it though. Thanks

**Comment by adrai** [comment]
indroduced in v13.3.0 https://github.com/i18next/react-i18next/issues/1685
