### ISSUE TITLE
evaluating '_intl.default' when calling init

### ISSUE THREAD

**Issue by salan1** [i18next/react-i18next#1376]
## 🐛 Bug Report

With React Native 0.65.1 I'm unable to build since calling init generate the below error.
TypeError: undefined is not an object (evaluating '_intl.default')
Removing this fixed the error. 

## To Reproduce
void intlNext.init({
  fallbackLng: "en",
  debug: true,
  resources,
  lng: "en",
  keySeparator: false,
  interpolation: {
    escapeValue: false,
  },
})

## Your Environment
"typescript": "4.4.3"
 "react-native": "0.65.1",
 "react": "17.0.2",
 "i18next": "^20.6.1",
 "react-i18next": "^11.12.0",

**Comment by adrai** [comment]
Sorry, need more information.
what is _intl.default?
Please provide more information.

**Comment by salan1** [comment]
I'm not sure what other info I can give. The logs only provide the below when calling init with any config provided.
`TypeError: undefined is not an object (evaluating '_intl.default')`
Has the library been tested to work with React Native 0.65.1 before?

**Comment by adrai** [comment]
Sorry, but I have no mobile development environment on my machine....
That's why I was asking for more information.
Maybe at least a stacktrace?

**Comment by salan1** [comment]
It looks like the issue was that i8n was exported with the modules assigned but initialized in another file. Putting both the module assignment and initialization fixed the issue.

**Comment by adrai** [comment]
ok, so this issue can be closed?
