### ISSUE TITLE
useTranslation keyPrefix - please bump peerDependency of `i18next`

### ISSUE THREAD

**Issue by marek-tkaczyk** [i18next/react-i18next#1377]
I wanted to use a new feature, ability to supply **keyPrefix** into _useTranslation_ hook.

`const { t } = useTranslation('myTranslations', { keyPrefix: 'deeply.nested' })`

I couldn't figure out why it didn't want to work,
 so I started investigation into [merged PRs ](https://github.com/i18next/react-i18next/pull/1371)and found out that I need to upgrade `i18next` package to at least 20.6 version.

No npm. or yarn informed me about this, because[ version of `i18next` as a **peerDependency** was not bumped up.](https://github.com/mdjastrzebski/react-i18next/blob/80b257984ddb24be1b6b087ca93cc529d906ace5/package.json#L92)
So please bump it to save others developers time for searching this.

**Comment by jamuhl** [comment]
peerDependency wasn't bumped up - because it is only needed for that one specific new feature which is a core feature..not a react-i18next feature

**Comment by jamuhl** [comment]
will add a note to docs
