### ISSUE TITLE
Please do not show migration warning during tests

### ISSUE THREAD

**Issue by maapteh** [i18next/react-i18next#1380]
Is it possible to not display the warning when we are in test environment?

While building and developing im fine with the "new" warning put at:

https://github.com/i18next/react-i18next/search?q=It+seems+you+are+still+using+the+old+wait+option%2C+you+may+migrate+to+the+new+useSuspense+behaviour.

But during tests in watch mode im getting:
```
    console.warn
      react-i18next:: It seems you are still using the old wait option, you may migrate to the new useSuspense behaviour.

      38 |   onSubmit,
      39 | }: TLoginFormProps) {
    > 40 |   const { t } = useTranslation('component');
         |                 ^
      41 |   const { register, handleSubmit, formState } = useForm<TInput>({
      42 |     mode: 'onChange',
      43 |   });
 ```
 
 with stacktraces which actually pollutes my test view during working a lot.
 
 My proposal is if NODE_ENV === 'test' maybe can be used to not display it? Or even better a generic way to turn it off. The move to Suspense will be done later.

**Comment by adrai** [comment]
The problem is not the log statement, but somewhere in your code you still use wait (which does not have any functionality)
So just remove the wait option from your code.

**Comment by maapteh** [comment]
Thanks!
