### ISSUE TITLE
Optionally passing i18n instance to `Trans` when `t` function is given

### ISSUE THREAD

**Issue by gabsprates** [i18next/react-i18next#1382]
I had the error bellow when I tried to use `<Trans t={t} i18nKey="notification.success" />` inside a React Portal.
`You will need to pass in an i18next instance by using i18nextReactModule`

I'm using Next.js with `next-i18next` and I fixed that just calling `setI18n` with my `i18next.i18n` instance.

But I looked at the code and there's my question:

Based on the code bellow, should it be possible to avoid the warn with early return when `t` function is provided, even without an `i18n` instance, from line 699?
https://github.com/i18next/react-i18next/blob/12a9e92cceb5411be42fa8a776914fe0f5d6506f/react-i18next.js#L699-L708

I noticed it uses `i18n.options`, but with a given bounded `t` function, my question remains.

**Comment by jamuhl** [comment]
agree passing in a bound `t` function in props that warning could be somewhat avoided...only problem I see is that the useTranslation hook also returns the i18n instance...

**Comment by gabsprates** [comment]
With "only problem" do you mean "you can just pass both `t` and `i18n` and the problem is solved"?

**Comment by jamuhl** [comment]
if you pass in both `t` and `i18n` using props that warning should be gone...

but if you only pass in `t` that won't be enough as we return i18n from the hook

**Comment by gabsprates** [comment]
Thanks for clarifying @jamuhl !
