### ISSUE TITLE
How can I create multiple Text JSX tag wrap for React Native?

### ISSUE THREAD

**Issue by azim-barcove** [i18next/react-i18next#1383]
Hi, First of all, thanks for this wonderful library! I've been trying to use multiple tag replacement for React Native, but I do not know how to make of this, I have tried to follow the docs, but it seems it not working, basically this is my code:-
```
<View>
  <Trans
    i18nKey="HomeScreen.TestDescription"
    t={t}
    values={{ test: "This is Test" }}
    // components={[
    //   <Text style={[styles.startTestDescription, styles.italic]} />,
    //   <Text style={styles.startTestDescription} />
    // ]}
  >
  <Text style={styles.startTestDescription}>
    ABC
  </Text>
  <Text style={[styles.startTestDescription, styles.italic]}>
    This is test Variable Text
  </Text>
  <Text style={styles.startTestDescription}>
    DEF
  </Text>
 </Trans>
</View>
```

And my translation json looks like:-

```
"HomeScreen": {
    "TestDescription": "<0>This is First Text.</0> <2>{{test}}</2> <4>This is Last Text.</4>",
}
```

I tried to mix around the replacement tag numbers, but all I got is messed up format and JSX wrap issue. By the way, you can see the commented `components` prop which I tried to follow and it seems doesn't work too. but I'm not sure if I need to install `i18next-icu` extension or not as the docs seems doesn't emphasize on it.

Please bear with me, I'm new with this ecosystem and would appreciate the assistance.

Thank you.

**Comment by adrai** [comment]
Have you already had a look at this documentation? https://react.i18next.com/latest/trans-component#how-to-get-the-correct-translation-string

I have no react-native setup here, but this codesandbox example should be ok for you to understand how the Trans component works: https://codesandbox.io/s/react-i18next-example-forked-nd5vn?file=/src/app.js

```json
"HomeScreen": {
    "TestDescription": "before element 0<0>in element 0</0>before element 1<1>in element 1</1>before element 2<2>in element 2</2>after element 2"
}
```

```jsx
<Trans i18nKey="HomeScreen.TestDescription">
  <p style={{ color: "green" }}>ABC</p>
  <p style={{ color: "blue" }}>This is test Variable Text</p>
  <p style={{ color: "red" }}>DEF</p>
</Trans>
```

![image](https://user-images.githubusercontent.com/1086194/134937848-bcf7e3a7-bd27-444e-9374-a93e5f254239.png)

**Comment by azim-barcove** [comment]
Hi @adrai, thanks for your reply, from your examples I've concluded that the issue was I didn't wrap the spaces in the `json` file translation which breaks the JSX tag replacement, as currently code looks like this:-

```
<View>
  <Trans
    i18nKey="HomeScreen.TestDescription"
    values={{ test: "This is Test" }}
    components={[
      <Text style={[styles.startTestDescription, styles.italic]} />, // Replacement tag index no. 0
      <Text style={styles.startTestDescription} /> // Replacement tag index no. 1
    ]}
  />
</View>
```
And my **WRONG** `json` object is like this (Notice on spaces outside wrapping replacement tag there and the wrong index too):-
```
"HomeScreen": {
    "TestDescription": "<0>This is First Text.</0> <2>{{test}}</2> <4>This is Last Text.</4>",
}
```
which will render like:-
```
<Text style={styles.startTestDescription}>
    {'This is First Text.'}
</Text>
{' '}
<Text style={[styles.startTestDescription, styles.italic]}>
    {'This is test Variable Text'}
</Text>
{' '}
<Text style={styles.startTestDescription}>
    {'This is Last Text.'}
</Text>
```

Where the **RIGHT** `json` object should be like (Removed spaces outside replacement tags and corrected index no.):-
```
"HomeScreen": {
    "TestDescription": "<0>This is First Text.</0><1>{{test}}</1><0>This is Last Text.</0>",
}
```
which will render:-
```
<Text style={styles.startTestDescription}>
    {'This is First Text.'}
</Text>
<Text style={[styles.startTestDescription, styles.italic]}>
    {'This is test Variable Text'}
</Text>
<Text style={styles.startTestDescription}>
    {'This is Last Text.'}
</Text>
```

And finally solved the issue. Maybe you guys can add these findings as rules for React Native. Again thanks @adrai !
