### ISSUE TITLE
Transform static files to use translations as a one-time operation

### ISSUE THREAD

**Issue by goamn** [i18next/react-i18next#1385]
## 🚀 Feature Proposal

Not sure if this exists or not, none of my searches returned anything. Feature: allow for easy use of translations inside static files like .json files. Real-time download from CDN is not required, only a "one time" transform to update the json files.

## Motivation

Some frameworks force you to load pages from static json files (such as Teams App, the "About" tab is loaded from a manifest.json file, including all locales). It would be nice to have some integrated way of updating these static files.

## Example

As a full example. I will support Spanish locale in Teams App, my Spanish translations will be inside the `es-localization.json` file. Before deploying my app, I would like to pull down a few keys, and then transform `es-localization.json` and put them in the appropriate Spanish placeholders. i.e.
```
{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.8/MicrosoftTeams.Localization.schema.json",
  "name.short": "{name..short.locize}     //"Le App",
  "name.full": "{name.full.short.locize}     //"App pour Microsoft Teams",
  "description.short": "{description.short.locize}     //"Créez d'excellentes applications pour Microsoft Teams avec App.",
}
```
The above json file will have the appropriate `{X.Y.locize}` strings transformed into the appropriate Spanish translation inside the platform.

**Comment by jamuhl** [comment]
Not 100% but this looks more like you're requesting a feature for locize CLI than react-i18next?

Even there I'm not sure if it is really needed as the problem looks rather simple:

1) Load your template (es-localization.json) and the translations from locize CDN (using the CLI)
2) Find the `{key}` in your template and replace it with the found value in the translation file

**Comment by goamn** [comment]
> Not 100% but this looks more like you're requesting a feature for locize CLI than react-i18next?
> 
> Even there I'm not sure if it is really needed as the problem looks rather simple:
> 
> 1. Load your template (es-localization.json) and the translations from locize CDN (using the CLI)
> 2. Find the `{key}` in your template and replace it with the found value in the translation file

Yes I agree, it will be more than 3 entries, probably around 10, and with 4 languages it will be 40. Just thinking of one extra way to reduce localization maintenance but all good if nothing exists right now. Thanks for the reply :).

**Comment by jamuhl** [comment]
I mean it's easy to write a process doing what you need with a few lines of code (map over Object.values). Doing something like that in the locize CLI would mean we have to define some sort of template/conventions (which in the end might not fit your demand)

**Comment by goamn** [comment]
Right, a quick transformer that would run after the CLI pulls down the latest translations. Thanks for the idea
