### ISSUE TITLE
Type-safe translations do not work with plurals

### ISSUE THREAD

**Issue by Mephistofeles** [i18next/react-i18next#1386]
## 🐛 Bug Report

After setting up TypeScript type definitions I cannot use plurals support:

## To Reproduce

```js
{
  "key_one": "item",
  "key_other": "items",
}

t('key', {count: 0}); // TS error, only key_one or key_other are allowed
t('key', {count: 1}); // TS error
```

## Expected behavior

Such resources should be allowed to be used without the suffix.

## Your Environment

- react-i18next@11.12.0

**Comment by adrai** [comment]
Was this supported with i18next json format v3 in TypeScript?
Need @pedrodurek's help...

**Comment by jer-sen** [comment]
@njacob1001 you can use `patch-package` module
