### ISSUE TITLE
Type-safe translations do not work with keyPrefix

### ISSUE THREAD

**Issue by Shaddix** [i18next/react-i18next#1387]
## 🐛 Bug Report
After setting up a type-safe translations and having a translation file like 
```js
{
  "home": {
    "admin_settings": "Admin settings",
  }
}
```

## To Reproduce
The following thing works (and compiles)
```js
  const b = useTranslation('translation');
  b.t('home.admin_settings');
```
But the following doesn't compile (typescript complains)
```js
  const b = useTranslation('translation', { keyPrefix: 'home' });
  b.t('admin_settings');
```
## Expected behavior
The latter examples compiles without errors

## Your Environment

- *i18next version*: 21.2.4
- *react-i18next version*: 11.12.0
- *os*: Windows

**Comment by mdjastrzebski** [comment]
I wasn't aware of such feature. `keyPrefix` definitely needs to work with it. Would like to help, but unfortunately I won't be able to work on that in the next 2-3 weeks due to my workload.

**Comment by Shaddix** [comment]
Thanks!

Just one case: for me it only works if keyPrefix is without a dot, I mean the following still errors:

```ts
// you can define a keyPrefix to be used for the resulting t function
const { t } = useTranslation('translation', { keyPrefix: 'very.deeply.nested' });
const text = t('key'); // "here"
```

**Comment by vladi-strilets** [comment]
You are right @Shaddix, it would be great to also support nested key-prefixes.

**Comment by pedrodurek** [comment]
I'll look into it

**Comment by Shaddix** [comment]
@adrai could you please reopen the issue? Or should I create a separate one regarding nested keyPrefixes?

**Comment by adrai** [comment]
> @adrai could you please reopen the issue? Or should I create a separate one regarding nested keyPrefixes?

@pedrodurek what do you prefer?

**Comment by pedrodurek** [comment]
I'm working on it, we can reopen for now

**Comment by chengsokdara** [comment]
after update from 11.12.0 to 11.13.0, typescript auto complete stop working.
please try the example no-namespace and just update react-i18next to 11.13.0, auto complete stop working.
