### ISSUE TITLE
Destructuring the I18n instance returned from useTranslation causes calls to fail

### ISSUE THREAD

**Issue by Zanoro9000** [i18next/react-i18next#1388]
## Documentation issue

A clear and concise description of what the issue is.

For instance, when calling 

`const { i18n } = useTranslation();` 

if I wanted just the `changeLanguage` function in my component, I would destructure like so: 

`const { i18n: { changeLanguage }} = useTranslation();`

This causes an error as the changeLanguage function relies on `this` and `this` is undefined after destructuring (internally). While this limitation is fine (and removing it would be too much to ask I'm sure) it would be good to document and warn others for the future.

## Motivation

Please outline the motivation for the proposal.

The motivation is that I just spent a day trying to find out why `this` was undefined for my `changeLanguage` callback and thought it might be useful to document as there are no other stackoverflow links or anything that can help people sove this issue if they have it.

**Comment by jamuhl** [comment]
Isn't that a problem of deconstructing things that should not be deconstructed?!??

**Comment by jamuhl** [comment]
It's basic JavaScript knowhow.

```js
const changeLanguage = i18next.changeLanguage;
changeLanguage('de'); // this is not what you expect
```
