### ISSUE TITLE
Custom "ns" of t() doesn't work with "keyPrefix" specified in "useTranslation" hook

### ISSUE THREAD

**Issue by artischockee** [i18next/react-i18next#1393]
## 🐛 Bug Report

When using `useTranslation` hook with `keyPrefix` option provided, custom namespaces (in `t()` calls) don't work as expected. I didn't find any information about this, neither in library's documentation, nor StackOverflow, so I consider this behavior wrong.

If this is really a bug, I could give a hand on this fix. 🤔 

## To Reproduce

A [codesandbox](https://codesandbox.io/s/zealous-galileo-wzixd?file=/src/App.js) example.

## Expected behavior

I expect the `t()` function to return correct string from different (custom) namespace, when `useTranslation` hook is used with `keyPrefix` option.

```js
// i18next.js

i18next.use(initReactI18next).init({
  resources: {
    en: {
      languages: {
        de: "German"
      },
      some: {
        deeply: {
          nested: {
            thing: "Foobar"
          }
        }
      }
    }
  },
  fallbackLng: "en",
  interpolation: {
    escapeValue: false
  }
});
```

```js
// component.js

const { t } = useTranslation("some", { keyPrefix: "deeply.nested" });

t("thing");
// -> "Foobar"

t("languages:de");
// -> "German" (expected)
// -> "de" (actual)

t("de", { ns: "languages" })
// -> "German" (expected)
// -> "deeply.nested.de" (actual)
```

## Your Environment

- *runtime version*: node v16.11.0, Google Chrome v95.0.4638.54
- *i18next version*: 20.6.0
- *os*: Mac
- *react-i18next version*: 11.13.0

**Comment by adrai** [comment]
This is probably only a documentation issue.
With keyPrefix all this is not possible.

```js
// component.js

const { t } = useTranslation("some", { keyPrefix: "deeply.nested" });

t("languages:de");
// => because of keyPrefix, this key at the end looks like: `t("deeply.nested.languages:de");` and tries to lookup in the "some" namespace

t("de", { ns: "languages" })
// => because of keyPrefix, this key at the end looks like: `t("deeply.nested.de", { ns: "languages" })` and tries to lookup in the "languages" namespace
```

**Comment by adrai** [comment]
https://react.i18next.com/latest/usetranslation-hook#optional-keyprefix-option
![image](https://user-images.githubusercontent.com/1086194/139704822-512418e6-a032-446b-a46c-259f86b94e61.png)

https://www.i18next.com/overview/api#getfixedt
![image](https://user-images.githubusercontent.com/1086194/139704891-9a6681e2-51d4-42b9-b856-6e975af5fc20.png)
