### ISSUE TITLE
TS throw `Type instantiation is excessively deep and possibly infinite` when there are loads of keys in `Trans` component

### ISSUE THREAD

**Issue by Ambrozy** [i18next/react-i18next#1394]
## 🐛 Bug Report

The same issue as: https://github.com/i18next/react-i18next/issues/1222
But appears in `Trans` component only.

## To Reproduce

A [codesandbox](https://www.typescriptlang.org/play?noUnusedLocals=true&ts=4.3.5#code/C4TwDgpgBAgmkDsAmBpCIDOAeFBGANFCgEyEDKUEAHsBMhlBsAE4CWCA5lALxQAq4CAHkwwVgHsEGANoByANboyEMAENmq4OOayAugD4eUAAYASAN54oAMkYt2HAL4Wyzy8Rt22nR8YDcAFCgkLDwdKjoGMQ4BESkUBTUtPReDkYCkCJikjIKSirqmtp6hrxmlrieTN5OLm4AolQAxgA2AK5IEDjxiiDiAGZQqggg0gZV9j7+AUGCUACqCBIIfOIAkgi0zBgQTdkIWPOlUAAU85Q04QzDIFAA-KfyAFwLAJQ8hgBu4qxIUC8ICCfCDMd5JK6PF7sfogqBrd7cL4-JABKD3OGo-5QQHA5iBYLQABy2gAtqoWqwAF4QaJ8QgoIy9Ab8Y4M8EpJmDPiYh58aQoXQXZJIBgAJV22iQWGqDkIN30mLRvP5gvZIqgzAgqiQkhatxuY0VaPRcEQEUw0RQhE5-BVhgAPqEzWgLThCMTmGSKdTaXaFcbjS9TeEXdgrVAbXyBQ6nSHIm6oB6vVSaVgowZ-YHsUCQZiATm8bMQknySm08dI1BHSXvam+Pp8XMADKqJhCfrloyLZarDZbHZ7ZZpoUQm7ok4Iwx8LE4kGGNUMCcfKDQ2GinlQddo-O4xshYPIQlkLCE+nHcqEiY1RxPCwM2wyqZ7omk0vUgCybRaYjThHOC4jdBmTpKAmyMFs2w7I5jjAgD5g3A8kCPLAm3dV9azTaQmwzKtE3QlNP2-VhfygRpWg6Lp5kIJt9EzHcQWfRNVBJCAMDUJougAMSMTjyRaAAjVQmnkaVJg4WieNwzixkCItoD4Ti2gQJoXSwTFLwAwlmNY9iIHwTE+BQAAFTV+lYKgRxSF0TIgMyqBPY4lM6MzASQfS0WnXgABFbNUL9gHFDBxDaZgOIwAJjg0y4UhOSNXjGXDxW1XUQCwWKgK5eKDA3GsCP84iQMJaQEDaEl+JBbLt0TSz1UjDdDJsuyaoYSNpEJXQjQeXLqUw9rpAa0zzMqrNuq6Pl2ro1JOFkgkiHQRrzJPZqmJYtihIgSLlptHz+j879AuC0LWI3XiWgEoSRMfDhrQyqAdr2gLWMOsK2vGR0nNs9gIBRKqrtwj6XO+xiFKUwdJEC-yjD+x1xH4gArXZgFwmBmA0VLoagWGEb2GMAa+v5HRKs7GLIMT31UMAjHMKBpF6F4rt0F4x0cRiAGE2iYcQSQyCAjMKFj+ypzFNWAEKEEJL8WjuF5+PEcQWi1BBAjREWxfqElRBAUmamlqBZflxXAhZuT+EELJlgwU7zuEtMNCkFpNGWAA1ck2j0qBzckQhyeAJoAAsHBd9oNqMT2EGW3aWh2eq7YwB39iDt3lp9-3A9diBOqmjgjRePhY-j5307zfh88dyRE4gRjRoAIRAHmw+wAzS4T9P3I90QLeW9nOe5wQ+Y0AWQQYXh647nI29FdIzbHqQrcEm28+GOOy4QCvCAbuRVeYBB1c17WHD0QhZFkBVjlH-ZLb4+eRNFdeZ9yLfxclw-sUlhsTdG8VRe3tSPLbp226JGiuqDGkcdhT0yPfOQvRlBqA0FoHQHVjhOy2rdbkSo8KejfBAWu58LaYSdsNF4QDhQMDARnDBTti4oIAuUVczAiBuFcBYehm5fAbjZMAlqaDM6fwgN-A46ZCCikzFVWczBi7iKrvhD8+Uv5ixIk7ZBy06EIBhAwwkN4WFqLXOwjBUVSGAT6FyXhMiIDyJ-uNXQwjREzgLJIgswNFLKQsQcU8-BQyED4PdfyENvxeKMD4-aT0QphU2gBdKxj+BZRymYwiYhXEkUMpESaBiIR1X0WYxJVivGhkmnPC6aYgmPQwP5d+AR2BbF2hxfgziwYHHUstLSq1dJtwGp9CyAFrKDXsoSRyyBPquQilAcwmJf7GmSZgZaINlKqXce0uyMY+AQA1vHCA+9OAYBRmjZarCYAmjsbiNuHlil+KRgBGZ9SzlQzEsc-gfYQRgHlivcmlMAJY0RkYDZHBXmYn0CcI0dMPGRFwpMmQ1jMSvFznUxJ8zPH8FOaxMpysoDjI8qGaZdS5m5IWlQJZKywBrO+Vs1GqhbgAT2Qc+izA7neN8r4pF35MWg32Nc3gV0-kAoDECsFoLQxjDuc5B6FddZXTblC2poNYW5MiF4xFpTvzv0cDMWa8wdiL3tivQKTypBdDSSkZpOl1rHFGWiYA0KWVDj6UbWSnRWjqGgP0S1kgoAcwgBq5e+xhyaW0mtDi-ypC6z4BKtV7rm7LG1TkMa5TZoFJtpxAJvBtr0uCUFUJrFjj9VVFwmm4jBQPG4rnRi74QQcBwalECKBjhCBJKwYAJEbRVs8CgYG08L5GBLcwMttdxmmuNI-CWZ0XgsDdiilW-C1Ya1AN84dzBR2AvyHAoozAXiyAAHSyDHVAIV-kjyrpYEvAukhN1Gk1Gmo6GAXgHXTRgFFjg27dy0L3SBF8IqMXlc9ViEDhBQNkGez9GA9DvpTcAQ1fqxrfo3rIHd34jwlHSMtONl0xKGF5FiK6gRKkgmqfJWOJlxBgEbmiThhjLlzPnDmylDx9nUrbvq9UYHdLDL7U0LmOq6DAAwLrammpkoID1DTYAqgOCGvpmJRmWcoDGzRKxpSwBdYlTKgxTEMHOOirEii1guAAAcCAXS6wZI6FAMlMSBpeISFFwAG7cek1AT46cuMvHMLZ+TFrlJeutQEZVdqHaaigE69zywS5L3GSRiEZH0AOV2Tohh+zqOHJBHRppvqmP-LAMwAjl7gtSHw4RhMfSJUYZmAAegAFRQAALRVeqzV2rdX6sNfqwEcrAZWutdDdsKArHOhtd6210rARGtDeGyN6rpXisqrmNei9RgCTMn-TezDmxsPrSgI+rmeCcgjOFiEi9V7dthSNjMVjUgkYLZm7wPtUhcBOYXSAW7bXSn8RdKuq6sgjTKrRPe0zUQHvGiBbIN7mJvtoikAAZj+2iAHQOvttykAAFkh0Y17Yl3uw5+wAViR9D1HwO4cYAAGzY-QCjmoaOpP44AOzE-u1AQHuP0eg4wNpmnpOD545+wATlZ3TmHFOfu4AAAw8-p2TjnTPcA3e29yknvOGf84l8QEXfOQfYgwLgCH0v-uy9F+zxnavcBY611DnXKv8e4CJ8b5Hcuxf6+u9Tq3OPbcK4Nyzx3pv5eq+u9z93tPdecHJ17qIwvfds4D+LtXxApd9pN37s3P3iBK9DzbvXLupDEE1zH63-uOCB-0o4IYDATtMFksXpG1MkYF94G6j1R6EAnFkNd2QrxAhl41IypGvBgAN96Gup7Lpm+l5yOXqA5rR8eCr669V4bJAnDkE33QLeAht7Pf5DwXfiAN+u08Xv-f0CD5mB6k41MtO6Ze3T7fu+2jPf34QWTmwXhg8IF1tjkgONZeprLFoSBV2iQy5wKAYrfQWQKTKTJfIAA) example.

## Expected behavior

No typescript errors

## Your Environment

- typescript: 4.35
- i18next: 21.3.3
- react-i18next: 11.13.0

## Solution

Remove K generic.
```ts
    type I18nKeyType<N extends Namespace> = TFuncKey<N> extends infer A ? A : never;

    interface TransProps<N extends Namespace = DefaultNamespace, E extends Element = HTMLDivElement>
        extends React.HTMLProps<E> {
        children?: React.ReactNode;
        components?: readonly React.ReactNode[] | { readonly [tagName: string]: React.ReactNode };
        count?: number;
        defaults?: string;
        i18n?: i18n;
        i18nKey?: I18nKeyType<N> | I18nKeyType<N>[];
        ns?: N;
        parent?: string | React.ComponentType<any> | null; // used in React.createElement if not null
        tOptions?: {};
        values?: {};
        t?: TFunction<N>;
    }

    function Trans<N extends Namespace = DefaultNamespace, E extends Element = HTMLDivElement>(
        props: TransProps<N, E>,
    ): React.ReactElement;
```

**Comment by pedrodurek** [comment]
Hey @Ambrozy, this is a typescript limitation/bug that happens in cases where people have more than 22 namespaces. I managed to suppress the error by using the following approach `extends infer A ? A : never` for the `TFuncKey` type. Unfortunately, It seems the same workaround used for the `t` function doesn't work for the `Trans` component 😢 . 

Just to give you an update, this limitation is being addressed in [typescript 4.5](https://github.com/microsoft/TypeScript/issues/41406#issuecomment-954067162), which they plan to officially release sometime in November. In the meantime, I'll look into your suggestion and test the results, thanks!

**Comment by pedrodurek** [comment]
Hey @Ambrozy and @adrai, I'll rollback the changes here, @Ambrozy my advice to you is to way until typescript 4.5 is officially released, it'll fix your issue.

**Comment by xseignard** [comment]
@pedrodurek Hi there! I tried to update a codebase from typescript 4.2.4 to 4.5.2 and the bug reappeared
I can confirm it is related to the number of JSON files we have (~50 in our case)
