### ISSUE TITLE
Translation is load only after refresh

### ISSUE THREAD

**Issue by aaadipop** [i18next/react-i18next#1395]
## 🐛 Bug Report

if `LanguageDetector` is used without `fallbackLng: 'en',` and `detectOption` is only `path` the page will display only translation keys, if they are used both, the page will render correctly .
isn't really a bug but maybe should have some alert or error in this case 

related to: https://github.com/i18next/react-i18next/issues/881

## To Reproduce
https://gist.github.com/aaadipop/f43223ae1dd860d0c9eaa204514de225

## Expected behavior
to load system language 

## Your Environment

- *runtime version*: i.e. node v14.18.1
- *i18next version*: i.e. 19.6.3
- *os*: Mac
- *any other relevant information*

**Comment by aaadipop** [comment]
here: https://codesandbox.io/s/react-i18next-example-forked-v4kge?file=/src/i18n.js

**Comment by adrai** [comment]
The detection options are set to "path" how should this work with that example? there is no language path part in there...

**Comment by aaadipop** [comment]
yes ... I know now :) but usually when you hit a website you go to `/` and with `.use(LanguageDetector)` enabled I supposed that will detect/use a language 

as I said in first post isn't a bug but a poor documented feature. 
or you can consider adding an error/warning in this case because it takes ~2 hours to figure out why the content appears only after refresh :)

**Comment by adrai** [comment]
Sorry, I still don't get what your problem is...
Please try to elaborate with more detail information.
In case you think the documentation for the languageDetector can be optimized, please provide a PR here: https://github.com/i18next/i18next-browser-languageDetector
