### ISSUE TITLE
TS error on using `useTranslation` with multiple namespace without passing namespace prefix in `t`

### ISSUE THREAD

**Issue by jawad360** [i18next/react-i18next#1396]
## 🐛 Bug Report

I'm trying to use `useTranslation` hook passing multiple namespaces.
Now when I'm using the `t` without `namespace:` prefix in the key, it is giving a TS error although it is working fine.

As per the documentation there is no need for the key to be prefixed with `namespace:`, it'll by default take the first index, in this case `ns1`, while if we want to use other namespace we can pass it as a second argument as `{ns: '<namespace>'}`

So the problem is why is it throwing TS error when passing `t(title)` and not giving error on `t(ns:title)`, although both are working fine

## To Reproduce

Here is [codesandbox](https://codesandbox.io/s/react-i18next-namespaces-ovb62?file=/src/App.tsx) example where we can see TS error on using `useTranslation`

```js
function App() {
  const { t } = useTranslation(["ns1", "ns2"]);
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <h2>{t("ns1:title")}</h2> {/* No TS error */}
        <p>{t("description.part1")}</p> {/* TS error */}
        <p>{t("description.part2")}</p> {/* TS error */}
        <p>{t("description.part1", { ns: "ns2" })}</p> {/* TS error */}
        <p>{t("description.part2", { ns: "ns2" })}</p> {/* TS error */}
      </header>
    </div>
  );
}
```
But as per the [documentation](https://react.i18next.com/latest/usetranslation-hook) this should be working fine

## Expected behavior

There should be no TS type error

## Your Environment

- *runtime version*: node v14.17.5
- *i18next version*: ^20.4.0
- *react-i18next version*: ^11.13.0

**Comment by pedrodurek** [comment]
Hey @jawad360, this syntax is not supported when relying on typescript 4.1+, and here is the explanation why https://github.com/i18next/react-i18next/issues/1277#issuecomment-800455785, I'll include that info in the typescript section of our doc.
