### ISSUE TITLE
Typed translation namespaces

### ISSUE THREAD

**Issue by kusyka911** [i18next/react-i18next#1397]
## 🐛 Bug Report

With typed translations namespaces return type of `TFuntion` is `never`

## To Reproduce

A reproducible demo at condesandbox: https://codesandbox.io/s/react-i18next-typed-keys-bug-jbfr5?file=/src/app.tsx

```tsx
export const App: FunctionComponent = () => {
  // NOTE: LngNamespace in enum
  const { t } = useTranslation([LngNamespace.TRANSLATIONS]);

  return (
    <div className="App">
      <div className="App-header">
        {/* Actual result: Return type of TFunction is never */}
        {/* Expected result: Return type of TFunction is string */}
        <h2>{t("translations:WELCOME").toLowerCase()}</h2>
      </div>
    </div>
  );
};
```

## Your Environment

- similar as in conde-sandbox

**Comment by adrai** [comment]
maybe related? #1396 1396

**Comment by pedrodurek** [comment]
Hey @kusyka911, the enum already returns a literal value, so you don't need the `as const`. Just remove and it should work.

If you add `as const`, it'll return the enum type, not the actual literal value.

<img width="616" alt="Screenshot 2021-11-05 at 6 49 49 PM" src="https://user-images.githubusercontent.com/12190482/140592273-ea8b8f88-a3b5-401b-8e4b-7751a576bd8f.png">

**Comment by pedrodurek** [comment]
I'm going to close this one for now, you can reopen it if needed.

**Comment by kusyka911** [comment]
@pedrodurek I removed `as const` in demo, but this not fix main problem (return type of `t('someTranslation')` is `never`)

**Comment by kusyka911** [comment]
@adrai 
@pedrodurek 
Reopen the issue, please. Looks like I can not do this.

**Comment by pedrodurek** [comment]
Hey @kusyka911, it seems it's a typescript limitation, `enum` doesn't work the same way as literal values (I don't know why), but take a look at this example (both Results):
https://tsplay.dev/WG6k0m

So there isn't much we can do on our side. My advice is to replace the `enum` from the type definitions file to literal value:
https://codesandbox.io/s/react-i18next-typed-keys-bug-forked-klfcc?file=/src/react-i18next.d.ts

**Comment by kusyka911** [comment]
@pedrodurek Okay. Thanks for your response. In this case this issue maybe closed.
