### ISSUE TITLE
Trans component Issue

### ISSUE THREAD

**Issue by anwarjaved** [i18next/react-i18next#1398]
<Trans i18nKey="SampleKey" t={t} /> but vscode give me this warning

## 🐛 Bug Report

I am trying to render an html tag using Trans component like below sample

'Trans' refers to a value, but is being used as a type here. Did you mean 'typeof Trans'?
 What I am doing wrong here?
```tsx
<Trans i18nKey="SampleKey" t={t} />
```

## Expected behavior
it should render the html tag strong tag with value

```js
// Paste the expected results here
```

## Your Environment
"react-i18next": "^11.13.0"
- *runtime version*: i.e. node v14, deno, browser xy
- *i18next version*: i.e. 19.5.3
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by pedrodurek** [comment]
Could you share more context, or an example on codesandbox?

**Comment by anwarjaved** [comment]
I can't share the code but I am giving example

I have this in locale file for validation
"MIN_LEN": "<strong>{{Field}}</strong> must be at least {{Length}} characters",
    "MAX_LEN": "<strong>{{Field}}</strong>  must not exceed {{Length}} characters",
    "INVALID": "<strong>{{Field}}</strong> is invalid",

and I am just trying to make  field name bold and trying to return <Trans component from a function and it shows me error in vscode
`'Trans' refers to a value, but is being used as a type here. Did you mean 'typeof Trans'?`

**Comment by pedrodurek** [comment]
Hey @anwarjaved, I wasn't able to replicate your issue.
https://codesandbox.io/s/react-i18next-type-trans-component-pi5re?file=/src/App.tsx

**Comment by houzhitaohzt** [comment]
![image](https://user-images.githubusercontent.com/20673060/141968839-ed6a7494-df2e-43a7-ae1c-86550264b64a.png)
![image](https://user-images.githubusercontent.com/20673060/141968930-ca4ec087-03f4-47ca-93e6-674977695b70.png)
Antd Form validation error message not translated!!
Would you please tell me how to solve it？

**Comment by pedrodurek** [comment]
Hey @houzhitaohzt, this issue is unrelated, check if you're not memoizing the `required` string, or you could open another issue and provide more info.

**Comment by yesimk** [comment]
I had this issue, I changed .ts file to ,tsx and it solved

**Comment by dungtran5** [comment]
> I had this issue, I changed .ts file to ,tsx and it solved

I had same issue and this solution solved it too
