### ISSUE TITLE
Cannot import I18nextProvider with the version 1.0.0

### ISSUE THREAD

**Issue by Grmiade** [i18next/react-i18next#14]
Since the new version 1.0.0, `import { I18nextProvider } from 'react-i18next';` return undefined.

```javascript
import { I18nextProvider } from 'react-i18next';
console.log(I18nextProvider);
>>> undefined
```

**Comment by jamuhl** [comment]
just give me a second...found the same issue in our production....

my fault: migrated to babel6 but missed exports are different

**Comment by Grmiade** [comment]
Thanks :)

**Comment by jamuhl** [comment]
try 1.0.1

https://github.com/i18next/react-i18next/commit/9b84c0cc8f07d30055b5656100478639410bd46e

should fix it

**Comment by Grmiade** [comment]
It's fixed. Thanks
