### ISSUE TITLE
Upgrading to 11.14.0 crashes during TypeScript project build

### ISSUE THREAD

**Issue by mrlubos** [i18next/react-i18next#1401]
## 🐛 Bug Report

After upgrading to version 11.14.0, the app crashes during build due to TypeScript compiler error with the message `Type instantiation is excessively deep and possibly infinite.`. This is because I create a higher-order component on top of the `<Trans />` component.

## To Reproduce

Open [CodeSandbox](https://codesandbox.io/s/blissful-breeze-kfom6?file=/src/App.tsx)

## Expected behavior

The app compiles without any errors.

## Your Environment

- `react-i18next`: 11.14.0

**Comment by adrai** [comment]
v11.14.1
