### ISSUE TITLE
using useTranslation hooks in first route of react native make an error

### ISSUE THREAD

**Issue by rbayuokt** [i18next/react-i18next#1405]
## 🐛 Bug Report

Hi hello, thank you for creating react-18next, it awesome lib, sadly, I have a problem when I'm trying using `useTranslation` hooks in first route in react native, it gave me an error like this, it seems the error coming from `useTranslation.js`, this just happened only when putting useTranslation hooks in the first route ( first screen ) of react navigation 5, but if I'm using useTranslation hooks in another route ( screen ) it's fine

![image (3)](https://user-images.githubusercontent.com/49748249/141438420-79c2c3c8-9bca-4374-822e-19a052a0aa32.png)

## Your Environment
- "react-i18next": "^11.11.0"
- "i18next": "^20.3.1",
- @react-navigation/drawer": "^5.12.5",
- "@react-navigation/native": "^5.9.4",
- "@react-navigation/stack": "^5.14.4",

thank you so much, I really stuck with this problem , I'm using typescript

**Comment by FladioArmandika** [comment]
yes, i have exactly the same problem like this

**Comment by adrai** [comment]
It may be this is an issue of react-navigation?
this works right? https://github.com/i18next/react-i18next/blob/master/example/react-native/App.js
Can you share some code?
you may need to debug a bit on your own, I have no react-native environment here....

**Comment by rbayuokt** [comment]
> It may be this is an issue of react-navigation? this works right? https://github.com/i18next/react-i18next/blob/master/example/react-native/App.js Can you share some code? you may need to debug a bit on your own, I have no react-native environment here....

yes, I already set like that

in example 
`
.....
const RootNavigator = () => (
  <Stack.Navigator headerMode="none">
    <Stack.Screen
      name="NotWorkingTranslationScreen"
      component={NotWorkingTranslationScreen}
    />
    <Stack.Screen
      name={WorkingTranslationScreen}
      component={WorkingTranslationScreen}
    />
   </Stack.Navigator>
.........
`

NotWorkingTranslationScreen.tsx
`
...
const TestScreen = (props: ITestScreenProps) => {
  const {t} = useTransalion('translationfile')

  return(
    <Text>{t('CTA.button')}</Text>
  )
}
...
`

when I do like that it giving me the error like in the description above, but on the second route useTranslation hooks, is working, the error will always showing if I use useTranslation in the first route

**Comment by adrai** [comment]
Can you confirm this is only an issue with react-native? So a similar setup works with normal react (web)?

**Comment by rbayuokt** [comment]
> Can you confirm this is only an issue with react-native? So a similar setup works with normal react (web)?

yes, I confirm this, because I was trying with passing t from WithTranslation ( typescript ) , I passed the t which mean TFunction, and it wont load the translation, but in second or third route it loaded 😅 , I was set suspense to false also in the init, but not solving my problem 😔

**Comment by adrai** [comment]
hmm... sorry but if it's only related to react-native, you may try to debug it on your own... 😥

**Comment by rbayuokt** [comment]
> hmm... sorry but if it's only related to react-native, you may try to debug it on your own... 😥

oh no, sorry sir, do you know the best alternative lib for translation for react native ?

**Comment by adrai** [comment]
Why not debug more the verify what the issue is?
Can't you share a complete reproducible example? Create a public github repository... that way we can exclude any config or usage error...

**Comment by rbayuokt** [comment]
> Why not debug more the verify what the issue is? Can't you share a complete reproducible example? Create a public github repository... that way we can exclude any config or usage error...

I just fixed the problem, in App.tsx we need to wrap the navigation with this one

```
 <I18nextProvider i18n={i18n}>
      <React.Suspense fallback={null}>
           ...
       </React.Suspense>
 </I18nextProvider>
```
it solved my problem, for react native

**Comment by RickardZrinski** [comment]
Having the same issue when upgrading from React Native 0.63.3 to 0.66.3. One of the bigger changes between these releases is bumping to React 17.

It's only an issue when using useTranslation inside App.js.

**Comment by RickardZrinski** [comment]
Seems to be a timing issue where the i18n instance isn't yet initialised when running `useTranslation`. i18n is undefined in `useTranslation` which gives a `You will need to pass in an i18next instance by using initReactI18next` warning.

Our `i18next.use(...).init(...)` call lives inside our `i18n.js` file, from which we export a module with a few functions. For some reason changing our import from `import { fetchTranslations } from './i18n';` to `import i18n from './i18n';` in App.js gets rid of the error entirely.

Placing the `i18next.use(...).init(...)` in an `init` function instead and calling it above the App component also works.

Never had this issue on RN 0.63.3.
