### ISSUE TITLE
When trying to use <Trans /> component with components props that uses material tooltip the app crashes 

### ISSUE THREAD

**Issue by gg0203** [i18next/react-i18next#1406]
## 🐛 Bug Report

When trying to use <Trans /> component with components props that uses material tooltip the app crashes 

## To Reproduce

I created this codesandbox to reproduce:

https://codesandbox.io/s/small-rain-5bso5?file=/src/App.js

## Expected behavior

The app should not crash and i should be able to use a material tooltip with Trans component

**Comment by jamuhl** [comment]
rather sure tooltip uses some sort of "react portal" to get the element onto the root element in dom. Which makes it unusable inside Trans. Means the problem lies in the nature of the tooltip component not in Trans component.
