### ISSUE TITLE
node_modules/react-i18next/ts4.1/index.d.ts(259,35): error TS2344: Type 'undefined' does not satisfy the constraint 'KeyPrefix<N>'.

### ISSUE THREAD

**Issue by aminvb12** [i18next/react-i18next#1408]
#### You have already researched for similar issues?
It's not uncommon that somebody already opened an issue or in best case it's already fixed but not merged. That's the reason why you should [search](https://github.com/i18next/i18next/issues) at first before submitting a new one.
Search also on [StackOverflow](https://stackoverflow.com/) or similar.

#### Are you sure this is an issue with i18next or are you just looking for some help?

Issues should only be posted in this repository after you have been able to reproduce them and confirm that they are a bug or incorrect/missing information in the [docs](https://www.i18next.com/) [here](https://www.i18next.com/) or [here for react-i18next](https://react.i18next.com/).

For all other questions, requests, help resolving an issue, or if you are not sure if this is the right place, please do not open an issue here. Instead, ask a question on [StackOverflow](https://stackoverflow.com/) or similar.

If you have issues with the [i18next.com](https://www.i18next.com) site, please open an issue [here](https://github.com/i18next/i18next-gitbook/issues) or [here for react.i18next.com](https://github.com/i18next/react-i18next-gitbook/issues).

**Comment by adrai** [comment]
https://github.com/i18next/react-i18next/issues/1407
