### ISSUE TITLE
TS Throws "Type instantiation is excessively deep and possibly infinite. (TS2589)"

### ISSUE THREAD

**Issue by W3ND31** [i18next/react-i18next#1409]
## 🐛 Bug Report

TS Throws "Type instantiation is excessively deep and possibly infinite. (TS2589)"

## To Reproduce

My configuration is as follow:

File structure
![image](https://user-images.githubusercontent.com/22237679/142711899-083554ae-1ce8-4f50-a0b9-8ed2a6520518.png)

Code exemple (with error) https://codesandbox.io/s/peaceful-hypatia-m5fwf?file=/src/App.tsx

## Expected behavior

I expected that this error doesn't exist

## Your Environment

- *runtime version*: node v16
- *i18next version*:  21.5.2
- *os*:  Linux (Manjaro Gnome)

**Comment by adrai** [comment]
https://github.com/i18next/react-i18next/blob/f454af54af916513eafc23f5b815ea6d3abe19e9/ts4.1/index.d.ts#L15

https://github.com/i18next/react-i18next/issues/1222

**Comment by pedrodurek** [comment]
Hey @W3ND31, It's not possible to iterate over the keys (to infer the proper type) when relying on index signature. You should remove the `extends ResourceLanguage` from your interface.

**Comment by W3ND31** [comment]
> Hey @W3ND31, It's not possible to iterate over the keys (to infer the proper type) when relying on index signature. You should remove the `extends ResourceLanguage` from your interface.

@pedrodurek Worked but with a little "workaround".

When i remove the `extends ResourceLanguage` from the interface, on /i18n/index.ts gives an error that could only be resolved with the casting on locales file (as you can see here https://codesandbox.io/s/peaceful-hypatia-m5fwf?file=/src/i18n/locales/index.ts)

So, thanks for your help!
