### ISSUE TITLE
`TS2589: Type instantiation is excessively deep and possibly infinite.` with Typescript 4.5.2 and react-i18next 11.14.3

### ISSUE THREAD

**Issue by xseignard** [i18next/react-i18next#1417]
## 🐛 Bug Report

Using a `<Trans>` component with a lot of namespaces trigger the following typescript error:

```
TS2589: Type instantiation is excessively deep and possibly infinite.
```

The error starts to happen as soon as there's more than 45 namespaces.

You can check this behavior by modifiying the following file: https://github.com/xseignard/react-i18n-ts-bug-repro/blob/main/src/i18n/locales/en/index.ts

- export from `ns0` to `ns44` and there's no errors
- export from `ns0` to `ns45` (or more) and the error pops

Related issue comment: https://github.com/i18next/react-i18next/issues/1394#issuecomment-976853798

## To Reproduce

Here is a repo to repro: https://github.com/xseignard/react-i18n-ts-bug-repro

```
git clone git@github.com:xseignard/react-i18n-ts-bug-repro.git
npm i
npm run types
```

## Expected behavior

No typescript error

## Your Environment

- *runtime version*: node v14.18.1
- *typescript version*: 4.5.2
- *i18next version*: 21.5.3
- *react-i18next*: 11.14.3
- *os*: Mac

**Comment by jamuhl** [comment]
please check https://github.com/i18next/react-i18next/issues?q=Type+instantiation+is+excessively+deep

**Comment by xseignard** [comment]
I did, that why I'm opening yet another issue on that subject.

**Comment by pedrodurek** [comment]
The typescript team improved the way recursive types work, but it seems there are still some limitations. I'll try to find a workaround to suppress the error.

**Comment by pedrodurek** [comment]
Hey guys, I didn't manage to find a way to suppress the error, typescript team increased the number of recursive type instantiations from `50` to `100` (on TS 4.5), but it's not enough for 49+ namespaces. The workaround (`extends infer A ? A : never`) that I've been using to suppress the error **works**, but only when you call a function directly, not rendering as JSX 😢 . But I have a few suggestions that should work:

1 - Call `Trans` function directly when `useTranslation` receives an array:
```tsx
const { t } = useTranslation(["ns1"]);

return (
  <div className="App">
	{Trans({ t, i18nKey: "ns1:name", children: <h1>Weird</h1> })}
  </div>
);
```
2 - Add a ts-ignore (don't recommend)
```tsx
<div className="App">
  {/* @ts-ignore */}
  <Trans i18nKey="ns10:name" t={t}>
    <h1>Weird</h1>
  </Trans>
</div>
```
3 - Use [patch-package](https://www.npmjs.com/package/patch-package), to increase the number of instances [here](https://github.dev/microsoft/TypeScript/blob/main/src/compiler/checker.ts#L16751) to something like:
```tsx
if (instantiationDepth === 200 || instantiationCount >= 5000000) {
```

You can find more info about the discussion here: https://github.com/microsoft/TypeScript/issues/34933

**Comment by danielo515** [comment]
I don't have too many namespaces, I just have two, so where does my problem lives then?
And funnily it only happens in one part of my code. I mean, I have imported useTranslation dozen of times and just one is complaining about this problem, but it is not giving type checking either. Does it only complain the first time it finds the function being used or what.

Something to note is that my keys are deeply nested, can that be the root of the problem? They can look something like this:
````ts
t
('OneOffPayItemForm.details.title.label')
```

**Comment by pedrodurek** [comment]
Hey @danielo515, that can also happen if there is something wrong with your configuration (`react-i18next.d.ts`), can you share a simplified version of your configuration on codesandbox?

**Comment by danielo515** [comment]
Hello @pedrodurek , thanks for your answer.

This is my `react-i18next.d.ts` contents:

```
// import the original type declarations
import 'react-i18next';
// import all namespaces (for the default language, only)
import translation from './locales/en/translation.json';
import toast from './locales/en/toasts.json';
declare module 'react-i18next' {
  // and extend them!
  interface CustomTypeOptions {
    // custom namespace type if you changed it
    defaultNS: 'translation';
    // custom resources type
    resources: {
      translation: typeof translation;
      toast: typeof toast;
    };
  }
}
```

If you have a condesandbox template I will happily try to reproduce my problem there.

**Comment by danielo515** [comment]
I just reproduced the issue on a codesandbox and, while trying to slim down my translation file to not expose too much information a bit I accidentally fixed it. I'll do a diff of the files to see if I can determine where the problem is

**Comment by danielo515** [comment]
Ok, now I think I fixed it on my own repository too. Seems that my import path on the `d.ts` file was incorrect, but typescript was not complaining and just saying it was "any".
After I fixed the path now I get what looks like proper types and error messages. I have now hundreds of those, but most are because the t function doesn't seem to be returning a string

**Comment by xseignard** [comment]
Hi
So we ended up relying on option 1 described in @pedrodurek's [comment](https://github.com/i18next/react-i18next/issues/1417#issuecomment-983951906)

And got rid on of the annoying `TS2589` error.
Tested on TypeScript 4.5.5

**Comment by danielo515** [comment]
Hello. I think I am facing again an issue related to this problem (this time for real).
Seems that our default translation namespace is too big. We just flattened it to not be too nested (and therefore don't require any recursivity) but now the sum type seems so big that node runs out of memory while type-checking. Has anyone experienced such a problem? Do you know what is the maximum "keys" per namespace that will not break node?

**Comment by pedrodurek** [comment]
Hey @danielo515, can you create a similar (as nested as yours is) example on codesanbox, so I can investigate it?

**Comment by pedrodurek** [comment]
You can use this one https://codesandbox.io/s/react-i18next-typed-keys-bug-forked-x77zq

**Comment by danielo515** [comment]
I already started one, but thank you very much

**Comment by laneschmidt** [comment]
@danielo515 same issue here, subscribing

**Comment by tiavina-mika** [comment]
Hello.
this solution worked for me:
```
  const { i18n } = useTranslation<any>();
```

**Comment by the-night-wing** [comment]
Experienced the same issue, the reason was similar to the one @danielo515 had. In my case, it happened due to unexported resources:
![image](https://user-images.githubusercontent.com/45423106/180176752-54e7d3b3-5883-4af6-943d-6959a0cfbde7.png)
![image](https://user-images.githubusercontent.com/45423106/180176865-bfe78b51-66a3-4f21-b9a0-96d381acfec2.png)
![image](https://user-images.githubusercontent.com/45423106/180176955-6f3387fa-9d92-4644-825c-c998ce279d3c.png)

**Comment by DominicTobias** [comment]
Ah thanks @the-night-wing and @tiavina-mika I didn't set this stuff up and noticed it was `resources: typeof resources['en']` but should have been `resources: typeof resources['en-US']` for my use case

**Comment by mstuercke** [comment]
I found two workarounds to get rid of the error when using the `useTranslation()` hook. Just type the hook. Hope that helps someone.

```typescript
// before
const {t} = useTranslation(['foo', 'bar'])

// workaround 1 - explicit typing
const {t} = useTranslation<['foo', 'bar']>(['foo', 'bar'])
// or
const {t} = useTranslation<('foo' | 'bar')[]>(['foo', 'bar'])


// workaround 2 - use any
const {t} = useTranslation<any>(['foo', 'bar'])
```

**Comment by kai-dorschner-twinsity** [comment]
@mstuercke sounds like you are avoiding the types completely with your workaround. You could've just deleted the react-i18next.d.ts file entirely and have the same effect.

**Comment by mstuercke** [comment]
@kai-dorschner-twinsity You're right. I see it as a temporary fix until there is a better solution. I'm not a fan of that workaround either.

**Comment by Karmalakas** [comment]
> Hello. in `react-i18next.d` , I have just changed `type resources: typeof resources[DEFAULT_LANGUAGE];` to `resources: typeof resources.en;`

That fixed the issue for me on v15.4
Weird.. Wonder why using variable ends up in deep nesting

**Comment by fedeq** [comment]
I was having this issue only in one instance of useTranslation(). It was because I had something like this:

```
{
  product1: {
    features: ["feature 1", "feature2"]
  },
  product2: {
    features: [] -> this empty array was the issue
  }
}
```

**Comment by rindev0901** [comment]
> I was having this issue only in one instance of useTranslation(). It was because I had something like this:
> 
> ```
> {
>   product1: {
>     features: ["feature 1", "feature2"]
>   },
>   product2: {
>     features: [] -> this empty array was the issue
>   }
> }
> ```

Just like in my case, you simply need to add a value to the array.
