### ISSUE TITLE
Loading translations per component

### ISSUE THREAD

**Issue by ianschmitz** [i18next/react-i18next#1420]
## 🚀 Feature Proposal

I'm going to be honest, i'm not sure what the final API of something like this may look look like. That being said i've been using this pattern for quite a while now and it provides a fantastic developer experience (IMO), and keeps the translation files scoped at a component level which i've found easier to maintain. I would love to see this be supported first class within the React hook, most importantly within the TypeScript types of the `UseTranslationResponse`.

## Motivation

As a React developer when developing a new feature i generally think at a component level. When introducing new language strings i typically consider:

> Does this language string apply generally throughout the application, or is it specific to this component?

If it's generally applicable throughout the application, i add it to a `common.lang.json` file, otherwise i add it to a relative `ComponentName.lang.json` file alongside `ComponentName.tsx`. See my example below to get some more insight.

## Example

Note there are a couple quirks with the types i defined in `useTranslation.ts`. The most common one i've noticed is when referring to common namespace such as `t("common:something")` it returns `never`, but component specific keys seem to have the correct return type.

`Component.tsx`
```ts
import i18n from "./i18n";
import useTranslation from "./useTranslation";
import resources from "./Component.lang.json";

export default function Component() {
  // See useTranslation.ts for impl. details to give strong types
  const { t } = useTranslation({ ns: "Component", resources });

  // Note that t() is type safe here. 
  // You can't refer to any other keys that aren't in `Component.lang.json` or `common.lang.json`.
  const componentSpecificString = t("foo");
  const commonString = t("common:bar");
}
```

`i18n.ts`:
```ts
import common from "./common.lang.json";

declare module "react-i18next" {
    interface CustomTypeOptions {
        defaultNS: "common";
        resources: {
            common: typeof common;
            [key: string]: Resources;
        };
    }
}

i18n
    .use(LanguageDetector)
    .use(initReactI18next)
    .init({
        defaultNS: "common",
        fallbackLng: "en",
        resources: {
	      en: {
	          common,
	      },
	   }
    });

export default i18n;
```

`useTranslation.ts`:
```ts
import { StringMap, TFunctionResult, TOptions } from "i18next";
import { useMemo } from "react";
import {
    CustomTypeOptions,
    DefaultNamespace,
    DefaultResources,
    Resources,
    TFuncKey,
    TFuncReturn,
    useTranslation,
    UseTranslationResponse,
} from "react-i18next";

/**
 * A wrapper around {@link useTranslation} that adds language resources to the
 * `i18n` instance.
 * @param ns The namespace of the current component. This will be set as the
 * default namespace for the `t` function.
 * @param resources The language resources to add to the `i18n` instance.
 * Resources will be added to the provided namespace.
 * @returns The same return value of {@link useTranslation}, but strongly typed
 * to the available resource keys which are the provided resources, or the
 * common resources using a `common:` prefix.
 */
export function useTranslations<
    TCustomResources extends { [ns in N]: R } & DefaultResources,
    R extends Resources,
    N extends string = DefaultNamespace,
>(
    {
        ns,
        resources,
    }: {
        ns: N;
        resources: R;
    } = {
        ns: "" as N,
        resources: {} as R,
    },
) {
    // Modified type copied from react-i18next type for `t()`. This type
    // strongly types the `key` parameter.
    // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
    const trans: Omit<UseTranslationResponse<N, undefined>, "t"> & {
        t: <
            TKeys extends  // Default namespace (provided by `ns` param) doesn't need a prefix.
                | TFuncKey<N, undefined, TCustomResources>
                // Add in common namespace types which require `common:` prefix.
                | TFuncKey<[DefaultNS], undefined, TCustomResources>
                | TemplateStringsArray extends infer A
                ? A
                : never,
            TDefaultResult extends TFunctionResult = string,
            // eslint-disable-next-line @typescript-eslint/ban-types
            TInterpolationMap extends object = StringMap,
        >(
            key: TKeys | TKeys[],
            options?: TOptions<TInterpolationMap> | string,
        ) => TFuncReturn<N, TKeys, TDefaultResult, undefined, TCustomResources>;
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
    } = useTranslation(ns) as any;

    useMemo(() => {
        if (ns) {
            trans.i18n.addResourceBundle("en", ns, resources, true, true);
        }
    }, [ns, resources, trans.i18n]);

    return trans;
}
```

**Comment by pedrodurek** [comment]
Hey @ianschmitz, that can be done by having multiple type declarations. https://github.com/i18next/react-i18next/issues/1257#issuecomment-786089654

**Comment by ianschmitz** [comment]
@pedrodurek i don't quite follow. I don't see the overlap in your link and what i proposed. Perhaps i missed something?

**Comment by pedrodurek** [comment]
Perhaps I misunderstood the issue here, are you referring/suggesting to 
1 -  Refactor the `useTranslation` function to support loading translations per component?
2 - Infer the types based on the resources passed to `18n.addResourceBundle` function? If so, it's not possible, unless you're willing to have one `tsconfig` per component.
3 - Understand why it returns `never` for `t("common:something")`?

**Comment by ianschmitz** [comment]
More 1/2 than 3. The problem with 3 is likely just a slight issue in my custom types that i haven't got around to fixing yet.

I'm curious why 2 isn't possible? Isn't that essentially what i've demonstrated above?

**Comment by pedrodurek** [comment]
Hey @ianschmitz, sorry for the delayed response, very busy week 😅 .

> I'm curious why 2 isn't possible? Isn't that essentially what i've demonstrated above?

Not exactly, to use a similar approach, it would require a major restructuring on the `useTranslation` function. But I'm investigating other alternatives, I'll keep you posted.

**Comment by Karmalakas** [comment]
I assume this was never solved, right?

**Comment by charlesanim** [comment]
I'd appreciate any updates on this.
