### ISSUE TITLE
Type augmentation does not re-export all modules, like useTranslation hook

### ISSUE THREAD

**Issue by danielo515** [i18next/react-i18next#1421]
## Documentation issue

There is this page, which shows an amazing feature of this library with Typescript:

https://react.i18next.com/latest/typescript

However, if I create the declaration file that is specified on the first section, then the hook `useTranslation` is not recognized as part of the library and it starts to fail on all the imported components:

```
Module '"react-i18next"' has no exported member 'useTranslation'.ts(2305)
```

I can not do it all at once because I load the translations async so I need to create the declaration file

## Motivation

This is an outstanding feature, but with this problem we can not use it.

**Comment by danielo515** [comment]
Not sure if it may be the root of the problem, but I am using "typescript@4.4.4"

**Comment by danielo515** [comment]
For some reason, seems that the type definition file and the actual source code that uses it can not live in the same folder.
I just moved the types definition file to a `types` folder, which is latter included on `tsconfig.json` and it now works perfectly:

```ts
// tsconfig file
"include": ["./src/**/*", "./types"],
```

```

root/
├─ src/
├─ types/
│  ├─ react-i18next.d.ts
├─ tsconfig.json

```

**Comment by pedrodurek** [comment]
Hey @danielo515, I personally prefer placing type declarations outside the `src` path, but you can place them inside as well. It's probably some wrong with your tsconfig, try to follow this example: https://codesandbox.io/s/kind-framework-i5g0e?file=/src/react-18next.d.ts

**Comment by danielo515** [comment]
Thanks @pedrodurek , for now I will leave it as it is since it is now working and this is not a problem for me.
If I ever try to put it under the same directory and it still fails, I will come back here.

Thanks for your help.
