### ISSUE TITLE
Typescript section, no interpolation type definition

### ISSUE THREAD

**Issue by adelin-b** [i18next/react-i18next#1423]
## Documentation issue
On this documentation page we know how to extend the default type of translation using `declare module `react-i18next`
https://react.i18next.com/latest/typescript

However there is no description on how to extend the interpolation. This is doable since there is template literals 

And this guy done it : https://stackoverflow.com/a/58308279 (Look at his point n3 )

## Motivation

Having a way to have a nice interpolation type associated with every keys.

**Comment by pedrodurek** [comment]
Hey @adelin-b, it's not possible to get literal values from JSON files yet. https://github.com/i18next/react-i18next/pull/1193#issuecomment-778032161

Once it does, we can look into it.
