### ISSUE TITLE
Trans should allow html encoded character like `&lt; &amp; &gt;`

### ISSUE THREAD

**Issue by cuyl** [i18next/react-i18next#1424]
## 🐛 Bug Report

[Trans](https://react.i18next.com/latest/trans-component) should allow html encoded character like `&lt; &amp; &gt;`

## To Reproduce

[https://codesandbox.io/s/exciting-wescoff-kjz0j](https://codesandbox.io/s/exciting-wescoff-kjz0j)
## Expected behavior

Render `< & >` correctly.

Ref: https://github.com/i18next/i18next/issues/1567

## Your Environment

- *runtime version*:  node v16
- *i18next version*:  21.0.0
- *react-i18next version*: 11.10.0
- *os*: Mac, Windows, Linux

**Comment by jamuhl** [comment]
Feel free to provide a PR
