### ISSUE TITLE
Mocking useTranslation while testing gives typescript error

### ISSUE THREAD

**Issue by Nikhil-Vats** [i18next/react-i18next#1425]
## 🐛 Bug Report

Mocking the module doesn't work and gives the error - **TypeError: undefined is not a function**
```js
jest.mock('react-i18next', () => ({
  // this mock makes sure any components using the translate hook can use it without a warning being shown
  useTranslation: () => {
    return {
      t: (str: string) => str,
      i18n: {
        changeLanguage: () => new Promise(() => {}),
      },
    };
  },
}));
```

I tried changing useTranslation definition to `useTranslation: (namespace?: string) => {...}` because I also pass the namespace when I use hook but the error doesn't go away.

## To Reproduce
Put this block before a describe block or in setupTests.ts in react app or in beforeEach block in describe.
```js
jest.mock('react-i18next', () => ({
  // this mock makes sure any components using the translate hook can use it without a warning being shown
  useTranslation: () => {
    return {
      t: (str: string) => str,
      i18n: {
        changeLanguage: () => new Promise(() => {}),
      },
    };
  },
}));
```

## Expected behavior

Tests should work without error.

## Your Environment

- *runtime version*: node v16
- *i18next version*: 20.3.2
- *os*: Mac

Other info -
![image](https://user-images.githubusercontent.com/31413407/144833247-ea10027d-9c96-4714-8d87-417e73d9117e.png)

If I pass the config properly following [this example](https://react.i18next.com/misc/testing#testing-without-stubbing), the error goes away.

**Comment by pedrodurek** [comment]
Hey @Nikhil-Vats, this is actually not a typescript issue, but I'll try to help you!
Try like this:
```tsx
jest.mock('react-i18next', () => ({
  ...jest.requireActual('react-i18next'),
  useTranslation: () => {
    return {
      t: (str: string) => str,
      i18n: {
        changeLanguage: () => new Promise(() => {}),
      },
    };
  },
}));
```
Make sure you don't have any jest setup about `react-i18next`, so they don't get conflated.

**Comment by Nikhil-Vats** [comment]
@pedrodurek Thanks a lot for the quick response! In my login.test.tsx file, I tried but still got the same error -
```js
\\ imports

jest.mock('react-i18next', () => ({
  ...jest.requireActual('react-i18next'),
  useTranslation: (domain?: string) => {
    return {
      t: (str: string) => str,
      i18n: {
        changeLanguage: () => new Promise(() => {}),
      },
    };
  },
}));

describe(() => {
...
})
```

![image](https://user-images.githubusercontent.com/31413407/144907295-baa324be-3263-4010-a372-3037f56d808b.png)

**Comment by pedrodurek** [comment]
Hey @Nikhil-Vats, it seems to me that something is resetting or overlapping the mocks. It should work.

**Comment by NikhilPatel-Shell** [comment]
@pedrodurek , hey i am also facing the same issue. any solutions so far ?
