### ISSUE TITLE
Undocumented breaking change to Generic type 'UseTranslationResponse' requires 2 type argument(s).

### ISSUE THREAD

**Issue by amandapouget** [i18next/react-i18next#1427]
## 🐛 Bug Report

Upgrade from 11.11.4 to 11.14.3 produces error `Generic type 'UseTranslationResponse' requires 2 type argument(s).`

## To Reproduce

```js
(): UseTranslationResponse<'foobar'> => ...
```

## Expected behavior

No breaking change without doc on how to fix and preferably major version bump...

## Your Environment

11.14.3

**Comment by adrai** [comment]
@pedrodurek can you confirm?

**Comment by pedrodurek** [comment]
I'll update `UseTranslationResponse` to declare the default value for the second argument, for now, you can simple pass as `undefined` `UseTranslationResponse<'foobar', undefined>`

**Comment by adrai** [comment]
Thanks to @pedrodurek this should be fixed with v11.15.1.
