### ISSUE TITLE
Trans `shouldUnescape` prop is missing in .d.ts

### ISSUE THREAD

**Issue by predragnikolic** [i18next/react-i18next#1428]
## 🐛 Bug Report

Based on the documentation for the `<Trans />` component 
https://react.i18next.com/latest/trans-component#trans-props

There is a `shouldUnescape` prop,
but that prop doesn't exist in the index.d.ts file, 
so typescript complains

## To Reproduce

Try to use the `shouldUnescape` prop on the Trans compoent.

```js
export function SafeHtml({ htmlString }: Props) {
  return <Trans
    shouldUnescape
//  ^^^^^^^^^^^^^^  TS ERROR: Property 'shouldUnescape' does not exist on type 'IntrinsicAttributes & TransProps<Normalize<
    defaults={htmlString}
    components={ALLOWED_TAGS} />
}
```

## Expected behavior

No errors should be reported.

## Your Environment

- *runtime version*: node v14
- *i18next version*: 19.8.7
- *os*: Mac
- *any other relevant information*

**Comment by adrai** [comment]
Would you like to send a Pull Request to address this? Remember to add unit tests.

**Comment by predragnikolic** [comment]
I tried to override the react-i18next type:
```diff

declare module "react-i18next" {
  // add i18n translations type safty-https://stackoverflow.com/questions/58277973/how-to-type-check-i18n-dictionaries-with-typescript#answer-65348832
  export function Trans<
  K extends TFuncKey<N> extends infer A ? A : never,
  N extends Namespace = DefaultNamespace,
  E extends Element = HTMLDivElement
+  >(props: TransProps<K, N, E> & { 
+    shouldUnescape?: boolean
+   }): React.ReactElement;
}
```

And that silences the typescript error,
BUT although I added the `shouldUnescape` prop:
```jsx
import { Trans } from "react-i18next"

export function Example() {
  return <Trans
    shouldUnescape
    defaults={"<p>Hello&nbsp;you</p>"} />
}
```
 characters like `&nbsp;` are still not escaped.

Do you see any mistake in my code?

**Comment by predragnikolic** [comment]
> Would you like to send a Pull Request to address this?

No, not at the moment :)

**Comment by adrai** [comment]
@pedrodurek Can you help?
//cc: @cuyl

**Comment by predragnikolic** [comment]
@adrai, 
btw thanks for the quick replies!
