### ISSUE TITLE
Have a way to use <Trans> component with plural and natural language keys

### ISSUE THREAD

**Issue by eMerzh** [i18next/react-i18next#1431]
## 🚀 Feature Proposal

When using Trans component with plural you can't really use natural language keys.
While using t() with are using the plural: ...  option to define the string to display in case of plural

## Example

We could maybe use a plural props 🤔 
like : 
```jsx
<Trans count={12}>I need to buy {{count: 12}} <b>things</b></Trans>
```
=>
```jsx
<Trans count={12} plural="I need to buy {{count}} <1>things</b>">I need to buy {{count: 12}} <b>thing</b></Trans>
```

**Comment by adrai** [comment]
Why not add an i18nKey looking like to be natural language?

`<Trans count={12} i18nKey="I need to buy {{count}} <1>things</b>">I need to buy {{count: 12}} <b>thing</b></Trans>`

**Comment by eMerzh** [comment]
mmh why not... 
but at the moment if i do 
```jsx
<Trans count={contentCount} i18nKey="I need to {{spaceName}}  (<3>{{count}}</3> contents)">
  I need to {{ spaceName: succession.space.name }}&nbsp;(<b>{{ count: succession.contentCount }}</b> content)
</Trans>
```

i get in my extract (before saving that in po)
```jsx
  'I need to {{spaceName}} (<3>{{count}}</3> content)': {
    value: 'I need to {{spaceName}} (<3>{{count}}</3> content)',
    locations: [ [Object] ],
    context: null,
    plural: undefined
  },
```

so it doesn't seems to work

**Comment by adrai** [comment]
> 
> ```jsx
> 
>   'I need to {{spaceName}} (<3>{{count}}</3> content)': {
> 
>     value: 'I need to {{spaceName}} (<3>{{count}}</3> content)',
> 
>     locations: [ [Object] ],
> 
>     context: null,
> 
>     plural: undefined
> 
>   },
> 
> ```
> 

Sorry, but is that extract? It's not generated by saveMissing, right?

**Comment by eMerzh** [comment]
exact... i'm checking if it's an issue of the extractor ....

**Comment by eMerzh** [comment]
maybe i'm doing something wrong but using  i18next-parser i got something like this

```json
  "I need to {{spaceName}}\u00a0 (<3>{{count}}</3> contents)_one": "I need to {{spaceName}}&nbsp;(<3>{{count}}</3> content)",
  "I need to {{spaceName}}\u00a0 (<3>{{count}}</3> contents)_other": "I need to {{spaceName}}&nbsp;(<3>{{count}}</3> content)",
```

**Comment by adrai** [comment]
If this is not what you expect, open an issue in that repository.

**Comment by eMerzh** [comment]
I can do that... thanks for your help ... 
but in theory for you,
```jsx
<Trans count={12} i18nKey="KEY plural">KEY singular</Trans>
```
i18nKey can be used to to store of plural while the children are used as singular?

**Comment by adrai** [comment]
there is no difference between dot notation keys and natural language keys in i18next, so whatever i18nKey you use, it will always resolve with the appropriate plural suffix (key_one, key_other, etc.)

**Comment by eMerzh** [comment]
Many Thanks for the help ....
but if i use t() ... i can specify the plural and that will be used in the "main lang" (here english) when there is no translations

like this 
```jsx
{t('1 new activity', {
  plural: '{{ count }} new activities',
  count: newUpdatesCount,
})}
```

then i'll have correct fallback for english and translations for other langs .. but here it doesn't seems that english will be correct right?

**Comment by adrai** [comment]
Sorry, I don't understand what you're doing. Never seen such a plural property usage.
Can you provide a complete codesandbox example?
