### ISSUE TITLE
No method of escaping single quote in translation JSON works

### ISSUE THREAD

**Issue by mmacu** [i18next/react-i18next#1432]
## 🐛 Bug Report
No method of escaping single quote in `translation.json` seems to work. Neither `\'` nor `''` nor `\\'` nor `&apos;`. Did I miss a method or is there no option of putting single quote into translation JSON?

**Comment by adrai** [comment]
Sorry, but what do you exactly mean?

=> https://codesandbox.io/s/react-i18next-example-forked-qy4dj?file=/src/i18n.js:663-726

**Comment by mmacu** [comment]
Hey. Sorry. I've even started modifying your project to show the issue [here](https://codesandbox.io/s/react-i18next-example-forked-nt4ho?file=/src/app.js), but it works. After testing locally it works as well. Visual Studio Code was highlighting the line with single quote red, that's why I've started lookin for a ways of escaping, but seems it have been working without escape at all. Sorry about this.
