### ISSUE TITLE
Unescape soft-hypen

### ISSUE THREAD

**Issue by nilsmehlhorn** [i18next/react-i18next#1435]
## 🐛 Bug Report

The `<Trans/>` component has the property `shouldUnescape` to allow unescaping of HTML entities like `&lt;` or `&amp;` to become `<` and `&` respectively. However, this mechanism only works for a subset of HTML entities, in particular it does not work for soft-hyphens: `&shy;` won't turn into the invisible soft hyphen character (`U+00AD`).

## To Reproduce

Here's a [codesanbox](https://codesandbox.io/s/react-i18next-forked-2j7o6) showing the issue. You can also reproduce this by using the `<Trans/>` component as follows with a translation string that includes `&shy`: `<Trans shouldUnescape={true}>`

## Expected behavior

`&shy;` should be unescaped into the invisible soft hyphen character (`U+00AD`).

## Your Environment

- *runtime version*: Node 14, Chrome/FF
- *i18next version*: 11.15.1
- *os*: Windows, Linux

**Comment by adrai** [comment]
@cuyl what's your thought about this?

**Comment by nilsmehlhorn** [comment]
I was going to submit a PR based on this one: https://github.com/i18next/react-i18next/pull/1430/files

However, I just found out that an addition like this would not longer work for the current implementation which seems to use [html-escaper](https://www.npmjs.com/package/html-escaper) here https://github.com/i18next/react-i18next/blob/83cc2b63622b9b872815767d6307208ffbfb22a0/src/Trans.js#L249

**Comment by nilsmehlhorn** [comment]
The unescape implementation by html-escaper is limited to HTML entities which might introduce security issues and the author has stated that it will remain like that: https://github.com/WebReflection/html-escaper/issues/4#issuecomment-847134146

The thing is, I'd like to specify soft hyphens in my translations without introducing invisible characters in the source. Therefore, I'd rather use `&shy;` and have it unescaped into the invisible character during render.

**Comment by nilsmehlhorn** [comment]
How about moving to a different library for decoding HTML entities like [html-entities](https://github.com/mdevils/html-entities)? 

Another idea could be allowing to supply a custom pre-pass function instead of defaulting to `unescape` from html-escaper. That'd be one dependency less for this library and allow for further customization, however, it'd probably be a breaking change.

Either way, I'd be willing to submit a PR for one these approaches :)

**Comment by adrai** [comment]
> How about moving to a different library for decoding HTML entities like [html-entities](https://github.com/mdevils/html-entities)? 
> 
> 
> 
> Another idea could be allowing to supply a custom pre-pass function instead of defaulting to `unescape` from html-escaper. That'd be one dependency less for this library and allow for further customization, however, it'd probably be a breaking change.
> 
> 
> 
> Either way, I'd be willing to submit a PR for one these approaches :)

What do you think @cuyl ?

**Comment by cuyl** [comment]
I'm for less dependencies. Maybe we can allow user pass their own decode function.

**Comment by adrai** [comment]
@nilsmehlhorn would you like to provide a PR?

**Comment by danielsamuels** [comment]
&copy; is another entity which doesn't get unescaped as expected.

**Comment by agritchie** [comment]
The forward slash symbol ('/') is another one (as pointed out in https://github.com/i18next/react-i18next/issues/1487). This creates problems using <Trans/> to embed links.
@adrai Could this be re-opened?

**Comment by adrai** [comment]
@nilsmehlhorn do you still want to provide a PR?

**Comment by nilsmehlhorn** [comment]
Yes, working on it right now!
