### ISSUE TITLE
Release notes / changelog

### ISSUE THREAD

**Issue by zehawki** [i18next/react-i18next#1437]
It will be good to have some details as to what has changed between v10 and v11. The site only has this from long time ago: https://react.i18next.com/latest/migrating-v9-to-v10#new-in-v10

**Comment by adrai** [comment]
That was no bigger rewrite like the one between v9 and v10: https://github.com/i18next/react-i18next/blob/master/CHANGELOG.md#1100

**Comment by zehawki** [comment]
Ah, thank you for pointing me to that doc. I was looking under https://github.com/i18next/react-i18next/releases and didnt see anything.
