### ISSUE TITLE
t function runs multiple times

### ISSUE THREAD

**Issue by phoique** [i18next/react-i18next#1438]
## 🐛 Bug Report

The t function I call from useTranslation loops 3 times in useEffect.

## To Reproduce

```js
const { t } = useTranslation();
React.useEffect(() => {
toast(t('pages.title'), t('pages.titledesc'), 'danger');
}, [t]);
```

## Expected behavior
Working once in useEffect.

## Your Environment

- *runtime version*:. node v16.13.0
- *i18next version*: 21.6.5
- *os*: Mac
- *react-i18next*:  ^11.15.3,

**Comment by adrai** [comment]
https://github.com/i18next/react-i18next/issues/1228#issuecomment-762202043
