### ISSUE TITLE
Property 'lng' does not exist on type 'TFunction'

### ISSUE THREAD

**Issue by alishaz-polymath** [i18next/react-i18next#1439]
## 🐛 Bug Report

Hi,
I'm trying to use `await getTranslation("en", "common");` to get a TFunction response. When I console log the result, I get `[Function: fixedT] { lng: 'en', ns: 'common', keyPrefix: undefined }` however, when I try to access the `lng`, I get a type error. I can access the key `lng` to get the value 'en' just fine, but the type error persists. I tried to find any documentation regarding the same or what the TFunction type is, but I was unsuccessful.
 
## To Reproduce
use `await getTranslation("en", "common");` and then try to access the `lng` key to get its value. The Typescript throws an error:
`Property 'lng' does not exist on type 'TFunction'.ts(2339)` 

## Expected behavior

The typescript shouldn't throw an error

## Your Environment

- *runtime version*: 16.11.10, Chrome/Firefox
- *i18next version*: i.e. 8.9.0
- *os*: Windows

**Comment by adrai** [comment]
probably this has to be extended here somewhere: https://github.com/i18next/i18next/blob/master/index.d.ts

//cc @pedrodurek

**Comment by adrai** [comment]
@alishaz-polymath can you please first provide a more complete example? I don't know the function `getTranslation` it might be you're using it the wrong way.
btw: why do you want to access the lng property?

**Comment by adrai** [comment]
will close this, as it looks like wrong usage...

**Comment by alishaz-polymath** [comment]
Apologies for the incomplete info. Here's the `getTranslation` function:
`import i18next from "i18next";
import { i18n as nexti18next } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

export const getTranslation = async (locale: string, ns: string) => {
  const create = async () => {
    const { _nextI18Next } = await serverSideTranslations(locale, [ns]);
    const _i18n = i18next.createInstance();
    _i18n.init({
      lng: locale,
      resources: _nextI18Next.initialI18nStore,
      fallbackLng: _nextI18Next.userConfig?.i18n.defaultLocale,
    });
    return _i18n;
  };
  const _i18n = nexti18next != null ? nexti18next : await create();
  return _i18n.getFixedT(locale, ns);
};
`
And I'm trying to access the `lng` property to get the language used for translation in that TFunction definition

**Comment by adrai** [comment]
Sorry, but this looks totally strange... and is also related to [next-i18next](https://github.com/isaachinman/next-i18next)
if you're using the useTranslation hook you can get the current language from there (i18n.resolvedLanguage): https://react.i18next.com/latest/usetranslation-hook
or you can use the router information like here: https://github.com/isaachinman/next-i18next/blob/master/examples/simple/pages/index.js#L22
or on server side, you get it here: https://github.com/isaachinman/next-i18next/blob/master/examples/simple/pages/index.js#L43

**Comment by alishaz-polymath** [comment]
Thank you for your suggestions. Unfortunately our setup is a little more complicated and we can't really utilize these, not yet anyway. I was wondering if accessing the `lng` from the `getFixedT()` was actually properly supported or not, hence thought it might be a bug that I can access it but it throws typescript error.
Will explore this further and let you know if there are any findings on my end. :)

**Comment by adrai** [comment]
If you have access to the i18next instance you can simply use: `_i18n.resolvedLanguage` https://www.i18next.com/overview/api#resolvedlanguage

**Comment by jamuhl** [comment]
that fixedT.lng is basically an internal - not needed for exposed API: https://github.com/i18next/i18next/blob/master/src/i18next.js#L387

fixedT.lng is same as the lng you pass in

**Comment by alishaz-polymath** [comment]
Ah, okay. Makes sense! 
But if we're passing in `lng` for sure at the time of getFixedT, we would have access to it since, like you mentioned, it is the same lng as we pass in. We need to "break down" the TFunction returned into a string with lng value so that we can then store it in the database. So, by the looks of it, in our case it should actually work fine, just that it isn't part of the typescript specification. Is that correct?

**Comment by jamuhl** [comment]
should work...but idk...what you're doing looks very strange to me...

**Comment by alishaz-polymath** [comment]
Yeah, I think I'll go for a one of the suggested methods instead of this hacky way I was pursuing. Thanks for the support guys! Appreciate it.
