### ISSUE TITLE
Is it possible to replace the <0></0> with dynamic JSX

### ISSUE THREAD

**Issue by vejandla** [i18next/react-i18next#1440]
I took the example and started from here 

https://github.com/i18next/react-i18next/issues/1383

Following is my translation text: 

`Following actions are pending <0></0>. please complete.`

After the translation, I'm expecting to see this

Following actions are pending [Action1](Action1), [Action2](Action2), [Action3](Action3). Please complete.

```jsx

<Trans i18nKey="HomeScreen.DynamicCount">
          {["green", "blue", "red"].map((color) => (
            <Link key={color} style={{ color }} to={color}>
              {color}
            </Link>
          ))}
        </Trans>

```

The number of actions and URLs is dynamic. [Using React router <Link> component to form the link.]

Here is my code sandbox example. It's just simply ignoring <0></0> and I'm not able to see links.

https://codesandbox.io/s/react-i18next-example-forked-wu7nb

**Comment by adrai** [comment]
Can you please describe more precisely what the actual problem is?
If I check your codesandbox example, I can see all links:
![image](https://user-images.githubusercontent.com/1086194/151305366-74cd2ed3-be5d-456b-9427-d163904d3986.png)

**Comment by vejandla** [comment]
@adrai  Thanks for looking into this. Appreciate your help. 

**I was able to figure out what the exact problem is.** It is happening in my project with the following use case.

1) we get translations from the backend API, once the user gets authenticated.
2) we are letting the app render without translations API getting resolved. Until this API is resolved all the localized labels just display the default value as the actual translation key.
3) After we get the translations we are adding the translations to i18n using the following func. `i18n.addResourceBundle("en", "translation", translationData)`
4) Since all over the app we are using `useTranslation` hook, those components are re-rendering again with localized text received from API. 
5) But, in the above problem I reported in the thread, we ended up using the `<Trans>` component and the <Trans component is already rendered by the time translations API gets resolved (step2 & step 3). `<Trans>` component is not re-rendering after step 3.

Updated the code sandbox similar to my application. 

https://codesandbox.io/s/react-i18next-example-forked-wu7nb

**Once we added the resource bundle to the i18n, can we trigger a render for the <trans> component?**

**Comment by adrai** [comment]
Currently afk... but it might be there is some bindI18nStore event...
or what should for sure trigger a rerender is i18n.changeLanguage

**Comment by vejandla** [comment]
Yes, I used the same and it worked for me. Is that the only or best solution?

Is it possible to expose the context or internally update the context whenever we add the resource bundle? Since Trans is using `useContext(I18nContext)` it will re-render whenever we get resource bundle? Just a thought.. I may be wrong.

**Comment by jamuhl** [comment]
No...it's a separation of concern...Trans only does what it does (Interpolate react components)...it does not rerender or load translations

**Comment by adrai** [comment]
This should also work, without changeLanguage: https://codesandbox.io/s/react-i18next-example-forked-geg0x?file=/src/i18n.js:1434-1478

![image](https://user-images.githubusercontent.com/1086194/151411789-84d38daf-00cd-4436-9899-e308783eb804.png)

**Comment by vejandla** [comment]
Thanks, @adrai. This worked, but I had to use `const {t} = useTranslation()` even though I do not need that hook. I am still wondering if Trans component is internally using the useContext, why is it not re-rendering when the store context gets updated? Am I completely off in this thought process?
