### ISSUE TITLE
TS error with namespaces in i18n keys

### ISSUE THREAD

**Issue by drichard-nexapp** [i18next/react-i18next#1441]
## To Reproduce

A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

```js
  import 'react-i18next'
  import { resources, defaultNS } from '../src/main/internationalization/i18n'
  
  declare module 'react-i18next' {
    interface CustomTypeOptions {
     defaultNS: typeof defaultNS
     resources: typeof resources['en'];
   }
  }
```

## Expected behavior

I expect for t function and i18nKey of trans component to guess that `ns:` works
If I put the namesapce in the use translation it works. The more problematic use case is the Trans component i18nkey

```js
 const { t } = useTranslation();
 confirmLabel={t('common:confirm')}

No error on this
```

## Your Environment

- *runtime version*: i.e. node v12
- *i18next version*: i.e. 19.9.2
- *react-i18next version*: i.e. 11.15.3
- *os*: Mac

**Comment by adrai** [comment]
Did you already had a look at: https://react.i18next.com/latest/typescript ?

**Comment by pedrodurek** [comment]
Hey @drichard-nexapp, in typescript projects, this pattern will only work when relying on multiple namespace, for example:
```tsx
 const { t } = useTranslation(['common']);
 confirmLabel={t('common:confirm')}
```

For this case, you should use this pattern:
```tsx
 const { t } = useTranslation();
 confirmLabel={t('confirm')}
```

The types were designed like that to improve compilation time.

**Comment by pedrodurek** [comment]
I'm closing this as it's working as expected
