### ISSUE TITLE
Suspense not using fallback with i18next-http-backend

### ISSUE THREAD

**Issue by hugomassing** [i18next/react-i18next#1443]
## 🐛 Bug Report

Hello, when using a backend to load my JSON file, Suspense is correctly set but will never trigger. In my understanding, Suspense should fallback when the JSON file is loading? 

## To Reproduce

A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

Here a codesandbox to reproduce : [https://codesandbox.io/s/create-react-app-forked-xli5v?file=/src/App.js]( https://codesandbox.io/s/create-react-app-forked-xli5v?file=/src/App.js)

## Expected behavior

I expect Suspense to fallback to my composent while the JSON file is loading. 

## Your Environment

- *runtime version*: Chrome 97
- *i18next version*: 21.6.10
- *os*: Mac
-  create-react-app 3.0.4

**Comment by jamuhl** [comment]
To trigger a Suspense something within the component has to throw a Promise which resolves on ready.

Your codesandbox is incomplete...you need to use useTranslation which does the magic of checking if the translations are loaded and triggering that Suspense behaviour

**Comment by adrai** [comment]
You're not calling useTranslation or t nowhere...
Compare with this example: https://dev.to/adrai/how-to-properly-internationalize-a-react-application-using-i18next-3hdb#separate

**Comment by hugomassing** [comment]
@jamuhl Ohhh that's why, in my implementation I made a backward compatible hook with `i18n.t` without using `useTranslation()`. Thanks for the help
