### ISSUE TITLE
PluralProps doesn't include `values`

### ISSUE THREAD

**Issue by mwalkerr** [i18next/react-i18next#1444]
## 🐛 Bug Report

The `PluralProps` type as defined in ts4.1/icu.macro.d.ts doesn't include the `values` prop, which is required if there is a placeholder value inside a pluralized translation

## To Reproduce

Without `@ts-ignore`, TS complains that `TS2322: Type 'string' is not assignable to type 'never'.`
```js
              <Plural
                i18nKey="pluralizationEmbedded" // optional key
                count={foxPlural}
                // @ts-ignore because values are required..
                values={{ animalColor }}
                $0={
                  <>
                    The nonexistant quick <Text style={textStyles.bold}>{animalColor}</Text> foxes.
                  </>
                }
                one={
                  <>
                    The quick <Text style={textStyles.bold}>{animalColor}</Text> fox.
                  </>
                }
                other={
                  <>
                    The # quick <Text style={textStyles.bold}>{animalColor}</Text> foxes.
                  </>
                }
              />
```

## Expected behavior

No type error

## Your Environment

- *runtime version*: React Native 0.63.4
- *i18next version*: 11.15.3
- *os*: Mac

**Comment by adrai** [comment]
Would you like to send a Pull Request to address this?

**Comment by mwalkerr** [comment]
@adrai Sure, I can attempt that. Should I use the same type that's used for `TransProps` of `values?: {}`? Should it go directly on `PluralProps`?

**Comment by pedrodurek** [comment]
As we don't infer other props based on `values`, it makes sense to me `values` to be `values?: {}` or `values?: object`. Feel free to open the PR @mwalkerr. Thanks for that!

**Comment by mwalkerr** [comment]
@adrai @pedrodurek Just opened one here: https://github.com/i18next/react-i18next/pull/1446. Haven't created too many Github PRs, lemme know if I'm missing anything :)
