### ISSUE TITLE
joinArrays option does not work

### ISSUE THREAD

**Issue by clement-escolano** [i18next/react-i18next#1449]
## 🐛 Bug Report

The option `joinArrays` is not taken into account by react-i18next for interpolating arrays.

## To Reproduce

https://codesandbox.io/s/ecstatic-cohen-dtlqq?file=/src/App.js

`t("welcome {{users}}", { users: ["John", "Jane"], joinArrays: " and " })` outputs `Welcome John,Jane`.

## Expected behavior

I expect the translation to be `Welcome John and Jane`.

## Your Environment

- *i18next version*: 21.6.11

**Comment by adrai** [comment]
joinArrays is for array values in the translation json, not for variables: https://www.i18next.com/translation-function/objects-and-arrays#arrays

**Comment by clement-escolano** [comment]
OK sorry, I misunderstood the goal of this option
