### ISSUE TITLE
v21.x.x of i18-next doesn't support plurals in objects

### ISSUE THREAD

**Issue by wolkyura** [i18next/react-i18next#1450]
## Documentation issue

The previous version of `i18-next` (`v20.x.x`) supports plurals in object, e.g.:

```json
{
  "object": {
    "key": "{{count}} value",
    "key_plural": "{{count}} values"
  }
}
```

```js
const { key } = t('object', { count: 1, returnObjects: true }); // key - 1 value
const { key } = t('object', { count: 10, returnObjects: true }); // key - 10 values
```

After upgrading `i18-next` to `v21.6.6` this functionality doesn't work:

```json
{
  "object": {
    "key_one": "{{count}} value",
    "key_other": "{{count}} values"
  }
}
```

```js
const object1 = t('object', { count: 1, returnObjects: true });
const object10 = t('object', { count: 10, returnObjects: true });
console.log(object1); // { "key_one": "1 value", "key_other": "1 values" }
console.log(object10); // { "key_one": "10 value", "key_other": "10 values" }
```

## Motivation

It will be good to improve documentation (Migration guide from `v20.x.x` to `v21.x.x`), so it explains how this feature works now or inform that this feature doesn't work using `v21.x.x` version.

**Comment by adrai** [comment]
v21.x.x is more consistent now.
In my opinion in v20.x.x, having the key being translated to plurals value, is wrong. Never saw such a usage with returnObjects to then pick the key from the result... for me this looks like a wrong usage for v20.x.x anyway. But maybe @jamuhl knows more?

**Comment by jamuhl** [comment]
agree...even think this is more of a coincidence that only works as long there is the neutral key -> won't work for other languages having multiple or no plural (I guess)
