### ISSUE TITLE
T() function not providing typescript IntelliSense (React Native Setup)

### ISSUE THREAD

**Issue by johnny-mcfadden-dailypay** [i18next/react-i18next#1454]
## 🐛 Bug Report

Following the documentation on https://react.i18next.com/latest/typescript the t() function isn't providing any TS IntelliSense.

## To Reproduce

The setup implemented currently: 

`i18n.ts` file with content: 

```js
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import en from 'translations/en-us.json';

const resources = {
  en,
};

i18n
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: 'en',
    debug: false,
    keySeparator: '.',
    ns: ['translation'],
    defaultNS: 'translation',
    interpolation: {
      escapeValue: false, // react already safes from xss
    },
    react: { useSuspense: false },
    compatibilityJSON: 'v3',
  });

/**
 * Export a t() method that is bound to a i18n instance.
 * Useful in places where we are not able to call the useTranslation hook to get the t() method.
 *
 * This helps solve an issue that arose with our use of the t() method in error-handling-service.ts
 * See:
 *  https://github.com/i18next/i18next/issues/1287
 *  https://github.com/dailypay/native-mobile/pull/856
 */
const t = i18n.t.bind(i18n);
export { t };

export default i18n;

```

`react-i18n.d.ts` file located at root (outside src) to overload TS typings :

```js
import 'react-i18next';
import en from './src/translations/en-us.json';

declare module 'react-i18next' {
  interface CustomTypeOptions {
    defaultNS: 'translation';
    resources: typeof en;
  }
}

```

The translations file `en-us.json` located at `src/translations/en-us.json` (trimmed down): 

```json
{
  "translation": {
    "common": { "phone": "What's your phone number?" }
    }
}
```

and finally the the `t()` function with expected typings behaviour inside an example component file:

```js
import { useTranslation } from 'react-i18next';

const PhoneNumber = () => {
  const { t } = useTranslation();

  return (  <FieldHeading title={t('common.phone')} /> )

```

## Expected behavior

TS support for the `t()` function when using string with key `.` separator as argument. 

When I import the `CustomTypeOptions`:

```js
import { useTranslation, CustomTypeOptions } from 'react-i18next' 
```

... and assign to simple let or const to see if the interface is typed, it appears to be perfectly typed but just not inside the `t()` function. 

<img width="863" alt="Screenshot 2022-02-23 at 11 43 20" src="https://user-images.githubusercontent.com/93137292/155313027-03a89a21-0da1-4cbb-839b-0a921847ba5d.png">

## Your Environment

- *runtime version*: node 16 
- Deps: `"typescript": "~4.5.5"`, `"i18next": "^21.5.3"`, `"react-i18next": "^11.15.5"` 
- *os*: Mac

**Comment by johnny-mcfadden-dailypay** [comment]
Just checking in on this to see if there is anything I can do to help?

**Comment by pedrodurek** [comment]
Hey @johnny-mcfadden-dailypay, sorry for the delayed response. It's seems to me there is an import or configuration issue. Can you share your `tsconfig.json`?

**Comment by johnny-mcfadden-dailypay** [comment]
Sure thing @pedrodurek,thanks for looking! 🙇 

```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "jsx": "react-native",
    "lib": ["dom", "esnext"],
    "moduleResolution": "node",
    "noEmit": true,
    "skipLibCheck": true, 
    "resolveJsonModule": true,
    "rootDirs": ["src", "stories"],
    "allowSyntheticDefaultImports": true, 
    "strict": true,
    "forceConsistentCasingInFileNames": true, 
    "noEmit": true
    "noUnusedLocals": true, 
    "noUnusedParameters": true, 
    "incremental": true,
    "baseUrl": ".",
    "paths": {
      "actions/*": ["src/actions/*"],
      "screens/*": ["src/screens/*"],
      "services/*": ["src/services/*"],
      "components/*": ["src/components/*"],
      "constants/*": ["src/constants/*"],
      "hooks/*": ["src/hooks/*"],
      "interfaces/*": ["src/interfaces/*"],
      "navig/*": ["src/navig/*"],
      "assets/*": ["assets/*"],
      "environment": ["environment.ts"],
      "core/*": ["src/core/*"],
      "containers/*": ["src/containers/*"],
      "lib/*": ["src/lib/*"],
      "navigators/*": ["src/navigators/*"],
      "analytics/*": ["src/services/analytics/*"],
      "state": ["src/state"],
      "dp-constants": ["src/dp-constants"],
      "tests/*": ["src/__tests__/*"],
      "mocks/*": ["src/__mocks__/*"],
      "android/*": ["android/*"],
      "ios/*": ["ios/*"],
      "storybook/*": ["storybook/*"],
      "styles/*": ["src/styles/*"],
      "utils/*": ["src/utils/*"]
    }
  },
  "extends": "expo/tsconfig.base"
}
```

**Comment by johnny-mcfadden-dailypay** [comment]
> Hey @johnny-mcfadden-dailypay, sorry for the delayed response. It's seems to me there is an import or configuration issue. Can you share your `tsconfig.json`?

I had a look around to see if I could spot something i'm missing but couldn't spot anything obvious. Really hoping it's just a small tsconfig tweak to support obj diving inside inside the string passed to `t()`🙏

**Comment by pedrodurek** [comment]
Hey @johnny-mcfadden-dailypay, as your type declarations is placed outside the src `path`, you should included it using the `files` reference under your tsconfig.
For example:
```json
{
  files: ['react-i18next.d.ts']
}
```
I'm usually in favour of using `includes` rather than adding files individually, so if you add new type declarations, you won't need to worry about adding them in the tsconfig. I usually create a path called `@types` on the root path, add the `@types` path to the `includes` reference, and place all type declarations there (`@types/react-i18next.d.ts`).
```json
{
  includes: ['@types']
}
```

**Comment by JulianVerouden** [comment]
Hi @johnny-mcfadden-dailypay I am currently experiencing similar problems and came across this issue. I made a test environment and got to the same step as you (where exampleObj is correctly typed) except when I tried your solutions they did not seem to work. Do you remember how you fixed this? I tried renaming `react-i18n.d.ts` to `i18n-resources.d.ts` and have also added `files: ['i18n-resources.d.ts']` to `tsconfig.json` but this does not seem to change anything. Is there something I am missing?

(Or if @pedrodurek has any ideas that would be very helpful!)

My environment:
- Runtime version: Node 16
- Dependencies: `"typescript": "^4.9.5"`, `"i18next": "^23.6.0"`, `"react-i18next": "^13.3.1"`
- OS: Ubuntu

My `tsconfig.json`:
```{
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": [
    "src",
  ],
  "files": [
    "i18n-resources.d.ts"
  ]
}

**Comment by Sathyanarayanan-Dhanuskodi** [comment]
The solution worked for me

_Filename: i18next.d.ts_

```
import 'i18next';
import en from './src/locales/en.json';

declare module 'i18next' {
  interface CustomTypeOptions {
    resources: typeof en;
  }
}
```
