### ISSUE TITLE
Fallback at the key level

### ISSUE THREAD

**Issue by s1mrankaur** [i18next/react-i18next#1455]
## 🚀 Feature Proposal

I am currently using http-chained-backend for network failures and have en as the fallback language.  In case a "key" is not found in "en.json ", I would like for i18n to look into the local en.json file before failing.  I would also like to fall back to a couple of different files if a given key is not found in "en.json". 
## Motivation

Have translations files from both front end and backend that I would not like to merge into 1. Also, I'd like for keys to be checked locally if not available in the file loaded over HTTP

## Example

1. I have en.json pushed to S3 and also in the local. I added a new key locally which is not yet available in the S3 File. In that case, that key should be loaded from the local en.json file.
2. The backend file is currently named "en-BE.json". If a key is not present in en.json, look for it in en-BE.json.

**Comment by adrai** [comment]
This is already possible but only on language or namespace level:

https://www.i18next.com/how-to/backend-fallback

https://www.i18next.com/principles/fallback

but if a namespace exists in both "backends" this will not work.
