### ISSUE TITLE
translation not working within iframe in gatsby project

### ISSUE THREAD

**Issue by Hiiiij** [i18next/react-i18next#1457]
**Describe the bug**
I'm using `gatsby` and `react-i18n` for translation along with [react-pdf/renderer's](https://react-pdf.org/) `PDFViewer` component, however the translation is missing within PDFViewer / iframe and only the translation keys are rendered instead, however it seems to work properly outside

**To Reproduce**
Steps to reproduce the behavior including code snippet (if applies):
1. Go to https://github.com/Hiiiij/gatsby-pdf
2. run `npm install`
3. run `npm start`

**Expected behavior**
`intro` key within the rendered / downloaded PDF should show the translated text as set in `translation.json`

**Current behavior**
only translation key is rendered instead

**Comment by adrai** [comment]
Sorry, don't know much about gatsby or [gatsby-plugin-react-i18next](https://github.com/microapps/gatsby-plugin-react-i18next) maybe @stevensacks or @jimmyn can help?

**Comment by adrai** [comment]
maybe this helps? https://andremonteiro.pt/gatsby-i18next-wrap-page-element/

**Comment by Hiiiij** [comment]
Thanx Adrai!

**Comment by Hiiiij** [comment]
I'm still not sure how to work around it, @stevensacks @jimmyn I would super appreciate it if you have any chance to look it up!! Thx in advance!

**Comment by stevensacks** [comment]
I have no idea, but a possible creative solution that comes to mind is to parse the strings (using `t()`), and pass them to the iframe using `Window.postMessage()`.

**Comment by adrai** [comment]
if there is no way to omit the iframe, you could try to initialize i18next within that iframe page

**Comment by Hiiiij** [comment]
@stevensacks, @adrai the problem I don't create or have control over the iframe since it's created by the React PDF library.

**Comment by adrai** [comment]
@jeetiss @diegomura any advices?
