### ISSUE TITLE
add context prop to <Trans> Component

### ISSUE THREAD

**Issue by zanona** [i18next/react-i18next#1464]
## 🚀 Feature Proposal

Add `context` prop to the `Trans` component. Previously mentioned over #837 

## Motivation
Just like we have `<Trans count={n}>`, we could also have the `context` prop to pass the option rather than having to define it under `tOptions`, which is less readable.

## Example

```jsx
//auth.title_login: 'Some nice <i>Title</i>'
<Trans context='login'>auth.title</Trans>
// instead of
<Trans tOptions={{context:'login'}}>auth.title</Trans>
```

**Comment by adrai** [comment]
Would you like to send a Pull Request to address this? Remember to add unit tests.

**Comment by adrai** [comment]
Too bad you didn't get in touch... I quickly did it myself. I hope this is ok.
v11.16.0 has just been released.

**Comment by zanona** [comment]
Wow, thanks a lot and sorry for not getting back to you. When thinking on the implementation, I've noticed that there could be a few problems with Typescript validation as the context would need to be tied to the custom type, but I believe in that case, it would need to be set to `any` as there's not much we can do there.

Thanks again for implementing this so quickly.

**Comment by adrai** [comment]
Sorry, missed to update the types: v11.16.1 should be better
