### ISSUE TITLE
Cannot save missing translations

### ISSUE THREAD

**Issue by laclance** [i18next/react-i18next#1465]
Hi I am receiving multiple errors when  adding saveMissing: true

## Errors

```
POST http://localhost:3000/locales/add/en/pos 404 (Not Found)

Access to fetch at 'https://api.locize.app/missing/{projectId}latest/en/pos' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

POST https://api.locize.app/missing/{projectId}/latest/en/pos net::ERR_FAILED 401
```

## To Reproduce

```js
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import ChainedBackend from 'i18next-chained-backend';
import LocizeBackend from 'i18next-locize-backend';
import HTTPBackendLocal from 'i18next-http-backend';
import { getEnv } from './utils';

const locizeOptions = {
  projectId: process.env.LOCIZE_PROJECT_ID,
  apiKey: process.env.LOCIZE_API_KEY,
  referenceLng: 'en'
};

i18n
  .use(ChainedBackend)
  .use(initReactI18next)
  .init({
    debug: getEnv() === 'dev',
    fallbackLng: 'en',
    fallbackNS: 'pos',
    defaultNS: 'pos',
    ns: ['pos'],
    saveMissing: true,
    interpolation: {
      escapeValue: false
    },
    backend: {
      backends: [LocizeBackend, HTTPBackendLocal],
      backendOptions: [locizeOptions]
    }
  });

export default i18n;

```

## Expected behavior

Translations should get added to locize automatically

## Your Environment

Ubuntu 20 / node 16 /  Chromium: 99
"locize-cli": "^7.9.1",
"next": "^12.1.0",
"react-i18next": "^11.15.5",
"i18next": "^21.6.13",
"i18next-chained-backend": "^3.0.2",
"i18next-http-backend": "^1.3.2",
"i18next-locize-backend": "^5.0.0",

**Comment by adrai** [comment]
the first POST error is caused by your http backend on localhost

the second error is caused because of the wrong api-key used (401)

btw: it's considered to not use saveMissing with the chained-backend: https://github.com/i18next/i18next-chained-backend#important-advice-for-the-usage-in-combination-with-savemissingupdatemissing

**Comment by laclance** [comment]
ok thank you, thats what i thought but api key is correct, so you're I should have created a locales/add/en/pos manually, then what would i put there? ok  guess I won't use it then.

**Comment by adrai** [comment]
I don't know what you're trying to do with your i18next setup.
I just know, you should not use saveMissing if using chained backend.
So maybe describe a bit more what you like to achieve.

**Comment by laclance** [comment]
I just want a fallback for when there is no internet connection and just want to know the easiest way to save missing translations.

**Comment by adrai** [comment]
If you want a fallback for when there is no internet connection, will your website still work?
Or do you want to have a fallback for when the first backend might be unreachable (so AWS is globally down)?
Then probably you should bundle the translations, like described here: https://docs.locize.com/more/backend-fallback#browser-fallback-with-local-bundled-translations

I'll say it again: do not use `saveMissing: true` when using the chained backend.

You could i.e. use the chained backend only in production (saveMissing: false) and when working locally (non-prod) you use the i18next-locize-backend directly without chained backend and saveMissing: true

**Comment by laclance** [comment]
yes app works offline, ok thank you, of course i don't need need savemissing on production but then what do I do for locales/add/en/pos, and why do I get 401, I am using the same api key for the cli and that works fine.

**Comment by adrai** [comment]
you need to check the request and response, it might be you're not really runniing in a browser or in a different sandbox, and the cors might fail somehow...

**Comment by laclance** [comment]
Nevermind I just removed chained backend and everything works, thanks again for your time.
