### ISSUE TITLE
Add Customer nsSeparator To Typescript CustomTypeOptions

### ISSUE THREAD

**Issue by vanenshi** [i18next/react-i18next#1467]
## 🚀 Feature Proposal

current typescript `CustomTypeOptions` provides a way to customize the `keySeparator`. but there is no options to change the nsSeparator.

## Motivation

even though I have the ability to customize the `nsSeparator` in the i18n init function, I have no way to provide it to the `CustomTypeOptions`, hence it would be impossible to use  `nsSeparator` without getting an error from typescript
## Example

```
// i18n-resources.d.ts
import * as resources from './locales';

declare module 'react-i18next' {
  interface CustomTypeOptions {
    defaultNS: 'common';
    nsSeparator: '.';
    resources: typeof resources['en'];
  }
}
```

**Comment by adrai** [comment]
v11.15.7 should address this thanks to @pedrodurek
