### ISSUE TITLE
useTranslation does not follow react hooks best practices

### ISSUE THREAD

**Issue by ckedwards** [i18next/react-i18next#1473]
## 🐛 Bug Report

> Don’t call Hooks inside loops, conditions, or nested functions. Instead, always use Hooks at the top level of your React function, before any early returns.

https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level

useTransition breaks this rule by having an [early return](https://github.com/i18next/react-i18next/blob/master/src/useTranslation.js#L18).

I encountered a crash due to a race condition in my application because of the way it was dynamically importing code. As a result, sometimes the react components would render before i18n was initialized. When i18n was initialized later and the components re-rendered I got the following react error:

> Error: Minified React error #311; visit https://reactjs.org/docs/error-decoder.html?invariant=311 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

While the bug was in my code, and once I identified the problem it was easy enough to remedy, I believe that react-i18next should handle this case better so that it does not result in a crash inside the react rendering code.

**Comment by adrai** [comment]
Is it possible you was not using Suspense and also did not check for the ready flag? https://react.i18next.com/latest/usetranslation-hook#not-using-suspense

**Comment by jamuhl** [comment]
only such case I see is: https://github.com/i18next/react-i18next/blob/master/src/useTranslation.js#L11

and that's basically like using it without meeting conditions and alternative would be throwing that error

**Comment by ckedwards** [comment]
I was able to fix the bug in my code. The issue that I am mentioning is that useTranslation is not following the rules of hooks and resulted in a weird crash in my code. It took me a little wile to hunt down the source of the crash because it was a race condition in my specific case and the error was in react. 

When the first time the component renders without using hooks and the second time it does the hook stack gets corrupted (as I understand it), which results in the react render code throwing an error.

It seems like the `warnOnce` in this specific case should be `errorOnce` and console.error the message if the assumption is that this is an error on the part of the user? I also think useTranslation could be refactored to follow the rules of hooks.  I can look into making a PR for this if you would like.

**Comment by ajfranzoia** [comment]
@ckedwards I'm having the same issue. How did you get it resolved?

**Comment by adrai** [comment]
> @ckedwards I'm having the same issue. How did you get it resolved?

Can you share your logs in the developer console? Are there some other warnings when setting debug: true?

**Comment by ckedwards** [comment]
> @ckedwards I'm having the same issue. How did you get it resolved?

After I found the cause of the bug I noticed that there was a "You will need to pass in an i18next instance by using initReactI18next" warning in the console every time the crash occurred. My code uses the static `i18next.init` function, so I needed to make sure that function was called before I rendered any react components.

**Comment by ajfranzoia** [comment]
> > @ckedwards I'm having the same issue. How did you get it resolved?
> 
> Can you share your logs in the developer console? Are there some other warnings when setting debug: true?

I don't have the logs atm, but I detected that the issue happened when having a children function prop and calling it:

**Comment by ajfranzoia** [comment]
> > @ckedwards I'm having the same issue. How did you get it resolved?
> 
> Can you share your logs in the developer console? Are there some other warnings when setting debug: true?

> > @ckedwards I'm having the same issue. How did you get it resolved?
> 
> Can you share your logs in the developer console? Are there some other warnings when setting debug: true?

I don't have the logs atm, but I detected that the issue happened when having a children function prop and calling it:

**Comment by ajfranzoia** [comment]
> > @ckedwards I'm having the same issue. How did you get it resolved?
>
> Can you share your logs in the developer console? Are there some other warnings when setting debug: true?

  I don't have the logs atm, but I detected that the issue happened when having a children function prop and calling it directly:

  This caused the error:
  ```typescript
  interface Props {
    children: (p: OtherProps) => React.ReactNode;
  }
  
  const MyComp = (p: Props) => {
    const { t } = useTranslation();
    
    return <div>{children({ ... })}</div>;
  } 
  ```

  This did not provoke the error:
  ```typescript
  interface Props {
    children: ComponentType<OtherProps>;
  }
  
  const MyComp = (p: Props) => {
    const { t } = useTranslation();
    
    const ChildComp = children;
    
    return <div><ChildComp {...} /></div>;
  } 
  ```

**Comment by ckedwards** [comment]
Is `children` a functional component that gets conditionally rendered and uses hooks?  If so, that would cause the react crash. Looking into render props might solve your problem.

**Comment by akshayrajp** [comment]
Hey guys,

I too am facing a similar issue. A few components in my app are using i18next, while others are not. These said components render a blank screen for a few seconds before the waiting loader is rendered. To be specific, this is the order:

Blank screen is shown for a few seconds
                          ⬇
Waiting loader is shown
                          ⬇
The actual component is rendered
   
Is there any way I could avoid the blank screen here?
**Note:** I am not using Suspense here because I have to wrap my whole App inside of Suspense, which means that the loader gif will take over the entire screen whenever the translation files are being loaded. However, I only need the component to show the loader gif. I tried wrapping specific components with Suspense but that threw an error asking me to wrap Suspense higher up the component tree.

@ckedwards I believe I'm facing a similar issue that you described here.. How did you solve this? How did you ensure that the init function gets called before any sort of rendering happens?

**Comment by jamuhl** [comment]
@akshayrajp just use suspense correctly...it must be around the component that useTranslations (not inside that)...or don't use Suspense at all (more work) and use the ready flag: https://react.i18next.com/latest/usetranslation-hook#not-using-suspense

**Comment by akshayrajp** [comment]
@jamuhl 
Apologies for the late reply,

I am using the ready flag but I'm still facing the same issue.

**Comment by jamuhl** [comment]
@akshayrajp 100% the issue is on your side...something is wrong in your code -> https://github.com/i18next/react-i18next/blob/master/src/useTranslation.js#L100 if you set `useSuspense: false` react-i18next will not throw that suspense triggering promise.

Easiest might be to create a reproducible example on codesandbox so we can point you to your wrong code.

**Comment by akshayrajp** [comment]
@jamuhl  You were right, the error was on my side. We were lazy loading our components here and they all imported a function which helped them do that. This function was using Suspense and somehow I had missed that.

The issue of the blank screen went away as soon as I passed the fallback loader to it.

Apologies for any sort of trouble/stress my comments may have caused you. This was a blunder on my part.

**Comment by jamuhl** [comment]
@akshayrajp no worry...glad you figured it out
