### ISSUE TITLE
Empty string as suffix?

### ISSUE THREAD

**Issue by beganovich** [i18next/react-i18next#1475]
## 🐛 Bug Report

When using an empty string as a suffix, it is not parsed correctly.

## To Reproduce

Translation string:

```json
"pdf_page_info": "Page :current of :total",
```

Configuration:

```js
i18n.use(initReactI18next).init({
  resources: {
    en: {
      translation: en,
    },
  },
  lng: 'en',
  fallbackLng: 'en',
  interpolation: {
    escapeValue: false,
    prefix: ':',
    suffix: '',
  },
  debug: true,
});
```

Usage:

```js
{t('pdf_page_info',  { current: 1, total: 10 })}
```

Output: 
```
Page :current of :total
```

## Expected behavior

Page 1 of 10.

## Your Environment

- *runtime version*: Node v16.14.0
- *i18next version*: 11.15.4
- *os*: Linux
Running in Vite.

**Comment by adrai** [comment]
currently afk, suspecting a falsy value check somewhere...
as soon as I'm back to my workstation I'll check

**Comment by adrai** [comment]
probably here: https://github.com/i18next/i18next/blob/9ca694db52fe5b6f10da5debf3e106e6f615b907/src/Interpolator.js#L24

feel free to try a PR until I'm back

**Comment by beganovich** [comment]
Thanks, will have a look after work hours :)

**Comment by adrai** [comment]
little addition/hint... was just thinking about the whole empty string as suffix... I theory this can never work...
There must be both... a prefix and a suffix....  Think about formatting.... stuff like `Some format {{value, formatname}} etc...`  
with your prefix/suffix , how would this work? `Some format :value, formatname etc...`

**Comment by adrai** [comment]
null is not a text delimiter

it needs to be at least 1 character

**Comment by beganovich** [comment]
Hm, yeh, that's true as well. Not sure, to be honest, what would be the best way to tell the config to not include suffix? Btw. this is not that rare case I think as well. The translation convention we are using is Laravel's way of translating strings.

**Comment by adrai** [comment]
The problem is i18next needs prefix and suffix because it uses stuff like format arguments etc...
Laravel is not doing this...

So currently there is no way to have only a prefix or only a suffix, i18next requires to have both and both need to be at least 1 character

**Comment by beganovich** [comment]
Yeh, I think that's fair. Thank you for the explanation. I might have a look at it at some point. I guess it'll be easier to modify the translation string for now :) Thanks bud!
