### ISSUE TITLE
Property 'children' does not exist on type 'IntrinsicAttributes & I18nextProviderProps' on React 18 types

### ISSUE THREAD

**Issue by sachinahya** [i18next/react-i18next#1477]
## 🐛 Bug Report

After upgrading `@types/react` to `18.0.0`, the following code gives a TypeScript error.

```ts
return <I18nextProvider i18n={i18next}>{children}</I18nextProvider>;

// Type '{ children: ReactNode; i18n: i18n; }' is not assignable to type 'IntrinsicAttributes & I18nextProviderProps'.
//   Property 'children' does not exist on type 'IntrinsicAttributes & I18nextProviderProps'.ts(2322)
```

This is because the `I18nextProvider` props relies on the `children` prop implicitly being included on `React.FunctionComponent`, and this was removed in [v18 of `@types/react`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210).

## To Reproduce

https://codesandbox.io/s/react-i18next-react-18-ctvtf1

## Expected behavior

No TypeScript error.

## Your Environment

```json
"dependencies": {
  "i18next": "21.6.14",
  "react": "18.0.0",
  "react-dom": "18.0.0",
  "react-i18next": "11.16.2",
  "react-scripts": "4.0.3"
},
"devDependencies": {
  "@types/react": "18.0.0",
  "@types/react-dom": "18.0.0",
  "typescript": "4.4.2"
}
```

**Comment by adrai** [comment]
maybe also related to #1476/#1466?

**Comment by sachinahya** [comment]
Somewhat related in that the tightening of types in `@types/react` has caused both. The two issues #1476 and #1466 are caused by the downstream type coming from [i18next](https://github.com/i18next/i18next) and would need to be fixed there, whereas this one only covers this package.
