### ISSUE TITLE
Upgrading from 11.16.2 to 11.16.5 sends initialisation into and endless loop

### ISSUE THREAD

**Issue by cburgmer** [i18next/react-i18next#1484]
## 🐛 Bug Report

When using a trivial invocation of i18next without a language, the initialisation goes into an endless loop when upgrading to 11.16.5 from 11.16.2.

The use case for the minimal code is when used in conjunction with Storybook and Loki to test for visual regressions, where no translations are needed.

## To Reproduce

```js
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

i18n.use(initReactI18next).init({
  debug: true,
});
```

Workaround:

```js
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

i18n.use(initReactI18next).init({
  fallbackLng: 'dontcare',
  debug: true,
});
```

## Expected behavior

Throw an error, or work without language, just don't blow up the webpage.

## Your Environment

- *runtime version*: Chrome, Firefox
- *i18next version*: 21.6.16
- *os*: Mac

**Comment by adrai** [comment]
Sorry, I'm not able to reproduce this. => https://codesandbox.io/s/react-i18next-http-example-forked-x211j0?file=/src/i18n.js
Can you please provide a reproducible example?

**Comment by adrai** [comment]
could reproduce it.... on it...

**Comment by adrai** [comment]
v11.16.6 should be better, can you confirm?

**Comment by cburgmer** [comment]
Looking good here, hence closing the issue.
Thanks for the quick fix!
