### ISSUE TITLE
Add warning when overriding i18n

### ISSUE THREAD

**Issue by rluvaton** [i18next/react-i18next#1485]
## 🚀 Feature Proposal

Add a warning when setI18n is called when there is already an instance running

## Motivation

Just spent too many hours debugging an issue that apparently we override the i18n instance

## Example

React app initialize the i18n with `initReactI18next` which call setI18n internally

Some internal react library do the same thing instance of using `createInstance` which override the i18n instance

A warning is logged, the developer notice that and everyone is happy

> Based on a true and frustrating story

**Comment by adrai** [comment]
Can you please provide a bit more information?

Which other component did use the setI18n function?
In theory this is not a supported interface to be used from outside of react-i18next.

An example repo or codesandbox example may help me to understand your use case.

**Comment by rluvaton** [comment]
> Can you please provide a bit more information?
> 
> Which other component did use the setI18n function?
> In theory this is not a supported interface to be used from outside of react-i18next.

No one used the `setI18n` directly

The main react app use the translations:
```
i18n
  .use(initReactI18next)
  .init(some config)
```

This react app have a dependency which also use translation and do in his code:
```
i18n
  .use(initReactI18next)
  .init(other config)
```

Because `initReactI18next` save the i18n internally, the second call override it with the other config

If I did not explain myself well I'll try to create a code sandbox to illustrate that

**Comment by adrai** [comment]
ahhh, so the problem is the dependency did NOT create an own i18next instance: https://www.i18next.com/overview/api#createinstance

and probably did also NOT use the provider: https://react.i18next.com/latest/i18nextprovider#when-to-use

![image](https://user-images.githubusercontent.com/1086194/163046415-53381623-d81a-414b-ba75-d141a297b0c7.jpeg)

**Comment by rluvaton** [comment]
Yeah this is the problem, so add a warning will help avoid this mistakes

**Comment by adrai** [comment]
Currently afk, but adding a warning there will be more confusing in those situations...
in a setup with a component library the warning would be shown...

**Comment by rluvaton** [comment]
> Currently afk, but adding a warning there will be more confusing in those situations...
> in a setup with a component library the warning would be shown... 

Do you mean that it'll be confusing when the warning only be shown when consuming the library?

I think it's better than nothing, and with a descriptive warning, something like:

> you or one of your dependencies that use `react-i18next` has initialize and override the `i18n` instance that is used by `react-i18next`, to avoid this problem use `i18n.createInstance` or notify the library creator to create an instance

It would help solve those issues and avoid future problem

**Comment by adrai** [comment]
No, I mean the warning will always be shown when using a component library... also if it's correctly set up (createInstance etc.)
but need to verify tomorrow... 💤

**Comment by adrai** [comment]
Yes, I confirm what I suspected. Such a warning would also be logged, if the setup is correct. Like here: https://github.com/i18next/react-i18next/tree/master/example/react-component-lib
So we can't add a warning here, sorry.
