### ISSUE TITLE
Extractring translations : getting 404 post requests when trying to save missingKeys

### ISSUE THREAD

**Issue by youcef-Ismael** [i18next/react-i18next#1488]
## Documentation issue

There is no documentation for extracting translation made specifically for React. the general documentation of i18next gives explanation for differrent backends !

Which backed plugin should we use with react, and how should be the configuration for it?

## Main Issue

With `saveMissing:true` in the init function of i18n, and the backend cofigurated as discribed in the general documentation of i18next https://www.i18next.com/how-to/extracting-translations#3-runtime-extraction I couldn't manage to save the missingKeys.

The loading works fine. But when trying to save missing values I get 404 responses with post requests.
**`POST http://localhost:3000/locales/add/en/translation 404 (Not Found)`**

I am not sure about which backend do react apps use, and whether it is possible to make post requests to write on the public folder.

**Comment by jamuhl** [comment]
what backend react apps use...non...during development you're using the built in devserver...-> files in public folder are automatically static servers on `/` -> therefore putting files in the public/locales works for loading...but there is no way to get saveMissings working during development using only the build-in server (you either need a real server doing that -> eg. using https://github.com/i18next/i18next-http-middleware or if you like the comfortable solution use locize.com which gives you max. DX for it.)
