### ISSUE TITLE
Pluralization issue when running React Native app in release mode

### ISSUE THREAD

**Issue by joebernard** [i18next/react-i18next#1495]
## 🐛 Bug Report

I have successfully integrated `react-i18next` into my React Native app. When running the app in debug mode, all of the translations are successful 🚀

However, when I run the app in release mode pluralization breaks. I get a missing key error (`parseMissingKeyHandler` is called). If I switch back to debug, pluralizations begins working again.

## To Reproduce

Keys:
```JSON
{
  "followers_one": "follower",
  "followers_other": "followers"
}
```

Code:
```javascript
const {t} = useTranslation();
...
<Text>
  {t('followers', {count: 10})}
</Text>
```
All non-pluralized strings continue to translate. Only the pluralized strings are not finding their key in release mode. I will note that if I add a new key of "followers" it will return that key in release mode:

```JSON
{
  "followers": "follower",
}
```
If I switch back to debug, pluralizations begin working again.

## Expected behavior

Pluralizations should work regardless of the build mode.

## Your Environment

- *runtime version*: "react-native": "0.67.2",
- *i18next version*: "i18next": "21.3.3", "react-i18next": "11.13.0",
- *os*: Mac

Here is my internationalization class with init:
```js
import {NativeModules} from 'react-native';
import i18n from 'i18next';
import Config from 'react-native-config';
import {initReactI18next} from 'react-i18next';
import AsyncStorage from '@react-native-async-storage/async-storage';
import translationEN from '../localization/en/translation.json';

class Internationalization {
  deviceLng = `${
    NativeModules.SettingsManager.settings.AppleLocale ||
    NativeModules.SettingsManager.settings.AppleLanguages[0]
  }`.split('_')[0];

  resources = {
    en: {
      translation: translationEN,
    },
  };

  getSupportedLngs = () => {
    return Object.keys(this.resources);
  };

  getLng = async () => {
    const lng = await AsyncStorage.getItem('language');
    if (lng !== null) {
      return lng;
    }
    if (this.deviceLng in this.resources) {
      return this.deviceLng;
    }
    return DEFAULT_LNG;
  };

  init = async () => {
    // override locale with any preferences from storage
    const lng = await this.getLng();
    return i18n.use(initReactI18next).init({
      resources: this.resources,
      lng,
      fallbackLng: DEFAULT_LNG,
      interpolation: {
        escapeValue: false,
      },
      debug: Config.STAGE === 'dev',
      parseMissingKeyHandler: key => {
        console.error(`Missing translation key: ${key}`);
      },
    });
  };
}
```

**Comment by jamuhl** [comment]
https://www.i18next.com/misc/migration-guide#json-format-v4-pluralization

you might need to polyfill Intl.API: https://github.com/eemeli/intl-pluralrules

**Comment by adrai** [comment]
if you set the i18next debug option to true and run your release build, you may see some warnings in the developer console...

**Comment by joebernard** [comment]
The polyfill solved it.

```
yarn add intl-pluralrules
````

Then in my root index.js:

```js
import 'intl-pluralrules';
```

Thanks!

**Comment by MFrat** [comment]
It is not working for me. Tried @joebernard solution and didn't work. Had to use another library.

**Comment by Elozino** [comment]
> It is not working for me. Tried @joebernard solution and didn't work. Had to use another library.

What library did you use?
