### ISSUE TITLE
How to manage multiple instances in 3rd party library?

### ISSUE THREAD

**Issue by dohooo** [i18next/react-i18next#1497]
Hi there! THX for your effort for this awsome library!

I have a question about the documentation, It's also about a scene.  

e.g. I hava a monorepo project, It include three packages.

core pkg
```tsx
// init a i18next instance and export provider component.
export const ConfigProvider=()=>{
    return <I18nextProvider i18n={i18n}>{...}</I18nextProvider>
}
```

A-components pkg
```tsx
// define locale bundles about this pkg
export const AButton=()=>{
    const { t } = useTranslation();
    return <button>{t("some-text")}</button>
}
```

B-components pkg
```tsx
// define locale bundles about this pkg
export const BButton=()=>{
    const { t } = useTranslation();
    return <button>{t("some-text")}</button>
}
```

Then i use these pkgs for another project
```tsx
export const App = () =>{
    return <ConfigProvider>
        <AButton/>
        <BButton/>
    </ConfigProvider>
}
```

If I want the project to run in this structure, I need do many things, for example externalize `react-i18next` and `i18next` for `A-components pkg` and `B-components pkg`
<img width="880" alt="image" src="https://user-images.githubusercontent.com/32405058/166708041-a3b970e6-3b35-4d36-ab28-603ed0166014.png">
useTranslation hook always use current context, so I need let them to use `core pkg` context, After `core pkg` initializes i18next instance, `A-components pkg` and `B-components pkg` will load locale bundles.
And why i did'n externalize them for core pkg, because it would contaminate the user's project, make their language pack loading mess. 

e.g.  When I don't have externalized `react-i18next` and `i18next` for `core pkg`
```tsx
export const App = () =>{
    return <ConfigProvider>
        <Foo/>
    </ConfigProvider>
}

const Foo = () =>{
    const { t } = useTranslation();
    // This might show the content of the language defined in A/B-components pkg, since they share the same context
    return <button>{t("some-text")}</button>
}
```

I don't think I'm explaining it clearly enough, I'd like to do more to describe it. Is there an API I'm missing? I read almost every word in the documentation and looked at the source code, but couldn't find a better way to do it. 

If it is a feature or a related plugin, I would like a PR.

**Comment by dohooo** [comment]
> currently afk, did not read all of the issue, but maybe this helps: #1485 https://github.com/i18next/react-i18next/blob/master/example/react-component-lib/src/i18n.js#L28 ?

Thank you for your quick reply～

I've seen this example before. My scenario is that I need to put <OtherLibI18nextProvider/> at the top. Using this example, what happens if I put <OtherLibI18nextProvider/> in the Root Component?

**Comment by adrai** [comment]
Sorry, I don't know what you mean, but best would be you create a new repo based on https://github.com/i18next/react-i18next/blob/master/example/react-component-lib and show what explain issue is...

**Comment by dohooo** [comment]
> Sorry, I don't know what you mean, but best would be you create a new github repository based on https://github.com/i18next/react-i18next/blob/master/example/react-component-lib and show what explain issue is...

OK

**Comment by dohooo** [comment]
<img width="795" alt="image" src="https://user-images.githubusercontent.com/32405058/166724941-b6d1cb79-45c3-4cda-bbba-4b945fea71a3.png">
Is there another way to do this, can we manage another i18next context ourselves?

<img width="702" alt="image" src="https://user-images.githubusercontent.com/32405058/166725193-e5f57be7-655f-48a9-b47e-e57e90dd42dc.png">
Using this way, if I update i18n Instance, useTranslation will not make the component rerender

**Comment by adrai** [comment]
Sorry, I still don't get what you want to achieve.
If you want to have another context with a specific i18next instance, just wrap that part with an I18nextProvider https://react.i18next.com/latest/i18nextprovider

I also don't understand why you removed the I18nextProvider from within the component-lib...

Normally, the component-lib has it's own I18nextProvider with it's own i18next instance... not vice-versa...

Maybe @jamuhl understands better?

**Comment by dohooo** [comment]
> Sorry, I still don't get what you want to achieve. If you want to have another context with a specific i18next instance, just wrap that part with an I18nextProvider https://react.i18next.com/latest/i18nextprovider
> 
> I also don't understand why you removed the I18nextProvider from within the component-lib...
> 
> Normally, the component-lib has it's own I18nextProvider with it's own i18next instance... not vice-versa...
> 
> Maybe @jamuhl understands better?

<img width="870" alt="image" src="https://user-images.githubusercontent.com/32405058/166726374-7bde1b81-c666-43bf-97e3-33956eb5675f.png">
I added it here.

I'm going to bed thanks for your answer.

**Comment by dohooo** [comment]
I mean if there are multiple nested providers, is there any other way for useTranslation to distinguish between different instances? I'm not describing it very clearly, My bad... 😵‍💫

**Comment by dohooo** [comment]
My components lib can be used anywhere, so I need to put the <I18nProvider/> at root. Because we share the same context, we can use it everywhere under <I18nProvider/>, but I just want the Components lib to use it. 

So  can we change the default context by user needs?

**Comment by jamuhl** [comment]
@dohooo if you nest Components from different modules using different i18n instances - context will only work if your Components are wrapped into that I18nextProvider on the direct parent and not on some top-level component.

In that case it's simpler passing in i18n via props `const { t, i18n } = useTranslation('common', { i18n: myI18nInstance });`

Basically you also can build your own hook using context as needed and reusing the `useTranslation` with passed in i18n

```js
export const componentLibsUseTranslationHook = (ns, opts) => {
   const { i18nForModule } = useContext(MyCustomI18nContextForModule) || {};
   
   return useTranslation(ns, { ...opts, i18n: i18nForModule });
}
```

**Comment by dohooo** [comment]
> @dohooo if you nest Components from different modules using different i18n instances - context will only work if your Components are wrapped into that I18nextProvider on the direct parent and not on some top-level component.
> 
> In that case it's simpler passing in i18n via props `const { t, i18n } = useTranslation('common', { i18n: myI18nInstance });`
> 
> Basically you also can build your own hook using context as needed and reusing the `useTranslation` with passed in i18n
> 
> ```js
> export const componentLibsUseTranslationHook = (ns, opts) => {
>    const { i18nForModule } = useContext(MyCustomI18nContextForModule) || {};
>    
>    return useTranslation(ns, { ...opts, i18n: i18nForModule });
> }
> ```

That's what I did. I wonder if there's a better way. But I don't have any idea, Thank your for your patience.  @jamuhl @adrai
