### ISSUE TITLE
Typescript for i18next.t

### ISSUE THREAD

**Issue by bezvrednyy** [i18next/react-i18next#1500]
`const {t} = useTranslations` works great with typescript inside a component. I really want typing to work when using i18next.t() for use it outside components.

Also I want to have function like `useTranslations`. But method, no hook. For settings specific locale and keyPrefix, these also typed.

**Comment by bezvrednyy** [comment]
I tried expand the interface. But it didn't help to me.
![image](https://user-images.githubusercontent.com/61377069/167617529-c9b04961-1133-483e-9841-7ef58d9d5c14.png)

**Comment by ChambreNoire** [comment]
I have a similar issue. I have externalized a bunch of AntD table column definitions to a separate tsx file. Some column definitions have a 'render' property which contains a JXS.Element - in this case an AntD Tooltip. Using i18next.t here to supply a localized value to the Tooltip's title property yields the following:

```
TS2322: Type 'TFunctionResult' is not assignable to type 'ReactNode | RenderFunction'.
Type 'object' is not assignable to type 'ReactNode | RenderFunction'.  
index.d.ts(39, 5): The expected type comes from property 'title' which is declared here on type 'IntrinsicAttributes & (TooltipProps & RefAttributes<unknown>)'
```

Any ideas?

**Comment by alienzhangyw** [comment]
> I have a similar issue. I have externalized a bunch of AntD table column definitions to a separate tsx file. Some column definitions have a 'render' property which contains a JXS.Element - in this case an AntD Tooltip. Using i18next.t here to supply a localized value to the Tooltip's title property yields the following:
> 
> ```
> TS2322: Type 'TFunctionResult' is not assignable to type 'ReactNode | RenderFunction'.
> Type 'object' is not assignable to type 'ReactNode | RenderFunction'.  
> index.d.ts(39, 5): The expected type comes from property 'title' which is declared here on type 'IntrinsicAttributes & (TooltipProps & RefAttributes<unknown>)'
> ```
> 
> Any ideas?

I use `{t('key') as string}` to fix this.

**Comment by ChambreNoire** [comment]
@alienzhangyw Yeah I ended up doing {t<string>('key')}

**Comment by stasinski** [comment]
Hi, I was able to resolve this issue in my project with [patch-package](https://github.com/ds300/patch-package), this is obviously a dirty way to manage that, but works in my case.

```diff
diff --git a/node_modules/i18next/index.d.ts b/node_modules/i18next/index.d.ts
index 26dc5fe..829736c 100644
--- a/node_modules/i18next/index.d.ts
+++ b/node_modules/i18next/index.d.ts
@@ -747,7 +747,7 @@ export interface TFunction {
     TInterpolationMap extends object = StringMap,
   >(
     key: TKeys | TKeys[],
-  ): TResult;
+  ): string;
   <
     TResult extends TFunctionResult = TFunctionDetailedResult<object>,
     TKeys extends TFunctionKeys = string,
@@ -755,7 +755,7 @@ export interface TFunction {
   >(
     key: TKeys | TKeys[],
     options?: TOptions<TInterpolationMap> & { returnDetails: true; returnObjects: true },
-  ): TResult;
+  ): string;
   <
     TResult extends TFunctionResult = TFunctionDetailedResult,
     TKeys extends TFunctionKeys = string,
@@ -763,7 +763,7 @@ export interface TFunction {
   >(
     key: TKeys | TKeys[],
     options?: TOptions<TInterpolationMap> & { returnDetails: true },
-  ): TResult;
+  ): string;
   <
     TResult extends TFunctionResult = object,
     TKeys extends TFunctionKeys = string,
@@ -771,7 +771,7 @@ export interface TFunction {
   >(
     key: TKeys | TKeys[],
     options?: TOptions<TInterpolationMap> & { returnObjects: true },
-  ): TResult;
+  ): string
   <
     TResult extends TFunctionResult = string,
     TKeys extends TFunctionKeys = string,
@@ -779,7 +779,7 @@ export interface TFunction {
   >(
     key: TKeys | TKeys[],
     options?: TOptions<TInterpolationMap> | string,
-  ): TResult;
+  ): string;
   // overloaded usage
   <
     TResult extends TFunctionResult = string,
```

**Comment by vadimyen** [comment]
Still no news? I have the same problem.

**Comment by pedrodurek** [comment]
Hey @vadimyen, could you clarify the problem that you are facing?

**Comment by limpbrains** [comment]
I'm too having this issue. 


i18n.js
```js 
import i18n from 'i18next';

i18n.init(...);

export default i18n;
```

utils.js
```js
import i18n from './i18n'

i18n.t('key');  // Property 't' does not exist on type 'typeof import("i18next")'.
```
