### ISSUE TITLE
keyPrefix is missing in documentation and in typing

### ISSUE THREAD

**Issue by jansepke** [i18next/react-i18next#1503]
## Documentation issue

Reading the code here https://github.com/i18next/react-i18next/blob/f0b32549ee26be680ae6c0287c936c52ddcedae1/react-i18next.js#L809 it seems that it is possible to configure `keyPrefix` in the i18next configuration. But it is not listed as an option here https://react.i18next.com/latest/i18next-instance and also missing from the typescript definitions. If it is a allowed option it should be documented. As I am looking through the typings: could it be that all options are missing in the typescript definition?

## Motivation

We are using the same keyPrefix for an application so it is very redundant to configure the same keyPrefix on every `useTranslation`

**Comment by adrai** [comment]
v21.8.4 of i18next should included that
and the docs are also updated now
