### ISSUE TITLE
Typescript error when using variables in Trans component

### ISSUE THREAD

**Issue by eszthoff** [i18next/react-i18next#1504]
## 🐛 Bug Report

Typescript throws when using variable in Trans component. Maybe a bit of an edge case, but when using a custom component that expects string as children within `Trans` and the child to this component should include a variable Typescript throws an error. Also it is impossible to ignore TS in this situation.

## To Reproduce

A [codesandbox](https://codesandbox.io/s/mutable-wildflower-2se8hs?file=/src/App.tsx) 

Note that this is a minimal reproduction (e.g. i18next is not fully set up).

One of the conditions for this bug is that you have the child in a separate line. If they would be in one line, you could add a `{/* @ts-ignore */} before hand. However it is not working when the code is in multiple lines.

## Expected behavior

TS doesn't throw or at least there is a way to ignore it.

**Comment by adrai** [comment]
outside of your StringWrapper it works, right? https://codesandbox.io/s/mutable-bash-6gdqy2?file=/src/App.tsx:323-348

**Comment by eszthoff** [comment]
@adrai do you mean if you move the variable to a different position? Yes, that works. 
But that is not a viable solution, if the variable needs to be inside the string of `StringWrapper`.

**Comment by adrai** [comment]
I'm not a TypeScript user, but if it works like this: 

```js
      <Trans>
        <StringWrapper className="my-class">
          Your count 
        </StringWrapper>
        {{ amount: data.length }} has been counted
      </Trans>
```

it may be your StringWrapper component is doing something that is causing the problem.

**Comment by eszthoff** [comment]
This solution doesn't answer the requirements (see above). Also that component doesn't do much (see in the example attached).

**Comment by eszthoff** [comment]
Thank for your work and the suggestions. 

Unfortunately changing the children type will also not fulfil the requirements. Even in the current (contrived) example that will allow incorrect children to be passed. E.g. `<div>text</div>` that would result in incorrect HTML such as `<span><div>text</div></span>`.  

I think there are several real world scenarios when you want to have a strong type checking:
* `StringWrapper` is part of a library that you expect others to use 
* `StingWrapper` is used by a large amount of developers in your company in different context where `Trans` is only one use case.

**Comment by ChambreNoire** [comment]
I'm experiencing something similar:
```
const title = `${title} something`
return (
    <Trans i18nKey="myKey">
        Edit <span style={{color: '#40a9ff'}}>{{title}}</span>
    </Trans>
)
```
yields:
`TS2322: Type '{ title: string; }' is not assignable to type 'ReactNode'.   Object literal may only specify known properties, and 'title' does not exist in type 'ReactElement<any, string | JSXElementConstructor<any>> | ReactFragment | ReactPortal'.`

**Comment by TrueCarry** [comment]
Problem still exists. Maybe there's workaround for default components like span?

**Comment by rodriguezmarting** [comment]
Problem still exists...

**Comment by pedrodurek** [comment]
Everyone who is still facing this problem, please set `allowObjectInHTMLChildren` to `true` in your `react-i18next` type declaration file. You can follow the instructions [here](https://react.i18next.com/latest/typescript#create-a-declaration-file) to learn how to create a type declaration file, it should look similar to this one: 
```ts
import "react-i18next";
...

declare module "react-i18next" {
  interface CustomTypeOptions {
    allowObjectInHTMLChildren: true, // This property should be true
    defaultNS: "ns1";
    resources: {
      ns1: typeof ...;
    };
  }
}
```
If the error still persists, please share a minimalistic version of your app (using the Trans component), and I'll help you.

**Comment by pedrodurek** [comment]
As far as I could see, @eszthoff issue is different from others as she can't change the children `Props`, if you can't change the children props to `React.ReactNode` or `string | Record<string, unknown>;`, please explain why and I'll try to help you.

**Comment by falkoschumann** [comment]
@pedrodurek Setting `allowObjectInHTMLChildren` to `true` works for me. Thanks.

What is the reason why it is not true by default? Are there any disadvantages?

**Comment by BrooceLR** [comment]
> @pedrodurek Setting `allowObjectInHTMLChildren` to `true` works for me. Thanks.
> 
> What is the reason why it is not true by default? Are there any disadvantages?

Wouldn't that suppress typescript errors on *any* children prop? And objects are not valid JSX children, meaning that outside `Trans` components: I'd expect it to crash the runtime?

**Comment by falkoschumann** [comment]
@BrooceLR I tested this, `allowObjectInHTMLChildren` works like disabling the TypeScript warning globally. It suppresses warnings in all JSX. So this is not a good solution.

**Comment by rodriguezmarting** [comment]
> Everyone who is still facing this problem, please set `allowObjectInHTMLChildren` to `true` in your `react-i18next` type declaration file.

This workaround is not a good solution for the reasons @falkoschumann mentioned. On top of that, when mocking i18n for tests the object inside JSX is still there, React throws the same `Objects are not valid as a React child..`

**Comment by radekskrabucha** [comment]
I found an solution for this, you can pass `values` to `Trans` component like this:

```ts
      <Trans values={{ amount: data.length }}>
        <StringWrapper className="my-class">
          Your count 
        </StringWrapper>
        {data.length} has been counted
      </Trans>
```

**Comment by PiTiLeZarD** [comment]
Not sure if people are still looking for a solution to this but the problem lies in their definition of children. It's not just ReactNode. You can fix it by doing this:

```
type TransChild = ReactNode | Record<string, unknown>;
type MyProps = {children: TransChild | readonly TransChild[]}

export const MyComp: FC<MyProps> = ({children}) => (<Whatever>{children}</Whatever>) 
```

That'll tell TS that your children prop also accept objects. Not sure if it helps anyone.
