### ISSUE TITLE
TypeScript error when using variables in {t} function.

### ISSUE THREAD

**Issue by FanManutd** [i18next/react-i18next#1505]
## 🐛 Bug Report

I have a declaration file 
![image](https://user-images.githubusercontent.com/90761929/170036453-71c2e958-c44a-4065-a15b-4e0b38f6e42e.png)

My `componentHeader.json`:
```
{
  "projects": "Projects",
  "education": "Education",
  "community": "Community"
}
```

And my code. Unfortunately `as const` don't help.
![image](https://user-images.githubusercontent.com/90761929/170037071-f0338115-0912-465a-9919-253f0cae11fd.png)
![image](https://user-images.githubusercontent.com/90761929/170037276-2c975076-5778-4e47-b1ec-656edcca2153.png)

Is it possible to specify `t` like `'projects' | 'education' | 'community' | string` ?

**Environments**

- *react-i18next*: 11.16.2
- *typescript*: 4.6.3

**Comment by pedrodurek** [comment]
Hey @FanManutd you need to convert your `links` to literal values in order to work, you can do that by asserting your `links` to `as const`.
```tsx
const links = [
...
] as const

...
<Link .... text={link.label} />
```

**Comment by FanManutd** [comment]
> Hey @FanManutd you need to convert your `links` to literal values in order to work it, you can do that by asserting your `links` to `as const`.
> 
> ```tsx
> const links = [
> ...
> ] as const
> 
> ...
> <Link .... text={link.label} />
> ```

Yes, I already thought about it and realized that my question doesn't make sense, because `'projects' | 'education' | 'community' | string` will actually result in `string` and no typing.

But what if `links` comes from outside and its content is not known in advance?

**Comment by pedrodurek** [comment]
The types from `t` function are meant to ensure that we'll always render the proper translations and there is no typo in the key passed to it. If we don't know the labels (literal values) in advance, what will you render instead? If `t` function doesn't find the translation for the given key, it'll place the key instead (`key.title`), and that's not ideal. That's what we want to prevent with typescript.

**Comment by pedrodurek** [comment]
The labels coming from the backend may change, cases by case, but you must know the different options that it can return, and based on that you'll type the shape of links

**Comment by pedrodurek** [comment]
For example:
```tsx
type Link = {
  href: string;
  label: 'projects' | 'community' | 'education'
}

const fetchLinks = (): Promise<Links[]> => {
}
```

**Comment by FanManutd** [comment]
> The types from `t` function are meant to ensure that we'll always render the proper translations and there is no typo in the key passed to it. If we don't know the labels (literal values) in advance, what will you render instead? If `t` function doesn't find the translation for the given key, it'll place the key instead (`key.title`), and that's not ideal. That's what we want to prevent with typescript.

Well, that sounds reasonable. Initially, I thought of `t` function typing as an option to use autocomplete, rather than type safety. Perhaps it was wrong on my part. Thanks for the answer.

**Comment by pedrodurek** [comment]
Yeah, it provides autocomplete and type safety.
