### ISSUE TITLE
Typescript declaration does not include new `allowObjectInHTMLChildren` option

### ISSUE THREAD

**Issue by cravend** [i18next/react-i18next#1506]
## 🐛 Bug Report

Following PR #1492 and issue #1483, a new option (`allowObjectInHTMLChildren`) was added to fix the `<Trans />` component. However, this seems to have been left out of the index.d.ts file, and is still raising errors inside the Trans component.

## To Reproduce

https://github.com/cravend/react-i18next-debug

## Expected behavior

The option works as expected.

## Your Environment

- *runtime version*: Typescript 4.6.3
- *i18next version*: 21.8.3, react-i18next 11.16.9
- *os*: Mac

**Comment by adrai** [comment]
@pedrodurek should we wait for #1501 ?

**Comment by pedrodurek** [comment]
Hey @cravend, sorry for the delayed response, actually you should set `allowObjectInHTMLChildren` type declarations file: https://codesandbox.io/s/react-i18next-typed-keys-bug-forked-x77zq?file=/react-i18next.d.ts

**Comment by Igosuki** [comment]
Setting `allowObjectInHTMLChildren` to true fixes the Trans component interpolation compilation but breaks children collocation, for example : 

```
<span>
          {t('congrats', { ns: 'common' })}{' '}
          <span>Hi</span>
</span>
```

Breaks with `TS2746: This JSX tag's 'children' prop expects a single child of type 'ReactNode | Record ', but multiple children were provided.`

**Comment by Igosuki** [comment]
Not really stale...
