### ISSUE TITLE
TS doesn't check props of wrapping component

### ISSUE THREAD

**Issue by vovsemenv** [i18next/react-i18next#1510]
react-i18next
"version": "11.16.9"
ts
"typescript": "4.6.2"

```ts
// Shoud have ts error (props dont have t)
const TestCompError: FC<{ testProp: number }> = () => <div />;
export const TestCompErrorHOC = withTranslation()(TestCompError);

// Shoud be ok
const TestCompSuccess: FC<{ testProp: number } & WithTranslation> = () => <div />;
export const TestCompSuccessHOC = withTranslation()(TestCompSuccess);
```

**Comment by pedrodurek** [comment]
If you try to access `t` in the first case, it will return a ts error:
```tsx
const TestCompError: FC<{ testProp: number }> = ({t}) => <div />;
export const TestCompErrorHOC = withTranslation()(TestCompError);
```

**Comment by pedrodurek** [comment]
Sorry, I don't follow. What do you mean by _"with this error i could find useless withTranslation usages and delete it"_. Could clarify it a bit further?

**Comment by vovsemenv** [comment]
yes, i have some cases when i refactored whole component and remove all usages of `t` but forgot to delete lines that actually wrap the component.
But it's rare case
