### ISSUE TITLE
react-i18next with Suspense break dom layout info

### ISSUE THREAD

**Issue by Bowen7** [i18next/react-i18next#1514]
## 🐛 Bug Report

react-i18next with Suspense break dom layout info

## To Reproduce

A [codesandbox](https://codesandbox.io/s/react-i18next-suspense-54qjnd?file=/src/test.js)

```js
// Test.js
import React, { useCallback } from "react";
import { useTranslation } from "react-i18next";

const A = () => {
  // code from https://reactjs.org/docs/hooks-faq.html#how-can-i-measure-a-dom-node
  const measuredRef = useCallback((node) => {
    if (node !== null) {
      console.log("A: ", node.getBoundingClientRect());
    }
  }, []);
  return <p ref={measuredRef}>123</p>;
};

const B = () => {
  const { t } = useTranslation();
  const measuredRef = useCallback((node) => {
    if (node !== null) {
      console.log("B: ", node.getBoundingClientRect());
    }
  }, []);
  return <p ref={measuredRef}>123</p>;
};

const Test = () => (
  <div>
    <A />
    <B />
  </div>
);

export { Test };
```

Will log:
```
A:  DOMRect {x: 0, y: 0, width: 0, height: 0, top: 0…}
B:  DOMRect {x: 8, y: 50, width: 1090, height: 18, top: 50…}
```

This is strange for me (I don't know much about Suspense). The output of `A` is unexpected.
Also, I find a related question in [StackOverflow](https://stackoverflow.com/questions/58871043/react-i18next-suspense)

## Expected behavior

So, how can I measure a DOM node in the `A`component(without `useTranslation`)?

## Your Environment

- *runtime version*: Chrome 101.0.4951.64
- *i18next version*: 21.8.8
- *os*: Mac M1

**Comment by adrai** [comment]
probably related: https://github.com/facebook/react/issues/18706

**Comment by adrai** [comment]
Seems to work with newer React versions: https://codesandbox.io/s/react-i18next-suspense-forked-4tk019?file=/src/test.js
