### ISSUE TITLE
Trans escapes html tags in `defaultVariables` if `values` is not specified or interpolation prefix and suffix are not specified in `tOptions`

### ISSUE THREAD

**Issue by AlexKrupko** [i18next/react-i18next#1515]
Hi there,

I use the following `interpolation` config for the i18next -
```js
interpolation: {
    defaultVariables: {
        company: 'Company name<sup>TM</sup>',
    },
    escapeValue: false,
}, 
```
As you can see we have a html tag inside variable. 
The translation string is following - `"Test text. My company is <strong>{{ company }}</strong>"`
Then put it to the `Trans` component - 
```jsx
<Trans i18nKey="testKey" />
```
Trans recognizes `strong` tag, but ignores `sup` tag inside default variable. But if we pass also `values` prop, everything will work as expected, all tags are recognized as html, not plain text. 
```jsx
<Trans i18nKey="testKey" values={{}} />
```

The reason of that behavior is following lines in `Trans` component source code - 
```js
const interpolationOverride = values
        ? tOptions.interpolation
        : { interpolation: { ...tOptions.interpolation, prefix: '#$?', suffix: '?$#' } };
```
So, if we don't provide a `values` prop, the `Trans` component uses custom prefix and suffix which are different from the default ones. As result, the `t` function can't interpolate this variable. Then it will be interpolated anyway inside the `mapAST` function, but as text node. 

You can play with it on [Codesandbox](https://codesandbox.io/s/vigilant-mestorf-q4ylec?file=/src/App.js:860-887)

I don't know why the custom prefix and suffix are used there, but I guess the `Trans` component should nest global interpolation options from i18n and override them from `tOptions` prop, and don't depend of `values` prop - 
```js
const interpolationOverride = { interpolation: { ...i18n.options.interpolation, ...tOptions.interpolation } };
```

Thanks

**Comment by adrai** [comment]
I suspect the special interpolation prefix (#$?) and suffix (?$#) were added to skip the i18next default interpolation... maybe @jamuhl can help here?

**Comment by AlexKrupko** [comment]
@adrai , yes it seems so. But that's the problem for me. 
Also why do we need to skip the default interpolation here? I checked the Trans component with my suggested condition above in my project. And it seems like everything is ok. 
Even if there is some reason to skip it here, then it should be interpolated correctly in `mapAST` function, i guess.

**Comment by jamuhl** [comment]
it does not interpolate react elements (there is no html)

**Comment by jamuhl** [comment]
adding `sup` tag to  https://github.com/i18next/react-i18next/blob/master/src/context.js#L10 should be enough to make it work (at least if strong works)

read: https://react.i18next.com/latest/trans-component#usage-with-simple-html-elements-like-less-than-br-greater-than-and-others-v10.4.0

**Comment by AlexKrupko** [comment]
Hi @jamuhl, 
no, you are wrong, it's not enough. 
Please just open my [sandbox example](https://codesandbox.io/s/vigilant-mestorf-q4ylec?file=/src/App.js:860-887)
You will found all configuration options that I used and code examples I described in my first message

**Comment by adrai** [comment]
Would you like try a Pull Request with a dedicated test, so @jamuhl might be able to review it?

**Comment by jamuhl** [comment]
Didn't read the issue careful enough...read `strong` works without looking in details (strong only works because it's not in the variable that gets interpolated)

Using values comes from a different use case -> https://react.i18next.com/latest/trans-component#alternative-usage-components-array (interpolated components do not come from children; main reason it exists ICU syntax can't be used in react children as it would be invalid)

`defaultVariables` is not supported as is in Trans (only in the workaround for ICU as interpolation works normal there).

So my next guess...adding `defaultVariables` here might work: https://github.com/i18next/react-i18next/blob/b2dcdfadc7e5433d6044080459bb0cd8056ccb92/src/Trans.js#L119

**Comment by AlexKrupko** [comment]
@jamuhl ,
Unfortunately no, it also doesn't work
Moreover, it can't work. If we are in `renderNodes` function, so node types are already defined and this is `text` for `{{ companyName }}` children. 
It should be interpolated inside `t` function before calling `renderNodes`. Exactly this behavior we have if specify `values` prop. 

Could you answer on my question I asked before. Why do you try to skip interpolation by setting your custom prefix and suffix if no `values` specified? Is there some hidden logic that I don't understand?

**Comment by jamuhl** [comment]
have a look at: https://react.i18next.com/latest/trans-component#interpolation

-> we get the translation using `t` here: https://github.com/i18next/react-i18next/blob/master/src/Trans.js#L327
-> but the interpolation value we get later here: https://github.com/i18next/react-i18next/blob/master/src/Trans.js#L132 and here https://github.com/i18next/react-i18next/blob/master/src/Trans.js#L189 using data from children https://github.com/i18next/react-i18next/blob/master/src/Trans.js#L132

**Comment by AlexKrupko** [comment]
yes, I got it. But anyway it doesn't work
If I put `companyName` as a React component, I got `My company is <strong>[object Object]</strong>` as a result 
```jsx
<Trans i18nKey="testKey">
    {{companyName: <>Company name<sup>TM</sup></>}}
</Trans>
// => My company is <strong>[object Object]</strong>
```

If put it as a string, the `sup` tag is not interpolated. 
```jsx
<Trans i18nKey="testKey">
    {{companyName: 'Company name<sup>TM</sup>'}}
</Trans>
// => My company is <strong>Company name&lt;sup&gt;TM&lt;/sup&gt;</strong>
```

But again, if we add `values` prop to use alternative variant, everything works as expected. 
```jsx
<Trans i18nKey="testKey" values={{}}>
    {{companyName: 'Company name<sup>TM</sup>'}}
</Trans>
// => My company is <strong>Company name<sup>TM</sup></strong>
```

I've fixed this issue by wrapping in my own component, but it looks not good. I'd like it works out of the box.
```jsx
const Trans = ({values = {}, ...props}) => <I18nTrans values={values} {...props} />;
```

**Comment by jamuhl** [comment]
The reason it does not work is this change: https://github.com/i18next/react-i18next/issues/1344

Why it works passing in values is that it's a different use case and interpolates already in the `t` call - therefor html parsing sees that `sup`. Regular Trans usage picks the interpolation values from the content and therefore delays it.

Alternatives that work:

```js
testKey: "Test text. My company is <strong>{{ company }}</strong>",
testKey2: "Test text. My company is <2>{{ company }}<1>TM</1></2>",
       
       // use the "TM" char
      <Trans i18nKey="testKey">
        My company is {{ company: "Company name ™" }}
      </Trans>
      <hr />

      // Threat the sup as a react element as interpolating does not allow html tags inside
      <Trans i18nKey="testKey2">
        My company is{" "}
        <strong>
          {{ company: "Company name " }}
          <sup>TM</sup>
        </strong>
      </Trans>
      <hr />
```

To make this work we would have to either break https://github.com/i18next/react-i18next/issues/1344 (basically adding values already breaks that issue) or check if the interpolated value has any valid closing html tag used in `transKeepBasicHtmlNodesFor` and call `renderNodes` for that content so html get parsed for that content.

Would mean to:

1) check if `transSupportBasicHtmlNodes` is enabled and the content has valid html tags that are in `transKeepBasicHtmlNodesFor` array
2) Parse the content like [transSupportBasicHtmlNodes](https://github.com/i18next/react-i18next/blob/master/src/Trans.js#L136)
3) call mapAst correctly like here: https://github.com/i18next/react-i18next/blob/master/src/Trans.js#L211

**Comment by jamuhl** [comment]
On the other hand I'm not really sure we should allow react-nodes inside interpolated content...even if done restricted https://github.com/i18next/react-i18next/blob/master/test/trans.render.spec.js#L160 it feels like something one should not do

**Comment by adrai** [comment]
//cc: @ckruse

**Comment by AlexKrupko** [comment]
Hi @jamuhl ,

Unfortunately, none of these alternatives is convenient for me. The `company` is provided by customer and it should contain exactly `<sup>TM</sup>` part, but not a regular trademark symbol. Because of that we can't split it and hardcode the `<1>TM</1>` to the json since most of companies don't have it in their names. So, for us it should be exactly one single string with html tag inside defined in the `defaultVariables`.

Also, I've checked my suggestion yesterday for `interpolationOverride` from the first message. And it breaks 8 other tests in `thans.render.spec.js`.

**Comment by jamuhl** [comment]
Last alternative use nesting instead of interpolation:

```js
   en: {
      common: {
        companyName: "Company name<sup>TM</sup>",
        testKey: "Test text. My company is <strong>$t( companyName )</strong>",
```

**Comment by jamuhl** [comment]
PR with 

1) check if transSupportBasicHtmlNodes is enabled and the content has valid html tags that are in transKeepBasicHtmlNodesFor array
2) Parse the content like [transSupportBasicHtmlNodes](https://github.com/i18next/react-i18next/blob/master/src/Trans.js#L136)
3) call mapAst correctly like here: https://github.com/i18next/react-i18next/blob/master/src/Trans.js#L211

will be only alternative to a workaround

**Comment by AlexKrupko** [comment]
yes, this alternative  with nesting key works for me. I don't know why I did't try it before.

The only one thing is we can't add `companyName` to the json as we get it from conf. But I solved it with `parseMissingKeyHandler` function - 
```js
appendNamespaceToMissingKey: false,
parseMissingKeyHandler: (key, defaultValue) =>
{
    if (i18n.options.interpolation?.defaultVariables?.hasOwnProperty(key)) {
        return i18n.options.interpolation.defaultVariables[key];
    }

    throw new Error('Error loading locale namespace');
},
```

**Comment by AlexKrupko** [comment]
even better variant. I add it to the common namespace with `addResource` function to prevent error about missing key 
```js
i18n.use(ChainedBackend)
    .use(LanguageDetector)
    .use(initReactI18next)
    .init({
        supportedLngs: supportedLocales.map(({locale}) => locale),
        fallbackLng: false,
        fallbackNS: 'common',
        ns: 'common',
        defaultNS: 'common',
        load: 'languageOnly',
        debug: process.env.NODE_ENV === 'development',
        appendNamespaceToMissingKey: true,
        parseMissingKeyHandler: () =>
        {
            throw new Error('Error loading locale namespace');
        },
        react: {
            useSuspense: false,
            transSupportBasicHtmlNodes: true,
            transKeepBasicHtmlNodesFor: ['br', 'strong', 'em', 'b', 'i', 'u', 'sup', 'sub', 'mark', 'small', 'del', 'ins'],
        },
       // ....
    });



// Then add it to the resources in the Company provider
const {skin} = useApplicationConf();
const {current: {locale}, i18n: {addResource, options: {defaultNS = 'common'}}} = useLocale();
const {name, } = companies[skin];

const value = useMemo(() =>
{
    const companyName = getCompanyLocalizedParameter(name, locale);
    addResource(locale, defaultNS, 'companyName', companyName);

    return {
        name: companyName,
        // ...
    };
}, [name, locale, addResource, defaultNS]);

```
