### ISSUE TITLE
Improving razzle SSR application bundle size

### ISSUE THREAD

**Issue by Ibadichan** [i18next/react-i18next#1519]
Hi! Thank you for a good library. 
I have recently optimized the package size of my application and want to improve the SSR example if this is the right optimization.

https://github.com/i18next/react-i18next/blob/master/example/razzle-ssr/src/i18n.js#L30
Do we need to use "i18next-browser-language detector" with SSR application?
I think we can set `lng: window.initialLanguage` in options to avoid loading the language detector library in the production environment.

**Comment by adrai** [comment]
yes, on server side i18next-browser-language-detector is probably not necessary

**Comment by Ibadichan** [comment]
@adrai , I mean, it's not necessarily on the client side, when the language is detected on the server (react SSR).
Can I open a PR?

**Comment by adrai** [comment]
In theory the server side could set the initialLanguage and the client will try to detect a more suitable language for the user...

Yes, feel free to open a PR

**Comment by Ibadichan** [comment]
Hmm, I forgot that `i18next-browser-languagedetector` caches the user's language (for example, in cookies),
so if the user changes the language without the browser language detector installed, the server will not extract this language from cookies when the page is reloaded, that can cause bugs. If it is right, close the issue please.
