### ISSUE TITLE
Fallback does not work when using `returnObjects: true` option

### ISSUE THREAD

**Issue by Ibadichan** [i18next/react-i18next#1523]
## 🐛 Bug Report

Hello. Thank you very much for the library. I am developing a `react` application and  have one problem related to the `returnObjects: true` option (I use this option to read text data from react components). The `fallbackLng` option in this case stops working for nested keys and returns `undefined` instead. Is there any way to solve this problem? Thank you very much.

## To Reproduce
Here is the react hook I use:
```js
function useTextContent(ns = [], key, values = {}, options = {}) {
  const {
    camelizeKeys = true,
  } = options;

  const hostname = useContext(HostnameContext);

  const [translate] = useTranslation(ns);

  let textContent = translate(
    key,
    {
      hostname,
      site_name: getSiteName(hostname),
      support_mail: getSupportMail(hostname),
      returnObjects: true, // is set to true
      ...values,
    },
  );

  if (camelizeKeys) {
    textContent = humps.camelizeKeys(textContent);
  }

  return textContent;
}

function MyComponent() {
  const meta = useTextContent(['cabinet'], 'meta');
  const textContent = useTextContent(['cabinet'], 'content', {
    foo: 'foo',
    bar: 'bar',
  });

  return (
    <section>
      {/* Will be `undefined` if nested key `title` is not found */}
      <h1>{textContent.title}</h1>

      <p>{textContent.info}</p>

      <ul>
        {textContent.list.map((listItem) => (
          <li>
            <h2>{listItem.title}</h2>
            <p>{listItem.text}</p>
          </li>
        ))}
      </ul>
    </section>
  )
}
```

## Expected behavior
If nested key is not found than get if from fallback language.

**Comment by adrai** [comment]
Can you please provide a complete reproducible example.
Something like this? https://codesandbox.io/s/dazzling-zhukovsky-r50zyo?file=/src/index.js

**Comment by Ibadichan** [comment]
@adrai , thank you for the template!
https://codesandbox.io/s/gallant-gauss-yhpjx3?file=/src/index.js

**Comment by adrai** [comment]
Ahh, now I understand what you are looking for...
No, this is not possible, since the lookup key is `"tree"` and that key is found in `"ru"`

**Comment by Ibadichan** [comment]
@adrai , could you please check my solution to this problem?
https://codesandbox.io/s/bold-snowflake-7p425r?file=/src/index.js
I decided to just create a `fallback` text content and do a `merge` of two objects.

So is it a good idea to pass `lng` option directly to `t()` function params?

**Comment by adrai** [comment]
If this works for you, then it's ok.
Passing lng via t options is ok.
