### ISSUE TITLE
Support customize I18nextContext 

### ISSUE THREAD

**Issue by Jokcy** [i18next/react-i18next#1524]
## 🚀 Feature Proposal

Provide a `customizeI18next` function to create all components/hooks of i18next-react. The function signature may look like:

```
function customizeI18next(context: ReactContext): {
  I18nextProvider,
  Trans,
  useTranslation,
  ..etc
}
```

The main purpose of this api is to provide multiple nestable I18next context in the same application tree.

```
<I18nextProvide1>
  <I18nextProvide1>
    <YourApp />
  </I18nextProvide1>
</I18nextProvide1>
```

Add this api will not affect current usage.

## Motivation

We are facing a scenario that we have a module federation app1 that has it's own i18n, and another app2 will run app1 inside and inject some components into app1. Something like:

```js
<App2>
  <App1 components={{ Comp1: xxx }} />
</App2>
```

We want mange i18n in each app and they won't affect each other, so I suppose the best way to do this is use customize context to provide i18next instance

## Example

```js
const {I18nextProvide: I18nextProvide1, Trans: Trans1} = customizeI18next(React.createContext())
const {I18nextProvide: I18nextProvide2, Trans: Trans2} = customizeI18next(React.createContext())

// render app
<I18nextProvide1>
  <I18nextProvide1>
    <YourApp />
  </I18nextProvide1>
</I18nextProvide1>

// in components
// if you want use i18n1
<Trans1 i18nKey="xxx" />

// if you want use i18n2
<Trans2 i18nKey="xxx" />
```

**Comment by Jokcy** [comment]
I can pr to implement this if you accept this proposal.

**Comment by adrai** [comment]
usually the provider is defined in the component library: https://github.com/i18next/react-i18next/blob/2eb634989abaeb657d2596ef7cc50483bfb6a68b/example/react-component-lib/src/other-lib/component.js#L14

**Comment by Jokcy** [comment]
> usually the provider is defined in the component library:
> 
> https://github.com/i18next/react-i18next/blob/2eb634989abaeb657d2596ef7cc50483bfb6a68b/example/react-component-lib/src/other-lib/component.js#L14

I know, the library can still provide a default I18nextProvider and for most use case it's enough. Provide a customize api will improve the flexibility for scenarios like mine.

**Comment by Jokcy** [comment]
@jamuhl It's not about who's responsibility but another option, just like we can pass an i18next instance to Trans to switch instance, customize context will help to create multiple copy of i18next-react at the top level.

**Comment by jamuhl** [comment]
Still including your option would mean we recommend that option more than all possible alternatives...which option is best depends strongly on the scenario one has + personal taste

**Comment by Jokcy** [comment]
To me another option is always good since we won't break any existing apis.

**Comment by Jokcy** [comment]
> I think it is also the fact of having another concept to maintain, docs, support, etc.
> 
> If you think this is not the case, you may try a PR so this could be reviewed in more detail. But no guarantee this will land.

OK, I will try
