### ISSUE TITLE
Any text inside <link> tag is rendered outside of the tag.

### ISSUE THREAD

**Issue by iaroslavshvets** [i18next/react-i18next#1526]
## 🐛 Bug Report

If translation value used with Trans is using tag called `link`, like `<link>SOME_TEXT</link>` tag, `SOME_TEXT` part will be rendered outside of the empty tag (for example if `<strong />` is passed as `link` component, it will render`<strong></strong>SOME_TEXT`). Changing name to any other than `link` will produce correct output. 

## To Reproduce

A [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

codesandbox: https://codesandbox.io/s/react-i18next-playground-forked-2fhulx

```js
import i18n from "i18next";
import React from "react";
import ReactDOM from "react-dom/client";
import { I18nextProvider, Trans } from "react-i18next";

i18n.init({
  fallbackLng: "en",
  lng: "en",
  resources: {
    en: {
      translation: {
        link_key: "<link>inside_text</link>"
      }
    }
  },
  interpolation: {
    escapeValue: false
  },
  react: {
    useSuspense: false
  }
});

const App = () => {
  return (
    <I18nextProvider i18n={i18n}>
      <Trans i18nKey="link_key" components={{link: <strong />}}/>
    </I18nextProvider>
  );
}

const root = ReactDOM.createRoot(document.getElementById("root"));
root.render(<App />);
```

## Expected behavior

text from the translation value should be inside the <link> tag.

```js
<strong>inside_text</strong>
```

## Your Environment

- *runtime version*: i.e. node v14-16, browser (any)
- *i18next version*: 21.8.11
- *react-i18next*: 11.17.3
- *os*: Mac, Linux

**Comment by jamuhl** [comment]
Element names can not be names of valid html elements

**Comment by adrai** [comment]
<img width="783" alt="image" src="https://user-images.githubusercontent.com/1086194/176174611-cb8a1185-5d07-4fff-95b1-426773509725.png">

https://react.i18next.com/latest/trans-component#alternative-usage-which-lists-the-components-v11.6.0

**Comment by iaroslavshvets** [comment]
> <img alt="image" width="783" src="https://user-images.githubusercontent.com/1086194/176174611-cb8a1185-5d07-4fff-95b1-426773509725.png">
> 
> [react.i18next.com/latest/trans-component#alternative-usage-which-lists-the-components-v11.6.0](https://react.i18next.com/latest/trans-component#alternative-usage-which-lists-the-components-v11.6.0)

The thing is that 'link' is not listed in the array of reserved tags https://github.com/i18next/react-i18next/blob/584e91b1312aae7ad4fc09818eacb7ef6b1c398f/react-i18next.js#L349. I did expect, that I can choose which tags are reserved... Correct me, if I'm wrong.

**Comment by jamuhl** [comment]
nope:

transKeepBasicHtmlNodesFor: allowes to have basic html in your translations without passing components for them

the reserved tags are more related to how html parser will convert them.
