### ISSUE TITLE
Change in the way React is imported by the UMD module in 11.17.3

### ISSUE THREAD

**Issue by glondu** [i18next/react-i18next#1527]
## 💥 Regression Report

`dist/umd/react-i18next.min.js` expects React to be available as `react` whereas `umd/react.production.js` exports `React`.

## Last working version

Worked up to version: 11.17.2

Stopped working in version: 11.17.3

## To Reproduce

Create a file `index.html`:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>Bugreport</title>
  </head>
  <body>
    <script src="node_modules/react/umd/react.production.min.js"></script>
    <script src="node_modules/i18next/dist/umd/i18next.min.js"></script>
    <script src="node_modules/react-i18next/dist/umd/react-i18next.min.js"></script>
  </body>
</html>
```

Create a file `package.json`:
```json
{
  "name": "bugreport-testcase",
  "version": "0.0.0",
  "description": "Bugreport test case",
  "author": "Stéphane Glondu",
  "license": "AGPL-3.0",
  "dependencies": {
    "i18next": "^19.7.0",
    "react": "^16.13.1",
    "react-i18next": "^11.7.3"
  }
}
```

Run:
```
npm install
python3 -m http.server
```

Browse to `http://0.0.0.0:8000/`, and open the JS console. There is an error `Uncaught TypeError: n is undefined`.

## Expected behavior

No error.

Adding:
```html
<script>var react = React;</script>
```
before loading `react-i18next` fixes the issue.

## Your Environment

- *runtime version*: Firefox 91.10.0esr
- *i18next version*: 19.9.2
- *os*: Linux

**Comment by adrai** [comment]
fyi: https://github.com/i18next/react-i18next/pull/1525 @jy95

**Comment by adrai** [comment]
v11.17.4 has just been published

**Comment by glondu** [comment]
Thank you for the prompt reaction!

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏
