### ISSUE TITLE
How to extract translation keys from the parameter of `t` to the separate type?

### ISSUE THREAD

**Issue by vadimyen** [i18next/react-i18next#1530]
How can I extract the type of the possible keys from `t` function? It works perfectly when I use it inside components after `useTranslation()` call, so I want to use the type anywhere, for example, as the type of a prop.

## To Reproduce
I tried something like this, but it looks weird and I get the error `TS2589: Type instantiation is excessively deep and possibly infinite`
```ts
 type TranslationKeys = Parameters<ReturnType<typeof useTranslation>['t']>[0]
```
My declaration file:

```ts
import en from 'assets/i18n/en-US.json';

type Resources = typeof en;

declare module 'react-i18next' {
  interface CustomTypeOptions {
    resources: Resources;
  }
}
```
I can construct it on myself by `Resources` manipulations, but it should be possible to do it "natively"
## Your Environment
- *i18next version*: 21.8.1
- *react-i18next*: 11.16.9
- *typescript*: 4.6.4

**Comment by pedrodurek** [comment]
Hey @vadimyen, you should be able to accomplish it with the `TFuncKey`.
```tsx
type TranslationKeys = TFuncKey<'translation'>
```

The generic passed to `TFuncKey` is the namespace that you want the keys to be inferred with. It accepts singles and multi namespaces (array).
If you don't pass any argument, it'll default with the `defaultNS`.

**Comment by develohpanda** [comment]
Hello @pedrodurek! I'm trying to use `TFuncKey<'translation'>` to type a wrapped `t` function, however something is a bit off. Would you be able to help me figure this out?

In the screenshot below, `foo` is a simple function which wraps the `t` function, and types the key using `TFuncKey`. If I call `foo` with a valid key, the return type is not a string, but also includes the types in the 2nd level of translations from my json file, for some reason.

![image](https://user-images.githubusercontent.com/4312346/199914295-33790bd6-f060-4677-a222-d789dc8b06f3.png)

If I call `t` directly with the same key, I get the expected `string` return type.

![image](https://user-images.githubusercontent.com/4312346/199914623-42e2f006-d153-4388-a4ee-969bea8a91a8.png)

This wrapping may seem a bit pointless but we've got some logic to execute before each translation and I was hoping wrapping like this may do the job. I can create a codesandbox next week if that'll help.

**Comment by howlettt** [comment]
I believe the issue with your `foo` function is you need to add the generic type to `TFuncKey`, for example `TFuncKey<"YourNamespaceHere">`

**Comment by ericlesaquiles** [comment]
I'm having a quite similar issue here. 
I've tried doing `type TranslationKeys = TFuncKey<'translation'>`, and, although my translation keys fit in there (ie. I can do things like `const v: TranslationKeys = 'user.acceptedTerms'`), it doesn't work when I try to wrap a function - it would seem `TranslationKeys` has more than `t` would get.

Namely, I get essentially the same error as @develohpanda when trying to wrap t

**Comment by gladiuscode** [comment]
Hi all!
It may be late, but I've been experiencing this issue today and managed to fix it with the following steps:

### Step 1

Upgrade Typescript to version > 5.1.6. This is required to enhance autocompletion and fix the annoying recursive issue.

### Step 2

Follow i18next guidelines to properly extend its global type. Here there is my implementation:
```
declare module 'i18next' {
  interface CustomTypeOptions {
    defaultNS: <-- your default namespace
    ns: <-- your namespaces
    resources: <-- your resources;
  }
}
```
I've put this file under **PROJECT_ROOT/@types/**.

### Step 3

Create a file in which you create the following type to use
to properly type localized string that match i18next.t argument.
```
import {ParseKeys} from 'i18next';

type NS = <your namespaces array>

type DefaultNS = <your default namespace>;

export type LocalizedLabelKey =
  | ParseKeys<NS, {}, DefaultNS>
  | TemplateStringsArray;
```

Please bear in mind that it may not work with your project requirements. My project is fairly simple and I don't leverage i18next to its full scope. 
I haven't tested this implementation with custom key prefixes or with all the options that you can pass to i18next.t function itself.
You can play around with LocalizedLabelKey type and ParseKeys generics to tweak this implementation and match your requirements.

I hope that you will find it helpful.

Cheers!

**Comment by natezhengbne** [comment]
> This gets me close with `v25.0.1` (assuming you define `CustomTypeOptions` with your resources):
> 
> type Keys = ParseKeys<[FlatNamespace]>;
> However, it doesn't enforce namespaces properly. In the example below, note that `specific` is an acceptable value, which is wrong. It should be prefixed with `myNamespace:`.
> 
> import type { FlatNamespace, ParseKeys } from 'i18next';
> 
> declare module 'i18next' {
>   interface CustomTypeOptions {
>     resources: {
>       translation: {
>         generic: 'generic',
>       },
>       myNamespace: {
>         specific: 'specific',
>       },
>     }
>   }
> }
> 
> type Keys = ParseKeys<[FlatNamespace]>;
> // 'generic' | 'specific' | 'translation:generic' | 'myNamespace:specific'
> Looking at the type definition for `t`, they use something like this:
> 
> type InferArrayValuesElseReturnType<T> = T extends (infer A)[] ? A : T;
> type Namespaces = [
> 	...$NormalizeIntoArray<DefaultNamespace>,
> 	...Exclude<FlatNamespace, InferArrayValuesElseReturnType<DefaultNamespace>>[]
> ];
> 
> export interface i18n {
>   t: TFunction<Namespaces>;
>   ...
> }
> Unfortunately, those types are not exported, but if I copy them into my own types and use them it works:
> 
> type Keys = ParseKeys<[Namespaces]>;
> // 'generic' | 'translation:generic' | 'myNamespace:specific'
> I am not sure why passing the namespaces that way works.

Thanks, `type Keys = ParseKeys<[Namespaces]>;` this works for me
