### ISSUE TITLE
getting missingKey when using text as keys 

### ISSUE THREAD

**Issue by cesarvarela** [i18next/react-i18next#1534]
`
i18next::translator: missingKey en translation Submitters Submitters
`

I'm getting lots of these when building a Gatsby app, which kind of makes sense because I'm using text as keys, and therefore the  JSON is empty `{}.` 

Is there a way to suppress this warning for the default language?

**Comment by adrai** [comment]
debug: false

https://github.com/i18next/i18next/issues/1634
