### ISSUE TITLE
Phrase response with \\n

### ISSUE THREAD

**Issue by gHashTag** [i18next/react-i18next#1536]
## 🐛 Bug Report

The problem with the returned string via the Phrase. The expected result of the response is a string with special characters that were in the string when sending.
The result is a string with broken special characters such as `\n`.
expect => get
`some\nstring` => `some\\nstring`

![unknown-1](https://user-images.githubusercontent.com/6774813/180497232-642d49cf-e1af-440e-adb8-260e4d883164.png)

![unknown-2](https://user-images.githubusercontent.com/6774813/180497252-d8000e14-dbcb-4753-bb53-f3815532cdf0.png)

**Comment by adrai** [comment]
react does not know \n use <br> https://react.i18next.com/latest/trans-component#usage-with-simple-html-elements-like-less-than-br-greater-than-and-others-v10.4.0

**Comment by gHashTag** [comment]
Problem with Phrase + Trans. If translations come with Phrase, then Trans shows the translation character, but should break the line

**Comment by adrai** [comment]
Can you create a reproducible example with based on something like: https://github.com/i18next/react-i18next/tree/master/example/react-native

**Comment by adrai** [comment]
btw: this may help: https://stackoverflow.com/a/69436906/1859027

**Comment by jamuhl** [comment]
It's not react-i18next that does this. It's more or less a quirk in react-native...@adrai's provided link and the accepted answer there shows it https://stackoverflow.com/a/32480141/923356 even more the comment

> If the text comes from a prop, make sure you pass it like this: <Component text={"Line1\nLine2"} /> instead of <Component text="Line1\nLine2" /> (notice the added curly braces)

**Comment by gHashTag** [comment]
@adrai 
This is the solution I used:
<img width="699" alt="image" src="https://user-images.githubusercontent.com/6774813/181062212-544eac28-b5be-4aa9-ba11-14446b8a51b7.png">

> I abandoned the Trans component for the following reasons:
> - translations with line breaks need to be formatted
> - It is impossible to pass a formatted string to Trans because the t() function returns a value without double curly brackets:
> expectation - <>{{email}}</>
> result - <></>
> - If you use the Trans component, then when transferring the translation, the component loses its meaning

**Comment by gHashTag** [comment]
> It's not react-i18next that does this. It's more or less a quirk in react-native...@adrai's provided link and the accepted answer there shows it https://stackoverflow.com/a/32480141/923356 even more the comment
> 
> > If the text comes from a prop, make sure you pass it like this: `<Component text={"Line1\nLine2"} />` instead of `<Component text="Line1\nLine2" />` (notice the added curly braces)

Not worked for me
