### ISSUE TITLE
`t()` or `Trans` with HTML entities 

### ISSUE THREAD

**Issue by hurvajs77** [i18next/react-i18next#1537]
## 🐛 Bug - HTML entities aren't translated

If I use any HTML entity in JSON, so I see output as entity code, not character. Sometimes is required use a special charter as hellip, non-break space etc.

## To Reproduce

```json
{ "text": "Some text with hellip (&hellip;) - three dots as one character" }
```

```js
t('text')

// or

<Trans i18nKey="text" />
```

## Expected behavior

I expect that pure HTML will be display as real entity.

```js
Some text with helip (…) - three dots as one character
```

## Your Environment

- *runtime version*: node v16.13,
- *i18next version*: i.e. 11.18.0
- *os*: MacOS

**Comment by adrai** [comment]
Did you already try the unescape option? https://github.com/i18next/react-i18next/pull/1529

**Comment by hurvajs77** [comment]
yeah, I did.

```json
{ "text": "u&nbps;nás" }
```

```js
<Trans shouldUnescape i18nKey="text" />
```

The reusult is always the same `u&nbsp;nás`, but must be "**u nás**" with non-break space. - doesn't matter on `shouldUnescape`. The same situation when I try to use any one other HTML entity.

Primarily, I use NPM package next-i18next (wrapper above react-i18n), I've latest versions.

**Comment by adrai** [comment]
Seems to work: https://codesandbox.io/s/react-i18next-http-example-forked-p7k3hn?file=/src/app.js:819-858
https://codesandbox.io/s/react-i18next-http-example-forked-p7k3hn?file=/src/i18n.js

**Comment by hurvajs77** [comment]
🤣🤣

really? I need to manually convert HTML entities? 🙈 LOL. Ok, in this case I stop using this crazy and funny package and write custom implementation based on real translation package ReactIntl.

**Comment by adrai** [comment]
If you're interested in having this html entities unescaped without providing a custom unescape function, why do you not contribute with a PR and extends this? https://github.com/i18next/react-i18next/blob/master/src/unescape.js

**Comment by adrai** [comment]
@hurvajs77 v11.18.2 should include also the helip... the according PR: https://github.com/i18next/react-i18next/pull/1538
