### ISSUE TITLE
UTC with render provide unexpected results with react-i18next.

### ISSUE THREAD

**Issue by NikhilPatel-Shell** [i18next/react-i18next#1540]
## To Reproduce
@pedrodurek , hey i am also facing the same issue. any solutions so far ?

**setupTest.ts** 

```
import "@testing-library/jest-dom";

jest.mock("react-i18next", () => ({
  ...jest.requireActual("react-i18next"),
  useTranslation: () => {
    return {
      t: (str: string) => str,
      i18n: {
        language: "en",
        addResourceBundle: () => jest.fn(),
        changeLanguage: () => new Promise(() => {}),
      },
    };
  },
}));
```

**Navbar.tsx ( component )**

```
const Navbar: React.FC = (): JSX.Element => {
  const { t, i18n } = useTranslation("common");

  i18n.addResourceBundle(i18n.language, "common", {
    ...getResource(i18n.language, "common"),
  });
  
  return (
  <Heading type="h4">
          <b>{t("navbar.heading")}</b>
        </Heading>
  )

```

on render, UTC result is as follows

```
<h4>
   <b>
        navbar.heading
   </b>
  </h4>
  
```
  
## Expected behavior
[](url)
 it should be the translated value instead of the key.

```js
<h4>
   <b>
        ABC Company
   </b>
  </h4>
```

## Your Environment

- *runtime version*: node v14.17.1, browser: Chrome
- *i18next version*: 21.8.14
- *react-i18next version*:  11.18.1
- *os*: Mac
- *any other relevant information*

## Found same issue with no resolution

[Github issue: 1425](https://github.com/i18next/react-i18next/issues/1425)

**Comment by pedrodurek** [comment]
Hey @NikhilPatel-Shell, is this error happening on your tests or the actual application?

**Comment by NikhilPatel-Shell** [comment]
@pedrodurek 
yes, but we resolved it actually.
in this new version, we just imported the react-i18next config.js file to setupTests.ts file and everything is solved no need to mock and useTranslation , Trans, etc.. 

and now we are getting the 

UTC debug Result as expected : 

```
<h4>
   <b>
        ABC Company
   </b>
  </h4>

```

let us know if this approach we did is not right.

**Comment by thinhnguyenpionero** [comment]
> @pedrodurek yes, but we resolved it actually. in this new version, we just imported the react-i18next config.ts file to setupTests.ts file and everything is solved no need to mock and useTranslation , Trans, etc..
> 
> and now we are getting the
> 
> UTC debug Result as expected :
> 
> ```
> <h4>
>    <b>
>         ABC Company
>    </b>
>   </h4>
> ```
> 
> let us know if this approach we did is not right.

Can you share your config.ts? Thank you
