### ISSUE TITLE
Type-safe translations do not work with context

### ISSUE THREAD

**Issue by stefan-schweiger** [i18next/react-i18next#1541]
## 🐛 Bug Report

Similar to https://github.com/i18next/react-i18next/issues/1386 having a context does not work with typesafety:

## To Reproduce

```js
{
  "key_optionA": "My Option A",
  "key_optionB": "My Option B",
}

t('key', {context: "optionA"}); // TS error, only key_optionA or key_optionB are allowed
t('key', {context: "optionB"}); // TS error
```

## Expected behavior

Such resources should be allowed to be used without the suffix.

## Your Environment

- `i18next@^21.8.14`
- `react-i18next@11.18.3`

**Comment by stefan-schweiger** [comment]
Not stale

**Comment by stefan-schweiger** [comment]
not stale

**Comment by stefan-schweiger** [comment]
not stale...

**Comment by adrai** [comment]
@pedrodurek is there a chance this is going to work with your new TypeScript rewrite? btw: any ETA?

**Comment by stefan-schweiger** [comment]
@adrai @pedrodurek any chance of removing the stale tag permanently so I don't have to post a comment every week? 😄

**Comment by adrai** [comment]
try with i18next v22.4.5

**Comment by adrai** [comment]
i18next v22.4.5 might be better

**Comment by lamo2k123** [comment]
I faced the same problem

**Comment by adrai** [comment]
https://github.com/i18next/react-i18next/issues/1617

**Comment by adrai** [comment]
i18next v23.0.0 will probably not address that yet

**Comment by ngima** [comment]
i18next v23.2.11 has still not addressed.

getting error when using context

**Comment by adrai** [comment]
handled in i18next v23.4.0 (https://github.com/i18next/i18next/pull/2007/files#diff-97e65d0ee521805ff4ac2d967b61062da8f5543569da4177ceeff689ce4463a3)
