### ISSUE TITLE
`t` is not refreshed when `keyPrefix` is changed

### ISSUE THREAD

**Issue by halouvi** [i18next/react-i18next#1542]
## 🐛 Bug Report

I wanted to use a dynamic `keyPrefix` in my component to support an A/B test we're running on the copy of a component.
When the component mounts, i fetch a new variant for the current user and so in the initial render, the `keyPrefix` is suffixed with an `undefined` that resolves to one of my variants as soon as the fetch is successful, way before the component is ever rendered on screen.

## To Reproduce

[codesandbox](https://codesandbox.io/s/react-i18next-forked-4t1xso?file=/src/app.js)

## Expected behavior
`useTranslation` should reset `t` when keyPrefix changes and reflect the new `keyPrefix`

The solution is simple:
Add `keyPrefix` to the dependency array of the useEffect starting in line 99 in `useTranslation.js` so that `t` is reset whenever `keyPrefix` changes.

## Your Environment

- *runtime version*: chrome
- *i18next version*: 21.8.10
- *os*: Mac

**Comment by adrai** [comment]
Would you like to send a Pull Request to address this?

**Comment by halouvi** [comment]
Sure, i'd love to.

**Comment by halouvi** [comment]
I couldn't create a new branch though.

**Comment by adrai** [comment]
just fork the repo and create a PR: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by adrai** [comment]
try to solve it like this: https://github.com/i18next/react-i18next/commit/47d9670a80af35430162d613f0e855d94d25b50e

**Comment by halouvi** [comment]
I'm trying to understand why `usePrevious` was added in [47d9670](https://github.com/i18next/react-i18next/commit/47d9670a80af35430162d613f0e855d94d25b50e).
I mean, there's this equality check `previousJoinedNS !== joinedNS` but as i understand it, since `joinedNS` is in the dependency array and is a string, that `useEffect` will not have even run again if `previousJoinedNS === joinedNS`.

**Comment by adrai** [comment]
https://github.com/i18next/react-i18next/issues/1517#issuecomment-1155415734
