### ISSUE TITLE
'react-i18next' module from react-typescript 4.1 no-namespace example is not using CustomTypeOptions interface

### ISSUE THREAD

**Issue by lpolon** [i18next/react-i18next#1545]
## Documentation issue
Hey everyone. I was setting up i18next in a project for the first time, following along with the [no-namespace example](https://github.com/i18next/react-i18next/blob/master/example/react-typescript4.1/no-namespaces). I realized that the [Resources interface](https://github.com/i18next/react-i18next/blob/master/example/react-typescript4.1/no-namespaces/%40types/react-i18next/index.d.ts#L6) has a deprecated annotation. It caused a bit of confusion and delay in sorting it out.

## Motivation
streamline the onboarding experience of people following along the example.

Is a PR welcome?

**Comment by adrai** [comment]
For sure, PRs are always welcome ;-)
