### ISSUE TITLE
Testing: document how to mock the t function and access it

### ISSUE THREAD

**Issue by soullivaneuh** [i18next/react-i18next#1546]
## Documentation issue

On the [testing section](https://react.i18next.com/misc/testing) of the documentation, you recommend to mock `useTranslation` this way:

```typescript
jest.mock('react-i18next', () => ({
  // this mock makes sure any components using the translate hook can use it without a warning being shown
  useTranslation: () => {
    return {
      t: (str) => str,
      i18n: {
        changeLanguage: () => new Promise(() => {}),
      },
    };
  },
}));
```

It works. However, translation function call may be done with calculated parameters, for example:

```typescript
t('common:paginationEntries', {
  first: perPage * (page - 1) + 1,
  last: page !== totalPages ? (perPage * (page - 1) + perPage) : (total),
  total,
})
```

With that mock implementation, I am not able to verify the translation parameters are correct because it will always render the key.

The best would be to replace the default function by `jest.fn().mockImplementation((str) => str)`, which does the same but allows to access to the made call and parameters.

However, I am not able to declare it outside of the `jest.mock` function scope.

Is it something doable? If yes, I think it would be a very nice documentation addition.

Thanks

**Comment by soullivaneuh** [comment]
@andrewbranch I want to verify the `first`, `last` and `total` translation parameters I pass on the `t` function have the expected computed values.

As the function is just returning the key, I can not verify the result.

This is why I need to access the mock call parameters to verify the values. Someting like:

```
expect(t.mock.calls.length).toBe(1);
expect(mockCallback.mock.calls[0][1]).toMatchObject({ first: 1, last: 10, total: 42 });
```

**Comment by adrai** [comment]
IMO, if you want to test the amount of t calls and the passed arguments, you're actually not testing your code, but the i18next or react-i18next code 🤷‍♂️

**Comment by soullivaneuh** [comment]
@adrai I am not, this is the goal of mocking. I will verify my code is indeed calling the `t` function and is passing the right parameters on it.

I am not verifying the translation result here, only the call.

**Comment by adrai** [comment]
what is currently happening, pseudo code:

```
function myFunction (arg1, arg2) {
  // library code
}

// the test:
var passArg1 = 1
var passArg2 = 2

// mock myFunction in tests:
myFunction = function (arg1, arg2) {
   assert(arg1, passArg1)
   assert(arg2, passArg2)
}

myFunction(passArg1, passArg2)
```

this is just testing your mock

**Comment by adrai** [comment]
https://github.com/i18next/react-i18next/commit/db9ba28569c891761bb30a483cb08f756178c842

**Comment by adrai** [comment]
https://react.i18next.com/misc/testing

**Comment by soullivaneuh** [comment]
Thanks for the sample and the documentation update, I'll test that soon! :+1:
