### ISSUE TITLE
How to link a web app to a local checkout of react-i18next?

### ISSUE THREAD

**Issue by amagee-willow** [i18next/react-i18next#1549]
## Documentation issue

I was not able to find documentation on how to run a web app that is connected to a build from a local checkout of the react-i18next repository, as opposed to a regular `npm install react-i18next`.

This is useful for working on fixes / modifications to the react-i18next code and wanting to see their results in context as you make them.

I was able to come up with a very fragile solution, which might be of some use to people, but hopefully someone can improve on this.

What I did:

1. Clone the `react-i18next` repository
2. From the react-i18next checkout: `yarn install` (note: `npm install` did not work (npm install output is listed below))
3. From the react-i18next checkout: `npm run build`
4. From the react-i18next checkout: `npm link` - this creates a link to `react-i18next` in a centralised location in a system-dependent location (for me it is `~/.fnm/node-versions/v16.11.1/installation/lib/node_modules/react-i18next`).
5. From my web app's repository: `rm -rf node_modules/react-i18next`
6. From my web app's repository: `npm link react-i18next` (sets up a link from my web app's repo to the link setup in step 4)
7. My web app uses webpack, so I set up the following aliases in my webpack.config.js to avoid doubling up on react-i18next's peer dependencies:

``` 
module.exports = ({ /* ... */ }) => ({
  // ...  
  resolve: {
    // ...
    alias: {
      react: path.resolve('./node_modules/react'),
      'react-dom': path.resolve('./node_modules/react-dom'),
      'i18next': path.resolve('./node_modules/i18next')
    }
  },
```

This was enough to get it to work _sometimes_, but even with all this work it was not reliable. Sometimes it would work, and sometimes I would get errors saying that my JSX elements were not valid JSX elements - looking like React was still being imported multiple times.

My simpler solution was to just copy the output file from the build on top of the index file of the `node_modules/i18next` directory in my web app. That is, simply

```
npm run build
cp react-i18next.js ~/my-webapp/node_modules/react-i18next/dist/es/index.js
```

This seems to work reliably, but in my current setup, requires a restart of my dev server to apply the change, as the dev server does not watch the files in node_modules. This can probably be fixed with configuration.

But hopefully there is a better solution than both of these!

Output from `npm install` on a clean `react-i18next` checkout:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: react-test-renderer@17.0.2
npm ERR! Found: react@16.14.0
npm ERR! node_modules/react
npm ERR!   dev react@"^16.10.2" from the root project
npm ERR!   peer react@"*" from @testing-library/react@11.2.7
npm ERR!   node_modules/@testing-library/react
npm ERR!     dev @testing-library/react@"^11.2.7" from the root project
npm ERR!   3 more (@testing-library/react-hooks, react-dom, react-shallow-renderer)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.2" from react-test-renderer@17.0.2
npm ERR! node_modules/react-test-renderer
npm ERR!   dev react-test-renderer@"^17.0.1" from the root project
npm ERR!   peer react-test-renderer@">=16.9.0" from @testing-library/react-hooks@3.7.0
npm ERR!   node_modules/@testing-library/react-hooks
npm ERR!     dev @testing-library/react-hooks@"^3.4.2" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@"17.0.2" from react-test-renderer@17.0.2
npm ERR!   node_modules/react-test-renderer
npm ERR!     dev react-test-renderer@"^17.0.1" from the root project
npm ERR!     peer react-test-renderer@">=16.9.0" from @testing-library/react-hooks@3.7.0
npm ERR!     node_modules/@testing-library/react-hooks
npm ERR!       dev @testing-library/react-hooks@"^3.4.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/amagee/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/amagee/.npm/_logs/2022-08-26T05_49_50_896Z-debug-0.log
```

**Comment by adrai** [comment]
Personally, when I need to do this type of things, I copy the dist output.
