### ISSUE TITLE
TypeScript: keyPrefix is ignored in withTranslation HOC

### ISSUE THREAD

**Issue by inomn** [i18next/react-i18next#1550]
## 🐛 Bug Report
I'm using HOC `withTranslation`, here's the usage:
```
export default withTranslation('default', { keyPrefix: 'components/errorBoundary'})(ErrorBoundary);
```

In the component:
```
const { t } = this.props;
```

TypeScript doesn't see keyPrefix
<img width="638" alt="Screenshot 2022-08-30 at 15 07 53" src="https://user-images.githubusercontent.com/6470994/187445478-542929a8-79b9-4136-bbf1-e3528f5c8da7.png">

and I'm getting errors because translation keys are not found, since I'm referring to them considering keyPrefix.

p.s. works perfectly fine with `useTranslation` hook

## To Reproduce
You should have at least 1 namespace
Class component with withTranslation, use as shown at the beginning of the issue.

## Expected behavior
Suggestions and Type checks should pass \ or be the same as with `useTranslation`

## Your Environment

- *runtime version*: node v16.15.1
- *i18next version*: 21.9.1
- *react-i18next*: 11.18.4
- *os*: Mac

**Comment by adrai** [comment]
Would you like to send a Pull Request to address this? https://github.com/i18next/react-i18next/blob/master/index.d.ts

**Comment by adrai** [comment]
btw: seems to work here: https://github.com/i18next/react-i18next/blob/master/test/typescript/withTranslation.test.tsx#L78
