### ISSUE TITLE
Website Documentation is encoded

### ISSUE THREAD

**Issue by JacobGeoGeek** [i18next/react-i18next#1553]
### Do you have a documentation issue?
I want to use the react-i18next library to translate my react app. However, the text documentation from the [website](https://www.i18next.com/) is encoded (which is weird):

<img width="1754" alt="image" src="https://user-images.githubusercontent.com/19539781/188143484-9494fa9e-7d78-4d81-b961-d154bcb1afe5.png">

I have tried Chrome and Firefox and they have the same problem.

**Comment by adrai** [comment]
<img width="835" alt="image" src="https://user-images.githubusercontent.com/1086194/188144713-9781877a-4a98-41d4-9ab7-29c1170ab7ea.png">

never seen this

**Comment by adrai** [comment]
You may clear your cache and reload the page?

**Comment by JacobGeoGeek** [comment]
I cleared the cache in Chrome, but the problem is still there.
<img width="1754" alt="image" src="https://user-images.githubusercontent.com/19539781/188146885-a080adc1-aeaf-4964-8c51-c870b6c625f8.png">

**Comment by adrai** [comment]
Sorry I have no idea....
Check for proxies / VPN... browser plugins...
Check on a different machine.... idk
