### ISSUE TITLE
UseTranslationOptions ts definition is missing nsMode

### ISSUE THREAD

**Issue by mauron85** [i18next/react-i18next#1554]
## 🐛 Bug Report

Typescript definition for UseTranslationOptions is missing nsMode prop

## To Reproduce

A [minimal reproducible example](https://minimum-reproduction.wtf/).
A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

```js
// Paste your code here
```

## Expected behavior

```js
// Paste the expected results here
```

## Your Environment

- *runtime version*: i.e. node v14, deno, browser xy
- *i18next version*: i.e. 19.5.3
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by adrai** [comment]
v11.18.6 should address this
