### ISSUE TITLE
Use parent i18next with a React components library

### ISSUE THREAD

**Issue by ugnelis** [i18next/react-i18next#1555]
## Some context
* I have a mono repo with an `app` and a components library called `ui`.
* The `app` is fetching translations from a remote server. 
* The `ui` lib uses the same translations as the `app`.

## What I have tried
* Inject the `i18next` via the `I18nextProvider` and use app translations inside the external library
* It didn't work

## Source

`app/package.json`

```json
{
  "name": "app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@types/react": "^17.0.43",
    "@types/react-dom": "^17.0.14",
    "i18next": "^21.6.14",
    "i18next-browser-languagedetector": "^6.1.4",
    "i18next-http-backend": "^1.4.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-i18next": "^11.16.2",
    "ui": "*"
  },
  ...
}
```

`app/index.tsx`

```typescript
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';
import { I18nextProvider } from 'react-i18next';
import i18n from './services/i18n';

ReactDOM.render(
  <React.StrictMode>
    <React.Suspense fallback={'Loading'}>
      <I18nextProvider i18n={i18n}>
        <App />
      </I18nextProvider>
    </React.Suspense>
  </React.StrictMode>,
  document.getElementById('root'),
);
```

`app/services/index.tsx`

```typescript
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';
import Backend from 'i18next-http-backend';
import { Http } from 'api';

i18n
  .use(Backend)
  .use(LanguageDetector)
  .use(initReactI18next)
  .init(
    {
      debug: false,
      react: {
        useSuspense: true,
      },
      backend: {
        loadPath: `${Http.baseUrl}/language/{{lng}}`,
        allowMultiLoading: false,
      },
      lng: 'en',
      fallbackLng: ['en', 'lt'],
      saveMissing: true,
      interpolation: {
        escapeValue: false,
        formatSeparator: ','
      },
    }
  );

export default i18n;
```

`app/layout/index.tsx`

```typescript
import React  from 'react';
import { I18nextProvider, useTranslation } from 'react-i18next';
import i18n from 'services/i18n';
import { Temp } from 'ui';

const Layout: React.FC = () => {

  const { t } = useTranslation();

  return (
    <>
      <I18nextProvider i18n={i18n}> {'<- NOT INJECTING'}
        <Temp />
      </I18nextProvider>
    </>
  );
};
export default Layout;

```

`ui/package.json`

```json
{
  "name": "ui",
  "version": "0.0.0",
  "main": "./dist/index.js",
  "types": "./dist/index.d.ts",
  "sideEffects": false,
  "private": true,
  "scripts": {
    "build": "tsup",
    "clean": "rm -rf dist",
    "dev": "tsup --watch",
    "lint": "eslint src/*.ts*"
  },
  "files": [
    "dist",
    "src"
  ],
  "dependencies": {
    "@types/react": "^17.0.43",
    "@types/react-dom": "^17.0.14",
    "i18next": "^21.6.14",
    "i18next-browser-languagedetector": "^6.1.4",
    "i18next-http-backend": "^1.4.0",
    "typescript": "^4.6.3",
    "react": "^17.0.2"
  },
  "devDependencies": {
    "tsup": "^5.10.1"
  },
  "tsup": {
    "clean": true,
    "dts": true,
    "external": [
      "react"
    ],
    "format": [
      "cjs"
    ],
    "entryPoints": [
      "src/index.tsx"
    ],
    "loader": {
      ".svg": "dataurl"
    }
  }
}
```

`ui/components/temp/index.tsx`

```typescript
import React, { useEffect } from 'react';
import { useTranslation } from 'react-i18next';

const Temp: React.FC = () => {
  const { t, i18n } = useTranslation();
  return <div>{t('sidebar.clients')}</div>;
};

export default Temp;
```

## Question

**Is it possible to inject parent translation for the library components?**

**Comment by adrai** [comment]
Did you compare with this setup?
https://github.com/i18next/react-i18next/blob/master/example/react-component-lib

https://github.com/i18next/react-i18next/issues/1497

**Comment by ugnelis** [comment]
> Did you compare with this setup? https://github.com/i18next/react-i18next/blob/master/example/react-component-lib
> 
> #1497

Yes, the example is different than what I am trying to achieve.
In the `react-component-lib` example, the `other-lib` has its own translations. In my case, the translations in the `app` and the `ui` lib are the same. 

I have also tried to inject the `i18n` in a different way:

`ui/components/temp/index.tsx`

```typescript
import React from 'react';
import { withTranslation, WithTranslation } from 'react-i18next';

const Temp: React.FC<WithTranslation> = ({ t, i18n }) => {
  return <div>{t('sidebar.clients')}</div>;
};
export default withTranslation()(Temp);
```

`app/layout/index.tsx`

```typescript
import React from 'react';
import { Temp } from 'ui';
import i18n from '../../services/i18n';

const Layout: React.FC = ({ children }) => {

  return (
    <>
       <Temp i18n={i18n}/>
    </>
  );
};
export default Layout;
```

This works but I would I don't like this solution because I will need to inject `i18n` in every component from the `ui` lib.
I would rather have something like the below but it doesn't work, maybe I am doing something wrong:


`app/layout/index.tsx`

```typescript
import React from 'react';
import { withTranslation, WithTranslation } from 'react-i18next';

const Temp: React.FC<WithTranslation> = ({ t, i18n }) => {
  return <div>{t('sidebar.clients')}</div>;
};
export default withTranslation()(Temp);
```

`app/layout/index.tsx`

```typescript
import React from 'react';
import { I18nextProvider } from 'react-i18next';
import { Temp } from 'ui';
import i18n from '../../services/i18n';

const Layout: React.FC = ({ children }) => {

  return (
    <>
       <I18nextProvider i18n={i18n}>
         <Temp />
       </I18nextProvider>
    </>
  );
};
export default Layout;
```

**Comment by adrai** [comment]
Seems to work: 
[react-component-lib.zip](https://github.com/i18next/react-i18next/files/9547477/react-component-lib.zip)

**Comment by ugnelis** [comment]
Thank you!

**Comment by benoit-nadaud** [comment]
Hi @ugnelis, am trying to deal with the same problem. I have an app and multiple custom packages used as dependencies in my app. I dont understand the @adrai 's solution. Could you help me ?

**Comment by ugnelis** [comment]
Try this repo: https://github.com/ugnelis/turbo-react-i18next not sure if it is working anymore

**Comment by bmarotta** [comment]
Hi @benoit-nadaud , in your example it looks like you are not initializing the translations in the component library, only in the app. Meaning that each app must make sure to initialize the translations for all components it is using. 

I would really like to see a solution that illustrates the following:

1. There is only one i18n instance shared by all components and app
2. All different component libraries and the app initialize the i18n as following:
  a. If there is no i18n instance yet, create a new instance and initialize it
  b. If there is already an i18n instance, the library/app translations are appended to it

@adrai : Any idea on how to achieve it?

**Comment by adrai** [comment]
> Any idea on how to achieve it?

not achievable...

Either you have multiple i18next instances or you pass the i18next instance to the component libraries...

I would go with: https://github.com/i18next/react-i18next/tree/master/example/react-component-lib
