### ISSUE TITLE
plural not worked in react-i18next-11.8.4

### ISSUE THREAD

**Issue by gajjardarshithasmukhbhai** [i18next/react-i18next#1556]
## 🐛 Bug Report

As per Doc [plurals-i18next](https://www.i18next.com/translation-function/plurals)
```JSON
{
  "key_one": "item",
  "key_other": "items",
  "keyWithCount_one": "{{count}} item",
  "keyWithCount_other": "{{count}} items"
}
```
it won't work in react "17.0.1", please correct me if I am wrong.

## Expected behavior
- dynamic special translation
- it will change singular/plural as per the `count` value

## solution Find
```JSON
{
   "key" : "item",
   "key_plural": "items"
}
```
## Your Environment

- *runtime version*: i.e. node v14.18.3
- *i18next version*: i.e. 19.8.4
- *os*: Mac

**Comment by jamuhl** [comment]
please read: https://www.i18next.com/misc/migration-guide#v20.x.x-to-v21.0.0

plural forms changed in v21
