### ISSUE TITLE
Global PostProcess Not Being Called

### ISSUE THREAD

**Issue by ghost** [i18next/react-i18next#1557]
## 🐛 Bug Report

Setting the `postProcess` key  as part of the InitOptions does not apply the selected postProcessor globally. 
```TypeScript
t(text.key, text.default) // Does not work with postProcessor set globally
```
```TypeScript
t(text.key, text.default, { postProcess: 'custom' }) // This does work
```

## To Reproduce

```TypeScript
import Settings, { InitOptions } from 'i18next';
import Backend from 'i18next-http-backend';
import LanguageDetector from 'i18next-browser-languagedetector';

const initOptions = (): InitOptions => ({
  debug: true,
  detection: {
    order: ['queryString', 'cookie'],
    caches: ['cookie'],
  },
  fallbackLng: 'en',
  interpolation: {
    escapeValue: false,
  },
  saveMissing: true,
  postProcess: ['custom'],
});

Settings.use(Backend)
  .use(LanguageDetector)
  .use(initReactI18next)
  .use({
    type: 'postProcessor',
    name: 'custom',
    process: (value: string, key: string, options: any, translator: any): string => {
      return 'hello';
    },
  })
  .init(initOptions);

export default Settings;

```

## Expected behavior

When a `postProcess` property is defined on the init options, that process should be ran globally for all translation calls.

## Your Environment

Window 10
Node 16.17.0
"i18next": "^21.9.2",
"i18next-browser-languagedetector": "^6.1.5",
"i18next-http-backend": "^1.4.1",
"react": "^18.2.0",

**Comment by adrai** [comment]
try to define overloadTranslationOptionHandler

https://github.com/i18next/i18next-emoji-postprocessor/blob/44fb2f4a26fbfd125b98c8f4a9e8c3f4a7fbde8c/lib/index.js#L41

**Comment by adrai** [comment]
Seems to work for me also, without overload...

https://codesandbox.io/s/react-i18next-http-example-forked-uqvyqs?file=/src/i18n.js

Please provide a reproducible example.

**Comment by jamuhl** [comment]
really should work: https://github.com/i18next/i18next/blob/master/src/Translator.js#L383
