### ISSUE TITLE
`languages ` from i18n object does not contain languages from `resources`

### ISSUE THREAD

**Issue by hornta** [i18next/react-i18next#1558]
## 🐛 Bug Report

Languages specified in `resources` are not available to use in the `languages` property of the i18n object. 

## To Reproduce

https://codesandbox.io/s/upbeat-lovelace-s36p3q

## Expected behavior

I expect the `languages` to contain all possible languages the user can switch to.

## Your Environment

Browser, react-i18n v11

**Comment by adrai** [comment]
No, the languages property is used to look up the translation value: https://www.i18next.com/overview/api#languages

**Comment by hornta** [comment]
What does "look up" mean? I assume i18n would always use the current language to find a string based on the key.

I just want to accomplish getting a list of languages user can choose from(preferably from react-i18n itself based on the resources) and the current language(also from the react-i18n object) and then build a simple UI to control this.

**Comment by adrai** [comment]
i18next does not always know all your available languages (think about lazy loading languages via backend plugin, etc...)
But if in your setup you have only inline-translations, you could do something like this:

https://codesandbox.io/s/react-i18next-http-example-forked-m7b7l4?file=/src/app.js:158-264
