### ISSUE TITLE
How to use in ecmascript5 code?

### ISSUE THREAD

**Issue by Perde1989** [i18next/react-i18next#156]
Hello! If I want to use react-i18next in React components not written in ecmascript2015 how can I load translation json?

I think I need the `@translate(['componentA'], { wait: true })` equivalent in ecmascript5 style.

Sample Code:
```
var ComponentA = React.createClass({
	render : function() {
		// I need the @translate(['componentA'], { wait: true }) equivalent in ecmascript5 javascript
		var t = reactI18next.translate;
		return <div>
			<p>{t(myNamespace:test)}</p>
		</div>
	}
});


var I18nextProvider = reactI18next.I18nextProvider;
ReactDOM.render(
	<I18nextProvider i18n={ i18n }>
		<ComponentA  />
	</I18nextProvider>,
	document.getElementById('componentA')
);
```

**Comment by jamuhl** [comment]
is the same as https://github.com/i18next/react-i18next/blob/master/example/app/components/YetAnotherComponent.js#L8

`translate('myNamespace', { wait: true})(myComponent)`

**Comment by jamuhl** [comment]
And please checkout http://locize.com if you want the translation process covered ;)

**Comment by Perde1989** [comment]
Thank you very much!
