### ISSUE TITLE
Error: Unable to resolve module ./withSSR 

### ISSUE THREAD

**Issue by mantegnous** [i18next/react-i18next#1561]
None of these files exist:
  * node_modules/react-i18next/dist/commonjs/withSSR(.native|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.svg|.native.svg|.svg)
  * node_modules/react-i18next/dist/commonjs/withSSR/index(.native|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.svg|.native.svg|.svg)
  106 | var _I18nextProvider = require("./I18nextProvider");
  107 |
> 108 | var _withSSR = require("./withSSR");
      |                         ^
  109 |
  110 | var _useSSR = require("./useSSR");
  111 |

**Comment by adrai** [comment]
Please provide a reproducible example... and more information...
No idea what you're trying to do...

https://react.i18next.com/latest/ssr#using-the-withssr-hoc
