### ISSUE TITLE
[12.0.0] Resources type is not exported anymore 

### ISSUE THREAD

**Issue by belgattitude** [i18next/react-i18next#1562]
## 🐛 Bug Report

```
> tsc --noEmit false --declaration --emitDeclarationOnly --outDir dist/types

src/types.ts:8:3 - error TS2305: Module '"react-i18next"' has no exported member 'Resources'.
```

## To Reproduce

I think it's a breaking change... You can have a look to this PR and watch for the CI failure

https://github.com/i18next/next-i18next/pull/1966

## Your Environment

- *runtime version*: i.e. node v14, deno, browser xy
- *i18next version*: i.e. 19.5.3
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by adrai** [comment]
https://app.circleci.com/pipelines/github/i18next/next-i18next/3611/workflows/427ea430-1771-4690-ba73-af7352b23c90/jobs/7720

**Comment by adrai** [comment]
It's now probably part of i18next and not react-i18next anymore: https://github.com/i18next/i18next/pull/1775 ?

**Comment by belgattitude** [comment]
Mmmh that will make it harder to support reanges of react-i18next and i18next  in next-i18next... First intuition, It should be re-exported from react-i18next v12.0.0  to prevent bc. Or least be mentionned in the changelog

**Comment by pedrodurek** [comment]
yep, we moved all types to `i18next`, where it should be since the very beginning. I put a PR adding a reference to the new doc. https://github.com/i18next/react-i18next-gitbook/pull/140

**Comment by adrai** [comment]
So can this be closed @belgattitude ?

**Comment by belgattitude** [comment]
Closed, thanks a lot
