### ISSUE TITLE
Declare module "react-i18next" doesn't work after 12 major release

### ISSUE THREAD

**Issue by Witcher1337** [i18next/react-i18next#1563]
Noticed that since the 12 version, there is no way to enlarge types for "resources". 

Declaration file looks like this:
```import 'react-i18next';
import en from '../../public/locales/en/common.json';

declare module 'react-i18next' {
  interface CustomTypeOptions  {
    defaultNS: 'common';
    resources: typeof en;
  }
}

export {}
```

Created demo, when you can upgrade and downgrade the version of react-i18next and check this as well

https://codesandbox.io/s/stoic-field-bnz3oq?file=/src/App.tsx

**Comment by meyfa** [comment]
You should be declaring types for `i18next` instead of `react-i18next`: https://www.i18next.com/overview/typescript

**Comment by Witcher1337** [comment]
> You should be declaring types for `i18next` instead of `react-i18next`: https://www.i18next.com/overview/typescript

Thx a lot!

**Comment by Witcher1337** [comment]
I just followed this doc https://react.i18next.com/latest/typescript
