### ISSUE TITLE
The prop `t` is marked as required in withI18nextTranslation(Component), but it's value is undefined.

### ISSUE THREAD

**Issue by tswaters** [i18next/react-i18next#1564]
## 🐛 Bug Report

When using withTranslation on a class component, a propType warning is raised if the `t` function is defined as a propType.

> Warning: Failed prop type: The prop `t` is marked as required in `withI18nextTranslation(_App)`, but its value is `undefined`.
I18nextWithTranslation@https://7kuq3j.csb.app/node_modules/react-i18next/dist/es/withTranslation.js:51:26

It should be noted the `t` prop is there and can be used without issue.

## To Reproduce

Refer to the following code sandbox to see a full example:  https://codesandbox.io/embed/vigorous-worker-7kuq3j

This covers it:

```js
class _MyComponent extends Component { 
  static propTypes = {
    t: func.isRequired,
  }
  render() {
    return this.props.t('Hello!')
  }
}

const MyComponent = withTranslation()(_MyComponent)
MyComponent.propTypes = _MyComponent.propTypes

export default MyComponent
```

## Workaround

Mark the propType as non-required to silence the react warnings about it.

## Expected behavior

The warning should not be raised.

## Your Environment

- *runtime version*: browser
- *i18next version*: 22.0.2
- reacti8nextversion: 12.0.0

**Comment by pedrodurek** [comment]
That's not a typescript question, but I can see the problem.

@tswaters, you assigned the same `propTypes` from `_App` to `App`. That's not true, `App` don't have required props. The `withTranslation` HoC is responsible for passing down `i18next` related props to `_App`, not `App` component.

![Screenshot 2022-10-24 at 11 32 16 AM](https://user-images.githubusercontent.com/12190482/197590827-e515fe28-c046-44b9-bca2-803ac95d7e5f.png)

You can see the props received in the image above.

Just remove the line 24, and it should remove the warning.

**Comment by tswaters** [comment]
Interesting.  I did some more tests and not hoisting the propTypes still works as expected - the "underlying" component still has it's statics I suppose and everything still works.   prop-types I can ignore, but contextTypes had me a ltitle concerned.

I wonder if the instructions on the withTranslation page on the website readme could add some clarifications in this regard.

i.e.,  add a paragraph to that section on the page that says "Any internal statics that react looks for such as propTypes, getDerivedStateFromProps and contextTypes should not need to be hoisted"

I can appreciate that there might be tons of use-cases for statics outside react internals, so it's a good flag -- but the way it's written makes it sound like the static must be hoisted or things will break which is not necessarily the case.
