### ISSUE TITLE
v12.0.0 - `returnObjects` returns an `object` type instead of the typed namespace

### ISSUE THREAD

**Issue by danr-za** [i18next/react-i18next#1565]
## 🐛 Bug Report

The typing of the returned objects when using `returnObjects: true` has broke in v12.0.0 and now returns `object` instead of the configured namespace keys.

## To Reproduce

* Add a translation namespace
* Use the following code

user.json
```json
{
  "keys": { 
    "name": "Name" 
  } 
}
```

```ts
const { t } = useTranslation(['user'])
const resources = t('user:keys', { returnObjects: true }) // <== resources is of type 'object' instead of '{name: string}'
```

## Expected behavior

Should preserve the typing as previously

## Your Environment

- *i18next version*: 12.0.0
- *os*: Mac

**Comment by pedrodurek** [comment]
Hey @danr-za, we just moved the types to `i18next`. In order to have `i18next` and `react-i18next` fully type-safe, just follow the instructions here https://www.i18next.com/overview/typescript.
In short, you just need change the `declare module "react-i18next"` line to `declare module "i18next"`.

**Comment by sklawren** [comment]
I did that and now I'm getting:
```
const {i18n} = useTranslation();

i18n.language
^^^ TS2339: Property 'language' does not exist on type 'i18n'.
```

Looking at the type of i18n now, it's:
```
declare module 'i18next' {
  interface i18n {
    reportNamespaces: ReportNamespaces;
  }
}
```

But the language property is clearly there (when output to the console), along with lots of others.

**Comment by ximex** [comment]
you need something like that
```ts
// i18next.d.ts
import "i18next";
import type { defaultNS } from "./from/your/i18n";
import type resources from "./your/resources";

declare module "i18next" {
	interface CustomTypeOptions {
		defaultNS: typeof defaultNS;
		resources: typeof resources["en"];
	}
}
```

**Comment by danr-za** [comment]
Thanks,  didn't notice that!
Closing
