### ISSUE TITLE
TFunction is declared locally but not exported

### ISSUE THREAD

**Issue by albohlabs** [i18next/react-i18next#1566]
## 🐛 Bug Report

In version < 12.0.0 the `react-i18next` lib exported a `TFunction`.

## To Reproduce

Import the `TFunction` in version 12.0.0

```js
import { TFunction } from "react-i18next";
```

## Expected behavior

I would like to type a parameter as a `TFunction` which was imported from `react-i18next`

```js
import { TFunction } from "react-i18next";

type Generator = (
  client: Client,
  t: TFunction<"common">,
) => Promise<{ title: string; link: string }>;

```

**Comment by adrai** [comment]
The TFunction is now part of i18next => https://github.com/i18next/i18next/blob/master/index.d.ts#L885

**Comment by ximex** [comment]
you have to import it now as:
```ts
import type { TFunction } from "i18next";
```

**Comment by pedrodurek** [comment]
Hey @albohlabs, we just moved the types to `i18next`. In order to have `i18next` and `react-i18next` fully type-safe, just follow the instructions here https://www.i18next.com/overview/typescript.
In short, you just need change the `declare module "react-i18next"` line to `declare module "i18next"`

**Comment by albohlabs** [comment]
Awesome. It works. Many thanks for your great work. :medal_military:
