### ISSUE TITLE
TypeScript  - Types definition file (d.ts)

### ISSUE THREAD

**Issue by alexkuc** [i18next/react-i18next#1567]
On the page [TypeScript](https://react.i18next.com/latest/typescript) of the current documentation, the global module augmentation is suggested for module `react-i18next`:

![image](https://user-images.githubusercontent.com/3331946/197531934-690167db-2002-46dc-a6b6-8f6747fc2cff.png)

However, in doing so, the types are not applied. Looking further into the issue, I found #1563.

Perhaps documentation went stale and needs updating?

If not, then perhaps I am misunderstanding something since types definition file for i18next is practically [identical](https://www.i18next.com/overview/typescript):

![image](https://user-images.githubusercontent.com/3331946/197532378-0ce2f841-2ee8-4c28-b9b6-09d88e7aed0b.png)

**Comment by adrai** [comment]
<img width="798" alt="image" src="https://user-images.githubusercontent.com/1086194/197532801-67c0a9db-48da-4c09-b982-a685374f1ba4.png">
