### ISSUE TITLE
When importing i18n in my setupTest file I get TypeError: Cannot destructure property 'config' of 'cacheKeyOptions' as it is undefined

### ISSUE THREAD

**Issue by alveshelio** [i18next/react-i18next#1569]
## 🐛 Bug Report

I'm using `react-i18next` in my App and I have not issues with the translations. However, when doing tests following this guide: https://react.i18next.com/misc/testing#testing-without-stubbing.

I'm getting an error: **TypeError: Cannot destructure property 'config' of 'cacheKeyOptions' as it is undefined.**
I've searched for this type of error and found these two issues:
https://sebastian-rogers.medium.com/cannot-destructure-property-config-of-cachekeyoptions-as-it-is-undefined-f31b383abf5c
https://github.com/callstack/react-native-testing-library/issues/743

However, both of them are saying that it's simply because Jest is outdated. This is not my case since I'm running the latest version of Jest at the moment which is 29.2.2. I'm also using `ts-jest` and it too is up to date, version 29.0.3

I've tried the other approaches that suggest to mock `useTranslations` hook, however, this does not work for me since I need to have the translations in the code and not only the translation keys.

I've deleted most of my translations files, in `public/locales/en` I only have one file for the example but in my project I have a bunch of them.

This is a Create React App V4 that I've ejected.  

## To Reproduce

Here's a [codesandbox](https://codesandbox.io/p/github/alveshelio/jest-i18n-error/draft/bitter-water?selection=%5B%7B%22endColumn%22%3A22%2C%22endLineNumber%22%3A105%2C%22startColumn%22%3A22%2C%22startLineNumber%22%3A105%7D%5D&file=%2Fsrc%2Fcomponents%2FShared%2FRangeSlider%2FRangeSlider.test.tsx&workspace=%257B%2522activeFileId%2522%253A%2522cl9qgkb1z001tlrej2gj05jqr%2522%252C%2522openFiles%2522%253A%255B%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522key%2522%253A%2522cl9qhh8nt000u2v6jmzpot8is%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522test%2522%252C%2522key%2522%253A%2522cl9qh62nb029g2v6jewpbvzab%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522cl9qgyncx01t32v6j0j23qn4o%2522%252C%2522isMinimized%2522%253Atrue%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522key%2522%253A%2522cl9qgsed000jw2v6jzwkwrysv%2522%252C%2522isMinimized%2522%253Atrue%257D%255D%257D) example

```js
// Paste your code here
```

## Expected behavior

I would expect Jest to be able to import the `i18next` instance to provide translations in my tests

## Your Environment

- *runtime version*: i.e. node v16.17.0
- *i18next*: "^21.6.14",
- *i18next-http-backend*: "^1.3.1",
- *i18next-parser*: "^6.4.0",
- *react-i18next*: "^11.16.2",
- *os*: Linux Ubuntu 20

**Comment by adrai** [comment]
sorry, no idea....
you may try to create a minimum reproducible example...
just the most necessary parts to reproduce the issue

**Comment by alveshelio** [comment]
Hi Adira,

Thank you for getting back, indeed, the problem isn't with i18next, it was with Jest. In case someone ends up with the same issue as me here's what was happening.

I have a project in Typescript but some config files are in JavaScript and Jest needs to load these config files. I'm using `ts-jest` to transform Typescript files but I was missing `babel-jest` to transform JavaScript files.

The I only needed to add `'^.+\\.js$': 'babel-jest',` to `transform` and it fixed my problem.
