### ISSUE TITLE
Type instantiation is excessively deep and possibly infinite

### ISSUE THREAD

**Issue by laclance** [i18next/react-i18next#1570]
## 🐛 Bug Report

`useTranslation()`  works fine
useTranslation('pos', { useSuspense: true })`  causes TS error

changing `declare module "i18next" ` to `declare module "react-i18next" ` removes error but  'DefaultTFuncReturn' returns an object instead of string | undefined.

## To Reproduce

```js
//react-i18next.d.ts
import { resources, defaultNS } from "./i18n";

declare module "i18next" {
  interface CustomTypeOptions {
    defaultNS: typeof defaultNS;
    resources: typeof resources["en"];
  }

  type TranslationKeys = TFuncKey
}

//i18n.ts
import i18next from 'i18next';
import { initReactI18next } from 'react-i18next';
import Locize from 'i18next-locize-backend';

export const defaultNS = 'pos';
export const resources = {
  en: {
    pos: 'pos'
  }
} as const;

const locizeOptions = {
  projectId: '593a3627-ce30-4c00-a1cb-99cc4dff6211',
  referenceLng: 'en'
};

i18next
  .use(Locize)
  .use(initReactI18next)
  .init({
    fallbackLng: 'en',
    fallbackNS: 'pos',
    defaultNS: 'pos',
    ns: ['pos'],
    saveMissing: true,
    interpolation: {
      escapeValue: false
    },
    backend: locizeOptions
  });

export default i18next;

```

## Your Environment

- *runtime version*: i.e. node v14, chrome
- *i18next version*: i.e. 22.0.2
- *os*: Ubuntu 22
- *react-i18next version*: i.e. 12.0.0

**Comment by pedrodurek** [comment]
Hey @laclance, could you add a few keys under the `pos` namespace? For example:
```tsx
export const resources = {
  en: {
    pos: {
      key1: 'key1'
    }
  }
} as const;
```

**Comment by laclance** [comment]
that removes error but does that mean i have to add all my 100's of keys?

**Comment by laclance** [comment]
also see another problem now, how to use t directly from `import { t } from 'i18next';` 
```
Argument of type '"product.enterName"' is not assignable to parameter of type 'TemplateStringsArray | `${string}:${string}` | `${string}:${any}` | (TemplateStringsArray | `${string}:${string}` | `${string}:${any}`)[]'
```

**Comment by laclance** [comment]
`useTranslation()` also causes `Type instantiation is excessively deep and possibly infinite ` but then if i close and reopen the file it goes away.

**Comment by pedrodurek** [comment]
Hey @laclance, you need at least one key, please take a look at our examples, https://github.com/i18next/react-i18next/tree/master/example/react-typescript, https://github.com/i18next/i18next/tree/master/examples/typescript
I'm closing this for now, but feel free to reopen it if you still face the same issue.

**Comment by laclance** [comment]
@pedrodurek  the problem is my translations are stored in the public folder because I am using `i18next-http-backend` so I cant import translation file for ```export const resources = {
  en: {
    translation,
  }
};```
does that mean I have to keep 2 copies of my translation file?

**Comment by ruiaraujo012** [comment]
I'm facing the same problem and I can't find any solution...

**Comment by ruiaraujo012** [comment]
@laclance how did you resolve this problem?

**Comment by laclance** [comment]
I haven't yet.
