### ISSUE TITLE
i18next-react useTranslation with version 22+ requires wrapping t function into <></>

### ISSUE THREAD

**Issue by kirill-linnik** [i18next/react-i18next#1574]
I have a project based on Ant Design and, after upgrading to version 22+ (22.0.4 to be precise), I see the following problem:

![image](https://user-images.githubusercontent.com/15168102/198839071-0be2dd8d-737f-49bd-953e-3afc691b8ab4.png)

I can workaround it by wrapping `t` function into `<></>`, but refactoring whole project because of that is a bit of a pain. I was able to re-construct issue in a playground project in a separate brunch (and you can compare to `main` where issue doesn't exist with a previous version):
https://github.com/kirill-linnik/react-redux/tree/i18next-trouble

checkout, do `yarn` - and VSCode shows you error at `Main.tsx` line 58. `yarn start` does the same,

**Comment by pedrodurek** [comment]
Hey @kirill-linnik, it seems message don't accept `null`, but t function could return `null`. I'd advice to fallback to something else. E.g.: `t('key') ?? ''`

**Comment by pedrodurek** [comment]
If you want to make the `t` function fully type-safe follow the instructions here https://www.i18next.com/overview/typescript

**Comment by kirill-linnik** [comment]
> If you want to make the `t` function fully type-safe, follow the instructions here https://www.i18next.com/overview/typescript

As I see, I have exactly the same implementation, isn't? https://github.com/kirill-linnik/react-redux/blob/i18next-trouble/src/i18n.ts

**Comment by kirill-linnik** [comment]
> Hey @kirill-linnik, it seems message don't accept `null`, but t function could return `null`. I'd advice to fallback to something else. E.g.: `t('key') ?? ''`

this advice is similar to wrapping it to `<></>`, which means quite a work. can you, please, advice if it is possible `t` return `string` as it used to be in previos versions (in other words, if translation is not found, then key is returned)?

**Comment by badsyntax** [comment]
> If you want to make the `t` function fully type-safe, follow the instructions here https://www.i18next.com/overview/typescript

How can we use the custom types in `i18next.d.ts` to set the `t()` function to only return string? this is a pretty major breaking change and i really don't want to do `t('key') ?? ''` everywhere.

**Comment by pedrodurek** [comment]
Everyone who is facing the same issue, you need to type augment `i18next` in order to leverage `t` function fully type-safe, by doing that, you won't have this problem again. Please take a look at our examples: https://github.com/i18next/react-i18next/tree/master/example/react-typescript
For people who can't override the resources type because you can't get the translation files in build time, I'll create a PR to fix this later today.

**Comment by adrai** [comment]
should be fixed with i18next v22.0.5

**Comment by kirill-linnik** [comment]
just checkes with 22.0.5. unfortunately, still have:
`S2322: Type 'DefaultTFuncReturn' is not assignable to type 'string | ReactElement<any, string | JSXElementConstructor<any>> | undefined'`

**Comment by pedrodurek** [comment]
Hey @kirill-linnik,
`t` function **can** return `null`, this behaviour is set by default, if you want to change it, set `returnNull` type to `false`.
```tsx
// i18next.d.ts
import 'i18next';

declare module 'i18next' {
  interface CustomTypeOptions {
    returnNull: false;
  }
}
```
 I also recommend updating your i18next configuration to behave accordantly. https://www.i18next.com/overview/configuration-options#translation-defaults

**Comment by kirill-linnik** [comment]
> Hey @kirill-linnik, `t` function **can** return `null`, this behaviour is set by default, if you want to change it, set `returnNull` type to `false`.
> 
> ```tsx
> // i18next.d.ts
> import 'i18next';
> 
> declare module 'i18next' {
>   interface CustomTypeOptions {
>     returnNull: false;
>     ...
>   }
> }
> ```
> 
> I also recommend updating your i18next configuration to behave accordantly. https://www.i18next.com/overview/configuration-options#translation-defaults
> 
> ```tsx
> i18next.init({
>   returnNull: false,
>    ...
> });
> ```

first one helps, huge thanks!

now, can you, please, help me understanding why I need/want to specify `returnNull` value twice? if I use it only in `init` as you suggested in the second part, nothing works, I get tons of errors back. what is the purpose of having it then?

**Comment by pedrodurek** [comment]
Unfortunately, we can't infer the `react-i18next` types based on the arguments passed to the `i18next` `init` function. That's why we need the type declaration file. A lot of libs rely on the same approach (e.g.: https://styled-components.com/docs/api#create-a-declarations-file)
