### ISSUE TITLE
Inaccurate Trans unescape test label

### ISSUE THREAD

**Issue by wjramos** [i18next/react-i18next#1577]
https://github.com/i18next/react-i18next/blob/b93be8e860b9418b072142f1dd451196bd87ba76/test/trans.render.spec.js#L631-L645

The referenced test specifies that `&lt;` and `&gt;` should be unescaped to render as `<` and `>`, however the rendered result in the test has these characters still displayed as entities

**Comment by adrai** [comment]
don't know what you mean... this is corresponding html
