### ISSUE TITLE
`t` function missing from `WithTranslationProps`

### ISSUE THREAD

**Issue by tleunen** [i18next/react-i18next#1581]
## 🐛 Bug Report

`t` function missing from `WithTranslationProps`

https://github.com/i18next/react-i18next/blob/3c391a13067ea3f75c0dc102db3bcf318da8191a/index.d.ts#L135-L138

## To Reproduce

- Use the `withTranslation` HoC
- Make the custom component props be based on `WithTranslationProps`
- Notice missing `t` function

## Expected behavior

`t` function should be available

**Comment by pedrodurek** [comment]
Hey @tleunen use `WithTranslation` type instead
https://github.com/i18next/react-i18next/blob/master/index.d.ts#L126-L133

```tsx
type Props = WithTranslation<'ns1'>;
const Component = ({t}: Props) => {
}

return withTranslation('ns1')(Component)
```

**Comment by tleunen** [comment]
Gotcha. Thank you.
But if `WithTranslation` is the right type, it seems it's also missing `useSuspense` then?
Reading this part of the documentation, it looks like it should expose `useSuspense` after wrapping the component with `withTranslation()`

https://react.i18next.com/latest/withtranslation-hoc#not-using-suspense

**Comment by pedrodurek** [comment]
`useSuspense` is just the argument that you pass to the `HoC`, but we don't expose that to the wrapped component.
