### ISSUE TITLE
Errors on build (production) for languages that I do not support.

### ISSUE THREAD

**Issue by einazare** [i18next/react-i18next#1584]
## 🐛 Bug Report

Errors on build (production) for languages that I do not support.

## To Reproduce

I have used the following example to get started with react-i18next: https://github.com/i18next/react-i18next/tree/master/example/react

I changed the `en` and `de` languages to `ro-RO` and `en-GB`. I only need these two languages in my application.

While in development mode, everything is ok, but when I build my app and run it in production mode, I get errors for languages that I do not want, for example, `en`, `ro`, or `en-US`.

Example of errors:
```
request.js:44          GET http://localhost:3002/locales/ro/translation.json 404 (Not Found)

request.js:44          GET http://localhost:3002/locales/en/translation.json 404 (Not Found)

request.js:44          GET http://localhost:3002/locales/en-US/translation.json 404 (Not Found)
```

## Expected behavior

I only want my i18n to run for `ro-RO` and `en-GB`, in both production and development.

## Your Environment

- *runtime version*: node v16.16.0 LTS
- *i18next version*: 22.0.4
- *os*: Mac

```
    "i18next": "22.0.4",
    "i18next-browser-languagedetector": "7.0.1",
    "i18next-http-backend": "2.0.1",
    "react-scripts": "5.0.1",
    "serve": "14.0.1",
```

**Comment by adrai** [comment]
How does your i18next config look like?
if you know all supported languages just pass them like this:

```
i18next.init({
  supportedLngs: ['ro-RO', 'en-GB']
})
```

**Comment by einazare** [comment]
Hi @adrai 

My config looks like this:
```
import i18n from "i18next";
import Backend from "i18next-http-backend";
import LanguageDetector from "i18next-browser-languagedetector";
import { initReactI18next } from "react-i18next";

i18n
  // load translation using http -> see /public/locales
  // learn more: https://github.com/i18next/i18next-http-backend
  .use(Backend)
  // detect user language
  // learn more: https://github.com/i18next/i18next-browser-languageDetector
  .use(LanguageDetector)
  // pass the i18n instance to react-i18next.
  .use(initReactI18next)
  // init i18next
  // for all options read: https://www.i18next.com/overview/configuration-options
  .init({
    fallbackLng: "en-GB",
    debug: true,

    interpolation: {
      escapeValue: false, // not needed for react as it escapes by default
    },
  });

export default i18n;

```

Sorry, should have mentioned this from the start.

**Comment by einazare** [comment]
I'll give it a try with removing `fallbackLng: "en-GB",` and adding `supportedLngs: ['ro-RO', 'en-GB']`.

**Comment by einazare** [comment]
Seem this fixed the issue. Thank you, and sorry for the unnecessary issue.
