### ISSUE TITLE
TypeScript simple example doesn't translate stuff

### ISSUE THREAD

**Issue by kamikaze** [i18next/react-i18next#1585]
## Documentation issue

Hi. I was trying to follow the simple example: https://github.com/i18next/react-i18next/tree/master/example/react-typescript/simple

But my template project doesn't translate anything. t() returns the key, not the translation. My code is here:
https://github.com/kamikaze/react-project-template/tree/feature/i18n

## Motivation

It would be nice to have a fully working and explained example. Thanks

**Comment by adrai** [comment]
You missed to add the namespace:
<img width="313" alt="image" src="https://user-images.githubusercontent.com/1086194/203826791-e7f8afb2-18f2-4b5a-bef4-7fe2bd298ee5.png">

here: https://github.com/kamikaze/react-project-template/blob/feature/i18n/src/i18n/config.ts

**Comment by kamikaze** [comment]
Thanks @adrai , it worked! but there is no such thing in sample code as I can see...

**Comment by adrai** [comment]
for sure there is: https://github.com/i18next/react-i18next/blob/master/example/react-typescript/simple/src/i18n/config.ts#L7

**Comment by kamikaze** [comment]
Wow... so it works like a key as well... nice. Will have to learn TS better :) thanks again
