### ISSUE TITLE
Return type problem

### ISSUE THREAD

**Issue by mazenkhalil** [i18next/react-i18next#1587]
## 🐛 Bug Report

Upon updating to `v12.0.0` return type issue appears as follows:
![image](https://user-images.githubusercontent.com/21160900/204221870-84aaa9f4-6a64-4ae0-897d-1c547d8e822a.png)

As you can see, explicitly defining the return type to `string | undefined` shows an error. But defining the type as string alone doesn't show any error.

Compare that with explicitly defining the value as below, the behavior sounds weird to me.

![image](https://user-images.githubusercontent.com/21160900/204223360-04112991-b646-4420-821a-6f56e4aab1bd.png)

As you can see here, if the type is `string` or `string | undefined` and the value is null, the error appears (expected).
 
## Expected behavior

`string | undefined` return type should work without issues as it was before updating to v12.0.0.

## Your Environment

- *runtime version*: node v16
- *i18next version*: v12.0.0
- *os*: Mac

**Comment by adrai** [comment]
https://www.i18next.com/overview/typescript#argument-of-type-defaulttfuncreturn-is-not-assignable-to-parameter-of-type-xyz

**Comment by mazenkhalil** [comment]
@adrai That doesn't solve the issue. It still persists.

**Comment by mazenkhalil** [comment]
Sorry my bad. I had to restart the IDE to reload the configurations.

**Comment by eiskalteschatten** [comment]
I have been trying to solve this problem all day in my project, but when I follow the instructions linked above, I get these errors:

```
TS2305: Module '"i18next"' has no exported member 't'.
     1 | import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
   > 2 | import { t } from 'i18next';
```

```
TS2339: Property 'use' does not exist on type 'typeof import("/Users/alexseifert/other/typescript-fastify-react-boilerplate/packages/client/src/i18next")'.
      7 |
      8 | i18n
   >  9 |   .use(initReactI18next)
        |    ^^^
     10 |   .init({
     11 |     resources,
     12 |     defaultNS: 'common',
```

Apparently, I'm missing something since it seems to override all of i18next's typings rather than merge with them. Any ideas? For now, I'm going to have downgrade and keep i18next at a fixed version.

This is the `i18next.d.ts` within the project:
https://github.com/eiskalteschatten/typescript-fastify-react-boilerplate/blob/main/packages/client/src/i18next.d.ts

**Comment by millar** [comment]
Hey @eiskalteschatten,

I had the same issue and what worked for me was putting the override in my `i18n.ts` file like so:

```ts
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

declare module 'i18next' {
  interface CustomTypeOptions {
    returnNull: false;
  }
}

i18n
  .use(initReactI18next)
  .init({
    returnNull: false,
  });

export default i18n;
```

**Comment by eiskalteschatten** [comment]
Hey @millar,

Thanks for the example. That worked wonderfully for me!

**Comment by schaeferCode** [comment]
@millar,

Thank you for that example. Worked for me as well. The thing that bothers me now is I don't know _why_ that worked! Can anyone explain why that putting the override in the `i18n.ts` file fixed the issue when adding a `i18next.d.ts` file with the same content didn't?

**Comment by Wordllban** [comment]
@schaeferCode,

I'm not sure, but maybe it's because override from separate file isn't reading in proper order to apply it

**Comment by OZZlE** [comment]
> ```ts
> initReactI18next
> ```

I don't have any i18n.ts file? Using next.js ...

**Comment by adrai** [comment]
@OZZlE here an example: https://github.com/i18next/next-i18next/blob/master/examples/simple/%40types/i18next.d.ts

**Comment by OZZlE** [comment]
Why is this ticket closed, it's still an issue?

**Comment by marcus-sa** [comment]
I can't get it to work either ...

**Comment by adrai** [comment]
did you set returnNull: false ?

https://www.i18next.com/overview/typescript#argument-of-type-defaulttfuncreturn-is-not-assignable-to-parameter-of-type-xyz

**Comment by marcus-sa** [comment]
> did you set returnNull: false ?
> 
> [i18next.com/overview/typescript#argument-of-type-defaulttfuncreturn-is-not-assignable-to-parameter-of-type-xyz](https://www.i18next.com/overview/typescript#argument-of-type-defaulttfuncreturn-is-not-assignable-to-parameter-of-type-xyz)

Yeah, I've done it for both `react-i18next` and `i18next`.

**Comment by adrai** [comment]
please provide a minimal reproducible example repository

**Comment by adrai** [comment]
<img width="787" alt="image" src="https://github.com/i18next/react-i18next/assets/1086194/0d4f5fa3-dc76-4329-b5bd-786c456383ba">

**Comment by marcus-sa** [comment]
> 

As I've said, that doesn't fix it.
I worked around it by downgrading `i18next` and `react-i18next`.
I'd recommend better DX for this because it seems like **A LOT of** people are having difficulties with your new API.

**Comment by adrai** [comment]
@marcus-sa like said: please provide a minimal reproducible example so that can be investigated, like here: https://github.com/i18next/react-i18next/tree/master/example/react-typescript/simple

especially: https://github.com/i18next/react-i18next/blob/7c92aa0497fb45861d869665f3d8f91c058f689d/example/react-typescript/simple/src/%40types/i18next.d.ts#L8
and: https://github.com/i18next/react-i18next/blob/master/example/react-typescript/simple/src/i18n/config.ts#L17

beside that, @pedrodurek is currently working on a redesign: https://github.com/i18next/i18next/pull/1911
feel free to help and contribute

**Comment by audunolsen** [comment]
I've got another beast entirely. 

```
<img width="510" alt="Screenshot 2024-09-23 at 15 46 57" src="https://github.com/user-attachments/assets/aa94e264-7efd-4819-b7fb-b9435189f1a7">
```
