### ISSUE TITLE
Translation files as .ts instead of JSON

### ISSUE THREAD

**Issue by Lesik** [i18next/react-i18next#1590]
## Documentation issue

It's possible to import translations from a .ts file instead of a JSON file. I was wondering if there were any known downsides to this (something like build speed comes or IDE sluggishness to mind), and if not, whether we should mention this more prominently in the docs.

## Motivation

Having the translations in a .ts file would allow to give them a type to make sure that all translations from the default language (e.g. English) are present in the translated language as well (e.g. French):

```ts
import { en } from "./en";

export const fr: typeof en = {
  // if a translation that exists in the English translations is missing from this one, TS will complain
}
```

It is possible to do the typecheck in the file where you're combining all the languages to the `resources` field of `init()`, but then the error message if you're missing one will will be in the wrong file, and be less helpful.

**Comment by adrai** [comment]
imo, complaining if a translation does not exist in fr but exists in en is not in line with the fallback behaviour of i18next => https://www.i18next.com/principles/fallback

**Comment by erzaehlsalex** [comment]
@Lesik Did you come up with a solution for that?

**Comment by pedrodurek** [comment]
It should work the same way, independently whether you're importing from a JSON or TS file

**Comment by Lesik** [comment]
This issue was about documentation not mentioning that possibility, which I don't think has changed. Or is this a WONTFIX?
