### ISSUE TITLE
Intellisense doesn't work with TS by the docs

### ISSUE THREAD

**Issue by nikitawolfik** [i18next/react-i18next#1591]
## Documentation issue
"i18next": "^22.4.3",
"react-i18next": "^12.1.1",
"typescript": "^4.6.4",

related #1566

https://react.i18next.com/latest/typescript states that to extend TS you are supposed to
`declare module 'react-i18next'`, not `declare module 'i18next'`
but actually only the latter works.

## Motivation

Therefore, to actually enable intellisense and type-safe way to use `TFunction`, it is required to `declare module 'i18next'` instead of the way it is documented right now.

**Comment by adrai** [comment]
<img width="813" alt="image" src="https://user-images.githubusercontent.com/1086194/207373595-90947513-2f58-4b72-8481-3261ce8175c6.png">
