### ISSUE TITLE
App keep refreshing  when click on Change Language

### ISSUE THREAD

**Issue by naveenprakash74** [i18next/react-i18next#1592]
## 🐛 Bug Report

I am Using this module in my react native app to handle Arebic and English language. app is keep refreshing when user click on changeLanguage button. this issue will create on if my mobile default language is arebic. it works fine if mobile default language is English

## To Reproduce

change your device language to Arebic then open app and change app language to english then the app will keep refreshing user is not able to use the app.  

```js

i18n.changeLanguage(languageSelected === 'en-US' ? 'en' : 'ar');
.....

i18n
  .use(initReactI18next)
  .init({
    compatibilityJSON: 'v3',
    fallbackLng: 'ar',
    resources,
    // lng: 'en', //default language
    keySeparator: false,
    interpolation: {
      escapeValue: false,
    },
  });
```
dependency

"react-i18next": "^11.16.9",
 "i18next": "^21.8.0",

**Comment by adrai** [comment]
Not easy to help without seeing the rest of your code.

**Comment by abuzar-javed** [comment]
Facing the Same Issue in my React Native Application. 

@adrai  I have followed your article on Medium.
 
 
 ```
const handleLanguageChange = async (selected: number) => {
    const lang = selected === 0 ? 'en' : 'se';
    i18n.changeLanguage(lang);
  };
```

### Dependencies

 "react": "17.0.2",
"react-native": "0.68.5",
"react-i18next": "12.1.1",
"i18next": "22.4.6",

**Comment by adrai** [comment]
@abuzar-javed not able to reproduce it myself, please create a minimal reproducible example repo or codesandbox

**Comment by abuzar-javed** [comment]
### Issue Resolved

After a lot of Research I have found the clue from this [Thread](https://stackoverflow.com/questions/71035763/react-i18next-navigates-back-to-first-screen-in-navigation-on-changelanguage)

I am making a **Mistake** By using the **useTranslation** Hook inside my navigation component (Bottom Tabs).

When the language changed it resets the navigation component which results in App Refreshing.

@naveenprakash74 @adrai 

**What I am doing.**

<Tab.Screen name={t('home')} component={HomeView}/>

 **Solution**
 
<Tab.Screen name={'Home'} component={HomeView} options={{tabBarLabel: `${t('home')}`}}/>
