### ISSUE TITLE
TS2459: Module '"react-i18next"' declares 'TFunction' locally, but it is not exported. 

### ISSUE THREAD

**Issue by villesau** [i18next/react-i18next#1593]
## 🐛 Bug Report

When importing the TFunction, it has worked previously as it's been exported: `import { TFunction } from 'react-i18next';`

However, that's no longer the case so the above fails. I think return values of the hooks should be exported as those values might be passed all over to other functions etc.

## To Reproduce

`import { TFunction } from 'react-i18next';`

## Expected behavior

It should be exported in my opinion since the return value of the hook might be used in other functions. getting the return value via typescript using helpers is also a bit too cumbersome in most cases. In previous versions importing has worked.

## Your Environment

- *runtime version*: node v18
- *i18next version*: 22.4.5
- *os*: Mac
- *react-i18next version*: 12.1.1
- *Typescript version*: 4.9.3

E: Also `DefaultNamespace` is not exported anymore.

**Comment by adrai** [comment]
```diff
+import { TFunction } from 'i18next';
-import { TFunction } from 'react-i18next';
```
