### ISSUE TITLE
t not works when I pass it as prop...

### ISSUE THREAD

**Issue by shop-fluencer** [i18next/react-i18next#1596]
## 🐛 Bug Report

Hello,

I use useTranslation hook and pass the " t " function in my Memo Item but it does not translate. I get this console.log

```
LOG  T: function fixedT(a0, a1) { [bytecode] }
 LOG  T: function fixedT(a0, a1) { [bytecode] }
 LOG  T: function fixedT(a0, a1) { [bytecode] }
 LOG  T: function fixedT(a0, a1) { [bytecode] }
```

When I dont use memo and dont leave my code outside it works...

## To Reproduce

```
function isEqual(prev: IMyOrders, next: IMyOrders) {
  if(prev.name=== next.name) {
    return true;
  } else {
    return false;
  }
}

const Item = ({
  name,
  order_date,
  t
}: { name: string; t: any; }) => {
  return (
    <Pressable style={s.item}>
       <Text style={s.product_name}>Ordered Date: { t('profile.logged.reviews.created_at', { date: order_date }) }</Text>
    </Pressable>
    )
  };

const MEMO_ITEM = memo(Item, isEqual);

## MEMO END ##

const SettingsMyOrders = () => {
  const { t, i18n } = useTranslation();

  const renderItem: ListRenderItem<IMyOrders> = ({ item }) => (
    <MEMO_ITEM 
      {...item}
      t={t}
    />
  );

  return (
     <FlashList 
       data={data}
       keyExtractor={(item, i) => item.name.toString()}
       renderItem={renderItem}
       estimatedItemSize={280.7}
     />
  )
}
```

## Your Environment

 expo sdk 47
- *i18next version*: 12.0.0
 windows

**Comment by adrai** [comment]
Why should this work? You're not comparing the t prop in the isEqual function...
Try to change it like this:

```diff
function isEqual(prev: IMyOrders, next: IMyOrders) {
+  return prev.t === next.t;
-  if(prev.name=== next.name) {
-    return true;
-  } else {
-    return false;
-  }
}
```

**Comment by shop-fluencer** [comment]
> Why should this work? You're not comparing the t prop in the isEqual function... Try to change it like this:
> 
> ```diff
> function isEqual(prev: IMyOrders, next: IMyOrders) {
> +  return prev.t === next.t;
> -  if(prev.name=== next.name) {
> -    return true;
> -  } else {
> -    return false;
> -  }
> }
> ```

Not working

**Comment by adrai** [comment]
works for me: https://codesandbox.io/s/react-i18next-http-example-forked-1sdwe5?file=/src/app.js:811-835
please provide a minimal reproducible example
