### ISSUE TITLE
i18next-resources-to-backend with an initial resourses object.

### ISSUE THREAD

**Issue by Phoelpis** [i18next/react-i18next#1597]
Hello,
Is there a way to have an initial resources object (with minimal translations for every language) on init.
And just latter on, lazy load other resources using i18next-resources-to-backend (specific to lng)?

I managed to do the second part, but not sure how to not import on init, and just use the resources prop.

Thank you!

**Comment by adrai** [comment]
Should work with `partialBundledLanguages`: https://www.i18next.com/how-to/add-or-load-translations#combined-with-a-backend-plugin

**Comment by Phoelpis** [comment]
Thank you Adrai!

**Comment by Phoelpis** [comment]
Thank you Adrai. 
Also how can i trigger the lazy loading withing the initial component? 
I want to load the secondary en.json in the main component while the user sees the inline resources and not in the secondary component which is decorated with the withTranslation hoc?

**Comment by adrai** [comment]
I don't know exactly what you mean... you may want to provide a minimal example repository...

**Comment by Phoelpis** [comment]
firstComponent -> gets the translations from .init({ resourse: 
secondComponent -> gets them from .use(resourcesToBackend((language: any, namespace: any) => import(`./${namespace}/${language}.json`); when I add withTranslation('secondaryNs')(secondComponent );
Can trigger the lazyload import for the secondaryNs somehow from the firstComponent? So it loads in the backgrund before the user goes to the secondComponent.
Thank you fro your time Adrai, i appreciate your time and don't have to fallow up, as this is more of an implementation issue on my end.

**Comment by adrai** [comment]
still don't know exactly what you want to do, but maybe this helps: https://www.i18next.com/overview/api#loadnamespaces

**Comment by Phoelpis** [comment]
I wanted this:
  i18next
    .use(resourcesToBackend((language: any, namespace: any) => {
      import(`./${namespace}/${language}.json`)
        .then(({ default: resources}) => {
          i18next.addResourceBundle(language, "translations", resources);
        });
        
Should it work?

**Comment by adrai** [comment]
no, the resourcesToBackend return needs to be a promise with the resources

**Comment by Phoelpis** [comment]
It needs to, in order to add the resources to the new namespace. But in my case it worked as I do that via addResourceBundle. This way i was able to load also ts files not only json, by calling i18next.loadNamespaces('secondary') from anywhere down the line. Now I am not sure if this approach is perfect but it solved my issue. Thank you Adrai, beein reading all your related posts for the last two days.
