### ISSUE TITLE
Type errors when doing interpolation in react-typescript/simple

### ISSUE THREAD

**Issue by adr29truck** [i18next/react-i18next#1598]
## 🐛 Bug Report

Using the simple react-typescript example and introducing a variable to interpolate in the translation file causes `Type instantiation is excessively deep and possibly infinite.` or `'TFunctionDetailedResult<never>' is not assignable to type 'ReactI18NextChild | Iterable<ReactI18NextChild>'.
  Property '[Symbol.iterator]' is missing in type 'TFunctionDetailedResult<never>' but required in type 'Iterable<ReactI18NextChild>'` to be raised 

## To Reproduce

Using the simple react-typescript example in this repo, introduce a variable in the translation file 
```json
{
  "title": "Welcome to react using react-i18next fully type-safe",
  "description": {
    "part1": "This is a simple example. {{hello}}",
    "part2": "😉"
  }
}
```
then in `app.tsx` try accessing `description.part1` using the `t` function derived from `useTranslation`.
```tsx
<p>{t('description.part1', {hello: 'string'})}</p>
```
or 
```tsx
<p>{t('translation:description.part1', {hello: 'string'})}</p>
```
respectively.

See this commit https://github.com/adr29truck/react-i18next/commit/24a615a6bc1b56b133e06cefdf21662efc7e4d82  on fork

## Expected behavior
It should not raise type errors.

## Your Environment

- *runtime version*:  node v16.13.0, chrome
- *i18next version*: ^22.4.3
- *react-i18next version*: ^12.1.1
- *os*: Mac

**Comment by adrai** [comment]
Sorry, but I'm not able to reproduce it...
https://github.com/i18next/react-i18next/commit/98b118b2243fb583ff22f7621103f92b64219165#diff-ac4dc9bfd1bf289f94946a467ac5c76f365692d68cc9ca9258f7c6396a598f9e

**Comment by adr29truck** [comment]
@adrai Thanks for taking a look.

So when checking out the new commit, It raises an error in VSCode only. Typescript does not fail to compile.
If I however try using `translation:title` instead of `title` as the key then typescript fails to compile all together with the second error.  (see screenshot)
<img width="901" alt="Screenshot 2022-12-22 at 16 12 04" src="https://user-images.githubusercontent.com/9713439/209164336-0d65bfff-25a9-41f6-bd83-e04002d01aee.png">
 translation:title

If I then provide it a `deaultValue` the second error goes away and it now only raises `Type instantiation is excessively deep and possibly infinite.` but does not fail to compile.

**Comment by adr29truck** [comment]
> fyi: this works: <img alt="image" width="467" src="https://user-images.githubusercontent.com/1086194/209171338-97141521-e081-4478-aad6-b6e44af1f41b.png">

Yeah, that compiles, but it still raises the possibly infinite error
<img width="1386" alt="Screenshot 2022-12-22 at 16 51 00" src="https://user-images.githubusercontent.com/9713439/209172144-0830e171-76cb-4bce-97be-064bfc6974b1.png">

**Comment by marakim** [comment]
I am also seeing this problem on `"i18next": "^22.4.6"`

**Comment by marakim** [comment]
Any form of interpolation gives the "excessively deep" type error.

**Comment by marakim** [comment]
This is with `"react-i18next": "^12.1.1"`

**Comment by IuliiaBondarieva** [comment]
Same by mir. Is there any workaround for this error?

**Comment by pedrodurek** [comment]
Hey @adr29truck, I also didn't manage to reproduce it, and I'm using the latest vscode version. My assumption is that there is a conflict with one of your vscode extensions. Could you share your extension list, please?

**Comment by farmerpaul** [comment]
In my experience, this issue occurs both in VS Code, and when running `tsc` – @adrai's [suggested workaround](https://github.com/i18next/react-i18next/issues/1598#issuecomment-1362993938) doesn't work to solve the issue in either case.

However, the moment I downgraded `react-18n` from v12 to v11.18.6, it was solved, and that suits me fine for now.

**Comment by DumasOlivier** [comment]
Exactly the same error here ...
`"i18next": "^22.4.9"` `"react-i18next": "^12.1.4"`

**Comment by DumasOlivier** [comment]
Update, I managed to make it work using this code:
```typescript
// Type instantiation is excessively deep and possibly infinite.ts(2589)
<div>
  {t('myKey', {count: myCounter})}
</div>

// No error
<div>
  {Trans({t, i18nKey: 'myKey', count: myCounter})}
</div>
```

**Comment by cainlevy** [comment]
I solved this by updating to at least `typescript@4.7.2`.

**Comment by MiryksV** [comment]
We can confirm that bumping typescript v4.7.2 fix the issue of the TypeScript Error `Type instantiation is excessively deep and possibly infinite`. We could use more than 45 namespace/`.json` files.
We had this problem in our project using `typescript@4.6.3` by, after bumping, no more problem.

**Comment by MiryksV** [comment]
> > I solved this by updating to at least `typescript@4.7.2`.
> 
> Confirmed ! We could not use more than 45 namespace/`.json` files... We had this problem in our project using `typescript@4.6.3` by, after bumping, no more problem.

Well.. we still have problem ! We temporally fix the problem with the workaround 1 & 2 listed here : https://github.com/i18next/react-i18next/issues/1417#issuecomment-983951906. 
Like @adr29truck said, it compiles but it still raises the possibly infinite error warning...

**Comment by MiryksV** [comment]
@adrai do we have any news about this issue ? It still compiles but still raises the possibly infinite error warning...

**Comment by MiryksV** [comment]
Amazing, thanks a lot for the follow-up !

**Comment by adrai** [comment]
@MiryksV with the next major release this is fixed
