### ISSUE TITLE
Typescript slow compilation

### ISSUE THREAD

**Issue by Lav39** [i18next/react-i18next#1600]
## 🐛 Bug Report

In our project, we have 60430+ keys distributed across 77 namespaces and we have a good amount of deeply nested keys as well.
The Typescript compilation almost died on running the TS check.

## To Reproduce
1. Add 60430+ keys

2. Add a typing file

```js

import 'react-i18next';
// Resouce with 77 namespace and 60430+ keys
import type { TranslationResources } from '../translations/types';
declare module 'react-i18next' {
  interface CustomTypeOptions {
    defaultNS: 'common';
    resources: TranslationResources;
  }
}
```

## Your Environment
node - 12.19.1
npm - 6.14.8
typescript - 4.9.3
react-i18next - 11.18.0
i18next - 21.8.13

**Comment by pedrodurek** [comment]
Thank you for the feedback. I'm working in a new version that will likely improve the performance. I'll keep you posted.

**Comment by Lav39** [comment]
@pedrodurek Thank you. 
Do you have anything to suggest that we can do on our end to improve the performance? Right now, it's a blocker for us.

**Comment by pedrodurek** [comment]
For now, I'd suggest removing the `resources` type from `CustomTypeOptions`, it'll infer keys and return type as string, but it won't affect the compilation time.

**Comment by Lav39** [comment]
@pedrodurek we do need typescript for translation resources. Is there no other workaround?
