### ISSUE TITLE
useTranslation support key in namespace

### ISSUE THREAD

**Issue by Darhagonable** [i18next/react-i18next#1603]
## 🚀 Feature Proposal

Add support for using key in namespace when adding namespace as param in the useTranslation() hook:
`useTranslation('namespace:key-in-namespace')`

## Motivation

I'm working on a platform with multiple different sections. I have made each section have their own namespace and each file then containing groups.
In my components i wanna use both translations from a group in my namespace and `common` which is set as `fallbackNS`.
If I would use the `keyPrefix` option it won't work with the translations from `common`.

## Example

Let's say one has the two following namespaces:
common.json
```json
{
  "name": "Name",
  "version": "Version",
  "app-title": "My very good web app"
}
```

admin-pages.json
```json
{
  "users-admin-pages": {
    "first-name": "First name",
    "sir-name": "Sir name"
  },
  "devices-admin-pages": {
    "status": "Status"
  }
}
```

`common` is set as `fallbackNS`

Now I might have a React Componenet like this:
```jsx
export default function UserAdminPage({ user }) {
  const { t } = useTranslation('admin-pages:users-admin-pages')

  return (
    <>
      <h2>{t('app-title')}</h2>
      <p>{t('first-name')}: {user.firstName}</p>
      <p>{t('sir-name')}: {user.lastName}</p>
    </>
  )
}
```

**Comment by jamuhl** [comment]
If I see it right `keyPrefix` is already there for this and should work as expected:

https://github.com/i18next/i18next/blob/master/src/i18next.js#L396 -> keyPrefix gets prepended before searching for a valid value: https://github.com/i18next/i18next/blob/master/src/Translator.js#L440

**Comment by Darhagonable** [comment]
Well `keyPrefix` will result in it trying to find `users-admin-pages.app-title` which doesn't exist.
I wanna have the prefix only for the `admin-pages` namespace.

**Comment by jamuhl** [comment]
don't use prefix at all in that case and call `{t(['users-admin-pages.app-title', 'app-title'])}`

https://www.i18next.com/principles/fallback#key-fallback

**Comment by Darhagonable** [comment]
The goal is to make the code more dry and not have to write `users-admin-pages.` all the time like this:
```jsx
export default function UserAdminPage({ user }) {
  const { t } = useTranslation('admin-pages')

  return (
    <>
      <h2>{t('app-title')}</h2>
      <p>{t('users-admin-pages.first-name')}: {user.firstName}</p>
      <p>{t('users-admin-pages.sir-name')}: {user.lastName}</p>
    </>
  )
}
```

It's not a big problem for small components like this but in bigger components it becomes very repetitive so being able to set the prefix per namespace would make the code simpler and more readable.

**Comment by jamuhl** [comment]
I understand your goal...but not something we can solve inside i18next

you can use `useTranslation` twice in your component...once with prefix once without
