### ISSUE TITLE
`t` function doesn't work with `keyPrefix` and array of keys 

### ISSUE THREAD

**Issue by AlexKrupko** [i18next/react-i18next#1604]
## 🐛 Bug Report

`t` function doesn't work if `keyPrefix` is specified and array of keys provided. It fails with `missingKey` error. 
As far as I understood, this line of code is a reason of that error - [https://github.com/i18next/i18next/blob/5bd9ac037867edbb45fcdf9976e3b5ea48f164d5/src/i18next.js#L396](https://github.com/i18next/i18next/blob/5bd9ac037867edbb45fcdf9976e3b5ea48f164d5/src/i18next.js#L396)

```js
i18next.use(initReactI18next).init({
  // ... 
  resources: {
    en: {
      translation: {
        group: {
          key1: "Translation 1",
          key2: "Translation 2"
        }
      }
    }
  }
});

export default function App() {
  const { t } = useTranslation("translation", { keyPrefix: "group" });

  return t(["key1", "key2"]); // Doesn't work
}
```

## To Reproduce

A [codesandbox](https://codesandbox.io/s/mystifying-lake-0zi767?file=/src/App.tsx) example

## Expected behavior

Translation for `key1` value should be returned

**Comment by adrai** [comment]
v22.4.9 should address this

**Comment by adrai** [comment]
fyi: https://github.com/i18next/i18next/commit/dbe99407f0fa8a7517831273c394520bbf3d724a#diff-6859f2a371e0f563ec9c27c5cf64cb82f8d91750467509caaa8f6f0e6d06dec5
