### ISSUE TITLE
<Trans> component should be more robust regarding the formatting of text (e.g. "Prettier" extension auto format)

### ISSUE THREAD

**Issue by devnull69** [i18next/react-i18next#1605]
## 🚀 Feature Proposal

Currently it is necessary to know the JSX code for the <Trans> component very well before using it. So I started to put "everything inside the <Trans> component in one line" so that the translation.json file keeps being easy to edit.

But: It is quite common to use auto formatting tools like "Prettier" in IDEs. Unfortunately those tools tend to reformat these JSX code parts as soon as they become too complex. This will always break the <Trans> component.

So, I would be looking for a way to make <Trans> more robust with regards to the formatting of JSX in your editor

## Motivation

Keeping up with reformatted JSX for the <Trans> component is tedious and sometimes seems even impossible to do.

## Example

This works flawlessly

```
<Trans i18nKey="msg_new_user_register">
   New user - please <Link to="/register">register</Link>
</Trans>
```

with this in translation.json

```
  "msg_new_user_register": "New user - please <1>register</1>",
```

but, due to Prettier reformatting, this no longer works:

```
<Trans i18nKey="msg_new_user_register">
   New user - please{" "}
   <Link
      to="/register"
      state={
         location.state
         ? { from: { pathname: location.state.from.pathname } }
          : null
      }
   >
   register
   </Link>
</Trans>
```

**Comment by jamuhl** [comment]
You got any idea - how to solve your proposal?

Building the resulting string and replacements is dependent on the Trans element it's children array...not sure we should clean that from "unwanted" formatting from prettier?

alternative usage could be only solution I guess: https://react.i18next.com/latest/trans-component#alternative-usage-which-lists-the-components-v11.6.0

**Comment by devnull69** [comment]
Then what does this mean exactly (taken from the linked page)

```
Existing self-closing HTML tag names are reserved keys and won't work. Examples: link: <Link />, img: <img src="" />, media: <img src="" />
```

**Comment by jamuhl** [comment]
means you can't name your link "link"

`components={{ link: <Link /> }}` --> nok: "open <link>this</link>"

`components={{ goto: <Link /> }}` --> ok:  "open <goto>this</goto>"

**Comment by devnull69** [comment]
It did this ... and it does not really work. The translation is fine, but there is no link showing, just the plain text

```
          <Trans
            i18nKey="msg_new_user_register"
            defaults="New user - please <mylink>register</mylink>"
            components={{
              mylink: (
                <Link
                  to="/register"
                  state={
                    location.state
                      ? { from: { pathname: location.state.from.pathname } }
                      : null
                  }
                />
              ),
            }}
          />
```

**Comment by jamuhl** [comment]
Did you try:

```js
          <Trans
            i18nKey="msg_new_user_register"
            defaults="New user - please <mylink>register</mylink>"
            components={{
              mylink: (
                <Link
                  to="/register"
                  state={
                    location.state
                      ? { from: { pathname: location.state.from.pathname } }
                      : null
                  }
                />
              ),
            }}
          >just some dummy child string so the element has a children</Link>
```

**Comment by devnull69** [comment]
I just did ... to no avail. It's still "text only"

**Comment by jamuhl** [comment]
should work. https://github.com/i18next/react-i18next/blob/master/test/trans.render.object.spec.js#L56

do you still have the old string in JSON?

**Comment by devnull69** [comment]
I feel like I'm missing something obvious ...

This is the exact JSX code I'm currently using:

```
          <Trans
            i18nKey="msg_new_user_register"
            defaults="New user - please <mylink>register</mylink>"
            components={{
              mylink: (
                <Link
                  to="/register"
                  state={
                    location.state
                      ? { from: { pathname: location.state.from.pathname } }
                      : null
                  }
                >
                  DUMMY
                </Link>
              ),
            }}
          />
```

This is my translation.json

```
  "msg_new_user_register": "New user - please <1>register</1>",
```

And this is the result copied from dev tools:

```
"New user - please "
"register"
```

**Comment by adrai** [comment]
Replace:
`"msg_new_user_register": "New user - please <1>register</1>",`
with:
`"msg_new_user_register": "New user - please <mylink>register</mylink>",`

**Comment by devnull69** [comment]
This worked.

Is it mentioned this way in the docs? I cannot find it.

But THANK YOU anyway, this helped me a lot!

**Comment by adrai** [comment]
<img width="865" alt="image" src="https://user-images.githubusercontent.com/1086194/211494903-379d12c7-a8d2-4106-9e95-d316503e5e19.png">
https://react.i18next.com/latest/trans-component#alternative-usage-which-lists-the-components-v11.6.0
Can this issue be closed now?

**Comment by devnull69** [comment]
Yes, go ahead

Thanks again

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏

**Comment by whydidoo** [comment]
Recently I have written a [package](https://www.npmjs.com/package/eslint-plugin-react-i18next-prettier) for eslint(plugin). It adds a /* prettier-ignore*/ for all components <Trans>
