### ISSUE TITLE
ESLint "react/jsx-key" Error when using `<Trans />` with `components` props

### ISSUE THREAD

**Issue by cody-ta** [i18next/react-i18next#1607]
## 🐛 Bug Report

Still work in development. Console show error when run `npm run build`:

```console
Error: Missing "key" prop for element in array  react/jsx-key
```

Currently there's no way to pass `key` prop to JSX `<span />`

```tsx
<Trans
  i18nKey="hero_text"
  ns={["documents", "common"]}
  t={t}
  components={[ <span style={{ color: "purple" }} /> ]}
/>
```

```tsx
{
  "namespace_key1": "string 1",
  "namespace_key2": "string 2"
  "namespace_key": "...<0>$t(namespace_key1)</0>...<0>$t(namespace_key2)</0>..."
}

```

## To Reproduce

1. Clone this repo: https://github.com/codyslex1a/next-i18next-trans-component-bug.
2. `npm run build`

## Expected behavior

Package should build successfully without disabling ESLint rules.

## Your Environment

- *runtime version*: node v16
- *i18next version*: 22.4.9
- *react-i18next version*: 12.1.5
- *next-i18next version*: 13.1.4
- *next.js version*: 13.1.6 or any versions of next.js 13
- *os*: Mac, Windows, Linux

**Comment by jamuhl** [comment]
how should we solve that eslint issue in your opinion?

my guess it's a false positive on `[ <span style={{ color: "purple" }} /> ]` - so it's your code that breaks the rule - not ours ;)

eventual changing it to unneeded `[ <span key="makeEslintHappy" style={{ color: "purple" }} /> ]` already removes the eslint false positive

alternative use named components like: https://react.i18next.com/latest/trans-component#alternative-usage-which-lists-the-components-v11.6.0

**Comment by codyslex1a** [comment]
> how should we solve that eslint issue in your opinion?
> 
> my guess it's a false positive on `[ <span style={{ color: "purple" }} /> ]` - so it's your code that breaks the rule - not ours ;)
> 
> eventual changing it to unneeded `[ <span key="makeEslintHappy" style={{ color: "purple" }} /> ]` already removes the eslint false positive
> 
> alternative use named components like: [react.i18next.com/latest/trans-component#alternative-usage-which-lists-the-components-v11.6.0](https://react.i18next.com/latest/trans-component#alternative-usage-which-lists-the-components-v11.6.0)

I think it's better if it worked as passing `key={namespace_key.[iterator]}` under the hood. For example, `key={namespace_key.0}` if that's the first item of array.

**Comment by jamuhl** [comment]
how should that work? the rule breaks on your static code...not on what happens during runtime...we not even render that elements as array (that's why I said it's a false positive of eslint <- problem of eslint not react-i18next)

**Comment by codyslex1a** [comment]
![CleanShot 2023-02-03 at 19 37 49@2x](https://user-images.githubusercontent.com/8092790/216605527-d83a23c8-7a96-4b30-9757-41b5a26c488f.png)

Yes, it does fix on when `build`. But I don't think React should render 2 different elements with the same key, when using React DevTools & hover on the Element Tree, they highlighted multiple DOM nodes.

**Comment by jamuhl** [comment]
key is only relevant if node children is an array of same elements...

**Comment by codyslex1a** [comment]
@jamuhl Thank you for clarifying that.

Don't you think that providing API like a `render` prop to Trans component has better customization & DX?
I don't think ESLint won't complain for this pattern:
```jsx
<Trans ns={"common"}
	i18nkey={"translation_key"}
	components={(component) => <>{component}<>}
	/>
```

```jsx
<Trans ns={"common"}
	i18nkey={"translation_key"}
	components={{
		0: (component) => <>{component}<>,
		1: (component) => <>{component}<>,
		
		{// for named tags}
		link: (component) => <a href="#">{component}</a>
	}}
	/>
```

**Comment by jamuhl** [comment]
Not sure how that should be better DX?

You already have:

```js
<Trans ns={"common"}
	i18nkey={"translation_key"}
	components={{

		link: <a href="#"></a>
	}}
	/>
```

it automatically sets those components child (if string) or even children -> for component trees...

having a render prop would either just simple set the one child string to be interpolated or be a lot more difficult to handle a JSX tree of components.

But might I don't really see what use case is better handled with a render prop?
