### ISSUE TITLE
Move from v11.18 to v12 made TSC die.

### ISSUE THREAD

**Issue by Malien** [i18next/react-i18next#1608]
## 💥 Regression Report

We have an 800 lines long type definition of the translations (namespaces, keys and all). We also have a relatively-moderate usage of it, with around ~260 calls to the `useTranslation` hook, and around 500 calls to the `t` function throughout the project.

On the `react-i18n` version 11.18 (with standalone types that do not rely on `i18next` v22) compilation performance did exhibit a hit, but not a big one (we can live with that).

Same exact scenario, but on version 12. (with changes from `declare module "react-i18next"` to `declare module "i18next"`) makes the typescript compiler seemingly stuck, and after a long while, V8 ran out of memory.

Note: that we've just began our journey to typescriptify our use of i18n and the project itself surely, does have type errors that come from sudden introduction of type-safety.

## Last working version

Worked up to version: 11.18.6

Stopped working in version: 12.1.4

## To Reproduce

```ts
import { Translations } from "auto-generated-typescript-types"

declare module "i18next" {
  interface CustomTypeOptions {
    resources: Translations
  }
}
```

Unfortunately I cannot make a minimal reproduction case, as it seems to work fine on small projects, and wasn't able to troubleshoot the exact circumstances, which make it make TSC stuck. Maybe I can troubleshoot it further, but not today.

## Your Environment

This concerns build performance, so the environment is TSC in node.
- *runtime version*: node v18
- *i18next version*: 22.4.9
- *react-i18next version*: 12.1.4
- *os*: macOS 10.15
- *typescript*: 4.9.5

**Comment by adrai** [comment]
With the current TS approach there seems to be a performance implication... @pedrodurek is currently working on a different approach

**Comment by effektsvk** [comment]
I came across this issue as well, although it started happening after upgrading `typescript` from `4.9.5` to `5.0.2`. I have `react-i18next` on `12.2.0`. I even increased the heap size but it just crashed inside typescript with error `Map maximum size exceeded`.

**Comment by adrai** [comment]
Please try with i18next v23.0.1 and react-i18next v13.0.0

**Comment by Malien** [comment]
Okay, I've migrated our project to the newer version, and here are my findings:

### The good things
- `tsc` no longer runs out of memory, hurray!
- Calls to `i18n.t` are typed (not only `useTranslation` `t`s). _Helped us uncover a few bugs/key missmatches_
- `returnObjects` thingy is a godsend.
- I haven't explored possibility of typing interpolation parameters, but it does sound juicy. Not sure how `as const`-ing out translation type definitions will affect compilation speeds tho. 

### Not so great things
- `tsc --watch` still crashes v8, after the initial typecheck is complete (aka. after saving a file)
- Compilation times have risen from ~12s to ~82s.

### 😬 things 
- `tsserver` LSP performance is greatly degraded. It still behaves OK-ish most of the times, but the startup time and response latency has risen drastically. Auto imports take a couple of looong seconds, allowing me to change the file in meantime, and tsserver corrupting it as a result. 
- On occasion LSP process crashes, leaving my instance of neovim in limbo indefinitely.

There is a possibility that my helper type for extracting keys that return objects of matching shape is adding compilation overhead. It is used ~10-ish times throughout the project. Not sure.

```ts
import type { ParseKeys, TFunctionReturn, Namespace } from "i18next"

declare module "i18next" {
  interface CustomTypeOptions {
    resources: {
      ns1: {
        foo: {
          title: string
        },
        bar: {
          title: string,
          description: string
        },
        faz: string
     }
  }
}

// Yoinked from i18next type definitions
type AppendKeyPrefix<Key, KPrefix> = KPrefix extends string
  ? `${KPrefix}.${Key & string}`
  : Key;

type _TFuncShapedKey<
  Shape,
  N extends Namespace,
  Prefix,
  K = ParseKeys<N, { returnObjects: true }, Prefix>
> = K extends any
  ? TFunctionReturn<N, AppendKeyPrefix<K, Prefix>, {}> extends Shape
    ? K
    : never
  : never;

export type TFuncShapedKey<
  Shape,
  N extends Namespace,
  Prefix = undefined
> = _TFuncShapedKey<Shape, N, Prefix>;

type A = TFuncShapedKey<{ title: string }, "ns1">
//   ^? "foo" | "bar"
```

These are definitely nice changes. The performance is greatly improved since v22/v12 release, allowing the project to typecheck at all. But in the end I'm not sure we can stick to the newer release. 

There will be rounds of discussion among our team, deciding what matters: typesafety, LSP performance / `ts --watch` / compilation, or staying on the latest version.

![Untitled-2023-05-16-1710-3](https://github.com/i18next/react-i18next/assets/7205038/4b068676-3a55-44ec-b88a-f6ff529532ba)

- typesafety & perf: staying on v11 with `react-i18next` typings
- typesafety & latest release: v23/v13 with `i18next` typings
- perf & latest release: v23/v13 without types at all

_Or maybe we can get all 3 if I acquire a beefier development machine_

Thanks for your and @pedrodurek contributions ❤️

**Comment by pedrodurek** [comment]
Thank you for your feedback @Malien! Much appreciated!
I still have some ideas to improve the performance even more, I'll keep you posted!

**Comment by Malien** [comment]
Also, I forgot to mention the upgrade to TS v5.1. It may have played a role in perf improvements, since typescript team rewritten parts of it in v5. 
https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#speed-memory-and-package-size-optimizations

**Comment by hollandThomas** [comment]
Just to add to what @Malian summed up nicely: Our team just decided to go with the "typesafety & perf: staying on v11 with `react-i18next` typings" route for now. New versions introduce a _heavy_ performance penalty that totally crushes our productivity. Fingers crossed those will be sorted out sometime ✌️

**Comment by leonardopn** [comment]
My application has the same problem using the V11. I'm waiting a solution for upgrade my packages of i18

**Comment by adrai** [comment]
@leonardopn, @pedrodurek is looking for a good example project so he can better investigate...

**Comment by adrai** [comment]
Can you try if it's better with i18next v23.3.0?

**Comment by sedatbasar** [comment]
> Can you try if it's better with i18next v23.3.0?

Thank you @adrai it looks like performance issue is fixed with v23.3.0. It is still a bit slow but at least it doesnt cause tsc to die.

But i have another issue after upgrading to 23.3.0 with namespaces

assume that i have a function like 
```
getInventoryTranslations = (t: TFunction<'inventory'>) => 
  ({
    firstText: t('some_keys', { ns: 'inventory' })
  })
```

and assume that i call this in different react components
```
const CompontA = () => {
  const { t } = useTranslation(['common', 'inventory'])
  const inventoryTranslations = getInventory(t)
}
```
```
const CompontB = () => {
  const { t } = useTranslation(['dashboard', 'inventory'])
  const inventoryTranslations = getInventory(t)
}
```

This was working well previously but it started to return TS error saying `'common' is not assignable to 'inventory'` or `'dashboard' is not assignable to 'inventory'` so it is being hard to maintain this

**Comment by adrai** [comment]
@sedatbasar that's because of https://github.com/i18next/i18next/pull/1994 @jtbandes can you help?

**Comment by adrai** [comment]
@sedatbasar I would suggest you use 2 t functions... something like:

```ts
const CompontA = () => {
  const { t } = useTranslation('common')
  const { t: tInventory } = useTranslation('inventory')
  const inventoryTranslations = getInventory(tInventory)
}
const CompontB = () => {
  const { t } = useTranslation('dashboard')
  const { t: tInventory } = useTranslation('inventory')
  const inventoryTranslations = getInventory(tInventory)
}
```

**Comment by adrai** [comment]
@Malien did you try the new i18next v23.3.0?

**Comment by Malien** [comment]
I'm back with my new findings. Here they are:

### v23.3 Performance
Running on my somewhat noisy dev machine from-scratch typechecking times on typescript v5.1.3 have gone from ~76s. on v23.0 to ~32s. on v 23.3. Memory usage halved from ~1.8Gigs to ~900Megs. `tsc --watch` no longer runs out of memory on incremental recompilations. 🎉 👏 🥳

32s. is a LOT better than it used to be on v23.3, but still a far cry from `react-i18next` v11.8's ~12s. and ~450Megs.

Although I think this might be good enough for me to pull the lever and go forth with the newer version. It is saddening tho.

### v23.4 Issues
From what I can tell, you've moved all of the typescript stuff into `i18next/typescript/*`, sure, ok. It is not documented anywhere, but that's not my issue here.

v23.4 doesn't work for me at all! It promptly ignores `CustomTypeOptions` (which are now under `declare module "i18next/typescript/options"`), and `t` funcs just return `any`s. 

Also, it doesn't seem to catch type arguments to the `useTranslation` hook, aka: 
```ts
useTranslation("foo", { keyPrefix: "bar" })

// instead of generics being derived to literals like
useTranslation<"foo", "bar">("foo", { keyPrefix: "bar" })

// it is derived to base strings
useTranslation<string, string>("foo", { keyPrefix: "bar" })
```

I didn't bother creating a minimal reproduction case for now, might be something inherent to the project on-hand.

### Possible improvements? 🤔 
I wonder if the interpolation-parameter-deduction thingy influences compilation times in a significant way. The one that deduces `"string" | "interpolation"` from `ns1: { foo: "My translation {{string}} with {{interpolation}}" }`.

Such analysis could be done ahead-of-time. We already require running typegen out-of-tsc-process, since json type imports (`import type ns1 from "./ns1.json"`) erase concrete literal types. We might want to emit extra type declarations to avoid running `ParseInterpolationValues<Ret>` at tsc-compile-time when analyzing translation files. 

I bet we can write extraction logic in JS (and maybe even not in JS 🤔) a lot faster, than TS-es type-level-string-literal-parsing-magic _(it's basically a really slow, turing-complete, functional expression language interpreter at this point)_. As a bonus, it should be easier to express more complex formatting rules and interpolations (ie. deriving `"{{count, currency(USD)}}"` to be `{ count: number }`, and not `any`)

For now I don't provide literal values in my type-generation workflow, so I wonder if it has significant effect when running interpolation parameter inferring on `foo: string` and not `foo: "concrete literal"`. Presumably not.

### Miscellaneous
As for the relevancy of this issue. TSC no longer "dies" even under `--watch`. But I still think there should be an issue for tracking performance troubles, since even the current state of affairs is not satisfactory.

<br />
<br />
<br />
<br />

_P.S. I also found a typo on [the docs page](https://www.i18next.com/overview/typescript#slow-compilation-time) — "This should not ~~habben~~ happen anymore since v23.0.0"_

**Comment by adrai** [comment]
> P.S. I also found a typo on [the docs page](https://www.i18next.com/overview/typescript#slow-compilation-time) — "This should not ~habben~ happen anymore since v23.0.0"

should be fixed, thx => https://www.i18next.com/overview/typescript#slow-compilation-time

**Comment by adrai** [comment]
> I'm back with my new findings. Here they are:
> 
> ### v23.3 Performance
> Running on my somewhat noisy dev machine from-scratch typechecking times on typescript v5.1.3 have gone from ~76s. on v23.0 to ~32s. on v 23.3. Memory usage halved from ~1.8Gigs to ~900Megs. `tsc --watch` no longer runs out of memory on incremental recompilations. 🎉 👏 🥳
> 
> 32s. is a LOT better than it used to be on v23.3, but still a far cry from `react-i18next` v11.8's ~12s. and ~450Megs.
> 
> Although I think this might be good enough for me to pull the lever and go forth with the newer version. It is saddening tho.
> 
> ### v23.4 Issues
> From what I can tell, you've moved all of the typescript stuff into `i18next/typescript/*`, sure, ok. It is not documented anywhere, but that's not my issue here.
> 
> v23.4 doesn't work for me at all! It promptly ignores `CustomTypeOptions` (which are now under `declare module "i18next/typescript/options"`), and `t` funcs just return `any`s.
> 
> Also, it doesn't seem to catch type arguments to the `useTranslation` hook, aka:
> 
> ```ts
> useTranslation("foo", { keyPrefix: "bar" })
> 
> // instead of generics being derived to literals like
> useTranslation<"foo", "bar">("foo", { keyPrefix: "bar" })
> 
> // it is derived to base strings
> useTranslation<string, string>("foo", { keyPrefix: "bar" })
> ```
> 
> I didn't bother creating a minimal reproduction case for now, might be something inherent to the project on-hand.
> 
> ### Possible improvements? 🤔
> I wonder if the interpolation-parameter-deduction thingy influences compilation times in a significant way. The one that deduces `"string" | "interpolation"` from `ns1: { foo: "My translation {{string}} with {{interpolation}}" }`.
> 
> Such analysis could be done ahead-of-time. We already require running typegen out-of-tsc-process, since json type imports (`import type ns1 from "./ns1.json"`) erase concrete literal types. We might want to emit extra type declarations to avoid running `ParseInterpolationValues<Ret>` at tsc-compile-time when analyzing translation files.
> 
> I bet we can write extraction logic in JS (and maybe even not in JS 🤔) a lot faster, than TS-es type-level-string-literal-parsing-magic _(it's basically a really slow, turing-complete, functional expression language interpreter at this point)_. As a bonus, it should be easier to express more complex formatting rules and interpolations (ie. deriving `"{{count, currency(USD)}}"` to be `{ count: number }`, and not `any`)
> 
> _Maybe there are some other ahead-of-time low-hanging-fruit optimizations possible. Dunno_
> 
> For now I don't provide literal values in my type-generation workflow, so I wonder if it has significant effect when running interpolation parameter inferring on `foo: string` and not `foo: "concrete literal"`. Presumably not.
> 
> ### Miscellaneous
> As for the relevancy of this issue. TSC no longer "dies" even under `--watch`. But I still think there should be an issue for tracking performance troubles, since even the current state of affairs is not satisfactory.
> 
> 
> 
> 
> 
> _P.S. I also found a typo on [the docs page](https://www.i18next.com/overview/typescript#slow-compilation-time) — "This should not ~habben~ happen anymore since v23.0.0"_

@pedrodurek insights for you ;-)

**Comment by davidgoli** [comment]
Can repro with:

"typescript": "5.1.6"
"i18next": "^23.4.1"
"react-i18next": "^13.0.3"

**Comment by davidgoli** [comment]
For what it's worth, we have 87 individual namespaces loaded into a shared instance. Would this cause a problem?

**Comment by sedatbasar** [comment]
> > Can you try if it's better with i18next v23.3.0?
> 
> Thank you @adrai it looks like performance issue is fixed with v23.3.0. It is still a bit slow but at least it doesnt cause tsc to die.
> 
> But i have another issue after upgrading to 23.3.0 with namespaces
> 
> assume that i have a function like
> 
> ```
> getInventoryTranslations = (t: TFunction<'inventory'>) => 
>   ({
>     firstText: t('some_keys', { ns: 'inventory' })
>   })
> ```
> 
> and assume that i call this in different react components
> 
> ```
> const CompontA = () => {
>   const { t } = useTranslation(['common', 'inventory'])
>   const inventoryTranslations = getInventory(t)
> }
> ```
> 
> ```
> const CompontB = () => {
>   const { t } = useTranslation(['dashboard', 'inventory'])
>   const inventoryTranslations = getInventory(t)
> }
> ```
> 
> This was working well previously but it started to return TS error saying `'common' is not assignable to 'inventory'` or `'dashboard' is not assignable to 'inventory'` so it is being hard to maintain this

We added a couple of more namespaces and it started to die again

**Comment by davidgoli** [comment]
I suspect there's an upper bound on the number of supported namespaces and/or translation strings. We have quite a large Next.js production app, so it may be that we're hitting this limit. I (or someone) would need to put some work into a minimal repro app to determine exactly what that limit is.

**Comment by pedrodurek** [comment]
Unfortunately, typescript is slow, and depending on the size of the project, iterating over all translation objects to infer the keys and return type might be expensive. I do have some ideas to make it faster, but I'm not sure it'll fix everyone's issues. I'll keep you posted.

To improve the overall typescript compiler performance on big projects, I'd recommend using [Project References](https://www.typescriptlang.org/docs/handbook/project-references.html). You can also find other performance tips [here](https://github.com/microsoft/TypeScript/wiki/Performance).
