### ISSUE TITLE
react-i18next + ICU does not accept nested object as values for the translation string

### ISSUE THREAD

**Issue by artuska** [i18next/react-i18next#1610]
## Bug Report

If i use `i18next.use(ICU)` for my translations, i can no more pass a nested object as the data for my translation strings, i only can pass a single-level object. 

## To Reproduce

This does not work:

```yaml
dashboard_hdd:
  stats: {used.value} {used.type} used of {total.value} {total.type}
```

```js
const total = {
  value: '7.1',
  type: 'TB',
};

const used = {
  value: '6.6',
  type: 'TB',
};

<Trans
  i18nKey="dashboard_hdd.stats"
  values={{
    total,
    used,
  }}
/>
```

This is how i have to do now:

```yaml
dashboard_hdd:
  stats: {used_value} {used_type} used of {total_value} {total_type}
```

```js
const total = {
  value: '7.1',
  type: 'TB',
};

const used = {
  value: '6.6',
  type: 'TB',
};

<Trans
  i18nKey="dashboard_hdd.stats"
  values={{
    total_value: total.value,
    total_type: total.type,
    used_value: used.value,
    used_type: used.type,
  }}
/>
```

## Expected behavior

Well, i18next works well with data models -- https://www.i18next.com/translation-function/interpolation#working-with-data-models

```js
{
  "key": "I am {{author.name}}"
}

const author = { 
  name: 'Arthur',
  github: 'artuska'
};

i18next.t('key', { author });

// -> "I am Arthur"
```

## Your Environment

- "i18next": "22.4.9"
- "i18next-icu": "2.1.0"
- "react-i18next": "12.1.5"

**Comment by adrai** [comment]
Using i18next-icu will use the ICU i18n format only. There is no mix of i18next i18n format and ICU i18n format.
Here the proof ICU is not able to handle this: https://codesandbox.io/s/mystifying-voice-mhuoy2?file=/src/index.js
