### ISSUE TITLE
Empty `Trans` component not returning nothing when rendered with `@testing-library/react`

### ISSUE THREAD

**Issue by ivanbogdan-git** [i18next/react-i18next#1613]
## 🐛 Bug Report

Hi, this is my first time writing an issue so please forgive if I've misunderstood anything.
I'm using a `Trans` component with dynamically passed `i18nKey` and because of that I'm of no need to pass any children to the component.
Reason I need a`Trans` component instead of regular `t` is the usage of `<strong>` or `<i>`, so my component finally looks like this:
```
<Trans i18nKey={translationKey} values={{ component, components }} />
```
This previously wouldn't work, but it was fixed in issue https://github.com/i18next/react-i18next/issues/379. Well, the same error mentioned in the issue is logged within Jest when testing/rendering the component:
```
Uncaught Error: Trans(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
```

## To Reproduce

1. Create a simplest React app with only a trans component within.
2. Try rendering that component using `render` from `@testing-library/react`.

```js
const App = () => <Trans />

render(<App />)
```

## Expected behavior
Empty `Trans` component should work within Jest as it works on the local dev server.

## Your Environment

- *runtime version*: node v14
- *@testing-library/react*: 11.2.6,
- *i18next version*: 11.8.15
- *os*: Mac

**Comment by adrai** [comment]
If it works outside of the test, I suspect you're mock is probably not like you expect...
But the question is, what would you like to expect during the test?
If you want to fallback to the i18nKey if no children are passed, have a look at this: https://github.com/i18next/react-i18next/blob/7f76aa9a10ec53245504f9b6bdc44e68c33c0e75/example/test-jest/src/__mocks__/react-i18next.js#L40

**Comment by sKopheK** [comment]
it will fail if it cannot obtain `i18n` instance from `I18nContext` so you have to pass it via `i18n` prop
