### ISSUE TITLE
Make `<Trans />` suspend on missing resources

### ISSUE THREAD

**Issue by Malien** [i18next/react-i18next#1614]
## 🚀 Feature Proposal

It's a small one. I think it makes sense to make `<Trans />` component suspend when translation resources haven't loaded yet.

## Motivation

We cannot really suspend the rendering of the whole tree when there are translations absent. As such we had to write a silly one-liner

```jsx
function App() {
  return <div>
    <h1>
      <Suspense>
        <Title />
      </Suspense>
    </h1>
    <ImportantComponentToRender />
  </div>
}

function Title() {
  return useTranslation().t("key")
}
```

## Example

```jsx
function App() {
  return <div>
    <h1>
      <Suspense>
        <Trans i18nKey="key" />
      </Suspense>
    </h1>
    <ImportantComponentToRender />
  </div>
}
```

Also `<Trans />` doesn't trigger loading of namespaces by itself.

**It is not that big of a deal, and mostly a "nothing" change (which is also breaking). This can _somewhat_ easily be done by users themselves, by following the suspending logic of [`useTranslation`](https://github.com/i18next/react-i18next/blob/master/src/useTranslation.js). The use case is minimal and honestly absurd, but it makes sense for `<Trans />` to suspend in the same way `useTranslation` does for consistency sake, if we are embracing suspense-first APIs.**

I can follow-up with a PR if this change is worth it (I doubt it is tho)

**Comment by jamuhl** [comment]
I somewhat disagree.

`Trans` is a component and should not be loading and suspending rendering itself...that's the job for a hook, HOC or render prop

Simplest to do in user land:

```js

function SuspendingTrans({ ns, i18nKey, children }) {
  const { t } = useTranslation(ns);
  
  return <Trans t={t} i18nKey={i18nKey}>{children}</Trans>
}

```

**Comment by Malien** [comment]
Yeah, that seems kinda reasonable

**Comment by ryancwalsh** [comment]
I have a related question. 

I'm not trying to get Trans to use Suspense because of asynchronously loading _translation_ files, but I _do_ want to use Suspense because of asynchronously loading data that will get injected into the translations (e.g. the last 4 digits of a credit card number).

https://stackoverflow.com/questions/79055852/how-to-use-react-suspense-for-part-of-a-translation-such-as-with-trans-componen

**Comment by jamuhl** [comment]
Suspense is triggered by throwing a promise....not returning it
