### ISSUE TITLE
Does react-i18next support react server components?

### ISSUE THREAD

**Issue by remy90** [i18next/react-i18next#1616]
### Do you have a documentation issue?
Does react-i18next support react server components? I'm looking to include an i18n package in a nextjs 13 project utilising app directory with server components

### Do you have a technical/code issue?
No

#### You have already researched for similar issues?
Yes

## Motivation
The docs haven't made any reference to react server components, only that servers (like nodejs) are supported

**Comment by remy90** [comment]
Just spotted [this blog post](https://locize.com/blog/next-13-app-dir-i18n/). Not sure it's worth closing this, as it's still an issue with your documentation but the query behind the issue is satisfied

**Comment by adrai** [comment]
Yes there is TransWithoutContext etc...
but not yet officially documented beside that blog post.
