### ISSUE TITLE
Using context with Typescript doesn't seem to resolve types properly

### ISSUE THREAD

**Issue by litera** [i18next/react-i18next#1617]
## 🐛 Bug Report

I'm getting typescript error when I use context with my translations.

## To Reproduce

A [minimal reproducible example](https://stackblitz.com/edit/react-ts-vpwweq?file=App.tsx).
The interesting thing is that the code runs correctly (at least in the example Stackblitz). In the code there's a typescript error same as in my project.

## Expected behaviour

I've defined `i18next.d.ts` as instructed by the docs, initialized the i18next but I can't seem to make the context work as per documentation. Or at least the documentation is missing more information about Typescript usage.

## Your Environment

- *i18next version*: latest
- *react-i18next version*: latest
- *typescript version*: latest

**Comment by litera** [comment]
If I also add the `defaultValue` property, the error gets away. But adding the prop should not be mandatory when one uses context.

**Comment by adrai** [comment]
https://github.com/i18next/react-i18next/issues/1541

**Comment by adrai** [comment]
handled in i18next v23.4.0 (https://github.com/i18next/i18next/pull/2007/files#diff-97e65d0ee521805ff4ac2d967b61062da8f5543569da4177ceeff689ce4463a3)

**Comment by Jelle-vz** [comment]
Was this resolved actually? I still get the same error:

Code
`t('COMMON:DEVICES.STATUS', { context: hardwareInfo.devices.DOCUMENT_SCANNER ? 'ENABLED' : 'DISABLED' })`

throws:
`Argument of type '["COMMON:DEVICES.STATUS", { context: "ENABLED" | "DISABLED"; }]' is not assignable to parameter of type '[key: TemplateStringsArray | TemplateStringsArray[], options?: { readonly context: "ENABLED" | "DISABLED"; }] | [key: string | string[], options: { readonly context: "ENABLED" | "DISABLED"; } & $Dictionary & { ...; }] | [key: ...]'.
  Type '["COMMON:DEVICES.STATUS", { context: "ENABLED" | "DISABLED"; }]' is not assignable to type '[key: string | string[], defaultValue: string, options?: { readonly context: "ENABLED" | "DISABLED"; } & $Dictionary]'.
    Type at position 1 in source is not compatible with type at position 1 in target.
      Type '{ context: "ENABLED" | "DISABLED"; }' is not assignable to type 'string'.ts(2345)`

**Comment by adrai** [comment]
> Was this resolved actually? I still get the same error:
> 
> Code `t('COMMON:DEVICES.STATUS', { context: hardwareInfo.devices.DOCUMENT_SCANNER ? 'ENABLED' : 'DISABLED' })`
> 
> throws: `Argument of type '["COMMON:DEVICES.STATUS", { context: "ENABLED" | "DISABLED"; }]' is not assignable to parameter of type '[key: TemplateStringsArray | TemplateStringsArray[], options?: { readonly context: "ENABLED" | "DISABLED"; }] | [key: string | string[], options: { readonly context: "ENABLED" | "DISABLED"; } & $Dictionary & { ...; }] | [key: ...]'. Type '["COMMON:DEVICES.STATUS", { context: "ENABLED" | "DISABLED"; }]' is not assignable to type '[key: string | string[], defaultValue: string, options?: { readonly context: "ENABLED" | "DISABLED"; } & $Dictionary]'. Type at position 1 in source is not compatible with type at position 1 in target. Type '{ context: "ENABLED" | "DISABLED"; }' is not assignable to type 'string'.ts(2345)`
> 
> working with: `"i18next": "^23.10.0", "react-i18next": "^14.0.5",`

please provide a minimal reproducible example, not just code snippets... in case you can reproduce this, please open a new issue

**Comment by annsch** [comment]
I got the same error with i18next version "23.11.5"

**Comment by elr0berto** [comment]
Having this issue with 25.3.2
