### ISSUE TITLE
When using Custom Plugin to load translations, I don't have an option to choose nearest GCP-47 tag if the locale is not found.

### ISSUE THREAD

**Issue by ytambi** [i18next/react-i18next#1619]
I've implemented react-i18next in my project in a following manner. Here I've defined the locale files inside ./locale directory.

```
const LazyImportPlugin = {
  type: "backend",
  read: function (language, namespace, callback) {
    import(`./locale/${language}.json`)
      .then((obj) => {
        callback(null, obj);
      })
      .catch((err) => {
        // this is where I want to handle selecting the nearest GCP-47 tag.
        console.error(err.message);
        console.warn(`Language fallback to - ${i18n.languages[0]}`);
      });
  },
};

i18n
  .use(LazyImportPlugin)
  // pass the i18n instance to react-i18next.
  .use(initReactI18next)
  // init i18next
  // for all options read: https://www.i18next.com/overview/configuration-options
  .init(
    {
      fallbackLng: "en-US",
      () => {
        document.documentElement?.setAttribute("lang", i18n.language);
        // This will always gets call whenever language gets changed.
        i18n.on("languageChanged", function (lng) {
          document.documentElement?.setAttribute("lang", lng);
          import(`./locale/${i18n.language}.json`).then((obj) => {
            // set it to a variable.
          });
        });
      }
    );
```
I can't seem to find a way to select nearest GCP-47 locale in case the language I passed doesn't exist in my locale files. For example, if I pass "pt-BR" as key but I only have translations for "pt", I want "pt" locale to be selected.

## Expected behavior
When passing "pt-BR", "pt" language should be selected.

## Observed behaviour
I only see this error.
```js
Unknown variable dynamic import: ./locale/en.json
```
Code snippet based examples will be deeply appreciated. Also, just FYI, big fan of the library <3

**Comment by adrai** [comment]
Set the load option to languageOnly.
btw: why not using i18next-resources-to-backend? https://www.i18next.com/how-to/add-or-load-translations#lazy-load-in-memory-translations

**Comment by ytambi** [comment]
@adrai Still seeing the same error. The reason is in the locale files, I don't have `en.json` but `en-US.json`. Also, I want to keep `en-US.json` because we might add another translation file `en-GB.json` in future.

**Comment by adrai** [comment]
Then you need to customize the json loading... if en load en-US etc...

**Comment by ytambi** [comment]
Wouldn't we have to do that for every language which has a multiple sub-tags ?
Off the top of my head - `en-US, en-GB, zh-Cant, zh-Hans, sr-Latn, sr-Cyrl, etc.`

**Comment by adrai** [comment]
If you want to customize the loading, yes.
But honestly I would just use: i18next-resources-to-backend

**Comment by adrai** [comment]
btw: you may also define some fallbackLng mapping like here: https://github.com/i18next/i18next-resources-to-backend/blob/main/examples/simple/index.js

**Comment by ytambi** [comment]
@adrai  So here I'm facing issues with the naming conventions of locale files. I updated my i18n config to use `i18next-resources-to-backend` in following way - 
```
i18n
  .use(
    // eslint-disable-next-line no-unused-vars
    resourcesToBackend((language, translation) =>
      import(`./locale/${language}.json`)
    )
  )
  // pass the i18n instance to react-i18next.
  .use(initReactI18next)
  // init i18next
  // for all options read: https://www.i18next.com/overview/configuration-options
  .init(
    {
.........
});
```
I've two Serbian locale (`sr-Cyrl.json` and `sr-Latn.json`) files. Let's say if a user passes 'sr' language key, it's defaulting to English instead of the either two. How to intelligently pick up any one of the locale in such a case ?

**Comment by adrai** [comment]
I already told you: use fallbackLng -> https://www.i18next.com/principles/fallback#fallback-to-different-languages

**Comment by ytambi** [comment]
@adrai I got what you were saying, now. I was just passing a `fallbackLanguage: 'en'`. However, with above approach, I am now defining a fallback locale for each language and that works just fine. Thanks!
