### ISSUE TITLE
TS2322: Type 'DefaultTFuncReturn' is not assignable to type 'string | undefined'.

### ISSUE THREAD

**Issue by adnan-muhammadi** [i18next/react-i18next#1621]
<div aria-label={t('Example')}></div>
The above won't work because t returns DefaultTFuncReturn instead of string

Expected behavior
<div aria-label={t('Example')}></div>

TS2322: Type 'DefaultTFuncReturn' is not assignable to type 'string | undefined'.

**Comment by adrai** [comment]
https://www.i18next.com/overview/typescript#argument-of-type-defaulttfuncreturn-is-not-assignable-to-parameter-of-type-xyz

**Comment by adrai** [comment]
Please provide a minimal reproducible example

**Comment by marcus-sa** [comment]
> [i18next.com/overview/typescript#argument-of-type-defaulttfuncreturn-is-not-assignable-to-parameter-of-type-xyz](https://www.i18next.com/overview/typescript#argument-of-type-defaulttfuncreturn-is-not-assignable-to-parameter-of-type-xyz)

That doesn't fix the issue.

**Comment by adrai** [comment]
Please provide a minimal reproducible example...
And this may then fix the problem: https://github.com/i18next/i18next/pull/1911

**Comment by lb1129** [comment]
@adnan-muhammadi try t<string>('key') or  t<key>('key')
