### ISSUE TITLE
react-i18next shared to Module federation apps

### ISSUE THREAD

**Issue by el-j** [i18next/react-i18next#1622]
hi, i am struggling with a sharing problem. 
i have a module federation app (lerna  nx). with a structure like:
```
| -- library
| -- apps
       | --- containerApp (main menu + nav)
       | --- remoteApp (content in containerApp)
       | --- remoteApp2 (content in containerApp)
      ....
```
the i18n instance lives in the library and should work shared to the remoteApps. The ContainerApp has the language switch button. 

so now i tried to use i18nProviders in the remoteApp and the containerApp to pass the instance from the library.
all the translations get loaded, so this is nice, but a language change does only render and translate the containerApp, not 
the remoteApps....

i also tried this approach with no luck
#787
and using it as external always complains about missing `react` in `react-i18next`
#788
so no luck...

any idea how i can have this working?

the example provided for a library does not work for me, as my apps are not nested in each others folder structure like here:
https://github.com/i18next/react-i18next/tree/master/example/react-component-lib

currently i do a complete reload of the page on language change...but its very uncomfortable...

_Originally posted by @el-j in https://github.com/i18next/react-i18next/issues/788#issuecomment-1457975800_

**Comment by adrai** [comment]
Please provide a minimal reproducible repository.

**Comment by jamuhl** [comment]
my guess...you have two versions of react-i18next bundled...one with the container app one with the remote app -> make sure only one instance of react-i18next is bundled
