### ISSUE TITLE
Trans component: Existing self-closing HTML tag names has Link as example

### ISSUE THREAD

**Issue by eljo** [i18next/react-i18next#1623]
## Documentation issue
https://react.i18next.com/latest/trans-component has this warning:

> Existing self-closing HTML tag names are reserved keys and won't work. Examples: link: <Link />, img: <img src="" />, media: <img src="" />

Struggling to understand that <Link /> example. Unlike img, Link isn't a HTML tag name, it is a react component?

**Comment by jamuhl** [comment]
![image](https://user-images.githubusercontent.com/977772/225052290-25ebd14c-432a-46a4-a099-2398ee859308.png)

eg. for the `{ link: <Link />}` where link is a component....but it's not about the component it's about parsing html in your translation which for the link case looks like `some <link />` (where self-closing html elements won't work)

**Comment by jamuhl** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link self-closing html element (won't work as a naming for a replace with a react component)

**Comment by eljo** [comment]
Got it, thank you! Think it'd make sense to extend that bit in the documentation -- "Existing self-closing HTML tag names within translations are reserved keys and won't work" maybe?
