### ISSUE TITLE
Option to make <Trans /> update on language change events

### ISSUE THREAD

**Issue by uncaught** [i18next/react-i18next#1624]
## 🚀 Feature Proposal

Add a configuration option to make the `<Trans />` component update on language changed events.

Config path could be `react.updateTransComponent: boolean`.

## Motivation

I have read the [docs](https://react.i18next.com/latest/trans-component) and know that you have designed the Trans-component to be inert, although I don't know the reasoning behind this.

There are several situations where the Trans-component cannot be replaced with the `useTranslation` hook or HOC. For example translations with HTML or components inside or static definitions outside of components:

```js
// For a dropdown/select component:
const dropdownOptions = [{text: <Trans i18nKey={'foo'} />, value: 'foo'}];

// Column definitions for react-table:
const columns = [{Header: () => <Trans i18nKey={'table.header.bar'} />}];
```

Adding `useTranslation();` in every of our component just to trigger a re-render of the `<Trans />` inside is bad design if the hook was otherwise not used, and prone to error if this was forgotten or the code moved/split or even if a `react.memo` was used between the latest hook and the Trans-component.

## Example

```js
i18next.init({react: {updateTransComponent: true}});
```

**Comment by uncaught** [comment]
@adrai. I stated that it is not _possible_ to use the hook in several situations. And I've also stated that I have _read_ the docs. No point in simply repeating yourself.

What is your solution for those situations where the hook is not usable?

**Comment by adrai** [comment]
Why is a hook or HOC not always usable?

**Comment by adrai** [comment]
The Trans component is just like the t function... the t function will also not magically re-execute...

**Comment by adrai** [comment]
btw: you can always wrap the Trans component and do something like this:

```js
function MyTrans(props) {
  const { t, i18n } = useTranslation(props.ns);
  props.t = t;
  props.i18n = i18n;
  return Trans(props);
}
```

**Comment by uncaught** [comment]
The t-function will re-execute because the `useTranslation`-hook updates, which will trigger a re-render.

Hookes or HOCs are not possible if you give variables into other components, and those render the <Trans />. 

Examples

# 1. Static variables

```js
import {Dropdown} from 'your-favorite-ui-component-library';

const dropdownOptions = [{text: <Trans i18nKey={'foo'} />, value: 'foo'}];

function Header({options]) {
  return <div>{/*more code*/}<Dropdown options={dropdownOptions} />{/*more code*/}</div>;
}
```

# 2. HTML inside translations

A translation with `I am <b>bold</b>` will only work with `<Trans />`.

# 3. Components inside translations

A translation with `I <link>can be clicked</>` will only work with `<Trans />`.

-----

 All of these should not be forced to have the `useTranslation`-hook just there.

-----

And please could you give a reason, _why_  you wouldn't let `<Trans />` update? The framework is called _react_ after all, all components should react to changes.

**Comment by adrai** [comment]
> The t-function will re-execute because the `useTranslation`-hook updates, which will trigger a re-render.

Like you said, the t-function only re-executes, because of the `useTranslation`-hook. The same is for the `Trans` component.

Currently, the Trans component was designed to NOT be reactive, just like the t-function. For the original aspects of that decision, we might hear @jamuhl opinion.
But tldr; Trans is like t-function => t function needs useTranslation to re-execute, so also the Trans component.

**Comment by uncaught** [comment]
Well, pure functions are non-reactive by nature. However, hooks and components should be reactive by nature. I don't follow your argumentation. But if @jamuhl can shed some light on this, it would be great.

For now we are modifying your Trans with a package patch:

```
diff --git a/node_modules/react-i18next/dist/es/Trans.js b/node_modules/react-i18next/dist/es/Trans.js
index 25096d6..ea65566 100644
--- a/node_modules/react-i18next/dist/es/Trans.js
+++ b/node_modules/react-i18next/dist/es/Trans.js
@@ -9,6 +9,7 @@ function _objectSpread(target) { for (var i = 1; i < arguments.length; i++) { va
 import { useContext } from 'react';
 import { nodesToString, Trans as TransWithoutContext } from './TransWithoutContext.js';
 import { getI18n, I18nContext } from './context.js';
+import { useTranslation } from './useTranslation.js';
 export { nodesToString };
 export function Trans(_ref) {
   var children = _ref.children,
@@ -32,7 +33,8 @@ export function Trans(_ref) {
       defaultNSFromContext = _ref2.defaultNS;
 
   var i18n = i18nFromProps || i18nFromContext || getI18n();
-  var t = tFromProps || i18n && i18n.t.bind(i18n);
+  var {t: tFromHook} = useTranslation();
+  var t = tFromProps || tFromHook || i18n && i18n.t.bind(i18n);
   return TransWithoutContext(_objectSpread({
     children: children,
     count: count,
@@ -45,7 +47,7 @@ export function Trans(_ref) {
     components: components,
     ns: ns || t && t.ns || defaultNSFromContext || i18n && i18n.options && i18n.options.defaultNS,
     i18n: i18n,
-    t: tFromProps,
+    t: t,
     shouldUnescape: shouldUnescape
   }, additionalProps));
 }
\ No newline at end of file
```

**Comment by jamuhl** [comment]
easy gets down to this:

only thing useTranslation does -> react to changes and assert translations are loaded
only thing Trans does -> Interpolate react components into a given translation

If Trans should be reactive it would result in just changing the export of Trans to what @adrai already posted:

```js
function MyTrans(props) {
  const { t, i18n } = useTranslation(props.ns);
  props.t = t;
  props.i18n = i18n;
  return Trans(props);
}
```

**Comment by jamuhl** [comment]
As most cases do not need Trans to be reactive - the decision was made to not make it reactive - end of discussion ;)
