### ISSUE TITLE
TypeError: “t is not a function" when running the web application.

### ISSUE THREAD

**Issue by itSubeDibesh** [i18next/react-i18next#1625]
## 🐛 Bug Report

**TypeError**: `“t is not a function. (In 't()', 't' is undefined)` when running the web application.

**Background**

We have a web application following a mono-repo approach using **********Lerna********** `v3.22.1`, **react-i18next** `v11.7.4` with **************NextJs************** `v10.1.3` and have three different sub-projects(User, Admin, and Company) sharing resources and our `i18n` configuration. An `i18n.ts` file holds the following configuration and is used on other sub-projects.

```typescript
import i18n from "i18next";
import LanguageDetector from "i18next-browser-languagedetector";
import { initReactI18next } from "react-i18next";
// Translation files
import translationEN from "../locales/en/translation.json"; 
import translationJA from "../locales/ja/translation.json";

const resources = {
  en: {
    translation: translationEN,
  },
  ja: {
    translation: translationJA,
  },
};

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    whitelist: ["ja", "en"],
    load: "languageOnly",
    nonExplicitWhitelist: true,
    fallbackLng: "en",
    interpolation: {
      escapeValue: false,
    },
    keySeparator: false,
    nsSeparator: "|",
  });

export const language = i18n.languages[0];
export { i18n };
```
And we are using `useTranslation` hook to extract the `t` function and use it for translation and we also have imported the `i18n` in our `_app.tsx` file.  When we build our application and run it we get a console error message with the following signature.

**TypeError: `t is not a function. (In 't("Progress")', 't' is undefined)`** 

This issue is seen on the **User** sub-repository but has no side effects on the other projects.

## To Reproduce

This issue is seen in a variety of devices but mostly apple devices and our sentry server constantly gets flooded by this error. On our close inspection, this error occurs on build time only and is mostly reproducible when the cache is disabled in the browser. 

![Untitled](https://user-images.githubusercontent.com/65608497/225247654-ee167ab7-b77b-4500-b8db-03e260e61a8f.png)

## Expected behavior

The web application should run without any errors and the t function should be defined.

**What we tried:**

- Clear local `npm` cache and update packages version
    - [react-i18next](https://www.npmjs.com/package/react-i18next) → From **v11.7.3** to **v12.2.0**
    - [i18next-browser-languagedetector](https://www.npmjs.com/package/i18next-browser-languagedetector) → From **v6.0.1** to **v7.0.1**
    - [i18next](https://www.npmjs.com/package/i18next) → From ****v19.8.4**** to **v22.4.11**
- Tried implementing `i18next-http-backend` but our shared components also used `i18n` which created difficulties.
- Splitting translation files into multiple smaller files

## Your Environment

- Lerna **`v3.22.1`**
- NextJs **`v10.1.3`**
- Device: MacBook Air (Apple M1) running MacOS Ventura 13.2.1
- Browser: Safari Version 16.3
- react-i18next `v11.7.4`

**Comment by adrai** [comment]
Sorry, not able to reproduce it. :-(

**Comment by RwwL** [comment]
@itSubeDibesh Old/closed thread, I know, but.. did you ever find your own resolution to this? I'm clearing out some Sentry errors in our app and we have what sounds like the same thing going on. All of these errors have occurred in Safari 16.3 - 16.5.1 for us.

I don't think the `t` is necessarily anything to do with this package, though, might just be something local to that file that was minimized as `t`, but I really have no idea yet.

**Comment by itSubeDibesh** [comment]
Hey @RwwL,
After issuing the report we also did a deeper inspection, and we came to know that the issue was raised from `"web-vitals": "0.2.4"` package which is a dependency of `nextjs` `v10.2.0`. But we didn't further tried upgrading because of our other dependencies. If you found any solution that would mean a lot to me and my team as well 🙏.

**Comment by afurm** [comment]
Hello 👋 ! We have same error reporting on our sentry server. This is only reported for IOS devices.

**Comment by cchhno** [comment]
Hey @itSubeDibesh ,
We have the same problem. May I ask how to solve this problem?

**Comment by leomonzonspaceguru** [comment]
I am currently facing a similar error.
I solved it with **t?.(key)**

nextjs 12.3.4
next-i18next 15.2
react-i18next 14.0.5
