### ISSUE TITLE
What is type of useTranslation for using mockReturnValue in typescript

### ISSUE THREAD

**Issue by lazarus2019** [i18next/react-i18next#1626]
vi.mock("react-i18next", () => ({
  useTranslation: vi.fn(),
  initReactI18next: { type: "3rdParty", init: () => {} },
}));

const tSpy = vi.fn(str => str);

const useTranslationSpy = useTranslation;

  beforeEach(() => {
    vi.clearAllMocks();
    useTranslationSpy.mockReturnValue({
      t: tSpy,
      i18n: {
        changeLanguage: () => new Promise(() => {}),
        language: "en",
      },
    });
  });

![image](https://user-images.githubusercontent.com/62226062/225597645-485e682e-4f4d-470b-b103-f07dda96d2ec.png)
Property 'mockReturnValue' does not exist on type '<N extends Namespace<string> = "translation", TKPrefix extends KeyPrefix<N> = undefined>(ns?: N | Readonly<N> | undefined, options?: UseTranslationOptions<TKPrefix> | undefined) => UseTranslationResponse<...>'.

**Comment by adrai** [comment]
Sorry, I don't know what you mean?
did you check? https://react.i18next.com/misc/testing and https://github.com/i18next/react-i18next/tree/master/example/test-jest/src

**Comment by adrai** [comment]
Sorry, I'm not a TypeScript expert... https://github.com/i18next/react-i18next/blob/master/index.d.ts#L74
Maybe @pedrodurek may help?

**Comment by maxymapp** [comment]
@lazarus2019 it looks like you're using Vitest https://vitest.dev/api/mock.html#mockreturnvalue
according to the docs,
you should say what you're mocking like this:
`const useTranslation = vi.fn()`
I think the line giving the error sees that `useTranslationSpy` is just a func, so it can't access `mockReturnValue` on it.
Suggested solution:
```
const useTranslation = vi.fn()
useTranslation.mockReturnValue(...)
```
haven't checked myself, but just a hint :)
