### ISSUE TITLE
i18next::pluralResolver: Your environment seems not to be Intl API compatible, use an Intl.PluralRules polyfill. Will fallback to the compatibilityJSON v3 format handling.

### ISSUE THREAD

**Issue by chaitanyaparashar** [i18next/react-i18next#1628]
Getting error 
"i18next::pluralResolver: Your environment seems not to be Intl API compatible, use an Intl.PluralRules polyfill. Will fallback to the compatibilityJSON v3 format handling"
on the IOS simulator and physical device for Xcode 14.2

code: init code:

`const languageDetector = {
  type: 'languageDetector',
  async: true,
  detect: cb => cb('en'),
  init: () => {},
  cacheUserLanguage: () => {},
};

i18next
  .use(languageDetector)
  .use(initReactI18next)
  .init({
    compatibilityJSON: 'v3',
    fallbackLng: 'en',
    debug: true,
    resources: {
      en: en,
      hi: hi,
    },
  });
`

I tried initiating the multi-language support but got the above error.added compatibilityJSON: 'v3' in initialization but still the same.Tried installing intl-pluralrules and importing it in index.js still the same. App UI became unresponsive.

## To Reproduce

A [minimal reproducible example](https://minimum-reproduction.wtf/).
A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

```js
// Paste your code here
```

## Expected behavior

```js
// Paste the expected results here
```

## Your Environment

- *runtime version*: i.e. node v14, deno, browser xy
- *react-i18next: "^12.2.0",
- *i18next: "^12.2.0",
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by adrai** [comment]
You need to check how your Intl api gets polyfilled...
There's not much we can do.

**Comment by chunghn** [comment]
https://github.com/i18next/react-i18next/issues/1495#issuecomment-1113990587
