### ISSUE TITLE
Issue when using the react-i18next with Vite

### ISSUE THREAD

**Issue by trunghieu0207** [i18next/react-i18next#1630]
Hi everybody!
I am using the `react-i18next` with Vite, when running `vite build --watch --config ./vite.config.ts` I got an error. You can see my config below:

- React version: 18.2.0
- Vite version: 4.1.4
- react-i18next: 12.2.0

The `vite.config.ts` file:
```javascript
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import babel from 'rollup-plugin-babel';
import { nodePolyfills } from 'vite-plugin-node-polyfills';
import commonjs from '@rollup/plugin-commonjs';

export default defineConfig({
    plugins: [
        react(),
        nodePolyfills(),
        commonjs({
            include: /node_modules/
        }),
        babel({
            babelrc: true,
            exclude: 'node_modules/**'
        })
    ],
    build: {
        target: 'modules',
        commonjsOptions: {
            sourceMap: false
        },
        rollupOptions: {
            input: {
                'main': './Index.tsx'
            },
            output: {
                format: 'cjs',
                entryFileNames: '[name].js',
                dir: './public/dist'
            }
        }
    }
});
```

The ```Hello``` component file

```JSX
import { useTranslation } from 'react-i18next';
const { t } = useTranslation();

export const Hello = () => {
    return <h2>{t('Welcome to React')}</h2>;
};
```

The `Index.tsx` file
```JSX
import { Hello } from './Hello';
import { createRoot } from 'react-dom/client';
import React from 'react';

const element = document.getElementById('root');
const root = createRoot(element);
root.render(<Hello />);
```
When run the command ```vite build --watch --config ./vite.config.ts```, the error display as bellow
```terminal
"isValidElement" is not exported by "node_modules/react/index.js", imported by "node_modules/react-i18next/dist/es/TransWithoutContext.js".
file: /Users/path/to/project/node_modules/react-i18next/dist/es/TransWithoutContext.js:11:9
 9: function _objectSpread(target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i] != null ? arg...
10: 
11: import { isValidElement, cloneElement, createElement } from 'react';
             ^
12: import HTML from 'html-parse-stringify';
13: import { warn, warnOnce } from './utils.js';
```
I try to build the file without react-i18next but the error does not display and the build succeeds. I think react-i18next is not compatible with the Vite build.

Can you guys help me fix this error? 
Thank you very much! :open_hands: :open_hands:

**Comment by adrai** [comment]
Sorry, never used Vite myself.
Have you already tried to ask in the Vite community?
The other builders works without issues.

**Comment by trunghieu0207** [comment]
> 

I fixed it!
Thank you!!

**Comment by jamuhl** [comment]
@trunghieu0207 might help other users if you leave some comments here with your solution / changes

**Comment by brenopgarcia** [comment]
> > 
> 
> I fixed it! Thank you!!

How did you fixed?!

**Comment by timvlaer** [comment]
I had the exact same issue when migrating my react app from CRA to Vite. I only saw the issue when making a production build (`vite build`), not when just running `vite`.

I don't think this error is related to this project, but a result of an old vite plugin (in my case `rollupNodePolyFill`)

I'll document what I did for future reference: 

At first, I fixed this particular error by adding the [replace plugin](https://www.npmjs.com/package/@rollup/plugin-replace) to the vite plugin list:
```
replace({
   "process.env.NODE_ENV": '"development"',
   preventAssignment: true,
})
```
Which led me to the same error for another object which looked like a polyfill issue to me: `RollupError: "Buffer" is not exported by...`

Since I couldn't figure out the `Buffer` polyfill to work, I decided to remove `rollupNodePolyFill()` plugin to start with a clean slate and that fixed the issue for me. I also removed the `replace` plugin which is no longer necessary. So it looks like the rollupNodePolyFill was the culprit. 

My working vite config now looks like this:
```
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react-swc";
import viteTsconfigPaths from "vite-tsconfig-paths";

export default defineConfig({
  plugins: [viteTsconfigPaths(), react()],
  server: {
    port: 3000,
  },
  resolve: {
    alias: {
      stream: "stream-browserify",
    },
  },
  optimizeDeps: {
    esbuildOptions: {
      define: {
        global: "globalThis",
      },
    },
  },
});
```

**Comment by ajaffie** [comment]
Anyone else getting this issue? I tried setting up stream-browserify and globalThis like @timvlaer but it had no effect and I'm not including any polyfills.
The only other external configurations I have in my vite.config.js are esbuild-plugin-react-virtualized, vite-plugin-svgr, and the @achmadk/void-elements fork.

**Comment by daninus14** [comment]
> > 
> 
> I fixed it! Thank you!!

@trunghieu0207 how did you fix it??

**Comment by imp-dance** [comment]
> > 
> @trunghieu0207 
> I fixed it! Thank you!!
>
> ...closed this as [completed](https://github.com/i18next/react-i18next/issues?q=is%3Aissue%20state%3Aclosed%20archived%3Afalse%20reason%3Acompleted) [on Apr 11, 2023](https://github.com/i18next/react-i18next/issues/1630#event-8970092861)

Seeing this reply with no follow up two years later after spending hours on the same problem is making me lose my sanity slightly.

---

Edit: For anyone encountering this problem, try doing the following:

* Add `react-i18next` to `optimizeDeps.include` in your vite config
* Add `/react-i18next/, /node_modules/` to `build.commonjsOptions.include` in your vite config
* `rm -rf node_modules/.vite`
* Try to build the app

This atleast did it for me, might be you're in the exact same scenario.

**Comment by bean2307** [comment]
In my case, the issue was caused by this in `vite.config.js`: 
```
requireTransform({
  fileRegex: /.js$|.jsx$|.ts$|.tsx$/,
})
```

I changed it to:
```
requireTransform({
  fileRegex: /src\/.*\.(js|jsx|ts|tsx)$/,
})
```
and I hope this helps.
