### ISSUE TITLE
react-i18next module works well on my local, but has an error on Digital Ocean App platform

### ISSUE THREAD

**Issue by healer-1205** [i18next/react-i18next#1631]
## My Environment

- *runtime version: node v16.13.1, react v17.0.2
- *i18next version: 22.1.5
- *os: Windows
- *any other relevant information*

### index.js file
![image](https://user-images.githubusercontent.com/91068182/233104124-7cb254c2-aa8e-4077-880c-95c0d27c896b.png)

### change language component
![image](https://user-images.githubusercontent.com/91068182/233104324-9c673a2b-1f9e-49cb-a2e7-2b09d86b1143.png)

Current i18next module works well on my local but doesn't work on deployed project.
* It worked well few days ago. 
Please let me know the reason.

**Comment by adrai** [comment]
Sorry, not able to help without a reproducible example.
I suspect your production build is somehow different.
Check the production build and try to run that one locally.

**Comment by healer-1205** [comment]
I've checked but there is no differences between local and deployed project.
