### ISSUE TITLE
Only TypeScript Error: Unable to Specify Non-Default Namespace in t Function

### ISSUE THREAD

**Issue by gmaxlev** [i18next/react-i18next#1632]
## 🐛 Bug Report

I have come across a situation where I need to use translations from many namespaces. I use the `useTranslation` hook and the syntax `namespace:key`. This works well with JavaScript, but TypeScript produces an error if I have namespaces with the default namespace. It seems that TypeScript has an incorrect type in the argument of useTranslation because JavaScript handles it correctly and **I only receive errors during type checking**.

## To Reproduce

1. Configure i18next with react-i18next
2. **Use it with the default namespace**
3. Use TypeScript declaration (from [docs](https://www.i18next.com/overview/typescript))
```ts
declare module 'i18next' {
  interface CustomTypeOptions {
    defaultNS: 'common';
    resources: {
      one: {
        a: "Apple"
      },
      two: {
        b: "Orange"
      },
      common: {
        c: "Banana"
      }
    };
  }
}
```

4. Use `useTranslation` hook **without a namespace**

```ts
const { t } = useTranslation();
```

5. Try to use `t` **with namespaces**

```ts
t("one:a") // ❌ TS error
```
```ts
t("two:b") // ❌ TS error
```
```ts
t("common:c") // ❌ TS error
```
It only works with the keys of the default namespace, but this is not what I need.
```ts
t("c") // ✅ 
```

⚠️ It works correctly if the default namespace is not specified.
⚠️ It works correctly in JavaScript.

## Expected behavior

The same behaviour in JavaScript and TypeScript. Allow to specify any namespace in `t` function in TypeScript.

```ts
t("one:a") // Returns "Apple"
```
```ts
t("two:b") // Returns "Orange"
```
```ts
t("common:c") // Returns "Banana"
```
```ts
t("c") // Returns "Banana"
```

## Your Environment

- *runtime version*: 12.2.0
- *i18next version*: 22.4.15
- *os*: Mac

**Comment by adrai** [comment]
Pass the the namespace via `useTranslation('ns')` or `useTranslation(['ns1', 'ns2'])`

**Comment by gmaxlev** [comment]
@adrai thank you, I didn't know about that solution, but it works! However, in pure JS, it is possible to not specify anything in useTranslation. In addition, now we are forced to control the used namespaces. If this difference is not too critical, then we can close this issue.
