### ISSUE TITLE
useTranslation - override language

### ISSUE THREAD

**Issue by joekur** [i18next/react-i18next#1637]
## 🚀 Feature Proposal

Allow `useTranslation` to take an optional `lng` prop to override the language passed to `getFixedT` ([link](https://github.com/i18next/react-i18next/blob/dbe2d0e1b6cea2e552bf7e79160ea4274c40c6a3/src/useTranslation.js#L61)).

## Motivation

In a server-side rendering (SSR) environment, there is no single language, since a single server could handle different requests in different languages. This requires you to manage multiple `i18n` instances, one per language, in order for a `useTranslation` somewhere down the react tree to work. While something like next-i18next may handle this for you, we have use-cases for shared component libraries that may execute in both SSR and client-side environments, which requires to hand-roll some code for synchronizing language between app and library, and initializing an `i18n` instance (or multiple) for the component library to use (with its own translation files).

To correctly support SSR in the component library, this seems to require creating an `i18n` instance per supported language, and initializing each of them with the translation files, so that the correct one for the given request's language can be passed down via context. However if we could instead just pass down, say, the current language via context, we could have just a single `i18n` instance, and we could wrap `useTranslation` in a hook that passes that language to it.

## Example

Simple example:

```js
const { t } = useTranslation('ns1', { lng: 'es' });
```

How this might be used in a component lib (let's keep it simple and say our component takes a `lng` prop itself):

```js
const i18n = i18next.createInstance(...);

const MySharedComponent = ({ lng }) => {
  cons { t } = useTranslation('ns1', { i18n, lng });
  return t('foo');
};
```

**Comment by joekur** [comment]
I had actually thought about that - my uncertainty was around if that `t` would inherit the other properties that are being passed to the `getFixedT` inside `useTranslation` - namely the `namespaces` and `keyPrefix` as shown in your code screenshot?

**Comment by joekur** [comment]
And yeah as far as we're currently concerned, we would load translation files upfront - we wouldn't be using any other special backends for these component libraries.

**Comment by jamuhl** [comment]
not a fan of that change...might work for this scenario...but all others (using this not serverside with backends) will complain:

```js
cons { t } = useTranslation('ns1', { lng });

// -> i get missings....why useTranslation does not assert lng get loaded?!?
```

**Comment by adrai** [comment]
There is no guarantee resolvedLanguage is always defined, but can you please provide a minimal reproducible example showing resolvedLanguage to be undefined? Just tested in a normal client side environment, and at least there it seems to be defined.

**Comment by adrai** [comment]
Or do you mean this? https://github.com/i18next/i18next/pull/1960
