### ISSUE TITLE
Global context

### ISSUE THREAD

**Issue by thewizarodofoz** [i18next/react-i18next#1638]
## 🚀 Feature Proposal
Pass `context` once to `useTranslation` and it will be passed to all calls of `t('...')`.

## Motivation

We are customizing our app for a certain "vertical" which will affect quite a lot of texts.
Instead of passing `context` to every call of `t(...)` we would like to be able to pass it once somewhere up in the app tree or at least once for every component, and then everywhere we use `t` it will be pre-populated with the `context`.

## Example
in component:
```tsx
const { t } = useTranslation(NAMESPACES.CONTACTS, {
  keyPrefix: 'contact_view',
  context: user.vertical
});

<div>{t('title')}</div>
<div>{t('description')}</div>
<div>{t('warning')}</div>
```

in dictionary:
```js
{
contact_view: {
  title: 'welcome to your home',
  title_consultants: 'this is your consultancy home'
}
}
```

**Comment by adrai** [comment]
To achieve this we would not only need to change react-i18next but also i18next (getFixedT function)...
I've personally never seen the context functionality been used in a way like you describe (verticals)...
I would probably use a dedicated vertical namespace with fallback to the main namespace: https://www.i18next.com/principles/fallback#namespace-fallback

**Comment by anion155** [comment]
> but also i18next (getFixedT function)...
Nope. At least implementation would support it

https://github.com/i18next/i18next/blob/803db78f6758a900a0c087f2d90b6263ba467f0d/src/i18next.js#L377
```
getFixedT(lng, ns, keyPrefix) {
    const fixedT = (key, opts, ...rest) => {
      let options;
      if (typeof opts !== 'object') {
      } else {
        options = { ...opts };
      }
      return this.t(resultKey, options);
```

**Comment by anion155** [comment]
For me it's case like this. 

```ts
function FileInput({ type }: { type: 'mixed' | 'document' | 'photo' | 'video' }) {
  const [t] = useTranslation(undefined, {
    keyPrefix: 'components.FileInput',
  });
  t('openButton', {context: type})
  t('opened', {context: type})
  t('detailsName', {context: type})
  ...
```

with translations like this

```
      "openButton": "Click to open your media file",
      "openButton_photo": "Click to open your photo",
      "openButton_video": "Click to open your video",
      "openButton_document": "Click to open your individual file",
```
