### ISSUE TITLE
Typescript documentation is incorrect

### ISSUE THREAD

**Issue by jkepps** [i18next/react-i18next#1639]
## Documentation issue

The instructions for typescript setup are incorrect. In the docs it says the declaration file should extend `react-i18next` but the type definitions only come through if `i18next` is extended. This means the name of the file should be `i18next.d.ts` and the import statement and module declaration statement should be for `i18next` not `react-i18next`. 

## Motivation

More accurate documentation.

**Comment by adrai** [comment]
<img width="869" alt="image" src="https://github.com/i18next/react-i18next/assets/1086194/1d8bdc05-b11e-4f8e-a33d-c1ad19aca77c">

https://react.i18next.com/latest/typescript

So just follow this: https://www.i18next.com/overview/typescript

**Comment by jkepps** [comment]
not sure how i missed that, thanks!
