### ISSUE TITLE
Usage of i18n instance outside of react component does not work in React and React Native.

### ISSUE THREAD

**Issue by jkepps** [i18next/react-i18next#1640]
## 🐛 Bug Report

The documentation says the following:

> If you need to access the t function or the i18next instance from outside of a React component you can simply import your ./i18n.js and use the exported i18next instance:
>```
>import i18next from './i18n'
>
>i18next.t('my.key')
>```

This yields the following typescript error "Property 't' does not exist on type 'Promise<TFunction<"common", undefined, "common">>'.". This makes sense considering the init function returns a promise, however if I try to await the promise before exporting, I get the following error and the metro dev server crashes:

```[Error: Exception in HostFunction: Compiling JS failed: 12:24:';' expected Buffer size 2335 starts with: 5f5f642866756e6374696f6e2028676c]```

It should also be noted that, according to my typescript compiler, the resolved value is the translator function itself, not the i18n instance. In other words, the resolved value appears to be the `i18next.t()` function and not the full `i18next` object.

## To Reproduce

https://codesandbox.io/s/musing-pine-hicxb3?file=/src/App.tsx

## Expected behavior

I should be able to use the i18n instance outside of a react component as stated in the docs.

## Your Environment

- *runtime version*: React/React Native
- *react-i18next version*: 12.3.1
- *i18next version*: 22.5.0
- *os*: Mac

**Comment by adrai** [comment]
you export is wrong: https://codesandbox.io/s/epic-cdn-2o02by

<img width="525" alt="image" src="https://github.com/i18next/react-i18next/assets/1086194/10b32bd6-cf87-4aa4-a7bd-893eea20849d">

**Comment by adarshaacharya** [comment]
@adrai @jkepps what was the original mistake can't see any difference in codesandbox , for me its not working (using next js)

**Comment by devqazi** [comment]
@adarshaacharya In case you are still wondering what the issue is. You need to reexport the imported i18n instead of assigning the .use calls to a new variable.

**Incorrect**

```
import i18next from "i18next";
const myInstance = i18next.use(/* blah blah */);
export default myInstance
```

**Correct** 

```
import i18next from "i18next";
const myInstance = i18next.use(/* blah blah */);
export default i18next; // Notice I am re-exporting the top import
```

**Comment by adrai** [comment]
> @adarshaacharya In case you are still wondering what the issue is. You need to reexport the imported i18n instead of assigning the .use calls to a new variable.
> 
> **Incorrect**
> 
> ```
> import i18next from "i18next";
> const myInstance = i18next.use(/* blah blah */);
> export default myInstance
> ```
> 
> **Correct** 
> 
> ```
> import i18next from "i18next";
> const myInstance = i18next.use(/* blah blah */);
> export default i18next; // Notice I am re-exporting the top import
> ```
> 
> 
> 
> 

Yes, and you may also have a look at this: https://www.locize.com/blog/how-to-use-i18next-t-outside-react-components
