### ISSUE TITLE
Typescript freezes and eventually runs out of memory when using typescript 5.0.1

### ISSUE THREAD

**Issue by wolthers** [i18next/react-i18next#1641]
## 🐛 Bug Report

When importing anything from react-i18next, typescript hangs and eventually runs out of memory.

Works as expected in 4.9.5 (last version before 5).

Also reproduces with 5.0.2 and 5.0.3 and 5.0.4

## To Reproduce

**Important:** The issue doesn't reproduce on the link because `npm run build` isn't actually invoked on codesandbox. 
1. Instead, to reproduce, download the codesandbox as zip. 
<img width="407" alt="image" src="https://github.com/i18next/react-i18next/assets/841834/02263676-60fc-4933-9ae3-cd9fee3f27e7">

2. Unzip and cd into the folder
3. Run `npm i`
4. Run `npm run build`
5. Observe that node eventually runs out of memory:

```
Wolle@Wolles-MacBook-Pro lol % npm run build

> lol@1.0.0 build
> tsc --build

<--- Last few GCs --->

[3075:0x7fb220040000]   300982 ms: Mark-sweep 4060.4 (4130.0) -> 4045.2 (4130.7) MB, 2313.9 / 0.0 ms  (average mu = 0.137, current mu = 0.016) allocation failure; scavenge might not succeed
[3075:0x7fb220040000]   303389 ms: Mark-sweep 4061.1 (4130.7) -> 4046.0 (4131.5) MB, 2366.0 / 0.0 ms  (average mu = 0.080, current mu = 0.017) allocation failure; scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10c659fa5 node::Abort() [/usr/local/bin/node]
 2: 0x10c65a195 node::OOMErrorHandler(char const*, bool) [/usr/local/bin/node]
 3: 0x10c7dc81c v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0x10c9a10b5 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 5: 0x10c9a569a v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/usr/local/bin/node]
 6: 0x10c9a1da8 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::internal::GarbageCollectionReason, char const*, v8::GCCallbackFlags) [/usr/local/bin/node]
 7: 0x10c99edd0 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
 8: 0x10c9917ca v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
 9: 0x10c992165 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
10: 0x10c974a2e v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/local/bin/node]
11: 0x10cd9e856 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
12: 0x10d18cb79 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/usr/local/bin/node]
```

6. Comment out the import from react-i18next in src/index.ts
7. Run `npm run build` again
8. Observe that the project now builds as expected

## Expected behavior

Expected tsc to exit after compilation succeeded

## Your Environment

- *runtime version*: node v18.16.0 (also reproduced on node 16.19.0)
- *i18next version*: 12.3.1
- *os*: Intel mac (also reproduced on M2 apple silicon mac)
- *any other relevant information*

**Comment by adrai** [comment]
Will be addressed with https://github.com/i18next/i18next/pull/1911 by @pedrodurek

**Comment by DemonZito** [comment]
Downgraded to Typescript to 4.9.5 in the meantime but problem persists? Do I also need to downgrade react-i18next package or anything else?

**Comment by wolthers** [comment]
> Downgraded to Typescript to 4.9.5 in the meantime but problem persists? Do I also need to downgrade react-i18next package or anything else?

Downgrading typescript 4.9.5 only works for me on my minimal repro project. Remember to delete package-lock.json and re-run npm i

**Comment by adrai** [comment]
will be probably addressed in the next version

**Comment by adrai** [comment]
Please try with i18next v23.0.1 and react-i18next v13.0.0

**Comment by wolthers** [comment]
> Please try with i18next v23.0.1 and react-i18next v13.0.0

Waiting for https://github.com/sergiodxa/remix-i18next/pull/139 to go in before I can upgrade

**Comment by wolthers** [comment]
@adrai Verified that it no longer reproduces with i18next v23.0.1 and react-i18next v13.0.0
