### ISSUE TITLE
 Using i18n in next.js, the online environment reports an error

### ISSUE THREAD

**Issue by zjy365** [i18next/react-i18next#1642]
## 🐛 Bug Report

I am using next.js to do i18n, and it will report server-side rendering errors. Another problem is that the local development console does not report errors, and it crashes directly online.
![img_v2_6ef8c255-d927-444d-b2b0-4db47d205edg](https://github.com/i18next/react-i18next/assets/72259332/5fae18bc-ca3a-43f0-becc-096298f64da1)

## To Reproduce

A [minimal reproducible example](https://minimum-reproduction.wtf/).
A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

```js
// Paste your code here
```

## Expected behavior

```js
import { initReactI18next } from 'react-i18next';
import i18n from 'i18next';
import LanguageDetector from 'i18next-browser-languagedetector';
import Backend from 'i18next-http-backend';

i18n
  // load translation using http -> see /public/locales
  // learn more: https://github.com/i18next/i18next-http-backend
  .use(Backend)
  // detect user language
  // learn more: https://github.com/i18next/i18next-browser-languageDetector
  .use(LanguageDetector)
  // pass the i18n instance to react-i18next.
  .use(initReactI18next)
  // init i18next
  // for all options read: https://www.i18next.com/overview/configuration-options
  .init({
    fallbackLng: 'zh',
    debug: false,

    interpolation: {
      escapeValue: false // not needed for react as it escapes by default
    }
  });

export default i18n;

```

## Your Environment

- *runtime version*: i.e. node v14, deno, browser xy
- *i18next version*: i.e. 19.5.3
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by adrai** [comment]
Sorry, can't help without a reproducible example...
But if you use next.js please have a look at:
https://github.com/i18next/next-i18next (if you use next.js with pages setup)
https://locize.com/blog/next-13-app-dir-i18n/ (if you use next.js with app directiry setup)
