### ISSUE TITLE
Add wbr element to the default transKeepBasicHtmlNodesFor option

### ISSUE THREAD

**Issue by kiddliu** [i18next/react-i18next#1643]
## 🚀 Feature Proposal

Add `wbr` element to the default `transKeepBasicHtmlNodesFor` option

## Motivation

Usually, it may require these 2 solutions when dealing with languages such as German and Russian.

## Example

Check https://developer.mozilla.org/en-US/docs/Web/HTML/Element/wbr

```html
<div id="example-paragraphs">
    <p>Fernstraßenbauprivatfinanzierungsgesetz</p>
    <p>Fernstraßen<wbr>bau<wbr>privat<wbr>finanzierungs<wbr>gesetz</p>
    <p>Fernstraßen&shy;bau&shy;privat&shy;finanzierungs&shy;gesetz</p>
</div>
```

**Comment by adrai** [comment]
Would you like to send a Pull Request to address this? Remember to add unit tests.

**Comment by adrai** [comment]
btw: https://github.com/i18next/react-i18next/issues/1560

**Comment by kiddliu** [comment]
Yes, I did a poor job searching for the related issue and sorry for any inconvenience. Closing the issue...
