### ISSUE TITLE
Date interpolation and formatting do not work as per documentation

### ISSUE THREAD

**Issue by RachelScodes** [i18next/react-i18next#1644]
## 🐛 Bug Report

When defining an interpolated date using the example in the docs, it does not interpolate the string successfully.

## To Reproduce

A [minimal reproducible example](https://minimum-reproduction.wtf/).
A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

```ts
// in translations.ts
{
  "warning":  "This page will be deprecated on {{date, datetime}}.",
}
```

```ts
// in component.tsx
import { useTranslation } from 'react-i18next';

import { Banner } from '../components';

// MONTHS ARE 0 INDEXED
const DEPRECATION_DATE = new Date(Date.UTC(2023, 5, 31, 1, 0, 0));

export const OldHomePage = () => {
  const { t } = useTranslation();

 return (
    <Banner
        variant="warning"
        text={t('warning', {
          date: DEPRECATION_DATE,
          formatParams: {
            val: {
              weekday: 'long',
              year: 'numeric',
              month: 'long',
              day: 'numeric'
            }
          }
        })}
      />
  );
}
```

## Expected behavior

Should render like this, as per the docs:

`This page will be deprecated on Friday, June 30, 2023`

Instead, it's this:
`This page will be deprecated on {{date, datetime}}.`

  - I have tried changing to var and val instead of date
  - I have changed whitespace
  - I have tried one set of curly brackets vs 2
 
## Your Environment

- *runtime version*: i.e. node v14, deno, browser xy
- *i18next version*: i.e. 19.5.3
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by adrai** [comment]
Seems to work: https://locize.com/blog/react-i18next/#formatting

Probably you're using ICU or fluent i18n format? If so you can't use i18next formatting.

**Comment by adrai** [comment]
Here you see it works: https://codesandbox.io/s/react-i18next-http-example-forked-jw74wh?file=/src/app.js:869-1184
