### ISSUE TITLE
Nullish coalescing operator (??) breaks typescript-eslint when used inside jsx

### ISSUE THREAD

**Issue by esetnik** [i18next/react-i18next#1647]
## 🐛 Bug Report

When using nullish coalescing operator a typescript-eslint error is generated

<img width="891" alt="image" src="https://github.com/i18next/react-i18next/assets/664434/4e1b6ecd-88b5-449c-a148-42b1d5ca766e">
<img width="901" alt="image" src="https://github.com/i18next/react-i18next/assets/664434/38a8dd80-e6dd-482b-8eec-638a977f573c">

## To Reproduce

A [minimal reproducible example](https://minimum-reproduction.wtf/).
A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

```tsx
export const Test: React.FC<{
  prop?: string;
}> = ({ prop }) => {
  const { t } = useTranslation();

  return <div>{prop ?? `${t('labels.complete')}`}</div>;
};
```

## Expected behavior

No typescript error since the `labels.complete` exists in `translation.json`:

```json
{
  "labels": {
    "complete": "test translation"
  }
}
```

## Your Environment

- *runtime version*: node v18.16.1
- *i18next version*: v23.2.3
- *react-i18next version*: v13.0.1
- *os*: Mac
- *any other relevant information*

**Comment by adrai** [comment]
Can you please try to reproduce it here? https://github.com/i18next/react-i18next/tree/master/example/react-typescript/simple

**Comment by esetnik** [comment]
@adrai I was able to reproduce in https://github.com/i18next/i18next/issues/1921#issuecomment-1614113491 so I think this issue may be related.

**Comment by adrai** [comment]
> @adrai I was able to reproduce in [i18next/i18next#1921 (comment)](https://github.com/i18next/i18next/issues/1921#issuecomment-1614113491) so I think this issue may be related.

@esetnik also without the nullish operator there is an error, so I suspect the nullish operator does not influence this:
<img width="660" alt="image" src="https://github.com/i18next/react-i18next/assets/1086194/a9335d69-dbe8-4fee-8f00-01eb253f0765">

**Comment by esetnik** [comment]
@adrai yes it's possible. In my real-world project currently I use the same localization files and same configuration as far as I can tell but I have many other components and I do not receive the "Type instantiation is excessively deep and possibly infinite." error rather the one mentioned in this issue in that project. So I think it's good to keep both issues open in case there's something unique going on here that I'm not noticing.
