### ISSUE TITLE
defaultTransParent can't accept RN Text component

### ISSUE THREAD

**Issue by ziga-hvalec** [i18next/react-i18next#1648]
## 🐛 Bug Report

I'm trying to use the Trans component. But since I use React native I need to wrap whatever Trans component returns into a Text component. I'm now trying to use defaultTransParent and pass Text component but typescript doesn't like that since it only accepts string. It does work correctly it's just typescript that doesn't like it

## To Reproduce

Just pass Text component to defaultTransParent
```js
import { Text } from 'react-native';

react: {
    defaultTransParent: Text,
},
```

## Expected behavior

Typescript not complaining

## Your Environment

- i18next version: 12.3.1
- 22.5.0: 22.5.0

**Comment by adrai** [comment]
Please try with the new versions of react-i18next and i18next.
If the problem persists, feel free to start a PR.

**Comment by pedrodurek** [comment]
It's been a month now, so I'll close this issue, feel free to reopen it if the error persists.

**Comment by Rexogamer** [comment]
This is still an issue:
![image](https://github.com/i18next/react-i18next/assets/42586271/66ba35ac-36a7-4baf-b2ec-be7365e283bb)

**Comment by Rexogamer** [comment]
bump (still an issue - should i open a new issue?)
