### ISSUE TITLE
PostProcessor process value typing is not accurate

### ISSUE THREAD

**Issue by bastienvalentin** [i18next/react-i18next#1649]
## 🐛 Bug Report

When looking at the following typing:

```ts
export interface PostProcessorModule extends Module {
  /** Unique name */
  name: string;
  type: 'postProcessor';
  process(value: string, key: string | string[], options: TOptions, translator: any): string;
}
```

We assume that the value is a string but nothing prevents other types to be passed.

## To Reproduce

Here is [a sandbox](https://codesandbox.io/s/hardcore-mountain-33z2sx?file=/src/app.js) with:
- a number as a value of a translation
- a post-processor logging all the values passed.

Or if you prefer code directly:

```js
const testProcessor = {
  type: 'postProcessor',
  name: 'testProcessor',
  process(
    value,
    keys,
    options,
    translator
  ) {
    console.log({value}) // simply log the value
    return value
  },
}


i18n
  // load translation using http -> see /public/locales
  // learn more: https://github.com/i18next/i18next-http-backend
  .use(testProcessor)
  .use(Backend)
  // detect user language
  // learn more: https://github.com/i18next/i18next-browser-languageDetector
  .use(LanguageDetector)
  // pass the i18n instance to react-i18next.
  .use(initReactI18next)
  // init i18next
  // for all options read: https://www.i18next.com/overview/configuration-options
  .init({
    fallbackLng: 'en',
    debug: true,
    postProcess: ['testProcessor'],
  });
```

```json
// translation.json
{
  "title": "Welcome to react using react-i18next",
  "description": {
    "part1": "To get started, edit <1>src/App.js</1> and save to reload.",
    "part2": "Switch language between english and german using buttons above.",
    "foo": 14,
  }
}
```

## Expected behavior

Either having the type `any` to the value to tell developers to perform type checking themselves or having only string passed to that function

## Your Environment

- *runtime version*: node 18.13.0
- *i18next version*: i.e. 23.2.6
- *os*: Mac
- *any other relevant information*

**Comment by adrai** [comment]
usually it is string... but basically it can be all you have as translation value....
feel free to provide a PR for any or for i.e.  string | number | null
