### ISSUE TITLE
Allow unknown keys in `Trans` component, when `children` are provided

### ISSUE THREAD

**Issue by janpaepke** [i18next/react-i18next#1650]
## 💥 Regression Report

This is related to the same issue for the `t` function in i18next: https://github.com/i18next/i18next/issues/1867

When using the `Trans` component it is now impossible to use with `i18nKey` values that don't exist in the default namespace, even when `children` are provided, which it could fall back to.

Please see Discussion here for how this was resolved for the `t` function: https://github.com/i18next/i18next/pull/1911#issuecomment-1613081122

## Last working version

Worked up to version: 21

Stopped working in version: 22

## To Reproduce

```ts
<Trans i18nKey="unknown.key">
    My Default Value
</Trans>
```

## Expected behavior

When `children` is supplied, any key can be used.

## Proposed Solution

There should be an overload for the trans component, allowing `string` for `i18nKey`, if `children` is part of the props.

## Your Environment

runtime version: node v16
i18next version: 23.2.6
react-i18next version: 13.0.1
os: Mac

**Comment by adrai** [comment]
feel free to provide a PR
