### ISSUE TITLE
i18n instance overridden by i18n's createInstance on-demand

### ISSUE THREAD

**Issue by andrejoaquim-dc** [i18next/react-i18next#1651]
## 🐛 Bug Report

`react-i18next`'s i18n instance is overridden when creating a i18n instance on-demand that's also using `initReactI18next`. In my case, I've a library that needs to create several instances on-demand for different components.

```jsx
// app
import ComponentOne from "component-one-pkg"
import ComponentTwo from "component-two-pkg"
import { useTranslation } from "react-i18next";
import i18n from "i18n";

i18n.use(initReactI18next).init({ /* ... */ })

const App = () => {
  const { t } = useTranslation();
  return <>
    {t("appTitle")}
    <ComponentOne />
    <ComponentTwo />
  </>
}
```

```jsx
// component-one package
import createComponent from "library"

const resources = {
  en: { translation: { "hello": "Hello from C1" }}
}

const MyComponentOne = () => {
  const { t }  = useTranslation();
  return <span>{t("hello"))}</span>
}

export default createComponent(MyComponentOne, resources);
```

```jsx
// component-two package
import createComponent from "library"

const resources = {
  en: { translation: { "helloTwo": "Hello from C2" }}
}

const MyComponentTwo = () => {
  const { t }  = useTranslation();
  return <span>{t("helloTwo"))}</span>
}

export default createComponent(MyComponentTwo, resources);
```

```jsx
// library

const createI18nInstance = () => {
  const instance = i18n.createInstance();
  instance.use(initReactI18next).init();
  return instance;
}

export createComponent = (Component, translations) => {
  const i18n = createI18nInstance(); // I need a separate instance for each component, and not a global instance provided by this package

  return (
    <I18nextProvider i18n={i18n}>
      <Component />
    </I18nProvider>
  )
}
```

## To Reproduce

I've put together a codesandbox – https://codesandbox.io/s/throbbing-wave-xqnkg7 – based on `react-component-lib` example which has a simple reproducible version of the issue described above.

## Expected behavior

The expected behaviour is that the instance created on-demand doesn't override the `react-i18next`'s instance defined by the application.

`description.part2` should have the translated text.

## Your Environment

- *runtime version*: i.e. node v14.16.1
- *i18next version*: i.e. 23.2.6
- *react-i18next version*: i.e. 13.0.1
- *os*: Mac

**Comment by adrai** [comment]
Just wrap your app component (Page) with the provider and the correct i18n instance => https://codesandbox.io/s/adoring-brahmagupta-7zr3nr?file=/src/App.js:1728-1767

**Comment by andrejoaquim-dc** [comment]
Thanks, that did the job! ✅

**Comment by adrai** [comment]
@andrejoaquim-dc sorry I don't get what your issue is... can you create an example that shows our issue?

**Comment by andrejoaquim-dc** [comment]
@adrai Sorry for the late response. I've come up with a solution in the meantime. In the library, I never call `initReactI18next` and I just rely on having the components wrapped by `I18nextProvider` and `useTranslation` using the instance from the provider.

In the main application, I call `initReactI18next` that allows me not to have the Provider you suggested I added. IMHO, the main application should use `react-i18next` as they want and be conditioned by a library's implementation of `react-i18next`.

Thanks for the help!
