### ISSUE TITLE
./icu.macro is not exported from package.json

### ISSUE THREAD

**Issue by jellevandevelde** [i18next/react-i18next#1652]
## 🐛 Bug Report

When importing the Trans component from `react-i18next/icu.macro`, Webpack throws the following error: `Module not found: Error: Package path ./icu.macro is not exported from package`

## To Reproduce

- Install latest version
- Import e.g. `<Trans>` from `react-i18next/icu.macro`
- Run project

```js
import React, { Component } from 'react';
import { withTranslation } from 'react-i18next';

// importing the macro components from react-i18next
import { Trans, Plural, Select } from 'react-i18next/icu.macro';
```

## Expected behavior

No build errors

## Your Environment

- *runtime version*: node v16.10.0. Webpack 5
- *i18next version*: 
```
    "i18next": "^23.2.6",
    "i18next-http-backend": "^2.2.1",
    "i18next-icu": "^2.3.0",
    "react-i18next": "^13.0.1",
```
- *os*: Mac

**Comment by adrai** [comment]
try with v13.0.2
