### ISSUE TITLE
Global predefined component for Trans

### ISSUE THREAD

**Issue by m1heng** [i18next/react-i18next#1656]
## 🚀 Feature Proposal

A way to predefine some project wide used component for `<Trans/>`

## Motivation

Currently `<Trans/>` accepts component as a prop to customize in translation components like below
```
<Trans
  i18nKey="myKey"
  defaults="hello world <my_comp/>"
  components={{ my_comp: <MyComp /> }}
/>
```
But when you have multiple usage for same component in different i18nKey, like a inline icon, things gets dirty. You have to write the same `components={{ my_comp: <MyComp /> }}` every time you want the translation can use `<my_comp/>`

## Example
```

i18n.use(initReactI18next).init({
    // ...
    react: {
        defaultComponents: {
            a: <A />
        }
    },
    // ...
});
```

**Comment by adrai** [comment]
if this is something that many users desires, feel free to provide a PR
