### ISSUE TITLE
Allow non-list children to render correctly with i18nIsDynamicList

### ISSUE THREAD

**Issue by nicegamer7** [i18next/react-i18next#1658]
## 🚀 Feature Proposal / Possible bug fix
Hi there!

Proposals (all of which I can open a PRs for, if desired):
1. Allow `i18nIsDynamicList` to function correctly, even when child is not a list.
2. Rename `i18nIsDynamicList` to `i18nIsDynamicContent` (will be done in a backwards compatible way, i.e. both will exist for a time, maybe till v14)

## Motivation
1. I believe this first proposal is actually a bugfix. Currently, the Trans component assumes that the child of an element with the `i18nIsDynamicList` prop is a list, which may not be the case. See the following example:
```ts
const someDynamicVar = cond ? <Comp /> : 'Text';

<Trans>
  Hi there,{' '}
  <React.Fragment i18nIsDynamicList>
    {someDynamicVar}
  </React.Fragment>
</Trans>
```
The above will not render correctly. However, the following does:
```ts
const someDynamicVar = cond ? <Comp /> : 'Text';

<Trans>
  Hi there,{' '}
  <React.Fragment i18nIsDynamicList>
    <></>
    {someDynamicVar}
  </React.Fragment>
</Trans>
```

By adding a fragment, the child becomes a list, and therefore the content renders correctly. My proposal is to make it work without the need for a list.

2. If we make the above change, which seems to me to be a bugfix, it would make sense to rename the `i18nIsDynamicList` prop to something that better describes what it's for. I was thinking `i18nHasDynamicChildren`. We can make this change in a backwards compatible way (i.e. both `i18nIsDynamicList` and `i18nHasDynamicChildren` will exist for a time, maybe till v14)

Please let me know if these changes are welcome, in which case I'll make a PR!

**Comment by adrai** [comment]
Feel free to create a PR to address this, but I would not rename the prop.
