### ISSUE TITLE
React 15.2 errors

### ISSUE THREAD

**Issue by sorahn** [i18next/react-i18next#166]
There is new error reporting in react 15.2 that complains about leaking attributes into the DOM.

Looks like there are a couple in here.

https://www.dropbox.com/s/cxnnffy7cw0ahtk/Screenshot%202016-07-11%2015.01.24.png?dl=0

In that screenshot 'currentYear' and 'domain' are our attributes getting passed into `<Interpolate />`

**Comment by jamuhl** [comment]
seems we should stop passing the props to the component in interpolate...will look into this asap and publish a fix. thanks for reporting.

**Comment by jamuhl** [comment]
should be fixed in react-i18next@1.6.2
