### ISSUE TITLE
TypeScript type checking from t() function

### ISSUE THREAD

**Issue by MickaelAustoni** [i18next/react-i18next#1666]
copy of https://github.com/i18next/react-i18next/issues/1665

## 💥 Regression Report

Since version 23.x.x  from 22.x.x, i have lost type checking autocomplete with `t` function from `useTranslation` react hook. 

## Last working version

Worked up to version: 22.X.X

Stopped working in version: 23.X.X

## To Reproduce

My `i18next.d.ts` :

```` TypeScript
import "i18next";
import en from "@/locales/en";

declare module "i18next" {
  interface CustomTypeOptions {
    returnNull: false;
    defaultNS: "translation";
    resources: {
      translation: typeof en;
    };
  }
}

````

Result :
![version23](https://github.com/i18next/next-i18next/assets/108873902/955b0039-1867-4257-8f90-3c18cc654d9b)

## Expected behavior

With the same config in 22.x.x :
![version22](https://github.com/i18next/next-i18next/assets/108873902/b0a70bb6-55ad-4c29-928a-fc4961b09913)

## Your Environment

- *runtime version*: node v18, chrome, Vite 4.3.9
- *i18next version*:  23.2.8
- *os*: Mac
- *IDE*: WebStorm (Build #WS-232.8660.143)

Same behavior with `react-typescript` sample : https://github.com/i18next/react-i18next/tree/master/example/react-typescript/simple

**Comment by adrai** [comment]
Why are you copying and reopening this issue again?
Seems to work as expected:
<img width="621" alt="image" src="https://github.com/i18next/react-i18next/assets/1086194/c2e56c02-ac46-4b7e-b616-1cdcd48fbde5">

If you still think there is an issue with react-i18next please provide a minimal reproducible example repository and explain exactly what does not work.

**Comment by MickaelAustoni** [comment]
>Why are you copying and reopening this issue again?  

Yes, i have closed https://github.com/i18next/react-i18next/issues/1665 and copy on this repo.


>Also check if your IDE is up-to-date

Yes my IDE is up to date (Build #WS-232.8660.143)

> try with a different IDE, like Visual Studio Code

Indeed, it works with VCS...With WebStorm, `resources` type is not augmented from `i18next.d.ts` :

Visual Studio Code :
![Capture d’écran 2023-08-24 à 17 26 40](https://github.com/i18next/react-i18next/assets/108873902/d75454b2-fd9a-476d-8909-0220c49c0171)

WebStorm :
![Capture d’écran 2023-08-24 à 17 27 10](https://github.com/i18next/react-i18next/assets/108873902/198d9e50-11e9-4675-997a-203f64f69d22)

**Comment by adrai** [comment]
Sorry, but we're not able to fix Webstorm

**Comment by MickaelAustoni** [comment]
WebStorm don't have internal TypeScript version, it's defined from` package.json ` on your current project. Indeed, if i upgrade to TypeScript `5.xx.xx` it work again ! 

Maybe update the doc to say that it is necessary to have `TypeScript` > to  `5.x.xx` with > to `23.xx.xx` to make the autocompletion of the translation keys work.

**Comment by adrai** [comment]
Just done so ;-)
https://www.i18next.com/overview/typescript
