### ISSUE TITLE
T function wrapper broken types after update to 13.x

### ISSUE THREAD

**Issue by ithrforu** [i18next/react-i18next#1667]
## 🐛 Bug Report

We have a wrapper for `t` function in our codebase:
```js
import { useTranslation as reactI18nUseTranslation } from "react-i18next";
import { TOptions } from "i18next";

const useTranslation = () => {
  const { t } = reactI18nUseTranslation();

  return useMemo(
    () => ({
      t: (key: string, options?: TOptions) => notUndefined(t(key, options))
    }),
    [t]
  );
};
```
Before the updating we used react-i18next 11.18.6 and i18next 21.10.0 and there was not a single mistake in the tsc. But after updating to react-18next 13.2.0 and i18next 23.4.5 the wrapper began to have type errors.

## To Reproduce
react-i18next 11.18.6/ i18next 21.10.0: 
https://codesandbox.io/s/usetranslation-wrapper-before-c436fz?file=/src/App.tsx

react-i18next 13.2.0 and i18next 23.4.5: 
https://codesandbox.io/s/usetranslation-wrapper-after-d9vgrm?file=/src/App.tsx

## Expected behavior

`t` function wrapper has no types errors.

## Your Environment

- *runtime version*: node 16.20.1
- *os*: Linux
- *typescript*: 5.1.6

**Comment by adrai** [comment]
Did you try with the WithT => https://github.com/i18next/i18next/blob/master/test/typescript/mock.test.ts ?

**Comment by ithrforu** [comment]
@adrai, thank you for the quick response. `WithT` helps in codesandbox:
https://codesandbox.io/s/usetranslation-wrapper-after-witht-d9vgrm?file=/src/App.tsx
```js
const useTranslation = () => {
  const { t } = reactI18nUseTranslation();

  const withT: WithT = useMemo(
    () => ({
      t: (key: string, options?: TOptions) => notUndefined(t(key, options))
    }),
    [t]
  );

  return withT;
};
```

But in our codebase i have an error:
```
Type '{ t: (key: string, options?: TOptions) => string; }' is not assignable to type 'WithT<"translation">'.
  Types of property 't' are incompatible.
    Property '$TFunctionBrand' is missing in type '(key: string, options?: TOptions) => string' but required in type 'TFunction<"translation", undefined>'.ts(2322)
t.d.ts(210, 3): '$TFunctionBrand' is declared here.
```

**Comment by jtbandes** [comment]
what about `as TFunction<"translation">`?

**Comment by ithrforu** [comment]
@jtbandes `as TFunction<"translation">` prevents the error:
```
export const useTranslation = () => {
  const { t } = reactI18nUseTranslation();

  const withT = useMemo(
    () => ({
      t: ((...args) => notUndefined(t(...args))) as TFunction<'translation'>,
    }),
    [t]
  );

  return withT;
};
```
But I'm not sure if type casting is a good way to solve the problem.

**Comment by steugene** [comment]
Any updates on this?

**Comment by ryanswanson** [comment]
I found this thread while upgrading i18next from v19 to v23 and encountering the same `'$TFunctionBrand' is missing` error.  Sharing the following in case it helps others.

We updated our `createT()` factory method that configures a `TFunction` wrapper with custom logic as follows:
- `TFunction` type parameters should flow from passed `TFunction` to returned `TFunction`
- `$TFunctionBrand` (a runtime JS Function property that serves as a [branded type](https://egghead.io/blog/using-branded-types-in-typescript)) should be added to the returned `Function` from the passed `Function`.

v19
```typescript
function createT(t: TFunction): TFunction {
  return (...targs: Parameters<TFunction>): ReturnType<TFunction> => {
    // Custom wrapper logic
    return t(...targs);
  };
};
```

v23
```typescript
function createT<Ns extends Namespace = DefaultNamespace, KPrefix = undefined>(
  t: TFunction<Ns, KPrefix>
): TFunction<Ns, KPrefix> {
  const tFunction = (
    ...targs: Parameters<TFunction<Ns, KPrefix>>
  ): ReturnType<TFunction<Ns, KPrefix>> => {
    // Custom wrapper logic
    return t(...targs);
  };
  tFunction.$TFunctionBrand = t.$TFunctionBrand;
  return tFunction;
}
```
