### ISSUE TITLE
[Trans component] Format using `[[${value}]]` instead of `{{${value}}}` ?

### ISSUE THREAD

**Issue by gustaveWPM** [i18next/react-i18next#1668]
Hello,

I'm experiencing an issue in TypeScript with the current _Trans_ component formatter's conventions.

```tsx
<Trans i18nKey="languageSwitcher" t={t}>
  Switch from <strong>{{lng}}</strong> to:{' '}
</Trans>
```

Gives me a **ts(2322)** error.

```tsx
<Trans i18nKey="languageSwitcher" t={t}>
  Switch from <strong>[[lng]]</strong> to:{' '}
</Trans>
```

Seems "Valid".

I tried to read quickly the code of _TransWithoutContext.js_, and it seems to be a "minor" change to do on the line 89.

```js
stringNode += `{{${value}}}`;
```

Would become:

```js
stringNode += `[[${value}]]`;
```

(I guess? lol.)

Unfortunately, given the widespread adoption of the library, I think introducing such a silly _breaking change_ would be quite detrimental. However, do you have a 'magical' solution to suggest? I think I haven't understood the code well, nor have I grasped how to use this formatter effectively.

I am very frustrated to have this error, and having to add TypeScript annotations to ignore it also deeply bothers me, unfortunately.

**Comment by adrai** [comment]
I don't understand what the problem with curly brackets in TS really means, but we will not change the brackets style. Sorry.

**Comment by gustaveWPM** [comment]
@adrai Have you any "Tricky" solution to bypass the TypeScript error?
I tried to write `Switch from <strong>{'{{lng}}'}</strong> to:{' '}`, but it doesn't work and always display a raw `{{lng}}`, unfortunately.

**Comment by gustaveWPM** [comment]
ping @adrai 

I found a workaround.
```tsx
      <Trans i18nKey="languageSwitcher" t={t}>
        Switch from
        <strong>
          <>{{ lng }}</>
        </strong>
        to:{' '}
      </Trans>
```
