### ISSUE TITLE
`TransWithoutContext` is missing a typescript definition

### ISSUE THREAD

**Issue by javiertury** [i18next/react-i18next#1671]
## 🐛 Bug Report

`TransWithoutContext` is missing a typescript definition

## To Reproduce

```js
import { TransWithoutContext } from 'react-i18next';
```

## Expected behavior

Typescript  should not raise an error about `TransWithoutContext` not being defined

## Your Environment

- *runtime version*:node V20
- *i18next version*: 23.4.1
- *os*: Linux

**Comment by adrai** [comment]
should be fixed with v13.2.2
