### ISSUE TITLE
React-Typescript "simple-multi-namespaces"-example no type-checks

### ISSUE THREAD

**Issue by gandalf92** [i18next/react-i18next#1674]
## 🐛 Bug Report
Typechecks in t-function from useTranslation seem not to work after i18next version 23.3.0

## To Reproduce

1. Clone this repo
2. Open `example/react-typescript/simple-multi-namespaces`
3. Run npm i
4. Open `example/react-typescript/simple-multi-namespaces/src/components/Comp1.tsx`
5. Enter wrong key

```
import { useTranslation } from 'react-i18next';

function Comp1() {
  const { t } = useTranslation();

  return (
    <div className="App">
      <p>{t('title')}</p>
      <p>{t('description.WRONG')}</p>
      <p>{t('description.part2')}</p>
    </div>
  );
}

export default Comp1;
```

After downgrading i18next to version 23.3.0 Typechecks seem to work again.

## Expected behavior

Typescript should show an error.

## Your Environment

- *runtime version*: node 18.17.1
- *os*: Mac

**Comment by adrai** [comment]
seems to work:
<img width="670" alt="image" src="https://github.com/i18next/react-i18next/assets/1086194/e0754d22-76f4-40a4-b736-d629a09d5416">
