### ISSUE TITLE
useTranslation does not trigger suspense when language is not loaded

### ISSUE THREAD

**Issue by romulof** [i18next/react-i18next#1677]
## 🐛 Bug Report

`useTranslation` triggers React Suspense when language is not available, but when changing to another language that is not yet loaded, it won't trigger Suspense.

## To Reproduce

https://codesandbox.io/s/shy-dawn-kzv2fy

Here I made a Backend module that delays delivery by 2 seconds.
When the app loads for the first time, it triggers suspense perfectly, but when you switch languages you can see it takes 2 seconds to switch, but no suspense was triggered.

## Expected behavior

If I configure i18next to use a language that is not yet loaded, and react-i18next is configured to use suspense mode, it should trigger suspense mode.

## Your Environment

- *runtime version*: node v16, chrome 116
- *os*: macOS
- *react-i18next*: 12.2.0
- *i18next version*: 22.4.10

**Comment by adrai** [comment]
Why should it suspense?
The first language is still there and has valid values until the second language loads the translations.

**Comment by adrai** [comment]
You can force it with listening also to the languageChanging event:

https://codesandbox.io/s/funny-gagarin-vsdh4x?file=/src/i18n.js:739-805

```js
    react: {
      bindI18n: "languageChanged languageChanging"
    },
```

**Comment by romulof** [comment]
> Why should it suspense? The first language is still there and has valid values until the second language loads the translations.

Use-case:
1. User made an interaction to switch language
2. Browser takes a while to switch the language
3. User don't get a visual indication that something is loading

Yeah, we can create our own loading indication on top of the existing one, but it would be one more, on top of the one that already exists.

**Comment by jamuhl** [comment]
closing as solution was provided: https://github.com/i18next/react-i18next/issues/1677#issuecomment-1714357090
