### ISSUE TITLE
Nested plurals don't take cardinality into account

### ISSUE THREAD

**Issue by arieltorti** [i18next/react-i18next#1678]
## 🐛 Bug Report

I'm following https://www.i18next.com/translation-function/nesting#passing-options-to-nestings to create a sentence with many plurals. But it seems like when nesting plurals are ignored all together and the cardinality (_zero, _one, etc) is never used.

## To Reproduce

https://codesandbox.io/s/ecstatic-wilbur-v77j78?file=/src/App.js

```js
// App.js
t("girlsAndBoys", { girls: 3, boys: 2 })
```

```
// en.translation.js
{
    girlsAndBoys: 'They have $t(girls, {"count": "{{girls}}" }) and $t(boys, {"count": "{{boys}}" })',
    boys: "{{count}} boy",
    boys_other: "{{count}} boys",
    girls: "{{count}} girl",
    girls_other: "{{count}} girls"
}
```

## Expected behavior

It should display the plural form:

> They have 3 girl**s** and 2 boy**s**

instead, it displays the singular form:

> They have 3 girl and 2 boy

I also tried adding the `ordinal` prefix as shown in https://github.com/i18next/i18next/pull/1945 but didn't work. Although i may be doing something wrong.

## Your Environment

- *runtime version*: Node v20
- *i18next version*: v23.5.1
- *react i18next version*: v13.2.2
- *os*: Linux

**Comment by adrai** [comment]
The count value needs to be a number, not a string:

```diff
- girlsAndBoys: 'They have $t(girls, {"count": "{{girls}}" }) and $t(boys, {"count": "{{boys}}" })'
+ girlsAndBoys: 'They have $t(girls, {"count": {{girls}} }) and $t(boys, {"count": {{boys}} })'
```

```json
{
    "girlsAndBoys": "They have $t(girls, {\"count\": {{girls}} }) and $t(boys, {\"count\": {{boys}} })",
    "boys": "{{count}} boy",
    "boys_other": "{{count}} boys",
    "girls": "{{count}} girl",
    "girls_other": "{{count}} girls",
}
```
