### ISSUE TITLE
Angel brackets in replacement value unexpected behavior

### ISSUE THREAD

**Issue by justanotheranonymoususer** [i18next/react-i18next#1680]
## 🐛 Bug Report

I thought values are treated as plain text, I tried to use something like this:
Translation template: `"Test: <0>{{replace_me}}</0>... end of test"`
`components={[<span style={{ color: "red" }} />]}`
`values={{ replace_me: "<replacement>" }}`

I wanted to see a red `<replacement>`, but everything became red it got a closing tag (?!):

![image](https://github.com/i18next/react-i18next/assets/5781692/cf7073f7-4a90-44e1-9e37-b190b3f66afc)

Is it a bug or an obscure feature? Is there a workaround while it's being fixed?

## To Reproduce

https://codesandbox.io/s/beautiful-cloud-wrv5t6?file=/src/App.js

```js
// test: "Test: <0>{{replace_me}}</0>... end of test"
<Trans
  t={t}
  i18nKey="test"
  components={[<span style={{ color: "red" }} />]}
  values={{
    replace_me: "<replacement>"
  }}
/>
```

## Expected behavior

I wanted to see a red `<replacement>`.

## Your Environment

- *runtime version*: i.e. node v14, deno, browser xy
- *i18next version*: 23.5.1
- *os*: Windows
- *any other relevant information*

**Comment by adrai** [comment]
Seems there is a problem if the interpolated value includes the `<` character

**Comment by adrai** [comment]
ahh, just seen you set the escapeValue interpolation option to false...
See this: https://codesandbox.io/s/frosty-khayyam-p9hyj7?file=/src/i18n.js:521-595

**Comment by justanotheranonymoususer** [comment]
But your link shows `&lt;replacement&gt;`. I want to show `<replacement>` obviously.

**Comment by adrai** [comment]
that's because it's automatically html escaped by react / html-parse-stringify

**Comment by adrai** [comment]
try shouldUnescape: https://codesandbox.io/s/bold-tharp-jyd4hv?file=/src/App.js:393-407

**Comment by justanotheranonymoususer** [comment]
OK, thank you for the workaround, but I'm afraid that enabling `escapeValue: true` for the whole project might break other things. I'll look for another workaround, and will meanwhile wait for a fix.

**Comment by adrai** [comment]
There is no fix, this is how it works.
Alternatively, you can pass the tOptions like this instead of the global options: https://codesandbox.io/s/bold-tharp-jyd4hv?file=/src/App.js:418-566

**Comment by justanotheranonymoususer** [comment]
Thanks, that's a workaround I can use.

> There is no fix, this is how it works.

But why? Why not treat it as text? Why `<` causes this behavior?

Why this:
```
shouldUnescape
tOptions={{
  interpolation: {
    escapeValue: true
  }
}}
```
makes a difference at all? Why isn't it the default behavior?

**Comment by adrai** [comment]
Because with escapeValue: true the interpolation value <replacement> is targeted so it passes the React handling...
and shouldUnescape brings it back...
btw: `escapeValue` is `true` by default, but you've overriden it in the global options.
So in a "normal" setup you would only need to pass shouldUnescape, because all interpolated values are escaped by default.

**Comment by justanotheranonymoususer** [comment]
> Because with escapeValue: true the interpolation value is targeted so it passes the React handling...

But why without it there's the buggy handling?

Also, can I set `shouldUnescape` globally?

> btw: `escapeValue` is `true` by default, but you've overriden it in the global options.

I copied from the official guide:
https://react.i18next.com/latest/using-with-hooks#configure-i18next

**Comment by tommoor** [comment]
> I copied from the official guide:

Agreed, it's odd that the official docs still show this as an example by the way – I'm sure many have copied it and are now left in this confusing situation
