### ISSUE TITLE
Typescript error `Type 'HTMLAttributes<T>' is not assignable to type 'DOMAttributes<T>'`

### ISSUE THREAD

**Issue by moonray** [i18next/react-i18next#1681]
## 🐛 Bug Report

I've read through, and worked through all suggested fixes in previous iterations of this bug report.
However, there doesn't seem to be a valid solution with the latest versions of @types/react.

I configured `allowObjectInHTMLChildren: true;`

The specific error:
```
| ../../node_modules/@types/react/index.d.ts:232:106 - error TS2344: Type 'P' does not satisfy the constraint 'DOMAttributes<T>'.
 |   Type 'HTMLAttributes<T>' is not assignable to type 'DOMAttributes<T>'.
 |     Types of property 'children' are incompatible.
 |       Type 'ReactI18NextChildren | Iterable<ReactI18NextChildren>' is not assignable to type 'ReactNode'.
 |         Type 'Record<string, unknown>' is not assignable to type 'ReactNode'.
 |           Type 'Record<string, unknown>' is missing the following properties from type 'ReactPortal': key, children, type, props
 ```

## Expected behavior

I expect to have my code not run into typescript errors.

## Your Environment

typescript: 5.2.2
react: 18.2.0
@types/react: 18.2.22
i18next: 23.5.1
react-i18next: 13.2.2

**Comment by adrai** [comment]
@gshokanov @lexanth @ghost @JCMais @nicegamer7 can you confirm this?

**Comment by adrai** [comment]
https://github.com/i18next/react-i18next/commit/16312fff7ec16255b9d59a7f7bdfcb7d726e7a70 by @nicegamer7

**Comment by nicegamer7** [comment]
This happens when `skipLibCheck` is disabled. This was an issue prior to https://github.com/i18next/react-i18next/commit/16312fff7ec16255b9d59a7f7bdfcb7d726e7a70 as well. If you enable `skipLibCheck` in tsconfig this will go away.

**Comment by adrai** [comment]
https://www.i18next.com/overview/typescript#type-htmlattributes-less-than-t-greater-than-is-not-assignable-to-type...

**Comment by moonray** [comment]
Was that always in the docs, or did you just add it?
If the prior: my apologies. I missed it.
If the latter: thank you!

**Comment by adrai** [comment]
just added 😉
