### ISSUE TITLE
Error when using <br/> inside Trans component

### ISSUE THREAD

**Issue by AsuraKev** [i18next/react-i18next#1683]
Hi there,

A piece of my translations has a line break in the content and I followed the guide to have <br/> in both the component and translation files like below:
![image](https://github.com/i18next/react-i18next/assets/52765572/80814908-d469-4009-83b6-057245c2110c)

![image](https://github.com/i18next/react-i18next/assets/52765572/c48ceb4a-72cb-40a2-8a38-2eada8761d0d)

but i am still getting this error :(

![image](https://github.com/i18next/react-i18next/assets/52765572/67061871-0d64-4926-84a3-bdc6efad9c55)

**Comment by adrai** [comment]
The component index is wrong: it's not `<1>` but `<3>` in your example... `<1>` is targeting the `<br />`
Like: https://codesandbox.io/s/react-i18next-http-example-forked-9vh29k?file=/public/locales/en/translations.json:459-483

**Comment by SpLouk** [comment]
Hello @adrai, question for you:
1. why is the index <3> for the NavLink and not <2>
2. Would it be possible for react-i18next to know not to target <br /> if the user has their `transKeepBasicHtmlNodesFor` config include 'br'? This is the default value for this setting. 

If the answer to 2 is no, this seems like a foot gun to me, since the `i18next-cli extract` util does not properly index tags (it will start indexing at 1, even if a `<br />` tag exists before it.

**Comment by adrai** [comment]
> If the answer to 2 is no, this seems like a foot gun to me, since the `i18next-cli extract` util does not properly index tags (it will start indexing at 1, even if a `<br />` tag exists before it.

@SpLouk the new version of i18next-cli, does exactly the same as react-i18next, since it uses the same function to create the indexes.

**Comment by SpLouk** [comment]
@adrai Which version? I just upgraded to the latest i18next-cli and react-i18next, and now when I run `extract` I get a bunch of warnings like: 
```
react-i18next:: Invalid child - Object should only have keys {{ value, format }} (format is optional). {
  code: 'TRANS_INVALID_OBJ',
  i18nKey: undefined,
  child: {
    '$$typeof': Symbol(react.transitional.element),
    type: 'br',
    key: null,
    props: {},
    _owner: null,
    _store: {}
  }
```

and the translations for this specific key are not generated.

**Comment by adrai** [comment]
> [@adrai](https://github.com/adrai) Which version? I just upgraded to the latest i18next-cli and react-i18next, and now when I run `extract` I get a bunch of warnings like:
> 
> ```
> react-i18next:: Invalid child - Object should only have keys {{ value, format }} (format is optional). {
>   code: 'TRANS_INVALID_OBJ',
>   i18nKey: undefined,
>   child: {
>     '$$typeof': Symbol(react.transitional.element),
>     type: 'br',
>     key: null,
>     props: {},
>     _owner: null,
>     _store: {}
>   }
> ```
> 
> and the translations for this specific key are not generated.

@SpLouk v16.5.1 https://github.com/i18next/react-i18next/blob/master/CHANGELOG.md - But you should provide a reproducible example (or even better a new test case) in the i18next-cli repository, if you think there's an issue.

//cc @joshkel
