### ISSUE TITLE
`Trans` only interpolates `defaultVariables` if `values` or `components` is present

### ISSUE THREAD

**Issue by hubgit** [i18next/react-i18next#1685]
## 🐛 Bug Report

I was surprised to find that the `Trans` component does not interpolate values from `defaultVariables` when only the translation key is provided.

## To Reproduce

https://codesandbox.io/p/sandbox/i18-next-trans-default-variables-tq3xmv

```js
import i18n from 'i18next'
import { initReactI18next, Trans } from 'react-i18next'

i18n.use(initReactI18next).init({
  lng: 'en',
  interpolation: {
    defaultVariables: {
      name: 'Bob',
    },
  },
  resources: {
    en: {
      translation: {
        test: 'My name is {{name}}.',
      },
    },
  },
})

export const App = () => (
  <div className="App">
    <div>
      <Trans i18nKey="test" />
    </div>
    <div>
      <Trans i18nKey="test" components={{}} />
    </div>
    <div>
      <Trans i18nKey="test" values={{}} />
    </div>
  </div>
)
```

<img width="167" alt="image" src="https://github.com/i18next/react-i18next/assets/14294/c4388c8c-ffc2-4b73-b058-8e2c0078eb3d">

## Expected behavior

`<Trans i18nKey="test" />` should interpolate default variables into the translation template with key `test`.

## Your Environment

- *runtime version*: Node v18, Chrome v117
- *i18next version*: 23.5.1
- *react-i18next version*: 13.2.2
- *os*: macOS

- refs #1375
- refs #1515

**Comment by adrai** [comment]
That's a new feature... coming with v13.3.0
