### ISSUE TITLE
`Trans` replaces components in values

### ISSUE THREAD

**Issue by hubgit** [i18next/react-i18next#1686]
## 🐛 Bug Report

It seems that `Trans` is parsing the HTML input and replacing components _after_ interpolating the values, so markup in the values (which can come from user input) is converted to components.

## To Reproduce

https://codesandbox.io/p/sandbox/i18-next-trans-escape-j3ct2z

```js
import i18n from 'i18next'
import { initReactI18next, Trans } from 'react-i18next'

i18n.use(initReactI18next).init({
  lng: 'en',
  interpolation: {
    escapeValue: false,
  },
  react: {
    transSupportBasicHtmlNodes: false,
  },
  resources: {
    en: {
      translation: {
        test: 'My <code>name</code> is {{name}}.',
      },
    },
  },
})

export const App = () => (
  <div className="App">
    <div>
      <Trans
        i18nKey="test"
        values={{
          name: "<code>Bob O'lob</code>",
        }}
        components={{
          code: <code style={{ background: 'yellow' }} />,
        }}
      />
    </div>
  </div>
)
```

<img width="174" alt="image" src="https://github.com/i18next/react-i18next/assets/14294/3d692fe4-16ab-49d1-8271-e68783223203">

## Expected behavior

The values should be treated as plain strings, without any added components, so that a user is not able to inject any markup into the page.

<img width="271" alt="image" src="https://github.com/i18next/react-i18next/assets/14294/243c5172-30c9-4c5e-b57d-f0edc1ce9f82">

## Your Environment

- *runtime version*: Node v18, Chrome v117
- *i18next version*: 23.5.1
- *react-i18next version*: 13.2.2
- *os*: macOS

**Comment by hubgit** [comment]
A workaround is to set `escapeValue: true` and add the `shouldUnescape` prop to every use of the `Trans` component.

**Comment by adrai** [comment]
That's not a workaround, that's the way to go ;-)

**Comment by hubgit** [comment]
The trouble with setting `escapeValue: true` is that it also applies to the values passed to `t`, and as far as I can tell there isn't a way to set `shouldUnescape` for those.

https://codesandbox.io/p/sandbox/i18-next-t-escape-p9qr3x

```js
import i18n from 'i18next'
import { initReactI18next, Trans, useTranslation } from 'react-i18next'

i18n.use(initReactI18next).init({
  lng: 'en',
  interpolation: {
    escapeValue: true,
  },
  react: {
    transSupportBasicHtmlNodes: false,
  },
  resources: {
    en: {
      translation: {
        test: 'My name is {{name}}.',
      },
    },
  },
})

export const App = () => {
  const { t } = useTranslation()

  return (
    <div className="App">
      <div>
        <Trans i18nKey="test" values={{ name: "Bob O'lob" }} shouldUnescape />
      </div>
      <div>{t('test', { name: "Bob O'lob" })}</div>
    </div>
  )
}
```

<img width="208" alt="image" src="https://github.com/i18next/react-i18next/assets/14294/248e295b-eeb6-44e0-8435-aeb4effab947">

**Comment by hubgit** [comment]
I've just discovered that it's possible to pass `interpolation: { escapeValue: false }` as an option to `t`, which stops it escaping the values.

**Comment by hubgit** [comment]
Another attempt, this time setting `escapeValue: false` globally (so `t` works as expected without extra options), and passing `tOptions={{ interpolation: { escapeValue: true } }} shouldUnescape` to every `Trans` component:

https://codesandbox.io/p/sandbox/i18-next-interpolation-6gxtv3

```js
import i18n from 'i18next'
import { initReactI18next, Trans, useTranslation } from 'react-i18next'

i18n.use(initReactI18next).init({
  lng: 'en',
  interpolation: {
    escapeValue: false,
  },
  react: {
    transSupportBasicHtmlNodes: false,
  },
  resources: {
    en: {
      translation: {
        test: 'My name is {{name}}.',
        test_with_code: 'My <code>name</code> is {{name}}.',
      },
    },
  },
})

export const App = () => {
  const { t } = useTranslation()

  return (
    <div className="App">
      <div>
        <Trans i18nKey="test" values={{ name: "Bob O'lob" }} />
      </div>
      <div>{t('test', { name: "Bob O'lob" })}</div>
      <div>
        <Trans
          i18nKey="test_with_code"
          values={{
            name: "<code>Bob O'lob</code>",
          }}
          components={{
            code: <code style={{ background: 'yellow' }} />,
          }}
          tOptions={{
            interpolation: { escapeValue: true },
          }}
          shouldUnescape
        />
      </div>
    </div>
  )
}
```

<img width="265" alt="image" src="https://github.com/i18next/react-i18next/assets/14294/235f1153-b26b-4aea-8082-5c19b91c9bd2">

**Comment by ashfurrow** [comment]
I found this issue while trying to figure out why my React Native app kept turning apostrophes into `&#39;`. @hubgit your code was very helpful, thank you!
