### ISSUE TITLE
Instance from component lib overrides resorces in root i18n

### ISSUE THREAD

**Issue by Karine91** [i18next/react-i18next#1690]
## 🐛 Bug Report

If i18n instance from component library was initialized latter then i18n in main project, it overrides the main resource store.
![image](https://github.com/i18next/react-i18next/assets/26932594/094224af-1923-45a6-8b90-c423544ec8e0)

## To Reproduce

To reproduce the issue I used your example of the using instance for component library and updated deps:
https://github.com/i18next/react-i18next/tree/master/example/react-component-lib

and modified the i18n files like so:
https://gist.github.com/Karine91/d27cf7436b67df039ae0998b09385545

## Expected behavior

Instances should not override each other no matter of the init order

## Your Environment

- *runtime version*:  node v18
- *i18next version*: 23.4.4
- *os*: Windows

**Comment by jamuhl** [comment]
-> https://react.i18next.com/latest/i18nextprovider#when-to-use

you can't use `initReactI18next` when having multiple instances

**Comment by Karine91** [comment]
> -> https://react.i18next.com/latest/i18nextprovider#when-to-use
> 
> you can't use `initReactI18next` when having multiple instances

but that's how it was used in your example

**Comment by adrai** [comment]
you don't need initReactI18next to be passed in the component-lib: https://github.com/i18next/react-i18next/commit/461986289fe82a70a5ddae9078c7c7e68f86f7dd

**Comment by Karine91** [comment]
Thanks, now working
