### ISSUE TITLE
Hit typedscript error when using useTranslation hook (TS2589: Type instantiation is excessively deep and possibly infinite.)

### ISSUE THREAD

**Issue by henryhoo** [i18next/react-i18next#1692]
## 🐛 Bug Report

Hit ts error when upgrading to a newer version of i18next.

> TS2589: Type instantiation is excessively deep and possibly infinite.

## To Reproduce

* [minimal reproducible example](https://github.com/henryhoo/i18next-issue/commits/main).
   *  The project is a clean react ts template (created from `npx create-react-app i18n-issue --template typescript`)
   *  i18next related change is in [this commit](https://github.com/henryhoo/i18next-issue/commit/b1b131e88d39bed8aaf5c12e0bda4ed416a7d5ea)
* [step to reproduce the error](https://github.com/henryhoo/i18next-issue/blob/main/README.md)

### Note:

hit this issue with following version:
* "react-i18next": "^13.3.2",
* "i18next": "^23.7.1",

if downgrade to this version, issue is gone:
* "react-i18next": "^11.18.3",
* "i18next": "^21.8.16",

![image](https://github.com/i18next/react-i18next/assets/7495621/1830c879-a9a6-45c6-a9ae-346c1c6ae2c5)

## Expected behavior

Project run and build fine

## Your Environment

- *runtime version*: i.e. node v21.1.0, chrome
- *i18next version*: i.e. 23.7.1
- *os*: Mac

**Comment by adrai** [comment]
update your typescript dependency and the error should be gone

**Comment by adrai** [comment]
https://github.com/henryhoo/i18next-issue/blob/109179bdf05177ffb989c8c5a50dd20d1dcf359e/package.json#L18
https://www.i18next.com/overview/typescript
<img width="799" alt="image" src="https://github.com/i18next/react-i18next/assets/1086194/bb9cb1a5-873c-4a71-aa05-2471e5abf264">

**Comment by kamikaze** [comment]
but hey... How do you expect us upgrading typescript since react-scripts does not support it? Did you ever tested latest react-i18next on a fresh node_modules install? You either will not install it due to dependencies, either you will get an error later.

**Comment by adrai** [comment]
Feel free to contribute with a PR if you have a way to address this without using ts v5...

**Comment by adrai** [comment]
ts v4 might also work, but your tsconfig would probably need to be set to `"module": "CommonJS",` and `"moduleResolution": "Classic",`

**Comment by adrai** [comment]
I have another idea

**Comment by adrai** [comment]
try with v23.7.5

**Comment by kamikaze** [comment]
works with:

```typescript
  "overrides": {
    "react-scripts": {
      "typescript": ">3.2.1"
    }
  },
```

**Comment by adrai** [comment]
should also work with v23.7.5 without overrides

**Comment by adrai** [comment]
i18next v23.7.6 + react-i18next v13.4.1

**Comment by Eng-FerasAhmad** [comment]
i18next v23.7.6 + react-i18next v13.4.1 didn't work for me :-( 
typescript 5.2.2, any new Idea?

**Comment by adrai** [comment]
@Eng-FerasAhmad please update the versions. If it still does not work create a minimal reproducible example repository.

**Comment by Eng-FerasAhmad** [comment]
@adrai I found a problem with the i18n.d.ts 
solved, thanks

**Comment by QVladislav** [comment]
> @adrai I found a problem with the i18n.d.ts solved, thanks

What was your solution? I'm having the same issue

**Comment by 3pleFly** [comment]
> [@adrai](https://github.com/adrai) I found a problem with the i18n.d.ts solved, thanks

bro. did u reply to show off or what? 
wheres the soltuins
