### ISSUE TITLE
Type error with i18next@23.7.2+

### ISSUE THREAD

**Issue by rktyt** [i18next/react-i18next#1693]
## 🐛 Bug Report

The following error occurs:

> error TS2741: Property 'reportNamespaces' is missing in type 'import("/tmp/test/node_modules/i18next/index").i18n' but required in type 'import("/tmp/test/node_modules/i18next/index").i18n'.

More details:
![スクリーンショット 2023-11-13 18 54 36](https://github.com/i18next/react-i18next/assets/26789317/8429705a-7eaa-49fd-986f-558e4a87d2e9)

----

No errors with i18next versions 27.6.0, 27.7.0, 27.7.1.
I’m got errors with i18next versions 27.7.2, 27.7.3.

## To Reproduce

The following three files are required to reproduce.

index.tsx:
```typescript
import { createInstance } from 'i18next'
import type { ReactNode } from 'react'
import { initReactI18next, I18nextProvider } from 'react-i18next'

const i18n = createInstance()
await i18n.use(initReactI18next).init({
  lng: 'en',
  fallbackLng: 'en',
  ns: ['common'],
  defaultNS: 'common',
  debug: false,
  interpolation: {
    escapeValue: false,
  },
  resources: { en: { common: {} } },
})

export function I18nextTestStubProvider({ children }: { children: ReactNode }) {
  return <I18nextProvider i18n={i18n}>{children}</I18nextProvider>
}
```

package.json:
```json
{
  "dependencies": {
    "i18next": "23.7.3",
    "react": "^18.2.0",
    "react-i18next": "^13.4.0"
  },
  "devDependencies": {
    "@types/react": "^18.2.37",
    "typescript": "^5.2.2"
  }
}
```

tsconfig.json:
```json
{
  "compilerOptions": {
    "target": "ESNext",
    "useDefineForClassFields": true,
    "lib": ["DOM", "DOM.Iterable", "ESNext"],
    "allowJs": false,
    "skipLibCheck": true,
    "esModuleInterop": false,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "strictNullChecks": true,
    "removeComments": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "baseUrl": "."
  }
}
```

After creation, check with `npm install && npx tsc --noEmit`

## Expected behavior

No type errors.

## Your Environment

- *runtime version*: node v18
- *i18next version*: 23.7.3
- *os*: Linux

## Additionnal context

Probably the same as #1379.
However, the cause seems to be different because multiple versions of i18next are not installed.

**Comment by adrai** [comment]
Can you provide a reproducible example please?

**Comment by rktyt** [comment]
@adrai 
I've updated it to include everything you need to reproduce it.

**Comment by konomae** [comment]
Same here 🙋‍♂️

I also created a minimum reproduction:
https://stackblitz.com/edit/vitejs-vite-vpz18f?file=src%2Fmain.ts

<img width="673" alt="Screenshot" src="https://github.com/i18next/react-i18next/assets/1920783/3dabdd4e-0e43-4864-9885-427e9ea888a1">

**Comment by adrai** [comment]
seems this is because of the moduleResolution set to bundler... if you change it to NodeNext, it works

**Comment by adrai** [comment]
https://github.com/i18next/i18next/issues/2063

**Comment by stevensacks** [comment]
@adrai Usage in remix requires moduleResolution "bundler" due to ESM/CJS conflicts.

**Comment by adrai** [comment]
If you have an idea on how to "fix" this, feel free to provide a PR.

**Comment by stevensacks** [comment]
cc: @sergiodxa (the author of remix-i18next)

**Comment by adrai** [comment]
v13.4.1 should be better

**Comment by adrai** [comment]
i18next v23.7.6 + react-i18next v13.4.1

**Comment by adrai** [comment]
Alternatively, try to cast it:

```ts
import { createInstance, i18n as I18N } from "i18next";
import { useTranslation } from "react-i18next";

const i18n = createInstance();
useTranslation("test", { i18n: i18n as I18N });
```

**Comment by stevensacks** [comment]
Still a problem in 23.7.6 and 13.4.1.

**Comment by adrai** [comment]
Did you try to cast it? Like here: https://github.com/i18next/react-i18next/issues/1693#issuecomment-1808105772

**Comment by stevensacks** [comment]
Yes, but it doesn’t resolve the type error with the Provider i18n prop. The example above is used with the useTranslation hook, but that isn’t an issue in remix. Just the provider.

**Comment by adrai** [comment]
Did you try this?

```jsx
import { i18n as I18N } from "i18next";
// ...
<I18nextProvider i18n={instance as I18N}>
```

**Comment by adrai** [comment]
This works for me:

```tsx
import { createInstance, i18n as I18N } from 'i18next'
import type { ReactNode } from 'react'
import { initReactI18next, I18nextProvider } from 'react-i18next'

const i18n = createInstance()
i18n.use(initReactI18next).init({
  lng: 'en',
  fallbackLng: 'en',
  ns: ['common'],
  defaultNS: 'common',
  debug: false,
  interpolation: {
    escapeValue: false,
  },
  resources: { en: { common: {} } },
})

export function I18nextTestStubProvider({ children }: { children: ReactNode }) {
  return <I18nextProvider i18n={i18n as I18N}>{children}</I18nextProvider>
}
```

**Comment by stevensacks** [comment]
In remix-i18next, on the entry.server file, you do this:

https://github.com/sergiodxa/remix-i18next#server-side-configuration

```ts
let instance = createInstance();
  let lng = await i18next.getLocale(request);
  let ns = i18next.getRouteNamespaces(remixContext);

  await instance
    .use(initReactI18next) // Tell our instance to use react-i18next
    .use(Backend) // Setup our backend
    .init({
      ...i18n, // spread the configuration
      lng, // The locale we detected above
      ns, // The namespaces the routes about to render wants to use
      backend: { loadPath: resolve("./public/locales/{{lng}}/{{ns}}.json") },
    });

  return new Promise((resolve, reject) => {
    let didError = false;

    let { pipe, abort } = renderToPipeableStream(
      <I18nextProvider i18n={instance}>
        <RemixServer context={remixContext} url={request.url} />
      </I18nextProvider>,
      ```

**Comment by adrai** [comment]
You're still not casting the instance in your code.

Instead of:

`<I18nextProvider i18n={instance}>
        <RemixServer context={remixContext} url={request.url} />
</I18nextProvider>,`

Do:

`<I18nextProvider i18n={instance as I18N}>
        <RemixServer context={remixContext} url={request.url} />
</I18nextProvider>,`

**Comment by stevensacks** [comment]
That’s not my code, I pasted the code example from the docs I linked to.

In my code, I cast it as I said:
>`I tried i18n={instance as I18N} but the error persists.`

**Comment by adrai** [comment]
So can you please provide your complete reproducible Code repository?
Or keep the ts-ignore 🤷‍♂️

**Comment by stevensacks** [comment]
Can’t do the first, unfortunately. I’ll keep the ts-ignore but other remix-i18next users may run into the same issue so I’ll have Sergio make a note about it.

**Comment by stevensacks** [comment]
Got it working with the casting.

**Comment by 127** [comment]
> Did you try this?
> 
> ```js
> import { i18n as I18N } from "i18next";
> // ...
> <I18nextProvider i18n={instance as I18N}>
> ```

this one works perfectly with remix 2.2.0

**Comment by tgds** [comment]
this module augmentation is the problem: https://github.com/i18next/react-i18next/blob/fdab4e8953b2cdaf29d21d716d33ebfd0eca99f2/index.d.ts#L41

**Comment by adrai** [comment]
v14.0.0 has just been released that should make it optional

**Comment by tgds** [comment]
> v14.0.0 has just been released that should make it optional

thanks for the super quick release!
