### ISSUE TITLE
after webpack production build error

### ISSUE THREAD

**Issue by wkylin** [i18next/react-i18next#1694]
## 🐛 Bug Report

after change lang error:
Uncaught TypeError: Cannot convert undefined or null to object

## To Reproduce

A [minimal reproducible example](https://minimum-reproduction.wtf/).
A [codesandbox](https://codesandbox.io/examples/package/i18next) example or similar
or at least steps to reproduce the behavior:

```js
import i18n from 'i18next'
import Backend from 'i18next-http-backend'
import { initReactI18next } from 'react-i18next'
import LanguageDetector from 'i18next-browser-languagedetector'

i18n
  .use(Backend)
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    backend: {
      loadPath: `/locales/{{lng}}/{{ns}}.json`,
    },
    lng: 'zh',
    fallbackLng: 'zh', // 默认语言
    debug: process.env.NODE_ENV === 'production', // 开启调试模式
    interpolation: {
      escapeValue: false, // 不转义特殊字符
    },
    detection: {
      order: ['localStorage', 'navigator'],
    },
  })

export default i18n
```

## Expected behavior

```js
after change lang error:
Uncaught TypeError: Cannot convert undefined or null to object

```

## Your Environment

- *runtime version*: i.e. node v21, browser chrome
- "i18next": "^23.7.3",
- "i18next-browser-languagedetector": "^7.2.0",
- "i18next-http-backend": "^2.4.1",
- *os*: Mac
- *any other relevant information*

website:
https://wkylin.github.io/pro-react-admin/

**Comment by adrai** [comment]
I don't think this is related to i18next. Can you please share the code?

**Comment by adrai** [comment]
fyi: i tried to run https://github.com/wkylin/pro-react-admin/ locally, and I can't see that error.

**Comment by wkylin** [comment]
The problem has been solved.

The webpack configuration in this project has a separate handling of json, which is built into webpack5.
