### ISSUE TITLE
Show warnings whenever i18n cannot find matched strings

### ISSUE THREAD

**Issue by ngtrthinh169TPC** [i18next/react-i18next#1696]
## 🚀 Feature Proposal

Show warning (or even pop error) if t function cannot find any matching results.

## Motivation

This is meant to be a developer experience improvement, and it should feel like linters.

For every beginner developers, having a linter and typescript in their project is always a blessing, there's warnings, suggestions, and you really cannot go wrong with things like undefined variables, some libraries not found, ...

Using i18n will make projects a bit more complicated, as a price for what it offers. Taking texts out of contexts (which is what i18n required us to use) is making a pitfall of failure. We define some jsons at `locale` then re-type the keys wrong in our code at `src`, and that's all it takes to create confusion for why this text looks wrong. My proposal is to pop some kind of warnings whenever developer wrongly write a key that i18n cannot recognize (or find) from `locale`. It will reduce the confusions and help avoiding such preventable bugs.

I know that the problem can be solved with "always remember to copy paste your keys instead of re-typing", but copy paste should be an option, not a forced way to not mess up. I also reckon that "just don't type it wrong" is another way, but mistakes are not avoidable, we can only reduce it. In that spirit, this proposal will take part in that effort to try to reduce mistakes.

## Example

Provide a json (`locale/en.json`):
```json
{
  "myText": "myTextIsNice"
}
```

and its usage
```js
const { t } = useTranslation();
// this line is ok
console.log(t("myText"));
// this line should make a warning show
console.log(t("notMyText"));
```

The result will be
```sh
myTextIsCool
notMyText
```

I think it will be better to pop a warning to the developer that "notMyText" doesn't match anything, so that they could decide to "fix" the text or just convert it back to normal texts instead of using i18n unnecessarily.

**Comment by adrai** [comment]
https://www.i18next.com/overview/typescript

**Comment by adrai** [comment]
https://locize.com/blog/i18next-typescript/

**Comment by ngtrthinh169TPC** [comment]
@adrai Thank you, sorry that I couldn't find this earlier. Just another question but with multiple namespace, is there any other way but importing all namespace one by one?

**Comment by adrai** [comment]
check the video: https://youtu.be/GLIas4DH3Ww?si=GekcZAH_DRPk29ox
there's i18next-rousources-for-ts
