### ISSUE TITLE
Is there any way to put translate in constant file

### ISSUE THREAD

**Issue by ducndt** [i18next/react-i18next#1698]
## 🚀 Translate in constant file
I don't know how to translate in constant file
## Motivation

Please outline the motivation for the proposal.

## Example
```
import i18next from 'i18next';

export const PUBLIC_SIDE_BAR = [
  {
    icon: ICONS.iconGame,
    title: i18next.t('test'),
 }
]
```

When i change the language, text don't change. If i put the translation in function component like this, 
`<p>{t('comingSoon')}</p>`
It can translate

Any one can help me

**Comment by jamuhl** [comment]
https://github.com/i18next/react-i18next/issues/1236#issuecomment-762039023

and others....just search outside in issues
