### ISSUE TITLE
shouldUnescape  prop to <Trans> tag doesn't escape all HTML entities

### ISSUE THREAD

**Issue by getsnoopy** [i18next/react-i18next#1701]
## 🐛 Bug Report

It seems like despite specifying the `shouldUnescape` prop to the `<Trans>` tag, it doesn't work with most HTML entities. Upon looking into the source code and some related issues (#1435 and #1560), it seems like it only supports an arbitrary subset of entities, and when it doesn't support the ones I'm using, I have to provide my own `unescape` function to interpret those symbols. This is not at all ideal; the docs make it seem like it will "just work", which is how it should be anyway.

## To Reproduce

The JSX code:
```jsx
<Trans t={t} i18nKey="entity_rich_text" shouldUnescape={true}></Trans>
```
The translation JSON file:
```json
{
    "entity_rich_text": "3 &times; 3 = 9"
}
```

This renders as `3 &times; 3 = 9`.

## Expected behaviour

It should render as `3 × 3 = 9`.

Why doesn't the library just pass through all HTML entities to the browser as-is, and let the browser handle them when the `shouldUnescape` parameter is enabled?

## Your Environment

- *runtime version*: Node `v14.21.3`
- *i18next version*: `15.1.1`
- *os*: Linux

**Comment by adrai** [comment]
shouldUnescape was introduced to only work for specific characters.
If you think that needs to be extended, feel free to provide a PR.
