### ISSUE TITLE
Autocomplete and Validation Not Working with t Function

### ISSUE THREAD

**Issue by sAtluna** [i18next/react-i18next#1702]
## 🐛 Bug Report

I'm facing an issue with the `t` function where it does not provide autocomplete or validation for translation keys. This problem persists both outside and inside React components. Unlike the `<Trans> `component, the `t` function does not perform key validation or offer autocomplete suggestions. I followed the official [documentation](https://react.i18next.com/latest/using-with-hooks).

Worth to mention, `<Trans> `component and `useTranslation()` have the expected behaviour. I just need to use the `t` function outside of a component, thats why I cant use `<Trans> ` or  `useTranslation()`

## To Reproduce

**My i18n configuration: `@/i18n/config`**

```
import generalEN from "@/i18n/en/general.json";
import myPageEN from "@/i18n/en/my-page.json";
import i18next from "i18next";
import { initReactI18next } from "react-i18next";

i18next.use(initReactI18next).init({
  debug: true,
  defaultNS: "general",
  lng: "en",
  resources: {
    en: {
      myPage: myPageEN,
      general: generalEN,
    },
  },
});
```

**Resources configuration in `resources.ts`:**
```

import myPageEN from "../i18n/en/myPage.json";
import generalEN from "../i18n/en/general.json";

const resources = {
  myPage: myPageEN,
  general: generalEN,
} as const;

export default resources;

```

**Usage of the `t` function:**

```
import i18n from '@/i18n/config';

i18n.t('myPage.title');
```

1.     Set up i18next using the configuration provided.
2.     Use the t function in a component or outside, doesn't matter.
3.     Notice that autocomplete and validation for translation keys are not working.

## Expected behavior

I expected the `t` function to provide autocomplete suggestions and key validation, similar to the `<Trans>` component.

`<Trans>` (works):

![Screenshot 2023-12-18 at 08 30 11](https://github.com/i18next/react-i18next/assets/135033966/aca17a6d-6804-4080-8737-0ffe326bdcf6)

`t` (not working):

![Screenshot 2023-12-18 at 08 28 48](https://github.com/i18next/react-i18next/assets/135033966/76cd8bf9-f763-4b27-83a2-794c261b00ed)

## Your Environment

- *runtime version*: node: v20.9.0
- *i18next version*: v13.5.0
- *os*: Mac: 14.1.1

**Comment by adrai** [comment]
Please provide a minimal but complete example repository for reproduction.

**Comment by sAtluna** [comment]
Hello @adrai,

I've just reviewed my code: `t('title', { ns: 'myPage' })`, and it turns out that's the solution I needed. I must have overlooked this in the documentation. I am aware that 'myPage' is set up as a multiple namespace, but <Trans> does work with:

`<Trans i18nKey={'myPage:test'} ></Trans>`

So I was expecting the `t` function to work similarly. However, it's working now 👍.

I will go ahead and close this comment. Thanks!
