### ISSUE TITLE
TypeScript and i18nIsDynamicList Property in Trans Component

### ISSUE THREAD

**Issue by ThomasCode92** [i18next/react-i18next#1703]
## 🐛 Bug Report
I encountered an issue while attempting to use the Trans component with a dynamic list, as documented in the [official documentation](https://react.i18next.com/latest/trans-component).

In my TypeScript project, the following error occurred:
```
Type '{ children: Element[]; i18nIsDynamicList: true; }' is not assignable to type 'DetailedHTMLProps<HTMLAttributes<HTMLUListElement>, HTMLUListElement>'.
  Property 'i18nIsDynamicList' does not exist on type 'DetailedHTMLProps<HTMLAttributes<HTMLUListElement>, HTMLUListElement>'
```

In the console I got the error:
`Warning: Each child in a list should have a unique "key" prop.`

It seems that TypeScript is not recognizing the 'i18nIsDynamicList' property. I seek guidance on how to resolve this issue or implement the functionality correctly.

## To Reproduce
1. Follow the documentation link: [Trans Component Documentation](https://react.i18next.com/latest/trans-component).
2. Implement the Trans component with a dynamic list in a TypeScript project.

```typescript
  <Trans i18nKey="list_map">
    <ul i18nIsDynamicList>
      {actionItems.map(actionItem => (
        <li>{actionItem}</li>
        ))}
     </ul>
   </Trans>
```

## Actual behavior
The TypeScript compiler reports an error, indicating that 'i18nIsDynamicList' is not recognized.

## Expected behavior
The TypeScript compiler should recognize the 'i18nIsDynamicList' property without errors and console error should go away.

## Your Environment
- *runtime version*: node v20.10.0
- *i18next version*: 12.2.2
- *TypeScript version*: 5.3.2
- *os*: WSL2

## Question:
How can I resolve this TypeScript error, or what is the correct way to implement the 'i18nIsDynamicList' functionality in a TypeScript project?

Thank you for your assistance!

**Comment by adrai** [comment]
You need a custom ul type element... something like:

```tsx
interface MyUlProps extends React.DetailedHTMLProps<React.HTMLAttributes<HTMLUListElement>, HTMLUListElement> {
  i18nIsDynamicList?: boolean;
}

const MyUl: React.FC<MyUlProps> = ({ children, ...props }) => {
  return (
    <ul {...props}>
      {children}
    </ul>
  )
}

// ...

      <Trans i18nKey="list_map">
        <MyUl i18nIsDynamicList>
          {actionItems.map((actionItem, i) => (
            <li key={i}>{actionItem}</li>
          ))}
        </MyUl>
      </Trans>
```
