### ISSUE TITLE
Change language after mount does not re-render components

### ISSUE THREAD

**Issue by woochanleee** [i18next/react-i18next#1705]
## 🐛 Bug Report

Change language after mount does not re-render components.

https://github.com/i18next/react-i18next/assets/48552260/ff12f3ae-54dc-41e4-a265-78298b6c0730

## To Reproduce

[CSB](https://codesandbox.io/p/sandbox/change-language-after-mount-does-not-re-render-components-react-i18next-dx4n7p)

## Expected behavior

Change language after mount re-render components.

## Your Environment

- *i18next version*: 23.7.11
- *os*: Mac

**Comment by adrai** [comment]
Why are you doing that changeLanguage there in the useEffect?
Here a version that works: [CSB](https://codesandbox.io/p/sandbox/change-language-after-mount-does-not-re-render-components-react-i18next-dx4n7p?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqns3m4r00063b6hubh6fzfy%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqns3m4r00023b6h8rv09c5s%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqns3m4r00033b6hbedc7evn%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqns3m4r00053b6h1g9z4yq8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqns3m4r00023b6h8rv09c5s%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqns3m4r00013b6hr5oqo689%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%257D%255D%252C%2522id%2522%253A%2522clqns3m4r00023b6h8rv09c5s%2522%252C%2522activeTabId%2522%253A%2522clqns3m4r00013b6hr5oqo689%2522%257D%252C%2522clqns3m4r00053b6h1g9z4yq8%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqns3m4r00043b6hbvvnlwj7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqns3m4r00053b6h1g9z4yq8%2522%252C%2522activeTabId%2522%253A%2522clqns3m4r00043b6hbvvnlwj7%2522%257D%252C%2522clqns3m4r00033b6hbedc7evn%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqns3m4r00033b6hbedc7evn%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by woochanleee** [comment]
Thanks. In my case, initialize locale from cookie.

Instead `useEffect`, adjust the state directly during rendering is better?

```tsx
function Foo ({ language }) {
  const { i18n } = useTranslation();

  if (language === i8n.language) {
    i18n.changeLanguage(language);
  }

  return ...
}
```

**Comment by adrai** [comment]
Use a languageDetector plugin like https://github.com/i18next/i18next-browser-languageDetector or create your own: https://www.i18next.com/misc/creating-own-plugins#languagedetector

**Comment by woochanleee** [comment]
Good idea.

The part I thought was a bug, I understood why. Because `boundReset` registration for the 'languageChanged' event in `useTranslation` is in useEffect.

So in my [CSB example](https://codesandbox.io/p/sandbox/change-language-after-mount-does-not-re-render-components-react-i18next-dx4n7p), `languageChange` inside the `useEffect` was executed before the useTranslation's useEffect, so it's not reflected in the UI.

https://github.com/i18next/react-i18next/assets/48552260/083f267d-e461-4b5b-ae80-acbaee1112c4

This is [Resolved CSB example](https://codesandbox.io/p/sandbox/resolved-change-language-after-mount-does-not-re-render-components-z9t9hq?file=%2Fsrc%2Fapp.js).


https://github.com/i18next/react-i18next/assets/48552260/4ea213a0-6cdf-4532-856f-c26dcba5c1f5
