### ISSUE TITLE
Error: async/await is not yet supported in Client Components, only Server Components when translating parent client component and child server component in Next.js.

### ISSUE THREAD

**Issue by tomgwasira** [i18next/react-i18next#1706]
## 🐛 Bug Report
I am using Next.js and have configured i18next exactly as discussed in [this article](https://locize.com/blog/next-app-dir-i18n/).

However, I receive the error 'Error: async/await is not yet supported in Client Components, only Server Components. This error is often caused by accidentally adding `'use client'` to a module that was originally written for the server' when trying to translate a parent client component and a child server component. I have passed a server component to a client component correctly as discussed in the [Next.js documentation](https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#supported-pattern-passing-server-components-to-client-components-as-props). Is the desired behaviour not possible or have I missed something? (See code snippets below for further details).

## To Reproduce
Removing translation in `page.tsx` resolves the error, but I would like to carry out translations here as well.
```tsx
// page.tsx
'use client';

import React from 'react';

import { useTranslation } from '@/app/i18n/client';

import ClientComponent from './ClientComponent';
import ServerComponent from './ServerComponent';

export default function MyApp({ params: { lng } }) {
  const { t } = useTranslation(lng);

  return (
    <>
      {t('app_title')}
      <ClientComponent lng={lng}>
        <ServerComponent lng={lng} />
      </ClientComponent>
    </>
  );
}
```

```tsx
// ClientComponent.tsx
'use client';

import React from 'react';

import { useTranslation } from '@/app/i18n/client';

export default function ClientComponent({ lng, children }) {
  const { t } = useTranslation(lng);

  return (
    <>
      <h1>{t('client_component_title')}</h1>
      {children}
    </>
  );
}
```

```tsx
// ServerComponent.tsx
import React from 'react';

import { useTranslation } from '@/app/i18n';

export default async function ServerComponent({ lng }) {
  const { t } = await useTranslation(lng);

  return (
    <>
      <h2>{t('server_component_title')}</h2>
      <p>Hello world</p>
    </>
  );
}
```

## Expected behavior
Translations should occur for parent element and children without error.

## Your Environment
next v14.0.3
i18next v23.7.11

**Comment by adrai** [comment]
You need to create something similar to this Footer component: https://github.com/i18next/next-app-dir-i18next-example/tree/main/app/%5Blng%5D/components/Footer

**Comment by adrai** [comment]
basically, pass the t function down to the Server and or the Client component so you don't need to call useTranslation in those components

**Comment by tomgwasira** [comment]
Awesome. Thanks Adriano. So, just to clarify, it doesn't matter that I'm passing `t` created from a client component into a server component and vice versa? It seems to work alright.

And also, when do we use `useTranslation` in a child component and when do we pass `t` to the child as a prop. In the [Footer example](https://locize.com/blog/next-app-dir-i18n/),  `app/[lng]/client-page/page.js` does not pass `t` to the child component `Footer`; instead, `Footer` calls `useTranslation`.

Thanks again.

**Comment by adrai** [comment]
the t function can be passed to any component... that should never be a problem...
The Footer example is a little bit different than your example... it has a FooterBase component (receiving the t function via prop), used by the Footer component of the client or used by the Footer component of the server. => so the useTranslation call is always specific to the environment (client or server), and the t function can be passed to whatever component you like

**Comment by tomgwasira** [comment]
I see. Thanks so much for the help!

**Comment by tomgwasira** [comment]
Currently passing `lng` and calling `useTranslation` in the child when the parent is a server component and the child is a client component because of error: 'Functions cannot be passed to Client components`. For everything else, I pass the `t` function down. I would like to believe React will work on making this possible in the future.
