### ISSUE TITLE
Importing i18n file or using it in I18NextProvider in react native causes error

### ISSUE THREAD

**Issue by mstaniewski** [i18next/react-i18next#1709]
## 🐛 Bug Report

After setting up a fresh react native project (cli not expo) and following getting started guide, react native app throws an error:
![Screenshot 2024-01-03 at 13 42 04](https://github.com/i18next/react-i18next/assets/11744682/29486990-6425-4ad3-9a05-7048b58042a8)

## To Reproduce
https://github.com/mstaniewski/intl-bug

## Expected behavior

react-i18next should work with react native 

## Your Environment

- *runtime version*: 18.17.1
- *i18next version*: 23.7.15
- *os*: Mac
- react native 0.73.1

**Comment by adrai** [comment]
currently afk, but yesterday I just created a similar example for react-native: https://github.com/i18next/react-i18next/tree/master/example/ReactNativeLocizeProject
Can you compare it with that one?

**Comment by adrai** [comment]
Here another example without locize usage: https://github.com/i18next/react-i18next/tree/master/example/ReactNativeProject

**Comment by mstaniewski** [comment]
@adrai maybe I'm missing something, but I have moved 1:1 configs from these repositories, cleared cache and rebuilt an app. The buffer size error remains

**Comment by adrai** [comment]
usually the buffer size error occurs when trying to dynamically import a file etc...
I think this is not really related to i18next

**Comment by mstaniewski** [comment]
@adrai could you check the repository I have linked? It's bare react native starter from cli and i18n configured. Maybe i have oversighted somethig?

**Comment by adrai** [comment]
Yes, I was not able to build it... the ios build fails because of some missing header files

**Comment by adrai** [comment]
I might know why your repo example has problems...
Try to correctly define the content of this json file: https://github.com/mstaniewski/intl-bug/blob/master/locales/en/common.json

for example with something like this:

```json
{
  "next": "Next"
}

```

**Comment by mstaniewski** [comment]
@adrai thanks for this one! such a stupid problem 🙄

**Comment by adrai** [comment]
did that fix it?
if so, can we close this issue?

**Comment by mstaniewski** [comment]
> did that fix it?
> if so, can we close this issue?

Yes, it did. Thanks!
