### ISSUE TITLE
Utility to find unused translation strings

### ISSUE THREAD

**Issue by DBCintron** [i18next/react-i18next#1712]
## 🚀 Feature Proposal

Utility that can be run to find translation seeds that are unused in project outside of their definition.

## Motivation

After a couple of years of using react-i18next, our team has built up a backlog of translation seeds/strings that aren't in use. There's generally hesitancy to remove any without being careful as it could result in a broken one. So it becomes a bit overblown after awhile. 

## Example

Script or cli or linter rule, etc.

Would find that I'm never using `foo` as a keyPrefix so it recommends removing, or that I'm never using the translation string `foo.bar` anywhere so it should be removed.

**Comment by adrai** [comment]
Maybe i18next-scanner or i18next-parser could help... (you might check those projects)

Alternatively there is: https://docs.locize.com/guides-tips-and-tricks/unused-translations

**Comment by DBCintron** [comment]
https://www.npmjs.com/package/i18n-unused
