### ISSUE TITLE
String cutoff from the middle

### ISSUE THREAD

**Issue by lhypds** [i18next/react-i18next#1714]
## 🐛 Bug Report

The string fullscreen... cutoff from the middle, for string:

![image](https://github.com/i18next/react-i18next/assets/4526937/dfe92060-cd4d-4870-bba1-fa25b6afe06d)

All other string is fine, except this one

![image](https://github.com/i18next/react-i18next/assets/4526937/2cd2bb51-017e-4c69-9938-86f54201a99c)

** But not for:

![image](https://github.com/i18next/react-i18next/assets/4526937/03b29920-84df-41a0-8d9a-02a67f24a22b)

## To Reproduce

You can use a JSON file, like `translate.json`, use above screenshot as key, and try switch to another language.

```js
const { t } = useTranslation("documentation");

...

const shortcuts = [

...
{ action: t("Stop generating. (`:stop`)"), shortcut: "⌃C", condition: t("Generating.") },
    { action: t("Clear output. (`:clear`)"), shortcut: "⌃R", condition: t("Has output.") },
    { action: t("Clear output and reset session. (`:reset`)"), shortcut: "⇧⌃R", condition: "-" },
->  { action: t("Fullscreen. (`:fullscreen [off?]`)"), shortcut: "F11(*)", condition: "-" },
    { action: t("Split screen. (`:fullscreen split`)"), shortcut: "⌃|", condition: "-" },
    { action: t("Clear the input."), shortcut: "ESC", condition: t("Focused on the input area. Input area not empty.") },
    { action: t("Unfocus from the input box."), shortcut: "ESC", condition: t("Focused on the input area. Input area is empty/cleared.") },
    { action: t("Repeat last input."), shortcut: "Tab", condition: t("Focused on the input area. Input area is empty/cleared.") },
    { action: t("Command autocomplete."), shortcut: "Tab", condition: t("Focused on the input area. Input commands `:use`, `:function use`, `:role use`, `:store use`, `:node use`, `:theme`, `:lang use`, `:user set` and type the starts characters of the value.") },
...

```

In Json file I have

```
   "Has output.": "Has output.",
   "Clear output and reset session. (`:reset`)": "Clear output and reset session. (`:reset`)",
-> "Fullscreen. (`:fullscreen [off?]`)": "Fullscreen. (`:fullscreen [off?]`)",
  " Split screen. (`:fullscreen split`)": "Split screen. (`:fullscreen split`)",
   "Clear the input.": "Clear the input.",
```

![image](https://github.com/i18next/react-i18next/assets/4526937/efd2ba75-ca98-43ec-beee-ef96534aaf31)

## Expected behavior

Except this string to be shown properly.

## Your Environment

- *runtime version*: i.e. node v21.5.0, browser Firefox
- *i18next version*: 
    "i18next": "^23.7.18",
    "i18next-browser-languagedetector": "^7.2.0",
    "i18next-http-backend": "^2.4.2",
    "react-i18next": "^14.0.1",
- *os*: Windows

**Comment by lhypds** [comment]
@adrai Thank you for your prompt reply.



I've just created below minimal reproducible repo:
https://github.com/lhypds/i18n-app-reproduce

The code is in App.js.

As you can see, the string 

Fullscreen. (`:fullscreen [off?]`)

and

Clear output and reset session. (`:reset`)

They both contains: . (`:

However the Fullscreenxxx is cutoff from the middle, that's why I feel strange here.

Kindly have a look, thank you.

![image](https://github.com/i18next/react-i18next/assets/4526937/aa691931-800d-4ec2-95e9-0845ebf8f243)

**Comment by adrai** [comment]
like already assumed in my last comment... you need to set the keySeparator (and probably also the namespace separator to false):

<img width="273" alt="image" src="https://github.com/i18next/react-i18next/assets/1086194/0e167cd2-2024-4079-bcc9-1e6092a3eee4">
<img width="489" alt="image" src="https://github.com/i18next/react-i18next/assets/1086194/6f7db671-e159-490f-b103-6a74d8be7f34">

**Comment by lhypds** [comment]
@adrai Thank you, very clear!
