### ISSUE TITLE
Type instantiation is excessively deep and possibly infinite.

### ISSUE THREAD

**Issue by pavanjoshi914** [i18next/react-i18next#1715]
## 💥 Regression Report
i have chrome extension written in react with react-i18next used for translations when for the resuable component i think 4 level nesting is throwing error
```
Type instantiation is excessively deep and possibly infinite.
```

```
PasswordForm component: 
 const { t } = useTranslation("translation", {
    keyPrefix: i18nKeyPrefix,
  });


<TextField
          autoFocus={autoFocus}
          id="password"
          label={t("choose_password.label")}
 		 .....  
        />
```

reusable component PasswordForm called through some other component
```
<PasswordForm
              i18nKeyPrefix="welcome.set_password"
              formData={formData}
              setFormData={setFormData}
            />
```

so the final translation is welcome.set_password.choose_password.label

config::

```
import { defaultNS, resources } from "./i18n/i18nConfig";

declare module "i18next" {
  interface CustomTypeOptions {
    defaultNS: typeof defaultNS;
    resources: (typeof resources)["en"];
  }
}

```

## Last working version

Worked up to version: v12

Stopped working in version: v13 and onwards

## To Reproduce

```js
// Paste your code here
```

## Expected behavior

```js
// Paste the results here
```

## Your Environment

- *runtime version*: i.e. node v14, deno, browser xy
- *i18next version*: 23.8.2
- react-i18next version: 14.0.1
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by adrai** [comment]
Please provide a minimal reproducible example... not just code snippets.

**Comment by adrai** [comment]
https://www.i18next.com/overview/typescript#type-error-excessively-deep-and-possibly-infinite
https://github.com/i18next/react-i18next/issues/1417
https://github.com/i18next/react-i18next/issues/1601

**Comment by pavanjoshi914** [comment]
what is the different between ```declare module "react-i18next"``` and declare module "i18next"

**Comment by adrai** [comment]
declare module "react-i18next" is for the old version...
You probably don't see errors with that because there is also no type safety

**Comment by jbarop** [comment]
I just had a very strange case.

I had the `i18next.d.ts` in the `/@types/` directory and was struggling with the TS2589 error. After I moved the file to `./` it suddenly worked.
