### ISSUE TITLE
Changing the language doesn't change the text in react native

### ISSUE THREAD

**Issue by gsk143** [i18next/react-i18next#1718]
## 🐛 Bug Report

Changing the language doesn't change the text in react native

## To Reproduce
I have created a bare RN app and tried following the steps in example folder. For ease I have added an attachment
## Expected behavior
Change in language should change the text 

## Your Environment

- *runtime version*: i.e. node v20.11.0
- *i18next version*: i.e. 23.8.2
- *os*: Mac
- *Android Emulator API  - 33*
[LanguageChange.zip](https://github.com/i18next/react-i18next/files/14161872/LanguageChange.zip)

I am new to RN so any help is appreciated

**Comment by jaredhan418** [comment]
Not your fault. This [PR](https://github.com/i18next/react-i18next/pull/1716) brings this issue.

**Comment by adrai** [comment]
yes, try v14.0.1

**Comment by gsk143** [comment]
Yep that fixed it. Thanks

**Comment by adrai** [comment]
reverted with v14.0.3 and waiting for a better fix

**Comment by adrai** [comment]
please try also v14.0.5
