### ISSUE TITLE
Interpolation of the `count` prop doesn't work correctly in the Trans component

### ISSUE THREAD

**Issue by timwest612** [i18next/react-i18next#1719]
## 🐛 Bug Report

When passing the `count` prop to a Trans component (with no values prop) the interpolation prefix/suffix change from the default to `#$?` & `?$#`

Including an empty values object in the Trans prop makes it work fine (shown in the example).
I'm trying to pinpoint exactly in which version this broke as I noticed it when running a host of upgrades. I'll keep digging but thought I'd put this ticket up sooner rather than later in case it's an obvious fix that I'm missing!

I think it is a similar issue this? https://github.com/i18next/react-i18next/issues/1685

## To Reproduce
A [Link to codesandbox](https://codesandbox.io/p/sandbox/blissful-jennings-yzwlm7?file=%2Fsrc%2Fapp.js%3A14%2C22)

## Expected behavior

The interpolation for count passed directly as props should be the same as the rest of the i18next behaviour

**Comment by adrai** [comment]
v14.0.4 should address this

**Comment by timwest612** [comment]
@adrai Amazing! Thanks so much, updated and all looks good 👌
