### ISSUE TITLE
Subscribe to onLanguageChange event?

### ISSUE THREAD

**Issue by melloware** [i18next/react-i18next#1721]
## 🚀 Feature Proposal

I work on [PrimeReact](https://primereact.org/installation/) library and it has its own management of locale's for loading its locale aware features of the library: https://primereact.org/configuration/#Locale

We would a way of subscribing to when a language is changed we can execute some code.  So for example if the browser language is detected and `react-il8next` changes languages how can we subscribe to that event?

## Motivation

We had a bug report from our user: https://github.com/primefaces/primereact/issues/5819 who use react-il8next and needs to basically change the language when it changes in react-il8next

## Example

Right now PrimeReact stores their current locale in a context and can be set with `context.setLocale(lng)`.

```js
const LoginPage = () => {
	// global hooks
	const { t, i18n } = useTranslation();
	const context = React.useContext(PrimeReactContext);


        const changeLanguage = (lng: string) => {
	    i18n.changeLanguage(lng);
	    context && context.setLocale(lng);
        };
```

So I can do it `manually` but i would like a hook to be able to call my `context.setLocale(lng)` whenever `react-il8next` changes the language.

**Comment by jamuhl** [comment]
https://www.i18next.com/overview/api#onlanguagechanged

**Comment by melloware** [comment]
Thanks!
