### ISSUE TITLE
`context` values resolved differently (and incorrectly) between `<Trans />` and `t(...)`

### ISSUE THREAD

**Issue by stefan-schweiger** [i18next/react-i18next#1730]
## 🐛 Bug Report

`<Trans />` and `t(...)` don't throw the same type errors when used with different context edge cases. But besides being inconsistent both `<Trans />` and `t(...)` don't correctly interfere if the context is ok or not.

## To Reproduce

https://stackblitz.com/edit/vitejs-vite-pabdwy?file=src%2FApp.tsx&terminal=dev

```json
{
  "testContext1": "EN: {{context}}",
  "testContext1_Test1": "EN: Context1 Test1",
  "testContext1_Test2": "EN: Context1 Test2",
  "testContext2_Test1": "EN: Context2 Test1",
  "testContext2_Test2": "EN: Context2 Test2"
}
```

```tsx
// WRONG: type error but SHOULD work
// Type '{ context: "asdf"; }' is not assignable to type 'string'
{t('testContext1', { context: 'asdf' })}
// OK: works
<Trans t={t} i18nKey="testContext1" context={'asdf'} />
// OK: works
<Trans t={t} i18nKey="testContext1" values={{ context: 'asdf' }} />

// OK: type error
// Type '{ context: "asdf"; }' is not assignable to type 'string'
{t('testContext2', { context: 'asdf' })}
// OK: type error
// Type '"testContext2"' is not assignable to type '"testContext2_Test1" | ...
<Trans t={t} i18nKey="testContext2" context={'asdf'} />
// OK: type error
// Type '"testContext2"' is not assignable to type '"testContext2_Test1" | ...
<Trans t={t} i18nKey="testContext2" values={{ context: 'asdf' }} />

// OK: works
{t('testContext2', { context: 'Test1' })}
// WRONG: type error but SHOULD work
// Type '"testContext2"' is not assignable to type '"testContext2_Test1" | ...
<Trans t={t} i18nKey="testContext2" context={'Test1'} />
// WRONG: type error but SHOULD work
// Type '"testContext2"' is not assignable to type '"testContext2_Test1" | ...
<Trans t={t} i18nKey="testContext2" values={{ context: 'Test1' }} />
```

## Expected behavior

See output above.

**Comment by marcalexiei** [comment]
> // WRONG: type error but SHOULD work
> // Type '{ context: "asdf"; }' is not assignable to type 'string'
> {t('testContext1', { context: 'asdf' })}


Right now `i18next` context validation requires to pass a valid context  which means that context must have `'Test1' | 'Test2'` type if provided.

If you need to access default value do not provide context parameter 
(or if context parameter is not valid on runtime it will fallback to the "default" context value)

<img width="508" alt="image" src="https://github.com/i18next/react-i18next/assets/24919330/a3cd1b19-a2ca-43d9-a425-9029bcd35236">

----

I'm not familiar with the types of `react-i18next` so far but after a quick look I can see that  `<Trans />` `values` and `context`  props are not typed with "strict" types as you can see here:

https://github.com/i18next/react-i18next/blob/bb29742b09ab09cb48badbc175a01b8f698d26b9/TransWithoutContext.d.ts#L17

and here

https://github.com/i18next/react-i18next/blob/bb29742b09ab09cb48badbc175a01b8f698d26b9/TransWithoutContext.d.ts#L24

Have them work properly it's not trivial as far as I can tell now 😔.
I'll try to make a PR in the upcoming days but if anyone wants to try a fix feel free to open a PR.

**Comment by stefan-schweiger** [comment]
But what if I want/need to provide a "unknown" context? For example imagine translating a long list of potential errors for which you get an error code from the backend. You have a somewhat good idea what the codes will be and you want to display them in the same location. But if you encounter a unknown error you want to fall back to the "generic" context.

```json
{
   "error": "Unknown error, with error code {{context}}. Please contact support.",
   "error_NotFound": "The resource you are looking for could not be found.",
   "error_Disabled": "Can't edit the resource because it's disabled.",
   // ...
}
```

```tsx
const Error = ({ errorCode }) => {
    const { t } = useTranslation();
    
    return <span>{t('error', { context: errorCode })}</span>
}
```

I know that you can try to workaround this issue in different ways, but in theory this is already supported by i18next, just not reflected in the typings.

Do you see any way of getting such cases handled correctly depending on if a key without a context exists or not?

If that is not possible what do you think about having at least an additional `TypeOption` like `typedContext` (or whatever makes sense) which if set to false in the `CustomTypeOptions` would ignore the context for the typings? I know that the implications are that if you don't have a "fallback" it will just display the key, but at least the type errors would be consistent.
