### ISSUE TITLE
i18n.changeLanguage dont work if we setup our app using SSR razzle example in react-i18next

### ISSUE THREAD

**Issue by Tarunmeena0901** [i18next/react-i18next#1737]
## 🐛 Bug Report

**A clear and concise description of what the bug is.**
i18n.changeLanguage dont work if we setup our app using SSR razzle example in react-i18next

## To Reproduce
setup the razzle app example in react-18next and add a langauge switcher in the home page 

### **My code**

```js
renderContent() {
		const { t , i18n} = this.props;
		const lngs = {
			en: { nativeName: 'English' },
			es: { nativeName: 'Spanish' }
		};
		return (
			<Container>
				<Row>
					<Col lg={{offset: 2, span: 8}}>
						<h1 className="text-center">The Open Book Database</h1>
						<p className="lead text-justify">
							{t('home.home_about')}
						</p>
					</Col>
					<Col>
            			{Object.keys(lngs).map((lng) => (
            			    <button key={lng} style={{ fontWeight: i18n.resolvedLanguage === lng ? 'bold' : 'normal' }} type="submit" 
                                          onClick={() => i18n.changeLanguage(lng)}>
            			        {lngs[lng].nativeName}
            			    </button>
            			))}
        			</Col>
				</Row>
```
i am using the withTranslation() with the class component everything else done is same as the example provide in link
**the t function works fine but the language changer is not working**

**Comment by adrai** [comment]
please provide a minimal but complete example repository, not just code snippets...

**Comment by Tarunmeena0901** [comment]
Hi , i am sorry but i implemented this in an organization code so i can not make a new repo for it, everything is working fine except the language changer
in this repo you can find all the relevant files . Thanks

[GITHUB LINK](https://github.com/Tarunmeena0901/SSR-I18next)

**Comment by adrai** [comment]
Sorry, but I need something to reproduce this...
Can you adapt this example so this can be reproduced?
https://github.com/i18next/react-i18next/tree/master/example/razzle-ssr

**Comment by Tarunmeena0901** [comment]
I am so sorry to say this but i am not able to find any time to create a repository adapting a example but i found out something weird happening with my setup and this not the issue with react-i18next so i think we can close this issue

**Comment by Tarunmeena0901** [comment]
by the way it would we be a great help  if anyone can give me any idea of what is wrong here .... as soon i import ../../i18n here
my frontend buttons stop working rest all is working fine . anything related to webpack ? I trying to setup i18n with SSR in react

![Screenshot 2024-03-21 022903](https://github.com/i18next/react-i18next/assets/97682967/151823cf-aeca-4a27-b42d-444e020936b8)
