### ISSUE TITLE
Client translation in NextJS 14 breaks React hooks rules

### ISSUE THREAD

**Issue by OlegGulevskyy** [i18next/react-i18next#1738]
## 🐛 Bug Report

Server side translation seems to work fine.
But if I  import `t` in any `use client` component, from `useTranslation`, I get invalid use of react hooks error:
![image](https://github.com/i18next/react-i18next/assets/43781031/dc1e6d9c-929d-481c-9011-6bbfe48ac40f)

The error above on the screenshot happens if I just log the result of `t("slogan")` into the console.
If I try to use translation in my DOM, I get the following error:
![image](https://github.com/i18next/react-i18next/assets/43781031/77cbf7f1-b163-4b88-ba98-191612935dc1)

I guess I get the fact that string `slogan` does not match the actual translation string when it lands on hydrated client, and I can see a flicker of the translation, but I am not sure how to fix the errors and what is most importantly how to approach this correctly.

I also get a log in the console:
```
react-i18next:: You will need to pass in an i18next instance by using initReactI18next
```

I have the same problem in my prod application, and I am not sure how to use client side transaltion without any errors.

You should be able (hopefully..) to reproduce with this minimal repo.
https://github.com/OlegGulevskyy/translations-repro

## Your Environment

- *runtime version*: NextJS 14
- *i18next version*: 23.10.1
- *os*: Mac

For some reason, you can notice, that usage of client side translation in a client component "Button" does not bring issues, that works fine. The problems start as on the level higher, when I use translations in `MainLayout` whic his a client side component also, so I don't expect it to have problems just like the button.

**Comment by adrai** [comment]
Please follow this guide for NextJs with app router setup: https://locize.com/blog/next-app-dir-i18n/
code: https://github.com/i18next/next-app-dir-i18next-example

**Comment by OlegGulevskyy** [comment]
Thanks, I was following outdated guides

**Comment by wiktoriavh** [comment]
> Please follow this guide for NextJs with app router setup: https://locize.com/blog/next-app-dir-i18n/ code: https://github.com/i18next/next-app-dir-i18next-example

1. The code example is breaking the rule of hooks with the if statements. Is there some other way I didn't see?
2. With the way it was set up, I also either need to know what the locale is in any component I am in, or keep passing it around through the props. I would like to not do that and the hook to know which locale I am in. I was not successful in finding a solution to this yet.
