### ISSUE TITLE
Argument of getFixedT is ignored

### ISSUE THREAD

**Issue by docu-bill** [i18next/react-i18next#1739]
## 🐛 Bug Report

The getFixedT functions in i18next and in useTranslation() are not effected by the first argument that selects the language. The language (of the TFunction returned) seems to be the currently detected language. 

## To Reproduce

You can see the behaviour in this [Codesandbox](https://codesandbox.io/p/sandbox/fervent-galileo-98k7ks)

My current work around is to change the language, get the fixed TFunction and change the language back. Is this how it should be used?

This does not work
```
const { i18n } = useTranslation()
const newDocT = i18n.getFixedT(lng)  // Some other language than i18next.language
// const newDocT = i18next.getFixedT(lng) does not work either
console.log("Checking doc language: " + lng + " - " + newDocT("keyToBeTranslated"))
```
By does not work, I mean that the translation displayed in the console is of the current language.

This does work:
```
if (lng != i18next.language) {
  const oldLanguage = i18next.language
  i18next.changeLanguage(lng).then(() =>{
    const newDocT = i18n.getFixedT(lng)
    console.log("Checking doc language: " + lng + " - " + newDocT("keyToBeTranslated"))
    i18next.changeLanguage(oldLanguage)
  })
  .catch((err: unknown) => {
    if (err instanceof Error) console.error("Error changing language: " + err.message) 
  })
}
```
## Expected behavior

I am sure I could be doing something incorrect, but expect to get the language that I ask for or throw an error... not just get the current language.

## Your Environment

- *runtime version*: i.e. node v18, 
- chrome (Version 123.0.6312.58)
- i18next: "^23.10.1",
- i18next-browser-languagedetector: "^7.2.0",
- i18next-http-backend: "^2.5.0",
- react-i18next: "^14.1.0",

- *os*: Windows
- *any other relevant information*

**Comment by jamuhl** [comment]
your `fr` language is not loaded therefore it shows fallback...(you have to assert it's loaded...)

add `    preload: ["fr"],` to your init to preload it...https://www.i18next.com/overview/configuration-options#languages-namespaces-resources

**Comment by docu-bill** [comment]
Thanks @jamuhl  Preloading in the init is not really convenient as I would have to preload all possible languages.  My app is a client side app and will use two possible languages... one that comes from outside the users browser and the browser language. I cannot know before the app loads either of the two languages.

Is there a way to manually load a language? Or is my current work around (changing the language and back) the best way to getFixedT of an un-preloaded language. Cheers

**Comment by jamuhl** [comment]
https://www.i18next.com/overview/api#loadlanguages

and I guess you can use https://www.i18next.com/overview/api#hasresourcebundle to check for loaded (eg. building your own useTranslation for the different language)

or better use: https://github.com/i18next/react-i18next/issues/1637 which (@adrai) is currently not documented

**Comment by adrai** [comment]
fyi: the lng prop via useTranslation hook will not load additional the language, it will only return the "appropriate" t function bound to that language

**Comment by docu-bill** [comment]
@adrai @jamuhl 
This seems to work. Is this what you meant?
```
if (!i18n.hasResourceBundle(lng, "translation")){
    i18n.loadLanguages(lng, (err: unknown) => {
        if (err instanceof Error) {
            console.error("Error loading language: " + err.message)
        } else {
            const newDocT = i18n.getFixedT(lng)
            //.... use newDocT
        }
    })
} else {
    const newDocT = i18n.getFixedT(lng)
    //.... use newDocT
}
```
The way I use it is by setting it to a state variable:
const [ myFixtT, setMyFixedT] = React.useState<TFunction | undefined>()
setMyFixedT(() => newDocT)

**Comment by adrai** [comment]
Did the useTranslation hook not work?

`const { t } = useTranslation('trandlation', { lng })`

**Comment by docu-bill** [comment]
Not sure I understand
>fyi: the lng prop via useTranslation hook will not load the additional language, it will only return the "appropriate" t function >bound to that language

You said it would not load the language.  I dont want to preload in the init. I just want a TFunction I can cache.  This language is fixed and specified by external data, not by the user or the browser.

**Comment by adrai** [comment]
Seems I was wrong... it loads the language... can you try that?

**Comment by docu-bill** [comment]
I need to do this inside a React.useEffect... useTranslate is throwing an error because it is a Hook inside a Hook... Well that is what I think is happening.

**Comment by jamuhl** [comment]
useTranslation is a hook...no need to run it inside useEffect

**Comment by docu-bill** [comment]
I need to run it inside useEffect as I dont know what language to set it to in the initial load ... I get the fixed language from the server and then set it.

**Comment by docu-bill** [comment]
I moved it into its own empty div rendering component so it could use the language  as a property. useTranslation works there. 
Thanks.
