### ISSUE TITLE
Typescript error: Context is not assignable to type 'string'

### ISSUE THREAD

**Issue by VasilNikolov** [i18next/react-i18next#1742]
## 🐛 Bug Report

The issue is that we are having the following error when using context in a typescript project.

Type '{ context: "Example"; }' is not assignable to type 'string'.

![image](https://github.com/i18next/react-i18next/assets/16212892/2bd6a853-601e-43de-a714-ae60de33134e)

## To Reproduce

A [minimal reproducible example](https://stackblitz.com/edit/vitejs-vite-jb61lw?file=src%2FApp.tsx).

```js
// Paste your code here
```

## Expected behavior

```js
// Paste the expected results here
```

## Your Environment

- *runtime version*: i.e. node v14, deno, browser xy
- *i18next version*: i.e. 19.5.3
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by stefan-schweiger** [comment]
@VasilNikolov I had a similar issue some time ago https://github.com/i18next/react-i18next/issues/1730#issuecomment-1981535589 and one of the answers was that context is really only meant for known values and that there are other fallback mechanisms. I don't think even today that I fully agree with that but I have changed my code accordingly..

**Comment by VasilNikolov** [comment]
> @VasilNikolov I had a similar issue some time ago and [one of the answers](https://github.com/i18next/react-i18next/issues/1730#issuecomment-1981535589) was that context is really only meant for known values and that there are other fallback mechanisms. I don't think even today that I fully agree with that but I have changed my code accordingly..

And what are considered known values?

**Comment by stefan-schweiger** [comment]
Everything specified in your translation file as possible context values.

**Comment by marcalexiei** [comment]
Like @stefan-schweiger  pointed out, you have to specify all possible values for the context value:

`asdf` is not present in your translation keys. 
If you have `asdf` as possible context value it should be specified in translation resources:
```text
//...
testContext1: 'EN: {{context}}',
testContext1_Test1: 'EN: Context1 Test1',
testContext1_Test2: 'EN: Context1 Test2',
testContext1_asdf: 'EN: Context1 asdf', // ⬅️⬅️⬅️⬅️
// ...
```

**Comment by VasilNikolov** [comment]
> Like @stefan-schweiger pointed out, you have to specify all possible values for the context value:
> 
> `asdf` is not present in your translation keys. If you have `asdf` as possible context value it should be specified in translation resources:
> 
> ```
> //...
> testContext1: 'EN: {{context}}',
> testContext1_Test1: 'EN: Context1 Test1',
> testContext1_Test2: 'EN: Context1 Test2',
> testContext1_asdf: 'EN: Context1 asdf', // ⬅️⬅️⬅️⬅️
> // ...
> ```

Yes, but when you introduce a json store for the translations it again throws the errors.
[Example](https://stackblitz.com/edit/vitejs-vite-jb61lw?file=src%2FApp.tsx)
