### ISSUE TITLE
Not existing context not detected as type error if covered by string union

### ISSUE THREAD

**Issue by stefan-schweiger** [i18next/react-i18next#1743]
## 🐛 Bug Report

When you use a string union as the context parameter it's possible to supply values for which a context does not exist and it does not result in an error. If you just use the plain string value or a const it works.

## To Reproduce

A [minimal reproducible example](https://stackblitz.com/edit/vitejs-vite-yxak5c?file=src%2FApp.tsx,src%2Fi18n.ts&terminal=dev).

```json
{
  "translation": {
    "testContext1_Test1": "EN: Context1 Test1",
    "testContext1_Test2": "EN: Context1 Test2",
  },
}
```

```js
const App = () => {
  const { t } = useTranslation('translation');

  return (
    <div>
      <p>
        {t('testContext1', { context: 'Test1' as 'Test1' | 'Test2' | 'Test3' })}
      </p>
      <p>{t('testContext1', { context: 'Test2' })}</p>
      <p>{t('testContext1', { context: 'Test2' as const })}</p>
      <p>
        {t('testContext1', { context: 'Test3' as 'Test1' | 'Test2' | 'Test3' })}
      </p>
      {/* Error: Type '{ context: "Test3"; }' is not assignable to type 'string' */}
      <p>{t('testContext1', { context: 'Test3' })}</p>
      {/* Error: Type '{ context: "Test3"; }' is not assignable to type 'string' */}
      <p>{t('testContext1', { context: 'Test3' as const })}</p>
    </div>
  );
};
```

## Expected behavior

String unions should be correctly detected as errors if they have cases which are not covered by the context.

## Your Environment

- *runtime version*: i.e. node v14, deno, browser xy
- *i18next version*: i.e. 19.5.3
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by marcalexiei** [comment]
This issue is an upstream issue, so it should be handled in `i18next` not `react-i18next`.
@adrai can the issue be moved there or it needs to be closed and reopened there?

**Comment by stefan-schweiger** [comment]
Thanks, I have reopened the issue in `i18next`.
