### ISSUE TITLE
TS Context error when using json for storing translations 

### ISSUE THREAD

**Issue by VasilNikolov** [i18next/react-i18next#1744]
## 🐛 Bug Report

When using a json store for translations using context results in a TS error.

## To Reproduce

A [minimal reproducible example](https://stackblitz.com/edit/vitejs-vite-jb61lw?file=src%2FApp.tsx)

## Expected behavior

There shouldn't be any errors since it's ok with the underlying i18n logic.

## Your Environment

- *runtime version*: i.e. node v14, deno, browser xy
- *i18next version*: 23.10.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by marcalexiei** [comment]
You have augmented i18n interface in 2 different places
  -  `@types/i18n.d.ts`
  -  `src/i18next.d.ts`
  I'm going to use `src/i18next.d.ts`

### `src/i18next.d.ts`

In this file there are 2 error: 
1. The resources should include all keys for a specific language, not all languages  (as described in the [official guide](https://www.i18next.com/overview/typescript#create-a-declaration-file))
```diff
+ resources: (typeof resources)['en'];
- resources: typeof resources;
```
2. You are not changing the default namespace (in your code you are using `test`)
```diff
+ defaultNS: 'test';
```

### `src/i18n`

You need to update the `defaultNS` also on `i18n.init`

> [!NOTE]
> Only on stackblitz I see an error on `src/i18next` which says `/src/en.json' is not a module.(2306)` on the json import. 
> On my local machine I don't see this error, so to fix it on stackblitz I'll add a casting.

```diff
 i18n.use(initReactI18next).init({
   resources,
+ defaultNS: 'test',
   fallbackLng: 'en',
   returnNull: false,
 });
```

---

An updated working example can be found here: 
https://stackblitz.com/edit/vitejs-vite-joyvfv?file=src%2FApp.tsx

<img width="796" alt="image" src="https://github.com/i18next/react-i18next/assets/24919330/8acbb050-f223-4e98-81d5-e97d297a46a0">
