### ISSUE TITLE
Anchor tag not working on Trans component

### ISSUE THREAD

**Issue by Frankusky** [i18next/react-i18next#1747]
## 🐛 Bug Report

Whenever I try to use Trans component passing an anchor tag as component in an object, it throws that he expected a function/element/etc but he get undefined. However, if instead of sending an anchor tag I send a bold or italic tag it will work fine. *Edit:* if I use an array on components attribute and I have hardcoded the text inside the anchor tag it works fine

## To Reproduce
Component
```js
<Trans
  i18nKey="user.login"
  ns="global"
  components={{
    loginCTA: (text: string) => {
      return (
        <a 
            href="https://www.google.com" 
            target="_blank"
            rel="noreferrer"
            className="underline text-brand-blue100">{text}</a>
      );
    },
  }}
/>
```
JSON's
```json
{"user":{"login": "To continue, you must <loginCTA>log In</loginCTA>"}}
```

```json
{"user":{"login": "Debes <loginCTA>Iniciar Sesión</loginCTA> para continuar"}}
```

## Expected behavior

I need to get the text inside the tags and add hiperlink to it. 

## Your Environment

- *runtime version*: node v20.9.0
- *i18next version*: 11.15.3
- *os*: Ubuntu
-  The error message is:
```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

**Comment by Frankusky** [comment]
So a workaround that I did is to create a component to wrap the anchor tag. 


```
const LinkTo = ({ children, href }: { children: any; href: string }) => {
  return (
    <a
      href={href}
      target="_blank"
      rel="noreferrer"
      className="underline text-brand-blue100"
    >
      {children}
    </a>
  );
};
```

Then pass it to the Trans component

```
<Trans
  i18nKey="user.login
  ns="global"
  components={{
    login: (
      <LinkTo href="https://google.com" />
    )
  }}
/>
 ```
Is there any way to avoid to create a new component just to wrap the anchor tag?

**Comment by adrai** [comment]
The components passed do not need to handle the children...
so try:

```js
<Trans
        i18nKey="user.login"
        components={{
          loginCTA: (
            <a
              href="https://www.google.com"
              target="_blank"
              rel="noreferrer"
              className="underline text-brand-blue100"
            />
          ),
        }}
      />
```

**Comment by Frankusky** [comment]
:astonished: oh that is working, thanks!

**Comment by o-faro** [comment]
> The components passed do not need to handle the children... so try:
> 
> ```js
>       <Trans
>         i18nKey="user.login"
>         ns="global"
>         components={{
>           loginCTA: (
>             <a
>               href="https://www.google.com"
>               target="_blank"
>               rel="noreferrer"
>               className="underline text-brand-blue100"
>             />
>           ),
>         }}
>       />
> ```

unluckily this is not working anymore. The proposed workaround seems to be the best solution
