### ISSUE TITLE
[Bug][IOS]: Error - Multiple commands produce React-Core-3e4f9a72-RCTI18nStrings | React-Core.common-RCTI18nStrings

### ISSUE THREAD

**Issue by rettranksX** [i18next/react-i18next#1748]
Hello.
I recently got this error when I was trying to build app on iOS via Xcode:

error: Multiple commands produce '/Users/user/Library/Developer/Xcode/DerivedData/Test-exffvuxnyqpfmxhdzauvmpdjfywh/Build/Intermediates.noindex/ArchiveIntermediates/Test/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/RCTI18nStrings.bundle'

    note: Target 'React-Core-3e4f9a72-RCTI18nStrings' (project 'Pods') has create directory command with output '/Users/user/Library/Developer/Xcode/DerivedData/Test-exffvuxnyqpfmxhdzauvmpdjfywh/Build/Intermediates.noindex/ArchiveIntermediates/Test/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/RCTI18nStrings.bundle'

    note: Target 'React-Core.common-RCTI18nStrings' (project 'Pods') has create directory command with output '/Users/user/Library/Developer/Xcode/DerivedData/Test-exffvuxnyqpfmxhdzauvmpdjfywh/Build/Intermediates.noindex/ArchiveIntermediates/Test/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/RCTI18nStrings.bundle'

Maybe you can help me to solve this issue?

These tasks did not help in solving the problem:
https://github.com/OneSignal/react-native-onesignal/issues/1665
https://github.com/facebook/react-native/issues/43610

![image](https://github.com/OneSignal/react-native-onesignal/assets/124816661/a156998f-8909-405a-94d7-97f62ac1f761)

Podfile:
<img width="347" alt="image" src="https://github.com/OneSignal/react-native-onesignal/assets/124816661/ccdf8e2d-00a9-4821-8b17-a9753dbc7a6a">

Step to reproduce:
1. Install react-i18next and i18next.
2. Add to Podfile -> config = use_native_modules!
3. pod install
4. Try to build the project.

Thanks!

**Comment by Jaydeep9963** [comment]
![Screenshot 2024-05-04 at 11 15 07 a m](https://github.com/i18next/react-i18next/assets/133762427/75d3e42e-62c8-4ac5-b17d-9b6a660ebf7b)

Hello rettranksX,
Until this matter is resolved internally from package side, you might want to consider giving this solution a try.

**Comment by rettranksX** [comment]
> ![Screenshot 2024-05-04 at 11 15 07 a m](https://private-user-images.githubusercontent.com/133762427/327925537-75d3e42e-62c8-4ac5-b17d-9b6a660ebf7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MTczMTIsIm5iZiI6MTcxNDgxNzAxMiwicGF0aCI6Ii8xMzM3NjI0MjcvMzI3OTI1NTM3LTc1ZDNlNDJlLTYyYzgtNGFjNS1iMTdkLTliNmE2NjBlYmY3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNFQxMDAzMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDgzNDAwOTczZjk0MTlkOTFjNzAyYjQwOTJkYWFmYzY2NzE1OGU1Mzk0ZTBmMDE0ZGZhZTE5ZWE1NjEzNTVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1o2HJxj5_2oNh9S4VeX4MqN2IUZDwhOqmbe_LSTH9Q4)
> 
> Hello rettranksX, Until this matter is resolved internally from package side, you might want to consider giving this solution a try.
> 
> Remove duplicate entry of RCTI18nStrings and stay with only one.

Hello!
This solution worked for me.
Thank you!

**Comment by jahanzaib5244** [comment]
@Jaydeep9963 I am facing the same error after removing the file from the pods it worked for me but I am using CICD to create a build and cannot delete the specific pod. can you please suggest me another way to handle this error
