### ISSUE TITLE
I18 doesnt work inside object

### ISSUE THREAD

**Issue by bhavesh2510** [i18next/react-i18next#1752]
This is how i initialise i18n

i18n.use(initReactI18next).init({
  resources,
  debug: true,
  fallbackLng: 'de',
  interpolation: {
    escapeValue: false,
    format: (value, format, lng) => {
      if (format === 'capitalize') {
        const firstLetter = value.charAt(0).toLocaleUpperCase(lng);
        return firstLetter + value.slice(1);
      }
      //no formating present atm
      return value;
    },
  },
  returnNull: false,
  
});

Basically i use `t` as constant

export const t: any = (key: string, interpolation?: any) => {
  return i18n.t(key, interpolation);
};

export const generalSettingsOption = {
  [key1]: t('translated_key1'),
  [key2]: t('translated_key2'),
};

Above keys are definitely present in respective json files

and i18n is not translating this, in the end it looks like translated_key1, translated_key1

Interestingly, this only happens when i change language i.e i18n.changeLanguage("de")
if i don't change language or call i18n.changeLanguage, this will work as expected

Would be really helpful if i can get quick reply

**Comment by adrai** [comment]
Please provide a minimal reproducible example... not just code snippets...
Also check the console output, there might be a warning or error logged.

btw. with react-i18next you should preferably use the t function returned by useTranslation or withTranslation, etc...

**Comment by bhavesh2510** [comment]
Reason why im using constant is because i can’t use hooks in utils (which is not react component)

minimum steps:

create a constant like t
make use of t inside object 
Const object = {
key:t(‘t_key’)
}

log that inside browser, you will notice it is not being translated, no errors can be seen

**Comment by adrai** [comment]
That's again just a code snippet, not a reproducible example...
And beside that, it's exactly this: https://github.com/i18next/react-i18next/issues/909
