### ISSUE TITLE
How to use Trans component for Arabic language?

### ISSUE THREAD

**Issue by AsuraKev** [i18next/react-i18next#1793]
hi  there. Is Arabic rtl supported in Trans component?  Could you please give an example on how it’s done?

thanks

**Comment by adrai** [comment]
The Trans component is just like the t function, they are not aware of the direction, this needs to be managed by you...
To check if the current language is rtl or ltr you can use the dir function: https://www.i18next.com/overview/api#dir

**Comment by AsuraKev** [comment]
Thanks but when I try to put a bracket <0>arabic text</0> its jumping around. any idea how to get around it with interpolation?

**Comment by SUCHiDEV** [comment]
I have the same issue
