### ISSUE TITLE
Trans component not interpolating correctly for Arabic translations

### ISSUE THREAD

**Issue by AsuraKev** [i18next/react-i18next#1794]
Hi there,

I have the following component defined

 <Trans i18nKey="teamRegistration.agreement.sentence1" dir='rtl'>
                  By signing up my team members, I accept the company
                  <StyledLink href="">
                    {t('teamRegistration.agreement.termsOfUse')}
                  </StyledLink>
                  and acknowledge the
                  <StyledLink href="">
                    {t('teamRegistration.agreement.privacyStatement')}
                  </StyledLink>
                </Trans>

and the english translation in the json as

"sentence": "By signing up my team members, I accept the Fisher & Paykel Healthcare <1><0>terms</0></1> and acknowledge the <3><0>privacy</0></3>.",

Everything renders correctly for the Link tag. However when i try this out with Arabic text
من خلال تسجيل أعضاء فريقي، فإنني أوافق على [شروط الاستخدام] الخاصة بشركة Fisher & Paykel Healthcare وأوافق على [بيان الخصوصية].

First issue I encountered was not able to put the interpolation expression in the text as the cursor jumps around and even i managed to push some in, it didnt render out correctly.

Can someone shed some light and show me example of actually apply Trans interpolation with arabic text?

thanks

**Comment by adrai** [comment]
<0> is for Trans component, not for t function: https://www.i18next.com/translation-function/interpolation

**Comment by AsuraKev** [comment]
Sorry yes using the Trans component I am unable to insert <></> placeholder in the Arabic text. Any idea how to get past this? Seems very tricky 😅

**Comment by jamuhl** [comment]
My problem...I have no idea what is incorrect on:

من خلال تسجيل أعضاء فريقي، فإنني أوافق على [شروط الاستخدام] الخاصة بشركة Fisher & Paykel Healthcare وأوافق على [بيان الخصوصية].

As I'm not able to read any rtl language

**Comment by AsuraKev** [comment]
I think I have resolved it. The issue is that the replacement tag needs to be reversed direction when working with RTL
