### ISSUE TITLE
interpolated object undefined if any other values are passed to Trans

### ISSUE THREAD

**Issue by literalpie** [i18next/react-i18next#1801]
## 🐛 Bug Report

When `alwaysFormat` is set to true, and you use `Trans` with any `count` or `values`, the interpolated value of objects is undefined.

For example, this causes "value: undefined":
```tsx
<Trans count={count}> 
  number: {'{{count, INTEGER}}'}
  <br />
  name: {{ name }}
</Trans>
```
but this works as expected:
```tsx
<Trans> 
  name: {{ name }}
</Trans>
```
A workaround is to interpolate the value itself instead of an object:
```tsx
<Trans count={count}> 
  number: {'{{count, INTEGER}}'}
  <br />
  name: { name }
</Trans>
```

## To Reproduce

[stackblitz with issue](https://stackblitz.com/edit/vitejs-vite-apasyw?file=src%2Fmain.tsx,src%2FApp.tsx) (`react-i18next: 15.0.1`)
[stackblitz working as expected](https://stackblitz.com/edit/vitejs-vite-gozbcs?file=src%2Fmain.tsx,src%2FApp.tsx,package.json) (`react-i18next: ^13.0.0`)

## Expected behavior

The result should be:  "number: (formatted 5)  name: (formatted Ben)"
but the actual result is: "number: (formatted 5)  name: (formatted undefined)": 

## Your Environment

- *runtime version*: Safari and Chrome
- *i18next version*: i.e. 23.15.1
- *os*: Mac

I can reproduce in ^14.0.0 and 15.0.1, but not in ^13.0.0 (see stackblitz above).

We use react-i18next in a very large monorepo, so it would be difficult to find all instances of this issue to apply the simple workaround mentioned above.

**Comment by adrai** [comment]
hehe... you need to talk with @timwest612
it's because of this issue: https://github.com/i18next/react-i18next/issues/1719 and this change: https://github.com/i18next/react-i18next/commit/2c4c4a77bc0ea4200646e7075b7838061073ada7

I've now tried to address also your case, but this gets trickier and trickier...
please try v15.0.2...

**Comment by literalpie** [comment]
Thank you so much!
