### ISSUE TITLE
failure in last bundle

### ISSUE THREAD

**Issue by Productivix** [i18next/react-i18next#1807]
- *i18next version*: 15.1.0
- 
info Reloading connected app(s)...
 BUNDLE  ./index.js 

error: Error: ENOENT: no such file or directory, open '/.../node_modules/react-i18next/node_modules/@babel/runtime/package.json'
    at Object.readFileSync (node:fs:448:20)
    at Package.read (/.../node_modules/metro/src/node-haste/Package.js:16:37)

I have no error with  *i18next version*: 15.0.3

**Comment by adrai** [comment]
Please create a minimal reproducible example repository.

**Comment by adrai** [comment]
That was the only change: https://github.com/i18next/react-i18next/commit/e05425ed3a7e89c0a0977f2d8d1813a792d631ab by @aiktb

**Comment by Productivix** [comment]
sorry it was a problem from my installation . this module in last version runs very well on RN 0.75.4--)
