### ISSUE TITLE
Not all namespaces are loaded when passing the `lng` option to useTranslate

### ISSUE THREAD

**Issue by pvdstel** [i18next/react-i18next#1809]
## 🐛 Bug Report

When passing the same value in the `lng` prop to the options of `useTranslation` with different namespaces, only one namespace is loaded. This causes the `Suspense` fallback to be shown forever, as i18next never attempts to load other namespaces. The behavior is related to [this section of code](https://github.com/i18next/react-i18next/blob/2934253363e83d6e6356bf8c9a99e6905c6e3e87/src/useTranslation.js#L159-L163), where it notices that `lng` is set, and only attempts to load the language. While debugging, I found that i18next notices that it does not need to load new languages, so it [bails out early](https://github.com/i18next/i18next/blob/8af192b7aab14b3fb50f4d4a1740a89fd54316a9/src/i18next.js#L501-L506), even if more namespaces should be loaded.

Note that the translations are loaded lazily.

Unexpected behavior:  
![unexpected-behavior](https://raw.githubusercontent.com/pvdstel/react-i18next-forced-language-unexpected-suspense/7221acf6f57cf32281e87cf1516cb2d8e198e475/static/unexpected.png)

I would like to note that the problem still occurs when `useSuspense` is disabled, but then it appears to be a race condition as to which files are loaded and which are not. It does not trigger Suspense, but the translations simply are not ready.

![unexpected-race](https://github.com/user-attachments/assets/ce9c80a3-068d-4805-8908-61bae6b00136)

## To Reproduce

Repository: https://github.com/pvdstel/react-i18next-forced-language-unexpected-suspense

The file `src/fixedLanguage.ts` contains a value which can be toggled for demonstrating the unexpected behavior. This value controls whether the value passed to the `lng` option is `'en'` or `undefined`. When `undefined` is passed, the behavior is as if `lng` is not set, giving the expected results. But if we set `lng` to `'en'`, only the first translation is ever loaded in.

To run:

```sh
pnpm install
pnpm dev
```

Then follow the instructions in the terminal as Vite has launched a development server.

## Expected behavior

I expect all required namespaces to be loaded in, and for the Suspense to disappear eventually:  
![expected-behavior](https://raw.githubusercontent.com/pvdstel/react-i18next-forced-language-unexpected-suspense/7221acf6f57cf32281e87cf1516cb2d8e198e475/static/expected.png)

Simply asking i18next to provide a specific language shouldn't cause namespaces to not load in.

## Your Environment

- *runtime version*: Node v22.11.0. Browsers: Firefox Developer Edition 133, Chrome 130.0.6723.117.
- *i18next version*: 23.16.4.
- *react-i18next version*: 15.1.0.
- *os*: Windows.

**Comment by adrai** [comment]
Can you try with v15.1.1 ?

**Comment by pvdstel** [comment]
That version works, both in the minimal example and in the larger application. Thank you! 😄

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

There are many ways to help this project 🙏
