### ISSUE TITLE
Adding a style attribute to a table, in a raw, multiline formatted string would throw an ambigous error

### ISSUE THREAD

**Issue by reanimatedmanx** [i18next/react-i18next#1810]
## 🐛 Bug Report

🚬 It's not that simple...

Anyways, so when having to:
- translate a raw formatted, multiline string
  - with multiple nested translations
    - together with a table
      - ❗and if the table has a `style` attribute to it...
      
 then an error is thrown.
`namespaces.forEach is not a function`

## To Reproduce

A [minimal reproducible example](https://codesandbox.io/p/sandbox/react-i18next-playground-forked-pkrp2m?file=%2Fsrc%2FApp.js%3A7%2C1).

```js
export default () =>
  i18n
    .use(backend)
    .use(initReactI18next)
    .init({
      load: 'languageOnly',
      lng: 'en',
      fallbackLng: 'en',
      interpolation: {
        escapeValue: false,
      },
      ns: ['translation', 'uncommon'],
      fallbackNS: 'uncommon',
    });
```

## Expected behavior

The concatenation of fallback namespaces should be an array, and overall no error happens and everything works.

## Diving deeper

One of the things observed here was:
![image](https://github.com/user-attachments/assets/080377a9-cc5e-4aa2-b93d-07b606bcbdd7)

`i18next.js | Line 776`

## Your Environment

- *runtime version*: i.e. node v18+, any browser
```
"i18next": "^23.8.1",
"i18next-browser-languagedetector": "^7.2.0",
"i18next-http-backend": "^2.4.2",
"react-i18next": "^14.0.1",
"react": "^18.2.0",
"react-dom": "^18.2.0",
```

**Comment by jamuhl** [comment]
@adrai it's returning here: https://github.com/i18next/i18next/blob/master/src/Translator.js#L66 where namespaces would still be a string (convert to array not gets applied in that exception but later: https://github.com/i18next/i18next/blob/master/src/Translator.js#L79 )

**Comment by adrai** [comment]
already there ;-)

**Comment by adrai** [comment]
i18next v23.16.5 should address this

**Comment by reanimatedmanx** [comment]
Confirm to be fixed! Thanks!
