### ISSUE TITLE
withTranslation mocking documentation example should return t: (str: string) => str

### ISSUE THREAD

**Issue by henkkasoft** [i18next/react-i18next#1814]
## Documentation issue
In here:
https://react.i18next.com/misc/testing
withTranslation mock-example mock all t-function calls to empty string. I think it should return the call-string similarly like useTranslation mock-example.

Now this:
```
jest.mock('react-i18next', () => ({
  // this mock makes sure any components using the translate HoC receive the t function as a prop
  withTranslation: () => Component => {
    Component.defaultProps = { ...Component.defaultProps, t: () => "" };
    return Component;
  },
}));
```

Should be this:
```
jest.mock('react-i18next', () => ({
  // this mock makes sure any components using the translate HoC receive the t function as a prop
  withTranslation: () => Component => {
    Component.defaultProps = { ...Component.defaultProps, t: (str: string) => str };
    return Component;
  },
}));
```

## Motivation

it can be misleading when copied mock-examples works differently with different components depending if withTranslation or useTranslation is used.
I think it is better to return t-function's call-string because then it can be used in unit-tests.

**Comment by adrai** [comment]
That's JavaScript not TypeScript... but I'll add a hint for that

**Comment by adrai** [comment]
<img width="790" alt="image" src="https://github.com/user-attachments/assets/844abc69-49de-4a5e-b40f-5c4e5058f3cb">
