### ISSUE TITLE
missing deps

### ISSUE THREAD

**Issue by boxxxie** [i18next/react-i18next#183]
there are 3 missing deps for this module.

`i18next`
`i18next-xhr-backend`
`i18next-browser-languagedetector`

**Comment by jamuhl** [comment]
missing?
https://github.com/i18next/i18next
https://github.com/i18next/i18next-xhr-backend
https://github.com/i18next/i18next-browser-languageDetector

i18next.com is the main xhr and browser are plugins. react-i18next is framework specific addon. sorry for not being clear about the setup.

Will try to make it more clear that i18next.com is the 'central' source

**Comment by karltaylor** [comment]
Throwing this in the `README.md` would be useful!

**Comment by jamuhl** [comment]
readme reads:

### react-i18next

> Higher-order components and components for React when using [i18next](http://i18next.com).

suggestions to make it more clear are welcome...
