### ISSUE TITLE
No unit tests ?

### ISSUE THREAD

**Issue by jmfrancois** [i18next/react-i18next#192]
Hi,

I'm currently evaluate this react module and I can't find any tests inside it.

Do you plan to add any QA to it ?

- [ ] write tests
- [ ] add test coverage
- [ ] add travis CI

**Comment by jamuhl** [comment]
not highest prio...but for sure if time allows it i will add tests. But right now the code is simple enough to not run into issues - the i18next framework on the other hand is fully tested https://github.com/i18next/i18next and there is the part which could break

**Comment by jamuhl** [comment]
PR would be welcome for adding tests.

**Comment by jmfrancois** [comment]
I will, could you just in this case create the entry on travis for react-i18next ?

https://travis-ci.org/i18next

**Comment by jamuhl** [comment]
Sure can do the travis part. Thanks a lot.
