### ISSUE TITLE
i18nLoadedAt prop sent even if cached - triggering unnecessary re-renders

### ISSUE THREAD

**Issue by rosskevin** [i18next/react-i18next#202]
Initially (without caching) I was seeing 14 re-renders on a simple page which I thought was way beyond reasonable, thinking we have fundamentally coded something incorrectly.

I found `i18nLoadedAt` prop to be sent even if the locale is cached.  I have [created a `Performance` class](https://gist.github.com/rosskevin/af84b4e81fe64f3dfc1d1127563dee0b) that I run `shouldComponentUpdate` through and it logs any diff in development.  

I have primed the following scenario by:

1. loading the page (primes the i18n cache, specifically the `common` namespace)
2. triggering the authentication dialog (same page)
3. clearing the log
4. triggering the authentication dialog (same as 2 above)

Here is the sequence:

```bash
# trigger the dialog
[Performance] [AppFrame] is dirty: state (key showAuthentication is diff)
[i18n] translator: missingKey - en common %s - $t(domain) %s - $t(domain)
[Performance] [AppFrame] is dirty: props ([i18nLoadedAt] keys are diff)
[18n] translator: missingKey - en common %s - $t(domain) %s - $t(domain)
```

So, the prop `i18nLoadedAt` is marking my component as dirty, even though:

1. the i18n is cached and _did not_ change
2. my component has not changed and does not need to be re-rendered

## Questions/solutions

1.  What is the intended purpose of `i18nLoadedAt`?
2.  Why is the `i18nLoadedAt` passed when the namespace in question is cached?
3.  As a hack (which I don't like), I could ignore `i18nLoadedAt`, but this doesn't seem like the right thing to do, and depending on 1 above, it may harm i18n non-cached locale pages and dynamic updating.

Thoughts?

**Comment by jamuhl** [comment]
i18nLoadedAt is set based on changes to the underlaying storage of i18next.

You might add the `wait option` to translate hoc:

```
translate(['defaultNamespace', 'anotherNamespace'], { wait: true })(TranslatableView);
```

this will delay rendering of your component until the instance is ready and all namespaces are loaded

**Comment by rosskevin** [comment]
Thanks @jamuhl , `translate([], {wait: true})` did stop it from re-rendering, but:

1.  My translations were cached/ready and shouldn't trigger re-rendering with `i18nLoadedAt`
2. Adding `{wait: true}` to every component, while it stops the re-rendering, would be painful to make sure is done consistently in every single widget.
3. I actually don't want it to wait, I think the asynchronous loading is a nice benefit

## Questions:
1. Is `i18nLoadedAt` informational only?  if so, can we just log that when debug is true to avoid unnecessary re-renders?
2. If it is required (so that we get re-renders when necessary), shouldn't it ensure that it isn't trigger re-rendering when cached?

**Comment by jamuhl** [comment]
it is sufficient to use the wait in some outer component. So that's assured the translation were loaded.

How do you cache the translations? Not sure how we should avoid the triggering. As it triggers if something changes (be it manually adding a key, a missing key, have something loaded,...) as the storage is not immutable we don't know if it changed.

So responding your question it is 2)...not sure but eg. loading from a cache plugin uses the addResourceBundle which triggers a change. So on init you got n-times were an update gets triggered. Using the outer wait will avoid unneeded renderings.

If you see anyway to improve this i'm open to suggestions.

**Comment by rosskevin** [comment]
I'm using the `i18next-localstorage-cache`.

I don't know the code well enough to suggest an alternative.  I took a look and it makes sense to use this as a trigger for re-rendering upon change, it just seems to ignore the cache case.

On the flip side of that, as you said, I can do this once in my highest order component and it is an improvement, albeit a bit unexpected.  If nothing is in the works to change, perhaps this should be added to the docs on the cache plugin?

**Comment by jamuhl** [comment]
hm as i see it - we can't remove that...as other libs might depend on that...

but can you test: if i see it right it gets triggered by https://github.com/i18next/react-i18next/blob/master/src/translate.js#L41 (not loading but the resourceStore added event). If so we could make listening to that optional - which should reduce re-rendering in your case.

**Comment by rosskevin** [comment]
I'm wondering if this top level project shouldn't be more "cache aware" or a tighter integration with a caching plugin so that it doesn't trigger these change events _unless_ a new translation is added.  It appears that as-is, the lib sees cached translations as `added` (which is technically true based on the API), but perhaps there is something to change here.  I'm not reloading a page, just showing/hiding a component.

- In general, I agree with the intent of the prop being sent on a store change.
- I don't think a library user would expect to see `n` changes to the store when locale's are cached (unless I'm missing a rendering use case here)
- I am not deep enough in react to know, I would assume that `n` unnecessary re-renders is a performance problem, perhaps not an acceptable one.
- As far as I can see, `n` re-renders is the _default_ behavior, so you actually have to invest time to have this library _not_ trigger unnecessarily

I see how we got here, but I think this is an unforeseen legitimate bug.  We could:

1. change defaults so that others don't see this behavior; or 
2. make this lib more cache aware, so that re-renders aren't triggered.

Again, I'm just waxing academically at this point; I'm not a react expert nor an expert on the internals of this lib.

**Comment by jamuhl** [comment]
a) you don't get any rerender triggers after first initialization is done -> so it renders n-times only the first load - or if additional stuff got loaded or language was changed

b) performance wise - only if there are dom changes the cost for rerenders are high - which obviously isn't the case here

c) there are not a lot of people using the cache layer (actually your the first one i got an issue opened for it - which does not mean its unimportant) - some bundle the resources with webpack

d) you actually have to invest time to have this library not trigger unnecessarily - for me that's a tone i don't like....this is OSS, you get this for free while i work on my spare time on this trading time with my family, friends,...even reading through this and trying to help you i "wasted" hours of my life - but ok it's a legitimate bug

Anyway published v1.9.0 were you can set bindI18n and bindStore to false to disable triggering - or set it to the events were you want it to trigger.

You can try http://www.locize.com if you like to support the development of i18next. Thanks.

**Comment by rosskevin** [comment]
Thanks @jamuhl - my tone wasn't intended to be negative even though it was constructive criticism.

I'm just looking for the best experience for newcomers since I myself invested a bunch of time to track this down; I hope you also consider what the time I have spent to present this information as a contribution to OSS.

Again, thank you for this work, I consider it the best of i18n and I evaluated many.

**Comment by rosskevin** [comment]
@jamuhl - originally the `{wait: true}` at the top component solved our issue, but as we are building out our application, this issue has come up again.

Even thought we have the `{wait: true}` at the top component, and we are seeing a bunch of `i18nLoadedAt` state changes sent.   
- We are showing 5 of `Foo` which multiloads 2 bundles, and we see 20 `i18nLoadedAt`.  
- We added `{wait: true}` to `Foo` and it reduced `i18nLoadedAt` state changes to 10.

Putting `{wait: true}` at the highest component doesn't appear to force subordinate components to wait for bundles to render.  Is there a different global config that could be used with the same effect?

So (from above):
a) Your assertion appears to be untrue in my situation - I see rerenders when expanding (adding a `detail`) one component on an existing page.  The `detail` component uses the same language bundles as the `parent`.   I expect one `Foo` component render trigger with the addition of a sub component, but all `Foo` components get the render trigger.

b) there is a cost if you have a high number of components (which we do on a list page) even without DOM render changes.  

c) the cache layer seems to be working well, but based on the design where `#translate` adds the cached bundles one-by-one (even though I remotely multiload) triggering state change/re-renders for each one regardless of `{wait: true}` at the top level.  Again, I think maybe I need to force the wait globally if possible.

I have to wonder if there is a better way with a global wait or some more advanced logic.

As-is right now, a single item expand on a test page with 5 items (a list page that could have 100 items or more) is triggering 20 re-renders due to `i18nLoadedAt`.  With 100 items that would be 400.  It's definitely a performance issue for us.

**Comment by jamuhl** [comment]
did you already change the 

```
{
  bindI18n: 'languageChanged loaded',   // which events trigger a rerender, can be set to false or string of events
  bindStore: 'added removed'            // which events on store trigger a rerender, can be set to false or string of events
}
```
https://github.com/i18next/react-i18next#translate-hoc

**Comment by rosskevin** [comment]
- `bindI18n: false` had no effect
- `bindStore: false` worked!

(options above tried with `wait: true`)

So minimally with our cached setup, it seems we always want `{wait: true, bindStore: false}` on every translate call.

Is there a way to default these globally so I don't need to add these options in all our components?  I see in the source that they are defaulted in the `#translate` options if not specified.  I could wrap it in a function, but it seems like we are adding up a ton of HOCs on an actual widget. If I did that, my widget would actually look like `myTranslate(translate(pure(relayContainer(Foo))))`, so any recommended global config or pattern is appreciated.  Thank you

**Comment by jamuhl** [comment]
there is no options right now to set those once and for all translated hocs...

we might add something for that by setting defaults for the hoc on the i18nProvider and pass that to hoc via context. Would be open for a PR - but right now i'm hard on time to implement that.

for the hocs you can do something like:
```
import compose from 'lodash.compose';

export default compose(
  requireAuthentication,
  translate(['locize-app'], { wait: true }),
  connect(mapStateToProps, mapDispatchToProps),
  pageTitle('locize-app', 'pages.titles.editor', props => ({ projectName: props.project.name || 'Project' }))
)(YourComponent);
```

**Comment by zarela** [comment]
I had the same issue and someone suggested setting bindStore to false
`export default translate('yourns', { bindStore: false })(App)`

**Comment by jamuhl** [comment]
@zarela yes beside that you now can set that globally too: https://react.i18next.com/components/i18next-instance.html

or by using the context API (our own): https://github.com/i18next/react-i18next/blob/master/src/context.js#L13
