### ISSUE TITLE
Plurals with interpolation

### ISSUE THREAD

**Issue by timhecker** [i18next/react-i18next#207]
Hi,
how can I use plurals with interpolation? I have sometihing like that: 

``{``
 ``"region": "in {{component}} region",``
 ``"region_plural": "in {{component}} regions"``
``}``

and in React comp: 

``const regionCount = (region) => (``
 `` <strong>``
 ``   {region.regionsCount}``
``  </strong>``
``);``
...
``const MyComp = ({``
  ``region,``
  ``t,``
``}) => (``
``<Interpolate i18nKey="ns:region" component={regionCount(region)} />``
``);``

Is there a way to pass the count in `<Iterpolate>`component, maybe like this: 
``<Interpolate i18nKey="ns:region" component={regionCount(region)} count={10} />``

to obtain:

`in <strong>10</strong> regions`

or

`in <strong>1</strong> region`

Thanx.

**Comment by jamuhl** [comment]
try `<Interpolate i18nKey="ns:region" component={regionCount(region)} options={{ count: 10 }} />` on mobile right now...can't test myself.

**Comment by timhecker** [comment]
Perfect: this is what I needed :) 
Thanks.

**Comment by GuskiS** [comment]
Doesn't seem to be working anymore.

**Comment by jamuhl** [comment]
means? not working -> giving an error? nothing changed there so guess it still works...

what is your translation.json, your interpolate code,...more info would be appreciated

**Comment by GuskiS** [comment]
Sure.
```
{
  "room": "{{count}} room",
  "room_plural": "{{count}} rooms",
  "guest": "{{count}} guest",
  "guest_plural": "{{count}} guests",
  "roomLabel": "{{rooms}}, {{guests}}"
}
```

```
    <Interpolate
      guests={<Interpolate i18nKey="common:guest"  options={{ count: sumGuest(rooms) }} />}
      i18nKey="common:roomLabel"
      rooms={<Interpolate count={rooms.length} i18nKey="common:room" />}
    />
```

`guests={...}` doesn't return interpolated number.
`rooms={...}` doesn't work with plural correctly.

**Comment by jamuhl** [comment]
you will need to add all variables as props the options itself is for getting the key for plural correctly -> so basically you need to pass:

```
<Interpolate
      guests={<Interpolate i18nKey="common:guest" count={sumGuest(rooms)} options={{ count: sumGuest(rooms) }} />}
      i18nKey="common:roomLabel"
      rooms={<Interpolate count={rooms.length} i18nKey="common:room" options={{ count: rooms.length }} />}
    />
```

**Comment by GuskiS** [comment]
Thanks, works. But feels very strange and unintuitive.

**Comment by jamuhl** [comment]
not sure if you saw it...that component was marked as better been replaced with the Trans component -> Interpolate will be marked deprecated in future release

**Comment by jamuhl** [comment]
beside that...your sample does no include a component so could be written as:

`<div>{t('common:room', { count: rooms.length })}, {t('common:guest', { count: guests.length })}</div>`

**Comment by GuskiS** [comment]
I know, that is just simplified example. My use case could be, `See {{rooms}} for {{guests}}` or whatever.
I will look into `Trans` component. Thank you for your quick help.
