### ISSUE TITLE
Date formatting relative to now

### ISSUE THREAD

**Issue by rosskevin** [i18next/react-i18next#208]
Are you interested in formatting dates relative to `now` with functionality similar to format.js `<FormattedRelative/>`?  

References:
- [API](https://github.com/yahoo/react-intl/wiki/Components#formattedrelative)
- [Component source](https://github.com/yahoo/react-intl/blob/master/src/components/relative.js)

I thought I saw a discussion here previously but am unable to find it.  

Thoughts?

**Comment by jamuhl** [comment]
i18next gives formatting in user land -> http://i18next.com/translate/formatting/ so there isn't a real way to know how we can get a date formatted `fromNow`.

So i'm not sure how you would implement this.

**Comment by rosskevin** [comment]
I'm not sure I understand your concern, the react-intl is rendered in the user's browser similar to us. You pass it a reference date e.g. `auction end date` and it renders something like `5 minutes` instead of a full format. It also has a timer that updates the time on a scheduled basis.

If it is not of interest I suppose I will just implement it for us, but helpers such as this are a huge convenience and are highly used in stacks such as rails, so it might be nice to have for those that are converting to react.

**Comment by jamuhl** [comment]
my concern we do not know how to get a value like `5 minutes ago` as we do not know if a user uses moment.js or the intl API for formatting...

i'm more than open to a PR

**Comment by rosskevin** [comment]
I'll submit a PR if I develop something useful.
