### ISSUE TITLE
html tags in i18next translation files in react are always getting escaped

### ISSUE THREAD

**Issue by scherler** [i18next/react-i18next#209]
Hi Jan,

I stumbled upon http://stackoverflow.com/questions/39836369/html-tags-in-i18next-translation-files-in-react/ and see the same problem. 

I played with different configuration:

translations:
```
EmptyState.activity.paragraph.2=Commit to the repository <em>{0}</em> or run the pipeline manually.
```

jsx:
```
 const inner = t('EmptyState.activity.paragraph.2', {
        0: repoName,
        interpolation: {
            escapeValue: false,
            escape: false,
        }
    });
```

I added the interpolation (I found both attributes in the web but I think only the first one is actually used) to see whether that makes a different but I have in the init already:

```
        interpolation: {
            escapeValue: false,
        }
```

Any hints?

**Comment by jamuhl** [comment]
not a problem of react-i18next - you just can't add html into a react element. react will safe you from xss vulnerability and escape the content:

more detail and possible solution: https://facebook.github.io/react/tips/dangerously-set-inner-html.html

but be aware if you put user content there not escaped you open your site to xss attacks.

more secure reading the react-i18next readme: https://github.com/i18next/react-i18next#interpolate-component

which makes you split content

so the "best" solution - at least what we do - is using markdown in the translations and use eg: https://github.com/acdlite/react-remarkable to convert that to formatted content.

shareeditdeleteflag
answered just now

jamuhl
1,036813

**Comment by scherler** [comment]
I actually tried with dangerous markup but boom goes the dynamite and I did not debugged the stack.

Yeah splitting does not rock, so I will look into the markdown way of doing things. Sounds clean and further powerful.

Thank you very much, as always quick as the lightning. 😀
