### ISSUE TITLE
Doesn't work with nested/deep interpolation keys

### ISSUE THREAD

**Issue by gustavohenke** [i18next/react-i18next#211]
I can't use nested/deep interpolation keys because they always return undefined.

Suppose I used the `Interpolate` component like this:

``` js
<Interpolate i18nKey="ns:key" user={ this.props.user } />
```

...and the key definition is `Hello, {{user.name}}!`, it will not work.
I am sure I'm passing the user prop as `{ name: 'foo bar' }`.

The problem seems to lie [here](https://github.com/i18next/react-i18next/blob/master/src/interpolate.js#L39-L40); at this point, `match` is equal to `user.name`, but obviously there is no `user.name` prop.

If I pass a plain string in the `user` prop, and I update `ns:key` to `Hello, {{user}}!`, everything works.

**Comment by jamuhl** [comment]
The Interpolate component is here to interpolate components into translations, eg. like links or others.

what you want is done by just:

`<div>{t('ns:key', this.props.user)}</div>`

**Comment by gustavohenke** [comment]
Okay, this one works!
However, don't you think `Interpolate` should work anyway with these deep keys?

**Comment by jamuhl** [comment]
would be nice...agree. WIll look what i can do - but has no prio. If you in the mood and got time you might provide a PR. Would be very welcome.

**Comment by jamuhl** [comment]
really think this is out of scope...but feel free to provide a PR if needed...closing for now.
