### ISSUE TITLE
Doesn't work with `react-google-maps`

### ISSUE THREAD

**Issue by kadishmal** [i18next/react-i18next#213]
When rendering `react-google-maps` component in a class that is wrapped with `react-i18next`, it throws the following error.

```
translate.js:115 Uncaught TypeError: Cannot read property 'getFixedT' of undefined
```

The conflict occurs in the component managed by that `react-google-maps`. For some reason it doesn't pass on the `i18n` property, so accessing `this.i18n. getFixedT()` throws an error.

**Comment by jamuhl** [comment]
honestly no idea what's happening

**Comment by kadishmal** [comment]
Yeah, no big deal. I've just completely dropped this module and instead using Maps API directly looking at your code. So, this modules helps anyway.

**Comment by akonyushevskiy** [comment]
Have same issue, looks like i18n undefined in react-google-maps nested component.

**Comment by jamuhl** [comment]
more an issue in react-google-maps

**Comment by akonyushevskiy** [comment]
Thanks, will go search answer there.
