### ISSUE TITLE
How to reload(re-render) react component after changeLanguage?

### ISSUE THREAD

**Issue by cnaa97** [i18next/react-i18next#215]
Hello. 

I used static table maker and render when first initialization (componentDidMount).

First time to translate (Initialization), It doesn't matter. 

but If I change lang after init, my static table doesn't translate like table header title or something. 

Does react-i18next have re-rendering component function?

How can I do?

**Comment by cnaa97** [comment]
In class, gridRender function
```js
gridRender() {
        const { t } = this.props;
        let $elem = this.$bxUserSetting,
            $gridElem = $elem.find('.grid'),
            that = this;

        if ($gridElem.get(0)) {
            this.grid = $gridElem.bxGrid({
                height: 200,
                $pageContainer: $elem.find('.pager'),
                colModel: [
                    {
                        label: t('settings.user-id'),
                        name: 'userId',
                        width: 100
                    },
                    {
                        label: t('settings.user-nm'),
                        name: 'userNm',
                        width: 100
                    }).render();
    }
```

**Comment by jamuhl** [comment]
0d1d443 i extended the example https://github.com/i18next/react-i18next/tree/master/example seems to work at least here.

Just changing the language via i18next.changeLanguage should be enough if your component is using the translated Hoc

**Comment by cnaa97** [comment]
Thank you for your reply. My question looks like odd. Please close this issue.

**Comment by NurbekGithub** [comment]
But what if you want the whole app to be aware of language change, not a specific component? When I call changeLanguage in my Header component only it's updating, but the rest of the app doesn't change.

**Comment by jamuhl** [comment]
Everything wrapped inside a HOC or render props (https://react.i18next.com/components/i18n-render-prop.html) will rerender.

You can also wrap the whole app into a change language aware component like: https://github.com/i18next/react-i18next/blob/master/example/react-native-expo/App.js#L18

**Comment by Viet27th** [comment]
> [0d1d443](https://github.com/i18next/react-i18next/commit/0d1d443f0b9170482c052112e73f4bfe663875e3) i extended the example https://github.com/i18next/react-i18next/tree/master/example seems to work at least here.
> 
> Just changing the language via i18next.changeLanguage should be enough if your component is using the translated Hoc

Hi guy, could you help me answer my question on this link? Thank you so much https://www.codeproject.com/Questions/5284870/Please-give-me-idea-to-write-a-library-like-react

**Comment by jamuhl** [comment]
@Viet27th it's really no magic...withTranslation uses the useTranslation hook https://github.com/i18next/react-i18next/blob/master/src/useTranslation.js which itself only uses hooks that come with react itself (useState to change the state and enforce a rerender, useEffect to bind to events like the language change)...
