### ISSUE TITLE
How to use react-i18next translate with generated component by jQuery DOM.

### ISSUE THREAD

**Issue by cnaa97** [i18next/react-i18next#216]
Sorry, My last question looks very terrible. 

I used Table generator by jQuery. It located component's function. not render function.

In this generator, I have to define first row's haad (table head).

like this : 
```js
colModel: [
                    {
                        label: t('settings.user-id'),
                        name: 'userId',
                        width: 100
                    },
                   {
                        label: t('settings.user-nm'),
                        name: 'userNm',
                        width: 100
                    }
                ]
```

The problem is not shown in first page initialization. 

The problem comes when I I change language using this `i18next.changeLanguage(event.target.value);` function.

It is remain initialized language. Other component is OK, but just defined items in table row didn't changed. I think, i18next can't catch look like `data-reactid=".0.0.3.1.0.7.1.1.0.0`

How do you think about?

**Comment by cnaa97** [comment]
I guess, I have to do like

```js
i18next.on('languageChanged', function(lng) {
  $('#generated-table').localize(); // jQuery translator
})
```

right?

**Comment by jamuhl** [comment]
that or trigger a rerender on the react-component holding the jquery component - basically trigger a rerender for that (you will need to trigger that on prop change - not mount)

**Comment by jamuhl** [comment]
closing for now...feel free to reopen if issue unresolved for you.
