### ISSUE TITLE
Should `i18next` be a peerDependency?

### ISSUE THREAD

**Issue by tleunen** [i18next/react-i18next#217]
When building an app with `react-i18next`, the file i18n has a reference on the module `i18next`. So it means the user project should have i18next has a direct dependency.

So `i18next` should be listed as a peerDependency so we know exactly which version we can install

**Comment by jamuhl** [comment]
can add that i18next >= 2.x.x for next version..no problem

**Comment by jamuhl** [comment]
upcoming version will include in package.json:

```
  "peerDependencies": {
    "i18next": ">= 2.0.0",
  },
```
