### ISSUE TITLE
wait set to true still load the component

### ISSUE THREAD

**Issue by keul** [i18next/react-i18next#219]
I'm experiencing a flickering effect when loading a component where I use `wait: true`.

Example to reproduce:

```
@translate(['common', 'app'], { wait: true })
class App extends Component {
  render() {
    const { t } = this.props
    return (
      <div className={ t('key2') }>
        { t('key1') }
        <div>{ t('common1') }</div>
      </div>
    )
  }
}
```

When application is loaded I see the component rendered with translation ids for few millisecs, then they are replaced by proper translations.

Isn't the `wait` option used for preventing this?

**Comment by keul** [comment]
BTW: enabling also `.use(Cache)` from `i18next-localstorage-cache` prevent the issue, but still I'm wondering if I missing something with `wait`

**Comment by jamuhl** [comment]
should work...will have a look after my xmas holidays (9th january)

**Comment by keul** [comment]
Thanks! This is the demo example I used: https://github.com/keul/react-i18next-demo

**Comment by jamuhl** [comment]
could you try with:

i18next@4.2.0
react-i18next@2.0.0

should now wait for initialization of i18next instance

**Comment by keul** [comment]
It works! Thanks you 🍻

**Comment by JulianWels** [comment]
It's not really fixed if you have to revert to some older version.
It works with `export default translate(['defaultNamespace'], { wait: true })(View);` but not when changed inside the settings, then this "flickering effect" keeps happening.

**Comment by jamuhl** [comment]
@JulianWels please check before writing. i18next 4.2.0 was current release when writing this fix. Also works with current 7.0.x. No need to revert. If not working anymore we might have introduced some regression we not yet are aware of...sorry.

What you mean changed inside settings?

**Comment by JulianWels** [comment]
Sorry, wasn't aware of that. I'm currently at react-i18next@2.2.0 & i18next@7.1.2 and experience the same issue as described from keul
`i18n.init({wait: false,…})` does not work for me. (Which I meant by "settings")

**Comment by jamuhl** [comment]
can't work...wait is not a setting inside i18next - it's just related to the translate hoc and has to be defined there. Where did you read this works?

By the way i like the idea to make that possible. As we more or less use the wait option more or less in every translated hoc we use.

**Comment by JulianWels** [comment]
Oh, I'm sorry, I just assumed that this would be a global setting as well. But, you're right; my fault; wasn't reading the docs right. At least I gave you an idea 😅

**Comment by jamuhl** [comment]
if you like open a new issue - requesting it. so you get an update when implemented.
