### ISSUE TITLE
SaveMissing causes errors with setState()

### ISSUE THREAD

**Issue by Vehicle** [i18next/react-i18next#220]
i18n.js configuration:
```
i18n
  .use(XHR)
  .use(LanguageDetector)
  .init({
    wait: true,
    bindI18n: 'languageChanged loaded',
    fallbackLng: 'cz',
    saveMissing: true,

    backend: {
      crossDomain: true,
      loadPath: endpoint.TRANSLATION + '/{{lng}}',
      addPath: endpoint.TRANSLATION
    }
  })
```

saveMissing: true causes _Warning: setState(...): Cannot update during an existing state transition (such as within `render` or another component's constructor). Render methods should be a pure function of props and state; constructor side-effects are an anti-pattern, but can be moved to `componentWillMount` error._

When setting to false, errors stop.

The problem occurs on line 113 of react-i18next/dist/commonjs/translate.js when this.setState({ i18nLoadedAt: new Date() }); is executed. (Commenting that line stops the errors, but breaks language changing.)

Versions:
```
"i18next": "^3.5.1",
"i18next-browser-languagedetector": "^0.3.0",
"i18next-xhr-backend": "^1.2.1",
"react-i18next": "^1.11.0",
```

**Comment by jamuhl** [comment]
that's expected behaviour.

save missing changes the stored translations during rendering - which triggers a rerender via setting state in the hoc.

during production you should not have savemissing enabled anyway - so just a warning during development.

but you can avoid this by setting `bindStore: false` on init

**Comment by Vehicle** [comment]
Thanks, will disable saveMissing on production then.
