### ISSUE TITLE
Inject components into translation

### ISSUE THREAD

**Issue by pgom** [i18next/react-i18next#222]
I'm wondering if I'm are the only one with this kind of needs. 
On the current application I'm working on, it might be useful if we could use a component as value. For example:

```
render() {
 return I18n.t('key', { value: <Link onclick={() => } />}
}
```

In this example, `Link` returns a link with predefined set of props that we use everywhere.
@jamuhl , does something like this makes sense to add? If so, how would you suggest to do it?

**Comment by jamuhl** [comment]
No idea how to do so...i18n.t calls the function of i18next which itself returns always a string and also only interpolates strings.

For this case we created an extra interpolation component doing what you want: https://github.com/i18next/react-i18next#interpolate-component

**Comment by pgom** [comment]
Yes, I'm doing just that. My intention was to keep the components "clean" and just invoke translation without creating another component. But still, this is pure gold...nice work.

**Comment by jamuhl** [comment]
if you find a simpler solution i'm more then open to it...just got no idea how to make that possible.
