### ISSUE TITLE
Is there any way to return an entire namespace via the translate function?

### ISSUE THREAD

**Issue by isaachinman** [i18next/react-i18next#224]
I have a datepicker component, which takes an object for localisation:

    {
      "lang": {
        "placeholder": "Select date",
        "rangePlaceholder": [
          "Start date",
          "End date"
        ],
        "today": "Today",
        "now": "Now",
        "backToToday": "Back to today",
        "ok": "Ok",
        "clear": "Clear",
        "month": "Month",
        "year": "Year",
        "timeSelect": "Select time",
        "dateSelect": "Select date",
        "monthSelect": "Choose a month",
        "yearSelect": "Choose a year",
        "decadeSelect": "Choose a decade",
        "yearFormat": "YYYY",
        "dateFormat": "M/D/YYYY",
        "dayFormat": "D",
        "dateTimeFormat": "M/D/YYYY HH:mm:ss",
        "monthFormat": "MMMM",
        "monthBeforeYear": true,
        "previousMonth": "Previous month (PageUp)",
        "nextMonth": "Next month (PageDown)",
        "previousYear": "Last year (Control + left)",
        "nextYear": "Next year (Control + right)",
        "previousDecade": "Last decade",
        "nextDecade": "Next decade",
        "previousCentury": "Last century",
        "nextCentury": "Next century"
      },
      "timePickerLocale": {
        "placeholder": "Select time"
      }
    }

I have this in my translations as `datepicker`, however accessing `t('datepicker')` returns `undefined`, presumably because it's meant to return a string, not an object.

I can access what I need via: `i18n.getResourceBundle(i18n.languages[0]).datepicker`, but I'm wondering if there is any way to do the same via the translate function itself, as this solution feels a bit hacky.

**Comment by jamuhl** [comment]
try `t('datepicker', { returnObjects: true })`

**Comment by jamuhl** [comment]
did that work for you....? can this issue be closed

**Comment by onionhammer** [comment]
@jamuhl that's a key, not the namespace

**Comment by jamuhl** [comment]
@onionhammer yes, must at least be inside one key...hopefully not to much asked to add a key and nest an object needed inside that...

**Comment by urtheone** [comment]
if  there any api can implement this now？

**Comment by jamuhl** [comment]
no

**Comment by urtheone** [comment]
I solved it this way in react-i18next:
`i18next.store.getResourceBundle(language, namespace);`
