### ISSUE TITLE
Question on tooling

### ISSUE THREAD

**Issue by TheTFo** [i18next/react-i18next#226]
Can you recommend a tool and configuration for using react-18next with a translation key extractor?  I'm unsure of the best way.

Thanks

**Comment by jamuhl** [comment]
There is:
https://github.com/i18next/i18next-parser
https://github.com/i18next/i18next-scanner

both are active projects...so might be a matter of taste - best ask there if having a concrete question regarding the usage - as i personally did never use them. Sorry.

An other option, which also will support the future development of react-i18next and i18next is using http://locize.com our localization as a service tier. This is also what we use in our personal projects. To get a picture of how it simplifies localization i strongly recommend reading: http://locize.com/2016-11-16-localization-fun/
