### ISSUE TITLE
I18nextProvider breaks server side rendering.

### ISSUE THREAD

**Issue by akonyushevskiy** [i18next/react-i18next#227]
Hi! After setup i18n on server side rendering i see, thats everything from first component wrapped in translate not render.

Server side code:
`const store = configureStore();

    const initialView = renderToString(
      <I18nextProvider i18n={req.i18n}>
        <Provider store={store}>
          <RouterContext {...renderProps} />
        </Provider>
      </I18nextProvider>
    );

    const finalState = store.getState();

    const html = renderHtml(initialView, finalState, {locale: 'en', resources: req.i18n.getResourceBundle('en', 'common')});`

And i get something like: 
`<html>... <body><header><div>static</div><!-- react empty: 1 --></header> <!--react empty:2 --></body></html>`

I check dictionaries, it loaded. (i use express middleware)

**Comment by jamuhl** [comment]
do you take into account that init is async? and resources are loaded async too?

**Comment by jamuhl** [comment]
For serverside (universal) rendering you might check: https://github.com/i18next/react-i18next/issues/38

**Comment by akonyushevskiy** [comment]
`const resources = req.i18n.getResourceBundle(lang, 'common');
        const i18nClient = {locale: lang, resources};

        const i18nServer = req.i18n.cloneInstance();
        i18nServer.changeLanguage(lang);
        setTimeout(function(){
          const initialView = renderToString(
            <I18nextProvider i18n={i18nServer}>
              <Provider store={store}>
                <RouterContext {...renderProps} />
              </Provider>
            </I18nextProvider>
          );

          const finalState = store.getState();
          const html = renderHtml(initialView, finalState, i18nClient);

          res
            .set('Content-Type', 'text/html')
            .status(200)
            .end(html);
        }, 5000);`

I tried this, and still no result.

**Comment by jamuhl** [comment]
You might try to contact @simpleblack https://github.com/i18next/react-i18next/issues/38 for help...or try to post an issue on stackoverflow...can't help to much personally ... as we do not use universal rendering in our projects - so i got no indeep knowhow - only thing i know...worked for others.

sorry

**Comment by jamuhl** [comment]
or have a look: https://github.com/ipatate/UniversalAppReact

**Comment by jamuhl** [comment]
you could solve this?

**Comment by akonyushevskiy** [comment]
Hi, yes. Thank you!

**Comment by vyarmak** [comment]
@akonyushevskiy bump! Have the same problem :) Pls, share a solution :)

**Comment by vyarmak** [comment]
Ok. Seems that when you are rendering on the server side `this.state.ready` is `false` and if you set `wait` to `true` - it will always return `null` in `render()` function. 

So for server side rendering just DON'T set `wait = true` :). You can set different initialization options for client and server side with `wait = true` / `wait = false` and you will not need to use `{ wait: true }` like in example `translate('view', { wait: true })(Component);`

**Comment by jamuhl** [comment]
the trick is you need to load all translations upfront...that way hoc will state it is ready. There should be no need to set wait: false on serverside -> at least i believe so. Like stated before...not to much into ssr -> might be a good time to add an example.

**Comment by jamuhl** [comment]
ok just made a next.js sample https://github.com/i18next/react-i18next/tree/master/example/nextjs

you indeed need to set wait according being on client or not: https://github.com/i18next/react-i18next/blob/master/example/nextjs/pages/index.js#L14

or you can set that on `i18next.init({ react: { wait: onServer ? false : true} });`

If you like we could also add a flag so we know we are on server and in that case ignore waits in translate hoc?!?

further i just added https://github.com/i18next/react-i18next/blob/master/src/translate.js#L28 so passing down initial translations is easier
