### ISSUE TITLE
Access currently active language

### ISSUE THREAD

**Issue by glenjamin** [i18next/react-i18next#228]
Is there a way to make the decorator expose the language which is currently enabled? I'm looking for a nice way to display this in my application's menu bar.

Is this something you'd be open to adding if it isn't currently supported?

**Comment by jamuhl** [comment]
hm...basically one could require the i18next instance passed to the provider directly or via context. From there it's `i18next.language` if you like to get detected language or `i18next.languages` if you like an array of used languages ordered by priority.

Not really sure we should start adding more props to get passed down - as they could be reached directly. The translated hoc as is basically is nothing more then an update trigger / wait component to assert translations are loaded or changes trigger a rerender - plus adds a t function that is fixed to a namespace.

But if you see a benefit in having that lng on props we could add that i think.

**Comment by glenjamin** [comment]
The main advantages of using the HoC would be access via context rather than requiring the singleton, and being subscribed to the "changeLanguage" event with appropriate cleanup.

I suppose any component that's subscribed to translate would reliably be re-rendered on that event, so accessing the language property in `render()` would be safe, but look a little bit like it isn't.

How about an option that also provides the `i18next` instance as a prop?

**Comment by jamuhl** [comment]
I would say go for it...let us add i18n as a prop - so one could access beside the language also all other values and function on i18next. It's one prop more and gives access to eg. exists, dir and other functions.

If you like you could provide a PR. Or i will try to add and publish this asap. Just can't promise it will happen today.

**Comment by jamuhl** [comment]
just published react-i18next@2.1.0 which exposes i18n via props on the translate hoc

**Comment by glenjamin** [comment]
awesome, thanks!

**Comment by Noiwex** [comment]
could you at least write an example
