### ISSUE TITLE
Support formatting in Interpolate component

### ISSUE THREAD

**Issue by KonstantinKritsin** [i18next/react-i18next#229]
Could you please add support for i18next formatting in Interpolate component?

Initial settings:
```javascript
import i18n from 'i18next';
import XHR from 'i18next-xhr-backend';
import moment from 'moment';

i18n.use(XHR)
.init({
  fallbackLng: 'en',
  ns: ['common'],
  defaultNS: 'common',
  debug: true,
  interpolation: {
    format: function(value, format, lng) {
      if(value instanceof Date) return moment(value).format(format);
      return value;
    }
  }
});
```
common.json:
```javascript
{
  "copyright":"&copy; {{date, YYYY}}. {{link}} - All rights reserved"
}
```
and component:
```javascript
<Interpolate i18nKey="copyright" useDangerouslySetInnerHTML date={new Date()} link={<a href="http://company" target="blank">Company</a>}/>
```
result is warning:
`i18next: interpolator: missed to pass in variable date, YYYY for interpolating &copy; {{date,YYYY}}. {{link}} - All rights reserved`

Thank you

**Comment by jamuhl** [comment]
hm...yes...did not thought of the case both components and formatted content. Good idea to add this.

Not yet got an idea when i will have the time to do so...should be able to add this next week. But no promise.

Meanwhile as workaround you might pass the formatted date. Will come back to you asap.

**Comment by jamuhl** [comment]
supported in react-i18next@2.2.0

see https://github.com/i18next/react-i18next/blob/master/example/app/i18n.js#L20 for configuration
see https://github.com/i18next/react-i18next/blob/master/example/locales/en/common.json#L3 for sample json
see https://github.com/i18next/react-i18next/blob/master/example/app/components/View.js#L39 for code using it

All like expected i hope...

**Comment by KonstantinKritsin** [comment]
Thanks) all works as expected.
Sorry for late reply

**Comment by OEvgeny** [comment]
@jamuhl Cool, all links are dead.

**Comment by jamuhl** [comment]
the links are over a year old...the new samples have no use of the Interpolate anylonger...as more or less that component is replaced by Trans component: https://react.i18next.com/components/trans-component.html

**Comment by parulMilttal** [comment]
Hi,
I have the same ques, I have used format function in interpolation but it is not working. 
const initI18next = (lang) => {
  return i18next.use(XHR).init({
    backend: {
      loadPath: () => {
        return "/locales/{{lng}}/{{ns}}.json";
      },
    },
    debug: true,
    fallbackLng: "en-US",
    interpolation: {
      escape(value) {
        return value;
      },
      format(value, format) {
        if (format === "uppercase") {
          return value.toUpperCase();
        }
        return value;
      },
    },
    lng: lang,
    load: "currentOnly",
    ns: nameSpaces,
    react: {
      wait: true,
    },
  });
};

**Comment by jamuhl** [comment]
@parulMilttal please also show the value of the translation key and how you call `t` to get the formatted translation

also consider adding a codesandbox sample for easier reproduction of your misconfiguration

**Comment by parulMilttal** [comment]
@jamuhl ,
i have used the below translation key:
"DELETE_LOCATION_ALERT": "Are you sure you want to delete location {{locationName,bold}}?",
I have used t as :
getNameLabel = () => {
    if (this.props.name) {
      return  this.props.name ;
    } else {
      return this.props.defaultText;
    }
  };
<LabelName id="deleteConfirmationMessage">
      {t("locations:DELETE_LOCATION_ALERT", { locationName: this.getNameLabel() })}
</LabelName>

**Comment by jamuhl** [comment]
``{{locationName, bold}}`` -> where did you define the format bold? i only see uppercase

```
format(value, format) {
if (format === "uppercase") {
return value.toUpperCase();
}
return value;
}
```

**Comment by parulMilttal** [comment]
That I have changed while pasting the code in forum, Issue is not with
this. My problem is format function is not excecuting.

**Comment by jamuhl** [comment]
make a sample on codesandbox...so i can check. Not sure where the issue is...but tests say it works ;)

**Comment by parulMilttal** [comment]
Hey
I need some time to create sandbox for this as we have used so many things
this is a big project. Might there are some conflicts between the
comoponents due to which format function is not working. If there is any
specific requirement to use format then pls let me know.

Thanks
Parul

**Comment by parulMilttal** [comment]
Also I want to know how I can debug the format function. I have set debug
true in init.

**Comment by jamuhl** [comment]
No...it's straight forward -> Just made a jsfiddle myself doing an toUpperCase: https://jsfiddle.net/acmLhybj/

**Comment by parulMilttal** [comment]
Is lng an important parameter?? Because I am not giving lng as parameter

**Comment by parulMilttal** [comment]
Also i m using XHR from i18nnext-xhr-bacend

**Comment by jamuhl** [comment]
@parulMilttal lng must be set if not using a languageDetector (so seems in your case it must be set). The difference when using xhr is the loading is async -> don't use the t function before init callback / Promise resolves.

**Comment by parulMilttal** [comment]
Ok I will try with this and revert if it will not work.

Thanks
Parul

**Comment by parulMilttal** [comment]
hi @jamuhl ,
It works!! But my problem hasn't resolved I want to bold that string which is in interpolation. How to do that can you please help me in that. string method bold giving me the html tag and when I am using dangerouslySetInnerHTML it is changing the tags in <b></b> but in string. 

![image](https://user-images.githubusercontent.com/29772038/53950790-f5b42d00-40f2-11e9-9a95-ec6a15a56a27.png)
like in this the first string is in dangerouslySetInnerHTML . 

Thanks
Parul

**Comment by jamuhl** [comment]
@parulMilttal rather sure it works if done correctly...for helping you i will need a codesandbox isolating your problem...not have the time to set this up myself
