### ISSUE TITLE
Disable output of warnings

### ISSUE THREAD

**Issue by 58a36f** [i18next/react-i18next#230]
Hello,

  This is screen from profiler:

![image](https://cloud.githubusercontent.com/assets/25285005/22898393/6ce5272a-f227-11e6-87e1-f686fa8718b0.png)

As you can see I am simply typing something to input which is causing to whole form re-rendering , because I use react-redux-form and did not implement any caching.
All lagging that occurs is due to warn logs:

"`i18next::languageUtils: rejecting non-whitelisted language code: en`"

How do I disable output of warning logs?

i18n-config:

```
import i18n from 'i18next';
import XHR from 'i18next-xhr-backend';
import LanguageDetector from 'i18next-browser-languagedetector';

var i18nconfig= i18n
    .use(XHR)
    .use(LanguageDetector)
    .init({
        fallbackLng: 'cz-CZ',
        preload: ['cz-CZ],
         ns: ['main'],
        defaultNS: 'main',

        debug: false,

        backend: {
             loadPath: 'assets/locales/{{lng}}/{{ns}}.json',
 
            addPath: 'assets/locales/{{lng}}/{{ns}}.missing.json',
     },

        wait: true
    },function(){

    });

export default i18nconfig;
```

**Comment by jamuhl** [comment]
hm...that's a warning which does not get written to console if you have set debug: false. 

further you only get that if you explicitly set a whitelist: https://github.com/i18next/i18next/blob/master/src/LanguageUtils.js#L91

both this seem not to be the case in your config...which confuses me a lot

**Comment by jamuhl** [comment]
any update on this?

**Comment by nkhine** [comment]
i have this in my conf,

```
const config = {
  debug: false,
  defaultNS: 'common',
  detection: {
    // order: ['navigator', 'querystring', 'cookie', 'localStorage', 'htmlTag'],
  },
  fallbackLng: 'en',
  ns: [
    'alerts',
    'breadcrumbs',
  ],
};
if (USE_PO) {
  config.backend = {
    loadPath: getTranslationFileUrl,
    parse: (data, url) => (/\.po$/.test(url) ? parseGettextPO(data) : parseCldrTerritories(data)),
  };
}

i18n
  .use(XHR)
  .use(LanguageDetector)
  .init(config);

export default i18n;
```

but when i load the page, i get 404's for missing 

```
GET http://localhost:3001/locales/en-GB/navbars.json 404 (Not Found)
```

what have i missed in the setup?

**Comment by jamuhl** [comment]
lookup for user detected language en-GB is en-GB, en, fallbackLng

if you just want en -> init option load: 'languageOnly'

**Comment by jamuhl** [comment]
closing as inactive for long - feel free to reopen
