### ISSUE TITLE
Method for iterating over an array

### ISSUE THREAD

**Issue by scottnath** [i18next/react-i18next#231]
I've been trying to find a way to use arrays of data. I think this way is a little hacky, but I'd like to get some feedback please. This solution works in [react-i18next](https://github.com/i18next/react-i18next)

## What it does

This grabs what would be fallback language file as a blueprint of the data. This assumes that the subsequent translations share the _same_ data (but translated), including the number of items in the array.

## Where it fails

I cannot figure out how to do a conditional. I would prefer to skip processing the `map` iteration when a piece of data may be missing - like if there was no name and/or url coming from the data.

## Data

This is just the relevant section of a larger json translation.

file: /app/data/en/content.json

```
{
  page: {
    title: "My Title",
    "projects": [
      {
        "name": "App Name 1",
        "url": "http://example.com/#1"
      },
      {
        "name": "App Name 2",
        "url": "http://example.com#2"
      },
      {
        "name": "App Name 3",
        "url": "http://example.com#3"
      },
      {
        "name": "App Name 4",
        "url": "http://example.com#4"
      }
    ]
}
```

## Usage

```
import defaultContent from '/app/data/en/content.json';

export const Page = ({ t }) => (
...
    {defaultContent.page.projects.map((item, index) => (
      <article title={t(`page.projects.${index}.name`)} link={[t(`page.projects.${index}.url`)]}>
      ...
    ))};
...
);

const PageWrapper = translate(['starter'], { wait: i18nWait })(Page);
```

**Comment by jamuhl** [comment]
there is also `i18n` on props - so you could check if the value exists by: `
```
i18next.exists(`page.projects.${index}.url`)
```

**Comment by jamuhl** [comment]
closing for now - feel free to reopen if not solved

**Comment by baxromxojasultonxojayev** [comment]
how can I iterate array elements to unrodered list with map

    {t("text", { returnObject: true }).map((text, country_code) => (
    {text}
    ))} 

when I do this it gives me t(...).map is not a function

**Comment by adrai** [comment]
@baxromxojasultonxojayev  it's `returnObjects` not `returnObject`
