### ISSUE TITLE
make work with Preact without preact-compat

### ISSUE THREAD

**Issue by Hotell** [i18next/react-i18next#236]
It would be super useful to remove tight coupling on React ( like React Router 4 does ) and be able to use react-18next with Preact for example.

This would benefit consumer ( Preact is 3kb alternative to React )

Maybe @developit can help / give suggestions how to proceed.

Thanks!

**Comment by jamuhl** [comment]
For sure open for PR enabling usage in preact...

**Comment by developit** [comment]
Only thing that needs to be changed is the string ref usage in translate.js.

**Comment by Hotell** [comment]
@developit
hmm and what about https://github.com/i18next/react-i18next/blob/master/src/translate.js#L1 ? 

I have this working with preact-compat, but I would rather ditch preact-compat and use just preact + react-ecosystem

**Comment by developit** [comment]
I'd suggest doing what we do for RR4 - aliasing this in:
https://github.com/developit/react-router-4-test/blob/master/src/lib/react.js

**Comment by jamuhl** [comment]
@Hotell @developit just added a preact sample https://github.com/i18next/react-i18next/tree/master/example/preact for simplicity using preact-compat works well so far.

As doing some fancy stuff in https://github.com/i18next/react-i18next/blob/master/src/trans.js i'm not sure the react-router-4 trick still would work - but i guess yes.

What i really would love would be a preact-i18next for of this - would be awesome - but honestly with maintaining i18next, react-i18next and a lot of other related modules in the i18next ecosystem i got a little fear this would get to much for my time available for open source development

Anyway...closing this for now.
