### ISSUE TITLE
Set "Wait" option at initialization

### ISSUE THREAD

**Issue by JulianWels** [i18next/react-i18next#237]
Because of my false assumption here: #219, I'd like to make a feature-request for setting the wait-option from the Translate-HOCs globally at initialization, like so:
```
i18n
   .init({
      wait: false,
   })
```

**Comment by jamuhl** [comment]
landet in react-i18next@3.1.0

**Comment by jamuhl** [comment]
i18n
   .init({
      wait: true,
   })

**Comment by Shereind** [comment]
Does it (this feature) work in i8next (not react-i 8next)?

**Comment by jamuhl** [comment]
that changed meanwhile -> all react specific options are in options.react

```js
​
i18n
  .use(reactI18nextModule) // passes i18n down to react-i18next
  .init({
    resources,
    lng: "en",
    
    keySeparator: false, // we do not use keys in form messages.welcome
​
    interpolation: {
      escapeValue: false // react already safes from xss
    },

    react: {
       wait: true
    }
  });
```

**Comment by Shereind** [comment]
So I need to add import react-i18next to use wait option?

**Comment by jamuhl** [comment]
yes -> the wait option is handled inside react-i18next `withNamespaces` hoc, `NamespacesConsumer` render prop (i18next itself has no connection to the react render loop)
