### ISSUE TITLE
Interpolate don't work with variables

### ISSUE THREAD

**Issue by DenisPustuev** [i18next/react-i18next#241]
Hello, i have interpolated component 

const alert=  this.props;

<Interpolate i18nKey={'alerts.' + alert.type + '.' + alert.transKey} parameters={alert.parameters} />

"renameFolderUnique": "There is already folder with name {{parameters}}." - this is translation.

console.log(typeof alert.parameters) //string

log in console 
i18next: interpolator: missed to pass in variable parameters for interpolating There is already folder with name {{parameters}}.

When i pass just a string instead of valiable, it works. alert.parameters is a string, it shows in console and if i write it near interpolate component. 

Please help

**Comment by jamuhl** [comment]
could it be that alert.parameters is undefined, emptyString or 0 on initial rendering...?!?

https://github.com/i18next/react-i18next/blob/master/src/interpolate.js#L38

**Comment by DenisPustuev** [comment]
no. i mapping array of alerts, so alert object already in my component when it mounts. Console log shows it, and when i write {alert.parameters} near <Interpolate /> component it is shows correctly.

**Comment by jamuhl** [comment]
just saying code does only show this msg if that prop is undefined, null, '' or 0 => https://github.com/i18next/react-i18next/blob/master/src/interpolate.js#L30

code is very clear there...so i'm rather sure it's a issue on your side => but feel free to prove me wrong...

**Comment by DenisPustuev** [comment]
I found problem, i have dynamic translation key {'alerts.' + alert.type + '.' + alert.transKey}, if i hardcode it, interpolation works. But i need it to be dynamic. 

If translation key is dynamic, only interpolation doesn't work, key is found correctly. 

Have any ideas?

thank you in advance

**Comment by jamuhl** [comment]
why should there be a difference hardcoded vs. dynamic -> can only be a difference if at some point alert.type is undefined. as in that case resulting key would be different.

add a console.log here https://github.com/i18next/react-i18next/blob/master/src/interpolate.js#L29 rather sure...your alert is an empty object

**Comment by DenisPustuev** [comment]
I found issue. Sorry it was on my side. Thank you for your answers.

**Comment by jamuhl** [comment]
what was it in the end?

**Comment by DenisPustuev** [comment]
I hardcoded alerts objects for testing my Alert component, and mixed up keys, so i really put empty string to Interpolate component).

**Comment by jamuhl** [comment]
ok glad your found the problem...if find anything else don't hesitate to open a new issue. thank you for using react-i18next.

**Comment by jamuhl** [comment]
if interested you might also have a look at http://locize.com our localization as a service tier...depending on your app size that might help you to save a lot of time on translating.

**Comment by DenisPustuev** [comment]
Thank you for this component. It is awesome.
