### ISSUE TITLE
Unnecessary warnings in Interpolate

### ISSUE THREAD

**Issue by realw98** [i18next/react-i18next#242]
For example, if we have &lt;Interpolate i18nKey="itemsCounter" totalCount={this.props.totalCount} /&gt; and if totalCount is 0, we get warning "i18next: interpolator: missed to pass in variable totalCount for interpolating..."
However, zero or empty string (or even "false" in some cases) are valid values for interpolating.
I suppose that the problem is in this condition
if (!props[k]) // then print warning
It should be more accurate, something like
if(props[k] === undefined)

**Comment by jamuhl** [comment]
agree...will be changed asap.

**Comment by jamuhl** [comment]
just published react-i18next@2.2.1 removing this unnecessary warnings.
