### ISSUE TITLE
How to configure path from which json is loaded

### ISSUE THREAD

**Issue by MocanuMarius** [i18next/react-i18next#243]
The documentation for this is so hard to understand and read, in main readme you see no requirements for backend module, then in the examples there it is, but it's not actually an XHR since it's stored locally. 
How does this work, i just want to import a list of json files from local and make it work with  { translate("whatever"). 
I see no option that specifies how to load local JSON files.

Also, what is { t } = props., and if you pass it by props then why do you need to import {translate} too ? 
also ...  even if you want to do that why would you use {t} for a propname could be so easily overwritten.

I'm so confused about this module, can someone explain to me what it can do and cannot do ?

**Comment by jamuhl** [comment]
are you familiar with react?

`t` in props is the translation function: use like http://i18next.com/translate/
`translate` is a higher order component -> asserts loading namespaces (the JSON files) injects t function to your components props

example uses xhr backend to load translations -> see console network

readme does not include backend as its options:
- you can use that xhr backend
- load manually and pass on init of i18next or by using i18next.addResourceBundle
- use another backend: http://i18next.com/docs/ecosystem/#backends

why shoud one use a prop with name `t`?

**Comment by MocanuMarius** [comment]
@jamuhl thanks for the answer, if it's not "top-level" injected then i understand it doesn't matter.
I will try your suggestions :)

**Comment by MocanuMarius** [comment]
@jamuhl ended up using addResourceBundle.. solved HMR issues by following one of the closed issues here by exporting 2 modules in the component folder like the last message suggested. It would be nice to have a short guide on that somewhere. (Fixing HMR)
