### ISSUE TITLE
react errors

### ISSUE THREAD

**Issue by dcversus** [i18next/react-i18next#244]
Warning: Unknown props `dispatch`, `i18nLoadedAt`, `i18n` on \<div> tag. 
![image](https://cloud.githubusercontent.com/assets/8696354/24401184/ff002820-13bb-11e7-8f6f-a2b3158ba9eb.png)

Could react-i18next serve as the reason?
i use react 15.4.2 and react-i18next 2.1.0

**Comment by dcversus** [comment]
Thanks for quick answer)
CalendarItem component is wrote myself, where i use react-i18next as:
```
import { translate } from 'react-i18next';

@translate()
export class CalendarItem extends Component {
	...
	
	render() {
		const { t } = this.props;
		...
		return (
			...
			<div className={styles.statusText}>{t('calendar:statusTitle')}</div>
			...
		)
	}
}
```

Where am I wrong?

**Comment by dcversus** [comment]
oh, Sorry for the inattention! I found problem... it on my side)
After refactoring and upd deps we missed an error

<div className={styles.wrapper} {...props}> ... </div>

thanks!

**Comment by jamuhl** [comment]
no problem...glad you found it...if you encounter any other issue...let me know
