### ISSUE TITLE
Hot reloading triggers "Cannot read property 'off' of undefined"

### ISSUE THREAD

**Issue by MocanuMarius** [i18next/react-i18next#245]
i18n.store.off is not defined when using hot reloading, any idea how to get around that ?

**Comment by jamuhl** [comment]
https://github.com/i18next/react-i18next/blob/master/src/translate.js#L71

could only be the case if i18next is not yet initialized - which would mean unmount happens very very (to) early ;)

we could add a check there...just strange...i18next.store was there on mount...so rather edgy hmr issue that should never trigger in production...so might be safe to have a check there first if store.off is a function

**Comment by MocanuMarius** [comment]
i'm using this package for hmr, i'll try some other options.
 https://github.com/gaearon/react-hot-loader

**Comment by jamuhl** [comment]
don't think the issue is related in hmr...like said...we might add a validation to not access that store while still undefined. Should at least remove the error.

**Comment by jamuhl** [comment]
try with react-i18next@2.2.2

**Comment by MocanuMarius** [comment]
Hmm tried, but issue persists.

**Comment by jamuhl** [comment]
my fault...please try react-i18next@2.2.3

**Comment by MocanuMarius** [comment]
@jamuhl Wow, It works now . Can i send cakes over Github?

**Comment by jamuhl** [comment]
haha...no need for that...happy if that solved your issue.

**Comment by MocanuMarius** [comment]
@jamuhl well i have some deadlines set, and maybe without your super-awesome prompt support i wouldnt've reached those. So thanks a lot

**Comment by jamuhl** [comment]
you're welcome...
