### ISSUE TITLE
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

### ISSUE THREAD

**Issue by kadishmal** [i18next/react-i18next#247]
warning.js?8a56:36 Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

The above is the warning that comes after install React `v15.5`. They've moved the `PropTypes` into a separate module called `prop-types`. Please use this.

**Comment by jamuhl** [comment]
Thank you for reporting...i'm aware of this...will change this when i got time...not a big deal but still currently hard on time...

**Comment by kadishmal** [comment]
I'll send a PR now. Please take a look.
