### ISSUE TITLE
Cannot GET /locales/en/common.json

### ISSUE THREAD

**Issue by xebu** [i18next/react-i18next#251]
Hi there. I am integrating this package with https://github.com/davezuko/react-redux-starter-kit#server. The company I have has it's own subtle variation of the starter kit. 

I've pretty much followed the example and added the locales folder at the same level as the entry file. However, I continually getting a http 404.

I'm probably missing something rather obvious - hoping you would be able to point it out.

Do let me know if you need anymore information. have uploaded entry point and i18n.js config.
[Archive.zip](https://github.com/i18next/react-i18next/files/946581/Archive.zip)

Thanks in advance.

>

**Comment by masquel** [comment]
@xebu You can copy `locales` folder to `public` folder in root or change webpack config to do it automatically

**Comment by xebu** [comment]
@masquel - I actually did try that and get the same issue.

**Comment by jamuhl** [comment]
in the end it's all about solving that the files get served - so they could be downloaded using xhr. You might add a static route to serve your locals in the express server.

**Comment by xebu** [comment]
@jamuhl - thanks ... that is what I thought. I decided to go and retry all the configured directories and got it working. It appears there was a static route already configured.

Thanks again to both.
