### ISSUE TITLE
[Help Wanted] HTML entities without having to Interpolate every translation

### ISSUE THREAD

**Issue by Stansbridge** [i18next/react-i18next#253]
Our content editors are not particularly tech orientated. This has caused us an issue where they would like to use various html entities inside a translation.

If we do not wrap every key with Interpolate then React will (quite rightly) escape the entities.

We were wondering if there are any recommendations, tips or tricks to deal with or avoid this problem?

**Comment by jamuhl** [comment]
what we do is try to use markdown in such cases.

something like https://github.com/rexxars/react-markdown

in combination with http://locize.com ;)

**Comment by Stansbridge** [comment]
Thanks @jamuhl 

Do you separate Markdown from your text nodes?

**Comment by jamuhl** [comment]
what you mean by separate?

**Comment by jamuhl** [comment]
regarding the resource file we have those mixed.

looking at components we use markdown only were needed.

**Comment by Stansbridge** [comment]
> regarding the resource file we have those mixed.
> looking at components we use markdown only were needed.

Thanks this is really useful to know and helpful!
