### ISSUE TITLE
React.PropTypes

### ISSUE THREAD

**Issue by ruzrulit** [i18next/react-i18next#255]
Hi guys,

Are you going to update React.PropTypes to PropTypes (prop-types)?

With kind regards.

**Comment by jamuhl** [comment]
what do you mean...we updated that on one of the latest releases...

https://github.com/i18next/react-i18next/pull/248

**Comment by jamuhl** [comment]
3.0.0 to be specific

**Comment by jamuhl** [comment]
feel free to reopen if an issue
