### ISSUE TITLE
Trying to create Enzyme Test with Translate

### ISSUE THREAD

**Issue by Weirdtopia** [i18next/react-i18next#256]
I'm currently trying to get Translate to work with Enzyme Testing but i get a response of 
  **

> **'undefined is not an object (evaluating '_this.il8n.options')
 Translate(Test)@webpack:///~/react-i18next/dist/commonjs/translate.js:66:0 <- tests/test-bundler.js:168038:32'**

**

! I'm very new to Enzyme Testing and React !

`import React, { Component } from 'react'
import { translate } from 'react-i18next'
class Test extends Component {
  render () {
    return (
      <div>
          TEST
      </div>
    )
  }
}`

I'm using Translate HOC 
    `export default translate(['common'])(Test)`

ENZYME TESTING
     I tried to bypass the HOC by  creating my own 
```
import React from 'react'
import { shallow, mount } from 'enzyme'
import Test from 'routes/components/test/test'
import { I18nextProvider } from 'react-i18next'
import il8n from 'i18next'

// i18next

describe('TEST ', () => {
  let _props, _spies, _wrapper
  beforeEach(() => {
    _spies = {}


    let il8nObj = il8n.init()
    il8nObj.options.wait = false
    _props = {
      il8n : il8nObj,
      i18nLoadedAt: null
    }
    _wrapper = shallow(
      <Test {..._props} />
    )
  })
  it('Is it a <div>', () => {
    expect(_wrapper.is('div')).to.equal(true)
  })
})

```
i also tried to use the  I18nextProvider as the parent element of Test 
` _wrapper = shallow(
    <I18nextProvider>
       <Test {..._props} />
    </I18nextProvider>
  ).dive()
`
but i get the same result when i dive() to get the Test component 

Thanks

**Comment by jamuhl** [comment]
do you want to test your component or the hoc? best option is to export your pure component without the wrapping it with the hoc for tests https://github.com/i18next/react-i18next/issues/233#issuecomment-282683522

if you like to test with hoc have a look at our tests: https://github.com/i18next/react-i18next/blob/master/test/translate.render.spec.js

**Comment by jamuhl** [comment]
worked out? closing for now...feel free to reopen if needing more help

**Comment by jamuhl** [comment]
is `i18n` an initialised i18next instance?

**Comment by oliviertassinari** [comment]
> i see...not sure if i can be of any help here

@jamuhl You could add warnings when the instance isn't initialize, you could add a documentation section around how using enzyme with react-i18next. It won't solve my issues, but will help future users trying out the library.
I don't want to be rude, but I have found a lake of refinement around the edge case. For anything from medium complexity, to advanced, there is no way to get along without looking at the source code. I know a pretty large chunk of the internal of the library now 😅.
I wish I could have solved this effort. It makes me wondering if I wouldn't have start from scratch, using your work as inspiration. Anyway, thanks for sharing your work :)!

> triggers a rerender

Exactly, you are storing a dead date object. Maybe you can use the [forceUpdate()](https://reactjs.org/docs/react-component.html#forceupdate) API of React instead?

**Comment by jamuhl** [comment]
@oliviertassinari agree on this. And i think i never put down a pull request improving i18next or the documentation. I'm one person supporting some of the most used i18next modules in my free time that's the current situation. I work on locize.com - as soon that grows enough to "buy me more time" for working on i18next i can look into improving such things - until then i depend fully on the help of the community.

Let's make a sample how should i do a documentation or sample here for electron...i just don't use electron myself (had never the need) and honestly got no time to also look into that in detail.

So covering this topics from your side would help others a lot. But don't expect me to go deeper into electron use case during my weekends ;)

**Comment by oliviertassinari** [comment]
@jamuhl I 💯  understand. From my experience, it's really hard to cover the edge cases. Let's hope we can find someone in the community with spare time to improve the situation :).
