### ISSUE TITLE
Has anyone done snapshot testing with this?

### ISSUE THREAD

**Issue by moneytree-doug** [i18next/react-i18next#258]
Since it's decorating the component at a high level, it will automatically render out all the i18n next stuff creating a huge snapshot. Perhaps my implementation is incorrect, but we're considering removing this library in favor of just manually importing the t function where necessary. Does anyone know how we can create smaller snapshots or at least only include the necessary parts required for a snapshot test?

**Comment by jamuhl** [comment]
https://github.com/i18next/react-i18next#testing might help...eventual not testing the decorated component but your pure component would be easier?

Decorate only on view level -> pass t function down to smaller components

**Comment by moneytree-doug** [comment]
@jamuhl That link doesn't work.

**Comment by jamuhl** [comment]
@moneytree-doug sorry upgraded the docs yesterday to gitbook for easier maintainance:

https://react.i18next.com/misc/testing.html

**Comment by jamuhl** [comment]
closing for now...
