### ISSUE TITLE
How to re-use components without i18nextProvider

### ISSUE THREAD

**Issue by spiderpug** [i18next/react-i18next#260]
Hi,

I'm using `react-rails` and it offers the possibility to render components on their own - by that I mean using them not in context of a single page app, but on demand. Currently I have the problem that I cannot easily reuse components that make use of `translate` without being wrapped in a `I18nextProvider`.

## Example

```jsx
class FilterPanel extends Component {
  render() { return <span>{ t('something') }</span>}
}

export default translate(['scope'])(FilterPanel)
```

This way, everything is fine:

```jsx
import myI18n from 'shared/i18n'
import MainView from 'components/MainView'

class MyComplexApp extends Component {
  render() {
    return (
      <I18nextProvider i18n={ myI18n }>
        <MainView/>
          <!-- MainView will render <FilterPanel /> for example -->
      </I18nextProvider>
    )
  }
}
```

Rails view:

```erb
<%= react_component "MyComplexApp" %>
```

Let's reuse FilterPanel somewhere else:

```erb
<%= react_component "FilterPanel", {...props}.as_json %>
```

Now this will fail. `i18n` is no longer present in the context of this component as it was created on its own.

Is there an easy way to deal with this without modifying (wrapping) all components? For example using a custom superclass?

**Comment by jamuhl** [comment]
You can pass an i18next instance to the translate hoc as prop (that way you don't need an i18nextProvider setting the instance to context).

Or pass i18next.t to your component as prop.

**Comment by spiderpug** [comment]
Thanks for your suggestions. Unfortunately I can only pass primitives/JSON objects with Rails.

I ended up with a solution like this to cover both use cases:

```js
// TranslationProvider.js
import i18n from 'shared/i18n'
import {
  translate as i18nTranslate,
} from 'react-i18next'

class TranslationProvider extends React.Component {
  // wraps children using <I18nextProvider i18n=i18n>
}

export default TranslationProvider
export function translate(scope) {
  const TranslateComp = i18nTranslate(scope)

  return function(comp) {
    let hoc = TranslateComp(comp)
    hoc.defaultProps = {
      i18n,
    }

    return hoc
  }
}
```

```js
// FilterPanel

import { translate } from 'TranslationProvider'

class FilterPanel extends Component {
  // ...
}

export default translate(['scope'], FilterPanel)
```

Thanks!
