### ISSUE TITLE
Can't get React Component from Translate's Instance /  ( Enzyme, Sinon )

### ISSUE THREAD

**Issue by Weirdtopia** [i18next/react-i18next#264]
> I forgot to Thank @jamuhl for answering my previous question
>        Thank You @jamuhl 

I'm trying to spy on a function within my React Component using Sinon that is using the Translate HOC. But i can't find the React component, in order to add the spy 

### Enzyme Fail Message
```  TEST (Component)
    ×  TEST RENDER
      PhantomJS 2.1.1 (Windows 8 0.0.0)
    expected spy to have been called at least once, but it was never called
    AssertionError@webpack:///~/assertion-error/index.js:74:0 <- tests/test-bundler.js:42374:24
    assert@webpack:///~/chai/lib/chai/assertion.js:107:0 <- tests/test-bundler.js:84366:31
    webpack:///~/sinon-chai/lib/sinon-chai.js:73:0 <- tests/test-bundler.js:78410:24
    addProperty@webpack:///~/chai/lib/chai/utils/addProperty.js:43:0 <- tests/test-bundler.js:88371:33
    doAsserterAsyncAndAddThen@webpack:///~/chai-as-promised/lib/chai-as-promised.js:293:0 <- tests/test-bundler.js:78111:34
    webpack:///~/chai-as-promised/lib/chai-as-promised.js:283:0 <- tests/test-bundler.js:78101:46
    get@webpack:///~/chai/lib/chai/utils/overwriteProperty.js:50:0 <- tests/test-bundler.js:88914:41
    webpack:///tests/components/test.spec.js:61:0 <- tests/test-bundler.js:80323:47
```
### Test Console Log Showing that testFunction has been called
```
LOG: '<Translate(Component)>
  <Component i18nLoadedAt={{...}} t={[Function]} i18n={{...}}>
    <Translate(TEST) i18n={{...}}>
      <TEST i18n={{...}} i18nLoadedAt={{...}} t={[Function]}>
        <div>
          TEST
          WOOT 2?
        </div>
      </TEST>
    </Translate(TEST)>
  </Component>
</Translate(Component)>'
```

### test.js
```
import React, { Component } from 'react'
import { translate } from 'react-i18next'
import PropTypes from 'prop-types'

class TEST extends Component {
  constructor (props) {
    super(props)
    this.state = {
      woot:'WOOOT'
    }
  }

  testFunction () {
    return 'WOOT 2?'
  }

  render () {
    return (
      <div>
        TEST
        {this.testFunction()}
      </div>
    )
  }
}

TEST.propTypes = {
  t: PropTypes.func
}

export default translate(['common'])(TEST)
```
### test.spec.js
```
const contextStore = {
  context: {
    i18n
  },
  childContextTypes: {
    i18n
  },
  lifecycleExperimental: true
}

let component, instance
describe('TEST (Component) ', () => {
  const buildSubject = () => {
    return ({ t }) => { return (<TEST i18n={i18n} />) }
  }

  const TranslateConnector = translate(['common'], { })(buildSubject())
  component = mount(<TranslateConnector />, contextStore)

  instance = component.instance()
  // Tried to do instance._reactInternalInstance
  instance.testFunction = sinon.spy(instance.testFunction)

  it(' TEST RENDER ', () => {
    component.update()
    console.log(component.debug())
    expect(instance.testFunction).to.have.been.called
  })
})
```
Thanks

**Comment by jamuhl** [comment]
not having a lot of time right now to deeper check...but https://react.i18next.com/components/translate-hoc.html#the-translate-hoc-can-take-a-few-options -> withRef option might be what you search...

**Comment by Weirdtopia** [comment]
When i Pass `{ withRef: true }` to the Translate HOC, i get a response back from Karma stating that 

> PhantomJS 2.1.1 (Windows 8 0.0.0) ERROR: 'Warning: Stateless function components cannot be given refs (See ref "wrappedInstance" in StatelessComponent created by Translate(Component)). Attempts to access this ref will fail.'

<hr>
<h4> In Translate Instance </h4>

`{ refs: Object    {  
   wrappedInstance:null
}}`

**Comment by jamuhl** [comment]
already late here...will have a look into this tomorrow...hopefully we will find a solution.

**Comment by jamuhl** [comment]
hm...right...only extended classes can have those...wondering if there is a better option to expose the wrapped component. Needs some googeling ;)

**Comment by jamuhl** [comment]
seems there is no real solution to this...at least i did not find one.

but this might help: https://github.com/acdlite/flummox/issues/225

`TestUtils.findRenderedComponentWithType(myConnectedComponent, MyComponent)` at least for testing.

Best would be to test calling of the `instance.testFunction` on mount by testing the non wrapped component...like described here: https://react.i18next.com/misc/testing.html#testing

**Comment by jamuhl** [comment]
closing for now...would accept a PR for any solution for this.
