### ISSUE TITLE
Support having locale string files near the code that needs it

### ISSUE THREAD

**Issue by gnapse** [i18next/react-i18next#265]
I know this feature request may imply a huge change on how this library works, but I wanted to fire off the discussion and see if it's possible, easy to achieve, or even desired by others.

Following the principle of not separating an app's source files by function, but rather by feature (see [here](https://jaysoo.ca/2016/02/28/organizing-redux-application/)), I was wondering if it would be possible to achieve having smaller locale json files contextualized inside each the modules and components that comprise an app, and then have `react-i18next` gather them all via some build process that would generate the files actually used by the app on runtime.

For instance, given the directory structure:

```
src
├── index.css
├── index.js
├── index.scss
├── locales
│   ├── en.js
│   └── de.js
├── pages
│   ├── Dashboard
│   │   ├── locales
│   │   │   ├── en.js
│   │   │   └── de.js
│   │   ├── Dashboard.js
│   │   └── index.js
│   ├── Home
│   │   ├── locales
│   │   │   ├── en.js
│   │   │   └── de.js
│   │   ├── Home.js
│   │   └── index.js
│   └── Login
│       ├── locales
│       │   ├── en.js
│       │   └── de.js
│       ├── Login.js
│       ├── actionTypes.js
│       ├── actions.js
│       ├── constants.js
│       ├── index.js
│       ├── reducer.js
│       ├── styles.css
│       └── styles.scss
├── reducer.js
├── registerServiceWorker.js
├── router.js
├── setupTests.js
└── store.js
```

Note how each major app module (Login, Home and Dashboard) has a `./locales/` sub-directory which in turn contains a file for each supported language. The idea is that these files contain only the strings needed by that module. Then you also have a global `/src/locales/` with strings that are global to the whole app, potentially needed by any page.

Is a setup like this even possible right now? Or maybe achievable with some changes in this library? Is it even desired and reasonable, or am I totally off on this one?

**Comment by jamuhl** [comment]
Can be done "rather" easily writing your own backend or bundler:

https://www.i18next.com/misc/creating-own-plugins.html#backend

-> xhr https://github.com/i18next/i18next-xhr-backend
-> webpack https://github.com/atroo/i18next-resource-store-loader

Just need to get those translations into i18next per namespace and use them in appropriate component using the translate hoc.

Or even better decouple code and translations using http://locize.com

**Comment by gnapse** [comment]
Thanks for the info. A quick look makes me think the emphasis on the phrase **"rather" easily** is highly justified, but I get that it's possible. I'll see if I can take the time to dive into this at some point in the near future, because I would like to have that feature a lot.

The webpack plugin you link to above seems to do something similar. I fear however that it makes the app loads all the locales as part of the build. Whereas with the xhr backend (which I'm already using) I like that the app only loads the locales it needs, asynchronously via xhr.

I may actually explore an alternative option which is to keep the xhr backend, and rather than developing a i18next plugin, I'd develop a script that would find all the locale files throughout my app's `src/` directory, and generate the corresponding locale files in the location where `i18next-xhr-backend` expects them to be (I would also keep these generated files out of git via `.gitignore`). Then I'd integrate this script as part of the build process, and also enable it to continually re-build the locale files when they change during the development process, using something like watchman to be notified of when the smaller locale files change (similarly to how node-sass can be setup to convert scss to css).

Anyway, again, thanks for the information. I'll close the issue for now.

**Comment by jamuhl** [comment]
agree. i think your approach having some task copy the localization files to the expected place might be the best option (better than having the xhr "guessing" the correct path by some convention).
