### ISSUE TITLE
Trans cannot interpolate Components without text

### ISSUE THREAD

**Issue by s-ol** [i18next/react-i18next#271]
I would like to interpolate an `input` tag into a localized text. I do not care about localizing the `value` field (though I could do that with the translate HOC and `t`), but the `Trans` component just removes it from the rendered output.

    <Trans i18nKey="share">
      <input value="copyme" readOnly />
    </Trans>

---

    share: 'Interpolated <0></0> component',

Also, when using a tag like `a` and either:
- putting no text contents in `children` (`<a href...></a>`) but in the translation (`<1>asd</1>`)
- putting text in `children` (`<a href...>asd</a>`) but none in the translation (`<1></1>`)

the component crashes:

    Uncaught TypeError: Cannot read property 'split' of undefined
    at getChildren (eval at <anonymous> (main.js:3801), <anonymous>:64:23)
    at eval (eval at <anonymous> (main.js:3801), <anonymous>:84:23)
    at Array.reduce (<anonymous>)
    at getChildren (eval at <anonymous> (main.js:3801), <anonymous>:69:21)
    at renderNodes (eval at <anonymous> (main.js:3801), <anonymous>:100:10)
    at Trans.render (eval at <anonymous> (main.js:3801), <anonymous>:141:68)
    at eval (eval at <anonymous> (main.js:3312), <anonymous>:796:21)
    at measureLifeCyclePerf (eval at <anonymous> (main.js:3312), <anonymous>:75:12)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (eval at <anonymous> (main.js:3312), <anonymous>:795:25)
    at ReactCompositeComponentWrapper._renderValidatedComponent (eval at <anonymous> (main.js:3312), <anonymous>:822:32)

**Comment by jamuhl** [comment]
Trans component does not work like this...your code needs to reflect what you like to translate...

```
<Trans i18nKey="share">
  hello
  <input value="copyme" readOnly />
  world
</Trans>
```

```
share: 'Interpolated <1></1> component',
```

**Comment by s-ol** [comment]
@jamuhl except that what I wrote works fine with a link tag but not with input; and also your example doesn't work; hence this issue.

If I create a component without a key and text + input tag in the missingKey message there isn't even a reference to an element.

**Comment by jamuhl** [comment]
ok...will need to check...

**Comment by jamuhl** [comment]
could you try react-i18next@4.6.2

**Comment by jamuhl** [comment]
hi @s-ol did it work with react-i18next v4.6.2 ?!?

**Comment by s-ol** [comment]
@jamuhl didn't get to try it yet, I will report back.

**Comment by arracso** [comment]
Hi, Im new to i18next. Loving the library. I'm having the same issue with v4.6.2 and v4.6.3
I have this key on the JSON: 

`"REGISTER_WARN": "<0>Doing click on REGISTER, you are agree with our <1>Terms & Conditions</1> and you have to read our <2>Privacy Policy</2>.</0>"`

and this should work:

`<Trans i18nKey="REGISTER_WARN"><Typography>Click<a href='/1'>Terms</a> and  read <a href='/2'>Conditions</a></Typography></Trans>`

But it doesn't. The second `<a>`  is shown as a blank space. Trying to put things well It only workedwhen I write the following:

`<Trans i18nKey="REGISTER_WARN"><Typography> <a href='/1'> </a><a href='/2'> </a></Typography></Trans>`

So, I notice that: 
We need to put a word (space is fine) inside the a component.
Children components does not count as "words" so I need to add a blank space.
All components at the same level must be toguether. This: `<Trans  i18nKey="key"><a> </a>word<a> </a></Tran>` won't work, but this: `<Trans  i18nKey="key"><a> </a><a> </a></Tran>` will.

It would be great if trans doesn't care about if you are writing something inside a component. And allows you to just put <a></a>.

**Comment by jamuhl** [comment]
@arracso let me give some minutes to evaluate...and fix

**Comment by jamuhl** [comment]
@arracso did you try: 

```
"REGISTER_WARN": "<0>Doing click on REGISTER, you are agree with our <1>Terms & Conditions</1> and you have to read our <3>Privacy Policy</3>.</0>"
```

the last link has index 3 not 2 at least on missing console output i get.

**Comment by jamuhl** [comment]
@arracso regarding your 1. - 4.

1) = 2) yes we need to know if an element can have children -> even if only giving an empty space else we could not make `<Trans i18nKey="share"><input value="copyme" readOnly /></Trans>` working with `Interpolated <0></0> component`
3) `<Trans i18nKey="key"><a> </a>word<a> </a></Trans>` works for me with value `<0>world</0> word are great <2>hello</2>`

> It would be great if trans doesn't care about if you are writing something inside a component. And allows you to just put <a></a>.

=> i agree would be great...but currently that will break all cases where we need elements that have no children (like inputs)...we basically split content by regex `new RegExp('(?:<([^>]*)>(.*?)<\\/\\1>)', 'gi')` getting an array like `['0', 'world']` for string `<0>world</0>` => does world come after given tag or inside -> we only can say this if the given component has children (empty string).

**Comment by arracso** [comment]
Ok. Now I understand why it works the way it does.

**Comment by jamuhl** [comment]
Closing for now...feel free to reopen if encounter any other issue / problem...

**Comment by mohitmorepatil** [comment]
I am getting an error Text strings must be rendered within a text component when I use text string inside trans component

**Comment by jamuhl** [comment]
@mohitmorepatil in react-native?

**Comment by mohitmorepatil** [comment]
> @mohitmorepatil in react-native?

Yes in react native

**Comment by mohitmorepatil** [comment]
@jamuhl Yes

**Comment by mohitmorepatil** [comment]
When we specify the properties lik i18nkey ,defaults,values in trans component then I am getting an error Text strings must be rendered within a text component

**Comment by jamuhl** [comment]
define parent on Trans (or in options)...and make sure you don't use plain strings...use Text

**Comment by mohitmorepatil** [comment]
@jamuhl Hello ,
Actually I am new to react native.i am using functional component and has defined navigator in App.js file and displayed screen 1 as my first screen of stacknavigator so parent component would be App component right?can you show me a syntactical example?

**Comment by jamuhl** [comment]
try

```js
import Reac from "react";
import { Text } from "react-native";

<Trans><Text>lorem ipsum</Text></Trans>

// or
<Trans parent={Text}>lorem ipsum</Text>

// you also can
i18next.init({
  // ...
  react: {
    // ...
    defaultTransParent: Text, // a valid react element
  }
});
```

All here: https://react.i18next.com/latest/trans-component

**Comment by mohitmorepatil** [comment]
` const dataArray = [
    {
      name: "rupert",
    },
    { name: "max" },
  ];

 <FlatList
        data={dataArray}
        keyExtractor={(item, index) => index}
        renderItem={(itemData) => (
          <Text>{t("list_map", { list_map_val: itemData.item.name })}</Text>
        )}
      />
//json code
"list_map": "My dogs named 

> `:{{list_map_val}}",`

`
How can we change language of the list rendered using Flatlist using tras component or using i18next or react-i18next

**Comment by jamuhl** [comment]
This is not an issue - but a how do I x in question...might be more suited for StackOverflow...or a development support

**Comment by mohitmorepatil** [comment]
<Trans i18nKey="list_map" parent={Text}>
  My dogs are named:
  <Text  i18nIsDynamicList>
     {['rupert', 'max'].map(dog => (<Text>{dog}</Text>))}
  </Textl>
</Trans>
// JSON -> "list_map": "My dogs are named: `<1></1>"```

when i add this code to JSX in react native it gives the error "Text strings must be rendered within a text component".Also when i remove the properties like i18nKey,defaults the errors go but nothing gets rendered inside  `<1></1>

**Comment by mohitmorepatil** [comment]
<Trans i18nKey="list_map" parent={Text}>
  My dogs are named:
  <Text  i18nIsDynamicList>
     {['rupert', 'max'].map(dog => (<Text>{dog}</Text>))}
  </Text>
</Trans>
// JSON -> "list_map": "My dogs are named: <1></1>"

When i add this code to JSX it throws error "Text shall be rendered inside text component.Also when i remove properties like i18nKey , defaults,components then the error goes but nothing gets rendered inside<1></1>

**Comment by jamuhl** [comment]
Then fix the error and wrap your stuff in a Text component...learn react, react-native...or hire someone supporting you...again - your problem is not an issue with react-i18next
