### ISSUE TITLE
Detect if child of I18nextProvider

### ISSUE THREAD

**Issue by malexandrum** [i18next/react-i18next#275]
We are building components that are supposed to be used in an app that uses react-i18next by using I18nextProvider as the root component. So the components we build are expecting to be wrapped inside I18nextProvider, but we want to test them without the wrapper. 
Is there a way to detect inside a component that it has been wrapped or not inside I18nextProvider? If we mount them without the wrapper and with the
`export default class translate()(ComponentName)`
there's this error:
`TypeError: Cannot read property 'options' of undefined
    at new Translate (webpack:///./~/react-i18next/dist/commonjs/translate.js?:70:32)`

So essentially we need to fallback when not wrapped and redefine t() to return the passed parameter.

**Comment by jamuhl** [comment]
hi @malexandrum did you already checked the testing guide: https://react.i18next.com/misc/testing.html

recommended way is to export the non extended component - so you could just pass a mock of the t function via props...

if you like to test extended you might do it like we did in our tests by passing i18n via context (enzym test): https://github.com/i18next/react-i18next/blob/master/test/translate.render.nsMode.spec.js#L42

**Comment by malexandrum** [comment]
@jamuhl thank you, double export enables us to test the non-translated version. It would still be nice if the error would only be a warning (when exporting the extended version but without i18 in context)

**Comment by jamuhl** [comment]
will check if i could catch that error and leave a warning about miss-configuration instead of throwing the error -> but on the other hand throwing the error shows there is a problem while console warnings get missed often...

**Comment by jamuhl** [comment]
@malexandrum leaving this like is - better having that as an error than a warning that gets missed. Not like more people not knowing why it does not work cause missing the warnings in console.
