### ISSUE TITLE
Trans component should not create a block element

### ISSUE THREAD

**Issue by wichert** [i18next/react-i18next#276]
Currently if you use the `Trans` component your text gets wrapped in a `div` element. This is a bit awkward since `div` is a block element, while you are generally looking for an inline element. Wouldn't it be better to use a `span` instead?

**Comment by jamuhl** [comment]
i think best will be to make it overridable like in the interpolate component: https://github.com/i18next/react-i18next/blob/master/src/interpolate.js#L74

This way a developer can choose which parent to set. What do you think?

Will add this as soon as possible. Or if you like you can provide a PR.

**Comment by wichert** [comment]
What I would *really* like is to have React 16 be ready so Trans could return the raw result without a containing element, but that will have to wait :). 

I've submitted a PR to make the element configurable.

**Comment by jamuhl** [comment]
haha...totally agree...removing that wrapping element would be best. As soon that lands we will remove that...would also help to make this work in react-native without setting parent to View.
