### ISSUE TITLE
escapeValue in React apps

### ISSUE THREAD

**Issue by dbendy** [i18next/react-i18next#277]
In all the examples in this repo (example: https://github.com/i18next/react-i18next/blob/master/example/webpack2/app/i18n.js#L30), I see:
```
escapeValue: false, // not needed for react!!
```

I am curious as to why `escapeValue` is not needed for React?  In my React app, I notice that when I set it to `false`, I lose the default `i18next` behavior whereby variables are treated as unsafe by default and only treated as safe when I use the `escapePrefix`.  When I set `escapeValue` to `true`, I am able to use the `escapePrefix` to determine if a variable should be treated as safe or not.  Why is this not needed for React?  It seems to me to be useful behavior, even in a React app.  Please explain.

**Comment by jamuhl** [comment]
when react renders text nodes to dom it will be escaped by the renderer already...so enabling it in i18next would lead to double escaping.

To output unescaped values with react you would have to use https://facebook.github.io/react/docs/dom-elements.html#dangerouslysetinnerhtml

**Comment by dbendy** [comment]
Got it.  What if I want the interpolation variables in my translation to be escaped, but not the rest of the string?  In that case, I don't see any other way but setting `escapeValue` to `true` and then wrapping it all in `dangerouslySetInnerHTML`.  Do you agee @jamuhl?

**Comment by jamuhl** [comment]
@dbendy if you like to set innerhtml that's the way to go...agree. You can pass escapeValue in t call too: `t(key, { interpolation: { escapeValue: true } });`

**Comment by dbendy** [comment]
Thanks for your help @jamuhl

**Comment by Noiwex** [comment]
It should be noted in README.md so no one will be confused.

**Comment by jamuhl** [comment]
https://react.i18next.com/getting-started -> has that in the first sample people see

@Noiwex not sure we need every detail in the readme ... ?
