### ISSUE TITLE
SSR Example without express?

### ISSUE THREAD

**Issue by 0xsven** [i18next/react-i18next#280]
Hi.
My client side implementation of react-i18next works very well. My app doesn't use express for server side rendering. So, I was wondering if someone can provide a small example on how to build the server part with node's http module?

**Comment by jamuhl** [comment]
for serverside rendering...? there are 3 samples...for that: https://react.i18next.com/misc/universal-rendering.html

in pure http module - i do not think anyone yet did this - but would be great if you could share your results with us

**Comment by mcquiggd** [comment]
I am also interested in this subject...  

I am looking at whether i18Next could be used with [ASP.Net Core's JavaScript Services](https://blogs.msdn.microsoft.com/webdev/2017/02/14/building-single-page-applications-on-asp-net-core-with-javascriptservices/); this handles server side rendering of SPAs by providing a server side Node environment which executes using WebPack dev server, rendering output to a string, which is returned to the browser. This sits behind the .Net Core Kestrel web server.

Using i18Next with browser language detection on the client, and xhr load of locales is working.

At the moment I have the issue of not being able to detect locale server side, to prerender according to the browser's accept-language and set that as the default locale. From what I can see, the general approach to language detection in the express-middleware could be reused with the ASP.Net Core approach... if only I can figure out how to plug it in ;-) 

There is also the option to do locale detection within ASP.Net Core, then pass that as a parameter to the render method.

And there are methods for passing data to and from the client, which would seem to be similar to how the selected locale and resources are passed from server to client in some examples.

Would love to hear if anybody has used i18Next with Asp.Net Core in this way... and if its possible to reuse all / most of the JavaScript code that has already been written.

**Comment by jamuhl** [comment]
Regarding language detection (or recover via cookie, session, what ever) this has to happen inside the request code => as a sample express middleware does this on every request using the middleware: https://github.com/i18next/i18next-express-middleware/blob/master/src/index.js#L23

From there you:
a) create a fixedT function to use inside request: https://www.i18next.com/api.html#getfixedt
b) create a new clone of main instance and change language on that: https://www.i18next.com/api.html#cloneinstance --> https://github.com/i18next/i18next-express-middleware/blob/master/src/index.js#L13 (on line 30 is the changeLanguage call)

**Comment by jamuhl** [comment]
closing for now...feel free to reopen

**Comment by kalpana-ideas2it** [comment]
Hi,
Client-side implementation of react-i18next works fine. My app is based on nodejs and loopback. Locale files are maintained in server only. Based on user input I need to send a locale object or file to a client then, render with  I18nextProvider. I have no idea about how to send to the locale to the client and where to store this.
I'd be happy if someone provides the solution or idea for this problem.
Thanks in advance

**Comment by jamuhl** [comment]
@kalpana-ideas2it i guess you will need to read through the express sample / code and reproduce this for your case. I guess no one will do the heavy lifting for you - at least not for free - i guess.

**Comment by jainam-shah-cygnet** [comment]
Any sample available of SSR with ASP .NET CORE or ASP .NET MVC project ?
