### ISSUE TITLE
Doesn't work with nested/deep child components

### ISSUE THREAD

**Issue by Clcll** [i18next/react-i18next#281]
I'm using react-i18next with redux and react-navigation 
My example like

`    const AppRouter = createNavigationContainer(StackNavigator({
        ['Screen1']: {screen: Screen1},
        ['Screen2']: {screen: Screen2},
    }, {headerMode: 'none'}));

    const AppRouterWrapper = ({dispatch, route}) => <AppRouter screenProps={{ t: i18n.getFixedT(), i18n: i18n }} navigation={addNavigationHelpers({dispatch, state: route})} />;

    const mapStateToProps = ({stocks: state}) => ({
        route: selectRouteObject(state),
        routes: selectRoutes(state),
        router: AppRouter,
    });

    const Navigation = connect(mapStateToProps)(AppRouterWrapper);

    const ReloadAppOnLanguageChange = translate('translation', {
        bindI18n: 'languageChanged',
        bindStore: false
    })(Navigation);
`

`        <Provider store={myStore}>
            <I18nextProvider i18n={ i18n }>
                <ReloadAppOnLanguageChange />
            </I18nextProvider>
        </Provider>`

In my Screens i get **screenProps** but I don't get i18n props. 
What's wrong in my code ? 
Thank you before hand

**Comment by jamuhl** [comment]
Hm...hard to say...more a question of router than the translate hoc

the screen props `screenProps={{ t: i18n.getFixedT(), i18n: i18n }}` are from your required module not from the translate hoc -> so nothing todo with react-i18next -> just a question of passing screenprops down ?!? or am i wrong?

**Comment by jamuhl** [comment]
closing for now...if you still feel this is an issue related to react-i18next please reopen this issue
