### ISSUE TITLE
Multiline support

### ISSUE THREAD

**Issue by vingrad** [i18next/react-i18next#282]
Can you please make a good solution to multiline support?

**Comment by jamuhl** [comment]
Could you please provide some more information what you like to achieve?

From guessing i would say you like to transform a translation having newlines `\n` to multiple react-dom `p` elements?!?

**Comment by jamuhl** [comment]
any additional info on this?

**Comment by jamuhl** [comment]
closing for now...as no detail information provided...please feel free to reopen

**Comment by WaldoJeffers** [comment]
@jamuhl I'd be very interesting in having react-i18next splitting `\n` to multiple react-dom `div` or `p`elements, if this hasn't been added already 😄

**Comment by jamuhl** [comment]
looks doable in some custom component...

basically split the result of a key by \n and map that array to divs...might not even need a component for that...

**Comment by jamuhl** [comment]
eg:

```js
render() {
  const items = t('myKey').split('\n');

  return (
    <div>
    { items.map(item => <p>{item}</p>) }
    </div>
  )
}
```

**Comment by WaldoJeffers** [comment]
Ok thanks for your quick reply @jamuhl , don't you think this would make sense if `react-i18n` had an option to do this automatically?

**Comment by jamuhl** [comment]
idk...basically i think this is just to trivial to add - i mean look at it...it's a .spilt and .map 

but if community agrees on it to be super useful to make a component out of it like:

```js
<List items={t('myKey').split('\n')} renderItem={item => <p>{item}</p>} />

or

<MappedSplitKey i18nKey="key" /> // defaultProps splitBy='\n', itemElement='p'
```

**Comment by WaldoJeffers** [comment]
Alright, thanks for this @jamuhl . Will use this workaround for now, and submit a PR if I find it too frustrating 😛

**Comment by annslittleflower** [comment]
i also found a way to do multiline stuff, here is example
"text": "bla bla bla. \nBetter photos by photo guideline \nIncluding"
then to tag you are going to insert this text you must add this css:
white-space: pre-wrap
????????????????
PROFIT!
p.s. guys please if you can edit formating of this message, im writing really in a hurry
p.p.s \n is so close to the words because white spaces also preserving

**Comment by ackvf** [comment]
Now what if I want to insert a `<br/>` element instead of wrapping it?

```
t('test').split('\n').reduce((r, c, x) => r ? [...r, <br key={x} />, c] : [c], null)
```
This is ugly enough to consider adding it to the library.

**Comment by adrai** [comment]
Couldn’t the Trans component be useful for this? https://react.i18next.com/latest/trans-component

**Comment by MariusMeiners** [comment]
this should be implemented for sure

**Comment by tigerabrodi** [comment]
@MariusMeiners Have you checked the Trans component as @adrai linked above?

**Comment by jamuhl** [comment]
The Trans component does not convert `\n` to `<br />` and for a good reason. Not everyone would expect this to happen. Linefeed belongs to text formatting and is not part of the HTML standard. Like @annslittleflower mentions if you need to support \n you need to use explicitly `<pre>` or set the correct css properties.

I wouldn't add this to Trans as it would have to be opt-in.

Adding a new component like https://github.com/i18next/react-i18next/issues/282#issuecomment-371865291 would be acceptable but to be honest, that is no rocket science and easy doable in userland. Like @ackvf show-cases there would be a significant difference in mapping to `<p>` vs adding a `<br />` which brings me back to @annslittleflower solution is the best option for doing it right.

**Comment by ErAz7** [comment]
@ackvf 
if you prefer JS approach, you can also use `dangerouslySetInnerHTML`. but obviously can be dangerous (vulnerable to XSS), should be carful not to use user input in them. I think this is cleaner since no logic is going on like in `.reduce`
```javascript
<div
    dangerouslySetInnerHTML={{
        __html: t('key').split('\n').join('<br />')
    }} />
```

**Comment by nathanpovo** [comment]
To use `<br/>` components inside your translations with the `<Trans/>` component, create a translation key-value similar to:

```json
{
  "message": "This is a line.<1/>This is another line.<1/>Yet another line"
}
```

Then, in your React component, use the `<Trans/>` component as follows

```tsx
<Trans i18nKey="message" components={{ 1: <br /> }} />
```

The translation value will be rendered as

![image](https://user-images.githubusercontent.com/17831160/212835810-a5cc9d3d-53e8-4093-a8aa-bcc6b985d564.png)

**Comment by jamuhl** [comment]
@nathanpovo or simpler: https://react.i18next.com/latest/trans-component#usage-with-simple-html-elements-like-less-than-br-greater-than-and-others-v10.4.0

**Comment by nathanpovo** [comment]
Unfortunately, that leads to a lot of guessing about the component index that i18n creates for you. Being explicit about the component indexes makes it simpler for me (even though you end up having to write a bit more code).

In my specific case, I also needed to leave the amount of `<br/>` components open ended because I am not sure how many line breaks the final client of the site will end up needing.

But that would work for anyone that doesn't have any issues similar to what I described above.

**Comment by jamuhl** [comment]
The link provided makes your sample change to:

To use <br/> components inside your translations with the <Trans/> component, create a translation key-value similar to:

```js
{
  "message": "This is a line.<br/>This is another line.<br/>Yet another line"
}
```

Then, in your React component, use the <Trans/> component as follows

```js
<Trans i18nKey="message" />
```

no need to know index...br is part of simple html element replacement

**Comment by Karmalakas** [comment]
> Unfortunately, that leads to a lot of guessing about the component index that i18n creates for you

The easiest way I found, is something like:
```json
{
  "message": "This is a <0>line</0>. This is <1>italic</1>. That's a <2>link</2>"
}
```
and 
```html
<Trans i18nKey="message" ><strong /><i /><a href="https://example.com" title=`${t("linkTitle")}` /></Trans>
```
