### ISSUE TITLE
Nextjs example doesn't work

### ISSUE THREAD

**Issue by vichyssoise** [i18next/react-i18next#283]
I try to run the example, and I got `Cannot read property 'home' of undefined`.

**Comment by jamuhl** [comment]
not having that issue...did you use the sample with next 3.0 ?!? we not yet tested it with v3...?!?

**Comment by gloorx** [comment]
Yes. I see.

**Comment by jamuhl** [comment]
Will update when having time....PR would be welcome.

**Comment by jamuhl** [comment]
sample was updated to latest - incl. a fix to having fallbackLng set on server...

closing again.
