### ISSUE TITLE
Allow other HOC options in global config

### ISSUE THREAD

**Issue by daltonjc** [i18next/react-i18next#284]
It would be quite nice if all the [translate hoc options](https://react.i18next.com/components/translate-hoc.html#the-translate-hoc-can-take-a-few-options) could be configured globally as well.  But it seems that only `wait` and `nsMode` can currently be set globally.

My particular use case is we want our entire project to use the same `translateFuncName` throughout the project as a convention, but as-is we must define this in a couple hundred components and not miss any: `return translate(['admin'], {translateFuncName: 'text'})(AdminThing);`

While I'm only currently concerned about `translateFuncName` I imagine the same would come up for the other existing options as well.

**Comment by jamuhl** [comment]
Will try to get that into the next version...providing a PR would speed this up...but no must ;)

**Comment by jamuhl** [comment]
should be possible with react-i18next@5.0.0

but you can't set the translateFuncName by i18next options as we need that value upfront to define the childContextTypes, but there is a setDefaults function on translate hoc now:

```
import translate from 'react-i18next';

translate.setDefaults({
  wait: false,
  withRef: false,
  bindI18n: 'languageChanged loaded',
  bindStore: 'added removed',
  nsMode: 'default',
  translateFuncName: 't'
});
```

for details please read the changelog.

**Comment by daltonjc** [comment]
Fair enough, thanks a lot!

**Comment by daltonjc** [comment]
@jamuhl maybe this is crazy town, but with this setDefaults() function you've added, I wonder if we could set the `i18n` option the same way?  I'm hopeful that would remove the need for the provider without having to pass it in as an option in all the components.  Is that doable and desirable?

**Comment by jamuhl** [comment]
try react-i18next@5.1.0

```js
import translate from 'react-i18next';
import i18n from './i18n';

translate.setI18n(i18n);
```

not yet had time to document it on react.i18next.com

**Comment by daltonjc** [comment]
Worked like a charm!  Thanks so much @jamuhl :)
