### ISSUE TITLE
Use Key as fallback not working on changeLanguage

### ISSUE THREAD

**Issue by fouadmasoud** [i18next/react-i18next#286]
Below is my current code. My english translation files only has keys and no values

{
"Translate this text" : ""
}
When the page loads everything is ok. Since no value is found the key is used as the fallback. When I change the language from en > de for example that works as well. When I switch it back to en, it doesn't use the key to fall back and the page stays in de even though the language is changed.

PS. This exact setup is working great in my REACT app. But this is required for a single pure javascript page.

```
i18next
      .use(i18nextXHRBackend)
      .use(i18nextBrowserLanguageDetector)
      .init({
        debug: true,
        nsSeparator: false,
        keySeparator: false,
        fallbackLng: false,
        returnEmptyString: false, // Consider empty string values as invalid translations.
        returnNull: false,
        backend: {
          loadPath: './locales/{{lng}}/{{ns}}.json'
        },
        detection: { // Settings for language detector
          order: ['querystring', 'cookie', 'navigator'],
          lookupQuerystring: 'langPref',
          lookupCookie: 'tableauLang',
          caches: ['cookie'],
          cookieMinutes: 525600, // one year
        }
      }, function (err, t) {
        jqueryI18next.init(i18next, $);
        $('[data-i18n]').localize();

        $('.language-link').click(function () {
          const langCode = this.getAttribute('hrefLang');
          i18next.changeLanguage(langCode, function () {
            $('[data-i18n]').localize();
          });
        });
      });
```

**Comment by jamuhl** [comment]
hm...jquery plugin does something very useful but also disabling what you want to do. The plugin always takes the content (innerHtml, text, ...) as a default value -> that's super useful if using the saveMissing feature.

https://github.com/i18next/jquery-i18next/blob/master/src/index.js#L37

so basically once the content is loaded in german and you change the language back to `en` it takes the german content as default.

setting `parseDefaultValueFromContent` to false: https://github.com/i18next/jquery-i18next#initialize-the-plugin should solve this.

(relevant code: https://github.com/i18next/jquery-i18next/blob/master/src/index.js#L32)

**Comment by fouadmasoud** [comment]
That worked thanks!

Also, you've been extremely responsive and helpful in using the i18n libraries, so thank you :D
