### ISSUE TITLE
Multiple re-renders if wait: false

### ISSUE THREAD

**Issue by SDSLeon** [i18next/react-i18next#292]
"i18next": "9.0.0"
"react-i18next": "5.2.0"

@translate(['layout'], { wait: false })
![image](https://user-images.githubusercontent.com/6071034/29810004-e9859aac-8ca6-11e7-9324-86132ee2dc03.png)

@translate(['layout'], { wait: true })
![image](https://user-images.githubusercontent.com/6071034/29810015-f3556d1e-8ca6-11e7-8d93-3f19cf9efe15.png)

and one more question:
It's possible to change how wait work? From "not render component" to 'return empty string from t() until load'?

**Comment by jamuhl** [comment]
we can't change how wait works - wait is here to assert we are ready to display translations.

what you want is to change what gets returned on calling t if not yet loaded the translations (which results technically in a missing key detection). https://www.i18next.com/configuration-options.html#missing-keys

you can set `parseMissingKeyHandler` on init of i18next.

But this will result in initial rerenders for the first render as we trigger a rerender onchange of loaded  translations.

so you can have - wait or rerenders
