### ISSUE TITLE
Docs not available

### ISSUE THREAD

**Issue by jukra** [i18next/react-i18next#293]
Hi!
Just noticed that your GitBook is not readable:

> Not Found
> Book has been detected as spam and suspended

**Comment by adrai** [comment]
WT*!!! Why?

**Comment by jamuhl** [comment]
Up again...

**Comment by gt510** [comment]
The same ... How to resove it?

**Comment by jamuhl** [comment]
https://react.i18next.com/ -> works for me

**Comment by nopara73** [comment]
It happened to my stuff as well. Did you resolve it by contacting the support? https://programmingblockchain.gitbook.io/programmingblockchain
