### ISSUE TITLE
Translate State Value

### ISSUE THREAD

**Issue by fouadmasoud** [i18next/react-i18next#294]
I have a state string I'm translating like this:

```
this.setState({ errorMessage: t('This email address is already in use.') + t('Please try again.') });

<div>{this.state.errorMessage}</div>
```

When the page first loads the translation works. If I change the language it's not translated. Should this work or is it a bug?

**Comment by jamuhl** [comment]
That's expected. Changing the language does trigger a rerender on the component tree -> but components do not get recreated -> so the content of state.errorMessage still is a translated string that was set in old language.

So better solution is setting the key to state and using t function inside render:

```js
//...
<div className="error">{t(this.state.errorMessageKey)}</div>
//...
```

This way you can even show a generic error if that is not found like: https://www.i18next.com/essentials.html#multiple-fallback-keys

Further you should avoid string concatenation `t('This email address is already in use.') + t('Please try again.')` -> this makes translating to other languages harder; Simpler just use the nesting feature of i18next: `t('This email address is already in use. ${Please try again.}')`

-> https://www.i18next.com/nesting.html

**Comment by jamuhl** [comment]
And if you like react-i18next - don't forget to star it and have a look at https://locize.com - our localization as a service tier (our way of trying to get all those i18next related project supported instead of using opencollect)

**Comment by WindDancerUBI** [comment]
> That's expected. Changing the language does trigger a rerender on the component tree -> but components do not get recreated -> so the content of state.errorMessage still is a translated string that was set in old language.
> 
> So better solution is setting the key to state and using t function inside render:
> 
> ```js
> //...
> <div className="error">{t(this.state.errorMessageKey)}</div>
> //...
> ```
> 
> This way you can even show a generic error if that is not found like: https://www.i18next.com/essentials.html#multiple-fallback-keys
> 
> Further you should avoid string concatenation `t('This email address is already in use.') + t('Please try again.')` -> this makes translating to other languages harder; Simpler just use the nesting feature of i18next: `t('This email address is already in use. ${Please try again.}')`
> 
> -> https://www.i18next.com/nesting.html

I am react bignner,I have the same problem above, I am happy to see you answer,but I can't understand "t(this.state.errorMessageKey)"，what is "errorMessageKey" means？

**Comment by jamuhl** [comment]
it's `this.setState({ errorMessage: t('This email address is already in use.') + t('Please try again.') });
`

Before he set translated value to state -> which gets not changed anymore on language change as it's fixed as a string in state.

so just saving a key to state and pass the key to the translation function will assert the content gets retranslated on every rerender in the correct language

**Comment by Sotatek-HuyTran3** [comment]
@jamuhl if my string have variable then how can we resolve this?
example ;

```
const amount = 10;
this.setState({ errorMessage: t('This email address is already in use.', {amount: amount}) + t('Please try again.') });

<div>{this.state.errorMessage}</div>
```

**Comment by jamuhl** [comment]
@Sotatek-HuyTran3 what about:


```js

const amount = 10;
this.setState({ errorMessageKey: 'myKeyForThisError', errorMessageOptions: { amount } });


<div>{t(state.errorMessageKey, state.errorMessageOptions)}</div>

```

**Comment by Sotatek-HuyTran3** [comment]
@jamuhl Actually I am using react hook and have a case like this:

```
const [msg, setMessage] = useState<string>('')
const amountCurrency = 'RM 10.29'
 setMessage(`Only ${amountCurrency} is allowed for a single transaction. Please reduce purchase amount to proceed.`)
 
 <div>t(msg)</div>
```
Please help

**Comment by jamuhl** [comment]
@Sotatek-HuyTran3 Did you even try...?

```js
// in JSON translation
"myKeyForThatMsg": "Only {{amountCurrency}} is allowed for a single transaction. Please reduce purchase amount to proceed."

// your code
const [key, setKey] = useState<string>('')
const amountCurrency = 'RM 10.29'
 setKey(`myKeyForThatMsg`)
 
 <div>t(key, { amountCurrency })</div>
```

**Comment by Sotatek-HuyTran3** [comment]
@jamuhl It's working well. Thank you
