### ISSUE TITLE
Default English dictionary

### ISSUE THREAD

**Issue by aniruddhashevle** [i18next/react-i18next#295]
Does it creates default English dictionary?
Basically in [i18n](https://www.npmjs.com/package/i18n)
When we write <%= __('Hello') %> in html (according to our template), it automatically creates en.json file and adds new property {'hello' : 'hello'} for english dictionary.

Does this plugin creates default english dictionary or json file explained above?

**Comment by jamuhl** [comment]
yes/no:

serverside rendering and using express-middleware: yes
clientside rendering and having a backend: yes

everytime i18next access a key not existing it will call the the missing handler on backend (for xhr will make a post to backend, for express middleware with fs-backend save to filesystem).

so for clientside there needs to be a server taking that post call and save that (can be done with express or nodejs - for other backends you will need to create that yourself)

saveMissing: https://www.i18next.com/configuration-options.html#missing-keys
express: https://github.com/i18next/i18next-express-middleware

see for working sample: https://github.com/i18next/react-i18next/tree/master/example/nextjs

or if you like it the easy way: https://www.youtube.com/watch?v=9NOzJhgmyQE
use https://locize.com ;)

**Comment by aniruddhashevle** [comment]
Now that makes sense. Thanks!

**Comment by jamuhl** [comment]
If there is anything else that is unclear - feel free to reopen this issue...closing for now
