### ISSUE TITLE
Testing containers

### ISSUE THREAD

**Issue by ezuk** [i18next/react-i18next#296]
Hi there,

I've read the advice about exporting an undecorated component -- that doesn't quite work for me in this case, as the container imports the decorated component, and I am testing the container (and the rendered component by extension).

So I've been trying to do something [like this](https://github.com/i18next/react-i18next/blob/master/test/translate.render.spec.js) -- i.e, not mock anything but actually render out the translations as part of my test. 

No luck there, either... So I figured I'd ask: Has anyone tested a container that imports a decorated component? If so, could you share your tests and setup? Jest with Enzyme here.

**Comment by jamuhl** [comment]
No luck there, either... what does not work? i guess loading translations via xhr (but just guessing).

If so you might just set lng to 'cimode' that way i18next will return keys instead of real translations...

**Comment by ezuk** [comment]
my config looks like this:

```javascript
import i18n from 'i18next';

i18n
  .init({
    backend: {
      loadPath: '/locales/{{lng}}/{{ns}}.json',
      addPath: '/locales/{{lng}}/{{ns}}',
    },
    fallbackLng: 'cimode',
    debug: true,
    saveMissing: false,

    interpolation: {
      escapeValue: false, // not needed for react!!
    },

    // react i18next special options (optional)
    react: {
      wait: true, // set to true if you like to wait for loaded in every translated hoc
      nsMode: 'default', // set it to fallback to let passed namespaces to translated hoc act as fallbacks
    },
  });


export default i18n;
```

And as for "what does not work" - I'm honestly not sure as I'm not getting any errors. Test looks like this:

```
 import { Provider } from 'react-redux';
  import { mount } from 'enzyme';
  import { I18nextProvider } from 'react-i18next';
  import configureStore from 'redux-mock-store';
  import ContactTable from './ContactTable';
  import actionTypes from '../constants';
  import i18n from '../i18nForTests';

  const mockStore = configureStore([]);
~ const store = mockStore({ contacts: [
+   {
+     id: 1,
+     avatar: 'https://api.adorable.io/avatars/40/joe.png',
+     name: 'David Mitchell',
+     email: 'dmitchell@gmail.com',
+     phone: '(415)123-1234',
+     last_activity: { what: 'Contact created', when: 'Today' },
+   },
+ ] });

  it('dispatches SORT_TABLE', () => {
    const enzymeWrapper = mount(
      <Provider store={store}>
        <I18nextProvider i18n={i18n}>
          <ContactTable />
        </I18nextProvider>
     </Provider>
    );
   console.log(enzymeWrapper.html());
    enzymeWrapper.find('th').simulate('click');
    const actions = store.getActions();
    expect(actions).toEqual([{ type: actionTypes.SORT_TABLE }]);
  });
```

and running it gives this:

```
Method “simulate” is only meant to be run on a single node. 0 found instead.
```

And the console.log gives nothing, as if the component renders no text at all. But it isn't empty, it does render text in the browser (fully works, in fact).

What makes this tricky is that it doesn't explode and doesn't produce any errors at all... Any thoughts? Thank you for taking the time to reply!

**Comment by jamuhl** [comment]
i think the issue is your i18next config for test is set to load per xhr and translate hoc is globally set to wait for load to finish before rendering a component so translations are ready:

```
i18n
  .init({
resources: {},
    //backend: {
    //  loadPath: '/locales/{{lng}}/{{ns}}.json',
    //  addPath: '/locales/{{lng}}/{{ns}}',
    //},
    fallbackLng: 'cimode',
    debug: true,
    saveMissing: false,

    interpolation: {
      escapeValue: false, // not needed for react!!
    },

    // react i18next special options (optional)
    react: {
wait: false,
      // wait: true, // set to true if you like to wait for loaded in every translated hoc
      nsMode: 'default', // set it to fallback to let passed namespaces to translated hoc act as fallbacks
    },
  });
```

should stop that

**Comment by ezuk** [comment]
Yes! Thank you! :) Docs PR submitted: https://github.com/i18next/react-i18next-gitbook/pull/2

**Comment by jamuhl** [comment]
awesome....and a lot of kudos for updating the docs...
