### ISSUE TITLE
Keep many contextual translation files (e.g. one per component) instead of global ones

### ISSUE THREAD

**Issue by gnapse** [i18next/react-i18next#299]
One thing I find great about React 's de-facto approach to project organization is that you group files by feature instead of by their function or technology. So you have a feature directory, where you keep that feature's components, css stylesheets, redux actions/reducers, etc. The only thing breaking that pattern for me right now is the translations, which are kept in a global file per language, and this is becoming unmanageable. Even if I split it into smaller files (which I think I saw an example of somewhere and i18next supports it), I'd still like to be able to have a component's translations closer to the component implementation file. Is this possible with react-i18next? If so, how? Thanks in advance.

**Comment by jamuhl** [comment]
Like said i see your point...i18next is rather flexible (built for that).

Depending on what you like to reach there are options:

a) Bundling into your app using webpack

you can go the approach of https://github.com/atroo/i18next-resource-store-loader just make it load not from a single path

b) loading via xhr

Assert the files get hosted (copied to public folder) using a appropriate loader. You could write a own backend to do solve the path issue: https://www.i18next.com/misc/creating-own-plugins.html#backend

c) Just use json loader and push stuff into i18next

https://www.i18next.com/api.html#addresourcebundle

d) create a i18next instance per file and pass that to translate hoc via props

https://www.i18next.com/api.html#cloneinstance (or create)
https://react.i18next.com/components/translate-hoc.html#the-translate-hoc-can-use-some-props-it-gets-passed

But personally while i agree it's great to have styles,...right next to components i'm not sure it's awesome for translations  -> you will need to pass those to translators so best solution would be having them not in your code base at all ;) ---> using eg. https://locize.com. But still if you prefer to do so - i'm rather sure i18next is one of the only frameworks being flexible enough to do so. Building a own i18n framework might be an other option - but are there not already enough frameworks for that??

**Comment by gnapse** [comment]
I see the advantage of something like locize (from a quick glance of what it does or seems to me it does). But still, not having the translations next to the code that use them has some issues:

- You refactor code and at some point some translation strings are no longer used, but the fact that they're kept far away from that code makes it difficult to detect them and remove them. Over time you can end up with huge translation files with lots of content that is not really being used. I've seen this happen in long-lived rails apps, and the approach is intrinsically the same so I don't see why this would not happen in a i18n library with global translation files.

- Large translation files, and the fact that usually projects keep one per supported language, elevate the chances that translation files from different languages start to diverge. They not only diverge in content (e.g. the English file has some strings that the Spanish file doesn't) but also in structure (e.g. things are not declared in different language files in the same order) making it more difficult to maintain them and keep them in sync.

Can i18next and react-i18next help mitigate these problems in some other way that diverges less from its more normal intended use? I'm already using it in my project, but in the "global translation files" find of way, and although my project is still young, I want to avoid having the above issues in the long run.

**Comment by jamuhl** [comment]
locize can provide something like: https://www.youtube.com/watch?v=9NOzJhgmyQE

a) no longer used translations

An option is to use one of the extractions tool and diff against your json

- http://i18next.github.io/i18next-scanner/
- https://github.com/i18next/i18next-parser
- others: https://www.i18next.com/plugins-and-utils.html#utils

for locize we plan to provide a functionality so i18next will send keys that where used to an endpoint so one can see which keys where not used for some months (should be save to remove them if not error messages ;)). Or to use one of the extractors to send which keys still are in the code base so we could update a lastUsed value and show users which keys are considered save to be removed.

b) diverging localization files

locize makes that easy as it enforces consistency against source language. Beside that something like https://github.com/jwbay/i18next-json-sync could help.

or using something like sdl trados and on every release translate everything from scratch using the current source files and translate using the translation memory.

**Comment by gnapse** [comment]
Ok, thanks for all the info. I think this closes the issue, as there are many options to explore to either achieve what I wanted, or alternative solutions that mitigate the problems of global translation files.

**Comment by bradvogel** [comment]
I found this issue when searching for a solution to co-locate is18next localization files with React components that use them. I agree with the reporter that this is much more maintainable when working with a large app.

Our solution is to provide utility methods that make it easy to load separate localization files. [See file here](https://gist.github.com/bradvogel/3e792f4f545b7ebd2cce8225cc12a114).

#### locale.en.json

```json
{
  "myTranslatedText": "translated text"
}
```

#### MyFunctionalComponent.js

```jsx
import locale from './locale.en.json';
import { useTranslationLocale } from '~/utils/i18n';

export function MyFunctionalComponent() {
  const { t } = useTranslationLocale(locale);
  return <p>{t('myTranslatedText')}</p>;
}
```

#### MyClassComponent.jsx

```jsx
import locale from './locale.en.json';
import { withTranslationLocale } from '~/utils/i18n';

class MyClassComponent extends React.Component {
  render() {
    const { t } = this.props;
    return <p>{t('myTranslatedText')}</p>;
  }
}

export default withTranslationLocale(locale)(MyClassComponent);
```

For now, since we're using `import locale from './locale.en.json';`, localization files will be compiled into the app. In the future when we introduce support for other languages, we'll add files for those languages such as `locale.de.json`. Then we'll build a custom webpack loader to import the correct `locale.*.json` file for the language bundle.

**Comment by jamuhl** [comment]
Just for people finding this issue. Please keep in mind while this might be a good solution looked at from the developer perspective...this approach might make it harder to maintain for the people doing the translations.

**Comment by longto** [comment]
I see that I18n scanner can collect locale string from all over the project into a json file. Why it cannot do the vice versal : populate string from i18n to the whole project ?

**Comment by DirkLachowski** [comment]
> this approach might make it harder to maintain for the people doing the translation work.

Not necessarily. We are using Crowdin for translations were you can use as many source files as you like. Still, translators do only see a single list with text to translate. Missing features in a translation tool shouldn't be a reason for code smells - and having translations far away from the component using them feels like a smell. Will bite you as soon as you start to build micro frontends.

**Comment by jamuhl** [comment]
@DirkLachowski not talking about presentation in translation management...our locize.com can do that too (and if you're using i18next you should also consider using locize to support our work).

Still, personally I prefer files per application section plus commonly used terms which works super easy when using something like HTTP backend (or locize CDN) - but that might be a taste.

I'm also not a fan of having folders like:

`components/MyComponent.js`
`components/MyComponent.en.js`
`components/MyComponent.de.js`
`components/MyComponent.it.js`
`components/MyComponent.fr.js`
`components/MyComponent.es.js`
`components/MyComponent.pt.js`
`components/MyComponent.....js`
`components/MyComponent2.js`
`components/MyComponent2.en.js`
`components/MyComponent2.de.js`
`components/MyComponent2.it.js`
`components/MyComponent2.fr.js`
`components/MyComponent2.es.js`
`components/MyComponent2.pt.js`
`components/MyComponent2.....js`

- feels more noisy to me...plus you will have more work when syncing those files with your tm tool...
- you will depend on a bundler capable of lazy loading

But as shown above by @bradvogel  you can write a component doing all needed...

**Comment by DirkLachowski** [comment]
@jamuhl We are building micro frontends using bit.dev, so there is no such thing as a global translation file - there's not even an application to start with. Each component is self contained, so the translations are an integral part of it.

**Comment by jamuhl** [comment]
@DirkLachowski if components are self-contained...they should be built with i18n in mind. Every visible text should be possible to pass in as a prop - so it makes no difference how you handle translations for your project as all texts are passed in during render time.

eg: `<SomeComponent label="someTranslatedText" someOtherText="someOtherTranslatedText" .... />`

**Comment by DirkLachowski** [comment]
@jahmul Feels like you don't get the idea of micro frontends. Take a component like:

```
<SalesContactForm />
```

That's a component a marketer can drop on any landing page he's building and that

- renders a contact form
- with the right form fields
- and translated labels and marketing copy
- so that we have a consistent presentation across a whole site or app

The fictional marketer using that form isn't interested in translating the form, he doesn't even know what the required fields are - thus "self contained". They only want to collect a lead. And it doesn't stop here. We have components like:

- `<ButtonReadMore />`
- `<ButtonSave />`

This buttons get incorporated in bigger components (like the `<SalesContactForm />`).

The translation of such components is part of the component. Each component is an independent npm module. Have a look at bit.dev, they have a nice demo of what micro frontends are and how they work.

But i got you. There are no plans to move translation files closer to the components using them, so building our own solution looks like the way to go here.

**Comment by jamuhl** [comment]
@DirkLachowski I do get the idea...I'm not overly stupid ;)...

> But i got you. There are no plans to move translation files closer to the components using them, so building our own solution looks like the way to go here.

I did not say that - regarding react-i18next there is everything there to do so, either going @bradvogel way and creating an additional instance or by adding resources using https://www.i18next.com/overview/api#addresourcebundle

In best case you will do some dynamic import for the translations - as you don't want to bloat the component size by bundling all translations.

**Comment by worthy7** [comment]
I think that the localization files should be with their relevant modules.
The issue of mass translating some files, is a tooling one. There should be a tool that can do that management but like the files where they are.

**Comment by jamuhl** [comment]
@worthy7 there is no one forcing you to not have the localization files beside the relevant modules...we're also open to accept PR's helping with doing so - but at my current knowledge it's not that easy (needs some script like @mizozobu did and some wrapping like @bradvogel did to import that namespace file named like the displayName of the component).

**Comment by layerok** [comment]
I want to share my solution in case someone finds it useful.

I'm using Vite, but the same approach should work with other bundlers that support dynamic imports

This is how it looks in a component:

```tsx

await loadTranslations('SelectComponent');

export const SelectComponent = () => {
    const { t } = useTranslation(TranslationNamespaceEnum.SelectComponent)
}

```

The `loadTranslations` function knows where to import translations from with the help of `getTranslationsPath`.
`getTranslationsPath` function maps a namespace and language to the  location of the corresponding translation file

```tsx
export const getTranslationsPath = (
  ns: string,
  lang: string,
): null | string => {
 
  if(ns === 'SelectComponent') {
      return `src/components/Select/locales/${lang}.json`
  }
 
  return null;
};
```

Here is the `loadTranslations` implementaion. This function load translation files and adds it on `i18n` instance using `i18n.addResourceBundle`
```tsx
import { i18n } from "src/lib/i18next/i18next.ts";
import { getTranslationsPath } from "src/lib/i18next/getTranslationsPath.ts";

const defaultLangs = ["en", "de"];

export const loadTranslations = async (
  ns: string,
  langs: string[] = defaultLangs,
) => {
  const jsonFiles = import.meta.glob<
    Record<string, any> | { default: Record<string, any> }
  >("/src/**/*.json");

  const translations = await Promise.all(
    langs.map(async (lang) => {
      const translationPath = getTranslationsPath(ns, lang);
      const key = "/" + translationPath;
      const loadTranslationsFn = jsonFiles[key];
      if (!loadTranslationsFn) {
        console.error(
          `Translations for [${ns}] namespace were not found at [${key}]`,
        );
        return {};
      }

      return loadTranslationsFn();
    }),
  );

  const resources = langs.reduce(
    (acc, lang, index) => {
      const translations_ = translations[index]?.default
        ? translations[index]?.default
        : translations[index];

      return {
        ...acc,
        [lang]: translations_,
      };
    },
    {} as Record<string, any>,
  );

  Object.keys(resources).forEach((key) => {
    i18n.addResourceBundle(key, ns, resources[key]);
  });

  return resources;
};

```

**Comment by layerok** [comment]
You can also implement this approach as a custom i18next backend.

For example:

```tsx
import { type BackendModule } from "i18next";

export type ViteDynamicImportBackendOptions = {
  loadPath: (ns: string, lang: string) => string | null;
};

let options: ViteDynamicImportBackendOptions = {
  loadPath: (ns, lang) => `src/locales/${ns}.${lang}.json`,
};

const backend: BackendModule<ViteDynamicImportBackendOptions> = {
  type: "backend",
  init: function (services, backendOptions, i18nextOptions) {
    options = backendOptions;
  },
  read: async function (language, namespace, callback) {
    const jsonFiles = import.meta.glob<
      Record<string, any> | { default: Record<string, any> }
    >("/src/**/*.json");

    const translationPath = options.loadPath(namespace, language);
    const key = "/" + translationPath;
    const loadTranslationsFn = jsonFiles[key];
    if (!loadTranslationsFn) {
      callback(
        new Error(
          `i18next-vite-dynamic-import-backend: error loading translations for ${namespace} namespace and ${language} language`,
        ),
        null,
      );
      return null;
    }

    loadTranslationsFn()
      .then((translations) => {
        const resources = translations?.default
          ? translations?.default
          : translations;
        callback(null, resources);
      })
      .catch((error) => {
        callback(error, null);
      });
  },
};
export default backend;

```

Then register the backend with i18next:
```tsx
import i18next from "i18next";
import { initReactI18next } from "react-i18next";

import ViteDynamicImportBackend, {
  type ViteDynamicImportBackendOptions,
} from "i18next-vite-dynamic-import-backend";

const loadPath = (ns: string, lang: string): string | null => {
   if(ns === 'SelectComponent') {
        return `src/components/Select/locales/${lang}.json`
   }
   return null;
}

i18next.use(initReactI18next).use(ViteDynamicImportBackend).init({
  backend: {
    loadPath,
  },
  resources: {},
  lng: 'en',
  partialBundledLanguages: true,
});

```

With this approach, i18next itself controls when a namespace needs to be loaded.

The backend receives the requested language and namespace, resolves the corresponding file through loadPath, dynamically imports it through Vite's import.meta.glob(), and returns the translation resources back to i18next.

This means components can use the standard i18next API without manually importing translation files:

const { t } = useTranslation("SelectComponent");

As long as i18next requests that namespace, the backend can load the corresponding translation file dynamically.
