### ISSUE TITLE
TypeError: _reactI18next2.default is undefined

### ISSUE THREAD

**Issue by 01Kuzma** [i18next/react-i18next#301]
Hi!
It's very pity, that there is no any good step-by-step tutorials regarding react-i18next setup and use.
I'm trying to recreate example from repo, but receiving this error:
`TypeError: _reactI18next2.default is undefined`
My index.js is:
```
import React from 'react';
import ReactDOM from 'react-dom';
import { BrowserRouter, Route, Switch } from 'react-router-dom';
import { ModalContainer } from 'react-router-modal';
import LandingPage from './components/villages/Landing Page.js';
import WOW from 'wowjs';

import { I18nextProvider } from 'react-i18next';
import i18n from './i18n';
import registerServiceWorker from './registerServiceWorker';

class App extends React.Component {
  componentDidMount() {
    new WOW.WOW().init();
  }

  render() {
    return (
      <div>
        <LandingPage/>
        <ModalContainer />
      </div>
    )
  }
}

ReactDOM.render(
    <I18nextProvider i18n={ i18n }>
      <BrowserRouter>
          <App />      
      </BrowserRouter>
    </I18nextProvider>,
     document.getElementById('app')
);
registerServiceWorker();
```

I've put both i18n.js and registerServiceWorker.js in my folder. In i18n.js.js I've commented the locize imports.

**Comment by jamuhl** [comment]
Would be great if you write one...there is a getting started which is not more than https://react.i18next.com/getting-started.html

or bins: https://www.webpackbin.com/bins/-KoCD3kvA-4QJNaHpkxi

and endless samples: https://github.com/i18next/react-i18next/tree/master/example

=> looking at your code i don't see a place where you try to import an default from react-i18next?

`_reactI18next2.default` is not part of the code provided from react-i18next -> wasn't able to find that in dist. Could you check where this error comes from?!?

**Comment by 01Kuzma** [comment]
Thank you for you answer!
Now I copied you provided sample and getting another error: `TypeError: t is not a function`.
The index.js looks like:
import React from 'react';
import ReactDOM from 'react-dom';
import { BrowserRouter, Route, Switch } from 'react-router-dom';
import { ModalContainer } from 'react-router-modal';
import LandingPage from './components/villages/Landing Page.js';
import WOW from 'wowjs';
import { translate, Trans } from 'react-i18next';
```

const InnerComponent = translate()(
  ({name}) => <Trans>some-test</Trans>
);

const MiddleComponent =  ({Component}) => <div><Component /></div> ;

const OuterComponent = translate()(
  class extends React.Component {
      render() {
          console.log('this loops like crazy...');
          return (
              <div>
                  <MiddleComponent Component={() => <InnerComponent name="qwe"/>}/>
              </div>
          );
      }
  }
);


class App extends React.Component {
  componentDidMount() {
    new WOW.WOW().init();
  }

  render() {

    const { t, i18n } = this.props;
    
    const changeLanguage = (lng) => {
      i18n.changeLanguage(lng);
    }

    return (
            <div>

              <div className="App">
                <OuterComponent />
                <div className="App-header">
                  <h2>{t('Welcome to React')}</h2>
                  <button onClick={() => changeLanguage('de')}>de</button>
                  <button onClick={() => changeLanguage('en')}>en</button>
                </div>
                <div className="App-intro">
                  <Trans>
                    To get started, edit <code>src/App.js</code> and save to reload.
                  </Trans>
                </div>
                <div style={{ marginTop: 40 }}>
                  <a href="https://react.i18next.js">Learn more: https://react.i18next.js</a>
                </div>
              </div>


                <LandingPage/>
                <ModalContainer />
              </div>
            )
          }
        }

ReactDOM.render(
      <BrowserRouter>
          <App />      
      </BrowserRouter>,
     document.getElementById('app')
);
```

**Comment by jamuhl** [comment]
There is missing the `i18nextProvider`!

```
ReactDOM.render(
<I18nextProvider i18n={ i18n }>
      <BrowserRouter>
          <App />      
      </BrowserRouter></I18nextProvider>,
     document.getElementById('app')
);
```

**Comment by 01Kuzma** [comment]
Added the `i18nextProvider` to ReactDOM.render and getting closer to final results.
Also I've modified the import with `import { translate, Trans, I18nextProvider } from 'react-i18next';`
But now the error is : `ReferenceError: i18n is not defined`

**Comment by jamuhl** [comment]
did you install i18next? npm i i18next --save?!? i18next instance is needed so `import i18n from 'i18next';` is correct

**Comment by 01Kuzma** [comment]
Yes, the i18next was missing. I did `npm install i18next --save` and now I get another error :(
`TypeError: t is not a function`

**Comment by jamuhl** [comment]
look it is rather simple:

i18nextProvider -> pass i18n to it -> the component will pass i18n down to every component by using react context

translate hoc -> will take i18n from context -> will pass down t function via props and context

Trans, Interpolate -> will need need to be nested inside translate hoc

So to work nest Trans into translate hoc into i18nextProvider

**Comment by 01Kuzma** [comment]
Thank you for the answer!
Did I understood clearly, that the problem is in the variable scope and nesting?
Sorry for such simple questions...
I changed the **index.js** to:

```
import React from 'react';
import ReactDOM from 'react-dom';
import { BrowserRouter, Route, Switch } from 'react-router-dom';
import { ModalContainer } from 'react-router-modal';
import LandingPage from './components/villages/Landing Page.js';
import WOW from 'wowjs';

import { translate, Trans, I18nextProvider } from 'react-i18next';
import {i18next } from 'i18next';
import i18n from './i18n';

class App extends React.Component {
  componentDidMount() {
    new WOW.WOW().init();
  }

  render() {
    return (
            <div>
              <LandingPage/>
              <ModalContainer />
            </div>
            )
          }
        }

ReactDOM.render(
  <I18nextProvider i18n={ i18n }>
    <BrowserRouter>
      <App />      
    </BrowserRouter>
  </I18nextProvider>,
    document.getElementById('app')
);
```

And added i18n functions inside particular component, **TechnologiesBlock.js**:

```
import React from 'react';
import ReactDOM from 'react-dom';


import { translate, Trans, I18nextProvider } from 'react-i18next';
const InnerComponent = translate()(
  ({name}) => <Trans>some-test</Trans>
);

const MiddleComponent =  ({Component}) => <div><Component /></div> ;

const OuterComponent = translate()(
  class extends React.Component {
      render() {
          console.log('this loops like crazy...');
          return (
              <div>
                  <MiddleComponent Component={() => <InnerComponent name="qwe"/>}/>
              </div>
          );
      }
  }
);

class TechnologiesBlock extends React.Component {
  render() {
    
    const { t, i18n } = this.props;
    
    const changeLanguage = (lng) => {
      i18n.changeLanguage(lng);
    }
    return (
      <div className="container">
		             
		<div className="App-header">
		<OuterComponent />
		  <button onClick={() => changeLanguage('de')}>de</button>
		  <button onClick={() => changeLanguage('en')}>en</button>
		</div>
		<div className="App-intro">
		  <Trans>
			To get started, edit <code>src/App.js</code> and save to reload.
		  </Trans>
		</div>
		<div style={{ marginTop: 40 }}>
		  <a href="https://react.i18next.js">Learn more: https://react.i18next.js</a>
		</div>
		        
      </div>         
    )
  }
}

module.exports = TechnologiesBlock;

Still getting errors :( `TypeError: this.t is not a function & TypeError: node is null`


By the way, the constants:

```
    const { t, i18n } = this.props;
    and
    const changeLanguage = (lng) => {
      i18n.changeLanguage(lng);
    }
```


must be nested inside the render function of the first main component(index.js) or in each component where the translation is needed?
Thank you!

**Comment by jamuhl** [comment]
TechnologiesBlock is not extended by translate hoc

`module.exports = translate()(TechnologiesBlock)`

**Comment by 01Kuzma** [comment]
Thank you!
Now it's working!

**Comment by jamuhl** [comment]
Awesome...don't forget to star the project if you like it...and if you want to support the project in future you might have a look into https://locize.com our saas tier.

**Comment by 01Kuzma** [comment]
Already stared 👍

**Comment by 01Kuzma** [comment]
Tell me please, the constant:
`
    const { t, i18n } = this.props;
`
should be written in each component where the translation function is needed?

And 
`
    const changeLanguage = (lng) => {
      i18n.changeLanguage(lng);
    }
`
only in component where language change occur?
Thank you!

**Comment by jamuhl** [comment]
`const { t }  = this.props;` where you use the t function

`const { i18n }  = this.props;` where you need to changeLanguage or access other stuff on the i18next instance (https://www.i18next.com/api.html)

**Comment by 01Kuzma** [comment]
Hi!
I do not want to open another issue, because it is similar to previous.
I am trying to translate data in modal window (there are few of them)…
Well, getting the `TypeError: t is not a function`.
I have a t function inside component's class -  `<h3>{t('some text')}</h3>` - it works fine, but translation inside `function modalNames(props)` doesn’t work :
```
import React from 'react';
import ReactDOM from 'react-dom';
import {ModalRoute, ModalLink} from 'react-router-modal';
import {Link} from 'react-router-dom';
import ImageLoader from 'react-load-image';
import {translate} from 'react-i18next';

function Preloader(props) {
  return <img src="../img/spinner.gif" className="img-responsive center-block image-loader" />;
}

function Revel(props) {  
    const {t} = props;
    return (
      <div className='basic__modal-content'>
        <div className="revel">
          <div className="modal-body">
                <h4>{t('text_data')}</h4>                    
                    <ImageLoader 
                      src="../img/horizontal_line.png"> 
                      <Preloader />
                    </ImageLoader>                                       
            <hr className="hr" />   
          </div>      
        </div>
      </div>
    );
  }
  export default translate()(Revel);

  function another_modal() {
    return ( …  );
  }  



class Items extends React.Component {
  
  render() {
    const {t} = this.props;    
    return (
        <div className="container">
            <ul>
                <div id="works">
                    <li>
                        <Link to ="/revel"> <img src="img/revel.jpg"/> </Link>
                        <h3>{t('some text')}</h3> 
                    </li>
            </ul>            
            <ModalLink component={Revel} path={`/revel`} />
… inks to other modals
        </div>

    )
  }
}

module.exports = translate()(Items);
```

So I’ve added `export default translate()(Revel);`
But it doesn’t solve the problem
What I've missed?
Thank you!

**Comment by jamuhl** [comment]
`<ModalLink component={Revel} path={`/revel`} />` is that using a `import Revel from './Revel';` or is the unextended Revel in same file?

Any way if i remember right we also had an issue in our Modal (using different Portal code) where it only supported extended components inside the modal but was unable on the modal itself.

Something like:

```
export function AddNamespaceModalPure({ project, version, modalState = {}, onCancel }) {
  const { open } = modalState;
  return (
    <Modal open={open} onClose={onCancel}>
      <ExtendedAddNamespaceCard project={project} version={version} onCancel={onCancel} />
    </Modal>
  );
}
```

**Comment by 01Kuzma** [comment]
> <ModalLink component={Revel} path={/revel} /> is that using a import Revel from './Revel'; or is the unextended Revel in same file?

It's in the same file, I'm using the react-router-modal library.  
`<ModalLink component={Revel} path={`/revel`} />` triggers the 
`function Revel(props) {  
    const {t} = props;
    return (...
)`

**Comment by 01Kuzma** [comment]
So is it possible that this issue will be fixed?
And what workaround you could suggest?

**Comment by jamuhl** [comment]
Revel Component is not extended - you just export an extended as default!

change it to:

```
// ...
const ExtendedRevel = translate()(Revel);
export default ExtendedRevel;

// ...
<ModalLink component={ExtendedRevel} path={/revel} />
```

**Comment by 01Kuzma** [comment]
Thank you!
It's working.
Just to clarify.
I've few modals in one file and it seems that the `export default Extended_Modal` is unnecessary, cause once I've wrote:
`
export default ExtendedRevel;
and
export default ExtendedAnotherModal;
` 
I've received the compilation error. So it could be omitted?

And only this code must be used:
`
const ExtendedAnotherModal = translate()(AnotherModal);
...
`

**Comment by jamuhl** [comment]
you can't export 2 "things" as default...you can use named exports if you need to export multiple objects, functions, ...

if you do not need an export `const ExtendedAnotherModal = translate()(AnotherModal);` is all needed
