### ISSUE TITLE
Last release breaks Trans rendering

### ISSUE THREAD

**Issue by wichert** [i18next/react-i18next#302]
I have a Trans component that looks like this:

```html
      <Trans
        i18nKey="button.register"
        parent="a"
        href={site.genUrl('/settings')}
        className="button"
      >
        Register now
      </Trans>
```

This worked fine with react-i18next 5.3.0, but after upgrading to 5.4.0 it breaks in renderNodes because result[0] is an object without a props key:

```
> JSON.stringify(result)
"[{"children":"Register now"}]"
```

leading to this backtrace:

```
Uncaught (in promise) TypeError: Cannot read property 'children' of undefined
    at renderNodes (trans.js:96)
    at Trans.render (trans.js:138)
    at callMethod (preact-compat.es.js:491)
    at Trans.render (preact-compat.es.js:502)
    at renderComponent (preact.esm.js:686)
    at setComponentProps (preact.esm.js:634)
    at buildComponentFromVNode (preact.esm.js:814)
    at idiff (preact.esm.js:355)
    at innerDiffNode (preact.esm.js:474)
    at idiff (preact.esm.js:397)
```

**Comment by jamuhl** [comment]
will look into this asap

**Comment by jamuhl** [comment]
could you please try with react-i18next@5.4.1

**Comment by wichert** [comment]
Thanks, that fixes it! I hadn't realised this was specific to preact, luckily that was visible from the traceback.

**Comment by jamuhl** [comment]
Luck i saw your sample used preact (console statement) - so i knew i must have messed up with preact as that vdom implementation is a little different to reacts.

Sorry for that - should have tested that upfront.

**Comment by jamuhl** [comment]
Don't forget to star the project if you like it ;)...and if you want to support the project in future you might have a look into https://locize.com our saas tier.
