### ISSUE TITLE
Comparison with react-intl

### ISSUE THREAD

**Issue by oyeanuj** [i18next/react-i18next#303]
Hi folks! Thank you for putting out this library. Since the library tagline mentions 'i18n done right', I was wondering if you could provide a brief comparison (pros/cons/tradeoffs) between this library and `react-intl` (and/or some other prominent react i8n solutions)?

I'm sure it would be super helpful to others as well, who are in the same boat trying to make s decision.

**Comment by jamuhl** [comment]
Hm...comparison is hard - as the maintainer of i18next i'm too deep into i18next to make a fair comparison i think: i once made a medium article showing some benefits of i18next over formatjs in general and polyglot: https://medium.com/@jamuhl/i18n-frameworks-the-unfair-showdown-8d436cd6f470

Pro for sure is i18next is not react exclusive - you learn it once and can use it in future in any framework (and believe me react will go some day too ;)) -> https://www.i18next.com/supported-frameworks.html

Further with v6 you can use not only hocs but render props too -> https://react.i18next.com/getting-started.html#basic-sample-using-render-props 

vs HOC & Provider: https://react.i18next.com/getting-started.html#basic-sample-using-hoc

Hm than there is the video showing the line behind i18n -> localization -> the process not only instrumentation: https://www.youtube.com/watch?v=9NOzJhgmyQE

Inline components can be translated very easy: https://react.i18next.com/components/trans-component.html

Tradeoffs:
- JSON format - No icu format (which in my view is a matter of taste - i think icu format is bloated and very complicated to use - takes to much time for developers to format right - while most cases you just need simple interpolations
- Not baked by ex-yahoo (not sure how they maintain that now): but still i18next ecosystem is over 6 years old

Ideas / Help on how to highlight the pros / cons of react-i18next in comparison to react-intl would be awesome (but i always fear to sound biased)

**Comment by adrai** [comment]
Probably not exactly what you are looking for, but at least I've found something ;-)
https://medium.com/@jamuhl/i18n-frameworks-the-unfair-showdown-8d436cd6f470
https://medium.com/@jamuhl/get-your-react-js-application-translated-with-style-4ad090aefc2c

**Comment by oyeanuj** [comment]
@jamuhl Thank you for the detailed response, appreciate it. I'll go over it all, before I ask more questions!

**Comment by jamuhl** [comment]
Closing for now...feel free to reach out again if having more questions....
