### ISSUE TITLE
question: passing t (or overriding namespaces) to child component

### ISSUE THREAD

**Issue by rosskevin** [i18next/react-i18next#307]
## Goal

We have a reusable `Form` which does validation message resolution.  In most cases, it uses the `validation` namespace, but in some cases, the specific use case (e.g. `SignInForm`) may require a different message.

## Old implementation

Prior to the removal of the HOC `transFuncName`, we created `Form` with a different translate function as a programmatic callback.  This allowed the specific use case to pass in `t`, and if it was present in props, we used it for resolution.

## New implementation

I'm not sure.  I put the `validation` ns into the fallbackNS, but I still want the specific use case (e.g. `SignInForm`) to be able to pass an additional overriding `ns` to `Form`.  What is the best way to achieve this on 6.0.x?

**Comment by jamuhl** [comment]
wouldn't that work: https://www.i18next.com/essentials.html#multiple-fallback-keys

**Comment by rosskevin** [comment]
I've got multiple fallback keys, so I have `['common', 'validations']`.  The problem is when `SignInForm` wants a different value vs `ForgotPasswordForm` vs `Form`.

So only the use case _knows_ what translations should be overridden with.

**Comment by rosskevin** [comment]
```
<Form><Text/></Form> // use 'validations'. t('required') == 'is required'
```

```
<SignInForm>
  <Form><Text/></Form></Form> // use 'signInForm'. t('required') == 'Please use your email address'
</SignInForm> 
```

**Comment by jamuhl** [comment]
Wouldn't it work to just add a component / custom hoc component taking the `t` prop and rename that to something else and pass down the renamed in props?

or pass down some prefix via props and in Form:

```
render: () {
  const { t, prefix } = this.props;

  const function switchingT(key) {
   if (prefix) return t([`prefix.${key}`, key]); // or as namespace: return t([`prefix:${key}`, key]);
   return t(key);
  }

  const required = switchingT('require');
}
```

**Comment by rosskevin** [comment]
Sure, I can HOC it.  I was just curious if it was already covered since i18next is already very configurable.  I just wanted to make sure I didn't miss anything.

Thank you

**Comment by jamuhl** [comment]
`transFuncName` was initially a good idea - but in the end lead to more problems than benefit (as it was not supported in the other components as those rely on having `t` passed through.

**Comment by jamuhl** [comment]
Sorry for making it an extra step for your use case.

**Comment by rosskevin** [comment]
No problem, after some thinking and seeing the cases, I'm just going to pass an optional prop `<Form tOverride={t}`.  I've found we have models that are effectively `Person extends Contact`, where we share a bunch of widgets. And we end up passing `t` down several levels, so I need to continue to pass `t` down in some way instead of the namespace I was originally thinking.
