### ISSUE TITLE
Trans component: Variable inside a component doesn't seem to be working

### ISSUE THREAD

**Issue by ncribt** [i18next/react-i18next#308]
I have the following **translation**:
`"myKey": "<1>text</1><2>{{var1}} more text {{var2}}</2>"`

And the following **component**:
```js
<Trans i18nKey="myKey">
  <Light>text</Light><Bold>{{var1}} more text {{var2}}</Bold>
</Trans>
```
I define the `var1` and `var2` earlier in my code.

I keep getting these warnings and the variables content is not displayed in the translated component:
```
i18next::interpolator: missed to pass in variable var1 for interpolating {{var1}} more text {{var2}}
i18next::interpolator: missed to pass in variable var2 for interpolating  more text {{var2}}
```

Could you help me understand what I am doing wrong ?

**Comment by jamuhl** [comment]
shoudn't it be: `"myKey": "<0>text</0><1>{{var1}} more text {{var2}}</1>"` ?!?

**Comment by ncribt** [comment]
Just fixed that, no more error but my translated component displays:
`text {{var1}} more text {{var2}}` instead of the actual values

**Comment by jamuhl** [comment]
ok sorry, had to paste your content to get the right string out of it:

`<0>text</0><1><0>{{var1}}</0> more text <2>{{var2}}</2></1>`

setting debug: true on init will show you the right text:

<img width="834" alt="screen shot 2017-09-29 at 17 28 51" src="https://user-images.githubusercontent.com/977772/31023334-ceffc39e-a53b-11e7-966b-bc926274bfa5.png">

**Comment by ncribt** [comment]
Thanks! This is pretty confusing but it's working!

**Comment by jamuhl** [comment]
The problem is:

```
<Trans i18nKey="myKey">
  <Light>text</Light><Bold>{{var1}} more text {{var2}}</Bold>
</Trans>
```

{{var1}} is not a string - it's an object and basically a render child we replace ;)

Not the nicest thing...but the only way we could make it work...as we need the index of the interpolation variables based on index in props.children.

**Comment by jamuhl** [comment]
Don't forget to star the repo if you like it...and if interested have a look at https://locize.com our as a service tier.
