### ISSUE TITLE
i18n language is undefined

### ISSUE THREAD

**Issue by MatteCarra** [i18next/react-i18next#309]
I'm trying to access i18n language in componentDidMount by importing `import i18n from '../i18n'` just like in examples.
If I do this after deleting cookies language is undefined but if a console.log i18n instance it shows my browser language.
I'm using react-18next 6.0.2

Example:
![image](https://user-images.githubusercontent.com/11074527/31030950-75d2e5b4-a557-11e7-84fe-bde9dbf77bd4.png)

Load home is called in componentDidMount

![image](https://user-images.githubusercontent.com/11074527/31030907-41c5914a-a557-11e7-951b-5e6a5ab4635c.png)

**Comment by jamuhl** [comment]
language detection will be done on i18next.init call - but with setImmediate call - so any other code can run before detecting language and loading the translations from a potential available backend plugin.

Therefor if your componentDidMount is accessing i18next.language before initialization has finished it will be undefined.

You could do something like: https://github.com/i18next/react-i18next/blob/master/src/I18n.js#L64 to assert init is done.

Or wrapping your component into a translate hoc and have wait set should do it too...

**Comment by jamuhl** [comment]
obviously safer would be accessing i18n on render....not sure what your case is to access it in didMount?

**Comment by MatteCarra** [comment]
I was using it to make an api call that needs to know user's language.
Anyway thank you very much! I will look into your suggestion

**Comment by MatteCarra** [comment]
P.S: The strange thing to me was that console logging i18n instance displayed my actual language, while console logging i18n.language displayed undefined

**Comment by jamuhl** [comment]
if not getting to a solution just try to provide a webpackbin sample based on https://www.webpackbin.com/bins/-KoCD3kvA-4QJNaHpkxi so i have a sample.

console.log shows sample as it displays an object - the console updates on object change so. console.log(JSON.stringify(i18next))
