### ISSUE TITLE
nsMode global configuration option

### ISSUE THREAD

**Issue by rosskevin** [i18next/react-i18next#311]
Did something change with 6.x?  Formerly, I could pass multiple namespaces into `translate` and I could use them without prefixes, understanding that the first key found would win.  Now it is not finding my key, but it will if I prefix it.

So, from the example in the docs:

```javascript
function TranslatableView(props) {
  const { t } = props;
  return (
    <div>
      <h1>{t('keyFromDefault')}</h1>
      <p>{t('anotherNamespace:key.from.another.namespace', { /* options t options */ })}</p>
    </div>
  )
}

export default translate(['defaultNamespace', 'anotherNamespace'])(TranslatableView);
```

^^ works, but the following no longer does:

```javascript
function TranslatableView(props) {
  const { t } = props;
  return (
    <div>
      <h1>{t('keyFromDefault')}</h1>
      <p>{t('key.from.another.namespace', { /* options t options */ })}</p>
    </div>
  )
}

export default translate(['defaultNamespace', 'anotherNamespace'])(TranslatableView);
```
This would state (something like my log message) `translation missing 'key.from.another.namespace' for en 'defaultNamespace'`.
Am I missing a config option?

**Comment by rosskevin** [comment]
nsMode?  Can I default that globally?

**Comment by rosskevin** [comment]
Ok, confirmed, I'm expecting `nsMode: 'fallback'`.  I see no global default, so I guess I'll wrap the HOC with an Object.assign...unless you think a global options for `translate` is reasonable?

**Comment by jamuhl** [comment]
hm...v6 added the render props option to replace hocs if preferring doing so: https://react.i18next.com/getting-started.html#basic-sample-using-render-props

The translate hoc forwards all options to the render props component I18n: https://github.com/i18next/react-i18next/blob/master/src/translate.js#L52

and the I18n should use that:
https://github.com/i18next/react-i18next/blob/master/src/I18n.js#L16
https://github.com/i18next/react-i18next/blob/master/src/I18n.js#L48


nsMode should be setable globally: https://github.com/i18next/react-i18next/blob/master/src/context.js#L7

**Comment by jamuhl** [comment]
Just made a test: https://www.webpackbin.com/bins/-KvMK7GooEOLVwtqEzgq

app.js line 55 -> nsMode in translate options: works
i18n.js line 40 -> nsMode in i18n options: works

(react-i18next@6.0.2)

Could you provide a webpackbin or more info where setting nsMode fails - seems i miss a case.

**Comment by rosskevin** [comment]
Thank you, this was my mistake.

I was looking here:
https://www.i18next.com/configuration-options.html

And I should have been looking here:
https://react.i18next.com/components/i18next-instance.html

I used the `react` addition to options and it works fine.
