### ISSUE TITLE
Refs warning with React 16

### ISSUE THREAD

**Issue by JesperWe** [i18next/react-i18next#312]
I am upgrading my i18next based app to React 16, and getting plenty of `Warning: Stateless function components cannot be given refs. Attempts to access this ref will fail.` from inside i18next.

Is this a know issue with the current version under React 16?

**Comment by jamuhl** [comment]
Which version of react-i18next are you using?

**Comment by JesperWe** [comment]
```
  "dependencies": {
    "i18next": "^9.0.1",
    "i18next-browser-languagedetector": "^2.0.0",
    "i18next-xhr-backend": "^1.4.3",
    "react": "^16.0.0",
    "react-dom": "^16.0.0",
    "react-i18next": "^6.0.2",
    "react-redux": "^5.0.2",
    "redux": "^3.7.2",
  },
```

**Comment by jamuhl** [comment]
do you have set withRefs true in options / settings? https://github.com/i18next/react-i18next/blob/master/src/translate.js#L46

**Comment by JesperWe** [comment]
No.

**Comment by JesperWe** [comment]
Here is a typical traceback:

__stack_frame_overlay_proxy_console__ | proxyConsole.js:56
-- | --
printWarning | warning.js:33
warning | warning.js:57
mountIndeterminateComponent | react-dom.development.js:10439
beginWork | react-dom.development.js:10601
performUnitOfWork | react-dom.development.js:12573
workLoop | react-dom.development.js:12682
callCallback | react-dom.development.js:1299
invokeGuardedCallbackDev | react-dom.development.js:1338
invokeGuardedCallback | react-dom.development.js:1195
performWork | react-dom.development.js:12800
scheduleUpdateImpl | react-dom.development.js:13185
scheduleUpdate | react-dom.development.js:13124
enqueueSetState | react-dom.development.js:9646
ReactComponent.setState | react.development.js:218
ready | I18n.js:81
initialized | I18n.js:93
(anonymous) | EventEmitter.js:46
emit | EventEmitter.js:45
(anonymous) | i18next.js:153
done | i18next.js:258
(anonymous) | i18next.js:272
(anonymous) | BackendConnector.js:134
loaded | BackendConnector.js:121
(anonymous) | BackendConnector.js:269
(anonymous) | BackendConnector.js:162
(anonymous) | index.js:94
x.onreadystatechange | ajax.js:69
XMLHttpRequest.send (async) |  
ajax | ajax.js:71
loadUrl | index.js:82
read | index.js:75
read | BackendConnector.js:155
loadOne | BackendConnector.js:265
(anonymous) | BackendConnector.js:211
load | BackendConnector.js:210
(anonymous) | i18next.js:206
load | CacheConnector.js:40
loadResources | i18next.js:205
setLng | i18next.js:271
changeLanguage | i18next.js:277
load | i18next.js:150
setTimeout (async) |  
init | i18next.js:162
(anonymous) | i18n.js:5
__webpack_require__ | bootstrap 59059f55caba57d6d41a:688
fn | bootstrap 59059f55caba57d6d41a:109
(anonymous) | Login.js:230
__webpack_require__ | bootstrap 59059f55caba57d6d41a:688
fn | bootstrap 59059f55caba57d6d41a:109
(anonymous) | polyfills.js:22
__webpack_require__ | bootstrap 59059f55caba57d6d41a:688
fn | bootstrap 59059f55caba57d6d41a:109
(anonymous) | fetch.js:461
__webpack_require__ | bootstrap 59059f55caba57d6d41a:688
(anonymous) | bootstrap 59059f55caba57d6d41a:789
(anonymous) | bundle.js:793

**Comment by JesperWe** [comment]
Hmm I think I know what is causing this. I am using `translate()` in a component that does not extend React.Component. This was not an issue in React 15, but throws a warning now. So not an i18next issue.

**Comment by JesperWe** [comment]
No I was thinking wrong, it does extend React.Component so that was not the thing ;-) Sorry for the confusion.

**Comment by jamuhl** [comment]
you set somewhere withRef = true:

see: https://www.webpackbin.com/bins/-KvRaH0frGcPDjnbV6ux -> open console no error
see withRef: https://www.webpackbin.com/bins/-KvRbFWw7bEYh0a8QNBp -> error in console

**Comment by JesperWe** [comment]
Did a full string search in the entire project, the string "withRef" does not exist anywhere in the code.

**Comment by JesperWe** [comment]
Do you have the current version built with React 16 without this warning?

**Comment by jamuhl** [comment]
in the component you get the error could you try setting it to false?

translate(ns, { withRef: false })(yourComponent)

it must be set somewhere - until my webpackbins are not totally wrong??!

**Comment by jamuhl** [comment]
react is just a dependency...not something built in - see those webpackbin -> configure top right uses react v16 and latest react-i18next - no error at all

**Comment by jamuhl** [comment]
any luck?

**Comment by JesperWe** [comment]
A bit of luck. Adding withRef: false made 3 out 7 errors move over to a different traceback, which made me suspect that the error was in a [different component](https://github.com/ant-design/ant-design/issues/7754).

So it's not an i18next problem, probably just React 16 tracebacks being slightly weird (not surprising since they changed a lot of that code).

**Comment by jamuhl** [comment]
If there is anything else - let me know. Thank you.
