### ISSUE TITLE
I18nextProvider in v6.0 broked react-router

### ISSUE THREAD

**Issue by melounek** [i18next/react-i18next#314]
demo: https://www.webpackbin.com/bins/-KvS28UhloVq0r9Le5yc

you can see the routing between "base/sub" links does not work and it worked in previous version 5.4 (you can switch and see)

I digged in and found it probably caused this change: https://github.com/i18next/react-i18next/commit/e20bcc444e557b697625b8490e3775ac49c63e1b#diff-e33631178d0e2def71f9f52b47c3bcdb

when I replace the PureComponent with Component in `node_modules/.../es/I18nextProvider.js` It starts work again.

I don't know if the issue is also on the react-router site, but for now I would define the I18nextProvider back as `Component`.

**Comment by jamuhl** [comment]
sorry react-i18next@6.0.4

**Comment by melounek** [comment]
works, thanks
