### ISSUE TITLE
best method for locale files for react and react native

### ISSUE THREAD

**Issue by webmobiles** [i18next/react-i18next#316]
Hello,

I don't understand the docs and examples, must I read the full doc on i18next ? 
I don't see clear how and where save the locale files, my idea is re use , that same locale ( dicctionary) files for be read for an react native, and react app, the projects was created with:

  create-react-app' and 'create-react-native-app 

I've seen the readme:

Example react with hoc
Example react with render props

what are the differences?
when i visit 'react with hoc' , readme is not about react-next 

In src/app.js

import { translate, Trans } from 'react-i18next';

but in the example, there no locale files? how i can install an example , running, und modify locales?

thanks

**Comment by jamuhl** [comment]
Hi, sure you can reuse the same files.

In the hoc sample the locales are in the public folder: https://github.com/i18next/react-i18next/tree/master/example/react_withHOC/public/locales

In the end it's a question which backend you use with i18next: https://www.i18next.com/plugins-and-utils.html#backends (loading via xhr or bundling using a webpack bundler (https://www.i18next.com/plugins-and-utils.html#utils))

**Comment by webmobiles** [comment]
thanks
i think it's better use xhr ? is more simple i think with create-react-app where  I don't need to set webpack.

I've got this error with example react_withHOC:


```
Wrapper
node_modules/react-i18next/dist/es/translate.js:76
  73 |   }]);
  74 | 
  75 |   return Translate;
> 76 | }(PureComponent);
  77 | 
  78 | Translate.WrappedComponent = WrappedComponent;
  79 | 
View compiled
./src/App.js
src/App.js:33
  30 |   }
  31 | }
  32 | 
> 33 | export default translate('translations')(App);
  34 | 
  35 | 
  36 | 
View compiled

```

**Comment by webmobiles** [comment]
upgrading

 react-i18next/example/react_withHOC/package.json 
from   react-i18next@6.0.3 to react-i18next@6.0.4, solved the error.
