### ISSUE TITLE
I18next error in loading page

### ISSUE THREAD

**Issue by wijdench** [i18next/react-i18next#319]
Hi, 
I get this error when i load my page:
"i18next::backendConnector: loading namespace translation for language en via multiloading" failed in console after this line : i18next::backendConnector: successfully loaded namespaces , translation for languages en via multiloading.
so i18nest is failed to load after the successfully loading.

**Comment by jamuhl** [comment]
comes from https://github.com/i18next/i18next/blob/master/src/BackendConnector.js#L150

does your backend provide a route for proper multiload? and `loaded namespaces , translation ` seems like your loading a namespace ` ` of empty string or something like that.

could you provide more details...with just this console output it's hard to guess what your project looks like.

**Comment by wijdench** [comment]
this is my i18next.js file 
`import i18next from 'i18next';
import LanguageDetector from 'i18next-browser-languagedetector';
import XHR from 'i18next-xhr-backend';

i18next
  .use(XHR)
  .use(LanguageDetector)
  .init({
    debug: true,
    backend: {
      loadPath: '/locales/resources.json?lng={{lng}}&ns={{ns}}',
      allowMultiLoading: true,
    },
    fallbackLng: {
      'en-US': ['en'],
      'fr-FR': ['fr'],
      default: ['en'],
    },
    ns: ['common', 'search',],
    interpolation: {
      escapeValue: false, // not needed for react!!
    },

    react: {
      wait: true, 
    },
  });


export default i18next;
`

**Comment by jamuhl** [comment]
and you backend is node.js with express middleware and the `getResourcesHandler` middleware added?

**Comment by wijdench** [comment]
Thanks, the add of default namespace correct the issue

**Comment by jamuhl** [comment]
awesome...
