### ISSUE TITLE
Trans tag is adding div for each translated value 

### ISSUE THREAD

**Issue by chetankumar45** [i18next/react-i18next#320]
Hi, 
I am using the trans tag for I18N, but the issue is its adding div tag for each value it translates.
Ex- <Trans>transaction.driver.license</Trans>

I just don't want any tag. Please provide your input.

Thanks,
Chetan

**Comment by jamuhl** [comment]
Problem was / is. Pre react 16 you could not return multiple components from render -> you have to return one root component.

So currently you can go for the div - or set another element via parent prop: https://react.i18next.com/components/trans-component.html#props

**Comment by chetankumar45** [comment]
Thanks, it works, can we have something at configuration level as it will be difficult for adding at each tag

**Comment by jamuhl** [comment]
Currently hard on time...PR would be more than welcome

**Comment by jamuhl** [comment]
react-i18next@7.0.0 -> new default is no wrapping component

you can get old behaviour or setting wrapper for all Trans components by setting react.defaultTransParent in i18next init options.

https://github.com/i18next/react-i18next/commit/bb1a4c2c4f5cc979c6268e69be395a2455d89cd4#diff-4ac32a78649ca5bdd8e0ba38b7006a1e

**Comment by jamuhl** [comment]
closing as with latest version no more div get added
