### ISSUE TITLE
Module not found: Error: Can't resolve 'html-parse-stringify2'

### ISSUE THREAD

**Issue by Kraxxis** [i18next/react-i18next#323]
I'm getting a failure to build originating from this project.  This only seems to occur with version `6.0.6`, and a fresh project (no `node_modules` folder exists yet).  Reverting back to `6.0.5` resolves the issue, as does installing `html-parse-stringify2` manually.

Webpack stack trace below:
```
Module not found: Error: Can't resolve 'html-parse-stringify2' in '<project-dir>/node_modules/react-i18next/dist/es'
 @ ./node_modules/react-i18next/dist/es/Trans.js 17:0-41
 @ ./node_modules/react-i18next/dist/es/index.js
 @ <project related files>
```

**Comment by jamuhl** [comment]
there was no change between 6.0.5 and 6.0.6 regarding that dependency...very strange...could you clear your npm cache and retry?

**Comment by jamuhl** [comment]
you still encounter this?

**Comment by jamuhl** [comment]
closing for now...feel free to reopen if still persists with latest version

**Comment by tiavina-mika** [comment]
I'm using     "react-i18next": "^11.15.6" and I'm facing this error, 
have you found a solution?
