### ISSUE TITLE
<I18n /> initially rendering null can cause issues with other libraries

### ISSUE THREAD

**Issue by TLadd** [i18next/react-i18next#324]
If the wait option is true, the <I18n /> component will initially render null and then eventually render children after the ready state is updated in the loadNamespaces callback in componentDidMount (https://github.com/i18next/react-i18next/blob/master/src/I18n.js#L61 and https://github.com/i18next/react-i18next/blob/master/src/I18n.js#L112)

Since turning on the wait option, this behavior has caused some issues with other libraries.

With [react-bootstrap](https://github.com/react-bootstrap/react-bootstrap)'s Overlay and Popover components, the popover ends up flickering and disappearing immediately.

Using a translated component with [Slate](https://github.com/ianstormtaylor/slate), results in an exception being thrown.

There are not issues if wait is set to false, and I'm able to get around these issues by selectively passing in { wait: false } to the translate HOC when I want to avoid this behavior.

I'm curious though if it would be possible to avoid this behavior in the majority of cases automatically. I understand why you would want to initially render null for the highest translated components in the component tree, but maybe it could be possible to avoid it after the namespace has been loaded? 

Would it be possible for the constructor to know that the namespaces have already been loaded, allowing the initial state of ready to be true and preventing null from being rendered initially?

If it's not feasible, I'm fine passing in { wait: false } where needed; just wanted to log an issue regardless in case others run into the same issue.

**Comment by jamuhl** [comment]
i think i can do some precheck and set wait to false if already loaded. But feeling a little uncomfortable as i do not have something to test the effect.

Would you be able to provide a webpackbin based on https://www.webpackbin.com/bins/-KvzvUPFsBVI_74Jll99 so i could reproduce it?

**Comment by andrewbranch** [comment]
Why was this closed? I’m having issues with this as well. Unnecessarily rendering `null` on the initial render of every translated component not only causes unexpected side effects, but is also a bummer for performance.

**Comment by jamuhl** [comment]
was closed accidentally...sorry

**Comment by andrewbranch** [comment]
@jamuhl I might be able to put together a PR. Coming up with a test case is actually more work than fixing the problem. Would an appropriate approach be to check `this.i18n.store.data` for the namespace/language combinations requested?

**Comment by jamuhl** [comment]
fixing should be rather straight forward.

https://github.com/i18next/react-i18next/blob/master/src/I18n.js#L13 -> this.namespaces

foreach namespace and i18n.languages check https://www.i18next.com/api.html#hasresourcebundle if so set wait: false like here https://github.com/i18next/react-i18next/blob/master/src/I18n.js#L29

**Comment by andrewbranch** [comment]
@jamuhl: I had to add a `requestAnimationFrame` polyfill to get tests to pass in master... is there something else I should know about going on there?

**Comment by andrewbranch** [comment]
@jamuhl Why would we mutate `options.wait` when we can just set the initial `state.ready` correctly? That seems more straightforward, doesn’t it?

**Comment by jamuhl** [comment]
published with react-i18next@6.1.0 thanks to @andrewbranch

**Comment by jamuhl** [comment]
no still there: https://github.com/i18next/react-i18next/blob/master/src/I18n.js#L33
