### ISSUE TITLE
A way to add the language parameter to the URL

### ISSUE THREAD

**Issue by 01Kuzma** [i18next/react-i18next#325]
HI there!
Having a couple of questions regarding the possibility to use the language param in the URL address.
Is it difficult to implement language parameter in i18Next with React Router v4?
In my app the languages are changed through the **changeLanguage** function as it’s showed in this example:
https://www.webpackbin.com/bins/-KoCD3kvA-4QJNaHpkxi
My wish is to make the additional possibility to switch the languages with the URL parameter. I.e. www.example.com/en/something  www.example.com/es/something
Any examples available?
Thank you!

**Comment by jamuhl** [comment]
the language detector can accept additional detectors: https://github.com/i18next/i18next-browser-languageDetector#adding-own-detection-functionality -> so you could add a detector getting language from location 

this will only be for the initial load...after that you will need to sync route change with i18next.changeLanguage. Using https://github.com/ReactTraining/react-router/issues/3554 -> should be rather straight forward

**Comment by 01Kuzma** [comment]
Understood, thank you for info!
A question regarding workflow **without** a URL parameter. As React.js is isomorphic does it mean, that search bots will see the all the translated versions of website with the help of i18next? Or additional configuration is needed?

**Comment by 01Kuzma** [comment]
Understood, thank you for info!
A question regarding workflow without a URL parameter. As React.js is isomorphic does it mean, that search bots will see the all translated versions of the website with the help of i18next? Or additional configuration is needed?

**Comment by jamuhl** [comment]
If searchbots can find a link to the other languages they should take those pages into the index too. 

Adding meta tags for discovering them should do the trick: https://support.google.com/webmasters/answer/189077?hl=de

**Comment by 01Kuzma** [comment]
Does the i18next supports automatic meta tag update once the language has been switched?

**Comment by jamuhl** [comment]
no...but as usual...easy doable just listen https://www.i18next.com/api.html#onlanguagechanged and on that modify the metas

**Comment by 01Kuzma** [comment]
@jamuhl is it a normal way to handle the change of language by URL?

It is the first child component of the parent
```
import i18n from 'i18n';
import LngDetector from 'i18next-browser-languagedetector';
import myDetector from './myDetector';
... 
class ... {
componentDidMount() {
  
  const lngDetector = new LngDetector();
  lngDetector.addDetector(myDetector);
  
    i18n     
      .init({
        detection: {
          order: ['querystring', 'cookie', 'localStorage', 'navigator', 'htmlTag'],
          
          lookupQuerystring: 'lng',        
          lookupCookie: 'i18n',
          lookupLocalStorage: 'i18nextLng',
        
          caches: ['localStorage', 'cookie'],
          excludeCacheFor: ['cimode'],
        
          cookieMinutes: 10,
          cookieDomain: 'myDomain',
        
          htmlTag: document.documentElement
        }
    });
    
  
      var lang = '';
      if (typeof this.props.match.params.lng !== 'undefined'){      
          lang = this.props.match.params.lng.toString();
      } 
      else{
          lang='en';
      }      
      
      i18n.changeLanguage(lang, (err) => {
        if (err) return console.log('something went wrong loading', err)
      });   
    }
```

and **mydetector.js** is the same as in the example:
```
export default {
    name: 'myDetectorsName',
  
    lookup(options) {
      return 'en';
    },
  
    cacheUserLanguage(lng, options) {
    }
  };
```
Thank you!

**Comment by 01Kuzma** [comment]
Hi!
[quote]
the language detector can accept additional detectors: https://github.com/i18next/i18next-browser-languageDetector#adding-own-detection-functionality -> so you could add a detector getting language from location
[/quote]
Could you please share a sample, how a custom detector could get language from a URL location?
For instance:
website.com/ or website.com - default lng
website.com/en - English lng
website.com/xx - xx lng

It seems that on initial load with my settings in `index.js` the `i18n.language` doesn't get the lang param correctly from URL

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next-browser-languageDetector/issues/140

use in your detector location.href...split that by '/'

**Comment by 01Kuzma** [comment]
Something like this?
[code]
import i18n from 'i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

const lngDetector = new LanguageDetector()
lngDetector.addDetector({
	name: 'customDetector',
	lng: window.location.href.split("/"),
});

i18n
  .use(LanguageDetector)
  .init({		
	 fallbacks: true,
	  fallbackLng: 'lt',
	  whitelist: ['lt', 'en'],
			detection: {			
			order: ['customDetector' ,'localStorage', 'querystring', 'cookie', 'navigator', 'htmlTag'],			
			.....			
	})
[/code]

But which appropriate option `key` must be used here `lng: window.location.href.split("/")`?

**Comment by jamuhl** [comment]
no, just follow the guide: https://github.com/i18next/i18next-browser-languageDetector#adding-own-detection-functionality

```js
export default {
  name: 'myDetectorsName',

  lookup(options) {
    // options -> are passed in options
    return 'en';
  },

  cacheUserLanguage(lng, options) {
    // options -> are passed in options
    // lng -> current language, will be called after init and on changeLanguage

    // store it
  }
};
```

detector has a function `detect` returning the detected language

**Comment by 01Kuzma** [comment]
I've successfully added a plain custom detector's interface:
[code]
import i18n from 'i18next';
import LngDetector from 'i18next-browser-languagedetector';
import myDetector from './myDetector';
const languageDetector = new LngDetector()
languageDetector.addDetector(myDetector);

i18n
	.use(languageDetector)
	.init({
		fallbacks: true,
		fallbackLng: 'lt',
		whitelist: ['lt', 'en'],
		detection: {
			order: ['myDetector', 'localStorage', 'querystring', 'cookie', 'navigator', 'htmlTag'],
...
[/code]

`custom detector`:
[code]
export default {
	name: 'myDetector',
  
        detect() {
        
        },
  };
[/code]

So, detector only needs one function? *detect()* ? In such way how it should detect URL param?

**Comment by jamuhl** [comment]
If you do a complete own plugin for detections (adding to i18next via i18next.use) it is this interface: https://www.i18next.com/misc/creating-own-plugins.html#languagedetector

if you add an additional custom detection to the i18next-browser-languagedetector it's: https://github.com/i18next/i18next-browser-languageDetector#adding-own-detection-functionality

you're mixing the two:
- custom detector implements partly the language detection plugin
- your init code partially adds a custom lookup to the i18next-browser-languagedetector

**Comment by alisahin** [comment]
@01Kuzma Did you solved the problem? I also want to add language paramater to the url.

For example

- /home (nl by default)
-en/home

**Comment by jamuhl** [comment]
@alisahin @01Kuzma looks like we get that request rather often - what you think about providing a PR for the i18next-browser-languageDetector adding that to the provided detection modes?

https://github.com/i18next/i18next-browser-languageDetector

**Comment by 01Kuzma** [comment]
@alisahin the URL is added with Router. I've made it in such way:
`
index.js

import { I18nextProvider } from 'react-i18next';
import i18n from './i18n';

  render() {       
    return (      
      <I18nextProvider i18n={i18n}>
        <div>                
          <Router history={customHistory}>
            <Switch>
              <Route exact path={`/:lng(en|lt)?`} component={LandingPage} />
			  regex CHECK
              ...
              <Route component={NoMatch} />
            </Switch>
          </Router>
        </div>
      </I18nextProvider>
    )
  }
  
  
  
  LandingPage.js
  

import { translate } from 'react-i18next';

class LandingPage extends React.Component {

  render() {
    const { i18n } = this.props;

    if ((typeof this.props.match.params.lng !== 'undefined') && ((this.props.match.params.lng == 'en') || (this.props.match.params.lng == 'lt'))) {
      this.props.lang = this.props.match.params.lng.toString();
    }
    else {
      this.props.lang = 'lt';
    }

    if (this.props.lang !== i18n.language) {

      i18n.changeLanguage(this.props.lang, (err) => {
        if (err) return console.log('something went wrong loading', err)
      });
    }

    return (
      <div>
        <Preloader />
        <Header />
        <SectionA />
        <SectionB />
        <SectionC />
        <SectionD lang={this.props.lang} />
        <Footer />
      </div>
    )
  }
}

module.exports = translate()(LandingPage);
`
But I think there should be more proper way of doing this.
What concerns **languageDetector** - well I haven't figured out how to tune it...

@jamuhl  it would be great but it should be done with correct solution. Mine is temporary...

**Comment by jamuhl** [comment]
@01Kuzma hm...i see...i thought more about initial detection upon load -> taking lng from the window.location

adding a solution to the detector for using with react-router would be a no go -> not used everywhere

**Comment by 01Kuzma** [comment]
@jamuhl I think it will be right!
I've observed such behaviour:
I've implemented SEO component, which changes the meta title and description depending on language acquired from URL or on language change.  It's done in `componentWillMount()` but the `i18n.language` holds previous value. The updated value is accessible in `componentDidMount or render`, but in my case the new value should be in `componentWillMount()`. So I think it could be somehow related to detector...

**Comment by jamuhl** [comment]
@01Kuzma language detector only runs on i18next init when not passing in a options.lng -> detects only once during initialization -> from that point the detector does nothing but persisting language change in localStorage or cookie if set to do so.

So your use case is a little beyond what the detector is meant to do...but i think it would be awesome if you could share your solution in a little more detailed medium blog post (i know costs time - but might help others doing similar solutions)

**Comment by terhuerne** [comment]
Just in case that someone still needs this feature: This is implemented in the new version of `i18next-browser-languageDetector`. Just use:
```
i18n
  .use(Backend)
  .use(LanguageDetector)
  .use(reactI18nextModule)
  .init({
    fallbackLng: 'en',
    ns: ['translations'],
    defaultNS: 'translations',
    load: 'languageOnly',
    debug: false,
    detection: {
      order: ['path', 'navigator']
    },
    interpolation: {
      escapeValue: false
    },
    react: {
      wait: true,
      defaultTransParent: 'div'
    }
  });
```

**Comment by 01Kuzma** [comment]
@terhuerne , that works!
Just a little note: while switching the languages with a button (onClick event) the meta tags doesn't change. Once page is accessed directly by a URL with language param - meta changes. 
Any workaround?

**Comment by terhuerne** [comment]
@01Kuzma how do you set the meta tags? I'm using [Helmet.js](https://github.com/helmetjs/helmet) and when the language changes I change the constants I pass to the Helmet-Component. This forces the component to re-render.
`
const lang = 'en'
const meta = [
              {name: 'description', content: t('description')},
              {name: 'tags', content: t('tags')},
              {property: 'og:title', content: t('title')},
              {property: 'og:description', content: t('description')},
              {property: 'og:locale', content: lang},
];
const script = 'Some Schema.org stuff';
return (<Helmet
            htmlAttributes={{
              lang
            }}
            title={t('title')}
            meta={[
              
            ]}
            script={[
              script
            ]}/>)`

**Comment by terhuerne** [comment]
@01Kuzma or another idea: Use react-routers <Link> component when clicking on another language.

**Comment by 01Kuzma** [comment]
@terhuerne I also use React Helmet. 
Once I switch the language with button, the title data remains with previous language. If I further access any URL(I use modals with URLs) the meta changes, but once, in my case, the modal window is closed the title fallback to previous language.

The React-router works just fine once URL accessed directly.

How I could force meta to change with language button switch? In order that Helmet would be engaged?
