### ISSUE TITLE
Is there a reason i18next re-render components thrice when switching to new language for first time

### ISSUE THREAD

**Issue by sojimaxi** [i18next/react-i18next#326]
Looking at the console the entire app was re-rendered three times when switching to the new locale for the first time.

![i18next](https://user-images.githubusercontent.com/5046640/31710443-f6020820-b3ec-11e7-87cb-3612c49cfa8c.png)

Here is switching back which just renders once - this is the expected behavior.

![image](https://user-images.githubusercontent.com/5046640/31710777-f4c7af36-b3ed-11e7-81d8-4be2612e343b.png)

**Comment by jamuhl** [comment]
try setting `bindStore` to false https://react.i18next.com/components/translate-hoc.html#the-translate-hoc-can-take-a-few-options

should optimize that

**Comment by sojimaxi** [comment]
Thanks. It worked. I also changed `bindI18n: 'languageChanged'` and It now renders just once.
