### ISSUE TITLE
Update docs after removing translateFuncName

### ISSUE THREAD

**Issue by moos** [i18next/react-i18next#330]
Change log shows this was removed in 6.0.0 but docs haven't been updated.

**Comment by jamuhl** [comment]
updated...seems i missed one place...thanks for reporting

**Comment by moos** [comment]
To be clear, I'm referring to https://react.i18next.com/components/translate-hoc.html, which still has reference to translateFuncName.

**Comment by jamuhl** [comment]
think i found the last places...hopefully ;)

**Comment by moos** [comment]
Looks good - thanks for the quick turn around.
