### ISSUE TITLE
Question: how to change formatting of part of a string

### ISSUE THREAD

**Issue by rajivshah3** [i18next/react-i18next#343]
I have a string (let's say "This is a string") but I want to put part of it in bold (e.g. "This **is a** string"). What's the best way to have i18next handle this formatting? I've given both the full string and the bolded part to translators (e.g. "This is a string" and "is a") but I'm not sure what the best way is to implement this in the app

**Comment by jamuhl** [comment]
Simplest would be using the Trans component: https://react.i18next.com/components/trans-component.html#trans-component

On that page is a sample too.

alternative: what we often do for such simple cases is using markdown with eg. https://github.com/acdlite/react-remarkable

**Comment by jamuhl** [comment]
I think important for translation is keeping the text together....makes it easier to translate.

**Comment by rajivshah3** [comment]
I'm not sure how I managed to skip that when I read the documentation 😂  thanks so much!

**Comment by jamuhl** [comment]
writing documentation is not my strongest skill - so don't blame you - need to improve that at some point
