### ISSUE TITLE
Allow setting Trans parent to an actual component

### ISSUE THREAD

**Issue by phiresky** [i18next/react-i18next#345]
using

```jsx
export const Trans = props => <Trans_ parent={Aux} {...props} />;
```

where 
```jsx
export const Aux = (p) => p.children;
```

to prevent component wrapping already works fine, but throws this warning:
`warning.js:33 Warning: Failed prop type: Invalid prop `parent` of type `function` supplied to `Trans`, expected `string`.`

**Comment by jamuhl** [comment]
i see, just need to replace https://github.com/i18next/react-i18next/blob/master/src/Trans.js#L120 i guess with `PropTypes.node`

Will do so for next version - or if you like send over a PR. But anyway fix should come rather fast ;)

**Comment by jamesjryan** [comment]
This would be super helpful.

Tangentially related - also being able to set no parent or multiple children a la React 16.

**Comment by jamuhl** [comment]
@jamesjryan hm, my plan is to make no parent the default (before react 16 we had that option not)...but still need to figure out a way to make it easy configurable to backwards compatibility (evtl. by setting it in i18next.react.options...

**Comment by jamesjryan** [comment]
Sounds solid - would agree with no parent as default with a configurable option at the init level :)

**Comment by jamuhl** [comment]
@jamesjryan @phiresky just made a new version react-i18next@7.0.0

as default there is no wrapping component anylonger -> https://github.com/i18next/react-i18next/commit/bb1a4c2c4f5cc979c6268e69be395a2455d89cd4#diff-4ac32a78649ca5bdd8e0ba38b7006a1e

**Comment by phiresky** [comment]
Nice, thanks! Haven't tried it yet, if it doesn't work I'll reopen this issue.

**Comment by jamesjryan** [comment]
Thanks so much, will upgrade and give it a try.

Appreciate your dedication to open source projects, great lib!
