### ISSUE TITLE
unexpected url - react-native - i18n

### ISSUE THREAD

**Issue by techSquad1** [i18next/react-i18next#347]
Console throws unexpected url '/locales/ns1.json' , when i use xhr backend to export json for translation.
ns1.json
`{
  "action": {
    "add": "Add",
    "search": "Search",
    "length": "Length"
  }
}`

`import i18n from 'i18next';
import Backend from 'i18next-xhr-backend';

i18n
    .use(Backend)
    .init({
        fallbackLng: 'en',
        resources: undefined,
        lngs: ['en'],
        ns: ['ns1', 'ns2'],
        defaultNS: 'ns1',
        fallbackNS: ['ns1', 'ns2'],
        backend: {
            loadPath: '/locales/ns1.json',
        }
    }, (err, t) => {
       
    });

**Comment by jamuhl** [comment]
rather sure on a device (reactnative) you have to fully qualify the loadPath! https://yourServer.com/yourpathtolocales/...

**Comment by techSquad1** [comment]
my server is dynamic , so i dont think i could use loadpath.

I am planning to implement this way: 
`import en from './locales/en.json';
import de from './locales/ns1.json';`


Do you think its a best practice ?

**Comment by jamuhl** [comment]
yes...that's the other option...use https://www.i18next.com/api.html#addresourcebundle to add that to i18next

**Comment by techSquad1** [comment]
` 
import en from './locales/en.json'; import de from './locales/ns1.json';
resources: {
            en,
            de
            // have a initial namespace

        },`

It works this way, do we need addresourcebundle still?

**Comment by jamuhl** [comment]
no...that works too...just have en.json

```
{
  namespace1: { keys }, 
  namespace2: { keys }, 
}
```

**Comment by techSquad1** [comment]
Are the name spaces mandatory ??

my current json   - 
**de.json**

`{
  "translation": {
  }
}`

what i want my json to look like is -

`{
    "name": "Hola"
}`

is there any possibility ??

With angularjs with i18next it was possible.

**Comment by jamuhl** [comment]
if loading from xhr default namespace is translation -> and in that the filename sets the namespace

so namespace is needed even if just one namespace translation

**Comment by techSquad1** [comment]
Thank you so much for the quick response. I am closing this issue
