### ISSUE TITLE
Trans component doesn't use translation unless defaultTransParent is set

### ISSUE THREAD

**Issue by ianschmitz** [i18next/react-i18next#349]
I've noticed after the release of 7.0.0, the `Trans` component will not render the correct translation unless `defaultTransParent` is set to something such as `"div"`.

`useAsParent` is undefined, and therefore just returns the original children: https://github.com/i18next/react-i18next/blob/712ace76778ac9d9893a04af47060cd617a974a1/src/Trans.js#L117-L123

This was reproduced using the `react_withHOC` sample, with `i18next@10.1` and `react-i18next@7`

**Comment by jamuhl** [comment]
it's what is stated here: https://github.com/i18next/react-i18next/blob/master/CHANGELOG.md#700

not wrapping a component is the new default behaviour.

**Comment by ianschmitz** [comment]
Yes I understand, and that new behavior is awesome, but it doesn't actually translate anything when using the new behavior.

**Comment by jamuhl** [comment]
argh...how could i miss that...

fixed in react-i18next@7.0.2

**Comment by ianschmitz** [comment]
Thanks!
