### ISSUE TITLE
i18n implementation 

### ISSUE THREAD

**Issue by techSquad1** [i18next/react-i18next#351]
Which is the best/right way to implement i18n for react native /react , I want my i18n,t to be available all over a large scale project 

```
import { translate } from 'react-i18next';
render(){
    const { t } = this.props;
...
}
export default translate()(componentToBeTranslated);


```
or 

```
//in my router
  <I18nextProvider i18n={i18n}>
          <Provider store={store}>
            <HomeNavigation screenProps={{ t: i18n.getFixedT() }} />
          </Provider>
        </I18nextProvider>
//In my component, i pass t as prop every where.
```

**Comment by techSquad1** [comment]
Can I wrap using translate() at global level , instead of declaring it at each component level.

**Comment by jamuhl** [comment]
yes possible...the translate hocs main usage beside passing down the t function is setting the default namespace for the components below and if set to wait for rendering when loading translations via xhr (i guess you do bundle the translations for react usage?).

Hard to say which is best solution for your project...really depends on your preferences - you have all the options ;)
