### ISSUE TITLE
t not set if Trans is used only with I18nextProvider

### ISSUE THREAD

**Issue by MichaReiser** [i18next/react-i18next#352]
If the Trans component is used outside of a component wrapped with the I18nHoc but in an application using the I18nextProvider, then `t` is undefined (resulting in a render error). 

```jsx
<I18nextProvider i18n={i18n}>
  <Trans key="Test" />
</I18nextProvider>
```

The issue is, that the I18nextProvider only sets the i18n object into the context but `Trans` expects `t` and `i18n` to be present. I'm willing to fix this issue in a PR but first wanted to ask what the preferred way to solve the issue is:

1. Also set `t` in I18nextProvider. 
2. Mark `t` as not required in `Trans` and use `i18n.t` if  `t` is not explicitly defined

Which solution would you prefer?

**Comment by jamuhl** [comment]
i would go for 2) -> as honestly i prefer to not use the provider at all in future -> doing `i18next.use(reactI18nextModule)`

both 1) or 2) only acts as a fallback (might work for simple cases) but the hoc or render prop do more than just passing t down (like delay rendering, load the needed namespaces,...)

**Comment by MichaReiser** [comment]
I'm struggling with setting up the project on my computer.

The `npm run test` script just gets stuck on my mac computer 

```
npm test

> react-i18next@7.0.2 test react-i18next
> BABEL_ENV=development jest --no-cache`
```

Running the tests in webstorm on my windows computer (with BABEL_ENV=development) runs fine but crashes because the source files are not transpiled with babel (ES6 imports are not supported by node).

Do you have any advices?

**Comment by jamuhl** [comment]
hm..strange..should be straight forward. Evtl. a mismatch of jest version running the tests...should start using the one in node_modules instead of the global one.

**Comment by MichaReiser** [comment]
Needed to run jest with `--no-watchman` to get it working. Maybe the npm lockfile should be commited as well?
