### ISSUE TITLE
Missing namespace for Trans component

### ISSUE THREAD

**Issue by deniss-muhla** [i18next/react-i18next#354]
After updating to v7.1.0 version have issue with namespaces in Trans component.

Before update translations was loaded from '{lng}/{MyComponent.displayName}.json' file for:

`<Trans>Inputs</Trans>`
...
`export default translate(_.kebabCase(MyComponent.displayName))(MyComponent);`

After update only from  '{lng}/{defaultNamespace}.json'.

Found workaround:
`const {t} = this.props;`
...
`<Trans t={t}>Inputs</Trans>`

**Comment by jamuhl** [comment]
should work again with react-i18next@7.1.1

**Comment by deniss-muhla** [comment]
It works.
Thanks!
