### ISSUE TITLE
Question : best practice adding keywords on the fly

### ISSUE THREAD

**Issue by misteragile** [i18next/react-i18next#356]
Hi,

We have a react app with i18next translation coming from xhr-backend and we'd like to add keywords and their translation on the fly coming from API calls to some component.
What is the best practice to do that with react-i18next ?

thanks for your help !

**Comment by jamuhl** [comment]
So if i understand you right you get some translations from another service (api) and you like to use that using the `t` function?!?

you can add translations received using: https://www.i18next.com/api.html#addresource (or addResources / addResourceBundle)

Hope i understood correct.

**Comment by jamuhl** [comment]
closing for now...if still unclear feel free to reopen...thank you
