### ISSUE TITLE
Question: how does deep key works?

### ISSUE THREAD

**Issue by Grsmto** [i18next/react-i18next#358]
Hi,

I'm trying to access a translation from a deep object but I feel like I'm missing a point. Best is to check the [Webpack Bin there](https://www.webpackbin.com/bins/-L-mcG9V7qxEj_EgUG7V).

```
en: {
        translations: {
          "actions": {
            "click": "click here"
          }
        }
}
```
`<h2>{t('actions.click')}</h2> // will output "actions.click"!??? :/`

Thanks for your help!

**Comment by jamuhl** [comment]
see i18n.js line 35 -> we turned keySeparation "off" - so keys can't be nested

having key "actions.click": "click here" would work but no actions: { click: "click here" } 

https://www.i18next.com/principles/fallback.html#key-fallback

**Comment by Grsmto** [comment]
🙏 thank you very much.

**Comment by jamuhl** [comment]
you're welcome

**Comment by sudthenerd** [comment]
Sorry but it's Not working.
I created different file for each namespace.
And have nested keys.
locale/en/customer.json
 {
    "title": {"key": "translation"}
 }

locale/fr/customer.json 
 {
    "title": {"key": "fr translation"}
 }

as you can see, I have two file for namespace customer. and I want deep key support like
t('title.key')
But it's not working.

Thanks 😊

**Comment by sudthenerd** [comment]
I was using addResource to add resources dynamically.
and now I. Using 
i18n.addResourceBundle(language, namespace, resourcesForLanguage, true)

n it's working fine.

Thanks community😊🤸🕺
Happy coding😊

**Comment by zevero** [comment]
Didn't get it from the above comments.
To use deep keys seperated by `'.'` just set
`keySeparator: '.'`
when set to `false` it wont look for deep keys (as for `true`)

**Comment by jamuhl** [comment]
@zevero yes default is `.` so not overriding it to false will do it -> not like to use it - set to false, like different char - set that

**Comment by flancer64** [comment]
Thanks, @sudthenerd !

Deep keys don't work with `i18next.addResources`, we need to use `i18next.addResourceBundle`.

Wrong way:
```
i18next.addResources('en', 'mySpace', {
    look: {
        deep: 'value of look deep'
    }
});
i18next.t('mySpace:look.deep'); // 'look.deep' - failed!
```

Right way:
```
i18next.addResourceBundle('en', 'mySpace', {
    look: {
        deep: 'value of look deep'
    }
}, true);
i18next.t('mySpace:look.deep'); // 'value of look deep' - succeed!
```
