### ISSUE TITLE
Is it possible to change url construction for languages?

### ISSUE THREAD

**Issue by agustif** [i18next/react-i18next#359]
What I mean is, should I be able to tweak from ?lng=de to /de/ easily on server.js?

I am not capable to see where that code is in the example, thanks! thanks 🙇

**Comment by jamuhl** [comment]
server.js? express? i18next-express-middleware? -> https://github.com/i18next/i18next-express-middleware#detector-options

language detection works by using a plugin for that (beside the one included for express): https://www.i18next.com/plugins-and-utils.html#language-detector

**Comment by jamuhl** [comment]
could this be closed or do you need additional information / help?

**Comment by jamuhl** [comment]
closing for now...feel free to reopen...
