### ISSUE TITLE
Warning about defaultTransParent

### ISSUE THREAD

**Issue by hco** [i18next/react-i18next#361]
I think not every *new* user to react-i18next will read the changelog.
But there are probably still a lot of react applications out there that are not running on react 16.

Maybe a warning could be added if react-i18next is running on react below 16, that you need to set `defaultTransParent`? Or even better: default to <div> again, if react is not on v16?

Maybe just a note in the docs might be sufficient.

Any ideas about that? If you would point me the direction you would like to take, I could send you a PR.

**Comment by jamuhl** [comment]
hm...nothing against adding some additional information...but honestly i got no idea were people would read it -> an additional migration guide page on react.i18next.com?!?

if we could get the installed version info of react (not sure that is available anyhow) we might add a defaultTransParent = 'div' in case of not >= react 16?!?
