### ISSUE TITLE
Shallow renders undefined

### ISSUE THREAD

**Issue by Keethanjan** [i18next/react-i18next#362]
Hi there,

I'm trying to test if a button has been clicked (with the HoC translate). The application code is using the decorator @translate and i'm using the named export and importing it in my test class like import { Login }  

My test looks like this 

```
it('button click calls onLogin callback', () => {
  // Arrange
  const onClick = jest.fn();
  const username = 'james', password = 'pwd2';
  const wrapper = shallow(<Login onLogin={onClick} t={key => key} />);
  wrapper.setState({ username: username, password: password });
  console.log(wrapper.debug());

  // Act
  const button = wrapper.find('[data-id="login"]');
  button.simulate('click');

  // Assert
  expect(onClick).toBeCalledWith(username, password);
});
```

The console.log debug line prints out the following:

```
 <I18n ns={{...}} wait={false} withRef={false} bindI18n="languageChanged loaded" bindStore="added removed" translateFuncName="t" nsMode="default" onLogin={[Function]} t={[Function]} i18n={[undefined]}>
   <undefined />
 </I18n>
```

I'm curious why it is saying undefined. Besides that the test is failing with the message 
`Method “simulate” is only meant to be run on a single node. 0 found instead.`

Could you help me with this? Thanks in advance! :)

**Comment by jamuhl** [comment]
did you read: https://react.i18next.com/misc/testing.html

beside that have a look at: https://github.com/i18next/react-i18next/tree/master/test

your issue looks like you test the component which was extended with the hoc -> so you will have to pass i18n via context - or test the pure component not extended

**Comment by Keethanjan** [comment]
Thanks for the quick response!
I did read the links which you send to me and I was able to get this to work with testing the pure component, without the hoc. What I was trying to achieve is to test it with the hoc.
I think the part what I was missing is to see the hoc as a way of inject stuff without touching the original component.   

I will test the pure component, thanks :).
