### ISSUE TITLE
Crash on empty text nodes

### ISSUE THREAD

**Issue by phiresky** [i18next/react-i18next#363]
Happens for this:

`<Trans>{""}</Trans>`

This is pretty annoying if you have an optional message somewhere:

```ts
const message = success ? "Succeeded." : null;
return <Trans>{message || ""}</Trans>;
```

```
Trans.js:85 Uncaught TypeError: Cannot read property 'content' of undefined
    at Trans.js:85
    at Array.reduce (<anonymous>)
    at mapAST (Trans.js:73)
    at renderNodes (Trans.js:100)
    at Trans.render (Trans.js:143)
```

**Comment by phiresky** [comment]
Same for `null` children which are allowed usually but crash <Trans/>:

```ts
<p>{null}</p> // works
<Trans>{null}</Trans> // crashes
```

**Comment by jamuhl** [comment]
```
const message = success ? "Succeeded." : null;
return !!message && <Trans>{message}</Trans>;
```

if no message do not create a component.

**Comment by phiresky** [comment]
Sure, but I converted a code base to use react-i18next and this was an unexpected change I only noticed after publishing it because the empty string case only happened very seldom in my case. And I'm not returning <Trans> standalone, it's embedded in some other text so replacing `return <p>....... <Trans>{msg}</Trans> ...</p>` with `return <p>....... {!!msg && <Trans>{msg}</Trans>} ...</p>` is not that pretty.

I think at the least it should not throw an error (and thus cause the whole component tree to unmount), maybe print a warning instead if you don't want to allow it.

**Comment by jamuhl** [comment]
Might look into this in future...should be rather simple to just ignore Trans component with empty children -> PR would be welcome

**Comment by phiresky** [comment]
Not actually sure why this happens, I thought it would happen on `<Trans>You are <b>{bool? "not":""}</b> cool</Trans>` but it does not.

**Comment by jamuhl** [comment]
this is not empty...it's just the AST parser inside the Trans component not supporting empty node

**Comment by phiresky** [comment]
Ok, so the real reason I think is that the outermost node is created by you as a dummy node, but this check:

https://github.com/i18next/react-i18next/blob/7fd710d1a0f0568be27197f8a68f818f0b941c30/src/Trans.js#L74

Which returns false for inner empty AST nodes (e.g. `You are <1></1> cool` returns true for the outermost dummy node, because that one does not pass `React.isValidElement(child)`

Also, "hasChildren(node)" returns false when node = `{children: ""}` even though "" arguably is a child. So there are multiple solutions:

1. 
    ```diff
    diff --git a/src/Trans.js b/src/Trans.js
    index a33809b..041040b 100644
    --- a/src/Trans.js
    +++ b/src/Trans.js
    @@ -63,7 +63,7 @@ function renderNodes(children, targetString, i18n) {
     
             if (typeof child === 'string') {
               mem.push(child);
    -        } else if (hasChildren(child)) {
    +        } else if (child.dummy || hasChildren(child)) {
               const inner = mapAST(getChildren(child), node.children);
               if (child.dummy) child.children = inner; // needed on preact!
               mem.push(React.cloneElement(
    
    ```
2. Modify hasChildren
3.
    ```diff
    diff --git a/src/Trans.js b/src/Trans.js
    index a33809b..767886d 100644
    --- a/src/Trans.js
    +++ b/src/Trans.js
    @@ -47,6 +47,7 @@ function nodesToString(mem, children, index) {
     }
     
     function renderNodes(children, targetString, i18n) {
    +  if (targetString === "") return [];
     
       // parse ast from string with additional wrapper tag
       // -> avoids issues in parser removing prepending text nodes
    ```

**Comment by jamuhl** [comment]
why not just check

https://github.com/i18next/react-i18next/blob/master/src/Trans.js#L99

if (children === '') return null;

**Comment by phiresky** [comment]
Because that doesn't fix the cause, and e.g. <Trans>{null}</Trans> still errors

**Comment by jamuhl** [comment]
then `if (!children) return null;`

**Comment by phiresky** [comment]
Yes, but then `<Trans>{""}</Trans>` renders `null` and not `""`

**Comment by phiresky** [comment]
`if (!children) return children;` would make sense?

**Comment by jamuhl** [comment]
will check your PR later...need to test that...currently not at a PC so just pseudo coding ;)

**Comment by jamuhl** [comment]
`if (!children) return children;` might be better - what i would like to avoid in those cases is accessing the t function for returning nothing -> which still leads to a missing call - which ends up in some json file via saveMissing.

**Comment by jamuhl** [comment]
`<div/>` which renders a 1px bar of nothing and `""` which renders nothing at all?!?

**Comment by phiresky** [comment]
Exactly, if all your Trans components cause a div to be wrapped around them
(which more importantly causes a line break etc.) you would expect that to
happen for empty Trans too. Just like `<div>{""}</div>` returns the same
thing as `<div />` and `<Fragment>{""}</Fragment>` returns `""`

2017-12-12 16:22 GMT+01:00 Jan Mühlemann <notifications@github.com>:

**Comment by jamuhl** [comment]
even more looking at your case why you use `Trans` at all instead of a simple `t` call?!?

```
const message = success ? "Succeeded." : null;
return <Trans>{message}</Trans>;
```

gets:

```
const message = success ? "Succeeded." : null;
return <div>{success ? t('Succeeded.') : ''}</div>;
```

**Comment by jamuhl** [comment]
means `Trans` component is for wrapping components - not one string

**Comment by jamuhl** [comment]
because it's more complicated then pure t function usage...but if it works for you better nothing against it ;)

Well i think i will merge your PR as is tomorrow and publish an update...i don't see any impact on existing projects - so it should not break any existing integrations...
