### ISSUE TITLE
Allow overriding namespace in Trans

### ISSUE THREAD

**Issue by phiresky** [i18next/react-i18next#366]
It would be helpful to be able to do `<Trans ns="test">hello</Trans>` to override the namespace regardless of what the context's namespace is.

**Comment by jamuhl** [comment]
take `ns` from props and add it here: https://github.com/i18next/react-i18next/blob/master/src/Trans.js#L109

`const translation = key ? t(key, { ns, interpolation: { prefix: '#$?', suffix: '?$#' }, defaultValue, count }) : defaultValue;`

beside that we might add an additional prop `tOptions` which accepts an object getting merged into those options allowing all the: https://www.i18next.com/essentials.html#overview-options ?!?

**Comment by jamuhl** [comment]
do you like to provide a PR?

**Comment by phiresky** [comment]
Sorry, I'm fairly busy right now so it would probably take a while for
me to get to it, and I solved the concrete instance where I needed
this differently. I still think it's useful though, feel free to add
it yourself if you want.

2018-01-11 14:11 GMT+01:00 Jan Mühlemann <notifications@github.com>:

**Comment by jamuhl** [comment]
ok...will see if i got time some day...thanks for the response

**Comment by jamuhl** [comment]
Will be supported in react-i18next@7.4.0 coming later today...
