### ISSUE TITLE
When to use t and i18next.t

### ISSUE THREAD

**Issue by ChCosmin** [i18next/react-i18next#368]
[HERE](https://react.i18next.com/components/i18n-render-prop.html) i've seen it being used with `{t('key')}`, but [HERE](https://www.i18next.com/interpolation.html) it uses` i18next.t('key',{ param: val});`

which way should it be done ? can i do interpolation with `{t('key')}` without needing an extra i18next import?

**Comment by jamuhl** [comment]
the `t` which you get inside the react related components is basically the same function as i18next.t (just fixed to the given namespace).

So all the options you see in the https://www.i18next.com/interpolation.html docs are also valid for that `t` function

**Comment by jamuhl** [comment]
means you can do `{t('key', { what: 'i18next', how: 'great' })}` or use plurals and all the other options

**Comment by ChCosmin** [comment]
how would i go about translating special chars like &amp; (&) and others like it?
if i do `{t('100% Wireless &amp; Cellular')}` im guessing the value for "100% Wireless &amp; Cellular" key can't be "100% Wireless & Cellular" because it's not encoded after translation. i've tried `{t('100% Wireless {{&amp;}} Cellular'), {&amp; : ???}}` but that also obviously didn't work cause of the syntax... i've looked over the documentation but can't seem to figure out what is needed here to get past this

also, how would i go about translating dynamical components that have {this.props.something} which would receive a random strings

**Comment by jamuhl** [comment]
why you would replace `&` with `&amp;` -> that's not needed anymore...react takes care of encoding

could you make a sample for the `{this.props.something}` - i don't get what you mean

**Comment by ChCosmin** [comment]
```
var cars = [
{name: 'audi', desc: 'this car is a'}
{name: 'toyota', desc:'i like'}
{name: 'mazda', desc: 'i want to buy a'}
]

{
  "This is easy to translate" : "Diz iz ez to trans",
  "this car is a": "diz car iz a",
  "i like": "i likez",
  "i want to buy a": "i wanna buy a"
}

cars.map((car)=>{ return (<Cars name={car.name} desc={car.desc} /> )})

class Cars extends React.Component {
  render() {
//+ <I18n ns={[namespace]}> + import above and all that //
    return (
      <div>
          <p>{this.props.desc} {this.props.name}</p>
          <p>{t('This is easy to translate')}</p>
      </div>
    );
  }
}
```

made on the fly, hope it's clear what i intend on doing, and sry for the stupid translations :) so yeah, how would i go about translating for example {this.props.desc}, each one being different for each car object

**Comment by jamuhl** [comment]
no does not help...but i guess now ;)

you like to choose a key based on a prop: -> `{t(\`someKey.${this.props.name}\`}` => use template string

integrate some value from props into translation use interpolation: https://www.i18next.com/interpolation.html

**Comment by ChCosmin** [comment]
this.props.name is the key it'self, that cant get different values depending on what's passed down through it.

i tried this: `{t(`${this.props.title}`)}` but it translates to [object Object]. 

another thing that i can't make it work is having strings with <br /> tags in it, i've tried using 
`{ 
"bannerHeading": "More than a {{enter}} Smart Home. {{enter}} A secure Home",
}`
`<p className="sm-first-textblock font-bold" dangerouslySetInnerHTML={{ __html: t('bannerHeading', { enter: <br /> }) }} />` but i think i understood it wrong, what am i doing wrong? and thanks for all your help so far

**Comment by jamuhl** [comment]
in this case your this.props.title is not a string...but some object...easy as that

`{ enter: <br /> }` is not a tag...it will be transpiled to a function -> that is jsx and a component in this case

use a string `{ enter: '<br />' }`

**Comment by ChCosmin** [comment]
i tried with string too, still didn't work but managed by using `<Interpolate i18nKey="bannerHeadingText" useDangerouslySetInnerHTML={true}/>` :)

**Comment by ChCosmin** [comment]
still can't make any string received by this.props.title `<h5>{this.props.title}</h5>` to be translated. Do you have any simple example of a component with props that translates its props?
```
stuff = {
  title: "I like eating cheese"
 text: "Unfortunately i cannot eat cheese because i am lactose intolerant, but i wish i could"
}
<Component title={this.stuff.title} text={this.stuff.text}>
//component file
class Component extends react.component {
  render() {
   return(
    <p>{this.props.text}</p>
   );
  }
}
```

**Comment by ChCosmin** [comment]
i managed to figure out the this.props thing, you said it right above but i don't think i connected the translation keys right, my bad. Thanks a lot for all the help :)
