### ISSUE TITLE
Allow first argument in translate HOC to be a function

### ISSUE THREAD

**Issue by EmmaSimon** [i18next/react-i18next#369]
Would it be possible for `translate` to take a function that returns the namespace(s)? The function would be passed the props of the component. It currently doesn't seem possible to use `translate` to conditionally load namespaces from the backend based on the wrapped component's props.

**Comment by jamuhl** [comment]
does that function have to be async? a simple synchronous function would be not a big deal...but an async function while possible is rather tricky to get right...

**Comment by jamuhl** [comment]
so

`translate(() => { return ['ns1', 'ns2'] })(mycomponent)`

or:

`translate((callback) => { callback(['ns1', 'ns2']) })(mycomponent)`

**Comment by EmmaSimon** [comment]
Oh, no I think synchronous is fine. But I'd think this would only really be useful if it was provided the props. So you can do something like,
```
translate((props) => {
    if (props.x) {
        return ['ns1'];
    }
    return [`ns-${props.y}`];
})(mycomponent)
```

**Comment by jamuhl** [comment]
that's doable: https://github.com/i18next/react-i18next/blob/master/src/translate.js#L21

if you like feel free to make a pull request...else i will add it sometime between xmas and new year.
