### ISSUE TITLE
Export static properties of the Component

### ISSUE THREAD

**Issue by kadishmal** [i18next/react-i18next#37]
Imagine I have a the following class with static properties.

	class Presets extends React.Component {
		static timeToAbbr() {
			console.log('timeToAbbr');
		};
	}

	export default translate(['presets'])(Presets);

From outside of the component I cannot call `Presets. timeToAbbr()` as a class function.

If I exported the class directly without wrapping it into `Translate` component as follows, it can successfully call the static function.

	export default Presets;

**Comment by jamuhl** [comment]
you have access to translated.wrappedComponent: https://github.com/i18next/react-i18next/blob/master/src/translate.js#L64

if you need more a PR would be welcome.
