### ISSUE TITLE
Weird replacement of the key by corresponding translation

### ISSUE THREAD

**Issue by RobinCsl** [i18next/react-i18next#370]
Hello there,
First of all, thank you very much for all your hard work!
I would like to report the following issue. When there are weird symbols in my code, the key is replaced by the translation and some other content. I do not understand this behaviour.

This is my source file.
```
import React from "react";
...
import { translate, Trans } from "react-i18next";

const ExampleOverview = props => (
  <div>
    <ContentBlock>
      <Trans>
        <h2>Example Page</h2>
      </Trans>
      <p>{props.t("Hello")}</p>
      <Trans>
        My other <em>example</em> with html entities &lt;\} &amp;
      </Trans>
      <Button>Example</Button>
    </ContentBlock>
  </div>
);
export default translate("ExampleOverview")(ExampleOverview);
```

My translations are loaded correctly, as can be seen in the following picture of my console in the dev tools:
![log-correctly-loaded](https://user-images.githubusercontent.com/22741774/34036934-1f05c8c0-e187-11e7-8917-f2c4072f2355.png)

But then, it gets rendered like below:
![rendered-text](https://user-images.githubusercontent.com/22741774/34036947-2be71094-e187-11e7-99c7-dda54dd81904.png)
Why is there **My other** appended to `Mon autre other <1>exampleofirehguh</1> with avec entités HTML <\} \{ &`, with `<\} \{ &` not showing up at all? 
Rendered result: ```Mon autre other exampleofirehguh with avec entités HTML **My other**```

It looks like i18next is not smart enough yet to deal with these symbols. Equally, when I use `&lt; hi &gt;`, the key gets compiled to `<hi>`, and having this in the translation means it does not get rendered. Is there something I am missing?

Thank you very much for your time and looking forward to reading your answer!
Best wishes,

**Comment by jamuhl** [comment]
More or less a limitation of what the Trans component can do...it parses the given translation via html parser into an ast - replaces those nodes given with the components passed in via children...

so mixin into translations html stuff - kills the "magic" as it can't match up translation with the children content.

**Comment by RobinCsl** [comment]
Thank you for your answer. 
Yes, I completely understand. However, `&gt;` should probably not be converted to `<` when creating the key. HTML entities should be rendered properly and not be interpreted as something else. 
Does that make sense?
And the translation parser should then transform HTML entities in the translation into the right characters.

**Comment by jamuhl** [comment]
not looked to deep into it...not sure where that happens at all - for sure we do not convert that - so might be the AST parser or somewhere else...

Feel free to provide a PR if needing this. Else i might take the time and check that in xmas holidays

**Comment by RobinCsl** [comment]
I will try and have a look. But if it is to modify how keys are generated, then it should probably be in the i18next project, and not in the react one, right? Actually, the way keys are generated is impacting all i18next projects, isn't it?

**Comment by jamuhl** [comment]
we do nothing with keys in i18next...no encoding/decoding...

in case of the Trans component if not passing a key we take generated defaultValue as key based on the children using this function: https://github.com/i18next/react-i18next/blob/master/src/Trans.js#L13

**Comment by jamuhl** [comment]
closing....guess we won't get a result on this issue.
