### ISSUE TITLE
Conflict with react-redux?

### ISSUE THREAD

**Issue by pors** [i18next/react-i18next#371]
Hi,

I use react-i18next with the HOC model using the `@translate` decorator and the I18nextProvider component.

All works fine for normal components, but when I apply the decorator to a "connected" component (with the react-redux connect function) I get the following error:

```
bundled-app.js:233857 Uncaught TypeError: _dec is not a function
    at Object.defineProperty.value (bundled-app.js:233857)
```

The error points to the second mention of `_dec` here:

```
var OnPremiseAgentBlock = (_dec = _reactI18next.translate['OnPremiseAgentBlock'], _dec(_class = function (_React$Component) {
     _inherits(OnPremiseAgentBlock, _React$Component);
...
```

Any idea how to debug this further?

Thanks.

**Comment by jamuhl** [comment]
no idea...never run into such code....

**Comment by jamuhl** [comment]
https://github.com/i18next/react-i18next/issues/367 that's how we do it - and zero issue

**Comment by pors** [comment]
So the use of a decorator seems to be the issue? In the comment here: https://github.com/i18next/react-i18next/issues/367#issuecomment-351655322 you call the translate function in the export statement.

**Comment by jamuhl** [comment]
could be...not used decorators for a while...

**Comment by pors** [comment]
OK, got it working now without using decorators. react-redux was unrelated here.

Thanks for the speedy responses again!

**Comment by SPreo26** [comment]
I've had the same error message which in my case happened if you try to pass additional args into a decorator (like the InnerComponent) and don't use a wrapper function.
The pattern that would fix it for me was:

```
const decoratorWrapperFunc = (ComponentWrappedByHOC, otherArgs) => {
  return (DecoratedClass) => {//returned is the actual decorator function as the @ operator expects
    //when the @ operator below is parsed, DecoratedClass would be automatically set to the class MyHOC
    //decorator code
  }
}
```

and then you could decorate your HOC with it

```
const funcThatReturnsDecoratedHOC = (ComponentWrappedByHOC) => {
  @decoratorWrapperFunc(ComponentWrappedByHOC, otherArgs)
  class MyHOC extends React.Component {
    ...
  }
  return MyHOC
}
```

look for Class Decorators section here https://www.sitepoint.com/javascript-decorators-what-they-are/
