### ISSUE TITLE
Can't translate deep keys

### ISSUE THREAD

**Issue by ChCosmin** [i18next/react-i18next#373]
```
{
  "Modals": {
    "Terms": { "Customer" : "abcd" }
  }
  "Commons:" {
     "Buy Now": "Cumpara Acum"
   }
}
<I18n ns={['Modals', 'Commons']}>
        {
          (t, {i18n}) => (
           <div>
              <h1>{t('Commons:Buy Now')}</h1> <---works
              <p>{t('Modals:Terms.Customer')}</p> <- not working
              <p>{t('Modals.Terms.Customer')}</p> <- not working
              <p>{t('Modals.Terms:Customer')}</p> <- not working
           </div>
           )
        }
</I18n>
```

I just can't seem to figure it out how to acces translations in key's withing key's...any idea what i am doing wrong?

**Comment by jamuhl** [comment]
can you paste your i18next init config?

i guess you set keySeparator to false -> so no keys in form key.deep.somewhere allowed

**Comment by ChCosmin** [comment]
`i18n
  .use(LanguageDetector)
  .init({
    // we init with resources
    resources: {
      en
    },
    fallbackLng: 'en',

    // have a common namespace used around the full app
    ns: ['translations'],
    defaultNS: 'translations',

    keySeparator: true, // we use content as keys

    interpolation: {
      escapeValue: false, // not needed for react!!
      formatSeparator: ','
    },

    react: {
      wait: true
    }
  });

export default i18n;`

yes you're right it was on false, put it to true but still can't figure out what to write to point it to the correct key :(

if i have` { key: deepKey: { x: "translation" } }.` how do i get acces to x in the `{t(' [...] ')}` format?

**Comment by jamuhl** [comment]
set keySeparator to `.` for `Terms.Customer`

**Comment by ChCosmin** [comment]
worked, thank you :)
