### ISSUE TITLE
This package requires react-dom, I'm using react native

### ISSUE THREAD

**Issue by jper92** [i18next/react-i18next#376]
I'm using a react native project, which doesn't require the `react-dom` package since the environment is not web, however, npm warns me that `react-i18next` requires a peer dependency of react-dom, is there a way to get rid of this warn?

**Comment by jamuhl** [comment]
hm...makes sense to remove that peer dependency...will publish an update

**Comment by jamuhl** [comment]
react-i18next@7.3.1

**Comment by jper92** [comment]
Thanks for your quick reply. Already installed the new version and seems fine
