### ISSUE TITLE
I18nextProvider cannot pass t as a function to a sub component in test with emzyme and jest

### ISSUE THREAD

**Issue by ManYang** [i18next/react-i18next#377]
Hi All,
I have a component which composite by several children components, of which use t to translate. When I warp the root component like:  
```
const wrapper = shallow(
      <I18nextProvider i18n={mockI18n}>
        <Parent state={stateA} />
     </I18nextProvider>
);
```

  It works fine, but just to the top level. For translate in child, it throws error like:    ReferenceError: t is not defined

      278 |     const columns = [
      279 |       {
    > 280 |         title: `${t('User Group Name')}`,
      281 |       },
This also happens when I use mount instead of shallow. I am not sure how to translate all thing in the components that applied t function. Can anyone help?

**Comment by jamuhl** [comment]
How do you pass down `t` to the childrens?

**Comment by ManYang** [comment]
@jamuhl 
In main.js there is i18next:
```
i18next
  .use(XHR)
  .use(sprintf)
  .init({
    lng,
    fallbackLng: ['en'],
    debug: false,
    interpolation: {
      format: localizeTime,
    },
    load: 'currentOnly',
    nonExplicitWhitelist: true,
    lowerCaseLng: true,
    ns,
    defaultNS: ns,
    fallbackNS: ns[0],
    backend: {
      loadPath: '/static/locales/{{lng}}/{{ns}}.json',
    },
    escapeInterpolation: false,
    nsSeparator: false,
    keySeparator: false,
    returnEmptyString: false,
  }, (err, t) => {
    window.t = t;
    render(App);
    i18next.on('languageChanged', () => {
      window.t = t;
      render(App);
    });
  });
```
The parent works probably beacuse it is warped by `<I18nextProvider i18n={mockI18n} />`

**Comment by jamuhl** [comment]
So you do not pass `t` to your components - but try to pass that to global window.t and use that...or how do you access t in your components?!? `const { t } = this.props;` ?!?

you can pass down `t` by using the translate HOC: https://react.i18next.com/components/translate-hoc.html

or the render props: https://react.i18next.com/components/i18n-render-prop.html

see samples:
https://github.com/i18next/react-i18next/blob/master/example/react_withHOC/src/App.js#L8 (t)
https://github.com/i18next/react-i18next/blob/master/example/react_withHOC/src/App.js#L33 (hoc)

**Comment by ManYang** [comment]
@jamuhl t is passed in the window object in the callback, when re-render the app by lang change, we already have window.t, so  there is no need to pass as props to the child component... during the development this strategy works fine, I am not sure how to do this in the test with enzyme and jest though, looks like the  translate HOC could be a potential solution, now my mockI18n is a plain object:
```
const mockI18n = {
  t(k) {
    return k;
  },
  on() {
  },
  getFixedT(k) {
    return (k) => k;
  },
  loadNamespaces(arg) {
    return (arg) => arg;
  }
};
module.exports = mockI18n;
```
Can I just replace it with i18next instance and passed down? If I can, how?

**Comment by jamuhl** [comment]
mocking it is ok...just your problem seems more to be related to using window.t than anything i18next related -> more a question of using window object in enzym (jest) environment.

you set window.t on languageChange of the "real" i18next instance or in init callback - do you set window.t in your tests?

**Comment by ManYang** [comment]
@jamuhl no, I am not sure how to do this though, sth like 

 `window.t = (k) => { return k} ;`

do not work out, any suggestions?

**Comment by jamuhl** [comment]
not sure if there is a window in this context of tests...you will need to check with JEST or whatever test env you use

**Comment by ManYang** [comment]
@jamuhl thanks for your help. I think this is on the right track, for this issue, you can close now.
