### ISSUE TITLE
What does HOC stand for?

### ISSUE THREAD

**Issue by scharf** [i18next/react-i18next#378]
The documentation talks a lot about HOC (e.g here https://react.i18next.com/getting-started.html#basic-sample-using-hoc) without explaining what HOC means.

**Comment by scharf** [comment]
I guess it means Higher Order Component.

**Comment by scharf** [comment]
Here is a link to react.org explaining what a [HOC (Higher Order Component)](https://reactjs.org/docs/higher-order-components.html) is.

**Comment by jamuhl** [comment]
added that link to the translate hoc page...might help others...thanks for reporting
