### ISSUE TITLE
Allow Trans component to have empty children

### ISSUE THREAD

**Issue by chucksellick** [i18next/react-i18next#379]
I am trying to use the Trans component like this:

`<Trans i18nKey="myns:some.key" />`

Since the key exists in my lang file I do not need to provide any default content.

However this blows up my app with error `Uncaught Error: Trans(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.`

If I fill in any string as children of the Trans component then it is then correctly loading my text from the locale file. Would be nice if I didn't have to provide default content here / duplicate strings that are already in the locale file.

<img width="766" alt="screen shot 2018-01-12 at 12 34 58" src="https://user-images.githubusercontent.com/1188786/34875412-0a8065ee-f795-11e7-9ab1-8b9580483b01.png">

**Comment by jamuhl** [comment]
That's not the way Trans component works - it is to translate combinations of react components by mapping translation with react.children

For just plain translations you can use the t function:

```
<div>{t('myns:some.key')}</div>
```

or is there some reason you prefer using the Trans component for plain string translation?

**Comment by jamuhl** [comment]
if needed we might add some check here: https://github.com/i18next/react-i18next/blob/master/src/Trans.js#L100 if no children we just return the translation based on passed key...

**Comment by chucksellick** [comment]
Ok, yes I slightly misunderstood its purpose. However, it is still possible that this component could be passed an empty children via some other interface, and perhaps it would be good to have a guard against this error. I don't see any reason why the component should *not* be used in this manner if desired.

In my case I have changed to the `t` function anyway now. I was just translating a single string and returning that as a component, and the Trans syntax seemed cleaner there than using the HOC, but either way this was no big deal to work around.

**Comment by jamuhl** [comment]
let's keep this open - will see if we can support your case.

**Comment by jamuhl** [comment]
will be in react-i18next@7.4.0 coming later today...
