### ISSUE TITLE
Trans component not affected by parseMissingKeyHandler

### ISSUE THREAD

**Issue by RobinCsl** [i18next/react-i18next#380]
Hi there,

I tried to set up a custom `parseMissingKeyHandler` to better see in the end result which keys still need translating. However, it seems that only translations produced by the `t` function are affected by this handler. 
Is the Trans component meant to work with `parseMissingKeyHandler` as well out of the box?

Thank you

**Comment by jamuhl** [comment]
The Trans component automatically adds a defaultValue -> means there is no trigger for parseMissingKeyHandler -> which only triggers if a key gets no value, defaultValue -> you could try the missingKeyHandler

Just call the backend.saveMissing function if you like that anyway: https://github.com/i18next/i18next/blob/master/src/Translator.js#L142

**Comment by jamuhl** [comment]
could this be closed? or still not working with using the missingKeyHandler?

**Comment by RobinCsl** [comment]
Yes, sorry, this can be closed. I decided to use a different solution to achieve the same result: having a dev language which just shows some random text with Chinese characters and underscores to indicate it has not been translated. My point was just to make it visibly obvious which keys need translating.

**Comment by jamuhl** [comment]
beside that -> using a translation management tool like our https://locize.com would solve it too (advertising ;))
