### ISSUE TITLE
React-Native Not Translating.

### ISSUE THREAD

**Issue by napoleonjones** [i18next/react-i18next#383]
I am using i18next with React-Native/Expo and it seems to be reading from the i18next.js file for EN, but when I change the system language in android to German, its still showing the English text.  I am using the code provided in the example with minor tweaks due to the way I have navigation setup.

**Comment by jamuhl** [comment]
did you reopen the app? lng gets set on init...

**Comment by napoleonjones** [comment]
Yeah, I tried that.  I put this <Text>{t('common:currentLanguage', { lng: i18n.language })}</Text> on the page to verify that its reading the correct language setting and its returning "de_DE"

**Comment by jamuhl** [comment]
can you log out i18n.languages? and paste your config? don't see why it should not work

**Comment by napoleonjones** [comment]
I'm really new to react native and haven't figured out how to get logging to work with Expo but I'll try.

**Comment by napoleonjones** [comment]
console.log(i18n.languages); returns the following:

Array [
  "de_DE",
  "en",
]

**Comment by jamuhl** [comment]
i see...language is set to de_DE should be de-DE for i18next to work correctly.

change: https://github.com/i18next/react-i18next/blob/master/example/react-native-expo/js/i18n.js#L10

to `detect: (callback) => { return /*'en'; */ Expo.Util.getCurrentLocaleAsync().then(lng => { callback(lng.replace('_', '-')); })  },`

**Comment by napoleonjones** [comment]
That fixed it.  I appreciate the help.

Also, thank you for creating this library.

**Comment by jamuhl** [comment]
you're welcome
