### ISSUE TITLE
Interpolate component doesn't update on update language

### ISSUE THREAD

**Issue by jfreixa** [i18next/react-i18next#384]
Reproducing the issue:
https://www.webpackbin.com/bins/-L3hIF--xKouhF4EYw9L

**Comment by jamuhl** [comment]
ok i see...it's cause it's a pure component...and it does not get triggered an update...will change it back to a component (non pure) so it gets a rerender triggered.

will update this asap.

**Comment by jamuhl** [comment]
could you please try with: react-i18next@7.3.2

**Comment by jfreixa** [comment]
working correctly with react-i18next@7.3.2
