### ISSUE TITLE
Colon character is not parsed properly

### ISSUE THREAD

**Issue by aniruddhashevle** [i18next/react-i18next#387]
Colon(:) character is not parsed using t function but it's been parsed using Trans jsx.

If we use `t('Please fill the information below:')` output shows nothing.

But if we use `<Trans>Please fill the information below:</Trans>` output renders properly as it is.

Even if we use any other character inside function t(), it'll be parsed properly except the colon.

If we use `t('Please fill the :information below')` output shows only '**information below**' text. **function t() basically removes the string before the colon.**

If we use more than one colon `t('Please fill the :information :below')`, output '**information .below**' text. **It converts the other colons into dot**.

**Comment by jamuhl** [comment]
If you like to use `:` inside translations you will need to set: https://www.i18next.com/principles/fallback.html#key-not-found

```js
i18next.init({
  // allow keys to be phrases having `:`, `.`
  nsSeparator: false,
  keySeparator: false,
});
```

**Comment by jamuhl** [comment]
Just added a new section to readme: https://www.i18next.com/getting-started.html#important-read
