### ISSUE TITLE
Uncaught TypeError: children is not a function

### ISSUE THREAD

**Issue by kfarst** [i18next/react-i18next#390]
I'm having some rendering issues because the `children` object in the `<I18n>` component is returning an array with two empty strings and one function, causing the error `Uncaught TypeError: children is not a function`. I'm not exactly sure what the problem is, but I am passing an object in as a property that has the values set as `i18n.t()` functions, but because it's prefixed with the `i18n` instance I can't see why it would be a function naming conflict.

**Comment by jamuhl** [comment]
could you please past some code? Hard to understand the problem...

**Comment by jamuhl** [comment]
closing for now...feel free to reopen with additional details

**Comment by matiasmagni** [comment]
Having the same problem, any solution for this?

**Comment by kfarst** [comment]
@jamuhl Sorry I totally forgot about this! 

@matiasmagni I don't remember at this point but I believe I either restructured how I was including my various JSX snippets within the `render()` or I created an HOC component to handle translations that couldn't be done within the `<I18n />` component described [here](http://kfarst.github.io/10-mins-of-code/2018/03/22/using-i18next-in-react-without-react-i18next/)

**Comment by jamuhl** [comment]
@matiasmagni could you paste some details? i simply guess your using the I18n component with react component as children instead of a render prop function

**Comment by matiasmagni** [comment]
@jamuhl I've already solved it. <I18n> component has to have only 1 child component.

**Comment by legendstar99999** [comment]
Well. in my experience. ...
