### ISSUE TITLE
Trans component does not work with Preact

### ISSUE THREAD

**Issue by karolisgrinkevicius** [i18next/react-i18next#391]
Since version **7** `Trans` component returns `undefined` in vdom using Preact.
Steps to reproduce this issue:
1. Checkout https://github.com/i18next/react-i18next/tree/master/example/preact_withHOC
2. Change `react-i18next` to version `7.0.2`.
3. `npm start`
 
Expected result:
`Trans` component renders translation of either german string or english one.

Actual result:
`Trans` component renders `undefined`.

**Comment by jamuhl** [comment]
Just added a hint: https://github.com/i18next/react-i18next#requirements

Starting from version 7 we enabled to return the children of Trans component without additional wrapping into a unneeded div (newly possible in react 16) -> which seems not yet supported in preact - so you will have to define a parent for Trans component like described in above links

**Comment by karolisgrinkevicius** [comment]
Thanks @jamuhl. Your hint makes sense!
