### ISSUE TITLE
Language prefix in axios instance with Next.js

### ISSUE THREAD

**Issue by julmot** [i18next/react-i18next#392]
Let's assume my project setup is equivalent to the [Next.js example](https://github.com/i18next/react-i18next/tree/master/example/nextjs).

Now, to get the current language within a page's `getInitialProps` when called in client-side environments too, I already need something like the following, which feels already like a hack:

```javascript
Page.getInitialProps = async({req, store, asPath}) => {
  let lang = null,
    props = {};
  
  if (req) { // server-side (i18n not yet initialized)
    props = i18n.getInitialProps(req, [translationNamespace, 'common']);
    lang = props.i18n.languages[0];
  } else { // client-side (i18n already initialized)
    lang = i18n.languages[0];
  }
  
  // do some HTTP requests using the determined language ...
  
  return props;
};
```

This worked. However, I now I not only want to request something inside `getInitialProps`, but also in other sub-components. And I don't want to import i18next for every HTTP call just to construct an API URL using the language, e.g. `http://localhost:3001/de/`. Now adding the host itself isn't a problem with a custom axios instance:

```javascript
const instance = axios.create({
  baseURL: 'http://localhost:3001'
});
```

However, I can't use the language here, since it's not available until `getInitialProps` is called. So for example when importing the axios instance inside the page' file (e.g. `import myAxiosInstance from '../helpers/fetch;`) then it wouldn't work, as the import is of course executed before `myAxiosInstance` is used in `getInitialProps`. Therefore this wouldn't work:

```javascript
import i18n from '../hoc/i18n';

const instance = axios.create({
  baseURL: `http://localhost:3001/${i18n.languages[0]}`
});
```

So, my question is how to get the currently available language without waiting for a page's `getInitialProps` function from getting called?

**Comment by jamuhl** [comment]
puhh...idk...neither to deep into next.js nor ever used axios...you might better ask this over at stackoverflow...as it's less a question about i18next, react-i18next but more about general setup of an environment.

idependent of what you do...i18next will only have the language when set by the initialProps or using detectors and pass them down via cookie or another detection option:

- https://github.com/i18next/i18next-express-middleware#language-detection
- https://github.com/i18next/i18next-browser-languageDetector

so an option might be to wait for the language change event and config axios after that: https://www.i18next.com/api.html#onlanguagechanged

**Comment by jamuhl** [comment]
closing for now...feel free to reopen with more details or change request
