### ISSUE TITLE
The interpolation of Trans component is overridden and not documented

### ISSUE THREAD

**Issue by KochiyaOcean** [i18next/react-i18next#393]
https://github.com/i18next/react-i18next/blob/master/src/Trans.js#L109

The original perfix `{{` and suffix `}}` are overridden as `#$?` and `?$#`, but this change didn't shown in the document.

![image](https://user-images.githubusercontent.com/8194131/36349115-113cd4bc-14c3-11e8-99b0-3c2d5a5fd7fa.png)

**Comment by jamuhl** [comment]
and? that change is irrelevant as only applies to calls in Trans component - which does it's own interpolation.

**Comment by KochiyaOcean** [comment]
So the `count` prop of Trans component is useless in this example?

**Comment by jamuhl** [comment]
no...count prop on Trans is for plural handling the `{{count}}` in the inner child elements is interpolation

**Comment by KochiyaOcean** [comment]
Thanks for explanation.
