### ISSUE TITLE
Confusion with nextjs example

### ISSUE THREAD

**Issue by kachkaev** [i18next/react-i18next#397]
I was playing with next.js + react-i18next + typescript this weekend and fell into a pretty unfortunate trap, which took a while to investigate. It is to do with the interface of [i18n.js file](https://github.com/i18next/react-i18next/blob/4830bff4165b9f1a06ab6d2c15bc7249638b6d0a/example/nextjs/i18n.js).

Because `i18n.js` uses `require` & `module.exports` and then pages go for `import i18n from '../i18n';`, it's easy to get lost in what's being passed around. Because of this I ended up providing `translate()` hoc with a wrong `i18n` (i.e., a module object, not a class) here:

https://github.com/i18next/react-i18next/blob/bf6582276c6c10d5d14971497cc6c513a3440dd7/example/nextjs/pages/index.js#L21

This happened to me partially because I was using `import`/`export` everywhere inside my TypeScript project and so quite a lot of time was lost 😅 

I'm wondering if `module.exports` could be made more explicit in `i18n.js` to help others avoid the same confusion. I'd export three non-default things rather than just `i18n` (which as I turned out has got `.default` property, equal to `I18n` class 😮 ). These exports would be:

```js
module.exports = {
  i18nInstance, // result of require('i18next') + manipulations like .use(XHR), to be used in server.js
  I18n: i18n.default, // Class to be used in translate hocs later
  getInitialProps, // a detached async function to be used in pages or withI18next hoc
}
```

Here is how a modified version of `i18n.js` looks in my TypeScript project: https://github.com/callthemonline/client-nextjs/blob/63d5d15cadd1879fd62e20d045f5c12a35d6406e/server/i18n.ts

WDYT of changing module exports @jamuhl? I'll be happy to submit a PR to the next js repo (because the example is a couple of commits ahead) and we'll then sync this repo's example too.

**Comment by kachkaev** [comment]
I [my i18n.ts](https://github.com/callthemonline/client-nextjs/blob/63d5d15cadd1879fd62e20d045f5c12a35d6406e/server/i18n.ts) I use `import * as i18n from "i18next";`, which works the same as `const i18n = require('i18next')`. Then I `export { getInitialProps, I18n, i18nInstance }`, which is compatible to `module.exports = { ... }`.

> i18n.default will be undefined

That's right, but that gets solved by `import { I18n } from '../i18n'` or `const { I18n } = require('../i18n')` in other project files. The point of exporting three things in parallel and later refer to them like this:

* https://github.com/callthemonline/client-nextjs/blob/63d5d15cadd1879fd62e20d045f5c12a35d6406e/server/index.ts#L9

* https://github.com/callthemonline/client-nextjs/blob/63d5d15cadd1879fd62e20d045f5c12a35d6406e/lib/hocs/withI18next.tsx#L2

This makes it easier to track what depends on what and also removes a combination I got trapped by:


https://github.com/zeit/next.js/blob/dbb1b732a06e92f8730d26fa01dac4d53c744732/examples/with-react-i18next/i18n.js#L59
↓
https://github.com/zeit/next.js/blob/dbb1b732a06e92f8730d26fa01dac4d53c744732/examples/with-react-i18next/lib/withI18next.js#L2

We are exporting `x` and are then importing `x.default` with the same name `x`. I missed this this important difference and simply replaced `module.exports = i18n` with `export default i18n` while moving `i18n.js` to TypeScript. Because I forgot to change `import i18n from '.../i18n`, I was importing a wrong object and it took a while to investigate why my translate hoc is failing. It was receiving an object instead of `I18n` class, which took a while to trace down.

My point is that if we change what's being exported in the example's `i18n.js` fewer people may get into the same trap because they won't have to deal with a hidden magic `i18n.default` property they do not know about.

I'm happy to submit a PR to next.js to better describe what I mean.

**Comment by jamuhl** [comment]
agree...i would say change that export...as it does not break - it does not hurt ;)

**Comment by kachkaev** [comment]
➡️ https://github.com/zeit/next.js/pull/3959

**Comment by kachkaev** [comment]
I've got one more little question left 😄 

What's the best way to toggle `debug` in `development`/`production`? If i18n only worked on the server, I'd be possible to replace [`debug: true`](https://github.com/zeit/next.js/blob/a225da4bb11d6618eb506ae1341acd34b135b593/examples/with-react-i18next/i18n.js#L13) with something like `debug: process.env.NODE_ENV === 'production'`. But how to make this universal? 🤔 

It'd be great if the example had `debug: false` in production.

**Comment by jamuhl** [comment]
@kachkaev not so deep into next.js...from guessing i would think process.env.NODE_ENV exists on client too (like in create-react-app) but chance is my guessing is wrong ;)

**Comment by kachkaev** [comment]
You're right, `process.env.NODE_ENV` does exist on the client too! 🎉 

https://github.com/zeit/next.js/pull/3964
