### ISSUE TITLE
[Feat] Ready prop while namespaces are being loaded

### ISSUE THREAD

**Issue by perrin4869** [i18next/react-i18next#398]
Right now if the `wait` prop is passed, `I18next` will render null until all namespaces have loaded. A more general approach would pass a `ready` (or maybe, `translationsReady` to avoid collisions) prop to the rendered component and allow it to decide what to do while the translations are loading (maybe show a spinner?)
Would you be open to a PR implementing this breaking change?
Thanks!

**Comment by jamuhl** [comment]
hm...i would prefer having that backwards compatible...breaking would be to annoying for the users happy with not showing something until loaded...

https://github.com/i18next/react-i18next/blob/master/src/I18n.js#L115

there are two options:

a) allow setting a placeholder component (less powerful - but good enough for a spinner)
b) pass down a prop like you suggest

Open for a PR doing a) or b) as long not breaking...(add an option for that via prop, i18next.options.react)

**Comment by perrin4869** [comment]
Hm... I really think it would be best to just go ahead and make a major release with a breaking change for something like this...
We can try to make it not breaking but it would be awkward... And upgrading would not be a big hassle for people upgrading and this is a pretty big improvement in usability
If you want to keep it backwards compatible nontheless, I can add a `renderNullWhileWaiting` kind of option that defaults to true, and pass a `translationsReady` property to the rendered component otherwise

**Comment by jamuhl** [comment]
it's not a problem if awkward as most people won't show a spinner. Where is the improvement in seeing a spinner for some milliseconds? Idk your backend...but at our production apps there is no noticable wait for that load of translations.

**Comment by jamuhl** [comment]
Sorry, didn't want to sound rude. But it's really just something i don't see that is needed by most users - so making life for them harder by breaking the code and needing to opt in for a placeholder while loading is a no go for me...

**Comment by perrin4869** [comment]
No problem. For the record, there could always be network latency, etc, and it would not make people necessarily opt in for a placeholder, they can just keep rendering `null` while waiting.
But I'll send a non-breaking PR shortly

**Comment by jamuhl** [comment]
closing as done with latest PR....
