### ISSUE TITLE
Facing problems with i18nLoadedAt

### ISSUE THREAD

**Issue by TimoRuetten** [i18next/react-i18next#401]
We are using the translate hoc for a few components in our Application. After facing some problems that components get rerendered multiple times we logged which properties rly changed in our application.

After we've done this we find out that the property i18nLoadedAt is triggering the most rerenders. In numbers: About 30 times our components will be rerendered because of this property. All in all maybe 20 (or more) components are using this hoc so its about 600 rerenders for the first init of our Application. 

I've found another issue where another person had the same problem. This did not helped at all.

What we are doing (maybe here is the problem ?) is:
- because we are using SSR on Server we will load the language files directly (there isnt a problem I guess)
- on client we will load (currently) ALL language data into the payload. So "reloading" any file is unnecessary.  (later we will change it, but currently its that way)

In the other issue I've read that I should set the react setting wait to true. But this, however, will cause a completely App crash with an error which does not help (Cannot read property 'properties' of undefined in the very first component which has the translateHoc - but the error is pointing to the componentWillMount method. Strange!)

So my questions are:
1) Why is this property updating, even when there is no file to load, because all data is still in payload ?
2) How to deactivate the i18nLoadedAt property in the hoc (if its possible)
3) Do you have any clue why I am not able to set the wait to true ?

This is my i18n configuration function:

```javascript
export default function (i18next, opt = {}) {
  i18next.init(Object.assign({
    fallbackLng: 'en',
    whitelist: [
      'en',
      'de',
      'pt',
      'es',
      'fr',
    ],
    nonExplicitWhitelist: true,
    ns: [
      'ui',
      'textBlock',
    ],
    defaultNS: 'ui',
    react: {
      wait: true,
    },
  }, opt));
  return i18next;
}
```

**Comment by TimoRuetten** [comment]
I will close this issue because we've fixed it. We used the XHR backend and the problem was that we can use the url /de but also /de-DE but in the payload only data for de is available. So when setting the language to de-DE i18next tries to load the file (which does not exist). We've removed the XHR Backend for now because currently we load everything into the payload.

**Comment by jamuhl** [comment]
if you only provide languages like you set in whitelist (without region -> no de-DE, only de) you can use the load option in i18next: https://www.i18next.com/configuration-options.html#languages-namespaces-resources

```js
i18next.init(Object.assign({
    fallbackLng: 'en',
    load: 'languageOnly',
    whitelist: [
      'en',
      'de',
      'pt',
      'es',
      'fr',
    ],
    nonExplicitWhitelist: true,
    ns: [
      'ui',
      'textBlock',
    ],
    defaultNS: 'ui',
    react: {
      wait: true,
    },
  }, opt));
  return i18next;
}
```

that way de-DE will only trigger to load de
