### ISSUE TITLE
How can I user different JSON file and setup i18n.js file

### ISSUE THREAD

**Issue by Rutulpatel7077** [i18next/react-i18next#402]
instead of using common namespace file called translations.json  can I use  many different files?

**Comment by jamuhl** [comment]
sure...that's what it is about...see the first sample here: https://react.i18next.com/components/translate-hoc.html#translate-hoc

**Comment by Rutulpatel7077** [comment]
is path is same? public/locales ?

**Comment by jamuhl** [comment]
yes...beside where the other translations.json is (or whatever you configure the path to be ;))

**Comment by Rutulpatel7077** [comment]
Got it!  Thanx Sir!

**Comment by jamuhl** [comment]
you're welcome...

**Comment by JavierPons** [comment]
Hi there, I'm interested in this issue. When I clicked on the upper link (from 6 Mar) I found that is dead. Could be possible to re-link again for see how it works? Thanks!

**Comment by jamuhl** [comment]
https://react.i18next.com/components/withnamespaces
