### ISSUE TITLE
Add translations at an array of list value

### ISSUE THREAD

**Issue by Sohadwd** [i18next/react-i18next#403]
First, thank you very much for this hard work and amazing tutorial.
I use it in my App and it's worked, but I need to translate the data component in the array of list.

I have this array : 
`var dataSaleThumb = [
      {
        id: 1,
        imageSaleThumb: require("../../images/men1.png"),
        brand: "שם מוצר",
        price: "$1,299",
        discount: "$500",
        discountedPrice: "$699",
        description: "סופר סלים מתאים חליפה רשמית"
      },
      {
        id: 2,
        imageSaleThumb: require("../../images/men2.png"),
        brand: "שם מוצר",
        price: "$1,299",
        discount: "$500",
        discountedPrice: "$699",
        description: "סופר סלים מתאים חליפה רשמית"
      }]`
and I need to translate description to another languge, and this way `{t("slider")}` dosn't work.
So How I can use it? 

Thank you very much for your time and looking forward to reading your answer!
Best wishes,

**Comment by jamuhl** [comment]
Hi @Sohadwd, i guess you like to translate the brand and descriptions from those objects in your array.  Right?

You will need to map through the array and translate those values like eg.

```js
const translatedDataSaleThumb = dataSaleThumb.map(item => {
  const ret = {
    ...item,
    brand: t(item.brand),
    description: t(item.description)
  };
  return ret;
});
```

**Comment by Sohadwd** [comment]
Yes exactly! 
And it's WORK thank you @jamuhl  :100: 

but it takes the same description ore translate for each item and I need a different description for each item, jow I can do it?

**Comment by jamuhl** [comment]
hm...descriptions in your array looks different so you should get different calls to `t` resulting in different translations...

could you paste your code you use to render this array?

**Comment by jamuhl** [comment]
so i guess the text you see is `roundImageText={item.roundImageText}` but that seems not to be a value of your items in `translatedDataSaleThumb`

**Comment by Sohadwd** [comment]
sorry for many questions , but see this my code in **Home page**

First the array : 

`var roundImageData = [  //first section / icons
  {
    id: 1,
    roundImageSource: require("../../images/wallet-icon.png"),
    roundImageText: "ארנק"  
  },
  {
    id: 2,
    roundImageSource: require("../../images/clothes.png"),
    roundImageText: "עניבה"  

  },
  {
    id: 3,
    roundImageSource: require("../../images/shirt.png"),
    roundImageText: "חולצה"
  
  },
  {
    id: 4,
    roundImageSource: require("../../images/jeans-pocket.png"),
    roundImageText: "ג'ינס"
     
  }
];`  

and here the map : 

`  const { t, i18n } = this.props;
    const translatedroundImageDat = roundImageData.map(item => {
    const ret = {
      ...item,
      roundImageText:item.roundImageText

    };
    return ret;
    });`

and here the render items: 

`<Card style={Style.mainCategories}>
            <List
              removeClippedSubviews={false}
              contentContainerStyle={{ flexDirection: "row" }}
              directionalLockEnabled={false}
              horizontal={true}
              showsHorizontalScrollIndicator={false}
              dataArray={translatedroundImageDat}
              renderRow={item =>
                <RoundImageButton
                  navigation={navigation}
                  roundImageText={item.roundImageText}
                  roundImageSource={item.roundImageSource}
                />}
            />
          </Card>`


and finally , the translate in i18n.js file : 

`  he: {   //en
        home: {
          section1: "מכנסיים ג’/ינסים",
          section2:"מכנסיים ג’/ינסים",
          section3:"חולצות מכופתרות מדהימות",
          slider: "מגמות",
          roundImageData1: "ארנק",
          roundImageData2: "עניבה",
          roundImageData3: "חולצה",
          roundImageData4: "ינס"
                },`

`  ar: {
        home: {
          section1: "بنطلون / جينز",
          section2: "بنطلون / جينز",
          section3: "قمصان زرقاء مذهلة",
          slider: 'اتجاهات',
          roundImageData1: "المحفظة",
          roundImageData2: "ربطة عنق",
          roundImageData3: "بلوزة",
          roundImageData4: "فينس"
        },`

So ho I can translate it, with different value for each item

**Comment by jamuhl** [comment]
Your map does currently no translation...but looking at your translations you can do:

```
<Card style={Style.mainCategories}>
            <List
              removeClippedSubviews={false}
              contentContainerStyle={{ flexDirection: "row" }}
              directionalLockEnabled={false}
              horizontal={true}
              showsHorizontalScrollIndicator={false}
              dataArray={translatedroundImageDat}
              renderRow={(item, i) =>
                <RoundImageButton
                  navigation={navigation}
                  roundImageText={t(`roundImageData${i}`}
                  roundImageSource={item.roundImageSource}
                />}
            />
          </Card>
```

i guess

**Comment by Sohadwd** [comment]
I try this way but it gives me a syntax error ! :/ 

Can I put the translation on the map?

**Comment by jamuhl** [comment]
roundImageText={t(`roundImageData${i}`**)**}

**Comment by Sohadwd** [comment]
the code doesn't accept this method! :\

**Comment by jamuhl** [comment]
best might be asking this over at stackoverflow - as this issue is not really related to i18next or this repo - it's more or less about how to write code.

Adding all the code well formatted would also help. Hard to do remote debugging with just "code doesn't accept this method!"

**Comment by jamuhl** [comment]
@hemavkha you ITEMS is a function -> call it `<component items={ITEMS(t)} />`

**Comment by hemavkha** [comment]
> @hemavkha you ITEMS is a function -> call it `<component items={ITEMS(t)} />`

Its working Thanks @jamuhl
