### ISSUE TITLE
componentWillMount is deprecated in React 16.3

### ISSUE THREAD

**Issue by se-bastiaan** [i18next/react-i18next#404]
See https://medium.com/@baphemot/whats-new-in-react-16-3-d2c9b7b6193b and https://github.com/reactjs/rfcs/blob/master/text/0006-static-lifecycle-methods.md

**Comment by jamuhl** [comment]
thanks for pointing this out...same is for the updated context - which as always makes it just harder to keep compatible with preact...

will need to find time for those update

**Comment by jamuhl** [comment]
https://github.com/i18next/react-i18next/commit/2e55617b2542139294fdc87803eeb157fde30589 will remove this

and will revisit https://github.com/i18next/react-i18next/issues/405 for context api update
