### ISSUE TITLE
prepare for react 17  - context api update

### ISSUE THREAD

**Issue by jamuhl** [i18next/react-i18next#405]
guess we need to polyfill it to stay backwards compatible with older versions and preact

possible polyfill: https://github.com/jamiebuilds/create-react-context

or completely remove the context stuff in favour of setting the build in i18nInstance using the reactI18nextModule https://react.i18next.com/components/i18next-instance.html#i18next-instance

or the setDefaults in our own global state: https://github.com/i18next/react-i18next/blob/master/src/context.js

**Comment by langovoi** [comment]
FYI: polyfills

https://github.com/jamiebuilds/create-react-context
https://github.com/reactjs/react-lifecycles-compat
https://github.com/soupaJ/create-react-ref

**Comment by jamuhl** [comment]
using https://github.com/jamiebuilds/create-react-context this was done in react-i18next@8.0.0
