### ISSUE TITLE
translate compose Cannot read property 'options' of undefined

### ISSUE THREAD

**Issue by melihberberolu** [i18next/react-i18next#406]
https://github.com/zeit/next.js/tree/canary/examples/with-i18next

I'm integrated like this example. But if i'm compose with translate(['common])
error : Cannot read property 'options' of undefined

**Comment by jamuhl** [comment]
did the sample as is work?

**Comment by melihberberolu** [comment]
Yep. It's like that.

**Comment by jamuhl** [comment]
if sample works without issue...it's something with your code

**Comment by jamuhl** [comment]
Closing this for now...feel free to reopen if still an issue.
