### ISSUE TITLE
`tReady` is not a valid property for React (16.2.0)

### ISSUE THREAD

**Issue by olivierpascal** [i18next/react-i18next#407]
Warning: React does not recognize the `tReady` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `tready` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

**Comment by jamuhl** [comment]
on which element do you get that?

**Comment by olivierpascal** [comment]
Oh sorry for the lack of context. Here is an example:

```
import { translate } from 'react-i18next';

const MyComponent = ({ children, ...rest }) => (
  <MyOtherComponent {...rest}>
    {children}
  </MyOtherComponent>
);

export default translate('myNamespace')(MyComponent);
```

**Comment by jamuhl** [comment]
And your "MyOtherComponent" is something like `<div {...props}></div>`

**Comment by olivierpascal** [comment]
Yes. I edit, for a clearer example.

**Comment by jamuhl** [comment]
doing `<div {...rest}>` is something you should avoid...be explicit on what attributes you need on a DOM element.

do something like:

```js
import { translate } from 'react-i18next';

const MyComponent = ({ children, ...rest }) => (
  <div {_.pick(...rest, ['style', 'otherOkProp']}>
    {children}
  </div>
);

export default translate('myNamespace')(MyComponent);
```

**Comment by olivierpascal** [comment]
It makes sense. And if I need to forward `t` or `tReady` properties I'd rather forward them via `data-t` or `data-tReady` DOM attributes.

**Comment by oliviertassinari** [comment]
Same problem. I will destructure the `tReady` property from the properties.

**Comment by onlydave** [comment]
Should `tReady` be added to the react-i18next DefinitelyTyped file?

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-i18next/src/props.d.ts

**Comment by jamuhl** [comment]
@onlydave should yes...the typescript definitions are maintained by the community...so you will have to create a PR there if like to have that in.

**Comment by onlydave** [comment]
@jamuhl should `tReady` is always present and a boolean or is it optional?

**Comment by jamuhl** [comment]
both hoc and render prop will pass it down:

hoc: https://github.com/i18next/react-i18next/blob/master/src/translate.js#L66
renderprop: https://github.com/i18next/react-i18next/blob/master/src/I18n.js#L123

**Comment by jamuhl** [comment]
and yes boolean true or false
