### ISSUE TITLE
any way to change namespace like i18n.changeLanguage("en") ?

### ISSUE THREAD

**Issue by johnantoni** [i18next/react-i18next#408]
Hi, is there any way to change the namespace like i18n.changeLanguage("en")

E.g.

`i18n.changeNamespace("blue-theme");`

**Comment by jamuhl** [comment]
no need for that:

you can do `i18next.t('namespace:key')` to get a key from another namespace

when using the translate hoc or I18n render prop you get a t function set to the first namespace passed in: https://react.i18next.com/components/translate-hoc.html or https://react.i18next.com/components/i18n-render-prop.html

```js
    <I18n ns={['defaultNamespace', 'anotherNamespace']}>
      {
        (t, { i18n, t, ready }) => (
           // t will return keys of 'defaultNamespace
        )
      }
    </I18n>
```

you also can use: https://www.i18next.com/api.html#getfixedt to get a fixed t function

**Comment by johnantoni** [comment]
thanks @jamuhl

**Comment by joshua-turner** [comment]
I disagree - there is absolutely a need for this.

We set namespaces dynamically based on client subdomains, which can change when impersonating those users in-app.

Setting a new default namespace doesn't rerender any strings already loaded, since there is no event listener like 'languageChanged' to listen to in the react init settings.

**Comment by jamuhl** [comment]
If you need to set namespace based on a per customer base (client subdomain) -> correctly that is done by using a language in form `lng-script-Region-x-customerId` eg. `en-x-github`. `-x-` is the marker for custom language variation.

**Comment by veelenga** [comment]
There is also [setDefaultNamespace](https://www.i18next.com/overview/api#setdefaultnamespace) which changes the default namespace obviously.

**Comment by jamuhl** [comment]
@veelenga 

- default -> used as default
- useTranslation -> gets a t function bound to the namespace passed
- getFixedT -> create a t function bound to a namespace
- prepend namespace in from of key to use that namespace `t(ns:key)`

**Comment by Zhuoqin** [comment]
https://www.i18next.com/overview/api#setdefaultnamespace
