### ISSUE TITLE
Implement on regular React-Native Project, Without Expo.

### ISSUE THREAD

**Issue by AliZeynalov** [i18next/react-i18next#409]
Hi,

I need to use the component on my React-Native project. But I do not use Expo. I got errors while trying to integrate component to my project. Can I use this component without expo?

P.S I created my app with `react-native init`, not `create-react-native-app`

**Comment by jamuhl** [comment]
Yes...we use this on a pure react-native app...different to the sample here https://github.com/i18next/react-i18next/blob/master/example/react-native-expo/js/i18n.js#L7 you should / could use the https://github.com/DylanVann/i18next-react-native-language-detector

**Comment by jamuhl** [comment]
did you get it to work...?

**Comment by AliZeynalov** [comment]
yeap. Your answer worked for me.
