### ISSUE TITLE
Does react-i18next work with react router?

### ISSUE THREAD

**Issue by terhuerne** [i18next/react-i18next#413]
Maybe this is a absolute noob question but I'm trying anyways. ;-) I'm trying to add react-i18next to my project but have a problem getting it work. I try to use the HOC approach. My Component looks like this:

```
import React, {Component} from 'react';
import {translate} from 'react-i18next';

import './main.scss';

class Main extends Component {
  render() {
    const {t} = this.props;
    return (
      <div className="main">
        <h1>{t('title')}</h1>
      </div>
    );
  }
};

export default translate('translations')(Main);
```

I can see from the console that i18n is initialized but my component does not load. When I export the class directly there is no issue. So I'm suspecting the last line to be the problem. I'm using react-router. Does anyone have an idea what's going wrong?

Thanks!

**Comment by terhuerne** [comment]
Okay, got it working. Without HOC but with the I18nextProvider

**Comment by jamuhl** [comment]
you need the provider outside -> or on i18next.use -> reactI18nextModule -> just follow the sample

the hoc or render prop (I18n) is needed to pass t function as prop to your component. Plenty of examples for both in the example folder.
