### ISSUE TITLE
translation not load with initialI18nStore option?

### ISSUE THREAD

**Issue by ducdigital** [i18next/react-i18next#415]
It seems like the initialI18nStore setting when set, automatically block i18next from loading ajax.

How can I force i18next to load the full translation file using ajax?

The reason is to reduce load, I pass only what required for serverside rendering into initialI18nStore after that I expected a full translation loaded using ajax.

How can I archive this?

Thank you

**Comment by jamuhl** [comment]
initialI18nStore does set what was passed -> i18next won't load the namespaces that were already in that object -> but will load every other namespace which should be loaded lazy afterwards (not part of initial load of that page).

Anyway:
a) if you like to load omit initialI18nStore
b) call i18next.reloadResources() https://www.i18next.com/api.html#reloadresources

**Comment by ducdigital** [comment]
@jamuhl thank you for your answer. I have been taking a look at `reloadResources()` but it seems like this method ignore all cache so every page load is loaded with the translation's json.

the main issue is that we only use one single namespace for everything. (this is not the best practice ofc)

method `a)` is not an option since if I omit, the SSR will cause translations to flicker ( translated -> non-translated -> translated)

method `b)` as I said above does not take into account the cache

The solution I currently come up with is set the translations returned from server-side rendering to a language called `ssr`, the in i18next config, I set the `fallbackLng` to `ssr`

This probably not a best method either.

It will be nice if we can add an option, that allows loading of translation anyway and override the loaded translation from `initialI18nStore`.

**Comment by jamuhl** [comment]
b) what you mean by taking into account the cache? it does a forced reload and overwrite the existing translations

if i get your setup right you just pass down partial content of the namespace to initialI18nStore - so reloading all does not really hurt - there is no way to load the missing stuff only anyway - you can just reload full namespaces.

"It will be nice if we can add an option, that allows loading of translation anyway and override the loaded translation from initialI18nStore." Its what reload does...it reloads all the translations and overrides initalI18nStore...might be i understand you wrong

**Comment by jamuhl** [comment]
This still an issue? or did you find a solution?
