### ISSUE TITLE
Interactive playground seems to be down

### ISSUE THREAD

**Issue by chrbala** [i18next/react-i18next#418]
https://www.webpackbin.com is down right now. I'm getting a ``server IP address could not be found`` and [http://www.isitdownrightnow.com/webpackbin.com.html](isitdown) says that it's down for everyone.

The playground should either be moved, or removed from the docs.

**Comment by jamuhl** [comment]
will need to copy it from: https://webpackbin-prod.firebaseapp.com/bins/-KvzvUPFsBVI_74Jll99 to https://codesandbox.io/ i guess...will do so the next days

Thank you for reporting

**Comment by jamuhl** [comment]
https://codesandbox.io/s/8n252n822

will update links now

**Comment by jamuhl** [comment]
Migration on gitbook (react.i18next.com) will take a little longer...need to migrate documentation first - seems gitbook made an big update i wasn't aware of :(
