### ISSUE TITLE
Trans unable of first word interpolation

### ISSUE THREAD

**Issue by newsiberian** [i18next/react-i18next#425]
Hi,

I faced with such problem:
```js
<Trans i18nKey="some-route" value="word">
  <strong>{{value: 'word'}}</strong> here
</Trans>
```
with json:
```json
{ "some-route": "<1><0>{{value}}</0></1> here" }
```
will transform into: "here here"

If I do:
```js
<Trans i18nKey="some-route" value="word">
  A <strong>{{value: 'word'}}</strong> here
</Trans>
```
with json:
```json
{ "some-route": "A <1><0>{{value}}</0></1> here" }
```
transforms into: "A **word** here".

Am I doeing anything wrong?

**Comment by jamuhl** [comment]
Your second sample is well formed while the first is not. 

The „tag“ <1> tells to insert the second react node at that position ( index starts with 0 ) 

So in your first sample it tells to take the text node here and it inserts that. So you end up having „here here“

Correct would be. 

<0><0>{{value}}</0></0> here

**Comment by newsiberian** [comment]
Great, it works!
@jamuhl, thanks for explanation and for your efforts.
