### ISSUE TITLE
Object interpolation doesn't work

### ISSUE THREAD

**Issue by resurge** [i18next/react-i18next#426]
Hey, [this example](https://www.i18next.com/translation-function/objects-and-arrays#objects) from the docs doesn't seem to work.

I adjusted the example code from [codesandbox](https://codesandbox.io/s/61n3k3vk3w) to illustrate.
I expected this to show the text "added gold". In reality it's showing the text "added {{something}}"

**Comment by adrai** [comment]
try to set `keySeparator: '.'` this should do the trick

**Comment by jamuhl** [comment]
like https://codesandbox.io/s/044kjv6xnp if you like having keySeparator set to false in general.

**Comment by resurge** [comment]
That seems to work yes, thanks.

I did notice that I misdescribed my real-world problem though. (Array interpolation)  
But I found a possible solution for that here: https://github.com/i18next/i18next/issues/1049

Thanks for the great library and quick support!
