### ISSUE TITLE
Passing initialI18nStore to translate HOC

### ISSUE THREAD

**Issue by ThiagoMiranda** [i18next/react-i18next#427]
Hi...
I'm using `react-i18next` with Gatsbyjs and I need to pass the locale directly to my `translate` HOC after importing it on my component so I won't need any ajax call. I've removed the i18next backend from my .use() function when initialising the i18n and passed to my I18nextProvider like this ( it took a while to figure it out because the docs are a little abstract about it. On my layouts/index.js file ):

```javascript
import HomeEN from '../locales/en/Home.json'
import HomePT from '../locales/pt/Home.json'

const store = {
    'en': {
         'Home': HomeEN
    },
    'pt': {
         'Home': HomeEN
    }
}

const Layout = (props) => (
  <I18nextProvider initialI18nStore={store} i18n={createI18n} initialLanguage={'en'}>
    <Fragment>
      <Header />
      <Body>{props.children()}</Body>
      <Footer />
    </Fragment>
  </I18nextProvider>
)
```
 
So this is working fine. But when I have more locales files the layout file gets a little verbose so I was wondering if I can pass to my Home Component directly, for example. I've saw this written in the docs but does not work if I use the same "pattern" as the i18nextProvider and I can't figure which one I can use. My goal would be something like this:

```javascript

import HomeEN from '../locales/en/Home.json' 
import HomePT from '../locales/pt/Home.json'
const store = {
    'en': {
         'Home': HomeEN
    },
    'pt': {
         'Home': HomeEN
    }
}

const Home = () => {}

export default translate({ initialI18nStore: store })(Header)

```

Thanks!

**Comment by jamuhl** [comment]
react-i18next is one implementation for i18next, so there are multiple options to pass translations to the i18next instance.

please read following docs:

- https://www.i18next.com/overview/getting-started#basic-sample (options.resources on init of i18n)
- https://www.i18next.com/overview/api#resource-handling (add resourceBundle)

the initialI18nStore is "just" for passing resources from server side render to client side render in case where translations are loaded async using xhr to avoid flickering.

if not getting to a solution with this additional information feel free to ask for more help.

**Comment by ThiagoMiranda** [comment]
Passing as resource property on the i18n will do. Thanks @jamuhl !!!
