### ISSUE TITLE
Feature recommendation: simple <TranslatedText/> component

### ISSUE THREAD

**Issue by JReinhold** [i18next/react-i18next#429]
Hi. I've been using react-i18next for a while now, and I'm really happy with it. Early on, I made a wrapper component that simplified the use of simple translations greatly. I would like to recommend that this component somehow became a standard component in this library, so everyone can use it. Let me explain what it is:

A simple `<TranslatedText/>` component that takes a translation key, and any extra `t` props, and renders a `string` in the component tree.

### Example usage:

```jsx
class SomeComponent extends Component {
  render() {
    return (
      <div>
        Here is how to say hello in your language: <TranslatedText translationKey="hello"/>
      </div>
    );
  }
}
```

Using this, you no longer have to wrap your renders in the `<I18n/>` component for render prop, or use the `translate` HOC. That is all handled directly inside the `<TranslatedText/>` component.

### Implementation

In it's simplest form, the TranslatedText component is implemented the following way:

```jsx
export const TranslatedText = ({ translationKey, ...options }) => {
  return (
    <I18n ns={'translation'}>
      {t => {
        return t(translationKey, options);
      }}
    </I18n>
  );
};
```

As you can see, all it does is that it calls `t()` with any optionally specified options, such as `count`, etc. I've also added string manipulation props to my own component such as `capitalize={true}`, but I'm not sure if they should be part of a core implementation in this repo.

This is really useful for places where you just want simple translated strings, which in my case is upwards of 95 % of the places.
If you want to use more advanced stuff from the translation functions, the regular method of render props/HOC is still better suited.

I'd be happy to submit a PR for this, if the maintainers of `react-i18next` thinks this is a good idea. This issue is basically to test the waters, before I put more work into it. :) This also means I haven't tested it outside of default React such as in next.js or Preact, but I don't see why it shouldn't work there as well.

**Comment by jamuhl** [comment]
For sure the documentation is not yet optimal...the main usecase is wrapping some more complex jsx nodes including html or custom elements

**Comment by JReinhold** [comment]
Okay, I've done some experiments now, and indeed the `<Trans/>` component is able to do what I want. Yay! I might do a PR to the documentation, that describes this "feature" better for newcomers.

I'm experiencing a weird issue though, that anywhere I use the `<Trans />` component, it will try to translate the key BEFORE i18n is fully initialized. This consistently results in missing translations, and gives me the following stream of warning in the console:
```
i18next::translator: missingKey undefined translation nested.welcomeMessage 
logger.js:23 i18next::backendConnector: loaded namespace translation for language en
logger.js:23 i18next: languageChanged en
logger.js:23 i18next: initialized {debug: true, initImmediate: true, ns: Array(1), defaultNS: "translation", fallbackLng: Array(1), …}
```

See that the language is `undefined`, and is only changed later to `en`. This is only a problem when using the `<Trans />`. I tried to reproduce the issue in a CodeSandbox, but I couldn't.

This is the i18n setup:
```
import * as i18n from 'i18next';
import * as XHR from 'i18next-xhr-backend';
import * as LanguageDetector from 'i18next-browser-languagedetector';
import { reactI18nextModule } from 'react-i18next';

i18n
	.use(XHR)
	.use(LanguageDetector)
	.use(reactI18nextModule)
	.init({
		fallbackLng: 'en',
		debug: true,
		interpolation: {
			escapeValue: false, // not needed for react!!
		},
		ns: ['translation'],
		defaultNS: 'translation',
		react: {
			wait: true
		},
	});

export default i18n;
```

Either way, I'm hoping it's an issue only related to this specific project, which I'm not continuing anyway. So don't spend too much time on this, it was only if you knew why this was happening.

You can close this issue if you want to.

**Comment by jamuhl** [comment]
a PR to documentation would be very welcome.

The issue you experience is initializing is asynchronous. Loading the translations via xhr. So the rendering occurs before the translations were loaded. For that we introduced the translate HOC / render prop with the option wait: true -> that component asserts translations were loaded before rendering any content.

**Comment by JReinhold** [comment]
That makes total sense, but I would expect that the `<Trans />` component would also wait, like the HOC/render prop.

Although if you use it like `<Trans>This is fallback text</Trans>` it of course shouldn't wait.

But the fact that `<Trans />` doesn't wait makes me rethink if it is really suitable for the use case I looking at.

**Comment by jamuhl** [comment]
Currently it's like this:

**I18nextProvider**: optional to pass i18n instance to react context
**Translate HOC / render prop**: Used to set namespace and pass down t function via context; additional option to wait for loaded
**Trans**: used to translate combined jsx nodes, eg. Links in text, formatted text,...

So based on the async init (if loading translations and not passing them in via options.resources on init) you will need the hoc or render prop at some place.

**Comment by JReinhold** [comment]
Okay, thanks for the overview!

Then for my use case, I will stick with the custom `<TranslatedText />` component, as the `<Trans />` component doesn't completely fill that use case.

**Comment by jamuhl** [comment]
Closing this for now
