### ISSUE TITLE
react-native-expo example seems too old and obslete

### ISSUE THREAD

**Issue by niteshgrg** [i18next/react-i18next#433]
Trying to figure out about provider with the example in repo but as decorators are obsolete.

Unable to get rid of decorator without not exporting react class out. Could use some clarification and if example could be updated then i think it would help a lot of people.

**Comment by jamuhl** [comment]
You can like with any other HOC not use decorators (decorators are just syntactic sugar). Just use the hoc like here:

https://github.com/i18next/react-i18next/blob/master/example/react_withHOC/src/App.js#L33

**Comment by jamuhl** [comment]
closing for now...a PR updating the sample would be welcome....else i will update that in a few months if having spare time doing so
