### ISSUE TITLE
How do I use Trans with interpolated components?

### ISSUE THREAD

**Issue by redcapital** [i18next/react-i18next#436]
I have this code:

```
const comp = <b>Comp</b>;
return <Trans i18nKey="foo">Foo {{ comp }}</Trans>;   
```

and the translation key is (taken from debug log for missing translations):

```
"foo": "Foo <1>{{comp}}</1>",
```

What I expect is this HTML output:

```
Foo <b>Comp</b>
```

but instead I get:

```
Foo [object Object]
```

how do I achieve this?

**Comment by jamuhl** [comment]
In Trans {{ var }} stands for interpolating numbers or strings -> not components.

You can:

```js
<Trans i18nKey="foo">Foo <b>Comp</b></Trans>
```

with:

`"foo": "Foo <1>Comp</1>",`

**Comment by jamuhl** [comment]
Means components can be naturally nested inside Trans.

**Comment by redcapital** [comment]
But what if component is a variable that you don't know ahead of time?

**Comment by jamuhl** [comment]
Than you will be out of luck until you do a PR enabling that...https://github.com/i18next/react-i18next/blob/master/src/Trans.js#L28

**Comment by redcapital** [comment]
OK, thank you
