### ISSUE TITLE
<I18n> rendering causes delay in componentDidMount

### ISSUE THREAD

**Issue by CWSites** [i18next/react-i18next#442]
I'm using a third party library which needs to be initialized in `componentDidMount`. My i18n configuration is set to `react: {wait: true}` which is causing a brief delay in the component actually rendering and `componentDidMount` isn't actually finished.

Is that accurate or am I doing something wrong? Currently my workaround is to set a timeout on initializing my third party library.

**Comment by jamuhl** [comment]
Rather easy. `Dashboard` does mount and renders the render prop `I18n` which itself will not render the `div` with ref as you set wait. So it didMount - just did not yet render the render prop.

Use a hoc in this situation or change to:

```
js
import React, { Component } from 'react';
import { I18n } from 'react-i18next';
import EasyPieChart from 'easy-pie-chart';

class Chart extends Component {
    constructor(props) {
        super(props);
        this.easyPie = React.createRef();
    }

    componentDidMount() {
        // the following returns null if I don't wrap it in a timeout
        new EasyPieChart(this.easyPie.current);
    }

    render() {
        const { t } = this.props; 
        return <div ref={this.easyPie}>...</div>;
    }
}

class Dashboard extends Component {
    render() {
        return (
            <I18n>
                {(t) => (
                    <Chart t={t}>
                )}
            </I18n>
        );
    }
}
```

**Comment by CWSites** [comment]
Thanks @jamuhl
