### ISSUE TITLE
Correct way to use Trans component and how to pass variables; incomplete docs

### ISSUE THREAD

**Issue by vladeck** [i18next/react-i18next#443]
i18next **11.3.2**
react-i18next **7.6.1**

By reading the docs, it is unclear to me (from the simple example with no context located at https://react.i18next.com/components/trans-component; the linked source has nothing to do with the provided code snippet - where does **Arthur** value comes from?) as to how to pass variable values when using `Trans` component. For example:

`Foo.tsx` (snippet for clarity):
```tsx
<Trans i18nKey="objects.errors.unknownType.content">
    Object with ID <strong>{this.props.objectId}</strong> is of unknown type.
    Go back to <a
        href="/objects"
        onClick={this.handleNavigationHrefClick}
    >
        Objects
    </a> route.
</Trans>
```

`en.json` (snippet for clarity):

```json
"objects": {
    "errors": {
        "unknownType": {
            "title": "Unknown Object Type",
            "content": "Object with ID <1>{{id}}</1> is of unkown type. Go back to <3>Objects</3> route."
        }
    }
}
```

I get:

`react-i18next: the passed in value is invalid - seems you passed in a variable like {number} - please pass in variables for interpolation as full objects like {{number}}. __ACTUAL_VALUE_HERE__`

I also tried (by guessing) `tOptions={{id: this.props.objectId}}` with no luck.

What is the correct way to use `Trans` component and pass variable values to it?

**Comment by vladeck** [comment]
Got it working. I'll leave working code here (so you can compare), for future references:

`Foo.tsx` (snippet for clarity):
```tsx
const id = this.props.objectId;

<Trans i18nKey="objects.errors.unknownType.content">
    Object with ID <strong>{{id}}</strong> is of unknown type.
    Go back to <a
        href="/objects"
        onClick={this.handleNavigationHrefClick}
    >
        Objects
    </a> route.
</Trans>
```

`en.json` (snippet for clarity):
```json
"objects": {
    "errors": {
        "unknownType": {
            "title": "Unknown Object Type",
            "content": "Object with ID <1><0>{{id}}</0></1> is of unknown type. Go back to <3>Objects</3> route."
        }
    }
}
```

**Comment by jamuhl** [comment]
You were to fast - not even had time to read the full issue ;)

**Comment by vladeck** [comment]
Sorry for spamming, but I spent several hours trying to figure out this problem. And then, just as I posted the question, I had a **A-HA** moment :)

**Comment by jamuhl** [comment]
Will try to add some more complete sample to the docs - guess that would help for future users running in same issue

**Comment by ayoung** [comment]
I'm still getting this. What was that A-HA moment? This is what I have in tsx

```html
<Trans i18nKey="ThereAreXUsers" count={numberOfUsers}>
   There are available {numberOfUsers} users to login with
</Trans>
```

and in my translations

```ts
{
  ThereAreXUsers:
    'There are <1><0>{{numberOfUsers}}</0></1> user available to login with',
  ThereAreXUsers_plural:
    'There are <1><0>{{numberOfUsers}}</0></1> users available to login with'
}
```

**Comment by AStaege** [comment]
what do you need "count" for, if you just use "numberOfUsers" instead ;)

so you just use
`<Trans i18nKey="ThereAreXUsers" count={numberOfUsers}>
   There are available {{count}} users to login with
</Trans>`

i know a little late, but for all (noobs like me) to understand: this `{{count}}` in double curly braces is nothing more than an js object (inner curly braces) written as a property shorthand, therefore would not be wrong to be written as `{count: count}`.

so it would be possible to write `.. {{count: numberOfUsers}} ..` or just `{{numberOfUsers}}` as then the "numberOfUsers" key will appear in the translation. (careful: i guess the concrete usage of the "count" attrib initializes the "_plural" translation string generation)

makes it pretty easy to use the return val of a function:
`<Trans i18nKey="ThereAreXUsers">
   There are available {{count: getNumberOfUsers()}} users to login with
</Trans>`

**Comment by jamuhl** [comment]
@AStaege the count prop is used to find the plural form for that translation

count=1: `There is available {{count: getNumberOfUsers()}} user to login with`
count=5: `There are available {{count: getNumberOfUsers()}} users to login with`

see the JSON: https://react.i18next.com/components/trans-component#sample

**Comment by AStaege** [comment]
sorry, was mentally still in that missing key generating process, just to understand the replacing tag mechanism. But yes, for production systems, that's pretty much it :)

**Comment by dagan-arbox** [comment]
I dont understand something.
the key is the translation, why I need to rewrite him on any component, it's a massive overkill for large applications

**Comment by jamuhl** [comment]
@dagan-arbox  not at all understand what you're talking about

**Comment by geraman21** [comment]
Maybe someone can clarify this for me:
So we write value for <Trans> component only to get the right indexes of the HTML tags used inside of it ? The actual text can be whatever but with correct html tags?

**Comment by jamuhl** [comment]
@geraman21 Sorry but I don't understand your question at all...can you make a sample?

**Comment by geraman21** [comment]
`                        <Trans i18nKey="example">
                            0 <strong>2</strong> 3 <strong>5</strong> 6
                        </Trans>

"example": "Konfigurieren Sie die Schnittstellen zum <1>Google Tag Manager</1> und <5>GoogleAnalytics</5> für Retargeting.",
`

In the example above I just used numbers to follow the indexation (although it didnt go as I expected), and then wrote the translation using the correct indexed for tags.
So this still doesnt work because I am messing up the indexation for the second strong tag, I probably understood it wrong.

**Comment by jamuhl** [comment]
Yes, content can be what you like...but if you use the correct content you can use save missing (and there is no need to guess anymore)...or just set debug: true (not yet having the key in your translations and you will see correct translation value (indexes) in the developer console. 

All with examples here: https://react.i18next.com/latest/trans-component#how-to-get-the-correct-translation-string

If you're guessing you do not understand react children, just check the above link

**Comment by geraman21** [comment]
@jamuhl but then doesn't it feel like I am just writing redundant text there ? My i18nKey already points at a translation string and I don't see the reason for rewriting the English version of it. 
This point can be maybe added to the Documentation, I am sure many people will find it helpfull.

**Comment by dagan-arbox** [comment]
> @dagan-arbox not at all understand what you're talking about

if I have 
```
<Trans i18nKey="ThereAreXUsers" count={numberOfUsers}>
   There are available {numberOfUsers} users to login with
</Trans>
```
'There are <1><0>{{numberOfUsers}}</0></1> user available to login with', - in trans

meaning I have to rewrite every translation if I need something strong or <> inside

now all I have to do is t('key',{})
is there a way to keep using t('key',{}) when I need bold text aswell?

**Comment by jamuhl** [comment]
@dagan-arbox this is react not html...try to understand the difference of adding HTML to a document and rendering a react element (one is a string the other is a render function)...apple and banana:

HTML: `<strong>BOLD</strong>` <- a string
JSX: `<strong>BOLD</strong>` <- not a string 


@geraman21 depends on your setup...looks like you work harder than you need by writing first translations and add them later into your code ---> we do the opposite...just write code and let i18next create the translation files...

If you like that to be mentioned in the documentation - open for a PR there.

**Comment by geraman21** [comment]
@jamuhl Our app waswirtten without translation in mind on German, so since we already have German translation, I create the json file with German version, and then populate the code with the keys. Could you suggest a more efficient way of doing it ?

**Comment by jamuhl** [comment]
https://www.youtube.com/watch?v=9NOzJhgmyQE that's what we do (nowadays with locize...in past with our own server having save missing)
