### ISSUE TITLE
Trans component documentation - add a few full samples

### ISSUE THREAD

**Issue by jamuhl** [i18next/react-i18next#444]
https://github.com/i18next/react-i18next/issues/443#issuecomment-392769327

**Comment by arkross** [comment]
Personally, I was confused on how do the "index tag" (e.g. `<0>`, `<1>`) corresponds to which part of the Trans component's children. So I made a [note](https://github.com/arkross/arkross.github.io/wiki/Using-react-i18next-Trans-Component) specifically about this. Here are some examples I made by experimenting:

Assuming we ignore the `title` attribute in `<strong>` tag and the value of `count`, we focus only on the content of the `<strong>` tag.

### Example 1: Single children, multiple properties in a node

```html
<Trans i18nKey='userMessagesUnread' count={count}>
    <Hello <strong title={t('nameTitle')}>{{name: 'Jan', title='Mr.'}}</strong>, you have {{count}} unread message. <Link to="/msgs">Go to messages</Link>.
</Trans>
```

```javascript
"userMessagesUnread": "Hello <1><0>{{title}} {{name}}</0></1>, you have <3>{{count}}</3> unread message. <5>Go to message</5>."
```

### Example 2: Multiple children in a node

```html
<Trans i18nKey='userMessagesUnread' count={count}>
    Hello <strong title={t('nameTitle')}>{{name: 'Jan'}}{{title: 'Mr.'}}</strong>, you have {{count}} unread message. <Link to="/msgs">Go to messages</Link>.
</Trans>
```

```javascript
"userMessagesUnread": "Hello <1><1>{{title}}</1> <0>{{name}}</0></1>, you have <3>{{count}}</3> unread message. <5>Go to message</5>."
```

### Example 3: No unusable text nodes

```html
<Trans i18nKey='userMessagesUnread' count={count}>
    <strong title={t('nameTitle')}>{{name='Jan', title: 'Mr.'}}</strong>{{count}}<Link to="/msgs">third node</Link>
</Trans>
```

```javascript
"userMessagesUnread": "Hello <0><0>{{title}} {{name}}</0></0>, you have <1>{{count}}</1> unread message. <2>Go to message</2>."
```

All examples will render the same output

```html
Hello <strong title='Jan'>Mr. Jan</strong>, you have 1 unread message. <Link to="/msgs">Go to messages</Link>
```

---

Feel free to audit if there's any mistake.

**Comment by jamuhl** [comment]
@arkross really awesome...would you mind me copy https://github.com/arkross/arkross.github.io/wiki/Using-react-i18next-Trans-Component and adding it to https://react.i18next.com ?!? Will also add a reference to your original content...

**Comment by jamuhl** [comment]
Those are used if using ICU -> also the ICU macro converts the inner content to append values and components props: https://react.i18next.com/misc/using-with-icu-format#using-the-trans-component
