### ISSUE TITLE
react-i18next with redux setup

### ISSUE THREAD

**Issue by LekovicMilos** [i18next/react-i18next#445]
Hi guys. Sorry if this is a bit straightforward question, but can you guide me how to set up react-i18next with redux?

My i18n.js file is:

`import i18next from 'i18next';
import Backend from 'i18next-xhr-backend';
import LanguageDetector from 'i18next-browser-languagedetector';
import { reactI18nextModule, translate as translator } from 'react-i18next';
import { flatten, StringUtil } from './modules/core/util';
import * as R from 'ramda';
// //Put into config
const featureKeysUrl = '/dev/feature-keys.json';
const dictionaryUrl = '/dev/feature-keys-{{ns}}.json';
const lng = 'en';
let loadedDictionaries = [];

i18next
	.use(Backend)
	.use(LanguageDetector)
	.use(reactI18nextModule)
	.init({
		fallbackLng: 'en',

		// have a common namespace used around the full app
		ns: ['translations', 'prevodi'],
		defaultNS: 'translations',
		lng: 'en',
		debug: true,

		interpolation: {
			escapeValue: false, // not needed for react!!
		},

		react: {
			wait: true,
		},
		// resources: {
		// 	'Hello World!': 'Siema Świecie!',
		// 	'Translate me!': 'Przetłumacz mnie',
		// 	'One plus one equals ${ 1 + 1 }': 'Jeden plus jeden jest równe ${ 1 + 1 }',
		// 	'key_0': 'elementów',
		// 	'key_1': 'element',
		// 	'key_2': 'elementy',
		// 	'key_5': 'elementów',
		// 	'key_21': 'elementy'
		// }
		resources: {
			en: {translation: require('./translations/en.po')}
		},
		// loadPath: '/locales/{{lng}}/{{ns}}.json',
	}, (err, t) => {
		loadDictionary();
	});

export function loadDictionary(ns) {
	const namespace = !ns ? 'translation' : ns;
	const url = !ns ? featureKeysUrl : R.pipe(
		StringUtil.replaceAll('{{ns}}', namespace),
		StringUtil.replaceAll('{{lng}}', lng)
	)(dictionaryUrl);

	if (loadedDictionaries.indexOf(namespace) === -1) {
		fetch(url)
			.then(res => res.json())
			.then(data => {
				i18next.addResourceBundle(lng, namespace, flatten(data), true, true);
				loadedDictionaries = [
					...loadedDictionaries,
					ns || namespace
				];
			})
			.catch(err => console.log(err));
	}
}

export const translate = (context) => translator()(context);

export default i18next;`

In app.js file I have:
`import { translate } from './i18n';`
and
```export default R.pipe(
  connect(
    mapStateToProps,
    mapDispatchToProps
  ),
  localizedRouter,
  translate
)(App);```

In the child component I have 

`import { translate, Trans } from 'react-i18next';`

in render I have

`const { r, t } = this.props;

<h1>{t('welcome')}</h1>`

and then 

```
export default R.pipe(
  localizedRouter,
  translate
)(HeaderComponent);
```

I get an error TypeError: t is not a function. What did I set wrongly? How do I set it?

**Comment by jamuhl** [comment]
translate is a function returning a component...

```
export default R.pipe(
localizedRouter,
translate(/* namespace(s) ,optional options /*)
)(HeaderComponent);
```

**Comment by jamuhl** [comment]
could this be closed?

**Comment by LekovicMilos** [comment]
Yes, thanks
