### ISSUE TITLE
get warning with translate function when using the new method getDerivedStateFromProps of react

### ISSUE THREAD

**Issue by slim-hmidi** [i18next/react-i18next#448]
I upgraded the version of react from `v16.2.0` to `16.4.0` and I'm trying to change the life cylce `componentWillReceiveProps` by the new method `getDerivedStateFromProps`, I got some warning with the function `translate` used in some components:
```
Warning: Translate(TextAreaName): Did not properly initialize state during construction. Expected state to be an object, but it was undefined. warning.js:33
	printWarning warning.js:33
	warning warning.js:57
	constructClassInstance react-dom.development.js:11342
	updateClassComponent react-dom.development.js:13036
	beginWork react-dom.development.js:13715
	performUnitOfWork react-dom.development.js:15741
	workLoop react-dom.development.js:15780
	renderRoot react-dom.development.js:15820
	performWorkOnRoot react-dom.development.js:16437
	performWork react-dom.development.js:16358
	performSyncWork react-dom.development.js:16330
	requestWork react-dom.development.js:16230
	scheduleWork$1 react-dom.development.js:16096
	scheduleRootUpdate react-dom.development.js:16663
	updateContainerAtExpirationTime react-dom.development.js:16690
	updateContainer react-dom.development.js:16717
	ReactRoot.prototype.render react-dom.development.js:17000
	legacyRenderSubtreeIntoContainer/< react-dom.development.js:17140
	unbatchedUpdates react-dom.development.js:16557
	legacyRenderSubtreeIntoContainer react-dom.development.js:17136
	render react-dom.development.js:17195
	<anonymous> index.jsx:69:4
	setSuccess keycloak.js:780
	Keycloak/kc.init/< keycloak.js:116
	setSuccess keycloak.js:780
	authSuccess keycloak.js:575
	processCallback/req.onreadystatechange keycloak.js:549
```
**react-i18next:** v7.3.6
**react:** v16.4.0
**react-dom:** v16.4.0
When I comment the `translate` function the warning disappears.

**Comment by jamuhl** [comment]
What version of react-i18next did you use?

**Comment by slim-hmidi** [comment]
@jamuhl sorry I didn't mentioned it in the issue, I'm using `react-i18next v7.3.6`

**Comment by jamuhl** [comment]
https://github.com/i18next/react-i18next/blob/master/CHANGELOG.md#760

i guess you will need to upgrade react-i18next to >7.6.x

**Comment by slim-hmidi** [comment]
I upgrade it to version  `7.7.0` and still getting the same warning.

**Comment by jamuhl** [comment]
just tried with the example: https://github.com/i18next/react-i18next/blob/master/example/react_withHOC/src/App.js

(after updating all dependencies)

```js
class App extends Component {
  constructor(props) {
    super(props);
    this.state = {};
  }
  
  static getDerivedStateFromProps(props, state) {
    return { foo: 'bar' };
  }
```

i do not get an error / warning...could you provide a sample to reproduce.

**Comment by jamuhl** [comment]
did you check if the react-i18next version was updated? package-lock.json, or yarnlock, npm cache,...

**Comment by slim-hmidi** [comment]
@jamuhl I tried the example that you have already sent to me [example](https://codesandbox.io/s/x2omvqyzq) and I got the warning.

**Comment by slim-hmidi** [comment]
@jamuhl I will send you a version of my app containing this warning.

**Comment by jamuhl** [comment]
any update on this one?

**Comment by JukoPowel** [comment]
I suggest to reopen this issue.
Comment which may help to fix it:
https://github.com/facebook/react/issues/12981#issuecomment-395615021
