### ISSUE TITLE
undefined Error when string has no closing tag

### ISSUE THREAD

**Issue by dguillamot** [i18next/react-i18next#451]
An error is thrown from Trans.js line 78 (react-i18next.js line 1064) when the inputted string is just a single opening XML element. 

Our string was 'This is a test string'.. However, translators accidentally surrounded this with angle brackets.  making the string `<This is a test string>`.

The result was a crash in Trans.js at line 78 in renderNodes(). 'Cannot read property 'content' of undefined' at this line:
const interpolated = i18n.services.interpolator.interpolate(node.children[0].content, child, i18n.language);

So, if the inputted string does not have a valid closing xml tag (in our case the entire string was one single opening xml tag), node.children[0] is, naturally, undefined as there are no children to that node. 

Should Trans.js check for null node.children here, or higher up in the pipeline?

**Comment by jamuhl** [comment]
would you mind providing a PR or at least a failing testcase for this?

**Comment by dguillamot** [comment]
@jamuhl Yes, if I have time on the weekend I will take a crack at it.

**Comment by jamuhl** [comment]
i guess the error is caused here: https://github.com/i18next/react-i18next/blob/master/src/Trans.js#L56

evtl. doing a try catch around the parse and log an error on catch + fallback to unparsed value might be sufficient fix...

**Comment by isaachinman** [comment]
@jamuhl Is this fixed, or would you like a PR for it?

**Comment by jamuhl** [comment]
not yet fixed...was to low on my personal prio list...feel free to create a PR so this gets finally closed.

**Comment by isaachinman** [comment]
@dguillamot It's been several months since your offer, do you want to contribute to this library, or shall we take it from here?

**Comment by jamuhl** [comment]
looks like this got solved by other changes already - at least that code part was removed (changed heavily) and newly added tests do not show any issue for those invalid html tags from translations.
