### ISSUE TITLE
Improvement suggestions for optimization 

### ISSUE THREAD

**Issue by ido1wald** [i18next/react-i18next#454]
in Trans component or create another component that can be a wrapper for Trans Component.
use React.PureComponent instead of React.Component
Why? example bellow

class myRefreshComponent extends React.Component{
constructor(props){
 super(props);
 this.state.data = "";
}
 componentWillMount(){
  setTimeout(()=>{this.setState({data: "mynewData"}, 2000); // this will re-render our component after 2 ms 
}
 render(){
 return <div>
            <div> <Trans>My data is</Trans>
             {this.state.data} 
          </div>
  }
}

notice that Trans translation function will be called **twice**! 
Once when the component finish it's first render,
and second after the component changed his state in "componentwillmount" callback.

Conclusion:
To improve the performance of your app. 
in places where you just want to add static text (not dynamic!)
add a wrapper to Trans, use PureComponent such as
class PureT extends React.PureComponent{
  render(){
    return <Trans>{this.props.trans}</Trans>
  }
}

**Comment by jamuhl** [comment]
Why not just leave that in userland...or you might provide a PR adding https://github.com/i18next/react-i18next/blob/master/src/translate.js#L34 to Trans component?

**Comment by jamuhl** [comment]
if i remember right that was added some time after having moved to support render props beside the hoc
