### ISSUE TITLE
"Object doesn't support property or method 'apply' " for IE9

### ISSUE THREAD

**Issue by trungvuNeji** [i18next/react-i18next#455]
I build a React site with react-i18next, and it works flawlessly in all other browsers/ platform, except for IE9. At first I got the error "Set/Map is undefined", but it quickly went away after I included some polyfills. However, now I'm stuck with the above error message: "Object doesn't support property or method 'apply' ". I tried to include as many other polyfills as I could find as well, but none of them made it work.

The error pointed to the line in my i18n file where I call 

`
i18n.use(LanguageDetector).init({...})
`

Do you know a work around for this? Sorry if this question got asked before. I tried to read up on these posted issues and I know you don't want/like to support IE, but we have some traffic coming to our site using IE9. Hope that it won't bother you too much.

Thanks for a wonderful package.

**Comment by jamuhl** [comment]
Problem is IE9 is out of what i can support (as i got no windows machine it's hard to debug - even having access to it - IE9 is a pain to debug ;))

From a quick search i saw it seems to be most time related to console.log statements which we use https://github.com/i18next/i18next/blob/master/src/logger.js#L18 too

But not sure - just try to set debug: false on init eventual the problem goes away not calling console.log?!?

**Comment by trungvuNeji** [comment]
You must be kidding!! I spent days scratching my head over that and just by simply set debug: false like you suggested, the problem is now gone, and the whole page is there. I feel like a complete noob now. Thanks so much Jan!!!

**Comment by jamuhl** [comment]
No...don't worry...sometimes it's easier having some distance from the problem.

To solve this for production (not having a call to console.error) i would recommend to pass in a own logger plugin for IE9 -> just doing noop calls. https://www.i18next.com/misc/creating-own-plugins#logger

Just throw that in like any other plugin: -> `i18next.use(noopLogger);`
