### ISSUE TITLE
Using react-i18next with backend using xhr

### ISSUE THREAD

**Issue by imprashast** [i18next/react-i18next#457]
Tried to search a lot about this but there are no examples.

What I am trying to do is to use i18next with xhr to load translations files directly in browser. This is how it looks in the debug logs on console:
<img width="563" alt="screen shot 2018-06-21 at 14 40 33" src="https://user-images.githubusercontent.com/21952706/41719802-6b382a8a-7561-11e8-8492-6507e4521393.png">

My i18n.js looks like this:

```
import i18next from 'i18next';
import XHR from 'i18next-xhr-backend';

i18next.use(XHR).init({
    interpolation: {
        // React already does escaping
        escapeValue: false,
    },
    lng: 'no' || 'en',
    fallbackLng: 'no',
    debug: true,
    react: {
        wait: true,
    },
    backend: {
        loadPath: '/assets/locales/{{lng}}.json',
    },
});

export default i18next;

```

Any help would be much appreciated

**Comment by jamuhl** [comment]
And what is not working? Your console output even shows it loaded content. `::backendConnector: loaded ...` stuff.

There is a full sample here: https://github.com/i18next/react-i18next/blob/master/example/react_withHOC/src/i18n.js

**Comment by imprashast** [comment]
If you look at line 3 of the log:
```
i18next::translator: missingKey undefined translation welcome.label welcome.label
```

So basically everything is loading fine but the translation isn't happening. Not sure whats wrong

**Comment by jamuhl** [comment]
point is line 3 should be after 4 ;)

there must be somewhere a call to `i18n.t` that is done before init...as undefined there also shows there is not yet a language set

**Comment by imprashast** [comment]
This is my component:

```
<I18nextProvider i18n={i18n}>
<main role="main">
 <div >{i18n.t('welcome.label')}</div>
</main>
</I18nextProvider>

```

**Comment by jamuhl** [comment]
You either need to use the 

translate HOC https://react.i18next.com/components/translate-hoc

or

the render prop https://react.i18next.com/components/i18n-render-prop

to assert translations were loaded (what the react: { wait: true } option is for)

**Comment by imprashast** [comment]
Okay I'll try them now 👍

**Comment by jamuhl** [comment]
as a sample: https://github.com/i18next/react-i18next/blob/master/example/react_withHOC/src/App.js#L33

**Comment by imprashast** [comment]
Works fine now. Cool Thanks 😃
