### ISSUE TITLE
Trans doesn't update when language is loaded

### ISSUE THREAD

**Issue by peteruithoven** [i18next/react-i18next#458]
It looks like the <Trans> component doesn't update itself when a language is loaded. 
We switched from using the I18n with render prop to using Trans components and we noticed that, unless the component is re-rendered because of a unrelated state change, the translations aren't updated. 

It doesn't seem to matter whether we set the `react.wait` option. 

It looks like the components are updating when the components in which we use Trans is nesting in the translate HOC component. 

Looking through the [code of the Trans component](https://github.com/i18next/react-i18next/blob/master/src/Trans.js) there doesn't seem to be a "listener" / "subscription" for language updates.

Shouldn't the Trans component update itself in response to these changes? Otherwise I think a note should be added to the documentation.

Demo:
https://codesandbox.io/s/1r60pvqr8q

**Comment by jamuhl** [comment]
No. The `I18n` render prop or `translate HOC` are the one triggering rerenders and wait functionality. The Trans component is just an additional component enabling translation of react components - string / component combinations - not more.

**Comment by peteruithoven** [comment]
Alright, thanks for the quick reply. This is mostly to keep the Trans component simple? 

I think this should be documented. Now it's not clear that when using `Trans` and the `react.wait` config, you also need the `I18n` render prop or `translate` HOC.

It's probably also out of the scope of functionality of the I18nextProvider to trigger a re-render?

**Comment by jamuhl** [comment]
the provider is only out there to put the i18n instance into context so it can be used by hoc, render prop (optional as you can set that via the reactI18nextModule like: https://github.com/i18next/react-i18next/blob/master/example/react_withHOC/src/i18n.js#L9

but still useful if using multiple different i18n instances in an app.

**Comment by jamuhl** [comment]
It's rather easy:

I18nextProvider -> is a Provider
translate -> is a HOC
I18n -> is a render prop (special type of component)
Trans, Interpolate -> are components

So its Provider -> HOC -> Trans

**Comment by jamuhl** [comment]
But agree...the documentation could need some more love.

**Comment by peteruithoven** [comment]
Thanks for the clarifications. 

I think you could further clarify it by saying that:
- `translate` and `I18N` are smart / connected / container components 
- `Trans` and `Interpolate` are dumb components

See: https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0

**Comment by jamuhl** [comment]
Hope that helps in future: https://react.i18next.com/components/overview
