### ISSUE TITLE
Strategy for picking up translation files/namespaces based on discriminator

### ISSUE THREAD

**Issue by cristian-eriomenco** [i18next/react-i18next#459]
Suppose we have a multitenant app:

`{tenant1}.domain.com` - supports en, de
`{tenant2}.domain.com` - supports en, it

What would be the correct way of structuring the json/translation files?

1.  Using multiple i18n.js files:
`localization/tenant1.i18n.js`
`localization/tenant2.i18n.js`

2. Using namespaces 
Drawbacks:
- Cluttered because of language being a top level discriminator and it might not be supported by some tenants.
- File becomes too big and unnecessary translations will be loaded for all tenants.
- Some HoC needed for injecting the correct namespace when using `translate("namespace")(Component)` or when invoking `t("key.to.prop")`

```
i18n
.use(Backend)
.use(LanguageDetector)
.use(reactI18nextModule)
.init({
    fallbackLng: "en",
    ns: ["tenant1"],
    defaultNS: "tenant1",
    debug: true,
    resources: {
        en: {
            tenant1: {
                "portal": {
                    "title" : "Portal Page",
                }
            },
            tenant2: {
                "portal": {
                    "title" : "Portal - Page",
                }
            },
        },
        de: {
            tenant1: {
               "portal": {
                    "title" : "Portalseite",
                }
            }
        },
        it: {
            tenant2: {
               "portal": {
                    "title" : "Pagina del Portale",
                }
            }
        },
    },
});
```
Are there any other options?

**Comment by jamuhl** [comment]
i would solve it using custom languages. i18next already does key resolving like `de-DE` -> `de` -> `en` (going from regional local to language to fallback).

So i would add `en`, `de`, `it` as invariant languages for both of them.

The tenants themself could add languages like: `en-US-x-tenant1` (-x- stands for custom language variants).

The only thing you would have to do is wrapping the language detector with a custom logic appending `-x-tenant1` based on the domain found.

**Comment by cristian-eriomenco** [comment]
@jamuhl I have had a look at the language detectors implementation. So correct me if i'm wrong, you're suggesting to implement a custom language detector somewhat like that:
```
const multitenantLanguageDetector = {
    name: "multitenantLanguageDetector",
    lookup(options) {
      // options -> are passed in options
        return "en-US-tenant1";
    },
    cacheUserLanguage(lng, options) {
      // options -> are passed in options
      // lng -> current language, will be called after init and on changeLanguage
      // store it
    }
};
```
But then i'd need to create implementations of these, one per each kind of supported persistence mechanism  like these : `['querystring', 'cookie', 'localStorage', 'navigator', 'htmlTag', 'path', 'subdomain']` am i right? :(

**Comment by jamuhl** [comment]
like i said wrap the browserLanguageDetector in a full detector plugin not just create a lookup:

```js
{
  type: 'languageDetector',
  init: function(services, detectorOptions, i18nextOptions) {
    // create and init the regular browserLanguageDetector
  },
  detect: function() { 
    // call detect from regular browserLanguageDetector and append your suffix
  },
  cacheUserLanguage: function(lng) {
    // call cache on regular
  }
}
```

https://www.i18next.com/misc/creating-own-plugins#languagedetector

**Comment by cristian-eriomenco** [comment]
@jamuhl I have tried to implement it by wrapping the browserLanguage detector but it was failing on some utils. After all i thought that it would make more sense to just resolve the correct json translations using a `Backend` like this:

```
function getDefaults() {
    return {
        loadPath: "./translations/{{subdomain}}/{{lng}}.json",
        allowMultiLoading: false,
        reloadInterval: false
    };
}

class StaticJsonBackend {
    constructor(services, options = {}) {
        this.init(services, options);
        this.type = "backend";
    }

    init(services, options = {}) {
        this.services = services;
        this.options = { ...getDefaults(),
            ...this.options,
            ...options
        };
    }

    read(language, namespace, callback) {
        const subdomain = window.AppGlobals.brand.subdomain;

        let path = this.services.interpolator.interpolate(this.options.loadPath, {
            lng: language,
            subdomain: subdomain
        });

        import(`${path}`).then(data => {
            callback(null, data)
        }).catch(err => {
            callback(err, false);
        });
    }
}

StaticJsonBackend.type = "backend";

export default StaticJsonBackend;
```

**Comment by jamuhl** [comment]
that will also work...;)
