### ISSUE TITLE
I18next with a help of new react context

### ISSUE THREAD

**Issue by dmtrKovalenko** [i18next/react-i18next#460]
Hello there! 
I have created an alternative way to use i18next in react with a help of context. Here is my lib - https://github.com/dmtrKovalenko/ns-react-18next.

Maybe you will post the link for it from the docs, or it can be merged to `react-i18next` if its convenient. Thank you)

**Comment by jamuhl** [comment]
Will add it to the i18next docs asap.

There is a plan to update this module to the new context API. Currently i'm still waiting for preact to catch up with this - so we can do a new BREAKING version that works for latest react / preact - without having to shim the context API (all pre react v16 would have to use the old major release).

**Comment by jamuhl** [comment]
added: https://www.i18next.com/overview/supported-frameworks
