### ISSUE TITLE
Next.js: Replace lng=en to /en/

### ISSUE THREAD

**Issue by markolofsen** [i18next/react-i18next#463]
**Next.js**
Example source: [https://github.com/zeit/next.js/tree/canary/examples/with-react-i18next](https://github.com/zeit/next.js/tree/canary/examples/with-react-i18next)
What's best way for replacing lang-param in url from `?lng=en` to `/en/`
Necessary for ssr till load the page
**Default:** http://localhost:3000/catalog?lng=en
**Need:** http://localhost:3000/en/catalog

**Comment by jamuhl** [comment]
set up the route in express - the used https://github.com/i18next/i18next-browser-languageDetector can already detect lng from route path: 

use lookup `path` and set `lookupFromPathIndex` as needed

**Comment by markolofsen** [comment]
Cool!
