### ISSUE TITLE
Trans requires objects as children but this is not valid in React

### ISSUE THREAD

**Issue by jake-nz** [i18next/react-i18next#465]
I've always been uneasy about `Trans` having objects as children like `{{ name }}` because it's non-standard. In fact React will normally throw an error rendering them "Objects are not valid as a React child..."

Today this caused me problems when testing with enzyme.

``` js
import { shallow } from 'enzyme'
const name = "Mock Thing"
const type = "square"
shallow(<Trans i18nKey="test">
  Sorry, you cannot delete the {{ type }} <b>"{{ name }}"</b>
</Trans>)
```

This results in an error "TypeError: Cannot read property 'children' of undefined" becasue enzyme sees an object with a key 'type' and expects it to also have children [(code)](https://github.com/airbnb/enzyme/blob/6cd6fa248b3c76fb039f2b7bd0046be337043200/packages/enzyme-adapter-utils/src/Utils.js#L161)

I'm not sure why enzyme does this and perhaps it's something they should fix, but I'd like to suggest here that `Trans` adopt a React standard aproach to avoid issues. Perhaps this:
```
<Trans i18nKey="test" type={type} name={{ name , format }}>
  Sorry, you cannot delete the type <b>"name"</b>
</Trans>
```

**Comment by jamuhl** [comment]
That way we can't detect were to interpolate.

Still you can:

```js
<Trans
  defaults="hello <0>{{what}}</0>"
  values={{ what: 'world'}}
  components={[<strong>dummyChildren</strong>]}
/>
```

**Comment by jamuhl** [comment]
Personally i would prefer having a babel macro converting 

```js
<Trans i18nKey="test">
  Sorry, you cannot delete the {type} <b>"{name}"</b>
</Trans>
```

to

```js
<Trans
  defaults="Sorry, you cannot delete the {{type}} <0>{{name, format}}</0>"
  values={{ type, name }}
  components={[<b>dummyChildren</b>]}
/>
```

**Comment by jamuhl** [comment]
Why not doing a string replace in `Sorry, you cannot delete the type <b>"name"</b>`?

Translators would translate that eg to: `Entschuldigen Sie, Sie können den Typ mit <b>"Namen"</b> nicht löschen` -> no replacement possible

**Comment by jamuhl** [comment]
But any suggestion that would would improve this would help.

**Comment by jamuhl** [comment]
overall why enzyme does not work? it does here: https://github.com/i18next/react-i18next/blob/master/test/trans.render.spec.js#L131

did you mock the Trans component?

Beside...no i guess changing the interpolation prefix/suffix is not the best option. In the end JSX is no valid javascript anyway -> just gets transpiled to it ;)

If needed i would prefer an approach doing the same as we do for the ICU format usecase - ICU is always invalid as a node child -> https://react.i18next.com/misc/using-with-icu-format#using-babel-macros-trans-plural-select

**Comment by ioliver** [comment]
To avoid this issue, I ended up modifying Trans component mock function:

```javascript
const React = require('react');
const reactI18next = require('react-i18next');

const hasChildren = node =>
  node && (node.children || (node.props && node.props.children));

const getChildren = node =>
  (node && node.children ? node.children : node.props && node.props.children);

const renderNodes = (reactNodes) => {
  if (typeof reactNodes === 'string') {
    return reactNodes;
  }

  return Object.keys(reactNodes).map((key, i) => {
    const child = reactNodes[key];
    const isElement = React.isValidElement(child);

    if (typeof child === 'string') {
      return child;
    } else if (hasChildren(child)) {
      const inner = renderNodes(getChildren(child));
      return React.cloneElement(
        child,
        { ...child.props, key: i },
        inner,
      );
    } else if (typeof child === 'object' && !isElement) {
      return Object.keys(child).reduce((str, childKey) => `${str}${child[childKey]}`, '');
    }

    return child;
  });
};

module.exports = {
  // this mock makes sure any components using the translate HoC receive the t function as a prop
  translate: () => Component => props => <Component t={k => k} {...props} />,
  Trans: ({ children }) => renderNodes(children),
  I18n: ({ children }) => children(k => k, { i18n: {} }),

  // mock if needed
  Interpolate: reactI18next.Interpolate,
  I18nextProvider: reactI18next.I18nextProvider,
  loadNamespaces: reactI18next.loadNamespaces,
  reactI18nextModule: reactI18next.reactI18nextModule,
  setDefaults: reactI18next.setDefaults,
  getDefaults: reactI18next.getDefaults,
  setI18n: reactI18next.setI18n,
  getI18n: reactI18next.getI18n,
};
```

**Comment by jamuhl** [comment]
@ioliver cool...makes sense...i updated the sample using your code: https://github.com/i18next/react-i18next/blob/master/example/test-jest/__mocks__/react-i18next.js

**Comment by jamuhl** [comment]
@jake-nz ok that works too ;) -> just would not have created the right string for translations at start using the save missing feature. If it works for you - that's great.

**Comment by jamuhl** [comment]
closing this....if still an issue - feel free to reopen this one

**Comment by Jme797** [comment]
Was there ever a fix for this?

**Comment by jamuhl** [comment]
It's not like it does not work...it's just the lint rules of react. Like written above you can use the component like: https://react.i18next.com/latest/trans-component#alternative-usage-which-lists-the-components-v11.6.0 (No childs therefore no object in childs)
