### ISSUE TITLE
Documentation request: What's the advantage over standard i18next?

### ISSUE THREAD

**Issue by jeznag** [i18next/react-i18next#466]
Hi,
Naieve newbie here. I don't really get the use case of react-i18next. It adds 20kb to my bundle and apparently has performance issues (https://github.com/i18next/react-i18next/issues/456).

Is there any reason to use it if I only have simple translations and don't have any need to switch languages without a page load? Can I just get away with using i18next on its own?

As context, I have a completely separate URL for the Japanese version and thus have no need to switch languages client side.

I'd propose you add a section to the README/website spelling out the exact scenarios when react-i18next is useful and when it's overkill. Happy to submit a PR after receiving some guidance here :)

**Comment by jamuhl** [comment]
If your app is simple you can just use i18next (import it - init somewhere - and use i18next.t).

No need to trigger rerender on clientside language change.
No need for lazy loading namespaces.
No use case for the Trans component.

=> Use just i18next

**Comment by jamuhl** [comment]
And that performance issue is a single application that encounter thats -> so that could be something on that project side -> could not really reproduce a problem yet.

**Comment by jamuhl** [comment]
added here: https://react.i18next.com/
