### ISSUE TITLE
Object with keys in namespace

### ISSUE THREAD

**Issue by 0FilipK** [i18next/react-i18next#467]
Hello,

Is it possible to have an object in namespace? Something like this:

```
resources: {
    en: {
      translations: {
        footer: {
          'title': 'XXX',
          'header': 'YYY',
        },
      },
    },
}
```

and then use simply `{t('footer.title')}`? I'm using `translations` namespace by default and using "empty" HOC in my component `export default translate()(ComponentName)`.

**Comment by jamuhl** [comment]
did you try?

https://www.i18next.com/translation-function/essentials#accessing-keys

guess yes...just not have setting keySeparator: false on init

**Comment by 0FilipK** [comment]
I didn't see this before but it doesn't work. In config file I have:

`keySeparator: false, // we use content as keys` right after `ns` and `defaultNS`. The result of `{t('footer.title')}` is just printing the key `footer.title` not the value.

I also tried:
`{t('footer.title', {keySeparator: false})}`
and
`{t('footer.title', {keySeparator: true})}`

but there is no difference.

**Comment by jamuhl** [comment]
Having no keySeparator means you would have json:

```js
resources: {
    en: {
      translations: {
          'footer.title': 'XXX',
          'footer.header': 'YYY',
      },
    },
}
```

`{t('footer.title', {keySeparator: true})}` -> should be -> `{t('footer.title', {keySeparator: '.'})}`

**Comment by 0FilipK** [comment]
Ok, now I see.

For others with same problem:

 ```
resources: {
    en: {
      translations: {
        footer: {
          'title': 'XXX',
          'header': 'YYY',
        },
      },
    },
}
```

and in config:
`keySeparator: '.'`

Then u can use:
`{t('footer.title')}`
