### ISSUE TITLE
Is there a way to call the translate HOC only on the root Component

### ISSUE THREAD

**Issue by acmoune** [i18next/react-i18next#468]
I have something like this

```javascript
<I18nextProvider i18n={i18n}>
    <Provider store={store}>
      <BrowserRouter>

          <Route component={App} />

      </BrowserRouter>
    </Provider>
  </I18nextProvider>
```

and I export my App component with 

`export translate([...])(App)`

I can use `this.props.t()` in the App component, but not it its children.

Do I have to export all the children using the translate HOC ? or is there a way to get around this ?

**Comment by jamuhl** [comment]
translate adds `t` to the wrapped component as prop -> props are not automatically added to children....either you pass down `t` from parent to children or wrap children into additional translate (or I18n if prefer render props)

**Comment by jamuhl** [comment]
so best practice is to add translate to container components (page/view/data access) and pass it down from there via props (or for richer/larger components wrap again in hoc)

**Comment by acmoune** [comment]
Thanks @jamuhl . Just wanted to confirm.
