### ISSUE TITLE
Is it possible to make a complete component reload on languageChanged ?

### ISSUE THREAD

**Issue by acmoune** [i18next/react-i18next#469]
I know the config option **bindI18n** controls which event triggers a rerender.

I am setting the document title in `componentDidMount`, But when I` changeLanguage`, of course the title is not updated directly. I have to navigate somewhere else (unload the component), then navigate back (reload the component) to see the change.

Is it possible to force an unmount-remount on `languageChanged` instead of just rerendering ?

**Comment by acmoune** [comment]
I think for now I will just run` window.location.refresh()` after `changeLanguage().` But supporting it like **bindI18n** could be good.

**Comment by jamuhl** [comment]
you can check on `shouldComponentUpdate(nextProps, nextState)` if `nextProps.t !== this.props.t` if so set title like in didMount

**Comment by acmoune** [comment]
@jamuhl , yes I know. The title was just an example. I have more, like async fetch, on so many other components... but I don't want to create more **shouldComponentUpdate** or **componentReceivedProps** to check for languageChange. And for me it makes sense to reload to whole app on language change, it should not be a light event.

**Comment by jamuhl** [comment]
i see...
