### ISSUE TITLE
Error when nesting components without children using the defaults prop

### ISSUE THREAD

**Issue by beheh** [i18next/react-i18next#470]
We've been using the new `defaults` strategy from #439 and been really happy with it. Unfortunately we're seeing errors when nesting components.

The following `Trans` component:

```jsx
<Trans
  defaults="<0>hello <1></1> {{what}}</0>"
  values={{ what: 'world'}}
  components={[<span>placeholder</span>, <br>placeholder</br>]}
></Trans>
```
throws the following error

```
TypeError: Cannot read property 'content' of undefined
  at src/Trans.js:78:86
    at Array.reduce (<anonymous>)
  at mapAST (src/Trans.js:62:21)
  at src/Trans.js:70:23
    at Array.reduce (<anonymous>)
  at mapAST (src/Trans.js:62:21)
  at src/Trans.js:70:23
    at Array.reduce (<anonymous>)
  at mapAST (src/Trans.js:62:21)
  at renderNodes (src/Trans.js:93:16)
```

I'm aware that right now I always need to add children to childrenless nodes, and that's fine in the toplevel case without nesting. I would like to be able to nest them though.

**Comment by jamuhl** [comment]
not tested nesting but should be same as with having regular children - just the values get interpolated regular i18next way - so i guess it should be:

```js
<Trans
  defaults="<0>hello <1></1> {{what}}</0>"
  values={{ what: 'world'}}
  components={[<span>placeholder<br /></span> ]}
></Trans>
```

-> `br` must be nested in component at index 1

**Comment by beheh** [comment]
Hm, while this works, the following doesn't:

```jsx
<Trans
  defaults="<0>prefix</0> <1>hello <2></2> {{what}}</1>"
  values={{ what: 'world'}}
  components={[<span>placeholder</span>, <span>placeholder<br /></span> ]}
></Trans>
```

We encounter this patterns in a few places of our codebase where `<0>` is the heading and `<1>` is a continued subheading.

I'm at a bit at a loss with regards to how the indexing works, maybe another example will help me to understand this better.

**Comment by jamuhl** [comment]
<Trans
  defaults="<0>prefix</0> <1>hello <1></1> {{what}}</1>"
  values={{ what: 'world'}}
  components={[<span>placeholder</span>, <span>placeholder<br /></span> ]}
></Trans>

should work...think of it like <0>**<0>**prefix**</0>**</0> <1>**<0>**hello**</0>** <1></1><2>{{what}}</2></1>

**Comment by jamuhl** [comment]
https://react.i18next.com/misc/the-trans-component-explained might help

**Comment by beheh** [comment]
Alright, great! Thanks for the docs, I wasn't aware of those. I think then this is a non-issue then, as I see you've also added test case already.

**Comment by jamuhl** [comment]
If i got time i will write a converter page some day where you just can paste the content and get the correct transform - just currently got no time for this.

**Comment by beheh** [comment]
At least to me this was just non-intuitive in the manual mode. I was expecting tag `<X>` to correspond to index X in the `components` array, but the docs did clear that up now.

**Comment by jamuhl** [comment]
It's not very simple indeed...i know...just got no better solution for it yet.
