### ISSUE TITLE
How to prefix translation json files?

### ISSUE THREAD

**Issue by darde** [i18next/react-i18next#472]
Is there any way to prefix my translation json files? I need to do something like that:

**i18n/locales/en/common.json**

```
"en" {
  "editor": {
    "sidebar": {
      "header": {
        ...
      }
    }
  }
}
```
**i18n/locales/pt/common.json**
```
"pt-BR" {
  "editor": {
    "sidebar": {
      "header": {
        ...
      }
    }
  }
}
```

Without the prefixes `en` and `pt-BR` my project is working well. This is my index:

**i18n/index.js**

```
import i18n from 'i18next';
// import LanguageDetector from 'i18next-browser-languagedetector';
import pt from './locales/pt/common.json';
import en from './locales/en/common.json';

const options = {
  interpolation: { escapeValue: false },
  lng: 'en',

  resources: {
    pt: {
      common: pt,
    },
    en: {
      common: en,
    },
  },

  fallbackLng: 'pt',

  ns: ['common'],

  defaultNS: 'common',

  react: {
    wait: true,
  },
};

i18n.init(options);


export default i18n;
```
I also posted this question in [stackoverflow](https://stackoverflow.com/questions/51287339/how-to-load-prefixed-json-files-in-i18next).

**Comment by jamuhl** [comment]
why you need that prefix?

**Comment by jamuhl** [comment]
``` 
 resources: {
    pt: {
      common: pt[pt-BR],
    },
    en: {
      common: en.en,
    },
  },

```

**Comment by darde** [comment]
Because I'm using [https://crowdin.com/](https://crowdin.com/ ). This is a localization management platform and I'm only able to create prefixed json files.

**Comment by jamuhl** [comment]
use https://locize.com instead -> that's from us - so you support i18next directly.

Beside that just see the last comment:

 resources: {
    pt: {
      common: pt[pt-BR],
    },
    en: {
      common: en.en,
    },
  },

**Comment by darde** [comment]
Thank you very much man. Your solution works fine. Congrats for the awsome work!!!

**Comment by jamuhl** [comment]
Still using locize.com and supporting us would be more awesome ;)

**Comment by darde** [comment]
I'll suggest this for my team. Thanks!!!

**Comment by jamuhl** [comment]
https://www.youtube.com/watch?v=9NOzJhgmyQE might be helpful
