### ISSUE TITLE
Using i18next in enums (TypeScript)

### ISSUE THREAD

**Issue by 0FilipK** [i18next/react-i18next#479]
Hello, I'm using React with react-i18next plugin and I want to translate value of enums. Is it possible?

Code:
```
enum catSize {
    SMALL = 'Small',
    MEDIUM = 'Medium',
    LARGE = 'Large',
}
```

and I'd like to convert this to something like:

```
enum catSize {
    SMALL = t('sizes.small'),
    MEDIUM = t('sizes.medium'),
    LARGE = t('sizes.large'),
}
```

but obviously it won't work because we don't have access to `t` function which is provided by HOC. Is there any trick to achive translations outside render function and use it in my case?

**Comment by jamuhl** [comment]
you can directly access `t` on your i18n instance: https://www.i18next.com/overview/api#t

just make sure you have the needed namespace loaded -> fill enum in/after init callback: https://www.i18next.com/overview/api#init

**Comment by 0FilipK** [comment]
Makes sense but TSLint shows:
`TS2553: Computed values are not permitted in an enum with string valued members`

Code:
```
enum catSize {
    SMALL = I18n.t('sizes.small'),
    MEDIUM = I18n.t('sizes.medium'),
    LARGE = I18n.t('sizes.large'),
}
```

BTW. I will take this opportunity to ask about something else. If i have exported my instance of I18Next so it's better to use this instance everywhere instead of using additional HOC to get this `t` function right?

**Comment by jamuhl** [comment]
The hoc does more than just passing down a `t` function -> asserts namespaces were loaded (wait option), triggers rerender on language change, ...

**Comment by 0FilipK** [comment]
Ok, but I'm using only one namespace and I disabled language change by user (language can be changed only on deploy - based on env variables).

**Comment by jamuhl** [comment]
in that case you can also just use i18n.t directly if you prefer...https://react.i18next.com/#what-is-react-i-18-next see first hint

**Comment by 0FilipK** [comment]
Ohh, thanks

**Comment by anddon** [comment]
@0FilipK did you manage to find a decent solution for translating members of string enums?

**Comment by 0FilipK** [comment]
@anddon Unfortunately I didn't find solution. I just hardcoded values.

**Comment by anddon** [comment]
@0FilipK Seems like the only way, yeah. Thank you.

**Comment by gmarokov** [comment]
> @0FilipK Seems like the only way, yeah. Thank you.

How did you guys hardcoded the values

**Comment by Nancy-Badran** [comment]
Hi @0FilipK , I have the same issue, I cant load translated text in enum  with i18next,  How did you manage to fix it

**Comment by lucaslt89** [comment]
What I ended up doing is to include the translation keys in the enum, and then use `i18n.t` function with the returned key to get the localized text.

**Comment by ErollIncodeks** [comment]
@jamuhl  Do you have any idea how to solve this:

enum catSize {
    SMALL = I18n.t('sizes.small'),
    MEDIUM = I18n.t('sizes.medium'),
    LARGE = I18n.t('sizes.large'),
}
I'm getting this error:
Computed values are not permitted in an enum with string valued members.ts(2553)

**Comment by jamuhl** [comment]
@ErollIncodeks not sure...in the end it's just typescript complaining and not a real programming language issue. Ignore typescript warnings for that lines of code

**Comment by jamuhl** [comment]
beside that...why does the enum need translated values at all? just move the translation to the rendering

**Comment by FilipKitowski** [comment]
@ErollIncodeks You cannot do that in this way because enum needs to be "prepared" for compilation process and you cannot do any function in there. Just do what @jamuhl said and leave enum like:

`
enum catSize {
SMALL,
MEDIUM,
LARGE,
}
`

and then translate it in your component for example:

`
const getSizeTranslated = () => ({
[catSize.SMALL]: t('translation...'),
[catSize.MEDIUM]: t('translation...'),
[catSize.LARGE]: t('translation...'),
})[size];
`

**Comment by ErollIncodeks** [comment]
@FilipKitowski  Thank you lot :D

**Comment by adrai** [comment]
https://stackoverflow.com/questions/73451867/i18next-react-native-enum-translation-issue

**Comment by richard-unterberg** [comment]
Hey, this is the getter we use, if not we are not in the react context

```
// pointing to your i18n config file in repo
import i18n from '../i18n'

export const getTranslation = (
  key: string,
  options?: Record<string, string | number | undefined>,
) => i18n.t(key, { ...options })
```

can you help me with the types, I think `options` can be refined.
