### ISSUE TITLE
Doesn't seem to work on certain browsers

### ISSUE THREAD

**Issue by harrisrobin** [i18next/react-i18next#480]
Hi,

I'm getting some complaints that the internalization is not working for certain users of our app.

here are some screenshots: 
![image d ios 1](https://user-images.githubusercontent.com/3880008/43038149-2d7b8eb8-8d0c-11e8-93fc-64e47e112373.png)

As you can see, only the key shows up and not the actual text.

I am working on getting more details, but was wondering if anyone else runs into this issue?

**Comment by jamuhl** [comment]
Is this related to loading translation files from https://locize.com - if so i'm not aware of an issue.

Or do you load translations from your own server?

**Comment by harrisrobin** [comment]
@jamuhl files are loaded from my server but would be open to switching if the former solves this. I just don’t understand why this would happen even if they are loaded from my server :s

**Comment by jamuhl** [comment]
I guess translation files were not loaded, or not yet loaded...do you use the wait option on the translate hoc? Really just can guess - did you try to load your side with console setting to have slow network?

**Comment by harrisrobin** [comment]
@jamuhl weird enough this only happens to 2-3 users, I was not actually able to reproduce and to answer your question, i am using the wait option in the `init` and i tried to load my site on a slow network, works fine on my computer. 

I'm getting on a call with the person to investigate, ill come back with more details asap if I manage to reproduce.

**Comment by jamuhl** [comment]
eventual outdated browsers....idk....looking forward to get more informations

**Comment by harrisrobin** [comment]
My bad, the mistake was on our part.

We basically forgot to include a fallbackLanguage and the edge cases were users with browsers outside of our defined languages so all they saw were keys.

Closing this.

**Comment by jamuhl** [comment]
glad you figured that out...
