### ISSUE TITLE
Interpolate.js renders an unwanted <span>

### ISSUE THREAD

**Issue by accessabilly** [i18next/react-i18next#483]
Hi guys,
First of all, I really love your lib! And I would like to contribute something to it's great code.

I encountered, that the `<Interpolate>` component renders a `<span>` element around the given contents (Interpolate.js, line 13 and 20). This is not completely wrong, but in some cases this can be bad for the markup structure.

For example, if you use a CSS Flexbox around a parent element, this makes the `<span>` a block element by default, without any possibility to make it inline. Just a little Codepen to illustrate:
https://codepen.io/accessabilly/pen/NBvvVd

I know, that older versions of React didn't support this feature, but currently you can wrap this in a `<React.Fragment>` and keep the content raw without any wrapping HTML elements.

Thanx for your great work!
Martin

**Comment by jamuhl** [comment]
Personally i think we could remove the Interpolate component - as the Trans component does the same just more flexible...

Do you still see any real use case for it that is not covered by the Trans component? If so we might keep it.

Beside using `React.Fragment` sounds like a valid solution - i'm not to concerned about older versions not supporting it as currently i plan to create a version of react-i18next which replaces the usage of the old context API with the new one - so there will be a breaking version soon anyway - so that change could be added to that major version i guess.

**Comment by accessabilly** [comment]
Hi jamuhl,
Sorry for the late answer.

I personally think after a quick look at the documentation on the [Trans Component](https://react.i18next.com/components/trans-component) , I would agree, that we could maybe use it as well in our project.

But I think, to implement a `<React.Fragment>` in the Interpolate Component would be lesser harmful in terms of breaking other peoples implementations after updates.

Greets,
Martin

**Comment by jamuhl** [comment]
Hm...the Trans component does not add additional wrappers (at least not for react >16) it just returns the children.

**Comment by accessabilly** [comment]
Yes. Using it instead is perfectly fine for me.
Thank you!

**Comment by florentcuret** [comment]
Hi, I agree with @accessabilly, I guess <React.Fragment> would solve the following warning:

`Warning: validateDOMNesting(...): <span> cannot appear as a child of <option>.
    in span (created by Interpolate)
    in Interpolate (at TestComponent.js:33)
    in option (at TestComponent.js:63)
    in select (created by FormControl)
    in FormControl (at formUtil.js:202)
    in div (created by FormGroup)`

**generated html:**
[test.html.txt](https://github.com/i18next/react-i18next/files/2269269/test.html.txt)

**Comment by florentcuret** [comment]
Just tried with Trans component and got
`Warning: validateDOMNesting(...): <div> cannot appear as a child of <option>.
    in div (created by Trans)
    in Trans (at BonusConfigurationDialogComponent.js:38)
    in option (at BonusConfigurationDialogComponent.js:71)
    in select (created by FormControl)
    in FormControl (at formUtil.js:202)`

**Comment by jamuhl** [comment]
Did you set a parent for Trans -> regulary it should not add a wrapper but just return the children you added

**Comment by florentcuret** [comment]
no i did not. in the warning it is written 'in div (created by Trans)'. Now I simply use translate to avoid the warning.

**Comment by jamuhl** [comment]
like said the Trans component does not create own elements just uses what i gets...have a look at the code
