### ISSUE TITLE
Tabs translated using fallBackLanguage

### ISSUE THREAD

**Issue by HaJo10** [i18next/react-i18next#484]
Hi, I added some tabs using createBottomTabNavigator (v2). All works well on tab-screens, but the navigationOptions / tabBarLabel s are translated using i18n.init.fallbackLng instead of using the selected language which is used to translate contence inside the screens.

Any idea?

My sample is based on 
https://github.com/i18next/react-i18next/tree/master/example/react-native-expo
npm i i18next react-i18next --save
npm install --save react-navigation

**Comment by jamuhl** [comment]
No idea...can only guess those tabs get translated before i18next init was done

**Comment by HaJo10** [comment]
ok, not really understood why translation of tabTitles was done by using fallBackLng. But after I moved title as a -static navigationOptions- to the screen files it works as expected !!!
Thanks, your answer atleast brought me to think it over and find the solution.
So thankyou very much!!!

**Comment by craigcosmo** [comment]
@HaJo10  can you share how exactly you do it? Appreciate
