### ISSUE TITLE
DRY issue with the razzle-ssr example

### ISSUE THREAD

**Issue by a-barbieri** [i18next/react-i18next#485]
Hi I have a DRY issue with the **razzle-ssr example**. 

I can probably solve it myself but I'd rather ask before doing something wrong.

1. Is there any reason for which [i18n options](https://github.com/i18next/react-i18next/blob/master/example/razzle-ssr/src/i18n.js#L5-L29) aren't implemented [on the server side rendering](https://github.com/i18next/react-i18next/blob/master/example/razzle-ssr/src/server.js#L21-L25)?
1. Is there a reason for which `wait` isn't set globally among [i18n options](https://github.com/i18next/react-i18next/blob/master/example/razzle-ssr/src/i18n.js#L5-L29), but spread around the application ([here](https://github.com/i18next/react-i18next/blob/master/example/razzle-ssr/src/i18n.js#L32) and [here](https://github.com/i18next/react-i18next/blob/master/example/razzle-ssr/src/Home.js#L33))

Happy to make a PR if needed

**Comment by jamuhl** [comment]
1) init is here and than here again for server specific stuff -> doing a second init will use existing options and just overwrite the new options

2) might be cause that global option did not yet exist when creating the sample...or just some copy over...could be changed to global if you prefer - PR welcome

**Comment by a-barbieri** [comment]
> doing a second init will use existing options and just overwrite the new options
Good to know.

I've made a PR to update the example and DRY `wait` option

**Comment by jamuhl** [comment]
merged...thank you
