### ISSUE TITLE
SSR with Razzle doesn't render nested translations

### ISSUE THREAD

**Issue by a-barbieri** [i18next/react-i18next#487]
Hi I've made an [example](https://github.com/a-barbieri/react-i18next/commit/83a4760820ae8e5fc2b3b33a9c0403c350edc680) in my fork in order to easily reproduce the issue.

In the Razzle example, React-i18next doesn't render nested translations as [it should](https://www.i18next.com/translation-function/essentials).

Say we have the following translations

```json
{
  "website": {
    "title": "My amazing blog"
  }
}
```

If we do `t("website.name")` it prints `website.title`

But it does work for top level values:

```json
{
  "website_title": "My amazing blog"
}
```

If we do `t("website_name")` it correctly prints `My amazing blog`

**Comment by a-barbieri** [comment]
Bummer. It was just [this line](https://github.com/i18next/react-i18next/blob/master/example/razzle-ssr/src/i18n.js#L13):

```
keySeparator: '##### not used #####', // as we use full text keys in this sample
```

Changing it this way it get back to the default behaviour.

```
keySeparator: '.'
``` 

Question: does this generate a issue with `<Trans>` component [here](https://github.com/i18next/react-i18next/blob/master/example/razzle-ssr/src/Home.js#L17-L20)?

**Comment by jamuhl** [comment]
Right...main reason i switch those samples to use no keySeparator is to allow the Trans component to define it's key by the content (which can include `.` and would be split on lookup otherwise).

Adding the keySeparator back you will have to define the prop `i18nKey` on the Trans component.

**Comment by a-barbieri** [comment]
If it's ok with you I'd rather define `i18nKey` on the Trans component and leave the default behaviour.

From my experience doing SSR for the first time is very complex and it's very helpful to have examples that uses default settings rather then edge cases.

If it's ok with you I can update the PR. How should `Trans` component be written?

**Comment by jamuhl** [comment]
Just add the prop i18nKey to it and have the translation have the key instead of the content...

For me it's ok if you change than -> and yes...SSR is far from easy

**Comment by jamuhl** [comment]
merged
