### ISSUE TITLE
Wrapping containers with i18n and injecting t to children elements

### ISSUE THREAD

**Issue by wsielskx** [i18next/react-i18next#490]
I was wondering if there is currently an option to use `translate` for the container elements only and inject `t()` to the children elements. For example, having an application like this:

```
<App>
	<Users>
        <List>
            <User />
            <User />
        </List> 
    </Users>
</App>
```

For me, it's fine to use current `translate()` within the `<Users />` component because I can use the `tReady` flag to make sure it's namespace is fetched and ready to use. But I don't really need the i18n wrapper for the child elements of the `<Users />`. I know I can pass the `t()` as a prop to the children tree, but I don't really like this idea.

Maybe simple HOC injecting the `t()` inside the components would be a good idea? Something like the simplified version of `translate` from before `react-i18next@6.0` version?

**Comment by jamuhl** [comment]
Yes the next upcoming major version will use the new context API so you will be able to get `t` from the context consumer...

Would that work for you? Means are you already on react > 16.x

**Comment by wsielskx** [comment]
Sounds great! Happy to hear that. Kepp up good work! :)
