### ISSUE TITLE
<Trans> component count is undefined

### ISSUE THREAD

**Issue by HichemBenChaaben** [i18next/react-i18next#492]
Sorry, that might sound silly.
in this example here i got ```count``` is undefined, borrowed from the documentation
assuming in this snippet `state.count` is defined and passed to the component but the `{{count}}` is undefined.

```
<Trans i18nKey="userMessagesUnread" count={this.state.count}>
  Hello you have {{count}} unread message.
</Trans>
```
the project setup is exactly this https://codesandbox.io/s/l4qrory2nl

**Comment by jamuhl** [comment]
Was this solved?

**Comment by HichemBenChaaben** [comment]
@jamuhl nope, but i opened two issues by mistake.

I think I managed to figure out what was the issue in there, the interpolated `count` which is undefined need to receive a value.
So in my case, the fix looks like this.

```
<Trans i18nKey="userMessagesUnread" count={this.state.count}>
  Hello you have {{count: this.state.count}} unread message.
</Trans>
```
