### ISSUE TITLE
Razzle example i18n logging details to server console

### ISSUE THREAD

**Issue by DevanB** [i18next/react-i18next#496]
Hey there 👋 

I've noticed that the Razzle example logs a _lot_ of information to the console on server restart (which happens often). 

I've been unable to find where this is being toggled to log at so I can turn it off.

I do have `debug: false` in my `i18n.js` config, but that didn't stop the logging.

It seems it might be one of the few plugins used on the Express side?

Thanks for any help! :)

Screenshot of the information being logged out:
![screen shot 2018-08-15 at 8 22 30 am](https://user-images.githubusercontent.com/354652/44148056-adfd598e-a064-11e8-9865-1feff86e68cf.png)

**Comment by jamuhl** [comment]
first line of the screenshot...debug: true -> somewhere it must be set to true

**Comment by DevanB** [comment]
You are absolutely right! I just needed another set of eyes to point it out to me. 

The file had `debug: true` removed, however Razzle didn't know about the updated file it looks like.

Razzle also doesn't know to reload with updated translations, but that's a different issue :)

Thanks for all the fantastic help @jamuhl!
