### ISSUE TITLE
Functions are not valid as a React child

### ISSUE THREAD

**Issue by robclouth** [i18next/react-i18next#498]
Hey, this might be a silly problem but I'm getting that error when wrapping a basic component with ```translate```, and the component fails to render. I'm getting the debug messages saying that i18next has initialised.

I'm rendering it like this:
```const Test = translate(props => <div>{props.t("test")}</div>);```

I've wrapped the App root component in ``` <I18nextProvider i18n={i18n}>```

My i18n config is this:
```
import i18n from "i18next";
import languageDetector from "./languageDetector";
import backend from "./backend";

export default i18n
  .use(backend)
  .use(languageDetector)
  .init({
    fallbackLng: "en",
    resources: {
      en: {
        common: {
          test: "Test"
        }
      }
    },
    ns: ["common"],
    defaultNS: "common",
    debug: true,
    interpolation: {
      escapeValue: false
    },
    react: {
      wait: true
    }
  });
```

Any ideas?

**Comment by robclouth** [comment]
I'm wrapping the root component of the whole app in ```I18nextProvider```.
I haven't tried using ```reactI18nextModule``` but not ```setI18n```. I'll try that.

**Comment by jamuhl** [comment]
hm...having it wrapped should be good enough...wondering why it does not work.

What is your i18n that you pass as props to the I18nextProvider?!?

**Comment by robclouth** [comment]
It's the one I posted in the first message.

**Comment by jamuhl** [comment]
arghhh now i see it:

you have `const Test = translate(props => <div>{props.t("test")}</div>);`

but should be:

`const Test = translate()(props => <div>{props.t("test")}</div>);`

https://react.i18next.com/components/translate-hoc#sample -> `export default translate()(TranslatableView);`

**Comment by robclouth** [comment]
Wow that was silly of me. Thanks loads for spotting it!

**Comment by Fl4v10** [comment]
None of the pages linked above are available.

**Comment by jamuhl** [comment]
@Fl4v10 It's an issue that is 1 year old - the documentation changed since that date...

https://react.i18next.com is the link of the documentation
