### ISSUE TITLE
Interpolating Components

### ISSUE THREAD

**Issue by Adkaiser** [i18next/react-i18next#501]
Hello. I know this question has been asked before, but I'm having trouble finding a straightforward example of the current solution for this. I need to interpolate the text output of React components into my translations. I've been messing with the Interpolate component, but it seems to be giving me nothing but <noscript> results, despite the fact that my translations seem to be working. I also see that component is depreciated. The Trans component returns content, but the interpolated components just display as [object Object], as happens when calling my i18n.t() function directly.

Is there a good working example of the current way to do this?

**Comment by jamuhl** [comment]
https://github.com/i18next/react-i18next/blob/master/example/react_withHOC/src/App.js#L23

Guess more or less every sample in the example folder has a case of using the Trans component.

My guess is you just took / created a wrong translation string for the Trans component: Make sure you take that from the console output (set debug: true on init to get the missing output for that translation)
