### ISSUE TITLE
Super confused about Docs about Trans component

### ISSUE THREAD

**Issue by alex-wilmer** [i18next/react-i18next#502]
This is from the Trans docs:

![image](https://user-images.githubusercontent.com/2880089/44751346-ee79ea00-aae5-11e8-8528-0d5bc38edc95.png)

My key confusion comes from this line:

> Your en.json (translation strings) **will** look like:

how though?? Is there some utility script I'm supposed to be running to generate these key value pairs?

**Comment by jamuhl** [comment]
https://react.i18next.com/components/trans-component#how-to-get-the-correct-translation-string

Most will use the save missing function to create those. Eg. have a look at https://github.com/i18next/react-i18next/tree/master/example/locize-example how to get that fully automated

Or use the https://github.com/i18next/i18next-parser - i guess that also supports extracting the Trans component

**Comment by jamuhl** [comment]
Feel free to reopen. Closing this for now - we're aware that documentation could be improved -> accepting PR on docs would be a great way to contribute too
