### ISSUE TITLE
Imported static field translation does not reevaluate

### ISSUE THREAD

**Issue by Elminday** [i18next/react-i18next#503]
To create translations for my form I use exported fields:
```
// ProfilesFormConfig
import i18n from '~/shared/i18n';

class ProfilesFormConfig {
  static fields = {
    name: {
      label: i18n.t(`${MODULE.PROFILE}:label.name`),
    },
  };
}
```
and import it here:

```
// FormConfigFactory
import ProfilesFormConfig from '~/shared/form/config/ProfilesFormConfig';

create() {
  console.log(i18n.languages[0]); // 'lt'
  console.log(ProfilesFormConfig.fields.name.label); 'en translation, expect lt'
}
```

How can this be solved so that my imported fields are reevaluated on create function?

**Comment by jamuhl** [comment]
we run into this our self in the past...as `t` does just return a string you must change how you^re using your stuff - delay calling that t function:

```js
// ProfilesFormConfig
import i18n from '~/shared/i18n';

class ProfilesFormConfig {
  static fields = {
    name: {
      label: () => i18n.t(`${MODULE.PROFILE}:label.name`),
    },
  };
}
```

```js
console.log(ProfilesFormConfig.fields.name.label());
```

**Comment by jamuhl** [comment]
or just use keys there and during render:

`console.log(t(ProfilesFormConfig.fields.name.label));`

**Comment by Elminday** [comment]
Thank you for such a fast reply!

**Comment by Elminday** [comment]
Off-topic question, is it possible to assign static object property a getter?

This way `this` is undefined as it is static.
```
class ProfilesFormConfig {
  static get nameLabel() {
    return i18n.t('label.name');
  }

  static fields = {
    name: {
      label: this.nameLabel,
    },
};
```

Because my form handling library accesses label as a value not as a function.

**Comment by jamuhl** [comment]
Hm...you will need to do a quick try...not sure but i guess it will also be that the label gets set to a string and not revalidate.

An other options would be to set those values again if you get an event: https://www.i18next.com/overview/api#onlanguagechanged

```js
class ProfilesFormConfig {
  static fields = {
    name: {
      label: () => i18n.t(`${MODULE.PROFILE}:label.name`),
    },
  };
}

i18n.on('languageChanged', function(lng) {
  ProfilesFormConfig.fields.name.label = i18n.t(`${MODULE.PROFILE}:label.name`); // has now the new lng
})

```
