### ISSUE TITLE
I18NextProvider.reportNS function does not report default namesapce

### ISSUE THREAD

**Issue by tutok** [i18next/react-i18next#504]
It looks like namespaces reported by `reportNS` is `undefined` when no namespace is specified and fallback rule is executed. 

For example, if I set `{ defaultNS: 'global' }` option in i18next and use translate HOC `translate()(Home);` then component `Home` will be translated using `global` namespace. But `reportNS` returns `undefined`

@olivierpascal can you look on this?

**Comment by olivierpascal** [comment]
This is definitely a bug. I'll take care of it.

**Comment by olivierpascal** [comment]
@tutok are you using this feature for SSR? Just wondering.

**Comment by tutok** [comment]
@olivierpascal yes, I use it with SSR

**Comment by jamuhl** [comment]
guess this one could be closed...PR was merged
