### ISSUE TITLE
Setting up with React-native-router-flux

### ISSUE THREAD

**Issue by ramibaraka** [i18next/react-i18next#505]
The react native example is limited to using a stack based navigator with React-nativation.

Since react-native-router-flux is a very popular option i think it would be appreciated by many if you could setup a quick example on how to use the provider wrapper with it.

**Comment by jamuhl** [comment]
We used that library in the past and i would love to see a sample using - but with react-navigation i personally opt out of using it.

If you like provide a PR with that sample - this would be very appreciated and merged asap.

**Comment by ramibaraka** [comment]
Could you post some example code from your previous experience with it? 

I've been trying to get it to work with no luck.

**Comment by jamuhl** [comment]
no...sorry. no access to that code...plus that was a very old version.

What problem you run into? should be rather straight forward...i18n is not coupled to routing

**Comment by ramibaraka** [comment]
Just not sure how to set it up. Should I just wrap the router with the provider?

**Comment by jamuhl** [comment]
If you need the provider yes

**Comment by ramibaraka** [comment]
Im guessing I do in order to rerender the routes. Or have I misunderstood the way it works?

**Comment by jamuhl** [comment]
the translate hoc does the rerender on language change: https://github.com/i18next/react-i18next/blob/master/example/react-native-expo/App.js#L18

the provider only passes down the i18n instance via context -> https://react.i18next.com/components/overview#components
