### ISSUE TITLE
PrevProps the same as current props

### ISSUE THREAD

**Issue by lomboboo** [i18next/react-i18next#508]
Hi and thanks for awesome library.

I use react-i18next in my project and I've got an issue when I want to access `prevProps` within `ComponentDidUpdate` for example. In this case `language` field in the `i18n` object is the same as `this.props`. You can see it in this [demo](https://codesandbox.io/s/03877y0960) .

I took a look in the [core](https://github.com/i18next/react-i18next/blob/master/src/translate.js#L20) and found that inside `translate` HOC you mutate `i18n` object. 

Is there any reason why it was implemented this way? I'd really like to have `prevProps` has correct values

**Comment by jamuhl** [comment]
it is the same object (singleton) and not an immutable...it just try to look it up in the different possible locations (context, props, ...)

what exactly is your issue - why you need that previous language?

**Comment by lomboboo** [comment]
Thanks for quick response.

I have a case where I need to do some async calls when language changed. So I'd have condition in the `ComponentDidMount` something like `this.props.i18n.language !== prevProps.i18n.language` then do some logic.

Although i18next has `languageChanged` event, it's inconvenient to use in the react app. It'd be much simpler if prevProps worked "react like".

**Comment by jamuhl** [comment]
hm...then i would suggest we pass lng from translate to component as a prop...the i18n instance is based on i18next and can't be really changed therefor

so adding it to the I18n render props which is used in translate hoc and from there add it to components props?!?

**Comment by lomboboo** [comment]
I can work on PR, but I'm not sure what are you referring to. You're talking about pass as prop [here](https://github.com/i18next/react-i18next/blob/master/src/translate.js#L74)?

**Comment by jamuhl** [comment]
yes and also here: https://github.com/i18next/react-i18next/blob/master/src/I18n.js#L124 

basically passing it from that I18n to the line you showed above...

feel free to make a PR
