### ISSUE TITLE
Typescript Type Error When Used With Constructor

### ISSUE THREAD

**Issue by CJamesKeller** [i18next/react-i18next#510]
**Overview:**
Our project is using:
- react-i18next   7.11.0,
- i18next   11.6.0,
- react   16.0.0,
- react-native   0.51.0,
- typescript   2.9.2,
- @types/react-i18next   7.8.2,
- @types/i18next   8.4.4,
- @types/react   16.4.7,
- @types/react-native   0.56.4

And we have a component setup like this:

**index.tsx**
```javascript
import * as React from 'react';
import { I18nextProvider } from 'react-i18next';
import { Provider } from 'react-redux';
import { applyMiddleware, createStore } from 'redux';
import thunkMiddleware from 'redux-thunk';

import AppContainer from './containers/app/index';
import i18n from './i18n';
import reducers from './reducers/index';

const store = createStore(reducers, applyMiddleware(thunkMiddleware));

const App = () => (
	<I18nextProvider i18n={i18n}>
		<Provider store={store}>
			<AppContainer />
		</Provider>
	</I18nextProvider>
);

export default App;
```

**i18n/index.ts**
```javascript
import * as i18n from 'i18next';
import { reactI18nextModule } from 'react-i18next';

import * as enUS from './en-US/common.json';

export default i18n
	.createInstance()
	.use(reactI18nextModule)
	.init({
		lng: 'en-US',
		react: { wait: true },
		resources: { 'en-US': { common: enUS } },
	});
```

**tsconfig.json**
```javascript
{
	"compilerOptions": {
		"allowJs": true,
		"allowSyntheticDefaultImports": true,
		"experimentalDecorators": true,
		"jsx": "react-native",
		"module": "commonjs",
		"moduleResolution": "node",
		"noEmit": true,
		"noErrorTruncation": true,
		"outDir": "dist",
		"pretty": true,
		"rootDirs": [
			"src",
			"example/src"
		],
		"skipLibCheck": true,
		"target": "es2015",
		"types": [
			"jest",
			"node",
			"react",
			"react-native"
		]
	},
	"exclude": [/* our excluded folders*/],
	"include": [/* our included folders */]
}
```

And then within the App, we have a component like this:
(The interfaces are exported from another file, but all laid out here, names changed, in the exact format as we use them)

**Some Component:**
```javascript
interface ComponentProps {
	func1: Function;
	func2: Function;
	t?: Function;
	infoObj1: any;
	stringThing: string;
	importantThing: ImportantThing; /* defined by another interface */
	error?: ErrorObject; /* same deal */
}

interface ImportantThing { /* all optional */
	name?: string;
	isThingish?: boolean;
	someId?: string | null;
	importance?: Importance; /* again, another interface */
	watch?: Watch; /* and here */
}

interface Importance {
	group: Group[];
	names: Names;
}

interface Group {
	title: string;
}

interface Names {
	display: string;
}

interface Watch {
	attribute: Attribute[];
	organizedAttrs: OrganizedAttrs;
}

interface Attribute {
	writable: boolean;
	name: string;
	display: Display;
	labels: string[];
}

interface Display {
	name: string;
}

interface OrganizedAttrs {
	main: Main;
	secondary: Secondary;
}

interface Main {
	attributes: Attribute[];
}

interface Secondary {
	label: string;
	attributes: Attribute[];
}

interface ErrorObject {
	status?: string | number;
	message: string;
	name?: string;
}

interface ComponentState {
	doThing?: boolean;
}

class SomeComponent extends Component<ComponentProps, ComponentState> {
	public constructor (props) {
		super(props);
		this.state = {
			doThing: false
		};
	}
	/* lifecycle methods and content rendered; setState is used for an onPress() function */
}

export const Some = translate(['common'])(SomeComponent);
```

**Error Message:**
`Type '{ /* properties with types here */ }' has no properties in common with type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<Pick<any, never> & TranslateHocProps, ComponentState, any>> & Readonly<{ children?: ReactNode; }> & Readonly<Pick<any, never> & TranslateHocProps>'.`

**Question:**

Our component renders and tslint is happy as can be if we do not call `super(props)`.

But as soon as we add in a constructor again to handle `state`/`setState`, we get the errors.

I was unable to find any documentation of similar errors that helped with this issue, and have been using a bad workaround for the time being.

Do you have any idea why we might be encountering this issue?

Thank you.

**Comment by jamuhl** [comment]
Not using typescript at all i won't be able to be of big help - if there is anything wrong with the code provided by us that needs to be changes - let me know - we would be able to do so.

eventual opening this question over at stackoverflow migh extend the reach?!?

**Comment by CJamesKeller** [comment]
I am not sure that there are specific issues with your package, so no worries, but I wonder if the way the component is wrapped ends up causing type-compatibility issues that the folks at `@types/react-i18next` could answer... I will close the issue here and open with them!

**Comment by xfo78** [comment]
@CJamesKeller can you please link to the issue in @types/react-i18next. I'm experiencing a similar behavior. I'm wrapping a lot of HOCs around my components (material-ui's withStyle & withWidth, react-redux' connect) that also use own properties. But it's just the translate HOC that is causing this error message. In my case it's got nothing to do with a constructor, simply the fact that the component uses own properties.

**Comment by CJamesKeller** [comment]
Here is the other issue; hope it helps!
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/28709
