### ISSUE TITLE
Correct type when using `t()` 

### ISSUE THREAD

**Issue by DevanB** [i18next/react-i18next#512]
Hey! 👋 

First, thanks for a great library!

I'm using react-i18next with TypeScript while building a component library for my employer. I'm curious what the correct type declaration would be when using the `t()` function. Here is an example component:

```
<StyledInput id={id} placeholder={placeholder} {...props}/>
```

My props interface is:

```
export interface StyledInputProps {
  id: string
  placeholder:
    | string
    | InferableComponentEnhancerWithProps<"t">
    | InferableComponentEnhancerWithProps<"t"> & string;
}
```

This seems a bit verbose, and actually conflicts with the standard HTML placeholder definition, which leads me to believe I'm doing it incorrectly. 

Any thoughts would be appreciated! Thanks! 😄

**Comment by DevanB** [comment]
@ramonitor This helps so much! I didn't realize `InjectedTranslateProps` was an exported interface I can extend.

While I have your attention, do you have an example of correctly using the `Trans` component in TS? I'm doing something to the likes of:

```
<Trans
  i18nKey="calculator.employees-with-benefits-question"
  employees={this.state.numberOfEmployees}
>
  Out of {{ employees }} employees, how many receive health benefits?
</Trans>
```

However, TS doesn't like that `employees` isn't defined in the props for the `Trans` component, and isn't a value when used. I might be using the component incorrectly all together.

@jamuhl Thanks for keeping this issue open despite your sentiment on TS! 😄

**Comment by ramonitor** [comment]
@DevanB Just got my first Trans component working after some trouble myself so at this moment I'm not exactly sure how it works. As far as I known you can only specify the props defined in the TransProps interface to the Trans component. Maybe you can use the values prop for this, not sure.

**Comment by DevanB** [comment]
@ramonitor I looked at the interface and notices the values prop, but haven't gotten it working correctly, still.

**Comment by jamuhl** [comment]
no need to add it to Trans props:

The Trans works like:

```js
const { numberOfEmployees }  = this.state;

<Trans
  i18nKey="calculator.employees-with-benefits-question"
>
  Out of {{ numberOfEmployees }} employees, how many receive health benefits?
</Trans>

// or

<Trans
  i18nKey="calculator.employees-with-benefits-question"
>
  Out of {{ employees: this.state.numberOfEmployees }} employees, how many receive health benefits?
</Trans>
```

**Comment by jamuhl** [comment]
yes...you will see it in console -> using debug true (missing key)

Or use https://locize.com with the i18next-locize-backend and it gets added to your translation project automatically.

Just to note, in your current code there is no need to use Trans, as this is the same:

```js
{t('employees-with-benefits-question', { employees: this.state.numberOfEmployees })}
```

would be different if you use some thing like string formatting:

```js
<Trans
  i18nKey="calculator.employees-with-benefits-question"
>
  Out of <strong>{{ employees: this.state.numberOfEmployees }}</strong> employees, how many receive health benefits?
</Trans>

// translation
"employees-with-benefits-question": "Out of <1>{{employees}}</1> employees, how many receive health benefits?",
```

for details: https://react.i18next.com/components/trans-component#how-to-get-the-correct-translation-string

or the full story: https://react.i18next.com/misc/the-trans-component-explained

**Comment by DevanB** [comment]
Ah! Thanks! I figured there was an option to use `t`. In fact, I'd prefer that. Thanks for the help!
