### ISSUE TITLE
Global instance usage within sagas, redux, etc.

### ISSUE THREAD

**Issue by chacestew** [i18next/react-i18next#515]
This is firstly a question following which I might have a suggestion. Are there problems caused by calling methods on the i18n instance outside of the React tree in a single client-side application? 

For example, within a redux middleware.

i18n.js

```js
import i18n from 'i18next';

i18n.init(options);

export default i18n;
```
client.js

```js
import { I18nextProvider } from 'react-i18next';
import i18n from './i18n.js';

<I18nextProvider i18n={i18n}>
  {...etc}
</I18nextProvider>
```

saga.js
```js
import i18n from './i18n.js';

function* triggedByReduxAction () {
  i18n.loadNamespaces(ns) // avoiding redux-saga syntax for sake of example
}
```

My assumption is that `i18n` prop in the React context is a reference to the instance, so by loading new namespaces all consumers of context will have access to the new namespace. Additionally, changing the language outside of the tree will also cause React components to update accordingly.

**Comment by jamuhl** [comment]
No there is no problem calling function on i18n outside of the render tree.

We use that for accessing t function in saga's or whatever we're up to. As long there is only one i18next instance used inside your app there is no problem with it.

**Comment by chacestew** [comment]
Thanks for confirming. I was then wondering how to handle universal code that interacted with i18n instance. For example, the same saga above could be running both client- and server-side. My solution has been to pass the instance as an additional argument to the root `runSaga()` called at the top of client and server - which works fine, but can introduce many places where you need to pass down the instance.

This could be simpler with a way to store the i18next instance in redux for middleware to access outside of the render tree. Has this been done or suggested elsewhere? Something similar to how [connected-react-router](https://github.com/supasate/connected-react-router) keeps a synced router state in the store and exposes the ability to call navigation methods via actions, etc.

**Comment by jamuhl** [comment]
guessing not done yet -> you might be the first sharing such an approach...idk (personally not had the need for universal stuff)

**Comment by jamuhl** [comment]
closing this for now - would be happy to hear back from you if you digged deeper into this
