### ISSUE TITLE
Array of objects in json

### ISSUE THREAD

**Issue by nagman** [i18next/react-i18next#518]
Is it possible to pass an array of objects in the translation json files?
So that I can loop on them easily.

For instance, in my .json:
```
{
  "testimonials": [
    {
      "text": "I like ice cream",
      "author": "Bob"
    },
    {
      "text": "I like dogs",
      "author": "Dog"
    }
  ]
}
```

And in my component:
```
t('testimonials').map(({text, author}) => (
  <blockquote>{text}</blockquote>
  <cite>{author}</cite>
);
```

If I try this, `testimonials` returns undefined.

**Comment by nagman** [comment]
Woops, sorry it actually works 😛 
I was using the wrong Provider for i18n.

**Comment by baxromxojasultonxojayev** [comment]
how can I iterate array elements to unrodered list with map

<ul className="right-side">
          {t("text", { returnObject: true }).map((text, country_code) => (
            <li key={country_code}>
              <a href="#">{text}</a>
            </li>
          ))}
        </ul>

when I do this it gives me t(...).map is not a function

**Comment by jamuhl** [comment]
it's not `t` that gives the map function -> if `t` returns an array given it is an array in your resources there is a map function

**Comment by adrai** [comment]
@baxromxojasultonxojayev it's `returnObjects` not `returnObject`
PS. please do not post your questions in other issues... you commented on 3 different issues

**Comment by baxromxojasultonxojayev** [comment]
Hi! I have issue about i18next, I have an array list and I want to
translate lements to different languages with the help of i18next library
of react. Yet when I wrote and run code it works well at first later it
does not work. Here my code t("text", { returnObjects: true }).map((item,
country_code ) =>(<li key={country_code}> <a href="#">{item}</a> </li>).
And my error is t(...).map is not function. I could not solve this. Can you
help me <https://github.com/i18next/react-i18next/issues/1364> can not
reproduce
<https://github.com/i18next/react-i18next/issues?q=is%3Aissue+is%3Aopen+label%3A%22can+not+reproduce%22>

вт, 31 авг. 2021 г. в 14:23, Jan Mühlemann ***@***.***>:

**Comment by adrai** [comment]
@baxromxojasultonxojayev you already opened an issue here: https://github.com/i18next/react-i18next/issues/1364
please comment there!

**Comment by Rohullah-Sarabi** [comment]
I have the same problem, If anyone can help me I will be thankful.
this is my json file:
{"menu":[
      {"title":"Home","link":""},
      {"title":"Browse Jobs","link":"/jobs"},
      {"title":"Canditates","link":"/canditates"},
      {"title":"Contact US","link":"/contact"},
      {"title":"Blog","link":"/blog"},
      {"title":"login","link":"/login"},
      {"title":"Sign Up","link":"signin"}
    ]  }
and this is my code:
function Nav() {
  const t  = useTranslations("nav");
  return (
    <ul>
      {
        t("menu",{returnObjects: true}).map(({title,link})=>(
          <li>{title}</li>
        ))
      }
    </ul>);
}

the output is :TypeError: t(...).map is not a function

**Comment by adrai** [comment]
@Rohullah-Sarabi please provide a reproducible example.
Like this one: https://codesandbox.io/s/react-i18next-http-example-forked-ml97gt?file=/src/app.js:729-808 (seems to work)...
In case you're not using suspense, make sure you check the ready flag... if the translations are not yet loaded, the t function will return a string and not an object
