### ISSUE TITLE
Inherit namespaces and their fallbacks without explicitly naming them

### ISSUE THREAD

**Issue by nicolasschabram** [i18next/react-i18next#519]
Hey there,

short version: Is it possible to use i18n keys without explicitly naming the namespace as long as it has been loaded by some `I18n` component higher up in the component tree?

------

**Long version:**

I'm currently trying to use react-i18next for the following use case: an application that's built for different clients and targeted towards different user groups. The terminology for different clients differs but they will reuse a lot of the same UI components. Here's the namespace structure I came up with:

- **Admin.json**
  - **AdminClient1.json**
  - **AdminClient2.json**
- **Manager.json**
  - **ManagerClient1.json**
  - **ManagerClient2.json**
- **Editor.json**
  - **EditorClient1.json**
  - **EditorClient2.json**

The top-level namespaces (e.g. `Admin.json`) contain strings shared by all clients. The ones below (e.g. `AdminClient1.json` contain additional strings specific to one client as well as some strings overriding the ones in the parent namespace. Important to note is that, e.g. Client1 users should never download Client2 strings, and Editors should never download Manager or Admin strings.

There are different entry points to the app for the different clients. Ideally, that's the only place that has to know about different clients and their namespaces. I thought I could do something like this:

```jsx
const Client1EntryPoint = () => (
  <I18n ns={["AdminClient1", "Admin"]} nsMode="fallback">
    {t => <AdminInterface />}
  </I18n>
);

const Client2EntryPoint = () => (
  <I18n ns={["AdminClient2", "Admin"]} nsMode="fallback">
    {t => <AdminInterface />}
  </I18n>
);

const AdminInterface = () => (
  <I18n>
    {t => t("someKey")}
  </I18n>
);
```

My idea is that `AdminInterface` (which is shared by all clients) implicitly inherits all namespaces from its ancestor components. It should not have to specify namespaces (~~`AdminClient2:someKey`~~) so that it doesn't have to know about all the clients and their terminology differences. Instead, if `AdminInterface` happens to live inside `Client1EntryPoint`, it should first look up `"someKey"` in the `AdminClient1` namespace and, if missing, check out the `Admin` namespace. Accordingly, if `AdminInterface` is a descendant of `Client2EntryPoint`, it should first check `AdminClient2` and then `Admin`.

Now to the problem: Apparently, it doesn't work that way. The `I18n` component in `AdminInterface` doesn't inherit the namespaces higher up in the component tree but instead only looks up `someKey` in the `defaultNS` specified on the `i18n` instance's options. That's consistent with what [this code here](https://github.com/i18next/react-i18next/blob/master/src/I18n.js#L12) seems to be doing.

How would you approach that case? I got some (untested) ideas:

1. The EntryPoint components define the namespaces and their fallbacks and pass the `t` function from `I18n` down to `AdminInterface` as prop.
2. The EntryPoint components put the `t` function into a shared React context provider `AdminI18n` that can be imported from `AdminInterface` to get a `t` function with correct namespace (fallbacks).

I guess solution 1 is feasible and solution 2 even somewhat elegant. However, as the `I18n` component does 90% of what I need, couldn't that use case also be a thing that `react-i18next` handles itself?

I'd be happy to hear your thoughts on that! Let me know if I left things unclear or can be of any assistance!

Thanks for building i18next, and thanks for your help!
Nicolas

**Comment by jamuhl** [comment]
Let's make it short - yes both your solutions 1. and 2. will work. Another option would be already merging the clients and common translations while loading (creating some custom backend - guess you're using xhr).

While I not against an option to share/inherit those namespaces - I yet have no idea how to do so (might be something we could do more easily with the next breaking change when we adopt the react v17 context API). Also, it would have to be an opt-in solution - but really open getting this added.

**Comment by jamuhl** [comment]
closing this for now - if still relevant - feel free to reopen

**Comment by nicolasschabram** [comment]
Solution 2 has worked out okay-ish, although I had to jump through a few hoops. I've seen that you've recently released a new context-based major version. Would that make things easier with regards to inheriting namespaces?

**Comment by jamuhl** [comment]
i guess not really...the main API still stays the same - just using new context api under the hood
