### ISSUE TITLE
Using the t-function to replace part of the string with a value

### ISSUE THREAD

**Issue by paul019** [i18next/react-i18next#522]
Hi there,

it might be a stupid beginner question, but how is it possible to replace a part of a string with a certain value using the t-function? I tried various things, e.g. `t("Hello %{name}!", {name: "Noah"})`, but nothing worked.

Note: I use the string content as keys and locize as backend.

**Comment by jamuhl** [comment]
not sure if you missed the note on the translate hoc or i18n render prop: https://react.i18next.com/components/translate-hoc

-> lookup the details here for interpolation and plurals: https://www.i18next.com/translation-function/interpolation#basic

```js
// json
{
    "key": "{{what}} is {{how}}"
}

// js
i18next.t('key', { what: 'i18next', how: 'great' }); // -> "i18next is great"
```

**Comment by paul019** [comment]
Thank you very much!

I didn't find the needed information under the first link, but the second link now helped me very much.

**Comment by TutoDS** [comment]
Anyone already use to translate responses from api?
If yes is possible I translate parte of string, for example
Customer name is required, and I want translate to Portuguese like customer name => nome do cliente and translate is required => é obrigatório

if possible I reuse the common parts (like is required, needs to be a string, ...)

**Comment by jamuhl** [comment]
It's code....everything is possible somehow....as long the API response does not contain any variables in the returned string message it's even easy

**Comment by adrai** [comment]
> Anyone already use to translate responses from api?
> If yes is possible I translate parte of string, for example
> Customer name is required, and I want translate to Portuguese like customer name => nome do cliente and translate is required => é obrigatório
> 
> if possible I reuse the common parts (like is required, needs to be a string, ...)

@TutoDS Do you mean [nesting](https://www.i18next.com/translation-function/nesting) with a different namespace?
Something like this? https://codesandbox.io/s/react-i18next-forked-7wml9?file=/src/i18n.js:563-620
![image](https://user-images.githubusercontent.com/1086194/127966545-300dbf3a-7cf9-4187-af57-72988374c32b.png)

**Comment by TutoDS** [comment]
> > Anyone already use to translate responses from api?
> > If yes is possible I translate parte of string, for example
> > Customer name is required, and I want translate to Portuguese like customer name => nome do cliente and translate is required => é obrigatório
> > if possible I reuse the common parts (like is required, needs to be a string, ...)
> 
> @TutoDS Do you mean [nesting](https://www.i18next.com/translation-function/nesting) with a different namespace?
> Something like this? https://codesandbox.io/s/react-i18next-forked-7wml9?file=/src/i18n.js:563-620
> ![image](https://user-images.githubusercontent.com/1086194/127966545-300dbf3a-7cf9-4187-af57-72988374c32b.png)


Yes but I receive from the api. I trie like "Customer already exists": "Cliente já existe"
Exists any better way?

**Comment by adrai** [comment]
> https://codesandbox.io/s/react-i18next-forked-7wml9?file=/src/i18n.js:563-620

@TutoDS You can also [add resources after init](https://www.i18next.com/how-to/add-or-load-translations#add-after-init), like this: https://codesandbox.io/s/react-i18next-forked-2e5w4?file=/src/i18n.js:1186-1449

**Comment by TutoDS** [comment]
> @TutoDS You can also [add resources after init](https://www.i18next.com/how-to/add-or-load-translations#add-after-init), like this: https://codesandbox.io/s/react-i18next-forked-2e5w4?file=/src/i18n.js:1186-1449
> 
> ```js
> // load translations from somewhere else...
> i18n.addResourceBundle('en', 'common', {
>   shared: "some shared translation in the common namespace"
> });
> i18n.addResourceBundle('de', 'common', {
>   shared: "einige gemeinsame Übersetzungen im gemeinsamen Namensraum"
> });
> ```

Ok but how to do on translations to api responses?
For example:

```json
"Customer created with success!": "Cliente criado com sucesso!",
```

I put the `created: "criado com sucesso"` on common?

**Comment by adrai** [comment]
> > @TutoDS You can also [add resources after init](https://www.i18next.com/how-to/add-or-load-translations#add-after-init), like this: https://codesandbox.io/s/react-i18next-forked-2e5w4?file=/src/i18n.js:1186-1449
> > ```js
> > // load translations from somewhere else...
> > i18n.addResourceBundle('en', 'common', {
> >   shared: "some shared translation in the common namespace"
> > });
> > i18n.addResourceBundle('de', 'common', {
> >   shared: "einige gemeinsame Übersetzungen im gemeinsamen Namensraum"
> > });
> > ```
> 
> Ok but how to do on translations to api responses?
> For example:
> 
> ```json
> "Customer created with success!": "Cliente criado com sucesso!",
> ```
> 
> I put the `created: "criado com sucesso"` on common?

I don't understand your question...
The translation key, in your example "created" needs to be the same for all languages, so:

```javascript
// load translations from somewhere else...
i18n.addResourceBundle('es', 'common', {
  created: "criado com sucesso"
});
i18n.addResourceBundle('en', 'common', {
  created: "created with success"
});
```

**Comment by TutoDS** [comment]
> > > @TutoDS You can also [add resources after init](https://www.i18next.com/how-to/add-or-load-translations#add-after-init), like this: https://codesandbox.io/s/react-i18next-forked-2e5w4?file=/src/i18n.js:1186-1449
> > > ```js
> > > // load translations from somewhere else...
> > > i18n.addResourceBundle('en', 'common', {
> > >   shared: "some shared translation in the common namespace"
> > > });
> > > i18n.addResourceBundle('de', 'common', {
> > >   shared: "einige gemeinsame Übersetzungen im gemeinsamen Namensraum"
> > > });
> > > ```
> > 
> > Ok but how to do on translations to api responses?
> > For example:
> > 
> > ```json
> > "Customer created with success!": "Cliente criado com sucesso!",
> > ```
> > 
> > I put the `created: "criado com sucesso"` on common?
> 
> I don't understand your question...
> The translation key, in your example "created" needs to be the same for all languages, so:
> 
> ```javascript
> // load translations from somewhere else...
> i18n.addResourceBundle('es', 'common', {
>   created: "criado com sucesso"
> });
> i18n.addResourceBundle('en', 'common', {
>   created: "created with success"
> });
> ```
> 
> 

Ok but I can't use the created key to get response of API right?

**Comment by adrai** [comment]
> Ok but I can't use the created key to get response of API right?

Sorry, but I really don't understand what you want to do...
Please create an example repository somewhere and ask at Stackoverflow or open a new issue, if you think there is an issue....
If you need to know basic usage on how i18next is used on server side, have a look at: https://dev.to/adrai/how-does-server-side-internationalization-i18n-look-like-5f4c

**Comment by TutoDS** [comment]
> > Ok but I can't use the created key to get response of API right?
> 
> Sorry, but I really don't understand what you want to do...
> Please create an example repository somewhere and ask at Stackoverflow or open a new issue, if you think there is an issue....
> If you need to know basic usage on how i18next is used on server side, have a look at: https://dev.to/adrai/how-does-server-side-internationalization-i18n-look-like-5f4c

For example, to translate this response:
<img width="460" alt="image" src="https://user-images.githubusercontent.com/18479474/128002846-1c6cc4e1-91bf-4317-8d56-0ae2e5a1eb46.png">

On my frontend I do:
<img width="600" alt="image" src="https://user-images.githubusercontent.com/18479474/128002918-a281d2f4-8f7f-4701-a119-cea88149a724.png">


Right?
Is any way to use like partials. for example translate User to Utilizador and "create successfully" to "criado com sucesso" and join in translation.

Note: I use translations that way:
<img width="490" alt="image" src="https://user-images.githubusercontent.com/18479474/128003121-4995532f-849f-423f-b019-80b085e9fa65.png">

**Comment by adrai** [comment]
@TutoDS I would use the code instead of the message, but that should work too.
Regarding the "partials", this is exactly what I tried to explain with a separate namespace and the i18next nesting functionality... https://github.com/i18next/react-i18next/issues/522#issuecomment-891561912
Please check out the docs and the example I provided...
`"This should: $t(common:shared)"`

so you could do:

```javascript
{
  en: {
    translation: {
      userCreated: "$t(common:user) $t(common:created)!"
    },
    common: {
      user: "User",
      created: "created successfully"
    }
  },
  pt: {
    translation: {
      userCreated: "$t(common:user) $t(common:created)!"
    },
    common: {
      user: "Utilizador",
      created: "criado com sucesso"
    }
  }
}
```

**Comment by TutoDS** [comment]
> @TutoDS I would use the code instead of the message, but that should work too.
> Regarding the "partials", this is exactly what I tried to explain with a separate namespace and the i18next nesting functionality... [#522 (comment)](https://github.com/i18next/react-i18next/issues/522#issuecomment-891561912)
> Please check out the docs and the example I provided...
> `"This should: $t(common:shared)"`
> 
> so you could do:
> 
> ```js
> {
>   en: {
>     translation: {
>       userCreated: "$t(common:user) $t(common:created)!"
>     },
>     common: {
>       user: "User",
>       created: "created successfully"
>     }
>   },
>   pt: {
>     translation: {
>       userCreated: "$t(common:user) $t(common:created)!"
>     },
>     common: {
>       user: "Utilizador",
>       created: "criado com sucesso"
>     }
>   }
> }
> ```
I understand the partials.
My one question is how to use that on api response,

In example I post I use the `t('...')` on axios with `data.message` and not use the key `userCreated`

**Comment by adrai** [comment]
> In example I post I use the `t('...')` on axios with `data.message` and not use the key `userCreated`

```
{
  en: {
    translation: {
      "User created successfully!": "$t(common:user) $t(common:created)!"
    },
    common: {
      user: "User",
      created: "created successfully"
    }
  },
  pt: {
    translation: {
      "User created successfully!": "$t(common:user) $t(common:created)!"
    },
    common: {
      user: "Utilizador",
      created: "criado com sucesso"
    }
  }
}
```

**Comment by jamuhl** [comment]
Like Adriano said...you can use https://www.i18next.com/translation-function/nesting

But it's a bad idea to use it in your way...because it violates one of the most important rules - don't concatenate strings - because not every language works like english
