### ISSUE TITLE
Fetching only one/two language translations based on user language

### ISSUE THREAD

**Issue by Dineshchitta** [i18next/react-i18next#525]
Hey , 

I do not want to fetch all the languages files as it will increase loading time. I have gone through [Scalability section](https://www.i18next.com/#scalability) which told about specific to namespaces.So I want to fetch a default language (en) and other language (user selected language) in the bundle. If user changes language I should fetch other language files dynamically. How could I achieve that ? 

TIA

**Comment by jamuhl** [comment]
that's the default behaviour. It only loads detected user language and fallback. Loads only namespaces defined in init options plus lazy loads the one defined in the translate hoc.

**Comment by Dineshchitta** [comment]
Hi @jamuhl Thanks for the reply. Currently I am not using any backend service to manage translations.I am maintaining in local. Previously I used to load all languages in `resources` After your reply I tried in this way
```
import i18n from 'i18next'
import { reactI18nextModule } from 'react-i18next'
import CommonDe from '../translations/de/common.json'
import CommonEn from '../translations/en/common.json'
import RevenueEn from '../translations/en/revenue.json'
import RevenueDe from '../translations/de/revenue.json'

i18n.use(reactI18nextModule).init(
  {
    fallbackLng: 'en',
    lng: 'en',
    // have a common namespace used around the full app
    ns: ['common'],
    defaultNS: 'common',
    preload: ['en'],
    resources: {
      en: {
        common: CommonEn, // 'common' is our custom namespace,
        revenue: RevenueEn
      }
    },
    debug: true,

    interpolation: {
      escapeValue: false // not needed for react!!
    },

    react: {
      wait: true
    }
  },
  (err, t) => {
    if (err) return console.log('something went wrong loading', err)
    i18n.changeLanguage('de')
    console.log('Priting revenue title :', t('revenue:title')) // -> same as i18next.t
  }
)

i18n.addResources('de', 'common', { title: 'This is German Common title' })
i18n.addResources('de', 'revenue', { title: 'This is German revenue title' })

i18n.loadLanguages(['de'], () => {
  console.log('Priting revenue title after language:', i18n.t('revenue:title'))
})

// i18n.loadNamespaces('revenue', () => {
//   /* ... */
// })

// i18n.reloadResources()

export default i18n
```

After loading language when I am printing in `console.log(revenue:title)` it is being translated to `de` language only. But In the application when I changed the language it is not being translated. Is it the correct way to do ? or am I missing something ?

**Comment by jamuhl** [comment]
That is not loading (loading is using the xhr-backend like here: https://github.com/i18next/react-i18next/blob/master/example/react_withHOC/src/i18n.js#L7)

You're bundling all translations using webpack.

**Comment by Dineshchitta** [comment]
@jamuhl  Thank you. 😄 Got it worked

**Comment by cgxdd** [comment]
> That is not loading (loading is using the xhr-backend like here: https://github.com/i18next/react-i18next/blob/master/example/react_withHOC/src/i18n.js#L7)
> 
> You're bundling all translations using webpack.

hello, Can you give me a link to an example again? I also have the need to dynamically load more than a dozen languages.   
or you have a better demo? Thanks

**Comment by adrai** [comment]
https://locize.com/blog/react-i18next/#separate

https://github.com/locize/react-i18next-example-app/tree/i18next

https://github.com/i18next/react-i18next/tree/master/example/react

https://github.com/locize/react-tutorial/tree/main/step_0

**Comment by mnvr** [comment]
For other people who come to this page looking for a way to bundle translations _lazily_ using webpack, this package by does that nicely - https://github.com/i18next/i18next-resources-to-backend. Thank you, @adrai, @jamuhl 🙏
