### ISSUE TITLE
Fix npx link for nextjs_withAppJS example

### ISSUE THREAD

**Issue by Yankovsky** [i18next/react-i18next#526]
https://github.com/i18next/react-i18next/tree/master/example/nextjs_withAppJS
here npx link is the same as in https://github.com/zeit/next.js/tree/canary/examples/with-react-i18next
but code bases are different.

**Comment by jamuhl** [comment]
?

**Comment by jamuhl** [comment]
could we get some more details what the issue is about?

**Comment by jamuhl** [comment]
done
