### ISSUE TITLE
How to use content as a key and avoid missing translation message in a console?

### ISSUE THREAD

**Issue by StenaviN** [i18next/react-i18next#527]
Let's suppose I have 'en' as a default language and use content as a key. So if I provide English translation file it will look like this:
`{
  "My cool super long sentence": "My cool super long sentence"
}`

which is boring. However I see something like 'no translation provided for en' message in console if debug is set to 'true' which is annoying.

Any way to avoid this message in a console? How to instruct i18-next that key is exact my default language?

**Comment by jamuhl** [comment]
https://www.i18next.com/principles/fallback#key-fallback hope that helps

**Comment by StenaviN** [comment]
Ah, thank you!
