### ISSUE TITLE
v8.x: initSSR() creates new bugs

### ISSUE THREAD

**Issue by olivierpascal** [i18next/react-i18next#529]
```javascript
export function initSSR(props) {
  // nextjs / SSR: getting data from next.js or other ssr stack
  if (props.initialI18nStore) {
    props.i18n.services.resourceStore.data = props.initialI18nStore;
    props.i18nOptions.wait = false; // we got all passed down already
  }
  if (props.initialLanguage) {
    props.i18n.changeLanguage(props.initialLanguage);
  }
}
```

Following #528 

1. Using `I18nextProvider` with `initialI18nStore` now implies to also pass `i18n` AND `i18nOptions`. I have to use `i18nOptions={i18n.options.react}` as a workaround. **Is it expected?**

2. Related to `props.i18nOptions.wait = false;`. In SSR, I only pass down the critical locale strings (if my page use only 10 locale strings, I won't make the client download several Mb of unused locale strings). Then I preload the used namespaces in the next pages with a client Backend. I still use `wait: true`. **We should not assume that "we got all passed down already".**

Thanks.

**Comment by jamuhl** [comment]
Not yet updated all samples - next.js one is one of them -> will need to do this later today and see if that still works as intended.

**Comment by olivierpascal** [comment]
I confirm that, from my side, everything seems to work as intended now. Thanks again!

**Comment by jamuhl** [comment]
Awesome...still will need to update all the samples and cross-check - but great to hear. If there is anything else that seems broken - just let me know...

was a rather hard ride to get that switch to new context api

**Comment by olivierpascal** [comment]
Was a good idea to increase to a major version!

**Comment by jamuhl** [comment]
yes -> most should work -> but there are a lot of edge cases i don't trust
