### ISSUE TITLE
Compile error with v8.0.6

### ISSUE THREAD

**Issue by bbuehrig** [i18next/react-i18next#531]
I got an compile error with the last version.

./node_modules/react-i18next/dist/es/withNamespaces.jsModule not found: Can't resolve '@babel/runtime/helpers/getPrototypeOf' in '~/myReactApp/node_modules/react-i18next/dist/es'

**Comment by jamuhl** [comment]
looks like npm did not install dependencies proper. try deleting node_modules and doing npm i again

**Comment by bbuehrig** [comment]
You are right. It was a faulty react version!

**Comment by jamuhl** [comment]
glad it was solved - closing this again.
