### ISSUE TITLE
getWrappedInstance() broken in ^8.0.0

### ISSUE THREAD

**Issue by Kovensky** [i18next/react-i18next#534]
The documentation in the README specifies that you need to call `getWrappedInstance()` twice; however, neither of the new building blocks used internally by `withNamespaces` (`withI18n`, which in turn uses `withContext`) implement `getWrappedInstance()`. Even if they did, this would have required 3 chained calls of `getWrappedInstance()`, not 2.

A better approach would probably be to drop the `withRef` system entirely and have an `innerRef` prop that is forwarded as `ref` in the HOC's `render()`.

**Comment by jamuhl** [comment]
fully agree had no time yet to search for a solution...but yes...calling getWrappedInstance is no longer an options (out of the reasons you mention).

So if i get your approach right - just passing in a innnerRef function as prop and use that on the ref in rendering

**Comment by Kovensky** [comment]
Yeah, it doesn't even have to be a function; react 16.3+'s createRef object should do to.

It's similar to the approach taken by styled-components/emotion.

**Comment by jamuhl** [comment]
ok...will need to check that...

**Comment by Kovensky** [comment]
Even better would be `forwardRef` but that would require React 16.4+ and at least react-redux had some performance concerns about it: https://github.com/facebook/react/issues/13456

**Comment by jamuhl** [comment]
seems you know a lot more about refs then me 💪i just try to avoid them personally

**Comment by jamuhl** [comment]
landed in react-i18next@8.0.7

**Comment by jamuhl** [comment]
@Kovensky should be in react-i18next@8.0.8
