### ISSUE TITLE
NextJs example flickers on page load

### ISSUE THREAD

**Issue by isaachinman** [i18next/react-i18next#535]
I seem to have great timing - I'm just now looking for a localisation solution for NextJs and see you've updated the examples here within the past 24hrs.

However, knowing personally how hard localisation can be with SSR, I downloaded the `react-i18next/example/nextjs` dir, and did `yarn && yarn build && yarn start`.

If you then open `localhost:3000`, you'll see the page loads, then flashes white, then loads again.

Not sure exactly what's happening here, but the example can't be taken seriously in its present state.

**Update:** If I remove `NamespacesConsumer` from `_app.js` and render `<Component {...pageProps} />` directly, the flicker stops. So the problem lies somewhere therein.

**Further update:** If I swap the order of your `i18n` prop pipe on `NamespacesConsumer`, the flicker stops:

> i18n={i18n || (pageProps && pageProps.i18n)}

However, the flicker seems to stop because the initial render just isn't happening. In other words, the page simply remains white until the second render happens. This is not really a fix as it seems to negate SSR. I've noticed that `pageProps.i18n` is `null` on my clientside render, whereas it's a full object on my serverside render.

It would be great to get a response on this as soon as the maintainers are able.

**Comment by jamuhl** [comment]
retry now...just fixed the problem in _app.js: https://github.com/i18next/react-i18next/commit/c456a57a3504b2c0a9a5c1cf7eeebb21b074550e

**Comment by isaachinman** [comment]
@jamuhl Wow, thanks for a lightening fast response.

That does indeed seem to fix it. I had a feeling it was related to this `wait` prop. What are the implications of disabling `wait`?

Also just a small thing, it might be more helpful to specifically pass the necessary props into `NamespacesConsumer` rather than anonymously spreading them in, as this is an example after all.

**Comment by isaachinman** [comment]
Also if you don't mind, it would be useful to understand how one would dynamically change the locale clientside in this setup.

**Comment by jamuhl** [comment]
yes...like you said i18n and ssr is hard - so it is to create a sample that is still readable...will try to improve (but honestly currently i need a step back - worked to hard to get v8 of react-i18next out and adjusting all samples -> which was not so hard because of v8 of react-i18next but all other frameworks like next.js evolving too)

so the wait option would only assert namespaces get loaded (xhr) before rendering...not sure but i guess we could set that to process.browser -> means true for client side. The main issue was not passing in initialI18nStore and initialLanguage from props -> which pass down the serverside loaded translations -> so the client does not have to load them initial (just loads others depending on need when doing clientside navigation with additional translation files needed.)

**Comment by jamuhl** [comment]
setting language on client side would be like: https://github.com/i18next/react-i18next/blob/master/example/react/src/App.js#L39

**Comment by jamuhl** [comment]
if you're in the mood, you might improve the sample (when choosing to go for react-i18next) would help a lot - personally i do not use nextjs - so i'm very unsure what should make a great sample

**Comment by isaachinman** [comment]
Okay, got it. Thank you for your fast help on this. It's very likely that I'll begin development on a production NextJs/react-i18next application soon. I would certainly be willing to put together a PR for the NextJs example here.

I get what you mean about third-party frameworks evolving and having to support them in examples... Thank you for all your work on this, `react-i18next` is a great lib, I used it back in 2016 and still think it is a better option than `react-intl`.

**Comment by isaachinman** [comment]
Hey @jamuhl one other question (which is very important) - did you look into localised routes with this setup? I would expect:

    /contact-us            => English
    /de/contact-us       => German

And so on, where the Express server automatically generates localised routes and changes the locale as needed. I see that (i18next-express-middleware)[https://github.com/i18next/i18next-express-middleware] seems to do this out of the box and is already being used in the project. Any ideas?

**Comment by jamuhl** [comment]
yes...i18next-express-middleware has the option build in...the point i'm not sure is how the clientside router takes this up. I know others did this already but never gone the step to implement this in the sample -> might add some additional complexity making understanding it even harder...

Not sure - but if you like to invest time it would be great if you could share your experience doing so.
