### ISSUE TITLE
this.setState / callBack's

### ISSUE THREAD

**Issue by HaJo10** [i18next/react-i18next#540]
Hi,
I struggle where to extend the screenProps to have a place where I can handle my callBack's e.g. have "this" is defined, so I can use this.setState.
Tried it in the WrappedStack where the screenProps are set to use "t". I am able to define e.g. 
this.state = {items: []} and even fill in some default values. 
But adding a new item via a callBack like onSubmit fales at this.setState. So it does not work as it would without using i18next.

I could not find any sample where there is more than pure navigation with using react-i18next. 

Can you give me a hint???

**Comment by jamuhl** [comment]
Sorry...guess i do not fully understand the question. screenProps, handle callbacks?!?

🤔sounds like next.js - but how does the question relate to an issue with react-i18next?

**Comment by HaJo10** [comment]
Ok, it might not be an issue. More question. If this is the wrong place to ask, tell me where to go, please.
I think there must be any sample using both, navigation and react-i18next AND handling some data.

Using navigation only, the way to deal with my data (e-g- items) would be like in the code snippet below. I tried a long time to combine this with react-i18next. When I move it into the WrappedStack, items are put through the navigation and translation works well.
But I am not able to handle the callBack's like "refresh" in the sample down here. The reason is, that "this" is not fixed in WrappedStack.


export default class App extends Component {
  state = { items: [ some date here] };

  _deleteItem(item) {
    let { items } = this.state;
    const index = items.findIndex(i => i.date === item.date);
    items.splice(index, 1);
    this.setState({ items: items });
    Store.saveItems(items);
  }

  render() {
    return (
      <AppNavigator
        screenProps={{
          items: this.state.items,
          refresh: this._refreshItems,
        }}
      />
    );
  }
}

**Comment by jamuhl** [comment]
what is WrappedStack...? this must be bound to the this it needs to be...if App than App...if AppNavigator than there - but in the end the method belongs to some class where it access this.state ... so it should be bound to that class in its constructor

**Comment by HaJo10** [comment]
WrappedStack from your sample react-i18next-expo.

I have to think about your answer. Actual no idea how to manage the binding, I am to much a newbe to js. But some googling "binding" might help. Thanks so far, feeling I waste your time. Sorry for that.

// Wrapping a stack with translation hoc asserts we get new render on language change
// the hoc is set to only trigger rerender on languageChanged
const WrappedStack = ({ t }) => <Stack screenProps={{ t }} />;
const ReloadAppOnLanguageChange = withNamespaces('common', {
  bindI18n: 'languageChanged',
  bindStore: false,
})(WrappedStack);

// The entry point using a react navigation stack navigation
// gets wrapped by the I18nextProvider enabling using translations
// https://github.com/i18next/react-i18next#i18nextprovider
export default class App extends React.Component {
  render() {
    return <ReloadAppOnLanguageChange />;
  }
}

**Comment by jamuhl** [comment]
The problem you have is that `WrappedStack` is a pure functional component. You can convert it to a class to have constructor, ...

```js
class WrappedStack extends Component {
  // constructor, state and other statics

  render() {
    const { t } = this.props;
    return <Stack screenProps={{ t }} />
  }
}


```

**Comment by HaJo10** [comment]
Wow, its that easy, if one knows HOW TO !!! You DO, me not. Much to learn so far.
Thank You !!!

**Comment by jamuhl** [comment]
you're welcome
