### ISSUE TITLE
i18next, changeLanguage client side bug.

### ISSUE THREAD

**Issue by FeklistovGleb** [i18next/react-i18next#541]
When im use i18m.changeLanguage('en',(lng, fb) => {}) on client side, ljcalization switch and cookies not change, cookies still 'i18next=ru-RU'. This is bug or im not understand how its work?

**Comment by jamuhl** [comment]
did you set caches to add cookies?

**Comment by jamuhl** [comment]
at least it works like expected here: https://jsfiddle.net/hdvkfbua/

**Comment by FeklistovGleb** [comment]
Thanks, fine works!
