### ISSUE TITLE
Don't use Context.Provider inside NamespacesConsumer

### ISSUE THREAD

**Issue by Dremora** [i18next/react-i18next#542]
It seems that every usage of `NamespacesConsumer` creates another instance of Provider:

![image](https://user-images.githubusercontent.com/242202/46744731-aa146900-cca3-11e8-96ad-4ce826ba2827.png)

However, the same is already happening up the component hierarchy:

![image](https://user-images.githubusercontent.com/242202/46744764-b993b200-cca3-11e8-9e44-e8c37705ae54.png)

Consumers shouldn't be creating their own providers but simply accessing existing ones from the component hierarchy. It all works right now but seems like an overkill. The component hierarchy becomes also harder to inspect in the React developer tools, especially when there are multiple nested instances of `NamespaceConsumer`.

**Comment by jamuhl** [comment]
It's a shared Context for i18n...just I18nextProvider adds only i18n - while the hoc or render prop do both add i18n and t.

If there is no reason to use I18nextProvider - i wouldn't use it at all.

Yes...the new context api (which in my opinion is no context api - but just a render prop) adds a lot of useless components to the hierarchy - even more as at some point you need to decorate your components with a hoc to get stuff from consumer via props into your component. not a fan of it...but that's the way to go...not much i can do for your hierarchy inspection...sorry for that.

Just try to use the hoc, render prop where needed passing down `t` from container components to inner pure components -> no need to decorate every small component.

**Comment by Dremora** [comment]
We don't use any HOCs in our app for various reasons, one of them is that they don't work well with the flow types. There should be no reason to use HOCs at all, anything is perfectly doable with render props (and more). The React ecosystem is moving away from them, only keeping them as legacy API.

Context API is not “just” a render prop — it uses render prop pattern to propagate values through the component hierarchy and apply updates to the tree more efficiently when these values change.

I would put `t` in the context at the `i18nextProvider` level, so there'd be no need to re-create the context provider. In most cases one provider for a context type is enough. What is happening here seems like an anti-pattern to me.

**Comment by Dremora** [comment]
Also, removing `I18nextProvider` would lead to abusing React context where it's actually not required at all. I suggest going through the [official documentation](https://reactjs.org/docs/context.html) to understand how the context works and what problem it's meant to be solving.

**Comment by Dremora** [comment]
I had a brief look at the codebase and I think this would be quite a major undertaking. The main issue—something I've mentioned before in our Twitter conversation—is that there are too many ways and options to achieve the same thing.

Here, `NamespacesConsumer` is both context consumer and provider. If it was to just become a context consumer, it should not be accepting `i18n`, `initialI18nStore`, `initialLanguage`,`defaultNS` and probably anything else (there are properties which I simply don't understand) apart from `ns` and `wait`. These properties should be exclusive to `I18nextProvider`.

**Comment by jamuhl** [comment]
Like said...i18next might not be the simplest solution - but the most flexible. Personally, I would remove the I18nextProvider -> it's only needed if you need multiple i18n instances (huge apps sometimes have that demand).

The consumer needs initialI18nStore, initialLanguage -> the I18nextProvider is not used eg. in the next.js example....

**Comment by jamuhl** [comment]
Closing this for now - while agree simplification would be great not everything works like you would expect....eg. you can't say i18n, initialI18nStore, initialLanguage, defaultNS should only be in the Provider -> see the next.js sample...that's not the way it works.

closing this for now - not want to make your points not valid...but there are tradeoffs. Evtl. it would be awesome to have something like react-i18next-simple ... ?!?

**Comment by jamuhl** [comment]
@Dremora react hooks might come to the rescue: https://react.i18next.com/experimental/using-with-hooks

code a lot simpler: https://github.com/i18next/react-i18next/tree/master/src/hooks
