### ISSUE TITLE
withNamespaces is not a function

### ISSUE THREAD

**Issue by pimjansen** [i18next/react-i18next#544]
Im trying to migrate to the latest version (8.0.7) and start using the HOC inside my component. The things is that i have a library which contains all my UI kit elements. Over there we have some default labels as well that ofcourse also need to be multilanguage. 

When running all this within storybook it all runs fine but when i install it via npm and then consume these elements i get this error:
`caught TypeError: (0 , _reactI18next.withNamespaces) is not a function`

The main application ofcourse also uses translations so maybe that can be related? 

```
import i18n from 'i18next';
import { reactI18nextModule } from 'react-i18next';
import XHR from 'i18next-xhr-backend';
import LanguageDetector from 'i18next-browser-languagedetector';

i18n
  .use(XHR)
  .use(LanguageDetector)
  .use(reactI18nextModule)
  .init({
    load: 'languageOnly',
    backend: {
      loadPath: '../dist/locales/{{lng}}/{{ns}}.json'
    },
    fallbackLng: {
      'en-US': ['en']
    },
    ns: ['uielements'],
    defaultNS: 'uielements',
    fallbackNS: 'uielements',
    debug: false,
    keySeparator: '##',
    interpolation: {
      escapeValue: false // not needed for react!!
    },
    react: {
      wait: true,
      bindI18n: 'languageChanged loaded',
      bindStore: 'added removed',
      nsMode: 'default'
    }
  });

export default i18n;
```

And the component:
`export default withNamespaces()(Dialog);`

**Comment by jamuhl** [comment]
so this worked before - using 7.x.x??! If so i guess it's only a issue with npm not installing dependencies proper...=> removing node_modules and doing a fresh `npm i` should solve it in that case

**Comment by pimjansen** [comment]
> so this worked before - using 7.x.x??!
Yes but then i did not use the HOC withNamespaces which is only available frmo 8+

**Comment by jamuhl** [comment]
but you used the translate hoc?

**Comment by pimjansen** [comment]
The old version used the provider:
`<I18n ns={['uielements']}>`

But this will get a big messy when translations happen outside of render methods and such. Like inline error message that show up. But i will retry to build it from scratch later today to review that first.

Could also be the case that it has a different instance of `i18n`? The lib will be rendered with Babel but it will still load its own instance internally.

**Comment by jamuhl** [comment]
`I18n` render prop -> that was renamed to `NamespacesConsumer`

Shouldn't be an issue having multiple react-i18next -> as long those get passed an i18n instance all should be ok...my bet really is a bugged npm install -> sounds like withNamespaces is undefined which would mean there is still an old react-i18next used somewhere

**Comment by jamuhl** [comment]
What is it if not a function? can you check it's type?

**Comment by pimjansen** [comment]
> What is it if not a function? can you check it's type?

I will first have a chat with our dev team internally if we maybe can restructure some stuff as well. Since at this point all translations are bundled and shipped with the library where i'd rather have only 1 i18n instance instead. Maybe this also conflicts here

**Comment by jamuhl** [comment]
Ok....would be great if you could keep me updated - if there is an issue it would be nice to know.

**Comment by pimjansen** [comment]
Im getting close but i now hit this:

```
utils.js:10 react-i18next:: deprecation warning -> I18n was renamed to "NamespacesConsumer" to make it more clear what the render prop does.
I18n.js:42 Uncaught TypeError: Cannot read property 'options' of undefined
at new I18n (I18n.js:42)
at constructClassInstance (react-dom.development.js:11448)
at updateClassComponent (react-dom.development.js:13145)
```

No idea where it is coming from though. The setup is where i have an app which implements 8.x and a sub library which is having its own namespace and renders it internally that uses 7.x

Any ideas?

**Comment by jamuhl** [comment]
do you set i18n via I18nextProvider or i18next.use(reactI18nextModule)

**Comment by pimjansen** [comment]
Yes the settings are same as mentioned in first post in this thread

**Comment by jamuhl** [comment]
would need to review your code....but at some place it's seems to be related to mismatched version between your visual lib and main lib resulting in two versions of react-i18next luring around -> where 7.x not compatible with 8.x --> upgrade both or neither

**Comment by pimjansen** [comment]
@jamuhl yeah i tried that and in fact the translations are showing up however in dom i keep seeing these errors showing up. tReady is not something we implemented so maybe you can confirm where this comes from?

Warning: React does not recognize the `tReady` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `tready` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div
    in Ref
    in div
    in Ref
    in PortalInner
    in Portal
    in Modal
    in Dialog
    in NamespacesConsumerComponent
    in WithMergedOptions
    in WithContext
    in LoadNamespace
    in WithMergedOptions
    in LoadNamespace(Dialog) (at Results.jsx:145)
    in div (at Results.jsx:127)
    in div (at Results.jsx:118)
    in Results (created by NamespacesConsumerComponent)
    in NamespacesConsumerComponent (created by WithMergedOptions)
    in WithMergedOptions
    in WithContext (created by LoadNamespace)
    in LoadNamespace (created by WithMergedOptions)
    in WithMergedOptions
    in LoadNamespace(Results) (at Serviceability.jsx:271)
    in Serviceability (created by NamespacesConsumerComponent)
    in NamespacesConsumerComponent (created by WithMergedOptions)
    in WithMergedOptions
    in WithContext (created by LoadNamespace)
    in LoadNamespace (created by WithMergedOptions)
    in WithMergedOptions
    in LoadNamespace(Serviceability) (at index.jsx:84)
    in div (at Navbar.jsx:84)
    in div (at Navbar.jsx:62)
    in Navbar (created by NamespacesConsumerComponent)
    in NamespacesConsumerComponent (created by WithMergedOptions)
    in WithMergedOptions
    in WithContext (created by LoadNamespace)
    in LoadNamespace (created by WithMergedOptions)
    in WithMergedOptions
    in LoadNamespace(Navbar) (at index.jsx:78)
    in ConfigProvider (at index.jsx:68)
    in NavbarComponent (at index.jsx:102)
    in I18nextProvider (at index.jsx:101)

**Comment by pimjansen** [comment]
@jamuhl Thanks a lot! didnt knew this was the actual problem. For now i will keep 2 instances of i18next as well so i can just ship the library to contain everything. Keeping the libs in sync is indeed a problem but that is overall just a versioning thing

**Comment by jadbox** [comment]
Not working with typescript because there's no type definition for withNamespaces.

**Comment by jamuhl** [comment]
@jadbox https://github.com/i18next/react-i18next/issues/331
