### ISSUE TITLE
How to get the default system language?

### ISSUE THREAD

**Issue by THPubs** [i18next/react-i18next#546]
I used the `i18next-browser-languagedetector`. But my app won't detect the default system language. Currently, the system is set to Swedish. But it loads english by default. Any idea how to fix it?

**Comment by jamuhl** [comment]
system language? of you mac/pc? it has no access to that....only to the set browser language -> you want to use it for electron - if so there is an extra detector for that

**Comment by THPubs** [comment]
I just installed the Swedish firefox browser and now it works! Thanks @jamuhl
