### ISSUE TITLE
Link on text content

### ISSUE THREAD

**Issue by cassio-nuke** [i18next/react-i18next#551]
Hi guys,

First of all: Thanks for your amazing work!

I'd like to introduce a link inside my translated text. HTML example:
```
[...]
  "text_two": "Go to <a href='//google.com.br'>Google Portuguese</a>"
[...]
```

How could I do something similar in RN?
Do you have a direction to point me? I'm very newbie in i18n.

Thanks in advance

**Comment by cassio-nuke** [comment]
Hi Jan, 

Thanks for your answer.

My example was bad, but my situation is that I have a huge text with links inside it.

Here's my layout:
![image](https://user-images.githubusercontent.com/43763300/47084936-6e215c80-d1eb-11e8-94b4-11d55e05604a.png)

The best approach is to cut this text into many parts?

**Comment by jamuhl** [comment]
Not cutting it...use the Trans component: https://react.i18next.com/components/trans-component#sample

In that sample replace the Link with whatever is right for your RN link component.

**Comment by cassio-nuke** [comment]
That is exactly what I was looking for. Thank you!

**Comment by MareoRaft** [comment]
Both of the links in this answer are broken.  Could you post the solution here inline?

**Comment by jamuhl** [comment]
@MareoRaft https://react.i18next.com/latest/trans-component#samples

**Comment by sidharrth2002** [comment]
Won't you just end up with a hard-coded english translation here by using the Trans component?

**Comment by jamuhl** [comment]
@sidharrth2002 did you try it out? what would be the sense to create that component if it does not work for translating?!?
