### ISSUE TITLE
Too many re-renders on language change

### ISSUE THREAD

**Issue by Tobbe** [i18next/react-i18next#553]
I'm writing my first react app with translations, and only have a single component that does any translations this far.

Changing language causes 19 re-renders of that component.

```
11:36:37.371 logger.js:23 i18next: languageChanged en
11:37:35.508 Cms.jsx:120 re-render
11:37:35.511 Cms.jsx:120 re-render
11:37:35.515 Cms.jsx:120 re-render
11:37:35.520 Cms.jsx:120 re-render
11:37:35.523 Cms.jsx:120 re-render
11:37:35.528 Cms.jsx:120 re-render
11:37:35.533 Cms.jsx:120 re-render
11:37:35.537 Cms.jsx:120 re-render
11:37:35.540 Cms.jsx:120 re-render
11:37:35.544 Cms.jsx:120 re-render
11:37:35.547 Cms.jsx:120 re-render
11:37:35.549 Cms.jsx:120 re-render
11:37:35.551 Cms.jsx:120 re-render
11:37:35.554 Cms.jsx:120 re-render
11:37:35.557 Cms.jsx:120 re-render
11:37:35.559 Cms.jsx:120 re-render
11:37:35.562 Cms.jsx:120 re-render
11:37:35.565 Cms.jsx:120 re-render
11:37:35.568 Cms.jsx:120 re-render
11:37:35.569 logger.js:23 i18next: languageChanged se
```

This is my config

```
i18n
    .use(reactI18nextModule)
    .init({
        resources: {
            se: {
                translation: {
                    ...
                },
            },
            en: {
                translation: {
                    ...
                },
            },
        },
        lng: 'se',
        fallbackLng: 'se',
        interpolation: {
            escapeValue: false,
        },
        react: {
            wait: true,
            bindStore: false,
        },
        debug: true,
    });
```

My component is a `React.PureComponent`.

What can I do to get fewer re-renders?

**Comment by jamuhl** [comment]
Can you make your sample public so i can check? i do not get this on the https://github.com/i18next/react-i18next/tree/master/example/react when having set (bindStore: false like you did)

**Comment by jamuhl** [comment]
even you pass in translations by options.resources -> so there should be no loading at all.

**Comment by Tobbe** [comment]
> Can you make your sample public so i can check?

Unfortunately not. It's a huge project, and it's not opensource...

> even you pass in translations by options.resources -> so there should be no loading at all and therefor no rerender.

Not sure I understand. Sorry my English isn't the best... But for now I have hard-coded translations in the options object that I pass to `init()`. I just replaced them with `...` for the issue report.

**Comment by jamuhl** [comment]
passing in those translations (not loading by xhr-backend) means there is nothing like `loaded` events so the only thing triggering a rerender would be the `languageChanged` event.

So the only thing i could guess going on here is the `Cms.jsx` is nested deep in the component tree having multiple withNamespaces() there - so there are multiple levels in the tree triggering a rerender based on the updated language.

So either i would set `bindI18n: false` for components deeper in the tree to not trigger rerender on languageChanged (as most outer pageLevel / container component already does) or pass down `t` from container component to inner.

**Comment by Tobbe** [comment]
Thanks for your help. Seems to be something else that causes all of the rerendering. 

I'm currently passing the translated value on to a `<ContentEditable>` component (https://github.com/lovasoa/react-contenteditable).

If I change that to just directly output the translated text (i.e. remove `<ContentEditable>`), then I only get one rerender.

**Comment by jamuhl** [comment]
hm...odd...please keep me updated if there is something we could change to make it.

**Comment by Tobbe** [comment]
I think I've figured it out. Doesn't seem to be a problem with this project. I had several Cms component instances, but only a couple of them had translations enabled. But they still all got rerendered. That's why I got so many "rerending" console logs.  I didn't think of all the extra Cms component instances that I hadn't added translations to yet...

Thanks for helping me debugging :)

**Comment by sagarCS** [comment]
> or use the https://react.i18next.com/components/withi18n for inner components deeper in the tree were you do not need rerenders triggered...

The link you provided is not working.........And i want some knowledge on what happen on languageChange like what things get Rerender or is there a way we can do changeLanguage without rerendering if possible?

**Comment by adrai** [comment]
withI18n is for v9/v8 version: https://react.i18next.com/legacy-v9/withi18n
for newer versions have a look at: https://react.i18next.com/latest/withtranslation-hoc or similar

rerender events, have a look at bindI18n: https://react.i18next.com/latest/i18next-instance

**Comment by sagarCS** [comment]
> So either i would set `bindI18n: false` for components deeper in the tree to not trigger rerender on languageChanged (as most outer pageLevel / container component already does) or pass down `t` from container component to inner.

Can you be more specific about the bindl18n: false, where i should provide this in init config 
whether it should be inside:
```react: {
      wait: true,
      bindStore: false,
      bindl18n: false
    }
```
or somewhere else?

**Comment by sagarCS** [comment]
So correct me if i am wrong, 
When we change the language i18next instance will reRender all the Components which are using the translation methods (like withtranslation, t method etc) once on everyChange right?

**Comment by jamuhl** [comment]
using just `t` - nope. Using a HOC, hook whatever...yes

**Comment by sagarCS** [comment]
I have a React class component and I used only `t` method everywhere for translation(for function and class based component also) will it rerender the component on language change?

**Comment by jamuhl** [comment]
`t` only returns a string...how should it magically update your react component? That's why the HOC exists...

**Comment by adrai** [comment]
If you wrapped your component with the HOC and are using the according t function it will rerender

**Comment by sagarCS** [comment]
Can you provide an example on github or codesandbox for both case?...I will try some tweaks to get some more insights on it

**Comment by sagarCS** [comment]
> If you wrapped your component with the HOC and are using the according t function it will rerender

export default (withTranslation()(Roles))
You mean like this?

**Comment by jamuhl** [comment]
yes...just look at the examples...https://github.com/i18next/react-i18next/tree/master/example/v9.x.x/react

**Comment by sagarCS** [comment]
So that mean all the  component where I have used the translation method  wheather its class or functional it has to Render once so that DOM gets update with selected language(i.e  on languageChange)
right?

**Comment by ranshemt** [comment]
I had a similar problem. I'm using i18n with redux, and a custom form of persist-gate.

When the PersistGate component finishes its work it renders the AppProvider which creates the redux store.
The issue was that when I changed language it caused a rerender of the PersistGate, because i18n instance is configured by default to rerender in the event 'changeLangauge'.
**The solution:** Initialize i18n instance with the option `bindI18n: false`. I'm also using only functional components and not using suspense, so using the hook `useTranslation` gives me the updated language without causing a rerender of the PersistGate.

While the source of the issue may be related to my custom PersistGate and how it works, I felt it was important to share in any case someone experiences similar issues.
