### ISSUE TITLE
NextJS issue after changing locale

### ISSUE THREAD

**Issue by revskill10** [i18next/react-i18next#554]
In latest NextJS example, after changing locale, and refresh browser, there're two issues:
- The locale keeps using old locale before switching to new locale. 
- There's a mismatch between server content (using old locale) and the client content (using new locale)

Note: If I set `enableSubpath` to `false`, the second issue disappear, but the first one keeps using old locale before switching to new locale.

**Comment by revskill10** [comment]
@jamuhl  Ah, the issue is invalid because it requires you to use cookie caching if you want to reuse lang when switching.

**Comment by jamuhl** [comment]
hm, what do you think...should we enable that in the sample? i guess others will not easily find that cookies need to be enabled to get that back to serverside?

**Comment by revskill10** [comment]
@jamuhl I found the solution in one of closed issues about caching with cookies. 
But for newscomers who wants everything just works out of the box, i think we should enable it.
Do you want me to make a PR ?

**Comment by jamuhl** [comment]
agree...a PR would be awesome...would save me some time....👍
