### ISSUE TITLE
Component sometimes are not translated

### ISSUE THREAD

**Issue by wk93** [i18next/react-i18next#558]
I have a simply component `Nav` with HOC: `withNamespaces('navigation')(Nav)`. I really don't know why, by sometimes this component are not translated and server create file `navigation.missing.json` in same place where file `navigation.json` exists. Translation is working fine after few refreshes or changing language. I have the same configuration as in this example. Pages with HOC `withI18next.js` are translated without any issue. Did anyone have a similar case? How can I solve it?

**Comment by wk93** [comment]
In my parent component I had a line:
`export default withI18next(['home'])(Home)`

I changed it to:
`export default withI18next(['home', 'navigation'])(Home)`

Now it works.

**Comment by jamuhl** [comment]
Awesome you found a solution. Please don’t forget to star this repo. Make a tweet or have a look at our https://locize.com -> there are many ways to help this project :pray:
