### ISSUE TITLE
HOCs need to be explicitly typed

### ISSUE THREAD

**Issue by nmenke** [i18next/react-i18next#562]
Hi,

i have updated to the newest version of react-i18next today. I have noticed that the repository now contains typings. So for example the following definition:

```
export function withNamespaces(
  namespace?: string,
  options?: WithNamespacesOptions,
): <P extends object>(
  component: React.ComponentType<P & WithNamespaces>,
) => React.ComponentType<P>;
```

With this definition i need to say `withNamespaces("default")<Props>(component)`. Otherwise the compiler complains for missing Props like tReady.

```
type Omit<T, K> = Pick<T, Exclude<keyof T, K>>;
type Subtract<T, K> = Omit<T, keyof K>;

export function withNamespaces(
  namespace?: string,
  options?: WithNamespacesOptions,
): <P extends WithNamespaces>(
  component: React.ComponentType<P>,
) => React.ComponentType<Subtract<P, WithNamespaces>>;
```

This definition removes those types supplied by the HOC and you can use following statement: `withNamespaces("default")(component)` without compiler errors. It would be great if those typings would be used for every HOC.

**Comment by schettino** [comment]
PR coming. @jamuhl want to patch the changes right away or give it sometime to see if something else comes up in this initial phase and then release the possible changes all at once?

**Comment by jamuhl** [comment]
@schettino i added you as contributor with write access - feel free to merge in changes as needed - and ping me if there is a state we should publish again...

**Comment by schettino** [comment]
@jamuhl sounds good, thanks
