### ISSUE TITLE
Am I not allowed to add HTML tags in {t('key')} ?

### ISSUE THREAD

**Issue by ffan0811** [i18next/react-i18next#566]
There are 3 ways to translate in React If I understand the document right.
1. Using the HOC (which I'm not using)
2. Using the render prop
3. Using the Trans component

I get how to use the Trans component especially when I want to add HTML tags in the component.

However, I don't know how to do that with using the render prop. am I not allowed to with this way?
If there is a way to use the render prop, please give me some examples.
I heard It is also dangerous to add HTML tags? can you please tell the reason...

Thank you.

**Comment by jamuhl** [comment]
As you see the render props is just a child that is a function -> you define the content inside -> that is just like a hoc but used inside the render function of your component. You can use inside components like you need. You can inside use the t function as is or the Trans compoent.

The Trans component is a way to keep translation together: https://react.i18next.com/guides/step-by-step-guide#5-translate-jxs-nodes-as-one-string

HTML tags is not dangerous...what you have in mind is having something like a translation `hi <strong>formatting</strong>` which does not work -> react escapes content passed as string - so to make that translation render a formatted html you would need to use dangerouslySetInnerHtml or whatever that is called.

**Comment by ffan0811** [comment]
Thank you for your perfect reply. :)
