### ISSUE TITLE
Property 'ns' does not exist on NamespacesConsumer type

### ISSUE THREAD

**Issue by jchu231** [i18next/react-i18next#568]
I have just updated to v8.1.0 to get your typescript defs, however I am running into this error:
```
TS2339: Property 'ns' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<NamespacesConsumerProps, ComponentState,...'.
```

This is caused by something like:
```
return(
  <NamespacesConsumer ns={[ 'translation', 'common' ]}>
  {( t: any, {i18n}: any ) => (
    <div>
      {t( 'common:dviText' )}
    </div>
  )}
  </NamespacesConsumer>
);
```
I am fairly new to Typescript, but is this syntax expected to be supported by the Typescript definitions? It is the syntax used in the react-i18next docs.

**Comment by schettino** [comment]
You're right, it hasn't been listed on the props, I missed it

**Comment by schettino** [comment]
btw, you don't need to use `any` in `{( t: any, {i18n}: any ) => (`

just make sure you have added @types/i18next

**Comment by jchu231** [comment]
@schettino Thanks for the tip!
