### ISSUE TITLE
nextjs example - PageNames, SEO and Auto-detect lang

### ISSUE THREAD

**Issue by ITforHome** [i18next/react-i18next#570]
thank you for the nextjs-example, i follow up this and it works now. But i have few more questions about that... 

## 1. Different Names for Pages

How can i use different names for my Pages. For Example, i have a page called `privacy-policy` i can open this page like this:

`http://localhost:3000/en/privacy-policy
http://localhost:3000/de/privacy-policy` 

When i use German as Language, i want to display the PageName in German, in my case:

`http://localhost:3000/de/datenschutz`

How can i do that? 

## 2. SEO

I use the `next/head` Component to implemente SEO in my Application. How can i use it with `i18next`? There are disadvantages of this method?

## 3. Auto-detect Lang

When i open the `index.js`page on `http://localhost:3000` i get `http://localhost:3000` as URL, no matter if german oder english. But when i open the `index.js` page in german, i want to get this URL: `http://localhost:3000/de` or in english: `http://localhost:3000/en`

How can i do that?
Please show me a short detail example, so i can use it in my Code - thanks a lot...

**Comment by jamuhl** [comment]
@isaachinman not sure if you got some ideas for this?

**Comment by isaachinman** [comment]
1. That's outside the scope of the example. If you want different route names, create different routes in the normal NextJs way.
2. Did you have a specific question? The `next/head` component is a normal React component and can be localised in the same manner. There are no disadvantages, as this is fully SSR-friendly.
3. Your title says "auto detect lang", but the contents of your question seem to indicate a bug. Please clarify. Language detection is handled automatically by `i18next-browser-languagedetector` and is configurable via the options of that lib.

**Comment by jamuhl** [comment]
👍agree with @isaachinman 

for 1) i think really it is out of scope for the sample but looking at the sample how lng get added to route and on client side https://github.com/i18next/react-i18next/blob/master/example/nextjs/lib/languagePathCorrection.js

you might come up with a solution having translated routes and correct them back to real path...but this is really out of scope for here.

If you come up with a solution you might share your solution in a gist or similar...but like @isaachinman  points out the sample should not get any more complicate as it already has some steep learning curve

**Comment by ITforHome** [comment]
@jamuhl @isaachinman thanks for your answers, i unterstand our position. 

for 2) i can say, that the next/head-component work fine with i18next... 👍
for 3) do you think this could be a bug, if a enabled subpathes and i don‘t see it in the URL when i try to open `http://localhost:3000` What can i do that, in this case?

**Comment by isaachinman** [comment]
Hi @ITforHome. For the first question, you are better off posting on StackOverflow, making sure you tag NextJs. Someone from their side should be able to help you.

@jamuhl's point about `languagePathCorrection` is a good one, and you could indeed localise routes, but it seems like you should get a grasp on NextJs in general before approaching more advanced usage like that.

Can you explain your third point further? I don't entirely understand it. If you're seeing multiple languages on the exact same route with `enableSubpaths` set to `true`, that sounds like a bug.

**Comment by isaachinman** [comment]
@ITforHome Do you have any update for us on your third point? Otherwise, we'll close this issue.

**Comment by ITforHome** [comment]
@isaachinman
i haven‘t any updates about this. You can close the issue.
