### ISSUE TITLE
TypeError: Cannot read property 'ready' of null

### ISSUE THREAD

**Issue by sagarguhe** [i18next/react-i18next#572]
I am trying to follow this [example](https://github.com/i18next/react-i18next/tree/master/example/reactnative-expo) but getting this error:

react-i18next: `^8.1.0`
i18next: `^12.0.0`
react-native: `^0.57.0`

This is a code snippet from my `App.tsx`:

```

const WrappedAppNavigator = ({ t }) => <AppNavigator screenProps={{ t }} />;
const ReloadAppOnLanguageChange = withNamespaces('translation', {
	bindI18n: 'languageChanged',
	bindStore: false,
})(WrappedAppNavigator);

export default class App extends Component<Props, State> {

    render() {

        if (this.state.isLoading) {
	    return (
		<View style={styles.container}>
			<Text>Loading ...</Text>
		</View>
	    );
	}

        return (
            <Provider store={this.state.store}> {/*import { Provider } from 'react-redux';*/}
                <Root> {/* native-base */}
	            <ReloadAppOnLanguageChange screenProps={{ notifService: this.notifService, store: this.state.store }} />
                </Root>
           </Provider>
        );
    }
}
```

```
TypeError: Cannot read property 'ready' of null

This error is located at:
    in NamespacesConsumerComponent (created by WithMergedOptions)
    in WithMergedOptions (created by Context.Consumer)
    in WithContext (created by LoadNamespace)
    in LoadNamespace (created by WithMergedOptions)
    in WithMergedOptions (created by Context.Consumer)
    in LoadNamespace(WrappedAppNavigator) (at App.tsx:68)
    in RCTView (at View.js:44)
    in Root (at connectStyle.js:384)
    in Styled(Root) (at App.tsx:66)
    in Provider (at App.tsx:65)
    in App (at renderApplication.js:34)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in AppContainer (at renderApplication.js:33)

NamespacesConsumerComponent.render
    NamespacesConsumer.js:201:29
finishClassComponent
    ReactNativeRenderer-dev.js:10563:30
updateClassComponent
    ReactNativeRenderer-dev.js:10504:9
beginWork
    ReactNativeRenderer-dev.js:11337:13
performUnitOfWork
    ReactNativeRenderer-dev.js:14091:11
workLoop
    ReactNativeRenderer-dev.js:14129:23
renderRoot
    ReactNativeRenderer-dev.js:14226:6
performWorkOnRoot
    ReactNativeRenderer-dev.js:15193:6
performWork
    ReactNativeRenderer-dev.js:15090:6
performSyncWork
    ReactNativeRenderer-dev.js:15047:2
```

**Comment by jamuhl** [comment]
not what i asked....

but yes....must not be the root level -> can be wrapped inside other Providers.

can you paste your i18n.js

**Comment by jamuhl** [comment]
and the line in code where the error is

**Comment by sagarguhe** [comment]
> but the sample provided as is works?

**Comment by sagarguhe** [comment]
> not what i asked....
> 
> but yes....must not be the root level -> can be wrapped inside other Providers.
> 
> can you paste your i18n.js

Sorry I didn't read correctly. I have not tested that example app. let me do it I will get back to you...

**Comment by sagarguhe** [comment]
Here is the code from: `i18n/index.tsx`

```
import i18n from 'i18next';
import { reactI18nextModule } from 'react-i18next';

i18n
    .use(reactI18nextModule)
    .init({
        fallbackLng: 'en',
        resources: {
            'en-US': {
                translation: {
                    "title": "title" 
                }
            },
            'nl-BE': {
                translation: {
                    "title": "title" 
                }
            }
        },

        // have a common namespace used around the full app
        ns: ['common'],
        defaultNS: 'common',

        debug: true,

        interpolation: {
            escapeValue: false, // not needed for react as it does escape per default to prevent xss!
        }
    });


export default i18n;
```

**Comment by jamuhl** [comment]
hm...my first guess the export would be no real i18n instance so breaking the stuff...but using reactI18nextModule should result in correct results anyway.

Can you give me the code position throwing that error?

**Comment by sagarguhe** [comment]
the line at which I am calling this component `ReloadAppOnLanguageChange`. If I remove this and use original unwraped `AppNavigator` then the app works fine but if used wrapped component then failing.

**Comment by jamuhl** [comment]
`const WrappedAppNavigator = ({ t }) => <AppNavigator screenProps={{ t }} />;`

And:

`<ReloadAppOnLanguageChange screenProps={{ notifService: this.notifService, store: this.state.store }} />`

Guess you need to merge the screenProps!

**Comment by sagarguhe** [comment]
How do I merge screen props? Wrapped Component is defined outside of App Component?

**Comment by sagarguhe** [comment]
vscode showing error here: `bindI18n: 'languageChanged',` at this line.

<img width="724" alt="screen shot 2018-10-24 at 5 41 26 pm" src="https://user-images.githubusercontent.com/8309157/47429543-567e4100-d7b4-11e8-91d2-e450643ca4ab.png">

**Comment by jamuhl** [comment]
const WrappedAppNavigator = ({ t, screenProps }) => <AppNavigator screenProps={{ ...screenProps, t }} />;

**Comment by sagarguhe** [comment]
I will try to reproduce the issue and post the snack here..

**Comment by sagarguhe** [comment]
@jamuhl hmm, wrapping `<ReloadAppOnLanguageChange />` inside `<I18nextProvider i18n={i18n}> .... </..>` worked. I think I18next was trying to call `window.ready()` method which is really not available on react native so causing this error. Wrapping inside `<I18nextProvider/>` provider solved the problem. I am testing if translations are working or not will update you after that.

**Comment by sagarguhe** [comment]
Perfect! all the translations and language change events are working, But the issue is when I don't wrap `WrappedComponent` indide `I18nextProvider`  don't know why this is causing issue on `react-native-cli` app.

**Comment by jamuhl** [comment]
hm...there is a window.ready() call in i18next? new to me...but if it works for you...i'm happy 👍

And don’t forget to star this repo. Make a tweet or have a look at our https://locize.com -> there are many ways to help this project :pray:
