### ISSUE TITLE
Change default language by page

### ISSUE THREAD

**Issue by KingWu** [i18next/react-i18next#576]
i am new for using nextjs.

For my site, each user contains his language. For the nextjs example, i found that i has auto language detection. 

If the user login, the site use the user's language.
If the user does not login, the site auto detech the language.

How can i setup this feature?
Thanks

**Comment by jamuhl** [comment]
see:

https://github.com/i18next/i18next-express-middleware#language-detection -> for serverside

https://github.com/i18next/i18next-browser-languageDetector -> for clientside

**Comment by jamuhl** [comment]
sample has them built in: https://github.com/i18next/react-i18next/tree/master/example/nextjs

**Comment by KingWu** [comment]
if the user language is not match the language in cookie or session, how can I change language in slience?

**Comment by jamuhl** [comment]
Hm...i'm rather sure it's in the docs.

There is the i18n.changeLanguage or better adding a custom_detector for detecting it. Custom detection is described in the above links.

**Comment by KingWu** [comment]
Thanks. i change the language on componentDidMount in _app.js

i try to move all locales into other folder called 'assets'. i changed all path.
But, found the following issue.

ajax.js:71 GET http://localhost:3000/assets/locales/en/common.json 404 (Not Found)

any idea?

**Comment by jamuhl** [comment]
did you change that: https://github.com/i18next/react-i18next/blob/master/example/nextjs/server.js#L70 to assets/locales -> to make that folder hosted

**Comment by KingWu** [comment]
I changed server.js but still go to 404 error page

```
// serve locales for client
server.use('/assets/locales', express.static(path.join(__dirname, '/assets/locales')));

// missing keys
server.post('/assets/locales/add/:lng/:ns', i18nextMiddleware.missingKeyHandler(i18n));
```

**Comment by jamuhl** [comment]
And don’t forget to star this repo. Make a tweet or have a look at our https://locize.com -> there are many ways to help this project :pray:
