### ISSUE TITLE
Allow to define a fallback value in Trans for cases not getting a translation

### ISSUE THREAD

**Issue by jamuhl** [i18next/react-i18next#577]
Details: https://github.com/i18next/react-i18next/pull/462

**Comment by brodeynewman** [comment]
We use this project at work and we think it would be cool to be able to pass a prop into the `Trans` component as the fallback value. Is this what you're thinking? 

If so, i'd like to go ahead and knock this out.

**Comment by jamuhl** [comment]
or just apply https://github.com/i18next/react-i18next/pull/462/files#diff-e2b8d52a3ffb2c5b61049216c69ff761R108 should not be to harmful adding that on major v9 as final

**Comment by jamuhl** [comment]
@brodeynewman or props `defaults` -> https://github.com/i18next/react-i18next/blob/master/test/trans.render.spec.js#L356

**Comment by jamuhl** [comment]
published in react-i18next@9.0.0

allow defining `transEmptyNodeValue` in i18next.options.react to set a default fallback value
