### ISSUE TITLE
Bug with dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by ITforHome** [i18next/react-i18next#578]
Hi, 
thank you with `react-i18next`, but i have a problem with the `dangerouslySetInnerHTML`-prop...
For Example, inside my `common.json` file, i have this data:

```json
{
    "Text": "This is a text with a <a href='/example' target='_blank'>Link</a>"
}
```

Inside a page, i use this `common`-file like this:

```js
<p dangerouslySetInnerHTML={{ __html: t('Text', { interpolation: { escapeValue: false } }) }} />
```

When the page first loads... i see the text in the right language. If a reload the page again, the text will be shown in the default/fallback-language... How can i solve the issue?

**Comment by jamuhl** [comment]
nextjs?

how do you load the first time / second? what is the difference?

**Comment by ITforHome** [comment]
@jamuhl yes, i use nextjs

At the first time, i use the `npm run dev` script to load my Site/App, or what do you mean?
The Differences:

FirstLoad:
i get the german text

SecondLoad:
I get the english text (Fallback Language)

**Comment by jamuhl** [comment]
is it only that element or all wrong?

can't reproduce this on the sample provided here

**Comment by ITforHome** [comment]
@jamuhl only that element...

please take a look at: https://drive.google.com/file/d/15RoOJHojUTVaaI2sqV6ATz_MO1hSASCP/view?usp=sharing

**Comment by jamuhl** [comment]
hm...

which t function you're using...same as on the other elements?
do you get some missing in debug log on the second load...

what is the real key name? not "Text" i guess...very strange...looks like on second load that translation is not loaded - only explanation i got right now...else would be great to get a sample to reproduce....

**Comment by ITforHome** [comment]
@jamuhl on the other elements i use this t-function:

```jsx
<Paragraph>{t('The-legitimate.text')}</Paragraph>
```
note: I use a `Paragraph` Component, because i use a UI-Framework in my App... But I also get the error with a normal<p>Tag

The real keyname is `Existence.2Text`

And i found another bug in Footer...

My`common.js` looks like this:

```json
// /locales/de
{
   "Footer": "Das ist mein Footer-Text"
}

// /locales/en
{
   "Footer": "This is my Footer-Text"
}
```

In my `Footer-Component` i use it like this:

```jsx
<p dangerouslySetInnerHTML={{__html: t('Footer', {interpolation: {escapeValue: true}})}} />
```
but i always get the german Footer-Text... On the English-Page i get only the "Key" -> so in my case "Footer" where is the mistake...?

**Comment by jamuhl** [comment]
you're files are not named right

guess defaultNS is set to 'common'

it tries to load common.json in folder /locales/{lng} and Footer should be there...

how you're defining the hocs - just withNamespaces() ?!?

the question was is the t function passed via prop? what are you using to pass it in...

please show complete code

**Comment by ITforHome** [comment]
@jamuhl thanks for your help. Here is my complete Footer Component Code for example:

```jsx
import React, { Component } from "react";
import { Paragraph } from 'evergreen-ui'
import { withI18next } from '../../../translation/withI18next';
import '../../../css/Footer.css';
import logo from '../../../static/images/formally_logo_white.svg?inline';

class Footer extends Component {

    render() {
        const { t } = this.props
        return (
            <footer className="PageFooter bg-dark">
                <div className="PageFooter-inner FooterContainer">
                    <div className="PageFooter-left">
                        <object data={logo} type="image/svg+xml" height="auto" width={120} />
                    </div>
                    <div className="PageFooter-right">
                        <Paragraph dangerouslySetInnerHTML={{__html: t('Footer', {interpolation: {escapeValue: true}})}} />
                    </div>
                </div>
            </footer>
        );
    }
}
export default withI18next(['common'])(Footer);
```

**Comment by jamuhl** [comment]
Please be aware that in components not being pages you should use `withNamespaces` not `withI18next` hoc. The withI18next hoc does a lot to much - which is only needed on page level -> like setting initial language and the initial translations - might be the cause.

so do you have translation files `/locales/{lng}/common.json` ? having Footer key?

**Comment by ITforHome** [comment]
@jamuhl OK i found help... My Footer Component looks like this now:

```jsx
import React, { Component } from "react";
import { Paragraph } from 'evergreen-ui'
import { withNamespaces } from 'react-i18next';
import '../../../css/Footer.css';
import logo from '../../../static/images/formally_logo_white.svg?inline';

class Footer extends Component {

    render() {
        const { t } = this.props
        return (
            <footer className="PageFooter bg-dark">
                <div className="PageFooter-inner FooterContainer">
                    <div className="PageFooter-left">
                        <object data={logo} type="image/svg+xml" height="auto" width={120} />
                    </div>
                    <div className="PageFooter-right">
                        <Paragraph dangerouslySetInnerHTML={{__html: t('Footer', {interpolation: {escapeValue: true}})}} />
                    </div>
                </div>
            </footer>
        );
    }
}
export default withNamespaces('common')(Footer);
```
But i get the error:

`
Cannot read property 'ready' of null
`
What does it mean?

**Comment by jamuhl** [comment]
hm...only access to ready is here in render...would mean this.state is undefined...strange

**Comment by ITforHome** [comment]
@jamuhl My app is running again... I had completely forgotten to make the adjustments in the `_app. js`. However, some texts are no longer displayed to me. How can I add more files to the `ns`-prop?:

```jsx
<NamespacesConsumer
          {...pageProps}
          ns="common, privacy-policy, seo, next-steps" //this not be worked
          i18n={(pageProps && pageProps.i18n) || i18n}
          wait={process.browser}
        >
....
</NamespacesConsumer>

**Comment by jamuhl** [comment]
must be an array: `ns={['common', 'privacy-policy', 'seo', 'next-steps']}`

**Comment by ITforHome** [comment]
@jamuhl many thanks for your help and your time... 👍Always looks good now, also the Footer Text 😉

**Comment by jamuhl** [comment]
hope this gets not annoying, but need to get more attention to react-i18next so devs get aware there is some good alternative to react-intl ;)

--> don’t forget to star this repo. Make a tweet or have a look at our https://locize.com -> there are many ways to help this project :pray:
