### ISSUE TITLE
How to use content as key with : character?

### ISSUE THREAD

**Issue by hoang-rio** [i18next/react-i18next#579]
I use content as key with config `keySeparator: false, // we use content as keys` but when content pass to function `t` it will display text after : character.

Example `t('text before: text after')` will display `text after ` and it don't care i18n resources config.

**Comment by jamuhl** [comment]
reason the `:` you will have to also set nsSeparator to false or something different

**Comment by hoang-rio** [comment]
> reason the `:` you will have to also set nsSeparator to false or something different

Thanks. It worked!

**Comment by jamuhl** [comment]
And don’t forget to star this repo. Make a tweet or have a look at our https://locize.com -> there are many ways to help this project :pray:
