### ISSUE TITLE
Module parse failed: After changing the dirctory structure 

### ISSUE THREAD

**Issue by shakesBeardZ** [i18next/react-i18next#582]
After I changed the directory structure in the next Exmple I've got this wierd Error 
![image](https://user-images.githubusercontent.com/15571628/47560402-644cd700-d918-11e8-8510-0fb6b5f5c312.png)

![image](https://user-images.githubusercontent.com/15571628/47560412-6b73e500-d918-11e8-9813-fce559eff801.png)

**Comment by jamuhl** [comment]
Is this an issue with react-i18next?

**Comment by shakesBeardZ** [comment]
yeah I think so

**Comment by jamuhl** [comment]
hm...the sample works you break it - and it's our problem 😱

don't get me wrong - an issue is if something is defect with the module - not with your code

**Comment by jamuhl** [comment]
obviously...has to do with `loader` looks like some jsx issue -> hm -> related to webpack -> related to next.js build script?!? expecting entry points in pages...idk

**Comment by jamuhl** [comment]
@shakesBeardZ that is what stackoverflow is there for ... really issues are here to fix issues in the modules. OSS consumers really should stop expecting maintainers to also work through endless userland code to fix issues in their code - this honestly is one of the main reasons that many maintainers burn out.

But i understand your frustration and looking for help is not wrong - just see the relations - how many hours i work for free fixing all those unrelated issues.

**Comment by jamuhl** [comment]
@shakesBeardZ really guess default setting in next.js is `/pages` for entry points: https://github.com/zeit/next.js/blob/canary/packages/next/build/webpack.js#L150

=> there for sure is an option to override that - but that is related to next.js not react-i18next

**Comment by shakesBeardZ** [comment]
@jamuhl  thanks for understanding

**Comment by jamuhl** [comment]
And don’t forget to star this repo. Make a tweet or have a look at our https://locize.com -> there are many ways to help this project :pray:
