### ISSUE TITLE
`withI18n` breaks static members

### ISSUE THREAD

**Issue by ghengeveld** [i18next/react-i18next#583]
An example demonstrates this best:

```js
import React from "react"
import { withI18n } from "react-i18next"

class Demo extends React.Component {
  static foo = "bar"
  render() {
    return <div />
  }
}

Demo.Member = () => <div />

console.log(Object.keys(Demo))             // => ["foo", "Member"]
console.log(Object.keys(withI18n()(Demo))) // => []
```

This essentially breaks access to static members of the wrapped component, which is often used to expose compound components.

I discovered this when using I18next with [React Async](https://github.com/ghengeveld/react-async), which uses compound components.

**Comment by ghengeveld** [comment]
What you probably need to do is hoist non-react statics: https://github.com/mridgway/hoist-non-react-statics

See also: https://reactjs.org/docs/higher-order-components.html#static-methods-must-be-copied-over

**Comment by jamuhl** [comment]
done for `withNamespaces` https://github.com/i18next/react-i18next/blob/master/src/withNamespaces.js#L56

feel free to provide a PR doing the same for `withI18n`

**Comment by ghengeveld** [comment]
I'm writing a PR. Hold on.

**Comment by ghengeveld** [comment]
Fixed it 👍
