### ISSUE TITLE
Errors in nextJS sample

### ISSUE THREAD

**Issue by shakesBeardZ** [i18next/react-i18next#587]
I recently built my website based on the sample of nextJS but I was getting errors in the console, at first I thought it was an error in my code until I figured out that actually it does exist also in the sample

![image](https://user-images.githubusercontent.com/15571628/47609753-3d3ff380-da45-11e8-8652-922e000934e7.png)

so could anyone explain why or propose a fix for it.

**Comment by jamuhl** [comment]
closing this in favour of the other issue
