### ISSUE TITLE
Comply with react strict mode

### ISSUE THREAD

**Issue by JimmyLaurent** [i18next/react-i18next#594]
React strict mode complains about the use of "componentWillReceiveProps" in "I18nextProvider".

Can we can replace it with "getDerivedStateFromProps" as suggested by the warnings ?

Thanks

**Comment by jamuhl** [comment]
Sure...are you open for a PR? Else i will add the change in the next version. Guess not to urgent to get patched.

**Comment by JimmyLaurent** [comment]
Done.

I had to mirror the i18n prop in the state, though.

And you're right, it's not urgent.

**Comment by jamuhl** [comment]
Thank you...will take a look later today

**Comment by jamuhl** [comment]
should be solved with 022b9aa

published on npm in react-i18next@8.3.6

If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
