### ISSUE TITLE
Mid/Long term contributors

### ISSUE THREAD

**Issue by jamuhl** [i18next/react-i18next#595]
What's the best way to give you some kudos?

@isaachinman @schettino you both helped a lot in the last weeks be it with nextjs or typescript. I highly appreciate the time you put into this and the load you take from me.

I would love to give you both write access to the repo (@schettino i guess i gave that already to you) and somehow mention you as official contributors.

Do you have any ideas?

- Adding you to the package.json
- Adding some section in the readme?
- Adding a section in the documentation?

**Comment by isaachinman** [comment]
That is very thoughtful of you! I suppose write access and a section in the README/docs is the best way to integrate someone, generally speaking. I don't think anyone actually reads package.json's! Maybe add a contributors section to the README if you feel the urge? The [nuxt](https://github.com/nuxt/nuxt.js) team seems to do a good job of crediting contributors and core members.

**Comment by jamuhl** [comment]
https://github.com/i18next/react-i18next#contributors added that section

@isaachinman you got now write access to this repo

hm...seems the contributors (PR) list is based on open collective tooling

**Comment by shakesBeardZ** [comment]
@jamuhl  @isaachinman  @schettino thanks a looooooooooooooot guys, you are the best, your contributions helped me a lot.

**Comment by isaachinman** [comment]
@jamuhl Ah yeah, I have seem Locize. It seems like a nice service. For compensation, it's not terribly important to me, but you can email me directly about it if you want.

**Comment by isaachinman** [comment]
@jamuhl Check out this project:

https://github.com/kentcdodds/all-contributors

**Comment by jamuhl** [comment]
added core contributor section in readme few days ago

**Comment by isaachinman** [comment]
Ah, I didn't see that. Nice!
