### ISSUE TITLE
Add issue templates?

### ISSUE THREAD

**Issue by isaachinman** [i18next/react-i18next#601]
Hi @jamuhl - since I'm now subscribed to all notifications in this repo, I've noticed that a lot (perhaps even the majority) of issues opened are basic usage kind of questions which probably belong on StackOverflow, not here.

You are very kind to answer these questions, but what do you think about creating some issue templates to discourage people from posting "how to" questions in issues, and also to (hopefully) structure issue format a bit better?

**Comment by jamuhl** [comment]
The variations of might be a lack in our documentation / provided samples to we need to teach basic javascript is rather big. While i don't want discourage to much of asking questions i'm all in for templates just already to get more structured issues - where we do not loose time to guess around what the code might look like ;)

**Comment by isaachinman** [comment]
Okay, I would propose at the very least:

1. Bug report
2. Feature request

Any other issue types you would like? Any repos you want to take inspiration from?

**Comment by jamuhl** [comment]
Never looked into it - i would say go for something that makes sense from your experience - we still could change it later if we see something should be added to the template.

**Comment by isaachinman** [comment]
@jamuhl Add three templates with #606. I'm not sure if it's even possible to demo them in branches that are not `master`. Once they're on `master` though, you can hit the New Issue button and see their effect.

**Comment by jamuhl** [comment]
awesome...merged and checked...good stuff 👍
