### ISSUE TITLE
About subpath

### ISSUE THREAD

**Issue by revskill10** [i18next/react-i18next#607]
**Problem**
I have seen many usage pattern on using lang on route, most of sites i know use `lng` as a query parameter , instead of subpath.

Current (for example) nextjs sample handles subpath in a very weird way, which leads to the code smell everywhere in the i18n related codebase.

**Suggestion**
Removing usage of subpath, and using query parameter instead.

**Comment by isaachinman** [comment]
@jamuhl With the number of these issues opened, we might want to consider a full rewrite of the NextJs example.

@revskill10 You're saying we have a problem of being too opinionated, and then proposing an opinionated "solution". 

> nextjs sample handles subpath in a very weird way

We're handling localised URLs in an industry standard way. If you want to handle lang via a query param, go ahead. If you want to share that approach with others, feel free create an example. That's not something @jamuhl or I am going to spend time on.

**Comment by jamuhl** [comment]
@isaachinman hm...next.js is really a huge topic...not saying time sink...not sure why it feels like a never ending story....not sure react-i18next is to complex with the loading translations instead of just adding them as resources like other i18n libs do - which avoids all the load complexity.

I would love to provide a sample that works...but always seems like it gets broken faster with custom changes / wishes / needs...

**Comment by jamuhl** [comment]
To keep it positive...next.js and i18n seems to be a hot topic - but as we both now...neither SSR nor i18n is as simple as one might think upfront.

**Comment by revskill10** [comment]
My experience with this library is this:
- Before subpath is enabled in the recent release, i use `I18NextProvider` , at that time, things work with a very simple code (and easy to hack/extend/understand).
- After adding `subpath`, things turn into a mess. I got issues and trying to resolve it. But i don't test about subpath because i don't use it.
The library shouldn't be opinionated (at least in sample) , and should be open for all users to hack themselves as simplest as possible.

**Comment by isaachinman** [comment]
Yup. I also wrote my feelings [here](https://github.com/i18next/react-i18next/issues/597#issuecomment-435622907). I am travelling through Monday, but I think the best thing to do (now that we don't have any glaring bugs) is to take a step back and look at a potential rewrite.

I appreciate hearing your opinion @revskill10. Perhaps it really is the case that we should remove that logic completely.

Even if we do, we still need to solve current issues relating to `initialLanguage`, and handling SSR in a sane way.

Certainly removing language subpaths removes almost all custom server complexity.

@jamuhl Shall we open a fresh issue to discuss the direction of the NextJs example? It's a "good problem" that it's getting a lot of attention, I suppose.

**Comment by isaachinman** [comment]
@revskill10 Just curious, is the language subpath a feature you would want if you felt it was stable/reliable?

**Comment by revskill10** [comment]
@isaachinman What i really want ( and other users, too), is a simple way to toggle feature, for example like caching, subpath, or queryString.
I think refactoring the API is a first step to clean out things to adapt more features in future.

**Comment by isaachinman** [comment]
Yes, I can understand that point of view. However, it's important to keep in mind that this is an _example_, not a boilerplate/starter kit, and the primary goal is to show users how they might _hypothetically_ integrate `react-i18next` and `nextjs`.

With a bunch of feature toggles, the codebase starts to become unapproachable, and very confusing to newcomers. Especially people who do not have previous experience doing server side NextJs development - the distinction between a custom server file, `_app.js`, `_document.js`, and `getInitialProps` can be very confusing.

We can continue discussing in a standalone issue.
