### ISSUE TITLE
v8 NamespacesConsumer breaks SSR

### ISSUE THREAD

**Issue by isaachinman** [i18next/react-i18next#610]
**Describe the bug**
I believe that the `NamespacesConsumer` component released in v8 breaks React SSR, and that this has something to do with the nested context providers/consumers.

**Occurs in react-i18next version**
v8.0.6

**To Reproduce**
Steps to reproduce the behaviour:
1. Clone demo repo [here](https://github.com/isaachinman/react-i18next-with-nextjs)
2. Do `yarn && yarn dev`
3. Open `localhost:3000` in a browser, with the console open
4. Observe flicker in render due to broken SSR, and warning in console

You can also do a perf recording in the Chrome dev tools to take a closer look at the white flash that happens due to the broken SSR. The console warning that appears will be something like this:

    Warning: Did not expect server HTML to contain a <button> in <div>.

This is a very cryptic error (as mentioned in @jamuhl's original code for the NextJs example), but ultimately can be traced back to `warnForDeletedHydratableElement`.

I compared the HTML returned by the initial doc request to the resulting HTML after clientside render, and found no difference. This leads me to believe the SSR breakage has something to do with context:

<img width="540" alt="screenshot 2018-11-05 at 19 35 44" src="https://user-images.githubusercontent.com/10575782/48041426-026b4900-e132-11e8-9b95-d3cb1cb0c7a4.png">

I have no idea why the component tree would look like this in the first place.

Crucially, if you remove _just_ the HOC in `components/LocaleSwitcher` in my given example, the error will go away and SSR will not be broken - no more flicker / clientside re-render. This `withNamespaces` HOC is coming directly from `react-i18next` core.

I'm not sure if this bug is contained to just NextJs SSR, or React SSR in general. Is there a working vanilla React SSR example somewhere? I looked but could not find one.

**Expected behaviour**
Built-in components from `react-i18next` should not break SSR.

**OS (please complete the following information):**
 - Device: MBP 2018 13
 - Browser: Chrome 70.0.3538.77

**Additional context**
This bug is currently blocking #609. @jamuhl It would be fantastic if you can take a look at this as soon as possible. I hope it is an easy fix, but I'm not really sure where to start in terms of debugging.

**Comment by isaachinman** [comment]
Possibly related:

https://github.com/zeit/next.js/issues/4194

**Comment by isaachinman** [comment]
Context was actual a complete red herring, I believe this was user error on my part.

**Comment by jamuhl** [comment]
@isaachinman that warning `Warning: Did not expect server HTML to contain a <button> in <div>.` was solved at some point...but seems some changes reintroduced it. Will hopefully find time tomorrow to dig into it.
