### ISSUE TITLE
withNamespaces won't load namespaces on SSR?

### ISSUE THREAD

**Issue by eilonmore** [i18next/react-i18next#614]
New namespaces that weren't initialized with i18next.init, won't be loaded on SSR using withNamespaces HOC?

Suppose I'm not able to pre-load the namespaces that are relevant to the current page (i'm not using react-router "match" function, thus can't use "loadNamespaces"),
how can I load the matched namespaces while rendering on server?

From a brief look on NamespacesConsumer, it seems that loadNamespaces will be called only on componentDidMount (which won't be called on server side rendering).

Any ideas?

**Comment by isaachinman** [comment]
Hi @eilonmore, have you seen our [NextJs example](https://github.com/i18next/react-i18next/tree/master/example/nextjs)? This might give you an idea of how to achieve what you want.

Specifically, take a look [here](https://github.com/i18next/react-i18next/blob/master/example/nextjs/pages/_app.js#L80). We're pushing necessary namespaces for a given React tree into an array, and then doing a `Promise.all` to fetch them all when hitting a new route.

If you're doing this without NextJs, you'll need to render your React tree somehow (eg `renderToString`) to compile your array of namespace dependencies, then `await` your fetching process, and finally render down that string.

In general, this type of question is so vague that it doesn't even belong on StackOverflow, but rather possibly Reddit or some dev Slack group. If you need further help you can email me directly, or post on one of those groups.

**Comment by jamuhl** [comment]
@eilonmore overall you should not load on server...all should be preloaded. Remember you're on the server...loading it once and for all users does not hurt.
