### ISSUE TITLE
Multiple languages in one component ?

### ISSUE THREAD

**Issue by revskill10** [i18next/react-i18next#621]
# Question about react-i18next

Is there api for us to use multiple language in one component ?

In my case, i'd like to show tooltip in another language when user hover on original text (in another language).

**Comment by jamuhl** [comment]
if you have loaded the other language by: https://www.i18next.com/overview/api#loadlanguages

you can either create a: https://www.i18next.com/overview/api#getfixedt

or call `i18next.t('key', { lng: 'the language you like' });`

**Comment by jamuhl** [comment]
closing this for now - guess this question is solved.

If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
