### ISSUE TITLE
hooks typings

### ISSUE THREAD

**Issue by alexolefirenko** [i18next/react-i18next#622]
The package does not have typings for hooks
reproduces in v8.3.8

```ts
import { useT } from 'react-i18next/hooks'
```
I catch an error

```Could not find a declaration file for module 'react-i18next/hooks'. '{project}/node_modules/react-i18next/hooks.js' implicitly has an 'any' type.
  Try `npm install @types/react-i18next` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-i18next/hooks';`
```
typings are already installed

Do you plan to support typings?

**Comment by isaachinman** [comment]
Hi @alexolefirenko. Not sure your level of involvement/awareness, but perhaps it's better to write your feedback in #591. In general, `react-i18next` does aim to fully support Typescript.

**Comment by jamuhl** [comment]
@alexolefirenko hooks version will be released in v10 - as hooks are not yet released in react. Typescript will be added before releasing that.

**Comment by alexolefirenko** [comment]
@isaachinman Thanks I'll check.
@jamuhl Understood, I just thought that typings have been lost or something else... alright, I'm waiting for release :)
