### ISSUE TITLE
Strings not being translated

### ISSUE THREAD

**Issue by falcon03** [i18next/react-i18next#625]
I have a pretty complex react-native app that wasn't designed with i18n in mind and I need to localize it to a couple of languages. I've tried using i18next+react-i18next to accomplish the goal, but I'm having an issue: strings are not being translated. According to the documentation it looks like I'm doing things the proper way, so I don't understand what's going wrong; could you help me please?

Here's the i18next configuration I put in index.js:
```javascript
import i18next from 'i18next';
import { reactI18nextModule } from 'react-i18next';
import RNLanguages from 'react-native-languages';
// some i18next unrelated code
i18next
.use(reactI18nextModule)
.init({
  debug: true,
  fallbackLng: false,
  initImmediate: false,
  keySeparator: false,
  nsSeparator: false,
  lng: RNLanguages.language,
  resources: {
    "it": require('./translations/it.json')
  }
});
// other i18next unrelated code
```

Then I try to translate strings in a component like this:
```javascript
import { withNamespaces } from 'react-i18next';
// some i18n unrelated code
export default withNamespaces()(class Welcome extends Component<{}> {
render() {
      const t = this.props.t;
// some i18n unrelated code
                <TouchableOpacity
                    accessible={true}
                    accessibilityLabel={ t('Settings') }
                    accessibilityRole='button'
                    style={styles.button}
                    onPress={() => {this.props.navigator.push({screen: 'Settings'})}}
                    >
                    <Text style={styles.baseText}>{ t('Settings') }</Text>
                </TouchableOpacity>
//some i18n unrelated code
}
});
```

And finally here's the content of translations/it.json:
```javascript
{
  "Settings": "Impostazioni"
}
```

I've already verified that the JSON gets loaded. I've enabled debug logging, but it does not help except for saying that the key is not found. Any ideas on what to look for in order to find the issue? The project uses react-native 0.57 plus a bunch of other modules.

I am using i18next 12.0.0 and react-i18next 8.3.8.

**Comment by jamuhl** [comment]
`require('./translations/it.json')` if not set namespace (learn about them: https://www.i18next.com/translation-function/essentials#accessing-keys-in-different-namespaces

Default namespace would be translation so it should be:

```js
import i18next from 'i18next';
import { reactI18nextModule } from 'react-i18next';
import RNLanguages from 'react-native-languages';
// some i18next unrelated code
i18next
.use(reactI18nextModule)
.init({
  debug: true,
  fallbackLng: false,
  initImmediate: false,
  keySeparator: false,
  nsSeparator: false,
  lng: RNLanguages.language,
  resources: {
    "it": { translation: require('./translations/it.json') }
  }
});
```

at least if your JSON is not containing that.

**Comment by isaachinman** [comment]
Are you using the `I18nextProvider` somewhere?

**Comment by falcon03** [comment]
@isaachinman no, I don't use I18nextProvider anywhere, I thought it wasn't necessary when using the hocs provided by react-i18next. Should I?

**Comment by isaachinman** [comment]
[Read the docs](https://react.i18next.com/components/i18nextprovider).

**Comment by falcon03** [comment]
@isaachinman thanks for pointing it out, but I am already using reactI18nextModule. So if I understand correctly the docs I don't need to use i18nextProvider, do I?

**Comment by isaachinman** [comment]
Not sure about RN specifically. Did you see the [example](https://github.com/i18next/react-i18next/tree/master/example/reactnative-expo)?

**Comment by jamuhl** [comment]
@falcon03 even if setting those separators to false. i18next always uses one namespace which defaults to `translation`

so best is to add that like i showed: `"it": { translation: require('./translations/it.json') }`

setting separators to false only lets you have keys containing the chars `.` and `:` -> you like to have keys that are in natural language -> key: `I would say: i18next is awesome. Agree?`

**Comment by jamuhl** [comment]
Using the I18nextProvider is not needed when you're using the `.use(reactI18nextModule)` and import that i18n.js in the index.js or app.js

**Comment by falcon03** [comment]
@jamuhl ok, thank you so much for the clarification and your help. After reading the docs I didn't understand that i18next always uses the "translation" namespace even when setting keySeparator and nsSeparator to false, I think it's a little bit anti-intuitive. :)

Anyways I agree, i18next is awesome... Especially when you understand how to make it work! :D

**Comment by ankit-akd** [comment]
I am also facing the same issue, parts of my website is also not translating. Can someone please help me with that?
