### ISSUE TITLE
not works correctly when it is bundled by webpack.

### ISSUE THREAD

**Issue by emilgpa** [i18next/react-i18next#627]
The app directly not works if I use i18next in it. I needs put it in "externals" in webpack.

**Comment by jamuhl** [comment]
Works in all our samples....could you provide a sample to reproduce?

**Comment by emilgpa** [comment]
I'm sorry. I don't have a sample to reproduce right now and I haven't time to create one. Sorry.
But I always use it with react-router. Maybe the problem is a compatibility with it.

**Comment by jamuhl** [comment]
how should using react-router be related to webpack 🤔

anyway - can't help much without a sample to reproduce this issue.

**Comment by emilgpa** [comment]
I do not understand the first sentence, what do you mean?

I refer to the connectors by HoC like this:
export default withRouter(connect(mapStateToProps, actions)(withNamespaces('translation')(App)));

**Comment by jamuhl** [comment]
your issue: The app directly not works if I use i18next in it. I needs put it in "externals" in webpack.

-> unrelated to react-router, unrelated on HOC, unrelated to everything in your code

**Comment by isaachinman** [comment]
@emilgpa

Please post implementation-specific questions on StackOverflow or elsewhere.

This repository contains an example which is meant to provide a basic guide for advanced-level users to create their own custom implementations.

If you don't want to worry about the details under the hood, feel free to install [next-i18next[(https://github.com/isaachinman/next-i18next) via npm.

**Comment by jamuhl** [comment]
i guess `import * as i18n from 'i18next'` is wrong. That is not an i18next instance and therefore can't be passed to I18nextProvider, use `import i18n from 'i18next'` guess production bundling handles that different...=> so this is only a guess and i won't invest more time into making your code work -> as isaachinman said best might be heading over to stackoverflow

**Comment by emilgpa** [comment]
In effect, it is that. Now it works. Thank you. 

The problem now is that the .d.ts of `i18next` is wrong because if I try to put `import i18n from 'i18next'` the typescript compiler fails:

```
Module '"/Users/emiliogpa/Documents/test_i18next/node_modules/@types/i18next/index"' has no default export.

1 import i18n from 'i18next';
```

I had that modify the .js directly. 
If I modify the .d.ts for making do it compatibility with default export, then the .d.ts included in react-i1next fails because it has to the imports like mine.

So, I will make a pull request to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) and when it has merged then I will another here.

**Comment by jamuhl** [comment]
@emilgpa if you're in the mood you might add a PR on the i18next repo adding typescript definitions there too: https://github.com/i18next/i18next/issues/1129

plan is to support that directly from the i18next and react-i18next repo for more straight forward typescript support.

**Comment by emilgpa** [comment]
It was just what I was thinking. I will do it. It is simply copy and paste.
