### ISSUE TITLE
Passing an object breaks the app

### ISSUE THREAD

**Issue by ddemirkhanyan-vineti** [i18next/react-i18next#632]
**Is your feature request related to a problem? Please describe.**
It's a little bit weird that the lib does not handle gracefully cases when an object is passed to the t function.

**Describe the solution you'd like**
In my understanding it would be fine if the t function would just `toString()` whatever is coming in.

**Comment by jamuhl** [comment]
why? a key needs to be a string...not an object, number,...

can you describe your need a little more?!?

**Comment by ddemirkhanyan-vineti** [comment]
@jamuhl sorry I should have probably opened this issue in the i18next repo, basically in the `Translate.js` file over there there is this check -
```
 // non valid keys handling
    if (keys === undefined || keys === null || keys === '') return '';
    if (typeof keys === 'number') keys = String(keys);
    if (typeof keys === 'string') keys = [keys];
```
however - an object also seems like a non valid key so if an object gets passed accidentally the translate function will break.

I think about opening an issue there and a pull request basically doing this
```
    // non valid keys handling
    if (keys === undefined || keys === null || keys === '' || typeof keys === 'object') return '';
    if (typeof keys === 'number') keys = String(keys);
    if (typeof keys === 'string') keys = [keys];
```
Should fix it. For me it's a valid case because I just spent an hour trying to figure out why a pretty big app broke after pulling and then it turned out that the problem was that some serialized data from the backend which used to be a string suddenly became an object. So I think a check like this will be useful to omit this headache in the future )))

**Comment by jamuhl** [comment]
Would you be able to provide a PR there or at least open the issue there too -> fully agree we should add this. 👍

**Comment by ddemirkhanyan-vineti** [comment]
@jamuhl would you be open to the idea of removing all of the if cases and just having this?
```
if(!Array.isArray(keys)) keys = [String(keys)];
```
Seems like that's pretty much what the code there is trying to achieve.

**Comment by jamuhl** [comment]
guess should be ok

**Comment by ddemirkhanyan-vineti** [comment]
Thanks for commenting so promptly! Opened the PR over here - https://github.com/i18next/i18next/pull/1143, closing this issue over here.
