### ISSUE TITLE
How to use html in translations ?

### ISSUE THREAD

**Issue by xuopled** [i18next/react-i18next#637]
# Question about react-i18next

Questions should be posted on StackOverflow

Hello, I want to translate something advanced like : 

`mykey: "During the year <1/> you have done <b>{{count, format1}}</b> something"`

I tried a lot a thing using the `<Trans />` component:
```
<Trans
            i18nKey="mykey"
            count={count}
          >During the year <select><option>2018</option><option>2017</option></select> you have done <b>{{count, format1}}</b> something</Trans>
``` 

My select is empty and option are not rendered. Count is not replaced. I don't find any documentation about advanced usage.

Could you help me ?

Thank you very much

**Comment by isaachinman** [comment]
> Questions should be posted on StackOverflow

You didn't even bother to delete this from the template before posting a question...

**Comment by isaachinman** [comment]
You also did not perform a [basic Google search](https://stackoverflow.com/questions/16038458/html-tags-in-i18next-translation).

**Comment by jamuhl** [comment]
Just using the https://codesandbox.io/s/l4qrory2nl and pasting your Trans without the {{count, **format1**}} (removing format1 as you can't pass format like that)

It works as expected...just your translation string is totally wrong (either just set debug: true and read the console output "missing" to get it or try harder to find the documentation 😃to understand how it gets build up: https://react.i18next.com/components/trans-component#how-to-get-the-correct-translation-string)

If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:

**Comment by xuopled** [comment]
I'm very sorry but I tried what you said.
<img width="1357" alt="screenshot 2018-12-05 at 17 07 09" src="https://user-images.githubusercontent.com/2683300/49526517-40ce6200-f8b0-11e8-9603-fcbc77eb71c1.png">
<img width="891" alt="screenshot 2018-12-05 at 17 06 45" src="https://user-images.githubusercontent.com/2683300/49526519-4330bc00-f8b0-11e8-9f7e-6b297dd15a2c.png">

My select is empty (no option are render), count is not interpolated and I have nothing in the console during debug

**Comment by jamuhl** [comment]
What i said: add the `Trans` component without adding the wrong translation for it `mykey: "During the year <1/> you have done <b>{{count, format1}}</b> something"` is wrong -> then look at the console output showing the missing for it

<img width="1303" alt="screenshot 2018-12-05 at 18 05 35" src="https://user-images.githubusercontent.com/977772/49530406-70816800-f8b8-11e8-8d20-7275985d101e.png">
