### ISSUE TITLE
The use t(key, options) via the Hoc withNamespaces does not work with i18next-scanner

### ISSUE THREAD

**Issue by djemalmohamed** [i18next/react-i18next#639]
Hello,

When using the translation function via the hoc withNamespaces and without passing the option {ns: 'ns'}, ex:

considering that default ns : common and:

```
...
t('key');
...
export default withNamespaces('otherNS')(MyComponent);
```

the i18next-scanner does not put scanned translations into the specified ns output file. all translations were added to the default namespace output file.

**Comment by jamuhl** [comment]
Not related to react-i18next...ask for a fix at the i18next-scanner repo.
