### ISSUE TITLE
How i declare a proptypes of i18n

### ISSUE THREAD

**Issue by feJustino** [i18next/react-i18next#640]
I would like to know how to declare the "Proptype" of this object (i18Next)

**Comment by jamuhl** [comment]
what?

**Comment by jamuhl** [comment]
https://react.i18next.com/components/overview#components

**Comment by Kostanos** [comment]
Hi, looking for the same. 
I managed to define it like:
```
MyComponent.propTypes = {
  t: PropTypes.func.isRequired,
};
```
But I wonder, if there is simplest way to do it, as, now I need to put this definition for every Component that uses translation.

**Comment by jamuhl** [comment]
For what...? Do this type declarations have a sense today...I never specify those...but seems I miss some added value they bring?

**Comment by Kostanos** [comment]
Oh man, agree with you, but some times in shared projects you can't go without them

**Comment by jamuhl** [comment]
Ok...guess this is the only way to declare them like you did
