### ISSUE TITLE
How to use different JSON file and setup i18n.js file?

### ISSUE THREAD

**Issue by JavierPons** [i18next/react-i18next#643]
# Question about react-i18next

Questions should be posted on StackOverflow

**Comment by JavierPons** [comment]
Hi there, 
I want to use different languages translation .json files. I saw a post with same issue but the solution link is dead. Could be possible to re-link for understand how it is possible to implement? Thanks!

**Comment by isaachinman** [comment]
Can you explain exactly what you mean, perhaps by example?

**Comment by JavierPons** [comment]
Sure!  I have a json file within three languages translation inside. The translation will increase. So I thought the possibility to use three different json lang for each of my translation. How can I do ? How to transform the i18n.js file or others. I have this ==>
`import i18n from 'i18next'
import locales from '../resources/locales.json'
i18n.init(
  {
    lng: 'fi',
    fallbackLng: 'fi',
    debug: true,

    interpolation: {
      escapeValue: false
    },

    resources: locales,

    react: {
      wait: false,
      bindI18n: 'languageChanged loaded',
      bindStore: 'added removed',
      nsMode: 'default'
    }
  },
  err => {
    console.error(err)
  }
)

export default i18n`

**Comment by isaachinman** [comment]
As far as I know, you'll need to restructure your data.

Perhaps @jamuhl has other info for you.

Why put three langs inside one file?

**Comment by jamuhl** [comment]
@JavierPons  There are tons of samples...https://github.com/i18next/react-i18next/tree/master/example/react/public/locales

look at them first...afterwards if still not clear reading docs https://react.i18next.com/ feel free to ask a specific question

**Comment by JavierPons** [comment]
@isaachinman @jamuhl  I will read and check all this. Thank u. Have a nice day.
