### ISSUE TITLE
redux field label

### ISSUE THREAD

**Issue by JavierPons** [i18next/react-i18next#644]
# Question about react-i18next

Questions should be posted on StackOverflow

**Comment by JavierPons** [comment]
Hi there,
`return (
      <I18n>
        {t => {     
          return(

         
      <MuiThemeProvider muiTheme={getMuiTheme()}>
        <form
          className="form-inline"
          onSubmit={handleSubmit(this.onFormSubmit)}
        >
          <div>
            <div className="form-group">
              <Field
                className="form-control frontpage-input"
                name="FirstName"
                component={renderTextField}
                label={t('signup.field_name')}
                type="text"
              />`
this is part of my code. In other components the translation {t('')} is working well, but I have problem with label. It is not working well. The path signup.field_name is correct. I haven't found information about. Any help it is welcome.

**Comment by valubehrend1** [comment]
same, did you fix it?
