### ISSUE TITLE
TypeError: props.i18n.changeLanguage is not a function

### ISSUE THREAD

**Issue by jadbox** [i18next/react-i18next#646]
I've updated to i18next": "^13.0.0 and started to get this error... not sure if it's a languageDetector or i18next-react issue?

```
TypeError: props.i18n.changeLanguage is not a function
initSSR
node_modules/react-i18next/dist/es/utils.js:46
  43 |   }
  44 | 
  45 |   if (!initializedLanguageOnce && props.initialLanguage) {
> 46 |     props.i18n.changeLanguage(props.initialLanguage);
  47 |     initializedLanguageOnce = true;
  48 |   }
  49 | } // --------------
```
using typescript: 3.2.2

**Comment by jamuhl** [comment]
https://github.com/i18next/react-i18next/pull/631 related?

**Comment by jamuhl** [comment]
published react-i18next@8.4.0 does that fix this?

**Comment by jadbox** [comment]
@jamuhl sadly no, still getting the same error.
```
    "react-i18next": "^8.4.0",
    "i18next": "^13.0.0",
    "i18next-browser-languagedetector": "^2.2.4",
    "i18next-chained-backend": "^0.1.2",
    "i18next-localstorage-backend": "^1.1.4",
    "i18next-xhr-backend": "^1.5.1",
```

My (typescript) code:
```
import i18n from 'i18next';
import XHR from 'i18next-xhr-backend';
import LanguageDetector from 'i18next-browser-languagedetector';
import Backend from 'i18next-chained-backend';
import LocalStorageBackend from 'i18next-localstorage-backend';

const instance = i18n
  .use(LanguageDetector)
  .use(Backend)
  .init({
    react: {
      wait: true
    },
    fallbackLng: 'en',
    debug: false,
    backend: {
      backends: [
        LocalStorageBackend, // primary
        XHR // fallback
      ],
      backendOptions: [
        {
          expirationTime: 60 * 60 * 1000
        },
        {
          loadPath: 'i18n/{{lng}}.json',
          crossDomain: true
        }
      ]
    }
  });

export default instance;
```

**Comment by jadbox** [comment]
Image of the Chrome crash:
[https://imgur.com/gallery/XNGl1ZB](https://imgur.com/gallery/XNGl1ZB)

**Comment by jamuhl** [comment]
v13 -> migration guide: https://www.i18next.com/misc/migration-guide#v-12-x-x-to-v-13-0-0 or changelog: https://github.com/i18next/i18next/blob/master/CHANGELOG.md#1300

> promise API added for all functions providing a callback https://github.com/i18next/i18next/pull/1130 -> means those will now return a Promise and not this -> so you can't chain eg. i18next.init().on() anylonger as init returns a Promise

```js
const instance = i18n.init(); // nope instance is a promise
```

**Comment by klis87** [comment]
@jamuhl but in official docs we still pass `i18next.use(i18nextXHRBackend).init()` to `I18nextProvider`, nothing changed regarding this, I really have no idea how to make it work

**Comment by jamuhl** [comment]
where in the docs it says that?!?

```js
import i18n from './i18n'; // initialized i18next instance
​
ReactDOM.render(
  <I18nextProvider i18n={ i18n }>
    <App />
  </I18nextProvider>,
  document.getElementById('app')
);
```

where i18n is: https://react.i18next.com/components/i18next-instance

```js
import i18n from 'i18next';
import XHR from 'i18next-xhr-backend';
import LanguageDetector from 'i18next-browser-languagedetector';
import { reactI18nextModule } from 'react-i18next';
​
​
i18n
  .init({
   ///...
  });
​
​
export default i18n;
```

yours is:

```js
import i18n from 'i18next';
import XHR from 'i18next-xhr-backend';
import LanguageDetector from 'i18next-browser-languagedetector';
import Backend from 'i18next-chained-backend';
import LocalStorageBackend from 'i18next-localstorage-backend';

const instance = i18n
  .use(LanguageDetector)
  .use(Backend)
  .init({
    react: {
      wait: true
    },
    fallbackLng: 'en',
    debug: false,
    backend: {
      backends: [
        LocalStorageBackend, // primary
        XHR // fallback
      ],
      backendOptions: [
        {
          expirationTime: 60 * 60 * 1000
        },
        {
          loadPath: 'i18n/{{lng}}.json',
          crossDomain: true
        }
      ]
    }
  });

export default instance;
```

`const instance = i18n.init()` but v13 of i18next returns a PROMISE on init

**Comment by klis87** [comment]
@jamuhl indeed, apologies, I must have missread that. Anyway, does it mean that i18n is a singletone object? Is it possible to create independent instances within the same process?

**Comment by jamuhl** [comment]
the default import is an instance of a class already created -> but provides https://www.i18next.com/overview/api#instance-creation to create additional instances if needed.

**Comment by klis87** [comment]
@jamuhl awesome, thx! btw, I confirm that this issue is not present, everything works fine after adjusting according to migration guide, so I think this can be closed @jadbox ?
