### ISSUE TITLE
How to import 't' 

### ISSUE THREAD

**Issue by Totone3** [i18next/react-i18next#647]
Hi,

I'm trying to use react-i18next, but I got a problem, I can't bind the t method in my components.
How I do:

1- I create the src/i18n.js file and export it
2- In src/app.jsx I do this: 
`ReactDOM.render(`
`  <I18nextProvider i18n={i18n}>`
`    <Router />`
`  </I18nextProvider>,`
`  document.querySelector('#root'),`
`)`
3- I don't do anything in the router (maybe I have to? what?). I'm using 'react-router-dom' for it and my component looks like `const Router = () => (`
`  <BrowserRouter>`
`    <Switch>`
`      <Route exact path="/" component={Home} />`
`      /*  routes */`
`      <Route component={NotFound} />`
`    </Switch>`
`  </BrowserRouter>`
`)`
4- In views component (eg: Home) I do: `import { withNamespaces } from 'react-i18next'`
and when I export: `export default withNamespaces()(Home);`
so, I shoud be able to use t component if I do this at the beginning of my component: `const {t} = props` but t isn't in props. 

Where is my mystake?
(ps: sorry for my English, I'm a French noob)

**Comment by Totone3** [comment]
I have tried the sandbox. Within it, everything works fine. But when I try To implement react-i18next on m'y projet, even if I follow the sample it doesn't work.

**Comment by jamuhl** [comment]
merry x-mas to you too - would you be able to put up a codesandbox with your sample - so i can at least try to reproduce and debug where you're issue might be...from what you pasted above i can't spot a direct issue.

**Comment by Totone3** [comment]
Okk, I came back and started to setup the sandbox... and it worked. I forgot to import withNamespaces. It's okay, it works,, sorry for the time haha ^^

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
