### ISSUE TITLE
namespace parameter in withNamespaces HOC not working?

### ISSUE THREAD

**Issue by minzojian** [i18next/react-i18next#648]
try use withNamespaces hoc with namespace parameter, however, it just not working as expect

![image](https://user-images.githubusercontent.com/361781/50438766-676d3f00-092a-11e9-8e6a-3dfdabac7da5.png)

console.log at the first place, it has correct value, however,
tried console.log that parameter'value before render return, and it always get undefined

https://github.com/i18next/react-i18next/blob/503d9e1c7c2f5f5f95c0972e94bdb1ef185c4ae5/src/withNamespaces.js#L35

**Comment by minzojian** [comment]
i tried use it in next.js.just a simple code like 
  
    import { withNamespaces } from 'react-i18next';
    ....
    export default withNamespaces(['test', 'test2'])(TestComp);

nothing special

under react-i18next@8.4.0

**Comment by isaachinman** [comment]
@minzojian If you're going to ask for help, you can at least put in the effort to explain your problem fully. No one can help you until you do. Link us to a repo or a CodeSandbox and you'll get a helpful response.

**Comment by minzojian** [comment]
sorry, it is a false call, run fine, thanks
