### ISSUE TITLE
I18nextProvider not accepts promise of i18next.init()

### ISSUE THREAD

**Issue by CaTzil** [i18next/react-i18next#651]
**Describe the bug**
I18nextProvider explodes when tries to bind the `t` function on i18n prop.

```jsx
import { I18nextProvider } from 'react-i18next';
import { App } from './components/App/App';
import i18next from 'i18next';
import * as i18nextXHRBackend from 'i18next-xhr-backend';

const i18n = i18next.use(i18nextXHRBackend).init({
        react: {
            wait: true,
        },
        lng: 'en',
        fallbackLng: 'en',
        keySeparator: false,
        interpolation: {
            escapeValue: false,
        },
        ns: ['messages'],
        defaultNS: 'messages',
        fallbackNS: [],
        backend: {
            loadPath: `client/assets/locale/{{ns}}_{{lng}}.json`,
            crossDomain: true,
        },
    });

<I18nextProvider i18n={i18n}>
    <App />
</I18nextProvider>
```

```
./node_modules/react-i18next/dist/es/I18nextProvider.js:39
  36 |       defaultNS: defaultNS,
  37 |       reportNS: reportNS,
  38 |       lng: i18n && i18n.language,
> 39 |       t: i18n && i18n.t.bind(i18n)
  40 |     }
  41 |   }, children);
  42 | }
```

**Occurs in react-i18next version**
"i18next": "^13.0.1",
"i18next-xhr-backend": "^1.5.1",
"react-i18next": "^8.4.0",

**Live example**
https://codesandbox.io/s/wk45o38y98

**Expected behaviour**
It should handle the promise that is returned from `i18next.init`.

**Comment by isaachinman** [comment]
This is not a bug. The `use` function does not return `this`. It returns a promise.

Check [this modified version of your example](https://codesandbox.io/s/q3wkjl1pyw). Your `App` component was also broken.

Let me know if you have any further questions. Next time post on StackOverflow.

**Comment by CaTzil** [comment]
Thanx
