### ISSUE TITLE
<En></En>, <De></De>, <Es></Es>

### ISSUE THREAD

**Issue by karland** [i18next/react-i18next#653]
First, let me say `i18next` is awesome. Thank you.

**Is your feature request related to a problem? Please describe.**
Here are my objectives for an i18n solution:
+ I do not want to handle parallel files for, say `\en\`, `\es\`, `\de\`
+ Sometimes I need to translate longer paragraphs with components in it, but the current solution with the [`<Trans>` component](https://react.i18next.com/components/trans-component) with or without  ICU is for my taste too complicated and I do not want to export everything into `translation.json` files.
+ For longer paragraphs I would just prefer to have the texts under each other.
+ In most cases, my websites are only having two (or three) languages, so this is ok to handle.

**Describe the solution you'd like**
```jsx
import React from "react"
import { En, De, Es } from "react-i18next-languages"

const SomeComponent = () => (
  <p>
     <En>English text</En>
     <De>Deutscher Text</De>
     <Es>Texto en español</Es>
  </p>
)
```

The feature is easy to implement in i18next and maybe you find this interesting for the core?

```jsx
// react-i18next-languages.js
import React from "react"
import { withNamespaces } from "react-i18next"

export const En = withNamespaces()(props => {
  const { language } = props.i18n

  if (language === "en") {
    return <React.Fragment>{props.children}</React.Fragment>
  }
  return null
})

export const De = withNamespaces()(props => {
  const { language } = props.i18n

  if (language === "de") {
    return <React.Fragment>{props.children}</React.Fragment>
  }
  return null
})

export const Es = withNamespaces()(props => {
  const { language } = props.i18n

  if (language === "es") {
    return <React.Fragment>{props.children}</React.Fragment>
  }
  return null
})

```

**Comment by jamuhl** [comment]
Thanks for sharing your solution - looking at this i guess you would not even need i18next itself

you basically only use the language detector: https://github.com/i18next/i18next-browser-languageDetector

Just create an instance of that and call the detect function - store the language somewhere and you're good to go. No need to pull in the extra kb of i18next.

Anyway i guess this is out of the scope for this module -> as we can do this without all the code provided by i18next/react-i18next...

**Comment by karland** [comment]
Thanks for the quick response. I probably did not explain myself correctly. I suggested the solution as a complement to `react-i18next`. My assumption was that I would use and pull in `react-i18next` for all its functionality already. But then I would also have an option to use the above suggested solution as an alternative to `<Trans/>` in order to save me figuring out the correct translation strings or having to deal with a complex solution in `translation.json` for multi-paragraph translations.

**Comment by jamuhl** [comment]
simplest is using a react markdown component for such cases - at least that is what we did.

Anyway...this is something that should be placed in userland....we do not recommend to add a solution that propagates having hardcoded translations in the code...
