### ISSUE TITLE
Setup ci testing

### ISSUE THREAD

**Issue by rosskevin** [i18next/react-i18next#656]
**Is your feature request related to a problem? Please describe.**
I just PR'd tests for typescript #654 and noticed there are no ci tests for PRs

**Describe the solution you'd like**
Setup circleci, travis, anything that would validate PRs before merge

**Comment by jamuhl** [comment]
PR runs through travis, coveralls and codeclimate...

**Comment by rosskevin** [comment]
oops, sorry, I missed that.  I've got three PRs going so I may have looked at a different one.
