### ISSUE TITLE
react-i18next@9.0.1" has unmet peer dependency "prop-types@>= 15.6.2".

### ISSUE THREAD

**Issue by basslagter** [i18next/react-i18next#657]
When installing (using Yarn) the following warning is shown:

react-i18next@9.0.1" has unmet peer dependency "prop-types@>= 15.6.2".

**Comment by jamuhl** [comment]
?

**Comment by basslagter** [comment]
That was what I was thinking ;)

**Comment by jamuhl** [comment]
if i see it right (need to check that later) prop-types is not needed anylonger...

but i guess overall - you have no idea what that warning likes to tell you?!?

Do you get an issue during build?

**Comment by basslagter** [comment]
No issues during build. Just wanted to point out the warning.

**Comment by jamuhl** [comment]
The warning tells you that react-i18next depends on the module prop-types which you should install in the version you need for your app...

But as i just checked it's not needed anylonger (was in past) - so ignore it for now - next version will remove that peer dependency 👍

**Comment by basslagter** [comment]
Cool. Thanks!
