### ISSUE TITLE
Hooks example

### ISSUE THREAD

**Issue by VincentLanglet** [i18next/react-i18next#659]
**Describe the bug**
The example didn't start

**Occurs in react-i18next version**
ae96305e7f4badddd62364a6f55751c72626bfe7

**To Reproduce**
git clone https://github.com/i18next/react-i18next.git
cd react-i18next/example/react-hooks
yarn install
yarn start
<open in browser>

**Screenshots**
![image](https://user-images.githubusercontent.com/9052536/50669035-1cef6080-0fc3-11e9-9346-621bfeeef3c4.png)

**OS**
 - Device: MacBookPro
 - Browser: Chrome

**Comment by jamuhl** [comment]
Could you please retry with the changes made in current master: https://github.com/i18next/react-i18next/commit/e2fea31c45fa544d51f3ae4b1b7019700f71458e

**Comment by VincentLanglet** [comment]
@jamuhl It worked.

But, if i install react@16.7.0 instead, i have the error message.
Since the hooks are in react@16.7.0-alpha, shouldn't they be in the 16.7.0 too ?

**Comment by VincentLanglet** [comment]
Ok found this : https://reactjs.org/blog/2018/12/19/react-v-16-7.html

**Comment by jamuhl** [comment]
good to know - missed they released a 16.7 (without hooks)

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
