### ISSUE TITLE
languageChanged event is fired after components are rendered

### ISSUE THREAD

**Issue by warpdesign** [i18next/react-i18next#660]
**Describe the bug**
When changing the language using i18next.changeLanguage(), a render of the React components is triggered.

i18next also triggers a `languageChanged` event but it's triggered *after* the components have been re-rendered. It can be a problem if the components make use of some code which uses i18next localized strings.

**Occurs in react-i18next version**
8.4.0

**To Reproduce**
One of my component is a simple file lister that looks like this:

```
file1 ... 10 bytes
file2 ... 12 kbytes
...
```

To avoid calling i18next for each and every files of my component, I preload the `kbytes` localized strings in some (external non-react) class.

On the languageChange event of i18next this class updates the localized strings but since the render happens before the `languageChanged` event, after the first render, `kbytes` is displayed using the previous language while the rest of the app is correctly using the new language.

**Expected behaviour**
Shouldn't the render happen **after** the i18next `languageChanged` has been triggered?

**Screenshots**

**OS (please complete the following information):**
 - Browser: Chrome/66.0.3359.181

**Additional context**
I am running Electron 3.0.5 and React 16.5.2

**Comment by jamuhl** [comment]
the `languageChanged` event is the trigger for rerender

using a proper backend implementation for loading those translations (even if using your custom code) should do the trick -> backend asserts translations are loaded / available before triggering the event

**Comment by warpdesign** [comment]
I'm closing the issue: there was actually something wrong with my code: the event is fired as expected.

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
