### ISSUE TITLE
Typescript & hooks 

### ISSUE THREAD

**Issue by stunaz** [i18next/react-i18next#661]
@jleclanche 
how are we suppose to use the hooks in typescript?
when I do `const [t, i18n] = useTranslation();`

later i want to get the current language with `i18n.language`

I get this typing error:

```typescript
Type error: Property 'language' does not exist on type '{} | on type '{} | i18n'.
  Property 'language' does not exist on type '{}'.  TS2339{}'.  TS2339
```

@jamuhl 
After reading the source code, I understand that the hooks can return  `{}` if an instance of i18n is not provided, and a warning is thrown ... I mean why event allow this?

**Comment by jleclanche** [comment]
Couldn't tell you, I ended up using the old system for now because I couldn't get suspense to work properly in my app. Just wanted to at least share my typings work.

**Comment by VincentLanglet** [comment]
You can create a function `isReady(i18n: {} | i18n): i18n is i18n`.
The best would be to add this function in this library.

**Comment by stunaz** [comment]
@

**Comment by VincentLanglet** [comment]
@stunaz In https://www.typescriptlang.org/docs/handbook/advanced-types.html, there is examples of type guard which return type predicate.
```
function isFish(pet: Fish | Bird): pet is Fish {
    return (<Fish>pet).swim !== undefined;
}
```

I think, you can do the same
```
function isReady(i18n: {} | i18n): i18n is i18n {
    return (<i18n>i18n).t !== undefined;
}
```

**Comment by stunaz** [comment]
ok thanks for the tip @VincentLanglet . I got it working, meaning I got it tyed :-) feels like a hack :-)
thanks again

**Comment by VincentLanglet** [comment]
If it's fine for you, you can close the issue @stunaz.

Since it's in the typescript I dont see this like a hack. Typeguard are so useful !
