### ISSUE TITLE
How to test components wrapped in “withNamespaces” HOC that have “innerRef”?

### ISSUE THREAD

**Issue by anatel** [i18next/react-i18next#664]
# Question about react-i18next
Hi,
I uploaded the question details on StackOverflow, please look at it [here](https://stackoverflow.com/questions/54077374/how-to-test-components-wrapped-in-withnamespaces-hoc-that-have-innerref)

I didn't find an example or documentation for this.

Thanks,
Anat

**Comment by jamuhl** [comment]
Why not:

```js
class A extends Component {
  constructor() {
    super(this.props);
    this.refToB = null;
  }

  render() {
    return (
      <B
        innerRef={(ref) => this.refToB = ref}
        prop1="prop1"
        prop2="prop2"
      />
    );
  }
}
```

no need to set innerRef as options in withNamepaces -> use innerRef directly as prop defined in the parent component

You mock needs to convert prop innerRef to ref, eg. like: https://github.com/i18next/react-i18next/blob/master/src/withNamespaces.js#L29

**Comment by anatel** [comment]
Thank you for your answer.

> no need to set innerRef as options in withNamepaces -> use innerRef directly as prop defined in the parent 

I tried it now and it looks like what I get in `refToB` is a reference to `WithMergedOptions` instance instead of B.
B is exported like this after your suggestion: (removed options)
`export default withNamespaces()(B)`


Regarding the mock implementation, is it ok to ask for a concrete example? I coudln't understand how to implement it.

**Comment by jamuhl** [comment]
Hope that helps: https://github.com/i18next/react-i18next/blob/master/example/test-jest/__mocks__/react-i18next.js#L37

**Comment by jamuhl** [comment]
never tested innerRef stuff myself - as never needed that to be honest.

**Comment by jamuhl** [comment]
closing for now....stackoverflow might be more helpful getting a answer on this one
