### ISSUE TITLE
How to translate inside export function with array and for loop

### ISSUE THREAD

**Issue by JavierPons** [i18next/react-i18next#666]
thank you for your time. I want to translate the month in different languages inside this switch. for that I have to loop. For that I should change the returns in switch for the path in translation.json that I created with different languages. So every return will have own path and language. For example in switch case 'August': return 'month.aug' will recognize the language when click on the language I want to see. But before that it works I need to use i18n and {t('something')} in this for loop. I have been using i18next for different cases all working well. Any Idea how to implement it here? Im using only FrontEnd. How it would be possible to translate every return in switch when for loop is pushing the month to array list?
Here my code ==>
`export const convertMonthNames = month => {
      switch (month) {
        case 'January':
          return 'Enero'
        case 'February':
          return 'Febrero'
        case 'March':
          return 'Marzo'
        case 'April':
          return 'Abril'
        case 'May':
          return 'Mayo'
        case 'June':
          return 'Junio'
        case 'July':
          return 'Julio'
        case 'August':
          return 'Agosto'
        case 'September':
          return 'Septiembre'
        case 'October':
          return 'Octubre'
        case 'November':
          return 'Noviembre'
        case 'December':
          return 'Diciembre'
      }
    }`
`export const labelInvoiceMonthlyArray = (array) => {
  let list = []
  for (var i = 0; i < array.length; i++) {
    list.push(convertMonthNames(array[i]))
  }
  return list
}`

**Comment by jamuhl** [comment]
`export const convertMonthNames = month => t(month);`

**Comment by jamuhl** [comment]
with json:

```js
{
  "January": "Enero",
  ...
}
```

**Comment by JavierPons** [comment]
@jamuhl  I dont get yet your point in `export const convertMonthNames = month => t(month);`  I have switch ? Could you tell a bit more, thanks

**Comment by jamuhl** [comment]
you do not need a switch - you call t with the month name

no need to:

```js
export const convertMonthNames = month => { switch (month) { case 'January': return t('January') 
```

**Comment by JavierPons** [comment]
Where I have to define <I18n> in this case?  console gives me error because is not defined.

**Comment by jamuhl** [comment]
what? define in?

**Comment by JavierPons** [comment]
sorry, It was my mistake. Forget this last post.

**Comment by jamuhl** [comment]
ok...so this is solved or still not clear?

**Comment by jamuhl** [comment]
Point is you do not need the switch - as this was just needed for you custom translation 

you can directly call the `t` function with a key build upon the array items (months in english)...

so not even need the convertMonthNames anylonger

```js
export const labelInvoiceMonthlyArray = (array) => { let list = [] for (var i = 0; i < array.length; i++) { list.push(i18next.t(array[i])) } return list }
```

or as nice code

```js
export const labelInvoiceMonthlyArray = array => array.map(month => i18next.t(month));
```

**Comment by jamuhl** [comment]
```js
import i18n from './i18n.js' // -> https://github.com/i18next/react-i18next/blob/master/example/react/src/i18n.js

export const labelInvoiceMonthlyArray = array => array.map(month => i18n.t(month));
```

Just make sure i18n was already initialized before calling this exported function! (eg. calling it on render time)

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:

**Comment by JavierPons** [comment]
so...  how I can do =>> you can directly call the t function with a key build upon the array items (months in english)...

so not even need the convertMonthNames anylonger

**Comment by jamuhl** [comment]
```js
import i18n from './i18n.js' // -> https://github.com/i18next/react-i18next/blob/master/example/react/src/i18n.js

export const labelInvoiceMonthlyArray = array => array.map(month => i18n.t(month));
```

**Comment by jamuhl** [comment]
https://codesandbox.io/s/92l02p89yy

**Comment by jamuhl** [comment]
app.js line 14 https://codesandbox.io/s/92l02p89yy

**Comment by JavierPons** [comment]
thank you very much!
