### ISSUE TITLE
withNamespace([])(Component).WrappedComponent is undefined

### ISSUE THREAD

**Issue by jpolo** [i18next/react-i18next#668]
**Describe the bug**
`withNamespace([])(Component).WrappedComponent` is undefined. 

It seems also all other statics are not present (using `Object.keys()` on the result).

**Occurs in react-i18next version**
v9.0.2

**To Reproduce**
1. Create a new component using the decorator withNamespaces()
2. Try to access any static property

**Expected behaviour**
When I read the decorator code there is this code :

```
LoadNamespaceWithContext.WrappedComponent = WrappedComponent;
LoadNamespaceWithContext.displayName = `LoadNamespace(${getDisplayName(WrappedComponent)})`;
LoadNamespaceWithContext.namespaces = namespaceArg;
```
So the WrappedComponent was intended to be accesible but is not.

**Screenshots**
N/A

**OS (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by jamuhl** [comment]
strange this tests don't fail https://github.com/i18next/react-i18next/blob/master/test/withNamespaces.spec.js#L12 which actually assert this

**Comment by jamuhl** [comment]
closing for now...feel free to reopen...for now i guess it's a local problem
