### ISSUE TITLE
How to use {t('something')} inside if conditional

### ISSUE THREAD

**Issue by JavierPons** [i18next/react-i18next#670]
Hi again, and thanks for your support.
import { I18n } from 'react-i18next' 
` const requiredFields = [
    'email',
    'FirstName',
    'Lastname',
    'password',
    'passwordConfirmation',
    'agree_to_terms'
  ]

  requiredFields.forEach(field => {
    
    if (!values[field]) {
      errors[field] = 'Field must be typed'
    }
  })`

I have been using i18next-react for a while. It has been working...  I wrapped into my app file <i18n>   {t =>{
      return(    <p>{t('path')  </p> I have all the files as i18n.js and json etc. I mean react-i18next is working for long. So how I have to implement in the same logic to the code I paste  and change ==> 'Field must be typed'  by something like I used before. I have been reading material and I didn't found anything... I tried but something more I have to learn. Thanks again.

**Comment by jamuhl** [comment]
this is the same as https://github.com/i18next/react-i18next/issues/666

```js
if (!values[field]) {
  errors[field] = i18n.t('Field must be typed')
}
```
