### ISSUE TITLE
react-i18next and dropdown.

### ISSUE THREAD

**Issue by JavierPons** [i18next/react-i18next#675]
Hi there. 
`const _createMenuItems = menuItems =>
  menuItems.map((item, index) => (
    <I18n>
   {t =>{ 
  return( 
    <MenuItem key={index} value={item} primaryText={t(item)} />
     )
  }}  
</I18n>
  )
  )`
this code translate a dropdown list of countries in different languages as I want. The issue here is that I can't select a item (in this case a country name) The dropdown doesn't work properly. I can move in the dropdown up and down but not select. Any idea?
Thank you for the support.

Do you know if exist any  react-i18next community? I couldn´t find anyone at the moment to join in.

**Comment by jamuhl** [comment]
stackoverflow.com is your friend

**Comment by JavierPons** [comment]
Sorry if I disturb with my post. It wasn´t my meaning. I knew the protocol, I step over. I have post: down Dropdown and react-i18next in stackoverflow. Sorry again.

**Comment by jamuhl** [comment]
Nothing to worry...just i got not enough time to solve individual programming issues that are more of a general problem than related to issues in i18next. Hope you understand.
