### ISSUE TITLE
fallbackLng: false seems to not be handled

### ISSUE THREAD

**Issue by birdy-** [i18next/react-i18next#677]
**Describe the bug**
If you use react-i18next (for me, with hooks, but I'm not sure it's related), if you init i18next with `fallbackLng: false` and an unknown `lng`, you'll encounter an error.
```
Cannot read property '0' of undefined in node_modules/react-i18next/dist/es/hooks/useTranslation.js?:52:52
```

**Occurs in react-i18next version**
9.02

**To Reproduce**
- Initialize a i18next with `fallbackLng: false` and set language to an unknown value (for example `eo`)

**Expected behaviour**
Working :)

**OS (please complete the following information):**
Happened on SSR, node 10 on Elasticbeanstalk and locally (MacOS)

**Comment by jamuhl** [comment]
will need to check - thank you for reporting

**Comment by jamuhl** [comment]
could you retry with react-i18next@9.0.3

that at least should fix the state never get ready and therefore "killing" the app

**Comment by jamuhl** [comment]
closing for now...feel free to reopen if still an issue in react-i18next@>=9.0.3
