### ISSUE TITLE
Shouldn't i18next wait for language detection result before loading fallback language

### ISSUE THREAD

**Issue by nikolay-borzov** [i18next/react-i18next#679]
# Question about react-i18next

I use [react-i18next example](https://github.com/i18next/react-i18next/tree/master/example/react) as a base.
I replaced 'i18next-browser-languagedetector' by custom language detector:
   

    class MyLanguageDetector {
      constructor(services, options = {}) {
        this.async = true;
        this.init(services, options);
      }
    
      init(services, options = {}, i18nOptions = {}) {  }
    
      detect(callback) {
        setTimeout(() => {
          callback('de')
        }, 5000);
      }
    
      cacheUserLanguage(lng, caches) {  }
    }

    MyLanguageDetector.type = 'languageDetector';

Config:

    i18n
      .use(MyLanguageDetector)
      .use(Backend)
      .use(reactI18nextModule)
    
      .init({
        fallbackLng: 'en',
        debug: true,
    
        interpolation: { escapeValue: false },
    
        react: { wait: true }
      });

What I see is:
 
    i18next::backendConnector: loaded namespace translation for language en
and after ~5 seconds:

    i18next::backendConnector: loaded namespace translation for language de
I expected that 'en' won't be loaded since detected language is 'de'

[this question on stackoverflow](https://stackoverflow.com/questions/53791333/shouldnt-i18next-wait-for-language-detection-result-before-loading-fallback-lan)

**Comment by jamuhl** [comment]
the set fallbackLng is en ---> it load en too -> `t('key')` if not found in de resources it will pick it from en

**Comment by jamuhl** [comment]
https://www.i18next.com/principles/fallback#language-fallback

you do not like fallbackLng but prefer having the keys as fallbacks: https://www.i18next.com/principles/fallback#key-fallback

**Comment by nikolay-borzov** [comment]
Thank you for the explanation. I'll try key fallback. On my current project I use `i18next-json-sync` so every language file keys are synced and key fallback will work better.
