### ISSUE TITLE
react-i18next throwing webpack error when initializeing using @babel/runtime 7.3.0

### ISSUE THREAD

**Issue by guiyep** [i18next/react-i18next#685]
since the dependency with @babel/runtime is anything from 7.1.2 with the latest update on @babel/runtime 7.3.0 (today) the library stops working. Had to manually downgrade the version to 7.1.2 to make the library work again.

**Comment by jamuhl** [comment]
? do you build react-i18next yourself? the runtime gets embedded during build time - so you should not really need/depend on it?

can you give a little more information what you are doing - and how you run into this?

**Comment by jamuhl** [comment]
Just updated all dependencies -> as i guess it might be related to babel-runtime update

did a republish of react-i18next@9.0.6 does using that resolve your issue?

**Comment by pedrorezende** [comment]
I guess I'm having a related problem. Just started a brand new create-react-app project yesterday, installed react-i18next and i18next and reused the same code I was using in another project. But today I'm getting the following error.

```
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.getOwnPropertyDescriptors (<anonymous>)
    at _objectSpread (objectSpread.js:19)
    at setDefaults (context.js:23)
    at Object.init (context.js:37)
    at i18next.js:187
    at Array.forEach (<anonymous>)
    at I18n.init (i18next.js:186)
    at Module../src/index.js (index.js:9)
    at __webpack_require__ (bootstrap:782)
    at fn (bootstrap:150)
    at Object.0 (WarningPanel.module.scss?c11d:45)
    at __webpack_require__ (bootstrap:782)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
    at main.chunk.js:1
```

**Comment by jamuhl** [comment]
could you try with react-i18next@9.0.7

**Comment by guiyep** [comment]
I'm getting the exact same issue as described before. Not cloning the repo just npm installing it and then initialising it as follow:

import { reactI18nextModule } from 'react-i18next';

// i18next configuration
const config = {
  resources,
  fallbackLng: 'en-AU',
  lng: 'en-AU',
  keySeparator: false,
  interpolation: {
    format(value, format, lng) {
      return formatterExecutor(allFormatters, value, format, lng);
    },
    escapeValue: false,
  },
};
const i18next = i18n.use(reactI18nextModule).init(config);

**Comment by jamuhl** [comment]
still an issue with `react-i18next@9.0.7` ?!? should not be the case as confirmed by https://github.com/i18next/react-i18next/pull/686

beside that please be aware `const i18next = i18n.use(reactI18nextModule).init(config);
` here i18next will be a Promise not the i18next instance if using i18next >= v13.0.0

**Comment by pedrorezende** [comment]
Hi @jamuhl . Thanks for the support. Setting the version of react-i18next to 9.0.7 fixed the problem for me.
