### ISSUE TITLE
Compile error babel-loader

### ISSUE THREAD

**Issue by meDev17** [i18next/react-i18next#689]
**Describe the bug**
Getting error message 
```
Failed to compile
./node_modules/i18next/dist/es/index.js
Module not found: Can't resolve '.../Project/node_modules/babel-loader/lib/index.js' in '.../Project'
```

**Occurs in react-i18next version**
    "react-i18next": "^9.0.7",
    "i18next": "^13.1.5",

**To Reproduce**
Just installed the i18next and react-i18next using yarn.
But when I try to run app, I'm getting the above error message.

**Expected behaviour**
Compile without error

![screen shot 2019-01-23 at 12 43 18 pm](https://user-images.githubusercontent.com/26999676/51597611-b2b84480-1f0c-11e9-993d-bed9d3d02296.png)

**Comment by jamuhl** [comment]
you shall not transpile the files in node_modules...are you running create-react-app or some custom webpack?

**Comment by meDev17** [comment]
Thanks for your reply, my app running create-react-app.

**Comment by meDev17** [comment]
Any idea?

**Comment by jamuhl** [comment]
Please provide a repo to reproduce...no idea from looking at the issue only 🤔
