### ISSUE TITLE
withNamespaces not show the wrapped component on Firefox & IE>=10

### ISSUE THREAD

**Issue by jeremygordilloors** [i18next/react-i18next#696]
Hello guys,
when i open my react app on Firefox or IE >= 10, the menu component not render. I'm using withNamespaces function with namespace "menu" to export my component.

`export default withNamespaces('menu')(withStyles(styles)(GroupMapped));`

My i18n config is that :

```
import i18n from 'i18next';
import BrowserLanguageDetector from 'i18next-browser-languagedetector';
import { reactI18nextModule } from 'react-i18next';
import XHR from 'i18next-xhr-backend';

const detectorOptions = {
  // order and from where user language should be detected
  order: [
    'querystring',
    'cookie',
    'localStorage',
    'navigator',
    'htmlTag',
    'path',
    'subdomain'
  ],

  // keys or params to lookup language from
  lookupQuerystring: 'lng',
  lookupCookie: 'i18next',
  lookupLocalStorage: 'i18nextLng',
  lookupFromPathIndex: 0,
  lookupFromSubdomainIndex: 0,

  // cache user language on
  caches: ['cookie', 'localStorage'],
  excludeCacheFor: ['cimode'], // languages to not persist (cookie, localStorage)

  // optional expire and domain for set cookie
  cookieMinutes: 60,
  cookieDomain: 'myDomain',

  // optional htmlTag with lang attribute, the default is:
  htmlTag: document.documentElement
};

function loadTranslations(url, options, callback) {
    import('../i18n/' + url + '.json').then(res => {
      callback(res.default, { status: '200' })
    }).catch(err => console.log(err));
}

const i18nOptions = {
  fallbackLng: 'en',
  ns: ['common'],
  defaultNS: 'common',
  detect: detectorOptions,
  debug: process.env.NODE_ENV === 'development',
  react: {
    wait: true
  },
  backend: {
    loadPath: "{{ns}}/{{lng}}",
    parse: data => data,
    ajax: loadTranslations
  }
};

i18n
  .use(BrowserLanguageDetector)
  .use(XHR)
  .use(reactI18nextModule)
  .init(i18nOptions, (err, t) => err ? console.log("i18n - Something went wrong loading", err) : console.info('i18next.language', i18n.language));

export default i18n;
```
In the Firefox inspector, i see that lng prop is `undefined`
 
![image](https://user-images.githubusercontent.com/45598337/51674619-700c7000-1fd1-11e9-87d6-177901627879.png)

I saw another difference, that Chrome use "it" as detected language meanwhile Firefox or IE detect "it-IT".
I assumed the mistake could be this, so i forced i18next to use only lang and it works but i need that in both cases work.

Ps. All this settings works fine on Chrome.

**Comment by jamuhl** [comment]
shouldn't make a difference it-IT still should load it and use that if values not found on it-IT

do you get any warnings in the console from i18next?

**Comment by jeremygordilloors** [comment]
> shouldn't make a difference it-IT still should load it and use that if values not found on it-IT
> 
> do you get any warnings in the console from i18next?

No, zero warnings.
I have only this logs 

![image](https://user-images.githubusercontent.com/45598337/51680823-1614a600-1fe3-11e9-972e-7b04a44be383.png)

**Comment by jeremygordilloors** [comment]
> Could you make a quick example to reproduce eg. based on https://codesandbox.io/s/l4qrory2nl to reproduce - must be something specific to your code as i get expected result on the sample sandbox

I found the error.
I added the callback fn in catch statement for the import of the custom ajax call.
```javascript
function loadTranslations(url, options, callback) {
  import("../i18n/" + url + ".json")
    .then(res => {
      callback(res.default, { status: "200" });
    })
    .catch(() => {
      callback(null, { status: "404" });
    });
}
```

Now works on Firefox & IE.
Thanks for help.

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
