### ISSUE TITLE
Add typescript tests for v10 hooks (like we had in v9)

### ISSUE THREAD

**Issue by jamuhl** [i18next/react-i18next#703]
Get back the test coverage for the upcoming v10 (currently (soon) it is published as npm i react-i18next@next)

**Comment by jamuhl** [comment]
@rosskevin would be awesome if we could add that coverage back in v10 - a lot changed with using hooks but basic type definitions should already be there

**Comment by rosskevin** [comment]
@jamuhl it looks like you dropped `NamespaceConsumer` from v10 but the hoc is retained.  That's too hard of a break in my opinion for class-based users.  I for one am exclusively using it over the hoc, and we have _many_ classes to convert before we can use hooks.  

If leaving this as-is I would have two choices:
1. convert my entire class code to functions and hooks (not incremental)
2. convert my entire function code to hooks AND convert all `NamespaceConsumer` usage to hocs or functions then hooks.

I suggest strongly that the render callback needs to be included in v10.

**Comment by rosskevin** [comment]
@jamuhl would you have any objections to converting the `spec.js` to `spec.tsx` typescript?  This would inherently provide coverage for the type definitions.

**Comment by jamuhl** [comment]
@rosskevin ...would prefer keeping stuff separated...

hm...might add a render prop like the HOC using the hook internally

**Comment by rosskevin** [comment]
> hm...might add a render prop like the HOC using the hook internally

That would definitely be advisable, it would be mostly a search/replace instead of a major upgrade crisis where everyone is forced to roll their own.
