### ISSUE TITLE
Add back render callback pattern for v10

### ISSUE THREAD

**Issue by rosskevin** [i18next/react-i18next#708]
**Is your feature request related to a problem? Please describe.**
/from https://github.com/i18next/react-i18next/issues/703#issuecomment-458969260

Currently the render callback from v9 was dropped but a the hoc is retained. That's too hard of a break in my opinion for class-based users. I for one am exclusively using it over the hoc, and we have many classes to convert before we can use hooks.

**Describe the solution you'd like**
I suggest strongly that a render callback needs to be included in v10.

**Describe alternatives you've considered**
If leaving this as-is I would have two choices:
- convert my entire class code to functions and hooks (not incremental)
- convert my entire function code to hooks AND convert all NamespaceConsumer usage to hocs or functions and hooks.

**Comment by jamuhl** [comment]
`TranslationRenderProp` ? or do you have an idea for a good naming?

**Comment by rosskevin** [comment]
I would just use `Translation` to provide the pattern - consistent in naming to `useTranslation` and `withTranslation`.

**Comment by jamuhl** [comment]
okey

**Comment by jamuhl** [comment]
`Translation` render prop landed in react-i18next@10.0.0-alpha.2
