### ISSUE TITLE
Should memoize translation in <Trans> component

### ISSUE THREAD

**Issue by rally25rs** [i18next/react-i18next#710]
**Is your feature request related to a problem? Please describe.**

In current `react-i18next@next` (the one using hooks) the translation is not memoized, so if you have a component with frequent renders, say something like:

```
export default class SignIn extends React.Component {
  constructor(props) {
    super(props);
    this.handleInputChange = this.handleInputChange.bind(this);
    this.state = {
      email: ''
    };
  }

  render() {
    return (
              <label>
                <Trans>email</Trans>
              </label>
              <input
                type="text"
                className="form-control"
                name="email"
                value={this.state.email}
                onChange={this.handleInputChange}
              />
            </div>
    );
  }

  handleInputChange(event) {
    this.setState({
      [event.target.name]: event.target.value,
    });
  }
```

Every keypress in the text box causes a `render()` call, and `<Trans>` re-calls `i18next.t()` which does all it's work to re-lookup the same translation (verified this in the browser debugger).

The result is degraded render performance for views like this.

**Describe the solution you'd like**

You can use the `useMemo` react hook to memoize the result of `.t()`

I didn't end up using this library, I wrote me own because it seemed simpler, but I did:

```
export default function Trans(props) {
  const {t, opts} = props;
  const translation = useMemo(() => i18n.t(t, opts), [t, opts]);

  return <>{translation}</>;
}
```
so the usage in this case is `<Trans t="email" />`

The point is the `useMemo()` call to only re-translate through i18next if the translation key changes.

**Comment by jamuhl** [comment]
Did you ever encounter any real performance issue with calling i18n.t? There are no complex calculations happening so there is no significant performance impact (this is not ICU). Basically memo does the same -> creates a map of persistant values -> i18next resource table is the same -> so the only benefit would be if you got very very calculation intense interpolation going on - which can't be the case -> i guess this is a good sample of premature optimization.

**Comment by matthewkwong2** [comment]
In some case, I use `memo` HOC to wrap the entire component to prevent unnecessary re-rendering. This is exceptionally useful when my dashboard web app enables users to toggle between light and dark theme on the fly, while it inclues several heavy components like SVG charts. 

I do a simple test on a component which I add a console output in the render functionand with the help of `why-did-you-render` library. Without memo, the component renders once while initializing, but it sometime unnecessarily re-renders during theme changes or state updates. With memo, the component renders twice during initialization, but no unnecessary re-renders afterwards

**Comment by jamuhl** [comment]
@matthewkwong2 sounds good...so you had performance issues and solved them...well done.

**Comment by matthewkwong2** [comment]
@jamuhl technically it is unsolved, the this library still causes unnecessary re-rendering during initialization

**Comment by jamuhl** [comment]
@matthewkwong2 are you using Suspense? Just checked the sample: https://github.com/i18next/react-i18next/tree/master/example/react

![image](https://user-images.githubusercontent.com/977772/67618227-e94d2380-f7ec-11e9-9557-11270f97961f.png)

first "render" warn in console: initial load in en
second "render" warn in console: changing language to de

So...I'm not sure...but looks to me like not the cause of the library as is...anyway...providing a codesandbox for reproduction I might have a look...

**Comment by matthewkwong2** [comment]
The only thing I've changed is wrapping and not wrapping the component inside `memo` so I doubt it

**Comment by jamuhl** [comment]
@matthewkwong2 like said - it works as expected in the sample...if I should help you - I need a sample to reproduce this...

**Comment by matthewkwong2** [comment]
That because none of the components are wrapped inside `memo`. Please note that re-rendering only happens for `memo` or `PureComponent` ONLY. I will make a sample later on.

**Comment by jamuhl** [comment]
![image](https://user-images.githubusercontent.com/977772/67618880-20273780-f7f5-11e9-923f-685204bfaaf4.png)

first "render" warn in console: initial load in en
second "render" warn in console: changing language to de

changing: https://github.com/i18next/react-i18next/blob/master/example/react/src/App.js#L7 to `PureComponent`

**Comment by jamuhl** [comment]
So, will wait for your sample...thank you...

**Comment by matthewkwong2** [comment]
@jamuhl Please read the console output.
** ONLY causes unnecessary re-renders when using `i18next-xhr-backend`**

https://codesandbox.io/embed/gifted-babbage-wzj08?fontsize=14

**Comment by jamuhl** [comment]
Wow...that is so weird - I extended your sample a little: https://codesandbox.io/s/react-i18next-test-z4jx0

(making sure no saveMissing, ... gets in the way, also adding a counter to the MemorizedButton to see it gets rendered to DOM only once - while called twice)

I moved the sample to local so I could add some more logs to the useTranslation:

```js
// ...
  if (!ready && !useSuspense) return ret; // not yet loaded namespaces -> load them -> and trigger suspense

  throw new Promise(function(resolve) {
    console.warn(`${props.name} throw Promise (trigger Suspense)`);
    loadNamespaces(i18n, namespaces, function() {
      console.warn(`${props.name} set state (loaded namespace -> sets new t function)`);
      setT(getT());
      console.warn(`${props.name} resolves Promise (resume Suspense)`);
      resolve();
    });
  });
```

![image](https://user-images.githubusercontent.com/977772/67620665-93d33f80-f809-11e9-845a-53058bc3c8c5.png)

The SimpleButton gets triggered it's rerender by the `setT`. Immediately after the MemorizedButton also renders - honestly I have no idea why. Then Suspense get resolved by the SimpleButton - removing the fallbackUI and showing the real content again. Then `setT` gets called for the MemorizedButton - and it rerenders (calls the function internally) while the rendered result stays the memoized `memorizedButton1` (counter says 2)...

Change the order of the 2 Buttons MemorizedButton before SimpleButton -> only one render as SimpleButton gives a shit about MemorizedButton gets setT called.

Move every Component in own Suspense -> both render only once

So...if this is related to react-i18next - feel free to provide a PR...as I don't know which magic triggers a rerender on the memorized component...I have no clue how to fix this...

**Comment by jamuhl** [comment]
To make it more clear - I got no idea what is triggering this render:

![image](https://user-images.githubusercontent.com/977772/67621030-f24ded00-f80c-11e9-9088-7724b07c7bd3.png)

I just know it's not useTranslation (neither the loading done as it comes later nor the bound events)
