### ISSUE TITLE
How do you test translated components wrapped with <Suspense/>?

### ISSUE THREAD

**Issue by krnlde** [i18next/react-i18next#713]
Since react-i18next v10 the way to use components that are wrapped `withTranslation()` require a `<Suspense/>` wrapped around it as seen [here](https://github.com/i18next/react-i18next/blob/57d23cb09b3fcd6c12837906433100bebc4c25d8/example/react/src/App.js#L34).

Based on your example we adapted our HoC:
```ts
export function wrapWithI18Next<P extends any>(i18n: i18n.i18n) {
  return (BaseComponent: React.ComponentType<P>) => (
    class extends React.Component<P> {
      public render(): React.ReactNode {
        return (
          <Suspense fallback={<span>loading</span>}>
            <BaseComponent {...this.props} />
          </Suspense>
        );
      }
    }
  )
}
```

The problem with this is, that our integration tests now fail, because the components are not loaded in time of testing (instead the fallback loader is rendered).

Our test case:
```ts
  it('should trigger the sidenav', function() {
    const { getByTestId } = renderHeader({ hasMenu: true });
    const el = getByTestId('ocm');
    fireEvent.click(el);
    // ... expectations
  });
```

The test-id `ocm` is not yet available. Unfortunately [your test example](https://github.com/i18next/react-i18next/blob/57d23cb09b3fcd6c12837906433100bebc4c25d8/example/react/src/App.test.js) doesn't cover this test-case. How would you achieve the correct behaviour, e.g. `await` the i18n to be fullfilled somehow (this doesn't work - I tried).

Thank you guys

**Comment by jamuhl** [comment]
https://react.i18next.com/misc/testing

https://github.com/i18next/react-i18next/tree/master/example/v9.x.x/test-jest

**Comment by krnlde** [comment]
This is a nice approach indeed. What about i18next's `cimode` feature which should tackle exactly that? We use that and it worked well up to v9 of react-i18next. But I guess you're right, too much complexity and dependencies for an integration test.

**Comment by jamuhl** [comment]
cimode works for end to end tests - but still a lot of async loading to worry.

what we might add is a suspense free mode...but not sure if that adds to simplicity. In the end i guess mocking away the i18n aspect is the way to go (as you're not testing it).

**Comment by jamuhl** [comment]
https://github.com/i18next/react-i18next/tree/master/example/test-jest --> see the __mocks__ folder

**Comment by krnlde** [comment]
Yeah nice, thank you :) Unfortunately with typescript its not allowed to set `useMock.i18n = {}` [here](https://github.com/i18next/react-i18next/blob/master/example/test-jest/__mocks__/react-i18next.js#L34). You'll need to add `as i18next.i18n` or replace it with `null`.

**Comment by jamuhl** [comment]
ok...that test sample is not in typescript...so 🤷‍♂️what should i say...

**Comment by jamuhl** [comment]
evtl. react-i18next@10.0.2 makes it easier without mocking...might be worth trying
