### ISSUE TITLE
I think v10 is not outputting a dist folder that I can import in CRA+TS app

### ISSUE THREAD

**Issue by lvl99** [i18next/react-i18next#716]
**Describe the bug**
```
./src/containers/App/index.tsx
Module not found: Can't resolve 'react-i18next' in '/Users/mattscheurich/Dev/react-app/src/containers/App'
```

**Occurs in react-i18next version**
`10.0.0`

**To Reproduce**

1. `npm i react-i18next --save`
2. `import { useTranslation } from "react-i18next";` in any file (note: I'm using CRA+TS)
3. `npm run start`
4. See error in bug description above

**Expected behaviour**
I'd expect it to import `react-i18next`!

I wonder if because I'm using CRA and don't want to eject `react-scripts` that I need to use ES5-compatible code. If there's no `dist` folder in the `node_modules/react-i18next` package that the `package.json`'s `main` file refers to.

**Screenshots**
<img width="813" alt="image" src="https://user-images.githubusercontent.com/238480/52360122-8b4c9600-2a3b-11e9-9b2e-0216ffdb6b55.png">

**OS (please complete the following information):**

- Device: MBP Mid-2015 15"

**Additional context**
I noticed that v10 was released just this morning! 🎉  Do I get to claim "first issue" for v10?

**Comment by jamuhl** [comment]
Just made an install...got those files around

<img width="434" alt="screenshot 2019-02-06 at 20 54 28" src="https://user-images.githubusercontent.com/977772/52369633-711db280-2a51-11e9-803d-e8b9df5d9d8d.png">

also:

https://unpkg.com/react-i18next@10.0.0/dist/commonjs/index.js
https://unpkg.com/react-i18next@10.0.0/dist/es/index.js

**Comment by SekibOmazic** [comment]
Libs:
```
"react-i18next": "^10.0.0",
"react": "^16.8.1",
"react-dom": "^16.8.1",
"i18next": "^14.0.1",
```

**Comment by lvl99** [comment]
I've deleted and reinstalled, seems to be back.

It was really strange because I removed my `node_modules` folder twice and attempted to reinstall everything twice, and this time I just deleted the single folder and reinstalled.

**Comment by panjiesw** [comment]
@SekibOmazic Imports should be just `react-i18next`. No need to use `react-i18next/hooks` in v10

**Comment by bikeshedder** [comment]
I can confirm that changing the imports from `react-i18next/hooks` to `react-i18next` works. I guess the `hooks.js` should be simply removed from the distribution as it broken and no longer needed.

**Comment by jamuhl** [comment]
@bikeshedder hooks.js will be removed in the next version - forgotten todo so.

**Comment by SekibOmazic** [comment]
@panjiesw Yes! Thanks for the hint!

**Comment by nathanredblur** [comment]
I have this error importing i18next in this way: `const {default: NextI18Next} = require('next-i18next');`
