### ISSUE TITLE
v10 I18nextProvider typings missing

### ISSUE THREAD

**Issue by panjiesw** [i18next/react-i18next#718]
**Describe the bug**
TypeScript typings doesn't include `I18nextProvider`.

**Occurs in react-i18next version**
v10.0.0

**To Reproduce**

1. `import {I18nextProvider} from 'react-i18next` in TypeScript
2. See error

```
Module '"node_modules/react-i18next/src"' has no exported member 'I18nextProvider'.ts(2305)
```

**Expected behaviour**
Typings should include `I18nextProvider`

**Comment by adrai** [comment]
Can you suggest a PR? And perhaps @rosskevin or @schettino could review...

**Comment by panjiesw** [comment]
Not now unfortunately, maybe later this night (UTC+7)

**Comment by jkeruzec** [comment]
Could you provide an upgrade guide from V9 to V10 please ? 

I saw that reactI18nextModule became initReactI18next.

I lost my withNamespaces and I don't what is replacing this ?

**Comment by Brisstor** [comment]
@jkeruzec seems like withTranslation is replacement for withNamespaces.
However, I didn't see any warnings about v10 containing some breaking changes...
I thing it would be nice to have some notification about that :)
Anyway, thanks for fast update!

**Comment by jamuhl** [comment]
> I didn't see any warnings about v10 containing some breaking changes

@Brisstor semver?!? 9.x.x -> 10.0.0 = Breaking API else it would be just 9.1.0 (additional hooks no breaking)

**Comment by Brisstor** [comment]
> > I didn't see any warnings about v10 containing some breaking changes
> 
> @Brisstor semver?!? 9.x.x -> 10.0.0 = Breaking API else it would be just 9.1.0 (additional hooks no breaking)
You're right, that makes sense, thanks

**Comment by jamuhl** [comment]
@jkeruzec @Brisstor https://react.i18next.com/latest/migrating-v9-to-v10 hopefully helps a little - contribution with your migration experiences would be very welcome.

**Comment by danielsogl** [comment]
I created an PR to fix that issue. I had the same problem after migrating to V10.
