### ISSUE TITLE
Problem with i18next and a const containing an array

### ISSUE THREAD

**Issue by JavierPons** [i18next/react-i18next#719]
I have been searching into StackOverflow. Anything found. I hope this is the correct way to ask. 
I have imported  ==>  `import i18next from 'i18next'`  in my file
After that in my json file I have the correct path ==> and I have this array inside countryList variable
 `const countryList = i18next.t([
  'name.norway',
  'name.russia',
  'name.estonia',
  'name.german',
])`
I think this is how it should be done. But this error appears in the terminal ==> Uncaught TypeError: Cannot read property 'map' of undefined.  So it doesn´t read the path, it is undefined when the arrray is wrapped  inside i18next.t
Am I doing anything wrong?

**Comment by jamuhl** [comment]
`i18next.t(AnArray)` -> https://www.i18next.com/principles/fallback#calling-with-fallback-keys

you want:
```js
const countryList = [ 'name.norway', 'name.russia', 'name.estonia', 'name.german' ].map(name => i18next.t(name));
```

**Comment by jamuhl** [comment]
and welcome back - and still basic progamming knowhow

**Comment by JavierPons** [comment]
@jamuhl thank you.  I think you misunderstood me. Anyway.  Here is where it should be used i18next. But using in many options it doesn´t work. :) for me.
`const _createMenuItems = menuItems =>
  menuItems.map((item, index) => (    
    <MenuItem key={index} value={item}>{item}</MenuItem>
  ))`

**Comment by jamuhl** [comment]
menuItems not an array i guess but some react children collection

**Comment by JavierPons** [comment]
Yes. You are right.

**Comment by JavierPons** [comment]
I will search for that. Thank you for your work!
