### ISSUE TITLE
How do make the switch from <I18n></I18n> to something similar in version 9.0.10

### ISSUE THREAD

**Issue by sabyc200** [i18next/react-i18next#722]
Hello guys,

I recently updated react-i18next from version 7.6.1 to version 9.0.10 .
Before I could wrap something with <I18n></I18n> and , when the language changed it would re-render. Now i see that this component is deprecated.

Before I had something like this 

`return (  
            <I18n> {(t) => (
                        <p>{t("some_text_to_translate")}</p>
                         //...more code here
             </I18n>`

I tried` withNamespaces` but I get errors in the parent container.
In order to do const `{ t } = this.props` I have to extend the props with `WithNamespaces` that are used for that component and this generate error in the parent component (Where the translated one is used) , something like Property `tReady is mssing in type` and `i18n is missing in type` .
I also tried `NamespacesConsumer` but got this error:

![image](https://user-images.githubusercontent.com/14923852/52411572-fb632680-2ae4-11e9-9211-a46085411c3c.png)

Something regarding the children property .

My question is , how can updated from <I18n> to something similar without getting any errors? Is there any tutorial regarding this?

I saw some example, but could not find more in depth coverage. I18n and react-i18n is an amazing work but it lacks some good documentation. Also a lot of the links the come up Google search are broke with 404, especially the ones with /component/

Thanks!

Questions should be posted on StackOverflow - I did but there was no answer

**Comment by jamuhl** [comment]
regarding lack good documentation - would be happy to accept PR on the documentation 🙏

**Comment by sabyc200** [comment]
>  but as usual i can't make anything out of the TS errors
> 
Exactly my thoughts regarding TS errors... My thinking is that `export const NamespacesConsumer: React.ComponentClass<NamespacesConsumerProps>;` thakes a `children` prop which is not optional so somehow it has to passed down to NamespacesConsumer - but that's a wild guess as I not so well trained in TS.

**Comment by rosskevin** [comment]
Look at the usage in the `tests/typescript` directory.  All you have to do is rename your `I18n` to use v10 `Translation`.  I did one rename and everything worked out of the box.

e.g.
```tsx
function basic() {
  return <Translation>{(t) => <div>{t('key1')}</div>}</Translation>;
}
```

**Comment by sabyc200** [comment]
After a break and some more investigation I found that the error was caused by a misplaced `}` . The TS error was a little bit misleading about this. 
Thanks for the quick response.

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
