### ISSUE TITLE
How to make work i18next with Material-UI Component MenuItem?

### ISSUE THREAD

**Issue by JavierPons** [i18next/react-i18next#724]
I appreciate your patience. I liked i18next and I want to learn more.  I carry on asking.  At the end of my large app translation I have a dead point.  Here it is:
    `const _createMenuItems = menuItems =>
menuItems.map((item, index) => (    
  <MenuItem key={index} value={item}>{item}</MenuItem>
))`
MenuItems is a component of the library MaterialUI exactely @material-ui/core": "^3.6.1".

if I type :
`const _createMenuItems = menuItems =>
 menuItems.map((item, index) => (
 <MenuItem key={index} value={item}>{i18next.t(item)}</MenuItem>
 ))`

It doesn´t appear any error but the app doesn´t show the text. It is empty. Nothing there.
I have try many things to solve it. Maybe it is a small thing that I can´t see or my "juniority"

**Comment by jamuhl** [comment]
It appreciate your appreciation - but i'm not a teacher - i'm a module maintainer doing OSS for free - so please try to find someone having the time and is willing to teach you

**Comment by JavierPons** [comment]
For more information this issue is not related to i18n. It is related to Material-UI and concretely to Wrapping components.
