### ISSUE TITLE
Loop when using namespace which doesn't exist

### ISSUE THREAD

**Issue by MartinTichovsky** [i18next/react-i18next#725]
**Describe the bug**
When using react-i18next with typescript and call function withTranslation() with namespace which doesn't exist (for example namespace missing in some dictionary, or someone forgot to put namespace to dictionary), then running application cause loop (processor high performance and endless loading).

**_Edit_**
This problem is even in **react** JS example project from react-i18next, just edit i18.init resource like bellow and then edit App.js on line 13 to `const Welcome = withTranslation("test")(LegacyWelcomeClass);` 

`i18n
  .use(Backend)
  .use(LanguageDetector)
  .use(initReactI18next).init({
    fallbackLng: "en",
    debug: true,
    interpolation: {
      escapeValue: false
    },
    resources: {
      de: {
        translation: {
          title: "Willkommen zu react und react-i18next",
          description: {
            part1:
              "Um loszulegen, ändere <1>src/App(DE).js</1> speicheren und neuladen.",
            part2:
              "Ändere die Sprachen zwischen deutsch und englisch mit Hilfe der beiden Schalter."
          }
        }
      },
      en: {
        translation: {
          title: "Welcome to react using react-i18next",
          description: {
            part1: "To get started, edit <1>src/App.js</1> and save to reload.",
            part2:
              "Switch language between english and german using buttons above."
          }
        }
      }
    }
  })`

**Occurs in react-i18next version**
10.0.1

**To Reproduce**
Just run the example in attachment

When you edit in Example/App.tsx row 18 to `const Welcome = withTranslation()(LegacyWelcomeClass);`, everything will be fine.

**Expected behaviour**
When i call namespace which doesn't exist, i expect to return text in t("tittle").

**OS (please complete the following information):**
Windows 10 x64 1809

- Browser: [Chrome  71.0.3578.98]

**Additional context**
This problem is observable with direct resources in 18n.init(), if i use backeend loader, then everything seems to be ok, but i don't want to use backend, i want to have languages dictionaries in .ts files.

[react.zip](https://github.com/i18next/react-i18next/files/2844550/react.zip)

**Comment by jamuhl** [comment]
could you please retry with react-i18next@10.0.2

**Comment by MartinTichovsky** [comment]
It works, thank you!

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
