### ISSUE TITLE
Optional children for Trans component

### ISSUE THREAD

**Issue by maksis** [i18next/react-i18next#727]
https://react.i18next.com/latest/trans-component#alternative-usage fails with error `Property 'children' is missing in type '{ defaults: string; values: { what: string; }; components: Element[]; }' but required in type 'TransProps'.` when using version 10.0.3

**Comment by basslagter** [comment]
Yes, same here. Fixed it by providing a child <Trans>{}</Trans> but does not seem like a sustainable solution

**Comment by jamuhl** [comment]
A pull request would be welcome...guess @rosskevin will then review that

**Comment by menthena** [comment]
Could you please check this? https://github.com/i18next/react-i18next/pull/728

**Comment by basslagter** [comment]
Thanks!
