### ISSUE TITLE
V10 Loading namespaces issue

### ISSUE THREAD

**Issue by jleeraert-conclusion** [i18next/react-i18next#729]
Hi I'm using React I18next for our front-end project. After upgrading to v10 today, I've noticed that only default namespaces are being loaded, not the ones I'm loading via ```	withTranslation('ns')```

Any idea if there's something I could have missed?

i18n configuration:
```

i18n.use(LanguageDetector)
	.use(Locize)
	.use(initReactI18next)
	.init({
		load: 'languageOnly',
		fallbackLng: 'en',
		saveMissing: true,
		saveMissingTo: 'all',
		defaultNS: 'common',
		debug: true,
		interpolation: {
			escapeValue: false // not needed for react as it escapes by default
		},
		preload: ['en', 'nl'],
		ns: ['common', 'alerts'],
		backend: {
			// the id of your locize project
			projectId omitted
			// add an api key if you want to send missing keys
			apiKey: omitted
			// the reference language of your project
			referenceLng: 'en'
		},
		// special options for react-i18next
		// learn more: https://react.i18next.com/components/i18next-instance
		react: {
			wait: true,
			bindStore: false,
			bindI18n: 'languageChanged',
			nsMode: 'fallback'
		}
	});
```

**Comment by jamuhl** [comment]
We‘re aware of it. Seems a little edge case in the ready functinality passing while it shoudn‘t. 

Will provide a fix asap.  

Von meinem iPhone gesendet

**Comment by jleeraert-conclusion** [comment]
Okay thank you for looking into it :)

**Comment by jamuhl** [comment]
should be fixed in react-i18next@10.0.5

**Comment by jleeraert-conclusion** [comment]
I can confirm that the issue has been resolved now, thanks!

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
