### ISSUE TITLE
Provide better name for Wrapper function in withTranslation HOC

### ISSUE THREAD

**Issue by ioliver** [i18next/react-i18next#730]
Using withTranslation HOC leads to some `Wrapper` elements appear in a components tree in a React DevTools. Would be nice to rename it into something more obvious like `TranslationWrapper`

**Comment by jamuhl** [comment]
You're right...will rename the Wrapper functions to something more "meaningful"

**Comment by jamuhl** [comment]
Will change in next version: https://github.com/i18next/react-i18next/commit/170aebaa1e26b6ae9e3c0c7845f83ec59df815d6

won't make a publish to npm just for this change - hope that is ok for you?

**Comment by jamuhl** [comment]
published in react-i18next@10.1.0
