### ISSUE TITLE
useTranslation with multiple namespaces

### ISSUE THREAD

**Issue by cthurston** [i18next/react-i18next#732]
Loading multiple namespaces does not work as described in the docs.
```js
useTranslation(['ns1', 'ns2'])
```

**Occurs in react-i18next version**
react-i18next@^10.0.0

**To Reproduce**

My config:
```js
import i18n from 'i18next'
import Backend from 'i18next-xhr-backend'
import LanguageDetector from 'i18next-browser-languagedetector'
import { initReactI18next } from 'react-i18next'

const defaultOptions = {
  fallbackLng: 'en',
  ns: ['general'],
  defaultNS: 'general',
  fallbackNS: 'general',
  nsSeparator: '::',
  keySeparator: '::',
  debug: true,
  interpolation: {
    escapeValue: false, // not needed for react!!
  },
  react: {
    wait: false,
  },
  backend: {
    loadPath: '/api/locales/{{lng}}/{{ns}}',
    allowMultiLoading: false,
    crossDomain: true,
    withCredentials: false,
  },
}

i18n
  .use(Backend)
  .use(LanguageDetector)
  .use(initReactI18next)
  .init(defaultOptions)

export default i18n
```

Then in a component:
```js
const {t} = useTranslation(['target_description', 'target'])
console.log(t('target:rp::title'))  // not found
console.log(t('rp::description')) // works great!
```

The debugger kicks out the following:
i18next::backendConnector: loaded namespace target for language en 
i18next::backendConnector: loaded namespace target_description for language en
i18next::translator: missingKey en-US target_description target:rp::title target:rp::title

The debugger indicates that it doesn't seem to be looking in the correct namespace.

**Comment by jamuhl** [comment]
Did you try with v10.0.5?!? should be fixed

**Comment by jamuhl** [comment]
and in your case as nsSeparator is set to :: it should be `console.log(t('target::rp::title'))`

**Comment by cthurston** [comment]
Okay, I miss read the docs.  I thought the single colon was a special ns selection.

Works with the correct ns separator!

**Comment by jamuhl** [comment]
would be normally: `console.log(t('target:rp.title'))` but you set:

```js
  nsSeparator: '::',
  keySeparator: '::',
```
