### ISSUE TITLE
Translations loaded despite using initialStore prop

### ISSUE THREAD

**Issue by crash7** [i18next/react-i18next#733]
Hello! I was updating the razzle-ssr example to use Hooks and noticed that even with the store pre-populated with the initial data, the translations are still trying to be loaded (triggering a suspense, making the page render again discarding the SSR render). Is this expected? Or a bug in xhr-backend?

I have another project with v9 and see the same behavior there.

The WIP can be found here: https://github.com/crash7/react-i18next/tree/example/razzle-ssr/example/razzle-ssr

**Comment by jamuhl** [comment]
highly appreciate your effort getting that sample up again.

https://github.com/crash7/react-i18next/blob/example/razzle-ssr/example/razzle-ssr/src/server.js#L31

you're only telling i18next to preload languages...but it has no information about which namespaces it has to load, init with:

```js
i18next.init({
  ns: ['ns1', 'ns2'], // all namespaces used
  defaultNS: 'ns1', // the default to use
  //...
```

I once had a helper in one of the next.js samples:
https://github.com/i18next/react-i18next/blob/v8.3.3/example/nextjs/lib/getAllNamespaces.js

used like:
https://github.com/i18next/react-i18next/blob/v8.3.3/example/nextjs/server.js#L21

might be helpful?

**Comment by crash7** [comment]
Actually the full i18n config is here: https://github.com/crash7/react-i18next/blob/example/razzle-ssr/example/razzle-ssr/src/i18n.js#L11

And this is the output of the debug info in the server console: 
```
i18next: initialized { debug: true,
  initImmediate: false,
  ns: [ 'translations' ],
  defaultNS: 'translations',
```

I didn't know you could extend the config doing that, but even if I declare the ns in the server config, the behavior is the same.

```diff
  .init(
    {
      preload: ['en', 'de'],
+     ns: ['translations'],
+     defaultNS: 'translations',
      backend: {
        loadPath: `${appSrc}/locales/{{lng}}/{{ns}}.json`,
        addPath: `${appSrc}/locales/{{lng}}/{{ns}}.missing.json`,
      },
    },
    () => {
      server
```

Another thing that validates the config, is that I get the translations in SSR (this means that the i18n is getting preloaded as expected) and also the initialStore data in the source HTML:

```
window.initialI18nStore = JSON.parse('{"en":{"translations":{"message":{"welcome":"Welcome to Razzle with i18n"},"guideline":"To get started, edit <1>src/App.js</1> or <3>src/Home.js</3> and save to reload."}}}');
```

I guess this is not expected? And `i18next` it's not handling well when the ns is already in the resources (https://github.com/i18next/i18next/blob/master/src/BackendConnector.js#L45).

**Comment by crash7** [comment]
Ok, I did some digging and the reason of this could be that the initialStore is being populated to [late](https://github.com/crash7/react-i18next/blob/example/razzle-ssr/example/razzle-ssr/src/client.js#L12), since the init of i18next engine is running way before that part. If I manage prepopulate the store directly in the init of i18next, the issue should be solved.

**Comment by crash7** [comment]
Found that using the [resources](https://github.com/i18next/react-i18next/commit/013ac483b637a3e0e1eddab5c66ee6b27e1004c4) option, I can avoid the flickering because the store gets populated from the beginning.

Funny thing: If do that and the request a `ns` that is not included in that initial data, I get an infinite loop that crashes the tab. Probably because of the following line:
https://github.com/i18next/i18next/blob/master/src/i18next.js#L144

Using the `partialBundledLanguages` option triggers the `Suspense` fallback as expected, without the infinite loop.

Could you confirm if this is the right approach? If so I can create the PR for the example (and maybe another one for the docs?) and close this one.

**Comment by jamuhl** [comment]
Guess i spotted the problem: Seems passing down initialStore works but you did not upgrade the way it gets passed to i18next:

https://github.com/crash7/react-i18next/blob/example/razzle-ssr/example/razzle-ssr/src/client.js#L12

```js
  <I18nextProvider
    i18n={i18n}
    initialI18nStore={window.initialI18nStore}
    initialLanguage={window.initialLanguage}
  >
```

=> In v10 the only thing the Provider does is passing down i18n via context - it does not handle the initial store stuff.

The initialStore/initialLanguage appending is done in `useSSR` or `withSSR` -> https://react.i18next.com/latest/ssr

**Comment by crash7** [comment]
Right, forgot that part of the docs. Let me update the example with that, although if withSSR is after the init, it might be the same. 

Meanwhile, what about the same scenario in v9?

**Comment by jamuhl** [comment]
Not having todo with init...has todo with setting before using any `t` 

for v9 any would set this I18nextProvider or withNamespaces HOC

**Comment by crash7** [comment]
Ok, I don't think that's the case but let's find out.

**v10: hydrate and useSSR**
Changed the client to do as you said: https://github.com/crash7/react-i18next/commit/a50172121784e76a4ce73717d0ee9cd33409a0a5

Still getting:
- loading message of `Suspense`
- XHR request to `translation.json`

Also, the docs [here](https://react.i18next.com/latest/ssr#using-the-usessr-hook) have the parameters in the wrong order
```diff
-  useSSR(initialLanguage, initialI18nStore);
+  useSSR(initialI18nStore, initialLanguage);
```

Based on that you said:
>Not having todo with init...has todo with setting before using any `t`

I went ahead and changed the hydrate to something like:
```
hydrate(
  <div />,
  document.getElementById('root'),
);
```
And checking the network tab, I see a request to `translations.json` going out:
![image](https://user-images.githubusercontent.com/1450075/52788232-1383fa00-303f-11e9-9b5d-87ee6c69436b.png)


**v9**
As you can see in the old example: https://github.com/i18next/react-i18next/blob/master/example/v9.x.x/razzle-ssr/src/client.js#L9 (despite that it's a bit wrong cause it's not using hydrate - I may update that once we sort this out), the behavior is almost the same: I have a XHR request to all the `ns` in the configuration.

I didn't tried passing the data in the `withNamespaces` HOC, but based on the code, it will be the same behavior.

**Comment by jamuhl** [comment]
on client is `ns: []` on init? else yes...will load

**Comment by crash7** [comment]
No, `ns: ['translations']`: https://github.com/crash7/react-i18next/blob/example/razzle-ssr/example/razzle-ssr/src/i18n.js#L10

**Comment by jamuhl** [comment]
try setting it to empty array and only on serverside add all namespaces. Or on client setting resource on init to empty object should also avoid loading on init

**Comment by crash7** [comment]
Tried with `ns: process.browser ? [] : ['translations'],` and now the XHR request it's gone, but `Suspense` fallback it's still being triggered.

**Comment by jamuhl** [comment]
useSSR run before useTranslation?

**Comment by crash7** [comment]
Yes:
```

const BaseApp = () => {
  useSSR(window.initialI18nStore, window.initialLanguage);
  return (
    <Suspense fallback={<div>loading i18n...</div>}>
      <BrowserRouter>
        <App />
      </BrowserRouter>
    </Suspense>
  );
}
```

**Comment by jamuhl** [comment]
Will need to checkout your repo tomorrow and debug through it

**Comment by jamuhl** [comment]
Ok had the time to check. Main Problem seems a condition that i18next not yet finished initializing while already rendering -> the hook rejects setting ready: true and triggers a suspense if i18next not yet initialized completely.

in react-i18next@10.1.2 i changed that check to also run through if initialI18nStore is set

So i got it working by updating dependecies to:

```js
    "babel-cli": "6.26.0",
    "babel-core": "6.26.3",
    "babel-eslint": "10.0.1",
    "babel-jest": "24.1.0",
    "babel-plugin-macros": "^2.5.0",
    "babel-preset-es2015": "6.24.1",
    "babel-preset-react": "6.24.1",
    "babel-preset-stage-0": "6.24.1",
    "babel-register": "6.26.0",
    "razzle": "2.4.1",
    "react": "16.8.2",
    "react-dom": "16.8.2",
    "react-router-dom": "4.3.1",
    "react-i18next": "10.1.2",
    "i18next": "15.0.4",
    "i18next-browser-languagedetector": "3.0.0",
    "i18next-express-middleware": "1.7.1",
    "i18next-node-fs-backend": "2.1.1",
    "i18next-xhr-backend": "2.0.0"
```

=> most important i18next, react-i18next


further i updated /src/i18n.js to finally use import/export (node supports that meanwhile)

```js
import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import XHR from 'i18next-xhr-backend';
import LanguageDetector from 'i18next-browser-languagedetector';

const options = {
  fallbackLng: 'en',
  load: 'languageOnly', // we only provide en, de -> no region specific locals like en-US, de-DE
  // have a common namespace used around the full app
  ns: ['translations'],
  defaultNS: 'translations',

  saveMissing: true,
  debug: true,

  // cache: {
  //   enabled: true
  // },

  interpolation: {
    escapeValue: false, // not needed for react!!
    formatSeparator: ',',
    format: (value, format, lng) => {
      if (format === 'uppercase') return value.toUpperCase();
      return value;
    },
  },
  wait: process && !process.release,
};

// for browser use xhr backend to load translations and browser lng detector
if (process && !process.release) {
  i18n
    .use(XHR)
    .use(initReactI18next)
    // .use(Cache)
    .use(LanguageDetector)
}

// initialize if not already initialized
if (!i18n.isInitialized) {
  i18n.init(options);
}

export default i18n;
```

and in client.js i changed:

```js
// import i18n from './i18n'; ---> would warn for unused variable
import './i18n';
```

**Comment by crash7** [comment]
Thank you for debugging this!
If the problem is that i18n is still loading, maybe I could change the hydrate to be inside the i18n callback - that may help that scenario.
Will try your fix and update the examples code. 

Thanks again!

**Comment by jamuhl** [comment]
should be ok with above changes...at least worked on my machine ;)
