### ISSUE TITLE
Trans component: variable name required to match variable in translation string

### ISSUE THREAD

**Issue by robertcoopercode** [i18next/react-i18next#734]
**Is your feature request related to a problem? Please describe.**

It would be very useful if we could pass in a variable that does not require to be named the same as what is used in the translation JSON file.

Here's an example of how things work now:

```jsx
<Trans i18nKey="UNREAD_MESSAGES" count={count}>
    Hello <strong>{{ name }}</strong>,
    you have {{ count }} unread message.
    <GoTo to="#msgs">Go to messages</GoTo>.
</Trans>
```

In translations file:

```json
{
	"UNREAD_MESSAGES": "Hello <1>{{name}}</1>, you have {{count}} unread message. <5>Go to message</5>.",
	"UNREAD_MESSAGES_plural": "Hello <1>{{name}}</1>, you have {{count}} unread messages.  <5>Go to messages</5>."
}
```

**Describe the solution you'd like**

Here's how I propose things should be able to work:

```jsx
<Trans i18nKey="UNREAD_MESSAGES" count={messageCount}>
    Hello <strong>{{ employeeName }}</strong>,
    you have {{ messageCount }} unread message.
    <GoTo to="#msgs">Go to messages</GoTo>.
</Trans>
```

In translations file:

```json
{
	"UNREAD_MESSAGES": "Hello <1>{{name}}</1>, you have {{count}} unread message. <5>Go to message</5>.",
	"UNREAD_MESSAGES_plural": "Hello <1>{{name}}</1>, you have {{count}} unread messages.  <5>Go to messages</5>."
}
```

As of right now, it's impossible to have the multiple instances of the `<Trans>` component which use the same translation key, but have have different values for the variables. For example, the following would be impossible to display in the same React component:

```jsx
<Trans i18nKey="UNREAD_MESSAGES" count={count}>
    Hello <strong>{{ name }}</strong>,
    you have {{ count }} unread message.
    <GoTo to="#msgs">Go to messages</GoTo>.
</Trans>
<Trans i18nKey="UNREAD_MESSAGES" count={messageCount}>
    Hello <strong>{{ employeeName }}</strong>,
    you have {{ messageCount }} unread message.
    <GoTo to="#msgs">Go to messages</GoTo>.
</Trans>
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jamuhl** [comment]
```js
<Trans i18nKey="UNREAD_MESSAGES" count={messageCount}>
    Hello <strong>{{ employeeName }}</strong>,
    you have {{ messageCount }} unread message.
    <GoTo to="#msgs">Go to messages</GoTo>.
</Trans>
<Trans i18nKey="UNREAD_MESSAGES" count={messageCount}>
    Hello <strong>{{ employeeName }}</strong>,
    you have {{ messageCount }} unread message.
    <GoTo to="#msgs">Go to messages</GoTo>.
</Trans>
```

wouldn't that just display the same thing twice like expected?

**Comment by jamuhl** [comment]
And why not just:

```js
<Trans i18nKey="UNREAD_MESSAGES" count={messageCount}>
    Hello <strong>{{ name: employeeName }}</strong>,
    you have {{ count: messageCount }} unread message.
    <GoTo to="#msgs">Go to messages</GoTo>.
</Trans>
```

**Comment by robertcoopercode** [comment]
> ```js
> <Trans i18nKey="UNREAD_MESSAGES" count={messageCount}>
>     Hello <strong>{{ employeeName }}</strong>,
>     you have {{ messageCount }} unread message.
>     <GoTo to="#msgs">Go to messages</GoTo>.
> </Trans>
> <Trans i18nKey="UNREAD_MESSAGES" count={messageCount}>
>     Hello <strong>{{ employeeName }}</strong>,
>     you have {{ messageCount }} unread message.
>     <GoTo to="#msgs">Go to messages</GoTo>.
> </Trans>
> ```
> 
> wouldn't that just display the same thing twice like expected?

Oops, I miss wrote my example. I've fixed it.

**Comment by robertcoopercode** [comment]
> And why not just:
> 
> ```js
> <Trans i18nKey="UNREAD_MESSAGES" count={messageCount}>
>     Hello <strong>{{ name: employeeName }}</strong>,
>     you have {{ count: messageCount }} unread message.
>     <GoTo to="#msgs">Go to messages</GoTo>.
> </Trans>
> ```

Oh nice, I did not know you could do that. I didn't realize that `{{ count }}` was just an object shorthand for `{{ count: count }}`.

Thanks for the explanation!
