### ISSUE TITLE
Cannot pass several components to <Trans /> 

### ISSUE THREAD

**Issue by brumeregan** [i18next/react-i18next#737]
**Describe the bug**
I try to pass several components created by map function to Trans component, but for now it renders only the first wrapper element

**Occurs in react-i18next version**
npm module version 10.0.5

**To Reproduce**

1. Create Trans with components property ```[ <ul>{['item1', 'item2'].map((item) => (<li key={item}>{item}</li>))}</ul>]```
2. In translation.json: "test": "some list: <0></0>"
3. See that it renders only the ul

Also, if I pass iterable component to a values property, it renders [object Object], because values property cannot accept objects.

**Expected behaviour**
I want to pass whole component as a translation variable,

**Sample to see**
https://codesandbox.io/s/ojqxzpw86y

**Comment by jamuhl** [comment]
Can't work...the Trans component evaluates it's children -> there is only one child which is a map function...no chance to get that to work...not even the length is save to be used in translation string

You will do something not using the Trans component but using directly `t` function

```js

<ul>{['item1', 'item2'].map((item) => (<li key={item}>{t(item)}</li>))}</ul>

```

**Comment by brumeregan** [comment]
@jamuhl item isn't translation key, it just some text variable that should be rendered in a list

**Comment by iaroslavshvets** [comment]
Hi! Having the same issue. Basically the case is this:
I have a text, where i have to pass array values, each of them should be wrapped in bold.

Currently the only option is (pseudo-code):

1)
```
<Trans id="first_part_of_text_id" />
<ul>
   {values.map((value) => <b>{value}</b>}
</ul>
<Trans id="second_part_of_text_id" />
```
But position of array may vary depending of the language, so this is not an option.

In previous versions of react-i18next one could pass this mapped array as variable to the translation and use later like `first part {{list}} second part`, but now we can't pass react as variables,
so it leaves us with using Trans children, where we lose everything inside <ul> tag and don't have access to it.

Solution may be in parsing this map as well and using it in translation like `first part <0><1></1></0> second part` or/alongside with passing some flag to Trans like `includeNestedChildren={true}`. This case is relatively rare, but sadly - pretty valid one.

**Comment by jamuhl** [comment]
@brumeregan still also Trans component would translate it as string `<0><0>item1</0><1>item2</1></0>` only difference -> Trans would keep it in one translation string - map with t multiple

@iaroslavshvets Trans did not change from v9 -> v10 but you can get an array from i18next translations anf map that https://www.i18next.com/translation-function/objects-and-arrays#arrays

**Comment by brumeregan** [comment]
@jamuhl hm, I cannot know the count of element in a list, so in translation I can't use <0>item1</0><1>item2</1>.

**Comment by jamuhl** [comment]
@brumeregan that's the reason why you can't use Trans -> needs to be fixed...it's not for translating lists.

**Comment by brumeregan** [comment]
@jamuhl But also I cannot use `t` as it doesn't allow components, yes?

**Comment by iaroslavshvets** [comment]
These values, that need to be included in translation string are dynamic. I get those values from server they are not hardcoded. Example:
```
componentDidMount() {
   fetchValuesFromBackend().then((values) => {
      this.setState({values});
   });
}

render() {
   if (!this.state.values) {
      return null;
   }
   return (
     <Trans i18nKey="translation_id">
        <ul>{values.map((value) => <b>{value}</b>)}</ul>
     </Trans>
   );
}
```

* where translation_id is "start of the list <0></0> end of the list"
** What i get is `start of the list <ul></ul> end of the list`

How can i render nested array?

**Comment by jamuhl** [comment]
So `values` is an array of strings you like to write in bold, let's make it concrete:

values = ['red', 'blue', 'green']

and you like to translate them to 

```
<ul><li><b>Rot</b></li><li><b>Blau</b></li><li><b>Grün</b></li></ul>
```

and sometimes you get:

values = ['yellow', 'black']

So you like

```
<ul><li><b>Gelb</b></li><li><b>Schwarz</b></li></ul>
```

Than do it like:

```js
   fetchValuesFromBackend().then((values) => {
      this.setState({values});
   });
}

render() {
  const { t } = this.props; // using withTranslation (or withNamespaces if v9)
   if (!this.state.values) {
      return null;
   }
   return (
     <Trans i18nKey="translation_id">
        <ul>{values.map((value) => <li><b>{t(`colors.${value}`)}</b></li>)}</ul>
     </Trans>
   );
}
```

**Comment by jamuhl** [comment]
@brumeregan no t can't handle components. But where you have components -> all you got is strings in an array:

`<ul>{['item1', 'item2'].map((item) => (<li key={item}>{item}</li>))}</ul>`

if you're items are components got from backend ---> nonnonoonoo, wrong

**Comment by iaroslavshvets** [comment]
I don't need to translate value passed from backend. Let's say it's IP address. They are totally different and random. I just need to wrap it in bold and include in the correct place in resulting rendered component. These values are not and not supposed to be translated. 

Bottom line: I have array of totally random values, which are not supposed to be translated, but my be wrapped in React component and passed to translation as value/tag/whatever

**Comment by brumeregan** [comment]
@jamuhl no, that not what I was talking about.
I need to fetch from backend some data, for example, list of cats names, and on frontend I want to render it in a components, for example, each name in a <strong></strong> tag.
And in translation I want to have something like this:
"cats": "These are my cats: {{listOfCatsNames}}"
So in this case in some other languages translator could translate as "{{listOfCatsNames}} are my cats",
And on fronted it should render as:
"These are my cats: <strong>cat1</strong>, <strong>cat2</strong>"
But I don't know how many cats user have

**Comment by jamuhl** [comment]
@iaroslavshvets you don't need value translated just bold so don't use Trans...don't even think about passing it to Trans...

@brumeregan 

```js
<p>{t('MyCatsText'}{['cat1', 'cat2'].map((item) => (<b key={item}>{item}</b>, ))}
```

**Comment by iaroslavshvets** [comment]
OK, I got your point. But how do you suggest to solve the issue, that this list may be in different position, depending of the language?

**Comment by brumeregan** [comment]
@jamuhl but I need this list in my translation, because of
```So in this case in some other languages translator could translate as "{{listOfCatsNames}} are my cats" ```

**Comment by jamuhl** [comment]
@brumeregan than don't use map but a standalone component

```js
function Cats({items}) {
  return <li>{items.map((item) => (<b key={item}>{item}</b>, ))}</li>
}




     <Trans i18nKey="translation_id">
        So in this case in some other languages translator could translate as <Cats items={['cat1', 'cat2']}are my cats
     </Trans>
```

**Comment by brumeregan** [comment]
@jamuhl oh, thanks, working solution! 😃

**Comment by iaroslavshvets** [comment]
Creating a separate react component works. Thanks. I'd tried to pass function, result of which is ignored/nested components. So yeh, moving anything nested to separate component - turned out to be the only viable option. Thanks

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
