### ISSUE TITLE
Documented Integration with momemnt.js does not work

### ISSUE THREAD

**Issue by draukadin** [i18next/react-i18next#738]
I've been following the documentation here: https://www.i18next.com/translation-function/formatting to include moment.js with i18next-react and the documentation does not describe a process that will actually work.

Here is my i18n.init()  The log statement never shows up in my browser logs so this code does not appear to be executed.

```
import i18n from 'i18next';
import Backend from 'i18next-xhr-backend';
import ICU from 'i18next-icu';
import LanguageDetector from 'i18next-browser-languagedetector';
import moment from 'moment';
import numeral from 'numeral';

i18n.use(Backend)
    .use(ICU)
    .use(LanguageDetector)
    .init({
        debug: true,
        fallbackLng: 'en-US',
        interpolation: {
            // not needed for react as it escapes by default
            escapeValue: false,
            format: function(value: any, format: any, lng: any) {
                console.log("Value: " + value + " Format: " + format + " Lng: " + lng);
                if (value instanceof Date) {
                    return moment(value).format(format);
                } else {
                    numeral.locale(lng);
                    return numeral(value).format(format);
                }
            }
        },
        load: 'currentOnly',
        backend: {
            loadPath: /i18n/{{lng}}.json'
        },
        react: {
            // ensure all required language files are loaded before rendering
            wait: true
        }
    });
export default i18n;
```

Here is how I am calling i18n
```
import React from 'react';
import { translate, InjectedTranslateProps } from 'react-i18next'
export class MyClass extends React.Component<InjectedTranslateProps> {
    render() {
        return (
            {t('date_format', {date: new Date()})}
        )
    }
}
export default translate()(MyClass)
```

If my key looks like this: ```"date_format":"{date}"``` the page will load without issue but I get no formatting applied.

If my key looks like this as described in the i18next formatting documentation: I get this error

> SyntaxError: Expected "0", [1-9] or [^ \t\n\r,.+={}#] but "{" found.

If I remove the extra set of curly braces I get this error:

> SyntaxError: Expected "date", "number", "plural", "select", "selectordinal" or "time" but "M" found.

Why would the interpolation.format function not be getting called?
Where is the documentation for the expected values in the Syntax Error message?
Where is the documentation for the syntax for the translation key value in the json?

**Comment by adrai** [comment]
probably you have not defined a format in your date_format resource => https://www.i18next.com/translation-function/formatting#basic

`"date_format":"{{date, MM/DD/YYYY}}"`

**Comment by draukadin** [comment]
Please note this part of the problem description

If my key looks like this as described in the i18next formatting documentation (which is where you linked to adrai): I get this error

    SyntaxError: Expected "0", [1-9] or [^ \t\n\r,.+={}#] but "{" found.

**Comment by adrai** [comment]
Can you reproduce the issue here: https://codesandbox.io/s/qzn50pwrvj ?

**Comment by jamuhl** [comment]
You're using i18next-icu -> i18next formatting does not get applied!!!

You will need to write ICU formatted translations...https://formatjs.io/guides/message-syntax/#formatted-argument

**Comment by draukadin** [comment]
jamuhl,
That was exactly it.  I removed ICU from my init and then changed my key to match what is documented on i18next and now it it working as expected.

Thanks for pointing out the issue and the link to the documentation for ICU formatting.
