### ISSUE TITLE
withTranslation HOC: Hooks Error without using them

### ISSUE THREAD

**Issue by toytonic** [i18next/react-i18next#739]
**Describe the bug**
After updating my project to v10 I get the following error when using the withTranslation HOC on my first component.

```
Invariant Violation: Hooks can only be called inside the body of a function component. (https://fb.me/react-invalid-hook-call)

This error is located at:
    in I18nextWithTranslation (created by Connect(I18nextWithTranslation))
    in Connect(I18nextWithTranslation) (at src/index.tsx:15)
    in PersistGate (at src/index.tsx:14)
    in Provider (at src/index.tsx:13)
    in Root (at renderApplication.js:34)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:33)
```
**Occurs in react-i18next version**
react-i18next 10.1.2

**To Reproduce**
Just use the withTranslation HOC

**Context**

Here is my setup:

```
i18n.use(initReactI18next).init({
    lng: language,
    fallbackLng: 'en',
    interpolation: {
        prefix: '%',
        suffix: '$@'
    },
    resources: {
        de: { translation: require('./messages/de-DE.json') },
        en: { translation: require('./messages/en-US.json') }
    }
});
```

Any guidance in the right direction is appreciated. Thanks a lot...

**Comment by jamuhl** [comment]
We use it: https://github.com/i18next/react-i18next/blob/master/example/react/src/App.js#L13 and got no issue...

If this is react-native - obviously react hooks are not yet supported -> comes in upcoming version

**Comment by toytonic** [comment]
Ah yes. You're right. I'm on react-native. Thanks for the hint and the fast reply.

**Comment by jamuhl** [comment]
react-native v0.59 is just around the corner - but from my own experience upgrading react-native is not the biggest fun...

If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
