### ISSUE TITLE
Add react native example for v10

### ISSUE THREAD

**Issue by faxioman** [i18next/react-i18next#741]
Hi.
After the tenth error trying using the new v10 with react native I switched back to v9.
An updated react native example would be manna from heaven :)

Thanks!

**Comment by jamuhl** [comment]
Currently you will need to use v9 with react-native or the upcoming v0.59.0 of react-native which starts supporting hooks

**Comment by pontusab** [comment]
Can confirm that it works with `v0.59.0-rc1`

**Comment by jamuhl** [comment]
@pontusab if you got a working simple sample you might contribute it to the examples folder here

**Comment by pontusab** [comment]
Sure will do, I will make a new one that I can share 👍

**Comment by pontusab** [comment]
@jamuhl https://github.com/i18next/react-i18next/pull/745
