### ISSUE TITLE
TypeError:(0, _react.useContext) is not a function

### ISSUE THREAD

**Issue by DevelopSmith** [i18next/react-i18next#742]
I have used this awesome package with React.js in the past but this is my first time to use it with React Native and I am getting the following error:

`TypeError:(0, _react.useContext) is not a function`

Here is my code:

```
import React, {Component} from 'react';
import {AppRegistry} from 'react-native';
import { Provider } from 'react-redux';
import { I18nextProvider } from 'react-i18next';
import {name as appName} from './app.json';

import App from './src/App';
import store from './src/store';
import i18n from './src/assets/i18n';

type Props = {};
class MyApp extends Component<Props> {
    render() {
		return (<I18nextProvider i18n={ i18n }>
			<Provider store={store}>
				<App />
			</Provider>
		</I18nextProvider>);
	}
}

AppRegistry.registerComponent(appName, () => MyApp);
```

![screenshot_1550378682](https://user-images.githubusercontent.com/5274944/52908511-fee27480-327f-11e9-9435-65d0940a3f24.png)

**Comment by jamuhl** [comment]
are you trying to use v10? react-native not yet supports hooks -> should land in react-native v0.59.0

**Comment by DevelopSmith** [comment]
@jamuhl Yup, I am using version `10.1.2` with react-native `0.57.7`

Which version should I use at the moment?

**Comment by adrai** [comment]
v9, until react-native gets hooks support

**Comment by adrai** [comment]
https://github.com/i18next/react-i18next/issues/741#issuecomment-464487688
