### ISSUE TITLE
Translation key is reported as missing when it exists in the translation files

### ISSUE THREAD

**Issue by lvl99** [i18next/react-i18next#747]
**Describe the bug**
I have a [test repo](https://github.com/lvl99/react-i18next-test) where I have the [following translation file](https://github.com/lvl99/react-i18next-test/blob/master/public/locales/en/translation.json):
```javascript
{
  "welcome.toReact": "Welcome {name} to React!",
  "this.is.a.test": "This is a test, {name}!",
  "this": {
    "is": {
      "another": {
        "test": "I can confirm it worked, {name}."
      }
    }
  }
}
```

When running the app the `welcome.toReact` key is replaced correctly, however for the other two keys the debug message output mentions that the keys are missing.

**Occurs in react-i18next version**
```
"i18next": "^13.1.1"
"i18next-browser-languagedetector": "^2.2.4"
"i18next-chained-backend": "^1.0.1"
"i18next-icu": "^1.0.1"
"i18next-localstorage-backend": "^2.1.2"
"i18next-xhr-backend": "^1.5.1"
"react-i18next": "^10.0.4"
```

**To Reproduce**

1. `git clone https://github.com/lvl99/react-i18next-test.git`
2. `cd react-i18next-test`
3. `npm i`
4. `npm run start`
5. Check the console to see the debug messages

**Expected behaviour**
I would expect that the translation keys would have been found and referenced within the app.

**Additional context**
I hope I've followed and understood the docs correctly! Is this _user error_ or an actual bug?

**Comment by jamuhl** [comment]
either you can have:

```js
  "welcome.toReact": "Welcome {name} to React!",
  "this.is.a.test": "This is a test, {name}!",
```

`keySeparator: false` on init

or 

```js
  "this": {
    "is": {
      "another": {
        "test": "I can confirm it worked, {name}."
      }
    }
  }
```

`keySeparator: '.'` (default) on init

but not both

**Comment by lvl99** [comment]
@jamuhl thanks for responding quickly and for a good resolution! I guess this is more a point to suggest for `i18next` that the documentation about the differences in parsing the keys using the separators (or not) should be better explained.

I had previously used `react-intl` which I think supports both string keys and nested objects so wasn't aware that it would be more strict with `i18next`.

**Comment by jamuhl** [comment]
yes...documentation might have to point that out more prominent...currently "hidden" here: https://www.i18next.com/principles/fallback#key-fallback

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project 🙏
