### ISSUE TITLE
TypeScript type definitions hook/HOC aren't correct

### ISSUE THREAD

**Issue by traverse** [i18next/react-i18next#751]
As the title already states the TypeScript type definitions aren't correct for both the hook and HOC, mainly the return type and prop definitions.

In both cases the types are missing the `ready` and `tReady` typings which I believe is just a boolean?

I read in some other issues that to fix these type definitions I should create a pull request to DefinitelyTyped but since the type definitions are now maintained here I think it should be fixed here.

Unless there is something I'm overlooking the fix is as simple as doing the following:
```typescript
export type UseTranslationResponse = [i18next.TFunction, i18next.i18n, boolean] & {
  t: i18next.TFunction;
  i18n: i18next.i18n;
  ready: boolean;
};

export interface WithTranslation extends i18next.WithT {
  i18n: i18next.i18n;
  tReady: boolean;
}
```

**Comment by jamuhl** [comment]
the `ready` / `tReady` where just added recently for the new mode `options.react.useSuspense: false`

If you like go ahead providing a PR for the typings @rosskevin will take care for review and merge.

**Comment by jleclanche** [comment]
it's also missing `suspense` in the ReactOptions

**Comment by jamuhl** [comment]
@jleclanche feel free to provide a PR including tests...as @traverse seems to be hard on time you might catch up on the PR https://github.com/i18next/react-i18next/pull/753 ?!?

**Comment by traverse** [comment]
@jleclanche @jamuhl is the `useSuspense` option supposed to be declared on the `ReactOptions` interface declared in `i18next` itself? @jleclanche maybe you want to create a pull request for that? I'll be working on #753 today.

**Comment by Jessidhia** [comment]
Ideally it'd be done through an interface augmentation, but the way i18next is declaring its own types makes the interface non-augmentable; until it is refactored it's have to be done directly in i18next.

**Comment by jamuhl** [comment]
Feel free to discuss changes with @rosskevin as personally i'm not using typescript and won't use it until forced to

**Comment by rosskevin** [comment]
@Jessidhia 
> Ideally it'd be done through an interface augmentation, but the way i18next is declaring its own types makes the interface non-augmentable; until it is refactored it's have to be done directly in i18next.

I am not sure what you are referring to specifically.  I don't doubt there is an improvement to be made, but the comment is not specific enough.  Are you referring to the originals being hidden by namespace (for which I have no reason - I just inherited it from whomever committed previously)?
---

@jamuhl forgive me - I have not dug in - but on the surface it makes no sense to me that `i18next` has `ReactOptions`, this seems like a lack of separation of concerns.  Is there a difficult problem that simply most easily solved this way or can those options be yanked and provided via a Provider/Context here?

**Comment by jamuhl** [comment]
@rosskevin...i18next use eg. options.backend for options to pass to the backend, options.detector for language detector -> so options.react -> get passed to the i18next react plugin (-> `initReactI18next`)
