### ISSUE TITLE
reactI18next.withNamespaces is undefined since 10.0.0 (working on 9.0.10)

### ISSUE THREAD

**Issue by vieira** [i18next/react-i18next#752]
**Describe the bug**
After upgrading react-i18next from 9.0.10 to 10.1.2, `withNamespaces`, which was a function, is now undefined.

```js
// (...)
import { withNamespaces } from 'react-i18next';
// (...)
console.log(typeof withNamespaces); // undefined
```

**Occurs in react-i18next version**
Was working with 9.0.10, stopped working with 10.0.0 and is still not working on 10.1.2.

**To Reproduce**
```js
// (...)
import { withNamespaces } from 'react-i18next';
// (...)
console.log(typeof withNamespaces); // undefined
```

**Expected behaviour**
`withNamespaces` is a function

**Screenshots**
N/A

**OS**

- Device: MBP 2018 13"
- Browser: Safari 12.0.3 (14606.4.5)

**Comment by jamuhl** [comment]
v9 -> v10 ---> BREAKING

https://react.i18next.com/latest/migrating-v9-to-v10#components-v9-greater-than-v10

**Comment by jamuhl** [comment]
short `withNamespaces` is now `withTranslation`

**Comment by vieira** [comment]
@jamuhl Sorry and thanks! Maybe that should be stated in the [CHANGELOG](https://github.com/i18next/react-i18next/blob/master/CHANGELOG.md)?

**Comment by jamuhl** [comment]
https://github.com/i18next/react-i18next/blob/master/CHANGELOG.md#1000

**Comment by vieira** [comment]
@jamuhl Thanks!

**Comment by alex20465** [comment]
is there anyway to use a HOC and overwrite the default namespace ? OR do I have to define the namespace in each call ? Anyway I implement a own HOC.

**Comment by jamuhl** [comment]
@alex20465 read the docs: https://react.i18next.com/latest/usetranslation-hook#loading-namespaces
