### ISSUE TITLE
useTranslation() multiple renders

### ISSUE THREAD

**Issue by ortigozamatias** [i18next/react-i18next#754]
Component is rendering multiple times when using useTranslation hook. I have to implement a function comparing all props in React.memo() to avoid multiple rendering. This situation goes away if I avoid using the hook. The component can be completely empty.

I'm using v10.0.5.

<img width="528" alt="screen shot 2019-02-24 at 1 50 49 pm" src="https://user-images.githubusercontent.com/18308689/53302270-7fcedc80-383b-11e9-825d-a73f143b5b62.png">

<img width="1668" alt="screen shot 2019-02-24 at 1 53 24 pm" src="https://user-images.githubusercontent.com/18308689/53302290-a260f580-383b-11e9-9f23-1a24906a5c59.png">

As you can see, props aren't changing between the renders. If I don't use the translation hook this stops happening.

<img width="554" alt="screen shot 2019-02-24 at 1 57 12 pm" src="https://user-images.githubusercontent.com/18308689/53302359-26b37880-383c-11e9-8e3e-8a4bc7f1bc6e.png">

<img width="1679" alt="screen shot 2019-02-24 at 1 59 21 pm" src="https://user-images.githubusercontent.com/18308689/53302447-d983d680-383c-11e9-8bdd-3ab105b04e7b.png">

**Comment by jamuhl** [comment]
Tried to reproduce:

<img width="997" alt="screenshot 2019-02-25 at 08 40 27" src="https://user-images.githubusercontent.com/977772/53321583-2b7a3a00-38d9-11e9-8a38-d4aecb2529a0.png">

render1 is before hook, render2 logs line after hook usage

So in sample seems all ok.

Could you provide a sample having this isssue - if possible on https://codesandbox.io

**Comment by ortigozamatias** [comment]
Hi! Apparently, it's a problem with the memoization since I took it out and only one render happens. 

Thanks anyway!

You can close this of course.

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
