### ISSUE TITLE
withTranslation() does not hoist non-react statics

### ISSUE THREAD

**Issue by ghengeveld** [i18next/react-i18next#757]
See https://github.com/mridgway/hoist-non-react-statics

Example:

```js
const Container = (props) => <div>my container component</div>
const Content = (props) => <div>my compound component</div>

Container.Content = Content

export default withTranslation()(Container)
```

Now, trying to use `<Container.Content>` fails with an error:

> Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

`withTranslation` should use `hoist-non-react-statics` to expose any static properties originally defined on the component.

**Comment by jamuhl** [comment]
https://github.com/i18next/react-i18next/issues/736
