### ISSUE TITLE
Can't set plural and context to key on one moment

### ISSUE THREAD

**Issue by Konstantin4y** [i18next/react-i18next#758]
**Describe the bug**
Plural don't set, after context variable

`t("key", { context: "some", count: 2 });`

translate.json:
```
"key__some": "item"
"key_some_plural": "items"
```

Expected result: 
"items"

Observed results:
"item"

**Occurs in react-i18next version**
   "react-i18next": "^9.0.7"

**Expected behaviour**
"items"

**Observed behaviour**
"item"

**Additional context**
i18n config:
```
        .init({
          returnObjects: true,
          keySeparator: false,
          interpolation: { escapeValue: false },
          react: { wait: true },
        })
```

**Comment by jamuhl** [comment]
there are tests covering this: https://github.com/i18next/i18next/blob/master/test/translator/translator.translate.combination.spec.js#L64

they succeed -> so please provide a sample to reproduce (codesandbox)
