### ISSUE TITLE
Move away from travis-ci for i18next projects

### ISSUE THREAD

**Issue by rosskevin** [i18next/react-i18next#760]
**Is your feature request related to a problem? Please describe.**
travis-ci was purchased about a month ago by private equity.  Last week they gutted their staff and it is clear to me that they are simply going to milk it until it pays off the investment+return with minimal continued investment.

travis-ci builds are queuing for long periods of time, and hooks are sometimes unreported to github, leading to `waiting` status.

**Describe the solution you'd like**
Any ci currently being maintained/invested-in.  We use circleci, but there are plenty of good options.

**Describe alternatives you've considered**
.

**Additional context**
.

**Comment by jamuhl** [comment]
Honestly we use travis for long - so having that is more like "there were no other real options on that time" -> so nothing against switching to circleci (not my personal highest prio - but will look into it when i got some free time)

**Comment by jamuhl** [comment]
Working on it...react-i18next is done, i18next will follow soonish
