### ISSUE TITLE
[9.0.10] 'react-i18next/hooks' should reference CommonJS module

### ISSUE THREAD

**Issue by nikolay-borzov** [i18next/react-i18next#762]
**Describe the bug**
`import { initReactI18next } from 'react-i18next/hooks'` imports `es` modules. It imports `hooks.js` from the root of the package.

Jest fails to test files containing `import { useTranslation } from 'react-i18next/hooks';`

**Occurs in react-i18next version**
9.0.10

**To Reproduce**

Try to run tests for files containing `import { useTranslation } from 'react-i18next/hooks'`

**Expected behaviour**
Deafault import should be in CommonJS fromat

**Additional context**
I cannot update to `10.x` yet (if this issue fixed there)

**Comment by jamuhl** [comment]
yes, update to v10 would be the solution -> it's there are no defined entry points in v9 for hooks as entry points in package.json point to the now called legacy version

you can try: `import { ... } from 'react-i18next/dist/commonjs/hooks';`

**Comment by nikolay-borzov** [comment]
Okay. Thanks. Feel free to close the issue if it won't be fixed for `9.0.10` version. Explicit path import should work.

**Comment by jamuhl** [comment]
It's not fixable in v9 -> like said: https://github.com/i18next/react-i18next/blob/v9.x.x/package.json#L5 can either point to the "old" code (v9) or the new code (v10) but not both.

v9 was with hooks experimental to try out - not to work with in production (at that time react released hooks not even, was still alpha).

So upgrading to v10 would be the way to go -> it's 99% the same as using `import { ... } from 'react-i18next/hooks'`. As i guess you did not mix using that with using components from the old version migration should be no issue at all.

**Comment by nikolay-borzov** [comment]
I tried upgrading but I didn't figure out how to pass ref through HOC'ed component (as I understand v10 removes ref forwarding)

**Comment by jamuhl** [comment]
No need for that...you still can pass any props `innerRef` to your component setting ref on it. Just the hoc won't make that innerRef = set ref on your component -> you will need a own wrapper doing this.
