### ISSUE TITLE
How use react-i18next with Ant design Form

### ISSUE THREAD

**Issue by hrodriguez91** [i18next/react-i18next#764]
# Question about react-i18next

Hi, am using react-i18next for translate Form in ant design, and I would like to do something like this:

```js
 export default translate('common') (Form.create()(Form))
```

but it gives me and error.

What is the correct way to do this??? Thx.

**Comment by jamuhl** [comment]
Using a HOC? https://react.i18next.com/latest/withtranslation-hoc

**Comment by hrodriguez91** [comment]
Thanks for the quick response.

I am working on a large project with version of react 16.7.0 where the hocs are still not available, the react update is comming but not yet.

That's why I was wondering if there was another way to do it. Thanks in advance

**Comment by hrodriguez91** [comment]
Thanks for the quick reply.

I had already considered using HOC but they give me an error for example:

When I try to use withTranslation:

```js
import { withTranslation } from 'react-i18next';
```
the error says:

`Module '"../../../../node_modules/react-i18next/src"' has no exported member 'withTranslation'.`

I am using react-i18next@9.0.10, thanks in advance.

**Comment by jamuhl** [comment]
use v9 docs...namings are different `withNamespaces` -> https://react.i18next.com/legacy-v9/withnamespaces

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
