### ISSUE TITLE
Unable to dynamically combined multiple applications each instantiating i18next

### ISSUE THREAD

**Issue by Icehunter** [i18next/react-i18next#765]
**Describe the bug**
I have applications being compiled with i18n. Each one specifies it's own locales, and instantiation.

Previous to v10 of the module; I could host the compiled files on a CDN, add the script tags for the entry points to my host application and then use the exported UMD module names from the window to mount this components (even inside each other) and the translations would work as expected.

Since v10; in switching out and updated all the modules, I now get an error that:
```
The above error occurred in the <I18nextWithTranslation> component:
    in I18nextWithTranslation
```

Which points me to:
```
https://reactjs.org/docs/error-decoder.html?invariant=307
```

Which is:
```
Hooks can only be called inside the body of a function component. 
(https://fb.me/react-invalid-hook-call)
```

**Occurs in react-i18next version**
10+

**To Reproduce**

It's a bit convoluted and a issue of our project system but it's all we have right now.

Setup 2 applications each with the following config
```javascript
import i18next from 'i18next';
import LanguageDetector from 'i18next-browser-languagedetector';
import { initReactI18next } from 'react-i18next';
// this is a json export
import { resources } from './locales';

export default i18next
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: 'en',

    // have a common namespace used around the full app
    ns: ['translations'],
    defaultNS: 'translations',

    debug: false,

    interpolation: {
      escapeValue: false // not needed for react!!
    },

    react: {
      wait: false,
      withRef: true,
      bindI18n: 'languageChanged loaded',
      bindStore: 'added removed',
      nsMode: 'default'
    }
  });
```

Compile to a single file. Inside 1 require the other with a script tag and then mount the new one within a react component.

```
<window.MyLib/>
```

I'm not using hooks but instead using withTranslation as a HOC.

**Expected behaviour**
I expected that each application would be scoped and maintain it's own translations.

**OS (please complete the following information):**

- Device: MB 13", Latest Mojave
- Browser: Latest Chrome/FireFox

**Comment by jamuhl** [comment]
Not sure what to tell on this one...not sure what changed to make this break...but if you dig deeper and find an easy fix for it feel free to provide a PR. Else i would suggest to keep using v9...we won't stop support on that in the next months.

Reproducing this would take to much time and i guess also finding the root cause (As this is a very specific way of using it)

**Comment by Icehunter** [comment]
@jamuhl So I noticed there was another issue similar to this one.

https://github.com/i18next/react-i18next/issues/726

I followed the example there and created a new i18n.js file and this is the contents:

```javascript
import i18next from 'i18next';
import { resources } from './locales';

const instance = i18next.createInstance();

instance.init({
  resources,
  lng: 'en',
  fallbackLng: 'en',

  // have a common namespace used around the full app
  ns: ['translations'],
  defaultNS: 'translations',

  debug: false,

  interpolation: {
    escapeValue: false // not needed for react!!
  }
});

export default instance;
```

I follow a similar pattern as that code example at the end; however I've tried do this with the module being used as NPM modules and with them being UMD modules.

If I dynamically bring in the component as a UMD module; I get the hooks error. If however I bring it in as a NPM module it loads correctly BUT the translations bleed together; I assume it's because I setup a ns/defaultNS and since they are the same in both projects that is the cause of the bleeding?

I'm still unsure why packing something as a UMD module and adding them as script tags manually to the HTML page is throwing that error.

I did some further testing.

Adding scripts to page:
No issue.

This exposes window.MyApplication as a variable.

Mounting the component:

```javascript
const { default: MyApplication } = window.MyApplication;
return <MyApplication />
```

I'll try and dig into it more; but as I have to go to prod with new updates, I'll be reverting an upgrade to v10.

Maybe it's a webpack issue??? That's the major difference between the two.

**Comment by jamuhl** [comment]
if you use `import { resources } from './locales';` in both - yes those get shared between the apps.

**Comment by Icehunter** [comment]
Let me see if I can make a minimal reproduction and than that might illustrate what is happening. I'll have to strip out all our business code.

**Comment by jamuhl** [comment]
Would be awesome if you got an idea for a possible fix...currently, this is more of an edge case.

**Comment by Icehunter** [comment]
Here we go:

https://github.com/Icehunter/i18n-issue-app/tree/master

So you can see with version nine; I load both components on the page and their translations work. If I use the solutions outlined in that other closed issue; I get the hooks can't be applied. If I was to add html plugin and render application one/two using either version nine or version ten, then would work correctly and independently.

Give the way these are "dynamic" loaded using scriptjs; is that a valid use case to have more than 1 thing hosted in a parent app?

**Comment by jamuhl** [comment]
Ok made a Test with version-nine (that works):

Changed index.js in Application_one like:

```js
import React, { useState } from 'react';
import { withI18n } from 'react-i18next';
import './i18next';

function Test() {
  const [s, setS] = useState('foo');
  return <div>NOPE</div>;
}

export default withI18n()(({ t, i18n }) => {
  console.log('OneTranslations:', i18n.options.resources);
  return (
    <div>
      {t('message')}
      <Test />
    </div>
  );
});
```

So using a Hook directly (react-i18next still on v9) -> same error - so this issue is on react internals

**Comment by Icehunter** [comment]
Filed a bug report over with react as well.

**Comment by jamuhl** [comment]
Not sure but the issue title is misleading. The problem is a big edge case - It's very specific to your setup running two app bundles in one app.

**Comment by Icehunter** [comment]
I'll go update it; that was just the error I got. Sorry! :)

**Comment by jamuhl** [comment]
Nothing to be sorry...just my 50 cents. Also, i would not say i18next -> it's a problem of using hooks in that way. You just got an issue with i18next as it's using a hook - the root problem is the usage of hooks in combination with your setup.

**Comment by Icehunter** [comment]
... so CRA was internally packing react; and the included one on the index.html was colliding... our dynamic fetcher also was for some reason packing react.

I've since updated everything to get rid of these "double packing" and it works as expected now. Sorry for the alarm.

**Comment by jamuhl** [comment]
That was a difficult one...good to know if anyone else runs in the same issue.

If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
