### ISSUE TITLE
how to import reactI18nextModule from react-i18next

### ISSUE THREAD

**Issue by ultrex** [i18next/react-i18next#767]
I want to import reactI18nextModule from react-i18next of this way,  but when i try it happen this message error:

Failed to compile.
Attempted import error: 'reactI18nextModule' is not exported from 'react-i18next'.

My code:

import i18n from 'i18next';
import { initReactI18next, reactI18nextModule }  from 'react-i18next';
import Backend from 'i18next-xhr-backend';
import LanguageDetector from 'i18next-browser-languagedetector';

i18n
  .use(Backend)
  .use(LanguageDetector)
  .use(initReactI18next)
  .use(reactI18nextModule)
  .init({
    // lng: "es",
    fallbackLng: 'en',

    // have a common namespace used around the full app
    ns: ['translations'],
    defaultNS: 'translations',

    debug: true,
    interpolation: {
      escapeValue: false
    },

    react: {
      wait: true
    }

  });

I am using those versions:

    "i18next": "^15.0.4",
    "i18next-browser-languagedetector": "^3.0.1",
    "i18next-xhr-backend": "^2.0.1",

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
