### ISSUE TITLE
Infinite loop when using "cimode" as the language

### ISSUE THREAD

**Issue by Jessidhia** [i18next/react-i18next#768]
**Describe the bug**
When the language is set to `cimode`, the `hasLoadedNamespace` check always returns `false` for any given namespace, as i18next will never load any namespace when the language is `cimode` (early return in `loadResources`). This causes an infinite loop with `react-i18next` constantly trying to load the "missing" translation and always finding it to not be loaded once it's notified.

**Occurs in react-i18next version**
10.2.0

**To Reproduce**

Use any `react-i18next` component or hook while the `i18next` instance has `lng: 'cimode'` set.

**Expected behaviour**
Translations to be rendered according to the `cimode` behavior (just returns the keys as-is, optionally with a namespace prefix)

**Screenshots**

![image](https://user-images.githubusercontent.com/73085/53727732-425df500-3eb4-11e9-94d8-35372360d1dc.png)

**OS (please complete the following information):**

- Device: MBP 2018 15"
- Browser: 72.0.3626.17

**Comment by jamuhl** [comment]
could you retry with react-i18next@10.2.1

**Comment by Jessidhia** [comment]
Yep, it worked :tada:

Just a note: `i18next` itself is case-insensitive w.r.t. `'cimode'`, though the check here is case-sensitive.

**Comment by jamuhl** [comment]
will add a toLowerCase for the check and publish with the next release....ok?

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
