### ISSUE TITLE
v10 is no longer going deep in translation json

### ISSUE THREAD

**Issue by Tony4469** [i18next/react-i18next#770]
Hi,

I just migrated to v10 today and my translation keys that are deeper in my json are no longer rendered correctly 

For instance, with this translation file :
{
	"Welcome": "Hi and welcome", 
	"test": {
           "here": "This is the expected render"
       }
}

t('Welcome') renders 'Hi and welcome'
t('test.here') renders 'test.here' instead of "This is the expected render"
t('test') renders undefined

It worked fine before the migration (9.0.10 before, 10.0.0-alpha.3 now)

My code is available on github (https://github.com/Tony4469/karfur) in the /client/src folder

Thank you for your help

**Comment by jamuhl** [comment]
sure it does

**Comment by Tony4469** [comment]
> sure it does

Yeah I posted a bit quickly, I added the bug description afterwards

**Comment by jamuhl** [comment]
And it does: you disabled it: https://github.com/Tony4469/karfur/blob/master/client/src/i18n.js#L21

**Comment by jamuhl** [comment]
remove `keySeparator: false` done

**Comment by Tony4469** [comment]
> remove `keySeparator: false` done

It fixed it! Thanks a lot for your help!

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
