### ISSUE TITLE
Testing, TypeScript and WithTranslation

### ISSUE THREAD

**Issue by janhartmann** [i18next/react-i18next#772]
I just upgraded to v10 and I am experiencing issues mocking the `t` function of my component using `WithTranslation`. Take for instance this:

```tsx
interface IDurationProps extends WithTranslation { }

const Duration: React.FC<IDurationProps> = ({ t }) => { 
   return <div>My title: {t("title")}</div>
}
```

I want to test this component using:

```tsx
describe("Duration", () => {
  const props: IDurationProps = {
    i18n: null,
    tReady: true,
    t: () => "3 hrs"
  };

  it("should work", () => {
    const component = shallow(<Duration {...props} />);
    expect(component.text()).toContain("3 hrs");
  });
});
```

However, mocking the `t` function gives this error:

```
Type '"3 hrs"' is not assignable to type 'TResult'.ts(2322)
index.d.ts(491, 20): The expected type comes from the return type of this signature.
```

How to I mock this `TFunction` and `TResult` generics?

**Comment by rosskevin** [comment]
We have found no good way to do this, only using `any`, but open to better solutions.

https://github.com/i18next/i18next/blob/master/test/typescript/mock.test.ts
