### ISSUE TITLE
Translation flashes and reverts to default in razzle

### ISSUE THREAD

**Issue by twumm** [i18next/react-i18next#775]
Hi,

I setup i18next in a project I have(razzle) but the translations revert immediately after refreshing the page. 
[This video](https://drive.google.com/file/d/13ivDl6ikgzIGh2pov8TxR0Nt-0dZt-c3/view) shows that scenario.

I have almost the same setup as the razzle example but end up having this issue.
I have created a sample example(similar to what I have in my project) and still had the same issue - that is what I shared the video from.

I will appreciate if you can point out what I might be missing. [Repo is here](https://github.com/twumm/myapp-razzle-afterjs-i18n)
I attempted following [this issue](https://github.com/i18next/react-i18next/issues/733) to resolve, but no luck.

**Comment by jamuhl** [comment]
Hm...it's not even similar to the razzle example...

One of the most important parts you currently miss is passing down initial translations and language so client continues where the server stopped (having same language and data):

serverside: https://github.com/i18next/react-i18next/blob/master/example/razzle-ssr/src/server.js#L78
clientside: https://github.com/i18next/react-i18next/blob/master/example/razzle-ssr/src/client.js#L9

**Comment by twumm** [comment]
@jamuhl thanks for the feedback.
I forgot to mention I sprinkled some custom Document.js from [razzle here](https://github.com/jaredpalmer/after.js/blob/master/README.md#custom-document) and I am using v9 of react-i18next.
I am new to development so I'm likely mixing and missing some stuff.

For what you pointed out, I thought I had it here for:
serverside: https://github.com/twumm/myapp-razzle-afterjs-i18n/blob/master/src/Document.js#L55
and here for:
clientside: https://github.com/twumm/myapp-razzle-afterjs-i18n/blob/master/src/client.js#L15

I'm not sure how to go about this - especially in the Document.js file.

**Comment by jamuhl** [comment]
As i don't use razzle myself you will have to debug through this yourself. Hope you figure all out. Will close this for now as this is more a how to question than an issue with this module.

**Comment by twumm** [comment]
Hi @jamuhl, I have been able to figure it out.
What was happening was how I was setting the initialI18nStore and initialLanguage on the window var.
It turns out I could only set it by preceding initialI18nStore or initialLanguage with 2 underscores - 
window.__initialI18nStore worked but window.initialI18nStore did not.

Thanks for your tip. It pointed out what to focus on.
Cheers.

**Comment by Kaeon** [comment]
Hi twumm, do you have a working example of react-i18next with razzle and afterjs?

**Comment by twumm** [comment]
In a project I once worked on, yes.
What would you like to know?
Can you share what you have?
