### ISSUE TITLE
Outdated UseTranslationOptions interface for Typescript

### ISSUE THREAD

**Issue by logusgraphics** [i18next/react-i18next#777]
**Describe the bug**
The **UseTranslationOptions** interface lacks the **useSuspense** boolean property definition.

**Occurs in react-i18next version**
10.4.1

**To Reproduce**

1. Create a react ts app using `create-react-app <project_name> --typescript`
2. Install the latest version of i18next and react-i18next `npm i -S i18next react-i18next`
3. Use the hook in the code `const { t } = useTranslation('ns', {useSuspense: false});`
4. The compiler will throw definition error on the `UseTranslationOptions`

**Expected behaviour**
The definition should include the correct translation options for the hook

**Screenshots**
The documentation states the option property is available

![Screen Shot 2019-03-11 at 19 02 17](https://user-images.githubusercontent.com/8888278/54163708-39c76a80-4430-11e9-945f-1a881d2cfce6.jpg)

Typescript compiler throws error

![Screen Shot 2019-03-11 at 19 03 30](https://user-images.githubusercontent.com/8888278/54163753-6aa79f80-4430-11e9-9fbf-958a55004bc6.jpg)

**OS**

- Device: macOS Mojave 10.14.3
- Browser: Safari 12.0.3, Chrome 72.0.3626.121

**Comment by jamuhl** [comment]
Feel free to add a PR to add this.

**Comment by logusgraphics** [comment]
https://github.com/i18next/react-i18next/pull/778
