### ISSUE TITLE
Use Trans with input placeholder

### ISSUE THREAD

**Issue by tungst993** [i18next/react-i18next#779]
# Question about react-i18next

Questions should be posted on StackOverflow
I want code like this but it not work :(
          <Input
            placeholder = { <Trans placeholder="chats.inputMessage"></Trans }
            value={this.state.value}
            onChange={this.onChange}
            onPressEnter={this.onEnter}
          />

**Comment by jamuhl** [comment]
for placeholder use the `t` function directly

**Comment by tungst993** [comment]
oh! I will try it

**Comment by jamuhl** [comment]
Can this be closed?

**Comment by forestfuture89** [comment]
Hi @jamuhl 
Before i used this code like this .. 
    <Input size="16"
                 type="text"
                 name="search"
                 id="search"
                 placeholder="Search"
                 value={search || ''}
                 onChange={e => handleChange(e.target.name, e.target.value)}
                 required/>

I want to change placeholder with translate .. 
so i used like this 
<Input size="16"
                 type="text"
                 name="search"
                 id="search"
                 placeholder={<Trans i18nKey="home.search"/>}
                 value={search || ''}
                 onChange={e => handleChange(e.target.name, e.target.value)}
                 required/>

But this is not working well .. could you help me for this ?

**Comment by jamuhl** [comment]
@forestfuture89 the code does not even show what you tried to translate the placeholder....

could be something like: `<Input placeholder={t('key')} />`

**Comment by charles-dejager** [comment]
Hi there.  Any update.  Would love this to work.

**Comment by jamuhl** [comment]
@charles-dejager sorry but this issue is over confusing on what should be achieved -> using `t` function all code snippets provided would work...

Can you make a sample of what you try and what you like to have?

**Comment by jamuhl** [comment]
@charles-dejager or even better if you like "any update" - i would suggest opening a new issue - this one was closed - so obviously we do not work on closed issues that are solved.

**Comment by charles-dejager** [comment]
Hi there.  I have managed to solve this.

Thanks

**Comment by mithun9421** [comment]
@charles-dejager May i know how did you solve this? I am facing the same issue. A code snippet would be really helpful :-)

**Comment by lossen** [comment]
` placeholder={props.t("Element name")}` doesn't work for me
And I see a message in console **i18next.js:22 i18next::translator: missingKey ru translations Element name Element name**

**Comment by jamuhl** [comment]
@lossen you get a missing -> means there is nothing taking care of "readiness" no suspense / or no manual handling of ready. So, you might have one of this issues:

- turned off suspense and not handling ready: https://react.i18next.com/latest/usetranslation-hook#not-using-suspense
- not using useTranslation on the component using Trans: https://react.i18next.com/latest/trans-component#important-note

**Comment by TinsFox** [comment]
> @forestfuture89 the code does not even show what you tried to translate the placeholder....
> 
> could be something like: `<Input placeholder={t('key')} />`

@jamuhl Hi, jamuhl. After I use the way you said, react-i18next is working normally, but there will be a ts type of error, can this be fixed? here is my [code](https://codesandbox.io/s/upbeat-surf-krmg6i?file=/src/App.tsx)
<img width="580" alt="image" src="https://user-images.githubusercontent.com/33956589/210041776-bb255a6f-202c-4526-bc8e-e7dabbf80bcd.png">

**Comment by jamuhl** [comment]
@TinsFox https://www.i18next.com/overview/typescript#argument-of-type-defaulttfuncreturn-is-not-assignable-to-parameter-of-type-xyz should help with this

**Comment by TinsFox** [comment]
> @TinsFox [i18next.com/overview/typescript#argument-of-type-defaulttfuncreturn-is-not-assignable-to-parameter-of-type-xyz](https://www.i18next.com/overview/typescript#argument-of-type-defaulttfuncreturn-is-not-assignable-to-parameter-of-type-xyz) should help with this

It workds, thanks a lot

**Comment by SanazzSeifi** [comment]
placeHolder={t("Enter Tags") + ""}

**Comment by SanazzSeifi** [comment]
adding an empty string helped me. or even you can toUpperCase() or toLowerCase() to return an string instead of null.

**Comment by Ulugbe7** [comment]
did you fix it?

**Comment by sesamemaki** [comment]
> placeHolder={t("Enter Tags") +||""}

That worked for me.. thank you
Mine was this one:
placeholder={t("Education") + ", " + t("Culture")}
