### ISSUE TITLE
I made a component with react-i18next in webpack externals, then I can't get withTranslation function

### ISSUE THREAD

**Issue by lixuguang1988** [i18next/react-i18next#780]
**Describe the bug**
I made a component with react-i18next in webpack externals, Like this
```js
  externals: {
    react: {
      root: 'React',
      commonjs2: 'react',
      commonjs: 'react',
      amd: 'react',
    },
    'react-i18next': {
      root: 'reactI18next',
      commonjs2: 'react-i18next',
      commonjs: 'react-i18next',
      amd: 'react-i18next',
    },
}
```
I got a component CommonHeader   
    
Then I <code>npm install CommonHeader and  import CommonHeader</code>   
  
but I  get this react-i18next don't has <code> withTranslation function </code>   
  
![image](https://user-images.githubusercontent.com/3655386/54269576-8b026600-45b8-11e9-9de3-738dd594597c.png)
![image](https://user-images.githubusercontent.com/3655386/54269621-a4a3ad80-45b8-11e9-8b07-dc9962fd4678.png)

**Occurs in react-i18next version**
* "i18next": "^15.0.4"
* "i18next-xhr-backend": "^2.0.1",
* "react-i18next": "^10.2.0",

**OS (please complete the following information):**

- Device: [e.g. window 7]
- Browser: [e.g. Chrome 72.0.3626.121]

**Additional context**
hope I say clear, thanks

**Comment by jamuhl** [comment]
looks 99% like that is not react-i18next >=10.0.0 ---> Interpolate, loadNamespaces only exists in v9

**Comment by lixuguang1988** [comment]
I'm confused.  The running project  also use <code>withTranslation</code>. if I removed <code>CommonHeader</code> , the project work well. Is a project can pack two version <code>react-i18next</code>?

additional I  remove node_modules ，then npm install . It's not work
package.json
```js
    "i18next": "^15.0.4",
    "i18next-browser-languagedetector": "^3.0.1",
    "i18next-xhr-backend": "^2.0.1",
     "react-i18next": "^10.2.0",
```

**Comment by jamuhl** [comment]
idk...not an issue with react-i18next but your setup - so closing this for now as I got no idea how to help you with that
