### ISSUE TITLE
lang param from URL not respected on Chrome

### ISSUE THREAD

**Issue by BeOleg** [i18next/react-i18next#781]
Lang param is passed but the language is always default (English).
The only way to choose a language is via the select box.

Our packages:
```
    "i18next": "10.3.0",
    "i18next-browser-languagedetector": "^2.2.0",
    "i18next-xhr-backend": "1.5.1",
```

Our full code:
https://github.com/onitsoft/nexchange-open-client-react

See the issue live:
https://n.exchange/?lang=DE

Behavior:
The selected language on this URL is English.

Expected Behaviour:
The selected language should be German.

```
- Device: MBP mid 2018 15"
- Browser: 
```

Google Chrome | 72.0.3626.121 (Official Build) (64-bit)
-- | --
Revision | da3787ba355f18db7db52abf75c42afb408d656f-refs/branch-heads/3626@{#883}
OS | Mac OS X
JavaScript | V8 7.2.502.28

```

P.S
We are hiring

**Comment by jamuhl** [comment]
remove the hardcoded language on init: https://github.com/onitsoft/nexchange-open-client-react/blob/master/src/i18n.js#L12 (if setting lng on init it won't go detecting)

Then detector if not configured different will use ?lng=de (not lang param)

**Comment by BeOleg** [comment]
Thanks a bunch
https://github.com/onitsoft/nexchange-open-client-react/pull/375
will test now

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:

**Comment by BeOleg** [comment]
I did, please tell me if there is anything else I can do.

Now it works from the first time for German
https://n.exchange/?lang=DE

But does not work for Russian, and does not work for any subsequent reload :( @jamuhl 

Vielen Dank :)

**Comment by jamuhl** [comment]
https://n.exchange/?lng=de

https://n.exchange/?lng=ru

work -> if you like `lang` instead of `lng` -> change https://github.com/i18next/i18next-browser-languageDetector#detector-options (lookupQuerystring option)

**Comment by BeOleg** [comment]
Hi again.
Thanks for your answer. it is helpful 👍  :)

As far as my limited understanding goes, I have changed the lang param using the settings.
Thanks again. (the reason why it is critical is that some affiliates already use the ?lang param).

Thanks!

**Comment by BeOleg** [comment]
So basically I am re-opening my issue with the request of case insensitive lang params

**Comment by BeOleg** [comment]
If you would not accept this issue I will probably use nginx to rewrite...

**Comment by jamuhl** [comment]
```js
i18next.init({
  cleanCode: true,
  // ...
});
```

should do the trick

**Comment by jamuhl** [comment]
guess this is solved...closing now...feel free to reopen if still an issue
