### ISSUE TITLE
can i use language like 'es-ES' this?

### ISSUE THREAD

**Issue by fanam** [i18next/react-i18next#782]
resources: {
        "en-EN": {
            translations: {
                "header": "Header",
                "print": "PRINT",
                "iHaveAQuestion": "i have a question",
                "takeABreak": "Take a break",
                "cannotBeEmpty": "cannot be empty"
            }
        },
        "es-ES": {
            translations: {
                "header": "encabezamiento",
                "print": "IMPRESIÓN",
                "iHaveAQuestion": "tengo una pregunta",
                "takeABreak": "Tomar un descanso",
                "cannotBeEmpty": "no puede estar vacío"
            }
        }
    },

**Comment by jamuhl** [comment]
yes - you can

**Comment by jamuhl** [comment]
feel free to reopen if still having questions

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
