### ISSUE TITLE
Using hooks under condition

### ISSUE THREAD

**Issue by saarkuriel** [i18next/react-i18next#786]
**Describe the bug**
In `useTranslations` hook, your'e using hooks after making sure i18n is defined:
https://github.com/i18next/react-i18next/blob/master/src/useTranslation.js#L17

Basically, everything after this `if` is `else` and under condition. Therefore, If someone were to initialize `i18next` after first render, React will throw an error.

**To Reproduce**
https://codesandbox.io/s/21olj3qoj

**Expected behaviour**
Hooks should be used according to hooks rules.

**Additional Context**
I can override this behavior by initializing `i18next` to global instance instead of null but this is only a patch as you should fix the way `useTranslation` uses hooks.

**Comment by jamuhl** [comment]
What are you talking about?

`if (!i18n) {}` than you did a big mistake. That's the reason will we warn you.

**Comment by saarkuriel** [comment]
The `if` I'm talking about is in `useTranslation` hook. Please take a look in the sandbox how I'm initializing i18next instance.

**Comment by jamuhl** [comment]
and i tell you...you're initializing it wrong -> therefore you get the warning you're doing it wrong and should have passed in an i18n instance.

**Comment by jamuhl** [comment]
you prefer instead of going on there we throw an error - that's the other option

**Comment by saarkuriel** [comment]
What's the way you would recommend in order to create an i18next instance in a component library that cannot use the global instance (cause it's being hosted in apps that use i18next too), without creating new instance on every render?

BTW, initializing it differently doesn't change the fact that your'e using hooks under a condition...

**Comment by jamuhl** [comment]
BTW a condition is only a condition if it's conditional -> used right there is no condition...but honestly...if you got a better idea to inform users for there mistake...create a PR...it's open source.

Why not just create your libs clone in i18n.js: https://github.com/i18next/react-i18next/blob/master/example/react/src/i18n.js

```js
import i18next from 'i18next';
import Backend from 'i18next-xhr-backend';
import LanguageDetector from 'i18next-browser-languagedetector';
import { initReactI18next } from 'react-i18next';

const i18n = i18next.createInstance();
i18n
  // load translation using xhr -> see /public/locales
  // learn more: https://github.com/i18next/i18next-xhr-backend
  .use(Backend)
  // detect user language
  // learn more: https://github.com/i18next/i18next-browser-languageDetector
  .use(LanguageDetector)
  // pass the i18n instance to react-i18next.
  // .use(initReactI18next) // not use as it's a singleton pattern -> use I18nextProvider
  // init i18next
  // for all options read: https://www.i18next.com/overview/configuration-options
  .init({
    fallbackLng: 'en',
    debug: true,

    interpolation: {
      escapeValue: false, // not needed for react as it escapes by default
    },
  });

export default i18n;
```

**Comment by jamuhl** [comment]
And if you need to sync languages between those use the: https://www.i18next.com/overview/api#onlanguagechanged

```js
i18next.on('languageChanged', function(lng) { i18n.changeLanguage(lng); })
```

or use the SSR stuff as a workaround: https://react.i18next.com/latest/ssr#using-the-usessr-hook

**Comment by saarkuriel** [comment]
I understand. Thank you for your time and work!
