### ISSUE TITLE
ReferenceError: setImmediate is not defined

### ISSUE THREAD

**Issue by krnlde** [i18next/react-i18next#787]
**Describe the bug**
When trying to call the `callback` method provided by `read` in a plugin, the error `ReferenceError: setImmediate is not defined` is thrown into the console.

`setImmediate()` is a [non-standard API](https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate#Browser_compatibility) and shouldn't be used in frontend code.

**Occurs in react-i18next version**
Occurs in the latest version of react-i18next which is currently v10.5.0.

https://github.com/i18next/react-i18next/blob/v10.5.0/src/utils.js#L32

**OS (please complete the following information):**
```
> yarn info
{ yarn:
   '1.15.0',
  node:
   '11.11.0',
  v8:
   '7.0.276.38-node.18',
  uv:
   '1.26.0',
  zlib:
   '1.2.11',
  brotli:
   '1.0.7',
  ares:
   '1.15.0',
  modules:
   '67',
  nghttp2:
   '1.34.0',
  napi:
   '4',
  llhttp:
   '1.1.1',
  http_parser:
   '2.8.0',
  openssl:
   '1.1.1a',
  cldr:
   '34.0',
  icu:
   '63.1',
  tz:
   '2018e',
  unicode:
   '11.0' }
Google Chrome: Version 72.0.3626.121 (Official Build) (64-bit)
```
**Additional context**
We use a custom backend-plugin as described [here](https://www.i18next.com/misc/creating-own-plugins), which eventually calls the `callback` from the `read` property like here:
```js
// ...
read: function(language, namespace, callback) {
    /* return resources */
    callback(null, {
      key: 'value'
    });
  },
// ...
```

**Comment by jamuhl** [comment]
replaced with a `setTimeout(()=>(),0)` in react-i18next@10.5.1

If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:

**Comment by krnlde** [comment]
That was fast man! Thank you so much!
