### ISSUE TITLE
Is it possible to use React Components in options?

### ISSUE THREAD

**Issue by vtni** [i18next/react-i18next#789]
I want to render some React components within my translated string. I tried it with `escapeValue: false` and `{{- .. }}`, but it doesn't work. Is it even possible?

My language file:

    "credits": "Credits: {{credit}}"

The content of my React Class:
   
    import {FormattedNumber} from "react-intl";
    ...
    render() {
      return (
        <div>{i18n.t('credits', {
                    interpolation: {
                        escapeValue: false // react already safes from xss
                    },
                    credit: <FormattedNumber
                        value={99.95}
                        style="currency"
                        currency="USD"/>
                })}</div>
      )
    }

However, the output is just `Credits: [object Object]`

**Comment by jamuhl** [comment]
no you can't interpolate components in options. there is https://react.i18next.com/latest/trans-component for this

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
