### ISSUE TITLE
transSupportBasicHtmlNodes doesn't work with self-closing Trans

### ISSUE THREAD

**Issue by pwiszowaty0** [i18next/react-i18next#790]
**Describe the bug**
New feature `transSupportBasicHtmlNodes` allow to use simple html elements like `<br/>` with Trans component, but it doesn't work with `Trans` component without `props.children`

**Occurs in react-i18next version**
react-i18next@10.5.1

**To Reproduce**
translation json: 
```json
"welcome": "Hello <br/> <strong>World</strong>"
```

JSX: Trans component self-closing:
```jsx
<Trans i18nKey="welcome" />
```

Results:
html elements was render as string

but for:
```jsx
<Trans i18nKey="welcome">any valid children</Trans>
```

works as expected

**Comment by jamuhl** [comment]
Will check this on monday....

**Comment by jamuhl** [comment]
should be fixed in react-i18next@10.5.2

**Comment by pwiszowaty0** [comment]
@jamuhl It's working, Thank you for your time

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
