### ISSUE TITLE
Is there an example with Storybook 4 or 5 and react-i18n actually working?

### ISSUE THREAD

**Issue by EdwardDrapkin** [i18next/react-i18next#791]
First, I know there's an example.  It's an ancient version of storybook.  And conveniently enough it doesn't use the <Trans> component or interpolated values, so it's hard to say if it works itself.

I have tried 1000 different things and I can't seem to get react-i18n to work with storybook 4 or with storybook 5.

Here's a gist with my storybook config, the story itself, the init i18n code, and the webpack config files: https://gist.github.com/EdwardDrapkin/afcb7d079e327b8324fee99eb4577006

I always get this error:
> Objects are not valid as a React child (found: object with keys {name}). If you meant to render a collection of children, use an array instead. in Node (created by Node) in div (created by Node) in Node (created by Node) in div (created by Node) in Node (created by Node) in div (created by Node) in Node (created by Node) in div (created by Node) in Node (created by Node) in div (created by Node) in Node (created by Story) in div (created by Pre) in pre (created by Pre) in Pre (created by Story) in div (created by Story) in div (created by Story) in div (created by Story) in div (created by Story) in div (created by Story) in Story in I18nextProvider in ThemeProvider (at config.js:41) in div (at config.js:39)

I am using `<I18nextProvider />` in a decorator.

I am waiting for the i18n init to launch storybook.

The init code works outside of storybook.

I wrote the entire init18n -> mount with i18nextprovider thing in a suspense component and decorated storybook with THAT and still no dice.

I don't even know what else to try.

**Comment by EdwardDrapkin** [comment]
Upon further experimentation, it seems that the `Trans` component does NOT work inside stories, but it DOES work inside decorators.  Changing my decorator from ` <I18nextProvider i18n={i18n}>{story()}</I18nextProvider>` to ` <I18nextProvider i18n={i18n}><Trans>{story()}</Trans><I18nextProvider>` seems to have "fixed" it, but now I'm worried the Trans nesting is going to bork the actual translations (which admittedly don't exist yet, so I can't really test).

**Comment by jamuhl** [comment]
Not yet looked to deep into storybook after the update to v10 -> will provide an updated sample as soon I got the time for it...hopefully later today, tomorrow. Using Trans from within the story should work...at least used to work in the past.

**Comment by jamuhl** [comment]
https://github.com/i18next/react-i18next/tree/master/example/storybook

Sample done...would be interesting to know where you struggled

**Comment by jamuhl** [comment]
closing this for now...feel free to reopen with more details on where you struggle...

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
