### ISSUE TITLE
React Navigation

### ISSUE THREAD

**Issue by Kamez** [i18next/react-i18next#792]
Does this library work with react-navigation ?

**Comment by jamuhl** [comment]
not followed the changes there - but in the past it used to work...there should be a handful closed issues handling the topic here.

**Comment by jamuhl** [comment]
any update on this?

**Comment by alexiri** [comment]
I've been trying to get react-navigation 3.4.1 to play nicely with react-i18next 10.6.0 on react-native 0.59.1 but I haven't managed to. The problem is all the old closed issues are for previous versions of both libraries, and things have changed quite drastically since then.

I've tried using the withTranslation HOC with my components, but doing so seems to break the possibility of defining the navigationOptions in the component. Perhaps I'm missing something. Is there an up-to-date example of this somewhere?

**Comment by jamuhl** [comment]
https://react.i18next.com/latest/withtranslation-hoc#hoist-non-react-statics

**Comment by alexiri** [comment]
Thanks a lot @jamuhl, I was missing that bit! I'm new to react, so I don't really know what I'm doing. The amount of boiler-plate increases some more...

```
export default connect(
  mapStateToProps,
  mapDispatchToProps
)(hoistStatics(withTranslation()(SettingsScreen), SettingsScreen));
```

I still haven't figured out how to get the translations on navigation components to refresh when the language changes, though. I have this at the "top level" of my app, which is probably wrong or incomplete:

```
      <Suspense fallback={this.loader}>
        <I18nextProvider i18n={i18n}>
          <View style={styles.container}>
            <StatusBar
              translucent={true}
              backgroundColor={"transparent"}
              barStyle="light-content"
            />
            <AppWithNavigationState screenProps={{i18n}}/>
          </View>
        </I18nextProvider>
      </Suspense>
```

**Comment by jamuhl** [comment]
You might ask over at stackoverflow...for sure there are people more deep into react-navigation

**Comment by msageryd** [comment]
I struggled a bit with this and thought I'd make it easy if others are struggling by leaving my code here.

I'm just doing like this when i'm exporting my components:

```
const Translated = withTranslation()(_MyScreen);
Translated.navigationOptions = _MyScreen.navigationOptions;
export default Translated;
```

Static lifecycle functions/objects seems to be hoisted automatically. So you should NOT do this: 
```
Translated.getDerivedStateFromProps = _MyScreen.getDerivedStateFromProps;
```
You'll even get an error from React if you try to do this.
