### ISSUE TITLE
Alter detector result.

### ISSUE THREAD

**Issue by developdeez** [i18next/react-i18next#797]
Hi,

I tried researching this online but noting was clear. Can we change the result of language detection? I mean something like this code:

const convertLang = lang => {
  if (convertLang === "en-US") {
    return "en";
  }
  return lang;
};

I simply want to turn en-US to en. Even if it’s after as a callback that would be fine.

Any help is much appreciated.

**Comment by jamuhl** [comment]
use `load: 'languageOnly'` on i18next init

**Comment by developdeez** [comment]
Thi sis what I have now:
![image](https://user-images.githubusercontent.com/13059525/54893669-1959d000-4e74-11e9-983b-727001bd8fb6.png)


Still getting "en-US"

**Comment by jamuhl** [comment]
i18next.language will always be what was detected (in pure form) use i18next.languages[0] to get first used language that is used to lookup translations (the other lngs in that array act as fallback)
