### ISSUE TITLE
Translation out of context I18nextProvider

### ISSUE THREAD

**Issue by leshkovichpvl** [i18next/react-i18next#799]
The root of my application uses I18nextProvider, but in the depths of application used third-party libraries, that don't provide context. And it doesn't work in that case:
```
<Translation i18n={i18n}>
    {
      t => ....
    }
</Translation>
```
I get that error: `Cannot read property 'i18n' of undefined`

Because getHasUsedI18nextProvider() returns `true` and then useContext(I18nContext) is equal to `undefined`:
```
export function useTranslation(ns, props = {}) {
  // assert we have the needed i18nInstance
  const { i18n: i18nFromProps } = props;
  const { i18n: i18nFromContext } = getHasUsedI18nextProvider() ? useContext(I18nContext) : {};
```
As a result, it's impossible to take i18n from props. How to use Translation( or useTranslation)  regardless of I18nextProvider ?

**Comment by jamuhl** [comment]
shouldn't it use first the i18n passed by props? https://github.com/i18next/react-i18next/blob/master/src/useTranslation.js#L15

**Comment by leshkovichpvl** [comment]
> shouldn't it use first the i18n passed by props? https://github.com/i18next/react-i18next/blob/master/src/useTranslation.js#L15

it breaks when trying to take by context: https://github.com/i18next/react-i18next/blob/b251e68c8833745c851ee41e4946dd5c79c21baa/src/useTranslation.js#L14

**Comment by jamuhl** [comment]
do you have multiple instances of i18next in your app? if not - just use ì18next.use(initReactI18next) and remove the Provider

**Comment by jamuhl** [comment]
Further only components breaking context i know are portals -> where you need to wrap components again - but that is not specific to react-i18next but all using context

**Comment by leshkovichpvl** [comment]
> do you have multiple instances of i18next in your app? if not - just use ì18next.use(initReactI18next) and remove the Provider

I use one instance. In this case, I will have to set i18n in each component?

**Comment by jamuhl** [comment]
i18next.use(initReactI18next) should be sufficient...best might be providing a sample on codesandbox so i can have a deeper look what happens - hard to say without having actual code.

**Comment by jamuhl** [comment]
in the end it's like: if you can't pass i18n to the components the regular way you always can pass i18n via props or options -> just make sure translations are loaded upfront
