### ISSUE TITLE
cannot access static fetchData function after using withTranslation

### ISSUE THREAD

**Issue by zhouyuan1990** [i18next/react-i18next#800]
currently I'm trying to upgrade the react-i18next from v7 to v10.
we use static function to fetchData in server side like below:
```
let comp = renderProps.components[renderProps.components.length - 1].WrappedComponent
      if (comp !== undefined && comp.fetchData) {
        return comp.fetchData({ renderProps, store, history, res: res, req: req })
      } else {
        ...
      }
```
I try to change the translate to withTranslation, but it failed to access to the previous static fetchData.
How can I reach the static fetchData function?

**Comment by jamuhl** [comment]
https://react.i18next.com/latest/withtranslation-hoc#does-not-hoist-non-react-statics

**Comment by zhouyuan1990** [comment]
Thanks for your quick reply 👍

**Comment by zhouyuan1990** [comment]
hi @jamuhl 
I just got another issue, that I always get ref as null after using withTranslation.
I have tried ref callback and createRef way (ref.current is also null).

**Comment by jamuhl** [comment]
not sure...never needed refs to much...

**Comment by zhouyuan1990** [comment]
I just solve this issue by upgrade hoist-non-react-statics to the latest version.

**Comment by zhouyuan1990** [comment]
in previous version we have withRef to make it work.
no idea how to pass ref in this version.....

**Comment by jamuhl** [comment]
pass a prop innerRef to your component setting ref on the component needed...

**Comment by zhouyuan1990** [comment]
Maybe withTranslation hoc can support forwardRef, to make it work?

**Comment by jamuhl** [comment]
You might add a PR? Not forget to add a test for the new feature.

**Comment by zhouyuan1990** [comment]
https://github.com/i18next/react-i18next/pull/802
not sure if also need to add forwardRef for withSSR, since our project doesn't use withSSR, so I cannot verify if it works well in real project.

**Comment by zhouyuan1990** [comment]
#https://github.com/i18next/react-i18next/pull/802

**Comment by jamuhl** [comment]
guess not needed on withSSR...still can add that when users ask for it...will review your PR tomorrow
