### ISSUE TITLE
i18n for React Library

### ISSUE THREAD

**Issue by KALrious** [i18next/react-i18next#804]
# Question about react-i18next

Questions should be posted on StackOverflow

**Comment by KALrious** [comment]
I have a react library with two app that's use two I18nextProvider with two different i18n instance.
My issue is that the second app in the DOM always fallback in the default language .... Any idea ?
here is a sample of my config:
`import i18n from 'i18next';
import XHR from 'i18next-xhr-backend';
import frTranslations from './locale-fr.json';
import enTranslations from './locale-en.json';
import deTranslations from './locale-de.json';
import esTranslations from './locale-es.json';
import itTranslations from './locale-it.json';
import nlTranslations from './locale-nl.json';

function loadLocales(url, options, callback, data) {
  switch (url) {
    case 'fr':
      callback(frTranslations, { status: '200' });
      break;
    case 'en':
      callback(enTranslations, { status: '200' });
      break;
    case 'de':
      callback(deTranslations, { status: '200' });
      break;
    case 'es':
      callback(esTranslations, { status: '200' });
      break;
    case 'it':
      callback(itTranslations, { status: '200' });
      break;
    case 'nl':
      callback(nlTranslations, { status: '200' });
      break;
    default:
      callback(null, { status: '404' });
      break;
  }
}
const toto= i18n.createInstance();
toto.use(XHR).init({
  backend: {
    loadPath: '{{lng}}',
    addPath: '{{lng}}',
    parse: data => data,
    ajax: loadLocales,
    allowMultiLoading: false,
  },

  react: {
    wait: true, // globally set to wait for loaded translations in translate hoc
    // exposeNamespace: true // exposes namespace on data-i18next-options to be used in eg. locize-editor
  },

  // have a common namespace used around the full app
  ns: ['locale'],
  defaultNS: 'locale',
  load: 'languageOnly',

  debug: false,

  // cache: {
  //   enabled: true
  // },

  interpolation: {
    escapeValue: false, // not needed for react!!
    formatSeparator: ',',
    format: function(value, format, lng) {
      if (format === 'uppercase') return value.toUpperCase();
      return value;
    },
  },
});

export default toto;`
APP:
`render() {
        return (
            <I18nextProvider i18n={i18n} initialLanguage='es'>
                <Hello />
            </I18nextProvider>
        );
    }`

other config are exactly similar.
The only change is JSON translation form

**Comment by KALrious** [comment]
`initialLanguage='es'```

**Comment by jamuhl** [comment]
set debug true on i18next init and check what happens.

add resources at init resources: {} on init: https://www.i18next.com/how-to/add-or-load-translations#add-on-init (as you import them - no need to simulate a backend)
