### ISSUE TITLE
reuse the il8n instance

### ISSUE THREAD

**Issue by martingg88** [i18next/react-i18next#806]
We are about using this library for large application. 
Basically we do have several react components displayed at different 
place in one page. How to cater for reuse the il8n instance without multiple 
initialization and API context for all the individual component displayed in one page?

a. Render first component at section 1 in one page

ReactDOM.render(
  <div>{t('Section1')}< </div>,
  document.getElementById("section1")
);

b. Render second component at section 2 in one page

ReactDOM.render(
  <div>{t('Section2')}< </div>,
  document.getElementById("section2")
);

**Comment by jamuhl** [comment]
https://react.i18next.com/latest/i18next-instance

`i18next.use(initReact18next)` will globally share the one instance of i18next

only case you need the I18nextProvider -> you app needs multiple instances, SSR

**Comment by martingg88** [comment]
thanks. but if i import "import i18n from './i18n'" (etc. which is the shared il8n initialization) into many components in different file and will it trigger the i18n,init() as many time as possible? is the il8n is the singleton instance and so it only trigger il8n.inti() one time only?

**Comment by jamuhl** [comment]
i don't know what you're doing...you only import `import './i18n'` once and no it's a module it does only load the module once...not on every import...not sure but do you understand how javascript modules work?

best is check out the sample: https://github.com/i18next/react-i18next/blob/master/example/react/src/index.js

**Comment by martingg88** [comment]
I do have two files that will have component each and partially rendered at different section in one html page. example as following.

1. First file. 
import './i18n';
ReactDOM.render(<div>Section 1</div>, document.getElementById('root1'));

2. Second File
import './i18n';
ReactDOM.render(<div>Section 2</div>, document.getElementById('root2'));

My question is that "il8n.init()" will be triggered one more time for Second File? Or il8n is the singleton instance for first and second file?

**Comment by jamuhl** [comment]
Like i said:

You call init only once in i18n.js -> so how should it be called twice? `import ... from ...` imports a module not rerun it on every import statement...

**Comment by martingg88** [comment]
ok. many thanks for your information. have a good day bro.
