### ISSUE TITLE
Attempted import error: 'reactI18nextModule' is not exported from 'react-i18next'.

### ISSUE THREAD

**Issue by developdeez** [i18next/react-i18next#807]
I recently did an update and noticed this error. Also same for withNamepaces.
Is there docs on what to use instead?

**Comment by jamuhl** [comment]
there is an extra section for this in the docs...https://react.i18next.com/latest/migrating-v9-to-v10

**Comment by kubido** [comment]
I tried replacing `reactI18nextModule` with `initReactI18next`

```
i18n
  .use(languageDetector)
  .use(initReactI18next)
```

got error like this:
![Screenshot_2019-04-04-17-12-36-072_host exp exponent](https://user-images.githubusercontent.com/247114/55562759-48d2cd00-56fd-11e9-81dd-a130b046f94a.png)

**Comment by jamuhl** [comment]
are you on react-native 0.59?!? https://github.com/i18next/react-i18next#requirements

**Comment by kubido** [comment]
I see. seems expo still on SDK 32 which still use RN 0.57.  thank you. not yet supported hook

**Comment by jamuhl** [comment]
Sorry for that meanwhile you can still try v9: https://react.i18next.com/legacy-v9/overview

Migration: https://react.i18next.com/latest/migrating-v9-to-v10#components-v9-greater-than-v10

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:

**Comment by Katanis** [comment]
I am facing same problem, docs don't solve my problem.
My stack link: https://stackoverflow.com/questions/62429986/react-i18next-getting-error-attempted-import-error

**Comment by adrai** [comment]
@Katanis seems to be solved now?

**Comment by Katanis** [comment]
@adrai Yes ;)
