### ISSUE TITLE
Using Trans function within ReactDOMServer.renderToString or renderToStaticMarkup

### ISSUE THREAD

**Issue by rchinerman** [i18next/react-i18next#808]
Would it be possible to allow the Trans function to be used within a call to `ReactDOMServer.renderToString(JSX)` or `ReactDOMServer.renderToStaticMarkup(JSX)`? 

I'm using `react-tooltip`, which only accepts strings for its data-tip, however I'd like to be able to pass the following JSX into the tooltip.

```js
        <itemdata>
          <itemname>${itemData.name}</itemname>
          <itemplaintext>${itemData.plaintext}</itemplaintext>
          <itemdescription>${itemData.description}</itemdescription>
          <itemcost>
          <Trans i18nKey="keyName">
            <span>Text</span>
            {{variable}} ({{variable})
          </Trans>
          </itemcost>
        </itemdata>
```

This is only possible by rendering it to a string, but I'm getting the error `TypeError: Cannot read property 'i18n' of undefined` here. Am I doing something wrong? Is there another way I can achieve this functionality?

**Comment by jamuhl** [comment]
You're using `I18nextProvider` or `i18next.use(initReactI18next)` ?!? Looks like either you pass no instance down by either of this method or you're using the Provider but that component does not support context API of react (or breaks it - using Portal or something).

As a last resort you can pass i18n as prop `<Trans i18nKey="myKey" i18n={i18n}>...`

**Comment by rchinerman** [comment]
Yes we are using them. The internationalization works completely fine, just not in this single instance. Passing i18n down as a prop doesn't work either.

I'm just going to make the necessary changes so I don't need to use the Trans component here, the t function works fine.

**Comment by jamuhl** [comment]
@rchinerman still strange -> does it give you a missing key warning if debug: true on init? -> eventual you need to pass needed namespase by prepending it to the key `myNamespace:myKey` separated by `:`.

Would be great if you could investigate that or provide a sample to reproduce at some point...
