### ISSUE TITLE
in ssr when then namespace not exist in the selected resource/language this is false and render return null

### ISSUE THREAD

**Issue by nathanredblur** [i18next/react-i18next#809]
**Describe the bug**
In ssr when then namespace not exist in the selected resource/language this is false and set ready in false. 

```
const ready = !!language && namespaces.every(ns => props.i18n.hasResourceBundle(language, ns));
```
later when we want make render of the component, this line return null
https://github.com/i18next/react-i18next/blob/11e23a4c482a3449ca1e664eedd745975957e3d6/src/NamespacesConsumer.js#L165

**Occurs in react-i18next version**
I'm using "next-i18next": "^0.31.0" who require "react-i18next@^9.0.4".

my config is:
```
{
  defaultLanguage: 'en',
  otherLanguages: ['en-US', 'es-ES'],
  ignoreRoutes: [
    '/_next',
    '/static',
    '/reload',
    '/uploads',
    '/assets',
    'favicon.ico',
  ],
  detection: {
    order: ['locale'],
  },
  customDetectors: [
    {
      name: 'locale',
      lookup: (req, res, options) => {
        const { locale } = res.locals; //locale set "es-ES" or "en-US" based on the domain.
        return locale;
      }
    }
  ],
  fallbackLng: ['en'],
  debug: (process.env.DEBUG && process.env.DEBUG.indexOf('i18n') >= 0),
  saveMissing: (process.env.DEBUG && process.env.DEBUG.indexOf('i18n') >= 0),
  saveMissingTo: 'current',
}
```

**To Reproduce**
1. start a new next project with nexti18next.
2. configure your application to change your language on send one or other url
3. run your app to start with language one.
4. see how you have a nice ssr version of your page
5. change the url to load the other language. 
6. ssr not happen.

**Expected behaviour**
1. hasResourceBundle  https://github.com/i18next/i18next/blob/master/i18next.js#L602 should return true when some namespace exist in the required language or the fallback language. 
2. this line should return true https://github.com/i18next/react-i18next/blob/v9.x.x/src/NamespacesConsumer.js#L49 if the previus condition is true
3. translated component should be render in the server.

**Comment by jamuhl** [comment]
hasResourceBundle is an i18next function -> that does return true if true for given language...not also true if fallback exists. Won't be able to change that.

You can just add an empty JSON file for those to make it work.

**Comment by nathanredblur** [comment]
yeap, but can you explain me why work only with the first language that you use in the first request when should fail with both?
also explain me why when I set saveMissing in true, create the missing namespaces for one language but not for the other?

**Comment by jamuhl** [comment]
1) what you mean?
2) configurable https://www.i18next.com/overview/configuration-options#missing-keys (saveMissingTo)

**Comment by nathanredblur** [comment]
1. I have this files:
```
o
`-- locals
    |-- en
    |   |-- common.json
    |   `-- home.json
    |-- en-US
    |   `-- common.json
    `-- es-ES
        `-- common.json
```

then later when react-i18nex call this function https://github.com/i18next/i18next/blob/master/i18next.js#L602 using "es-ES" with ns "home" not going to found that path in "this.data" and return false.

this condition should happen for both languages "en-US " and "es-ES", but what actually happen is that when the first language that you request to translate is "en-US", you receive a true and "es-ES" return false. and if you restar the aplication and the first language that you load is "es-ES", then "en-US" not work.

same things happen when you activate "saveMissing", when you start the application and the first request is use "en-US", then the i18next create the missing namespace, for that language, and on change to the "es-ES" not create the missing namespace.

**Comment by jamuhl** [comment]
You get a true for en-US because saveMissing wrote to it -> saveMissing does not only pass data to backend but also create that namespace on client. But actually both fail - as no content - only the first load hits a saveMissing letting it pass. This is expected behaviour.

The check https://github.com/i18next/react-i18next/blob/v9.x.x/src/NamespacesConsumer.js#L49 can't be true for es-ES in case en-US triggered the missing (even if you would set saveMissingTo: 'fallback') and we would change to pass ready in case the fallback is loaded -> this would end in all pages being ready for the fallback - but what you like is being ready for showing content in es-ES....right?


saveMissing (At least if not set different) always saves to fallbackLng (at least that is the default for saveMissingTo) -> you set it to `current` so it will save it once during runtime to the language (current) at that time and will add the key on that lng-ns - so it's missed only once.

**Comment by jamuhl** [comment]
So basically:

- If you want en-US and es-ES to fail turn saveMissing off
- If you want correct behaviour in production - have translations ready

**Comment by jamuhl** [comment]
> this condition should happen for both languages "en-US " and "es-ES", but what actually happen is that when the first language that you request to translate is "en-US", you receive a true

do you get this even if saveMissing is false - guess no - as there will be no data['en-US']['home'] in resources...

**Comment by nathanredblur** [comment]
yes I get this when saveMissing is false.

**Comment by jamuhl** [comment]
ahh...but only with next-i18next...right? a plain react-i18next wouldn't do that -> does `data['en-US']['home']` be an empty object you get passed from next-i18next by initialStore?

**Comment by nathanredblur** [comment]
yeap, I think you are right.

**Comment by nathanredblur** [comment]
ok, this helps with the client side rendering, but not with the server side rendering. I put some breakpoints in that app-with-translation file in that line and this is what I see.

1. restart application
2. breackpoint: 
initialLanguage: 'es-ES'
req.i18n.services.resourceStore.data: 
```
en: {common: {…}, home: {…}}
en-US: {common: {…}}
es-ES: {common: {…}}
```
3. play and request again for home page
4. breakpoint:
initialLanguage: 'es-ES'
req.i18n.services.resourceStore.data: 
```
en: {common: {…}, home: {…}}
en-US: {common: {…}}
es-ES: {common: {…},  home: {}}
```
5. changing the domain request to change the language. 
6. breakpoint:
initialLanguage: 'en-US'
req.i18n.services.resourceStore.data: 
```
en: {common: {…}, home: {…}}
en-US: {common: {…}}
es-ES: {common: {…},  home: {}}
```

someone is filling 
req.i18n.services.resourceStore.data['es-ES'] with empty namespaces and I could't find who. 
several breakpoints in /node_modules/next-i18next/node_modules/i18next/dist/commonjs/ResourceStore.js in "addResource, addResources or addResourceBundle" is not explain who fill this [es-ES][home] = {}.

**Comment by jamuhl** [comment]
not sure - but i would say neither i18next nor react-i18next do that - you might have to check https://github.com/isaachinman/next-i18next / ask there

**Comment by nathanredblur** [comment]
:( this is really terrible,  I did't find who change the object. but I want to suggest restrict the access to "resourceStore.data" to prevent some external code modify the object, lets make accesible only trow some kind of "resourceStore.set" and "resourceStore.get" methods.

**Comment by jamuhl** [comment]
the community over at next-i18next is large...i'm rather sure they will help you finding the cause.

But like said...while this seems like a problem...it's not - in production you do not use saveMissing and es-ES and en-US are fully translated

**Comment by nathanredblur** [comment]
thanks for your help, meanwhile I will create the empty namespaces files to not break the render.
