### ISSUE TITLE
Suspense not triggered on language change

### ISSUE THREAD

**Issue by LKay** [i18next/react-i18next#811]
**Describe the bug**
I'm using almost exact code as in the example and `Suspense` is triggered only on the initial render (showing loading component). However it is not triggered when `i18n.changeLanguage()` is called inside `onClick` event handler. I'm using XHR backend for locale load and after button is clicked request is being sent to the server but nothing happens until everything is fetched.

I tried to set `useSuspense` to `false` but in such case `ready` flag never gets back to `undefined` of `false` (on component re-render) and just re-renders component with `true` value after async language change finishes.

**Occurs in react-i18next version**
10.6.0

**Expected behaviour**
When this code is executed `Suspense` should trigger and display `fallback` component before all messages are fetched and language is fully changed.

```jsx
const handleClick = lng => {
    i18n.changeLanguage(lng);
  //^^^^^^^^^^^^^^^^^^^^^^^^
  //This returns unhandled Promise
};
```

**Comment by jamuhl** [comment]
The point is there is no way to notify the useTranslation of the languageIsChanging -> there is only an event for `languageChanged` -> so new language will be shown when ready - but right there is no Suspense triggered -> guess that would trigger Suspense on every component having text (depending on your setting resulting in showing one big spinner for your app -> guess this is not what most people like to have.

you can (untested):

```js
const handleClick = lng => {
  throw new Promise((resolve) => {
    i18n.changeLanguage(lng, () => {
       resolve();
    });
  })
};
```

**Comment by jamuhl** [comment]
Suggestions would be welcome...

**Comment by LKay** [comment]
@jamuhl Thanks for quick reply. I tried to wrap it similar way with a `Promise` or just throw a promise directly, which is basically the same:
```js
const handleClick = lng => {
  throw new i18n.changeLanguage(lng);
};
```
Unfortunately, seems like it's not being picked up by wrapping `Suspense` and just throws error in the console about uncaught promise:

<img width="299" alt="Image 2019-04-03 at 3 41 59 PM" src="https://user-images.githubusercontent.com/181078/55458191-38e8b980-5627-11e9-9247-6fda6993186e.png">

**Comment by jamuhl** [comment]
Hm...could be because it's not thrown during render but on event (but idk)

**Comment by LKay** [comment]
It's most likely. I haven't dug too deep in the code yet but I assume it's because `i18n.changeLanguage` doesn't deal with context the hook and `Suspense` depend on. Seems like i18next instance dispatches its own event which is not handled by react-i18next. 

Probably there should be some additional hook `useChangeLanguage` which updates context to address that case unless there is some other workaround?

**Comment by jamuhl** [comment]
Will need to think a little about it...like said i'm not sure i'm a fan of suspense usage on languageChange as it might look weird.

**Comment by jamuhl** [comment]
hm, thought about adding this inside to the useTranslation hook

```js
  const [targetLng, setTargetLng] = useState('');

  function changeLanguageWithSuspense(lng) {
    setTargetLng(lng);
  }

  if (targetLng && targetLng !== i18n.language) {
    // not yet loaded namespaces -> load them -> and trigger suspense
    throw new Promise(resolve => {
      i18n.changeLanguage(targetLng, () => {
        resolve();
      });
    });
  }
```

then expose that function...only issue i got so far - as only this `useTranslation` gets aware of the targetLanguage it will be the only one triggering a suspense. So depending on where you got the language change trigger and the Suspense component catching...it might only be partially show a fallback UI.

When i move the `targetLng` to global only this hook setState and therefore even does a rerun evaluating `targetLng && targetLng !== i18n.language`.

So my best guess would be adding a new event on i18next itself `languageChanging` -> this triggers a the rebind of `t` in the useTranslation hook and should throw the same Promise (because of not ready) and hopefully solves itself cause of the loadNamespaces.

Will need to elaborate further on this...but just want to let you guys know - I have not forgotten this.

**Comment by LKay** [comment]
that's a good start, I think. However I would rather use context, which is shared between components instead of state. Throwing a `Promise` should trigger all wrapping `Suspense` components going up the virtual DOM form the triggering component using `useTranslation`, so swallowing this boy only the first `Suspense` might not be ideal.

**Comment by jamuhl** [comment]
ok gone the additional event way...

can you try with:

- i18next@15.1.0
- react-i18next@10.9.0

**Comment by jamuhl** [comment]
If you encounter any issues with it - let me know.
