### ISSUE TITLE
Need info about common.json file in docs

### ISSUE THREAD

**Issue by MareoRaft** [i18next/react-i18next#812]
**Describe the bug**
This is a request for documentation improvement.  Need more info on where to put common.json in the step-by-step guide.

**Additional context**
The most recent step by step guide (https://react.i18next.com/latest/using-with-hooks) shows you how to set up a project in such a way that it depends on a `common.json` translations file, as far as I can tell.  But none of the steps in the guide say to create this file, where to put the file, and what the content of the file should be.  This should probably be one of the first steps.

Thank you!

**Comment by jamuhl** [comment]
Added a link to https://github.com/i18next/react-i18next/tree/master/example/react/public/locales should hopefully sufficient to show this (location always depend on your i18next backend settings)

**Comment by jamuhl** [comment]
If you got a better idea - a PR on docs would be highly appreciated

**Comment by MareoRaft** [comment]
I won't be able to make a PR because I wasn't able to get things working with i18next-xhr-backend, which is what the docs want you to use.

**Comment by MareoRaft** [comment]
actually, this issue should remain open since it is still an outstanding issue

**Comment by jamuhl** [comment]
There is a big difference not getting it working (= stackoverflow) and there is a bug in the code -> as long there is no bug there is no need to keep an issue open.

there is the examples folder with a working sample...https://github.com/i18next/react-i18next/tree/master/example/react

In case you need more information about the xhr-backend: https://github.com/i18next/i18next-xhr-backend#backend-options
