### ISSUE TITLE
SSR Suppresshydrationwarning Issue

### ISSUE THREAD

**Issue by martingg88** [i18next/react-i18next#813]
Any Idea to resolve the following "suppresshydrationwarning" issue when using the react hydrate for both server and client side rendering?

Warning: Text content did not match. Server: "Text 1." Client: "Text 1"

Thank.

**Comment by jamuhl** [comment]
using next.js?

**Comment by martingg88** [comment]
using i18next and react-i18next only. Any idea?

**Comment by jamuhl** [comment]
initial render is not the same as the one passed from serverside

do you pass down needed initialStore, initialLanguage use the SSR stuff to prefill clientside based on serverside translations used?!?

**Comment by jamuhl** [comment]
did you find the cause?

**Comment by martingg88** [comment]
Can i have an example for pass down  initialStore or initialLanguage by using SSR?

**Comment by jamuhl** [comment]
eg. the razzle sample:

passing to client via: https://github.com/i18next/react-i18next/blob/master/example/razzle-ssr/src/server.js#L78

client catch it at: https://github.com/i18next/react-i18next/blob/master/example/razzle-ssr/src/client.js#L9

**Comment by martingg88** [comment]
I will check this out and let u know. Many thanks.

**Comment by jamuhl** [comment]
Could this be closed?

**Comment by martingg88** [comment]
I use the following method to ajax pull those translation file, but still have same problem due the translation file loaded after react render the page at client side. Any idea to solve the issue by pre-load those the translation file?

 i18nOptions.backend = {loadPath :  Config.app.asset_url + '/dist/js/lang/{{lng}}/{{ns}}.json'};

**Comment by jamuhl** [comment]
https://react.i18next.com/latest/ssr
