### ISSUE TITLE
Using React i18next do I have to use withTranslation?

### ISSUE THREAD

**Issue by Jonovono** [i18next/react-i18next#816]
# Question about react-i18next

I am wondering something.

Say I have a component and I want to access the t value. Do I have to hook it to redux. Since to use react-i18next I am also using i18next can't I just do:
```
import i18next from 'i18next'

class Comp extends Component {
    render() {
      return <Text>{i18next.t('space')}</Text>
    }
}
```
Or what's the downside of doing this? It seems it still does my translation but there must be a downside? I'm guessing only if the locale changes it won't see the update? Anything else?

Thanks.

Questions should be posted on StackOverflow
Also posted on Stackoverflow: https://stackoverflow.com/questions/55518083/using-react-i18next-do-i-have-to-use-withtranslation

**Comment by jamuhl** [comment]
https://react.i18next.com/guides/the-drawbacks-of-other-i18n-solutions#the-drawbacks

=> hook and hoc assert namespaces are loaded and rerender on language change
