### ISSUE TITLE
Some problem about Trans component code

### ISSUE THREAD

**Issue by flytam** [i18next/react-i18next#825]
Before code
```javascript
<div>{index+1} <a>xxx</a></div>
```
What does the converted code look like if use Trans

**Comment by jamuhl** [comment]
You will have to change that to:

```js
<Trans>
   {{number: index + 1}} <a>xxx</a>
</Trans>
```

=> passing index + 1 as a variable to interpolate into the translation

Resulting string: `{{number}} <2>xxx</2>`

https://react.i18next.com/latest/trans-component#how-to-get-the-correct-translation-string

I just pasted the string to https://codesandbox.io/s/1zxox032q into app.js in a Trans and fixed that interpolation issue then caught that missing on console output for resulting string

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
