### ISSUE TITLE
Replace count prop from <Trans> in translation string automatically 

### ISSUE THREAD

**Issue by manuelbieh** [i18next/react-i18next#826]
**Is your feature request related to a problem? Please describe.**
As already discussed on Twitter:
https://twitter.com/ManuelBieh/status/1117491118223106048

The current usage of the `Trans` component:
```jsx
<Trans i18nKey="messageCount" count={3}>
  You have <strong>{{count: 3}}</strong> new messages.
</Trans>
```
with translation keys being:
```
messageCount: "Du hast <1>{{count}}</1> neue Nachricht",
messageCount_plural: "Du hast <1>{{count}}</1> neue Nachrichten",
```

feels unnecessarily complicated and also redundant if you're not using a variable for `count`. The value for `count` can possibly be replaced automatically based on the value that is passed to the `count` prop in the `Trans` component, so that this would be possible:

```jsx
<Trans i18nKey="messageCount" count={3}>
  You have <strong>?</strong> new messages.
</Trans>
```

**Describe the solution you'd like**
I'd love to see this working:
https://codesandbox.io/s/oqj2o017w9

**Comment by jamuhl** [comment]
works in react-i18next@10.8.0

**Comment by manuelbieh** [comment]
Schneller als die Feuerwehr 🚒 👨‍🚒 . Nice! Thank you!
