### ISSUE TITLE
Error using the t function on a plain js file

### ISSUE THREAD

**Issue by Luisdv93** [i18next/react-i18next#828]
I used the library before when it was on version 8 and I was able to import my i18next instance and use the translation function inside my plain js files.  I'm getting the following error when I try to replicate the same with the latest version:

```
import * as Yup from "yup";
import i18n from "../../i18n/i18n";

export const categorySchema = Yup.object({
  name: Yup.string()
    .min(3, i18n.t("categoryList.min"))
    .required(i18n.t("categoryList.required"))
});
```

`TypeError: _i18n_i18n__WEBPACK_IMPORTED_MODULE_1__.default.t is not a function`

I also tried importing i18next directly from the package but the translations didn't work. Any way I can achieve this?

**Comment by jamuhl** [comment]
does your i18n.js export the return value of init? that is a promise now and not the instance -> https://www.i18next.com/misc/migration-guide#v-12-x-x-to-v-13-0-0

```js
const i18n = i18next.init();

export i18n; // -> is a Promise now
export i18next; // -> is the instance
```

**Comment by Luisdv93** [comment]
Thanks! That solved my problem.

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:

**Comment by mmarshad** [comment]
I'm having the same issue and i have made the above changes but now it has fixed the error
`TypeError: _i18n_i18n__WEBPACK_IMPORTED_MODULE_1__.default.t is not a function`
however when I switch to different language, my validation does not reflect that and shows the errors with the default language
