### ISSUE TITLE
Placeholder

### ISSUE THREAD

**Issue by forestfuture89** [i18next/react-i18next#830]
# Question about react-i18next

Questions should be posted on StackOverflow

Before i used this code like this ..
<Input size="16"
type="text"
name="search"
id="search"
placeholder="Search"
value={search || ''}
onChange={e => handleChange(e.target.name, e.target.value)}
required/>

I want to change placeholder with translate ..
so i used like this
<Input size="16"
type="text"
name="search"
id="search"
placeholder={}
value={search || ''}
onChange={e => handleChange(e.target.name, e.target.value)}
required/>

But this is not working well .. could you help me for this ?

**Comment by jamuhl** [comment]
@forestfuture89 the code does not even show what you tried to translate the placeholder....

could be something like: <Input placeholder={t('key')} />

**Comment by forestfuture89** [comment]
How can i import t as translate ?  
So   you mean i have to use <input placeholder={translate('key')} ?

**Comment by jamuhl** [comment]
@forestfuture89 do you read any docs - look at any sample? t comes from using HOC, render prop or hook https://react.i18next.com/latest/using-with-hooks

**Comment by forestfuture89** [comment]
Ok 

Let me check again . 

Thanks very much

**Comment by forestfuture89** [comment]
This is fixed .. Thanks .

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
