### ISSUE TITLE
Maximum call stack size exceeded on load and changing language

### ISSUE THREAD

**Issue by pospichalales** [i18next/react-i18next#832]
Hi,

I upgraded react-i18next from legacy 9.0.10 to current 10.8.1 and experiencing this error.

When I first visit the page or when changing language, the page not load and I get error in console:

`RangeError: Maximum call stack size exceeded
    at index.js:42
    at e.exports (index.js:23)
    at index.js:96
    at e.exports (index.js:23)
    at index.js:96
    at e.exports (index.js:23)
    at index.js:96
    at e.exports (index.js:23)
    at index.js:96
    at e.exports (index.js:23)`

This happens only in production, development build is working great.

My current usage:

```
import i18n from 'i18next';
import Backend from 'i18next-xhr-backend';
import LanguageDetector from 'i18next-browser-languagedetector';
import { initReactI18next } from 'react-i18next';

i18n
    .use(Backend)
    .use(LanguageDetector)
    .use(initReactI18next)
    .init({
        fallbackLng: 'cs',

        // have a common namespace used around the full app
        ns: ['translations'],
        defaultNS: 'translations',

        debug: false,
		load: 'languageOnly',

        interpolation: {
            escapeValue: false, // not needed for react!!
        },

        react: {
            useSuspense: false
        }
    });

export default i18n;
```

```
import {withTranslation} from 'react-i18next';
...
class App extends Component {
...
...
render() {
        const { t } = this.props;
...
}
export default withTranslation('translations')(App);
```

I am testing it with Chrome 73. Web server in production is express 4.16.4.

**Comment by jamuhl** [comment]
Please provide a sample for reproduction. Can't make anything out of the error message, plus we do not have this issues in our production build...

**Comment by pospichalales** [comment]
i18n.js

```
import i18n from 'i18next';
import Backend from 'i18next-xhr-backend';
import LanguageDetector from 'i18next-browser-languagedetector';
import { initReactI18next } from 'react-i18next';

i18n
    .use(Backend)
    .use(LanguageDetector)
    .use(initReactI18next)
    .init({
        fallbackLng: 'cs',

        // have a common namespace used around the full app
        ns: ['translations'],
        defaultNS: 'translations',

        debug: false,
		load: 'languageOnly',

        interpolation: {
            escapeValue: false, // not needed for react!!
        },

        react: {
            useSuspense: false
        }
    });

export default i18n;
```

index.js
```
import 'react-app-polyfill/ie11';

import 'jquery/dist/jquery.slim.min.js';
import 'popper.js/dist/popper.min.js';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap/dist/js/bootstrap.min.js';

import React from 'react';
import ReactDOM from 'react-dom';

import './index.css';

import 'unorm';
import Routes from './Routes';
import * as serviceWorker from './serviceWorker';
import './i18n';

import { ThemeProvider } from 'styled-components';
import colors from "colors";
import ReactGA from 'react-ga';

import bugsnag from '@bugsnag/js';
import bugsnagReact from '@bugsnag/plugin-react';

const bugsnagClient = bugsnag({apiKey: 'xxxxxxxx', logger: null});
bugsnagClient.use(bugsnagReact, React);

const ErrorBoundary = bugsnagClient.getPlugin('react');

ReactDOM.render(<ErrorBoundary><ThemeProvider theme={colors}><Routes /></ThemeProvider></ErrorBoundary>, document.getElementById('root'));
serviceWorker.register();
```

Routes.js
```
import React from 'react';
import {Router, Route, Redirect, Switch} from 'react-router-dom';
import {withTranslation} from 'react-i18next';
import {getAmazonS3Url} from "./Utils/Utils";
import {createBrowserHistory as createHistory} from "history";
import ColorWrapper from "./Components/ColorWrapper";

import App from "./App";

const Routes = ({t}) => (
    <Router history={history}>
        <div>            
			<Switch>
				<Route exact path="/" render={() => <ColorWrapper isPoleDance={false}><App /></ColorWrapper>}/>
			</Switch>
        </div>
    </Router>
);

export default withTranslation()(Routes);
```

App.js
```
import React, { Component } from 'react';
import styled from 'styled-components';
import './App.css';
import {withTranslation} from 'react-i18next';
import FontAwesome from 'react-fontawesome';
import colors from "./colors";
import Button from "./Components/Button";
import {Container, Row} from "reactstrap";
import {media} from "./Utils/Media";
import Banner from "./Components/Banner";
import NavBar from "./NavBar";
import {TitleWrapper} from "./Components/StyledComponents";
import {getAmazonS3Url, repeat, trackPageView} from "./Utils/Utils";
import Footer from "./Components/Footer";
import {articles} from "./Data/data";
import Card, {L, M, S} from "./Components/Card";
import mainPhoto from './photos/main_photo.png';
import {Helmet} from "react-helmet";

class App extends Component {

render() {
        const { t } = this.props;
        const textBase = 'MainPage';
		
        return (
            <div className="App">
		</div>
);
    }
}

export default withTranslation('translations')(App);
```

**Comment by pospichalales** [comment]
The link within error is to node_modules/deep-equal/index.js:27

**Comment by pospichalales** [comment]
If it helps, node.js version is 11.14.0

**Comment by pospichalales** [comment]
The changes I have made from working v9.x is replacement translate -> withTranslation. In i18n.js changed reactI18nextModule to initReactI18next.

Changed react: 

```
react: {
            wait: true
        }
```
to
```
react: {
            useSuspense: false
        }
```

**Comment by jamuhl** [comment]
`deep-equal` is not a dependency of our module...

**Comment by pospichalales** [comment]
Thank you, I today updated workbox-cli, maybe bug there. I will downgrade that package, try it and let you know.

**Comment by pospichalales** [comment]
I can confirm that workbox-cli is using deep-equal so not a problem with react-i18next. Sorry for wasting your time.

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:

**Comment by pospichalales** [comment]
Reopening. It is true, what I write above, but downgrading workbox-cli to previous working version did not solve my issue. I decided to downgrade react-i18next to 9.0.10 and it is now working again.
It seems there is some incompatibility with google's workbox - service worker. In development there is no service worker - the page is working correctly. However in production it is causing problems.
I am using workbox-cli 4.1.1 (tried with 4.3 too) and translations files (jsons) are fetched using service worker with networkfirst strategy. Skipwaiting and clientsclaim settings are enabled.

**Comment by pospichalales** [comment]
The error is always right after fetching JSON file with translations
![image](https://user-images.githubusercontent.com/47054776/56378187-91fe4300-620c-11e9-8127-0568c3925909.png)

**Comment by pospichalales** [comment]
Since that error started appearing after react-i18next, it does not neccessarily means that bug is in this package. Please let me know, if it is something what should be solved here or I should contact workbox developer.

**Comment by adrai** [comment]
I would suggest to open also an issue there... and cross reference it.
And even better it would be to have a small sample repo or similar to reproduce the issue.

**Comment by pospichalales** [comment]
I do know how it is related with react-i18next upgrade but I found a problem with this code:
`<Helmet>
					<title>{t("WorkshopPage.title")+' | ERS Workout'}</title>
					<meta property="og:title" content={t("WorkshopPage.title")+' | ERS Workout'} />
					<meta property="og:url" content={window.location.href} />
				</Helmet>`

It was here for months and no issue with it. It started after react-i18next upgrade yesterday.

Removing these lines or upgrading react-helmet to 6.0.0 beta solves this issue. In this version there is deep-equal dependency replaces by is-equal.
