### ISSUE TITLE
Support passing objects to <Trans components={{ ... }} />

### ISSUE THREAD

**Issue by pleunv** [i18next/react-i18next#833]
Hi there! First of all, thank you for all the work you put into `i18next`! It is by far the best i18n lib we've come across, and it just keeps getting better and better :)

**Is your feature request related to a problem? Please describe.**

I'm running into some issues with the numeric (`<0>`) placeholders in the `<Trans components={[...]} />` prop. 
First of all, the translation tool we use has first-class support for html placeholders, meaning that during the translation process they automatically get detected and copied to the target translation. Without a mechanism like this you very quickly run into awkward scenarios with for example RTL input. However, this detection is built on top of an X(HT)ML parser, and the XML spec dictates that tags are only valid if they start with a letter. As a result the numeric `<0>` placeholders are not picked up and the detection does not work in this case.

Secondly, I'm noticing that numeric placeholders sometimes convey too little context to translators. Given the following 2 strings:

* `<0>{{firstName}} {{lastName}}</0> added a new <1>comment</1> to article <2>{{articleTitle}}</2>`
* `<profileLink>{{firstName}} {{lastName}}</profileLink> added a new <commentLink>comment</commentLink> to article <articleLink>{{articleTitle}}</articleLink>`

I personally prefer the latter one. It's a bit more verbose, but verbosity is important when involving external translators into a project as they need additional context to figure out what is what. In addition, it looks more familiar to html which they generally already have some notion of, + it's a bit more resilient to change as it doesn't rely on order.

**Describe the solution you'd like**

I was wondering if you'd be open to support a secondary object syntax for the `components` prop, i.e.:

```js
<Trans
  i18nKey="myKey"
  components={{
    articleLink: <a href="..." />,
    commentlink: <a href="..." />,
    profileLink: <a href="..." />
  }}
  values={values}
/>
```

Which would enable the use of the "named placeholder" method above. I can have a stab at this myself, just will have to dig into the `Trans` component a bit first :)

**Comment by jamuhl** [comment]
Will need to think about it...got a little mixed feeling about adding complexity...might be something for a custom component...not yet sure.

Beside that -> you should use https://locize.com to support us - that's our TM solution

**Comment by klis87** [comment]
The very big advantage of this is also you need to pass `children` for `Trans` currently, which I find really problematic. For instance thing like:
```js
<Trans i18nKey="dragOrPickFromDisk">
  Drag or
  <Button>
    pick from disk
  </Button>
</Trans>
```

Several problems with this:
- we kinda duplicate translations within jsx, really `dragOrPickFromDisk` should be all it needs plus object of components to be injected
- with multiple and nested components interpolation in translation becomes really hard to maintained, and is not too much readible

Compare it with this:
```js
<Trans
  i18nKey="dragOrPickFromDisk"
  components={{ button: <Button />}}
/>
```

Advantage is cleaner jsx, less duplication, plus it would be easy to use interpolations in translations, as u would not use indexes of components anymore, but keys

**Comment by jamuhl** [comment]
@klis87 matter of taste - like said...additional options add complexity (not only in the code - but in documentation and adaption too).

Open for a PR - but will decide after seeing the implementation if this could be accepted.

**Comment by iamandrewluca** [comment]
@klis87 duplication can be avoided.
```
"react-i18next": "^10.8.1",
```
```jsx
<Trans i18nKey="test" components={[<Link to="/" />]} />
```
```json
{
  "test": "You can <0>navigate to the home page</0> or use the main menu.",
}
```
```html
You can <a href="/">navigate to the home page</a> or use the main menu links.
```

**Comment by klis87** [comment]
@iamandrewluca awesome! I did not know it was added in version 10!

**Comment by iamandrewluca** [comment]
As I investigate,d [mapAST](https://github.com/i18next/react-i18next/blob/master/src/Trans.js#L120) is responsible for mapping, but it's a bit overcomplicated, it needs some core devs intervention I think. Or I'll give one more try.

**Comment by nphmuller** [comment]
I would also really like this feature. The `values` prop allows for a key identifier to be specified, so why not also allow this for `components`?

For my use case: 

Many of the translation entries in my json file look like this:
`"key": "Don't have an account? <1>Click to register!</1>`
With the following code in my React component:
`<Trans components={[null, <a href='/register' /> ]}>key</Trans>`

I now have to specify `null` everywhere as the first entry of the array. This gets worse with multiple interpolated components (for every piece of text between components I have to specify a `null` object in the array.

When objects in component are supported, I could simply specify the key as the property name, like this:
`"key": "Don't have an account? <registerLink>Click to register!</registerLink>`
`<Trans components={{registerLink: <a href='/register' />}}>key</Trans>`

Or maybe even like this, if you don't like the idea of a named key:
`"key": "Don't have an account? <1>Click to register!</1>`
`<Trans components={{1: <a href='/register' />}}>key</Trans>`

**Comment by jamuhl** [comment]
@nphmuller https://github.com/i18next/react-i18next/pull/859 not sure but that PR "just" misses the tests.

**Comment by nphmuller** [comment]
@jamuhl That's great to hear. But I just figured out a mistake I made in the samples I posted. So the feature is not necessary anymore for my use case.

I you like at my example, the a tags all are replaced with `<1>` in the translation file. If I however use the `components` prop, I can define them as `<0>`. That way I don't need the `null` value in the array for the `components` prop anymore! :)

**Comment by iamandrewluca** [comment]
@nphmuller waiting for this to be merged https://github.com/rayd/html-parse-stringify2/pull/20, and I'll add tests and finish this PR

**Comment by raghuprathap** [comment]
I have a key like `Enter a URL to send it as a simple message to other users by click on the {{videoIcon}} icon.`  and value also same in en.json. But trying to use 
```
<Trans
          i18nKey="Enter a URL to send it as a simple message to other users by click on the {{videoIcon}} icon."
          components={{ videoIcon: <VideoIcon /> }}
        />
```
But this is rendered as
 Enter a URL to send it as a simple message to other users by click on the [object Object] icon.

Please suggest how to use in this case.

**Comment by jamuhl** [comment]
@raghuprathap that does not work like this...read: https://react.i18next.com/latest/trans-component#alternative-usage components is an array and not a named interpolation value

**Comment by iamandrewluca** [comment]
@raghuprathap 
```tsx
<Trans
  i18nKey="Enter a URL to send it as a simple message to other users by click on the <0/> icon."
  components={[<VideoIcon />]}
/>
```

**Comment by robinsingh-bw** [comment]
@iamandrewluca I have a similar issue and cant seem to get Trans to work. Been at it for a couple hours now.

`<Trans i18nKey="navbar.poweredBy" components={[<Link to="/" style={{ color: 'white' }}>Disney</Link>]} />`

`poweredBy: "Powered by <0/>"`

It just prints Powered by, theres no Disney...

**Comment by jamuhl** [comment]
@robinsingh-bw did you try:

`poweredBy: "Powered by <0>Disney</0>"` ?

**Comment by robinsingh-bw** [comment]
@jamuhl I just tried that too, still nothing

**Comment by robinsingh-bw** [comment]
Gatsby was caching the translation files so no matter what I did it just wouldn't work. Clearing the cache solved it. You don't happen to know how to avoid caching translation files in gatsby by any change? :p

**Comment by jamuhl** [comment]
@robinsingh-bw sorry but no - I got no idea how to do that...would love to have the time to put up a sample with gatsby. Doing things the right way - like prerendering all languages to static files in separated folders - honestly always hoped the community will come up with something similar to next-i18next for gatsby...but seems not...

**Comment by rubystephenpoole** [comment]
This actually extends beyond a nice-to-have. Correct me if I'm wrong, but in cases where the translation's components change order between languages, the index-based solution doesn't work.

For example:

The current case
`en/common.json
{ "test": "This is a test translation where <1>ordering changes between languages</1>." }`
`fr/common.json
{ "test": "<0>Le this is a test translation</0> where ordering changes between languages." }`
`<Trans i18nKey="test" components={[<b></b>]} />`

Proposed solution
`en/common.json
{ "test": "This is a test translation where <bolded>ordering changes between languages</bolded>."}`
`fr/common.json
{ "test": "<bolded>Le this is a test translation</bolded> where ordering changes between languages." }`
`<Trans i18nKey="test" components={{ bolded: <b></b> }} />`

**Comment by jamuhl** [comment]
@rubystephenpoole no...`<0>` references the first item in the components array...nothing todo with the position in the translation string -> in your sample `en` sample is wrong...should be `{ "test": "This is a test translation where <0>ordering changes between languages</0>." }`

**Comment by rubystephenpoole** [comment]
Thanks for the clarification.

**Comment by iamandrewluca** [comment]
@jamuhl can be closed?

**Comment by jamuhl** [comment]
https://react.i18next.com/latest/trans-component#alternative-usage-v-11-6-0

**Comment by florian-milky** [comment]
I tried to use this but it doesn't work?
See https://codesandbox.io/s/react-i18next-forked-7kmz7?file=/src/i18n.js

**Comment by iamandrewluca** [comment]
Try not to use any void elements as keys
https://www.w3.org/TR/2011/WD-html-markup-20110405/syntax.html#syntax-elements

**Comment by florian-milky** [comment]
@iamandrewluca indeed! thanks for quick help

**Comment by nicknijenhuis** [comment]
Very nice that I came across this. Thank you very very much for building this @iamandrewluca my translations using Trans are way more clear now for translators!

**Comment by bwnstck** [comment]
Please update the docs! :)

It was a pain to find the answer... and afaik there is no reference in the docs

**Comment by jamuhl** [comment]
@bwnstck what is missing: https://react.i18next.com/latest/trans-component#alternative-usage-which-lists-the-components-v11.6.0

**Comment by bwnstck** [comment]
ah crazy :D i read this page around 43 times but didn't really understand the use-case ...

i'll have a look at the docs-repo the next days to make it maybe a bit more understandable! 
Thanks for your fast reply :)

**Comment by deepaknegi10** [comment]
I am stuck in a problem as the link text is getting rendered outside of `a` tag.
```
          <Trans
              i18nKey="translation-key"
              components={{
                strong: <strong />,
                link: <a href={csvLink} aria-label="download csv link" />,
              }}
            />
```
and the translation json is as below:
```
{
    translation-key: "Incorrect format. Please use this <strong><link>template</link></strong>."
}
```

The requirement is to use current template as a link to the actual pdf in S3, which I checked is correct. But it is rendering the text `template` outside the `a` tag as below:
```
<span>Incorrect format. Please use this <strong><a href="`correct csv link`"></a>template</strong>.</span>
```

Can someone please suggest what am I doing wrong here?

**Comment by letelete** [comment]
> I am stuck in a problem as the link text is getting rendered outside of `a` tag.
> 
> ```
>           <Trans
>               i18nKey="translation-key"
>               components={{
>                 strong: <strong />,
>                 link: <a href={csvLink} aria-label="download csv link" />,
>               }}
>             />
> ```
> 
> and the translation json is as below:
> 
> ```
> {
>     translation-key: "Incorrect format. Please use this <strong><link>template</link></strong>."
> }
> ```
> 
> The requirement is to use `template` as a link to the actual csv in S3, which I checked is correct. But it is rendering the text `template` outside the `a` tag as below:
> 
> ```
> <span>Incorrect format. Please use this <strong><a href="`correct csv link`"></a>template</strong>.</span>
> ```
> 
> Can someone please suggest what am I doing wrong here?

@deepaknegi10  You probably resolved it already, but anyone finding this thread - From [Documentation](https://react.i18next.com/latest/trans-component):
>Existing self-closing HTML tag names are reserved keys and won't work. Examples: link: <Link />, img: <img src="" />, media: <img src="" />

Replace `link` with other non-reserved key.
