### ISSUE TITLE
Trans component how to pass context?

### ISSUE THREAD

**Issue by tonix-tuft** [i18next/react-i18next#837]
When I use the `useTranslation` hook I can use the `t` function and pass it a `context`.

How can I pass a context to the `Trans` component too?

I couldn't find it in the documentation.

**Comment by jamuhl** [comment]
If you like to pass stuff down by context use the `I18nextProvider` it creates a ContextProvider consumed by the modules components. (https://github.com/i18next/react-i18next/blob/master/src/index.js#L10 is the exposed context Provider)

**Comment by MrLoh** [comment]
@jamuhl this was probably referring not to React context but to the [i18next context feature](https://www.i18next.com/translation-function/context). I'm also looking for this ability, but it doesn't seem to be possible.

**Comment by jamuhl** [comment]
@MrLoh You got it...now that makes more sense...

https://app.gitbook.com/@i18next/s/react-i18next/latest/trans-component#trans-props 

passing prop `tOptions` should do the trick

**Comment by tonix-tuft** [comment]
Hi folks! I ended up creating a wrapper component, like this:

```
export default function MyTranslationComponent(props) {
    const { t } = useTranslation()
    return (
        <Trans {...props} t={function () {
            const args = arguments
            const key = args[0]
            const options = args[1]
            if (props.context) {
                options.context = props.context
            }
            return t(key, options)
        }}>
        </Trans>
    )
}
```

And it works pretty well. Is `tOptions ` something new? I haven't seen it before in the docs.

Also, I see the following "not found" page if I open your link https://app.gitbook.com/@i18next/s/react-i18next/latest/trans-component#trans-props:

![Screen Shot 2019-08-30 at 10 14 25](https://user-images.githubusercontent.com/10134421/64004659-f8766480-cb0e-11e9-802e-f8d53c018a09.png)

**Comment by jamuhl** [comment]
correct link is: https://react.i18next.com/latest/trans-component#trans-props

tOption was existing for long...was just not documented

**Comment by tonix-tuft** [comment]
`tOption was existing for long...was just not documented` Understood, thanks!

**Comment by MrLoh** [comment]
Awesome, thanks for the super quick response.
