### ISSUE TITLE
I18next not passing Functions on Mount.

### ISSUE THREAD

**Issue by RafaelMateus93** [i18next/react-i18next#838]
I have 2 similar components, with similar functions. The only diference i see between them is that one exports withNamespaces and the other don't.

First one:

 - Component

```
class ProfileHeaderBackground extends React.PureComponent<AllPropsModel, StateModel>

export default ProfileHeaderBackground;
```

- Test File
```
const wrapper = mount(
  <ProfileHeaderBackground
     isLoading={isLoading}
     profileType={1}
   />
);

const instance = wrapper.instance();
instance.openAnimationCircleLoop();
```

**Works just fine.**

Second One:

 - Component

```
class RetirementGraphicLaptop extends React.PureComponent<RetirementSimulatorProps, GraphStateModel>

export default withNamespaces('translations')(RetirementGraphicLaptop);
```

- Test File
```
const wrapper = mount(
  <I18nextProvider i18n={i18n}>
    <RetirementGraphicLaptop
       monthly={monthlyActive}
       laptopBreakpointOutput={laptopBreakpoint}
     />
  </I18nextProvider>
);

const instance = wrapper.instance();
instance.openAnimationCircleLoop();
```

**Does not work**... and return:
`TypeError: instance.openAnimationCircleLoop is not a function`

**Comment by jamuhl** [comment]
https://react.i18next.com/latest/withtranslation-hoc#hoist-non-react-statics

**Comment by RafaelMateus93** [comment]
Thank you @jamuhl 
I wish i had found that article earlier.

You can close the issue now. Thanks!

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
