### ISSUE TITLE
instance 

### ISSUE THREAD

**Issue by marc-ed-raffalli** [i18next/react-i18next#839]
Hi, I have the following issue and would hope you could shed a bit of light:

**Describe the bug**

There are two separate instances of i18n, one created explicitly and another implicitly created with default config.
Logging `i18n` from `useTranslation()` in the lib and in the app shows 2 different objects, empty and configured instance

```
 const {t, i18n} = useTranslation('common');
 console.log(i18n);
```

**Occurs in react-i18next version**
The version is the latest and it is used alongside with:

```
"i18next": "15.0.9",
"i18next-browser-languagedetector": "3.0.1",
"i18next-xhr-backend": "2.0.1",
"react-i18next": "10.9.0",
```

This issue is not specific to latest, it is also present in "10.7.0"

**To Reproduce**

The react app initialises one i18n instance (imported by App) and imports components from a library of components (functions) using `useTranslation`.
Translation files are loaded with the `Backend` plugin.
The app and the library are bundled with Webpack, both are on the exact same version of `react-i18next`, `i18next`, etc

```
export default i18next
  .use(initReactI18next)
  .use(LanguageDetector)
  .use(Backend)
  .init({
    debug: true,
    fallbackLng: 'en',
    ns: ['common'],
    defaultNS: 'common',
    fallbackNS: 'common',
    nsSeparator: ':',
    backend: {
      loadPath: 'lang/{{lng}}/{{ns}}.json'
    },
    react: {
      wait: true,
      useSuspense: true
    }
  });
```

**Expected behaviour**

I would expect the instance created and imported at the app level to be accessible by any components.

**Additional context**

Debug being false by default, the logs are only showing one instance:

```
i18next::backendConnector: loaded namespace common for language en
i18next::backendConnector: loaded namespace page-a for language en
i18next::backendConnector: loaded namespace common-b for language en
i18next: languageChanged en
i18next: initialized
```

Moving the initialisation of the instance only moves the issue to the other side.
I tried to expose the declared instance using `I18nextProvider` with no luck either.

Calling `i18n.changeLanguage` from the second instance throws the following error:
`Uncaught TypeError: i18n.changeLanguage is not a function`

----

I hope the summary explains the context, it would be tricky to provide a sandbox.

Have you seen similar behavior, could you please indicate what did I miss?
Many thanks!

**Comment by marc-ed-raffalli** [comment]
Classical... turning this issue around for hours checking the API docs etc. and finding the solution 5mins after posting the issue.

**Solution**
Include `i18next`, `react-i18next`, *etc* in the list of webpack `externals` to prevent multiple instances

Sorry for the bother, excellent lib!

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:

**Comment by marc-ed-raffalli** [comment]
Stared it a few months back, may have a look in how to contribute code-wise when I get a chance :)
