### ISSUE TITLE
Error after upgrading: "Invariant Violation: Hooks can only be called inside the body of a function component.

### ISSUE THREAD

**Issue by harendra119** [i18next/react-i18next#841]
**Describe the bug**
Error after upgrading: "Invariant Violation: Hooks can only be called inside the body of a function component.

**Occurs in react-i18next version**
V 10.0

**Code**
`export default class App extends Component {
render() {
const { t, i18n } = useTranslation();
return (
<View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
<Text style={{ fontSize: 20, marginBottom: 20 }}>{t('hello')}</Text>

<TouchableOpacity onPress={() => i18n.changeLanguage(i18n.language === 'sv' ? 'en' : 'sv')}>
<Text>{t('change')}</Text>
</TouchableOpacity>
</View>
);
}

}
`
![Screen Shot 2019-04-30 at 2 28 09 PM (1)](https://user-images.githubusercontent.com/4833147/56960749-7893ba00-6b6f-11e9-921d-5d78fdca715c.png)

**Comment by jamuhl** [comment]
`class App extends Component` is a class and not a functional component like `function App() {}` 

you can't use hooks inside class components -> you will need to use the HOC `withTranslation` for that case (or the renderprop): https://react.i18next.com/latest/withtranslation-hoc
