### ISSUE TITLE
Send Accept-Language header

### ISSUE THREAD

**Issue by BeOleg** [i18next/react-i18next#842]
Hello!

We are using Django and DRF.

It follows the HTTP RFC and sets language by Accept-Language header.

Is it possible to add this functionality?

I have read in previous issues that you suggest to use the cookie, but cookie only changes on full page reload, and the user can change the language several times within the SPA.

Also, our API runs on a different domain (https://api.nexchnage.io) and the frontend on https://n.exchange

Thanks in advance!

**Comment by jamuhl** [comment]
How is this related to react-i18next? the i18next-browserlanguage-detector you can add a custom detector: https://github.com/i18next/i18next-browser-languageDetector#adding-own-detection-functionality

**Comment by BeOleg** [comment]
Would this allow to set a header on all the requests to the backend?

**Comment by jamuhl** [comment]
Ah...you need to set lng for requests -> just set the header....this has nothing todo with react-i18next

you can get current language by https://www.i18next.com/overview/api#language / https://www.i18next.com/overview/api#languages

**Comment by BeOleg** [comment]
So you suggest to implement it in a custom detector?

**Comment by jamuhl** [comment]
if i understand you right you like to pass language from client to server via accept-language header?

doing so is simple by reading i18next.language and set that header on request

setting language from request...i would just call i18next.changeLanguage as languageDetector runs on init (not bound to any request - so detector can't access that header)
