### ISSUE TITLE
withNamespaces vs withTranslation for connected component

### ISSUE THREAD

**Issue by pinkynrg** [i18next/react-i18next#843]
this used to work:
```
...
export default withNamespaces()(connect(...)(MyComponent))
```

this doesn't work:
```
...
export default withTranslation()(connect(...)(MyComponent))
```

the error got swallowed somewhere so I cant tell. My question is: is the above supposed to work or I'm made a wrong assumption about something?

application root looks like this:
```
ReactDOM.render(
  <I18nextProvider i18n={i18n}>
    <Provider store={store}>
      <Router>
        <Main/>
      </Router>
    </Provider>
  </I18nextProvider>,
  document.getElementById('app')
)
```

**Comment by jamuhl** [comment]
should work...the only difference between them withTranslation does use the hook internally and does not hoist statics.

**Comment by isaachinman** [comment]
@jamuhl Just ran into this in the process of trying to upgrade `next-i18next` to v10. We rely on the hoisting of statics to be able to drive NextJs internals like `getInitialProps`.

What's the reason for not maintaining support of hoisting?

**Comment by jamuhl** [comment]
because statics are not needed in most cases and can easily be hoisted in userland...https://react.i18next.com/latest/withtranslation-hoc#hoist-non-react-statics

**Comment by isaachinman** [comment]
Got it, thanks for the link to docs.
