### ISSUE TITLE
Why does this work if lng is not specified?

### ISSUE THREAD

**Issue by LaraMo** [i18next/react-i18next#844]
Here is my config file:

```
import i18n from 'i18next';
import en from '../locals/en';
import fr from '../locals/fr';
import { initReactI18next } from 'react-i18next';

i18n.use(initReactI18next).init({
	resources: {
		en,
		fr
	},
	fallbackLng: 'en',
	debug: true,
	ns: ['translations'],
	defaultNS: 'translations',
	keySeparator: false,
	interpolation: {
		escapeValue: false,
		formatSeparator: ','
	},
	react: {
		wait: true
	}
});
export default i18n;

```
As you may have noticed, I have never specified the lng. 
However, in my component I do:
`		const t = i18n.getFixedT('fr');
`
and then 
`					<h1>{t('in')}</h1>
`
And the text shows in french,
If I do:
`		const t = i18n.getFixedT('en');
`
The text is now in english. How does that work?
What is the difference between t and getFixedT?

**Comment by jamuhl** [comment]
`i18n.getFixedT` fixes a t to passed lng, ns
