### ISSUE TITLE
Translation not loaded when React Router matches a param in the URL

### ISSUE THREAD

**Issue by PaulRBerg** [i18next/react-i18next#846]
**Describe the bug**
Translations are not loaded when there's a matched param in the URL (matched by React Router).

**Occurs in react-i18next version**
Version `10.9.0`.

**Expected behaviour**

**Screenshots**

It works without the `txHash` param:

<img width="855" alt="Screen Shot 2019-05-04 at 17 30 08" src="https://user-images.githubusercontent.com/8782666/57182014-91171380-6e92-11e9-9bb7-6033c887c380.png">

It doesn't work with the "txHash" param:

<img width="855" alt="Screen Shot 2019-05-04 at 17 29 36" src="https://user-images.githubusercontent.com/8782666/57182024-a12ef300-6e92-11e9-90cf-6bba10175fce.png">

**OS (please complete the following information):**

- Device: MBP 2016 15"
- Browser: Brave Version 0.62.51 Chromium: 73.0.3683.103
- React: 16.8.6
- React Redux: 6.0.1
- React Router: 5.0.0
- Connected React Router: 6.4.0

**Context**

This is how I load i18n and how I use connected-react-router:

```javascript
i18n
  // load translation using xhr -> see /public/locales
  // learn more: https://github.com/i18next/i18next-xhr-backend
  .use(Backend)
  // detect user language
  // learn more: https://github.com/i18next/i18next-browser-languageDetector
  .use(LanguageDetector)
  // pass the i18n instance to react-i18next.
  .use(initReactI18next)
  // init i18next
  // for all options read: https://www.i18next.com/overview/configuration-options
  .init({
    backend: resources,
    debug: process.env.NODE_ENV !== "production",
    fallbackLng: "en",
    keySeparator: false,
    interpolation: {
      escapeValue: false,
    },
  });
```

```jsx
<div id="app-container">
  <MediaQuery query="(min-width: 768px)">
    <Header />
  </MediaQuery>
  <Web3Connect />
  <ConnectedRouter className="app-container" history={history}>
    <Switch>
      <Route exact path="/" component={PayWithSablier} />
      <Route exact path="/dashboard" component={Dashboard} />
      <Route exact path="/stream/:txHash?" component={Stream} />
      <Redirect exact to="/" />
    </Switch>
    <NetworkWarning />
  </ConnectedRouter>
</div>
```

**Comment by jamuhl** [comment]
There is the "failed because parsing" message -> check why the loaded translations are invalid JSON

**Comment by PaulRBerg** [comment]
Can't believe this 🤦‍♂️

Fixed the issue by replacing this:

```javascript
const resources = {
  loadPath: "./locales/{{lng}}.json",
};
```

With this:

```javascript
const resources = {
  loadPath: "/locales/{{lng}}.json",
};
```

Most likely, React Router fiddles with the location of the "locales" files when setting a query string in the URL.

This may have something to do with https://github.com/i18next/react-i18next/issues/431

**Comment by akashutosh77** [comment]
Oh yes, this works 

I had a URL in browser :-  abc.com/sbs/history/lpn/TEST768

Below code was not translating the above URL of react application on hard referesh(ctrl+shift+R) of page although it was working fine on usual redirects but not working(translating) on hard refresh.

```
i18next
.use(LanguageDetector)
.use(HttpApi)
.init({
fallbackLng:"en",
debug: false,
backend: {
loadPath: "../../assets/locales/{{lng}}/translation.json",
},
react: {useSuspense: false}
})
```

I changes the loadPath as below and it started working on hard referesh as well
`loadPath: "/assets/locales/{{lng}}/translation.json",`

Thank you very much @PaulRBerg
