### ISSUE TITLE
I Can't load Common namespace 

### ISSUE THREAD

**Issue by Ahmed-Rafat** [i18next/react-i18next#849]
# Question about react-i18next

I Can't load Common namespace .. defaultNS return undefined and i cant change localpath ... some option don't work

**Comment by jamuhl** [comment]
There must be something wrong in your code / configuration...did you set debug: true to get some more informations?

**Comment by Ahmed-Rafat** [comment]
# Debug
![Screen Shot 2019-05-07 at 8 03 57 AM](https://user-images.githubusercontent.com/22958905/57275618-5fbf6300-709f-11e9-9d34-5a78892f1583.png)

# i18n.js
![Screen Shot 2019-05-07 at 8 04 47 AM](https://user-images.githubusercontent.com/22958905/57275647-71086f80-709f-11e9-9ec2-82fe052d1df8.png)

# server.js
![Screen Shot 2019-05-07 at 8 05 03 AM](https://user-images.githubusercontent.com/22958905/57275662-7b2a6e00-709f-11e9-9112-7d40b4dee382.png)

# _app.js
![Screen Shot 2019-05-07 at 8 05 52 AM](https://user-images.githubusercontent.com/22958905/57275676-867d9980-709f-11e9-8e45-8dfc129f12a0.png)

**Comment by Ahmed-Rafat** [comment]
# Debug
![Screen Shot 2019-05-07 at 8 03 57 AM](https://user-images.githubusercontent.com/22958905/57275618-5fbf6300-709f-11e9-9d34-5a78892f1583.png)

# i18n.js
![Screen Shot 2019-05-07 at 8 04 47 AM](https://user-images.githubusercontent.com/22958905/57275647-71086f80-709f-11e9-9ec2-82fe052d1df8.png)

# server.js
![Screen Shot 2019-05-07 at 8 10 58 AM](https://user-images.githubusercontent.com/22958905/57275732-ab720c80-709f-11e9-8629-62c760aa96fd.png)

# _app.js
![Screen Shot 2019-05-07 at 8 05 52 AM](https://user-images.githubusercontent.com/22958905/57275676-867d9980-709f-11e9-8e45-8dfc129f12a0.png)

**Comment by jamuhl** [comment]
looks like your page gets rendered before i18next loaded the translations.

- evtl. misses the withNamespaces HOC
- you removed something needed (as the sample provided in next-i18next works)

=> this question is related to using next-i18next -> ask there: https://github.com/isaachinman/next-i18next as i do not know all internals of that integration anymore.

**Comment by Ahmed-Rafat** [comment]
very Thanks
