### ISSUE TITLE
how to use react-i18next of v10 to nextjs?  get language by queryString (?lang=en)

### ISSUE THREAD

**Issue by huanglijiao** [i18next/react-i18next#850]
# Question about react-i18next

Questions should be posted on StackOverflow

**Comment by huanglijiao** [comment]
we want to set the langauge of the i18n instant by queryString. we used react-i18next on SSR by nextjs.
for example,  our page url: https://www.joox.com/node/zh_hk/kplaylist?page=kplaylist&id=4&lang=zh_TW&country=hk

we need to get the param "lang" from url, then set the initLanguage of i18n instance.

**Comment by huanglijiao** [comment]
we use react-i18next v10

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next-browser-languageDetector#detector-options -> change lookupQuerystring to lang

**Comment by huanglijiao** [comment]
it can support two params of url.  for example:
const country = query.country ? query.country : 'th'
const lang = query.lang ? query.lang : 'th';
const lng = `${lang}_${country}`

**Comment by huanglijiao** [comment]
the code:

_app.js:
import React from 'react';
import App, { Container } from 'next/app';
import i18n from 'i18next';
import { I18nextProvider } from 'react-i18next';
import XHR from 'i18next-xhr-backend';
import i18nConfig from '../tool/i18nConfig';

class MyApp extends App {
  static async getInitialProps({ Component, ctx }) {
    let pageProps = {};

    if (Component.getInitialProps) {
      pageProps = await Component.getInitialProps(ctx);
    }
    const query = ctx.query;

    return { pageProps, query };
  }

  constructor(props) {
    super(props)
    const { pageProps, query } = props;

    if (!this.i18n) {
      const country = query.country ? query.country : 'th'
      const lang = query.lang
        ? query.lang
        : 'th';

      const lng = `${lang}_${country}`
      i18n.use(XHR).init({
        ...i18nConfig,
        lng,
        backend: {
          loadPath: `../static/locales/{{lng}}/{{ns}}.json`,
        },
      });

      this.i18n = i18n;

      //this.initialI18nStore = (this.i18n.services.resourceStore.data['th_th'] || {})['common'];
    }
  }

  render() {
    const { Component, pageProps } = this.props;
    const { initialLanguage } = pageProps;

    return (
      <Container>
        <I18nextProvider
          i18n={this.i18n}
          initialI18nStore={this.initialI18nStore}
          initialLanguage={'th_th'}>
          <Component {...pageProps} />
      </I18nextProvider>
      </Container>
    );
  }
}

export default MyApp;


i18nConfig.js:
export default {
  fallbackLng: false,
  load: 'currentOnly',
  ns: ['common', 'second-page'],
  defaultNS: 'common',

  debug: false, // process.env.NODE_ENV !== 'production',

  interpolation: {
    escapeValue: false, // not needed for react!!
    formatSeparator: ',',
    format: (value, format, lng) => {
      if (format === 'uppercase') return value.toUpperCase()
      return value
    },
  },
  react: {
    useSuspense: false
  }
};


index.js:
import React from 'react'
import PropTypes from 'prop-types'
import { withTranslation }  from 'react-i18next';

class Homepage extends React.Component {

    static async getInitialProps(ctx) {

      return {
        data: '测试多语言'
      }
    }

    render() {
        const { data, t } = this.props;

        return (
            <React.Fragment >
                <p>{t('测试多语言')}</p>

            </React.Fragment>
        )
    }
}

Homepage.propTypes = {
    //t: PropTypes.func.isRequired,
}

export default withTranslation('common')(Homepage);


the result on brower is that:  we first see "测试多语言", then we can see the translation of "测试多语言".
Maybe function t is run on brower, not server. So how can we run function t  on server?

**Comment by huanglijiao** [comment]
another problem:
we use i18next-xhr-backend, but error:
ReferenceError: XMLHttpRequest is not defined
    at Object.ajax (/Applications/hust-dev/nextjs/node_modules/i18next-xhr-backend/dist/commonjs/ajax.js:46:5)
    at Backend.loadUrl (/Applications/hust-dev/nextjs/node_modules/i18next-xhr-backend/dist/commonjs/index.js:82:20)
    at Backend.read (/Applications/hust-dev/nextjs/node_modules/i18next-xhr-backend/dist/commonjs/index.js:75:12)
    at Connector.read (/Applications/hust-dev/nextjs/node_modules/i18next/dist/commonjs/BackendConnector.js:184:34)
    at Connector.loadOne (/Applications/hust-dev/nextjs/node_modules/i18next/dist/commonjs/BackendConnector.js:250:12)
    at /Applications/hust-dev/nextjs/node_modules/i18next/dist/commonjs/BackendConnector.js:223:16
    at Array.forEach (<anonymous>)
    at Connector.prepareLoading (/Applications/hust-dev/nextjs/node_modules/i18next/dist/commonjs/BackendConnector.js:222:21)
    at Connector.load (/Applications/hust-dev/nextjs/node_modules/i18next/dist/commonjs/BackendConnector.js:229:12)
    at I18n.loadResources (/Applications/hust-dev/nextjs/node_modules/i18next/dist/commonjs/i18next.js:239:40)
    at setLng (/Applications/hust-dev/nextjs/node_modules/i18next/dist/commonjs/i18next.js:320:16)
    at I18n.changeLanguage (/Applications/hust-dev/nextjs/node_modules/i18next/dist/commonjs/i18next.js:330:9)
    at Timeout.load [as _onTimeout] (/Applications/hust-dev/nextjs/node_modules/i18next/dist/commonjs/i18next.js:178:16)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)

**Comment by huanglijiao** [comment]
one more question:
can we use the same  i18n instance on browser and server?

**Comment by jamuhl** [comment]
using next.js why not just follow -> https://github.com/isaachinman/next-i18next (avoid all possible problems using all this first time)

Can't help you with every problem in your code (like "XMLHttpRequest is not defined" - sure it's not defined - it's node - not a browser -> use i18next-express-middleware, i18next-fs-backend, ...)
