### ISSUE TITLE
Unable to convert List/FlatList..

### ISSUE THREAD

**Issue by shiprasharma12** [i18next/react-i18next#851]
I am trying to change language of ListView or FlatList from English to Arabic but I don't know the syntax for writing Array to create its Localized file. 

Please help , Thank you in advance.

**Comment by jamuhl** [comment]
Please ask questions not related directly to the module over at stackoverflow...you can't expect me to digg through implementation details of react natives lists and try to understand what you like to achieve by as litte information given....
