### ISSUE TITLE
useSuspence vs wait

### ISSUE THREAD

**Issue by klis87** [i18next/react-i18next#854]
**Is your feature request related to a problem? Please describe.**
In previous versions there was react `wait` option. I believe it is gone now, and that it was replaced by suspence. The problem is that wrapping whole app in suspence will cause flickering of the whole app on any namespace load. Suspence can be triggered after initial load when additional component is mounted with new namespace required. It will also get triggered on language change. One of the things I like so much about this library is that u can change language and all state is kept, use can continue working in the same place and with even the same scrolling position.  

**Describe the solution you'd like**
Revert `wait` option as alternative to suspence

**Describe alternatives you've considered**
Alternatively we could wrap any translatable node with separate suspence, but I guess this would introduce too much overhead in React tree. Previous `wait` solution was much better, on lang change previous lang was kept until new was loaded, and on load there was no any flickering, and no additional setup was required.

**Additional context**
N/A

**Comment by klis87** [comment]
In theory I could also do `parseMissingKeyHandler: () => ''`. Would it work the same like previous wait option more or less? Or maybe u have another solution to my problem. Or maybe there is a more clever suspense usage? But I believe suspence is not for me, because I really doesnt wanna show any spinners etc on language change

**Comment by jamuhl** [comment]
Do you know what wait: true did in the past? it did nothing but render null instead of your component...

you can in v10 opt out from using suspence: https://react.i18next.com/latest/usetranslation-hook#not-using-suspense

and bindI18n to languageChanged only - currently binds changing too (this would avoid "flickering" during load): https://github.com/i18next/react-i18next/blob/master/src/context.js#L4

**Comment by klis87** [comment]
I already use `bindI18n: 'languageChanged'`

So `wait: true` is exactly what I need and I miss right now. I read about `opt out from using suspence`, but this has 2 issues:
- I would need to check for `ready` props in multi places, `wait` just work globally and automatically
- `ready` is `false` on language change, while I really want components to render previous language until new one is loaded, I don't want to show spinners or anything like it

**Comment by jamuhl** [comment]
create on HOC doing what you like...use that on page level components -> set bindI18n to '' for all other usages.

We won't go back to the old API...if you need that just keep using v9

**Comment by klis87** [comment]
I see, for now I will stick to `parseMissingKeyHandler`, if I need, I will write my hoc based on `useTranslation` hook

**Comment by nicolama-dev** [comment]
@klis87  I agree with you - removing `wait` is clearly causing an issue. What was you solution at the end?

**Comment by klis87** [comment]
Actually if I remember correctly, I ended up using suspense
