### ISSUE TITLE
`locizeLastUsed` and `editor` are missing from `InitOptions` interface (TypeScript)

### ISSUE THREAD

**Issue by Boscop** [i18next/react-i18next#858]
**Describe the bug**
The members `locizeLastUsed` and `editor` are missing from `InitOptions`, defined in `node_modules/i18next/index.d.ts`. 
So I get a compiler error when trying to pass these options like [this](https://github.com/i18next/react-i18next/blob/1277ec2e42a2b225f4427dc90b306079a308572f/example/locize/src/i18n.js#L51-L52).

**Occurs in react-i18next version**
10.9.0

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next/pull/1248
