### ISSUE TITLE
Could react-i18next  be used with zanata translation service?

### ISSUE THREAD

**Issue by sindhuanamal** [i18next/react-i18next#863]
Hi,

I am trying to figure out the right library for adding translations to my reactjs application that gets the translations from zanata translating service. It needs the files of format .po . 

In using react-i18next how can i use this zanata translation service. 

Could you describe in brief the workflow.. thanks.

**Comment by jamuhl** [comment]
You might ask here: https://bitbucket.org/tagoh/i18next-node-zanata-backend/src/master/ or zanata support.

Even better would be using our https://locize.com which directly connects to i18next: https://github.com/i18next/react-i18next/tree/master/example/locize

**Comment by sindhuanamal** [comment]
okay thanks for the reply.
