### ISSUE TITLE
How to translate the value in state (basically whatever user inputs)?

### ISSUE THREAD

**Issue by sindhuanamal** [i18next/react-i18next#864]
Hi, i am new to translations and using react-i18next library.  I have started to translate simpler  strings and i am kind of stuck about how to translate a value that user enters in the form input element.
 
I have en.json where my translations are for the strings.
code looks like below,
<Validate
      name="name" placeholder="Name" required value={state.name}
      onChange={this.handle_input_change} />

How can i translate the value attribute? thanks.

**Comment by jamuhl** [comment]
you mean interpolate a user input in a translated string? -> https://www.i18next.com/translation-function/interpolation

**Comment by sindhuanamal** [comment]
So following the doc https://www.i18next.com/translation-function/interpolation i tried something like below,
<Validate
      name="name" placeholder="Name" required value={t('key',{state.name})}
      onChange={this.handle_input_change} />

It throws error expected token..

**Comment by jamuhl** [comment]
`t('key', state.name)` ---> the state.name is a string

should be: `t(key, options)` --> `t('key', { /* object containing the variables you like to interpolate */ })`

====> `t('key', { state })` as you take `"key": "{{state.name}}"` it expects a object state and takes the deeper var name in it

or you can `"key": "{{name}}"` and `t('key', { name: state.name})`

**Comment by sindhuanamal** [comment]
thanks for the explanation. works.

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
