### ISSUE TITLE
How do i translate array of objects?

### ISSUE THREAD

**Issue by sindhuanamal** [i18next/react-i18next#865]
Hi i want to translate the name in the below data structure named data,

export default class Example extends React.PureComponent {
    data = [
        {name:"first", id:"2", val: "3"},
        {name:"second", id:"2", val: "5"},
   ]
   
  render() {
  return (
      <ChildComponent
              values={this.filter_options}/>)
 }
}

How can i translate the name for data variable.
I have tried using 
data = [
        {name:t('first_name'), id:"2", val: "3"},
        {name:t('second_name)', id:"2", val: "5"},
   ]

But doesn't seem to work. Thanks

**Comment by jamuhl** [comment]
you can either...import i18n and use i18n.t(...)

or better do translations in the render function -> statics won't be retranslated eg. on languageChange...it's javascript not magic ;)

**Comment by sindhuanamal** [comment]
hmm translating it in the render like 

render() {
const {t} = this.props;
data = [
{name:t('first_name'), id:"2", val: "3"},
{name:t('second_name)', id:"2", val: "5"},
]

says t is not a function.

**Comment by jamuhl** [comment]
did you use the hoc `withNamespaces` or pass down the t function from container component to sub component...

**Comment by sindhuanamal** [comment]
not using withNamespaces... i have i18n.js file with configurations like
import i18n from 'i18next';
import Backend from 'i18next-xhr-backend';
import LanguageDetector from 'i18next-browser-languagedetector';
import { initReactI18next } from 'react-i18next';

const fallbackLng = ['en'];
const availableLanguages = ['en'];

i18n
  .use(Backend) // load translation using xhr -> see /public/locales. We will add locales in the next step

  .use(LanguageDetector) // detect user language

  .use(initReactI18next) // pass the i18n instance to react-i18next.

  .init({
    fallbackLng, // if user computer language is not on the list of available languages, than we will be using the fallback language specified earlier
    debug: true,
    whitelist: availableLanguages,

    interpolation: {
      escapeValue: false
    },
  });

export default i18n;

i import this i18n in app.js
and within components i use t functions..

I am not sure if this is the right way to do it.

**Comment by jamuhl** [comment]
Do you know how react works? what higher order components or hooks are?

Why not read the step by step guide? https://react.i18next.com/latest/using-with-hooks
