### ISSUE TITLE
Trigger translations after i18n.reloadResources

### ISSUE THREAD

**Issue by butchyyyy** [i18next/react-i18next#866]
**Describe the bug**
We're using useTranslation hook in our react components. When calling i18n.reloadResources the component won't render new texts.

The use case is using react-i18next and i18next with locize cloud services and locize-editor.
With following configuration:

```typescript
i18n
  .use(locize)
  .use(locizeEditor)
  .use(initReactI18next)
  .init({editor: {
    onEditorSaved: (lng: string, ns: string) => {
      getI18n().reloadResources(lng, ns)
    },
  })
```
Saving changes in the locize editor will reload the namespace from locize cloud, but the react component will not render new strings and full reload has to be performed.

**Occurs in react-i18next version**
10.9.0

**To Reproduce**

1. Use react-i18next and i18next with above mentioned configuration.
2. Load the app with ?locize=true parameter.
3. Edit and save some string in the locize-editor.
4. New resource is downloaded, but new strings are not rendered.

**Expected behaviour**
After calling the reloadResources, component rerenders with new translations. Optionally add method we can call in the reloadResources callback.

**Screenshots**
N/A

**OS (please complete the following information):**
- Device: Windows 10
- Browser: Chrome 74.0.3729.169

**Additional context**
N/A

**Comment by jamuhl** [comment]
not sure but we solved it by binding an extra event like:

emit: https://github.com/i18next/react-i18next/blob/master/example/locize/src/i18n.js#L59
and bind component reload: https://github.com/i18next/react-i18next/blob/master/example/locize/src/i18n.js#L63

**Comment by jamuhl** [comment]
there is also the "loaded" event - but that would eventual be triggered more than once -> so for us the above solution is the best option

**Comment by butchyyyy** [comment]
I was trying to find a way to do it in the docs and this seems to do the trick. I'll do some more testing today and if it's ok close the issue.
Thanks a lot!

**Comment by butchyyyy** [comment]
Sorry for the late reply. Works like a charm.
Thanks again Jan.
