### ISSUE TITLE
Problem translate with ":"

### ISSUE THREAD

**Issue by khoanguyen2610** [i18next/react-i18next#869]
Dear, 
Today i got a problem when issue react-i18next in my project.
I have a key like this **"today: my birthday"** and i want to translate this with **t("today: my birthday")**
Result i got is **"my birthday"**.
How can i translate ":" with react-i18next.
Best regards,

**Comment by jamuhl** [comment]
`:` acts as namespace separator -> accessing different "files"

-> see the basics: https://www.i18next.com/translation-function/essentials#accessing-keys-in-different-namespaces

setting `nsSeparator: false` on init removes that namespace discovery by `:` -> https://www.i18next.com/overview/configuration-options#misc

**Comment by khoanguyen2610** [comment]
> `:` acts as namespace separator -> accessing different "files"
> 
> -> see the basics: https://www.i18next.com/translation-function/essentials#accessing-keys-in-different-namespaces
> 
> setting `nsSeparator: false` on init removes that namespace discovery by `:` -> https://www.i18next.com/overview/configuration-options#misc

It works for me, thank you so much

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:

**Comment by dwalintukan** [comment]
`nsSeparator: false` or `namespaceSeparator: false` does not work for me.

**Comment by jamuhl** [comment]
@dwalintukan if it does not work on i18next-parser opening an issue or feature request there might help...

**Comment by dwalintukan** [comment]
Sorry, you're right. This was the wrong repo to post in.
