### ISSUE TITLE
Question on trans component

### ISSUE THREAD

**Issue by sindhuanamal** [i18next/react-i18next#874]
Hi, i am a beginner in using react-i18next and wanted to know how to use trans component for the content like below,

<span>
     {name} has {this.get_link()}
 </span>

What i have tried 
<Trans i18nKey="name">
    <span>{{name}} has {{this.get_link()}}</span>
</Trans>

This doesn't work. could someone provide some insights into this. thanks.

**Comment by jamuhl** [comment]
i see...think of the interpolation as passing objects

`{{ name }}` equals passing `{ name: name }`
`{{ this.get_link() }}` gives not what you like ---> `{{ link: this.get_link() }}` will pass down "link" to interpolation

translate string: `some {{name}} go to {{link}}` 

hope that is understandable - I know - getting started can be hard - just stay on it and learn on the way

**Comment by sindhuanamal** [comment]
Thanks works :)

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:

**Comment by sindhuanamal** [comment]
sorry that i had to reopen the issue.  when i use

{{name}} has {{link: this.get_link()}}
the value for name is shown proper in frontend however {{link: this.get_link()}} shows [object object] i have tried to define it in the variable
const link = this.get_link();

and use it like
{{link}}

Could you please let me know how to fix this. thanks.

**Comment by jamuhl** [comment]
you mean this.get_link() returns a Link component? in that case, you need to use https://react.i18next.com/latest/trans-component

**Comment by sindhuanamal** [comment]
okay tried to use something like
<Trans
     i18nKey="key1"
     defaults='{{name}} modified: {{text}}
     {{" "}}for the details <0><0></0></0>
     {{" "}}for item <1><0></0></1>'
     values={{name: person.name, text: details.text}}
     components={[this.get_details_link(), this.get_item_link()]}
/>

this works. but it throws some error likei18next.js:27 i18next::interpolator: missed to pass in variable " " for interpolating name modified: ffff
                            {{" "}}for the details <0><0></0></0>
                            {{" "}}for item <1><0></0></1>

what's that i am missing here. thanks

**Comment by jamuhl** [comment]
remove those `{{" "}}` in defaults -> just use a regular space

**Comment by sindhuanamal** [comment]
Thanks.
