### ISSUE TITLE
Usage of trans component with plurals

### ISSUE THREAD

**Issue by sindhuanamal** [i18next/react-i18next#875]
Hi, 

wanted to translate string below,

<p>set to {!some_var[key] && 'in'}editable</p>

I tried using trans component and count and i am using i18next-scanner for extracting key but doesn't work...I have looked into examples on react-i18next docs but not knowing how to use trans and count in this usecase.

Could someone help me with this. thanks.

**Comment by jamuhl** [comment]
not sure if i18next-scanner support that -> please provide a PR there for proper extraction.

For Trans set prop count on it - and keep thing being objects in code and strings in translations ;)

translation: `set to {myVar} editable`

code: `set to {{myVar: !some_var[key] && 'in'}} editable`

**Comment by sindhuanamal** [comment]
hmm thanks not sure if i18next-scanner can parse it..
