### ISSUE TITLE
[error/warning]: You will need pass in an i18next instance by using initReactI18next

### ISSUE THREAD

**Issue by devboell** [i18next/react-i18next#876]
Sorry to bother, I posted this question first on [SO](https://stackoverflow.com/questions/56643895/react-i18next-you-will-need-pass-in-an-i18next-instance-by-using-initreacti18n) 

I am using i18next and react, and locally it works as expected, but when I deploy on Surge I always get this error:
`react-i18next:: You will need pass in an i18next instance by using initReactI18next`

They way I implemented it is almost identical to the react-i18next documentation.

**main.jsx**
```
import React from 'react'
import ReactDOM from 'react-dom'
import { Provider } from 'react-redux'
import 'tabler-react/dist/Tabler.css'
import { BrowserRouter as Router } from 'react-router-dom'
import App from './App/container'
import i18next from './services/app/i18n'
// import './services/app/i18n' /* eslint-disable-line no-unused-vars */

import initStore from './initStore'

import '../sass/style.scss'
import 'dropzone/dist/dropzone.css'
import 'c3/c3.css'

const store = initStore()

// console.log('i18next', i18next) // if I uncomment this, it works on test server

ReactDOM.render(
  <Provider store={store}>
    <Router>
      <App />
    </Router>
  </Provider>,
  document.getElementById('root'),
)

```

**services/app/i18n.js**
```
import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'
import Fetch from 'i18next-fetch-backend'

import * as apiConfig from '../../../config/api'

import { transformTranslationsData } from './translation-helpers'

const apiEnv = apiConfig[API_ENV]


i18n
  .use(Fetch)
  .use(initReactI18next)
  .init({
    // debug: true,
    lng: 'en',
    keySeparator: false,
    fallbackLng: {
      default: [ 'en' ],
    },
    interpolation: {
      escapeValue: false, // react already safes from xss
    },
    react: {
      // wait: true,
      useSuspense: false,
    },
    backend: {
      loadPath: `${apiEnv.api}/translations?limit=0&locale={{lng}}&key=cm.*`,
      allowMultiLoading: true,
      parse: transformTranslationsData,
    },
  })

export default i18n

```

The thing I don't understand is that when I console.log the `i18next` variable in `main.jsx`, it prints out the initialised object, and it works when deployed. If I don't log it, it just shows the error and the translations are not available in the app.

  I am using these versions:
```
    "i18next": "^15.1.0",
    "i18next-fetch-backend": "^2.2.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-i18next": "^10.9.0",
```

It is going to be tricky for me to make a small repo that reproduces this error. For now I am hoping on clues and suggestions so I can investigate further.

**Comment by jamuhl** [comment]
What happens...the console.log statement does not come for free blocking execution below - which gives i18next the needed time to initialize (that's my guess).

So what basically happens as you do not use Suspense - and my guess you also do not handle `ready` props...your rendering happens before i18next even called init and long before translation files are loaded...

You might set `initImmediate : false` on i18next.init -> that at least might get that error away - but my guess will still leave you with missings during rendering as the translations were not yet loaded.

**Comment by devboell** [comment]
thanks @jamuhl,

  I wasn't aware of the `ready` prop. I will try to use it.

**Comment by jamuhl** [comment]
https://react.i18next.com/latest/usetranslation-hook#not-using-suspense
https://react.i18next.com/latest/withtranslation-hoc#not-using-suspense

**Comment by jamuhl** [comment]
sometimes it helps to talk about the issue - or in the worst case some distance to the problem and solutions come up

**Comment by devboell** [comment]
on the off chance that someone else runs into this, the error had nothing to do i18next, and it was merely a faulty webpack setting.

  In package.json we had:
```
"sideEffects": false
```
the issue got resolved by changing it into:

```
"sideEffects": [
    "./src/services/app/i18n.js"
  ]
```

**Comment by spsaucier** [comment]
In my case, the warning appeared during jest tests. For the time being, I've gotten around it by redefining `t` if in a test:
```
const { t } = jest ? s=>s : useTranslation();
```

**Comment by sgwilym** [comment]
@devboell Thanks, you've saved me what would have probably been a few hours of hair-tearing.

**Comment by chrisfinch** [comment]
For getting rid of Jest warnings easier than modifying components themselves:

```js
jest.mock('react-i18next', () => ({
  useTranslation: () => ({t: key => key})
}));
```

**Comment by DevScissors** [comment]
I am still getting a warning about i18nextReactModule in my App.test.js. I had more errors but researched and found this thread and added I18nextProvider to fix a few of them. Below are the files I am working with. Any help would be appreciated.

**i18n.js**
```
import i18n from 'i18next';
import LanguageDetector from 'i18next-browser-languagedetector';
import { initReactI18next } from 'react-i18next';
import usLocale from '../public/locales/en/en-us';
import ukLocale from '../public/locales/uk/en-uk';

i18n
    .use(LanguageDetector)
    .use(initReactI18next)
    .init({
        // we init with resources
        resources: {
            en: usLocale,
            uk: ukLocale,
        },
        fallbackLng: 'en',
        // have a common namespace used around the full app
        ns: ['translations'],
        defaultNS: 'translations',
        interpolation: {
            escapeValue: false // not needed for react as it escapes by default
        }
    });


export default i18n;`
```

**App.js**
```
import { hot } from 'react-hot-loader/root';
import React from 'react';
import './style.less';
import { useTranslation, Trans, I18nextProvider } from 'react-i18next';
import ComponentUseTranslation from '../tests/UseTranslation';

const App = () => {
    const { t, i18n } = jest ? { t: (s) => s } : useTranslation();
    return (
        <I18nextProvider i18n={i18n}>
            <div className="App">
                <div className="App-header">
                    <h2>{t('welcome')}</h2>
                    <button onClick={() => i18n.changeLanguage('uk')}>uk</button>
                    <button onClick={() => i18n.changeLanguage('en')}>en</button>
                </div>
                <div className="App-intro">
                    <Trans i18nKey="get-started">trans</Trans>
                </div>
                <div style={{ marginTop: 40 }}>
                    Learn more:&nbsp;
                    <a href="https://react.i18next.com">https://react.i18next.js</a>
                </div>
                <ComponentUseTranslation />
            </div>
        </I18nextProvider>
    );
};

export default hot(App);
```

**App.test.js**
```
import React from 'react';
import ReactDOM from 'react-dom';
import App from '../src/App';

it('renders without crashing', () => {
    const div = document.createElement('div');
    ReactDOM.render(<App />, div);
    ReactDOM.unmountComponentAtNode(div);
});
```
**UseTranslation.js**
```
import React from 'react';
import { useTranslation, I18nextProvider } from 'react-i18next';

import Enzyme from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

Enzyme.configure({ adapter: new Adapter() });

const CustomComponent = () => {
    const { t, i18n } = jest ? { t: (s) => s } : useTranslation();

    return (
        <I18nextProvider i18n={i18n}>
            <div>{t('welcome')}</div>
        </I18nextProvider>
    );
};

export default CustomComponent;
```

**UseTranslation.test.js**
```
import React from 'react';
import App from './UseTranslation';
import Enzyme, { mount } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

Enzyme.configure({ adapter: new Adapter() });

it('test render', () => {
    const mounted = mount(<App />);
    expect(mounted.contains(<div>welcome</div>)).toBe(true);
});
```
![image](https://user-images.githubusercontent.com/33975336/76482166-9f965b80-63d0-11ea-95ff-18236b175624.png)

**Comment by jamuhl** [comment]
@DevScissors where do you import the i18n.js?!?

The implementation is not:

Get i18n from useTranslation and pass it to the I18nextProvider. The I18nextProvider would get it from the import and would be the most outer Element (before getting t, i18n from useTranslation). The Provider is only needed if not calling `.use(initReactI18next)`.

```
import { hot } from 'react-hot-loader/root';
import React from 'react';
import './style.less';
import { useTranslation, Trans } from 'react-i18next';
import ComponentUseTranslation from '../tests/UseTranslation';

// import it
import from `./i18n.js`

const App = () => {
    const { t, i18n } = jest ? { t: (s) => s } : useTranslation();
    return (
        // nono: <I18nextProvider i18n={i18n}>
            <div className="App">
                <div className="App-header">
                    <h2>{t('welcome')}</h2>
                    <button onClick={() => i18n.changeLanguage('uk')}>uk</button>
                    <button onClick={() => i18n.changeLanguage('en')}>en</button>
                </div>
                <div className="App-intro">
                    <Trans i18nKey="get-started">trans</Trans>
                </div>
                <div style={{ marginTop: 40 }}>
                    Learn more:&nbsp;
                    <a href="https://react.i18next.com">https://react.i18next.js</a>
                </div>
                <ComponentUseTranslation />
            </div>
        // </I18nextProvider>
    );
};

export default hot(App);
```

**Comment by DevScissors** [comment]
@jamuhl Thank you, that fixed the warnings! I am still brand new to using i18next and pretty new to jest so this has been a bit of a rough ride. Thankfully it seems I was close :)

**Comment by luciomartinez** [comment]
> For getting rid of Jest warnings easier than modifying components themselves:
> 
> ```js
> jest.mock('react-i18next', () => ({
>   useTranslation: () => ({t: key => key})
> }));
> ```

Extending it for the case of handling objects:

```
const { t } = useTranslation();
const translations = t('my.key', { returnObjects: true });
translations.message.replace('{hash}', 'value');
```

It'd be:

```
jest.mock('react-i18next', () => ({
  useTranslation: () => ({
    t: (key) => ({
      message: key
    })
  })
}));
```

**Comment by eugenetumachov** [comment]
> For getting rid of Jest warnings easier than modifying components themselves:
> 
> ```js
> jest.mock('react-i18next', () => ({
>   useTranslation: () => ({t: key => key})
> }));
> ```

For those who use Trans component, it makes sense to mock it as well: 

```javascript
jest.mock("react-i18next", () => ({
  useTranslation: () => ({ t: key => key }),
  Trans: ({ children }) => children
}));
```

Otherwise there will be an error of "Invariant Violation: Element type is invalid".

**Comment by VisheshSingh** [comment]
Can someone explain where (which file) we need to write 👇
```
jest.mock('react-i18next', () => ({
  useTranslation: () => ({t: key => key})
}));
```
Do we need to have it within our test.js file or component.js file?

**Comment by rogger-frogger** [comment]
> Can someone explain where (which file) we need to write 👇
> 
> ```
> jest.mock('react-i18next', () => ({
>   useTranslation: () => ({t: key => key})
> }));
> ```
> 
> Do we need to have it within our test.js file or component.js file?

You can place it at the top of the file right after file imports and before the describe block

**Comment by saurkadam** [comment]
`jest.mock('react-i18next', () => ({
  useTranslation: () => ({t: key => key})
}));`

**Comment by IagoLast** [comment]
@VisheshSingh @rogger-frogger 

jest allows to define a set of setup files to handle this kind of stuff
- https://jestjs.io/docs/en/configuration#setupfiles-array

In create-react-app this file is called [setupTests.js](https://create-react-app.dev/docs/running-tests/#srcsetuptestsjs)


```ts
beforeEach(() => {
  jest.mock('react-i18next', () => ({
    useTranslation: () => ({ t: (key: string) => key })
  }));
});
```

**Comment by RSginer** [comment]
Using Jest with [next](https://nextjs.org/) and [next-i18next](https://www.npmjs.com/package/next-i18next)

My solution was:
`jest.mock('./i18n', () => ({
    withTranslation: (i18nFile) => (component) => {
        const i18nJson = require(`./public/static/locales/en-US/${i18nFile}.json`)

        return ((props) => component({t: key => i18nJson[key], ...props}))
    },
    i18n: {
        language: "en-US"
    }
}));`

**Comment by FDiskas** [comment]
can remember where I found this but it works really nice
**src/__mocks__/react-i18next.js**
```js
const React = require('react');
const reactI18next = require('react-i18next');

const hasChildren = (node) => node && (node.children || (node.props && node.props.children));

const getChildren = (node) =>
    node && node.children ? node.children : node.props && node.props.children;

const renderNodes = (reactNodes) => {
    if (typeof reactNodes === 'string') {
        return reactNodes;
    }

    return Object.keys(reactNodes).map((key, i) => {
        const child = reactNodes[key];
        const isElement = React.isValidElement(child);

        if (typeof child === 'string') {
            return child;
        }
        if (hasChildren(child)) {
            const inner = renderNodes(getChildren(child));
            return React.cloneElement(child, { ...child.props, key: i }, inner);
        }
        if (typeof child === 'object' && !isElement) {
            return Object.keys(child).reduce((str, childKey) => `${str}${child[childKey]}`, '');
        }

        return child;
    });
};

const useMock = [(k) => k, {}];
useMock.t = (k) => k;
useMock.i18n = {};

module.exports = {
    // this mock makes sure any components using the translate HoC receive the t function as a prop
    withTranslation: () => (Component) => (props) => <Component t={(k) => k} {...props} />,
    Trans: ({ children }) =>
        Array.isArray(children) ? renderNodes(children) : renderNodes([children]),
    Translation: ({ children }) => children((k) => k, { i18n: {} }),
    useTranslation: () => useMock,

    // mock if needed
    I18nextProvider: reactI18next.I18nextProvider,
    initReactI18next: reactI18next.initReactI18next,
    setDefaults: reactI18next.setDefaults,
    getDefaults: reactI18next.getDefaults,
    setI18n: reactI18next.setI18n,
    getI18n: reactI18next.getI18n,
};

```

**Comment by yangalli** [comment]
> "./src/services/app/i18n.js"

Dude, you saved my day. Thanks a lot!!

**Comment by natterstefan** [comment]
Thanks for the example @FDiskas.

> can't remember where I found this but it works really nice
> **src/**mocks**/react-i18next.js**

It's from here https://github.com/i18next/react-i18next/blob/7cfab9746b3ccc6f833cd9c892e7c3c804944a5e/example/test-jest/src/__mocks__/react-i18next.js.

**Comment by pgriscti** [comment]
create a `src/setupTests.ts` with the following:

```
import '@testing-library/jest-dom';

jest.mock("react-i18next", () => ({
  useTranslation: () => ({ t: (key: string) => key }),
}));
```

**Comment by igorlino** [comment]
Maybe useful for others, there is some good infos describing how to setup the test properly at:
https://react.i18next.com/misc/testing

I personally don't want stubbing, and there is an example for that.

**Comment by Philzen** [comment]
Maybe i'm overlooking something here, but for me the fix was a mere one-liner. Simply added

```js
  setupFiles: ['web/src/i18n'],
```

to the `config`-array in `jest.config.js` and the warning stopped.
