### ISSUE TITLE
Transform key to lower with HOC

### ISSUE THREAD

**Issue by khoanguyen2610** [i18next/react-i18next#877]
Dear, 
Today i got an issue. I want to lower key before compare resource. Mean, when i use t("AbcD") and my resource is { abcd: "Translate abcd"}, i will got "Translate abcd".
How can i do it?
Thank you

**Comment by jamuhl** [comment]
`t("AbcD".toLowerCase());` eventually?

**Comment by khoanguyen2610** [comment]
> `t("AbcD".toLowerCase());` eventually?

We have any config for this always upper or lower?

**Comment by jamuhl** [comment]
No there is no config for this...can you describe your use case? I'm not understanding the need of converting a key this way at all -> is it just to avoid typos?!?
