### ISSUE TITLE
using context creates two keys 

### ISSUE THREAD

**Issue by sindhuanamal** [i18next/react-i18next#880]
Hi,

i have a component for which i need to pass name prop something like 

<Somecomponent
     name={`${t('Add a name to', {context: 'user_name'})} ${user.name}`}
/ >
using i18next scanner to extract strings,
So this create two keys like below,

"Add a name to": "Add a name to"
"Add a name to user_name": "Add a name to"

I need only the second one "Add a name to user_name" as a key how can i do it
or is there some other way to do this. thanks.

**Comment by jamuhl** [comment]
Not sure but should be: both "Add a name to" and "Add a name to_user_name" ---> context: https://www.i18next.com/translation-function/context

context is always ----> key, key_contextValue

**Comment by sindhuanamal** [comment]
thanks.
