### ISSUE TITLE
Missing key undefined

### ISSUE THREAD

**Issue by sindhuanamal** [i18next/react-i18next#882]
Hi,

i get the error below for the key Name and also on refreshing page it changes the locale to english.
i18next::translator: missingKey undefined translation Name Name

below is the i18n.js file

import i18n from 'i18next';
import Backend from 'i18next-xhr-backend';
import LanguageDetector from 'i18next-browser-languagedetector';
import { initReactI18next } from 'react-i18next';

const fallbackLng = ['en'];
const availableLanguages = ['en', 'sv'];

export const languages = [
    {
        'code': 'en_US',
        'i18next_code': 'en',
    },
    {
        'code': 'fi',
        'i18next_code': 'fi',
    },
    {
        'code': 'sv',
        'i18next_code': 'sv',
    },
];

i18n
    .use(Backend)

    .use(LanguageDetector)

    .use(initReactI18next)

    .init({
        backend: {loadPath: '/public/locales/{{lng}}/{{ns}}.json'},
        lng: 'en',
        fallbackLng,
        debug: true,
        whitelist: availableLanguages,
        nonExplicitWhitelist: true,
        interpolation: {
            escapeValue: false,
        },
    });

export default i18n;

this is how i change the language

export default class LanguageChangingComponent extends React.Component {
    on_select = (event) => {
        const language = i18n.languages.find(language => language.code === event.target.value);
        language && i18next.changeLanguage(language.i18next_code);
    };

Could you provide insights into why this error is thrown. thanks.

**Comment by jamuhl** [comment]
`i18next::translator: missingKey undefined translation Name Name` ---> somewhere you access key Name of namespace translation with no language set -> either access before init, misses the HOC or hook...

**Comment by sindhuanamal** [comment]
okay..i have it defined outside the class component like this,

const values = [
    {label: i18n.t('Name')},
    {label: i18n.t('Description')},
];
class someComponent extends React.PureComponent {
    constructor(props) {
        super(props);
        this.state = {
            name: values[0];
        }
};


So translating keys which are outside class throws undefined error. one way is to define those inside class. rather than changin code accessing that variable is there something with react-i18next to fix it easily?

thanks.

**Comment by jamuhl** [comment]
best is translation while rendering...that way those values will also change eg. on language change,...

if doing outside you will need to set / reset those values by a event handler -> https://www.i18next.com/overview/api#events

**Comment by sindhuanamal** [comment]
okay thanks will have them defined within class. also about other part of question refreshing page changes the language to default...i am using lng: 'en', in i18n.js 

on first time log on will have the translations to english. user changes language to sv. then translations are in swedish..now if refreshes page then the translations are in english. how can i avoid this? i have tried removing lng: 'en'. then on logon it is always swedish...how to fix this. thanks for your time.

**Comment by jamuhl** [comment]
you can use: https://github.com/i18next/i18next-browser-languageDetector to detect / and persist lng

**Comment by sindhuanamal** [comment]
Thanks using 
 order: ['htmlTag'],
 caches: [],

on init worked for me.
