### ISSUE TITLE
withTranslation should hoistStatics for wrapped component

### ISSUE THREAD

**Issue by chunghe** [i18next/react-i18next#884]
**Describe the bug**
withTranslation HOC should hoist static for the wrapped component.
If a component with static property/functions (ex: navigationOptions for screen components), should retain those after wrapped in the withTranslation HOC.

withNamespaces hoist statics:
https://github.com/i18next/react-i18next/blob/11e23a4c482a3449ca1e664eedd745975957e3d6/src/withNamespaces.js

**Occurs in react-i18next version**
10.x.x

**Comment by jamuhl** [comment]
https://react.i18next.com/latest/withtranslation-hoc#hoist-non-react-statics
