### ISSUE TITLE
VSCode error `Cannot find module 'react-i18next'.`

### ISSUE THREAD

**Issue by m0tive** [i18next/react-i18next#885]
**Describe the bug**
When importing `react-i18next`, Visual Studio Code type checking highlights it red with: `Cannot find module 'react-i18next'. ts(2307)` (see screenshot). When built and run the library imports and works as expected. It seems like an issue finding the `index.d.ts`.

**Occurs in react-i18next version**
`"react-i18next": "^10.11.2",`

**To Reproduce**

1. Setup simple js project with `react-i18next`.
2. Add [jsconfig.json](https://code.visualstudio.com/docs/languages/jsconfig) with `"checkJs": true,`
3. Open folder in vscode, add file with `import { Trans, Translation } from 'react-i18next';`

**Screenshots**
![image](https://user-images.githubusercontent.com/235484/60191753-be49c780-982c-11e9-9c41-9fc32511322c.png)

**Comment by rosskevin** [comment]
I'm using vscode and have no problems - multiple projects and multiple developers.  Perhaps this is some quirk with using vscode and jsconfig.json vs tsconfig.json?  I am not sure what you have going on, but we can only ensure that the package.json is correct, and that files are published properly.

Below is a pic that proves it is published correctly (and typechecking in a vscode project):

![vscodeworks](https://user-images.githubusercontent.com/136564/60198974-7b75f880-9808-11e9-9393-3bdfe13f9a4d.gif)

**Comment by m0tive** [comment]
Yep, this seems to be an issue with my `jsconfig.json` setup. I was using `"module": "esNext",` but it seems I also needed `"moduleResolution": "node",`
