### ISSUE TITLE
Why using withtranslation and usetranslation?

### ISSUE THREAD

**Issue by sindhuanamal** [i18next/react-i18next#886]
I was wondering if it's possible to just use i18n.t method throughout the application for translations rather than using withtranslation for hoc and usetranslation for functional components.

Could you please let me know the pros and cons of using only i18n.t instead of withtranslation and usetranslation.

Thanks.

**Comment by jamuhl** [comment]
possible...but no handling for pending loading, language change,...https://react.i18next.com/guides/the-drawbacks-of-other-i18n-solutions
