### ISSUE TITLE
(v9) withNamespaces vs. withI18n...when to use each?

### ISSUE THREAD

**Issue by mshindal** [i18next/react-i18next#887]
Right now I'm using `withNamespaces()` everywhere, and it works great, but is there a performance penalty by doing this? Should I be using `withI18n()` instead?

**Comment by jamuhl** [comment]
all use the same functions behind the scene - so it makes no difference (or no recognizable).

the difference is what you prefer using HOC or render prop

**Comment by mshindal** [comment]
> the difference is what you prefer using HOC or render prop

I think we might be talking about different things, my question is regarding [this](https://react.i18next.com/legacy-v9/withi18n) and [this](https://react.i18next.com/legacy-v9/withnamespaces), both of which are HOCs.

**Comment by jamuhl** [comment]
Sorry for misunderstanding...in execution, both might be close to same results...just `withI18n` does no binding to change events - so no rerendering (uses less mem,...) --- just as a sidenote there is no direct replacement for that in v10....
