### ISSUE TITLE
<5> some text.. </5> obviously not replacing <Link>

### ISSUE THREAD

**Issue by Ashley20** [i18next/react-i18next#888]
`             
   import { withRouter, Link } from "react-router-dom";

    <Trans i18nKey="register.alreadySignedup">
          Already signed up? <Link to="/signin">Login here</Link>{" "}
          instead.
     </Trans>
`
I want to make this  already signed up link with 2 different languages. The problem is the text inside <Link> component stays as text. I want it to appear as link
Here is my translations files

tr
`
{
  "register": {
    "alreadySignedup": "Zaten üye misin? <5>Buradan giriş yap</5>"
  }
}
`

// en
`
{
  "register": {
    "alreadySignedup": "Already signed up? <5>Login here</5> instead."
  }
}
`

**Comment by jamuhl** [comment]
Are you sure `Already signed up? <5>Login here</5> instead.` is correct? my guess it should be `Already signed up? <1>Login here</1> instead.`

**Comment by Ashley20** [comment]
Thank you @jamuhl  I make this assumption from the docs. But changing <5> 's to <1> 's worked for me 


```
<Trans i18nKey="userMessagesUnread" count={count}>
  Hello <strong title={t('nameTitle')}>{{name}}</strong>, you have {{count}} unread message. <Link to="/msgs">Go to messages</Link>.
</Trans>

"userMessagesUnread": "Hello <1>{{name}}</1>, you have {{count}} unread message. <5>Go to message</5>.",
"userMessagesUnread_plural": "Hello <1>{{name}}</1>, you have {{count}} unread messages.  <5>Go to messages</5>."
```

**Comment by jamuhl** [comment]
ah...there the 5 is coming from...the number reflects the index of child node (Trans -> prop.childrens[i])

For getting that numbers right you might read: https://react.i18next.com/latest/trans-component#how-to-get-the-correct-translation-string

**Comment by abranhe** [comment]
I had some issue having two links, I just to have something like this:

```js
<Trans i18nKey="footer.agreement">
	...you agree to the <Link to="/terms">Terms of Service</Link> and <Link to="/privacy">Privacy Policy</Link>.
</Trans>
```

and in my translation, I tried:

```json
{
	"footer": {
		"agreement": "... you agree to the <1>Terms of Service</1> and <1>Privacy Policy</1>
	}
}
```

but although it was generated perfectly, the links (`href/to`) were both '/terms'. I tried many combinations:

- `<1>Terms..<1>...<5>Privacy..</5>`
- `<5>Terms..<5>...<5>Privacy..</5>`
- and many more

but the only one that seems to work for me was:

```
<1>First Link</1> <3>Second Link</3>
```

This is kinda weird, but if you face the same issue hope this helps you.

**Comment by jamuhl** [comment]
Trans node children (comment is the index):

```js
...you agree to the // 0
<Link to="/terms">Terms of Service</Link> // 1
 and // 2
<Link to="/privacy">Privacy Policy</Link> // 3
. // 4
```

so translation has to be `... you agree to the <1>Terms of Service</1> and <3>Privacy Policy</3>`

https://react.i18next.com/latest/trans-component#how-to-get-the-correct-translation-string
