### ISSUE TITLE
how to use the context for multiple keys

### ISSUE THREAD

**Issue by America-first-melon** [i18next/react-i18next#889]
# Question about react-i18next

I saw the use of context on the link.[https://www.i18next.com/translation-function/context](url)

How does this work?

{
      "a": "A",
      "a_b": "A->B",
      "a_b_c_d": "how?"
}

**Comment by jamuhl** [comment]
It's more like:

```js
{
"a": "a default",
"a_female": "a female",
"a_male": "a male"
}

t('a', { context: 'female' }); // a female
```

nesting on the other hand:

```js
{
"a": "a",
"ab": "$t(a) b",
"abc": "${ab} c"
}

t('abc'); // -> a b c
```

**Comment by America-first-melon** [comment]
found another way to handle `a_b_c_d`. 
yeah. it works. 
thanks
