### ISSUE TITLE
SSR － on the client language is changed to the default one

### ISSUE THREAD

**Issue by ElForastero** [i18next/react-i18next#890]
**Describe the bug**
The client is initialized with proper language, but then, it changes immediately to the default language.

Both locales start loading after page load.

![image](https://user-images.githubusercontent.com/5102818/60435867-b4083e80-9c1b-11e9-9ae2-a21f57ac66ab.png)

SSR is working nice, returning `initialI18nStore` and `initialLanguage`.

**Occurs in react-i18next version**
react-i18next: ^10.7.0

**To Reproduce**
-

**Expected behaviour**
-

**Screenshots**
Node Server where we can see languageChange to de.

![image](https://user-images.githubusercontent.com/5102818/60433073-ecf0e500-9c14-11e9-80d7-3760f0f37419.png)

Client code, where it first renders as de and then switches to the en.

![image](https://user-images.githubusercontent.com/5102818/60435740-583db580-9c1b-11e9-88fd-ff60f335a2e7.png)

Initial data is present.

![image](https://user-images.githubusercontent.com/5102818/60435928-e7e36400-9c1b-11e9-84c1-356eea2c9507.png)

And we also use `useSSR` hook on the client side.

![image](https://user-images.githubusercontent.com/5102818/60435986-0d706d80-9c1c-11e9-96fc-895821918893.png)

**OS (please complete the following information):**

- Device: MBP15 2015
- Browser: Chrome 75

**Additional context**

No errors.
No warnings.

We don't have language changing logic in our code base. Only subdomain-based detector.

**Comment by jamuhl** [comment]
looks like useSSR runs to early...before i18next.init

**Comment by ElForastero** [comment]
Yeah, it seems like `vendors-main` chunk is being evaluated later than `main`.
Despite the fact that they have the correct order in HTML.

I've tried to call `i18n.init()` right before `useSSR` hook, but no result.

The only way it works is this one:

![image](https://user-images.githubusercontent.com/5102818/60500151-ddcc6e80-9cca-11e9-86c4-77e966ff6b9b.png)

**Comment by jamuhl** [comment]
Using the HOC or hook would also prevent running that useSSR to early...but not sure you like to wrap your full App into a `withTranslation` or use a `useTranslation`

**Comment by ElForastero** [comment]
I've decided to leave it this way. We have Suspense in dev env, so wrapping an entire application in `withTranslation` will result in one extra parent component with Suspense. 🤔

The issue can be closed.
