### ISSUE TITLE
Is it possible a tag reference another?

### ISSUE THREAD

**Issue by FabianoLothor** [i18next/react-i18next#891]
# Question about react-i18next

`en_sample.json`
```json
{
  "text": {
    "test": "Test",
    "sample": "Sample"
  },
  "label": {
    "test": "text.test",
    "sample": "label.sample"
  }
}
```

Is it possible create something that give me `Test` when I call `t("label.test")`?

Obviously this is a basic sample just for show my problem.

**Comment by jamuhl** [comment]
```js
{
  "text": {
    "test": "Test",
    "sample": "Sample"
  },
  "label": {
    "test": "$t(text.test)",
    "sample": "$t(text.sample)"
  }
}
```

https://www.i18next.com/translation-function/nesting

**Comment by FabianoLothor** [comment]
> ```js
> {
>   "text": {
>     "test": "Test",
>     "sample": "Sample"
>   },
>   "label": {
>     "test": "$t(text.test)",
>     "sample": "$t(text.sample)"
>   }
> }
> ```
> 
> https://www.i18next.com/translation-function/nesting

Nice @jamuhl thank you!
