### ISSUE TITLE
Better way to redirect to known languages

### ISSUE THREAD

**Issue by developdeez** [i18next/react-i18next#893]
Would like a way to choose the chosen language when the browser langauge isn't supported. 
Im in US and browsers have either 'en' or 'en-US' would like to round them up to just look in the 'en' locales folder for translations. Fallback still works but the console gets severla not found errors of the original language lookup. Can I load a list to check before it tries?

**Comment by jamuhl** [comment]
https://www.i18next.com/overview/configuration-options#languages-namespaces-resources -> load, whitelist should do what you need
