### ISSUE TITLE
much namespace not work

### ISSUE THREAD

**Issue by huanglijiao** [i18next/react-i18next#894]
**Describe the bug**

**Occurs in react-i18next version**
npm module version, git tag or even better the explict commit causing the issue

**To Reproduce**

**Expected behaviour**

**Screenshots**
If applicable, add screenshots or a GIF to help explain your problem.

**OS (please complete the following information):**

- Device: [e.g. MBP 2018 13"]
- Browser: [e.g. Chrome 70.0.3538.77]

**Additional context**

**Comment by jamuhl** [comment]
?
