### ISSUE TITLE
How to prevent flickering effect

### ISSUE THREAD

**Issue by sagar-gavhane** [i18next/react-i18next#895]
# Question about react-i18next

Questions should be posted on StackOverflow
https://stackoverflow.com/questions/56946925/how-to-prevent-flickering-effect-in-react-i18next

**Comment by jamuhl** [comment]
wondering...

wait: true -> does not exist in v10 -> use suspense or handle state yourself: https://react.i18next.com/latest/withtranslation-hoc#not-using-suspense
cache -> does not exist in latest i18next -> https://github.com/i18next/i18next-localstorage-backend#getting-started using chained backend is the new way

**Comment by sagar-gavhane** [comment]
Hey Jan, Thanks for your prompt response.

**Comment by developdeez** [comment]
I have the same issue. Would it be wise to preload all namespaces for speed?

**Comment by jamuhl** [comment]
@developdeez no..preload does not change anything...you will still render before all was preloaded...just use the HOC, hook,...and either use Suspense or evaluate ready, tReady....

**Comment by developdeez** [comment]
Sorry I meant like this. It seemed to work for me:
`ns: ["common", "searchprofiles", "landing", "settings", "modals"],`

Is this bad practice?

**Comment by jamuhl** [comment]
no...as long those are not huge...

**Comment by developdeez** [comment]
Combined 27KB :/
But without it, it seems theres a slight delay. Or sometimes only key will show. 

I'm using HOC like so:
export default withTranslation("modals")(PopupModal);

But I will try adding the tready check. Thanks

**Comment by jamuhl** [comment]
https://react.i18next.com/latest/withtranslation-hoc#not-using-suspense --> see the info

**Comment by ChR-iSz** [comment]
I have the same issue on Button text's. What is the best practice to stop the flickering ?

**Comment by jamuhl** [comment]
@ChR-iSz best practice nowadays is using useSuspense (like in most samples) which will show fallback until your translations are loaded async. If you won't/can't use suspense just follow the docs: https://react.i18next.com/latest/usetranslation-hook#not-using-suspense

**Comment by ChR-iSz** [comment]
Hi jan,

Thanks for update. I have try, but still the same issue.

As example i have a html button:

<button data-i18n="Suche"><button>

My problem is now:

After page reload, the button text is for few milliseconds empty (the button size is small with no text value), and then comes the translation with the value and expand by button size. With few html elements it looks very strange after page reloading...

**Comment by jamuhl** [comment]
@ChR-iSz are you using `useTranslation` or `withTranslation`? Are you using Suspense?

Your problem basically does not exist if following the examples. Only way to get there is disabling useSuspense and not following the link I sent you.

**Comment by mathtev** [comment]
I solved flickering issue by preloading all needed namespaces in the root component:

useTranslation(['ns1', 'ns2', 'ns3']);
