### ISSUE TITLE
Dynamically translating unknown string with variables

### ISSUE THREAD

**Issue by psaniko** [i18next/react-i18next#897]
**Describe the bug**
I have error messages with double curly braces placeholders generated in the backend. They get passed to the frontend and should be translated, interpolating the variables. Instead, the variables disappear.

**Occurs in react-i18next version**
10.11.1

**To Reproduce**
```
let errorMessage = 'value is {{ var: 5 }}'
let translatedMessage = <Trans>{errorMessage}</Trans>
```

**Expected behaviour**
The translated message to be "value is 5".

**Comment by jamuhl** [comment]
The code is wrong...must be:

```js
let val = 5;
let translatedMessage = <Trans>value is {{ val }}</Trans>
```

or

```js
// json "errorMessage": "value is {{ var }}"
let translatedMessage = t('errorMessage', { var: 5 });
```

or
```js
let errorMessage = 'value is {{ var }}'
let translatedMessage = <Trans defaults={errorMessage} values={{ var: 5 }} />
```

**Comment by psaniko** [comment]
Sorry, I should have clarified more. The variables are only known in isolation by the backend. The backend generates one string which needs to include the variables in a way so that react-i18next can properly substitute them. Obviously, we'd like to avoid using eval.

**Comment by jamuhl** [comment]
Guess there is no way...building a string that acts as a fixed key and includes some variable in form of string...error -> send a code and the value to client...let the client build a key like: https://www.i18next.com/translation-function/essentials#multiple-fallback-keys and pass the value to it

**Comment by psaniko** [comment]
Thanks @jamuhl. We got it working with this helper function:

```
import React from 'react';

/**
 * Translate static strings coming from the backend
 *
 * @param str: string with placeholders in the format "value is {{val: 5}}"
 * @param t: react-i18next t instance
 * @returns: translated string
 */
export default function staticTranslate(str, t) {
  if (str === undefined) {
      return str;
  }
  let substitutions = {};

  function replacer(match, p1, p2, offset, string) {
    substitutions[p1] = p2;
    return '{{' + p1 + '}}';
  }

  str = str.replace(/\{\{\s?(\w+):\s?([^}]+)\}\}/g, replacer);
  return t(str, substitutions);
}
```
