### ISSUE TITLE
Cannot read property 'react' of undefined

### ISSUE THREAD

**Issue by nevolgograd** [i18next/react-i18next#898]
I'm getting this weird error when trying  get _t_ func. An error occurs when using a HOC and a hook too. I'm using typescript.

An error is in this line of _useTranslation_ function:
`var i18nOptions = _objectSpread({}, getDefaults(), i18n.options.react);`

It tries to get options object from a promise _i18nFromContext_:
`var i18n = i18nFromProps || i18nFromContext || getI18n();`

All works fine if i change the condition sequence to:
`var i18n = i18nFromProps || getI18n() || i18nFromContext;`

Is it a bug, or i screwed up with some ts init? 

**Dependency versions:** 
```
"i18next": "^15.1.3",
"i18next-browser-languagedetector":  "^3.0.1",
"react-i18next": "^10.11.4"
```

**Init function:** 

```
import i18n from 'i18next';
import LanguageDetector from 'i18next-browser-languagedetector';
import { initReactI18next } from 'react-i18next';

import enLocale from 'locale/en.json';
import ruLocale from 'locale/ru.json';

export const i18nInit: any = i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    fallbackLng: 'en',
    debug: false,
    ns: ['translations'],
    detection: {
      order: ["localStorage", "navigator"],
      caches: ["localStorage"]
    },
    defaultNS: 'translations',
    returnObjects: true,
    resources: {
      en: {
        translations: enLocale
      },
      ru: {
        translations: ruLocale
      }
    },
    react: {
      wait: false,
      bindI18n: 'languageChanged loaded',
      bindStore: 'added removed',
      nsMode: 'default'
    }
  });

```

**Comment by jamuhl** [comment]
Are you using the I18nextProvider somewhere? Is this v9 or v10?

**Comment by nevolgograd** [comment]
Yes, of course. 

`"react-i18next": "^10.11.4"`

```
import React from 'react';
import ReactDOM from 'react-dom';
import { I18nextProvider } from 'react-i18next';

import { i18nInit } from 'core/i18n';
import { App } from 'App/components';

const Root: React.FC = () => (
	<I18nextProvider i18n={i18nInit}>
		<App />
	</I18nextProvider>
);

ReactDOM.render(<Root/>, document.getElementById('root'));

```

**Comment by jamuhl** [comment]
Ok...the problem is...that you missed reading the migration guides for both i18next and react-i18next:

https://www.i18next.com/misc/migration-guide#v-12-x-x-to-v-13-0-0

`export const i18nInit: any = i18n` that's a Promise now...not an i18n instance

=> Just "re"-export i18next from your i18n.js

https://react.i18next.com/latest/migrating-v9-to-v10

there is no `wait: true` v10 uses Suspense to handle pending loading

**Comment by nevolgograd** [comment]
What do you mean "re"-export?  

Please look at clean example: https://rwebp.codesandbox.io/

**Comment by jamuhl** [comment]
doing that `export { i18n as i18nInit };`

**Comment by nevolgograd** [comment]
Oh, thank you!
But what's the difference between `export const i18nInit = i18n ...` and working solution? 
I really don't get it.

**Comment by jamuhl** [comment]
export const i18nInit = i18n.init() -> i18n.init does not return "this" like it did before...it now returns a Promise so i18nInit gets set to a Promise....
