### ISSUE TITLE
Count: 0 defaulting to singular form when language is 'pt'

### ISSUE THREAD

**Issue by Ericnr** [i18next/react-i18next#899]
I'm translating my app from english to Portuguese and Spanish and encountered this problem.
[CodeSandbox link](https://codesandbox.io/s/i18next-u8nnq)
"0 item" should actually be plural in Portuguese too.

**Comment by jamuhl** [comment]
looking at http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html#pt it is singular for 0 and 1

and http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html#pt_PT

don't ask me why the rule pt got set on same rule as pt-BR and not to the European pt-PT (but i don't make the rules)

You still can change the rules by passing your own: https://github.com/i18next/i18next/blob/master/src/PluralResolver.js#L90

**Comment by Ericnr** [comment]
Well that's strange, when I look up the grammar on this it says 0 is plural in Portugal, and in Brazil it seems to be plural too, though its often used in singular. Anyway, the plural resolver solves it, thanks!

**Comment by jamuhl** [comment]
I just try to follow the unicode specification - personally I'm not really good at learning languages...so my personal experience is rather limited (de, en, fr)...but yeah...I was very surprised the first time i saw that Brasil rule is different from Portugal (as far as i know this is the only language doing plurals different between regions 🤷‍♂️)
