### ISSUE TITLE
errors using Interpolate

### ISSUE THREAD

**Issue by chrisdrackett** [i18next/react-i18next#9]
I'm trying to use the `Interpolate` component, but I'm running into errors:

```Error: Invariant Violation: findComponentRoot(..., .0.0.0.0.0.1.0): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID ``.```

No idea where to start debugging, I'm using the code as described in the readme.

**Comment by jamuhl** [comment]
did you check the /example? https://github.com/i18next/react-i18next/blob/master/example/app/components/View.js#L13

should work...not sure what is causing your issue...but seems to be related to the interpolated component

**Comment by chrisdrackett** [comment]
ok, don't mind me, I'm using 0.0.4, so I obviously don't have `Interpolate`

**Comment by chrisdrackett** [comment]
@jamuhl any idea when the next release might be?

**Comment by jamuhl** [comment]
@chrisdrackett as soon there are new fixes or features: v0.1.0 is published few days ago including the interpolate component https://www.npmjs.com/package/react-i18next

you still get v0.0.4? might be you got ^0.0.4 in your package.json? so you don't get the minor update to 0.1.0?

**Comment by chrisdrackett** [comment]
I guess I'm used to checking tags (https://github.com/i18next/react-i18next/releases) and not NPM :)

**Comment by jamuhl** [comment]
hm...seems something in my build script gone wrong...should have push a tag.

**Comment by chrisdrackett** [comment]
so I'm updated to 0.1.0 and I'm still having issues with `Interpolate`. I'm not actually getting any errors now, but my output is completely blank. I'm copying the example exactly at this point and I'm not sure how to further debug :)

**Comment by jamuhl** [comment]
your component uses the translated hoc?

**Comment by chrisdrackett** [comment]
it does currently

**Comment by jamuhl** [comment]
so i18nextProvider -> translated -> Interpolate...should really work...

can you check if your component has context.i18n and context.t?

**Comment by chrisdrackett** [comment]
I've never used context, so I'm looking into that. Here is my code:

https://gist.github.com/chrisdrackett/4439cf3f0f6a136f519f

**Comment by chrisdrackett** [comment]
looks like both of those are returning `undefined` at the moment...

**Comment by jamuhl** [comment]
what is `translation.toml`?

**Comment by chrisdrackett** [comment]
we use web pack to parse that file into json, lets us write markdown. It works everywhere we're using `t('bla')`

**Comment by jamuhl** [comment]
k...in your render function, add `console.log(this.props.t('Snippet.instructions_md', {test: 'world'}));`

does that log as expected?

**Comment by chrisdrackett** [comment]
yep, I get an object with the correct HTML

**Comment by jamuhl** [comment]
at the place where it should render the interpolate component....do you find a <noscript> block in the html page?

**Comment by chrisdrackett** [comment]
looks like there is a `<noscript data-reactid=".0.0.1.0.1.0"></noscript>`

**Comment by jamuhl** [comment]
ok https://github.com/i18next/react-i18next/blob/master/lib/interpolate.js#L45 seems format is not defined.

can you go to node_modules and add a console.log(this.t) before that line?...seems like context gets not set

**Comment by chrisdrackett** [comment]
it prints

    [Log] function fixedT(key, options) { (scripts.js, line 40476)
        options = options || {};
        options.lng = options.lng || fixedT.lng;
	options.ns = options.ns || fixedT.ns;
	return _this4.t(key, options);
    }

**Comment by jamuhl** [comment]
what is format?

**Comment by jamuhl** [comment]
plus log `this.i18n.services.resourceStore.data`

**Comment by chrisdrackett** [comment]
ok, as a test I cut out our `.toml` file and things work in this case! Not sure why things work with `t()` and not Interpolate, but I'll keep digging.

**Comment by chrisdrackett** [comment]
FYI

format is `[Log] hello. {{test}} (scripts.js, line 40477)`
`this.i18n.services.resourceStore.data` is a fairly big object

**Comment by jamuhl** [comment]
ok..second is complete resources loaded. but seems all ok....format is defined as needed and {{test}} should get interpolated.

no idea what's the difference on `.toml`

**Comment by chrisdrackett** [comment]
It looks like the problem is that with `_md` we're passing the code through markdown first and `interpolate` is getting HTML. I didn't know that was based on the string and thought we were passing everything through markdown. Sorry about that!

**Comment by jamuhl** [comment]
ok i see...if you need some changes...PR would be accepted. But not postProcessing markdown in this case might be good enough.
