### ISSUE TITLE
Using withTranslation HOC with styleguidist

### ISSUE THREAD

**Issue by SirSketch** [i18next/react-i18next#900]
Is it possible to get better documentation using styleguidist?

So far we have something like this:

```jsx
class Foo extends React.Component<IFoo> {}

/**
 * @component
 */
export default withTranslation()(Foo);
```
Which works, but it does not find props as it does with components being exported directly.

Does anyone have an idea on how to document hoc wrapped components correctly?

**Comment by jamuhl** [comment]
🤷‍♂️no idea...never used that
