### ISSUE TITLE
react-i18next repeated rendering on server and client

### ISSUE THREAD

**Issue by huanglijiao** [i18next/react-i18next#904]
I used react-i18next + nextjs in my project.
I found it re-rendered on the client.

I used react-i18next v10.11.3.

i18nOption.js:
```
const moment = require('moment');
module.exports = {
  // 在当前语言目录下找不到对应词条的时候， 强制使用某一个语言下的翻译
  fallbackLng: false,
  // fallbackNS: 'common',
  // load的值有： all, languageOnly(en), currentOnly
  load: 'currentOnly',
  defaultNS: 'common',
  // debug模式下 多语言相关的日志信息会打印到控制台
  debug: true,
  interpolation: {
    escapeValue: false,
    formatSeparator: ',',
    format: (value, format, lng) => {
      // 可以对特定语言做处理
      console.log(lng);
      // 小写转大写
      if (format === 'uppercase') {
        return value.toUpperCase();
      }
      // 按一定的时间格式
      if (value instanceof Date) {
        return moment(value).format(format);
      }

      return value;
    },
  },
  react: {
    suppuse: false,
  },
};

```
withI18n.js, wrap _app.js:
```
import React from 'react';
import i18n from 'i18next';
import XHR from 'i18next-xhr-backend';
import intervalPlural from 'i18next-intervalplural-postprocessor';
import getLangDirByLang from '@utils/common/index';
import i18nOptions from '@constants/i18nOption';

export default App =>
  class AppWithI18n extends React.Component {
    static displayName = 'AppWithI18n(App)';

    static async getInitialProps(appContext) {
      let appProps = {};
      if (typeof App.getInitialProps === 'function') {
        appProps = await App.getInitialProps(appContext);
      }

      const { query } = appContext.ctx;

      return { query, ...appProps };
    }

    constructor(props) {
      super(props);

      // eslint-disable-next-line react/prop-types
      const { pageProps, query } = props;
      // server端的i18n实例
      // eslint-disable-next-line react/prop-types
      this.i18n = pageProps.i18n;

      if (this.i18n === null) {
        // eslint-disable-next-line react/prop-types
        const { lang } = query;
        const lng = getLangDirByLang(lang);
        // client端的初始化i18n实例
        i18n
          .use(XHR)
          .use(intervalPlural)
          .init({
            ...i18nOptions,
            lng,
            // eslint-disable-next-line react/prop-types
            ns: pageProps.nameSpace,
            backend: {
              loadPath: `http://localhost:3000/static/locales/{{lng}}/{{ns}}.json`,
            },
          });

        this.i18n = i18n;
      }
    }

    render() {
      return <App {...this.props} i18n={this.i18n} />;
    }
  };

```
withNamespaces.js, wrap some components:
```
import { withTranslation } from 'react-i18next';
import getLangDirByLang from '@utils/common/index';
import options from '@constants/i18nOption';
import i18n from 'i18next';

/**
 * @description 根据server端根据req.lang， 改变i18n实例的语言， 并导出实例和初始化数据
 * @method prepareForSSR
 * @param {object} ctx 上下文对象
 * @param {array} namespaces 动态按需的NS
 * @return {object} 返回i18n实例和初始化数据
 */
function prepareForSSR(ctx, namespaces) {
  const { req, query } = ctx;

  const defaultLangaugeName = getLangDirByLang(query.lang);
  req.i18n.changeLanguage(defaultLangaugeName);

  req.i18n.toJSON = () => null; // 参考 https://github.com/i18next/react-i18next/issues/274

  // 参考 https://github.com/i18next/react-i18next/commit/c9906bcb1465d382afc3a1291f888be5cc5bbd7c
  // 页面刷新两次问题， 参考 https://github.com/i18next/react-i18next/issues/626
  const initialI18nStore = {};
  req.i18n.languages.forEach(l => {
    initialI18nStore[l] = {};
    namespaces.forEach(ns => {
      initialI18nStore[l][ns] =
        (req.i18n.services.resourceStore.data[l] || {})[ns] || {};
    });
  });

  return {
    i18n: req.i18n,
    initialI18nStore,
    initialLanguage: req.i18n.language,
  };
}

const withNamespace = (namespaces = options.defaultNS) => ComposedComponent => {
  // 按需加载NS
  const Extended = withTranslation(namespaces, { wait: true })(
    ComposedComponent,
  );

  Extended.getInitialProps = async ctx => {
    const composedInitialProps = ComposedComponent.getInitialProps
      ? await ComposedComponent.getInitialProps(ctx)
      : {};

    const i18nInitialProps = ctx.req ? prepareForSSR(ctx, namespaces) : {};

    return {
      ...composedInitialProps,
      ...i18nInitialProps,
    };
  };

  return Extended;
};

export default withNamespace;

```

if I remove XHR on the client, it only rendered on the server, but some error 

react-i18next:: You will need pass in an i18next instance by using initReactI18next
warn @ utils.js:11
warnOnce @ utils.js:22
useTranslation @ useTranslation.js:19
withI18nextTranslation(Demo) @ withTranslation.js:10
renderWithHooks @ react-dom.development.js:12938
mountIndeterminateComponent @ react-dom.development.js:15020
beginWork @ react-dom.development.js:15625
performUnitOfWork @ react-dom.development.js:19312
workLoop @ react-dom.development.js:19352
renderRoot @ react-dom.development.js:19435
performWorkOnRoot @ react-dom.development.js:20342
performWork @ react-dom.development.js:20254
performSyncWork @ react-dom.development.js:20228
requestWork @ react-dom.development.js:20097
scheduleWork @ react-dom.development.js:19911
scheduleRootUpdate @ react-dom.development.js:20572
updateContainerAtExpirationTime @ react-dom.development.js:20600
updateContainer @ react-dom.development.js:20657
ReactRoot.render @ react-dom.development.js:20953
(anonymous) @ react-dom.development.js:21090
unbatchedUpdates @ react-dom.development.js:20459
legacyRenderSubtreeIntoContainer @ react-dom.development.js:21086
hydrate @ react-dom.development.js:21148
renderReactElement @ index.js:382
_temp11 @ index.js:49
doRender @ index.js:110
(anonymous) @ index.js:168
_catch @ index.js:13
_temp6 @ index.js:167
render @ index.js:186
(anonymous) @ index.js:336
Promise.then (async)
_temp2 @ index.js:311
Promise.then (async)
(anonymous) @ index.js:368
Promise.then (async)
push.../node_modules/next/dist/client/index.js.exports.default @ index.js:307
../node_modules/next/dist/client/next-dev.js @ next-dev.js:50
__webpack_require__ @ bootstrap:788
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js?ts=1563768833189:1
index.js:1 Warning: Text content did not match. Server: "当前时间是 07/22/2019" Client: "当前时间"
console.<computed> @ index.js:1
warningWithoutStack @ react-dom.development.js:506
warnForTextDifference @ react-dom.development.js:7467
diffHydratedProperties @ react-dom.development.js:8126
hydrateInstance @ react-dom.development.js:9004
prepareToHydrateHostInstance @ react-dom.development.js:14266
completeWork @ react-dom.development.js:16894
completeUnitOfWork @ react-dom.development.js:19142
performUnitOfWork @ react-dom.development.js:19340
workLoop @ react-dom.development.js:19352
renderRoot @ react-dom.development.js:19435
performWorkOnRoot @ react-dom.development.js:20342
performWork @ react-dom.development.js:20254
performSyncWork @ react-dom.development.js:20228
requestWork @ react-dom.development.js:20097
scheduleWork @ react-dom.development.js:19911
scheduleRootUpdate @ react-dom.development.js:20572
updateContainerAtExpirationTime @ react-dom.development.js:20600
updateContainer @ react-dom.development.js:20657
ReactRoot.render @ react-dom.development.js:20953
(anonymous) @ react-dom.development.js:21090
unbatchedUpdates @ react-dom.development.js:20459
legacyRenderSubtreeIntoContainer @ react-dom.development.js:21086
hydrate @ react-dom.development.js:21148
renderReactElement @ index.js:382
_temp11 @ index.js:49
doRender @ index.js:110
(anonymous) @ index.js:168
_catch @ index.js:13
_temp6 @ index.js:167
render @ index.js:186
(anonymous) @ index.js:336
Promise.then (async)
_temp2 @ index.js:311
Promise.then (async)
(anonymous) @ index.js:368
Promise.then (async)
push.../node_modules/next/dist/client/index.js.exports.default @ index.js:307
../node_modules/next/dist/client/next-dev.js @ next-dev.js:50
__webpack_require__ @ bootstrap:788
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js?ts=1563768833189:1
Show 2 more frames
utils.js:11 react-i18next:: You will need pass in an i18next instance by using i18nextReactModule
warn @ utils.js:11
warnOnce @ utils.js:22
Trans @ Trans.js:202
renderWithHooks @ react-dom.development.js:12938
mountIndeterminateComponent @ react-dom.development.js:15020
beginWork @ react-dom.development.js:15625
performUnitOfWork @ react-dom.development.js:19312
workLoop @ react-dom.development.js:19352
renderRoot @ react-dom.development.js:19435
performWorkOnRoot @ react-dom.development.js:20342
performWork @ react-dom.development.js:20254
performSyncWork @ react-dom.development.js:20228
requestWork @ react-dom.development.js:20097
scheduleWork @ react-dom.development.js:19911
scheduleRootUpdate @ react-dom.development.js:20572
updateContainerAtExpirationTime @ react-dom.development.js:20600
updateContainer @ react-dom.development.js:20657
ReactRoot.render @ react-dom.development.js:20953
(anonymous) @ react-dom.development.js:21090
unbatchedUpdates @ react-dom.development.js:20459
legacyRenderSubtreeIntoContainer @ react-dom.development.js:21086
hydrate @ react-dom.development.js:21148
renderReactElement @ index.js:382
_temp11 @ index.js:49
doRender @ index.js:110
(anonymous) @ index.js:168
_catch @ index.js:13
_temp6 @ index.js:167
render @ index.js:186
(anonymous) @ index.js:336
Promise.then (async)
_temp2 @ index.js:311
Promise.then (async)
(anonymous) @ index.js:368
Promise.then (async)
push.../node_modules/next/dist/client/index.js.exports.default @ index.js:307
../node_modules/next/dist/client/next-dev.js @ next-dev.js:50
__webpack_require__ @ bootstrap:788
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js?ts=1563768833189:1
index.js:1 Fetch API cannot load webpack://%5Bname%5D_%5Bchunkhash%5D/../node_modules/react-dom/cjs/react-dom.development.js?. URL scheme must be "http" or "https" for CORS request.
(anonymous) @ index.js:1
A @ index.js:1
(anonymous) @ index.js:1
e.<computed> @ index.js:1
S @ index.js:1
i @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
A @ index.js:1
(anonymous) @ index.js:1
e.<computed> @ index.js:1
S @ index.js:1
i @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
q @ index.js:1
I @ index.js:1
G @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
replayUnitOfWork @ react-dom.development.js:18578
renderRoot @ react-dom.development.js:19468
performWorkOnRoot @ react-dom.development.js:20342
performWork @ react-dom.development.js:20254
performSyncWork @ react-dom.development.js:20228
requestWork @ react-dom.development.js:20097
scheduleWork @ react-dom.development.js:19911
scheduleRootUpdate @ react-dom.development.js:20572
updateContainerAtExpirationTime @ react-dom.development.js:20600
updateContainer @ react-dom.development.js:20657
ReactRoot.render @ react-dom.development.js:20953
(anonymous) @ react-dom.development.js:21090
unbatchedUpdates @ react-dom.development.js:20459
legacyRenderSubtreeIntoContainer @ react-dom.development.js:21086
hydrate @ react-dom.development.js:21148
renderReactElement @ index.js:382
_temp11 @ index.js:49
doRender @ index.js:110
(anonymous) @ index.js:168
_catch @ index.js:13
_temp6 @ index.js:167
render @ index.js:186
(anonymous) @ index.js:336
error (async)
u @ index.js:1
K @ index.js:1
ce @ index.js:1
connect @ hot-dev-client.js:179
push.../node_modules/next/dist/client/webpack-hot-middleware-client.js.exports.default @ webpack-hot-middleware-client.js:24
../node_modules/next/dist/client/next-dev.js @ next-dev.js:45
__webpack_require__ @ bootstrap:788
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js?ts=1563768833189:1
Show 18 more frames
react-dom.development.js:9088 Uncaught TypeError: Cannot read property 'suppressHydrationWarning' of null
    at didNotFindHydratableInstance (react-dom.development.js:9088)
    at insertNonHydratedInstance (react-dom.development.js:14166)
    at tryToClaimNextHydratableInstance (react-dom.development.js:14245)
    at updateHostComponent (react-dom.development.js:14832)
    at beginWork (react-dom.development.js:15649)
    at performUnitOfWork (react-dom.development.js:19312)
    at workLoop (react-dom.development.js:19352)
    at HTMLUnknownElement.callCallback (react-dom.development.js:149)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:199)
    at invokeGuardedCallback (react-dom.development.js:256)
    at replayUnitOfWork (react-dom.development.js:18578)
    at renderRoot (react-dom.development.js:19468)
    at performWorkOnRoot (react-dom.development.js:20342)
    at performWork (react-dom.development.js:20254)
    at performSyncWork (react-dom.development.js:20228)
    at requestWork (react-dom.development.js:20097)
    at scheduleWork (react-dom.development.js:19911)
    at scheduleRootUpdate (react-dom.development.js:20572)
    at updateContainerAtExpirationTime (react-dom.development.js:20600)
    at updateContainer (react-dom.development.js:20657)
    at ReactRoot.render (react-dom.development.js:20953)
    at eval (react-dom.development.js:21090)
    at unbatchedUpdates (react-dom.development.js:20459)
    at legacyRenderSubtreeIntoContainer (react-dom.development.js:21086)
    at Object.hydrate (react-dom.development.js:21148)
    at renderReactElement (index.js:382)
    at _temp11 (index.js:49)
    at doRender (index.js:110)
    at index.js:168
    at _catch (index.js:13)
    at _temp6 (index.js:167)
    at render (index.js:186)
    at index.js:336
didNotFindHydratableInstance @ react-dom.development.js:9088
insertNonHydratedInstance @ react-dom.development.js:14166
tryToClaimNextHydratableInstance @ react-dom.development.js:14245
updateHostComponent @ react-dom.development.js:14832
beginWork @ react-dom.development.js:15649
performUnitOfWork @ react-dom.development.js:19312
workLoop @ react-dom.development.js:19352
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
replayUnitOfWork @ react-dom.development.js:18578
renderRoot @ react-dom.development.js:19468
performWorkOnRoot @ react-dom.development.js:20342
performWork @ react-dom.development.js:20254
performSyncWork @ react-dom.development.js:20228
requestWork @ react-dom.development.js:20097
scheduleWork @ react-dom.development.js:19911
scheduleRootUpdate @ react-dom.development.js:20572
updateContainerAtExpirationTime @ react-dom.development.js:20600
updateContainer @ react-dom.development.js:20657
ReactRoot.render @ react-dom.development.js:20953
(anonymous) @ react-dom.development.js:21090
unbatchedUpdates @ react-dom.development.js:20459
legacyRenderSubtreeIntoContainer @ react-dom.development.js:21086
hydrate @ react-dom.development.js:21148
renderReactElement @ index.js:382
_temp11 @ index.js:49
doRender @ index.js:110
(anonymous) @ index.js:168
_catch @ index.js:13
_temp6 @ index.js:167
render @ index.js:186
(anonymous) @ index.js:336
Promise.then (async)
_temp2 @ index.js:311
Promise.then (async)
(anonymous) @ index.js:368
Promise.then (async)
push.../node_modules/next/dist/client/index.js.exports.default @ index.js:307
../node_modules/next/dist/client/next-dev.js @ next-dev.js:50
__webpack_require__ @ bootstrap:788
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js?ts=1563768833189:1
Show 3 more frames
index.js:1 The above error occurred in the <strong> component:
    in strong (created by Demo)
    in Trans (created by Demo)
    in p (created by Demo)
    in div (created by Demo)
    in Demo (created by withI18nextTranslation(Demo))
    in withI18nextTranslation(Demo) (created by MyApp)
    in I18nextProvider (created by MyApp)
    in Container (created by MyApp)
    in MyApp (created by AppWithI18n(App))
    in AppWithI18n(App)
    in Suspense

React will try to recreate this component tree from scratch using the error boundary you provided, MyApp.
console.<computed> @ index.js:1
logCapturedError @ react-dom.development.js:17117
logError @ react-dom.development.js:17153
callback @ react-dom.development.js:18094
callCallback @ react-dom.development.js:16433
commitUpdateEffects @ react-dom.development.js:16472
commitUpdateQueue @ react-dom.development.js:16463
commitLifeCycles @ react-dom.development.js:17364
commitAllLifeCycles @ react-dom.development.js:18736
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
commitRoot @ react-dom.development.js:18948
(anonymous) @ react-dom.development.js:20418
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:20417
performWorkOnRoot @ react-dom.development.js:20346
performWork @ react-dom.development.js:20254
performSyncWork @ react-dom.development.js:20228
requestWork @ react-dom.development.js:20097
scheduleWork @ react-dom.development.js:19911
scheduleRootUpdate @ react-dom.development.js:20572
updateContainerAtExpirationTime @ react-dom.development.js:20600
updateContainer @ react-dom.development.js:20657
ReactRoot.render @ react-dom.development.js:20953
(anonymous) @ react-dom.development.js:21090
unbatchedUpdates @ react-dom.development.js:20459
legacyRenderSubtreeIntoContainer @ react-dom.development.js:21086
hydrate @ react-dom.development.js:21148
renderReactElement @ index.js:382
_temp11 @ index.js:49
doRender @ index.js:110
(anonymous) @ index.js:168
_catch @ index.js:13
_temp6 @ index.js:167
render @ index.js:186
(anonymous) @ index.js:336
Promise.then (async)
_temp2 @ index.js:311
Promise.then (async)
(anonymous) @ index.js:368
Promise.then (async)
push.../node_modules/next/dist/client/index.js.exports.default @ index.js:307
../node_modules/next/dist/client/next-dev.js @ next-dev.js:50
__webpack_require__ @ bootstrap:788
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js?ts=1563768833189:1
Show 7 more frames

**Comment by jamuhl** [comment]
Something is wrong on your code...what should I say...I won't debug your app and I won't read through endless pasted code...

This is not a reproducible issue with react-i18next - using https://github.com/isaachinman/next-i18next/issues/294#issuecomment-490139480 might avoid such issues in first place...
