### ISSUE TITLE
can you offer a demo of nextjs + react-i18next(v10+)

### ISSUE THREAD

**Issue by huanglijiao** [i18next/react-i18next#905]
according to https://github.com/i18next/react-i18next/tree/master/example/nextjs
react-i18next < v10,  it works well.
But v10 differs greatly from v9.. 
So can you offer a demo of nextjs + react-i18next(v10+)

I really don't want to use next-i18next....

**Comment by jamuhl** [comment]
next-i18next is made for the case next.js + i18next and works with v10

If you do not like using next-i18next it's up to you to adapt your code to v10...

**Comment by danlutz** [comment]
Would also like to see how to implement this without next-i18next!

**Comment by adrai** [comment]
...interesting... are there any reasons not to use next-i18next? Seems pretty cool imo.

btw: feel free to create an example... perhaps @isaachinman can help to review it? 🤷‍♂️

**Comment by jamuhl** [comment]
@danlutz next-i18next is nothing than glue together what is needed to get react-i18next or i18next in general to work -> so read through that code than implement that same thing yourself...😁it's like asking how can i build a react app without using react -> build preact
