### ISSUE TITLE
react-i18next v10 not work well

### ISSUE THREAD

**Issue by huanglijiao** [i18next/react-i18next#906]
the project: https://codesandbox.io/s/9o68r5o8mp
it works well. 
"next": "latest",
"react": "^16.5.2",
"react-dom": "^16.5.2",
"react-i18next": "8.0.6"

then I update react and react-dom to v16.8.6, it also works well.

finally, I  update react-i18next to v10.11.4 and according to https://react.i18next.com/latest/migrating-v9-to-v10, I change withNamespaces to withTranslation, NamespacesConsumer to Translation. the page rerendered on the client.

warning: Warning: Text content did not match. Server: "integrates react-i18next for simple internationalization." Client: "Loading..."
I found it load common.json on the client, but using react-i18next <v10, it can't load common.json on the client.

So  it's the problem of react-i18next to v10. 

So, it's not wrong in my code . https://github.com/i18next/react-i18next/issues/904

**Comment by jamuhl** [comment]
https://github.com/i18next/react-i18next#requirements --> react 16.8.x

v10 is completely different to v9 ---> not just a change of component names...
