### ISSUE TITLE
Trans component does not translate with React Native

### ISSUE THREAD

**Issue by brandtnewww** [i18next/react-i18next#907]
**Describe the bug**
I just upgraded to the lastest version and now translations via the Trans component don't work. However, using a translation via t works perfect.

**Occurs in react-i18next version**
"i18next": "^17.0.6",
"react": "16.8.6",
"react-i18next": "^10.11.4",
"react-native": "0.60.4",

**To Reproduce**
Use a <Trans i18nKey="key">Text</Trans> for translation.

Here's my example (separate ViewName.tsx)
`
<View style={styles.footnoteContainer}>
   <Paragraph light type={'p2'}>
      <Trans i18nKey="legalNote">
         By subscribing, you agree to our
         <Paragraph light onPress={onOpenTermsOfService} type={'p2'} underlined>
            Terms of Use
         </Paragraph>
          , and certify that you have read and understood our
          <Paragraph light onPress={onOpenPrivacyPolicy} type={'p2'} underlined>
             Data Policy
          </Paragraph>
          .
       </Trans>
    </Paragraph>
</View>
`

And here I use withTranslation (separate index.tsx file):

```
const enhance = compose(
  connect(
    mapStateToProps,
    actionCreators
  ),
  withTranslation('viewName')
)

export { ViewName }
export default enhance(ViewNameWithLogic)
```

In my corresponding translation file, I've set the key value pair like this:

` "legalNote": "By subscribing, you agree to our <1>Terms of Use</1>, and certify that you have read and understood our <3>Data Policy</3>.",`

It worked prior to upgrading to the new version. Maybe something's wrong with the withTranslate HOC? Using t function everything works fine. Also, everything else is correctly translated into different languages. Not the Trans component though which doesn't get translated at all.

**Expected behavior**
I except the Trans component to translate the text.

**OS (please complete the following information):**
- Device: iPhone 6, X and XS (Simulator) - iOS 12.2

**Additional context**
The behavior occurred after upgrading to react-native 0.60.4 and react-i18next 10.11.4. It seems like the i18nKey of the Trans component doesn't lead to the right file.

**Comment by adrai** [comment]
Which react version are you using?

**Comment by adrai** [comment]
https://github.com/i18next/react-i18next/issues/906#issuecomment-514123092

**Comment by jamuhl** [comment]
Trans Component not working is not very specific...I'm 100% it works...just namespaces do not get set automatically in v10 based on the HOC - that magic is gone...

**Comment by brandtnewww** [comment]
> Which react version are you using?
"react": "16.8.6" - updated my issue. Seems to fulfill the requirements.

**Comment by brandtnewww** [comment]
> Trans Component not working is not very specific...I'm 100% it works...just namespaces do not get set automatically in v10 based on the HOC - that magic is gone...

How can I make it more specific? Which information do you need? I'm using the t function and the <Trans /> component in the same file. Translation via t function works perfectly while translation via <Trans /> component does not. I only changed withNamespaces to withTranslation. It worked and still does work on the master branch.

**Comment by jamuhl** [comment]
hm....https://github.com/i18next/react-i18next#requirements

beside that your react version is to low - try `<Trans t={t} ...`
