### ISSUE TITLE
Parent react components stay unchanged when using I18n.changeLanguage(lng)

### ISSUE THREAD

**Issue by ValeryVS** [i18next/react-i18next#908]
**Describe the bug**
It in some way similar to #611
May be a bug, but may be i'm doing something wrong.

**Occurs in react-i18next version**
10.11.4

**To Reproduce**
I create language switcher component. Use it in root component.
In all other components I use `Trans` and `useTranslation`.
After language switch only swticher component is updated.
But, if I use `changeLanguage` directly in root component, app will be rerendered as expected.
Should I use `I18nextProvider` or something?
```
import React, {useCallback} from 'react';
import {useTranslation} from 'react-i18next';

const LanguageSwitcher = ({className}) => {
  const {i18n} = useTranslation();

  const setEnglish = useCallback(() => {
    i18n.changeLanguage('en');
  }, [i18n]);

  const setRussian = useCallback(() => {
    i18n.changeLanguage('ru');
  }, [i18n]);

  return (
    <div className={className}>
      <button
        onClick={setEnglish}
      >
        English
      </button>
      <button
        onClick={setRussian}
      >
        Русский
      </button>
    </div>
  );
};

export default LanguageSwitcher;
```

**Expected behaviour**
All components, that use `useTranslation` should recive new `t` and/or `i18n` and rerender when language switched.

**OS (please complete the following information):**

- Device: Ubuntu 18.04
- Browser: Yandex.Browser 19.4.2.698 beta (64-bit)

**Comment by ValeryVS** [comment]
Can't reproduce on codesandbox though.
Probably something isn't right with my app's code.

**Comment by ValeryVS** [comment]
Oh, I see.
I have a parent component, that doesn't use any translation.
```
<Parent>
  <LanguageSwitcher />
  <Child />
</Parent>
```
If only `Child` and `LanguageSwitcher` use `useTranslation`, than `Parent` and `Child` is not updating.
But if `Parent` use `useTranslation`, all will be ok.

Still strange. Try to reproduce on simple app.

**Comment by jamuhl** [comment]
Please ping me if there is a reproducible issue...

**Comment by ValeryVS** [comment]
@jamuhl 
made an example
https://github.com/ValeryVS/react-i18next-example
There is App, Wrapper, LanguageSwitcher and Content.
```tsx
<App>
  <Wrapper>
    <LanguageSwitcher />
    <Content />
  </Wrapper>
</App>
```
Translations loaded dynamicaly, Suspension is set on App.
If Wrapper doesn't import `useTranslation` then language is not switched.
https://github.com/ValeryVS/react-i18next-example/blob/master/src/Wrapper.tsx

**Comment by jamuhl** [comment]
The `Trans` component does not get a magical rerender on languageChange -> only hook, HOC get that, so correct would be passing `t` to the Trans component (Trans component does only enable translation of JSX nodes - nothing more):

```js
import React from 'react';
import { Trans, useTranslation } from 'react-i18next';

const Content: React.FC = () => {
  const {t} = useTranslation();
  return (
    <div>
      <Trans
        t={t}
        i18nKey={`content`}
        defaults='My content'
      />
    </div>
  );
};

export default Content;
```

**Comment by jamuhl** [comment]
basically: Any Page, Component that uses `t` under the hood should either get that injected using hook or HOC or pass t down from the container component

**Comment by ValeryVS** [comment]
@jakutis 
Thanks, it works.
But may be `Trans` components should get own `t` by itself?

Is there any downsides if I just wrap it like this?
https://github.com/ValeryVS/react-i18next-example/commit/30988df966a1f4d979dbb6df4a81171eb13936da

**Comment by jamuhl** [comment]
downside -> when using multiple namespaces `t` can be bound to a namespace

it gets a `t` function -> it just does not get any update on languageChanged...that's "all" (beside having a t function bound to global configured defaultNamespace)
