### ISSUE TITLE
Can we make the default function translate instead of t?

### ISSUE THREAD

**Issue by danielmockaitis** [i18next/react-i18next#910]
I doubt I am the first to request this,

For projects I have seen use this library, the teams end up renaming the function `t` to `translate`, so I was wondering if we could make the default translate?

**Comment by adrai** [comment]
what would be the benefit? Just an alias?
btw: most other i18n frameworks just have a t function: i18n-js, polyglot, lingui, etc...

**Comment by danielmockaitis** [comment]
Yeah an alias. To prevent a breaking change also just adding translate and keeping t to do the same thing would be best.

Most linters do not accept one letter function names and it's clearer to have translate.

**Comment by danielmockaitis** [comment]
#911

**Comment by adrai** [comment]
There are a lot more t that would need to be alised... also in i18next directly...
Personally I don’t think such an alias is necessary, but let’s see what @jamuhl thinks of...

**Comment by jamuhl** [comment]
PR was closed because of the above reason...`t` is widely used. I don't know a linter complaining about it...and easy to create a own component wrapping useTranslation
