### ISSUE TITLE
Property 'initializedLanguageOnce' does not exist on type 'i18n'

### ISSUE THREAD

**Issue by isaachinman** [i18next/react-i18next#913]
Consumers of the i18next ecosystem which export packages to end consumers may, in some cases, need to be aware of internals like `initializedLanguageOnce`.

Currently, it looks like `initializedLanguageOnce` is not declared on the publicly available types.

Would be great to get this added, if @jamuhl thinks it makes sense. Happy to get a PR in if it will be approved.

**Edit:** wasn't sure if this issue belonged in this repo or the main i18next repo. Do let me know.

**Comment by jamuhl** [comment]
For typescript (as I have no plan) - please provide a PR and ping @rosskevin for a review...

**Comment by isaachinman** [comment]
https://github.com/i18next/i18next/pull/1298
