### ISSUE TITLE
Typescript.  react-i18next v10.11.5 breaks compatibility with i18next v16.0.0

### ISSUE THREAD

**Issue by susam-projects** [i18next/react-i18next#914]
**Describe the bug**
Typescript.  react-i18next v10.11.5 breaks compatibility with i18next v16.0.0
Typescript doesn't see the "t" property in this.props of a react class component

**Occurs in react-i18next version**
10.11.5

**To Reproduce**

0. Given a react project with typescript
1. install i18next@16.0.0
2. install react-i18next@10.11.5
3. create react component with WithTranslation interface:
    ```
    // file TestComponent.tsx
    import * as React from "react";
    import { withTranslation, WithTranslation } from "react-i18next";

    class TestComponent extends React.Component<WithTranslation> {
        render() {
            return <div>{this.props.t("")}</div>;
        }
    }
    export default withTranslation()(TestComponent);
    ```
4. try to compile the file with typescript
5. See error "Error:(6, 33) TS2339: Property 't' does not exist on type 'Readonly<WithTranslation> & Readonly<{ children?: ReactNode; }>'."

**Expected behaviour**
The file is compiled without any error.

**OS (please complete the following information):**
Tested on Windows 10
typescript@3.5.3
react@16.8.6
@types/react@16.8.24

**Additional context**
If the latest i18next (17.0.9) is installed, the file is compiled correctly.
I suggest to fix the compatibility or update major version of the project and requirements in readme.

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next/issues/1294

**Comment by susam-projects** [comment]
You're rigth. The bug is responsibility of i18next. On the other hand, requirements of this project is nevertheless no longer "i18next >= 10.0.0" for typescript users.

**Comment by jamuhl** [comment]
https://github.com/i18next/react-i18next/blob/master/README.md#requirements

**Comment by jamuhl** [comment]
hope that helps...
