### ISSUE TITLE
AMD not working in IE11

### ISSUE THREAD

**Issue by roti** [i18next/react-i18next#915]
**Describe the bug**
The AMD dist does not work in IE11 due to usage of the class syntax for `ReportNamespaces`.

**Occurs in react-i18next version**
10.11.5

**To Reproduce**
Load react-i18next in IE11.

**Expected behaviour**
IE11 should be supported.

**OS (please complete the following information):**
- OS: Windows 10
- Browser: IE 11.3024.14393.0

**Additional context**
AMD and UMD modules are build using `rollup.config.js`, where `@babel/preset-env` is configured with `targets.esmodules = true`. CommonJS seems to be fine, but I could not test it.

I'm not familiar with the effects of this setting, but apparently this causes babel not to target ES2015. Removing `targets.esmodules` had the expected effect for me, but I'm not 100% sure whether that's the correct solution. Here's my config from `rollup.config.js`.
```
const babelOptions = {
  presets: [
    '@babel/preset-env',
    '@babel/react',
  ],
  babelrc: false,
};
```

**Comment by jamuhl** [comment]
hm...will have to look into this when I got more time - honestly not too familiar with that myself...

**Comment by StevenDevooght** [comment]
Hi, we also ran into this issue.

**Comment by jamuhl** [comment]
My guess preset-env per default picks browsers not older than 2 versions -> not sure about IE11 (but I would consider IE11 a dead horse => outdated browser)

**Comment by roti** [comment]
Well, it's the default browser on Windows 10. :)

mie., 30 oct. 2019, 11:35 Jan Mühlemann <notifications@github.com> a scris:

**Comment by lekoaf** [comment]
> Well, it's the default browser on Windows 10. :)

That's debatable. I'd argue that Edge is the default browser on Windows 10.

https://en.wikipedia.org/wiki/Microsoft_Edge#Features
> Microsoft Edge is the default web browser on Windows 10, Windows 10 Mobile, and Xbox One consoles, replacing Internet Explorer 11 and Internet Explorer Mobile.

**Comment by roti** [comment]
Hmm. I have Windows 10 Version 1809 (OS Build 17763.805) and it came with IE 11.805.1773.0.

**Comment by lekoaf** [comment]
> Hmm. I have Windows 10 Version 1809 (OS Build 17763.805) and it came with IE 11.805.1773.0.

Unfortunately Windows 10 comes with both IE 11 and Edge. However Edge is the default and recommended browser.

**Comment by jamuhl** [comment]
https://github.com/i18next/react-i18next/pull/988

published in react-i18next@11.1.0

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.
If you liked my support / work - I would enjoy a coffee sponsored using the “:purple_heart:Sponsor Button”.
There are many ways to help this project :pray:

**Comment by roti** [comment]
Thanks.
