### ISSUE TITLE
macro error: Can't resolve 'react/i18next'

### ISSUE THREAD

**Issue by baldurh** [i18next/react-i18next#916]
**Describe the bug**
When using the macro I get this error.
Seems there is a typo in the macro code at https://github.com/i18next/react-i18next/blob/master/icu.macro.js#L327
Shouldn’t this line be `t.stringLiteral('react-i18next'),`?

**Occurs in react-i18next version**
10.11.5
Node v8.12.0

**To Reproduce**

1. Clone https://github.com/baldurh/react-i18next-macro-repro
0. `yarn`
0. `yarn dev`
0. You get an error: `Can't resolve 'react/i18next'`

**Expected behaviour**
You should not get an error

**Comment by jamuhl** [comment]
Do you import `react/i18next` ? it's `react-i18next`

**Comment by adrai** [comment]
Hmmm... there tests are not failing: https://github.com/i18next/react-i18next/blob/master/test/icu.macro.spec.js

different babel version?

**Comment by jamuhl** [comment]
@baldurh guess you're right...mind providing a PR fixing this?

**Comment by adrai** [comment]
Probably this will fix this problem too, right? https://github.com/i18next/react-i18next/pull/917

**Comment by baldurh** [comment]
Seems so yes 👍🏻

**Comment by redbugz** [comment]
I can separate out the bug fix from #917 if that's helpful

**Comment by baldurh** [comment]
If that mean the bug fix will be merged and released earlier then that would be helpful to me at least! 😄 But I don’t mind either way

**Comment by jamuhl** [comment]
PR will be merged in a few minutes...stay tuned ;)

**Comment by jamuhl** [comment]
published in react-i18next@10.12.0

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:

**Comment by baldurh** [comment]
Nice thanks! Great project 🙂
