### ISSUE TITLE
How do I wait for translations to load when using instance?

### ISSUE THREAD

**Issue by andrejohansson** [i18next/react-i18next#920]
If I am using the i18next instance in a typescript file that exports an object. How can I ensure that the translations have been loaded so that I do not get missing key exceptions? I also want to be able to export my object (so I cant use HOC, withTranslation or hooks).

I have seen the other methods to chain loading ina promise after i18n loads but that doesnt work in my case since I want to export types of a certain format that I can´t change the signature of.

### Sample
```typescript
import {ValidationSchema} from "class-validator";
import i18next from "i18next";

// WAIT UNTIL LOADED HERE?

export let UpdateOrganizationValidationSchema: ValidationSchema = {
  name: "updateOrganizationValidationSchema", 
  properties: {
    name: [{
      type: "isNotEmpty",
      message: i18next.t('organizations:validation.nameisnotempty')
    }]
  }
};

``` 

### Log
Notice how the translator function is trying to load before the namespace have been loaded. Even though I load my i18n file in the app root
```
i18next::translator: missingKey undefined organizations validation.nameisnotempty validation.nameisnotempty
i18next::backendConnector: loaded namespace organizations for language sv 
```

**Comment by jamuhl** [comment]
https://www.i18next.com/overview/api#loadnamespaces

```js
import {ValidationSchema} from "class-validator";
import i18next from "i18next";

const properties =  {
    name: [{
      type: "isNotEmpty",
      message: "not yet ready"
    }]
  }

i18next.loadNamespaces('organizations', () => {
  properties.name[0].message = i18next.t('organizations:validation.nameisnotempty');
})

export let UpdateOrganizationValidationSchema: ValidationSchema = {
  name: "updateOrganizationValidationSchema", 
  properties
};
```

**Comment by andrejohansson** [comment]
Works like charm, thank you!

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project :pray:
