### ISSUE TITLE
How to change language based of mobx/redux?

### ISSUE THREAD

**Issue by JonasGroenbek** [i18next/react-i18next#921]
I am using i18n to supply translations to my project, currently it will translate based on browser language. I want it to instead of that change the language based on a property in a mobx store.

I have tried looking into ``react-mobx-i18n``, and it seems like a bad solution. Because I would have to annotate every single component as translatable and restructure everything. 

I am using a file for each language, so far I have four languages

```js
import i18n from 'i18next'
import en from './en.json'
import fr from './fr.json'

i18n
    .init({
        fallbackLng: 'en',
        resources: {
        en: 
        },
        ns: ['application'],
        defaultNS: 'application',
        en: en,
        fr: fr
        react: {
            wait: true,
        },
    })

export default i18n
``` 

here is the render of my App.js

```js
import React, { Component } from 'react';
import { I18nextProvider } from 'react-i18next'
import i18n from './i18n'
import { Provider } from 'mobx-react'

export default class App extends Component {

 render() {

        return (
            <Provider {...this.props.stores}> //mobx stores
                <I18nextProvider i18n={i18n}> 
                //router want to change mobx-state and rerender everything with a new language
                </I18nextProvider>
            </Provider>
        )
    }
}

``` 
en.json
```json
{ 
  "application" :  {
     "hello": "hello"
  }
}
``` 
fr.json
```json
{ 
  "application" :  {
     "hello": "bonjour"
  }
}
``` 

I would like to somehow make i18n subscribe to my mobx state and update when a new language is detected. Should this be impossible, then I would like to write a handler in a store to change the language based on some input.

**Comment by adrai** [comment]
Have you already tried with i18next.changeLanguage?

https://stackoverflow.com/a/41021229

**Comment by JonasGroenbek** [comment]
the i18next instance passed down as props does not have the changeLanguage function.
I would like for the actual language change to happen in a store rather than a component as well, since it should depend on what user is logged in

**Comment by adrai** [comment]
Can you try to just require/import your i18n file and call the changeLanguage function from wherever you want?

**Comment by JonasGroenbek** [comment]
adrai, I have wasted hours. It took me 3 minutes ..

**Comment by adrai** [comment]
So it’s ok for you? Did it work?

**Comment by JonasGroenbek** [comment]
Absolutely, I just imported the file into the mobx store and called ``i18next.changeLanguage( lang )`` on login and put it in an handler for the dropdown. Works like a charm, rerenders and all

**Comment by adrai** [comment]
Nice to hear 👍

**Comment by adrai** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project -> there are many ways to help this project 🙏

**Comment by sanketdeshmukh19** [comment]
Can you tell me how do you manage to re-render whole app using redux after `i18next.changeLanguage(lang)`?

**Comment by jamuhl** [comment]
@sanketdeshmukh19 how do you rerender an app using redux?

**Comment by jamuhl** [comment]
@sanketdeshmukh19 https://github.com/i18next/react-i18next/issues/924
