### ISSUE TITLE
Is there any possbile to set i18n.init(lng) after promise or HTTP request

### ISSUE THREAD

**Issue by rkl1994** [i18next/react-i18next#922]
# Question about react-i18next
Hi, I have one question about i18next in my react application.
In i18n.js, there is some code like this:
`i18n.init({
lng: language
})`

I have a demand that the client language is loaded from backend from HTTP request. And Http request is async, so how could I do if I want to put i18n.init after one HTTP request such as promise?

If I put i18n.init after promise, i18n.init will not be execute. 
I would appreciate if you could give any suggestions. Thank you

**Comment by jamuhl** [comment]
so you tell me executing a function that returns a Promise blocks all code run afterwards ?!?

**Comment by rkl1994** [comment]
It seems ridiculous, however, I am facing the problem that users' client language depends on its backend language.

Maybe, i18n.changeLanguage can help me? I mean, I render the page firstly with default language, then after get the request from end, then re-render the page if language changed?

**Comment by jamuhl** [comment]
or create your own detector having async flag set ... https://www.i18next.com/misc/creating-own-plugins#languagedetector

=> https://github.com/i18next/i18next/blob/master/src/i18next.js#L249

**Comment by rkl1994** [comment]
thanks I will have a try
