### ISSUE TITLE
Re-render whole app after changeLanguage( lang )

### ISSUE THREAD

**Issue by aniketdalvi38** [i18next/react-i18next#924]
How do I manage to re-render whole app after changeLanguage ( lang ) using redux?

**Comment by jamuhl** [comment]
- how do you rerender an app using redux?

- how do you rerender a component using redux?

- what has the question todo with redux?

- why you put everything into redux?

- did you read the documentation?

- if you read the documentation - what is https://react.i18next.com/latest/usetranslation-hook or https://react.i18next.com/latest/withtranslation-hoc doing?

**Comment by aniketdalvi38** [comment]
In my app I am giving user an option to select language of user choice and I want to update whole app after user select the language.
So after updating language I am able to re-render that component but not the whole app, any solution by using redux?

**Comment by jamuhl** [comment]
wow...you're really not getting it...everything (component) that is either us useTranslation or withTranslation gets rerendered on languageChanged independent of being called from redux or whatever...

**Comment by adrai** [comment]
if you’re using the hook or the hoc etc... just do it like here: https://github.com/i18next/react-i18next/issues/921#issuecomment-521260428

import your i18next instance and call changeLanguage on you language selection...
