### ISSUE TITLE
TypeError: Cannot read property 't' of null (when inspecting tree using React dev tools)

### ISSUE THREAD

**Issue by hansott** [i18next/react-i18next#926]
**Describe the bug**
When I'm inspecting a function component with the React dev tools that uses the `useTranslation` hook, I'm getting the following error:

<img width="496" alt="Screenshot 2019-08-19 10 22 34" src="https://user-images.githubusercontent.com/3886384/63250171-4798db80-c26b-11e9-8fed-8f4f132f4e2a.png">

In my component:

```js
const { t } = useTranslation("producers");
```

Probably this line: https://github.com/i18next/react-i18next/blob/master/src/useTranslation.js#L79

**Occurs in react-i18next version**
i18next: 15.0.8
react-i18next: 10.6.0
React: 16.8.3

**To Reproduce**
Inspect the component using React dev tools

**Expected behaviour**
No `TypeError`

**Screenshots**
![crash](https://user-images.githubusercontent.com/3886384/63250220-68f9c780-c26b-11e9-84fa-058fd3d7235d.gif)

**OS (please complete the following information):**
Chrome 76 (macOS 10.14.4)

**Comment by hansott** [comment]
More details:
<img width="919" alt="Screenshot 2019-08-19 10 27 08" src="https://user-images.githubusercontent.com/3886384/63250435-ec1b1d80-c26b-11e9-8eb6-1321269cef14.png">

**Comment by jamuhl** [comment]
That only occurs when inspecting...hm...looks like a case of quantum physics...observing the experiment has an influence on the result ;)

No idea what's the cause...might be something for the people created the react dev tools?

**Comment by hansott** [comment]
@jamuhl Yeah, I was not sure whether this was a valid bug... Maybe we can just add a null check for now? I can create a PR for it?

**Comment by jamuhl** [comment]
Go ahead with a PR...if that is enough to get it "work" it's ok for me...

**Comment by jamuhl** [comment]
closing this due inactivity...PR still welcome
