### ISSUE TITLE
mock for Trans breaks on nested tags

### ISSUE THREAD

**Issue by CynthiaXJia** [i18next/react-i18next#927]
**Describe the bug**
If I run a test with the mock given for `Trans`, I get errors.

**Occurs in react-i18next version**
Latest commit
a46263e
on Feb 14

**To Reproduce**

1. write a jest test with component 
`<Trans> <a href="google.com"><b>link</b></a>` and the mock provided

**Expected behaviour**
The test gives this `Error: Uncaught [TypeError: Cannot convert undefined or null to object]`

**OS (please complete the following information):**

- Device: MBP 2014 13"

**Comment by jamuhl** [comment]
Sorry what mock provided -> we do not provide any mocks with this library...

**Comment by CynthiaXJia** [comment]
https://github.com/i18next/react-i18next/blob/master/example/test-jest/__mocks__/react-i18next.js

it's in react-i18next/example/test-jest/__mocks__/react-i18next.js

**Comment by jamuhl** [comment]
works there...so idk...you can simply mock it as `Trans: ({ children }) => <React.Fragment>(children)</React.Fragment>`

**Comment by jamuhl** [comment]
closed due inactivity
