### ISSUE TITLE
visual-studio-code does not see .d.ts

### ISSUE THREAD

**Issue by isoftninja** [i18next/react-i18next#930]
visual-studio-code does not see .d.ts. Show minimal working example.

**Comment by jamuhl** [comment]
don't get me wrong...but this for sure is not an issue

**Comment by isoftninja** [comment]
@jamuhl In the file src/index.d.ts does not mention key words declaration and module. Like tsc by following link from package.json will understand what to do with file?

**Comment by jamuhl** [comment]
No, personally I do not use typescript but those typings are maintained by @rosskevin and the community. There is a test coverage for them too.

If something is wrong...please provide a PR and include tests to assert no future regression.

**Comment by isoftninja** [comment]
@jamuhl I like your manners! You do not know case, but immediately close issue. Truly inspiring on PR!

**Comment by jamuhl** [comment]
I'm sorry, my bad...
