### ISSUE TITLE
Language Selection ex. .override("en_US") or .f("en_US")

### ISSUE THREAD

**Issue by a93h** [i18next/react-i18next#933]
**Is your feature request related to a problem? Please describe.**
Language selection override directly after or inside ".t" function call.

**Describe the solution you'd like**
example: i18n.t( "username").override("en_US")
AKA override
example: i18n.t("username").f("en_US")
AKA force

**Describe alternatives you've considered**
Alternative already exists. That's about it, I like this idea instead of the i18next.getFixedT()

**Additional context**
Right now I need to create a list of "i18next.getFixedT()" functions and it's really not something I expected to need.

**Comment by a93h** [comment]
I found a workaround, but I wonder if it's maybe faster if the library takes care of it?

```JS
function langString(language){
  return i18next.getFixedT(language);
}
```

**Comment by a93h** [comment]
And another workaround example
```js
i18next.getFixedT(this.props.locale)('language_list.locale_change'),
```

**Comment by jamuhl** [comment]
@a93h  `i18next.t(key, { lng: 'de-DE' });` and don't use `_` to separate locales that won't work (i18next splits it by `-`)

**Comment by jamuhl** [comment]
And just use this as override -> if it's a permanent user choice use `i18next.changeLanguage`

**Comment by a93h** [comment]
Thanks.
