### ISSUE TITLE
useSuspense false and use of loaders when not ready do not seem to work well

### ISSUE THREAD

**Issue by javierguzman** [i18next/react-i18next#936]
Hello all,

I am using react-i18next with useSuspense set to false. Then I grab the translations like this:

```
const {t, ready} = useTranslation("header-footer");
const translationsAvailable = ready;
```
Then in my render I have this:
```
if (translationsAvailable === false){
        return (
            <div className="text-center">
                <Loader height={30} weight={30} />
            </div>
        );
    }

```
However, when I enter the website or refresh, etc. For a fraction of a second I can see the translation keys(e.g. "header-home", "header-about", etc.) rather than my loader. 

Based on the documentation I think I am doing everything needed. Is this a bug or is this expected?

Thank you in advance and kind regards.

- Device: 15" Laptop
- Browser: Firefox 69.0

**Comment by jamuhl** [comment]
No should not be the case but might be we got an edge case -> can you check if you run into this code block? https://github.com/i18next/react-i18next/blob/master/src/utils.js#L46 that's at least my guess currently.

Setting that return to false should fix it...

**Comment by javierguzman** [comment]
Hello Jan!

I could not debug that code as it is inside node_modules and my Visual Code did not like that (that is a different story I guess). However, I have injected an infinite loop and console logs and it looks like line 46 does not execute.

I have also changed that to false and the behaviour remains the same.

**Comment by jamuhl** [comment]
If it's pure clientside that's the only possible problem I can think of to get that value true for ready before it's really ready ;)

you will have to dig deeper or provide a sample on codesandbox to reproduce this behaviour...

**Comment by javierguzman** [comment]
Thanks! I will continue investigating more. I will let you know sooner or later the outcome! :)

**Comment by PsychedMagnet** [comment]
Hi, @javierguzman 

Excuse me,  as I may be misunderstanding something, but doesn't `useTranslation` return an array and not an object? In the snippet you gave, you are destructuring it as an object, not an array.

**Comment by jamuhl** [comment]
@PsychedMagnet https://react.i18next.com/latest/usetranslation-hook#what-it-does does both

**Comment by PsychedMagnet** [comment]
> @PsychedMagnet https://react.i18next.com/latest/usetranslation-hook#what-it-does does both

I didn't even know it is possible, even looking at the source I still don't understand how that is.
Anyways, discard my comment in this case! 😄

**Comment by javierguzman** [comment]
Hello!

It seems that after handling the ready in the high level "App" works fine. So in other words, before I had my react router stuff, whatever page I was, I was including as well Header and Footer components always. For some reason I do not understand, even though each component was handling the ready/loading stuff, it was not working good.

Maybe one subcomponent was slow enough to not even show the loading, and when the loading was gonna be shown, it was not needed because the language was ready. So while the loading is not shown, the translation keys would be shown. Not sure if I am explaining myself well. Does this make sense?

The summary is that, handling as well the translation ready in the app where I have my router stuff, seems to fix the problem, as until the App is not ready, nothing is ready.

I will wait a few days to see some answers and then I will close this from my side. However, I will keep an eye on this, as is all assumptions!

**Comment by jamuhl** [comment]
closing this for now...feel free to reopen with more insights
