### ISSUE TITLE
icu.macro for Plural/SelectOrdinal does not handle count prop of name count, or expressions

### ISSUE THREAD

**Issue by redbugz** [i18next/react-i18next#937]
**Describe the bug**
I am working on a PR to fix this, but wanted to start a discussion about the best way to handle it.

When using the non-`Trans` icu macros `Plural/SelectOrdinal` (and `Select` with the `switch` prop), the `count` prop is put into `values` during transformation, and since `count` is handled specially by the normal `Trans` component, it does not render correctly.
This means you cannot use a variable named `count` in `Plural` or `SelectOrdinal`

Also, it must be a standalone variable, no expressions are allowed. If you use an expression in the `count` or `switch` props, you get `TypeError: react-i18next/icu.macro: Property name expected type of string but got null`

**Occurs in react-i18next version**
all versions I believe. I don't think this has ever worked, it has either never come up, or always got worked around by introducing local variables

**To Reproduce**
Use `Plural` with a variable named `count`

```
<Plural
          i18nKey="somekey"
          count={count}
          $0="There are no items."
          one="There is <Link to='items'># item</Link>."
          other="There are <Link to='items'># items</Link>."
        />
```
This results in the `#` being replaced with `NaN` because `count={count}` above is transformed into `<Trans values={{count}}...` and `Trans` requires that `count` be a special prop. So you end up with opts like this:
```
{ count: undefined, values: {count: count} }
```
Since `count` is undefined, you get `NaN` instead of using the `count` in values.

OR use `Plural` with `count` as an expression
```
<Plural
          i18nKey="items.link.string" // optional key
          count={index+1}
          $0="There are no items."
          one="There is <Link to='items'># item</Link>."
          other="There are <Link to='items'># items</Link>."
        />
```
This results in the TypeError from above.

**Expected behaviour**
The `count` prop of `Plural/SelectOrdinal` and the `switch` prop of `Select` can be an expression or a variable named `count` 

**Additional context**
For the variable named `count`, the solutions I see are either to transform `count` into the prop named `count`
`<Plural count={count} --> <Trans count={count}`
or to allow the `count` prop to come from values if it isn't defined as it's own prop.

For not allowing expressions, we can either just document that limitation, or transform it correctly:
`<Plural count={index+1} --> <Trans count={index+1}`
OR if we decide to allow count to come from values as a fallback:
`<Plural count={index+1} --> <Trans values={{count:index+1}}`

Transforming `count` into the same `count` prop on `Trans` seems like the easiest solution, just want to confirm that it won't trigger any special behavior around the `count` prop and cause conflicts or other unforeseen side effects.

For the expressions, I believe I can just check if it is an expression type and copy the expression over. If you want to keep the code simpler and just document the limitation that you must introduce a local variable for the expression, I can do that too.

**Comment by redbugz** [comment]
Both can be worked around by introducing new local variables to rename `count` to something else, or to hold the expression:
```
const mycount = count
<Plural count={mycount} ...

const newcount = index + 1
<Plural count={newcount}...
```

**Comment by jamuhl** [comment]
Guess `count` here https://github.com/i18next/react-i18next/blob/master/src/Trans.js#L240 could be `count: count || (values && values.count)` but not tested

**Comment by redbugz** [comment]
Is that the preferred direction, to allows an undefined count to fallback to values?

We will need to do an actual undefined check since count could be zero. But I will put that in the PR with some tests.

**Comment by jamuhl** [comment]
right ... needs check for undefined. Guess this does not hurt...in the end values are expected to be passed to t function as options

**Comment by redbugz** [comment]
After working in the code, in order to support expressions I had to do most of the work to support copying the count prop to Trans, so I just decided to implement copying the count prop from Plural to Trans.
I can also have it fallback to values as you suggested as well if you like.

**Comment by jamuhl** [comment]
closing this now - PR was merged
