### ISSUE TITLE
Plural doesn't work for non en locale

### ISSUE THREAD

**Issue by Skriptach** [i18next/react-i18next#940]
**Describe the bug**
Given such keys:
for en
```json
    "upload": {
      "files": "{{count}} file was uploaded",
      "files_plural": "{{count}} files were uploaded"
    },
```
and for ru
```json
    "upload": {
      "files": "загружен {{count}} файл",
      "files_plural": "загружено файлов: {{count}}"
    },
```

Invoke in a react component:
```javascript
const { count } = this.state;
<p>{ t('upload.files', { count }) }</p>
```
Works fine when locale is `en`. But after switching to `ru` returns only single key. No matter what `count` is.

**Occurs in react-i18next version**
react-i18next@^10.12.2

**Comment by jamuhl** [comment]
ru has more than one pluralform: https://www.i18next.com/translation-function/plurals#languages-with-multiple-plurals and https://www.i18next.com/translation-function/plurals#how-to-find-the-correct-plural-suffix

**Comment by Skriptach** [comment]
Thanks for help :)
