### ISSUE TITLE
Translation not used, if key has a period in it

### ISSUE THREAD

**Issue by stevewillard** [i18next/react-i18next#944]
## Describe the bug
If you have a locale, for example: `static/locales/en/common.json`
```
{
    "Do something.": "here!",
}
```
If the key has a `.` (period) in it, the string doesn't translate properly.

## Occurs in next-i18next version
`1.2.0`

## Steps to reproduce
See the JSON above

## Expected behaviour
The string is translated.

**Comment by jamuhl** [comment]
Hope that helps: https://www.i18next.com/principles/fallback#key-fallback

https://www.i18next.com/overview/configuration-options#misc -> keySeparator: false, nsSeparator: false

**Comment by stevewillard** [comment]
Perfect! Thank you.
