### ISSUE TITLE
Adding descriptions to the translation value

### ISSUE THREAD

**Issue by JiahaoShan** [i18next/react-i18next#946]
Hey, I am new to the react-i18next and I wonder if there is a way I can provide some descriptions to the translation. 

In react-intl, you can provide `description` to a [FormattedMessage](https://github.com/formatjs/react-intl/blob/master/docs/Components.md#formattedmessage). Is there an equivalent feature in react-i18next?  

For example, if there is a text, "Application", needs to be translated, without a description, it can either mean an software application or a job application. What is a good way to provide this context/description to the translator? Thank you!

**Comment by jamuhl** [comment]
Depends on the backend used...:

`t` can be called like `t(key, defaultValue, contextInfo)` or `t(key, { tDescription: 'contextInfo' })`

but currently only locize.com as TM will use that context information for translators...
