### ISSUE TITLE
Conditional usage of hooks?

### ISSUE THREAD

**Issue by imbhargav5** [i18next/react-i18next#949]
**Describe the bug**
useSSR is utilising useContext conditionally and this is causing a bug.
https://github.com/i18next/react-i18next/blob/83625bab0c1ee7fc7f889ff4c0f70a2e8cdfb79a/src/useSSR.js#L6
**Occurs in react-i18next version**
N/A

**To Reproduce**
N/A
**Expected behaviour**
N/A

**Screenshots**
N/A

**OS (please complete the following information):**
N/A

**Additional context**
This occurs rarely.

**Comment by jamuhl** [comment]
It happens only if your app ist broken by using useTranslation outside of the Provider....but

feel free to provide the same fix like in https://github.com/i18next/react-i18next/pull/935 as a PR

**Comment by imbhargav5** [comment]
@jamuhl Done

**Comment by jamuhl** [comment]
published in react-i18next@10.13.1
