### ISSUE TITLE
HOC `withTranslation` doesn't copy static attributes and methods over

### ISSUE THREAD

**Issue by percypyan** [i18next/react-i18next#958]
**Describe the bug**
The statics of WrappedComponent aren't passed over the `withTranslation` HOC.

**Occurs in react-i18next version**
Noticed in version 10.13.1, but I suppose it's this way since the introduction of `withTranslation` HOC to replace the `translate` one.

**To Reproduce**
Simply define some statics on a component, then try to use one those statics on the WrappingComponent.

I've already done a Pull Request (#959) with a non-regression test, you can refer to it. 

**Expected behaviour**
We expect the statics to be passed over.

**Comment by jamuhl** [comment]
https://react.i18next.com/latest/withtranslation-hoc#hoist-non-react-statics it's expected behaviour

**Comment by percypyan** [comment]
Yep, my bad. I've should have checked.
