### ISSUE TITLE
React has detected a change in the order of Hooks called by withI18nextTranslation

### ISSUE THREAD

**Issue by james2406** [i18next/react-i18next#960]
**Describe the bug**
useEffect and useState are conditionally called in the useTranslation.js file

**Occurs in react-i18next version**
10.13.1

**To Reproduce**
1. Initialise i18next with the i18next-xhr-backend plugin
2. Initialise useTranslation hook in a component which displays before i18next is ready

**Expected behaviour**
NA

**Screenshots**
<img width="687" alt="Screenshot 2019-10-03 at 13 56 58" src="https://user-images.githubusercontent.com/10858584/66128454-c06ab180-e5e5-11e9-8bf4-9c03b0a2d347.png">

**OS (please complete the following information):**
- Device: MBP Late 2013 15"
- Browser: Chrome 77.0.3865.90 (Official Build) (64-bit)

**Additional context**
NA

**Comment by james2406** [comment]
You can see that useState line is conditional as line 26 returns before it is called https://github.com/i18next/react-i18next/blob/b9c1b1c8c81c793c0f446f42d693a3993299ff4b/src/useTranslation.js#L26

**Comment by jamuhl** [comment]
Don't you think that this is ok?

There is no i18n defined at that if -> means your app is broken in the sense of it is broken...we can change that code...only difference...you get no warning from react...but your app is still broken

**Comment by james2406** [comment]
I see what you mean. The block of code with the return should never run if your application has been set up correctly. I'll solve it by making sure i18n is initialised before rendering my react app.

Thanks for the help and for creating an amazing library that makes internationalization easy!
