### ISSUE TITLE
More documentation around useSSR

### ISSUE THREAD

**Issue by bruqui** [i18next/react-i18next#962]
I wish there was a little more documentation around the useSSR. In the documentation it states to build a component like this...

```
import React from 'react';
import { useSSR } from 'react-i18next';

export function InitSSR({ initialI18nStore, initialLanguage }) {
  useSSR(initialI18nStore, initialLanguage);
  
  return <App />
}
```

The problem is it doesn't show where the initialI18nStore prop comes from. I get initialLanguage would be something like 'es', 'en', 'etc', but I'm just not sure where initialI18nStore comes from. Is that something from the middleware or the I18nextProvider?

**Comment by jamuhl** [comment]
`initialI18nStore` gets passed down from the server, eg. razzle sample:

server: https://github.com/i18next/react-i18next/blob/master/example/razzle-ssr/src/server.js#L78
client: https://github.com/i18next/react-i18next/blob/master/example/razzle-ssr/src/client.js#L9

for next.js you might have a look at: https://github.com/isaachinman/next-i18next

And like always...would be happy if you contribute your insights to the documentation - improving it for the next one struggling...

**Comment by bruqui** [comment]
Thanks @jamuhl. My real problem is trying to get this to work with Gatsby and if I can figure it out, I'd be happy to contribute. There's a [Gatsby blog post](https://www.gatsbyjs.org/blog/2017-10-17-building-i18n-with-gatsby/) on how implement this library, but it doesn't really work... at least the way I want it to. As a result, I'm attempting to find the best solution and pass it on like you're suggesting.

**Comment by jamuhl** [comment]
My hope it gatsbyjs get soon the momentum to create a gatsby-i18next like the nextjs community did with next-i18next...

**Comment by bruqui** [comment]
There are some plugins created, but they're kinda weird so I thought I'd try to crank one out if I can. I'm new to Gatsby as well so there's a pretty big learning curve for me going on.

**Comment by jamuhl** [comment]
neither using next nor gatsby...so I'm happy the community steps in

**Comment by bruqui** [comment]
Oh wow... I think your links to the examples is going to help me quite a bit! The i18next-node-fs-backend library looks promising for what I need. Thanks for your help.
