### ISSUE TITLE
Type Check Dictionaries with TypeScript

### ISSUE THREAD

**Issue by wzup** [i18next/react-i18next#963]
## Question about react-i18next

Is there a possibility to type check existing keys in dictionaries? And throw TS error if key doesn't exist. Default behavior doesn't do it.

Here is what I mean.
Suppose, we have this dictionary:

```json
{
  "footer": {
    "copyright": "Some copyrights"
  },

  "header": {
    "logo": "Logo",
    "link": "Link",
  },
}
```

If I provide non-existent key, TS should blow up:
```
const { t } = useTranslation();

<span> { t('footer.copyright') } </span> // this is OK, because footer.copyright exists
<span> { t('footer.logo') } </span> // TS BOOM!! there is no footer.logo in dictionary
```

What is the proper name of this technique? I'm very sure I'm not the only one who is asking for this behavior. 
Is it implemented in this library? 
Are there API to extend the library somehow to enable it?

## Questions should be posted on StackOverflow

https://stackoverflow.com/questions/58277973/how-to-type-check-i18n-dictionaries-with-typescript

**Comment by jamuhl** [comment]
No that is not built in...also not sure how to achieve such a check during build time...but there is a missing handler you can use during runtime (or the saveMissing feature)

**Comment by wzup** [comment]
@jamuhl 
I found a blog post where a guy explains how he did it with Airbnb’s Polyglot package https://spin.atomicobject.com/2017/12/19/type-check-polyglot-dictionary/
So it is possible. We need to understand how to implement it with this package.

**Comment by jamuhl** [comment]
`i18next.store.data` is where the translations are stored `i18next.t` the function called to access translations...guess that is all you need?!?

**Comment by wzup** [comment]
@jamuhl 
> i18next.store.data is where the translations are stored

Can we access translations directly from store? Like:

```typescript
const t = i18next.store.data;
<span>{ t.Header.title }</span>
```

I think it may allow to use typescript path suggestion

**Comment by ydang204** [comment]
Sorry, but can you share with me an example on how to configure React app with I18Next and Typescript?
I faced some errors and can not make it works.
Thanks

**Comment by jamuhl** [comment]
@ydang204 i would check the https://github.com/i18next/react-i18next/blob/master/tsconfig.json and tests...

**Comment by jamuhl** [comment]
closing in favour to https://github.com/i18next/i18next/issues/1337

**Comment by zmnv** [comment]
You can use that only for flat structure:

```
import en from './en.json';

const key = 'someKey';

type TranslationKeys = keyof typeof en;
export const t = translation<TranslationKeys>(key);
```
