### ISSUE TITLE
How can you define three same constants in 'useTranslation' function?

### ISSUE THREAD

**Issue by wzup** [i18next/react-i18next#967]
### Question about react-i18next

It is here. How is it possible?
![screenshot-newtab-2019 10 13-21_44_31](https://user-images.githubusercontent.com/3880497/66720254-13710f80-ee03-11e9-9911-19ca28bbacbe.png)

https://github.com/i18next/react-i18next/blob/master/src/useTranslation.js#L15

**Comment by jamuhl** [comment]
https://wesbos.com/destructuring-renaming/

**Comment by wzup** [comment]
I thought it was TS type check.
Thanks
