### ISSUE TITLE
404 on resources loading

### ISSUE THREAD

**Issue by M3lkior** [i18next/react-i18next#97]
Hi,

I try to integrate react-i18next in my react project but the translations init fail with a 404 :

![image](https://cloud.githubusercontent.com/assets/5501911/15252774/ce951a10-192f-11e6-8086-163896661ff9.png)

Here is my project structure & i18N configuration : 

![image](https://cloud.githubusercontent.com/assets/5501911/15252838/ff65ca0e-192f-11e6-9e45-5d854c581e7c.png)

My index.jsx

```

import React from "react";
import ReactDOM from "react-dom";
import { I18nextProvider } from 'react-i18next';
import i18n from './utils/i18n'; // initialized i18next instance


import 'bootstrap/less/bootstrap'
import App from "./containers/App";

ReactDOM.render(
    <I18nextProvider i18n={ i18n }><App /></I18nextProvider>,
    document.getElementById("app")

);
```

The component render by App : 

```
import React from 'react';
import { translate } from 'react-i18next';

function Component({t}) {
  return <p>{t('usingDefaultNS', { /* options t options */ })}</p>
}

export default translate()(Component);
```

I don't find what i do wrong ... any ideas ?

**Comment by jamuhl** [comment]
Not sure. But it seems the resources are not served by a server. The xhr backend won't find the resources if there is no server counterpart. You can try the webpack loader.

Alternatively you can use locize.com if you like to use a saas offering for internationalization. We are close to beta launch. If you're interested we might get you on private beta...

**Comment by M3lkior** [comment]
Hi @jamuhl,

Thanks for your reply. I actually test your sample who works without any webpack loader ... after comparing the source, i don't find the differences between souces code.

What about the webpack loader you are talking about ?

Concerning locize.com, i must use a experienced vendor ^^

**Comment by jamuhl** [comment]
https://github.com/atroo/i18next-resource-store-loader for the loader...

how do you serve the locales folder?

**Comment by M3lkior** [comment]
Oh right my bundles was in server side and so not exposed. Thanks @jamuhl 

i18next-resource-store-loader allows webpack to serve server side locales to client ?

**Comment by jamuhl** [comment]
no the loader will bundle the assets...not recommended if having big projects
