### ISSUE TITLE
Way to render html with hook useTranslation ("t") ?

### ISSUE THREAD

**Issue by Oxygen66** [i18next/react-i18next#972]
Hi ! 

I use the hook useTranlation() and i don't find the way for use HTML directly in  translation's files.

Can you help me please ?

Thanks

**Comment by jamuhl** [comment]
react does not allow to pass html as string content -> you will have to create a component using https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml

**Comment by Oxygen66** [comment]
The <Trans /> component allow to do that.
Why the hook does not allow to do the same?

**Comment by jamuhl** [comment]
the hook gives you a `t` function - the function does give you a `string` a string gets passed to react component tree -> how should be magically be able to tell react to dangerously insert that string?


```js
const { t } = useTranslation();

<div>{t('key')}</div> // <--- it's a string not more
```

**Comment by Oxygen66** [comment]
Hmm okay, i close so.

**Comment by jamuhl** [comment]
And the `t('key')` can return html...it's react that encodes strings per default...to save you from xss...that's why you need to tell react to use dangerouslySetInnerHtml on your own risk
