### ISSUE TITLE
Docs URL given in error message no longer exists (legacy v9)

### ISSUE THREAD

**Issue by Gummy47** [i18next/react-i18next#973]
**Describe the bug**
When encountering an error indicating a missing i18n instance, the attached docs URL (https://react.i18next.com/components/overview#getting-the-i-18-n-function-into-the-flow) no longer exists.

```
react-i18next:: You will need pass in an i18next instance either by props, using I18nextProvider or by using i18nextReactModule. Learn more https://react.i18next.com/components/overview#getting-the-i-18-n-function-into-the-flow
0|ssr-dev  | TypeError: Cannot read property 'wait' of null
0|ssr-dev  |     at NamespacesConsumerComponent.render (/client/node_modules/react-i18next/dist/commonjs/NamespacesConsumer.js:220:33)
```

**Occurs in react-i18next version**
9.0.10

**To Reproduce**
Try to apply `withNamespaces()` HOC without having implemented `I18nextProvider` higher in the component tree.

**Expected behaviour**
A correct URL

**OS (please complete the following information):**
- Device: PC
- Browser: Chrome 77.0.3865.120

**Comment by jamuhl** [comment]
the page can be found here...https://react.i18next.com/legacy-v9/overview#getting-the-i-18-n-function-into-the-flow

there is no current section for this in the documentation - will remove the link or next release

**Comment by jamuhl** [comment]
ah...that is even the old react-i18next v9 version...so not much to do...v10 already removed that link

**Comment by Gummy47** [comment]
Sure but since it's a legacy version, might as well point to an existing page don't you think? I understand it's far from being a big deal though, just a small detail.

**Comment by jamuhl** [comment]
Would need to publish an update to v9...just to update that link...honestly would prefer people upgrading to v10 ;)

**Comment by Gummy47** [comment]
If there are no other requests for v9, I understand. I would have used v10 if my project allowed it, unfortunately i'm around 1k components all written in class and I just don't have the time to refactor them in order to work with hooks. Thanks for your work on this module though!
