### ISSUE TITLE
Uncaught Invariant Violation: Invalid hook call.

### ISSUE THREAD

**Issue by samayo** [i18next/react-i18next#978]
This is either a bug or a question, because I can't get this library to work for some reason.

Basically I am trying to use it inside a component as: 
```js
import { useTranslation, Trans } from 'react-i18next'

class HelloWorld extends React.Component {
 
  render () {
      const { t, i18n } = useTranslation();
  }
}
```
this throws an error like: 

> Uncaught Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component...

and no example is given to circumvent this problem and my `HelloWorld` component is already contained inside a HOC, so I don't know what the solution is. 

If I remove `react-i18next` and use just `i18next` it works without any problem as

```js
// i18n.js
import i18next from 'i18next'
i18next.init({
 lang: 'de',
 resources: {
  en: {
   translation: { "welcome" : "welcome" }
  },
  de: {
   translation: { "welcome" : "willkommen" }
  }
 }
})
export default i18next
```

And in my component, it works as shown in the readme
```js
import trans from '../i18n'

class HelloWorld extends React.Component {
 
  render () {
      return <div> { trans.t('welcome') </div>
  }
}
```

So, it is strange that `react-i18next` being a wrapper is supposed to ease working with `i18next` actually makes it impossible to use

**Comment by jamuhl** [comment]
Uncaught Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component...

Says it all...hooks are for functional components https://react.i18next.com/latest/usetranslation-hook#what-it-does

```js
export function MyComponent() {
  const { t, i18n } = useTranslation();
  // or const [t, i18n] = useTranslation();

  return <p>{t('my translated text')}</p>
}
```

can't be used inside of a class component!!!

https://react.i18next.com/latest/withtranslation-hoc use this for your class based components...

**Comment by samayo** [comment]
@jamuhl  Thanks. I thought about using HOC already, but I am using one for redux in all my components as: 
```js
const mapStateToProps : any = state => ({
...
})

export default connect(mapStateToProps)(HelloWorld)
```
The question is, how do I even wrap a component that is already wrapped and is there any alternative than to do this for every component?

**Comment by jamuhl** [comment]
Is this an issue or a teaching lesson in react?!? https://reactjs.org/docs/higher-order-components.html#convention-maximizing-composability

The compose utility function is provided by many third-party libraries including lodash (as lodash.flowRight), Redux, and Ramda.

**Comment by jamuhl** [comment]
or wrap the wrapped component `export default withTranslation()(connect(mapStateToProps)(HelloWorld))`

**Comment by Kikketer** [comment]
<img width="1015" alt="Screen Shot 2020-09-29 at 12 34 02 PM" src="https://user-images.githubusercontent.com/958042/94597207-e6f01680-0252-11eb-8e64-b72286a00ede.png">

Sorry digging up an old one.  This is the error I see when simply adding the `useTranslation` to my current react-native project.  The other hooks work fine, not until I add this line.  Is there something different I should be doing for react-native?  This same setup is built in my basic react project.

react-native@0.61.5
react@16.9.0
react-redux@7.1.0 -- probably not related but you never know

**Comment by jamuhl** [comment]
no idea...can you reproduce it in the sample? https://github.com/i18next/react-i18next/blob/master/example/react-native

**Comment by Kikketer** [comment]
Narrowed down the issue to having multiple instances of React in my project.  Background: it's a mono-repo with react-native as one of the "packages".  React-Native and the other projects had their own instance of React (even though they were the same version).  Fixed it by adjusting our no-hoist configuration (yarn).
