### ISSUE TITLE
Load the whole namespace

### ISSUE THREAD

**Issue by bitttttten** [i18next/react-i18next#980]
Is it possible to load the whole namespace into an object? I have a team that use different namespaces for config, or to keep parts of the website different for each language.

For example, there is a part of the website that displays different headings, although these can be different amount of headings per language. We also use the `key` of the translation to fetch statistics from a 3rd party api, so each `key` is loading some data to display too.

```
// nl.json
{
	"course": "Menugang",
	"aed": "Allergiën en dieet",
	"other": "Overig"
}
```

```
// en.json
{
	"course": "Course",
	"allergy": "Allergies",
	"age": "Age",
	"other": "Other"
}
```

So it seems easiest to just load the whole namespace and work with the object. Is this possible?

**Comment by jamuhl** [comment]
do you mean this: https://www.i18next.com/translation-function/objects-and-arrays#objects ?!?

**Comment by jamuhl** [comment]
works with one limitation...you can't pull the namespace but a key inside namespace being an object:

```js
// en.json
{
  data: {
	"course": "Course",
	"allergy": "Allergies",
	"age": "Age",
	"other": "Other"
  }
}

i18next.t('data', { returnObjects: true });
```

**Comment by bitttttten** [comment]
Yes, returnObjects but returning the whole namespace.

Well I think I can work with putting them all into a key and getting them out of the key. Thanks!

**Comment by jamuhl** [comment]
Needs a key...there is no option for getting it without putting it in one key to access
