### ISSUE TITLE
Using colon `:` with t() make a split of the value given

### ISSUE THREAD

**Issue by mahmoud-zakria-sociomantic** [i18next/react-i18next#985]
**Describe the bug**
Using `:` in a `t()` makes a split for the value for example `t("Example: zak")` it gives me "zak" only, or looks like it behave like key/value pairs and needs to be escaped.

**Occurs in react-i18next version**
11.0.1

**Comment by adrai** [comment]
Maybe your nsSeparator is ‘:’ ?

https://www.i18next.com/overview/configuration-options#misc

**Comment by mahmoud-zakria-sociomantic** [comment]
@adrai Yes, found it and closing this issue.
