### ISSUE TITLE
Initial language

### ISSUE THREAD

**Issue by hlarcher** [i18next/react-i18next#986]
I need the current language to be stored in redux, how do I keep the react-i18next in sync with it and most importantly how do I initialise react-i18next with the language in redux so that when I refresh I have the same language in both?

**Comment by gediminaskv** [comment]
I use this to get current language in React:
`const { t, i18n } = useTranslation();`
`const currentLang = (Array.isArray(i18n.languages)) ? i18n.languages[0] : i18n.languages;`

**Comment by jamuhl** [comment]
`i18next.changeLanguage()` to change language...

but...not everything should be put into a redux store...there is i18next-browserLanguage-detector  which caches languages set...
