### ISSUE TITLE
Basic usage not working with Next serverless - Text is overridden by the frontend

### ISSUE THREAD

**Issue by Vadorequest** [i18next/react-i18next#989]
**Describe the bug**
I've configured a very simple example to see how it works with a Next.js app v9.2.

When the page loads (SSR) it first renders the right string ("Bienvenue !") but then changes it to "welcome". If I click on the "Accueil" link, it displays the right string again. 

Here is a reproduction live demo: https://tfp-26dl9lieb.now.sh/

Here is a screenshot:
![image](https://user-images.githubusercontent.com/3807458/68356238-08638380-0112-11ea-8dc8-f9b012466d56.png)

**Occurs in react-i18next version**
    "i18next": "19.0.0",
    "react-i18next": "11.0.1",

**To Reproduce**
Here is a diff of my source code:
https://diffy.org/diff/t0jhkm3aj1vkmzzzdvi24vx6r

(it'll be available only 5 days)

**Expected behaviour**
The "Bienvenue !" text should be displayed and not be changed on the frontend.

**OS (please complete the following information):**

- Browser: Chrome latest

**Comment by jamuhl** [comment]
Please have a look at https://github.com/isaachinman/next-i18next/tree/master/src integration into next.js is out of scope for this repo as @isaachinman and the community did a great job with next-i18next (getting that right and covering all edge cases might be harder than one might think on first glance)

**Comment by Vadorequest** [comment]
Yeah, but they don't yet cover the "serverless" mode, which is what I'm using.

So, I'm trying to understand what's wrong with my own implementation, which doesn't seem complicated at all.

**Comment by jamuhl** [comment]
as you pass translation as resources there is no loading...only thing could happen -> different language on server than on client...

**Comment by Vadorequest** [comment]
I loaded the file using `require` from filesystem, I wonder if that could be the cause. Maybe it's available on the server, but not on the client.

The language should be the same. I'll dig in. I couldn't make the file loader work because it asks for a full path, and I want to use a relative one.

**Comment by Vadorequest** [comment]
Alright, so, after a bit more digging around I understood my mistake: I had put the code that configure react-i18next in the `pages/_app` file, in the `getInitialProps`, which is only executed on the server side.

Moving the code to my the `render` function made it work.

**Comment by jamuhl** [comment]
glad you found the cause...
