### ISSUE TITLE
Updating to v11 can break prop forwarding when using withTranslation

### ISSUE THREAD

**Issue by emroussel** [i18next/react-i18next#990]
**Describe the bug**
Forwarding a ref named `forwadedRef` (which is the [name react use in the examples in their docs](https://reactjs.org/docs/forwarding-refs.html#forwarding-refs-in-higher-order-components)) does not work on v11, but used to on v10.

I am not familiar with the best practices of forwarding refs with HOCs, and I can just rename this ref to something else to make our code work again, but it feels confusing that this specific name wouldn't work. If this behavior is indeed common and the maintainers don't feel like it's something worth fixing, this should probably at least be mentioned in the breaking changes of v11.

**Occurs in react-i18next version**
Seems to have been introduced by this commit since it's grabbing `forwardedRef` out of props: https://github.com/i18next/react-i18next/commit/299f4ff31339a0ace8d05e79b5e45e0a5bfe525e

**To Reproduce**
This code used to appropriately pass `ref` to the wrapped component in v10, it doesn't in v11.

```js
const InputWithRef = compose(
    withTranslation(),
    withProps(({ forwardedRef }) => ({ ref: forwardedRef }))
)(Input);

export const Input = React.forwardRef(
    (props, ref) => <InputWithRef {...props} forwardedRef={ref} />
);
```

**Expected behaviour**
For `withTranslation` to not remove `forwardedRef` from the props passed to its children.

**Screenshots**
N/A

**OS (please complete the following information):**

- Device: N/A
- Browser: N/A

**Additional context**

**Comment by jamuhl** [comment]
can you check if changing https://github.com/i18next/react-i18next/blob/master/src/withTranslation.js#L28 to: `const forwardRef = (props, ref) => <I18nextWithTranslation forwardedRef={ref} {...props}  />;` works for you?

**Comment by emroussel** [comment]
@jamuhl that didn't work, but after looking at the code, I realized there's a `withRef` option that can be passed to `withTranslation`. For simple examples like the one above, it can be fixed by doing this

```js
export const Input =  withTranslation(undefined, { withRef: true })(Input),
```

However, I still think it's unexpected that `withTranslation` would never propagate `forwardedRef` to its children (and makes it hard to wrap a component with multiple HOCs), so I opened this PR to fix it: #992 

It should make the code I had above work.

**Comment by jamuhl** [comment]
that's what I meant...you need to set withRef...

will check the PR but basically you're PR makes setting withRef obsolete by always forwarding forwardedRef

**Comment by emroussel** [comment]
@jamuhl oh that's true, I could only add `forwardedRef` to the props if `withRef` if falsy. What do you think?
