### ISSUE TITLE
Working in local, error in production build (Urgent Attention Required!) 

### ISSUE THREAD

**Issue by rollinmendez000** [i18next/react-i18next#993]
**Describe the bug**
I am using react-i18n along with react, redux latest versions.

Code is as shown below

import { withTranslation } from 'react-i18next'

Using HOC  function as shown below

export default withTranslation()(connect(mapStateToProps, mapDispatchToProps)(Component))

This is to use with class components. Working fine in local but getting error in production build.

**Occurs in react-i18next version** - 11.1.0
npm version 6.9.0

**Expected behaviour**
Expects same behaviour even in production build as in development environment.

**Screenshots**

**OS (please complete the following information):**

- Device: [e.g. iMac "]
- Browser: [e.g. Electron - v1.8]

**Additional context**

**Comment by jamuhl** [comment]
Do you really believe this is an issue with this module and not with your setup????

**Comment by jamuhl** [comment]
did you figure out what was causing it?

**Comment by rollinmendez000** [comment]
> did you figure out what was causing it?

Please check mail..
