### ISSUE TITLE
Using i18n.t function on SSR synchronously

### ISSUE THREAD

**Issue by carloscuesta** [i18next/react-i18next#996]
Hello 👋

I have a project where I'm using [`next-i18next`](https://github.com/isaachinman/next-i18next) to SSR translations. In some parts of my codebase I need to use `i18n.t` function outside React components. The usage of `i18n.t` as stated in [this comment](https://github.com/i18next/react-i18next/issues/909#issuecomment-514604843) not asserts translations are loaded when the function is called. So clearly this **is not a bug**

Then on rendering, the translations are loaded asynchronously. That means that the page source does not include the translations on initial load, so bots and SEO will be affected.

<details>
  <summary>Here's a little GIF of what happens</summary>

  ![2019-11-15 12-33-06 2019-11-15 12_33_33](https://user-images.githubusercontent.com/7629661/68941417-22523580-07a6-11ea-8504-e8b3d8151fb4.gif)
</details>

I tried to set the [`initImmediate`](https://www.i18next.com/overview/configuration-options#misc) to `false` in order to fix that issue but it's not working as I would expect. Probably I missunderstood the purpose of that option 😅.

So I'm wondering if it's possible or if any workarounds could be made to use `i18n.t` outside React components and have the translations loaded synchronously from the server.

I've made a repository that shows my use case:

- [Reproduction repository](https://github.com/carloscuesta/next-i18next)

Related issues: #909

Thanks ❤️ 🙏

**Comment by jamuhl** [comment]
a) use next-i18next correctly...the point using next-i18next is SSR -> SEO friendly render first on server. Correctly following the sample you will see initial translations needed will be passed down as initialStore and language set on server as initialLanguage...=> regarding using next-i18next you will get more help asking questions there...

initImmediate -> just runs init directly (not delaying it for other code to run first)
synchronously loading -> find a backend doing sync loading or create one your own ---> but this is a very bad idea...better use next-i18next like intended

**Comment by carloscuesta** [comment]
Thanks @jamuhl 

I was just wondering if that was possible, with the `useTranslation` hook everything works perfectly. I will cut out those edge cases where I use the `i18n.t` outside React

Thanks for the quick response 🙏

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.
If you liked my support / work - I would enjoy a coffee sponsored using the “:purple_heart:Sponsor Button”.
There are many ways to help this project :pray:
