### ISSUE TITLE
Cannot read property 'type' of undefined error message in i18next.js 

### ISSUE THREAD

**Issue by mcopur** [i18next/react-i18next#997]
Hi,

I am using  "react-i18next": "11.2.1", i18.js file as below: 

```
import i18n from 'i18next';
import XHR from 'i18next-xhr-backend';
import config from 'config';
import { reactI18nextModule } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

i18n.use(XHR)
  .use(LanguageDetector)
  .use(reactI18nextModule) // if not using I18nextProvider
  .init({
    fallbackLng: 'en',
    debug: true,

    interpolation: {
      escapeValue: false, // not needed for react!!
    },

    // react i18next special options (optional)
    react: {
      wait: false,
      bindI18n: 'languageChanged loaded',
      bindStore: 'added removed',
      nsMode: 'default'
    }
  });

export default i18n;
```

And my index.jsx file like that: 

```
const mount = document.getElementById('app');
ReactDOM.render(
  <IntlProvider locale="en">
    <I18nextProvider i18n={i18n}>
      <Provider store={store}>
        <Routes history={history} routes={routes} />
      </Provider>
    </I18nextProvider>
  </IntlProvider>,
  mount
);
```

When I run the application I got  that error:

![image](https://user-images.githubusercontent.com/10618618/68984478-96c1be80-0810-11ea-9c06-fe18131263a3.png)

![image](https://user-images.githubusercontent.com/10618618/68984522-de484a80-0810-11ea-9802-4a99fa1f04a7.png)

What am I missing? Can you help me?

**Comment by jamuhl** [comment]
find out which module you pass in at i18n.use(THIS) is `undefined`

but as you're using an uptodate version I guess it should be:

`import { initReactI18next } from 'react-i18next';` not  `reactI18nextModule`  -> https://react.i18next.com/latest/i18next-instance

**Comment by jamuhl** [comment]
If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

If you liked my support / work - I would enjoy a coffee sponsored using the “:purple_heart:Sponsor Button”.

There are many ways to help this project :pray:

**Comment by tsuz** [comment]
A passer-by here. I ran into this issue and the stack trace told me I was calling initializing more than once...hope that helps
