### ISSUE TITLE
Warning if not using BackendConnector

### ISSUE THREAD

**Issue by DavidCasillasRivero** [i18next/react-i18next#998]
Using react-i18next v10 gives a warning if loading all translations via `addResourceBundle` on init and not using a backend connector. 

    i18next::backendConnector: No backend was added via i18next.use. Will not load resources.

This is the code used to init and load the translations.

    import i18next from 'i18next';
    import LanguageDetector from 'i18next-browser-languagedetector';
    import { initReactI18next } from "react-i18next";

    i18next
     .use(LanguageDetector)
     .use(initReactI18next)
     .init({
       fallbackLng: 'en',
       ns: ['translation', 'thermography'],
      });

    i18next.addResourceBundle('en', 'translation', myTranslationEn);
    ...
    ...
    ...

The warning points to [i18next.js](https://github.com/i18next/i18next/blob/master/src/i18next.js) which in turn points to an old issue in i18next repo. [https://github.com/i18next/i18next/issues/879](https://github.com/i18next/i18next/issues/879), but I could not get any help from there. Setting the flag `initImmediate: false`  did not resolve the issue.

** Versions used **

    "i18next": "^17.0.13",
    "i18next-browser-languagedetector": "^3.0.3",
    "react-i18next": "^10.12.2",
    "react": "^16.9.0",

**Comment by jamuhl** [comment]
If not using a backend...at least pass in resouces at init (even if empty) to avoid initial load call.

```js
i18next
 .use(LanguageDetector)
 .use(initReactI18next)
 .init({
   fallbackLng: 'en',
   ns: ['translation', 'thermography'],
    resources: {}
  });
```

**Comment by DavidCasillasRivero** [comment]
Perfect, that prevents the warning. Thanks for the ultra fast response. You can close the issue although a note on the docs about how to not use a backend connector could be fine. Anyway maybe it is not a frequent use case mixing no backend with no resources preloaded on init config object.

**Comment by jamuhl** [comment]
Just improved the docs a little to mention passing in the empty resources: https://www.i18next.com/how-to/add-or-load-translations#add-after-init

If you like this module don’t forget to star this repo. Make a tweet, share the word or have a look at our https://locize.com to support the devs of this project.

If you liked my support / work - I would enjoy a coffee sponsored using the “:purple_heart:Sponsor Button”.

There are many ways to help this project :pray:
